### ISSUE TITLE
meteor test runs on more files than specified in the guide

### ISSUE THREAD

**Issue by jamesmillerburgess** [meteor/meteor#9332] opened 2017-11-09 13:20 UTC
Meteor v1.6, OS X

#### Expected behavior:

`meteor test` as per the [guide](https://guide.meteor.com/testing.html#test-modes):
> *Does* eagerly load any file in our application (including in `imports/` folders) that look like `*.test[s].*`, or `*.spec[s].*`

My understanding of that statement is that there must be a period before and after the word `test`, `tests`, `spec`, or `specs` in order for the file to be loaded.

#### Actual behavior:

`meteor test` loads files in which `test`, `tests`, `spec`, or `specs` are preceded by a period and which end in `.js` but ignores anything in between.

The following files are eagerly loaded, when I would have expected them to be ignored:

* `index.testt.js`
* `index.testtt.js`
* `index.testttttttttt.js`

Here is a [reproduction](https://github.com/jamesmillerburgess/meteor-extra-tests) with additional test cases.

So either:
1) I misunderstood the guide,
2) the guide should be adjusted, or
3) this is a bug

I'm happy to make a pull request for 2 or 3.

I would prefer a configurable way to grep the files, since I am using jest test files in my project structure as well. Luckily jest can configure this, so I am renaming my jest tests to avoid colliding with `meteor test` for now.

**Comment by axelvaindal** [comment] 2017-11-09 13:59
Hi,

I indeed confirm this behavior which seems not to be `v1.6` specific because I believe to remember it was already the case since at least  `v1.3` (not sure though).
By the way, these file names are also loaded : 

- `index.tests.js` // which is normal
- `index.testssssss.js` // which is not normal

It appears that as long the filename is in this form `test[s]` or `spec[s]`, not matter what follows, the file is loaded. 
Based on the guide (which do use the terms "look like"), it seems to be expected behavior, but I agree with @jamesmillerburgess that the guide should be more precise about this being possible if it is not planned to be changed.
If, however, this is a bug, I would suggest only take *.test[s] or *.spec[s] specifically to make sure there is no further misunderstanding.

By the way, as we are talking about test, looking at the code, I saw a dependency between `meteor test` and `meteor test-packages`  ([here](https://github.com/meteor/meteor/blob/master/tools/cli/commands.js#L1572)).
However, in the second command (i.e `meteor test-packages`) filenames like these are loaded as well : 

- `*-tests.js`
- `*-test..js`

I tried these filenames with `meteor test` and files were not loaded (unless I use the `--full-app` option) so I found it pretty weird.
Considering the link, I had expected these commands to work in the similar manner.
Shouldn't we make them work as such ?

Finally, I logged the help for the `meteor test` command and it seems there is some weird meaning sentence in the helper.
See : 

```
--driver-package  Name of the optional test driver package to use to run
                    tests and display results. For example:
                    --driver-package practicalmeteor:mocha
```

If the driver-package option is mandatory, why is it marked as "optional test driver package" since there is no default one ?
I am not an english native speaker, so this maybe a misunderstanding of my own.

**Comment by hwillson** [comment] 2017-11-09 18:13
This looks like a bug, but it's difficult to say for sure. I mean the regex is doing exactly what you've identified:

https://github.com/meteor/meteor/blob/3690d7a3275546c9d41871d17834a097a116bb50/tools/isobuild/test-files.js#L5-L15

but whether that was intentional or not is lost to history. So, I think we should just make a decision here. Assuming people have been following the Guide's recommendation, I think we should consider this a bug. If you don't mind submitting a PR that fixes the regex @jamesmillerburgess, that would be great!

One small caveat - it's possible that by fixing this we'll be breaking tests for people that were leveraging the existing regex loophole. Given that most people are likely following the Guide though, I think this is an acceptable risk (if anyone disagrees, let me know!). Thanks!

**Comment by axelvaindal** [comment] 2017-11-09 18:51
@hwillson 

Thanks, I was looking for these regular expressions and didn't find them.
Based on the two comments line 6 & 12, I assume this was not intentional and only one "s" was intended as the plural form of both words.
This regex seems to work fine : `\.test(s\b|\b).`

What is your opinion about unifying `meteor test` and `meteor test-packages` in terms of filename syntax ? 
What about the help of the `--driver-package` option ?

Thanks for your answer 🙂

**Closed** 2017-11-22 16:21 UTC
Labels: bug, confirmed, Impact:few, pull-requests-encouraged, Severity:has-workaround
