### ISSUE TITLE
infinite - Downloading missing packages

### ISSUE THREAD

**Issue by p3pp8** [meteor/meteor#9125] opened 2017-09-22 15:02 UTC
Hello, after updating to 1.5.2 anytime i change a single byte to my code, meteor rebuilding gets stuck for a looong time at this line:

   Downloading missing packages              |

Any suggestion is appreciated, it's impossible to work this way...

Cheers!

**Comment by hwillson** [comment] 2017-09-22 16:51
Sorry to hear @p3pp8! A few questions:

- What version of Meteor were you using previously?
- What OS are you using?
- Is your application fairly new or was is created several Meteor versions ago?
- Are you seeing any other details on the console, and if so can you supply them here?
- When you say rebuilding gets stuck for a long time, approximately how long?
- Any chance you could share your application or put together a reproduction that shows this problem?

Any other relevant details you can provide will greatly help with troubleshooting (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Comment by hwillson** [comment] 2017-09-22 16:53
Also, just to add @p3pp8 - does https://github.com/meteor/meteor/issues/9094 sound like the same problem you're seeing?

**Comment by p3pp8** [comment] 2017-09-25 07:06
@hwillson old version was 1.5.1 - OS is MacOS X Sierra - Was created several versions ago(with 1.4 if i remember well), but, i've tried removing .meteor/local folder, clearing cached and resetting project, nothing to do, i suspect it's a 1.5.2 related problem. - No, it hangs on Downloading missing packages console output, this happens after few rebuilds - It hangs approximately 2 minutes - No, it's a private project, i'm not able to release any part of the code, i'm really sorry.
Unfortunally it's something different from referenced threads.... 

Thanx for the support mate!

**Comment by hwillson** [comment] 2017-09-25 13:58
Thanks @p3pp8 - reviewing your comments, I really do think this is a duplicate of https://github.com/meteor/meteor/issues/9094. Your symptoms might not be the exact same, but behind the scenes this issue is more than likely being caused by the same problem. I'll close this issue here - let's continue the discussion in https://github.com/meteor/meteor/issues/9094, since it has more context / participants. Thanks!

**Closed by hwillson** 2017-09-25 13:58 UTC
