### ISSUE TITLE
Unexpected Blaze reactivity when calling 2 helper in one mustache

### ISSUE THREAD

**Issue by nerdmed** [meteor/meteor#4662] opened 2015-07-01 02:38 UTC
Dear MDG Team,

I was searching to death to find the reason for the rerun of a particular helper in my project.
What I expect and whats documented is the following:

```
Under the hood, each helper starts a new Tracker.autorun. 

When its reactive dependencies change, the helper is rerun.
Helpers depend on their data context,
passed arguments and 
other reactive data sources accessed during execution. 
```

I think 'execution' means the execution of the helper function. I checked every data context and every argument till there was nothing left in my functions. Then i noticed that the following expression will cause helper 1 to run when something inside helper 2 changes and vice versa.

```
{{>MyTemplate foo=helper1 bar=helper2}}
```

This breaks the rules defined in the docs and will get very confusing when passing a helper down to multiple child templates and one template down the way has the idea to put it inside a helper with a rerunning reactive variable (e.g. animated svg).

I think this happens because the created data context for the new template gets invalidated on every change for helper2 and it will pull helper1 to be updated. The docs say that helpers have some kind of Tracker.autoruns therefore we could know if the computation is really invalidated and rerun the functions only when needed without having any drawbacks?

I think it should be at least be mentioned in the docs or changed when possible. What do you think?

Here is a sample Project: [https://github.com/nerdmed/blaze-reactivity](https://github.com/nerdmed/blaze-reactivity)
1. Clone 
2. Run
3. Watch the console to see the empty helper rerunning

Would be great to hear from you. If needed i could start to find a solution for this.

**Comment by stubailo** [comment] 2015-07-07 21:27
This is because the whole object passed to `With` is evaluated at once, as one reactive function (even if the helpers have their own autoruns).

You can see the code for this here: https://github.com/meteor/meteor/blob/d634651232f66839b3467152cd046ec6887351b7/packages/spacebars/spacebars-runtime.js#L213-L222

Basically instead of passing `argFunc` we would have to pass an object of `ReactiveVar` or functions, and run them independently.

It might not be easy to convert this to be reactive in the fine-grained way you are looking for, it might be easier to write your helpers in such a way that calling them extra times doesn't incur any extra cost to your app (for example, by caching the return value somewhere to avoid doing expensive computations).

I think it would be good to update the docs to make this more clear. I'd take a look at a docs PR about this, and if there was a really simple solution to the reactivity issue that might be good as well (although I doubt it will be simple).

**Comment by nerdmed** [comment] 2015-07-07 23:00
The question is really how you and your team wants this to work. For me it would really work as expected regarding blaze and spacebars. In terms of overall performance fine grained helpers would also have an impact when the calculation is fast when you start scaling the rate at which data is changed.

I think a solution is possible, but i would have to dig in deeper into Blaze.
Would be great to get a clear direction whether to improve docs and live with it or try to find a solution for this. At least what the preferred solution is.

**Comment by stubailo** [comment] 2015-07-07 23:43
My personal opinion would be to improve docs and live with it for now. It looks like it will be a big change, and as far as I know the rest of Blaze doesn't make that much of an effort to avoid rerunning helpers (running a helper is considered a low-cost operation, I think).

**Comment by nerdmed** [comment] 2015-07-08 01:02
allright then thats what we will do :+1: i will make a suggestion for the docs

**Comment by mitar** [comment] 2015-10-15 01:59
For such things I use [computed-field](https://github.com/peerlibrary/meteor-computed-field) package with which I then scope reactivity changes.

**Comment by nerdmed** [comment] 2015-10-15 10:51
@mitar thanks a lot for your feedback. Honestly i did get the docs for computed field on the first read. But i will give it a try and i am pretty sure it could be very valuable.

**Comment by hwillson** [comment] 2016-12-08 18:52
Closing for now since this functions as designed. Please re-open via the [Blaze repo](https://github.com/meteor/blaze) if necessary. Thanks!

**Closed by hwillson** 2016-12-08 18:52 UTC
Labels: feature, Project:Blaze, Project:Blaze:Spacebars, Project:Docs, pull-requests-encouraged
