### ISSUE TITLE
failed to download meteor installation package on windows os

### ISSUE THREAD

**Issue by hackper** [meteor/meteor#6955] opened 2016-05-02 06:37 UTC
i was connected to internet then i got this error during installation of meteor 1.3 on windows 8.1 64 bit.

![pic1](https://cloud.githubusercontent.com/assets/15670527/14948469/0aad6004-105a-11e6-85c7-366b3a52e058.png)

![pic2](https://cloud.githubusercontent.com/assets/15670527/14948476/1365d848-105a-11e6-97c2-a9c6e2e1aaeb.png)

Log File : 
[Meteor_20160502112145.log.txt](https://github.com/meteor/meteor/files/244600/Meteor_20160502112145.log.txt)

**Comment by mirza444** [comment] 2016-05-02 06:42
I am also facing this issue on windows 10 64 bit.

**Comment by n1mmy** [comment] 2016-05-04 22:24
Hi folks. We believe this might be an issue with specific geographies and our CDN.

Can you see if the issue is fixed for you now? We've rolled back to using an older CDN for now.

Also, I get your IP address for debugging? If you're not comfortable posting it publicly feel free to email me: nick at meteor dot com.

**Comment by abernix** [comment] 2016-05-09 15:15
It's safe to say that this issue is a duplicate of #6960.  Closing this ticket in favor of that one.

@mirza444 & @hackper I'll close this particular issue, but if you haven't already passed your information along to @n1mmy we'd greatly appreciate if you could do that so we can isolate the situation.  Your IP addresses would be most helpful, which you can find at http://checkip.amazonaws.com/.  Just update Issue #6960 or drop him an e-mail with that information.

**Closed by abernix** 2016-05-09 15:15 UTC

**Comment by hackper** [comment] 2016-05-10 11:34
Issue Resolved :)

**Comment by sumeet7** [comment] 2016-05-24 11:00
Hi,

I am still facing the issue. How to tackle the problem. 
Thanks,
Sumeet

**Comment by abernix** [comment] 2016-05-24 11:03
@sumeet7 Please review the other issue #6960 to report and include the information requested for debugging in that issue.

**Comment by abosmond** [comment] 2016-06-29 05:54
I'm also failed to download package. I'm from Indonesia. Using Win 7 64 bit.

**Comment by XizzoR** [comment] 2016-07-07 15:54
Had a same problem as OP but fixed it by running an installation as administrator.

**Comment by vanithaeswara** [comment] 2017-09-26 19:38
same issue on windows7
