### ISSUE TITLE
Meteor 1.3.5.1 update failing on mrt:redis

### ISSUE THREAD

**Issue by RavDanny** [meteor/meteor#7438] opened 2016-07-19 23:56 UTC
I am using Meteor version 1.3 in a Docker container running on Ubuntu 14.04LTS on a Virtualbox VM on a Windows 7 Host.

I am using the following packages:
```
accounts-password         1.1.6* Password support for accounts
accounts-ui               1.1.7* Simple templates to add login widgets to an app
alanning:roles            1.2.15  Authorization package for Meteor
aldeed:autoform           5.8.1  Easily create forms with automatic insert an...
aldeed:collection2        2.9.1  Automatic validation of insert and update op...
cfs:autoform              2.2.1  Upload files as part of autoform submission
cfs:filesystem            0.1.2  Filesystem storage adapter for CollectionFS
cfs:standard-packages     0.5.9  Filesystem for Meteor, collectionFS
cfs:ui                    0.1.3  CollectionFS, provides UI helpers
ecmascript                0.4.1* Compiler plugin that supports ES2015+ in all...
es5-shim                  4.5.8* Shims and polyfills to improve ECMAScript 5 ...
houston:admin             2.0.7  A zero-config Meteor Admin
iron:router               1.0.12* Routing specifically designed for Meteor
jquery                    1.11.6* Manipulate the DOM using CSS selectors
matdutour:popup-confirm   0.1.26  A clean and easy to use confirmation popup
meteorhacks:npm           1.5.0  Use npm modules with your Meteor App
mickaelfm:vermongo        1.1.5  Add versions to your documents. Implementing...
mrt:redis                 0.1.3  Meteor package to wrap redis driver. Include...
npm-container             1.2.0+ Contains all your npm dependencies
okgrow:router-autoscroll  0.1.8  Smart management of scroll position across r...
standard-app-packages     1.0.7* Moved to meteor-platform
standard-minifier-css     1.0.4* Standard css minifier used with Meteor apps ...
standard-minifier-js      1.0.4* Standard javascript minifiers used with Mete...
```
When running ```meteor update``` I get the following error in the console output:

```
/root/.meteor/packages/meteor-tool/.1.3.5_1.6ou8fk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: EXDEV, cross-device link not permitted '/root/.meteor/packages/mrt_redis/.0.1.3.1jxmxmk++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/hiredis'
    at Object.fs.renameSync (fs.js:555:18)
    at Object.wrapper [as rename] (/tools/fs/files.js:1379:35)
    at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:819:11)
    at /tools/isobuild/meteor-npm.js:251:11
    at Array.forEach (native)
    at Object.rebuildIfNonPortable (/tools/isobuild/meteor-npm.js:250:17)
    at /tools/isobuild/bundler.js:409:19
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.3.5_1.6ou8fk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at Function.readDirsFromJSON (/tools/isobuild/bundler.js:408:9)
    at /tools/isobuild/isopack.js:1095:10
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.3.5_1.6ou8fk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:965:7)
    at Isopack._.extend.initFromPath (/tools/isobuild/isopack.js:885:17)
    at /tools/isobuild/isopack-cache.js:286:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/isopack-cache.js:272:24
    at Function.time (/tools/tool-env/profile.js:305:10)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:262:15)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.3.5_1.6ou8fk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:822:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:821:18)
    at /tools/project-context.js:284:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:274:18)
    at /tools/project-context.js:266:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:265:13)
    at /tools/cli/commands-packages.js:1537:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:273:29)
    at maybeUpdateRelease (/tools/cli/commands-packages.js:1536:8)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:1614:29)
    at /tools/cli/main.js:1402:23
```

**Comment by abernix** [comment] 2016-07-20 06:51
Can you describe your setup a bit more?  As the message (kind of) describes, this is due to a link attempting to be made across file systems.  Do you have your Meteor project on one partition/mount and your home (`$HOME`) directory on another?

Similar to #7435

**Comment by benjamn** [comment] 2016-07-20 15:22
Just to be clear, this code is trying to rename a directory like `.../npm/node_modules/hiredis` to `.../npm/node_modules/hiredis-1234`, so that the original `.../npm/node_modules/hiredis` directory can be replaced by `.../npm/node_modules/.temp-5678/hiredis`, and `hiredis-junk5678` can be deleted later. All of this is happening within the `.../npm/node_modules/` directory, so I have trouble believing the renaming is actually happening across drives.

**Comment by abernix** [comment] 2016-07-20 15:36
Bizarre.  Could it be that since this is a docker image with a (_potentially_ – I'm just assuming here) re-mounted partition and that there is an existing broken symlink to a device that is no longer available (or the docker host?) and meteor-npm is trying to rename it to a location on the local device?

**Comment by RavDanny** [comment] 2016-07-20 23:56
Not sure what else to tell you.

When I run ```df -P``` on my meteor project and on my home directory, it
says that they are both "Mounted on /".

**Comment by abernix** [comment] 2016-07-21 07:47
Yes, but what filesystem are they on?  You said you're running a Docker image (unspecified OS) on a Ubuntu VirtualBox on a Windows machine – which FS are the files on?  Are you using Shared Folders to pass them down the chain of virtualization?  I'd like to recreate the setup so I can see the problem myself and determine what the problem is.

Could you make a reproduction in a new Meteor project and provide a Docker image (or at least a `Dockerfile`) that can be tested with?

**Comment by RavDanny** [comment] 2016-07-22 00:59
The Docker image is also running Ubuntu 14.04.
I'm new to Linux and Docker, so you'll have to bear with me.
Regarding the file system: `df -T` within the Docker image returns:
```
Filesystem     Type   1K-blocks      Used Available Use% Mounted on
none           aufs   153706532  21007316 124868280  15% /
tmpfs          tmpfs     830984         0    830984   0% /dev
tmpfs          tmpfs     830984         0    830984   0% /sys/fs/cgroup
/dev/dm-0      ext4   153706532  21007316 124868280  15% /pals
Downloads      vboxsf 228337660 212997432  15340228  94% /mnt/sharing
shm            tmpfs      65536         0     65536   0% /dev/shm
```

My original dockerfile was something like this (see attached), and it was built with a much earlier version of Meteor. When I tried to build it now it gave me new problems.
[test_docker.txt](https://github.com/meteor/meteor/files/377250/test_docker.txt)

Would my best bet would be to update the Dockerfile for the current versions of everything and build it using the new version of meteor?

**Comment by RavDanny** [comment] 2016-07-26 03:02
I now tried `meteor update` to Meteor version 1.4 and got a different error, also associated with mrt:redis (below). It says to include a file with a help request, but there is no such file.

```
=> Errors while initializing project:

While loading package mrt:redis@0.1.3:
error: Command failed:
/root/.meteor/packages/meteor-tool/.1.4.0.5x68bw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
In file included from ../src/hiredis.cc:3:0:
../src/reader.h:11:27: error: expected class-name before '{' token
class Reader : ObjectWrap {
^
../src/reader.h:17:36: error: 'Arguments' does not name a type
static Handle<Value> New(const Arguments&
args);
^
../src/reader.h:17:47: error: ISO C++ forbids declaration of 'args' with no
type [-fpermissive]
static Handle<Value> New(const Arguments&
args);
^
../src/reader.h:18:37: error: 'Arguments' does not name a type
static Handle<Value> Feed(const Arguments
&args);
^
../src/reader.h:18:48: error: ISO C++ forbids declaration of 'args' with no
type [-fpermissive]
static Handle<Value> Feed(const Arguments
&args);
^
../src/reader.h:19:36: error: 'Arguments' does not name a type
static Handle<Value> Get(const Arguments
&args);
^
../src/reader.h:19:47: error: ISO C++ forbids declaration of 'args' with no
type [-fpermissive]
static Handle<Value> Get(const Arguments
&args);
^
In file included from ../src/hiredis.cc:1:0:
/root/.node-gyp/4.4.7/include/node/v8.h: In function 'void
init(v8::Handle<v8::Object>)':
/root/.node-gyp/4.4.7/include/node/v8.h:885:13: error:
'v8::HandleScope::HandleScope()' is protected
V8_INLINE HandleScope() {}
^
../src/hiredis.cc:9:21: error: within this context
HandleScope scope;
^
make: *** [Release/obj.target/hiredis/src/hiredis.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/root/.meteor/packages/meteor-tool/.1.4.0.5x68bw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-35-generic
gyp ERR! command
"/root/.meteor/packages/meteor-tool/.1.4.0.5x68bw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.4.0.5x68bw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/root/.meteor/packages/mrt_redis/.0.1.3.1jxmxmk++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-2shd1c/node_modules/hiredis
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Linux 4.2.0-35-generic
npm ERR! argv
"/root/.meteor/packages/meteor-tool/.1.4.0.5x68bw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.4.0.5x68bw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! hiredis@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hiredis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/root/.meteor/packages/mrt_redis/.0.1.3.1jxmxmk++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-2shd1c/npm-debug.log
In file included from ../src/hiredis.cc:3:0:
../src/reader.h:11:27: error: expected class-name before '{' token
class Reader : ObjectWrap {
^
../src/reader.h:17:36: error: 'Arguments' does not name a type
static Handle<Value> New(const Arguments&
args);
^
../src/reader.h:17:47: error: ISO C++ forbids declaration of 'args' with no
type [-fpermissive]
static Handle<Value> New(const Arguments&
args);
^
../src/reader.h:18:37: error: 'Arguments' does not name a type
static Handle<Value> Feed(const Arguments
&args);
^
../src/reader.h:18:48: error: ISO C++ forbids declaration of 'args' with no
type [-fpermissive]
static Handle<Value> Feed(const Arguments
&args);
^
../src/reader.h:19:36: error: 'Arguments' does not name a type
static Handle<Value> Get(const Arguments
&args);
^
../src/reader.h:19:47: error: ISO C++ forbids declaration of 'args' with no
type [-fpermissive]
static Handle<Value> Get(const Arguments
&args);
^
In file included from ../src/hiredis.cc:1:0:
/root/.node-gyp/4.4.7/include/node/v8.h: In function 'void
init(v8::Handle<v8::Object>)':
/root/.node-gyp/4.4.7/include/node/v8.h:885:13: error:
'v8::HandleScope::HandleScope()' is protected
V8_INLINE HandleScope() {}
^
../src/hiredis.cc:9:21: error: within this context
HandleScope scope;
^
make: *** [Release/obj.target/hiredis/src/hiredis.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/root/.meteor/packages/meteor-tool/.1.4.0.5x68bw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-35-generic
gyp ERR! command
"/root/.meteor/packages/meteor-tool/.1.4.0.5x68bw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.4.0.5x68bw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/root/.meteor/packages/mrt_redis/.0.1.3.1jxmxmk++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-2shd1c/node_modules/hiredis
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Linux 4.2.0-35-generic
npm ERR! argv
"/root/.meteor/packages/meteor-tool/.1.4.0.5x68bw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.4.0.5x68bw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! hiredis@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hiredis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/root/.meteor/packages/mrt_redis/.0.1.3.1jxmxmk++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-2shd1c/npm-debug.log
```

**Comment by abernix** [comment] 2016-07-26 08:21
The most recent error appears to be a compilation error from `redis`.  If the source code has errors or the node-gyp settings (of that package) aren't setup to compile properly, it will certainly fail.

I realize this is subject to personal interpretation and reasoning but generally speaking, you're using very old versions of things.  Just at a glance:

* `mrt:redis` is a package left over from the pre-Atmosphere days and is a NPM wrapper package that [hasn't been updated in over 3 years](https://github.com/stevemanuel/meteor-redis) – just updating this alone could make a huge difference.
* `iron:router` which is no longer actively maintained and is [known to have compatibility issues](https://github.com/iron-meteor/iron-router/issues) with Meteor 1.3 (FlowRouter is preferable)
* Using `meteorhacks:npm` which is no longer necessary (or encouraged) in Meteor 1.3 (Meteor supports NPM natively now using `meteor npm install --save redis`, for example).
* The `Dockerfile` you linked is:
 * Still using `meteorite`, a Meteor package tool that was discontinued as of Meteor 0.9.0.
 * Installing a version of Node (v4) which, up until Meteor 1.4 being released this morning, isn't supported by the version of Meteor you were using (Meteor already comes with Node, too so installing it in your case isn't necessary)
 * Using a Postgres driver that is compiled with one version of Node (v4) and being used by another (0.10)
 * Adding `meteor` packages each time you start your `Dockerfile` which should be included in your Git repository (Meteor handles this for you if you commit it to your code)

I really think you would have more luck updating to more recent versions of packages and using NPM directly or locking into an old version and staying there.  [The very helpful Meteor Guide](http://guide.meteor.com/) has information on making these migrations.  Even simply fixing things I mentioned above and properly version controlling your project _with the packages already added_ your `Dockerfile` would only be about 9 lines and probably much much faster at executing - adding all those packages each time seems slow.

If you still have problems on current infrastructure, I think this issue would be valid one, but as it stands right now you're trying to use very outdated dependencies on a Meteor version that has changed significantly and there's no telling where the issue might be.

**Comment by RavDanny** [comment] 2016-07-27 03:08
@abernix Thanks. That was very helpful.

**Comment by abernix** [comment] 2016-07-27 07:02
Glad it's resolved!  At your leisure, definitely look into some of the other lovely enhancements to the Meteor ecosystem! 😸  

Closing!

**Closed by abernix** 2016-07-27 07:02 UTC
Labels: bug
