### ISSUE TITLE
services.resume.loginTokens array can grow indefinitely, leading to poor performance

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#8084] opened 2016-11-21 21:43 UTC
This occurs in the current release of Meteor (1.4.2.3) and has been the case for a long time. This is an issue with accounts-base.

The services.resume.loginTokens array in the Meteor.users collection, managed by accounts-base, can grow without bounds.  This is easily triggered by any end user logging in repeatedly without logging out.  There is time-based expiration but no way to expire tokens based on there being too many of them.

MongoDB does not perform well with documents with indexed arrays which grow indefinitely, especially when they are updated with `$addToSet`.  `$addToSet` writes oplog entries of the form "$set services.resume.loginTokens to [the entire array]", though it could act like `$push` and just write oplog entries of the form "$set services.resume.loginTokens.999 to the new element" (this is true on MongoDB master today).

We found that a user creating thousands of login tokens was able to induce severe performance problems on our MongoDB.  This was exacerbated by our use of MongoDB 2.6 (which we have since upgraded) which holds locks on the *entire database* for every write, not just a single collection or document. However, even with Mongo 3.0 the performance of an `$addToSet` or `$push` on this loginTokens array is terrible when the array is large: eg, 25 seconds when there are 7000 elements in the array.  (`$push` appears just as bad as `$addToSet` but at least leaves a smaller oplog entry.)  The poor performance is presumably due to the multiple indexes on fields inside the array, which perhaps need to be all re-evaluated even when just one new entry is added.

One answer is that accounts-base should limit the number of outstanding login tokens per user.  There is no `$slice` modifier for `$addToSet` like there is for `$push`, sadly.  A larger change that probably makes sense would be to use a separate collection for login tokens rather than leaving them on the users collection.

**Comment by mitar** [comment] 2016-11-22 07:57
+1 for moving those tokens to a separate collection.

**Comment by alphanso** [comment] 2016-12-01 23:39
If nobody is working on it then I am willing to submit a patch.

**Comment by glasser** [comment] 2016-12-01 23:58
@alphanso I don't know of any particular plan here, so that would be great!

**Comment by abernix** [comment] 2017-01-20 15:43
The solution for this issue should also include a solution for the (similarly implemented) resume token – as discussed in #8163.

@alphanso Were you still interested in making a contribution to Meteor?  It'd be much appreciated!  Let me know if you're encountering any barriers to getting started, or if you decide to work on it. Thanks! :smile:

**Comment by mitar** [comment] 2017-01-20 16:23
I would also ask if at the same time we could start supporting multiple reset tokens: #8273

**Comment by abernix** [comment] 2017-01-20 16:54
I've changed my comment above a bit so as to not change the scope of this issue too much.  I believe that my suggestion and @mitar's should be considered in the _design_ of a schema for a new table/collection, but I'd say unless it happens to be incredibly simple to implement those additional aspects, they shouldn't be considered as a requirements.  I don't want to feature-creep this too much. :)

**Comment by alphanso** [comment] 2017-01-31 13:43
@abernix I can start working on this from this weekend. I will ask for help if I encounter any issue. Thanks :)

**Comment by abernix** [comment] 2017-02-03 09:41
@alphanso That's great news.  Feel free to submit a partial proposal if you're looking for feedback, or just ask questions here.  Definitely try to make sure you have a good plan in mind as the `accounts` packages are a very important part of the Meteor ecosystem.

I think it's very important to imagine and hopefully implement a migration process to maintain backward compatibility.  I guess new tokens could be exclusively placed into the new table, and if they don't exist, then look at the `Meteor.users` table?  Then if the old configuration was found to be in use (for a particular user), that user would be migrated to the new system and the residue from `Meteor.users` would be removed.

Thoughts?

**Comment by alphanso** [comment] 2017-04-02 10:24
@abernix I tried working on it but I am unable to get a starting point. Can you give me some pointers?

**Comment by abernix** [comment] 2017-04-03 07:19
@alphanso Any problems in particular?  Have you tried looking at [`Development.md`](https://github.com/meteor/meteor/blob/devel/Development.md) to get some starting points and tips?

**Comment by alphanso** [comment] 2017-04-12 18:06
New collection will have login tokens so it should not be exposed to client so it should be declared in either accounts_server.js or password_server.js. I believe it should be part of password_server.js as its only dealing with password package. What is correct place for this new collection?

Also, how should it be structured? I am of the opinion that it should be one entry per token instead of current array structure.

**Comment by glasser** [comment] 2017-04-26 05:22
Right, the whole point is to avoid the bad behavior that happens in Mongo with large arrays.

Resume tokens are used for all login methods, so it should be in accounts-base, not accounts-password.  (There are other token types like password reset tokens but this issue is about resume tokens.)

**Comment by stevenhao** [comment] 2017-07-14 01:54
I've been working on this issue with @abernix and here are a few of my thoughts.

- The performance issue occurs on older versions of Mongo running MMAPv1 (on my computer, it was ~5 seconds for a single `$addToSet` on a loginTokens array of size 7000).
- The performance issue does not occur on development apps created using Meteor 1.4 (Meteor 1.4 uses Mongo 3.2, which uses WiredTiger instead of MMAPv1 as its default storage engine)
- There are [a lot of](https://github.com/search?p=1&q=loginTokens%5C.hashedToken+language%3Ajavascript&type=Code&utf8=%E2%9C%93) meteor projects and packages that directly use the `Meteor.users` collection to lookup login tokens

The last bullet point makes it difficult to begin storing tokens in a separate collection, as it would require that we deprecate the `services.resume.loginTokens` list which is used by a lot of developers.

As glasser mentioned in his original post, another option is that we can limit the number of outstanding login tokens per user. In many ways, this is a less disruptive change it seems to be relatively safe to limit it to, say, 100 per user by default. The biggest concern here would be that some developers may actually want to be able to issue hundreds of active login tokens (and perhaps they are on a updated version of Mongo, so performance is not an issue). In that case, we could possibly make the limit an opt-in or configurable feature.

There are probably options other than creating a tokens collection / limiting the number of tokens --
 it'd be great to hear more thoughts around this!

**Comment by glasser** [comment] 2017-07-14 20:28
While there are many projects that use direct access to the collection, they all depend on an undocumented underscored API. It seems like adding that useful API now would be useful even if we don't change the underlying storage immediately.

Can you work out more precisely exactly what fixed the performance issue? You describe "old (no specific version?) MMAPv1" and "3.2 with WiredTiger". Is the change MMAPv1 vs WiredTiger or old vs 3.2? It would be great to have a very specific understanding of what changes resolved this issue.  I did test with some 3.0 version when I originally filed this, though I could have given a clearer optimization.

The problem with doing a limit it isn't very compatible with having some login tokens that need to be "long term" non-expiring (eg as API tokens) though maybe that's not a big deal.  It's also the case that we can't directly enforce the limit in a single $push.

**Comment by stevenhao** [comment] 2017-07-18 23:43
I agree that we should add a public API to expose the loginTokens to the developer -- I think `loginWithToken` is the only public one right now, but it's not hard to extract the token-validation logic out of it.

---

I did not exhaustively try all Mongo setups, and I didn't take super detailed notes on my experiments with reproduction, but here's (to the best of my memory) what I tried and what I found:

On MMAPv1 and meteor's default replication settings, the issue occurs on both Mongo 2.6 and 3.0.12.
On WiredTiger and the default replication settings, the issue does not occur on Mongo 3.2.
On MMAPv1 and no replication settings, the issue does not occur on Mongo 3.0.8.

I can dig deeper to this if necessary, but my conclusion was that the issue occurs on replicated databases on MMAPv1. I'm guessing that this is a common setup for our users, so we should make sure to solve this issue for this setup at the very least.

---

> It's also the case that we can't directly enforce the limit in a single $push.

I believe (according to https://docs.mongodb.com/manual/reference/operator/update/push/#example-push-each) that something like this might work:
```js
this.users.update(query, {
  $push: {
    "services.resume.loginTokens": {
      $each: [hashedToken],
      $sort: {when: -1},
      $slice: maxTokensPerUser,
    }
  }
});
```

**Comment by timbotnik** [comment] 2017-07-21 01:40
I feel like the opt-in hard limit is a good option which at least provides a workaround for this particular issue.  Imposing a reasonable default (like most-recent 100) would be nice, but seems like we cannot be sure that it is going to work for everyone. 

I'm not sure how much sense it makes to have say thousands of tokens attached to a single user, vs. thousands of users, but perhaps that is a valid use-case.

**Comment by mitar** [comment] 2017-07-24 21:58
I hoped that this be resolved in the way that we can have more of tokens, not less (by limiting them). One reason why I would like is to support [multiple reset and invitation tokens](https://github.com/meteor/meteor-feature-requests/issues/121). In my case, this is very problematic because I allow users to invite other users. So if somebody gets multiple invitations, only one works.

So, my issues are:
* if we decide that schema is fixed and cannot be changed, then probably changing one token to multiple will also be hard to do :-(
* if we would have a separate collection for login tokens, then it would be a less of a performance hit anyway

But it seems also that Meteor is moving to MongoDB 3.4, so if performance is not an issue then, maybe we can just leave an array and this is it?

**Comment by glasser** [comment] 2017-07-27 23:46
I would really love a solid answer as to whether the fix is WiredTiger or MongoDB 3.2, since that suggests very different workarounds.  It's not too hard to download and run various versions of mongod — it shouldn't be too hard to get a reproduction recipe up and running and try a whole matrix of versions.

Re `$slice`, I meant to say a single `$addToSet` not `$push`, as `$addToSet` is what Accounts actually uses.  (The reproduction should use it too if it's not just using accounts directly.)

My discomfort with the `$slice` solution is that it's a shame if a misconfigured process that adds tons of login tokens causes other logins to break. That said, it is arguably the case that we shouldn't allow a random user to add an unbounded amount of data to the db, so maybe it's fine (except for the fact that it can't be done with `$addToSet` in a single step).

**Comment by stevenhao** [comment] 2017-07-28 21:59
I ran some more tests, and I think the difference is between MongoDB 3.0 and 3.2.
- On MongoDB **version 3.2.11, it took 80ms** to complete `$addToSet` to a list of length 7000, using mmapv1 as a storage engine
- On MongoDB **version 3.0.12, it took 5000ms**, also mmapv1.

This seems to pretty solidly point to Mongo version as the deciding factor for this issue.
---
**Re: reproduction recipe**

Here is the terminal output of the commands I used.
```
➜  ~ brew services start mongodb@3.0
==> Successfully started `mongodb@3.0` (label: homebrew.mxcl.mongodb@3.0)
➜  ~ mongo
MongoDB shell version v3.4.6
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.0.12
WARNING: shell and server versions do not match
rs0:PRIMARY> use meteor
switched to db meteor
rs0:PRIMARY> load("tokenBenchmark.js")

====================================================================
DB Version: 3.0.12
Storage Engine: {"name":"mmapv1"}
Replication Info: {"logSizeMB":192,"usedMB":41.48,"timeDiff":1294836,"timeDiffHours":359.68,"tFirst":"Thu Jul 13 2017 15:07:21 GMT-0700 (PDT)","tLast":"Fri Jul 28 2017 14:47:57 GMT-0700 (PDT)","now":"Fri Jul 28 2017 14:48:46 GMT-0700 (PDT)"}

Adding 1000 users with 10 tokens each...
Populating services.resume.loginTokens with 7000 tokens...
Calling $addToSet 5 times
Took 5059.2ms on average
Done running benchmark
====================================================================
true
rs0:PRIMARY> ^C
bye
➜  ~ brew services stop mongodb@3.0 && brew services start mongodb@3.2
Stopping `mongodb@3.0`... (might take a while)
==> Successfully stopped `mongodb@3.0` (label: homebrew.mxcl.mongodb@3.0)
==> Successfully started `mongodb@3.2` (label: homebrew.mxcl.mongodb@3.2)
➜  ~ mongo
MongoDB shell version v3.4.6
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.2.11
WARNING: shell and server versions do not match
rs0:PRIMARY> use meteor
switched to db meteor
rs0:PRIMARY> load("tokenBenchmark.js")

====================================================================
DB Version: 3.2.11
Storage Engine: {"name":"mmapv1","supportsCommittedReads":false,"persistent":true}
Replication Info: {"logSizeMB":192,"usedMB":46,"timeDiff":1294915,"timeDiffHours":359.7,"tFirst":"Thu Jul 13 2017 15:07:21 GMT-0700 (PDT)","tLast":"Fri Jul 28 2017 14:49:16 GMT-0700 (PDT)","now":"Fri Jul 28 2017 14:50:31 GMT-0700 (PDT)"}

Adding 1000 users with 10 tokens each...
Populating services.resume.loginTokens with 7000 tokens...
Calling $addToSet 5 times
Took 81.8ms on average
Done running benchmark
====================================================================
true
rs0:PRIMARY>
```

If you want to reproduce these results, here are the relevant files:
* The benchmark script: [`tokenBenchmark.js`](https://gist.github.com/stevenhao/6d73ded92ee0f2fa2a252274500519e8)
* The replicaSet configuration: [`mongod.conf`](https://gist.github.com/stevenhao/f206e1743dfa31c46f1b716a2a9a6fe4)

To set up the meteor.users collection and its indices,
* Start a `mongod`that uses mmapv1
* From a meteor project with the `accounts-password` package, run `MONGO_URL=mongodb://localhost:27017/meteor meteor`

**Comment by glasser** [comment] 2017-07-28 22:28
Thanks, that's really helpful!

**Comment by mitar** [comment] 2018-02-27 19:23
So what is conclusion here? That this is not a problem anymore with new MongoDB? Can this be closed?

**Comment by hwillson** [comment] 2018-03-05 15:43
Seems like it @mitar - closing for now (but if anyone feels differently, let us know and we'll re-open). Thanks!

**Closed by hwillson** 2018-03-05 15:43 UTC
Labels: Project:Accounts (in user apps), Project:Server Performance, pull-requests-encouraged

**Comment by zhaoyao91** [comment] 2019-09-22 04:37
so what is the solution for this problem? just let it go and allowing loginTokens grow infinitely?

**Comment by mitar** [comment] 2019-09-22 06:12
That there is no poor performance, but you can clean them yourself with a periodic job or something, given any strategy you prefer.

**Comment by zhaoyao91** [comment] 2019-09-22 06:16
@mitar if user does not call `logoutOtherClients`, will the expired tokens stay here forever?

**Comment by mitar** [comment] 2019-09-22 06:19
Again, this is what you should be cleaning with a background job. It is not what user should be doing.

**Comment by paulincai** [comment] 2019-09-22 06:22
@zhaoyao91 You may want to take a look at this:
https://github.com/meteor/meteor/issues/891#issuecomment-407093854

**Comment by zhaoyao91** [comment] 2019-09-22 06:26
@paulincai wow, exactly what I am curious about. Thanks.
