### ISSUE TITLE
Upgrading from 1.6 -> 1.7: Mongo 'Password contains an illegal unescaped character'

### ISSUE THREAD

**Issue by tonymckendry** [meteor/meteor#10011] opened 2018-06-19 15:15 UTC
Similar to #9996 which was closed - saw that others were reporting this issue as well and wanted to get this solved as we are currently unable to upgrade any of our projects. 

When upgrading from 1.6 to 1.7 we receive the following error when deployed to a production server (Galaxy in this case):

Ive attempted to re-encode all of our passwords, and even went so far as to wipe all of our users out of our db and deploy a fresh version of the app to a new server (just to see if I could get the server to start) - no dice. I am still getting the following error even when I have zero users in my database: 

```
/app/bundle/programs/server/node_modules/fibers/future.js:280
	throw(ex);
	^

Error: Password contains an illegal unescaped character
 at parseConnectionString (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:297:13)
 at parseHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:129:14)
 at module.exports (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:25:12)
 at connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:878:3)
 at connectOp (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:268:3)
 at executeOperation (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:420:24)
 at MongoClient.connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:259:10)
 at Function.MongoClient.connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:480:22)
 at new MongoConnection (packages/mongo/mongo_driver.js:169:11)
 at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
 at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
 at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
 at new Collection (packages/mongo/collection.js:97:40)
 at new AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
 at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
 at server_main.js (packages/accounts-base/server_main.js:9:12)
```

**Comment by hkstsony** [comment] 2018-06-21 18:11
I'm having the same issue

**Comment by fancyfootwork** [comment] 2018-06-22 19:17
I am also having this issue. I had no problems with 1.6, but this is happening after upgrading to 1.7 during remote deployment.

**Comment by glasser** [comment] 2018-06-22 20:14
This is about how you put your MongoDB password into MONGO_URL and/or MONGO_OPLOG_URL, not anything related to users of your apps. It sounds like the newer mongo client is stricter about encoding characters in password URLs. You'll want to convert interesting characters to their %-encoded alternative; a simple way to do that is to run it through the browser encodeURIComponent function.

**Comment by glasser** [comment] 2018-06-22 20:15
Closing as duplicate of #9996. Note that this isn't really a Meteor change — it's a change in the node mongo driver.

**Closed by glasser** 2018-06-22 20:15 UTC

**Comment by tonymckendry** [comment] 2018-06-22 21:12
@glasser totally makes sense, i'll give that a shot! Thanks!

**Comment by fancyfootwork** [comment] 2018-06-22 22:00
That fixed it for me! thanks @glasser!

**Comment by hkstsony** [comment] 2018-06-22 22:35
Thank you @glasser!!
