### ISSUE TITLE
Need a way to access the DOM before a template is destroyed

### ISSUE THREAD

**Issue by avital** [meteor/meteor#2141] opened 2014-05-12 17:33 UTC
**_4 Upvotes**_ The main use-case is a jQuery plugin that's initialized in the `rendered` callback. You can't clear it in the `destroyed` callback since the DOM is no longer available then. We should either make it available, or add a new `beforeDestroyed` callback.

An example of a particular use-case is discussed here: https://groups.google.com/forum/#!topic/meteor-talk/XJCzctKR-_Q

**Comment by otroboe** [comment] 2015-06-19 18:57
Old issue, but is there finally a way to access the template's DOM before it's removed ?

**Comment by steph643** [comment] 2015-06-19 19:34
See https://github.com/meteor/meteor/issues/3050#issuecomment-66213614

**Comment by zimme** [comment] 2015-06-19 19:42
```js
.onDestroyed(function() {
  this.$('#someElement').someJqueryPluginUnregisterFunction();
});
```

**Comment by otroboe** [comment] 2015-06-19 20:21
I don't know if my problem is coming from Autoform or Blaze, but I've got this :

```
// Form is found
Template.autoForm.onRendered(function () {
    console.log(this.$('form'));
});

// Form is not found
Template.autoForm.onDestroyed(function () {
    console.log(this.$('form'));
});
```

**Comment by KrishnaPG** [comment] 2015-09-17 15:17
Same problem here. Below is the behavior of  template created with UI.Dynamic in `onRendered` and `onDestroyed` methods. The nodes are all cleared out by the time Destroyed is reached.

![image](https://cloud.githubusercontent.com/assets/4610831/9937154/2bc0c352-5d7d-11e5-9afc-ed3bad7329fd.png)
The first `this` output is from `onRendered`

**Comment by steph643** [comment] 2015-09-17 16:03
I've never had this problem. You should create a repo so that MDG can have a look.

**Comment by frozeman** [comment] 2015-09-17 18:16
You should be aware, that the objects you log in the console can be mutated, even after you logged them.

**Comment by steph643** [comment] 2015-09-17 18:41
@frozeman is right. To be sure about your log, clone the object before logging it.

**Comment by rclai** [comment] 2015-09-17 19:32
Why hasn't this been addressed yet? Are there blockers?

**Comment by KrishnaPG** [comment] 2015-09-18 01:40
What you see in the screen shot are not console log outputs. They are manual commands entered at breakpoints. You can see in the screenshot that the control is still active in the destroyed method.

**Comment by mitar** [comment] 2015-10-15 02:35
Blaze Components have [low-level DOM manipulation hooks](https://github.com/peerlibrary/meteor-blaze-components#low-level-dom-manipulation-hooks) which you can hook into and know when particular DOM element is being removed.

Also, from looking at the code, it looks like [onDestroyed callbacks are called before DOM is really removed](https://github.com/meteor/meteor/blob/devel/packages/blaze/view.js#L492)?

Maybe what is needed is simply to use the `Blaze._DOMBackend.Teardown.onElementTeardown` method?

**Comment by zimme** [comment] 2015-10-15 07:29
@mitar: If `_fireCallbacks` is calling the callbacks async, then once these callbacks run there is a high risk that the `destroyMembers` have already run and there is no DOM any more.

What should be done here is setting a reactive var once all `onDestroyed` have run and only then run `destroyMembers` to remove the DOM. or using a promise or whatever.

or am I wrong?

**Comment by mitar** [comment] 2015-10-15 07:33
Hm, internal Blaze callbacks are not called async.

**Comment by zimme** [comment] 2015-10-15 07:39
Never mind, my brain haven't woken up yet.

For some reason I got it into my hed that all functions ran async :sleeping:

**Comment by mitar** [comment] 2015-10-15 07:43
Yes, if you go through JavaScript events/setTimeout. But those callbacks are handled by Blaze directly. And are called in sync. And probably are the best way to assure sync nature (reactivity is not, like your idea of "wait for reactivity to be processed and then remove" is really fragile idea).

So the main question is where exactly to hook into Blaze. So where is that moment which is before destroying DOM. Maybe there is already a callback, or one could be added.

**Comment by zimme** [comment] 2015-10-15 08:55
@mitar Blaze is actually already destroying the view on `onElementTeardown`. https://github.com/meteor/meteor/blob/devel/packages/blaze/view.js#L308

**Comment by mitar** [comment] 2015-10-15 11:05
Yes, it calls `Blaze._destroyView`, and that `Blaze._destroyView` calls `Blaze._fireCallbacks(view, 'destroyed');`? So you should get `onDestroyed` before `view._domrange.destroyMembers` is called?

**Comment by zimme** [comment] 2015-10-15 11:14
Yeah, so this should work now.

But are people having trouble with this? or is it because people can't do async work within the onDestroyed because when the callback runs the DOM might have been destroyed?

This won't work as DOM is destroyed?
```js
.onRenderd(function () {
  doAsyncWork(() => {
    this.$('div').destroyPlugin();
  });
});
```

Would this work?
```js
.onRenderd(function () {
  let $div = this.$('div');
  
  doAsyncWork(() => {
    $div.destroyPlugin();
  });
});
```

**Comment by mitar** [comment] 2015-10-15 11:27
So the example in #4951 was React: https://github.com/meteor/meteor/issues/4951#issuecomment-148282209

We should see what https://react-in-meteor.readthedocs.org/en/latest/react-template-helper/ does.

**Comment by TimHeckel** [comment] 2015-10-20 20:56
They attach `container` to the template instance `onRendered`, then it's unmounted `onDestroyed`:

https://github.com/meteor/react-packages/blob/devel/packages/react-template-helper/react-template-helper.js#L45

**Comment by hwillson** [comment] 2016-11-29 21:07
As @mitar mentioned in https://github.com/meteor/meteor/issues/2141#issuecomment-148260591, `onDestroyed` callbacks are called before the DOM is removed. Taken from [`blaze/view.js#L489-L502`](https://github.com/meteor/blaze/blob/239be86d59cc2e4b6eb297fa4adccb0fc90eecb7/packages/blaze/view.js#L489-L502):

```js
Blaze._destroyView = function (view, _skipNodes) {
  if (view.isDestroyed)
    return;
  view.isDestroyed = true;

  Blaze._fireCallbacks(view, 'destroyed');

  // Destroy views and elements recursively.  If _skipNodes,
  // only recurse up to views, not elements, for the case where
  // the backend (jQuery) is recursing over the elements already.

  if (view._domrange)
    view._domrange.destroyMembers(_skipNodes);
};
```

It really seems as though `onDestroyed` can be used to clean the DOM as needed. That being said, if someone is able to link to a reproduction showing this issue, that would be great. I'll close this for now (and re-open in the [Blaze repo](https://github.com/meteor/blaze) if needed). Thanks!

**Closed by hwillson** 2016-11-29 21:07 UTC
Labels: confirmed, Project:Blaze

**Comment by michcoll** [comment] 2018-06-20 15:32
Hi. 

I reviewed this post while I was researching ways to access a modal with onDestroyed. After some research I ended up using this package - https://github.com/PeppeL-G/bootstrap-3-modal. I hope this is useful for someone down the road who needs to create a call to action or pop-up using meteor onDestroyed.
