### ISSUE TITLE
"Cannot enlarge memory arrays" error while upgrading to meteor from 1.4.2 to 1.4.3.2 in Windows 10

### ISSUE THREAD

**Issue by AngelCastilloB** [meteor/meteor#8078] opened 2016-11-20 13:42 UTC
Hi guys, I am getting the following error while trying to upgrade to meteor 1.4.3.2 from meteor 1.4.2:

- **OS**:    Windows 10 (64-bits).
- **npm**: 1.4.2.
- **node**: v4.4.5

> MINISAT-out: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
> MINISAT-err: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
> 
>
> C:\Users\Angel\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:190
>       throw error;
>       ^
> abort() at Error
>     at jsStackTrace (packages/logic-solver.js:22:18626)
>     at stackTrace (packages/logic-solver.js:22:18809)
>     at abort (packages/logic-solver.js:52:28956)
>     at enlargeMemory (packages/logic-solver.js:22:19142)
>     at Function.Runtime.dynamicAlloc [as alloc] (packages/logic-solver.js:22:7927)
>     at _sbrk (packages/logic-solver.js:22:58803)
>     at Sd (packages/logic-solver.js:26:98389)
>     at Ud (packages/logic-solver.js:26:109800)
>     at qc (packages/logic-solver.js:26:47010)
>     at Nb (packages/logic-solver.js:26:13758)
>     at Kb (packages/logic-solver.js:26:10169)
>     at Dc (packages/logic-solver.js:26:58380)
>     at Object.dd [as _addClause] (packages/logic-solver.js:26:83874)
>     at packages/logic-solver.js:148:14
>     at Object._native.savingStack (packages/logic-solver.js:111:16)
>     at [object Object].MiniSat.addClause (packages/logic-solver.js:142:23)
>     at [object Object].Logic.Solver.solve (packages/logic-solver.js:1671:34)
>     at [object Object].Logic.Solver.solveAssuming (packages/logic-solver.js:1714:21)
>     at minMaxWS (packages/logic-solver.js:1986:31)
>     at [object Object].Logic.Solver.minimizeWeightedSum (packages/logic-solver.js:2087:10)
>     at packages/constraint-solver.js:1326:28
>     at Function.time (C:\tools\tool-env\profile.js:305:10)
>     at [object Object].CS.Solver.minimize (packages/constraint-solver.js:1310:16)
>     at [object Object].CS.Solver.minimize (packages/constraint-solver.js:1304:10)
>     at [object Object].CS.Solver._getAnswer (packages/constraint-solver.js:1697:8)
>     at packages/constraint-solver.js:1561:17
>     at Function.time (C:\tools\tool-env\profile.js:305:10)
>     at [object Object].CS.Solver.getAnswer (packages/constraint-solver.js:1560:23)
>     at packages/constraint-solver.js:2258:25
>     at Object.Logic.disablingAssertions (packages/logic-solver.js:390:12)
>     at Function.CS.PackagesResolver._resolveWithInput (packages/constraint-solver.js:2257:16)
>     at [object Object].CS.PackagesResolver.resolve (packages/constraint-solver.js:2221:34)
>     at C:\tools\project-context.js:518:35
>     at Function.time (C:\tools\tool-env\profile.js:305:10)
>     at C:\tools\project-context.js:514:19
>     at C:\tools\utils\buildmessage.js:359:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at C:\tools\project-context.js:486:20
>     at C:\tools\packaging\catalog\catalog.js:100:5
>     at C:\tools\utils\buildmessage.js:271:13
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:264:29
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:262:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:253:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.capture (C:\tools\utils\buildmessage.js:252:19)
>     at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
>     at ProjectContext._resolveConstraints (C:\tools\project-context.js:485:13)
>     at C:\tools\project-context.js:268:9
>     at C:\tools\utils\buildmessage.js:359:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at ProjectContext._completeStagesThrough (C:\tools\project-context.js:258:18)
>     at C:\tools\project-context.js:250:12
>     at Function.run (C:\tools\tool-env\profile.js:490:12)
>     at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:249:13)
>     at C:\tools\cli\commands-packages.js:1513:20
>     at C:\tools\utils\buildmessage.js:271:13
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:264:29
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:262:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:253:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.capture (C:\tools\utils\buildmessage.js:252:19)
>     at Object.main.captureAndExit (C:\tools\cli\main.js:273:29)
>     at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1512:8)
>     at Command.func (C:\tools\cli\commands-packages.js:1586:29)
>     at C:\tools\cli\main.js:1483:23
> If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by abernix** [comment] 2016-11-21 10:13
Duplicate of #7533.  There is not currently a solution, but it is believed that it is related to large package trees with extremely complex dependencies.  I would suggest doing a reinstall using the Windows installer:

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7/Win8.1:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.  If you are unable to delete it due to long file-paths, please try using the [7-zip File Explorer](http://www.7-zip.org/) application to do it instead.
* **Restart**
* Install fresh 1.4.2.3 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

But ultimately, this discussion is better to have in the other issue.  So closing in favour of #7533.

**Closed** 2016-11-21 10:13 UTC
