### ISSUE TITLE
meteor shell somehow injects `path` into the global namespace on the server

### ISSUE THREAD

**Issue by jonmc12** [meteor/meteor#5415] opened 2015-10-12 23:16 UTC
I've attempted to show a reproduction of the underlying cause of this issue [in a fork of the todos example](https://github.com/jonmc12/todos-path).

```
git clone https://github.com/jonmc12/todos-path.git
cd todos-path
meteor
```

from client:  `Meteor.call('testPath')` will trigger the error:

```
Exception while invoking method 'testPath' ReferenceError: path is not defined
   at [object Object].Meteor.methods.testPath (server/bootstrap.js:55:1)
   at maybeAuditArgumentChecks (livedata_server.js:1692:12)
   at livedata_server.js:708:19
   at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
   at livedata_server.js:706:40
   at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
   at livedata_server.js:704:46
   at tryCallTwo (/Users/jonmc12/.meteor/packages/promise/.0.5.0.h2jsml++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
   at doResolve (/Users/jonmc12/.meteor/packages/promise/.0.5.0.h2jsml++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
   at new Promise (/Users/jonmc12/.meteor/packages/promise/.0.5.0.h2jsml++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
```

Next,  open `meteor shell` and from the shell `Meteor.call('testPath')` - you will see this works.  It seems strange to me that the method works differently on the client than the server.

Now, go back into your browser and issue `Meteor.call('testPath')`.  This command will no longer trigger an error.
## Additional background

In my own code repo, there seems to be a set of package dependencies that was exacerbating this issue in a way that the error appears intermittently and non-deterministically.  Some of the things I observed that would cause the error to come and go:
1.  Changed `api.use('check')` to `api.use('check', 'client')` in package.js in angular-meteor
2.  Change version of `check` in versions.json in angular-meteor
3.  `meteor add check` and `meteor remove check`
4.  Reseting server via `meteor run ios-device`
5.  Waiting several hours (I should note I have a few cron jobs running)
6.  `meteor add ongoworks:google-spreadsheets` and `meteor remove ongoworks:google-spreadsheets` - note: this package uses `Npm.require('path');` and also the `check` method
7.  `meteor remove angular` and `meteor add angular`

At this point, I've changed the code in my repo to work around this error.

**Comment by stubailo** [comment] 2015-10-13 20:39
So clearly, that code _should_ be throwing an error - `path` is not supposed to be something available to all Meteor server code unless you explicitly request it with something like `Npm.require('path')`. It looks like somehow Meteor shell is injecting that into the server environment, because as you pointed out the code throws an error only until you make the call in Meteor shell.

@benjamn, can you think of how this would happen?

**Comment by jonmc12** [comment] 2015-10-14 15:43
@stubailo I tried to allude in 'Additional Background' that I've seen ```path``` injected into the global name space in several circumstances, not just when it is used from a method call in meteor shell.  However, the meteor shell case is the only case I'm able to reproduce consistently.

Additionally, when you say ```path``` is not intended to be available to all Meteor server code - is there a reference for the methods that are available / not available on the server?  The Meteor Docs don't seem to cover many of the utility methods I see available in the shell.  For instance, to get the path of a PEM file in my private folder, I've switched to use ```process``` vs ```path``` in my server method.  I'm not certain if the ```process``` method is intended to be used like that.  Perhaps I'm missing in docs or another resource?

**Comment by stubailo** [comment] 2015-10-14 17:01
@jonmc12 technically, only the ones documented should be available (and probably `process`). I bet almost all of the other ones are there "by accident".

**Comment by abernix** [comment] 2016-05-28 09:03
Confirming that this currently still happens on `release-1.3.3` and `release-1.4` (node 4).

And not saying this isn't a Meteor problem (I'm not certain), but `meteor shell` uses Node's REPL behind the scenes, and it's had some other bugs in it – #7095 being the most recent and kinda-related (though that issue is fixed in Node 4, which is why I thought I'd check this one too).

The same thing happens with other modules too: `assert`, `fs`, etc.  Basically, anything the Node REPL needs to operate, I'm guessing.  Since they become loaded on the server in order to run the REPL, I believe they just stop needing to be required elsewhere in your code since they're already loaded.

**Comment by hwillson** [comment] 2017-11-02 15:48
I've confirmed this is still happening with Meteor 1.6. Here is a simplified repro:

1. `meteor create --bare path-test`
2. `cd path-test`
3. `echo "if (Meteor.isServer) { export default function dumpPath() { console.log(path); }}" > index.js`
4. `meteor`
5. `meteor shell`
6. Run `require('/index').default()` in the shell.

This will then `console.log` the contents of Nodes [`path`](https://nodejs.org/dist/latest-v8.x/docs/api/path.html#path_path) object, even though it hasn't been explicitly required.

**Comment by hwillson** [comment] 2018-01-16 15:58
Fixed by https://github.com/meteor/meteor/pull/9406.

**Closed by hwillson** 2018-01-16 15:58 UTC
Labels: Impact:few, Project:Tool:Shell, Severity:has-workaround, bug, confirmed
