### ISSUE TITLE
"unexpected eof" from fstream decorate error

### ISSUE THREAD

**Issue by digz6666** [meteor/meteor#7766] opened 2016-09-10 05:58 UTC
Cannot run meteor 1.2.1 app on freshly installed 1.4.1_1 meteor tool, throws following issue:

```
"C:\Program Files (x86)\JetBrains\WebStorm 10.0.4\bin\runnerw.exe" C:\Users\digz\AppData\Local\.meteor\meteor.bat --settings settings.json
C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
    at Extract.Abstract.error (C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)
    at Extract._streamEnd (C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\extract.js:91:35)
    at BlockStream.<anonymous> (C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:203:10)
    at BlockStream.resume (C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:58:15)
    at Extract.Reader.resume (C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\reader.js:242:34)
    at Entry.<anonymous> (C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:261:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at Entry.resume (C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:93:8)
    at FileWriter.<anonymous> (C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:147:11)
    at emitNone (events.js:67:13)
    at FileWriter.emit (events.js:166:7)
    at WriteStream.<anonymous> (C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\file-writer.js:45:10)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:205:14
    at C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:232:16
    at C:\Users\digz\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:232:16
    at FSReqWrap.oncomplete (fs.js:82:15)

Process finished with exit code 1

```

OS: Windows 7 32bit on Oracle Virtualbox

**Comment by laosb** [comment] 2016-09-11 21:56
Maybe your app/meteor install is corrupted?

**Comment by digz6666** [comment] 2016-09-12 01:00
@laosb My app is running fine on meteor 1.2.1

**Comment by laosb** [comment] 2016-09-12 22:14
Try creating a new test app and run it with `meteor create` and `meteor` to see whether it was caused by the tool itself or your old version app.

**Comment by kylemclaren** [comment] 2016-09-13 02:00
I have this same issue but with Mac OS X

**Comment by abernix** [comment] 2016-09-20 09:18
There are a couple possibilities here.  If you're experiencing this problem, please try the following steps, in order, and report back your findings:

0. Try creating a new Meteor 1.2.1 app using: `meteor create --release 1.2.1 new-1.2.1-project-name` and see if it works for you.  If it works fine, then it indicates something needs to change with your old project – which makes sense as 1.2.1 to 1.4.1.1 is a big jump.
0. In your _existing_ application, if you're using the `meteorhacks:npm` package, make the migration to direct NPM usage which is supported with Meteor 1.4.1.1.  ([Instructions can be found here](https://github.com/meteorhacks/npm#using-with-meteor-13))
0. In your _existing_ application, remove `node_modules` completely and run `meteor npm install` to rebuild it.  Then see if the project works.
0. Try a `meteor reset` which will wipe away many of the caches and things which could be broken.  Please note that **this will delete your development database**.  To avoid this, you can accomplish a similar reset by removing all directories in your `.meteor/local/` directory **except** for `db`.

If you are still having this problem after these steps, please make a copy of your project that you can share with us but remove the complexities of your application.  Essentially, start ripping out major parts of your application/deleting files until this error message goes away.  Once you have a bare-minimum project with as few files as possible, share it with Meteor Issues by posting it to a GitHub repo and sharing the link.

**Comment by munky444** [comment] 2016-09-20 12:55
Hi, I'm having an similar issue, trying to create a meteor app for v 1.3.5 but when I try and roll back I get a similar issue - I cant get the app to run on the latest version of meteor and it worked perfectly  before

I've used both commands without any success:

meteor update --release 1.3.5
meteor create test --release 1.3.5

```
C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;   ^
Error: unexpected eof
    at decorate (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
    at Extract.Abstract.error (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)
    at Extract._streamEnd (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\extract.js:91:35)
    at BlockStream.<anonymous> (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:203:10)
    at BlockStream.resume (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:58:15)
    at Extract.Reader.resume (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\reader.js:242:34)
    at Entry.<anonymous> (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:261:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at Entry.resume (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:93:8)
    at resume (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:62:16)
    at unblockEntry (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:43:28)
    at Entry.<anonymous> (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:47:9)
    at FileWriter.<anonymous> (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:146:11)
    at emitNone (events.js:67:13)
    at FileWriter.emit (events.js:166:7)
    at WriteStream.<anonymous> (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\file-writer.js:45:10)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:205:14
    at C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:232:16
    at C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:232:16
    at FSReqWrap.oncomplete (fs.js:82:15)
Please, can someone give me some advice, I'm really struggling.
```

I've posed a link to my repo, in case someone can assist, I'm pulling my hair out!

https://github.com/munky444/testapp.git

Thanks,

**Comment by abernix** [comment] 2016-09-20 13:34
@munky444 Your reproduction repo works fine for me on Windows and OS X.  If you are experiencing the exact same error message on that repo, please try the steps I [mentioned above](https://github.com/meteor/meteor/issues/7766#issuecomment-248248608) – specifically steps 4 and 5!

**Comment by munky444** [comment] 2016-09-20 14:00
hi there, bizarre that it works on your side, I can't get my app to launch at all, even after doing all the steps you described above. I'm not getting another error, probably unrelated but still extremely frustrating as this all worked.. really not sure what else I can try. I was hoping that the meteor apps would be compatible on future meteor releases without having to scratch around and redevelop 

```
Error: Bootstrap's JavaScript requires jQuery
W20160920-15:57:16.382(2)? (STDERR)     at meteorInstall.js.bootstrap.js (js/bootstrap.js:8:9)
W20160920-15:57:16.384(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160920-15:57:16.387(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160920-15:57:16.390(2)? (STDERR)     at C:\dev\testapp\.meteor\local\build\programs\server\app\app.js:9180:1
W20160920-15:57:16.393(2)? (STDERR)     at C:\dev\testapp\.meteor\local\build\programs\server\boot.js:292:10
W20160920-15:57:16.395(2)? (STDERR)     at Array.forEach (native)
W20160920-15:57:16.396(2)? (STDERR)     at Function._.each._.forEach (C:\Users\jacqu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160920-15:57:16.399(2)? (STDERR)     at C:\dev\testapp\.meteor\local\build\programs\server\boot.js:128:5
```

**Comment by abernix** [comment] 2016-09-20 14:05
@munky444 What version of Windows are you using?  Can you reproduce on a different computer or OS?  Generally speaking, Meteor tries to be (very) backwards compatible.  As with all software, sometimes changes will be required otherwise forward progress and innovation becomes difficult.  Please make sure all of your dependencies are properly updated as well.  I would try to resolve your other errors as well – but the place for that is on the forums, as you're already doing.

**Comment by munky444** [comment] 2016-09-20 14:28
I'm using windows 10, no access to another os right now. let me post this latest error on the forum as you suggest... thanks man

**Comment by abernix** [comment] 2016-09-30 06:16
I'm almost entirely sure this is due to the Windows tar problems, _similar_ to #7689, and ultimately fixed by d5c83aaf8fe59a09688f0d17a61b6e7f10ee7af2.  This fix has currently surfaced in the beta channel and should be released when 1.4.2 is finally released.  There is no ETA for when this will happen, but I would expect it within a few weeks.

If you're in a position to test the beta, can you try updating to Meteor 1.4.2 beta 6 by running the following in the root of your project:

    meteor update --release 1.4.2-beta.6

Please write back if this resolves your issues so we can resolve this issue and confirm the bug as fixed.

Thanks!

**Comment by Data-Meister** [comment] 2016-10-11 09:07
For me on Windows 10, this problem was caused by having insufficient disk space for temporary files. You might need quite a lot of space - I had 9GB free and it didn't work. But with 30BG free it's working again. 

I guess when you download, unzip, and install the latest meteor package it needs a lot of free space.

**Comment by jkd65** [comment] 2016-10-12 00:56
Getting this same error again... Originally doing what @abernix suggested worked, but this time it is not.

![image](https://cloud.githubusercontent.com/assets/10778294/19293785/14c96d88-8fdc-11e6-885d-dafda54806fc.png)

**Comment by aaroncalderon** [comment] 2016-10-12 14:15
@jkd65 I have seen this issue myself. However, I have 313GB of free disk space on my disk. So, I could not confirm I am experiencing this error for the same issue.

**Comment by digz6666** [comment] 2016-10-12 14:59
@Data-Meister Thanks for you finding. My virtualbox Windows has 7GB of free space, I will increase the partition and test again.

**Comment by JacquesRobin** [comment] 2016-10-12 20:55
I also have the same issue.
Meteor 1.4.1.1 installed.
I receive suggestion to update project because patch is available (1.4.1.2).
I run: meteor update --patch.
I get the dreaded 'unexpected eof' error.
I am on Windows 7 w/ 81GB of free disk space.

**Comment by emoen** [comment] 2016-10-13 14:05
I get the same error. Im on windows 7 - 64 bit, meteor 1.4.1.2 and the command is 
<code>
meteor add static-html react-meteor-data twbs:bootstrap anti:i18n http u2622:persistent-session accounts-password matteodem:server-session cfs:standard-packages cfs:filesystem didstopia:admzip pfafman:filesaver tsega:bootstrap3-datetimepicker ejson kaso:bootstrap-treeview maxharris9:classnames session
</code>

**Comment by hmontes** [comment] 2016-10-13 23:02
Same error with meteor update --release 1.4.2-beta.9

Windows 10 x64 (Aniversary edition)

**Comment by hmontes** [comment] 2016-10-13 23:10
With beta 7. Same error.

**Comment by hmontes** [comment] 2016-10-13 23:11
`D:\code\meteor>meteor update --release 1.4.2-beta.7
C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
    at Extract.Abstract.error (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)
    at Extract._streamEnd (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\extract.js:91:35)
    at BlockStream.<anonymous> (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:203:10)
    at BlockStream.resume (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:58:15)
    at Extract.Reader.resume (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\reader.js:242:34)
    at Entry.<anonymous> (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:261:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at Entry.resume (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:93:8)
    at resume (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:62:16)
    at unblockEntry (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:43:28)
    at Entry.<anonymous> (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:47:9)
    at FileWriter.<anonymous> (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:146:11)
    at emitNone (events.js:67:13)
    at FileWriter.emit (events.js:166:7)
    at WriteStream.<anonymous> (C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\file-writer.js:45:10)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:214:14
    at C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:241:16
    at C:\Users\GaDo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:232:16
    at FSReqWrap.oncomplete (fs.js:82:15)`

**Comment by emoen** [comment] 2016-10-14 06:06
I got this error on a new project:
<code>
meteor create tmp
C:\tmp>meteor add static-html react-meteor-data twbs:bootstrap anti:i18n http u2
622:persistent-session accounts-password matteodem:server-session cfs:standard-p
ackages cfs:filesystem didstopia:admzip pfafman:filesaver tsega:bootstrap3-datet
imepicker ejson kaso:bootstrap-treeview maxharris9:classnames session
C:\Users\johndoe\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows
.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promi
se\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (C:\Users\johndoe\AppData\Local\.meteor\packages\meteor-tool\1.4.
1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:
36)
...
</code>

**Comment by emoen** [comment] 2016-10-14 07:45
git it working again by removing git.

**Comment by abernix** [comment] 2016-10-14 13:03
I've marked this as "confirmed" (because so many people are experiencing it) but, but I still don't have a way to reproduce it and therefore no way to suggest work-arounds (or figure out WHY it's failing!).

That being said, the error itself is definitely coming from the `tar` NPM, which is used to extract packages (and the `meteor-tool` itself).

Can any of you experiencing this problem try installing the [7-zip](http://www.7-zip.org/) tool which provides a `7z.exe` command line tool?  If installed, Meteor will try to use it instead of the `tar` NPM.  Not only should this be faster than using the JS implementation, but it should hopefully provide additional perspective.  You'll need to restart your Command Prompt before trying again (and maybe reboot? not sure.)

Please report back!

**Comment by remcoplasmeyer** [comment] 2016-10-14 15:02
I don't think it's a tar issue. `meteor update` doesn't let 7zip throw an error, which causes NPM tar to be used. 7zip also throws the eof error when I debug it.

However, I did try to download the release manually at https://warehouse.meteor.com/builds/EXSxwGqYjjJKh3WMJ/1476416916613/CXq2c75py8/meteor-tool-1.4.2-beta.11-os.windows.x86_32+web.browser+web.cordova.tgz

When trying to download this through my browser, I eventually end up with a network error.

**Comment by digz6666** [comment] 2016-10-14 15:16
@remcoplasmeyer I got network error too when try to download that using browser.

**Comment by abernix** [comment] 2016-10-14 15:26
@remcoplasmeyer Good find!  Me too.  Wow.  It would seem that MaxCDN definitely having some serious problems right now.

I added a `hosts` entry which points `warehouse.meteor.com` to `54.192.225.217` and it worked fine.

The `tar` NPM (not to be confused with the `tar` command) has been a point of issue in the past, which is why I mentioned it, and more than anything it's just really inefficient.  The CDN definitely doesn't always have such serious problems, but this could definitely be happening sporadically and returning incomplete/corrupted files to `tar` (both the command and the NPM) and `7z` alike.

This could explain a lot of errors including the `os.json` errors.  Will investigate some more.  If anyone is having this problem, try adding:

    54.192.225.217 warehouse.meteor.com

to your `c:\Windows\System32\Drivers\etc\hosts` file,

**Comment by digz6666** [comment] 2016-10-14 15:27
@abernix I've installed 7zip and run meteor command. But it failed during the download of the tool.
![meteor](https://cloud.githubusercontent.com/assets/1736110/19393043/b509cd7a-9265-11e6-8a9a-74d29b5a7905.png)

![meteor2](https://cloud.githubusercontent.com/assets/1736110/19393069/c7ca9dfe-9265-11e6-9efc-a599a68f55af.png)

**Comment by abernix** [comment] 2016-10-14 15:32
@digz6666 Thanks for that.  This confirms it for me.

The network conditions are particularly terrible enough right now (for me too) that this is easily reproducible.

I can reproduce this and the suspicion from #7806 that started a few days ago [discussed in this comment](https://github.com/meteor/meteor/issues/7806#issuecomment-252854647) is happening to me too.

**Comment by digz6666** [comment] 2016-10-14 15:36
@abernix Thanks for workaround. That hosts file change definitely helped. Should I close the issue?

**Comment by abernix** [comment] 2016-10-14 15:39
Let's leave this open for the time-being.  It's definitely a CDN issue at the moment, but there needs to be more resilience in the way this is handled.

**Comment by JacquesRobin** [comment] 2016-10-15 14:40
@abernix 
Adding 
54.192.225.217 warehouse.meteor.com
to my c:\Windows\System32\Drivers\etc\hosts file, 
-- which was empty BTW -- did not change anything.
Extraction of the 1.4.1.1 archive still seems to loops infinitely after meteor reset.

@emoen 
But, with git uninstalled the meteor reset apparently returned and manage to install 1.4.1.1 in the folder of my app which no longer starts with 1.4.1.2 (no clue why). I can now continue to debug it where I left after the attempt to update to 1.4.1.2 (bad idea).
How did you get that idea that git could be interferring? Do you know if there is a choice in the git installation step on Windows that could prevent this interferrence with the meteor-tool archive extraction?
Abernix seems to think this is a CDN problem. How is this related to git?

Newb question here:  is meteor's backward compatibility implemented:
- by downloading the version found in the .meteor/local/release file
- unzipping it
- installing it somewhere on the client in addition to the latest release that was manually installed?

Or am I completely lost? Could someone explain to me how this works, or send me a pointer to a clear description of this?

Thanks a bunch

**Comment by JacquesRobin** [comment] 2016-10-15 14:43
@abernix 
One more thing: those beta releases that you mention are those available for download there: [](https://github.com/meteor/meteor/releases)

Are they only available for OSX and Linux while Windows installers are only provided for official releases?

**Comment by wurlJAM** [comment] 2016-10-15 21:49
i was having the same issue, event after trying `meteor npm install`, what solved my issue was just going to .meteor/local and delete everything and then just `meteor` it worked again really quick so it might be a damaged file thing

**Comment by JonniK** [comment] 2016-10-16 21:51
Got same eror on Windows 10:
`C:\Users\joo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\joo\AppData\Local\Temp\mt-12p38yw\os\packages\jparker_gravatar.js'
    at Error (native)`

any existing packages works, but installation of any new packages is crashing on extracting stage.
Reinstalation of meteor, meteor update --patch, meteor npm rebuild, adding address in hosts file is not helps.

**Comment by aaroncalderon** [comment] 2016-10-17 21:29
@JonniK I worked around that same issue by manually downloading the files and putting them on the `packages` folder.

As explained in meteor documentation [Overriding packages with a local version](https://guide.meteor.com/writing-atmosphere-packages.html#overriding-atmosphere-packages):

> A Meteor app can load Atmosphere packages in one of three ways, and it looks for a matching package name in the following order:
>
Package source code in the `packages/` directory inside your app.

However, the underlying issue persists. The package that is downloaded through meteor cannot be installed successfully.

**Comment by abernix** [comment] 2016-10-18 08:49
_(This is similar to my suggestion for Unix users, [over here](https://github.com/meteor/meteor/issues/7806#issuecomment-254125662))_

As a more temporary (and easier) work-around than my [above suggestion](https://github.com/meteor/meteor/issues/7766#issuecomment-253833824) that doesn't involve changing your `hosts` file, you can also start Meteor with the `METEOR_WAREHOUSE_URLBASE` environment variable set to the old CDN hostname using one of the following methods (depending on your command prompt environment).

### with Command Prompt (`cmd.exe`)
```sh
C:\Users\IEUser\my-app>set METEOR_WAREHOUSE_URLBASE=https://d3fm2vapipm3k9.cloudfront.net

C:\Users\IEUser\my-app>meteor
```
### With PowerShell
```sh
PS C:\Users\IEUser\my-app> $Env:METEOR_WAREHOUSE_URLBASE="https://d3fm2vapipm3k9.cloudfront.net"
PS C:\Users\IEUser\my-app> meteor
```

I'm assuming the most common use-case here would be using it with the `meteor update` command but it will work with any command that you execute after the environment variable is set.  While the possibility still exists for this to fail with the old CDN, I can only reproduce it on the new CDN.  Of course, your experience may vary in different parts of the world.

This might be better as a work-around as it will just be used temporarily, and you won't forget that it's in your `C:\windows\system32\drivers\etc\hosts` file when the problem is eventually resolved.

Solutions to this problem are coming in Meteor 1.4.2, but unfortunately the fix will have to wait until the 1.4.2 release is officially recommended and installed.  This might involve using the above solution when that update does come around.

**Comment by abernix** [comment] 2016-10-28 12:26
Per my comment on [the other issue](https://github.com/meteor/meteor/issues/7806#issuecomment-254125662) and relevant here...

> I reached out to MaxCDN Support over chat and worked with their (actually really fantastic support team, especially considering I'm just an end-user) for almost 45 minutes and they reproduced and corrected an issue on their end. For the first time in the last two weeks, I am able to fully download Meteor without using any work-arounds.

I'm sure the situation is not perfect for everyone, but can anyone who was experiencing this problem consistently confirm that this is fixed? With the change that was made in 1.4.2 (30aec9f) to prevent incomplete downloads (and retry them), I really hope to put this issue to rest.

If you actually cannot upgrade to 1.4.2 for some reason, please consider doing a full reinstall with the Windows 1.4.2 installer [per these instructions](https://github.com/meteor/meteor/issues/7524#issuecomment-236166061).

Would love to close this issue!

**Comment by aaroncalderon** [comment] 2016-10-28 15:13
I was able to upgrade two of my projects to 1.4.2 without issue yesterday.

**Comment by abernix** [comment] 2016-11-18 14:22
Thanks to those tho reported this issue.  Closing as I believe is fixed per the related issues and lack of continued reports.  If you're still seeing this error, please update to the latest Meteor.

If you experience this problem while updating to a new Meteor version, please re-install using the instructions at https://www.meteor.com/install to get the newest networking code.

**Closed by abernix** 2016-11-18 14:22 UTC
Labels: bug, confirmed, Impact:some, Project:Windows

**Comment by umair-khanzada** [comment] 2016-12-23 11:34
Thanks @abernix,
 
Your step 4 works for me `meteor reset`. =D

**Comment by kimochi** [comment] 2017-12-31 18:18
I had the same problem this date, and meteor reset worked for me too, thank's @abernix
