### ISSUE TITLE
Sometimes, <pre> tag inserts a new line before the contents

### ISSUE THREAD

**Issue by avital** [meteor/meteor#2053] opened 2014-04-11 22:48 UTC
Originally reported by @nilnullzip (Juan Pineda) on meteor-talk, but we couldn't find a consistent small reproduction. A reproduction would greatly help fixing this. We'd also look at pull requests implementing this that come with tests (see examples/spacebars-tests for example)

Original report below:

The `<pre>` tag now inserts and extra line vs 0.7.2. To get the same result:

With 0.7.2:
```
<pre>
foo
```

With 0.8.0:
```
<pre>foo
```

**Comment by hwillson** [comment] 2016-10-20 16:14
I've tried several different `<pre />` tag combinations with Meteor 1.4.1.2 (Blaze 2.1.9) and can't seem to re-create this issue. `<pre>Test1 Test 2 Test3</pre>` shows properly with all strings beside each other, whereas

```
<pre>
  Test1
  Test2
  Test3
</pre>
```

shows properly with each string displayed on a newline. It looks like this issue can be closed.

**Comment by abernix** [comment] 2016-10-25 11:31
Thanks, @hwillson.  It does seem to be idle and never had a reproduction (or +1s).  If it comes up again, this can go to [meteor/blaze](https://github.com/meteor/blaze/).

Closing.

**Closed by abernix** 2016-10-25 11:31 UTC
Labels: bug, confirmed, Project:Blaze, pull-requests-encouraged
