### ISSUE TITLE
Improve main-thread performance of client-side DDP 

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6835] opened 2016-04-17 00:32 UTC
Receiving a DDP message with published data sometimes takes up a whole frame, and when there's more than one message in a row, the UI becomes very janky – scrolling is bad, and trying to render something new is worse. Could any of the processing (or even the socket) be moved into a worker?

![image](https://cloud.githubusercontent.com/assets/251288/14584364/8ecac9d0-0411-11e6-9195-d67538802b85.png)

cc @mitar

**Comment by mitar** [comment] 2016-04-17 00:58
Have you tried this after #5680?

**Comment by mitar** [comment] 2016-04-17 01:01
I am not sure if moving to a worker would improve much, hm. Because processing in my opinion does not really do much. I think it is Minimongo which is slow. So updating Minimongo. This is only real processing. Or user's custom `observe` on top of Minimongo changes.

So maybe Minimongo should be moved to workers? Like a real database. :-)

**Comment by lorensr** [comment] 2016-04-17 01:08
Oh, nice. Don't think so – I'm on `1.3.2-rc5`. Looks like it or removing observes wouldn't affect the particular situation pictured – most of the time is spent inside `registerStore.update / insert`, so moving minimongo to a worker might be the best solution.

**Comment by mitar** [comment] 2016-04-17 01:14
I am just saying that observes are chained synchronously. So after store updates Minimongo, if there are observes, they will be called, and if your `added` or whichever callback is bloated, this will slow down everything. I am not saying that in this particular case this is the cause of slowdown. But yes, cutting it at Minimongo would probably be the best. So that registerStore just sends message to Minimongo, and then whenever that is recomputed, `observe`s are called back.

The issue I think is that I am not sure MDG will be investing more in development of Minimongo, they are working on Apollo. @stubailo?

Moving observe callbacks into the worker would be backwards incompatible. So then observes would have to be called on the main thread, but that means that bloated observes would still slow-down things.

Do not forget also that many mobile browsers do not have web workers.

**Comment by hwillson** [comment] 2017-06-12 14:38
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Improve%20main-thread%20performance%20of%20client-side%20DDP%20&body=Migrated%20from:%20meteor/meteor%236835) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-12 14:38 UTC
Labels: confirmed, feature, Impact:some, Project:Minimongo, Severity:production
