### ISSUE TITLE
[1.6.2-beta.3] Meteor can't start Mongo server after switching mongo versions 

### ISSUE THREAD

**Issue by jamesmillerburgess** [meteor/meteor#9591] opened 2018-01-29 10:27 UTC
Switching between 32 and 64-bit versions of MongoDB causes apps to crash when attempting to start MongoDB.

Reproduction steps:
```
meteor --release 1.6.0.1 create --bare .
meteor --release 1.6.0.1                 // kill once the app has started
meteor npm install @babel/runtime
meteor --release 1.6.2-beta.3

[[[[[ ~/projects/mongo-64-bit ]]]]]

=> Started proxy.
Unexpected mongo exit code 62. Restarting.
Unexpected mongo exit code 62. Restarting.
Unexpected mongo exit code 62. Restarting.
Can't start Mongo server.

meteor --release 1.6.0.1                 // it won't work on the original version now either

[[[[[ ~/projects/mongo-64-bit ]]]]]

=> Started proxy.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
Can't start Mongo server.
Unspecified unrecoverable error. Exit was not clean
```

Alternatively:
```
meteor --release 1.6.2-beta.3 create --bare .
meteor --release 1.6.2-beta.3                    // kill once the app has started
meteor --release 1.6.0.1            

[[[[[ ~/projects/mongo-64-bit ]]]]]

=> Started proxy.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.

meteor --release 1.6.2-beta.3                    // but this version still works, unlike the first scenario
```

There is a workaround: `meteor reset`

**Comment by hwillson** [comment] 2018-01-29 18:56
@jamesmillerburgess I wasn't able to reproduce the first part of your repro steps (I was able to create the 1.6.0.1 project and run it using 1.6.2-beta.3 without any errors), but I did get the `Unexpected mongo exit code 14. Restarting.` error when jumping back to 1.6.0.1. 

I'll mark this as `confirmed` but I have a feeling addressing this might not be worth the headache involved (especially if Mongo is updating the database files in way that isn't backwards compatible). In theory the number of people impacted by this should be low, but we'll need to dig into this a bit further. Thanks!

**Comment by KoenLav** [comment] 2018-01-30 22:06
We're also experiencing this issue moving from 1.6.1 to 1.6.2-beta.3 and back.

Meteor reset fixes it, but that's not ideal.

**Comment by hwillson** [comment] 2018-01-31 01:04
Thanks guys - the 1.6.2 beta Mongo 3.6 changes have been reverted until we can track down what's happening (https://github.com/meteor/meteor/commit/85d74f8d2be3b26f29ea51723a2241441bf7aa25).

**Comment by brookback** [comment] 2018-02-08 08:30
I also get this, but not in 1.6.2-beta 👋 

Switched back from a branch with Meteor 1.6.1, to a `master` branch with Meteor 1.4.x. Getting:

```
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.
make: *** [start] Error 254
```

before app crashes.

**Comment by hwillson** [comment] 2018-02-21 14:53
Hi all - just a quick update on this. The database can be repaired by finding the `dev_bundle/mongodb/bin/mongod` binary that lines up with the Meteor version you're jumping back to, and running a Mongo repair. So in the case of the repro (and using MacOS as an example):

```
/Users/jsmith/.meteor/packages/meteor-tool/1.6.0_1/mt-os.osx.x86_64/dev_bundle/mongodb/bin/mongod --dbpath /your/app/.meteor/local/db --repair
```

Not an ideal fix, but this should at least help get anyone who was hit by this back up and running. We're working on a proper fix for this in https://github.com/meteor/meteor/pull/9632. Thanks!

**Comment by benjamn** [comment] 2018-03-21 20:27
@hwillson Can we close this now, since we decided to solve this problem with documentation rather than doing something automatic?

**Comment by hwillson** [comment] 2018-03-22 00:02
Sure thing @benjamn - I was just waiting for https://github.com/meteor/meteor/pull/9632 to be merged (since it includes the documentation). Now that it's in, we're all set here. Thanks!

**Closed by hwillson** 2018-03-22 00:02 UTC
Labels: Impact:few, Project:Tool, Severity:has-workaround, bug, confirmed

**Comment by VikR0001** [comment] 2018-06-05 22:16
I've got this anomaly too. I'll try some of the fixes described here.
