### ISSUE TITLE
[1.4] Switching run --port from initial --port stalls forever

### ISSUE THREAD

**Issue by axelvaindal** [meteor/meteor#7563] opened 2016-08-03 16:45 UTC
Hi,

It seems the `meteor run` command is not working as expected when the `--port` option is specified at least since the latest patch for v1.4.0.1 (or at worst since 1.4.0 release).

Let's start from the beginning.
The command `meteor run` starts a new meteor instance on the port 3000 by default, and a new MongoDB instance on the port 3001 (Meteor Port + 1).
This behavior is working properly, as you can see on this picture I made.

`meteor run`

![meteor_run](https://cloud.githubusercontent.com/assets/11026659/17373301/dae02d10-59a7-11e6-98df-f5c361c79ee9.jpg)

Now, I can also specify the port thanks to the `--port` options.
If I specify the port 3000, as in the default behavior, everything works fine, as you can see in the output.
Also, there is no difference between using `-p` or `--port`.

`meteor run --port 3000` or `meteor run -p 3000`

![meteor_run_3000](https://cloud.githubusercontent.com/assets/11026659/17373376/38d9f3d8-59a8-11e6-84be-227a71d3f090.jpg)
.

However, if I try to launch a new meteor instance on another port than the 3000 one, it seems to not work properly, since it display "Launching your app forever" and never display "MongoDB started." as it should.
For example;

`meteor run --port 3002`

![meteor_run_3002](https://cloud.githubusercontent.com/assets/11026659/17373398/4c87d562-59a8-11e6-8b29-ac86ef23a73d.jpg)

I don't know how it has come to this, since it was working in v1.3.x so I guess it is about either the recent release or patch.
The weirdest part is, that if an instance is running on port 3000, I got a Mongo Error if I try to launch an other instance on another port.

![dual](https://cloud.githubusercontent.com/assets/11026659/17373804/25d43fbc-59aa-11e6-8730-7d2d1af64525.jpg)

This behavior has been found both on Mac and Linux (2 different Ubuntu Server).
This was found in the v1.4.0.1 of Meteor, after the release patch. I don't know if the behavior exists without the patch or even on the 1.3.X release.
Every regular workarounds have been tested : meteor reset, new project with meteor create, export PORT, etc. None seems to fix the issue.

Discussions have been made about it on the Gitter: 
https://gitter.im/meteor/meteor
A forum post has been made, available here: 
https://forums.meteor.com/t/meteor-starts-only-on-port-3000-not-any-other-port/27271/10

My guess is that there has been something changed during the latest release, since it was about the new MongoDB version, and may be (still a guess) the MongoDB instance keeps trying to run on port 3001 when Meteor runs.

In consequence:

- If you try to run your instance for the first time in port XXX (different than 3000), it doesn't work. (Maybe something like if meteor port + 1 different from 3001 it crashes or something).
- If you try to run your second instance in port XXX as the first one runs in port 3000, you got MongoDB Error 100, revealing that the second instance absolutely tries to access the running instance on port 3001, which shouldn't be the expected behavior.

Hope I was pretty clear in this issue, since it is a very strange behavior, and I would like to run two instances of meteor on the same server at the same time, which I cannot at the very moment.

Thanks for reading,
Greetings,
@axelvaindal

**Comment by Dranithix** [comment] 2016-08-03 18:08
Just wanted to comment that running on another port works fine for Windows on Meteor 1.4.0.1.

```
[[[[[ ~\D\Dranithix\Test ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3001/
   Type Control-C twice to stop.
```

**Comment by laosb** [comment] 2016-08-04 00:33
Please provide a reproduction. I can't reproduce it on my Mac with OS X El Capitan.

**Comment by abernix** [comment] 2016-08-04 06:42
Are you trying to run the **same application** twice on _different_ ports?  Or **different applications** twice on _different_ ports?

Based on the screenshots above, you're using the same project directory (`/var/www/test`).  This causes Meteor to try to use the same `/var/www/test/.meteor/local` directory for its own purposes (including the database) and will **not** work.  This has not worked in any previous version of Meteor either.  The only way to run two copies of the _exact_ same project is by specifying a `METEOR_LOCAL_DIR=.meteor/local-2` environment variable which should cause Meteor to write its files (and database) into a different place and allow two versions of the exact same project.  But again, this is not necessary if you are running from different Meteor project folders.

I'm going to copy and paste (approximately) what I wrote on the forums as "things to know".  Remember, by default, meteor uses port 3000 (let's call this `p`):

> * You cannot* run two different Meteor projects on 3000 and 3001 because Meteor uses `p` for itself and `p+1` for the Mongo server it uses.  You should use ports that are further away from each other.  (Personally, I use 3100, 3200, 3300, etc.)
>
>  <sub>* = Unless you use your own Mongo server with `MONGO_URL`, which prevents starting a Mongo server on `PORT+1`</sub>
> * You cannot run two different versions of the same project from the same folder unless you specify a new `MONGO_LOCAL_DIR` environment variable. (i.e. `MONGO_LOCAL_DIR=.meteor/local2 meteor --port 3600`

I'm closing this because based on what was written in the forums, Gitter and here it appears that you're trying to do something that hasn't worked before and based on what I've explained above, wouldn't work.

Happy to re-open if you have further reproduction steps!

**Comment by axelvaindal** [comment] 2016-08-04 08:51
@abernix Not trying to launch the same application twice nor two different applications.
Just trying to launch my application on port 3002 instead of port 3000.
This was a bit confuse in the previous post since I wrote :

> However, if I try to launch a new meteor instance on another port than the 3000 one, it seems to not work properly, since it display "Launching your app" forever and never display "MongoDB started." as it should.

But I can assure I'm not launching the application twice. I killed the process between each step of my demonstration.

I can provide a reproduction repository if needed, but actually that would seem pointless considering I just did a `meteor create` and then launched the application with `meteor run --port 3002`.

Exact Process:

- Connected to an Ubuntu Server 14.04.4 
- Use meteor create test to create a new project
- cd test/
- meteor run (works fine)
- Ctrl + C
- meteor run --port 3002 (don't work)

What bugs me is that some people seems to have the problem, and some others no, which mean it seems to be an environment problem, but can't understand why for now.

**Comment by abernix** [comment] 2016-08-04 10:05
I tried it on both.  The image is trying to show that the `-3` and `-4` examples are 1.3.5.1 – the `-1` and `-2` are Meteor 1.4.0.1.  Sorry it wasn't more clear what 1 and 2 were.

I will try to reproduce this on Ubuntu but I would like to see some information from the Mac users who are experiencing this that you referred to.  I cannot reproduce it.

**Comment by axelvaindal** [comment] 2016-08-04 10:49
Nope, this is my bad, your explanations were pretty clear to begin with ^^.

I will try to get in touch with him, for him to provide feedback, through Gitter private chat.
I will also try this on Windows, to see if it's my end or not, considering @Dranithix didn't have the issue.

Thanks for your concern :).

**Comment by abernix** [comment] 2016-08-04 10:50
I have actually just reproduced this on Ubuntu 14.04 so I'm sure I'm reproducing it the right way.  I cannot reproduce on Windows or OS X though so I'm assuming the OS X issue must be due to one of other conflicts I mentioned earlier.

**Comment by axelvaindal** [comment] 2016-08-04 11:18
Okay, great to know it wasn't only on my side !
Seems Ubuntu related so.

Let me know if there is anything I can do to help this being fixed, I would be happy to do so :).

**Comment by guidouil** [comment] 2016-08-04 12:17
I have the same issue with different meteor projects on my mac. I can start first project on port 3000 without specifying anything, then I can start a second project on port 3002. But without any project launched I can't just start one project on port 3002 (nothing listening on this port). I am on a mac 10.11.6 (15G31) with meteor 1.4.0.1 patched.
Starting directly a meteor like this `meteor run -p 3100` results in a forever spinning `Starting your app` after the `Started proxy` and the verbose start does not give any clue...

**Comment by abernix** [comment] 2016-08-04 12:59
Ok, apologies!  I've recreated on OS X and Ubuntu – not sure about Windows at the moment, but this is enough to work with.

The problem has to do with _switching_ ports after you've already started a project.  Essentially, whatever port you run your project on after you do a `meteor create` or `meteor reset` is the port that it becomes "locked into".

The problem lies with the way that the replicaSet is being initiated on a fresh database.

The hostname is being stored in the replicaSet configuration when it's originally started.  Mongo then believes this hostname is the primary for the replica set.  But the next time you start Mongo, it's trying to maintain the previous Mongo instance as the replica set primary but since it can no longer connect to it in order to try to "keep it in sync", it never gives the thumbs up to Meteor that it's reliable enough to use.  Stalling forever.

#### Easy Reproduction
```sh
 ~/Dev/Misc/meteor-tests $ meteor create --release 1.4.0.1 meteor-issue-7563
... snip text ...
 ~/Dev/Misc/meteor-tests $ cd meteor-issue-7563
 ~/Dev/Misc/meteor-tests/meteor-issue-7563 $ meteor --port 3000
[[[[[ ~/Dev/Misc/meteor-tests/meteor-issue-7563 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
^C
~/Dev/Misc/meteor-tests/meteor-issue-7563 $ # NOTE THE CTRL-C HERE! SAME WINDOW
~/Dev/Misc/meteor-tests/meteor-issue-7563 $ meteor --port 3500
[[[[[ ~/Dev/Misc/meteor-tests/meteor-issue-7563 ]]]]]

=> Started proxy.
   Starting your app                         \|/-\|/-\|/-\|/-
^C
~/Dev/Misc/meteor-tests/meteor-issue-7563 $ # It will spin forever!
```

That's all for now.  Thanks to those reporting this, sorry for the previous misunderstanding and thanks for working through it!

**Comment by abernix** [comment] 2016-08-04 15:17
> But the next time you start Mongo, it's trying to maintain the previous Mongo instance as the replica set primary but since it can no longer connect to it in order to try to "keep it in sync",

Turns out a Meteor solution was already in place for this but it would only work for the `mmapv1` database.  With the use of WiredTiger (the new Mongo engine), Meteor can't just delete the `local` DB since all the collections are in a single set of files to maintain [better data durability](https://docs.mongodb.com/manual/core/wiredtiger/) – it needs to connect and run commands.  I won't be able to look any more tonight, but I'm pretty sure that's waz' up.

**Comment by THPubs** [comment] 2016-08-19 02:19
Any updates on this? Just updated to Meteor 1.4.1 and still have the issue.

**Comment by axelvaindal** [comment] 2016-08-19 10:52
@THPubs No updates for now, this issue wasn't part of the 1.4.1 release (nor probably on 1.4.2 which is also about performance issues).

**Comment by jorisbontje** [comment] 2016-08-23 07:51
As a workaround you can use a local MongoDB rather than starting the Meteor managed one:

```
MONGO_URL=mongodb://localhost:27017/my-app meteor --port 3010
```

**Comment by frenchbread** [comment] 2016-09-20 18:17
You can actually "hack" it for time being.

- Start `meteor` on default port & launch `meteor mongo`
- Switch to `local` db
- Modify the doc in `system.replset` collection. Update `members.0.host` value to fit port you wanna use for meteor app + 1. (Say, if meteor app runs on port 8080, set the host value as `127.0.0.1:8081`)

**Comment by axelvaindal** [comment] 2016-09-21 07:14
@jorisbontje Thanks for your help, but I rather keep the Meteor managed one, I don't wanna have to worry about switching to local MongoDB. It's more a matter of coherence than a real technical problem, considering this wouldn't happen in production. 
If Meteor should run on different port with a local db, it should be working, regardless on db configuration. You shouldn't have to hack it or use a local db instead, as Meteor help us skip this boring part. 
This is why opened the issue in the first place, to help the community fix what I assume is a pain for developers eager to discover meteor in development :).

@frenchbread Thanks for you hack, but as I said I would rather see this being fixed than hacked ^^. By the way, I suppose I have to do this every time I switch port, which isn't really convenient.

Thanks anyway for your response and help keeping this issue alive :).

**Closed** 2016-09-29 20:56 UTC
Labels: bug, confirmed, Impact:some, Severity:blocks-development, Severity:has-workaround

**Comment by abernix** [comment] 2016-09-30 08:18
Thanks to those who reported this!  This will be fixed in a future stable release of Meteor but is available in beta right now (specifically, `1.4.2-beta.7`)

The beta channel isn't always bug free and you may run into unrelated bugs, but if you're in a position to test that this particular feature has been fixed for you, it would certainly be appreciated.  You can find instructions for using the current beta release in #7668.

Please report back if you still have problems with this!

**Comment by axelvaindal** [comment] 2016-09-30 09:25
I just created a copy of my local project to run it on the 1.4.2-beta.7 release and it seems to work fine.

I can now switch port from 3000 to 3002, as expected !

Thanks a lot @abernix and @benjamn for your great work fixing this :).

**Comment by Chugot** [comment] 2016-10-10 18:26
When I start a meteor app on any port besides 3000, the app launches but as soon as I try to connect through my browser I receive:  
ReferenceError: Package is not defined
ReferenceError: meteorInstall is not defined

In the browser console, is this likely the same issue or separate?

**Comment by Chugot** [comment] 2016-10-11 16:05
Yes that is pretty much the crux of it, interestingly enough I can provide --port 3000 or no --port at all and it works, specifying another port results in the ReferenceErrors.  I did try removing the package referenced by the first error, and in that case I receive ReferenceErrors for what appears to be every package meteor tries to load.  Unfortunately I am not sure I can provide a reference of the code as it is internal and also references several other locally developed packages, is there anything I can provide that is well short of a full repo?  I have tested other applications that share some similar dependencies but nothing identical, and they seem to work fine regardless of the supplied port. 

My projects were initially meteor 1.3.2, my local meteor install was as far back as 1.1.x(?) I believe, as I was running into some build issues I updated my meteor install to 1.4.2.  The project I am having the issue with exhibits the behavior at 1.3.2 and 1.4.2.

**Comment by abernix** [comment] 2016-11-08 16:18
@Chugot Please try again with `1.4.2.1-rc.1` and see if this problem is resolved for you.  If you still experience the problem, please open a new issue with a reproduction or as much as a reproduction as you can provide.  Thanks!

This issue itself is resolved.
