### ISSUE TITLE
Support implicit dependencies in Npm.

### ISSUE THREAD

**Issue by ryanfields** [meteor/meteor#4372] opened 2015-05-12 17:51 UTC
Npm's standard module loading hierarchy supports the concept of implicit dependencies, where my module can perform a `require` call for some other module not explicitly declared in my package.json dependencies.  This enables a module developer to depend on something, but let the module consumer at a higher level decide which version of that dependency is supplied.

As an example, say I have a module that extends some feature of React.  Anyone who consumes my module is already going to be using React.  The consumer will have already brought in React as a dependency and will have already "exported" that version into the code.  In a normal npm hierarchy, when my module is added to the project and I perform `require('react')`, npm won't find React in my module's node_modules folder, but it _will_ find React one step up in my project.

As it stands, Meteor breaks up that hierarchy.  In a Meteor package, dependency resolution starts and stops with `.npm/package/node_modules`.  If I've included React at the top level of my app, in `packages.json`, it's invisible to my packages.  If I've exported React via `api.imply`, it doesn't actually make it down to the Npm level where `require` statements need it.

Yes, I _could_ bring in React via Npm.depends.  However, this creates a nasty situation where any number of packages can bring in any number of React versions.  On the server side, it'll be React version chaos.  On the client-side, in contrast, the dependency is ignored and all of these packages will have browser distributions that just fetch React from `window.React`.

Client-side takes advantage of what developers did for years before CommonJS/AMD builders/loaders came along.  Server-side would do roughly the same if it supported the standard Npm hierarchy.

In the long run, I'd rather have isomorphic CommonJS/ES6 support and throw out Meteor's implicit importing entirely.  In the short term, it'd be nice to have some option to let a package search the app's `node_modules` if a `require` dependency isn't met by `.npm/package/node_modules`.

**Comment by glasser** [comment] 2015-05-12 22:11
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

The idea that Npm dependencies are an internal encapsulated property of a Meteor package was by design, but it's definitely open to be rethought.  We are hoping to move more towards ES6 modules in the future, and it's worth considering this as we go.

**Comment by hwillson** [comment] 2016-12-29 20:57
ES2015 module support was introduced in [Meteor 1.3](https://github.com/meteor/meteor/blob/devel/History.md#es2015modules), and the Meteor Guide was updated with a [Peer npm dependencies](https://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies) section, which recommends using the [tmeasday:check-npm-versions](https://atmospherejs.com/tmeasday/check-npm-versions) package to address the rigidity of `Npm.depends`. Given this, I'll close this issue off. Thanks!

**Closed by hwillson** 2016-12-29 20:57 UTC
Labels: feature, Project:Isobuild
