### ISSUE TITLE
Subscription disconnects when loading a lot of data via meteor method

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#7649] opened 2016-08-15 03:38 UTC
Version: METEOR@1.3.4.1

We need to load quite a lot of data on the client (couple 100s of documents with 4-100KB contents).

Unfortunately, we're seeing the subscription is getting stopped a lot (the `onStop` method is called on server) for unknown reason.

We though that maybe using subscription for such a heavy load was not the right way to go, so we decided to use a published cursor just to get the ids of the documents to load and then load them via methods (in batches by 50). However, the subscription still disconnects (seemingly randomly) and takes somewhere between 10-100s to start again.

We're loading data in methods, why would that cause the subscription to stop? Maybe the server doesn't receive a heartbeat from the client? (But we ping it with methods so the server should know we're online.)

BTW, this seems to be a much bigger issue on mobile (cordova app, testing with iPhone 5) than desktop. It almost never happens on desktop.

**Comment by realyze** [comment] 2016-08-15 09:10
Hmm...actually this looks like a connectivity issue. 3G works as expected and doesn't drop the connection. But both WiFis I have access to - in the office and at home - drop connection (and reconnect) a lot.

Maybe a cordova ios wifi issue? Android seems to be OK too (on wifi).

**Comment by laosb** [comment] 2016-08-15 22:01
Maybe related to device performance too, since iPhone 5 was poor in hardware compared to most Android phones.

**Comment by realyze** [comment] 2016-08-15 22:36
@laosb We support offline mode so there actually kinda is. Also, it usually drops when I load one of the first batches so it's not even loading that many documents. I assume loading 100-200KB of data should work for any app.

Is there any setting that could be tweaked to make the websocket connection more resilient to sudden connectivity drops?

**Comment by realyze** [comment] 2016-08-19 06:14
@laosb By the way, I just stumbled upon this: https://news.ycombinator.com/item?id=6513778 And it feels like I'm running exactly into what he's describing

```
 SockJS (transport protocol used by Meteor) does not have rate-limiting built-in. If client connects using one of the polling transports and payload is too large to be received in 30 (? - vanilla SockJS uses 5) seconds, server drops connection thinking that client timed out. Partially, it is SockJS problem and partially it is Meteor problem, as Meteor will just send all outgoing data without caring if client is on slow connection. But because of previous point, generally it is bad idea to send large amount of data anyway.
```

It's actually pretty easy to simulate this: deploy an app to galaxy (or heroku) with a method that returns a random document that has say 500KB, use Network Link Conditioner (if you're on OS X) to simulate "very bad network", call the method a few times from the client and ta-da! The connection drops.

Sadly, the world is full of bad networks, more so if you're on mobile. And what we have now with Meteor is a situation when data doesn't load from the server _and_ the client receives no error so we can't really tell the user. Not great...

**Comment by laosb** [comment] 2016-08-20 06:55
OK, will try to repro a week later (at school now, holidays begin next week) or any can do this?

**Comment by realyze** [comment] 2016-08-20 08:17
Oh, sorry, I thought you were from MDG. :-)

**Comment by laosb** [comment] 2016-08-21 05:52
I'm just a repo collaborator here and I'll try to help out :-)

**Comment by ramezrafla** [comment] 2017-01-14 04:14
Is this still an issue? Will ddp-rate-limiter help in this case?

**Comment by realyze** [comment] 2017-01-15 21:10
We have switched to long-polling meanwhile which doesn't seem to suffer from this. But I would bet  this is still an issue.

**Comment by ramezrafla** [comment] 2017-01-15 23:03
Thanks, are you interested in getting to the bottom of this issue (e.g. ddp raté limiter) or should we close this issue for now?

**Comment by JulianKingman** [comment] 2017-01-19 16:20
I'm interested, I have a similar issue, also with mobile (although using react native instead of cordova, still using and ddp underneath).

**Comment by maxfi** [comment] 2017-07-14 10:39
> We have switched to long-polling meanwhile which doesn't seem to suffer from this. But I would bet this is still an issue.

Are you able to elaborate on this @realyze? Thanks.

**Comment by realyze** [comment] 2017-07-14 13:23
@maxfi We set `DISABLE_WEBSOCKETS=1` on the server which switches to using HTTP long polling (then we have an nginx running in front of the server that gzips the requests). The response times are worse but it's OK.

**Comment by hwillson** [comment] 2017-11-22 21:10
A lot has changed with Meteor since version 1.3.4.1. Please try updating to 1.6 and post back if you're still seeing this happen (ideally with a reproduction if possible). Thanks!

**Closed by hwillson** 2017-11-22 21:10 UTC
Labels: bug, Impact:few
