### ISSUE TITLE
uncaught TypeError : createContainer is not a function

### ISSUE THREAD

**Issue by gurjit03** [meteor/meteor#8318] opened 2017-02-06 06:30 UTC
I am getting **uncaught TypeError : createContainer is not a function** while using createContainer function.

I have added the package **react-meteor-data** and make sure that its imported as well. Following is the code snippet giving me the error.

```
import {Meteor} from 'meteor/meteor'
import { createContainer } from 'meteor/react-meteor-data'
import React,{Component} from 'react'
import { Projects } from '../../api/projects/projects.js'
import {ProjectDisplay} from './ProjectDisplay'

export default ProjectDisplayContainer = createContainer(({ params }) => {
  const subscription = Meteor.subscribe('project-data');
  const loading = !subscription.ready();
  let projects = Projects.find().fetch();

  let filterData = function(searchInput,selectorName) {
    if(searchInput) {
      if(selectorName == 'hours' || selectorName == 'price') {
        projects = Projects.find({ selectorName : { $gt: searchInput } }).fetch();
      }else if(selectorName == 'course' || selectorName == 'classes') {
        console.log(Projects.find({selectorName : searchInput}).fetch());
        projects = Projects.find({selectorName : searchInput}).fetch();
      }else {
        const selector = {};
        selector.name = {
          $regex: new RegExp(`.*${searchInput}.*`, 'i')
        }
        projects = Projects.find(selector).fetch();
      }
    }
  }

  console.log(params,"sdkjfslfjlj")
  console.log(projects);

  return { loading, projects ,filterData};
}, ProjectDisplay);

```

**Comment by gurjit03** [comment] 2017-02-06 06:36
I am getting the above error while using createContainer function.
I have added the package react-meteor-data.
Also imported {createContainer} from 'meteor/react-meteor-data';

**Comment by stubailo** [comment] 2017-02-06 08:20
Can you please:

1. Edit the original comment with your issue information, right now it's just the template
2. Add the information requested, including a specific code snippet of what you tried

**Comment by gurjit03** [comment] 2017-02-06 08:30
@stubailo , edited the information as you have requested.

**Comment by stubailo** [comment] 2017-02-06 09:36
Thanks - at first glance the code looks correct, so I'm not sure what the issue is. What versions of Meteor and the react-meteor-data package are you using?

**Comment by gurjit03** [comment] 2017-02-06 09:38
@stubailo 
Meteor version -- **1.4.2.3**
react-meteor-data@0.1.9

**Comment by gurjit03** [comment] 2017-02-06 10:56
Nit sure how much this will help,  but i even try to use ract-komposer. To my surprise it also returns me TrackerWithComposer is not a function.

**Comment by hwillson** [comment] 2017-02-06 12:52
@gurjit03 there are 2 main issues with your repro:

1. You're using both an npm version of [react-meteor-data](https://www.npmjs.com/package/react-meteor-data) and the Atmosphere based version, at the same time. Remove the npm version for now.

2. You're using an old version of the Atmosphere [react-meteor-data](https://atmospherejs.com/meteor/react-meteor-data) package. Run a `meteor update` within your app, and you'll be updated to 0.2.9.

Since this is an issue with your application and not an issue with Meteor, I'll close this off. For questions like this in the future, please try posting on the [Meteor Forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) first. Thanks!

**Closed by hwillson** 2017-02-06 12:52 UTC
