### ISSUE TITLE
[1.2 RC15] FileReader not working using Android

### ISSUE THREAD

**Issue by miri-am** [meteor/meteor#5202] opened 2015-09-18 09:54 UTC
Reproduction here: https://github.com/miri-am/fileReaderIssue

Works fine on iOS but not on Android:

To reproduce:
1. `meteor run android --mobile-server localhostIP:3000`
2. click button
3. reader.onerror called on Android, reader.onload called on iOS
Also tried using an updated version of cordova-file-plugin: `meteor add cordova:cordova-plugin-file@3.0.0`but problem persists.

**Comment by martijnwalraven** [comment] 2015-09-18 13:37
I can't check this right now, but what is the actual error that gets passed to `onerror`? 

I don't suspect this is something we can solve in Meteor, but it might be caused by the upgraded Cordova and plugin versions.

**Comment by miri-am** [comment] 2015-09-18 14:02
logging the error from `onerror`: 

```
{
    "total": 0,
    "loaded": 0,
    "lengthComputable": false,
    "path": [],
    "cancelBubble": false,
    "returnValue": true,
    "srcElement": {
        "onloadend": null,
        "onabort": null,
        "onprogress": null,
        "onloadstart": null,
        "error": {
            "code": 1,
            "message": "A requested file or directory could not be found at the time an operation was processed.",
            "name": "NotFoundError"
        },
        "result": null,
        "readyState": 2
    },
    "defaultPrevented": false,
    "timeStamp": 1442330540332,
    "cancelable": true,
    "bubbles": false,
    "eventPhase": 2,
    "currentTarget": {
        "onloadend": null,
        "onabort": null,
        "onprogress": null,
        "onloadstart": null,
        "error": {
            "code": 1,
            "message": "A requested file or directory could not be found at the time an operation was processed.",
            "name": "NotFoundError"
        },
        "result": null,
        "readyState": 2
    },
    "target": {
        "onloadend": null,
        "onabort": null,
        "onprogress": null,
        "onloadstart": null,
        "error": {
            "code": 1,
            "message": "A requested file or directory could not be found at the time an operation was processed.",
            "name": "NotFoundError"
        },
        "result": null,
        "readyState": 2
    },
    "type": "error"
}
```

**Comment by stubailo** [comment] 2015-09-21 04:22
@martijnwalraven any new thoughts on this?

**Comment by martijnwalraven** [comment] 2015-09-21 10:13
I have been able to reproduce this, but I don't have a solution. I suspect this is either caused by incorrect usage of the FileReader API or a bug in the Android plugin code. Either way, I do not believe this is a Meteor-specific issue, so I'm going to close this.

**Closed by martijnwalraven** 2015-09-21 10:13 UTC
Labels: Project:Mobile

**Comment by miri-am** [comment] 2015-09-21 11:20
@martijnwalraven. IMHO this should not be closed. For me this represents a big problem, because I am unable to update my apps to v1.2. When you say "incorrect usage", do you have any example of correct usage of FileReader API inside Meteor? It used to work before (if you downgrade Meteor in my reproduction to v1.1.0.3 it works fine) and now I am unable to use important packages such as @aldeed collectionFS in Meteor. Even if this may not be a Meteor-specific issue, it keeps users from using Meteor in the next release.

**Comment by miri-am** [comment] 2015-09-21 12:12
I think that is the issue that causes this: https://issues.apache.org/jira/browse/CB-7273?jql=text%20~%20%22fileError%22

**Comment by martijnwalraven** [comment] 2015-09-21 12:38
Why do you think this issue is related? Maybe I misunderstand, but I don't believe your code even attempts to read a file from the file system?

I understand this issue is a problem for you, but if the behavior has changed between Meteor 1.2 and earlier versions this is really a consequence of updating Cordova and plugin versions. I can't justify spending too much time tracking down app-specific issues, because there is plenty to do on the Meteor side.

I've looked into this some more however, and it turns out the error is thrown from the native Android `FileReader.readAsDataURL` implementation. Not sure what is wrong here, but apparently the `Blob` you're passing is not an acceptable argument.

I don't know what you're trying to accomplish with your code, but `FileReader.readAsDataURL` in `cordova-plugin-file` is defined as taking a `File` and returning a base 64 data URL with the encoded contents. I assume constructing a `Blob` from a base 64 data URL is something you added just to test this behavior, but I'd suggest using a real `File` and seeing if that works.

**Comment by miri-am** [comment] 2015-09-22 08:41
yes my usage of readAsDataURL was confusing. However tried other fileReader functions as well - giving up for now - maybe will give it another try once I have a free mind again...

**Comment by aldeed** [comment] 2015-09-23 16:04
`Blob` and `File` are almost always interchangeable in w3c spec because `File` inherits from `Blob`, but possibly the cordova plugin is not as forgiving. Unfortunately I don't have the time to dive deep into this either.

I think the "bug" here for Meteor is that cordova version and Meteor version should be decoupled. You should not have to necessarily upgrade Cordova in order to get the benefits of a new Meteor version.

**Comment by dnish** [comment] 2015-09-23 19:21
After upgrading to 1.2, all my uploads fails with Android and Cordova. I'm using CollectionFS/GridFS and insert base64 data strings (jpeg) from "cordova-camera-plugin" into my collection. Insert works, but <strong>isUploaded()</strong> returns always false. Also I can't generate an url anymore. On Meteor 1.1 it worked without problems.

**Comment by MoeBadr** [comment] 2015-09-24 14:07
if anyone has a workaround or temporary fix please share, this issue will force me to downgrade  to 1.1 :( as I can't seem to find a solution atm.

**Comment by martijnwalraven** [comment] 2015-09-24 21:26
This took a while to figure out, but it turns out this is a [bug in Cordova Android](https://issues.apache.org/jira/browse/CB-8608?jql=project%20%3D%20CB%20AND%20text%20~%20%22FileReader%22). It should be fixed in a new Cordova release.

Fortunately, there is an easy workaround. Just add this to your `mobile-config.js`:
```
App.accessRule("blob:*");
```

**Comment by dnish** [comment] 2015-09-25 00:06
@martijnwalraven Thanks, you saved my day :) - that works.

**Comment by MoeBadr** [comment] 2015-09-25 08:29
@martijnwalraven Thank you!!! :+1:

**Comment by miri-am** [comment] 2015-09-25 08:33
@martijnwalraven thanks a lot. This was really bugging me!

**Comment by DavidReinberger** [comment] 2015-11-10 10:48
@martijnwalraven THANK YOU!!! I was minutes away from breaking the phone I was testing on :D This should be mentioned somewhere official...

**Comment by sumanla13a** [comment] 2016-03-03 06:52
someone should document this somewhere easily accessible :) 
@martijnwalraven thanks, you saved my day

**Comment by chrise86** [comment] 2016-03-30 16:48
@martijnwalraven I really :heart: you right now, this was driving me insane! Thanks very much!

**Comment by Micjoyce** [comment] 2016-04-08 03:04
@martijnwalraven  Thank very much, you save my day:)
