### ISSUE TITLE
Cordova does not work on iOS simulator when jQuery mobile is used.

### ISSUE THREAD

**Issue by KerimG** [meteor/meteor#3792] opened 2015-02-22 18:14 UTC
Am testing out "meteor run iOS" and "meteor run iOS-device"

Cordova or whatever wrapper-app is being used cannot display this simple jQuery mobile site: 
http://pastebin.com/HzmWvTR9

It works fine when accessed from the host PC's browser as well as the Safari app of the simulator. Unfortunately, I do not have an actual iOS device to test it on there.

When using "meteor run ios-device" Xcode starts up and I can actually see that there are 4 issues during building:

```
(...)/.meteor/local/cordova-build/platforms/ios/tg/Plugins/org.apache.cordova.file/CDVLocalFilesystem.m:438:93: Implicit conversion loses integer precision: 'NSUInteger' (aka 'unsigned long') to 'int'
```

```
(...)/.meteor/local/cordova-build/platforms/ios/tg/Plugins/org.apache.cordova.file-transfer/CDVFileTransfer.m:642:29: Implicit conversion loses integer precision: 'NSInteger' (aka 'long') to 'int'
```

```
(...)/.meteor/local/cordova-build/platforms/ios/tg/Plugins/com.meteor.cordova-update/METEORCordovaURLProtocol.m:51:96: Sending 'METEORCordovaURLProtocol *const __strong' to parameter of incompatible type 'id<NSURLSessionDelegate>'
```

```
(...)/.meteor/local/cordova-build/platforms/ios/CordovaLib/Classes/CDVURLProtocol.m:30:33: 'atomic' attribute on property 'statusCode' does not match the property inherited from 'NSHTTPURLResponse'
```

**Comment by Slava** [comment] 2015-02-22 20:17
Can you please provide a git-clonable reproduction with all Meteor metadata so I can reproduce it? Also provide the exact expected behavior and behavior you observe?

For one, I can see you are linking jquery scripts in head to jquery servers. You should note, that these files will not be loaded to the device app's storage, so you would require the internet connection to load those.

**Comment by shaungs** [comment] 2015-04-02 22:23
Maybe this will help.
1. meteor create --example todos
2. meteor build
3. Open in Xcode
4. Build

results in following error:
===================
/meteor/cordova-build/ios/project/Todos/Plugins/com.meteor.cordova-update/METEORCordovaURLProtocol.m:51:96: warning: sending 'METEORCordovaURLProtocol *const __strong' to parameter of incompatible type 'id<NSURLSessionDelegate>'
  NSURLSession *session = [NSURLSession sessionWithConfiguration:sessionConfiguration delegate:self delegateQueue:nil];

**Comment by Slava** [comment] 2015-04-02 22:27
@shaungs this doesn't look related to the original issue. And you posted a warning from ObjC compiler, which is not an error preventing the build.

**Comment by Slava** [comment] 2015-04-21 21:41
Closing this due to no reproduction.

**Closed by Slava** 2015-04-21 21:41 UTC
Labels: Project:Mobile

**Comment by msavin** [comment] 2015-07-03 06:20
I've experienced a similar error.. this was the only post I could find on it when Googling. Turns out there was a conflict with the app that was generated from 'meteor run ios'. When I removed it from the home screen and  restarted the app in Xcode, it worked fine.

**Comment by boblikesoup** [comment] 2015-07-13 02:28
Hey @msavin I'm experiencing the same bug.  What's the "it" that you refer to that you removed from the home screen?

**Comment by rafaelcorreiapoli** [comment] 2015-12-17 05:42
I'm having the same issue
