### ISSUE TITLE
Does .meteor in home need to keep old packages? Huge list of files in folder

### ISSUE THREAD

**Issue by AndreasGalster** [meteor/meteor#7400] opened 2016-07-13 09:30 UTC
It seems that meteor stores all package versions or meta data in the home directory .meteor folder. I've been trying to delete the folder to recompile some packages and this is what has been going on for almost 45 minutes now!

I really think there should be a limit for how long things get stored there. I mean seriously, that folder must be Gigabytes large and it is already reaching the 1.5 million (!) file mark to delete that folder. Can't we just delete no longer relevant packages in that folder by default so this will not happen if you've been using meteor for a long time?

![screenshot 2016-07-13 17 28 09](https://cloud.githubusercontent.com/assets/3836411/16798554/3a03a9b4-491f-11e6-96da-fb35b9dc8c7f.png)

**Comment by abernix** [comment] 2016-07-13 10:04
Meteor caches a lot of objects in that folder and in addition to that, it can contain a lot of nested node module dependencies.  There isn't a mechanism in place to prune this directory automatically but it doesn't hurt to remove the entire folder and re-run your recent projects which will re-build the still-relevant structures.

(Btw, if you run into problems deleting the folder, you should try using 7zip's file manager to do it as Windows Explorer will often times fail since "file paths are too long")

Closing as related/duplicate of #6580 which begins to address the issue.

**Closed by abernix** 2016-07-13 10:04 UTC

**Comment by hwillson** [comment] 2016-07-13 10:31
Just adding a reference to one more open issue relating to this - #5818 (dealing with the .meteor/local/bundler-cache not being cleared properly).
