### ISSUE TITLE
Default export breaks with upgrade to Meteor 1.5

### ISSUE THREAD

**Issue by yogiben** [meteor/meteor#8797] opened 2017-06-14 08:23 UTC
Could be a [meteor webpack](https://github.com/thereactivestack-legacy/meteor-webpack) issue.

On upgrading to 1.5, it is no longer possible to use `export default` / `import foo from 'meteor/bar'`.

The object returned is
```js
{ default: [Function] }
```

whereas it should be just the function.

Following up in meteor/webpack with this [issue](https://github.com/thereactivestack-legacy/meteor-webpack/issues/291).

Could be related to #8791

**Comment by benjamn** [comment] 2017-06-14 13:25
Just as a sanity check, I've reconfirmed this works in a fresh Meteor 1.5 app. I think your suspicion of `webpack:webpack` interfering somehow is probably accurate. I imagine you know this already, but you really shouldn't be using `webpack:webpack` anymore, as it's no longer actively maintained (and was never supported by MDG), and there's not much we can do to work around its limitations.

**Comment by yogiben** [comment] 2017-06-20 07:10
@benjamn yes, you're right. Do you have a gut feeling why this release might've broken it?

**Comment by SimonSimCity** [comment] 2017-06-27 12:28
Am having the same with the package `meteor-stub-collections` ... https://github.com/hwillson/meteor-stub-collections/issues/17

**Comment by hwillson** [comment] 2017-06-27 13:08
I responded in https://github.com/hwillson/meteor-stub-collections/issues/17#issuecomment-311351863 with a small repro showing things are working properly with Meteor 1.5 and a simple app (that includes the `hwillson:stub-collections` package). As mentioned in https://github.com/meteor/meteor/issues/8797#issuecomment-308430113, it sounds like something outside of Meteor is causing this to happen.

**Comment by SimonSimCity** [comment] 2017-06-27 13:58
I put all my meteor-packages on the project created by your few lines and got the same error, @hwillson. Removing `pbastowski:angular-babel` (which I had on my project) and replacing it by `ecmascript@0.8.0` (which was on the project from the start off) fixed it for the sample, but when I try the same on the project I'm working on, it hangs during `Building for web.browser` ...

@yogiben can you check if you also use `pbastowski:angular-babel`?

**Comment by hwillson** [comment] 2017-09-13 13:04
Closing as this doesn't seem to be a Meteor issue. Happy to re-open if anyone can show otherwise (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Closed by hwillson** 2017-09-13 13:04 UTC

**Comment by danscan** [comment] 2017-10-04 20:00
@hwillson This seems to be an issue with Meteor.

### To reproduce
`defaultExport.js`
```javascript
const defaultExport = true;
console.log('(pre-export) defaultExport:', defaultExport);

export default defaultExport;
```

`index.js`
```javascript
import defaultExport from './defaultExport';
console.log('(imported) defaultExport:', defaultExport);
```

**[Actual behavior]** This will log the following:
```
(imported) defaultExport: { [Symbol(__esModule)]: true, default: true }
(pre-export) defaultExport: true
```

**[Expected behavior]** This _should actually_ log:
```
(imported) defaultExport: true
(pre-export) defaultExport: true
```

**Comment by abernix** [comment] 2017-10-05 07:32
@danscan Could you please open a new issue since this issue is closed and looks to be different than the issue above.  Not critical, but if you could package your reproduction up into a GitHub repository and link to it in the new issue (rather than pasting in code snippets), that would be helpful too! Thanks!

**Comment by johnsunam** [comment] 2020-01-22 09:40
Any progress on above @danscan issue, I too am facing same issue while I import.
