### ISSUE TITLE
Failing conditional imports for 1.4.2.7 and 1.4.3.2

### ISSUE THREAD

**Issue by nerdmed** [meteor/meteor#8546] opened 2017-03-30 20:13 UTC
Dear Team,

after updating to 1.4.2.7 a lot has changed regarding conditional imports.
First of all I needed quite some time to find out that the following breaking change was introduced by a **patch**: 

```js
// works pre Meteor 1.4.2.3
if(Meteor.isCordoa) import 'myFile.js';

// same case fails in Meteor 1.4.2.7 with a totally not readable error
// in 1.4.2.7 it has to be
if(Meteor.isCordoa) {
  import 'myFile.js';
}
```

In addition conditional imports aren't working anymore!
The following code will just fail in Meteor 1.4.2.7

```js
if(true){
 import test from 'test';
}

test();
// Uncaught ReferenceError: test is not defined
```

I expect this to be caused by an external babel dep or something, but i expect that an patch does not introduce such a breaking change to the code base. @benjamn I have tried to install `reify` manually and add it to the babel.rc or something but it just does not work anymore.

Here is an reproduction example: https://github.com/nerdmed/meteor-failing-import

PS.: It also fails on 1.4.3.2 - there is a 1.4.3.2 branch on reproduction example repo

As it was not obvious to get it running on a fresh 1.4.2.7 i have created a working version on the working branch. Here is the diff: https://github.com/nerdmed/meteor-failing-import/pull/1/files

**Comment by abernix** [comment] 2017-03-31 09:28
This speaks about the same issue which was brought up in https://github.com/meteor/meteor/issues/8369.

Conditional imports do work properly in Meteor 1.4.3.2, however they now have correct scoping which behaves the same as a `let` variable would behave inside a conditional.  When using a symbol outside/after a conditional block which was `import`-ed inside a conditional block, you were/are assuming that `import` statements should be hoisted, which was not and is not the intended behavior.

The new behavior is correct and the existing behavior was a bug (which you happened to be taking advantage of).  It was previously un-resolvable prior to changes made during the 1.4.3.x series.  Specifically, [`reify`](https://github.com/benjamn/reify/) (which generates `let` statements) can now run _before_ [`babel`](https://github.com/meteor/babel/) and `babel` can now properly compile the `let` statements which `reify` produced.

With that said, unfortunately, Meteor 1.4.2.x had a free-for-all version-pinning scheme for core packages which did not pin them to the Meteor release.  This allowed updates to the `babel-compiler` / `ecmascript` packages in Meteor 1.4.3 to trickle to users of Meteor 1.4.2.x who had `meteor update`-d.  While it mainly affected users using conditional imports, it was difficult to prevent.  This has been resolved in Meteor 1.4.3.x which now has more explicit version pinning of core packages (while still allowing core packages to be incrementally updated without a full Meteor release).

If you'd like to maintain the existing behavior in Meteor 1.4.2.7, you should be able to pin your `ecmascript` package to explicitly `0.6.1` in your `.meteor/packages` file (`ecmascript@=0.6.1`), though you can easily continue to use your existing behavior in Meteor 1.4.3.x by using `require` and explicitly defining your intentions with an outer-scoped `test` variable:

```js
let test;
if (true) {
 test = require('test');
}
test();
```
or even:
```js
let moduleTest;
if (true) {
  import * as test from 'test';
  moduleTest = test;
}
test();
```

Sorry for the trouble here, but we do believe this is the correct behavior for conditional imports.

**Closed by abernix** 2017-03-31 09:28 UTC

**Comment by nerdmed** [comment] 2017-03-31 12:43
@abernix thx for your explination

**Comment by ephemer** [comment] 2017-04-01 00:22
I can understand the explanation about hoisting and scoped declarations, but is this really intended behaviour?:


```
// works pre Meteor 1.4.2.3
if(Meteor.isCordoa) import 'myFile.js';

// same case fails in Meteor 1.4.2.7 with a totally not readable error
// in 1.4.2.7 it has to be
if(Meteor.isCordoa) {
  import 'myFile.js';
}
```

Playing with JS semantics in this way seems unexpected

**Comment by abernix** [comment] 2017-04-03 10:22
@ephemer Is this the error you're referring to?:

```
   While processing files with ecmascript (for target web.browser):

   /Users/jesse/.meteor/packages/ecmascript/.0.6.3.1xz9o6o++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-generator/lib/printer.js:383:24:
   /client/main.js: Cannot read property 'leadingComments' of undefined
   at Generator.printAndIndentOnComments
... snipped ...

```

?

If so, can you try updating to the latest version of Meteor:

    meteor update --release 1.4.4-rc.5

...and see if you still experience that error?  I can imagine this may have been fixed recently upstream in `reify` by https://github.com/benjamn/reify/commit/ad5c10478b935061258730e36c0b7f00bbd976bf, which is now in the latest 1.4.4 release candidate.  Would be good to know!

**Comment by nerdmed** [comment] 2017-04-09 21:45
@abernix Goddamn the `Meteor 1.4.2.x had a free-for-all version-pinning scheme` is screwing a lot up. Cant update the accounts package that is breaking the facebook login without breaking nearly everything else in my app arrrgh

**Comment by abernix** [comment] 2017-04-10 08:59
@nerdmed Sorry about that!  Though that is exactly why [we back-ported the fix](https://github.com/meteor/meteor/pull/8534) from`accounts-facebook@1.1.1` (Meteor 1.4.3.x+) to the 1.0.x version range (pre-Meteor 1.4.3).

    meteor add accounts-facebook@1.0.12
