### ISSUE TITLE
TypeError in server/boot.js after 1.6.1-beta.7

### ISSUE THREAD

**Issue by keuaemou** [meteor/meteor#9383] opened 2017-11-17 00:35 UTC
The version of Meteor showing the problem: 1.6.1-beta.7
The last version of Meteor where the problem did _not_ occur, if applicable: 1.6
The operating system you're running Meteor on: Linux / Ubuntu 16.04 LTS
The expected behavior: module gets correcly imported, application works
The actual behavior: type error, application crashes

Reproduction:
Emptied ~/.meteor + installed 1.6

meteor --version
Meteor 1.6

meteor create app
cd app
meteor add jalik:ufs
meteor run
```
[[[[[ /tmp/app ]]]]]                          

=> Started proxy.                             
=> Started MongoDB.       
...
...
...
I20171117-01:20:48.670(1)? ufs: temp directory created at "/tmp/ufs"
=> Started your app.

=> App running at: http://localhost:3000/
```

---------------
meteor update --release 1.6.1-beta.7
meteor run
```
[[[[[ /tmp/app ]]]]]                          

=> Started proxy.                             
=> Started MongoDB.                           
W20171117-01:26:53.482(1)? (STDERR) /home/user/.meteor/packages/meteor-tool/.1.6.1-beta.7.j2dbou.7vod++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171117-01:26:53.516(1)? (STDERR) 						throw(ex);
W20171117-01:26:53.517(1)? (STDERR) 						^
W20171117-01:26:53.517(1)? (STDERR) 
W20171117-01:26:53.517(1)? (STDERR) TypeError: Class constructor Collection cannot be invoked without 'new'
W20171117-01:26:53.517(1)? (STDERR)     at new ns.Collection (packages/matb33_collection-hooks.js:275:27)
W20171117-01:26:53.517(1)? (STDERR)     at ufs-tokens.js (packages/jalik:ufs/ufs-tokens.js:32:23)
W20171117-01:26:53.518(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171117-01:26:53.518(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171117-01:26:53.518(1)? (STDERR)     at ufs.js (packages/jalik:ufs/ufs.js:1:438)
W20171117-01:26:53.518(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171117-01:26:53.519(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171117-01:26:53.519(1)? (STDERR)     at /tmp/app/.meteor/local/build/programs/server/packages/jalik_ufs.js:2789:15
W20171117-01:26:53.519(1)? (STDERR)     at /tmp/app/.meteor/local/build/programs/server/packages/jalik_ufs.js:2794:3
W20171117-01:26:53.519(1)? (STDERR)     at infos.forEach.info (/tmp/app/.meteor/local/build/programs/server/boot.js:415:13)
=> Exited with code: 1
W20171117-01:26:55.226(1)? (STDERR) /home/user/.meteor/packages/meteor-tool/.1.6.1-beta.7.j2dbou.7vod++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171117-01:26:55.227(1)? (STDERR) 						throw(ex);
W20171117-01:26:55.227(1)? (STDERR) 						^
W20171117-01:26:55.227(1)? (STDERR) 
W20171117-01:26:55.228(1)? (STDERR) TypeError: Class constructor Collection cannot be invoked without 'new'
W20171117-01:26:55.228(1)? (STDERR)     at new ns.Collection (packages/matb33_collection-hooks.js:275:27)
W20171117-01:26:55.229(1)? (STDERR)     at ufs-tokens.js (packages/jalik:ufs/ufs-tokens.js:32:23)
W20171117-01:26:55.229(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171117-01:26:55.230(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171117-01:26:55.230(1)? (STDERR)     at ufs.js (packages/jalik:ufs/ufs.js:1:438)
W20171117-01:26:55.231(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171117-01:26:55.231(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171117-01:26:55.231(1)? (STDERR)     at /tmp/app/.meteor/local/build/programs/server/packages/jalik_ufs.js:2789:15
W20171117-01:26:55.231(1)? (STDERR)     at /tmp/app/.meteor/local/build/programs/server/packages/jalik_ufs.js:2794:3
W20171117-01:26:55.232(1)? (STDERR)     at infos.forEach.info (/tmp/app/.meteor/local/build/programs/server/boot.js:415:13)
=> Exited with code: 1
W20171117-01:26:56.563(1)? (STDERR) /home/user/.meteor/packages/meteor-tool/.1.6.1-beta.7.j2dbou.7vod++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171117-01:26:56.566(1)? (STDERR) 						throw(ex);
W20171117-01:26:56.566(1)? (STDERR) 						^
W20171117-01:26:56.567(1)? (STDERR) 
W20171117-01:26:56.567(1)? (STDERR) TypeError: Class constructor Collection cannot be invoked without 'new'
W20171117-01:26:56.567(1)? (STDERR)     at new ns.Collection (packages/matb33_collection-hooks.js:275:27)
W20171117-01:26:56.567(1)? (STDERR)     at ufs-tokens.js (packages/jalik:ufs/ufs-tokens.js:32:23)
W20171117-01:26:56.568(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171117-01:26:56.568(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171117-01:26:56.569(1)? (STDERR)     at ufs.js (packages/jalik:ufs/ufs.js:1:438)
W20171117-01:26:56.570(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171117-01:26:56.570(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171117-01:26:56.571(1)? (STDERR)     at /tmp/app/.meteor/local/build/programs/server/packages/jalik_ufs.js:2789:15
W20171117-01:26:56.571(1)? (STDERR)     at /tmp/app/.meteor/local/build/programs/server/packages/jalik_ufs.js:2794:3
W20171117-01:26:56.572(1)? (STDERR)     at infos.forEach.info (/tmp/app/.meteor/local/build/programs/server/boot.js:415:13)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by keuaemou** [comment] 2017-11-18 04:53
Continues with meteor update --release 1.6.1-beta.8

@benjamn @abernix

**Comment by StorytellerCZ** [comment] 2017-11-18 11:23
Similar issue:
```sh
=> Started proxy.                             
=> Started MongoDB.                           
W20171118-12:20:50.554(1)? (STDERR) /home/storyteller/.meteor/packages/meteor-tool/.1.6.1-beta.8.mfd9if.0cw3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171118-12:20:50.576(1)? (STDERR) 						throw(ex);
W20171118-12:20:50.576(1)? (STDERR) 						^
W20171118-12:20:50.576(1)? (STDERR) 
W20171118-12:20:50.577(1)? (STDERR) TypeError: Match.Where is not a constructor
W20171118-12:20:50.577(1)? (STDERR)     at packages/aldeed_simple-schema.js:1547:26
W20171118-12:20:50.577(1)? (STDERR)     at packages/aldeed_simple-schema.js:2160:4
W20171118-12:20:50.577(1)? (STDERR)     at packages/aldeed_simple-schema.js:3128:3
W20171118-12:20:50.578(1)? (STDERR)     at infos.forEach.info (/home/storyteller/Web/meteor/Literary-Universe/.meteor/local/build/programs/server/boot.js:415:13)
W20171118-12:20:50.578(1)? (STDERR)     at Array.forEach (<anonymous>)
W20171118-12:20:50.578(1)? (STDERR)     at /home/storyteller/Web/meteor/Literary-Universe/.meteor/local/build/programs/server/boot.js:414:9
W20171118-12:20:50.578(1)? (STDERR)     at /home/storyteller/Web/meteor/Literary-Universe/.meteor/local/build/programs/server/boot.js:468:5
W20171118-12:20:50.578(1)? (STDERR)     at Function.run (/home/storyteller/Web/meteor/Literary-Universe/.meteor/local/build/programs/server/profile.js:510:12)
W20171118-12:20:50.578(1)? (STDERR)     at /home/storyteller/Web/meteor/Literary-Universe/.meteor/local/build/programs/server/boot.js:467:11
=> Exited with code: 1

```

**Comment by abernix** [comment] 2017-11-20 11:51
@keuaemou I don't believe this is an issue with Meteor itself, but rather in third-party packages.  Looking at the stack trace, it shows usage of `matb33:collection-hooks` code that is no longer present [in the current version](https://github.com/matb33/meteor-collection-hooks/blob/b96fa1fa9f40a8c07885f2629a91545339af5232/collection-hooks.js) (notably the `new ns.Collection` call, which seems like it's been refactored).

A newer version of `matb33:collection-hooks` would likely fix the problem however the other package in the stack trace, `jakik:ufs`, is [explicitly depending on](https://github.com/jalik/jalik-ufs/blob/25c188f4182c98675bb84a061d7aa92e32d1d441/package.js#L40) an older version.

Happy to reopen this issue if you can demonstrate that this problem lies in Meteor, but please do so by providing a reproduction per the steps for [reporting a bug](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-bug) in this repository.  Thanks!

**Comment by StorytellerCZ** [comment] 2017-11-20 16:42
@abernix Thanks! Will update to new the newest version of simple-schema and see if that fixes the issues.

**Comment by zimme** [comment] 2017-11-20 22:34
The latest version of `matb33:collection-hooks` is `0.9.0-rc.4`, which you will have to specify manually when installing the package.

The package do have [this line](https://github.com/matb33/meteor-collection-hooks/blob/b96fa1fa9f40a8c07885f2629a91545339af5232/collection-hooks.js#L272), which I'm not if it can be the cause of the problems for people using the package.

**Comment by alexgzhou** [comment] 2017-11-23 17:03
mikowals:batch-insert package with meteor 1.6.1 also showed this error, work fine when removed mikowals:batch-insert

**Comment by bmanturner** [comment] 2017-11-26 22:24
Can confirm ```matb33:collection-hooks@0.9.0-rc.4``` is still broken as of ```1.6.1-beta.11```. My project might be stuck on ```1.6``` until I can think of the proper workaround for how my code is organized.

**Comment by hwillson** [comment] 2017-11-28 17:32
Since this isn't a Meteor core issue, I'll close it off. Thanks!

**Comment by zimme** [comment] 2017-11-28 17:46
@hwillson In `matb33:collection-hooks` we're wrapping the `Mongo.Collection`/`Meteor.Collection` constructor and calling it with `.apply(this, ...)` and the mongo contstructor complains that we didn't create a new instance of the class with `new Mongo.Collection(...)`.

[This](https://github.com/meteor/meteor/commit/6fcf190bb489db19dc6b13052dc1391cf9209cb4#diff-9d3eee78c27b2ff499f0abf2e53eb3c7R27) is the change that triggered this breakage. So it would be good to see if there is a way to fix it in Meteor or at least find a fix for this that we could implement in our packages.

/cc @benjamn

**Comment by hwillson** [comment] 2017-11-28 17:58
Good to know, thanks @zimme - re-opening to track further discussion.

**Comment by woutervanwijk** [comment] 2017-12-03 14:18
Same behaviour here, but with the package service-configuration

**Comment by woutervanwijk** [comment] 2018-01-06 11:34
Sorry, I reported that it was service-configuration, but it is the lai:collection-extensions package that is broken. See https://github.com/rclai/meteor-collection-extensions/issues/14

**Comment by benjamn** [comment] 2018-01-16 00:29
Subclassing `Mongo.Collection` using non-native/compiled classes should work again if you try `meteor update --release 1.6.1-rc.6`, thanks to the commits linked above.

@StorytellerCZ Your problem with `Match.Where` should be fixed as well!

**Closed by benjamn** 2018-01-16 00:29 UTC
Labels: Project:Mongo Driver
