### ISSUE TITLE
Add a way for event maps to only handle events from the current template, not its children

### ISSUE THREAD

**Issue by Akash-dvd** [meteor/meteor#4064] opened 2015-03-30 07:02 UTC
In Template.myTemplate.events
the event selectors firing should be scoped to elements inside template (myTemplate) only.
IS there any work around right now.

**Comment by Akash-dvd** [comment] 2015-03-30 07:11
Something better than event.stopImmediatePropagation()

**Comment by PeppeL-G** [comment] 2015-03-30 07:14
A question:

```html
<template name="parent">
	<p>I'm in the parent template.</p>
	{{> child}}
</template>

<template name="child">
	<p>I'm in the child template.</p>
</template>
```

```javascript
Template.parent.events({
	'click p': funciton(){
		// This should only catch clicks in the parent's paragraph?
	}
})
```

**Comment by Akash-dvd** [comment] 2015-03-30 07:35
yupp , 
But i think stopPropagation() should be a dafault thing.
Also what if there are child 1 and child 2 .
Is child2 event captured by child 1 ,incase they match.
In that case stopImmediatePropagation should also be default.

**Comment by stubailo** [comment] 2015-03-30 18:59
@Akash-dvd I think a lot of people actually use the event maps expecting that events from children will be caught. I think we would maybe need an extra option or a different way of defining events that works the way you described.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by mitar** [comment] 2015-10-15 02:24
In [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) you can simply return from an event handler if you detect that `this.currentComponent() !== this.component()`. So that origin of an event is not in the current component.

**Comment by hwillson** [comment] 2016-11-25 21:52
Closing this issue as:

1. This is intended Blaze behavior (functions as designed); changing this functionality would break a lot of existing code.
2. There are workarounds.
3. There has been very little activity on this issue/request in over a year.

If anyone thinks this issue should stay open, please consider submitting a new feature request via the [Blaze repo](https://github.com/meteor/blaze).

**Closed by hwillson** 2016-11-25 21:52 UTC
Labels: feature, Project:Blaze

**Comment by mitar** [comment] 2016-11-26 03:19
Planned inline events will address this.
