### ISSUE TITLE
Latest MongoDB native driver

### ISSUE THREAD

**Issue by martinheidegger** [meteor/meteor#5763] opened 2015-12-08 03:04 UTC
Please see https://github.com/meteor/meteor/issues/6957 for a high level description of what needs to be done on this ticket. 

---

***1 Upvote*** The current MongoDB driver shipping with Meteor is [1.4.39](https://github.com/meteor/meteor/blob/5c3ace29269e3b67086303110133f62af400b55f/packages/npm-mongo/package.js#L6) but the latest MongoDB-native driver is [2.0.50](https://github.com/mongodb/node-mongodb-native/blob/6b348cb0197c21157a54db1855f30230e03c9a35/package.json#L3). The new version supports very useful methods such as `findOneAndDelete` which would be available to be used on the server of meteor using `rawCollection` or `rawDatabase`. It would be great if Meteor could ship with a newer version.

**Comment by avital** [comment] 2015-12-08 23:29
We tried doing the following:

Copy over the contents of Meteor's `npm-mongo` package into your app's `packages/` subdirectory. Then modify the `package.js` to refer to version 2.0.50 of the native Mongo driver (apparently that package no longer has binary dependencies so we don't need to maintain our own fork anymore)

Then you can run your app with the new Mongo driver.

The problem is that Meteor's `mongo` package depends on the API of the Mongo driver (including some private underscore'd methods and properties) and it breaks with the following error:

```
W20151208-15:18:51.519(-8)? (STDERR) TypeError: Cannot read property 'master' of undefined
W20151208-15:18:51.519(-8)? (STDERR)     at Object.Future.wait (/Users/avital/.meteor/packages/meteor-tool/.1.1.10.azw7zu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20151208-15:18:51.520(-8)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
W20151208-15:18:51.520(-8)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
W20151208-15:18:51.520(-8)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
W20151208-15:18:51.520(-8)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
W20151208-15:18:51.520(-8)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:102:1)
W20151208-15:18:51.520(-8)? (STDERR)     at AccountsServer.AccountsCommon (accounts_common.js:23:18)
W20151208-15:18:51.521(-8)? (STDERR)     at new AccountsServer (accounts_server.js:16:5)
W20151208-15:18:51.521(-8)? (STDERR)     at Package (globals_server.js:5:12)
W20151208-15:18:51.521(-8)? (STDERR)     at /Users/avital/tmp/todos/.meteor/local/build/programs/server/packages/accounts-base.js:1814:4
W20151208-15:18:51.521(-8)? (STDERR)     - - - - -
W20151208-15:18:51.521(-8)? (STDERR)     at packages/mongo/mongo_driver.js:183:1
W20151208-15:18:51.521(-8)? (STDERR)     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

which looks like it's coming from this line: https://github.com/meteor/meteor/blob/ccb044bb5ced9c90fead432cf6026aa56abd9370/packages/mongo/mongo_driver.js#L183. Looks like `db.serverConfig._state` is undefined.

So the solution requires re-engineering parts of the `mongo` package. You should be able to do that by also forking the `mongo` package into your app in the same way and modifying it until it works.

This isn't high enough priority for us to continue investigating this now, but if you (or anyone else) would like to continue digging into this, we'd happily look at a pull request changing the `mongo` package appropriately.

**Comment by zimme** [comment] 2015-12-09 20:17
Played around a bit with this and changing `db.serverConfig._state` to `db.serverConfig.isMasterDoc` and `db.serverConfig._state.master.name` to `db.serverConfig.isMasterDoc.primary` seems to work to solve the problem you got here @avital.

Then you also need to change this: https://github.com/meteor/meteor/blob/devel/packages/mongo/oplog_tailing.js#L214-L215
to be `if (!(isMasterDoc && isMasterDoc.setName)) {`.

So far things starts to look ok. Now the real problem kicks in.

The mongo driver have changed it's return value for `insert`/`update` and `remove`, they now return the full `mongo-core` results and have had their third reutrn value removed to better work with async and such, according to this: https://mongodb.github.io/node-mongodb-native/2.0/meta/changes-from-1.0/

**Comment by serkandurusoy** [comment] 2015-12-11 23:11
BTW this is now a blocking issue for those wanting to use latest Mongodb 3.2 which has some gamechanging new features.

[Required driver version >=2.1.0](https://docs.mongodb.org/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-mongodb-node)

**Comment by bySabi** [comment] 2015-12-11 23:41
and driver >=2.1.0 need node 4.X.X.
We are really screw up for a long time, I´m afraid.

**Comment by dcworldwide** [comment] 2015-12-11 23:46
+1

**Comment by glasser** [comment] 2015-12-16 00:48
@bySabi What makes you say that? The table in the link @serkandurusoy linked says that driver 2.1 is supported back to Node 0.8.

**Comment by bySabi** [comment] 2015-12-16 07:04
is my fault!!  sorry!! . Driver 2.1 is supported on Node 0.10
Glad to hear it. We'll got MongoDB  3.2 after all.

**Comment by georgiosd** [comment] 2016-01-13 15:48
Guys,

Does meteor currently support mongodb 3.2? We just updated and while the deployed app (RocketChat) was working fine for a while, it was throwing errors here and there about driver version. Does this have side-effects or just nagging?

**Comment by laran** [comment] 2016-04-03 21:32
This is a biggie for me too. My app depends on some features of 3.2 for indexing and full text search. A big 'ol +1 from me.

**Comment by lirbank** [comment] 2016-04-07 08:02
We're running 3.2 as well. It works with Meteor if you don't use oplog tailing (which is a bummer, but our product is pretty big on data and have lot's of other parts than Meteor, so we decided to sacrifice the oplog tailing in favor of getting all the goodies in MongoDB 3.2). At least this is true if you use Compose for hosting.

I think @debergalis mentioned that upgrading the mongo driver is a priority once 1.3 is out, in his talk at a Meteor event a little while ago. So hopefully there will be a resolution sometime soon.

**Comment by oscmejia** [comment] 2016-05-12 21:30
wow... this is taking really looooooong...

**Comment by lirbank** [comment] 2016-05-13 00:18
Update, We're running Meteor 1.3 with MongoDB 3.2 and oplog tailing successfully for our staging environment, and it seems to work well. We use Compose (Mongo 3.2) for production and oplog doesn't work at all with their setup. The setup where oplog works is a replicaset while Compose is a sharded cluster, so it could be the problem is with sharded clusters, not sure. So as long as you can live without findOneAndDelete and Compose, you can use Meteor 1.3 with Mongo 3.2 and oplog.

**Comment by mhagmajer** [comment] 2016-05-15 12:32
What this the Meteor Development Group view on this?

**Comment by liamzebedee** [comment] 2016-05-29 05:41
In follow-up to what @lirbank mentioned, I've just followed the Galaxy tutorial on the official Meteor site, which suggests using Compose (oplog not working with their setup).

**Comment by fabiodr** [comment] 2016-05-31 16:30
Will the driver be upgraded to latest version in Meteor 1.4?

**Comment by abernix** [comment] 2016-05-31 16:58
@fabiodr The plan right now is to ship Meteor 1.4 with the `mongodb@2.1.18` node driver and Mongo 3.2

**Comment by laosb** [comment] 2016-08-08 13:09
Fixed in 1.4. Closing.

**Closed by laosb** 2016-08-08 13:09 UTC
Labels: Project:Mongo Driver, pull-requests-encouraged

**Comment by vikas0121** [comment] 2018-08-09 14:06
how to update mongo driver in meteor application version 1.4.2.5?
I want to update the mongo driver from
mongo@1.1.14
mongo-id@1.0.6
mongo-livedata@1.0.12

**Comment by benjamn** [comment] 2018-08-09 14:17
@vikas0121 Since Meteor bundles a specific version of the Mongo binary in the `meteor-tool` package, which is specific to a given Meteor release, your best/only option is to update Meteor itself. See https://guide.meteor.com/1.7-migration.html for advice about the upgrade. Remember to back up your app (including the `.meteor`) directory in version control, and we recommend updating incrementally to the latest 1.5.x version (1.5.4.2), then 1.6.x (1.6.1.3), then 1.7.0.4:
```sh
meteor update --release 1.5.4.2
# verify that everything works
meteor update --release 1.6.1.3
# verify that everything works
meteor update
# verify that everything works
```
