### ISSUE TITLE
[Meteor 3] Unable to run bundle from "meteor build"

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#12932] opened 2023-12-22 17:03 UTC
Reproduction:
```
meteor create --release 3.0-alpha.19 test
cd test
meteor build --directory ../test-bundle
cd ../test-bundle/bundle/programs/server

# make sure node and npm versions match the versions in test-bundle/bundle/star.json

npm install
```

`npm install` errors with:

```
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /tmp/test-bundle/bundle/programs/server/npm-shrinkwrap.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/tmp/test-bundle/bundle/programs/server/npm-shrinkwrap.json'
npm ERR!  [Error: EACCES: permission denied, open '/tmp/test-bundle/bundle/programs/server/npm-shrinkwrap.json'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/tmp/test-bundle/bundle/programs/server/npm-shrinkwrap.json'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

For some reason npm tries to write to `npm-shrinkwrap.json` which fails since Meteor has always created it as a read only file. Old versions of Meteor worked correctly. There might be an issue with the npm-shrinkwrap.json file used in Meteor 3, or this might be caused by using a newer version of npm (though I wouldn't expect npm to try to update the shrinkwrap.json in this scenario).

**Comment by parlin** [comment] 2024-03-27 21:46
I am experiencing thie EACCESS error when trying to migrate an older app up to 2.13.1
I get the error when deplying on my webhost, but I get no error when running locally..

Would be great to hear if anyone has info on this. thank you

npm ERR! code EACCES
       npm ERR! syscall open
       npm ERR! path /build/f8c6d03b-508b-4b3d-ab38-3deb77404a6b/.app-build/bundle/programs/server/npm-shrinkwrap.json
       npm ERR! errno -13
       npm ERR! Error: EACCES: permission denied, open '/build/npm_***/.app-build/bundle/programs/server/npm-shrinkwrap.json'
       npm ERR!  [Error: EACCES: permission denied, open '/build/npm_***/.app-build/bundle/programs/server/npm-shrinkwrap.json'] {
       npm ERR!   errno: -13,
       npm ERR!   code: 'EACCES',
       npm ERR!   syscall: 'open',
       npm ERR!   path: '/build/f8c6d03b-508b-4b3d-ab38-3deb77404a6b/.app-build/bundle/programs/server/npm-shrinkwrap.json'

**Comment by harryadel** [comment] 2024-06-24 10:10
Yup, I run into this problem too. @nachocodoner @leonardoventurini Will you please take care of this problem in the next release?

**Comment by leonardoventurini** [comment] 2024-06-24 13:26
@harryadel, could it be perhaps related to the Node.js version? I think if you create a project in for Meteor 3 from a Meteor 2 default install, you would need to make sure the bundle for Meteor 3 is also installed for it to properly build with the right Node.js/NPM version. A potential fix would be to make sure Meteor 3 is installed by default in the docker image.

cc @nachocodoner

**Comment by nachocodoner** [comment] 2024-06-27 15:44
I've reproduced this issue in my Docker environment, used for development. It doesn't occur on other setups like Ubuntu or Mac without containerization.

Granting write permissions to `npm-shrinkwrap.json` resolves the issue. I'm considering automating on `meteor build` command a chmod for this file in specific environments to address the problem. Any thoughts on this fix?

I'm aware this raises security concerns, as modifying npm-shrinkwrap.json is not recommended. I'll investigate further why Docker environments attempt to modify this file during npm install.

@harryadel: Did you get this issue within a docker container? or in other circumstances?

**Comment by harryadel** [comment] 2024-06-30 21:48
@nachocodoner I get this issue when I try to build the application locally on my Manjaro (arch linux) device and also when trying to deploy using [Scalingo](https://scalingo.com/). Let me know, we can further assist you.

**Comment by harryadel** [comment] 2024-07-01 08:58
@nachocodoner I attempted to verify your claim and you're right. Seems to be building fine locally but gets messed up in docker environments.

https://github.com/harryadel/simpletasks/tree/main

You shall find a docker file in root directory, run it like so: `docker build -t my-meteor-3-app .`

and it'd yield the following result:
<img width="959" alt="2024-07-01_11-58" src="https://github.com/meteor/meteor/assets/6644545/c9a15c46-db31-4a2c-9c89-3e55dab412f0">

**Comment by nachocodoner** [comment] 2024-07-08 16:41
I have investigated this issue on a Mac Intel machine, outside of a Docker environment, and the problem persists.

## Build a Meteor 2 project

Meteor 2.x uses **node@14.x** and **npm@6.x**.

1- Run `meteor build --directory ../test-bundle`.
2 - Navigate to `../test-bundle/bundle/programs/server` and run `npm install`.

The `npx-shrinkwrap.json file` is [automatically modified](https://github.com/meteor/meteor/assets/2581993/6e06d73b-bdf3-49b5-b7d0-522d10289646) and [the write permission is not set](https://github.com/meteor/meteor/assets/2581993/bdd7c4e0-4c7c-46b2-9229-5cba58aea99b).

Using **node@20.x** and **npm@10.x**, [the error from this PR occurs](https://github.com/meteor/meteor/assets/2581993/97a8935f-d589-474b-b2c5-9411b1a533d1), even with a Meteor 2.x bundle.

## Build a Meteor 3 project

Meteor 3.x uses **node@20.x** and **npm@10.x**.

1 - Run meteor build --directory ../test-bundle.
2 - Navigate to ../test-bundle/bundle/programs/server and run npm install.

The `npx-shrinkwrap.json` file attempts to be modified, [throwing the error from this PR](https://github.com/meteor/meteor/assets/2581993/db354973-5543-4196-bf6b-c95089c67182), and [the write permission is not set](https://github.com/meteor/meteor/assets/2581993/a71514f2-6e02-4e3e-8f58-e80f64e0a5f7).

Using **node@14.x** and **npm@6.x**, [the npx-shrinkwrap.json file is modified and the lockfileVersion is downgraded](https://github.com/meteor/meteor/assets/2581993/fef5f2eb-8fa5-4cf9-a157-6b6af042be55).

If we rebuild the Meteor 3 app and set the write permission with `chmod 755 npx-shrinkwrap.json`, then [the npx-shrinkwrap.json file is modified with the lockfileVersion respected](https://github.com/meteor/meteor/assets/2581993/df652741-4c8c-4500-9f9b-bdf4e69a98fd).

## Conclusion

- The issue occurs broadly, not just in Docker environments.
- The npx-shrinkwrap.json file gets modified regardless of the npm version.
- Old npm versions (npm@6.x) modify the npx-shrinkwrap.json even without write permissions.
- New npm versions (npm@10.x) throw a permission error when modifying the npx-shrinkwrap.json without write permissions.

This issue seems related to a change in the npm installer on new versions used by Meteor 3.x by default. The `npx-shrinkwrap.json` file needs to be modified regardless.

Said this, I will implement the fix of automating the permission set as part of the `meteor build` command to ensure proper installation during `npm install` later.

**Comment by harryadel** [comment] 2024-07-09 08:56
I managed to have a workaround solution to deploy our Meteor application applying what you just suggested @nachocodoner 

https://github.com/harryadel/nodejs-buildpack/blob/af7c0ea815c45432cadb9c0c27a1be1e764d2a6a/bin/meteor.sh#L270

For anyone using Scalingo set `BUILDPACK_URL` to `https://github.com/harryadel/nodejs-buildpack` in order to use our customized version

**Comment by nachocodoner** [comment] 2024-07-09 12:17
Changes on the meteor build command implemented and tested here, https://github.com/meteor/meteor/pull/13219

`chmod 644 npm-shrinkwrap.json` is actually enough.

**Comment by harryadel** [comment] 2024-07-09 13:05
Great work, thank you for your efforts :clap:

**Comment by StorytellerCZ** [comment] 2024-07-19 17:40
@zodern @harryadel is this resolved now?

**Comment by denihs** [comment] 2024-07-24 17:17
This should be fixed now. I'm closing this issue, but we open it again in the future if necessary.

**Closed by denihs** 2024-07-24 17:17 UTC
Labels: confirmed, Type:Bug, Severity:has-workaround
