### ISSUE TITLE
Meteor commands mess up windows 10 powershell?

### ISSUE THREAD

**Issue by lednhatkhanh** [meteor/meteor#7826] opened 2016-09-27 14:25 UTC
Open powershell.
`cd` to the project dir
`meteor run`
The project still run but the powershell console is a mess, everything displays incorrectly.

**Comment by abernix** [comment] 2016-09-27 17:33
Duplicate of #6785.  It seems the work-around, until someone submits a fix for it, is to turn on "Legacy Mode" in your command prompt, but please see that issue for details.

**Closed by abernix** 2016-09-27 17:33 UTC
