### ISSUE TITLE
Meteor can't get assets with names containing special chars

### ISSUE THREAD

**Issue by arboleya** [meteor/meteor#5626] opened 2015-11-06 22:58 UTC
Yes, I know it doesn't look good to have names like `private/images/maça verde ou limão.png`.

``` javascript
Assets.getBinary('images/maça verde ou limão.png')
 // throw error EACESS file not found..
```

However I think Meteor should find the assets regardless of it's name (with or not special chars).

Makes sense?

**Comment by zol** [comment] 2015-11-17 23:04
Hey @arboleya . This looks like a valid issue. Could you please save collaborators some time and create a small reproduction repo as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by arboleya** [comment] 2015-11-27 17:15
Hi @zol, somehow I've lost track of this. I'll put up a repo. :v:

**Comment by arboleya** [comment] 2015-11-27 17:27
@zol here it is:
https://github.com/arboleya/meteor-assets-bug

**Comment by zol** [comment] 2015-12-04 01:12
Thanks @arboleya - I've confirmed your repro. Not sure on when we'll have time to work on a fix, PR's are encouraged!

**Comment by hwillson** [comment] 2016-10-21 09:31
I've dug into this a bit further; this is a [Unicode normalization](http://unicode.org/reports/tr15/) issue. Here's a quick example of where this is failing in the source.

Let's say we're making a `Assets.getText('maça verde.txt')` call. Looking in [boot.js](https://github.com/meteor/meteor/blob/cca97e2784831b4cd966a688842a892d7749d029/tools/static-assets/server/boot.js#L228-L229):

```
...
if (!fileInfo.assets || !_.has(fileInfo.assets, assetPath)) {
  _callback(new Error("Unknown asset: " + assetPath));
...
```

In this conditional, `fileInfo.assets` returns an object that looks like:

```
{ 
  'maça verde.txt': 'assets/app/macaverde.txt' 
}
```

and `assetPath` returns `maça verde.txt`. So the `_.has` call appears to look like:

```
_.has({ 'maça verde.txt': 'assets/app/macaverde.txt' }, 'maça verde.txt')
```

This should return true, but always returns false. This is because the two `maça verde.txt` strings are actually different thanks to Unicode code points; they're essentially lookalikes.

Since the `fileInfo` object is loaded from the `server/program.json` file, a really quick fix for this is to leverage ES2015's [`String.prototype.normalize()`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) capabilities. We could make sure that when the `program.json` file is loaded, it uses the Unicode Normalization Form of the loaded JSON string. So we could update [`tools/static-assets/server/server-json.js`](https://github.com/meteor/meteor/blob/cca97e2784831b4cd966a688842a892d7749d029/tools/static-assets/server/server-json.js) to look like:

```
var fs = require("fs");
var path = require("path");
var serverJsonPath = path.resolve(process.argv[2]);
module.exports = JSON.parse(
  fs.readFileSync(serverJsonPath, 'utf8').normalize('NFC')
);
```

I've tested these changes locally and this does fix the issue, but I'm by no means a Unicode expert. I can submit a PR for this but just thought I'd outline everything before I do, in-case anyone see's any issues with this approach. Thanks!

**Comment by abernix** [comment] 2016-10-21 14:27
Nice find!  I can confirm that the bug is indeed as you described.  So I guess this is a matter of one method being used by the operating system (or even input device, I suppose?) and another being used by Node?

I wonder if the `program.json` should be explicitly normalized before its written too?

**Comment by abernix** [comment] 2016-10-24 13:23
@hwillson Thinking about it a bit more, you're right that doing it when reading the file is the best failsafe and really the most important thing to address here.  The `program.json` will probably reflect what is on the actual file system that built it and I think that's reasonable, but any change to that process would be optional.

I would say go for the PR on this, and if you can include tests (perhaps [in here](https://github.com/meteor/meteor/blob/dbf8471c1fe139d207e3597cee334ddedae434ce/tools/tests/compiler-plugins.js), but maybe somewhere else?) then even better.  And happy to advise if you need help.

**Comment by hwillson** [comment] 2016-10-24 13:26
Thanks @abernix, will do!

**Comment by hwillson** [comment] 2016-10-26 01:31
Hi guys - I've submitted PR #7963 to address this issue. @abernix - looking over the existing `compiler-plugins.js` tests, it didn't quite look like a test for this would fit with the other tests listed there. Instead I created a new `tools/tests/assets.js` test file, with an associated `tools/tests/apps/unicode-asset-app`. Let me know if you think any of this should change. Thanks!

**Comment by hwillson** [comment] 2017-02-13 17:47
The PR for this was merged, so I'll close this off. Thanks for posting this issue!

**Closed by hwillson** 2017-02-13 17:47 UTC
Labels: bug, confirmed, Project:Utilities, pull-requests-encouraged
