### ISSUE TITLE
Meteor 1.3 issue with Cordova camera plugin and Android 6

### ISSUE THREAD

**Issue by jamalx31** [meteor/meteor#6976] opened 2016-05-05 12:17 UTC
We built a custom cordova plugin to capture videos, the app and the plugin works fine with android 5.
But on android 6, the plugin runs fine (no errors or exceptions) but the camera preview is a black screen (calling the plugin's api doesn't work as well). We tried Meteor 1.2 + plugin + android 6 and it works as expected. So this seems to be something with meteor 1.3 and android 6.

**Comment by abernix** [comment] 2016-05-05 13:02
Hey, can you make a very simple reproduction and upload it to github?

**Comment by jamalx31** [comment] 2016-05-05 13:22
@abernix 
here it's https://github.com/jamalx31/meteor-rep-recorder 
```meteor run android-device```

I tested it on nexus 5, android 6

**Comment by inspiraluna** [comment] 2016-05-05 20:14
I have a similar problem as it seems. 

I upgraded my working meteor 1.2.x webrtc kurento with crosswalk demo - app to meteor 1.3 lately.

But now the final problem seems to be here "**the camera stays black**" too. 
Fortunately I can give permissions under Android 6.0.1 manually! So camera suddenly works. :)  (@jamalx31 can you check this in your case please) 

Giving camera permissions manually in AndroidManifest.xml doesn't seem to help at all.
Tested on Samsung Galaxy S7, Android 6

if somebody wants to try it out here: 
https://github.com/inspiraluna/kurento-meteor/tree/master/hello-world

**Comment by inspiraluna** [comment] 2016-05-08 07:50
Sorry guys, I think its not a meteor bug! you need to take care of the permissions in Android by yourself as it seems.... Not sure if meteor can help here... but more people will fall over it I guess...

Please check:
https://forums.meteor.com/t/resolved-android-marshmallow-runtime-permissions-for-microphone-and-local-storage/22149/4
https://github.com/dpa99c/cordova-diagnostic-plugin/#android-runtime-permissions

**Comment by jamalx31** [comment] 2016-05-08 11:32
@inspiraluna you are right, thanks!
This is what I had to do:
```meteor add cordova:cordova.plugins.diagnostic@2.3.16```

and add this code:
```cordova.plugins.diagnostic.requestCameraAuthorization(function (granted) {
            console.log("Successfully requested camera authorization: authorization was " + (granted ? "GRANTED" : "DENIED"));
        }, function (error) {
            console.error(error);
        });

        cordova.plugins.diagnostic.requestMicrophoneAuthorization(function(granted){
            console.log("Successfully requested microphone authorization: authorization was " + (granted ? "GRANTED" : "DENIED"));
        }, function(error){
            console.error(error);
        });```

**Comment by abernix** [comment] 2016-05-09 10:18
This sounds like it might need to be addressed in the Meteor Guide.  @martijnwalraven should I turn this into a `guide` repo issue request?

**Comment by martijnwalraven** [comment] 2016-05-09 18:57
@abernix: Yes, that would be great! A pull request with some content would be even better :)

**Comment by lorensr** [comment] 2016-05-10 22:54
@abernix please keep either bug or feature in the label list to keep it out of the `is:issue is:open -label:bug -label:feature` filter for maintainer todo list, thanks!

**Comment by abernix** [comment] 2016-05-11 06:12
@lorensr If that's a golden rule, it should be in `Issue Triage.md` or discussed among Contributors and not in this issue.

**Comment by abernix** [comment] 2016-05-31 08:47
I've opened meteor/guide#470 to track this.  Unfortunately, I didn't have a PR to submit with it as I don't understand/use Cordova, but if anyone who is more familiar with the matter wants to do that I'm sure the Guide team would appreciate it greatly!

Closing this here though, as it's a documentation issue.  Thanks for reporting the issue!

**Closed by abernix** 2016-05-31 08:47 UTC
Labels: feature, Impact:some, known-fix, Project:Docs, Project:Mobile, Severity:has-workaround

**Comment by inspiraluna** [comment] 2016-05-31 20:36
if somebody explains me where and what to fork, I could write this and propose a PR.

**Comment by lorensr** [comment] 2016-06-01 03:30
@inspiraluna here are the three places to make note:

https://github.com/meteor/guide/blob/master/content/mobile.md

(I guess in the configuring-your-app section, saying how to do Android permissions in pre-6 and in 6)

https://github.com/meteor/mobile-packages/blob/master/packages/mdg:camera/README.md
https://github.com/meteor/mobile-packages/blob/master/packages/mdg:geolocation/README.md

**Comment by abernix** [comment] 2016-06-01 06:42
@inspiraluna I've looped you on the Meteor Guide issue and posted @lorensr's advice there as well.  Happy to continue the discussion over there. 😄
