### ISSUE TITLE
How can I debug in Meteor core packages in my app?

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9226] opened 2017-10-13 20:31 UTC
With v1.6-rc.9 node debugging with Chrome is a reality YAY!! (even on windows 😄)

All of my project files are properly mapped to the scripts and it is very simple/easy to use chrome node debugging.

### Why enable debugging in core meteor code?
Under some scenarios, it is useful to step into Meteor core code.  As an example for #9225 I could have helped with the Meteor fix if I was able to step into the `logging` package.

I think this could be useful to MDG because then we users can help them pinpoint issues for our often times very specific repro cases.

### Environment
- Windows 10 1703 (OS Build 15063.608)
- Meteor 1.6-rc.9

### Repro
1. start my meteor project `meteor --inspect-brk`
2. start chrome debug tools.
3. navigate to `(no domain)packages\logging.js`
The file shows up here:
![untitled](https://user-images.githubusercontent.com/14342237/31564962-f027ad96-b019-11e7-90f4-d12541a2ee76.png)

4. set breakpoint.

### Result
Breakpoint was not hit, but an error was thrown on that line of code.

### Expected
To be able to set breakpoints in Meteor core packages &/or code.

**Comment by hwillson** [comment] 2018-02-14 12:07
Hi @brucejo75 - you should be able to set breakpoints in Meteor core code. As an example, after your app starts up and you hit the first `debugger` statement, set a new breakpoint in `webapp/webapp_server.js`, on the `var app = connect();` line. Resume execution in the debugger, and you'll see that this breakpoint is hit.

It's likely that your `logging.js` breakpoint isn't hit as it's not called in the code flow that you're executing. If you're able to provide a small runnable reproduction with exact steps outlining where you're setting breakpoints and how you're calling your code, we'll take a look. I'll close this for now though since Meteor core breakpoints should be working properly. Thanks!

**Closed by hwillson** 2018-02-14 12:07 UTC
