### ISSUE TITLE
update to 1.4.2.3 from 1.4.2.1 memory error

### ISSUE THREAD

**Issue by gwhahaha** [meteor/meteor#8086] opened 2016-11-22 02:35 UTC
# Error
```
meteor update --patch
MINISAT-out: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
MINISAT-err: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
                                              
/Users/guowei/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
abort() at Error
    at jsStackTrace (packages/logic-solver.js:22:18626)
    at stackTrace (packages/logic-solver.js:22:18809)
    at abort (packages/logic-solver.js:52:28956)
    at enlargeMemory (packages/logic-solver.js:22:19142)
    at Function.Runtime.dynamicAlloc [as alloc] (packages/logic-solver.js:22:7927)
    at _sbrk (packages/logic-solver.js:22:58803)
    at Sd (packages/logic-solver.js:26:98389)
    at Ud (packages/logic-solver.js:26:109915)
    at gc (packages/logic-solver.js:26:41378)
    at Array.Oc (packages/logic-solver.js:26:73968)
    at Zb (packages/logic-solver.js:26:29115)
    at _b (packages/logic-solver.js:26:30575)
    at $b (packages/logic-solver.js:26:35130)
    at Bc (packages/logic-solver.js:26:54870)
    at Object.hd [as _solveAssuming] (packages/logic-solver.js:26:84479)
    at [object Object].MiniSat.solveAssuming (packages/logic-solver.js:157:18)
    at [object Object].Logic.Solver.solve (packages/logic-solver.js:1681:33)
    at [object Object].Logic.Solver.solveAssuming (packages/logic-solver.js:1714:21)
    at minMaxWS (packages/logic-solver.js:1986:31)
    at [object Object].Logic.Solver.minimizeWeightedSum (packages/logic-solver.js:2087:10)
    at packages/constraint-solver.js:1326:28
    at Function.time (/tools/tool-env/profile.js:305:10)
    at [object Object].CS.Solver.minimize (packages/constraint-solver.js:1310:16)
    at packages/constraint-solver.js:1286:12
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at [object Object].CS.Solver.minimize (packages/constraint-solver.js:1285:7)
    at [object Object].CS.Solver._getAnswer (packages/constraint-solver.js:1753:8)
    at packages/constraint-solver.js:1561:17
    at Function.time (/tools/tool-env/profile.js:305:10)
    at [object Object].CS.Solver.getAnswer (packages/constraint-solver.js:1560:23)
    at packages/constraint-solver.js:2258:25
    at Object.Logic.disablingAssertions (packages/logic-solver.js:390:12)
    at Function.CS.PackagesResolver._resolveWithInput (packages/constraint-solver.js:2257:16)
    at [object Object].CS.PackagesResolver.resolve (packages/constraint-solver.js:2221:34)
    at /tools/project-context.js:518:35
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/project-context.js:514:19
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:486:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._resolveConstraints (/tools/project-context.js:485:13)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/cli/commands-packages.js:1513:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:273:29)
    at maybeUpdateRelease (/tools/cli/commands-packages.js:1512:8)
    at Command.func (/tools/cli/commands-packages.js:1586:29)
    at /tools/cli/main.js:1483:23
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```
# packages
```
meteor-base@1.0.4                           # Packages every Meteor app needs to have
mobile-experience@1.0.4                     # Packages for a great mobile UX
mongo@1.1.14                                # The database Meteor supports right now
reactive-var@1.0.11                         # Reactive variable for tracker
tracker@1.1.1                               # Meteor's client-side reactive programming library
shell-server@0.2.1                          # Server-side component of the `meteor shell` command.
http                                        # Make HTTP calls to remote servers
accounts-password                           # Password support for accounts

# angular2
angular2-compilers                          # Angular 2 Templates, HTML and TypeScript compilers for Meteor
barbatus:angular2-polyfills                 # Polyfills for Angular2

# collection & schema
aldeed:simple-schema                        # A simple schema validation object with reactivity. Used by collection2 and autoform.
matb33:collection-hooks                     # Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
reywood:publish-composite                   # Publish a set of related documents from multiple collections with a reactive join

# fix ionic
urigo:cancel-fastclick                      # Removes fastclick in case it exists, Used for the official Ionic package
```

# versions
```
accounts-base@1.2.14
accounts-password@1.3.2
aldeed:simple-schema@1.5.3
allow-deny@1.0.5
angular2-compilers@0.6.6
autoupdate@1.3.12
babel-compiler@6.13.0
babel-runtime@0.1.13
barbatus:angular2-polyfills@0.5.0
barbatus:css-compiler@0.3.5_1
barbatus:scss-compiler@3.8.2
barbatus:typescript@0.5.2
barbatus:typescript-compiler@0.8.4
barbatus:typescript-runtime@0.1.2
base64@1.0.10
binary-heap@1.0.10
blaze@2.2.0
blaze-tools@1.0.10
boilerplate-generator@1.0.11
caching-compiler@1.1.9
callback-hook@1.0.10
check@1.2.4
ddp@1.2.5
ddp-client@1.3.2
ddp-common@1.2.8
ddp-rate-limiter@1.0.6
ddp-server@1.3.12
deps@1.0.12
diff-sequence@1.0.7
ecmascript@0.5.9
ecmascript-runtime@0.3.15
ejson@1.0.13
email@1.1.18
fastclick@1.0.13
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.10
id-map@1.0.9
jquery@1.11.10
launch-screen@1.1.0
livedata@1.0.18
localstorage@1.0.12
logging@1.1.16
matb33:collection-hooks@0.8.4
mdg:validation-error@0.5.1
meteor@1.6.0
meteor-base@1.0.4
minifier-css@1.2.15
minimongo@1.0.19
mobile-experience@1.0.4
mobile-status-bar@1.0.13
modules@0.7.7
modules-runtime@0.7.7
mongo@1.1.14
mongo-id@1.0.6
npm-bcrypt@0.9.2
npm-mongo@2.2.11_2
observe-sequence@1.0.14
ordered-dict@1.0.9
promise@0.8.8
random@1.0.10
rate-limit@1.0.6
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
reywood:publish-composite@1.4.2
routepolicy@1.0.12
service-configuration@1.0.11
sha@1.0.9
shell-server@0.2.1
spacebars@1.0.13
spacebars-compiler@1.0.13
srp@1.0.10
tracker@1.1.1
ui@1.0.12
underscore@1.0.10
urigo:cancel-fastclick@0.0.2
urigo:static-html-compiler@0.1.8
url@1.0.11
webapp@1.3.12
webapp-hashing@1.0.9

```

# finished-upgraders
```
notices-for-0.9.0
notices-for-0.9.1
0.9.4-platform-file
notices-for-facebook-graph-api-2
1.2.0-standard-minifiers-package
1.2.0-meteor-platform-split
1.2.0-cordova-changes
1.2.0-breaking-changes
1.3.0-split-minifiers-package
1.4.0-remove-old-dev-bundle-link
1.4.1-add-shell-server-package
```

# release
```
METEOR@1.4.2.1
```

**Comment by deltaag** [comment] 2016-11-22 06:26
Same problem updating from 1.4.2

**Comment by abernix** [comment] 2016-11-22 10:49
Duplicate of #7533.  Please [search](https://github.com/meteor/meteor/issues?utf8=%E2%9C%93&q=cannot%20enlarge%20memory) before opening new issues!

Closing but please follow, +1 in the other issue so we can gather information to resolve this!

**Closed by abernix** 2016-11-22 10:49 UTC
