### ISSUE TITLE
Meteor Email not Working on meteor > 1.4

### ISSUE THREAD

**Issue by ridumai** [meteor/meteor#8674] opened 2017-05-07 08:38 UTC
There's something wrong with the email package since I've updated to 1.4. Meteor 1.4 has been a huge improvement in terms of performance and I wouldn't like to downgrade, but I've read a lot of issues concerning email package and I still think there's something unsolved there, as I keep getting a self signed certificate error. 

I have the mail url setup in process.env.MAIL_URL and in the mup settings file within the env section, with and without the 's' in the smtp and cannot make it work.

I am desperate now.

**Comment by joadr** [comment] 2017-05-07 16:29
what version of the email package do you have? (you can see this in your `.meteor/versions` file). Also it would be interesting to know what version of meteor are you using, which mail provider, how is your smtp uri.

**Comment by ridumai** [comment] 2017-05-08 08:43
Hi joadr,

- email@1.2.1
- Meteor 1.4.4.2

- Mail url in the env section of mup.js:
MAIL_URL: 'smtp://eneas%40eneas.es:mypassword@smtp.eneas.es:465'

- Mail url in startup method:
process.env.MAIL_URL = 'smtp://eneas%40eneas.es:mypassword@smtp.eneas.es:465';

Getting errors with/without the smpts. Greeting never received or self signed certificate if I am using smtp or smtps.

Everything working fine until updating meteor to 1.4.

**Comment by hwillson** [comment] 2017-05-08 17:00
Hi @ridumai - your issue seems to be a duplicate of #8637 - can you confirm? As a temporary workaround, you can try downgrading your email package:

```
meteor add email@=1.1.18
```

**Comment by ridumai** [comment] 2017-05-09 07:45
Had seen the thread you linked. Could not find the solution.

I will try the downgrade, but if someone has had the same problem and got to a solution I will truly appreciate it.

**Comment by hwillson** [comment] 2017-05-09 11:05
Thanks @ridumai - #8637 doesn't have a solution yet, but it sounds like your issue is the same. Since that issue has already been triaged and marked as a feature request, I'll close this issue. Let's continue the discussion over there. Thanks!

**Closed by hwillson** 2017-05-09 11:05 UTC

**Comment by tyleha** [comment] 2017-05-10 22:51
Also experiencing this issue with our Meteor apps interfacing with Mailchimp/Mandrill. Seeing: `Error: Greeting never received`. Downgrading to email@1.1.18 did not have an effect.

Instead, the solution came from re-configuring Mandrill for SMTP over TLS: https://github.com/Wylio/meteor-mandrill/commit/a708dd2f48668b99559cdcbb783d8b50d5af000b

**Comment by interfaith** [comment] 2018-06-10 02:08
forget meteor email use nodejs
meteor is a nodejs framework now
https://nodemailer.com/about/
