### ISSUE TITLE
[chrome-stable] Error: Failed to parse SourceMap

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#7206] opened 2016-06-13 02:30 UTC
![image](https://cloud.githubusercontent.com/assets/8347826/15995678/3ead6934-3149-11e6-96a4-9475ad37a723.png)

this is my project:
https://github.com/lyquocnam/meteor-1.3-test

**Comment by Taakn** [comment] 2016-06-13 20:55
Same problem for me

**Comment by jamielob** [comment] 2016-06-14 10:13
Getting this issue again after upgrading to 1.3.3 on Chrome.    Not there in Canary or Safari.

**Comment by wojtkowiak** [comment] 2016-06-14 11:12
Experiencing the same problem.

**Comment by sahanDissanayake** [comment] 2016-06-14 21:17
Aslo get this warning in my console when starting the project
```
Warning: unable to resolve "meteor" in presets of myapp/location/dir/.babelrc

```

**Comment by sahanDissanayake** [comment] 2016-06-14 21:21
Has the build time slowed down for anyone else ? or is it just me ?

**Comment by markoshust** [comment] 2016-06-15 16:05
Same SourceMap error here on 1.3.3. Chrome Version 51.0.2704.84 (64-bit)

**Comment by jamielob** [comment] 2016-06-15 16:17
I got it back again too.  Narrowed it down to use with `react` and `react-dom` but couldn't fix.  Just disabled JS source maps for now in Chrome.

**Comment by kimeshan** [comment] 2016-06-16 03:39
Same here, SourceMap error immediately after upgrading to 1.3.3.

**Comment by sahanDissanayake** [comment] 2016-06-16 04:33
The issue gets worse. I did not update to Meteor V1.3.3 but the app itself did some updating or something and now I can see the same error without even updating. Weird

**Comment by dohomi** [comment] 2016-06-16 06:43
same issue for me on 1.3.3 and current stable Chrome

**Comment by s-devaney** [comment] 2016-06-17 21:21
![image](https://cloud.githubusercontent.com/assets/4226191/16165076/c52afcfe-34d9-11e6-88ad-e2666524bf33.png)

Windows 10 on latest stable Chrome

**Comment by mzygmunt** [comment] 2016-06-18 07:41
![image](https://cloud.githubusercontent.com/assets/13297558/16169724/b1a9ca0c-3538-11e6-8c68-d2c1373e9aec.png)

The same on Meteor 1.3.3.1 and Mac Chrome 51.0.2704.103 (64-bit).

**Comment by kimeshan** [comment] 2016-06-18 19:15
This has been fixed for me after I upgraded from 1.3.3 to 1.3.3.1. (Mac El Capitan on latest stable Chrome)

**Comment by s-devaney** [comment] 2016-06-18 21:10
![image](https://cloud.githubusercontent.com/assets/4226191/16173687/608151f4-35a1-11e6-82ad-a98574ca70d6.png)

Upgrading to 1.3.3.1 fixed one of the source map issues but I still have 1 error

**Comment by nicooprat** [comment] 2016-06-20 11:30
Stil getting errors with Chrome Version 51.0.2704.103 (64-bit) (Mac OS 10.11.5) and Meteor 1.3.3.1.

Downgrading to Chrome 49 resolved it ([found here](http://www.slimjet.com/chrome/google-chrome-old-version.php)). Looks like an issue with its latest version, upgrading Meteor and packages didn't change anything...

**Comment by laosb** [comment] 2016-06-21 04:45
Sounds like a Chrome error now?

**Comment by philrennie** [comment] 2016-06-21 15:25
I think it might be this chrome issue,

https://bugs.chromium.org/p/chromium/issues/detail?id=611328

In hindsight it probably started the other day when I let chrome upgrade to 51 and doesn't occur in canary.

**Comment by omsk359** [comment] 2016-06-25 21:22
Same error.
I don't think that it is the problem of Chrome, because if my app has an error, and I open it in Firefox, get something like this:
![tt2](https://cloud.githubusercontent.com/assets/6259915/16359131/4fdc7178-3b3a-11e6-8dfa-aeb8321b9c25.png)
Looks like, source map loaded incorrectly.

This bug appear/disappear randomly.
I use Debian i686, Chromium 51, FF 47, Meteor 1.3.3.

**Comment by abernix** [comment] 2016-06-28 09:41
I can confirm that this is reproducible using Meteor 1.3.3 but I can also confirm that the problem goes away when updating to Meteor 1.3.3.1.  I'm not entirely sure which change fixed it as there doesn't appear to be a specific commit that causes it (or is targeted to fix it) but there were some dependency upgrades between 1.3.3 and 1.3.3.1 that could have temporarily caused it – most likely `babel`.

I realize there are still some other issues with Source Maps (primarily with FireFox, #7140, #7076), but this particular issue as reported appears to be fixed.  I'll reopen this and dig deeper into it if someone can confirm this particular problem is still happening after Meteor 1.3.3, but otherwise I'll close this.

@omsk359 Your problem seems to be of a different nature entirely.

**Comment by tomitrescak** [comment] 2016-07-01 09:04
I have the very same problem running 1.3.4.1. Easy to replicate, just install the semantic:ui package and let it generate the basic set of styles. This error appears in Chrome 51.

**Comment by aboire** [comment] 2016-07-01 09:26
I had the same error and it was due to an error in one of my SCSS files (sass), I updated sass and corrected the problem of the SCSS file, and I have no error (for me not bind to the browser, the error did not appear before 1.3)

**Comment by s-devaney** [comment] 2016-07-01 17:36
I'm also using the semantic:ui package

**Comment by kachkaev** [comment] 2016-07-04 15:37
I also have this issue in a current project that uses `Meteor 1.4-beta.7`. Can this simply happen when a sourcemap becomes too big for Chrome? Mine is 3300KB.

**Comment by nicooprat** [comment] 2016-07-04 15:40
Also having the issue with a 255ko sourcemap file...

**Comment by kachkaev** [comment] 2016-07-04 15:50
Could anyone suggest a tool to analyze what's wrong with the sourcemap? A Chrome extension by a chance?

**Comment by abernix** [comment] 2016-07-04 16:54
Those that are using `semantic:ui` and having problems, are you also using `flemay:less-autoprefixer`?

**Comment by kachkaev** [comment] 2016-07-04 17:01
@abernix I'm not using any of those if that helps (at least they are not in `.meteor/versions`). Including [`react-bootstrap`](http://react-bootstrap.github.io/) from npm though.

**Comment by s-devaney** [comment] 2016-07-04 17:15
@abernix I am also using that

**Comment by abernix** [comment] 2016-07-04 17:40
The reason I bring it up is that I just found out [in another issue](https://github.com/meteor/meteor/issues/6798#issuecomment-230261775) that `flemay:less-autoprefixer` is incompatible with Meteor 1.3+.  It even states so on the [README.md for the project](https://github.com/flemay/less-autoprefixer#less--autoprefixer) and the author has [no plans to fix it right now](https://github.com/flemay/less-autoprefixer/issues/10).

I then noticed that `semantic:ui` recommends using this package in its installation instructions, so I'm guessing a fair number of folks are doing that.

Luckily, you can get the same functionality (and still use `semantic:ui`) by using `juliancwirko:postcss`.  You can read more about it in the [`README.md` for `juliancwirko:postcss`](https://github.com/juliancwirko/meteor-postcss).  This is actually recommended process in the [the Meteor Guide](https://guide.meteor.com/build-tool.html#postcss) anyhow.  Just make sure you `meteor remove flemay:less-autoprefixer` before you install it.  I won't be able to provide help on specific details of that migration, but it looks like it should solve your problem, @s-devaney (and others).

**Comment by detrohutt** [comment] 2016-07-04 19:04
Anyone who attempts the migration that @abernix suggested, take care to add autoprefixer as a "dependency" instead of a "devDependency"(as the guide currently suggests, in contradiction to the meteor/todos implementation). I've submitted a PR to the guide to address this.

**Comment by detrohutt** [comment] 2016-07-04 20:45
#### semantic:ui migration (flemay:less-autoprefixer to juliancwirko:postcss)
**Note:** These instructions are intended for meteor 1.3+ 
#### Edit meteor packages
`meteor remove flemay:less-autoprefixer`
`meteor remove standard-minifier-css`
`meteor add juliancwirko:postcss`
`meteor add less`

#### Edit package.json
```
{
  "dependencies": {
    "autoprefixer": "^6.3.1"
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {"browsers": ["last 2 versions"]}
    }
  }
}
```
`meteor npm install`

#### Restart the server
Kill the meteor process if it's running and start meteor as you normally would

**Comment by abernix** [comment] 2016-07-05 07:13
@detrohutt Thanks for the clarifications and taking the time to submit those PRs – much appreciated!

To the others who are not using `flemay:less-autoprefixer` and won't find this as a solution – I'm aware that it's likely only a portion of the problem, but any progress on knocking out various source-map issues is welcomed in my book.

**Comment by nicooprat** [comment] 2016-07-05 09:34
I'm using SCSS and not LESS, looks like @detrohutt's solution works with `fourseven:scss` too. No more errors in the console, SCSS & autoprefixer still working... Thanks!

**Comment by abernix** [comment] 2016-07-05 13:20
@nicooprat If you're on 1.4.x (and maybe even 1.3??), see #7297.

**Comment by nicooprat** [comment] 2016-07-05 13:29
@abernix Thanks for the heads up, but I meant errors in the browser console. No problem at Meteor build ;) But it could help others though...

**Comment by abernix** [comment] 2016-07-05 14:30
Ok, if you're getting `Failed to parse SourceMap` that is not resolved by removal of `flemay:less-autoprefixer`, could you click on the link to the `.map` file that it indicates as the problem and provide either:

 * *At a minimum,* the value of the `sources` object (stopping before the `mappings` and `sourcesContent`)
 * _If you feel comfortable_, a link to a [Gist](https://gist.github.com/) of the full contents.

**Comment by nicooprat** [comment] 2016-07-05 16:11
Here are my two errors (I'm not using `less-autoprefixer` btw, but `fourseven:scss` and `juliancwirko:postcss`):

https://gist.github.com/nicooprat/b0f85d7e8c08011ba9db1ba831dd3356 (you might look at raw versions)

**Comment by abernix** [comment] 2016-07-06 05:43
Ok, this is an intermittent bug.  It doesn't seem to ever happen to me on the first load, and only happens selectively on reloads (for me it seems to be about 1 in 5).  I was able to reproduce this (by reloading over and over again) with Meteor versions back to 1.3.3, and previous reporters above have shown that as well.

On the fresh project, I only see the `geojson-utils` source map error (seems to be a trend here) and on the existing project I see `geojson-utils` _and_ `softwarerero_accounts-t9n` (same as you @nicooprat).

**Comment by abernix** [comment] 2016-07-06 05:54
It doesn't appear to be a Meteor bug but instead a (relatively popular) bug in Chrome Stable:
https://bugs.chromium.org/p/chromium/issues/detail?id=611328

Which was fixed (recently) in this commit:
https://chromium.googlesource.com/chromium/src.git/+/ef323f099efc6246a16362f427cc52d9136de4ad
_(Commit Position 397618, Target Version 2743)_

The bug fix has [shipped to Chromium and Chrome Canary, Dev and Beta](https://googlechrome.github.io/current-versions/) channels.

**I cannot reproduce this issue any longer in Chrome Canary, but the fix will not ship to Chrome Stable until ["around July 26th"](https://bugs.chromium.org/p/chromium/issues/detail?id=611328#c21).**

I'm not sure why it's always showing on the same packages but, as the chromium.org issue suggests, it's likely related to utf-8 encoding within the source maps for those particular files.

Can anyone else confirm that this no longer occurs using Chrome Canary, Beta or Dev versions over (v52 and higher)?

**Comment by abernix** [comment] 2016-07-06 06:11
Just to further support my claim:

`geojson-utils`.`sourcesContent` has a single unicode character in it here:

```javascript
> sourceMapContent.sourcesContent.toString().match(/[^\x00-\x7F]/g).length
< 15519
```

Seen here:

    // normalise to -180..+180º

And `softwarerero_accounts-t9n`.`sourcesContent` has, well, a lot (expectedly):

```javascript
> sourceMapContent.sourcesContent.toString().match(/[^\x00-\x7F]/g).length
< 15519
```

My other (several dozen) SourceMaps have no (explicit) Unicode characters and work/load fine.

**Comment by nicooprat** [comment] 2016-07-06 09:18
Many thanks for your investigation @abernix! No more errors in Chrome Canary (54.0.2789.0) indeed.

**Comment by tomitrescak** [comment] 2016-07-06 18:16
I can confirm that with Chrome Canary the error no longer appears! But the initial page load of my app went from ~1 second to more then 10 seconds (I tried many times) ;( I guess that is why it's only a "canary".

**Comment by abernix** [comment] 2016-07-07 06:49
I wouldn't draw any conclusions between Meteor slowness and Chrome Canary.  Canary builds are done completely automatically on a daily basis with zero testing and contain a lot of wonky features.

Glad to hear the OP is appears resolved though.  Since this was a popular issue, I'll leave this open for a bit longer for feedback, but I'm going to consider it fixed.

**Comment by ffxsam** [comment] 2016-07-19 21:44
I can confirm that in Canary, source maps are working great. In Chrome 51, not so much. 💩  I suppose I'll be using Canary for my dev work for the time being.

**Comment by markoshust** [comment] 2016-07-22 14:18
Just an FYI to all who want to keep using Chrome stable and ignore the source maps error, you can just turn them off in debug tools https://www.dannycroft.co.uk/enabling-source-maps-in-chrome/

**Comment by abernix** [comment] 2016-07-22 14:51
Actually, the new Chrome Stable 2743 with this fix [just came out](https://googlechrome.github.io/current-versions/) for most desktop platforms.  If you haven't got it yet, check your Chrome for updates. :wink:

I can confirm this is fixed in the latest Chrome Stable so closing this issue.  Thanks to all who assisted in tracking it down!

**Closed by abernix** 2016-07-22 14:51 UTC
Labels: bug, confirmed, fixed, Impact:some, Severity:has-workaround
