### ISSUE TITLE
Need a consistent and cross-browser approach to logging caught errors

### ISSUE THREAD

**Issue by alanshaw** [meteor/meteor#2232] opened 2014-06-12 08:25 UTC
**_1 Upvote**_ I can't debug my app in Firefox. The error messages are really hard to decipher:
![screen shot 2014-06-12 at 09 22 22](https://cloud.githubusercontent.com/assets/152863/3255430/b96fdcea-f20a-11e3-82c5-bf5ae51ee6db.png)

Same exception in Chrome:
![screen shot 2014-06-12 at 09 23 36](https://cloud.githubusercontent.com/assets/152863/3255448/ee7a44fc-f20a-11e3-84b8-248a38082d63.png)

It seems as though the error message isn't being logged.

**Comment by MattiSG** [comment] 2015-01-05 16:20
Duplicate of #1211?

**Comment by ffxsam** [comment] 2015-05-24 01:21
I don't understand why the error shows up so differently in Firefox. How are errors being dumped? Are these not using `throw Error` or `console.error`? Should Meteor be using a more standard way of error reporting?

**Comment by lalomartins** [comment] 2015-06-07 18:26
All right, after about two days trying my hand at this… I got a much better situation on Firefox (without compromising Chrome). You can see my work on https://github.com/lalomartins/meteor/tree/error-improvements, and a test project at https://github.com/lalomartins/meteor-test-errors.

It's by no means a complete fix for this, especially not as described by @glasser — I touched tracker and blaze error reporting, there are still heaps more, so not “consistent”. A debugging package might make sense here, or at least a proper debugging API in the meteor package, but I'm not going to venture designing that on my own; maybe I'll start a hackpad.

This also fixes Firefox complaining about assigning to __proto__ as described in #4472.

**Comment by lalomartins** [comment] 2015-06-17 19:53
Ultimately (and somehow it seems nobody in the previous discussion noticed this, including myself), the main problem is that in Firefox we don't have the actual exception text (type + message), so it's hard to debug what actually happened. We were focusing on how ugly the stack looks, and didn't notice this.

That is definitely a Meteor bug; Meteor is counting on the stack property containing the type + message data, which it does in Chrome, but is not a standard.

(Incidentally, my branch does fix that, at least for Meteor errors.)

**Comment by Diggsey** [comment] 2015-06-17 20:44
Nice work @lalomartins - with these changes I will finally get zero warnings in my meteor app - a first as long as I've used meteor...

**Comment by alanshaw** [comment] 2015-06-17 23:02
Thank you @lalomartins

**Comment by ffxsam** [comment] 2015-06-17 23:09
Thanks! I've never understood why the errors are clean in Chrome but not Firefox. I thought we were supposed to be striving towards completely cross-platform solutions?

**Comment by lalomartins** [comment] 2015-06-18 00:48
@ffxsam unfortunately we won't be able to do much better than that :-( there's no such a thing as a standard error reporting/debugging facility. The console spec suggests logging an error object should produce a specialised display, but Firefox doesn't implement it fully (I did submit a patch, fwiw) and off the top of my head, I'm not sure Chrome does, either.

But if you get the error type and message, that would make it at least usable.

**Comment by ffxsam** [comment] 2015-06-18 01:31
This may be an ignorant question, but why doesn't Meteor just use `console.error()`? That's supported pretty universally.

**Comment by lalomartins** [comment] 2015-06-18 10:02
In my branch I do switch to `console.error` if available. **But**, that doesn't really have anything to do with what we're talking about; `console.error` doesn't do what I think you think it does ;-)

Actually `console.error` goes through the exact same output formatting as `console.log`; it's not an exception formatting function. The difference is `console.error` uses an “error” logging severity, which on Firefox devtools makes it red. You can also filter log output by severity. And there are additionally `console.info` and `console.warn`. Although `console.error` does display a trace of where it was _called_ — but that's not the same as where the error was thrown.

![console](https://cloud.githubusercontent.com/assets/1211455/8228524/bea21c04-15af-11e5-9285-2c74ff25aa79.png)

[Firefox console documentation](https://developer.mozilla.org/en-US/docs/Web/API/console)
[Console spec](https://github.com/DeveloperToolsWG/console-object/blob/master/api.md)
[Detailed test case/demo](http://htmlpad.org/console-error-subclass-2/)

Firefox does in fact special-case the built-in Error classes (Error, TypeError, etc), [but not custom errors](https://bugzilla.mozilla.org/show_bug.cgi?id=1172337) such as Meteor.Error and Match.Error.

And Chrome does *not*, in fact, handle any of this any better; it has only two differences, and those are in the creation of the Error object itself, not in `console.*`:

- Each line in the stack property has some leading whitespace (yes the stack property is just a big string with each `\n`-separated line being a stack level)
- And it has the error text in the first line (while Firefox doesn't) — and Meteor relies on this idiosyncrasy for its error output, so it displays only the stack, not the error text.

Additionally, the Chrome console detects references to source files, optionally with line and column numbers, and makes those clickable. But this is unrelated to the thing being logged being an Error or not.

So yeah, the longer answer to “why don't we just use a standard way of error reporting” is, there's no such thing :smile_cat: in fact, the word “mess” comes much closer to describing the current state of affairs.

**Comment by mitar** [comment] 2015-06-18 10:06
I am using [stacktrace.js](https://github.com/stacktracejs/stacktrace.js) to unify stack traces in my code.

**Comment by lalomartins** [comment] 2015-06-19 11:49
So here's my main issue with this issue:

- The original report is not a feature, it's a bug (it's almost impossible to debug Meteor apps in Firefox)
- And it should have a pretty high priority
- But then it scope-creeped into a feature that's pretty costly to implement and arguably lower priority
- Meanwhile the bug stays unfinished

I'd recommend splitting it. Except, of course, if my PR is accepted, the bug becomes moot ;-) so in that case we can just leave it as it is.

**Comment by MattiSG** [comment] 2015-06-20 16:10
+1 @lalomartins

**Comment by lalomartins** [comment] 2015-06-20 18:21
I rebased the branch so it can be easily merged. Apologies those using a checkout, you'll have to pull --force (or merge if you made changes of your own).

**Comment by lalomartins** [comment] 2015-06-20 18:33
I also pushed an error-improvements-1.1.1 for those (of us) not quite willing to develop our apps against devel ;-)

**Comment by lalomartins** [comment] 2015-06-22 16:36
For the record, the reason there's no pull request is that I'm a new contributor and as such I'm following the contributor guidelines :smile_cat: discussion first then sponsor then contributor agreement *then* PR

**Comment by Gaelan** [comment] 2015-08-30 20:54
FYI, the error messages are equally awful for the two web developers in the world still using Safari (myself included). :+100000:

**Comment by stubailo** [comment] 2015-09-21 05:05
@lalomartins can you submit a PR? It's hard to review a branch on its own.

**Comment by lalomartins** [comment] 2015-09-21 09:41
Note it can't be merged as it is. When it looks good I'll have to update the branch and probably do some manual merging.

**Comment by mquandalle** [comment] 2016-02-10 14:50
This should really be fixed as getting unreadable errors in bug reports is super frustrating (eg https://github.com/wekan/wekan/issues/516). Could the participants in this discussion share any actualized information that would help get the work done?

**Comment by stubailo** [comment] 2016-02-10 17:04
Yeah I'd love to get this fixed, if there's a PR with well tested code or even better a well-tested package, that would be great.

**Comment by lalomartins** [comment] 2016-02-10 17:10
If someone wants to take over my branch, I won't be offended. I don't have time to work on it right now. (It's missing tests and needs to be refreshed.)

**Comment by hwillson** [comment] 2017-06-12 14:32
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Need%20a%20consistent%20and%20cross-browser%20approach%20to%20logging%20caught%20errors&body=Migrated%20from:%20meteor/meteor%232232) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-12 14:32 UTC
Labels: feature, Project:JS Environment, Project:Utilities, pull-requests-encouraged
