### ISSUE TITLE
Meteor 1.3, Windows 10 : App does not start when "meteor" command is issued.

### ISSUE THREAD

**Issue by velu76** [meteor/meteor#7100] opened 2016-05-22 16:03 UTC
Hi,

Updated to windows 10. Then updated to Meteor 1.3

When I try to run my application, it hangs at "Starting App" as shown below.

![image](https://cloud.githubusercontent.com/assets/2929522/15454977/3e9bdd80-2079-11e6-902b-a0b43533650e.png)

I googled and found out that it was due to port config in Mongo. I had to use the "set MONGO_URL=mongodb://127.0.0.1:27017/sample" and same time I had to run my mongo server to get this to work.

Is this normal? Or is it a bug in the Window 10 install. 

Tested in Windows 7, seems to work fine.

**Comment by abernix** [comment] 2016-05-23 09:54
If another port is in use, I would expect an error to be produced (as it does on *nix systems).  For the Mongo port, the Meteor Tool automatically uses the app port (default: 3000) + 1 (so 3001).  Do you have something else running on that port?

What happens if you do `meteor -p 5000` (or some other port number?)

And does this happen on a blank new project?

**Comment by velu76** [comment] 2016-05-23 15:15
@abernix 
Hmmm. I checked the port is not used. And I have to manually get mongod to run in order for the whole thing to work. I am not sure why. Meteor runs its own internal MongoDB engine but in Windows 10 case, I need to run mongod and then only my application runs.

**Comment by velu76** [comment] 2016-05-25 13:21
I have confirmed the following issues on this matter:
1. Meteor 1.3 in Windows 10 is not able to start the local MongoDB
2. This causes the "meteor" on CLI to hang at the "Starting App"
3. Even if the port is set using "set MONGO_URL=mongodb://127.0.0.1:3001" meteor is still unable to connect to Mongo. Below screenshot if of the error.

![image](https://cloud.githubusercontent.com/assets/2929522/15541290/72a7dbfa-22be-11e6-8b63-bedfa9bd2098.png)

Therefore, I believe that the internal MongoDB engine in Meteor is not starting up when the meteor command is run.

**Comment by abernix** [comment] 2016-05-26 11:25
@velu76 Do you have another Windows 10 machine to try this on?  I'm able to run it fine on my Windows 10 VirtualBox.

**Comment by velu76** [comment] 2016-05-26 12:05
@abernix thank you for trying it. I don't have another Windows 10. But I tried in my office Win 7 pro it works. My Windows 10 is Home edition. Do you think it could be due to the fact that it is home edition that it is not working?

**Comment by abernix** [comment] 2016-05-26 14:55
@velu76 Unfortunately, I'm not sure at all and don't have access to Home Edition..  I would highly suggest making a post or searching  http://forums.meteor.com to see if someone has tried.

**Comment by vicktor3** [comment] 2016-06-17 14:05
For what it is worth, I have Windows 10 Pro and do not have the same issue as @velu76.  I do not believe the differences between Windows 10 Pro and home would make Mongo fail at reserving a port on startup through the Meteor script. 

@velu do you have VirtualBox or Vagrant installed with an image installed?

**Comment by abernix** [comment] 2016-06-27 10:16
I've now seen a couple times in the last month that Home doesn't work and Professional does.  There are probably good reasons for this, but I'm not really that familiar with the differences in Windows versions or what makes one work over the other.  I use Windows Professional at all levels. 

At the very least maybe try installing Visual Studio 2015 Community Edition?

**Comment by velu76** [comment] 2016-06-27 10:25
@vicktor3 Thanks mate for the response. I will try in Vagrant and see how that goes.

@abernix. Thank you as well. At least I know that Windows 10 Home might be the reason. I will continue to test and update on it.

**Comment by ivanmaia** [comment] 2016-08-24 05:09
I had same problem here after updated to 1.4.1. 
I use Ubuntu 14.04 LTS.
I solved the problem here running a Project reset: meteor reset.

**Comment by abernix** [comment] 2016-11-25 22:16
Closing as the original issue seems to be irreproducible and this hasn't been recurring.

If this happens, please reset your app with `meteor reset` (note, this will clear your development database, so make a backup if necessary).

**Closed by abernix** 2016-11-25 22:16 UTC
