### ISSUE TITLE
Assets with duplicate files in different folders are not built

### ISSUE THREAD

**Issue by Metamist** [meteor/meteor#7366] opened 2016-07-07 21:26 UTC
Currently using Meteor 1.3.4.1

If I add two directories that both contains a file called foo.txt with the contents "bar" into the private folder, only one of these folders are built into assets/app/

Example:

```
private/folder1/foo.txt -> bar
private/folder2/foo.txt -> bar
```

This structure will result in these built assets:

```
assets/app/folder1/foo.txt -> bar
```

`folder2` is ignored and not built at all.
I assume this is because both files have the same exact checksum.
Is this the intended functionality or is this a bug?

**Comment by abernix** [comment] 2016-07-08 10:31
Thanks for pointing this out.  I can confirm that the behavior you're referring to does in fact happen, but I can't actually see a situation where this actually breaks anything – that is unless you're doing your own accessing (via node's `fs.readFile`, etc.) of the files in that directory.

But, I think it's important to make a distinction between "Assets" (stored in `private`) and simple public files.  What you're talking about is Assets.

The Assets ([docs](https://docs.meteor.com/api/assets.html)) you put in the `private/` folder are accessible via `Assets.getText` and `Assets.getBinary`.  When you recreate the structure you have above, both `Assets.getText('folder1/foo.txt')` and `Assets.getText('folder2/foo.txt')` still work correctly, both in development and in production, despite the fact that when the files are bundled only one of them gets packaged up.  Internally, Meteor just points both references to the same single file – and in a way, more efficiently packages the assets since they're the same (saving space).

So, are you actually encountering a bug with this setup?  Or was it just an observation? :smile:

**Comment by Metamist** [comment] 2016-07-08 10:47
I encountered this bug while I was using the fs package from node, yes. I needed to get a list of files and directories in the private directory (assets/app) to iterate over. I could not find anything such as ```Assets.getList```or the like, so I had to use ```fs.readdir``` to get a list of files. That is when I noticed that some of the files were missing.
I have since then changed how my app works and am no longer in need to get a list of files since I now use an index file that contains an array of files that should be loaded.
If I am missing something and there is indeed a way to get a list of files and directories through the Assets library, then please do tell since it might come in handy in the future of my project.

**Comment by abernix** [comment] 2016-07-08 10:57
A `getList` method isn't available from the `Assets` API at the current time.  But yea, if you create an `index.json` asset in there (or something), that would be the best way to do it currently.

I'm going to mark this as confirmed bug until it can get reviewed.

**Comment by Metamist** [comment] 2016-07-08 10:58
Should also be noted that since assets are meant to be read-only, functions such as ```Assets.exists``` should also be available in the ```Assets``` API in my opinion.

**Comment by abernix** [comment] 2016-07-08 11:02
Assets aren't (currently) expected to change, stop existing, or be interacted with outside of the `Assets` API – generally best for private data files that your server might need to read.  Basically, if you use `Assets.getText`, then you put the file in `private/` and leave it there, thus an `Assets.exists` seems superfluous. 

What you're trying to do would probably work just fine using the `public/` folder though, unless the files cannot be available publicly on the client.

**Comment by Metamist** [comment] 2016-07-08 11:03
I suspected that I was misusing the private assets, thanks for clearing that up.
So, for files that are expected to change and should not be available to the client, where would those be located?

**Comment by abernix** [comment] 2016-07-08 11:14
Can you be more specific about what you're trying to do?

**Comment by Metamist** [comment] 2016-07-08 11:27
I store directories that contain Lua files, that will be iterated over and compiled into one big file which is then later minified. The minified file is then served through a REST API.
Basically, if I have a directory structure like this:
```
scripts/
--> 1234/
----> index.json
----> a.lua
----> b.lua
----> folder/
------> file.lua
```
These lua files will be compiled into one file according to a load order defined in the index.json.
These should not be available on the client for irrelevant reasons.
I will then access them with a REST API, for example ```/api/script/1234/``` which will compile the script, minify it, and serve it to the client.
As I said, these are not really expected to change currently, but in the future I will implement a way for me to upload these files through a web panel, which means I will have to write them to the disk. Which means I shouldn't use the Assets API since they are read-only.
But where can I store them and read them so that they are only available to the server, and not the client.
I am still fairly new to Meteor, and if there is a better way of doing what I want, then shoot. As I said, these files should not be available to the client.

**Comment by abernix** [comment] 2016-07-08 11:46
Well, you can write files where ever you would like on the server (well, outside of the `web.browser/app` directory) and read/serve them yourself, of course – you are still operating in a node environment, after all.   `mktemp` is a popular npm for choosing temp files.  Though, since you'll run into problems when working an environment with multiple servers, something like that would be written to a s3 bucket (or similar) and served from there.

What you're doing is very doable, but I don't think the Assets API is what you're looking for.

**Comment by Metamist** [comment] 2016-07-08 12:02
But when building the app, some folders aren't copied to the app directory so the relative path will be incorrect after building it. I am not exactly sure about the build process, but I would have to be playing with different paths depending on development environment and built environment. I might look more into S3 though, it might be a good way to store the files I need.
Are you saying I should store the files outside of the meteor app completely?

**Comment by abernix** [comment] 2016-07-08 13:11
> Are you saying I should store the files outside of the meteor app completely?

Generally speaking, yes, I'd recommend that.  Anywhere on the filesystem is fine.

**Comment by lucendio** [comment] 2016-09-14 10:52
I would like to have control over which files get optimized and which dont - e.g. with an options flag, like `bare` in `addFiles`.  I'd like to read and serve some files as streams, but with the current assets API it's not possible.

**Comment by gsabran** [comment] 2016-10-18 22:55
Even though this is not directly an issue for me, I've been surprised by this behavior. I don't see why a developer would except identical files under different paths within assets to be merged. I know this doesn't happen in public, but sometime you don't want things to be public.

For instance I'm using assets to store ssl certificates for Apple push notification, through [this library](https://github.com/node-apn/node-apn) that directly accesses the files and has no idea of the Assets API, which is probably the case for any node library.

Is there a reason the private folder is not directly copied to an asset folder, and to just make the path to the asset folder available?

**Comment by abernix** [comment] 2016-10-19 09:35
I don't think there's a reason – the `Assets` API just hasn't got attention in a while and I think behavior above is was just not expected or (as in the case of the original issue) just a straight-up bug.

**Comment by abernix** [comment] 2016-11-03 11:10
@hwillson I know you dove into some `Assets` stuff recently, so maybe you might have a fresh mind/perspective/reasoning as to what's up with this?  No worry if you don't, sometimes it's just nice to dabble in things you've recently dabbled in. :wink:

**Comment by hwillson** [comment] 2016-11-03 14:07
Hi @abernix - yes, I know why it's happening; the culprit code block is in [`tools/isobuild/bundler.js`](https://github.com/meteor/meteor/blob/fa86a682baad77c453af1800fddc54963188402b/tools/isobuild/bundler.js#L1935-L1946):

```js
loadItem.assets = {};
_.each(item.assets, function (data, relPath) {
  var sha = watch.sha1(data);
  if (_.has(assetFilesBySha, sha)) {
    loadItem.assets[relPath] = assetFilesBySha[sha];
  } else {
    loadItem.assets[relPath] = assetFilesBySha[sha] =
      builder.writeToGeneratedFilename(
        files.pathJoin(assetBundlePath, relPath), { data: data });
  }
});
```

A `sha` hash is being calculated based on each assets data which is then used to make sure each matching asset is only written once by the builder. If you remove the 

```js
  if (_.has(assetFilesBySha, sha)) {
    loadItem.assets[relPath] = assetFilesBySha[sha];
  } else {
```

block above, then duplicate assets in different directories are maintained.

So, this appears to have been by design (not a bug). I'm assuming the reasoning behind this was that since Meteor apps use the `Assets` API to access static resources, the Isobuild system can add some extra smarts to help reduce application overhead (by de-dupping static resources for example). I'm not sure if much thought was put into accessing these files outside of the `Assets` API however ...

**Comment by abernix** [comment] 2016-11-03 14:27
Thanks for the input, @hwillson.  That logic seems to make a lot of sense to me.  I'm going to backtrack on calling this a bug and go back to my [original comment](https://github.com/meteor/meteor/issues/7366#issuecomment-231328205): I don't think it's a bug, I don't see an actual issue and the behavior is expected.  `Assets` (which includes the use of the `private/` directory) are designed to be accessed by using `Assets.getText` and `Assets.getBinary` and when you use that API, the asset is correctly returned, even if duplicate assets have been squashed.

@gsabran The docs for `node-apn` indiciate that it [supports passing the file data or a `Buffer`](https://github.com/node-apn/node-apn/blob/master/doc/provider.markdown) (`Assets.getText` and `Assets.getBinary`, respectively) instead of the path to the file.  This is typically supported practice in NPMs.  Passing the `Buffer` received from `Assets.getBinary` allows Meteor to keep managing duplicate assets and squashing them if necessary – a net benefit to the bundle size.

**Comment by Metamist** [comment] 2016-11-06 22:11
@abernix I agree completely, but as my original issue depended on getting a list of files in a directory, there is no `Assets.getList` function, which is why I were using `fs` in the first place. If the assets are meant to be accessed only with the `Assets` API, we need more functions such as getting a list of files in a directory, as it's very limited right now.

**Comment by abernix** [comment] 2016-11-08 13:44
Ok, I guess ultimately, it seems like this would be better labelled as a feature request then.  Is this something you'd be willing to work on?

**Comment by hwillson** [comment] 2017-06-08 01:33
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Assets%20with%20duplicate%20files%20in%20different%20folders%20are%20not%20built&body=Migrated%20from:%20meteor/meteor%237366) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-08 01:33 UTC
Labels: feature, Impact:few, Project:Isobuild, pull-requests-encouraged, Severity:has-workaround

**Comment by b-jsshapiro** [comment] 2024-10-20 02:07
@hwilson In the discussion above, there was mention of needing to deploy ssl certificates that seems to have gotten lost in the comments. I've just run into a case where things broke badly because of this behavior. The problem with these files ia that there really isn't any other place to put them from which the bundler will pick them up.

I'm very open to putting mine someplace else, but they need to get bundled. Any suggestion on where/how to accomplish that?
