### ISSUE TITLE
Out of memory error when using console.log() with a large array on Windows

### ISSUE THREAD

**Issue by SeanBannister** [meteor/meteor#5543] opened 2015-10-26 15:51 UTC
I'm running Meteor 1.2.0.2 (Windows 8.1 64bit) and receiving the following error when I use console.log() server side on a large array or object:

```
C:\Users\Sean\SkyDrive\Development\test>meteor
[[[[[ C:\Users\Sean\SkyDrive\Development\test ]]]]]

=> Started proxy.
=> Started MongoDB.

C:\Users\Sean\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\tools\utils
\fiber-helpers.js:168
    }).run();
       ^
FATAL ERROR: Evacuation Allocation failed - process out of memory
```

When it occurs I have 4gb of RAM free according to Windows (I have page files enabled). And the node.js process is using about 160mb of RAM.

To debug this error further and isolate it I created a fresh meteor project with `meteor create` removed all the html and javascript and removed all packages except meteor-base. The only javascript I run is: https://gist.github.com/SeanBannister/151afb2c2a84861aaa07

I've also tested this on a second machine running Windows 10 64bit and I've tried it under Meteor 1.1 and get the same error. I've also tried removing ecmascript and es5-shim.

So I'm not really sure what's causing this, if there's anything else I can do to debug this please let me know.

**Comment by stubailo** [comment] 2015-10-26 18:08
I've confirmed that this doesn't happen when you log the same thing from a regular node.js script.

**Comment by stubailo** [comment] 2015-10-26 18:10
OK on my Mac this doesn't happen at all, even inside a Meteor app.

@SeanBannister, can you try running a regular Node script that logs the same thing, and run it using Node.js on Windows? That might be faster than me getting to a Windows PC.

**Comment by SeanBannister** [comment] 2015-10-26 18:54
@stubailo Thanks, just ran it as a node.js script and it runs fine.

**Comment by stubailo** [comment] 2015-10-26 19:02
OK so sounds like it could be Meteor-specific.

**Comment by AlbinoGeek** [comment] 2015-11-10 02:35
Yup, having this issue a lot here too!

How do I get around it for the mean time, is there a shallow log extension somewhere?  (anyone?)

**Comment by SeanBannister** [comment] 2015-11-10 06:29
@AlbinoGeek  Decided to throw together an ugly work around when I saw your message and received the error again. I'm pretty printing the object and writing it to a log file in the project root.

    var log = function(obj) {
      Npm.require('fs').appendFile(process.cwd() + '/../../../../../log.json', JSON.stringify(obj, null, 2), function (err) { 
        if (err) throw err;
      });
    }
    log (myObject);

**Comment by alokshenoy** [comment] 2016-01-11 23:54
Got the same issue. Server side console.log( really big array ) crashes with the same error as above.

**Comment by femanso** [comment] 2016-02-23 20:53
Same here, runing on windows 10, when I call a big json object from http and log
```
    const usersObj = JSON.parse(response.content);
    _.forOwn(usersObj, function(value, key) {
      console.log(value);
    } );
```
I get the following 
```
FATAL ERROR: JS Allocation failed - process out of memory
```

**Comment by kasun32** [comment] 2016-03-10 09:28
I'm having the same issue here. I tried running [Telescope](http://www.telescopeapp.org/) which is buit on meteor. The app starts and loads fine. But when I am trying to post something it crashes returning the same error. An screenshot is attached below

![image](https://cloud.githubusercontent.com/assets/7568242/13665008/53b01f84-e6d0-11e5-869c-5912c0441615.png)

Please help me to resolve this.

**Comment by dtrimsd** [comment] 2016-04-23 00:02
I've run into the same problem. This has never occurred before. I've been running into weird things since 1.3. I'm currently on 1.3.2.2.


FATAL ERROR: Evacuation Allocation failed - process out of memory
Aborted (core dumped)
I'm using sendmail. I'm heavily logging. 

Here are the packages I use:

accounts-password      1.1.8  Password support for accounts
accounts-ui            1.1.9  Simple templates to add login widgets to an app
blaze-html-templates   1.0.4  Compile HTML templates into reactive UI with Meteor Blaze
check                  1.2.1  Check whether a value matches a pattern
ejson                  1.0.11  Extended and Extensible JSON library
email                  1.0.12  Send email messages
http                   1.1.5  Make HTTP calls to remote servers
iron:router            1.0.12  Routing specifically designed for Meteor
jquery                 1.11.8  Manipulate the DOM using CSS selectors
logging                1.0.12  Logging facility.
meteor-base            1.0.4  Packages that every Meteor app needs
mobile-experience      1.0.4  Packages for a great mobile user experience
mongo                  1.1.7  Adaptor for using MongoDB and Minimongo over DDP
random                 1.0.9  Random number generator and utilities
reload                 1.1.8  Reload the page while preserving application state.
sacha:spin             2.3.1  Simple spinner package for Meteor
session                1.1.5  Session variable
spacebars              1.0.11  Handlebars-like template language for Meteor
standard-minifier-css  1.0.6  Standard css minifier used with Meteor apps by default.
standard-minifier-js   1.0.6  Standard javascript minifiers used with Meteor apps by default.
tracker                1.0.13  Dependency tracker to allow reactive callbacks
twbs:bootstrap         3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.

**Comment by Rahman-S-M** [comment] 2016-04-26 02:29
I'm getting fatal error while refreshing...the changes are minimal
How to debug this? There is no  other message?

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

=> Meteor server restarted
=> Meteor server restarted
=> Meteor server restarted
=> Client modified -- refreshing
=> Meteor server restarted
=> Client modified -- refreshing
FATAL ERROR: JS Allocation failed - process out of memory

**Comment by hwillson** [comment] 2017-08-18 16:29
There have been many new Meteor releases since this issue was posted, with numerous performance/memory optimizations. Since there hasn't been any activity on this issue in a while, I'll close it for now. If anyone is still encountering this issue with a current version of Meteor (1.5.1 as of today), please post back and I'll re-open accordingly. Thanks!

**Closed by hwillson** 2017-08-18 16:29 UTC
Labels: Project:JS Environment, Project:Windows
