### ISSUE TITLE
Error: EPERM, unlink `.../jquery.js` on Windows

### ISSUE THREAD

**Issue by niklomi** [meteor/meteor#4973] opened 2015-08-16 15:25 UTC
I am using MeteorJS on Windows and after some corrections and saves in code (use SublimeText 3) my app dies. And I see this 
![2 part](https://cloud.githubusercontent.com/assets/10808204/9293870/880162be-4443-11e5-9a29-0d07242462bb.PNG)
![1 part](https://cloud.githubusercontent.com/assets/10808204/9293869/87ff1626-4443-11e5-8493-8781b6f46980.PNG)

<b>I hope this is important!</b> - I use WIDNOWS 8 and sometimes, after saving the code,  I do not wait when my app refresh(upgrade), I change something in my code and save it at once!

**Comment by sjmcdowall** [comment] 2015-08-16 16:01
Yes that could be important -- also, Windows 8.1 or Windows 10?  If so, have you tried running the cmd shell with Windows 7 compatibility mode?  This seems to be a known issue because the file is still "busy" during the rebuild or something.. (there are other reported bugs with similar errors -- all EPERM on Windows during a rebuild) ... <shrug>

**Comment by niklomi** [comment] 2015-08-16 16:05
Windows 8.0 . No I don't try this, but I will today.
Also I have this error but with other file (not "../jquery.js), and when I try to find this files, they doesnt exist

**Comment by rfox90** [comment] 2015-08-17 11:37
I see a ton of this sort of thing on windows 7 too.  If it keeps happening i just delete the build folder inside .meteor/local slows down the next build but usually fixes it for awhile.

**Comment by anubhav94** [comment] 2015-08-18 21:42
Duplicate of #4933.

**Closed by anubhav94** 2015-08-18 21:42 UTC
Labels: Project:Windows
