### ISSUE TITLE
Issue with changes to tracker behaviour in 1.1

### ISSUE THREAD

**Issue by JackAdams** [meteor/meteor#4110] opened 2015-04-02 16:19 UTC
When upgrading from 1.0.5 to 1.1, I'm seeing this error in the client console.  It's not deterministic -- only happens roughly 2 out of 3 hard browser refreshes (and doesn't happen on hot code reloads).
```
"Exception from Tracker recompute function:" meteor.js:888:10
"TypeError: domrange is undefined" meteor.js:888:10
"doRender/<@http://localhost:3000/packages/blaze.js?264be6a901108935eddf10209d174ed62a9bc64b:2031:9"
```
I'm guessing it's something to do with the changes made to tracker in 1.1.  The line of code referenced is from the `Blaze._materializeView` function, which I don't think was changed in 1.1:
```
// Causes any nested views to stop immediately, not when we call                                          
// `setMembers` the next time around the autorun.  Otherwise,                          
// helpers in the DOM tree to be replaced might be scheduled   
// to re-run before we have a chance to stop them.  
Tracker.onInvalidate(function () {     
  domrange.destroyMembers();  
});  
```
Any ideas where I could start looking for what's causing this in my app? (Note: this app has been working well with all updates to Meteor since 0.5.7.)

**Comment by glasser** [comment] 2015-04-02 16:24
Duplicate of #4097.  We'll probably put out a patch release soon to fix it.

**Closed by glasser** 2015-04-02 16:24 UTC
