### ISSUE TITLE
[Meteor 1.3-rc.8] node_modules error

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#6570] opened 2016-03-23 07:58 UTC
```
W20160323-14:32:39.941(7)? (STDERR)
W20160323-14:32:39.943(7)? (STDERR) fs.js:696
W20160323-14:32:39.944(7)? (STDERR)   return binding.stat(pathModule._makeLong(path));
W20160323-14:32:39.944(7)? (STDERR)                  ^
W20160323-14:32:39.945(7)? (STDERR) Error: ENOENT, no such file or directory 'D:\D\DEV\Meteor\Meteor\rc8\node_modules'
W20160323-14:32:39.945(7)? (STDERR)     at Object.fs.statSync (fs.js:696:18)
W20160323-14:32:39.945(7)? (STDERR)     at findAppDir (D:\DEV\Meteor\Meteor\rc8\.meteor\local\build\programs\server\npm-require.js:9:10)
W20160323-14:32:39.945(7)? (STDERR)     at addByPath (D:\DEV\Meteor\Meteor\rc8\.meteor\local\build\programs\server\npm-require.js:58:22)
W20160323-14:32:39.947(7)? (STDERR)     at registerNodeModules (D:\DEV\Meteor\Meteor\rc8\.meteor\local\build\programs\server\npm-require.js:45:5)
W20160323-14:32:39.947(7)? (STDERR)     at D:\DEV\Meteor\Meteor\rc8\.meteor\local\build\programs\server\npm-require.js:37:9
W20160323-14:32:39.947(7)? (STDERR)     at Array.forEach (native)
W20160323-14:32:39.948(7)? (STDERR)     at Function._.each._.forEach (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.2.5-rc.8\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160323-14:32:39.948(7)? (STDERR)     at Object.<anonymous> (D:\DEV\Meteor\Meteor\rc8\.meteor\local\build\programs\server\npm-require.js:30:3)
W20160323-14:32:39.948(7)? (STDERR)     at Module._compile (module.js:456:26)
W20160323-14:32:39.948(7)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
=> Exited with code: 8
W20160323-14:32:44.885(7)? (STDERR)
W20160323-14:32:44.885(7)? (STDERR) fs.js:696
W20160323-14:32:44.886(7)? (STDERR)   return binding.stat(pathModule._makeLong(path));
W20160323-14:32:44.886(7)? (STDERR) Error: ENOENT, no such file or directory 'D:\D\DEV\Meteor\Meteor\rc8\node_modules'
W20160323-14:32:44.886(7)? (STDERR)                  ^
W20160323-14:32:44.886(7)? (STDERR)     at Object.fs.statSync (fs.js:696:18)
W20160323-14:32:44.887(7)? (STDERR)     at registerNodeModules (D:\DEV\Meteor\Meteor\rc8\.meteor\local\build\programs\server\npm-require.js:45:5)
W20160323-14:32:44.887(7)? (STDERR)     at addByPath (D:\DEV\Meteor\Meteor\rc8\.meteor\local\build\programs\server\npm-require.js:58:22)
W20160323-14:32:44.887(7)? (STDERR)     at D:\DEV\Meteor\Meteor\rc8\.meteor\local\build\programs\server\npm-require.js:37:9
W20160323-14:32:44.888(7)? (STDERR)     at Array.forEach (native)
W20160323-14:32:44.888(7)? (STDERR)     at Function._.each._.forEach (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.2.5-rc.8\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160323-14:32:44.888(7)? (STDERR)     at Object.<anonymous> (D:\DEV\Meteor\Meteor\rc8\.meteor\local\build\programs\server\npm-require.js:30:3)
W20160323-14:32:44.888(7)? (STDERR)     at Module._compile (module.js:456:26)
W20160323-14:32:44.889(7)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160323-14:32:44.887(7)? (STDERR)     at findAppDir (D:\DEV\Meteor\Meteor\rc8\.meteor\local\build\programs\server\npm-require.js:9:10)
=> Exited with code: 8
```

my packages:
```
{
  "name": "rc8",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "meteor-node-stubs": "~0.2.0",
    "bootstrap-less": "^3.3.8",
    "font-awesome": "^4.5.0",
    "lodash": "^4.6.1",
    "mantra-core": "^1.2.0",
    "numeral": "^1.5.3",
    "react": "~0.14.1",
    "react-bootstrap": "^0.28.3",
    "react-dom": "^0.14.6",
    "react-helmet": "^2.3.1",
    "react-mounter": "^1.0.0",
    "summernote": "^0.8.1",
    "sweetalert": "^1.1.3"
  }
}

```
all code is plain.

**Comment by lyquocnam** [comment] 2016-03-23 07:59
same here: [6568](https://github.com/meteor/meteor/issues/6568)

**Comment by martijnwalraven** [comment] 2016-03-23 08:38
Closing this as a duplicate of #6568.

**Closed by martijnwalraven** 2016-03-23 08:38 UTC
