### ISSUE TITLE
meteor/cordova/ios not allowed to load local resource on IOS

### ISSUE THREAD

**Issue by dotnetwise** [meteor/meteor#3799] opened 2015-02-23 20:25 UTC
We are using the file transfer plugin to download a file to 
`file:///var/mobile/Containers/Data/Application/6BB3B78C-0BAA-42FF-93F0-C70B80B86944/tmp/cdv_photo_003.jpg`

However, then trying to access that path with an `<img` tag will give us security errors:
`Not allowed to load local resource: file:///var/mobile/Containers/Data/Application/6BB3B78C-0BAA-42FF-93F0-C70B80B86944/tmp/cdv_photo_003.jpg`

This won't happen in a normal `cordova` app since it starts via `file:///` protocol

However `meteor` breaks this beacuse the app will start on `http://meteor.local`

So, how to give access to the app's `file:///` sandbox files?

**Comment by Slava** [comment] 2015-02-24 22:04
You are right, there is no good way to do it right now.

**Comment by dotnetwise** [comment] 2015-02-25 07:53
So, why enforce `http://meteor.local` then?

I think there should be an option to be on the file protocol so that would be the same as normal cordova app.

What about `file:///meteor.local` to be "served" the same way as `http://meteor.local`
This way would also fix the `android 2.3` buggy `http://meteor.local` and would also keep the same functionality/behavior as for a normal cordova (meteorless) app.

What do you think?

**Comment by Slava** [comment] 2015-02-25 08:04
The environment on `file://` urls doesn't match the environment you get in the browser on a regular website. A lot of this has to do with cross-origin requests, single-page routing, hash fragments and problems coming out of this approach.

**Comment by dotnetwise** [comment] 2015-02-25 08:19
Yes, but none of them are a problem in a normal cordova app.

And if we are migrating from an existing app towards meteor then we will have a broken app, just because the app won't run in a file:/// environment anymore.

So, at least give us the option in the `mobile-config.js` to specify the `http://meteor.local` or `file:///meteor.local` or anything else.

**Comment by ddresch** [comment] 2015-03-12 18:28
What exactly does this mean? It's not possible to access downloaded files in any way? Are there any solutions or practices how to download and store larger assets like sounds etc. AND access these later on? 

I mean this is not an rare use case, it's pretty common I guess. `appcache` is probably not the best solution to build on if you handle bigger files, I got no experience with it so this is more a question.

**Comment by glasser** [comment] 2015-04-01 20:24
Just closed #3229 as duplicate of this. It contains a good reproduction:  https://github.com/jperl/repro-meteor-3229

**Comment by glasser** [comment] 2015-04-01 20:31
https://github.com/phonegap/phonegap-app-developer/issues/134
https://muut.com/i/appgyver/steroids:using-file-uri-not-showing
https://github.com/AppGyver/kitchensink/blob/master/app/controllers/camera.coffee#L67
https://code.google.com/p/chromium/issues/detail?id=40787

It sounds like this isn't a Meteor problem so much as a general issue on Cordova/WebKit apps. If they're not running from `file:` they can't access `file:`, even with CORS configured.  So unless I'm confused there's not much you can do.  The camera.coffee there seems to show something where it moves the file to another path that it then serves via an http server and uses a `/foo` URI instead of `file:`.

**Comment by nate-strauser** [comment] 2015-04-15 21:45
i came up with a workaround for this.  use the cordova http server plugin (https://github.com/floatinghotpot/cordova-httpd) to serve up the downloaded files.

flow is like so:
start up web server on app startup (localhost only)
file transfer does download to device storage
http server serves up downloaded files
meteor app loads assets from urls like "http://127.0.0.1/<file>"

i wonder if we could add an option into the cordova autoupdate server to offer this functionality.  eg: a 'files' directory that would be usable for downloads and then serving to the app

**Comment by Slava** [comment] 2015-04-15 21:50
@nate-strauser as a matter of fact, we already use cordova-httpd: https://github.com/meteor/com.meteor.cordova-update

**Comment by nate-strauser** [comment] 2015-04-15 23:14
@Slava i saw that! that's what i was referring to as "the cordova autoupdate server"

I was thinking that we could offer a config option that would serve up a particular directory in addition to the application assets.  i didn't really dig into the file structure of the cordova update functionality.  would it be advisable to just download files into the same area which meteor downloads new application code?

**Comment by Slava** [comment] 2015-04-16 00:23
> would it be advisable to just download files into the same area which meteor downloads new application code?

@nate-strauser Not sure what you mean by this sentence.

If you want to play with the changes to meteor-update, here are two ways to do that, I will describe the one that is a bit more hassle but generally has no issues with caching of xcode, etc:

- fork the com.meteor.cordova-update repo
- make changes to the iOS part or Android part
- get a checkout of meteor/meteor
- edit the file `/packages/webapp/package.js`, edit the line that imports the `cordova-update` plugin (replace the url to the tarball url of your change)
- use the checkout of meteor to create a new android/ios app

**Comment by nate-strauser** [comment] 2015-04-20 17:55
maybe this will be a little more clear...

see my example app which uses a web server to serve up files written to the file system with the file transfer plugin - https://github.com/nate-strauser/meteor-offline-mobile-files-demo - works very well after files are downloaded and connection is dropped

what i was suggesting is that instead of this 2 http server solution, the autoupdate http server could provide the same capability (serve up some files from the filesystem to the app as well as provide app code updates)

![http server](https://cloud.githubusercontent.com/assets/389646/7236759/dd21966a-e764-11e4-86ef-79b86a479daa.png)

just wanted to see what the core team / community thought about this as a solution to the file storage problem

**Comment by miri-am** [comment] 2015-04-27 16:52
to me this is not some edge case but a core functionality in most mobile apps. There needs to be an easy way to access locally saved files.

**Comment by icenpop** [comment] 2015-05-11 19:34
@miri-am +1

**Comment by udiedrichsen** [comment] 2015-05-29 06:02
I tried the last week to get access to local files in meteor cordova app without success.
Why is this not possible ?

@miri-am +1

**Comment by qdsang** [comment] 2015-06-26 11:33
@miri-am  +1

**Comment by harellevy** [comment] 2015-07-02 21:25
+1

**Comment by rtchOx** [comment] 2015-07-02 22:33
+1

**Comment by rtchOx** [comment] 2015-07-02 22:38
This has been an issue for me as well. +1

**Comment by irrigator** [comment] 2015-07-06 15:16
I met this problem, too. +1 Still no solution?

**Comment by yiluxin** [comment] 2015-07-06 18:46
+1！This problem cause I need to rework，can't to resolve

**Comment by sicter** [comment] 2015-07-06 19:56
+1 rather large issue for me, really need a solution

**Comment by shishircc** [comment] 2015-07-14 04:35
+1 large issue for me too. I spent 3 days trying to figure out what I was doing wrong compared to the samples on the web for cordova. I am sure lot of people are stumped by this issue.

**Comment by rtchox** [comment] 2015-07-16 17:00
@nate-strauser Thanks you for your offline-files demo! Solved the problem beautifully for me.

**Comment by nate-strauser** [comment] 2015-07-16 18:05
:)  glad it helped

i'm in the process of turning the file server portion of that demo into a
package for easy use - should have that out in a week or so

**Comment by rtchox** [comment] 2015-07-16 18:13
wonderful -- that will be well appreciated by the community.

**Comment by martijnwalraven** [comment] 2015-07-16 18:40
@nate-strauser Thanks for your work on this issue. I won't be able to spend time on this for a few weeks, but my intention is to look into it as part of improvements to the Cordova integration that I hope to get into the Meteor 1.2 release. I'd like to move part of the Hot Code Push functionality into native code, and that might open up opportunities for dealing with other file access.

**Comment by nate-strauser** [comment] 2015-07-16 19:20
@martijnwalraven are you planning to have the app code still be served up from http://meteor.local?  if you change it to be served from the filesystem, then we should be able to load files from a file:// url without needing a http server to proxy them.  it seems the root issue here is a http:// originated app is blocked from trying to access file:// resources.  i'm not really pushing for a particular path here, just curious.

let me know if you wanted to chat further about this or i can help in any way.  my plan was to roll out a couple packages related to cordova issues i've dealt with recently.  mainly accessing files on the filesystem and downloading files for offline use.  my demo project lays out solutions to these issues, but i'd prefer to deliver a set of easily reusable packages.

**Comment by martijnwalraven** [comment] 2015-07-16 19:35
To be honest, I haven't had a chance to think about this in detail, but from what I understand the reason to serve files from http://meteor.local instead of file:// urls is that the latter don't support pushState properly. That seems like a good reason to stick with it, unless you know of another workaround.

I'd definitely be interested in learning more about the Cordova issues you've run into and the solutions you've found. I'm fairly new to Cordova myself (having done primarily native mobile development) and feel the current Cordova integration could use some improvements.

Ideally, features like this should just work and not require additional packages/plugins. Having more control over the native wrapper might help I think, but I'll need to spend more time on this to know whether that is the right direction.

**Comment by henkstom** [comment] 2015-07-17 06:55
I found a way to work around this problem. I use the internalURL      cdvfile://

   rootToURL = fileSystem.root.toURL();
   rootToInternalURL = fileSystem.root.toInternalURL();
   image.src = imageData.replace(rootToURL,rootToInternalURL);

It works for me with images on iOS.

**Comment by udiedrichsen** [comment] 2015-07-17 07:49
@henkstom How do you set the imageURL ?
cdvfile://localhost/persistent/dcim
or 
cdvfile://meteor.local/persistent/dcim

**Comment by henkstom** [comment] 2015-07-17 07:53
i used 

cdvfile://localhost/persistent

**Comment by nate-strauser** [comment] 2015-07-24 00:43
i wanted this to work as the cordova http server solution feels clumsy, but it appears to only work for images - see https://github.com/nate-strauser/meteor-offline-mobile-files-demo/tree/cdv-test

images appear to download and then load from the device just fine, but video and audio do not seem to work (they download fine, but will not load from the internal url) - i'm wondering if it is related to this issue - https://issues.apache.org/jira/browse/CB-6051 - i also tried to load in the cordova file + media plugins, but that doesn't seem to help https://github.com/nate-strauser/meteor-offline-mobile-files-demo/blob/cdv-test/.meteor/cordova-plugins

unfortunately, i don't believe the `cdvfile://` urls work for complex media like audio and video  :(

**Comment by dekelblip** [comment] 2015-07-30 02:56
I have the same error message when trying to access contact images. Setting an img src to something like "content://com.android.contacts/contacts/30470/photo" works with plain cordova but not with meteor project. Is there a workaround for this? It is a rather common requirement from a mobile application...

**Comment by hitchcott** [comment] 2015-08-03 06:11
Thanks @henkstom for the workaround. I'm at least able to display an image in the DOM now.

Problem is, now I'm now getting `[Error] Unable to get image data from canvas because the canvas has been tainted by cross-origin data.` (when using canvas) even though I have `App.accessRule("*")` in `mobile-config.js`.

Any ideas?

**Comment by henkstom** [comment] 2015-08-03 10:08
I have the same problem. I'm trying with cordova-httpd. And searching for a way to set the CORS header.

**Comment by sday** [comment] 2015-08-09 22:00
"There needs to be an easy way to access locally saved files."

agreed

**Comment by hitchcott** [comment] 2015-08-11 11:37
I was able to get around my video streaming from camera issue by sending base64 data from the native app but things got warm pretty quick. Looks like it would need throttling.

**Comment by dwilt** [comment] 2015-08-28 03:19
:+1: on this needing to be easier

**Comment by johanbuys** [comment] 2015-08-28 08:16
+1 Major stumbling block at the moment.

**Comment by martijnwalraven** [comment] 2015-08-28 08:33
I've heard you! This is definitely at the top of my todo list for after the Meteor 1.2 release, together with Hot Code Push improvements.

**Comment by johanbuys** [comment] 2015-08-28 08:37
@martijnwalraven Thanks a mill for all the hard work! :)

**Comment by derwaldgeist** [comment] 2015-08-30 13:25
@martijnwalraven: Thanks for taking care of this. I've just run into the same issue. Having a storage for any kind of rich media is an absolute must for most mobile apps, IMHO. My app is depending heavily on photos/videos taken by the user, and now I'm kinda stuck. :-/

**Comment by derwaldgeist** [comment] 2015-08-30 13:27
@nate-strauser: Any update on your planned public packages so far? Would love to hear they're finished, as this is a major road block for me, like for the others here.

**Comment by nate-strauser** [comment] 2015-09-03 19:29
@derwaldgeist here you go!  https://atmospherejs.com/natestrauser/cordova-file-server

This package just provides the http server part for you.  You still need to deal with downloading files and sending the correct url (local or remote) to the template.  In the future, I may make this functionality a separate package that depends on the cordova-file-server package.

**Comment by vigile** [comment] 2015-09-03 21:17
Wonderful !!! Thank you
Le 3 sept. 2015 23:30, "Nathan Strauser" <notifications@github.com> a
écrit :

**Comment by derwaldgeist** [comment] 2015-09-04 06:31
Thanks, this in great news!

**Comment by adrianolsk** [comment] 2015-09-10 18:11
I got the same error when trying to display a contact picture on android

``` Not allowed to load local resource: content://com.android.contacts/contacts/10 ```

**Comment by ilampirai** [comment] 2015-09-11 22:52
When I try the package  natestrauser/cordova-file-server

Got the following error :
starting server at /storage/emulated/0/
failed to start server: IO Exception: Host is unresolved: 127.0.0.1

plz help @nate-strauser

**Comment by byrne-yan** [comment] 2015-09-13 01:00
@ilampirai @nate-strauser I met the same issue. When I forked the project and then changed the 'localhost_only' to false, it worked.

**Comment by ilampirai** [comment] 2015-09-13 01:51
Thanks @byrne-yan  your fix works well.

@nate-strauser Is there a way to send www_root , port and localhost flag from our meteor js file ? (in meteor.startup function) that will be helpful greatly can you make your package work so?

**Comment by nate-strauser** [comment] 2015-09-13 20:21
i updated the package default for localhost_only to be false.  I also added the ability to override all the http server options via meteor settings.  hopefully this works for you all!

@adrianolsk it might.  you seem to be experiencing the same issue with not being able to load content across protocols.  although i'm not sure how you would be able to access contact pictures via the filesystem access that my package provides.

**Comment by dnish** [comment] 2015-09-13 22:51
Is there any possibility to upload a picture with CollectionFS? With your plugin, I can display a image - but I also need to add it to my file collection. I've tried to generate a base64 url with a canvas element, but that didn't work (seems a cross domain issue).

**Comment by derwaldgeist** [comment] 2015-09-14 06:39
@dnish: I had the very same problems. I wanted to upload a picture taken with a mobile camera via Cordova, this is always a base64 encoded string. But this was not accepted by CollectionFS/GridFS. So eventually, I switched over to Slingshot, which is not optimal for my use-case, but at least worked.

**Comment by dnish** [comment] 2015-09-14 11:06
@derwaldgeist CollectionFS isn't the problem here. I always get a 1979 byte base64 string, because Cordova can't access the image due policy (I think Nates plugin need to send a "allow-origin: *" header to make it work).

If you want to insert a base64 image string to CollectionFS, you also need the EJSON plugin for it - on my projects it works without problems.

https://github.com/CollectionFS/Meteor-cfs-ejson-file

Without that plugin you should get an error like "reached maximum stack size".

**Comment by derwaldgeist** [comment] 2015-09-14 13:20
Thanks for this info and the hint for the EJSON plugin. Is there any documentation available how to use this? The page only says "FS.File as EJSON", but in my case, I do not have a File object, I have a data URL.

Anyway, I did *not* get an error at all in my app. Instead, the upload seemed to work and was acknowledged by CollectionFS, but when I tried to download the file again, an invalid / incomplete URL was returned, and I also saw that the images collection did not contain the content, only the file record was there. Using slingshot, everything worked as expected.

**Comment by dnish** [comment] 2015-09-14 14:48
@derwaldgeist There is no documentation for EJSON, it works automatically after installation. I also add the "data:" url directly into my FS collection, that works without any problems. Do you use GridFS as storage engine? What about displaying an image with 

    <img src="{{foundImage.url store='your collection'}}"/>

**Comment by byrne-yan** [comment] 2015-10-17 14:22
@henkstom  have you found  a way to set the CORS header for cordova httpd?

**Comment by kartikTT** [comment] 2015-11-10 00:29
Would this same issue be causing a 401 on loading image urls? Just posted an SO question about this here: http://stackoverflow.com/questions/33620521/image-urls-fail-to-load-on-meteor-1-2-ios-cordova-app

Seems like the image urls are downloaded to the phone but unable to be accessed after, as you all have been mentioning.

**Comment by alfredclyim** [comment] 2016-01-01 05:27
The cordova-file-server works fine. I would like to remove the downloaded files. Is there anyway to do it?

**Comment by c0cky** [comment] 2016-01-06 03:04
+ 1

**Comment by c0cky** [comment] 2016-01-06 03:04
+1 need a solution

**Comment by DanielDornhardt** [comment] 2016-01-19 17:54
+1 for this. Please, please make this a priority, access to local files is the bridge to using many cordova media plugins. I'm gonna beg for this in the Meteor 1.3 Mobile Release Plan too: https://github.com/meteor/meteor/issues/5786

**Closed** 2016-01-23 04:58 UTC
Labels: in progress, Project:Mobile

**Comment by c0cky** [comment] 2016-01-23 05:02
:smile:

**Comment by martijnwalraven** [comment] 2016-01-23 05:59
Local file system access on iOS is now available in Meteor 1.3 beta. You can construct file system URLs manually (http://localhost:<port>/local-filesystem/<path>), but core plugins like `cordova-plugin-file` and `cordova-plugin-camera` (using `Camera.DestinationType.FILE_URI`) will now automatically return these URLs instead of `file://` URLs. (see https://github.com/meteor/meteor/issues/6050).

**Comment by cmboros** [comment] 2016-01-25 23:05
I'm using https://github.com/apache/cordova-plugin-media-capture it returns /private/var/mobile/Containers/Data/Application/23E3A830-5CC6-4A80-A8BF-ED4421B55580/tmp/capture-T0x14f6173b0.tmp.KmvTEI/capturedvideo.MOV but is not working. 
I have add http://localhost:8080/local-filesystem and also my IP instead of localhost and is still not working. I try to display a preview or to upload and both are not working. 
Is any way to get the url using Media Capture Plugin?

**Comment by martijnwalraven** [comment] 2016-01-25 23:12
I'm not sure what you mean by having added `http://localhost:8080/local-filesystem` or your IP, but there should be no further configuration needed. The actual port number should be in the 12000-13000 range (check the logs, it is based on the `appId` so will be the same on every run).

**Comment by cmboros** [comment] 2016-01-26 00:11
Hey thanks for the respond. I have fixed by adding /local-filesystem to the path and it works.

Thanks for a great update.

**Comment by jamalx31** [comment] 2016-01-26 13:28
+1
I'm trying to access a video file saved in /data/data/[packagename], with http://localhost:12000/local-filesystem and without
but it doesn't work, tried with meteor 1.3 beta too

**Comment by martijnwalraven** [comment] 2016-01-26 13:38
@jamalx31: Local file access should work on both iOS and Android with the latest beta (`1.3-cordova-beta.3`). On Android (which I'm guessing you're using, since you refer to the `/data` directory), you should now be able to use a regular `file://` URL (it doesn't use `localhost`).

**Comment by jamalx31** [comment] 2016-01-26 14:16
@martijnwalraven thank you so much. i was using beta.2, in beta.3 it works for android.
I guess there's there's problem with iOS, after the splashscreen I get black white page

**Comment by martijnwalraven** [comment] 2016-01-26 14:19
@jamalx31: Try to use Safari remote debugger to see if there are any error messages in the console (you may have to reload the page to see them).

**Comment by jamalx31** [comment] 2016-01-26 14:30
@martijnwalraven I checked, it shows nothing.
In another project with angular, I get the same problem with android. in chrome console I see:
deviceready has not fired after 5 seconds.
cordova.js:1178 Channel not fired: onDOMContentLoaded

**Comment by jamalx31** [comment] 2016-01-26 15:09
@martijnwalraven another problem I noticed.
I can bootstrap the app from the console by:
angular.bootstrap(document.documentElement, ['myApp']);

but I see for: <img src="/icon.png"/>: (should get from the 'public' folder)
GET file:///icon.png net::ERR_FILE_NOT_FOUND
Is this related to the previous problem ?

**Comment by martijnwalraven** [comment] 2016-01-26 15:16
Hmm, not sure where this goes wrong, but the URL should be file://app/icon.png

**Comment by Exilz** [comment] 2016-01-26 15:37
@jamalx31 with the latest beta release, here's what I'm doing :+1: 

iOS : `<img src="/img/icon.png" />`
Android : `<img src="file://app/img/icon.png" />`

I'm using a helper to do so, it works properly.

**Comment by jamalx31** [comment] 2016-01-26 15:48
@Exilz thanks, you are right. Do you have problem to bootstrap ?
Can you share your helper ? :)

**Comment by Exilz** [comment] 2016-01-26 15:52
@jamalx31 
```
// App.isAndroid comes from a package of mine, do the detection you want instead
const getRPath  = () => App.device.isAndroid ? 'file://app' : '';
App.GlobalFuncs.getRPath = getRPath;
Template.registerHelper("rPath", getRPath);
```
So I can do in HTML : 
    
    <img class="header--logo" src="{{rPath}}/img/logos/header.png" alt="" />

And in JS : 

    blankImage: `${App.GlobalFuncs.getRPath()}/img/default-landscape.jpg`

Hope that helps !

**Comment by martijnwalraven** [comment] 2016-01-26 16:04
@Exilz: That shouldn't be necessary. In `file://app/`, `app` is not part of of the path but the 'authority' (similar to a 'host'). So an absolute path (like `/img/logos/header.png`) should work without any issues.

**Comment by Exilz** [comment] 2016-01-26 16:46
@martijnwalraven that's what I figured, but it doesn't seem to be working on Android :/

**Comment by martijnwalraven** [comment] 2016-01-26 16:54
Hmm, I just tried this on Android 5.1 with the latest system web view and it worked. There might be a difference in the way different web views handle this. What is the URL it is trying to reach for you?

**Comment by Exilz** [comment] 2016-01-26 17:00
`GET file:///app/img/logos/header.png net::ERR_FILE_NOT_FOUND`

That's what I get on Android (5.0, with crosswalk)

**Comment by martijnwalraven** [comment] 2016-01-26 17:20
Thanks! It seems it is somehow treating 'file://app' as 'file:///app', not sure why. I won't be able to have a look at this until later this week, but I'll get back to you.

**Comment by ofcapl** [comment] 2016-02-02 13:15
is there any chance to provide easy file read from sd card on android & ios without CORS error?

**Comment by jamalx31** [comment] 2016-02-02 16:28
@Exilz are you using typescript in your project ?
I guess it's may related to the issue with 'file:///'

**Comment by Exilz** [comment] 2016-02-02 16:51
@jamalx31 No, I'm not. Only ES6

**Comment by jamalx31** [comment] 2016-02-03 12:00
@Exilz @martijnwalraven 
In my case the problem was I used <base href="app/">

but I still have a problem with the socket connection with the server

**Comment by martijnwalraven** [comment] 2016-02-03 13:49
@Exilz: Any chance `<base href="/">` is also the cause of your problem?

**Comment by jamalx31** [comment] 2016-02-03 14:16
@martijnwalraven do you have any idea why I get this error:
```GET http://domain.com/sockjs/info?cb=7lzrqhxyms net::ERR_CACHE_MISS```

is it connected to the difference between file:// and http:// protocols ?

**Comment by Exilz** [comment] 2016-02-03 14:32
@martijnwalraven nope, sadly :/ I'm not using it.

**Comment by martijnwalraven** [comment] 2016-02-03 15:49
@Exilz: Are you using Iron Router? I'm currently investigating an issue where it doesn't seem to respect the `file://app/` base URL.

**Comment by Exilz** [comment] 2016-02-04 08:25
@martijnwalraven I'm using FlowRouter.

**Comment by martijnwalraven** [comment] 2016-02-12 10:22
@Exilz: This should be fixed in the latest 1.3 beta. 

I've reverted the change to `file://app/` on Android made in a previous beta, because of issues with `file://` URLs that do not seem fixable. So we now serve files from `http://localhost:<port>` on both iOS and Android. Local files can be accessed from `http://localhost:<port>/local-filesystem/<path>`.

**Comment by Exilz** [comment] 2016-02-12 14:23
@martijnwalraven I got rid of my helpers, it's working fine now. Thanks a lot.

**Comment by nate-strauser** [comment] 2016-04-11 14:22
in case anyone is interested, i updated my example for cordova offline files to 1.3

see https://github.com/nate-strauser/meteor-offline-mobile-files-demo

so much simplier with 1.3's built in file serving - thanks @martijnwalraven

**Comment by nickmendes** [comment] 2017-02-27 10:47
**Still facing this issue on Android:** 

> Not allowed to load local resource: content://com.android.contacts/contacts/10

Meteor 1.3.2.4

**Comment by barisro** [comment] 2017-04-23 12:31
+1

**Comment by jeezs** [comment] 2019-12-03 06:27
i'm also hang this issue "Failed to load resource: unsupported URL" using cdvfile://.
But I'm on cordova not Ionic width Safari on MacOS
