### ISSUE TITLE
meteor-developer login fails for android/crosswalk

### ISSUE THREAD

**Issue by interfaith** [meteor/meteor#8053] opened 2016-11-14 22:45 UTC
Any 3rd party service with a callback FAILS with crosswalk.
This  has been tested on 3rd party hosting such as scalingo.io.
Crosswalk works ok by itself as a wrapper.
However crosswalk + meteor fails for the callback.
It may work on occasion, however a simple hello world  example
does fail.
for example
https://github.com/interfaith/twitterlogin
here are logs to show how to add certs if needed for local testing
scalingo.io  is free for demo
and simple for a small app
i could put twitterlogin on scalingo,io for easy testing
as then you just make the apk ? would you prefer that approach ?

**Comment by interfaith** [comment] 2016-11-15 04:18
deviceready has not fired after 5 seconds.
cordova.js:1178 Channel not fired: onDOMContentLoaded
webapp.js:68 Error: Error parsing asset manifest
    at http://localhost:12168/plugins/cordova-plugin-meteor-webapp/www/webapp_local_server.js:36:21
    at Object.callbackFromNative (http://localhost:12168/cordova.js:293:58)
    at processMessage (http://localhost:12168/cordova.js:1081:17)
    at processMessages (http://localhost:12168/cordova.js:1104:9)
    at pollOnce (http://localhost:12168/cordova.js:973:9)
    at pollOnceFromOnlineEvent (http://localhost:12168/cordova.js:960:5)(anonymous function) @ webapp.js:68

**Comment by interfaith** [comment] 2016-11-15 04:20
looks like the bug is finally exposed
amazed that others have no use for android ??

**Comment by interfaith** [comment] 2016-11-15 04:22
invalid redirect URI [400]
yet chrome login is ok  !!
there IS a bug here

**Comment by interfaith** [comment] 2016-11-15 04:32
fyi fyi see https://logintest.scalingo.io

looks like meteor is using the cordova webapp not crosswalk for auth
io

**Comment by interfaith** [comment] 2016-11-15 15:45
it seems  the manifest.json file generated for the apk cannot be parsed.
this is likely the case for ALL 3rd party login services for crosswalk/android
this has been a few MONTHS now that meteor has ignored this bug
luckily the meteor-development login service had code to flag it in the
chrome debugger , where as the other service had no code to show the error.
so ???????????

**Comment by interfaith** [comment] 2016-11-16 15:26
you cannot remove crosswalk -> meteor remove crosswalk
you must remove android then remove crosswalk then add android haha ha
testing android login without crosswalk also fails for meteor-developer
skeleton hello world apps are needed to show what really will and will not work
a simple android app will not allow meteor-developer login  
hello????

**Comment by abernix** [comment] 2016-12-20 20:23
Thanks for the additional information.  This issue is not being ignored and will be investigated but any follow ups on this problem will be through #8097

This will be closed as another duplicate of the same issue.  Please make sure all further updates about this problem go in #8097.

Duplicate of #8080, #8097, #8062, #8036, #7632

**Closed by abernix** 2016-12-20 20:23 UTC
