### ISSUE TITLE
Accounts.onCreateUser not respecting new user validation

### ISSUE THREAD

**Issue by mariusdarila** [meteor/meteor#3924] opened 2015-03-12 15:12 UTC
I have a server side method for account creation using accounts-password:
```
Meteor.methods({
    createUsers: function(options) {
        Accounts.createUser(options);
    }
})
```

I access this method from client side this way:
```
Meteor.call('createUsers', localUser, function(error, result) {
                if (!_.isUndefined(error)) {
                    console.log(error.reason);
                }
            });
```

On server side a have a hook on Accounts.onCreateUser like this:

```
Accounts.onCreateUser(function(options, user) {
    UserProfile.insert({
        user: user._id
    }, function(e) {
        if (e) {
            console.log(e);
        }

    });
    console.log(user);

    return user

})
```

The problem is that when i try to create a new user with the same username, i get the error callback from ```Accounts.createUser``` but on``` Accounts.onCreateUser``` the ```user``` is created O_O. Some logs from Accounts.onCreateUser:

```
I20150312-16:54:25.536(2)?   username: 'aa' }
I20150312-16:54:25.715(2)? { createdAt: Thu Mar 12 2015 16:54:25 GMT+0200 (EET),
I20150312-16:54:25.715(2)?   _id: 'wsdmFnnGerevCSQmD',
I20150312-16:54:25.715(2)?   services: { password: { bcrypt: '$2a$10$yJWaib36S5lRtZrIWvgPFesKrj67yu6t1zvkvff5mZdQ5NHjw..mO' } },
I20150312-16:54:25.715(2)?   username: 'aa' }
I20150312-16:54:25.871(2)? { createdAt: Thu Mar 12 2015 16:54:25 GMT+0200 (EET),
I20150312-16:54:25.871(2)?   _id: 'e4mvc2LHZfL7nE5Fi',
I20150312-16:54:25.871(2)?   services: { password: { bcrypt: '$2a$10$kzj2hwxFqTWIlpojNyeD8uIo3RmOlJbMs5wGiOSBuzOVyfRBYkr.C' } },
I20150312-16:54:25.871(2)?   username: 'aa' }
I20150312-16:54:26.014(2)? { createdAt: Thu Mar 12 2015 16:54:26 GMT+0200 (EET),
I20150312-16:54:26.014(2)?   _id: 'CDYq6rgNqmKdHfsxw',
I20150312-16:54:26.015(2)?   services: { password: { bcrypt: '$2a$10$J3r/.47GzSsehwq7vJjzU.s9lBip/Eddonh05BcNaNM6SaQwdPya.' } },
I20150312-16:54:26.015(2)?   username: 'aa' }
```

### When i check in db the user does not exist but the profile gets created. It seems like the user gets created no matter what and then it gets deleted.
This is my versions file:

```
accounts-base@1.1.3
accounts-password@1.0.6
alanning:package-stubber@0.0.9
alanning:roles@1.2.13
aldeed:collection2@2.3.2
aldeed:simple-schema@1.3.0
amplify@1.0.0
application-configuration@1.0.4
autoupdate@1.1.5
base64@1.0.2
binary-heap@1.0.2
blaze@2.0.4
blaze-tools@1.0.2
boilerplate-generator@1.0.2
callback-hook@1.0.2
check@1.0.4
coffeescript@1.0.5
dburles:collection-helpers@1.0.2
ddp@1.0.14
deps@1.0.6
ejson@1.0.5
email@1.0.5
fastclick@1.0.2
follower-livedata@1.0.3
geojson-utils@1.0.2
html-tools@1.0.3
htmljs@1.0.3
http@1.0.10
id-map@1.0.2
iron:controller@1.0.7
iron:core@1.0.7
iron:dynamic-template@1.0.7
iron:layout@1.0.7
iron:location@1.0.7
iron:middleware-stack@1.0.7
iron:router@1.0.7
iron:url@1.0.7
jquery@1.11.3
json@1.0.2
launch-screen@1.0.1
less@1.0.12
livedata@1.0.12
localstorage@1.0.2
logging@1.0.6
meteor@1.1.4
meteor-platform@1.2.1
minifiers@1.1.3
minimongo@1.0.6
mobile-status-bar@1.0.2
mongo@1.0.11
npm-bcrypt@0.7.7
observe-sequence@1.0.4
ordered-dict@1.0.2
pcel:loading@1.0.3
pfafman:font-awesome-4@4.3.0
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
raix:handlebar-helpers@0.2.4
random@1.0.2
reactive-dict@1.0.5
reactive-var@1.0.4
reload@1.1.2
retry@1.0.2
routepolicy@1.0.4
sanjo:jasmine@0.12.4
sanjo:karma@1.4.1
service-configuration@1.0.3
session@1.0.5
sha@1.0.2
spacebars@1.0.5
spacebars-compiler@1.0.4
srp@1.0.2
templating@1.0.11
tracker@1.0.5
twbs:bootstrap@3.3.2
ui@1.0.5
underscore@1.0.2
url@1.0.3
velocity:core@0.4.5
velocity:html-reporter@0.4.2
velocity:meteor-stubs@1.0.0_2
velocity:node-soft-mirror@0.3.1
velocity:shim@0.1.0
velocity:test-proxy@0.0.4
webapp@1.1.6
webapp-hashing@1.0.2
wizonesolutions:underscore-string@1.0.0
zimme:iron-router-active@1.0.1
```

**Comment by glasser** [comment] 2015-03-17 21:18
This is working as intended. `onCreateUser` is supposed to return a doc that will be inserted afterwards.  If you write arbitrary code with side effects, there's no way for the create-user code to magically reverse it on error.  Nothing in the [docs](http://docs.meteor.com/#/full/accounts_oncreateuser) suggest that it's a good idea to put side effects in your onCreateUser callback.

(By the way, while I appreciate that you provided slightly more context for your bug report than the absolute minimum, please read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which describes a better way of showing context for your bug report.)

**Closed by glasser** 2015-03-17 21:18 UTC

**Comment by mariusdarila** [comment] 2015-03-18 10:01
Thanks for explanation, i worked most of my time with django and I saw this like a post save signal :) (my bad).

**Comment by townmulti** [comment] 2015-03-18 21:49
@mariusdarila this question was helpful to me. I understand you are trying to save off the _id to another associated collection directly upon account creation. I am wanting to do the same thing :-) did you find a better solution to grab the _id?

**Comment by mariusdarila** [comment] 2015-03-19 08:34
@townmulti i will use this http://docs.mongodb.org/manual/reference/method/db.collection.findAndModify/  with ```upsert:true``` when i grab the user profile.

**Comment by evolross** [comment] 2015-10-08 19:41
I just ran into this same problem too.  It seemed like `onCreateUser` was a good place to put "success" side effects.  I see now that it's not.  Thanks for the explanation @glasser .
