### ISSUE TITLE
[Meteor 3] Node version is still pinned to v14 instead of v20

### ISSUE THREAD

**Issue by jamauro** [meteor/meteor#12913] opened 2023-12-06 03:28 UTC
I created a new meteor app with 

1. `meteor create --svelte [name]`
2. `meteor update --release 3.0-alpha.19`

When I run `meteor node --version`, I get `v14.21.4`. I expected that it would be `v20.x.x`

How can I resolve this? I want to experiment with an npm package but it requires v18+

**Comment by fredmaiaarantes** [comment] 2023-12-06 06:43
Hey @jamauro, are you running `meteor node --version` inside your project folder? If so, you should see `v20.9.0`.

If you run this command outside of your project, it will take the global Meteor installation, and I think that as Meteor `3.0` is still in alpha, it will use the latest official version, which is `2.13.3` and uses Node.js `v14.21.4`. Take a look at the screenshot below:

<img width="686" alt="Screenshot 2023-12-06 at 03 33 49" src="https://github.com/meteor/meteor/assets/559305/6cad8505-e04d-4e12-91ac-2e3d1ca2efb9">

So, I believe if you install the package you want to test by running `meteor npm i <package_name>` inside your project, it should work.

**Comment by jamauro** [comment] 2023-12-06 15:29
Hey @fredmaiaarantes, appreciate you taking a look. Here's what I see
<img width="226" alt="Screenshot 2023-12-06 at 9 27 32 AM" src="https://github.com/meteor/meteor/assets/1749828/1ed53ec7-d760-43b9-a7a1-e81ec71a4cbe">

Any ideas?

**Comment by Grubba27** [comment] 2023-12-06 17:45
I was able to reproduce your error.

Before going to the solution, you can see that your project does use the latest node version by running `process.versions` in your `Meteor.startup` for example.

## Solution
It is something with the global version of your meteor.

<img width="798" alt="Screenshot 2023-12-06 at 14 34 18" src="https://github.com/meteor/meteor/assets/70247653/d6c05166-af7a-4124-9654-9d89abb1f67a">

I ran with `curl` and got it globally.
<img width="893" alt="Screenshot 2023-12-06 at 14 41 08" src="https://github.com/meteor/meteor/assets/70247653/06376a75-40f9-48ee-a7a7-b60214241db3">


Note that you do not need to have it globally to use the node version.

**Comment by jamauro** [comment] 2023-12-06 19:35
Thanks Gabriel! I was able to see `node: 20.9.0` when console logging `process.versions`

Currently, when I run `meteor npm i` from the project folder I see this warning:
![Screenshot 2023-12-06 at 12 55 22 PM](https://github.com/meteor/meteor/assets/1749828/16901bb4-d30a-429e-87d6-59faa3822b1e)

Maybe I can just ignore it but I'm not sure :)

@fredmaiaarantes I'd like to be able to replicate how you have things set up. Any tips? It appears that whenever I use the `meteor` command it's using the global meteor install even when I'm inside the project folder. I'd prefer not to have multiple meteor versions installed on my machine that I need to switch between but if that's the only way then that would be good to know. I'm not sure if it's relevant but I'm using the Apple M silicon.

**Comment by paulincai** [comment] 2023-12-07 13:45
@jamauro 

2 projects side by side showing correct Node versions as per the respective Meteor versions.
Any chance you might have an old engines configuration in package.json?!

```
 "engines": {
    "node": "14.21.4",
    "npm": "6.14.17"
 },
```


![Screenshot 2023-12-07 at 5 42 38 PM](https://github.com/meteor/meteor/assets/26188915/07a98075-a51a-4238-a26f-30cea8a6dcd4)

**Comment by jamauro** [comment] 2023-12-07 16:09
@paulincai appreciate you taking a look. Unfortunately, I couldn't find anything in my project where  the node engine is set to v14. 

Is your Mac using a M chip? If so, then I can rule out that theory. Gabriel mentioned to me that he has the same issue I have and thought maybe it has something to do with M chips vs Intel chips in the way Meteor is installed.

**Comment by fredmaiaarantes** [comment] 2023-12-11 14:34
> Thanks Gabriel! I was able to see `node: 20.9.0` when console logging `process.versions`
> 
> Currently, when I run `meteor npm i` from the project folder I see this warning:
> 
> ![Screenshot 2023-12-06 at 12 55 22 PM](https://private-user-images.githubusercontent.com/1749828/288524941-16901bb4-d30a-429e-87d6-59faa3822b1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDI2NDMsIm5iZiI6MTcwMjMwMjM0MywicGF0aCI6Ii8xNzQ5ODI4LzI4ODUyNDk0MS0xNjkwMWJiNC1kMzBhLTQyOWUtODdkNi01OWZhYTM4MjJiMWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMTM0NTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTViZWQ0MThiMjE4NDVjZmEyNGQ2NWUyMzZjMWRiZGFlZGY4MmQxOWE3OWUwNGQ0MWU2NDBlZTBjZTQyZTdiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pM16KyaIHMycSVIO3fmoBRxSMVc-m-xDNQtvUfH1CHQ)
> 
> Maybe I can just ignore it but I'm not sure :)
> 
> @fredmaiaarantes I'd like to be able to replicate how you have things set up. Any tips? It appears that whenever I use the `meteor` command it's using the global meteor install even when I'm inside the project folder. I'd prefer not to have multiple meteor versions installed on my machine that I need to switch between but if that's the only way then that would be good to know. I'm not sure if it's relevant but I'm using Apple M silicon.

I'm using Mac Intel, and I don't remember doing anything special to make it work, @jamauro.

Did you try installing using curl as @Grubba27 suggested?

`curl https://install.meteor.com/\?release\=3.0-alpha.19 | sh`

**Comment by jamauro** [comment] 2023-12-13 16:04
> Did you try installing using curl as @Grubba27 suggested?
> 
> 
> 
> `curl https://install.meteor.com/\?release\=3.0-alpha.19 | sh`

If 3.0 is the globally installed version, then it shouldn't affect my existing 2.x apps right? I assume they'll still use the Node version that's tied to the 2.x release. 

I will likely experiment more over the holidays.

**Comment by zodern** [comment] 2023-12-20 18:18
I'm not able to reproduce at the moment, but I've seen the same bug in the past. It probably is a bug in Meteor 2 in the springboarding (switching from the global Meteor version to the version used by the app) where it is for some reason deciding to use the global version: https://github.com/meteor/meteor/blob/1a8905ac8c39519d8ab2a38edaca7767566aa76c/tools/cli/main.js#L933-L1178

**Comment by denihs** [comment] 2024-07-23 16:54
This should already be fixed by now. If not we can reopen this issue.

**Closed by denihs** 2024-07-23 16:54 UTC
Labels: Type:Bug
