### ISSUE TITLE
Infinite loop when manipulating large DOM set

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#3979] opened 2015-03-20 14:00 UTC
The issue is **best viewed with Chrome**.
### Code

Here is the repo: https://github.com/steph643/meteor-issue-3979/

Consider the following code, where `MyCollection` contains **1000 pairs of numbers [v1,v2]**. There are two publish functions, one to publish only v1, the other one to publish only v2:

``` html
<head>
</head>

<body>
    <h2>Infinite loop when manipulating large DOM set</h2>
    <p>
        <button id="v1">Publish v1</button>
        <button id="v2">Publish v2</button>
    </p>
    <p>myCollection:</p>
    <p>
        {{#each getValues}}
            <!-- You can remove the line below, the issue is still there! -->
            <div>{{v1}}, {{v2}}</div>
        {{/each}}
    </p>
</body>
```

``` javascript
MyCollection = new Meteor.Collection('myCollection');

if (Meteor.isServer) {

    MyCollection.remove({});
    for (var i=0; i<10000; ++i)
        MyCollection.insert({ v1: i, v2: i });

    Meteor.publish('myCollectionV1', function() { return MyCollection.find({}, { fields: { v1: 1 } }); });
    Meteor.publish('myCollectionV2', function() { return MyCollection.find({}, { fields: { v2: 1 } }); });
}

if (Meteor.isClient) {

    Template.body.helpers({
        getValues: function() { return MyCollection.find(); }
    });

    Template.body.events({
        'click #v1': function(event, template) { Meteor.subscribe('myCollectionV1'); },
        'click #v2': function(event, template) { Meteor.subscribe('myCollectionV2'); }
    });

    MyCollection.find().observeChanges({
        added:   function(id, doc)    { console.log('Added');   },
        changed: function(id, fields) { console.log('Changed'); },
        removed: function(id)         { console.log('Removed'); }
    });
}
```
### Normal Behavior

No data is initially published.
1. Press the "Publish v1" button -> 1000 values for v1 are published. The console shows `1000 Added`.
2. Press the "Publish v2" button -> 1000 values for v2 are published. The console shows `1000 Changed`.

So the final console log is:

```
1000 Added
1000 Changed
```
### Infinite reload

**In the above code, replace 1000 by 10000** and relaunch the application.

No data is initially published.
1. Press the "Publish v1" button -> 10000 values for v1 are published. The console shows `10000 Added`.
2. Press the "Publish v2" button -> 10000 values for v2 are published. The console starts showing the "Changed" event. **However**, after a variable amount of changes, there is a pause (pause length is variable also), then more changes start coming. Then another pause, then more changes. Etc.

After a few minutes, the log is like this and it keeps going:

```
Added
7174 Changed
sockjs-0.3.4.js:854 XHR finished loading: GET "http://localhost:3000/sockjs/info?cb=_d2ky6pxsm".
7174 Changed
8053 Changed
sockjs-0.3.4.js:854 XHR finished loading: GET "http://localhost:3000/sockjs/info?cb=x9s0s32he5".
8053 Changed
5406 Changed
sockjs-0.3.4.js:854 XHR finished loading: GET "http://localhost:3000/sockjs/info?cb=bve2awkkzh".
5406 Changed
7174 Changed
sockjs-0.3.4.js:854 XHR finished loading: GET "http://localhost:3000/sockjs/info?cb=vtuhv9rz4a".
7174 Changed
...
```

**Comment by steph643** [comment] 2015-03-20 14:46
This seems to relate to Blaze. Indeed, the issue remains if you remove `<div>{{v1}}, {{v2}}</div>` from the html, but not if you remove the `{{#each getValues}}` loop.

**Comment by steph643** [comment] 2015-03-20 14:48
Might be related to issue https://github.com/meteor/meteor/issues/3978
Might be related to issue https://github.com/meteor/meteor/issues/3976

**Comment by steph643** [comment] 2015-03-20 14:56
Here is the repo: https://github.com/steph643/meteor-issue-3979/

**Comment by dgreensp** [comment] 2015-03-31 22:43
Just to get this out of the way up front:  Our overall performance definitely needs some work when it comes to receiving data over the network, storing it in Minimongo, pulling it out, and rendering it via Blaze.

I was not able to reproduce this in Chrome; I get the correct behavior.

For anyone playing around with this, one thing to note is that `console.log` is fairly slow, and in cases like this can dominate the running time (even though the console nicely abbreviates the tens of thousands of messages).  Browser layout time also starts to become significant at the scale of tens of thousands of nodes, but I believe it is dwarfed by Blaze CPU in this case.

I'm untagging this as Blaze and retagging as DDP since this is almost certainly some kind of race condition that occurs when Blaze is hogging the CPU.

**Comment by haunguyen90** [comment] 2015-10-27 08:23
Can someone tell me the solution for this issue ?

**Comment by steph643** [comment] 2015-10-27 08:32
You should never display data which reactively depends on a large subscription. This leads to disastrous slow down and bugs like this one. The solution is to:
 1. stop data display (show a spinner instead)
 2. subscribe
 3. wait for the subscription to be ready
 4. turn data display back on

**Comment by haunguyen90** [comment] 2015-10-27 08:53
@steph643 
```javascript
{{#if subscriptionIsReady}}
   {{#each data}}
      <div>{{dataName}}</div>
   {{/each}}
{{else}}
   <div>Loading.... Spinner</div>
{{/if}}
```
Like that ?
If you do like that, so when you scroll down and subscribe new data, the old data (which are rendered) will be hidden

**Comment by steph643** [comment] 2015-10-27 09:30
You are right.
There are more advanced solutions for various use cases. If what you want to achieve is "infinite scrolling", you might find a dedicated package on Atmosphere. You might also want to check [aldeed:tabular](https://github.com/aldeed/meteor-tabular).

**Comment by hwillson** [comment] 2017-01-16 13:53
As mentioned in https://github.com/meteor/meteor/issues/3979#issuecomment-88275138, this issue is not reproducible by others trying the supplied reproduction, which points towards a fairly random race condition of some kind happening somewhere. Since this could be quite difficult to pinpoint, and it's not happening for others who try the repro (and due to the age / low interest of this issue), I'll close this off. Thanks for originally reporting this issue!

**Closed by hwillson** 2017-01-16 13:53 UTC
Labels: Project:DDP
