### ISSUE TITLE
Support bash install on windows

### ISSUE THREAD

**Issue by justinmchase** [meteor/meteor#5322] opened 2015-09-29 13:40 UTC
When working with node on windows I pretty much just use bash through git bash. Looking at your scripts I don't see any reason why they wouldn't work as is on windows except for the fact that the scripts explicitly block windows and the corresponding windows .tar.gz files don't appear to be uploaded to the same spots.

Also after installation on windows via installer you seem to be omitting the bash version of the meteor script which makes it unusable via bash. I guess I am just saying that if you tell people to get git bash (most probably already have it) then it may just work nearly the same as the other two platforms. 

Is there another known blocking issue? I would be willing to make a PR if I knew the url to the .tar.gz files.

**Comment by lukeadams** [comment] 2015-09-29 18:20
[This](https://github.com/meteor/meteor/blob/devel/meteor) is the file in question.
The script uses uname to identify platform. `uname`: Git bash returns `MINGW32_NT-6.2` while Cygwin returns `CYGWIN_NT-10.0`, so that would need to be accounted for. Also `uname -s` returns unknown on both, while `uname -m` returns `i686` and `x86_64`, respectively.

My only worry would be maintaining two different install paths (InstallMeteor.exe + CLI), but otherwise I think this is a good idea. I prefer CLI. Maybe we could get that working and make the windows installer wrap the CLI install?

**Comment by stubailo** [comment] 2015-09-29 23:26
Duplicate of: #4938

**Closed by stubailo** 2015-09-29 23:26 UTC

**Comment by justinmchase** [comment] 2016-08-02 03:44
By the way the issue linked to above isn't actually the same as what I was saying.

Also you can make this work by  installing, beside `meteor.bat`, a file called `meteor` with the following code:
```
#!/bin/bash

if [ -z $1 ]; then
    ARG="C:\\Users\\justin\\AppData\\Local\\.meteor\\meteor.bat"
else
    ARG="C:\\Users\\justin\\AppData\\Local\\.meteor\\meteor.bat $*"
fi

cmd "/c $ARG"
```

Where the path in the file is the path to your meteor.bat file.

**Comment by jirikrepl** [comment] 2017-04-30 09:17
Maybe this is another workaround.
On Windows with msygit installed I could use Meteor in bash script if I call `meteor.bat`

    #!/bin/bash
    ....
    # It is a deploy script 
    meteor.bat deploy ${APP_HOSTNAME} --settings settings.json

Then I call it:

    C:> bash deploy.sh

**Comment by Zenoo** [comment] 2025-02-01 15:24
> By the way the issue linked to above isn't actually the same as what I was saying.
> 
> Also you can make this work by installing, beside `meteor.bat`, a file called `meteor` with the following code:
> 
> ```
> #!/bin/bash
> 
> if [ -z $1 ]; then
>     ARG="C:\\Users\\justin\\AppData\\Local\\.meteor\\meteor.bat"
> else
>     ARG="C:\\Users\\justin\\AppData\\Local\\.meteor\\meteor.bat $*"
> fi
> 
> cmd "/c $ARG"
> ```
> 
> Where the path in the file is the path to your meteor.bat file.

I had to use this hack to actually be able to use the meteor cli on Windows using Git Bash.
It's kinda crazy it doesn't work out of the box in 2025.
