### ISSUE TITLE
Netstat -ano

### ISSUE THREAD

**Issue by damiantje99** [meteor/meteor#4382] opened 2015-05-13 20:17 UTC
I found a problem with meteor when you try to use it with the PlexRequest App.

Problem and solution can be found in the following issue:

lokenx/plexrequests-meteor#65

**Comment by Slava** [comment] 2015-05-19 20:47
It was fixed on devel. This issue is a duplicate of a previous issue: https://github.com/meteor/meteor/issues/4125

**Closed by Slava** 2015-05-19 20:47 UTC
