### ISSUE TITLE
Document cordova-plugin-crosswalk-webview configuration options

### ISSUE THREAD

**Issue by adaptabi** [meteor/meteor#5669] opened 2015-11-17 03:23 UTC
```
cordova plugin add cordova-plugin-crosswalk-webview  --variable XWALK_MODE="shared"
```

How do I specify the `--variable` arguments when

```
meteor add cordova:cordova-plugin-crosswalk-webview 
```

Also there is an atmosphere package called [`crosswalk`](https://atmospherejs.com/meteor/crosswalk) however its documentation is missing, especially of how you can make use of `share` mode

**Comment by martijnwalraven** [comment] 2015-11-17 11:43
From the [configuration options for the Crosswalk plugin](https://www.npmjs.com/package/cordova-plugin-crosswalk-webview#configure) it seems specifying `xwalkMode` should work here.

I haven't tested this, but I believe something like this should work:

```
App.configurePlugin('cordova-plugin-crosswalk-webview', {
  xwalkMode: 'shared'
});
```

The `crosswalk` package has no documentation because it is just a wrapper around the `cordova-plugin-crosswalk-webview` plugin and it adds no behavior of its own. But you're right, we should document how to use these configuration settings somewhere.

**Comment by dotnetwise** [comment] 2015-11-17 12:08
Presumebly this should be in the `mobile-config.js` ?
I have tried with 
```js
App.setPreference('xwalkMode', 'shared');
App.setPreference('xwalkVersion', 'xwalk_core_library:14+');
```

And it seems to be working, I can see preferences being applied in `AndroidManifest.xml`
```xml
<preference name="xwalkMode" value="shared" />
<preference name="xwalkVersion" value="xwalk_core_library:14+" />
```

However, the problem is when using `crosswalk` in `shared` mode the other plugins such as `com.mirasense.scanditsdk.plugin` could not be `found`. But that's a separate issue, non-meteor related.

**Comment by rjakobsson** [comment] 2016-10-30 21:56
As this is now documented, I believe this issue could be closed. 

From the Meteor 1.3.2 documentation:
```
// Pass preferences for a particular PhoneGap/Cordova plugin
App.configurePlugin('com.phonegap.plugins.facebookconnect', {
  APP_ID: '1234567890',
  API_KEY: 'supersecretapikey'
});
```

**Comment by abernix** [comment] 2016-11-08 15:14
Thanks, @rjakobsson.

For anyone looking for the current location that this is documented, it can be found here:

https://docs.meteor.com/api/mobile-config.html#App-configurePlugin

Closing.  Thanks for originally reporting this under-documented aspect of Meteor, @adaptabi.

**Closed by abernix** 2016-11-08 15:14 UTC
Labels: Project:Docs, Project:Mobile
