### ISSUE TITLE
Infinite update process to version 1.4 under Windows

### ISSUE THREAD

**Issue by olexandrbig** [meteor/meteor#7503] opened 2016-07-27 14:37 UTC
### On meteor update from  1.3.5.1 to 1.4 under windows
`
meteor update --release 1.4
`
`
   Downloading meteor-tool@1.4.0...          [========          ] 42% 39.4s
`
then
`
   Downloading meteor-tool@1.4.0...          /
`
and process become infinite, tested 2 times with 1 hour per each

### System 
- Windows 7 Ultimate x64
- Installed the [MS Build Tools](https://www.microsoft.com/en-us/download/details.aspx?id=48159).
- Packages:

> 
underscore@1.0.9
iron:router
accounts-password@1.2.12
email@1.1.16
alanning:roles
meteorhacks:search-source
accounts-github@1.0.10
aldeed:simple-schema
momentjs:moment
aldeed:autoform
fortawesome:fontawesome
twbs:bootstrap-noglyph
mizzao:bootboxjs
spiderable@1.0.13
reywood:iron-router-ga
less@2.7.4
zimme:active-route
natestrauser:animate-css
okgrow:router-autoscroll
kevohagan:sweetalert
chrismbeckett:toastr
monbro:iron-router-breadcrumb
meteor-base@1.0.4
mobile-experience@1.0.4
mongo@1.1.10
blaze-html-templates@1.0.4
session@1.1.6
jquery@1.11.9
tracker@1.1.0
logging@1.1.14
reload@1.1.10
random@1.0.10
ejson@1.0.12
spacebars@1.0.12
check@1.2.3
ecmascript@0.5.7
es5-shim@4.6.13
djedi:sanitize-html
meteorhacks:kadira
standard-minifier-css@1.1.8
standard-minifier-js@1.1.8
kaso:bootstrap-treeview
muqube:autoform-nouislider
practicalmeteor:mocha
practicalmeteor:sinon
hwillson:stub-collections
my:force-ssl

**Comment by brucejo75** [comment] 2016-07-28 06:14
Try running it for much longer (e.g. overnight.)  This issue has plagued windows meteor installations for a while.  See:
https://forums.meteor.com/t/very-long-wait-times-downloading-meteor-tools-on-update/24440/11
https://forums.meteor.com/t/problem-downloading-meteor-1-3-5-1/26759

My experience is that this comes and goes.  It has affected me in only one update.

One thing I noticed was that my CPU worked very hard during these installs and the culprit was the "Antimalware Service Executable" aka "Windows Defender Service".  As each file is extracted from the tarball the antimalware filter kicks in and analyzes the new files which bogs down the CPU.

**Comment by tmeasday** [comment] 2016-07-29 02:52
Hopefully this situation will be much improved soon: https://github.com/meteor/meteor/pull/7457

**Comment by abernix** [comment] 2016-08-01 13:17
Duplicate of #7283 (and many others).  Closing and hopefully #7457 will solve this soon.  Meanwhile, a fresh reinstall frequently helps:

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.
* Install fresh 1.3.4.1 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

**Closed by abernix** 2016-08-01 13:17 UTC

**Comment by olexandrbig** [comment] 2016-08-05 20:44
Hello @abernix , your comment doesn't help me
Solution that works for me:
* update your nodejs to v4.4.7
 - nvm is recommended
* as admin : npm install --global --production windows-build-tools
* as normal user : meteor npm install bcrypt
* meteor update
