### ISSUE TITLE
Meteor 1.2rc7 - Status bar hidden on meteor app (android) after add angular package

### ISSUE THREAD

**Issue by adrianolsk** [meteor/meteor#5098] opened 2015-09-03 22:40 UTC
I found something strange when I added the angular package
```js
meteor add angular
```

The angular integration worked but as soon as I added the package the status bar on my mobile app that was connected disappeared, it kinda went full screen at the top, when I remove angular and run the app again on the device the status bar show up again. But when I add the urigo:angular the status bar is there. I know it's not a blocking issue, but I think I should post it anyway

#### with the angular package from meteor 1.2rc7: no status bar

![angular](https://cloud.githubusercontent.com/assets/4512482/9672967/cd269e6e-5275-11e5-8706-a46628275a4f.png)

#### with the urigo:angular package the app have a status bar 

![urigo-angular](https://cloud.githubusercontent.com/assets/4512482/9672957/b08568ee-5275-11e5-8285-60537b2e53df.png)

it's  really strange not be able to see the clock and everything up there.
I tested on a device and emulator and got the same results

**Comment by martijnwalraven** [comment] 2015-09-04 04:47
@Urigo Do you have any idea what could be causing this?

**Comment by Urigo** [comment] 2015-09-04 12:14
@adrianolsk are you using the `meteor-include` directive?

If so, the problem is not in `angular` but in the new release of angular-meteor (it will probably happen to you also in `urigo;angular@0.10.2` )
It's because I've separated this functionality to a separate package with new syntax:
https://github.com/Urigo/angular-blaze-template
http://angular-meteor.com/api/blaze-template

Please let me know if the new syntax worked for you

**Comment by Urigo** [comment] 2015-09-04 12:25
also please share you `.versions` file as well

**Comment by adrianolsk** [comment] 2015-09-04 17:43
@Urigo I shared my code on
https://github.com/adrianolsk/SampleIssue

I got the same problem with the ``` urigo:angular@0.10.2 ```
I am using ng-include.

**Comment by martijnwalraven** [comment] 2015-09-06 07:45
I'm not sure I understand this issue correctly, because for me there is no difference between adding the `urigo:angular` or `angular` packages. Neither displays a status bar, and I think this is the expected default behavior. You can set other status bar preferences in your `mobile-config.js`:
```javascript
App.setPreference('StatusBarOverlaysWebView', 'false');
App.setPreference('StatusBarBackgroundColor', '#000000');
```

Could you elaborate on why RC12 is not running the app on a device for you?

**Comment by adrianolsk** [comment] 2015-09-08 22:24
It didn't work with the settings in mobile-config.js either.
If you run the app on emulator after create with the RC7, the status bar is there, as soon as you add the angular package the status bar is gone.

I got this error when I try to run on mobile using rc12

```
=> Errors executing Cordova commands:         
                                              
   While listing platform versions in Cordova project:
   Error: Command failed: /home/adriano/Documentos/Projetos/sample2/.meteor/local/cordova-build/platforms/android/cordova/version 
   /usr/bin/env: node: Arquivo ou diretório não encontrado
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at maybeClose (child_process.js:766:16)
   at Socket.<anonymous> (child_process.js:979:11)
   at Socket.emit (events.js:95:17)
   at Pipe.close (net.js:466:12)
```

**Comment by martijnwalraven** [comment] 2015-09-09 09:59
Thanks for the bug report about the 1.2 upgrade. Fixed in 95627b3badd4d7925c08a15977cfa46e94380f0b, so should make it into the next RC.

I haven't been able to reproduce the issue with the status bar. @Urigo?

**Comment by Urigo** [comment] 2015-09-09 16:00
Sorry, I've tried as well and it didn't happen to me..

@adrianolsk does it do the same thing with iOS?

**Comment by adrianolsk** [comment] 2015-09-09 20:54
It´s happening on ios device as well after upgrade to rc7 and add angular (using osx of a friend)
on android I was using Linux

![img-20150909-wa0003](https://cloud.githubusercontent.com/assets/4512482/9773807/04fabc2c-571b-11e5-9c14-701a892f1e45.jpg)

**Comment by stubailo** [comment] 2015-09-14 21:48
We can't reproduce this issue right now, any more information you have would be helpful.

Are you able to get a different computer and try it there?

**Comment by stubailo** [comment] 2015-09-15 18:38
Going to close this since we can't figure out how to fix it. Hopefully someone else will come along and we can figure out some reasons for why it happens.

**Comment by rjakobsson** [comment] 2015-09-16 15:25
We're having white status bar irregularly on METEOR@1.2-rc.15 , using Nexus 5, running android 5.1.1.

**Comment by rjakobsson** [comment] 2015-09-16 19:00
I dont think this is related to angular, we dont use it at all.

**Comment by martijnwalraven** [comment] 2015-09-16 19:38
Anything else you can tell me about the circumstances under which this seems to happen?

**Comment by martijnwalraven** [comment] 2015-09-16 20:25
Figured it out, it is a timing issue related to when the status bar plugin has been loaded. Working on a fix.

**Closed** 2015-09-16 20:57 UTC
Labels: confirmed, Project:Mobile

**Comment by stubailo** [comment] 2015-09-17 18:49
The fix is out now in RC 16!
