### ISSUE TITLE
[idea] Add a Template.onBeforeDestroyed hook.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4951] opened 2015-08-13 02:51 UTC
This would be convenient in order to clean things up that may have references to the DOM that is inside of a template (React, Famous, and other libraries that store internal references to DOM elements).

**Comment by stubailo** [comment] 2015-08-25 21:48
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Sounds like a good idea, I'd look at a PR for this.

**Comment by mitar** [comment] 2015-10-15 01:51
Blaze Components have [low-level DOM manipulation hooks](https://github.com/peerlibrary/meteor-blaze-components#low-level-dom-manipulation-hooks) which you can hook into and know when particular DOM element is being removed.

Because in your case I am unsure if you need really `onBeforeDestroyed` (which means that the whole template is being removed), or when any DOM element is being removed. If you store references to DOM elements, then the latter is probably what you want.

Can you give an example of `onBeforeDestroyed` use? A more concrete one? Because why do you need DOM to still exist in the DOM tree to be able to remove a reference to it?

Also, from looking at the code, it looks like [onDestroyed callbacks are called before DOM is really removed](https://github.com/meteor/meteor/blob/devel/packages/blaze/view.js#L492).

Alternatively, you can look into `Blaze._DOMBackend.Teardown.onElementTeardown` method.

**Comment by mitar** [comment] 2015-10-15 02:34
I think this is a duplicate of #2141, BTW.

**Comment by trusktr** [comment] 2015-10-15 04:56
Yep, that's a duplicate.

**Comment by trusktr** [comment] 2015-10-15 05:02
An example would be to unmount a react component before the Blaze component gets destroyed. I think the problem I was running into may have been that I could no longer get a reference to the template's DOM in the `onDestroyed` handler. I might be mistaken, but I don't feel like digging up the code at the moment.

Just try rendering a React component inside a Blaze template, then you should run into the problem when you try to clean it up (or perhaps I missed something that isn't well-documented at docs.meteor.com).

**Comment by stubailo** [comment] 2015-10-15 05:03
Duplicate for sure!

@trusktr did you use the helper from here? http://react-in-meteor.readthedocs.org/en/latest/react-template-helper/

**Closed by stubailo** 2015-10-15 05:03 UTC
Labels: feature, Project:Blaze, pull-requests-encouraged
