### ISSUE TITLE
Error 'meteorInstall' on IE and Safari

### ISSUE THREAD

**Issue by LeG3nDz** [meteor/meteor#7578] opened 2016-08-04 09:35 UTC
Hi community,

When i start my Meteor APP with `meteor --settings settings.json`, i've error JS on IE and Safari :

> Unable to get the property 'meteorInstall' a null reference or undefined

At this line :

`var meteorInstall = Package.modules.meteorInstall;`

### Versions

Meteor : 1.4
Node : 4.4.7

### My packages

insecure@1.0.7
iron:router
accounts-password@1.2.12
email@1.1.16
check@1.2.3
markdown@1.0.10
meteorhacks:ssr
aldeed:template-extension
autopublish@1.0.7
edgee:slingshot
leg3ndz:highlight.js
gadicohen:sitemaps
raix:handlebar-helpers
manuelschoebel:ms-seo

Do you have any idea for fix this problem ?

Thank you !

**Comment by abernix** [comment] 2016-08-04 11:26
I am not experiencing the problem you're referring to on Meteor 1.4 with Safari.  It sounds like the problem is possibly due to an error elsewhere in your code.

Could you please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple example as possible) and upload that project to GitHub?  Then, simply include the link to it and it will be easy for any developer to clone and see the same problem you're having and decide if it's a problem with your code, or a problem with Meteor itself.

Someone will be much more able to help you if you include this. Unfortunately, without providing a reproduction repository, it's very difficult to investigate further.

**Comment by LeG3nDz** [comment] 2016-08-05 13:19
Hi @abernix 

I've test with --production, and error disappears.

I think i can close this, certainly code SS6 not compile without --production ?

**Comment by abernix** [comment] 2016-09-13 11:27
I'm not entirely sure what you mean since the `--production` flag certainly shouldn't change whether your project is working or not.  I'm going to close this as you haven't provided a reproduction, but if you can reproduce the problem in a project repo that someone can look at this can certainly be re-opened.

**Closed by abernix** 2016-09-13 11:27 UTC
Labels: can't-reproduce
