### ISSUE TITLE
Windows EPERM symlink problems persist in test mode

### ISSUE THREAD

**Issue by leosco** [meteor/meteor#8091] opened 2016-11-22 16:49 UTC
This may have been [fixed](https://github.com/meteor/meteor/issues/7374) for Meteor 1.4 in normal development operation, but I'm still having the issue whenever I run `meteor test`. Does the fix account for building the project in test mode as well? I'm running Meteor 1.4.2.3

Here's the full command and output:
```
meteor npm test
> meteor test --full-app --driver-package practicalmeteor:mocha --port 5000

C:\Users\lscordilis\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: EPERM: operation not permitted, symlink 'C:\Users\lscordilis\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\' -> 'C:\Users\LSCORD~1\AppData\Local\Temp\meteor-test-run1defvtc\.meteor\local\build\programs\server\node_modules'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at Object.wrapper (C:\tools\fs\files.js:1535:35)
    at Object.files.cp_r (C:\tools\fs\files.js:501:11)
    at C:\tools\fs\files.js:488:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at C:\tools\fs\files.js:488:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at C:\tools\fs\files.js:488:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at copyDirIntoTestRunnerApp (C:\tools\cli\commands.js:1692:15)
    at doTestCommand (C:\tools\cli\commands.js:1698:5)
    at Command.func (C:\tools\cli\commands.js:1533:10)
    at C:\tools\cli\main.js:1483:23
npm ERR! Test failed.  See above for more details.

```

**Comment by blueknightone** [comment] 2016-11-23 01:46
I am having the same issue after updating to 1.4.2.3:
````
meteor test --driver-package practicalmeteor:mocha --port 3100                                                                                                                                              C:\Users\Justin\AppDa
ta\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: EPERM: operation not permitted, symlink 'C:\Users\Justin\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\' -> 'C:\Users\Justin\AppData\Local\Temp\meteor-test-run
1r1p2bg\.meteor\local\build\programs\server\node_modules'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at Object.wrapper (C:\tools\fs\files.js:1535:35)
    at Object.files.cp_r (C:\tools\fs\files.js:501:11)
    at C:\tools\fs\files.js:488:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at C:\tools\fs\files.js:488:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at C:\tools\fs\files.js:488:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at copyDirIntoTestRunnerApp (C:\tools\cli\commands.js:1692:15)
    at doTestCommand (C:\tools\cli\commands.js:1698:5)
    at Command.func (C:\tools\cli\commands.js:1533:10)
    at C:\tools\cli\main.js:1483:23
npm ERR! Test failed.  See above for more details. 
````

Only happens when running `meteor test`. I can run the app with `meteor run` normally. I've made sure that `practicalmeteor:mocha` is up to date.

**Comment by moranda** [comment] 2016-11-23 09:07
Running the console with admin rights prevents this problem, if it is an acceptable solution for you.

**Comment by blueknightone** [comment] 2016-11-23 16:45
@moranda Not the ideal solution, especially since it was fixed for `meteor run`, but at least there's a workaround to keep development from halting.

**Comment by abernix** [comment] 2016-12-16 14:57
I'm inclined to believe that could be an issue related to having already run Meteor with Administrator privileges in the past and now suffering from the consequences of that as I can't reproduce this.

Here's what I did to try:

```sh
> git clone https://github.com/meteor/todos
> cd todos
> meteor npm install
> meteor test --driver-package practicalmeteor:mocha --port 3100
> # worked fine
> meteor test --full-app --driver-package practicalmeteor:mocha --port 5000
> # also worked fine
```

I think it would be advisable for you to do a fresh reset of your development environment with `meteor reset`, possibly a fresh install and then trying again.  You should never need to run Meteor with Administrator permissions.

**Comment by john-osullivan** [comment] 2017-01-04 23:26
I'm getting this bug as well.  Seems kind of odd that having run Meteor in admin mode in the past would require it to be run that way at all times in the future, or that we aren't allowed to run Meteor in admin mode at all.

**Comment by jborlik** [comment] 2017-01-21 22:13
I got this error, too, and I do not believe that I have ever run Meteor with admin rights.  (I am running Meteor 1.4.2.3, and basically just following the tutorial word for word.)  Running `meteor reset` did fix the problem, though, as I was able to start/stop the tests as expected after that.

**Comment by rwdietrich** [comment] 2017-01-31 02:18
I thought as well that it was admin rights. Nope. I wiped out my meteor directories under c:\Users\me\AppData\local\.meteor and unzipped the latest (1.4.2.3) into the directory. I'm getting the same message.

**Comment by Louis30** [comment] 2017-01-31 02:38
On Jan 21, 2017 2:13 PM, "Jeffrey Borlik" <notifications@github.com> wrote:

I got this error, too, and I do not believe that I have ever run Meteor
with admin rights. (I am running Meteor 1.4.2.3, and basically just
following the tutorial word for word.) Running meteor reset did fix the
problem, though, as I was able to start/stop the tests as expected after
that.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/meteor/meteor/issues/8091#issuecomment-274291644>, or mute
https://signup.thrillist.com/unsubscribethe thread

**Comment by abernix** [comment] 2017-02-13 14:41
@benjamn On Windows, `meteor test` is attempting to copy a symlink into the test-runner temp directory and failing because of lack of Admin permissions.  Do you think adding respect for a `symlinkAsJunction` option (which would acknowledge that both paths are directories) here in in [`files.cp_r`](https://github.com/meteor/meteor/blob/release-1.4.2.2/tools/fs/files.js#L500-L501) which could be passed in within [`copyDirIntoTestRunnerApp`](https://github.com/meteor/meteor/blob/release-1.4.2.2/tools/cli/commands.js#L1692-L1694) could solve this problem?  

Alternatively, `files.cp_r` could test `from` and `to` and just use `junction` if they were both directories?

**Comment by leosco** [comment] 2017-03-03 21:45
Hey, just wanted to give an update: on Meteor 1.4.3.1 I'm still having this issue after doing a *clean* reinstall of Meteor (running the Windows uninstaller, deleting `%LOCALAPPDATA%\.meteor`, and then installing fresh from meteor.com) and I did a `meteor reset`. TBH, I don't remember ever running `meteor` as administrator. This issue only started happening for me around the 1.3 release if I recall correctly.

**Comment by Nakroma** [comment] 2017-03-14 17:13
Same problem here, on Meteor 1.4.3.2. It also doesn't work if I reinstall or do a meteor reset.  
It's really strange since I didn't change anything, it worked fine a month or so ago. I tried to add practicalmeteor:mocha and it stopped working.

**Comment by leosco** [comment] 2017-03-14 17:42
Yep, it looks like there are plenty of mysterious Windows based issues that
are cropping up like this. This particular one is almost certainly project
specific, so it's very hard to reproduce :(

**Comment by Nakroma** [comment] 2017-03-15 14:01
Since it seems to be an permission error, has anyone tried to change the groups in `gpedit.msc` under `Computer Configuration -> Windows Settings -> Security Settings -> Local Policies -> User Rights Assignment -> Create symbolic links`? I sadly can't try it since im one Home Edition.

**Comment by leosco** [comment] 2017-03-20 15:58
@Nakroma Even if that did work, it'd be just another work around for this issue, like running `meteor test` in admin mode.

**Comment by Aciho** [comment] 2017-04-06 14:49
Tried changing the permission level for creating symbolic links, but it didn't work.

**Comment by mmoo9154** [comment] 2017-04-29 01:52
I had this exact bug.  Based on one of the prior comments, I fixed it with the following:

```
meteor reset
meteor npm install
meteor test --driver-package practicalmeteor:mocha
```

**Comment by justbill2020** [comment] 2017-05-27 21:04
@mmoo9154's workaround fixed this for me as well...

**Comment by justbill2020** [comment] 2017-05-29 01:51
I also notice that this has a label can't reproduce... this can be reproduced by starting the meteor test using ```meteor test --driver-package practicalmeteor:mocha``` and then after that page is rendered, terminating the test environment... then starting meteor using ```meteor run``` then after that starts and you get the project rendered, terminate meteor. then start the test environment again and you should get the error.

**Comment by justbill2020** [comment] 2017-05-29 05:27
The issue with the workaround i'm having from @mmoo9154 is that I lose all data for my dev environment everytime i run the test environment which is frustrating. 

@abernix is there any assistance you can provide on this?

**Comment by leosco** [comment] 2017-05-31 21:29
@justbill2020 if that workaround is working for you (it isn't for me), then you can `mongodump` your dev database instance before you do it and then `mongorestore` to it again.
To do that, you should download [MongoDB](https://www.mongodb.com/download-center#community) for your machine, and add `\MongoDB\Server\3.4\bin` to your path.
Then you can run `mongodump -h localhost:3001 -d meteor` to dump your whole db and then restore it with `mongorestore -h localhost:3001 -d meteor <path_to_your_dump>`, or something like that.

**Comment by justbill2020** [comment] 2017-06-01 14:42
it was working over time it stopped working... 
now i'm getting this... 

```
Unable to resolve some modules:

  "react/addons" in /D/meteor/projects/notes/node_modules/enzyme/build/react-compat.js
(web.browser)
  "react/lib/ReactContext" in
/D/meteor/projects/notes/node_modules/enzyme/build/react-compat.js (web.browser)
  "react/lib/ExecutionEnvironment" in
/D/meteor/projects/notes/node_modules/enzyme/build/react-compat.js (web.browser)
  "react-dom/test-utils" in
/D/meteor/projects/notes/node_modules/enzyme/build/react-compat.js (web.browser)
  "react-test-renderer/shallow" in
/D/meteor/projects/notes/node_modules/enzyme/build/react-compat.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save react react-dom react-test-renderer

W20170601-09:39:19.714(-5)? (STDERR) module.js:327
W20170601-09:39:20.061(-5)? (STDERR)     throw err;
W20170601-09:39:20.061(-5)? (STDERR)     ^
W20170601-09:39:20.062(-5)? (STDERR)
W20170601-09:39:20.063(-5)? (STDERR) Error: Cannot find module 'fibers'
W20170601-09:39:20.063(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20170601-09:39:20.063(-5)? (STDERR)     at Function.Module._load (module.js:276:25)
W20170601-09:39:20.063(-5)? (STDERR)     at Module.require (module.js:353:17)
W20170601-09:39:20.064(-5)? (STDERR)     at require (internal/module.js:12:17)
W20170601-09:39:20.064(-5)? (STDERR)     at Object.<anonymous> (C:\Users\bmart\AppData\Local\Temp
\meteor-test-run4mtzsv\.meteor\local\build\programs\server\boot.js:1:75)
W20170601-09:39:20.065(-5)? (STDERR)     at Module._compile (module.js:409:26)
W20170601-09:39:20.065(-5)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170601-09:39:20.065(-5)? (STDERR)     at Module.load (module.js:343:32)
W20170601-09:39:20.066(-5)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170601-09:39:20.066(-5)? (STDERR)     at Module.require (module.js:353:17)
=> Exited with code: 1
```

**Comment by justbill2020** [comment] 2017-06-02 22:07
ok so somehow i messed up my meteor dev_build folder in the appdata directory.

i've reinstalled meteor and still having the same issue as before... 

it seems that its a rights issue with the temp directory for whatever reason. perhaps creating a .test folder within the .meteor/local and building the test environment there would solve this issue? since i have no issues creating symlinks within the .meteor/local folder?

**Comment by justbill2020** [comment] 2017-06-02 22:12
the oddest thing is that that temp folder that's created by meteor test command has a .meteor/local folder with other symbolic links within it... this is extremely odd... does can someone point me in a proper direction for where in the source code all of this is done... i would llike to change the target path for the test build and see if that solves the issue... is there a reason for it to be created in the users's temp directory?

**Comment by justbill2020** [comment] 2017-06-03 03:45
ok sorry to be a pest i'm hoping some of this might end up helping out...

when i hit control +c i get this in the console...
```
{ [Error: EBUSY: resource busy or locked, unlink 'C:\Users\bmart\AppDa
ta\Local\Temp\meteor-test-runmnj2mi\.meteor\local\db\local.0']
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\Users\\bmart\\AppData\\Local\\Temp\\meteor-test-runmnj2mi\\.meteor\\local\\db\\local
.0' }
```
i would venture to guess this is causing the underlying issue

**Comment by abernix** [comment] 2017-06-13 10:25
@justbill2020 I think that `EBUSY` error is https://github.com/meteor/meteor/issues/8485.  Please check that issue for updates about it (as I just made one!)

**Comment by john-osullivan** [comment] 2017-06-16 21:14
I'm having this bug as well, @justbill2020 , thank you for recording your experience with it!  Trying out the workaround @mmoo9154 proposed, hopefully it behaves consistently now.

**Comment by hwillson** [comment] 2017-09-13 11:47
There are multiple different issues discussed in this thread, but it sounds like the original issue can be addressed via https://github.com/meteor/meteor/issues/8091#issuecomment-298139868 (or, if you don't want to wipe your local DB, just remove everything in your apps `.meteor/local` directory except for the `db` directory). All other problems should be opened in new issues, if they're still occurring. Closing - thanks!

**Comment by leosco** [comment] 2017-12-01 19:21
@hwillson I've never been able to fix this issue, not with `meteor reset` or reinstalling Meteor or anything else. I just kinda live with it, tbh.

**Comment by hwillson** [comment] 2017-12-01 19:24
@leosco Have you tried re-installing with Chocolatey and using Meteor 1.6?

**Comment by leosco** [comment] 2017-12-19 15:20
@hwillson yep, literally nothing I do can fix this issue, unfortunately.

**Comment by AnderbergE** [comment] 2018-01-23 13:14
I have this problem as well and it's been like this for some time. I have the problem on multiple windows 10 home edition, using meteor 1.6.0.1 (but hasn't worked in previous versions either).

The fix mentioned above, to run ```meteor reset``` does fix the test, but only until I run the regular ```meteor``` again. Once I've done that I'm back to testing not working. How can this be? Is something in the testing command using things done when running ```meteor```?

(Note: It does work when I run as admin, but that only works in my local environment and is tbh a pretty bad workaround anyway.)

**Comment by hwillson** [comment] 2018-01-23 13:24
@leosco @AnderbergE Thanks for the update - sounds like this issue is still lurking. Re-opening - thanks!

**Comment by leosco** [comment] 2018-01-23 16:19
Jeez did I first open this in *2016*? Seems like it's just one of those unsquashables

**Comment by hwillson** [comment] 2018-03-09 17:26
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity (see the [bug issue lifespan](https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/ISSUE_TRIAGE.md#bug-issue-lifespan) section of Meteor's triage doc for more information). If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!

**Closed by hwillson** 2018-03-09 17:26 UTC
Labels: Project:Windows, bug, can't-reproduce, not-implemented, pull-requests-encouraged

**Comment by amanagarwal2189** [comment] 2018-03-12 19:30
I am having this issue. Same as explained by others. Doing this on Windows 10.
Running with admin privileges lets you proceed.

**Comment by jmdsg** [comment] 2018-03-19 18:57
I had the same issue but with vmware in a shared folder and executing the workstation as admin solved the EPERM error.
