### ISSUE TITLE
help with crash please

### ISSUE THREAD

**Issue by kirich1368** [meteor/meteor#7177] opened 2016-06-06 11:30 UTC
```
W20160606-13:40:27.759(3)? (STDERR)
W20160606-13:40:27.762(3)? (STDERR) Error: connect ECONNREFUSED
W20160606-13:40:27.762(3)? (STDERR) at errnoException (net.js:905:11)
W20160606-13:40:27.762(3)? (STDERR) at Object.afterConnect as oncomplete
W20160606-13:40:27.763(3)? (STDERR) --------------------
W20160606-13:40:27.763(3)? (STDERR) at Protocol._enqueue (/root/.meteor/pack ages/numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/mys ql/lib/protocol/Protocol.js:141:48)
W20160606-13:40:27.763(3)? (STDERR) at Protocol.handshake (/root/.meteor/pac kages/numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/my sql/lib/protocol/Protocol.js:52:41)
W20160606-13:40:27.763(3)? (STDERR) at Connection.connect (/root/.meteor/pac kages/numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/my sql/lib/Connection.js:123:18)
W20160606-13:40:27.763(3)? (STDERR) at new LiveMysql (/root/.meteor/packages /numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/mysql-l ive-select/lib/LiveMysql.js:42:11)
W20160606-13:40:27.763(3)? (STDERR) at meteorInstall.server.main.js (server/ main.js:1:10)
W20160606-13:40:27.763(3)? (STDERR) at fileEvaluate (packages/modules-runtim e/.npm/package/node_modules/install/install.js:141:1)
W20160606-13:40:27.763(3)? (STDERR) at require (packages/modules-runtime/.np m/package/node_modules/install/install.js:75:1)
W20160606-13:40:27.764(3)? (STDERR) at /root/met/.meteor/local/build/program s/server/app/app.js:455:1
W20160606-13:40:27.764(3)? (STDERR) at /root/met/.meteor/local/build/program s/server/boot.js:283:10
W20160606-13:40:27.764(3)? (STDERR) at Array.forEach (native)
=> Exited with code: 8
W20160606-13:40:37.285(3)? (STDERR)
W20160606-13:40:37.287(3)? (STDERR) Error: connect ECONNREFUSED
W20160606-13:40:37.287(3)? (STDERR) at errnoException (net.js:905:11)
W20160606-13:40:37.287(3)? (STDERR) at Object.afterConnect as oncomplete
W20160606-13:40:37.287(3)? (STDERR) --------------------
W20160606-13:40:37.287(3)? (STDERR) at Protocol._enqueue (/root/.meteor/pack ages/numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/mys ql/lib/protocol/Protocol.js:141:48)
W20160606-13:40:37.287(3)? (STDERR) at Protocol.handshake (/root/.meteor/pac kages/numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/my sql/lib/protocol/Protocol.js:52:41)
W20160606-13:40:37.287(3)? (STDERR) at Connection.connect (/root/.meteor/pac kages/numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/my sql/lib/Connection.js:123:18)
W20160606-13:40:37.288(3)? (STDERR) at new LiveMysql (/root/.meteor/packages /numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/mysql-l ive-select/lib/LiveMysql.js:42:11)
W20160606-13:40:37.288(3)? (STDERR) at meteorInstall.server.main.js (server/ main.js:1:10)
W20160606-13:40:37.288(3)? (STDERR) at fileEvaluate (packages/modules-runtim e/.npm/package/node_modules/install/install.js:141:1)
W20160606-13:40:37.288(3)? (STDERR) at require (packages/modules-runtime/.np m/package/node_modules/install/install.js:75:1)
W20160606-13:40:37.289(3)? (STDERR) at /root/met/.meteor/local/build/program s/server/app/app.js:455:1
W20160606-13:40:37.289(3)? (STDERR) at /root/met/.meteor/local/build/program s/server/boot.js:283:10
W20160606-13:40:37.289(3)? (STDERR) at Array.forEach (native)
=> Exited with code: 8
W20160606-13:40:47.200(3)? (STDERR)
W20160606-13:40:47.201(3)? (STDERR) Error: connect ECONNREFUSED
W20160606-13:40:47.202(3)? (STDERR) at errnoException (net.js:905:11)
W20160606-13:40:47.202(3)? (STDERR) at Object.afterConnect as oncomplete
W20160606-13:40:47.202(3)? (STDERR) at Protocol._enqueue (/root/.meteor/pack ages/numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/mys ql/lib/protocol/Protocol.js:141:48)
W20160606-13:40:47.202(3)? (STDERR) at Protocol.handshake (/root/.meteor/pac kages/numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/my sql/lib/protocol/Protocol.js:52:41)
W20160606-13:40:47.203(3)? (STDERR) at Connection.connect (/root/.meteor/pac kages/numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/my sql/lib/Connection.js:123:18)
W20160606-13:40:47.203(3)? (STDERR) at new LiveMysql (/root/.meteor/packages /numtel_mysql/.1.0.6.j3ik78++os+web.browser+web.cordova/npm/node_modules/mysql-l ive-select/lib/LiveMysql.js:42:11)
W20160606-13:40:47.203(3)? (STDERR) at meteorInstall.server.main.js (server/ main.js:1:10)
W20160606-13:40:47.203(3)? (STDERR) at fileEvaluate (packages/modules-runtim e/.npm/package/node_modules/install/install.js:141:1)
W20160606-13:40:47.203(3)? (STDERR) at require (packages/modules-runtime/.np m/package/node_modules/install/install.js:75:1)
W20160606-13:40:47.203(3)? (STDERR) at /root/met/.meteor/local/build/program s/server/app/app.js:455:1
W20160606-13:40:47.202(3)? (STDERR) --------------------
W20160606-13:40:47.204(3)? (STDERR) at /root/met/.meteor/local/build/program s/server/boot.js:283:10
W20160606-13:40:47.204(3)? (STDERR) at Array.forEach (native)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by lieuwex** [comment] 2016-06-06 15:12
Looks like it is an issue with https://github.com/numtel/meteor-mysql, I think reporting it there is more useful.

**Comment by kirich1368** [comment] 2016-06-06 16:31
Thank

**Comment by laosb** [comment] 2016-06-07 03:17
Looks much like a connection failure. Closing but feel free to reoopen if reproduced as a Meteor problem!

**Closed by laosb** 2016-06-07 03:17 UTC
