### ISSUE TITLE
Meteor testing with practicalmeteor:mocha has just stopped working

### ISSUE THREAD

**Issue by manuelro** [meteor/meteor#8412] opened 2017-02-22 21:11 UTC
Meteor version: 1.4.2.7
NPM version: 3.10.9
Node version: v6.9.2

Meteor testing for backend and frontend was working fine, until I decided to patch it with the latest patch offered by the CLI.

The command I'm running is the same I've been running since I started the project, and it was working:
`meteor test --driver-package practicalmeteor:mocha --port 5001`

Now I cannot run the test server if I don't have admin rights and even when I run it with admin rights it simply does not watches for changes on testing files. It also takes longer to start the server. 

The error when I try to run the server without admin rights:
```
C:\Users\xxxxxxxxxxxxxx\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: EPERM: operation not permitted, symlink 'C:\Users\xxxxxxxxxxxxxx\AppData\Local\.meteor\packages\meteor-tool\1.4.2_6\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\' -> 'C:\Users\xxxxxxxxxxxxxx\AppData\Local\Temp\meteor-test-run1abwp8c\.meteor\local\build\programs\server\node_modules'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at Object.wrapper (C:\tools\fs\files.js:1535:35)
    at Object.files.cp_r (C:\tools\fs\files.js:501:11)
    at C:\tools\fs\files.js:488:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at C:\tools\fs\files.js:488:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at C:\tools\fs\files.js:488:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at copyDirIntoTestRunnerApp (C:\tools\cli\commands.js:1700:15)
    at doTestCommand (C:\tools\cli\commands.js:1706:5)
    at Command.func (C:\tools\cli\commands.js:1541:10)
    at C:\tools\cli\main.js:1483:23
```

When I run the server with admin rights the watcher simply stops, and if I `ctrl + c` I get another error:
```
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\xxxxxxxxxxxxxx\AppData\Local\Temp\meteor-test-run14uegfh\.meteor\local\build\programs']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\xxxxxxxxxxxxxx\\AppData\\Local\\Temp\\meteor-test-run14uegfh\\.meteor\\local\\build\\programs' }
```

I tried removing all my tests and create simple `describe` and `it` to isolate the problem, but it persists. Is there any way to rollback to the previous version?

**Comment by leosco** [comment] 2017-02-23 22:41
Are you on Windows? This has been a problem on Windows for a while, unfortunately. See https://github.com/meteor/meteor/issues/8091

It looks like some of the only real solutions are doing a `meteor reset` or, more dramatically, reinstalling Meteor.

**Comment by manuelro** [comment] 2017-02-23 22:49
Thanks for the hint. I'll take a look at it. I thought about reinstalling Meteor but I wasn't sure.

**Comment by hwillson** [comment] 2017-05-01 20:05
Closing as a duplicate of #8091 (which has more discussion and suggests potential workarounds). Thanks!

**Closed by hwillson** 2017-05-01 20:05 UTC
