### ISSUE TITLE
Docker container error after updating to 1.5.2

### ISSUE THREAD

**Issue by mwarren2** [meteor/meteor#9068] opened 2017-09-07 17:15 UTC
I'm getting this message from my container - any pointers as to what this means?

> /root/.meteor/packages/meteor-tool/.1.5.2.2ahv3x++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by /root/.meteor/packages/meteor-tool/.1.5.2.2ahv3x++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node)

**Comment by benjamn** [comment] 2017-09-07 17:49
What version of Linux are you using? What is the output of this command?
```sh
ldd --version
```

**Comment by mwarren2** [comment] 2017-09-07 19:17
I was on debian:wheezy.
So I've updated to debian:jessie, which was about time I suppose.

The original message has gone, but I'm now getting something different.

> geoloc-for-walks_local | => Started proxy.
geoloc-for-walks_local | /root/.meteor/packages/less/.2.7.9.al762l++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
geoloc-for-walks_local |       throw error;
geoloc-for-walks_local |       ^
geoloc-for-walks_local | 
geoloc-for-walks_local | Error: spawn ENOMEM
geoloc-for-walks_local |     at exports._errnoException (util.js:907:11)
geoloc-for-walks_local |     at ChildProcess.spawn (internal/child_process.js:315:11)
geoloc-for-walks_local |     at Object.exports.spawn (child_process.js:365:9)
geoloc-for-walks_local |     at [object Object]._.extend._spawn (/tools/runners/run-app.js:265:31)
geoloc-for-walks_local |     at [object Object]._.extend.start (/tools/runners/run-app.js:88:22)
geoloc-for-walks_local |     at [object Object]._.extend._runOnce (/tools/runners/run-app.js:753:16)
geoloc-for-walks_local |     at [object Object]._.extend._fiber (/tools/runners/run-app.js:885:28)
geoloc-for-walks_local |     at /tools/runners/run-app.js:412:12
geoloc-for-walks_local exited with code 1

Any help would be gratefully received.

**Comment by myktra** [comment] 2017-09-07 19:57
Similar original issue here... using the `node:4.8.4-wheezy` base image. Will try a more recent distro.

```
/root/.meteor/packages/meteor-tool/.1.5.2.kb5xnw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by /root/.meteor/packages/meteor-tool/.1.5.2.kb5xnw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node)
/root/.meteor/packages/meteor-tool/.1.5.2.kb5xnw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /root/.meteor/packages/meteor-tool/.1.5.2.kb5xnw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node)
```

**Comment by mwarren2** [comment] 2017-09-07 20:37
So mine is presumably some kind of memory problem.

**Comment by benjamn** [comment] 2017-09-07 21:19
@myktra Same question for you: what does `ldd --version` print?

**Comment by mwarren2** [comment] 2017-09-07 21:34
If it's any help, my production system (still 1.5.1) has the same wheezy image

root@333d200386d3:/# ldd --version
ldd (Debian EGLIBC 2.13-38+deb7u12) 2.13
Copyright (C) 2011 Free Software Foundation, Inc.

**Comment by myktra** [comment] 2017-09-07 22:02
Hey:

```
ldd (Debian EGLIBC 2.13-38+deb7u12) 2.13
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Just switched to `node:4.8.4-stretch` and that worked fine...

```
ldd (Debian GLIBC 2.24-11+deb9u1) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by abernix** [comment] 2017-09-11 13:04
Our build machines for Meteor releases (which run on Amazon Web Services) were previously using Ubuntu 12.04 which is based on Debian Wheezy (Debian 7).  Ubuntu 12.04 reached its ["end of life"](https://aws.amazon.com/blogs/apn/save-the-date-end-of-life-for-ubuntu-12-04-lts-precise-pangolin/) in April 2017 and as of the end of August, those AMIs were also to be removed from Amazon by the Ubuntu team (i.e. Canonical).  In preparation for this, we switched our build infrastructure to Ubuntu 14.04 (LTS), which is based on Debian Jessie (👋). Thus, Meteor 1.5.2 (which came out this month) was built on Ubuntu 14.04.

While upgrading to a newer Debian distro will fix your problem (as you have found), you wouldn't be in the wrong for using Wheezy as that does not reach LTS (with Debian) until [May 31, 2018](https://wiki.debian.org/LTS).  Perhaps we should switch to building on Debian Wheezy until it reaches end-of-life itself?

**Comment by myktra** [comment] 2017-09-11 14:37
Thanks @abernix... only reason on my end to initially use a Wheezy-based image was from a recommendation by a third party host (Aptible); at the time they recommended using the **node:4.8.4-wheezy** image for my Meteor application so I can both build and run the application on the image. Not sure exactly why the Node team doesn't have a _node:4.8.4-jessie_ available (just too many images to maintain?).

Not sure if the requirement to both build the Meteor application and run it is compatible with some of these alternative options, or I'd be happy with those.

https://github.com/tozd/docker-meteor
https://github.com/Treecom/alpine-meteor

**Comment by jgraham-plm** [comment] 2017-09-13 20:40
Wanted to point out that I'm having the same issue on CentOS 6.3:

```
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
```

**Comment by abernix** [comment] 2017-09-14 10:01
Thank you for letting us know @jgraham-plm.  Are you also suggesting that it was working fine for you with Meteor 1.5.1?

Much like Debian Wheezy, I believe CentOS 6.3 is also under LTS so this is something we are going to get addressed.  It may need to wait until Meteor 1.5.3.  I believe you may have success with a newer version of CentOS, but we shouldn't force you to do that update if the OS release is still being actively maintained.

**Comment by jgraham-plm** [comment] 2017-09-14 15:33
@abernix Sure thing. Yes, I can confirm that 1.5.1 works fine on CentOS 6.3.

I also confirmed that 1.5.2 works on CentOS 7, as you predicted. But yes, CentOS 6 is slated for a few more years of support, so thank you for addressing this!

**Comment by jgraham-plm** [comment] 2017-09-18 16:41
@abernix This is actually causing me a bit of a headache.

I've been trying to track down a functioning means of avoiding an upgrade of ```meteor``` tool to 1.5.2. I've tried using the [flags mentioned here](https://github.com/meteor/meteor/issues/8938#issuecomment-317673148), but 1.5.2 keeps eventually installing — maybe I'm doing something wrong? I also tried creating a symlink and executing the 1.5.1 tool directly [as described here](https://github.com/meteor/meteor/issues/7491#issuecomment-235655623), but if 1.5.2 is present I still have the same issue(s):
```
> which meteor
~/bin/meteor
> readlink ~/bin/meteor
/home/<user>/.meteor/packages/meteor-tool/1.5.1/mt-os.linux.x86_64/meteor
> meteor --version
/home/<user>/.meteor/packages/meteor-tool/.1.5.2.jascif++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /home/<user>/.meteor/packages/meteor-tool/.1.5.2.jascif++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node)
/home/<user>/.meteor/packages/meteor-tool/.1.5.2.jascif++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/<user>/.meteor/packages/meteor-tool/.1.5.2.jascif++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node)
/home/<user>/.meteor/packages/meteor-tool/.1.5.2.jascif++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/<user>/.meteor/packages/meteor-tool/.1.5.2.jascif++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node)
```

The flags issue illustrated, as I understand it:
```
> ls ~/.meteor/packages/meteor-tool/
1.5.1
> echo $METEOR_NO_RELEASE_CHECK
1
[Some time later]
> ls ~/.meteor/packages/meteor-tool/
1.5.1  1.5.2
```

I'd appreciate any help you can give me with working around this for the time-being! Thanks.

**Comment by abernix** [comment] 2017-09-19 11:35
@jgraham-plm Ah, okay, yes, since 1.5.2 is the "recommended" release, it's still ultimately responsible for "springboarding" you to other Meteor releases.  Unfortunately, that uses `node`.

Two options to try:

1. Copy the `node` from 1.5.1 into your 1.5.2 directory, but keep your project on Meteor 1.5.1.  You won't be immune to the segmentation faults fixed by #9031 with Meteor 1.5.1 but not everyone was being affected by them so probably okay for now.  This command should do the trick:

        cp ~/.meteor/packages/meteor-tool/1.5.1/mt-os.linux.x86_64/dev_bundle/bin/node ~/.meteor/packages/meteor-tool/1.5.2/mt-os.linux.x86_64/dev_bundle/bin/node

2. Set the `METEOR_NO_RELEASE_CHECK` variable (and make sure it stays set), but reinstall using:

        curl https://install.meteor.com/?release=1.5.1 | sh

    This will wipe your current `~/.meteor/` installation and do full reinstall, but you should be pinned to 1.5.1 as it will have no knowledge of the newer version at all since the `?release=1.5.1` parameter will make sure you install a different bootstrap tarball, which is the tarball responsible for initially loading up your `~/.meteor` directory.

**Comment by jgraham-plm** [comment] 2017-09-20 13:55
@abernix Copying ```node``` seems to do the trick — thank you!

**Comment by abernix** [comment] 2017-09-26 18:26
We rebuilt the image using CentOS 6.4 as a base which should fix CentOS 6, Debian Wheezy and Ubuntu Precise (12.04).  This should take our support through the end of Wheezy and CentOS 6's LTS period. Ubuntu Precise is already out of LTS, but we'll still support that unofficially until we move to a newer CentOS.  This should resolve this issue.

@jgraham-plm If you have a chance, can you please try Meteor 1.5.2.1?  It was just released, but it should no longer require you to copy your 1.5.1 `node` binary over it.  Please let us know how it goes!

@myktra Node.js does maintain a Debian Jessie.  The `node:4` image (also known as `node:4.8` and `node:4.8.4`), _without the `-wheezy` suffix_,  is [based on `debian:jessie`](https://github.com/nodejs/docker-node/blob/b502aa016335c81a586b430328d8fee4897ee440/4.8/Dockerfile).  That should work for you!

**Closed by abernix** 2017-09-26 18:26 UTC
Labels: bug, confirmed, Impact:some, Project:Tool, Severity:blocks-development

**Comment by jgraham-plm** [comment] 2017-09-26 22:18
@abernix Yep, 1.5.2.1 works great. Thanks for the quick fix!
