### ISSUE TITLE
1.3 beta 11 - Cordova: cordova-plugin-statusbar broken?

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#6368] opened 2016-02-29 18:02 UTC
the

`StatusBar.hide()`

from

`cordova-plugin-statusbar`

does not work anymore?

**Comment by rlech** [comment] 2016-02-29 21:27
yes I have the same problem.

**Comment by martijnwalraven** [comment] 2016-03-01 08:22
I haven't been able to reproduce this on either iOS or Android. The core plugins, including `cordova-plugin-statusbar`, are definitely compatible with Cordova 6.0.

What problems specifically are you experiencing? Did you make sure to only make the call after `Meteor.startup()` has fired (that corresponds to `deviceready` in Cordova)?

**Comment by obiwarn** [comment] 2016-03-01 09:50
i think so.

I use Android.

package:

`cordova-plugin-statusbar@2.1.1`

code:

```
Meteor.startup( ->
    Helpers.addScope('Language', Language);
    StatusBar?.hide()
...
```

I also checked that StatusBar is defined (i.e. log returns object)

**Comment by martijnwalraven** [comment] 2016-03-01 09:53
Have you tried running `StatusBar.hide()` and `StatusBar.show()` from the Chrome remote debugger (`chrome://inspect/`)?

**Comment by obiwarn** [comment] 2016-03-01 10:09
both methods return undefined

```
> StatusBar.hide()
undefined
> StatusBar
Object {isVisible: false, overlaysWebView: function, styleDefault: function, styleLightContent: function, styleBlackTranslucent: function…}
backgroundColorByHexString: function (hexString) {
backgroundColorByName: function (colorname) {
hide: function () {
arguments: null
caller: null
length: 0
name: ""
prototype: Object
__proto__: function Empty() {}
<function scope>
isVisible: false
overlaysWebView: function (doOverlay) {
show: function () {
styleBlackOpaque: function () {
styleBlackTranslucent: function () {
styleDefault: function () {
styleLightContent: function () {
__proto__: Object
```

**Comment by martijnwalraven** [comment] 2016-03-01 10:33
Yes, but functions without a return value always return `undefined`, so that is not the issue. Looking at `StatusBar`, it seems the functions themselves are defined.

So is the issue that the status bar does not hide? Is this on Android or iOS? What version?

**Comment by obiwarn** [comment] 2016-03-01 11:12
yes, the bar is still visible.

Android 4.4

**Comment by martijnwalraven** [comment] 2016-03-01 12:44
@rlech: You mention you have the same problem. Is this on Android or iOS? What version? Any errors in the browser console or native logging?

**Comment by rlech** [comment] 2016-03-01 15:31
I dont know why but its working for me now. ive testet this code with an iOS device (iphone 6+) and the iOS Simulator (iphone 6+ simulator) only. So please give me some information if this is working on android (simulator AND device) also.

https://github.com/rlech/meteor-cordova-statusbar

**Comment by obiwarn** [comment] 2016-03-01 15:40
when i add hide() to a button event it works.
when i change the route (i.e. new template) the bar reappears.

**Comment by rlech** [comment] 2016-03-01 15:48
ironrouter or flowrouter?

**Comment by obiwarn** [comment] 2016-03-01 15:50
iron

**Comment by rlech** [comment] 2016-03-01 16:18
I´ve updated the project with `iron:router` and its working on my ios device and simulator. can you check this also? Can you test this project on an android device?

**Comment by obiwarn** [comment] 2016-03-01 16:38
this seems to be a bug with

`cordova-plugin-statusbar@2.1.1`

I just downgraded to

`cordova-plugin-statusbar@2.0.0`

and everything works fine

**Comment by rlech** [comment] 2016-03-01 16:41
do you have tested this on ios or android? (version?)

**Comment by rlech** [comment] 2016-03-02 17:00
I have  an other issue when I init a mobile layout/template on startup its init a fake bar. when I do a hot code push the bar disappears.

When I run my code in ios simulator (cordova build) it looks like its init the statusbar-overlay (even when I dont have the statusbar-overlay div in my code)

**when I run on ios simulator there is a container or something over my blue div. this container only appears when I create a native app (webapp seems to be ok)**

<img width="320" alt="with" src="https://cloud.githubusercontent.com/assets/3764301/13466129/e9e0a2e6-e098-11e5-9cad-b28018a4b23a.png">


**when I do a hot code push (change some code and the template will be updated in background) it disappears**
_this is how it should look like_

<img width="320" alt="without" src="https://cloud.githubusercontent.com/assets/3764301/13466161/0c911ce4-e099-11e5-89a5-bef85205d314.png">

my demo code
```
   <style>
       body{
           background: red!important;
       }
   </style>
    <div class="" style="background: blue">

        hello
    </div>
```

this only appears in meteor beta(11). not in 1.2.1 release

**Comment by LucNaterop** [comment] 2016-04-08 13:30
Anybody got some updates on this? I am using the `mobile-status-bar` package. I can hide the status bar by calling `StatusBar.hide()` temporarily but if I leave the app and open again in the status bar is back again (this happens on Anroid; it works fine on iOS). Only being able to use `StatusBar.hide()` is not good because we have to call it at runtime. We should also have the ability to hide the status bar [at startup](https://www.npmjs.com/package/cordova-plugin-statusbar#hiding-at-startup).

**Comment by rlech** [comment] 2016-04-08 16:49
working for me. are you using framework7?

**Comment by LucNaterop** [comment] 2016-04-08 16:53
@rlech I am using angular + ionic. I will soon have a look if your [small demo](https://github.com/rlech/meteor-cordova-statusbar) produces the same problems.

**Comment by hwillson** [comment] 2017-08-17 20:52
Based on this issues history, it doesn't sound like there is a Meteor problem here. I'll close this issue for now, but I'm happy to re-open it if anyone is still having this problem (and can ideally provide a reproduction demonstrating this issue - see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Closed by hwillson** 2017-08-17 20:52 UTC
Labels: Project:Mobile
