### ISSUE TITLE
Error running template on 1.3 beta.7

### ISSUE THREAD

**Issue by ndarilek** [meteor/meteor#6164] opened 2016-02-05 17:03 UTC
Seeing this over and over on 1.3 beta.7 whenever my app tries to render a page:

```
E20160205-10:48:23.579(-6) (webapp_server.js:716) Error running template: Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
```

Unfortunately that is the extent of the error message. If it provided a stacktrace then I'd have an easier time reproducing and possibly fixing this on my end. Unfortunately my app is fairly large, and I have no clue where to even begin looking.

I've switched back to beta.6 which works fine with the exact same codebase. Happy to try anything to help find what's causing this.

**Comment by dgreensp** [comment] 2016-02-05 20:41
Thanks for filing an issue.  beta.8 will have a better error message.

**Comment by huttonr** [comment] 2016-02-06 07:17
Looks like a duplicate of https://github.com/meteor/meteor/issues/6170

**Comment by avital** [comment] 2016-02-09 18:33
Probably a dup of #6170. I'll close this. If this is still happening please file a new issue with a simple repro.

**Closed by avital** 2016-02-09 18:33 UTC
