### ISSUE TITLE
Meteor periodically crashes when rebuilding after update to 1.5

### ISSUE THREAD

**Issue by SimonSimCity** [meteor/meteor#8945] opened 2017-07-26 08:52 UTC
After updating meteor to version 1.5 I have often had the following misbehavior:

When I call `meteor test --settings settings-test.json --driver-package practicalmeteor:mocha --port 3100` it runs for a while and executes the tests in the tab I have opened in my browser. That's all good and expected. But at the time I change a file, it might rebuild the tests and run a second time, but latest during the third or fourth time rebuilding it crashes, and the last state I could see was

    W20170726-11:27:51.621(4)? (STDERR) MochaRunner.runServerTests: failures: 0
    Building for web.browser                  -

until I get a command prompt like

    W20170726-11:27:51.621(4)? (STDERR) MochaRunner.runServerTests: failures: 0
    project (develop) $ _rowser                   |

and waits for my input. The underscore is my cursor :wink:. It leaves me with just this message - that's it. The first line is actually what I get after all tests are run, before changing the file. I've just added it so you get a better impression of what I see.

Trying it with the `--verbose` flag, I saw a lot of `Local package version up-to-date:` messages before it again started with

    Building for web.browser                  -

and failed with

    Segmentation fault: 11

As said, it only happens after a test-run, at a project-rebuild, in my case caused by changing a file in the repository.

As said, it sometimes fails on the second rebuild, sometimes on a later rebuild. It's seldom it let's me rebuild the project more than five times.

**Update:** I now also got it crashing when running in development (not only on testing) ... Just updated the title to reflect it.

**Comment by sdarnell** [comment] 2017-07-30 21:19
Possible duplicate of https://github.com/meteor/meteor/issues/8648

**Comment by SimonSimCity** [comment] 2017-07-31 06:47
I now read through some tickets related to #8648 and found this one: https://github.com/meteor/meteor/issues/8157#issuecomment-315562842

It seems that raising the memory is a valid way of not getting it to crash so fast. I'm using Mac OS X El Capitan - just for the record. This is the command I now have to run before running `meteor`:

    export TOOL_NODE_FLAGS="--max_old_space_size=4096"

In #8157 many people stated, that this error occurred more frequently after updating to meteor 1.5 and it could well happen that I was just under this limit and now (with the update to 1.5) am hitting it quite often.

**Comment by hwillson** [comment] 2017-08-01 15:38
As mentioned in https://github.com/meteor/meteor/issues/8945#issuecomment-318930457, this really does seem like a duplicate of #8648. I'll close this here @SimonSimCity, but please join in the conversation over in #8648. Thanks!

**Closed by hwillson** 2017-08-01 15:38 UTC
