### ISSUE TITLE
[1.6] not compatible with bluebird

### ISSUE THREAD

**Issue by joey-he8x** [meteor/meteor#9307] opened 2017-11-06 09:10 UTC
use bluebird v3.5

got errors like: TypeError: Promise.asyncApply is not a function

also when call Meteor.callPromise (provided by deanius:promise) got the same error

**Comment by benjamn** [comment] 2017-11-06 21:45
Are you getting these errors on the client or the server?

**Comment by joey-he8x** [comment] 2017-11-06 22:52
on server side

**Comment by hwillson** [comment] 2017-11-07 14:17
@joey-he8x Any chance you could put together a reproduction demonstrating this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug))? Thanks!

**Comment by javascriptlove** [comment] 2017-11-07 15:19
I was getting the same when i had Promise being loaded from a `q` package (https://www.npmjs.com/package/q) - it was overwriting the global Promise object, so just make sure you don't use those, and use native node promise

**Comment by jamesmillerburgess** [comment] 2017-11-07 17:34
[Reproduction](https://github.com/jamesmillerburgess/bluebird-promise-error) 

`index.js`
```
import Promise from 'bluebird'; // Comment out this line and there is no error

(async function noop() {
  return null;
})();
```

`error`
```
W20171107-18:30:05.513(1)? (STDERR) /Users/goldfibre/.meteor/packages/meteor-tool/.1.6.0.396ahw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171107-18:30:05.514(1)? (STDERR)                                             throw(ex);
W20171107-18:30:05.514(1)? (STDERR)                                             ^
W20171107-18:30:05.514(1)? (STDERR)
W20171107-18:30:05.514(1)? (STDERR) TypeError: Promise.asyncApply is not a function
W20171107-18:30:05.515(1)? (STDERR)     at noop (index.js:3:2)
W20171107-18:30:05.515(1)? (STDERR)     at index.js (index.js:3:1)
W20171107-18:30:05.516(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171107-18:30:05.516(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171107-18:30:05.516(1)? (STDERR)     at /Users/goldfibre/projects/bluebird-promise-error/.meteor/local/build/programs/server/app/app.js:31:1
W20171107-18:30:05.517(1)? (STDERR)     at infos.forEach.info (/Users/goldfibre/projects/bluebird-promise-error/.meteor/local/build/programs/server/boot.js:414:13)
W20171107-18:30:05.517(1)? (STDERR)     at Array.forEach (<anonymous>)
W20171107-18:30:05.517(1)? (STDERR)     at /Users/goldfibre/projects/bluebird-promise-error/.meteor/local/build/programs/server/boot.js:413:9
W20171107-18:30:05.517(1)? (STDERR)     at /Users/goldfibre/projects/bluebird-promise-error/.meteor/local/build/programs/server/boot.js:463:5
W20171107-18:30:05.518(1)? (STDERR)     at Function.run (/Users/goldfibre/projects/bluebird-promise-error/.meteor/local/build/programs/server/profile.js:510:12)
W20171107-18:30:05.518(1)? (STDERR)     at /Users/goldfibre/projects/bluebird-promise-error/.meteor/local/build/programs/server/boot.js:462:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by hwillson** [comment] 2017-11-10 20:33
Thanks for the reproduction @jamesmillerburgess! 

As mentioned in https://github.com/meteor/meteor/issues/9307#issuecomment-342515010, `import Promise from 'bluebird'` overwrites the `Promise` global Meteor uses. As a workaround, if you want to use `bluebird` consider changing your `import` to use another identifier for the loaded promise object, like:

```js
import P from 'bluebird'; 
```

**Comment by hwillson** [comment] 2017-11-29 10:34
Quick note - this issue is essentially a duplicate of https://github.com/meteor/meteor/issues/9067. They're different enough to level both issues open, but I'm just dropping a reference to link the issues.

**Comment by hwillson** [comment] 2018-01-16 20:00
This isn't likely going to change anytime soon, so if anyone is interested in using `bluebird`, try the workaround mentioned in https://github.com/meteor/meteor/issues/9307#issuecomment-343578785. Closing for now - thanks!

**Closed by hwillson** 2018-01-16 20:00 UTC
Labels: Impact:few, Project:Isobuild, Severity:has-workaround, confirmed
