### ISSUE TITLE
Blaze removes DOM Element data before removeElement hook is executed

### ISSUE THREAD

**Issue by marcodejongh** [meteor/meteor#5573] opened 2015-10-30 09:38 UTC
I've been trying to make the [gridstack](https://github.com/troolee/gridstack.js) jQuery plugin work with meteor. After setting up the ui hooks I found out that my removeElement hook wasn't working.

It appears that Blaze has already cleaned up whatever stuff was stored with `$().data` before the removeElement hook is called. If I remember correctly, when uiHooks are defined all handling of removing/cleaning up the node should be handed over to the uiHook. 

This bug makes it impossible to re-use a lot of jQuery plugins without monkey patching or altering the code of the plugin

I've setup a reproduction path here:
Code: https://github.com/marcodejongh/reproduce-html-element-data-removed-before-removelementhook
Deployed: [issue5573.meteor.com](http://issue5573.meteor.com)

I've confirmed the bug in both Firefox and Chrome on OS X.

**Comment by mitar** [comment] 2015-11-08 01:29
Just DOM removing should be handled through `uiHooks`. So the very last step.

BTW, who adds `_gridstack_node`? I do not think Blaze is removing `data` on elements just so.

**Comment by tmeasday** [comment] 2015-11-17 23:39
@mitar is correct, the Blaze system hooks into jquery's node cleanup+removal and simply handle the task of taking the element out of the DOM yourself.

I think it's probably tricky to do what you want here. However if the plugin is jquery compatible perhaps it handles the de-registering task itself already?

**Comment by marcodejongh** [comment] 2015-11-18 12:53
@tmeasday The problem is that for some reason the stuff assigned to the DOM element with ```$.data``` has already been deleted for some reason in the removeElement hook. This will make it hard to make a lot of jquery plugins work because a lot of them tend to rely heavily on ```$.data```.

Maybe I should create another reproduction path without the gridstack jQuery plugin as it seems to distract from the issue at hand.

**Comment by tmeasday** [comment] 2015-11-19 00:21
@marcodejongh but the point here is that if you were using pure jquery the same thing would happen (jquery would strip the `$.data`, then remove the element from the DOM). `_uihooks` just gives you a way of interjecting between the two spots.

If you want to do cleanup, I think `onDestroyed` is probably a better bet?

**Comment by marcodejongh** [comment] 2015-11-19 09:18
@tmeasday actually I need the $.data for removing the DOM element. That is the problem, in removeElement the data has already been removed for some weird reason.

**Comment by tmeasday** [comment] 2015-11-20 00:25
I'm not sure it's a weird reason, given what I said above: https://github.com/meteor/meteor/issues/5573#issuecomment-157906981

The problem is that `removeElement` happens after jQuery has already done its cleanup.

**Comment by marcodejongh** [comment] 2015-11-20 16:41
@tmeasday It's not cleanup I want to do, this particular jQuery plugin doesn't respond well to Blaze removing it's DOM nodes. If you look at the code I don't want to do cleanup or whatever, I want to call the plugin's method for removing the DOM node:

**Comment by hwillson** [comment] 2017-01-16 15:31
Closing this off as it doesn't look like this is an issue with Meteor specifically. If you think this should still be looked into, please create a new issue via the [Blaze repo](https://github.com/meteor/blaze). Thanks for reporting this originally!

**Closed by hwillson** 2017-01-16 15:31 UTC
