### ISSUE TITLE
Node 0.12.x support

### ISSUE THREAD

**Issue by westlakem** [meteor/meteor#4683] opened 2015-07-04 16:23 UTC
With the latest update in NodeJS, they addressed a severe bug (one that could bring down your whole system).  Is there any timeline on getting NodeJS 0.12.x support?

**Comment by robertpitt** [comment] 2015-07-06 13:30
@westlakem, have you confirmed that node.js 0.12 is incompatible with Meteor

**Comment by emgee3** [comment] 2015-07-06 16:16
0.10.x is not affected by the bugs resolved in the 4 July updates, according to http://dailyjs.com/2015/07/04/security-updates-node-0-12-and-io-js/ 

When in development mode, Meteor uses a bundled node binary rather than what is installed on the system. It currently bundles 0.10.36. When running from a bundle one can choose which copy of node to run.

However, [0.10.38 and 0.10.39](https://raw.githubusercontent.com/joyent/node/v0.10.39/ChangeLog) do contain fixes for bugs related to OpenSSL, so it would be a good idea to upgrade regardless, though I'm not qualified to determine how urgent this ought to be. 

On a related note, as of 2 July, fibers@1.0.6 was published which supports node 0.12 as well as iojs. So it should be possible to upgrade the bundled version of node now, though waiting for the reunification of node and iojs may come first.

**Comment by westlakem** [comment] 2015-07-06 18:22
@robertpitt I can confirm that meteor does not work with nodejs 0.12

**Comment by westlakem** [comment] 2015-07-06 18:34
@emgee3 
What are you specifically speaking to when you mean the reunification of node and iojs?  I know there were talks about it back in February, but I haven't heard anything since.  Do we have an updated timeline on when that or node 0.12 support will happen?

**Comment by emgee3** [comment] 2015-07-06 18:56
See https://medium.com/node-js-javascript/io-js-week-of-may-15th-9ada45bd8a28

I don't know of any timeframes mentioned, but I've not really been following too closely.

**Comment by westlakem** [comment] 2015-07-06 20:06
@emgee3 I've been looking around on forums and it doesn't look like much has been done.  I realize Node 0.12.x has only been out for about 5 months now, but hopefully something's in the works.

**Comment by glasser** [comment] 2015-07-07 20:42
Duplicate of #3666.

**Closed by glasser** 2015-07-07 20:42 UTC
Labels: Project:JS Environment
