### ISSUE TITLE
Mongo exit error code 48

### ISSUE THREAD

**Issue by thomasrivette** [meteor/meteor#5857] opened 2015-12-21 19:20 UTC
Unexpected mongo exit code 48. Restarting.

Can't start Mongo server.

MongoDB exited because its port was closed, or was already
taken by a previous instance of MongoDB

C:\Users\Thomas Rivette\Documents\SoftwareProjects\simple-todos>netstat -a -n | findstr 3001
TCP 0.0.0.0:3001 0.0.0.0:0 LISTENING

**Comment by tmeasday** [comment] 2015-12-29 23:15
Hi @thomasrivette I think this is a duplicate of https://github.com/meteor/meteor/issues/3058 ?

**Closed by tmeasday** 2015-12-29 23:15 UTC
