### ISSUE TITLE
Somewhat outdated underscore package

### ISSUE THREAD

**Issue by neoromantic** [meteor/meteor#3337] opened 2014-12-20 14:13 UTC
Underscore package includes right now underscore.js version of 1.5.2 while 1.7.0 is available.

Please, consider bumping it to current version.

**Comment by glasser** [comment] 2015-01-14 00:50
Duplicate of #1009, more or less.

**Closed by glasser** 2015-01-14 00:50 UTC
Labels: Project:Imported Packages

**Comment by Igor1201** [comment] 2015-05-10 16:27
+1
