### ISSUE TITLE
Duplicate key error

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#6637] opened 2016-03-30 11:01 UTC
I'm getting an exception that crashes my whole application if a user inserts a document to my collection:

```
Exception while invoking method 'addMessage' MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index:
```

This is the method, defined in **lib/methods/messages.js**

```
'addMessage': function (message) {
    check(message, String);
    var currentUser = Meteor.users.findOne(this.userId);

    Messages.insert({
        text: message,
        chatId: currentUser.profile.chatId,
        userId: this.userId,
        createdAt: new Date()
    });
}
```

Collection is defined in **lib/collections/messages.js**

```
Messages = new Meteor.Collection("messages");

if(Meteor.isServer) {
    Messages._ensureIndex({ "chatId": 1, "createdAt":-1});
}
```

This error doesn't happen every time, but sometimes, ending in crashing the whole worker (I'm using meteor-cluster with 4 workers on a single server). The collection has about 40k+ inserts daily. Currently I'm using Meteor 1.2

**Comment by Deilv** [comment] 2016-03-30 12:44
This seems more likely to be a cluster issue (i.e. two nodes trying to insert the same record) rather than meteor. Can you test if the error occurs without cluster?

In case this turns out to be a meteor issue, it may be already fixed in the latest version. Can you reproduce the error in meteor 1.3?

**Comment by dnish** [comment] 2016-03-30 12:50
@Deilv Yeah, could be possible. I've just recognized after I've change the method to server only, that some messages were added twice, this happened also when I've chatted with a user. The method is called on the client side, if the user presses enter.

What is the recommended way when we use multiple CPUs / instances for that? Just thought that cluster handles the whole sticky session thing and so the method only get's fired on one node?

**Comment by helfer** [comment] 2016-04-05 23:01
It looks like this issue is related to cluster, so you should report the issue there. As a workaround, you should consider wrapping that code in a try/catch block so it doesn't crash your server.

**Comment by dnish** [comment] 2017-02-12 22:28
@helfer according to this forum post https://forums.meteor.com/t/meteor-duplicate-key-error/20048/7 it seems like that it is a Meteor issue and not one of the cluster module.

**Comment by arggh** [comment] 2017-03-09 17:25
Not sure if related, but just today I got this on our staging server:

```
"E11000 duplicate key error collection: dev.tables index: _id_ dup key: { : "B85S9JSpnN2czdSLL" }"
```

It was caused by an action (a simple insert) that

a) hasn't changed in 6 months
b) hasn't caused any errors like this before

Immediately after the incident I tried causing the error again with poor results. It just worked for the next 100 or so inserts.

We are not using cluster module.

**Comment by divyanshupathak** [comment] 2017-03-21 07:43
Hello,
I am facing the same issue. Please give me some suggestion/help to resolve this issue.
Thanks.

**Comment by dnish** [comment] 2017-03-21 11:19
@helfer Would something like this fix the problem, or will Meteor try to add it again with the same id?


  'addMessage': function (message) {

        try {

            Messages.insert({
                text: message,
                userId: this.userId,
                createdAt: new Date()
            });

        }
        catch (e) {
            Meteor.call('addMessage',message);
        }
    }

**Comment by hwillson** [comment] 2017-09-08 19:29
Thanks for reporting this. Without a runnable reproduction demonstrating this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)) to test against, this type of issue is very difficult to troubleshoot. Since there hasn't been any activity on this issue in a while, I'll close it for now. If anyone is still encountering this problem (with a recent version of Meteor) and can supply a reproduction, I'll happily re-open this issue. Thanks!

**Closed by hwillson** 2017-09-08 19:29 UTC

**Comment by jamauro** [comment] 2021-02-11 22:09
@arggh were you ever able to diagnose the issue? Just experienced something similar to what you described.
