### ISSUE TITLE
[1.3] ReferenceError: Tinytest is not defined

### ISSUE THREAD

**Issue by CarlPhilippe** [meteor/meteor#6628] opened 2016-03-30 01:27 UTC
Trying to use Meteor 1.3 but got this error.

`W20160329-18:20:25.389(-7)? (STDERR) /Users/carl/dev/simple-todos/.meteor/local/build/programs/server/boot.js:324`
`W20160329-18:20:25.389(-7)? (STDERR) }).run();`
`W20160329-18:20:25.389(-7)? (STDERR)    ^     `
`W20160329-18:20:25.392(-7)? (STDERR) ReferenceError: Tinytest is not defined
W20160329-18:20:25.392(-7)? (STDERR)     at meteorEnv (packages/meteor.js:1388:1)
W20160329-18:20:25.392(-7)? (STDERR)     at Package (packages/meteor.js:1394:4)
W20160329-18:20:25.393(-7)? (STDERR)     at packages/meteor.js:2513:4`
`W20160329-18:20:25.393(-7)? (STDERR)     at packages/meteor.js:2527:3`
`W20160329-18:20:25.393(-7)? (STDERR)     at /Users/carl/dev/simple-todos/.meteor/local/build/programs/server/boot.js:283:10`
`
W20160329-18:20:25.393(-7)? (STDERR)     at Array.forEach (native)`
`W20160329-18:20:25.393(-7)? (STDERR)     at Function._.each._.forEach (/private/var/root/.meteor/packages/meteor-tool/.1.3.0_3.vqmt6x++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)`
`W20160329-18:20:25.393(-7)? (STDERR)     at /Users/carl/dev/simple-todos/.meteor/local/build/programs/server/boot.js:133:5
`

Tried:
- to remove Meteor with  `rm -Rf ~/.meteor` and to reinstall via `curl https://install.meteor.com/ | sh`
- to remove nodeJs and Npm and to reinstall them at the latest version

But nothing worked, still got this error for any Meteor 1.3 apps like simple todos, my_cool_app...

**Comment by derwok** [comment] 2016-04-02 14:40
I have the same issue. Working on a Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-042stab111.12 x86_64) box. Up till now meteor 1.2.1 worked happily on this machine. I did "meteor update" and hell brake loose - I always get "ReferenceError: Tinytest is not defined" - with same stacktrace as above.

As @CarlPhilippe I tried
* meteor re-install with curl ...
* creation of a fresh empty project with ```meteor create mytest```

```meteor --version``` gives Meteor 1.3
```node --version``` gives v0.10.25
```npm --version``` gives 1.3.10

Any help? Anybody?

**Comment by derwok** [comment] 2016-04-02 15:13
OK. Above was Ubuntu. Now testing meteor 1.3 on Mac OS X - I get the same issue!
So, either I am too stupid to perform ```meteor update``` or there is really a bad quality problem here...
This is really a showstopper for using 1.3.

As I'm not aware of a "re-install-older-version" script by MDG, to workaround the problem I'll launch my app via ```meteor --release 1.2.1```.
(Note: this only works, if you have versions & release file inside .meteor backups.)

**Comment by stubailo** [comment] 2016-04-05 23:05
This is odd - many people are using Meteor 1.3 and not encountering any issues like this. Can you please post the packages you're using in your app, and optimally a GitHub repository with a Meteor app that reproduces this issue?

**Comment by derwok** [comment] 2016-04-06 05:55
Working on my mac (Mac OS X 10.10.5), I have installed meteor 1.3 (with ```meteor update``` from 1.2.1). And all I need is create the fresh simple meteor example app with: ```meteor create NewApp```to get the error:

```bash
CL002533:~ wok$ meteor --version
Meteor 1.3
CL002533:~ wok$ cd source/
CL002533:source wok$ cd _js/
CL002533:_js wok$ meteor create delme
Created a new Meteor app in 'delme'.

To run your new app:
  cd delme
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn

CL002533:_js wok$ cd delme/
CL002533:delme wok$ meteor
[[[[[ ~/source/_js/delme ]]]]]

=> Started proxy.
=> Started MongoDB.

Unable to resolve some modules:

  "meteor-node-stubs" in
/Users/wok/.meteor/packages/modules/.0.5.1.499lul++os+web.browser+web.cordova/web.browser/packages/modules.js
(web.browser)
  "fibers" in
/Users/wok/.meteor/packages/promise/.0.6.5.3v1v4a++os+web.browser+web.cordova/web.browser/packages/promise.js
(web.browser)

Consider running: meteor npm install --save meteor-node-stubs fibers


Unable to resolve some modules:

  "meteor-node-stubs" in
/Users/wok/.meteor/packages/modules/.0.5.1.499lul++os+web.browser+web.cordova/os/packages/modules.js (os.osx.x86_64)

Consider running: meteor npm install --save meteor-node-stubs

W20160406-07:45:52.637(2)? (STDERR)
W20160406-07:45:52.637(2)? (STDERR) /Users/wok/source/_js/delme/.meteor/local/build/programs/server/boot.js:324
W20160406-07:45:52.638(2)? (STDERR) }).run();
W20160406-07:45:52.638(2)? (STDERR)    ^
W20160406-07:45:52.638(2)? (STDERR) ReferenceError: Tinytest is not defined
W20160406-07:45:52.638(2)? (STDERR)     at meteorEnv (packages/meteor.js:1388:1)
W20160406-07:45:52.638(2)? (STDERR)     at Package (packages/meteor.js:1394:4)
W20160406-07:45:52.639(2)? (STDERR)     at packages/meteor.js:2513:4
W20160406-07:45:52.639(2)? (STDERR)     at packages/meteor.js:2527:3
W20160406-07:45:52.639(2)? (STDERR)     at /Users/wok/source/_js/delme/.meteor/local/build/programs/server/boot.js:283:10
W20160406-07:45:52.639(2)? (STDERR)     at Array.forEach (native)
W20160406-07:45:52.639(2)? (STDERR)     at Function._.each._.forEach (/Users/wok/.meteor/packages/meteor-tool/.1.3.0_3.1nviyw3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160406-07:45:52.639(2)? (STDERR)     at /Users/wok/source/_js/delme/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
```

To get rid of the warnings, I do:
```
meteor npm install --save meteor-node-stubs fibers
meteor npm install --save meteor-node-stubs
```
and after this the warnigns are gone, but the error persists:
```
CL002533:delme wok$ meteor --port
[[[[[ ~/source/_js/delme ]]]]]

=> Started proxy.
=> Started MongoDB.
W20160406-07:53:50.203(2)? (STDERR)
W20160406-07:53:50.204(2)? (STDERR) /Users/wok/source/_js/delme/.meteor/local/build/programs/server/boot.js:324
W20160406-07:53:50.204(2)? (STDERR) }).run();
W20160406-07:53:50.204(2)? (STDERR)    ^
W20160406-07:53:50.205(2)? (STDERR) ReferenceError: Tinytest is not defined
W20160406-07:53:50.205(2)? (STDERR)     at meteorEnv (packages/meteor.js:1388:1)
W20160406-07:53:50.205(2)? (STDERR)     at Package (packages/meteor.js:1394:4)
W20160406-07:53:50.205(2)? (STDERR)     at packages/meteor.js:2513:4
W20160406-07:53:50.205(2)? (STDERR)     at packages/meteor.js:2527:3
W20160406-07:53:50.205(2)? (STDERR)     at /Users/wok/source/_js/delme/.meteor/local/build/programs/server/boot.js:283:10
W20160406-07:53:50.206(2)? (STDERR)     at Array.forEach (native)
W20160406-07:53:50.206(2)? (STDERR)     at Function._.each._.forEach (/Users/wok/.meteor/packages/meteor-tool/.1.3.0_3.1nviyw3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160406-07:53:50.206(2)? (STDERR)     at /Users/wok/source/_js/delme/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
```

What ist this stupid Tinytest for?
I dont want it. I dont need it?!

**Comment by stubailo** [comment] 2016-04-07 02:39
@benjamn this is very odd, any thoughts on what this could be?

**Comment by derwok** [comment] 2016-04-09 11:04
Great news: with meteor 1.3.1 the problem is gone on both machines where I had te above problem.
You can close this issue.

**Comment by stubailo** [comment] 2016-04-09 17:46
Awesome! Thanks.

**Closed by stubailo** 2016-04-09 17:46 UTC
