### ISSUE TITLE
Getting Error: Can't set timers inside simulations from observe on client

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2691] opened 2014-09-26 08:50 UTC
**_1 Upvote**_ I have such code on the client:

```
  TestCollection.find({}).observe({
    added: function (id, fields) {
      Meteor.setTimeout(function () {console.log("There is no bug? Strange.")}, 10);
    }
  });
```

I am getting:

```
Exception in queued task: Error: Can't set timers inside simulations
```

When trying to add an element on client with: `TestCollection.insert({})`

I think this is a bug because observe which is defined somewhere completely differently is run inside the simulation context. I think that this should not be like that but it should run normally (and then if insert is reverted, additional `removed` should be called in observe). In this way reactivity/observe works as expected and is decoupled from methods and simulations.

**Comment by mitar** [comment] 2015-01-17 00:59
How is this progressing?

**Comment by glasser** [comment] 2015-02-20 23:25
In general, the answer to "how this is progressing" is "it isn't, unless you actually see commits working on fixing it" :)

**Comment by mitar** [comment] 2015-02-20 23:29
I think that issues with unable to use Meteor.setTimeout inside observe is the biggest issue. So that after a client side method is run, observe callbacks keep running inside a noYieldAllowed.

**Comment by mitar** [comment] 2015-03-06 07:39
You cannot run Meteor.setTimeout, but also reactivity crosses over. If you have database insert inside an autorun, and then inside an observe somewhere else something which is reactive, that that reactive thing registers with the autorun, leading to crazy situations to debug. This is making the use of observes on the client really hard.

**Comment by avital** [comment] 2015-08-26 19:43
Accidentally fixed in d9fe23bc60234dbe72909c203ee10f75641e5820, should be out with Meteor 1.2!

I'd love a pull request adding a regression test for this particular issue though!

**Comment by avital** [comment] 2015-08-26 21:23
Somehow tests actually fail on d9fe23b (thanks @mitar for noticing). Apologies. I'm reverting this.

**Comment by avital** [comment] 2015-09-01 21:58
When we fix this, we should also merge in the following test: https://github.com/meteor/meteor/pull/5038

**Comment by davidworkman9** [comment] 2016-04-01 13:01
+1, would be nice if this gets fixed soon. Try making a ```Meteor.call``` inside an observe callback. You'll see it never actually gets ran on the server because it thinks it's still in a simulation.

**Comment by zimme** [comment] 2017-06-06 16:45
It seems that this issue is fixed with #8734.

**Comment by mitar** [comment] 2017-06-06 16:57
No it is not. ;-)

**Comment by hwillson** [comment] 2018-03-05 13:59
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity. If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!

**Closed by hwillson** 2018-03-05 13:59 UTC
Labels: Impact:few, Project:DDP, Project:Minimongo, Severity:has-workaround, confirmed, not-implemented, pull-requests-encouraged
