### ISSUE TITLE
Node cpu usage at >50% on idle

### ISSUE THREAD

**Issue by brettg2** [meteor/meteor#9022] opened 2017-08-17 18:09 UTC
We noticed this a few weeks ago and have yet to find a solution. Could this be something inherit with node? Would we need to downgrade Meteor? We are currently running Meteor version 1.5.1 on Windows 7 and 10 environments (plain cmd prompt). 

![image](https://user-images.githubusercontent.com/6796960/29426652-8c1694ea-8344-11e7-81da-f7e25a3116d5.png)

**Here is our package list:**
meteor-base@1.1.0
blaze-html-templates@1.0.4
jquery@1.11.10
tracker@1.1.3

es5-shim@4.6.15
ecmascript@0.8.1

fourseven:scss
fortawesome:fontawesome

lepozepo:accounting
momentjs:moment
standard-minifier-css@1.3.4
standard-minifier-js@2.1.1
oaf:moment-duration-format
flawless:meteor-toastr
mizzao:jquery-ui
reactive-var@1.0.11
ecwyne:mathjs
shell-server@0.2.4
numeral:numeral
alisalaah:jquery-contextmenu
reactive-dict@1.1.9
robertlowe:persistent-reactive-dict
meteor@1.7.0
webapp@1.3.17
icebrg82:blaze-magic-events
aldeed:template-extension
dynamic-import

**...and the versions file:** 
aldeed:template-extension@4.1.0
alisalaah:jquery-contextmenu@1.6.6
allow-deny@1.0.6
amplify@1.0.0
autoupdate@1.3.12
babel-compiler@6.19.4
babel-runtime@1.0.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.1.1
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
check@1.2.5
coffeescript@1.11.1_4
ddp@1.3.0
ddp-client@2.0.0
ddp-common@1.2.9
ddp-server@2.0.0
deps@1.0.12
diff-sequence@1.0.7
dynamic-import@0.1.1
ecmascript@0.8.2
ecmascript-runtime@0.4.1
ecmascript-runtime-client@0.4.3
ecmascript-runtime-server@0.4.1
ecwyne:mathjs@2.7.0
ejson@1.0.13
es5-shim@4.6.15
flawless:meteor-toastr@1.0.1
fortawesome:fontawesome@4.7.0
fourseven:scss@3.13.0
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.12
icebrg82:blaze-magic-events@0.0.6
id-map@1.0.9
jquery@1.11.10
lepozepo:accounting@1.0.0
livedata@1.0.18
logging@1.1.17
meteor@1.7.1
meteor-base@1.1.0
minifier-css@1.2.16
minifier-js@2.1.1
minimongo@1.2.1
mizzao:build-fetcher@0.3.2
mizzao:jquery-ui@1.11.4
modules@0.9.4
modules-runtime@0.8.0
momentjs:moment@2.18.1
mongo@1.1.22
mongo-id@1.0.6
npm-mongo@2.2.30
numeral:numeral@1.5.3_1
oaf:moment-duration-format@1.3.2
observe-sequence@1.0.16
ordered-dict@1.0.9
promise@0.8.9
random@1.0.10
reactive-dict@1.1.9
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
robertlowe:persistent-reactive-dict@0.1.2
routepolicy@1.0.12
shell-server@0.2.4
spacebars@1.0.15
spacebars-compiler@1.1.3
standard-minifier-css@1.3.4
standard-minifier-js@2.1.1
templating@1.3.2
templating-compiler@1.3.2
templating-runtime@1.3.2
templating-tools@1.1.2
tracker@1.1.3
ui@1.0.13
underscore@1.0.10
url@1.1.0
webapp@1.3.17
webapp-hashing@1.0.9

**Environment variables:**
METEOR_FS_FIBERS=1
MONGO_URL=none

Lastly, we don't have any server side code. The majority is front-end with an ajax call to our .NET/SQL backend.

Let me know if you need other information. Your help is greatly appreciated. Thank you!

**Comment by hwillson** [comment] 2017-09-14 18:08
Closing as a duplicate of https://github.com/meteor/meteor/issues/8803. Let's keep the discussion in that issue (which you've already commented on). Thanks!

**Closed by hwillson** 2017-09-14 18:08 UTC
