### ISSUE TITLE
meteor 1.6.1. strips font-families in css

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#9530] opened 2018-01-11 09:33 UTC
when i run meteor --production on a meteor 1.6.1-rc.2 app, custom fonts aren't loaded, because the some `@font-face` declarations are removed.

The delaration that gets removed is in 

```
@font-face {
  font-family: 'MyFont';
  src: url('/MyFont.eot');
  src: url('/MyFont.eot?#iefix') format('embedded-opentype'),
    url('/MyFont.woff2') format('woff2'),
    url('/MyFont.woff') format('woff'),
    url('/MyFont.ttf') format('truetype');
```

and is inside a a scss file (using fourseven:scss)

I think that is related to the update in the minifiers, maybe the path can't be resolved an the instruction gets stripped..?

**Comment by hwillson** [comment] 2018-01-11 18:45
Hmm - I'm not seeing this happen with `METEOR@1.6.1-rc.2`. I've created a simple reproduction to verify this is working [here](https://github.com/hwillson/meteor-issue-9530). Can you supply a reproduction that demonstrates this issue?

**Comment by macrozone** [comment] 2018-01-12 16:27
@hwillson sorry for not providing a good reproduction :-(. I hoped that someone else would have a similar problem or an idea.

Our guess is that it has to do with a feature from postcss that strips font-faces when the file is not found.

Can i leave it open until i can successfully reproduce it?

**Comment by hwillson** [comment] 2018-01-12 16:52
No problem at all @macrozone - we tend to close `needs-reproduction` issues that don't have a reproduction after 2 weeks or so.

**Comment by hrahuu** [comment] 2018-01-29 13:52
We had similar problem. The following nn CSS:
[ font-family: Helvetica, Arial, sans-serif, FontAwesome !important;  ]

was stripped to:
[ font-family: Helvetica, Arial,sans-serif!important; ]

After adding quotation marks around "sans-serif" result after was correct:
[ font-family: Helvetica,Arial,"sans-serif",FontAwesome!important;]

**Comment by macrozone** [comment] 2018-01-29 14:09
thx @hrahuu we will check

**Comment by hwillson** [comment] 2018-02-12 21:02
Since we haven't received a reproduction demonstrating this issue, I'll close this for now. We'll happily re-open this issue if anyone can provide a repro showing this problem. Side note - PR https://github.com/meteor/meteor/pull/9635 might be related (and was recently merged). Thanks!

**Closed by hwillson** 2018-02-12 21:02 UTC
Labels: Project:CSS, Project:Isobuild:Minifiers, can't-reproduce, needs-reproduction

**Comment by macrozone** [comment] 2018-02-13 08:01
@hwillson i did not test it, but i am pretty confident that this PR solved the issue, because of disabling `discardUnused`
