### ISSUE TITLE
Uncaught Error: Key $setOnInsert must not start with '$'

### ISSUE THREAD

**Issue by nadeemja** [meteor/meteor#9048] opened 2017-08-28 14:58 UTC
Hi,

In short: There's a mysterious, transient and devilish bug with all meteor releases since and including 1.5.2-beta152.0 (haven't tried 1.6), that adds a $setOnInsert key to my documents and then complains about it! 

Please see details and plot twists in the dicussion at https://forums.meteor.com/t/100-help-debug-uncaught-error-key-setoninsert-must-not-start-with.

I cannot provide repro-repo, but I'm comfortable adding any MDG official to our repository for a while if needed. 

Please let me know what I can do to help :) 

Regards, 

NadeemJQ

**Comment by abernix** [comment] 2017-08-28 16:15
First, please make sure you can reproduce the problem in the latest release candidate of 1.5.2: `1.5.2-rc.2`.

Second, I can understand not sharing your entire repository, but are you not able to create a basic reproduction with a new application created with `meteor create test-repo --release 1.5.2-rc.2` per the instructions in [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)?  We'd rather not dig into private repositories unless it's absolutely critical.

**Comment by nadeemja** [comment] 2017-08-28 16:33
I can confirm the issue with 1.5.2-rc.2, also. 

Thing is, I'm not sure what's causing the bug, so not sure what exactly the repro should contain.

If you're uncomfortable with a private repo, I'm willing to schedule a Skype-like meeting were we could look into it together. Possibly use some solution that allows sharing mouse/keyboard.

**Comment by abernix** [comment] 2017-08-28 16:59
I'm not uncomfortable with a private repository.  However, projects which are _needing_ to be private repositories are inherently more complicated and take a lot more time to debug than a simple reproduction which can quickly have it's code analyzed and third-party dependencies can be easily ruled out.  Scheduling a Skype-like screen sharing meeting only further complicates the matter.  Your help would be appreciated. :smile:

If this is in fact a bug in 1.5.2 and I had to take a guess, I'd look toward the changes in https://github.com/meteor/meteor/pull/8893 – though that's purely speculation.

**Comment by nadeemja** [comment] 2017-08-28 17:03
I understand :) 

Here's what I'm gonna do.

Instead of create repo from scratch, I'm just gonna copy my codebase and start stripping it until nothing but the absolutely relevant code remains. That shouldn't take too long. 

Will try to have something with the week. :)

**Comment by abernix** [comment] 2017-08-31 13:15
Any luck making a reproduction?  As it stands now, this is the only issue preventing the full release of Meteor 1.5.2 and while I don't believe this is an issue which is present in a bare Meteor application, if there is some interaction (or new bug we've somehow created) with a third-party package and we can prevent it, I'd like to make sure we do that before the final release!

**Comment by zimme** [comment] 2017-08-31 17:47
Could you give us the content of `.meteor/versions`? It might be worth looking into if it's a problem with any community packages that is manipulating the selector in any way.

**Comment by abernix** [comment] 2017-09-01 09:50
@sebakerckhof: @klaussner suspects (and I agree with his suspicion) that the changes from https://github.com/meteor/meteor/pull/8815 might be a contributing factor here.  Any thoughts?  I ask since you might be much more familiar with the code here and help to resolve it faster!

**Comment by sebakerckhof** [comment] 2017-09-01 10:02
Well, #8815 did introduce this line:
https://github.com/meteor/meteor/blob/devel/packages/mongo/mongo_driver.js#L582
Which seems like it might be related. However, for any further analysis I would at least need to know from @nadeemja :
1. Are you having this problem just with upserts?
2. What do you mean with "and then complains about it!", any specific error message?
3. Can you give any example query that gives this error?

**Comment by nadeemja** [comment] 2017-09-01 11:01
Hi everyone,

Sorry for being slow here, I've had a fever the last week and I'm still sick.

As this issue might be block the release of 1.5.2, I'm going to make an attempt at a reproduction today, and hopefully no later than tomorrow.

Thanks for your patience.

Regards,
Nadeem

**Comment by abernix** [comment] 2017-09-01 13:34
@nadeemja Much appreciated! I suspect you'll have the most success if you hone in on any cases where your application is doing `upsert`s.

I do suspect there is a bug here, but as it's a rather large change and `minimongo` has some other substantial refactoring done in this release already, reverting it may not be the most reasonable, though I'm prepared to do that until it can be re-worked if need be.

**Comment by nadeemja** [comment] 2017-09-01 14:37
Thanks, @abernix, @sebakerckhof 

I've been trying to create a repro for about an hour or so now. But, it's proving really tricky. 

The issue is transient in the first place, so I really don't know if I've removed chunks of code that "solves" it or if there remains code that "causes" it. So I'm going back and forth between stripping away and re-adding code. This is gonna take longer than I expected. 

I just scanned my entire codebase for `upsert`. I'm never doing upserts client-side. Also the upserts I am doing are unrelated to where the error occurs. 

To answer your questions @sebakerckhof:

1. No, not really, as I'm not doing any relevant upserts. 

2. Please see the first post in this thread:
https://forums.meteor.com/t/100-help-debug-uncaught-error-key-setoninsert-must-not-start-with/38843

3. I have no idea what is causing this, or even if it's a query. 

I will continue stripping/re-adding code for a while and see if I can narrow it down.

I'm also open to attacking this from another angle: Try out a supposed "fix" assuming that the problem is related to "/packages/mongo/mongo_driver.js@devel#L582". If this indeed is the culprit, then what would be a remedy? Testing the hypothetical remedy - by me running a modified meteor version - might be faster and confirm the bug before a reproduction is ready.

What do you think?

**Comment by sebakerckhof** [comment] 2017-09-01 15:01
Then it must be a different issue, since that line I mentioned is only being called for upserts.
The error comes from this line btw: https://github.com/meteor/meteor/blob/devel/packages/minimongo/local_collection.js#L1884

Can you also get a stack trace in development mode instead of on a production build? Might tell something more.

You don't actually need a full reproduction, minimongo is deterministic, so as long as you can give the query that causes this we should be able to reproduce this. (which shouldn't be too hard to find if you just work your way up the stack trace and put some logs)

**Comment by klaussner** [comment] 2017-09-01 16:45
> I just scanned my entire codebase for `upsert`. I'm never doing upserts client-side. Also the upserts I am doing are unrelated to where the error occurs.

I think that the error isn't caused by an `upsert` on the client. The stack trace you posted starts at `r.ws.onmessage`, where the client seems to receive a [DDP message](https://forums.meteor.com/t/100-help-debug-uncaught-error-key-setoninsert-must-not-start-with/38843/7) with an invalid `field` (`$setOnInsert`) from the server. The error is thrown when the local `minimongo` collection is updated with the fields in this message.

**Comment by nadeemja** [comment] 2017-09-01 17:13
@sebakerckhof 

That stack trace is from development. I've tried climbing it: 
https://forums.meteor.com/t/100-help-debug-uncaught-error-key-setoninsert-must-not-start-with/38843/7?u=nadeemjq

As I indicate on the forums, I'm unable to use the stack trace to identify the query involved, except that it is inside a subscription.

How do I figure out which query is causing it? How can I see what queries are involved up until the error?

**Comment by nadeemja** [comment] 2017-09-01 19:28
Everyone,

I'm not really sure if I can produce a repro or something else useful to you in a short timeframe. 

If you are comfortable releasing 1.5.2 with this open, that is of course your decision to make entirely. 

I really want to use 1.5.2 and so I'll try my best to keep momentum in resolving in this issue.

Regards,

Nadeem J. Q.

**Comment by klaussner** [comment] 2017-09-02 18:46
@nadeemja It's hard to debug this issue without knowing more about your app but here are some things you could try:

1. In the Chrome DevTools, go to Network → search for and select "websocket" → select the "Frames" tab. Check the `added` messages that were received before the error is thrown and look for the `$setOnInsert` key in the `fields` object. If the key exists, we know that the server sent an invalid update.
2. Comment out all `upsert`s for the `schedules` collection on the server (if that's possible), reset the database (and manually insert some schedule documents?), and check if the error still occurs. If yes, the changes from #8815 are probably not the origin of the problem, as @sebakerckhof mentioned.

Regarding the first point: an `added` message is sent for one of two reasons: (1) a new document has been added to the database and is sent to the client or (2) (more likely, based on your explanation) the client receives a document as part of the initial results of a subscription. You said that the error occurs when you visit a specific route, so maybe you are subscribing to a publication for `schedule` documents and the server responds with an `added` message containing `$setOnInsert`, which the client can't handle.

Also, is there anything unusual about your Meteor setup? Are you using the MongoDB version that is provided by Meteor? Are you using third-party packages that modify collections or are related to DDP? Is another process (not Meteor) writing to the database?

**Comment by abernix** [comment] 2017-09-03 18:57
@nadeemja: If you can reliably reproduce this in your private repository and are willing to share your private repository with me along with reproduction instructions, I'll take a look and see what I can uncover.  I can be found under the same username on the Meteor Forums.

**Comment by nadeemja** [comment] 2017-09-04 18:16
Hi guys,

Apologies for taking so long to respond, and my replies will have to wait a little longer.

But, I wanted to say that 2 seconds ago I observed this very same error on _1.5.1_ in a completely different codebase. I'm investigating, but this might mean that 1.5.2 is not to blame after all.

**Comment by abernix** [comment] 2017-09-05 11:40
Given this recent information and without a more concrete reproduction, I'm not going to hold up the 1.5.2 release any longer, which I've done out of an abundance of caution up until now.  I've tried to reproduce this in a number of applications, but haven't caught wind of it.  If this does cause a problem, the downgrade to 1.5.1 should be relatively easy and package patch updates to `minimongo` and/or `mongo` should be easy.

**Comment by nadeemja** [comment] 2017-09-15 15:10
Hi there,

I'm still working on this. Have a quick question: 

Is Collection.upsert and Collection.update(...., {upsert: true}) equivalent in this regard?

**Comment by sebakerckhof** [comment] 2017-09-15 15:27
Yes

**Comment by hwillson** [comment] 2017-10-13 19:39
Since we haven't received a reproduction demonstrating this issue, I'll close this off for now. Happy to re-open if anyone can provide a repro. Thanks!

**Closed by hwillson** 2017-10-13 19:39 UTC
Labels: can't-reproduce
