### ISSUE TITLE
Meteor 2.0 HMR not refreshing after CSS file goeing back to its original state.

### ISSUE THREAD

**Issue by abolo** [meteor/meteor#11300] opened 2021-01-21 20:27 UTC
Hi there! We're so happy to finally have HMR in Meteor 2.0! 🎉 We've been trying the new release and found some strange behaviour with HMR and css files.

We're working on a Meteor + React app. 
Somewhere in our app React side we import a BlogPost component which imports its own css file:

`import "./blogpost.css"`

Let's say `blogpost.css` has the folowing content:

```
h1 {
    font-size: 24px;
    font-weight: bold;
}
```
If we add a new rule to h1 element, i.e. `color: red`, HMR works fine, the app updates and the h1 element becomes red.
If we change this new line to `color: blue` it also updates fine and the h1 becomes blue. But then, when removing this rule, the css file goes back to its original state and no HMR is fired (the h1 stays blue). 

It seems that a css file going back to its original state when Meteor started is not firing an HRM update. We've tested and it doesn't seem to happen with js files, only css.

Thanks!

**Comment by filipenevola** [comment] 2021-02-01 20:40
Hi, I just created a new Meteor app using `meteor create my-app` and it's working as expected.

I did the same changes as you described above in the `main.css` file and the result was always what I had expected and not the problem that you reported above.

Could you provide a reproduction? 😉 Read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)

**Comment by StorytellerCZ** [comment] 2021-04-23 08:51
Hi @abolo since we still don't have a reproduction I will close this issue for now. If you can provide a reproduction please re-open this issue again.

**Closed by StorytellerCZ** 2021-04-23 08:51 UTC
Labels: needs-reproduction
