### ISSUE TITLE
ES6 not working in certain scenarios especially when putting code in "tests" folder

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#6899] opened 2016-04-25 14:43 UTC
Meteor 1.3.2.4

Reproducing it in repo: https://github.com/theodorDiaconu/meteor-testing-issue

**Issue 1**
If I put in my package, in ./tests folder the main module for testing and I import the test file within the same folder. ES6 is not available.

**Issue 2**
If I put code in ./testing folder, and run the imports, es6 will still fail.

**Comment by theodorDiaconu** [comment] 2016-04-25 14:46
Update: if in package folder I use any other name for the folder instead of "tests" it works.
If in the root folder if I use other prefix than .test.js it works.

**Comment by abernix** [comment] 2016-06-30 14:37
Thanks for the reproduction repo!

It appears that this problem appears when trying to import things across testing boundaries – for example when importing an `.app-test.js` file from a `.test.js` file (or vice versa).  If the file you are importing is simply `something.js` (for example), it processes it as ES6 accordingly.

Really though, I'm not sure if importing across modes like this is _intended_ to work and perhaps it should be avoided.  It's my understanding that `.test.js` and `.app-test.js` files are purely meant to give the testing framework entry points into the test modes (`meteor test` and `meteor test --full-app` respectively).  From those files, it's possible to import any `.js` files necessary and since  `.js` files within the `imports` directory aren't eagerly loaded, it works out fine.  Shared libraries between testing modes could just be `.test-lib.js` or something if you wanted to have a particular naming convention.

**Comment by abernix** [comment] 2016-07-01 17:24
I just ran into this issue myself in a slightly different configuration with a `tests` folder inside `/imports`/ and while not crossing test mode boundaries at all.  Probably the same bug though.  I'll investigate more next week.

**Comment by theodorDiaconu** [comment] 2016-10-18 08:37
Any update on this ?
I ended up having "testing" folders in my packages

**Comment by hwillson** [comment] 2017-12-19 20:50
I've updated your repro to Meteor 1.6.0.1 and tested things out; ES6 seems to be working properly (your `should crash` is not crashing). I'll close this issue for now, but I'm happy to re-open it if you're still seeing this happen. Thanks!

**Closed by hwillson** 2017-12-19 20:50 UTC
Labels: bug, confirmed, Impact:few, Project:Testing
