### ISSUE TITLE
Client-side observe misses documents

### ISSUE THREAD

**Issue by xwilders** [meteor/meteor#7270] opened 2016-06-21 10:23 UTC
This behaviour happens on meteor 1.3.3.1, and is fixed by reverting to meteor 1.3.2.4. 
(Chrome, OS X El Capitan, no package dependencies)

I have a publish function on the server that observes a collection A and calls self.added 60 times on newly observed documents (adding them to a client-side collection B).

A client observe on B calls console.log on each document that was added. With meteor 1.3.2.4, all documents come through. With 1.3.3.1, a few documents are 'missed' (roughly 5 out of 60), so it might look like the following: 
Server sends documents 0, 1, 2... 60
Client observes 0, 1, 2, 3, 5, 6, 7, 8, 9, 11...

**Comment by benjamn** [comment] 2016-06-21 15:45
Could this be due to the [DDP update batching changes](https://github.com/meteor/meteor/pull/5680) in Meteor 1.3.3?

**Comment by abernix** [comment] 2016-06-27 14:31
@xwilders Can you please post a reproduction git repo?  Otherwise we'll have to close this issue as not reproduceable.  As stated above, it could be due to DDP batching updates (for example, they might be entering your code from `changed` instead of `added`), but it would be nice to take a look.

**Comment by xwilders** [comment] 2016-06-28 17:44
@abernix I'll take a closer look this week when I have some free time and report back!
In my application I've relied quite heavily on the assumption that anything observed in 'change' would have previously been seen in 'added' so maybe it's just that that assumption no longer holds.

**Comment by xwilders** [comment] 2016-07-01 17:06
Here you go: https://github.com/xwilders/observeTest
The above works with meteor 1.3.2.4 (ie every document is observed by the client's 'added') but fails with latest.

The most contentious part is:
`const handle = Collection.find({}, {
    sort: { insertedAt: -1 },
    limit: 1,
  }).observe({...})`
ie the client wants to be notified of each newly inserted document, without maintaining a huge mergebox. Setting 'limit' to the amount of documents we're inserting is a solution, but not so ideal when dealing with a great many documents.

**Comment by abernix** [comment] 2016-07-06 08:12
@xwilders Thanks for the reproduction; I can see the problem you're experiencing.  It is due to the DDP batching as @benjamn suggested and as you said, it's the combination of the rapid succession with the limit.  I imagine documents are just gone before they are delivered.

You can work around it by disabling the buffering which is taking place.  It hasn't been a popular need and isn't normally recommended, so it isn't possible to change the default options on a connection.  However, it can be done after-the-fact on the `Meteor.connection` object which is exposed to the client:

    Meteor.connection._bufferedWritesInterval = 0;

Simply set this [before your subscription is made](https://github.com/xwilders/observeTest/blob/master/client/main.js#L12) and the problem should go away (it does in the reproduction):

I'm not sure if Meteor needs to make any changes for this, but it is a bit confusing to the end-user.  Perhaps it should just be documented?

@tmeasday, @mitar and @nathan-muir might have some input too.

**Comment by mitar** [comment] 2016-07-06 19:25
So disabling merge box will probably not solve the problem that client-side things are batched. These two things are solving two separate problems: batching on the client CPU usage when many changes come, merge box CPU and memory usage on the server when many documents are published.

Often, if you really want to know all changes to documents you also do not want CPU and memory on the server to be used (because all this diffing for many changes can be expensive), it is then easier to just stream changes yourself using https://github.com/RocketChat/meteor-streamer. I think this is a better solution then disabling batching and merge box.

**Comment by tmeasday** [comment] 2016-07-07 00:09
I agree with Mitar. I think if you want to stream events to the client, using both a DDP `added` + `removed` message seems like an inefficient way to do it.

**Comment by xwilders** [comment] 2016-07-07 11:18
From my research, it seems refactoring as below solves the issues I've been having. It also means I can remove the limit, keep server-side CPU and memory usage low, and still use native Meteor syntax rather than meteor-streamer (at the expense of feeling a bit hacky):

```
const handle = collection.find(userSpecificSelector, {
    sort: {
      insertedAt: -1,
    },
  }).observe({
    added(doc) {
      doc.id = doc._id; // this is how client's get the real id
      const disableDocCaching = ... // Copy of the last changed doc, except every value is undefined
      
      self.changed(eventStreamCollection, "someConstantId", _.extend(disableDocCaching, doc));
    },
    changed(doc) { ... },
});

self.added(collection, "someConstantId", {});
```

In my case, eventStreamCollection is a client-side collection unique to each client. I'm unsure how adapted meteor-streamer is to this use case.

**Comment by mitar** [comment] 2016-07-07 16:06
Hm, doing `observe` instead of `observeChanges` is much heavier and it requires potentially more caching on the server.

> I'm unsure how adapted meteor-streamer is to this use case.

I think it should work.

**Comment by hwillson** [comment] 2017-03-26 14:34
Since there are workarounds to the original issue (outlined [here](https://github.com/meteor/meteor/issues/7270#issuecomment-230706699) and [here](https://github.com/meteor/meteor/issues/7270#issuecomment-231050645)), and it doesn't appear as though there is anything that needs to change with Meteor to address this, I'll close this issue off. Thanks for reporting this originally!

**Closed by hwillson** 2017-03-26 14:34 UTC
Labels: bug, confirmed, Impact:few, Project:DDP

**Comment by mitar** [comment] 2017-03-26 19:18
My only issue is that `Meteor.connection._bufferedWritesInterval` is internal thingy. We might want to expose a method to configure those values.

**Comment by hwillson** [comment] 2017-03-26 19:44
Hmm - good point @mitar. I guess for this specific issue it doesn't really matter since the final solution didn't end up manipulating   `Meteor.connection._bufferedWritesInterval` to work around the original problem. If manipulating `Meteor.connection._bufferedWritesInterval` is something that becomes more common place though, then we should definitely consider making it more public (and mentioning it in the docs). Interestingly enough, there is already a public way of setting this value if using [`DDP.connect`](http://docs.meteor.com/api/connections.html#DDP-connect). The docs don't show this, but `DDP.connect` can accept an `options` object (as the second argument). If the `options` object includes a `bufferedWritesInterval` property, the connection's internal `_bufferedWritesInterval` property will be set accordingly. 

I guess since manipulating the `Meteor.connection._bufferedWritesInterval` setting doesn't appear to be that common, we can leave this issue closed for now (let me know if anyone disagrees). That being said, I'm not sure why `DDP.connect`'s options argument isn't documented - I'll open an issue about this in the docs repo. Thanks!

**Comment by mitar** [comment] 2017-03-26 20:57
The issue is also that `DDP.connect` options work only for non-default connection. But how do you pass options to default connect? (How are settings to the connection for Cordova apps passed?)

**Comment by mitar** [comment] 2017-03-26 21:00
Maybe we could use `__meteor_runtime_config__`?

**Comment by xwilders** [comment] 2017-03-27 08:57
FYI following the comment made by @mitar I've been using https://github.com/RocketChat/meteor-streamer for this use case, and it works extremely well. Thanks!
