### ISSUE TITLE
Jquery-waypoints

### ISSUE THREAD

**Issue by tdmoneybanks** [meteor/meteor#3908] opened 2015-03-10 22:53 UTC
the package doesnt have its own github so sorry if this is the wrong place to ask the question!
I am trying to use waypoints with meteor but having problems setting up a waypoint. 
I am just trying to use the simplest waypoint from the waypoint getting started docs and getting this in the console "uncaught reference Waypoint is not defined" any help would be appreciated!
Thanks.

**Comment by glasser** [comment] 2015-03-17 21:14
Duplicate of #3771

**Closed by glasser** 2015-03-17 21:14 UTC
Labels: Project:Utilities
