### ISSUE TITLE
1.3 beta 12: App works, then fails if I comment out import of no-longer-defined variable

### ISSUE THREAD

**Issue by ndarilek** [meteor/meteor#6364] opened 2016-02-28 20:20 UTC
I apologize for the somewhat amature nature of this bug report, but I don't know if I've hit some subtle module issue or if I've made some equally subtle mistake on my part.

In short, I have a somewhat complex Meteor app that is a tower of dependencies--Mantra, React, and various assorted modules. I have the line:

```
import {authState} from "../"
```

in a container component. `authState` once existed but doesn't any longer, so it resolves to undefined. If I comment that line out, my app fails to load with the following error:

```
Error: Curry function of composeAll needs an input.
```

and none of my app renders.

I get that this error is in react-komposer, and I've filed [an issue there](https://github.com/kadirahq/react-komposer/issues/42), but I can't help but think that if something is failing or succeeding based on the presence of an import line that pulls in a non-existent export, then something is seriously broken in the module system.

Unfortunately, I can't create a smaller reproduction. I've gotten things working again by stripping out lots of modules and adding things back, but I can't figure out why adding a given component back causes the error. I've done lots of refactoring lately, and it's quite possible that my code is erroring at some level, but I'm wondering if something in the module loader/compiler is swallowing an exception or something. To say that this failure case is driving me crazy is not much of an overstatement. :) At no point in this process do I get a useful exception about something in my module not compiling and thus causing this higher-level react-kompose error. Even so, at various points when I've hit this issue I _have_ uncovered errors in my modules, and it seems like those should have been reported but weren't.

Does this at all sound like an error that may have been fixed since beta 11? If so, awesome. If not, is there some way I might tar up and deliver my app privately for investigation? Sorry, not trying to score free consulting/support, but given that modules are a big focus of 1.3 and my problem seems module-related, I'm wondering if I've uncovered a serious bug that is too subtle for me to spot.

Additionally, if anyone has any advice for how to debug this further locally, that would be great. It just seems like an import of an undefined variable that is never used would be a no-op, so if stripping out a no-op causes my app to fail, then I just don't know what else I can do.

Thanks.

**Comment by Menda** [comment] 2016-02-29 09:34
Maybe I'm wrong, but when you `import {authState} from "../"`, you should at least provide a js file, right? For example `import {authState} from "../authstate-module.js"`.

**Comment by ndarilek** [comment] 2016-02-29 10:47
Would it not resolve to index.js like other directory imports?

But if you're right, then I'd expect commenting it out to fix the issue, 
not cause more errors. :)

**Comment by Menda** [comment] 2016-02-29 10:53
No, you need to import it explicitly were the export is done. If it's an installed module, then it works different (check this: https://github.com/meteor/meteor/blob/release-1.3/packages/modules/README.md)

**Comment by ndarilek** [comment] 2016-02-29 11:01
What part of that page would you have me read? I read it closely weeks 
ago, and was familiar with Node modules besides. If you search for 
"index.js", it seems to imply that import rules are the same--either 
index.js or the "main" field. Note that the README explicitly states 
"Node" modules, not NPM, which indicates identical behavior since my app 
modules are now Node modules.

But again, if you're right then I've deleted a bug, so my app should 
*start* working, not *stop*. Sorry, not trying to be snappy, I've just 
tried everything I can think of here *including* explicitly importing 
index.js in these cases. I'd note that I also have a bunch of other 
places where I'm counting on index.js being implicitly added and it is. 
This issue is getting under my skin. :)

**Comment by ndarilek** [comment] 2016-02-29 16:53
FWIW, same exact behavior when I run with the release-1.3 branch. Is there any way to enable some sort of enhanced logging or some other feature now that I'm running out of git? I'm not nearly smart enough to attempt debugging a module system but am happy to provide whatever I can.

Thanks.

**Comment by ndarilek** [comment] 2016-02-29 17:20
Another data point, not sure if it helps but I'm trying to provide all that I can:

Running out of things to try, I tried running my app with `--production`. The behavior is almost identical, but now I get this error in the failure case:

```
detailed error: TypeError: Package['service-configuration'] is undefined
```

If this wasn't an error in the module bundler, then shouldn't it simply fail in my own code, instead of also throwing this error as well?

**Comment by ndarilek** [comment] 2016-02-29 20:44
I have a zip file containing my app with node_modules, .meteor/local, local provisioning, settings, etc. stripped out, and a README.md explaining what line of what file to comment out to cause this. Unfortunately I'd rather not release it publicly since it's a commercial app, but it's 100% replicable even in this clean room environment. If there's official interest then do let me know and I can deliver it, it's 158K so not too large.

**Comment by ndarilek** [comment] 2016-03-01 05:49
OK, I swear I'm not on crack.

Commenting out the dreaded line whose tokens I will not type causes my Home component, the one that renders my app's homepage, to be undefined at the point where it is constructed into a container. That at least would explain the `composeAll` failure even though it doesn't get at underlying causes. I placed `console.log` calls around every `composeAll` call and saw the one for `Home` not completing. Even worse, I place a `console.log` call on top of home.jsx. Commenting out the infernal no-op import of doom somehow causes home.jsx not to import, thus causing `Home` to be undefined. I don't understand how not importing an undefined variable that is never used anywhere can cause an unrelated file in a different module to never import when it *is* explicitly imported.

This has to be a subtle module bug. I'm sure my code has an error somewhere--maybe I'm not importing a module correctly--but Meteor needs to report that rather than uber-fail.

Taking a mental health break from this app until I get some responses. :) I've been programming for nearly 30 years and this is probably one of the most (if not the most) baffling bugs I've ever encountered.

Thanks for any help.

**Comment by ndarilek** [comment] 2016-03-01 15:01
Same issue under beta 12.

**Comment by stubailo** [comment] 2016-03-01 23:16
Have you tried clearing your local build data? Sometimes, especially during a beta, the build system gets into an inconsistent state. Perhaps there is some file that is not being rebuilt correctly.

The build caches are in `.meteor/local`, so you can try deleting all of them and running your app again.

**Comment by ndarilek** [comment] 2016-03-01 23:27
Thanks for the tip. I ran `meteor reset` multiple times, which I assume 
should do that?

I did a bit more digging. client/modules/core/components/home.jsx 
imports a Dashboard component from client/modules/dashboard/ and a 
Landing component from client/modules/landing/. If I replace 
client/modules/core/components/home.jsx with something like:

```
export default () => <p>Welcome home.</p>
```

then it works. If I import the Dashboard or Landing components into 
home.jsx, then the home.jsx component doesn't appear to import at all, 
even if I never reference any of the imported components therein.

I don't know enough about the modules support to know if perhaps it 
breaks down if an app defines something 2-3 modules deep? Tomorrow I'm 
going to try a stripped-down reproduction that does this. My initial 
stab at a reproduction didn't have a deep module dependency tree.

**Comment by ndarilek** [comment] 2016-03-02 00:56
OK, I have a reproduction. https://github.com/ndarilek/meteor-modules-mystery Perhaps I'm doing something obviously stupid and wrong here, I've been fighting with this issue and ones like it for the past 4-5 days. :)

**Comment by zol** [comment] 2016-03-02 01:42
@ndarilek - Could you please whittle the code down to just the absolute bare minimum that triggers the issue. Often that process reveals more clues (and sometimes the answer). Thanks!

**Comment by ndarilek** [comment] 2016-03-02 01:45
Please see the comment right above yours. This is about the smallest I can make it, including a README.md pointing to the line to comment out and a few specific questions regarding the behaviors that triggers.

Thanks.

**Comment by zol** [comment] 2016-03-02 01:53
@ndarilek - There are many other files and lines of code in the repo that don't involve the issue itself. See the reproduction recipe [here](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor)

**Comment by ndarilek** [comment] 2016-03-02 03:29
Fair enough, though since I think the problem involves modules, there's 
a limit to how far the recipe will go (I.e. reducing to the fewest files 
will eliminate the very error conditions I'm testing for.)

Please see the repository again. This is the bare minimum needed to 
reproduce the issue. I'm also posting it to a react-komposer issue I 
filed a few days ago since that is one component I couldn't remove.

Thanks.

**Comment by zol** [comment] 2016-03-03 18:53
Thanks, we'll take a look when we have a moment.

**Comment by ndarilek** [comment] 2016-03-03 19:08
Cool, just paired the repro down further. It now no longer requires mantra-core, just react-komposer. There are now 2 separate isolated instances where importing a module causes this behavior.

Thanks!

**Comment by benjamn** [comment] 2016-03-08 19:58
Removing, adding, or rearranging `import` statements or a `require` calls can alter the load order of modules in ways that expose circular dependency problems in CommonJS, *even if the files you're modifying are not part of the cycle*. Here's a simplified [example](https://youtu.be/-zch_YmKfa0?t=8m5s) involving just three files, in case that gives you a better model of what might be going on.

Using ES2015 `import` in your own code will mostly protect you from this problem, as explained [here](https://github.com/meteor/meteor/issues/6381#issuecomment-193938592), but unfortunately you may be running into CommonJS circular dependency fragility in the npm packages that you're using.

I'll take a look at the reproduction and let you know if I can figure it out!

**Comment by ndarilek** [comment] 2016-03-25 12:51
So it looks like this has been bumped for after 1.3?

I ask because I hit it *yet again*. Was moving an app to Mantra and started getting `undefined` for very simple scenarios where I'd literally copied container definitions, tweaked them to ensure that the component names matched, then imported the exported functions. At time of export, the function is defined. But, mysteriously, it goes undefined when it is imported. I've quadruple-checked that I'm not referencing an undefined variable or anything. At this point I don't even bother debugging this one because I know that way lies madness. :)

If this were some minor thing I'd say fine, bump it. But as described earlier in this thread, literally changing the order of imports can cause something to go undefined. Is that not critical enough to land in 1.3?

I've upgraded the testcase to RC12 and the problem still exists.

Thanks.

**Comment by abernix** [comment] 2016-11-25 22:22
Closing due to lack of reproduction.

**Closed by abernix** 2016-11-25 22:22 UTC
Labels: Project:Isobuild
