### ISSUE TITLE
Meteor 1.6 bundled npm fails to build meteor-useraccounts/flow-routing

### ISSUE THREAD

**Issue by nethoncho** [meteor/meteor#9313] opened 2017-11-07 05:49 UTC
I have a detailed report on the flow-routing repo 
meteor-useraccounts/flow-routing#56
Looks like it is related to #9310 and #9300
OS: Ubuntu 10.04.3 x64 DigitalOcean droplet
Fresh install of Meteor 1.6
meteor create --bare testApp
meteor add useraccounts:flow-routing
=> Errors while adding packages:

**Comment by nethoncho** [comment] 2017-11-07 10:01
I believe this is an issue with dependencies not being resolved. I added kadira:flow-router then useraccounts:flow-routing built with out any issues.

**Comment by hwillson** [comment] 2017-11-07 13:54
Thanks for reporting this @nethoncho - this is a duplicate of https://github.com/meteor/meteor/issues/9310 (returns the same `Error: Cannot find module 'internal/util/types'` error), so let's move the discussion over there.

**Closed by hwillson** 2017-11-07 13:54 UTC
