### ISSUE TITLE
Cordova CORS issue

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#4132] opened 2015-04-05 17:02 UTC
I'm getting errors like `XMLHttpRequest cannot load http://192.168.8.109/. Origin http://meteor.local is not allowed by Access-Control-Allow-Origin.`

This is unexpected because the origin rule is set to `*` (wildcard)

Can be reproduced with a blank project

I have `mobile.config.js`

```
App.accessRule("*")
```

Edit the main js file to:

```
Template.hello.events({
    'click button': function () {
      // increment the counter when button is clicked
      Session.set('counter', Session.get('counter') + 1);

      HTTP.post("http://192.168.8.109", {
      }, function(err, result) {
        alert("POST " + err);
      })

      HTTP.get("http://192.168.8.109", {
      }, function(err, result) {
        alert("GET " + err);
      })
    }
  });
```

Tried on both iOS (8.1 iPhone 5) & Android (4.1 Samsung Galaxy S3).

**Comment by chrisbutler** [comment] 2015-04-05 21:03
+1

**Comment by jms301** [comment] 2015-04-07 17:38
This seems the same as https://github.com/meteor/meteor/issues/3469#issuecomment-88575124

**Comment by Tarang** [comment] 2015-04-07 18:07
@jms301 This is slightly different. That issue is about the DDP server marked with `--server`. This one is with a non DDP server/a unrelated REST api.

I think if you specify the DDP server the `accessRules` is changed to add it in but it only applies to that DDP server.

The difference is say you have a DDP server used to update the app's HTML/js files yet still use a 3rd party API based on a REST api.

I got passed this using the package at https://github.com/wymsee/cordova-HTTP. This is not as intuitive at it should be however. Meteor's HTTP package is perfectly fine, not to mention it easily does POST requests with JSON as the body data which the cordova package doesn't do.

**Comment by Slava** [comment] 2015-04-14 20:57
Access-Control-Allow-Origin (set by the response headers of your server) is not the same as access rules you set for your Cordova apps. I know it is confusing, but the `App.accessRule` record should not help you at this.

My understanding is, it can be solved by setting a response header in Meteor's "on-device" server: https://github.com/meteor/com.meteor.cordova-update/blob/master/src/ios/METEORCordovaURLProtocol.m#L57

I would love to know if you hit the same error running on older versions of Meteor (like 1.0).

**Comment by Tarang** [comment] 2015-04-15 07:15
@Slava Yes I think this is the way to fix it. At the moment there is no way to change that. 

It would be helpful if it matched up to the defined `accessRules`. I'm not absolutely certain whether this is the way to go. I know that you can have plugins which can do this anyway, but it would be much nicer to use Meteor's built in HTTP package.

Before the device server was used there was a brief moment it worked when cordova was still new. I don't remember the exact version number

**Comment by Lenin7** [comment] 2015-05-15 23:25
any updates on this?

**Comment by Slava** [comment] 2015-05-22 00:34
Your solution (or a workaround) would be allowing `meteor.local` in the `browser-policy` package, not changing the mobile app. You can learn more about CORS and how headers work on MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

```javascript
BrowserPolicy.content.allowOriginForAll("http://meteor.local");
```

in your server code should do the trick (from my understanding of the issue). Learn more about the `browser-policy` package here: https://atmospherejs.com/meteor/browser-policy

**Comment by Slanman3755** [comment] 2015-06-05 19:06
Copied from 3469:
@Slava I am still having this exact issue with my app. I am running the app on Android 4.1 though. I am trying to make an ajax call to one of our servers (cross-domain). The server is running Nginx but is configured with CORS. I can make ajax requests with no issues from my browser but when making the request from my phone I get "XMLHttpRequest cannot load https://foo.website.com/place/?get. Origin http://meteor.local is not allowed by Access-Control-Allow-Origin." I have implemeneted App.accessRule("*") but it did not seem to change anything. I've wasted a lot of time on this issue and I can confirm it definitely is still an issue so I'm not sure why it is closed.

**Comment by Tarang** [comment] 2015-06-06 14:21
I think for people that understand how CORS works this is still an issue.

If you're making an API call to some random website there's no way to get them to set CORS headers for you.

I think there should be a way to get the app to ignore the CORS issue somehow. I suggest perhaps modifying the http package so it doesn't use XMLHttpRequest request, rather proxies the request through a cordova plugin natively.

**Comment by Slava** [comment] 2015-06-11 23:40
@Tarang If a 3rd party website prevents other websites from fetching data from them - there is a reason for it and browsers obey this behavior.

The goal of the Meteor Mobile is to provide an environment very close to a mobile browser with some additional functionality (offline code access, updates, etc) and access to native APIs through Cordova.

If you really want to fetch the data that your browser client is not allowed to fetch (according to CORS response headers), then you can either fetch the data through your server or access native APIs to make a request yourself.


For fetching data from your website, configuring the CORS headers with the `browser-policy` package is a valid workaround.

**Comment by candicom** [comment] 2015-07-04 03:19
client/app.js
Meteor.startup(function() {
if(Meteor.isServer) {

BrowserPolicy.content.allowOriginForAll("http://meteor.local");

}
});

It worked.. But I don't know the reason. Any other case, all has an error like ReferenceError: BrowserPolicy is not defined

And... client directory is for client source code. But It worked only if(Meteor.isServer) in client directory

It is a little bit odd... Can I use Meteor.isServer in client directory?

**Comment by Lavan** [comment] 2015-07-05 13:53
@candicom No, you can't use Meteor.isServer on the client, or rather it will always return false. So what you did is to add server only code to the client side and then avoided executing it using a condition that always returns false.

So in essence you can just remove that block of code. :smile:

**Comment by candicom** [comment] 2015-07-06 02:51
But I tested. And tried all. And the only working solution was  if(Meteor.isServer) in client directory.
BrowserPolicy.content.allowOriginForAll("http://meteor.local");
I know it's unreasonable. But It worked. And the others all failed.
So it's odd... 
And is this issue solved? I don't think so. Still has a problem.

**Comment by dhavalrajani92** [comment] 2015-07-17 18:30
I have a third party iframe which authenticating my request origin then what should i do?

**Comment by MichaelJCole** [comment] 2015-08-27 16:14
@slava's assumptions and resolution didn't work for me either.  [This was the problem](https://github.com/meteor/meteor/issues/3382) for me and here's the solution that worked for me:

```
meteor remove force-ssl 
```

Some notes for future readers:

  - `App.accessRule("*");` in `mobile-config.js` - this code runs once during the Meteor build to make [config.xml used by Cordova](https://cordova.apache.org/docs/en/4.0.0/guide_appdev_whitelist_index.md.html)
  - `BrowserPolicy.content.allowOriginForAll("http://meteor.local");` etc. is setting the [content-security-policy header](http://www.html5rocks.com/en/tutorials/security/content-security-policy/).  
      - TLDR;  This header asks clients to only make requests to certain servers.  This helps secure your app and users by not loading malicious code from external servers.  You'll need this to load code from Stripe.com etc.
      - Incorrectly setting this header will show errors in the client, not the server.  
  - The error that googles here is talking about the [Access-Control-Allow-Origin header](http://www.html5rocks.com/en/tutorials/cors/).  
      - TLDR; This header asks browsers to only start your app if loaded from one of these domains.  This helps keep your app from being framed or hijacked.
      - Errors with this header are also in the client, not the server.  I'm guessing they show in the `meteor` output from a debug log on the client.

There is a bug in force-ssl that disrupts the Access-Control-Allow-Origin header.  This code was *not* a workaround for me:

```
WebApp.rawConnectHandlers.use(
  function(req, res, next) {
    // Cordova lives in meteor.local, so it does CORS
    if (req.headers && req.headers.origin === 'http://meteor.local') {
      res.setHeader('Access-Control-Allow-Origin', 'http://meteor.local');
    }
    next();
  }
);
```

If your app is using Stripe.com for example, you might need a Browser Policy like this:
```
Meteor.startup(function() {
  console.log('Configuring content-security-policy:');
  BrowserPolicy.content.allowSameOriginForAll();
  BrowserPolicy.content.allowOriginForAll('http://meteor.local');
  BrowserPolicy.content.allowOriginForAll('https://yourapp.io');
  BrowserPolicy.content.allowOriginForAll('https://*.yourapp.io');
  BrowserPolicy.content.allowOriginForAll('https://*.stripe.com');
  BrowserPolicy.content.allowEval();
  BrowserPolicy.framing.disallow();
});
```

**Comment by jaskinn** [comment] 2015-08-31 06:10
@MichaelJCole That is a nicely detailed answer. I do not have the force-ssl package installed. Could you explain the fix (relating to meteor/cordova) for your third point?

By the way, I have implemented the first two strategies ('accessRule' and 'BrowserPolicy') without success

**Comment by MichaelJCole** [comment] 2015-08-31 17:13
@jaskinn So, I ran into more problems.  There is no fix in the third point :(

Somewhere, the internet said Meteor 1.2 will improve its Mobile development experience and I'm looking forward to that maybe clearing up some issues.  

I was trying to proxy `http://localhost:3012` -> `httpS://localhost:4412` and use the `--mobile-server` tag to make sure my app was secure.  It didn't work for whatever reason - maybe a self-signed cert?  I gave up and just used an insecure `--port`.  I won't launch till after 1.2 so I'll see if that fixes it.

In the meantime, here's my setup:

``` bash
#!/bin/bash

MONGO_URL=mongodb://localhost:27017/project \
  meteor run android-device \
  --verbose \
  --settings settings.json \
#  --mobile-server https://meteor.local:4412 \
  --port 3012 \
```

```
//mobile-config.js
console.log('Configuring App.accessRule');
App.accessRule('https://project.io');
App.accessRule('https://*.project.io');
App.accessRule('https://*.stripe.com');

App.info({
  id: 'io.project',
  name: 'project.io',
  description: 'project.io',
  author: 'project.io',
  email: 'support.app@project.io',
  website: 'http://project.io'
});

// These are autogenerated with `ionic resources` - http://ionicframework.com/docs/cli/icon-splashscreen.html
App.icons({
  'iphone':       'resources/ios/icon/icon-60.png',
  'iphone_2x':    'resources/ios/icon/icon-60@2x.png',
  'iphone_3x':    'resources/ios/icon/icon-60@3x.png',
  'ipad':         'resources/ios/icon/icon-76.png',
  'ipad_2x':      'resources/ios/icon/icon-76@2x.png',
  'android_ldpi': 'resources/android/icon/drawable-ldpi-icon.png',
  'android_mdpi': 'resources/android/icon/drawable-mdpi-icon.png',
  'android_hdpi': 'resources/android/icon/drawable-hdpi-icon.png',
  'android_xhdpi':'resources/android/icon/drawable-xhdpi-icon.png',
});

App.launchScreens({
  'iphone':                 'resources/ios/splash/Default~iphone.png',
  'iphone_2x':              'resources/ios/splash/Default@2x~iphone.png',
  'iphone5':                'resources/ios/splash/Default-667h.png',
  'iphone6':                'resources/ios/splash/Default-667h.png',
  'iphone6p_portrait':      'resources/ios/splash/Default-736h.png',
  'iphone6p_landscape':     'resources/ios/splash/Default-Landscape-736h.png',
  'ipad_portrait':          'resources/ios/splash/Default-Portrait~ipad.png',
  'ipad_portrait_2x':       'resources/ios/splash/Default-Portrait@2x~ipad.png',
  'ipad_landscape':         'resources/ios/splash/Default-Landscape~ipad.png',
  'ipad_landscape_2x':      'resources/ios/splash/Default-Landscape@2x~ipad.png',
  'android_ldpi_portrait':  'resources/android/splash/drawable-port-ldpi-screen.png',
  'android_ldpi_landscape': 'resources/android/splash/drawable-land-ldpi-screen.png',
  'android_mdpi_portrait':  'resources/android/splash/drawable-port-mdpi-screen.png',
  'android_mdpi_landscape': 'resources/android/splash/drawable-land-mdpi-screen.png',
  'android_hdpi_portrait':  'resources/android/splash/drawable-port-hdpi-screen.png',
  'android_hdpi_landscape': 'resources/android/splash/drawable-land-hdpi-screen.png',
  'android_xhdpi_portrait': 'resources/android/splash/drawable-port-xhdpi-screen.png',
  'android_xhdpi_landscape':'resources/android/splash/drawable-land-xhdpi-screen.png',
});

// This is from the ProductHunt example
App.setPreference('StatusBarOverlaysWebView', true);
App.setPreference('StatusBarStyle', 'default');
```

```
// server/BroswerPolicyAndCORS.js
Meteor.startup(function() {
  console.log('Configuring content-security-policy');
  BrowserPolicy.content.allowSameOriginForAll();
  BrowserPolicy.content.allowOriginForAll('http://meteor.local');
  BrowserPolicy.content.allowOriginForAll('https://meteor.local');
  BrowserPolicy.content.allowOriginForAll('https://project.io');
  BrowserPolicy.content.allowOriginForAll('https://*.project.io');
  BrowserPolicy.content.allowOriginForAll('https://*.stripe.com');
  BrowserPolicy.content.allowEval();
  BrowserPolicy.framing.disallow();
});
```

If you're interested, here is the http->https proxy code:

```
var server = Meteor.settings.serverInfo;

if (server.proxyPort) {

  var fs = Npm.require('fs');
  var path = Npm.require('path');
  var httpProxy = Meteor.npmRequire('http-proxy');

  var options = {
    ssl: {
      key: fs.readFileSync(path.resolve('../../../../../../self.key'), 'utf8'),
      cert: fs.readFileSync(path.resolve('../../../../../../self.cert'), 'utf8'),
    },
    target : server.proxySource,  // a URL
    ws: true,
    xfwd: true,
    secure: false,  // help w/ self-signed certs?
  };

  process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';  // help w/ self-signed certs?
  httpProxy.createProxyServer(options).listen(server.proxyPort);
  console.log('=====> ' + server.name + ' @ https://localhost:' + server.proxyPort);
}
```

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
browser-policy
aldeed:collection2
accounts-password
iron:router
mizzao:user-status
less
sacha:spin
reactive-var
email
meteorhacks:cluster
meteorhacks:npm
wylio:mandrill
random
npm-container
fourseven:scss@2.0.0
meteoric:ionic-sass
meteoric:ionicons-sass
meteoric:ionic
```

**Comment by MichaelJCole** [comment] 2015-08-31 19:34
One more thing to check is that you can ping back and forth between the phone and computer.  W/o this it's possible to install the app, but not get data back and forth.

**Comment by StrictlySkyler** [comment] 2015-10-13 22:52
I am still experiencing this issue.  Neither adding `BrowserPolicy.content.allowOriginForAll("http://meteor.local");` in server-code or `App.accessRule('http://meteor.local');` in mobild-config.js solves this – when I run the app in an iOS simulator, it errors in this way.

I've even tried `App.accessRule('*');` and `BrowserPolicy.content.allowOriginForAll("*");`, to no avail.

**Comment by Lenin7** [comment] 2015-10-27 06:32
updates?

**Comment by phoue** [comment] 2015-11-02 09:07
The same issue on Android.

**Comment by PEM--** [comment] 2015-11-02 10:51
Same stuff, here also :disappointed:

**Comment by Lenin7** [comment] 2015-11-03 18:43
Anyone found a fix for this yet?

**Comment by mehdibalouchi** [comment] 2015-11-16 13:42
Same issue here, I have a Cordova/Ionic/Meteor app on meteor 1.2.1, `$http({method: 'GET', url: 'www.google.com')` returns an error with `satatus:-1`

**Comment by rdewolff** [comment] 2015-11-17 00:16
Are you guys switching between iOS device and Simulator when encountering this problem?

**Comment by keyvan-m-sadeghi** [comment] 2015-11-19 10:21
I had the same issue, resolved it by moving my HTTP calls to the server.

On server:
```javascript
Meteor.methods({
    invokeAPI: function (url, method, data={}, params={}
             onError = (error) => console.log('Error: ' + JSON.stringify(error)),
             onSuccess = (result) => console.log('Result: ' + JSON.stringify(result))) {

        let asyncResponse = new Future();
        Meteor.http.call(method, url,
            {
                params: params,
                headers: {
                    "Content-Type": "application/json",
                },
                data: data
            }, (error, result) => {
                if(!error) {
                    onSuccess(result);
                    asyncResponse.return(result);
                }
                else {
                    onError(error);
                    asyncResponse.throw(error);
                }
            });
        return asyncResponse.wait();
    };
});
```

On client (angular in my case):
```javascript
$meteor.call("invokeAPI", "<API_URL_HERE>", "POST", {some: "data"})
    .then(
        (response) => {
            alert("Response: " + response);
        },
        (error) => {
            alert("Error: " + error);
        }
    );
```

**Comment by alexissantos** [comment] 2015-12-29 04:25
BrowserPolicy didn't do the trick for me, but using this on the server did: http://enable-cors.org/server_meteor.html

```
// Listen to incoming HTTP requests, can only be used on the server
WebApp.connectHandlers.use(function(req, res, next) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  return next();
});
```

**Comment by elie222** [comment] 2016-02-14 22:52
Having the same issues. Above solutions didn't help

**Comment by mechiles** [comment] 2016-03-04 18:57
@alexissantos did you create a new file for your server side fix, or did you add the code to an existing file?

**Comment by alexissantos** [comment] 2016-03-04 23:24
@mechiles I created an access-control.js file with that code in the server folder. Hope that helps!

**Comment by mechiles** [comment] 2016-03-05 17:25
@alexissantos thanks! I'll give it a shot!

**Comment by tenshis** [comment] 2017-07-22 23:15
Any progress on this?

**Comment by ddspog** [comment] 2017-09-18 16:51
Could someone help me? I'm running 
`meteor run android-device --mobile-server https://inspetor-mups.herokuapp.com/ --settings ...`

The errors I've received are the following:

```
I20170918-04:49:58.315(-3)? 09-18 04:49:51.992 19940 19940 I CordovaLog: Changing log level to DEBUG(3)
I20170918-04:49:58.725(-3)? 09-18 04:49:52.370 19940 19940 I chromium: [INFO:library_loader_hooks.cc(144)] Chromium logging enabled: level = 0, default verbosity = 0
I20170918-04:49:58.730(-3)? 09-18 04:49:54.577 19940 19940 I MeteorWebApp: Serving asset bundle with version: a0d7e2dc964b0c0cd5e8e4979078ed33699f40f5
I20170918-04:49:58.731(-3)? 09-18 04:49:55.375 19940 20102 E chromium: [ERROR:BudgetService.cpp(165)] Unable to connect to the Mojo BudgetService.
I20170918-04:49:58.939(-3)? 09-18 04:50:00.957 19940 19940 I chromium: [INFO:CONSOLE(0)] "XMLHttpRequest cannot load https://inspetor-mups.herokuapp.com/sockjs/info?cb=dhw24yggh8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:12768' is therefore not allowed access. The response had HTTP status code 503.", source: http://localhost:12768/records (0)
I20170918-04:49:59.656(-3)? 09-18 04:50:01.674 19940 19940 I chromium: [INFO:CONSOLE(0)] "XMLHttpRequest cannot load https://inspetor-mups.herokuapp.com/sockjs/info?cb=v0efl3lmm8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:12768' is therefore not allowed access. The response had HTTP status code 503.", source: http://localhost:12768/records (0)
I20170918-04:50:00.248(-3)? 09-18 04:50:02.237 19940 19940 I chromium: [INFO:CONSOLE(0)] "XMLHttpRequest cannot load https://inspetor-mups.herokuapp.com/sockjs/info?cb=hiyfufv9vw. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:12768' is therefore not allowed access. The response had HTTP status code 503.", source: http://localhost:12768/records (0)
I20170918-04:57:19.882(-3)? 09-18 04:57:24.703 32759 32759 I chromium: [INFO:CONSOLE(0)] "Application Cache NoUpdate event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
I20170918-06:05:00.887(-3)? 09-18 06:05:05.746 22096 22096 I chromium: [INFO:library_loader_hooks.cc(144)] Chromium logging enabled: level = 0, default verbosity = 0
```
I'm putting my [mobile-config.js](https://gist.github.com/ddspog/c0d522d6e670e70b9942b13117c9cf47), if you want to take a look. This is a problem to solve on my repo [inspetor-mups](https://github.com/ddspog/inspetor-mups), but I'm still trying to solve this problem locally before commiting new code.

Could someone help me? I'm not trying to use any strange tools to fetch data outside my server. I'm using an external mongo database setting the URL, like meteor guides told me so, I'm setting the ROOT_URL like meteor guides told me so... I'm not trying any complicated code to acess sites outside my application. 

And, this code has stopped working without making any changes on it. I've changed my cellphone for testing this application from a Lollipop Android to a Nougat Android, so maybe the problem it's on Chromium on Android itself. Someone, plz help me.

**Comment by mustcan** [comment] 2017-09-29 12:57
@ddspog Have you found a solution?

**Comment by ddspog** [comment] 2017-09-29 13:15
@mustcan No, I've not. I've tried nonstop working on this project for over a month trying different solutions proposed here and on others points at internet. Almost every discussion about this problem points to this bug, and It's closed, and no solutions here worked.

I've put my project on hold until I receive updates on this problem. Thankfully this project compiled an Android version in June, that I uploaded on App Store, tested it and I wrote an report for the project conclusion. Unfortunately, the same code doesn't compile anymore because this bug appears everytime.

I've moved onto another project. I'll be listening to this bug report for a long while.

**Comment by hwillson** [comment] 2017-09-29 13:29
@ddspog  Sorry to hear about the frustration this issue has caused. I'll re-open this issue, but if anyone here could put together some form of a reproduction recipe (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)), that would go a long way towards helping get this issue resolved. Thanks!

**Comment by ddspog** [comment] 2017-09-29 13:33
@hwillson Thanks. I'm going to try creating a project seed with the packages I'm using to make a simple way to reproduce the problem.

**Comment by hwillson** [comment] 2018-01-24 13:56
@ddspog Any luck with creating a reproduction for this?

**Comment by hwillson** [comment] 2018-02-13 18:11
Closing for now since we haven't heard back regarding the additional information requested in https://github.com/meteor/meteor/issues/4132#issuecomment-333126484. If anyone can provide a small runnable reproduction that clearly demonstrates this issue, we'll happily re-open this issue. Thanks!

**Closed by hwillson** 2018-02-13 18:11 UTC
Labels: Project:Mobile, needs-reproduction

**Comment by awgust-taylor** [comment] 2018-03-21 15:07
please reopen im also experiencing this now but only on ios. I can run my app on android and web browser perfectly fine. There is a huge problem here that is not being attended too, because so many people seem to be suffering from the same problem. ios build is succesful, app is installed, splash screen to blank white screen. is it my Cordova? ERRORS in console are as follows
`[Error] Failed to load resource: Origin http://localhost:12952 is not allowed by Access-Control-Allow-Origin. (_timesync, line 0)
[Error] XMLHttpRequest cannot load http://000.000.00.000:3000/_timesync due to access control checks.`

please if anyone has been through this and know of a fix let me know. I have lost 2 weeks now on something that may be just a one liner. People on stackoverflow are more interested in editing your question than answering your problem.

**Comment by hwillson** [comment] 2018-03-21 16:09
@awgust-taylor Are you able to provide a small runnable reproduction that shows this happening? If so, then we'll gladly re-open this. Thanks!

**Comment by adamgins** [comment] 2018-05-24 10:25
@awgust-taylor @hwillson  did anything happen on this?

I am seeing this on the console

```
=> Started app on Android Device.             
I20180524-20:16:31.095(10)? 05-24 20:16:26.240 15536 15574 E chromium: [ERROR:devtools_http_handler.cc(292)] Cannot start http server for devtools. Stop devtools.
I20180524-20:16:31.097(10)? 05-24 20:16:27.629 15536 15579 E chromium: [ERROR:BudgetService.cpp(160)] Unable to connect to the Mojo BudgetService.
I20180524-20:16:33.233(10)? 05-24 20:16:32.579 15536 15536 I chromium: [INFO:CONSOLE(1218)] "deviceready has not fired after 5 seconds.", source: http://localhost:12456/cordova.js (1218)
I20180524-20:16:33.233(10)? 05-24 20:16:32.580 15536 15536 I chromium: [INFO:CONSOLE(1211)] "Channel not fired: onDOMContentLoaded", source: http://localhost:12456/cordova.js (1211)
I20180524-20:16:34.608(10)? 05-24 20:16:33.955 15536 15536 I chromium: [INFO:CONSOLE(83)] "currentDomain", source: http://localhost:12456/packages/buzzy-buzz_resources-core.js?hash=40a6c5899ba0d55aaf106a32f42699e807458d0f (83)
I20180524-20:16:34.609(10)? 05-24 20:16:33.956 15536 15536 I chromium: [INFO:CONSOLE(84)] "BUZZY_TEMPLATE_SERVER:false", source: http://localhost:12456/packages/buzzy-buzz_resources-core.js?hash=40a6c5899ba0d55aaf106a32f42699e807458d0f (84)
I20180524-20:16:40.860(10)? 05-24 20:16:40.208 15536 15536 I chromium: [INFO:CONSOLE(74413)] "Uncaught TypeError: cordova.plugins.diagnostic.isExternalStorageAuthorized is not a function", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (74413)
I20180524-20:16:40.907(10)? 05-24 20:16:40.251 15536 15536 I chromium: [INFO:CONSOLE(309)] "Error in Success callbackId: Diagnostic1361048150 : TypeError: cordova.plugins.diagnostic.requestLocationAuthorization(...) is not a function", source: http://localhost:12456/cordova.js (309)
I20180524-20:16:40.909(10)? 05-24 20:16:40.253 15536 15536 I chromium: [INFO:CONSOLE(309)] "Error in Success callbackId: Diagnostic1361048151 : TypeError: cordova.plugins.diagnostic.requestContactsAuthorization(...) is not a function", source: http://localhost:12456/cordova.js (309)
I20180524-20:16:40.909(10)? 05-24 20:16:40.254 15536 15536 I chromium: [INFO:CONSOLE(309)] "Error in Success callbackId: Diagnostic1361048153 : TypeError: successCallback is not a function", source: http://localhost:12456/cordova.js (309)
I20180524-20:16:40.912(10)? 05-24 20:16:40.257 15536 15536 I chromium: [INFO:CONSOLE(309)] "Error in Success callbackId: Diagnostic1361048154 : TypeError: successCallback is not a function", source: http://localhost:12456/cordova.js (309)
I20180524-20:16:40.940(10)? 05-24 20:16:40.288 15536 15536 I chromium: [INFO:CONSOLE(78139)] "query pageStyle", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (78139)
I20180524-20:16:41.013(10)? 05-24 20:16:40.339 15536 15536 I chromium: [INFO:CONSOLE(74391)] "Uncaught (in promise) TypeError: cordova.plugins.diagnostic.requestLocationAuthorization(...) is not a function", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (74391)
I20180524-20:16:41.014(10)? 05-24 20:16:40.340 15536 15536 I chromium: [INFO:CONSOLE(74402)] "Uncaught (in promise) TypeError: cordova.plugins.diagnostic.requestContactsAuthorization(...) is not a function", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (74402)
I20180524-20:16:41.014(10)? 05-24 20:16:40.342 15536 15536 I chromium: [INFO:CONSOLE(466)] "Uncaught (in promise) TypeError: successCallback is not a function", source: http://localhost:12456/plugins/cordova.plugins.diagnostic/www/android/diagnostic.js (466)
I20180524-20:16:41.014(10)? 05-24 20:16:40.343 15536 15536 I chromium: [INFO:CONSOLE(324)] "Uncaught (in promise) TypeError: successCallback is not a function", source: http://localhost:12456/plugins/cordova.plugins.diagnostic/www/android/diagnostic.js (324)
I20180524-20:16:41.017(10)? 05-24 20:16:40.363 15536 15536 I chromium: [INFO:CONSOLE(65103)] "LAYOUT AUTORUN 2", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (65103)
I20180524-20:16:41.018(10)? 05-24 20:16:40.364 15536 15536 I chromium: [INFO:CONSOLE(65105)] "LAYOUT AUTORUN 2", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (65105)
I20180524-20:16:41.027(10)? 05-24 20:16:40.375 15536 15536 I chromium: [INFO:CONSOLE(65125)] "about to subs for communityID", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (65125)
I20180524-20:16:41.037(10)? 05-24 20:16:40.385 15536 15536 I chromium: [INFO:CONSOLE(71938)] "NO CONNECTIONS HEADER", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (71938)
I20180524-20:16:43.931(10)? 05-24 20:16:43.277 15536 15536 I chromium: [INFO:CONSOLE(65103)] "LAYOUT AUTORUN 2", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (65103)
I20180524-20:16:43.932(10)? 05-24 20:16:43.278 15536 15536 I chromium: [INFO:CONSOLE(65105)] "LAYOUT AUTORUN 2", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (65105)
I20180524-20:16:43.937(10)? 05-24 20:16:43.280 15536 15536 I chromium: [INFO:CONSOLE(65125)] "about to subs for communityID", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (65125)
I20180524-20:16:43.959(10)? 05-24 20:16:43.305 15536 15536 I chromium: [INFO:CONSOLE(78139)] "query pageStyle", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (78139)
I20180524-20:16:44.011(10)? 05-24 20:16:43.357 15536 15536 I chromium: [INFO:CONSOLE(78139)] "query pageStyle", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (78139)
I20180524-20:16:44.252(10)? 05-24 20:16:43.600 15536 15536 I chromium: [INFO:CONSOLE(65393)] "sign in origin", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (65393)
I20180524-20:16:44.254(10)? 05-24 20:16:43.601 15536 15536 I chromium: [INFO:CONSOLE(65393)] "sign in origin", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (65393)
I20180524-20:16:46.140(10)? 05-24 20:16:45.488 15536 15739 E MeteorWebApp: Download failure
I20180524-20:16:46.140(10)? 05-24 20:16:45.488 15536 15739 E MeteorWebApp: com.meteor.webapp.WebAppException: Skipping downloading new version because the Cordova platform version or plugin versions have changed and are potentially incompatible
I20180524-20:16:46.140(10)? 05-24 20:16:45.488 15536 15739 E MeteorWebApp: 	at com.meteor.webapp.WebAppLocalServer.shouldDownloadBundleForManifest(WebAppLocalServer.java:367)
I20180524-20:16:46.141(10)? 05-24 20:16:45.488 15536 15739 E MeteorWebApp: 	at com.meteor.webapp.AssetBundleManager$1.onResponse(AssetBundleManager.java:131)
I20180524-20:16:46.141(10)? 05-24 20:16:45.488 15536 15739 E MeteorWebApp: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
I20180524-20:16:46.141(10)? 05-24 20:16:45.488 15536 15739 E MeteorWebApp: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
I20180524-20:16:46.141(10)? 05-24 20:16:45.488 15536 15739 E MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
I20180524-20:16:46.142(10)? 05-24 20:16:45.488 15536 15739 E MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
I20180524-20:16:46.142(10)? 05-24 20:16:45.488 15536 15739 E MeteorWebApp: 	at java.lang.Thread.run(Thread.java:761)
I20180524-20:16:46.143(10)? 05-24 20:16:45.491 15536 15536 I chromium: [INFO:CONSOLE(70)] "Error: Skipping downloading new version because the Cordova platform version or plugin versions have changed and are potentially incompatible", source: http://localhost:12456/packages/webapp.js?hash=d8189fa667b77a6959459ae756c28fd264ac2eaa (70)
I20180524-20:16:48.472(10)? 05-24 20:16:47.820 15536 15536 I chromium: [INFO:CONSOLE(65393)] "sign in origin", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (65393)
I20180524-20:16:49.320(10)? 05-24 20:16:48.667 15536 15536 I chromium: [INFO:CONSOLE(65393)] "sign in origin", source: http://localhost:12456/app/app.js?hash=5b3bd261b85e451152d05b0a26062777fadd115a (65393)
I20180524-20:17:07.704(10)? 05-24 20:17:07.044 15536 15598 W MeteorWebApp: App startup timed out, reverting to last known good version
```

**Comment by iwoj** [comment] 2020-01-06 22:43
I'm seeing the same problem.

**Comment by filipenevola** [comment] 2020-01-10 22:35
hi @iwoj as this issue is almost 5 years old could you open a new one describing exactly what is happening, what version are you using, etc.
