### ISSUE TITLE
issue with oauth 'end_of_popup_response' and 'end_of_redirect_response' .js file path (for meteor apps served using hostname/slug)?

### ISSUE THREAD

**Issue by cunnagin** [meteor/meteor#7979] opened 2016-10-27 21:15 UTC
I'm using Meteor's oauth package (via Accounts-base, Accounts-password & Accounts-oauth packages) and am using a login popup. Everything works fine and after entering credentials, the popup window closes as it should.

However, when I deploy multiple apps behind an nginx frontend with virtual hosts defined so that each app is addressed at http://host/slug such as "http://www.hostserver.com/appname" - for instance, the login popup does not close because the 'end_of_popup_response.html' file that is called tries to load the 'end_of_popup_response.js' script from the '/packages/oauth' directory (as dictated by the api.addAssets() command in package.js) and it should be loading that script from '/appname/packages/oauth' path... so, not knowing if there is a mechanism to overide this, I had to fork the meteor code and add some code to the 'oauth_server.js' file (part of the meteor oauth package.

So, unless I'm missing the boat, I think the fix is to use the Meteor.absoluteUrl() command to get the real full ROOT_URL path => strip off the appname => inject that into the HTML file at the head of the js file path. So, for the above dummy example; '/package/oauth/end_of_popup_response.js' would get turned into '/appname/package/oauth/end_of_popup_response.js' - and the popup window will close as expected.

I added the following code to the 'oauth_server.js' file at the end of the 'renderEndOfLoginResponse' function:

```
  var result = template.replace(/##CONFIG##/, JSON.stringify(config))

  // -----CHANGES----------------------------------------------------------
  // Get the ROOT_URL, split into an array at '/' character; also, the length of that array
  var UrlFix = _.without(Meteor.absoluteUrl().toLowerCase().split('/'),"")
  var UrlN = UrlFix.length

  // If the root had 'http' or 'https' in it, need to remove first 2 elements of the array
  if ((UrlFix[0]=='http:')||(UrlFix[0]=='https:')) {
    UrlFix.shift();
    UrlFix.shift();
  }

  // Now join all remaining slugs in served path
  UrlPatch = UrlFix.join('/')

  // And finally, add the path prefix to the HTML
  if (UrlN>=3) {

        // Search the HTML string and add the appname path prefix
        result = result.replace('/packages', '/'+UrlPatch+'/packages');
  }
  // ----------------------------------------------------------------------

  return "<!DOCTYPE html>\n" + result;
```

This just relies on the ROOT_URL environment variable having been passed at meteor runtime.  This works for me now, I'm just not sure if it's unnecessary because there is another way to handle it. I'd appreciate any comments!

**Comment by abernix** [comment] 2016-10-28 07:03
What is are you setting the `ROOT_URL` to when you launch these applications?  I won't say there isn't a bug in this logic when working with apps launched in a subdirectory (i.e. `ROOT_URL=https://mydomain.com/subappdirectory1/`, but have you looked at using [`redirectUrl` from `Accounts`'s `loginWith<ExternalService>`](https://docs.meteor.com/api/accounts.html#Meteor-loginWith<ExternalService>)?

Again though, it's entirely possible that there is a bug here.  For example, it's possible that the [`end_of_popup_response.html` template](https://github.com/meteor/meteor/blob/devel/packages/oauth/end_of_popup_response.html#L9) needs treatment similar to the [boilerplate HTML](https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator/boilerplate_web.browser.html#L24-L25) (which is [set here](https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L314)).  So theoretically (still not sure if this is the right solution), it should have an additional token added in front of `/packag...` (for example, `##ROOT_URL_PATH_PREFIX##`) which would need to be substituted-in [here in this code](https://github.com/meteor/meteor/blob/devel/packages/oauth/oauth_server.js#L345).

Anyhow, it's a bit difficult to fully diagnose this issue and say if it's a problem with your code or a problem with Meteor without an easy reproduction – and making reproductions is what takes up a lot of developers and issue-triagers time.  Could you provide simple steps to/repos reproduce this?   No need to provide a proxy server or anything (in fact, I'm not even sure it's necessary to do this behind a proxy), but at least the Meteor side of things.  With that, it would be easy to 1) Diagnose, and if necessary, 2) Fix, 3) Add tests, 4) Release (even before the next version of Meteor since versions are no longer pinned to releases with Meteor 1.4.1 or higher).

Hope this helps.  And thanks for reporting the potential issue!

**Comment by abernix** [comment] 2016-10-31 11:36
This seems like it might be a duplicate of #6707 but I'll wait to see if we can get confirmation and if that reproduction works.

**Comment by cunnagin** [comment] 2016-10-31 15:33
Yeah - it looks to me like these are all basically the same;  #6707 'sub-path' issue = my issue = the need for '##ROOT_URL_PATH_PREFIX##' patch that you described. Looks like #6707 solved it with definition of a route which pointed to the correct 'end_of_popup_response.js' file location in his app directory I suppose. I think the real fix needs to be for both HTML files 'end_of_popup_response.js' and 'end_of_redirect_response.js' - as you suggested or I tried to implement. Also, it needs to handle  multiple slugs (i.e. path depth, e.g. 'http://hostname/appname1/appname2/...') in the url.

Both #6707 and I are running deployed apps; mine happen to be running on a host where I have multiple meteor apps deployed on unique ports. On the host, I am running nginx and have setup unique virtual hosts for each app so that the each app can be addressed at http://hostname/appname. This seems to be a pretty common configuration in the wild.

I was able to easily reproduce the problem by creating a very simple facebook login app and configuring nginx for a single virtual host route at '/fb' which points to a default meteor server running on port 3000. I am including all the steps below:

1) Setup facebook with a test app registration. I followed the very good instructions at [Bulent Tastan](http://bulenttastan.net/login-with-facebook-using-meteor-js/)

    --- this instructs you how to create your meteor app registration on a facebook developer account and includes all the source code you need for your meteor app (you only have to install 2 packages 'accounts-facebook' & 'service-configuration'
    --- i didn't even have a fb account, and was able to set one up and login to a developer account very quickly; then I created a test facebook app in the development console
   --- under your test app profile, also add to the 'App Domains' the hostname you willserve your meteor app from (for instance, 'localhost' if you just want to use that); no port number here
   --- also, select 'add Platform' and choose 'website'. Then you can add your site URL (for redirect purposes). If you stick with localhost, then it would look like this (with port) 'http://localhost:3000/'. Note, there is NO app name slug here.

2) Setup your meteor app
   --- [HERE](https://dl.dropboxusercontent.com/u/17736877/fbPopupLogin-FAIL.zip) is the zipped up meteor app I created and used using this guide (meteor version 1.4.2 on Ubuntu 16.04)
    --- copy the 'appId' and 'secret' that you get from the facebook development console (for the test app you set up in step #1) into your meteor apps' 'social-config.js' file 

2) Setup nginx on your meteor host and create a virtual host for the default port 3000

   --- setup nginx using 'sudo apt-install nginx'
   --- need to add a virtual host so that your app will be accessible at the slug '/fb'; [HERE](https://dl.dropboxusercontent.com/u/17736877/default) is a link to my 'default' configuration file you can use, or just modify the following at the top of the your 'default' file at '/etc/nginx/sites-enabled/default':

~~~~
map $http_upgrade $connection_upgrade {
	default upgrade;
}

server {

	listen *:80;

	# Make site accessible from http://localhost/
	server_name localhost stephen-meteorVB.dhcp.ad.rds.lexmark.com;

	location /fb {
		proxy_pass http://127.0.0.1:3000;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header Host $host;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
		add_header Cache-Control no-cache;	
	}
~~~~

3) make sure nginx has loaded the configuration file, do a 'sudo service nginx stop' then 'sudo service nginx start'

4) run the meteor app with a ROOT_URL assignment with the hostname you want; if you use localhost as above, this would look like 'ROOT_URL=http://localhost/fb meteor'

If everything works, you'll be able to go to address 'http://localhost/fb' in a browser (running on the server host) and you should see the app page with a 'Facebook Login' button. Use the facebook account for the test app and notice that the popup window does not close after login.

5) Now, use [THIS](https://dl.dropboxusercontent.com/u/17736877/fbPopupLogin-OK.zip) meteor code (same as above but I created a local 'package' directory in the app and pulled in the 'accounts-facebook', 'accounts-base' and 'oauth' packages locally). I had to remove the 'accounts-facebook' and 'service-configuration' packages from the meteor project and then add them back to pull from that local directory. The 'oauth' package includes the additional code I put at the top of this post.

Also, remember to copy the 'appId' and 'secret' that you get from the facebook development console (for the test app you set up in step #1) into your meteor apps' 'social-config.js' file 

If you run this code (same as #4 above) you will see that the popup windows closes properly after login.

Hope that is enough to help you reproduce - if not please LMK.

Steve

**Comment by abernix** [comment] 2016-11-14 14:55
Thank you for your comments and thank you for reporting this problem originally.  I'm closing in favor of #6707 which I've confirmed reproduces this same problem.  It's not even necessary to run this behind a proxy to see the same behaviour, as you can see in that reproduction for that issue.

**Closed by abernix** 2016-11-14 14:55 UTC
Labels: bug, Impact:few, Project:Accounts:OAuth, Severity:has-workaround
