### ISSUE TITLE
HTTP shipping with 1.6x NOT DETECTING JSON and populating 'data' object in return.

### ISSUE THREAD

**Issue by anthonymanzo** [meteor/meteor#9298] opened 2017-11-03 18:06 UTC
Hi,
After updating meteor to 1.6 any of my HTTP calls that return json are returning 'undefined' for the response.data object.

Here's an example of what I am doing in server-side code:

```js
const response = HTTP.get(Meteor.settings.sea.url+'/v1/departments/all-active', {
  auth: Meteor.settings.sea.user+':'+Meteor.settings.sea.password
});
```

Prior to meteor upgrade response.data would be populated because the content of the called api's response was detected to be JSON.  After the update to meteor, the response.data is null.
I can still see valid json as text in the response.content.

Here is a snippet from the response raw header, as you can see it is indicating json correctly:

```
Status Code: 201
pragma: no-cache
date: Thu, 02 Nov 2017 18:45:36 GMT
server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.5.38 mod_wsgi/3.4 Python/2.7.5
x-powered-by: PHP/5.5.38
content-type: application/json;charset=utf-8
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
connection: Keep-Alive
keep-alive: timeout=5, max=100
content-length: 23
expires: Thu, 19 Nov 1981 08:52:00 GMT`
```

Here is the content of the response that is not being detected as json:
```json
[{"department_code":"AAS","department_code1":"AAS","department_name":"Academic & Administrative Services","org_level_2_desc":"Academic & Administrative Services","auth_area":"ADMIN","core":false,"dept_head_person_code":"9497"},{"department_code":"TGC","department_code1":"TGC","department_name":"Transgenics","org_level_2_desc":"Transgenic Core Facility","auth_area":"LABS","core":true,"dept_head_person_code":"4753"},{"department_code":"VCL-A","department_code1":"VCL","department_name":"VCL-Albright","org_level_2_desc":"Vision Center","auth_area":"LABS","core":false,"dept_head_person_code":"3334"},{"department_code":"VCL-S","department_code1":"VCL","department_name":"VCL-Stoner","org_level_2_desc":"Vision Center","auth_area":"LABS","core":false,"dept_head_person_code":"3097"},{"department_code":"X ACAD","department_code1":"X ACAD","department_name":"Academic & International Services","org_level_2_desc":"Academic & International Services","auth_area":"ADMIN","core":false,"dept_head_person_code":null}]
```

Thanks
Tony

**Comment by klaussner** [comment] 2017-11-03 20:41
I tried to reproduce the issue with a public JSON API (https://dog.ceo/dog-api/) and Meteor 1.6 but I got a correct response:

```js
const response = HTTP.get('https://dog.ceo/api/breeds/image/random');
```

```js
{ statusCode: 200,
  content: '{"status":"success","message":"https:\\/\\/dog.ceo\\/api\\/img\\/terrier-irish\\/n02093991_1565.jpg"}',
  headers:
   { date: 'Fri, 03 Nov 2017 20:25:41 GMT',
     server: 'Apache/2.4.26',
     'cache-control': 'no-cache, private',
     'access-control-allow-origin': '*',
     'content-type': 'application/json',
     via: '1.1 varnish-v4, 1.1 varnish-v4',
     'x-cache-hits': '0',
     'x-cache': 'MISS',
     'accept-ranges': 'bytes',
     'content-length': '87',
     age: '0',
     connection: 'close' },
  data:
   { status: 'success',
     message: 'https://dog.ceo/api/img/terrier-irish/n02093991_1565.jpg' } }
```

**Comment by anthonymanzo** [comment] 2017-11-03 20:44
Can you try putting in the exact same header for content-type, as I think this is where the issue is.
My content-type header (coming from a Slim PHP framework standard) is 
`content-type: application/json;charset=utf-8`

**Comment by anthonymanzo** [comment] 2017-11-03 20:48
Here is the output from meteor list:
  Anthonys-MBP:saw tony$ meteor list
  accounts-base                       1.2.14* A user account system
  accounts-password                   1.3.3* Password support for accounts
  aldeed:autoform                     6.2.0  Easily create forms with automatic insert and update, and automatic reactive validation.
  aldeed:collection2-core             2.0.1  Core package for aldeed:collection2
  aldeed:schema-index                 2.0.0  Control some MongoDB indexing with schema options
  aldeed:tabular                      2.1.1  Datatables for large or small datasets in Meteor
  blaze-html-templates                1.1.0* Compile HTML templates into reactive UI with Meteor Blaze
  cfs:filesystem                      0.1.2  Filesystem storage adapter for CollectionFS
  cfs:graphicsmagick                  0.0.18  Adds `gm` to scope with the ability to perform GraphicsMagick or ImageMagick manipulation
  cfs:gridfs                          0.0.33  GridFS storage adapter for CollectionFS
  cfs:s3                              0.1.3  Amazon Web Services S3 storage adapter for CollectionFS
  cfs:standard-packages               0.5.9  Filesystem for Meteor, collectionFS
  cfs:ui                              0.1.3  CollectionFS, provides UI helpers
  check                               1.2.4* Check whether a value matches a pattern
  copleykj:livestamp                  1.1.7  jQuery plugin providing auto-updating timeago text to your timestamped HTML elements using Moment.js
  dburles:collection-helpers          1.1.0  Transform your collections with helpers that you define
  ecmascript                          0.6.1* Compiler plugin that supports ES2015+ in all .js files
  ejson                               1.0.13* Extended and Extensible JSON library
  email                               1.1.18* Send email messages
  emdagon:bootstrap-multiselect       0.0.2  Bootstrap Multiselect wrapper for Meteor
  es5-shim                            4.6.15  Shims and polyfills to improve ECMAScript 5 support
  fortawesome:fontawesome             4.7.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
  http                                1.1.8* Make HTTP calls to remote servers
  iain:accounting                     0.4.2  Accounting.js -  number, money and currency formatting - fully localisable, zero dependencies.
  iron:router                         1.0.13* Routing specifically designed for Meteor
  jquery                              1.11.10  Manipulate the DOM using CSS selectors
  less                                2.7.8* Leaner CSS language
  matb33:collection-hooks             0.8.4  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
  maximum:server-transform            0.5.0  Meteor package to transform documents on publish
  meteor-base                         1.0.4* Packages that every Meteor app needs
  meteorhacks:aggregate               1.3.0  Proper MongoDB aggregations support for Meteor
  meteorhacks:unblock                 1.1.0  a way to use this.unblock inside publications
  mizzao:bootboxjs                    4.4.0  Programmatic dialog boxes using Twitter's bootstrap modals
  mobile-experience                   1.0.4* Packages for a great mobile user experience
  momentjs:moment                     2.17.1* Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
  mongo                               1.1.14* Adaptor for using MongoDB and Minimongo over DDP
  nemo64:bootstrap                    3.3.5_2* Highly configurable bootstrap integration.
  nimble:restivus                     0.8.12  Create authenticated REST APIs in Meteor 0.9+ via HTTP/HTTPS. Setup CRUD endpoints for Collections.
  peerlibrary:aws-sdk                 2.4.9_1  SDK for AWS services including Amazon S3, Amazon EC2, DynamoDB, and Amazon SWF
  perak:joins                         1.0.8* Generic collection joins for Meteor
  perak:user-roles                    1.0.10* User roles package for Meteor
  percolate:synced-cron               1.3.2  Allows you to define and run scheduled jobs across multiple servers.
  rajit:bootstrap3-datepicker         1.6.4* Meteor packaging of eternicode/bootstrap-datepicker for Bootstrap 3
  random                              1.0.10  Random number generator and utilities
  reactive-dict                       1.1.8* Reactive dictionary
  reactive-var                        1.0.11  Reactive variable
  reywood:publish-composite           1.4.2* Publish a set of related documents from multiple collections with a reactive join
  sergeyt:typeahead                   0.11.1_9  Autocomplete package for meteor powered by twitter typeahead.js
  session                             1.1.7  Session variable
  sewdn:masked-input                  1.0.6  Masked Input plugin for jQuery
  shell-server                        0.2.1* Server-side component of the `meteor shell` command.
  simple:rest                         1.1.1  The easiest way to add a REST API to your Meteor app
  spiderable                          1.0.13  Makes the application crawlable to web spiders
  standard-minifier-css               1.3.2* Standard css minifier used with Meteor apps by default.
  standard-minifier-js                1.2.1* Standard javascript minifiers used with Meteor apps by default.
  tracker                             1.1.1* Dependency tracker to allow reactive callbacks
  underscorestring:underscore.string  3.3.4  underscore.string (official): String manipulation extensions for Underscore.js javascript library.

**Comment by klaussner** [comment] 2017-11-03 21:05
The `application/json; charset=utf-8` content type is working, too. Example:

```js
{ statusCode: 200,
  content: '{"date":"2017-11-03","season":"ordinary","season_week":30,"celebrations":[{"title":"Friday, 30th week in Ordinary Time","colour":"green","rank":"ferial","rank_num":3.13},{"title":"Saint Martin de Porres, religious","colour":"red","rank":"optional memorial","rank_num":3.12}],"weekday":"friday"}\n',
  headers:
   { server: 'nginx/1.10.2',
     date: 'Fri, 03 Nov 2017 20:58:18 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '295',
     connection: 'close',
     status: '200 OK',
     'cache-control': 'max-age=3600',
     vary: 'Origin',
     'x-powered-by': 'Phusion Passenger 5.1.2',
     'x-proxy-cache': 'HIT' },
  data:
   { date: '2017-11-03',
     season: 'ordinary',
     season_week: 30,
     celebrations: [ [Object], [Object] ],
     weekday: 'friday' } }
```

**Comment by hwillson** [comment] 2017-11-07 17:51
@anthonymanzo Since we can't reproduce this there isn't much we can do to help. I'll close this for now, but if you're able to put together a small, runnable reproduction demonstrating this issue, please post back and I'll re-open. Thanks!

**Closed by hwillson** 2017-11-07 17:51 UTC
Labels: can't-reproduce, Project:Utilities:HTTP
