### ISSUE TITLE
Can't import .scss files with meteor test

### ISSUE THREAD

**Issue by Floriferous** [meteor/meteor#9562] opened 2018-01-22 12:23 UTC
I'm running Meteor 1.6.0.1, and `fourseven:scss` to use SCSS files in my app. I can now import .scss files directly in my React components (which appears to not always have been the case). The problem is, it won't work in tests. Importing any such sccs-importing-React component in a test file crashes the test runner: `Error: Cannot find module './someStyle.scss'`.

I expect to be able to import .scss files in my regular app as well as being able to run tests with `meteor test`. 

Here's a very simple repo to reproduce the error: https://github.com/Floriferous/meteor-scss-import-bug

An issue was filed in `fourseven:scss`, but it appears to be a build problem.
https://github.com/fourseven/meteor-scss/issues/242

**Comment by hwillson** [comment] 2018-01-22 12:40
Hi @Floriferous - switch from using `meteor test` to `meteor test --full-app`. See the [Guide](https://guide.meteor.com/testing.html#test-modes) for a breakdown of the differences, but essentially you're not loading enough of your Meteor app in the default/simplified test mode to be able to find/process the imported `.scss` file. This is by design, so I'll close this off. Thanks!

**Closed by hwillson** 2018-01-22 12:40 UTC

**Comment by Floriferous** [comment] 2018-01-22 13:14
Okay, that was indeed the issue. 

Too bad that by using local scss modules I'm essentially shutting myself off from ever using `meteor test` if I want all my unit tests to run at once. Plus I have to rename all my `*.test.js` files to `*.app-test.js` files (not too big a deal, though it feels very meteor centric).

There's no note about the performance between `meteor test` and `meteor test --full-app`, but I'm assuming full-app will be slower as it has to load all files.

So there is a solution, but not without consequences.

**Comment by hwillson** [comment] 2018-01-22 13:17
All very true, and yes `--full-app` is slower. Maybe consider opening a FR for this over in https://github.com/meteor/meteor-feature-requests?
