### ISSUE TITLE
Meteor needs to reinstall after cleaning a git repo

### ISSUE THREAD

**Issue by aniskhan001** [meteor/meteor#7414] opened 2016-07-15 18:29 UTC
I had some unstaged changes on some files and I ran

```
git clean -df
git checkout -- .
```

to go back to its previous states. Since then when I run `meteor run` or `meteor --version` it says:

```
The system cannot find the path specified
```

on the console.

Not only on the project folder but also system-wide meteor command is not working since then.
Uninstall/Reinstall solves the issue. Had this problem twice. The environment variable was there, fine.

I'm using Windows 10 64-bit. Meteor version is **1.3.4.4** installed and the project version is **1.3.2.4**

**Comment by sqlrob** [comment] 2016-12-20 05:01
This is occurring on 1.4.2_3 with a freshly created skeleton project

**Comment by abernix** [comment] 2016-12-27 12:02
@sqlrob Make sure you are not using the `-x` flag with `git clean`.  Alternatively, please provide more information on your setup (OS, etc.) as this is no longer known to be a problem.

**Comment by sqlrob** [comment] 2016-12-27 14:02
I am using -x, and I consider the inability to use -x a bug. Isn't that pretty much SOP before doing a distribution?

`git clean -fxd` should result in the same behavior as a fresh `git clone` on build. 

git 2.10 (upgraded to 2.11 the other day, haven't tried with it) Windows 10, 1607 14393.576

**Comment by abernix** [comment] 2016-12-27 14:45
@sqlrob: I'll copy and paste my comments from a [past conversation](https://forums.meteor.com/t/cmd-on-win10-going-away/31501/16?u=abernix) I've had about `git clean -fxd`:

> In case it's not obvious, that is an extremely dangerous command, especially on Windows. You are saying "forcefully and recursively delete directories and ignore all previously ignored files". You might be interested in [this issue](https://github.com/git-for-windows/git/pull/437) which outlines how git clean **follows junctions** and deletes their contents (though that's not too surprising, as that's [exactly what Microsoft says would happen](https://support.microsoft.com/en-us/kb/205524) on commands which work recursively).
>
> Within your app, there are various junctions (hard-links) to global installations, one of the most important being the `.meteor/local/dev_bundle` link. This (junction) ensures that your app matches the correct version of Meteor on your system, allows multiple versions of Meteor to co-exist without needing (large) meteor-tool installations for every app that you create. It also allows the `meteor npm` and `meteor node` commands to work on the proper versions of node binaries without relying on what could be a cluttered global installation (and likely not the correct version).
>
> Normally, you wouldn't have this problem because Meteor creates the proper `.gitignore` rule that prevents `.meteor/local/dev_bundle` from being included in `git` commands, but by adding the `-x` you've told `git` to ignore that. I would recommend not using the `-x` flag, or if you do use it, to add the `-i` flag to do any deletions interactively with prompts before deletion.

Regarding your comment:

> I am using -x, and I consider the inability to use -x a bug. Isn't that pretty much SOP before doing a distribution?

I'm not sure what standard, but really it depends entirely on _what_ you're distributing.  If you're doing a Meteor staging/production deployment you should be using `meteor build` to build a `node` bundle and deploying that.

If you're sharing development with other developers, they would (presumably) be doing their own `git clone`.  Obviously your distribution procedures are yours to decide but I personally don't see any reason to have that be part of a Meteor deployment.

**Comment by sqlrob** [comment] 2016-12-27 15:10
Deployment in this case is for a coursera meteor course where a zip file should be uploaded to the deployment server.

I have used git for about a decade, over various OSes, primarily Windows. This is the first time I've had any git clean issues that weren't caused by me forgetting to add something.  It's generally fixed far more problems for me than it's caused, so it's not something I worry about; surprising behavior is bad. 

Disk space is cheap. On Windows the tools should be copied, or at least ACLs set up on the files by the installer.

**Comment by sqlrob** [comment] 2016-12-30 00:55
I was able to get it to work by putting the ACL on the target directory, rather than the junction itself. This feels like it's incredibly messy, since updates would need them removed and replaced, and things may be painful in general depending on the permissions the files are opened with. When are files in the dev_bundle deleted, if ever?

The ACL that worked for me in my tests was Everyone, Deny, Delete, Delete SubFolders and files.  I'll see if I can get something working with the junction itself. 

I'm fairly new to node, so I'm not sure how long it'll take me to figure out the node to set up the permissions.

**Comment by abernix** [comment] 2016-12-30 19:10
Files in `dev_bundle` are not normally deleted except by the Uninstaller or if a user deletes their `%LocalAppData%\.meteor` directory (common usually in debugging or trying to fix a weird problem).  Otherwise they are written when a new version is installed, not by the installer, but by the version of the `meteor-tool` which downloaded the new version.  The uninstaller could definitely change the permissions in order to be destructive if need be.

I do think it would be ideal if it could somehow be enforced just on the junction and not on the files so if you find a way to do that, please do report back!  If you can at least provide the secret formula that works, maybe we can work together to find a way to set them in the right place, but I didn't an easy existing Node solution (e.g. NPM package).

Also, if git-for-windows/git#437 ever lands, it might alleviate the problem, at least in your case.  Users could still find some other way to destructively delete it though if this isn't resolved.  True symlinks would be better for that.

**Comment by hwillson** [comment] 2018-01-15 18:18
While there are improvements that could be made here, this issue isn't likely to be worked on anytime soon. The number of developers affected by this is extremely low, and fixing this is not trivial. I'll close this issue for now, but will happily re-open it in the future, if developer demand becomes greater. Thanks!

**Closed by hwillson** 2018-01-15 18:18 UTC
Labels: Impact:some, Severity:has-workaround, bug, confirmed
