### ISSUE TITLE
Strange behaviour of this.unblock()

### ISSUE THREAD

**Issue by npvn** [meteor/meteor#7047] opened 2016-05-13 10:06 UTC
**Reproduction: https://github.com/npvn/meteor-unblock-issue-reproduction**

`this.unblock()` inside a Meteor method won't work if:
- The method contains a MongoDB mutate operation (`insert`, `update`, `remove`) that is carried out on both client (simulation) and server
- **AND** The DDP request coming after the method call is a subscription request

So, if you call a Meteor method having the characteristics above and then call `Meteor.subscribe()`, the subscription will have to wait until the method call finishes, even if `this.unblock()` is used.

This issue won't happen if the MongoDB mutate operation is carried out on server-side only, or if the subsequent DDP request is another method call rather than a subscription request.

I created a reproduction repo to illustrate the issue: 
https://github.com/npvn/meteor-unblock-issue-reproduction

To reproduce the issue, execute the following code in browser console. This code calls `insertNewItem` (unblocked) and then subscribe to the `items` publication.

``` javascript
Meteor.call('insertNewItem', function() {
  console.log('insertNewItem method returned');
})

var now = new Date();

Meteor.subscribe('items', function() {
  console.log('Items sub ready', `| Elapsed time: ${new Date() - now}`);
}); 
```

Note that the `items` subscription is blocked until `insertNewItem` returns.

Compare with:

``` javascript
Meteor.call('insertNewItemOnServer', function() {
  console.log('insertNewItemOnServer method returned');
})

var now = new Date();

Meteor.subscribe('items', function() {
  console.log('Items sub ready', `| Elapsed time: ${new Date() - now}`);
});
```

This time the `items` subscription is not blocked by the method call anymore. Note that the only difference between `insertNewItem` and `insertNewItemOnServer` is that in `insertNewItemOnServer` the `Items.insert()` operation is executed on server-side only.

I am able to reproduce this issue with Meteor `1.2.1` and `1.3.2.4`.

Not sure if this is really a bug or just an undocumented behaviour of `this.unblock()`.
# 

**Update**: This blocking behaviour will happen even if the second request subscribes to an unrelated publication (i.e. the published collection is not touched by the first method call). This can be reproduced with:

``` javascript
Meteor.call('insertNewItem', function() {
  console.log('insertNewItem method returned');
})

var now = new Date();

Meteor.subscribe('products', function() {
  console.log('Products sub ready', `| Elapsed time: ${new Date() - now}`);
}); 
```

**Comment by abernix** [comment] 2016-05-13 11:14
Thank you for the beautiful reproduction!  Someone will take a look at this.

(I'm marking this as a 'confirmed bug' even though I'm not certain it is.)

**Comment by mitar** [comment] 2016-05-16 06:51
So not sure why is this a bug? So what is surprising here? If you modified your simulated state on the client, then client has to wait for confirmation to come from the server that this is real state before being able to proceed. If you do not go into simulated state, then it can immediately do stuff.

I would even say that you showed that Meteor goes out of its way to assure that things are sane. Straightforward implementation would not be doing this.

**Comment by npvn** [comment] 2016-05-18 09:39
Thanks for the input, @mitar. I think by design Meteor method stub on the client doesn't wait for confirmation from server. It performs an "optimistic write" - modifying the state (e.g. a collection doc) in advanced and later make necessary adjustment after receiving result from server. 

In my code for reproduction above, if you subscribe to another unrelated publication (instead of `items`), the subscription is still blocked. This is a hint that the issue is actually a bug.

**Comment by mitar** [comment] 2016-05-18 12:46
No, after you run a stub, Meteor client side goes into simulation mode. Your queries against that data return the simulated data, but it does not allow future writes from the server until it gets first confirmation from the server.

> and later make necessary adjustment after receiving result from server. 

Exactly. This is done by or going out of the simulation mode and applying any changes coming from the server. But client has to know which changes were done as part of stub and which not.

**Comment by npvn** [comment] 2016-05-19 03:34
@mitar Do you mean that if I have a method carrying out a database write, and call that method on the client twice, then the second stub will have to wait until the first method call finishes? I think this makes sense and it should be the expected behaviour in most cases.

But in my reproduction, the second request is not a method call, but a subscription (i.e. not a database write). Also, the mentioned issue will happen even if the second request subscribes to an unrelated publication (this publication publishes data from an unrelated collection that is not touched by the first method call). I don't see why this subscription has to wait for the method call to finish.

**Comment by abernix** [comment] 2016-05-19 07:59
A second method call (or even subscription) would still need to wait because other collections might be changed on the server in the process.  The server ultimately decides on what collections will be changed (cache table, related-fields, etc.).  If there was no waiting on the server, the subscriptions (even to other collections) might receive wrong data or data that is about to change.  Meteor waits to make sure it's accepting correct data.  That's the way I perceive this.

**Comment by mitar** [comment] 2016-05-19 20:00
Both second method calls or subscriptions modify local state on the client, this is why they have to wait.

> Also, the mentioned issue will happen even if the second request subscribes to an unrelated publication (this publication publishes data from an unrelated collection that is not touched by the first method call).

This part is something to investigate more. I think this pausing is happening on the per-collection (or store, as it is known internally) base. But your reproduction currently works on the same collection. So if you are observing that issue you are mentioning now, please create a reproduction for it. And make reproduction stand on its own. Not that one is required to write things in the console. Make a button which does something which fails and shows the point.

**Comment by mitar** [comment] 2016-05-19 20:04
Oh, the reason is probably because client side does not know which subscription will be modifying which collection on the client. So it pauses all.

I think there could be a small improvement here by allowing all methods and subscriptions to go through, but their results on the client side would be paused (not applied). Then we could pause only messages for particular store which have been modified. Not all. But this is pretty edge case. And maybe it even already works like that.

**Comment by npvn** [comment] 2016-05-25 11:28
@abernix, @mitar Thanks for your input. And sorry for the late reply.

> But your reproduction currently works on the same collection. So if you are observing that issue you are mentioning now, please create a reproduction for it.

I updated the first post with instruction on reproducing the blocking behaviour when the second request subscribes to an unrelated publication.

> And make reproduction stand on its own. Not that one is required to write things in the console. Make a button which does something which fails and shows the point.

I decided to keep the reproduction approach as it is. This issue happens when we make a method call followed by a subscription, so the most obvious way to illustrate it should be making a method call and a subscription in the browser console, accompanied by clear console outputs. I think hiding these details behind some UI elements won't make it easier to understand. Anyway, if the reproduction is still unclear please let me know.

> Oh, the reason is probably because client side does not know which subscription will be modifying which collection on the client. So it pauses all.

> I think there could be a small improvement here by allowing all methods and subscriptions to go through, but their results on the client side would be paused (not applied). Then we could pause only messages for particular store which have been modified. Not all. But this is pretty edge case. And maybe it even already works like that.

It's great if we can have an improvement like that. On the other hand, if we can't, I think we should at least mention this behaviour in the docs.

**Comment by hwillson** [comment] 2017-08-22 17:19
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Strange%20behaviour%20of%20this.unblock()&body=Migrated%20from:%20meteor/meteor%237047) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-08-22 17:19 UTC
Labels: Impact:few, Project:Webapp
