### ISSUE TITLE
[Meteor 1.6] Invalid schema, expected mongodb

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#9422] opened 2017-11-27 16:01 UTC
Since my upgrade from 1.5 to 1.6, I am occasionally facing that Meteor throws on startup with the error copied below. First, I thought this might be related to the upgrade itself and just did a `meteor reset`. Everything worked fine afterwards.

But now this error occurred although I did not touch release versions in the meantime. I could make it work again with `meteor reset`, but this of course killed all my local dev data again. So I am wondering what is causing this?

```
I20171127-16:56:15.618(1)? Note: Restart Meteor to start the MongoDB server.
W20171127-16:56:15.658(1)? (STDERR) /Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.1584upa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171127-16:56:15.659(1)? (STDERR) 						throw(ex);
W20171127-16:56:15.659(1)? (STDERR) 						^
W20171127-16:56:15.659(1)? (STDERR) 
W20171127-16:56:15.659(1)? (STDERR) Error: invalid schema, expected mongodb
W20171127-16:56:15.659(1)? (STDERR)     at module.exports (/Users/waldgeist/.meteor/packages/npm-mongo/.2.2.33.k8ci4s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/url_parser.js:19:11)
W20171127-16:56:15.660(1)? (STDERR)     at connect (/Users/waldgeist/.meteor/packages/npm-mongo/.2.2.33.k8ci4s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongo_client.js:486:16)
W20171127-16:56:15.660(1)? (STDERR)     at Function.MongoClient.connect (/Users/waldgeist/.meteor/packages/npm-mongo/.2.2.33.k8ci4s++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongo_client.js:250:3)
W20171127-16:56:15.660(1)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:168:11)
W20171127-16:56:15.660(1)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
W20171127-16:56:15.660(1)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
W20171127-16:56:15.660(1)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
W20171127-16:56:15.661(1)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:99:40)
W20171127-16:56:15.661(1)? (STDERR)     at new AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
W20171127-16:56:15.661(1)? (STDERR)     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
```

**Comment by klaussner** [comment] 2017-11-28 09:48
The `'invalid schema, expected mongodb'` error is thrown by the MongoDB driver if the database URL doesn't start with `mongodb://` and the `Note: Restart Meteor to start the MongoDB server.` message is [printed by the `mongo-dev-server` package](https://github.com/meteor/meteor/blob/c09d8e57f01ed95c987f7a8b34b4d2de1a75b249/packages/mongo-dev-server/server.js) if the MongoDB URL is [`'no-mongo-server'`](https://github.com/meteor/meteor/blob/c09d8e57f01ed95c987f7a8b34b4d2de1a75b249/tools/runners/run-all.js#L105). Apparently, Meteor doesn't start MongoDB and then attempts to connect to the database with an invalid URL.

Can you share the content of your app's `versions` file (or at least the versions of `mongo` and `mongo-dev-server`)?

**Comment by derwaldgeist** [comment] 2017-11-28 10:18
Sure, here's the versions file:

[versions.txt](https://github.com/meteor/meteor/files/1509383/versions.txt)

**Comment by abernix** [comment] 2017-11-28 11:33
Is there anything in your app that might be modifying `process.env.MONGO_URL` during runtime?

**Comment by derwaldgeist** [comment] 2017-11-28 13:53
No, not that I knew.

**Comment by zimme** [comment] 2017-11-29 20:50
I'm thinking there might have been a change in how mongo driver handles invalid urls since I worked on the `mongo-dev-server` package. I believe I chose `no-mongo-server` as the `MONGO_URL` because of the fact that there were no error when using an invalid `MONGO_URL`. But maybe that was a false assumption made from the fact that `MONGO_URL=false` didn't error out.

i.e. Maybe this is cause by the fact that `MONGO_URL="no-mongo-server"` isn't falsey?

**Comment by zimme** [comment] 2017-11-29 20:51
But that don't explain why suddenly the `mongo-dev-server` package isn't picked up at startup and results in `MONGO_URL="no-mongo-server"` being set, as per this message `Note: Restart Meteor to start the MongoDB server.`

**Comment by zimme** [comment] 2017-11-29 20:56
I'm wondering if the call to `self.projectContext.resolveConstraints()` is async and that makes `self.projectContext.packageMap` not be available or this lookup `packageMap.getInfo('mongo-dev-server')` not able to find the package.

**Comment by hwillson** [comment] 2017-12-04 20:54
@zimme Good thinking - I've confirmed `self.projectContext.resolveConstraints()` is not async though 🙁.

@derwaldgeist Is this happening when you're running a mobile build (e.g. `meteor run ios-device`)? If so I'm wondering if you're hitting some combination of https://github.com/meteor/meteor/issues/8096 here. The app is unintentionally running in `production` mode on first startup, and since the `mongo-dev-server` package is `debugOnly`, it's not being found by the runner, and a `mongoUrl` of `no-mongo-server` is being set. Then when the app rebuilds it's running back in `development` mode again (as outlined in  https://github.com/meteor/meteor/issues/8096) at which point the `mongoUrl` value of `no-mongo-server` then triggers the error message you're seeing, since the `mongo-dev-server` package can be reached again (since `debugOnly` is now accepted again). This could help explain why you're only seeing this happening sometimes.

https://github.com/meteor/meteor/issues/8096 has been tied to a handful of issues now, so I think addressing it should be moved up the priority list. I'll aim to take a look - thanks!

**Comment by derwaldgeist** [comment] 2017-12-05 09:51
Thanks for the info. I'm not 100% sure if the problem occurred when I tried to `run ios-device`. Will have an eye on it when it happens next time. But I can say that the problem disappeared after doing a `meteor reset`. So this would kinda contradict your assumption, as the very first run works as expected.

**Comment by sebakerckhof** [comment] 2017-12-06 09:04
FYI, one of my colleagues also saw this issue last week, and we never run ios-device.

**Comment by theodorDiaconu** [comment] 2018-02-08 07:16
I have now the same issue when trying to run `test-packages` 
```
W20180208-09:16:15.170(2)? (STDERR) /Users/theodor/.meteor/packages/meteor-tool/.1.6.1.1gzx6ra.fbim++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180208-09:16:15.171(2)? (STDERR)                                             throw(ex);
W20180208-09:16:15.171(2)? (STDERR)                                             ^
W20180208-09:16:15.171(2)? (STDERR)
W20180208-09:16:15.171(2)? (STDERR) Error: invalid schema, expected mongodb or mongodb+srv
W20180208-09:16:15.172(2)? (STDERR)     at module.exports (/Users/theodor/.meteor/packages/npm-mongo/.2.2.34.u96z3b.w4cc++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/url_parser.js:15:21)
W20180208-09:16:15.172(2)? (STDERR)     at connect (/Users/theodor/.meteor/packages/npm-mongo/.2.2.34.u96z3b.w4cc++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongo_client.js:485:3)
W20180208-09:16:15.172(2)? (STDERR)     at Function.MongoClient.connect (/Users/theodor/.meteor/packages/npm-mongo/.2.2.34.u96z3b.w4cc++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongo_client.js:250:3)
W20180208-09:16:15.172(2)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:169:11)
W20180208-09:16:15.172(2)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
W20180208-09:16:15.172(2)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
W20180208-09:16:15.172(2)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
W20180208-09:16:15.173(2)? (STDERR)     at extension.Collection (packages/mongo/collection.js:97:40)
W20180208-09:16:15.173(2)? (STDERR)     at new extension (packages/cultofcoders:redis-oplog/lib/mongo/mongoCollectionNames.js:28:9)
W20180208-09:16:15.173(2)? (STDERR)     at packages/socialize_server-presence.js:22:15
W20180208-09:16:15.173(2)? (STDERR)     at packages/socialize_server-presence.js:156:4
W20180208-09:16:15.173(2)? (STDERR)     at packages/socialize_server-presence.js:164:3
W20180208-09:16:15.173(2)? (STDERR)     at /private/var/folders/s7/dsnl79f91pq37bjdw7fcflzw0000gp/T/meteor-test-run7b9t9c.e9ekv/.meteor/local/build/programs/server/boot.js:411:36
W20180208-09:16:15.173(2)? (STDERR)     at Array.forEach (<anonymous>)
W20180208-09:16:15.174(2)? (STDERR)     at /private/var/folders/s7/dsnl79f91pq37bjdw7fcflzw0000gp/T/meteor-test-run7b9t9c.e9ekv/.meteor/local/build/programs/server/boot.js:220:19
W20180208-09:16:15.174(2)? (STDERR)     at /private/var/folders/s7/dsnl79f91pq37bjdw7fcflzw0000gp/T/meteor-test-run7b9t9c.e9ekv/.meteor/local/build/programs/server/boot.js:471:5
```

**Comment by hwillson** [comment] 2018-03-09 18:09
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to low activity (see the [bug issue lifespan](https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/ISSUE_TRIAGE.md#bug-issue-lifespan) section of Meteor's triage doc for more information). If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!

**Closed by hwillson** 2018-03-09 18:09 UTC
Labels: Project:Tool, bug, not-implemented, pull-requests-encouraged

**Comment by sourav2029** [comment] 2018-04-19 10:40
I am getting the exact same error. I am setting the MONGO_URL=false using 
$export MONGO_URL=false because I am not using Mongo DB for my backend. How can I run my meteor app without mongo? Please help

**Comment by klaussner** [comment] 2018-04-19 12:43
@sourav2029 `MONGO_URL` must be a valid URL. If you don't want to start MongoDB, simply remove the `mongo` package from your `.meteor/packages` file or run `meteor remove mongo`.

**Comment by zimme** [comment] 2018-04-19 14:12
@klaussner If you set `MONGO_URL=false` it should prevent mongo from starting locally and you can't really just remove the `mongo` package currently without losing other meteor functionality that "should" be unrelated to Mongo.

**Comment by klaussner** [comment] 2018-04-19 15:26
Ah, right. Thanks for clarifying, @zimme!

@sourav2029 Is it possible that you (or one of the packages you are using) creates a collection?

The `invalid schema, expected mongodb` error is thrown if `MONGO_URL` is set to `false` and the app attempts to create a collection. We could handle `MONGO_URL === "false"` [here](https://github.com/meteor/meteor/blob/4ab6c11f08552f04cff9a7b5962223d57238f8e3/packages/mongo/remote_collection_driver.js#L35) to throw a more meaningful error.

**Comment by sourav2029** [comment] 2018-04-19 16:13
@klaussner  This is what my .`meteor/package` looks like 
standard-minifier-css@1.4.0   
standard-minifier-js@2.3.1    
es5-shim@4.7.0                
ecmascript@0.10.0              
shell-server@0.3.1            
apollo

I don't have any other dependency. I am just using meteor for packaging my app. The front end is in REACT and backend is ingraphql. But when i build the app using meteor build i see mongo and npm-mongo inside `bundle/programs/server/npm/node_modules/meteor`. I am new in using it and am not sure how this is being generated.

I want to remove all mongo dependencies and be able to run my app by using MONGO_URL=false. 
My meteor version is : "meteorRelease": "METEOR@1.6.1",

**Comment by klaussner** [comment] 2018-04-19 16:25
The `apollo` package could be the problem. It [uses `accounts-base`](https://github.com/apollographql/meteor-integration/blob/c27e63ed718ecd233d86e8d7b3014de337e08c00/package.js#L10), which [depends on `mongo`](https://github.com/meteor/meteor/blob/1c0ebbf2f0a8db5939b1bd264c73e7717a2c8528/packages/accounts-base/package.js#L27) and creates the `Meteor.users` collection.

**Comment by sourav2029** [comment] 2018-04-19 18:55
Thanks @klaussner that was it. Great help.

**Comment by jaguarj** [comment] 2018-05-08 19:27
Getting the same error: 

1. I have a MongoDB Atlas account and have reached out to them for clarification on my MONGO_URL strings as an owner and for my oplog user MONGO_OPLOG_URL string. These env vars look ok. 

2. Mongo mentions that I need to incorporate the mongo driver, but my question is where do I put that code?  SeeMongoClient below, I currently put it in my startup/both/index.js. Is that correct? I can't seem to find any info on where to place this code. I want to use the api on the server to do reads/writes so I know I probably don't want it there, I only put it here just to deploy my app and then reconfig once I was up and running. I want to place it server side. Do I make a new file in startup/server/?? or do I put in startup/both/??? 

3. In my package.json, I have mongo as a dependency "mongodb": "^3.0.7" and it still fails Galaxy deployment.

4. I have also changed to the MONGO_URL = "false" and still can't get past the meteor.js Galaxy error below. 

Any ideas would be greatly appreciated! 

```
var MongoClient = require('mongodb').MongoClient;
var uri = "mongodb+srv://username:myPassword@cluster0.mongodb.net/test";
MongoClient.connect(uri, function(err, client) {
   const collection = client.db("test").collection("devices");
   // perform actions on the collection object
   client.close();
});
``` 

```Error: invalid schema, expected mongodb
y5qpy
2018-05-08 15:12:43-04:00 at module.exports (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:19:11)
y5qpy
2018-05-08 15:12:43-04:00 at connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:486:16)
y5qpy
2018-05-08 15:12:43-04:00 at Function.MongoClient.connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:250:3)
y5qpy
2018-05-08 15:12:43-04:00 at new MongoConnection (packages/mongo/mongo_driver.js:168:11)
y5qpy
2018-05-08 15:12:43-04:00 at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
y5qpy
2018-05-08 15:12:43-04:00 at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
y5qpy
2018-05-08 15:12:43-04:00 at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
y5qpy
2018-05-08 15:12:43-04:00 at new Mongo.Collection (packages/mongo/collection.js:99:40)
y5qpy
2018-05-08 15:12:43-04:00 at meteorInstall.imports.api.links.links.js (imports/api/links/links.js:5:22)
y5qpy
2018-05-08 15:12:43-04:00 at fileEvaluate (packages/modules-runtime.js:333:9)
```

**Comment by abernix** [comment] 2018-05-10 17:05
@jaguarj What version of Meteor are you using?  The version of the `mongodb` npm which is used by Meteor is handled by Meteor via the [`npm-mongo` package](https://atmospherejs.com/meteor/npm-mongo) - you shouldn't need to `require('mongodb')`, nor install the [`mongodb`](https://npm.im/mongodb) module yourself.  As of Meteor 1.7, Meteor will ship with a newer version of `mongodb` (in the 3.x range) thanks to the work done with https://github.com/meteor/meteor/pull/9790.  Perhaps you can try the latest beta?  That beta cycle is being tracked in #9826.

**Comment by jaguarj** [comment] 2018-05-10 22:45
Ok, thanks! I've set up a 3.4 mongo instance in atlas.  I want to validate my settings with that first.  Once that is complete, I will probably test with the meteor 1.7 build.  I appreciate the information.

**Comment by Nicxzmiller** [comment] 2018-05-12 13:51
I am new to Mongo and i'm facing the same issue. please i need help.
here's the error log

(node:5277) UnhandledPromiseRejectionWarning: Error: Invalid schema, expected `mongodb` or `mongodb+srv`
    at module.exports (/Users/nicholas/Desktop/Projects/shopping-cart/node_modules/mongodb/lib/url_parser.js:21:21)
    at connect (/Users/nicholas/Desktop/Projects/shopping-cart/node_modules/mongodb/lib/mongo_client.js:880:3)
    at connectOp (/Users/nicholas/Desktop/Projects/shopping-cart/node_modules/mongodb/lib/mongo_client.js:269:3)
    at executeOperation (/Users/nicholas/Desktop/Projects/shopping-cart/node_modules/mongodb/lib/utils.js:420:24)
    at MongoClient.connect (/Users/nicholas/Desktop/Projects/shopping-cart/node_modules/mongodb/lib/mongo_client.js:260:10)
    at Promise (/Users/nicholas/Desktop/Projects/shopping-cart/node_modules/mongoose/lib/connection.js:427:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/Users/nicholas/Desktop/Projects/shopping-cart/node_modules/mongoose/lib/connection.js:424:19)
    at Mongoose.connect (/Users/nicholas/Desktop/Projects/shopping-cart/node_modules/mongoose/lib/index.js:208:15)
    at Object.<anonymous> (/Users/nicholas/Desktop/Projects/shopping-cart/seed/product-seeder.js:5:10)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
(node:5277) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5277) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by abernix** [comment] 2018-05-14 08:04
@Nicxzmiller Do you have a `MONGO_URL` set?  If so, does it start with `mongodb://` or something else?  (It should start with either `mongodb://` or `mongodb+srv://`!)

**Comment by Nicxzmiller** [comment] 2018-05-14 08:07
I’m using Mongoose:/ instead of the mongodb://

**Comment by abernix** [comment] 2018-05-22 08:16
@Nicxzmiller Though I've never tried, I do believe there are ways of getting Meteor to work with Mongoose—though I'm pretty sure all of them would involve you losing access to Meteor's publish/subscribe mechanism.

Regardless though, from what I can tell the `MONGO_URL` should still be using `mongodb://` as the scheme.  For example, even the [Mongoose connection documentation](http://mongoosejs.com/docs/connections.html) still uses `mongodb://`.

Ultimately, I think you'll need to explore other options on this in order to accomplish what you're trying to do (using Mongoose) and this issue is not the same as the problem you're encountering.

**Comment by omern92** [comment] 2019-04-29 08:54
I'm facing the same problem. Did 'meteor reset' and it didn't work. I have the latest updated Meteor. Deleted the 'meteor' directory and restored the latest working one, ran again and still, it doesn't work.

**Comment by mrsinghda** [comment] 2019-10-21 14:11
Error!Error: Invalid schema, expected `mongodb` or `mongodb+srv`

**Comment by Iamchaudharysudhir** [comment] 2022-07-04 21:32
Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"

Index.js

import express from "express";
import bodyParser from "body-parser";
import mongoose from "mongoose";
import cors from "cors";
import postRoutes from "./Routes/posts.js";
import dotenv from "dotenv";

const app = express();
dotenv.config();

app.use(bodyParser.json({ limit: "50mb", extended: true }));
app.use(bodyParser.urlencoded({ limit: "50mb", extended: true }));
app.use(cors());

app.use("/posts", postRoutes);

const PORT = process.env.PORT || 4000;

mongoose
  .connect(process.env.CONNECTION_URL, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    app.listen(PORT, console.log(`Server is running on port ${PORT}`));
  })
  .catch((err) => console.log(err.message));



.env file

CONNECTION_URL =
  "mongodb+srv://<userName>:<Password>@cluster0.v5qzigz.mongodb.net/?retryWrites=true&w=majority";

PORT = 4000;

it works fine if i do not use .env File. Process.env.CONNECTION_URL is not working ?
