### ISSUE TITLE
[1.3.2.4] test-packages fails when `onTest` has no `Npm.depends`

### ISSUE THREAD

**Issue by Kriegslustig** [meteor/meteor#6888] opened 2016-04-24 11:11 UTC
When running `meteor test-packages` on a package that has no `Npm.depends` inside `Package.onTest`, it fails. When I add a `Npm.depends` it succeeds. My guess, is that the code that loads npm dependencies in the testing mode doesn't initialize the `.npm` directory if it hasn't been done yet.

The project I'm working on is [here](https://github.com/Kriegslustig/meteor-cycle-js/). The failing package.js:

``` js
Package.onUse(function (api) {
  api.versionsFrom('1.3.2.4')
  api.use(['ecmascript', 'mongo', 'tracker', 'meteor'])
  api.mainModule('main.js')
  Npm.depends({ rx: '4.1.0' })
})

Package.onTest(function (api) {
  api.use('ecmascript')
  api.use(['tinytest', 'mongo'])
  api.use('kriegslustig:cyclejs-mongo')
  api.mainModule('tests.js')
})
```

While this succeeds:

``` js
Package.onUse(function (api) {
  api.versionsFrom('1.3.2.4')
  api.use(['ecmascript', 'mongo', 'tracker', 'meteor'])
  api.mainModule('main.js')
  Npm.depends({ rx: '4.1.0' })
})

Package.onTest(function (api) {
  api.use('ecmascript')
  api.use(['tinytest', 'mongo'])
  api.use('kriegslustig:cyclejs-mongo')
  Npm.depends({ rx: '4.1.0' })
  api.mainModule('tests.js')
})
```

The error I'm getting is:

```
kriegslustig:cyclejs-mongo: updating npm dependencies -- rx...

/[...]/.meteor/packages/templating/.1.1.9.18zxs3f++os+web.browser+web.cordova/plugin.compileTemplatesBat
ch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: ENOENT, readdir '/[...]/meteor-cycle-js/packages/cyclejs-mongo/.npm/packag
e/node_modules'
```

I'd expect that if I added any `Npm.depends` to my `Package.onTest` it should work. But the following produces an infinite loop:

``` js
Package.onTest(function (api) {
  api.use('ecmascript')
  api.use(['tinytest', 'mongo'])
  api.use('kriegslustig:cyclejs-mongo')
  Npm.depends({ leftpad: '0.0.0' })
  api.mainModule('tests.js')
})
```

That looks something like this:

``` js
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
local-test:kriegslustig:cyclejs-mongo: updating npm dependencies -- leftpad...
kriegslustig:cyclejs-mongo: updating npm dependencies -- rx...
local-test:kriegslustig:cyclejs-mongo: updating npm dependencies -- leftpad...
kriegslustig:cyclejs-mongo: updating npm dependencies -- rx...
local-test:kriegslustig:cyclejs-mongo: updating npm dependencies -- leftpad...
kriegslustig:cyclejs-mongo: updating npm dependencies -- rx...
local-test:kriegslustig:cyclejs-mongo: updating npm dependencies -- leftpad...
kriegslustig:cyclejs-mongo: updating npm dependencies -- rx...
local-test:kriegslustig:cyclejs-mongo: updating npm dependencies -- leftpad...
kriegslustig:cyclejs-mongo: updating npm dependencies -- rx...
local-test:kriegslustig:cyclejs-mongo: updating npm dependencies -- leftpad...
kriegslustig:cyclejs-mongo: updating npm dependencies -- rx...
local-test:kriegslustig:cyclejs-mongo: updating npm dependencies -- leftpad...
kriegslustig:cyclejs-mongo: updating npm dependencies -- rx...
local-test:kriegslustig:cyclejs-mongo: updating npm dependencies -- leftpad...
kriegslustig:cyclejs-mongo: updating npm dependencies -- rx...
```

(since leftpad is kind of a special case, I also tested it with `lodash` with the same result.)

**Platform**: Meteor 1.3.2.4 web (also tested with release-1.3.3 branch, with the same result)
**Dependencies**: Probably irrelevant
**Reproduction**: `git clone https://github.com/Kriegslustig/meteor-cycle-js.git && cd meteor-cycle-js && git submodule update --init && cd packages/cyclejs-mongo && git checkout broken-ontest && meteor test-packages`

**Comment by benjamn** [comment] 2016-04-24 20:58
@tmeasday This seems related to the problem of tests not working until you've run the app at least once?

**Comment by Kriegslustig** [comment] 2016-04-25 05:49
Not sure, but when you run the above code for reconstruction and then `git checkout master`, the test will run. So it's probably something else.

**Comment by tmeasday** [comment] 2016-04-25 19:31
@benjamn 

> This seems related to the problem of tests not working until you've run the app at least once?

Hmm, I don't think it's the same, that was running in `meteor test`, rather than `meteor test-packages`. 

Here's a simple repro: https://github.com/tmeasday/test-npm-depends.git

I see:
  1. Error above on 1.3 + checked out `devel`.
  2. It works on 1.2.

@Kriegslustig this is easily workaround-able, just put your `Npm.depends` at the top-level in your `package.js`.

@benjamn it occurs to me that this could be the answer to testing with npm peer deps -- you could put an `Npm.depends` block inside your `onTest` block. (It doesn't currently seem to do anything however).

**Comment by Kriegslustig** [comment] 2016-04-25 20:12
@tmeasday That's what i ended up doing to fix it, thanks. Though I thought that depending on any npm-package should work. But as documented in the initial comment, if I depend on anything but the package I depend inside the `onUse` block the build process gets caught in an infinite loop.

**Comment by abernix** [comment] 2017-01-05 18:50
I just documented some of my own research on this matter in https://github.com/meteor/meteor/issues/8200#issuecomment-270723863, if anyone coming to this issue is interested.

**Comment by hwillson** [comment] 2017-02-23 15:17
Hi all - as mentioned previously in this issue thread, this problem is caused by using `Npm.depends` within the `onTest` function (for more specific details, see @abernix's excellent explanation in https://github.com/meteor/meteor/issues/8200#issuecomment-270723863). The solution to this problem is to use `Npm.depends` outside of `onTest` / `onUse`, at the top level of the `package.js` file. This isn't really a workaround - it's actually the recommended approach when using `Npm.depends` (and is documented in the [npm dependencies](https://guide.meteor.com/writing-atmosphere-packages.html#npm-dependencies) section of the Guide). Yes the Package API could be updated to prevent the use of `Npm.depends` within `onTest` / `onUse` (by throwing an error for example), but given that using `Npm.depends` is no longer the recommended approach for handling peer npm dependencies with Meteor (as documented in the [Peer npm dependencies](https://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies) section of the Guide), the chances of this issue being worked on further are pretty low. Give this, and the fact that anyone encountering this issue will be able to find this issue thread when searching the GH issue archive, I'll close this issue. Happy to re-open if anyone disagrees. Thanks for reporting this issue originally!

**Closed by hwillson** 2017-02-23 15:17 UTC
Labels: Project:Testing
