### ISSUE TITLE
Meteor v1.4.3.2 node version confusion

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#8554] opened 2017-04-02 18:34 UTC
I read [here](https://github.com/meteor/meteor/blob/devel/History.md#v1432-2017-03-14) that Meteor v1.4.3.2 has upgraded to node v4.8.

I have Meteor v1.4.3.2 installed.  When I query for the meteor version I get v4.7.3:

```
E:\>meteor node --version
v4.7.3
```

Did node v4.8 fail to get included in 1.4.3.2?  Or is my install messed up?

### Environment
meteor: 1.4.3.2 [node v4.7.3 (as reported)] [npm v4.3.0]
node: v4.7.3
npm: 2.5.11

### npm also confusing
When I look [here](https://nodejs.org/en/download/releases/), I see that node v4.8 comes with npm 2.15.11.
meteor reports npm version as 4.3.0
```
E:\>meteor npm --version
4.3.0
```
The [lastest ](https://nodejs.org/en/download/current/)version of node comes with npm 4.2.0.  Where is npm 4.3.0?  How can I install it independently of node?

**Comment by abernix** [comment] 2017-04-03 07:11
Thanks for reporting this.  This was unintentional and was my own oversight when I built Meteor and released Meteor 1.4.3.2 since I didn't realize that the Windows versions for those were kept in a [separate file](https://github.com/meteor/meteor/blob/f285bffed8bef30c4c5bf1a88f412ca9d12c0258/scripts/generate-dev-bundle.ps1#L4-L6) and not stored in [`build-dev-bundle-common.sh`](https://github.com/meteor/meteor/blob/devel/scripts/build-dev-bundle-common.sh#L8-L10).  Sorry about that!

I'd already caught this though and it's already fixed in the next release candidate for the Meteor 1.4.x.y release series (see #8439) where I've mentioned the problem (and [a fix](https://github.com/meteor/meteor/pull/8505) to make sure these are always properly updated) in the [`History.md`](https://github.com/meteor/meteor/blob/release-1.4.3.x/History.md#vnext).  This should be out soon.

As far as `npm` being a different version than the official one shipped with `node@4.8.0`, `npm` is just a package so you can install whatever version you want using `npm install npm@version`.  Meteor ships with `npm@4` and we recommend it over `npm@2` for a variety of reasons, but especially important on Windows, for its flatter dependency tree (which overcomes Windows file path length limitations).

**Comment by nosizejosh** [comment] 2017-04-03 08:56
@abernix @brucejo75 is this related to my [issue](https://github.com/meteor/meteor/issues/8556)? I have tried all possible means including fresh install of meteor but cannot get meteor to run any project.

**Comment by abernix** [comment] 2017-04-03 09:38
@nosizejosh No, the result here is you would still be running a project with an older version of Node.  Unrelated. :)

**Comment by brucejo75** [comment] 2017-04-03 16:15
@abernix, Thanks for the info and glad [you are on it](https://github.com/meteor/meteor/pull/8439)...  Should I close this now?  Or wait until 1.4.4 comes out and I can verify? [not sure on protocol].

Yeah, I was searching for how to install other versions of `npm` and did not think to simply try `npm` :-).

@nosizejosh, sorry, my build is working fine.  Simply was out of sync with [`History.md`](https://github.com/meteor/meteor/blob/release-1.4.3.x/History.md#vnext).

**Comment by abernix** [comment] 2017-04-03 17:33
Let's leave this open for the sake of others who may encounter it.   I've added it to the milestone to make sure it gets closed, but feel free to close once 1.4.4 has officially come out and you've confirmed it works. ;)

**Comment by benjamn** [comment] 2017-04-14 22:28
Can this be closed now? 🤞

**Comment by abernix** [comment] 2017-04-15 00:01
Yes!  I confirmed that this is fixed!  🎉

**Closed by abernix** 2017-04-15 00:01 UTC
Labels: bug, confirmed, fixed, Project:Windows

**Comment by brucejo75** [comment] 2017-04-16 16:40
looks good.
