### ISSUE TITLE
node-sass NPM binary in meteor package fails to rebuild when not included locally.

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#8014] opened 2016-11-04 13:06 UTC
To be honest, I don't know if this is a meteor, npm or node-sass bug.
I'm the maintainer of `fourseven:scss`, which depends on the npm `node-sass` module, which needs to be compiled. Since meteor 1.4.2 I've been publishing versions without `publish-for-arch`. 

However, some users report they get an error like:
```
While loading fourseven:scss@3.10.0...:
error: Command failed:
/.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --update-binary
module.js:327
throw err;
^

Error: Cannot find module
'/tmp/mt-1ftbq5x/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-eopfyt/node_modules/node-sass/scripts/install.js'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:974:3

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv
"/.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--update-binary"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.10.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.10.0 install script 'node
scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/tmp/mt-1ftbq5x/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-eopfyt/npm-debug.log
module.js:327
throw err;
```
Note that this is a trace I've got while running `meteor build` as root (with `--unsafe-perm` inside a docker container. But other users have reported this also happens when running meteor normally, although I haven't been able to reproduce that.

Now comes the weird thing. If I include the code of `fourseven:scss` in the `packages` folder local to my meteor project, I don't get this error. That's why I think this is a meteor bug.

**Comment by gossel-j** [comment] 2016-11-08 16:32
I get the same error when running in the same environment (docker and meteor 1.4.2).

**Comment by abernix** [comment] 2016-11-21 16:15
Would you be able to just provide a docker image this could be tested with?  Published or on GitHub, either way but it would be easier than recreating this from scratch.

**Comment by c9s** [comment] 2016-12-03 12:03
same error here.

I use `meteor publish-for-arch  c9s:sharp@0.16.2_4` but it always reports:

```
=> Errors while publishing build:

While publishing package build for c9s:sharp:
error: Cannot override existing build
```

**Comment by c9s** [comment] 2016-12-03 12:17
I have a package https://github.com/c9s/meteor-sharp that wraps "sharp" package, and when I use:

    meteor publish-for-arch c9s:sharp@0.16.2_4

It reports:

```
babel-compiler   added, version 6.9.1_1
c9s:sharp        added, version 0.16.2_4
modules-runtime  added, version 0.7.6_1
underscore       added, version 1.0.9

=> Errors while publishing build:

While publishing package build for c9s:sharp:
error: Cannot override existing build
```

However, if I run `show` command:

```
{
  "exports": [],
  "implies": [],
  "dependencies": [
    {
      "name": "ecmascript",
      "constraint": "0.5.8_1",
      "weak": false
    },
    {
      "name": "isobuild:isopack-2",
      "constraint": "1.0.0",
      "weak": false
    }
  ],
  "name": "c9s:sharp",
  "version": "0.16.2_4",
  "description": "Lovell Fuller's [sharp](http://github.com/lovell/sharp) bindings to the libvips\nimage processing library, packaged for Meteor.\n\nFor full documentation, visit [sharp.dimens.io](http://sharp.dimens.io/).\n\nFor sample use, see the\n[meteor-sharp-demo](https://github.com/bdunnette/meteor-sharp-demo) repository.",
  "summary": "Adds bindings to the libvips image processing library",
  "git": "https://github.com/c9s/meteor-sharp.git",
  "publishedBy": "c9s",
  "publishedOn": {
    "$date": 1480756019375
  },
  "installed": false,
  "architecturesOS": [
    "os"
  ]
}
```

Anyway, it used to work with 1.3.5. I think this is a bug, can't find any information about wrapping binary modules.

**Comment by c9s** [comment] 2016-12-03 14:46
Same for npm-bcrypt. It supposed to have binary bcrypt installed for the deployment, however on the production environment, it shows "This is the pure js bcrypt..."

**Comment by jbbr** [comment] 2016-12-14 14:40
Maybe related thing with `dispatch:phantomjs-tests` (dependency of `dispatch:mocha-phantomjs`:

Client tests fail on Linux because phantomjs binary is for OSX. `meteor npm rebuild` does not help.

Problem exists since the package is arch Independent (0.0.6+):
```
  "architecturesOS": [  "os" ]
```

Rebuild/arch independent packages seem to have some problem.

@c9s I also get the bcrypt message. What does seem to work is to add bcrypt to the local package.json and built it from there.

**Comment by hwillson** [comment] 2017-09-05 18:22
Without a concrete reproduction this is definitely a tricky one to track down. Is anyone still seeing this happen with a recent version of Meteor? Given that there hasn't been any activity on this issue in some time, and there have been 9 Meteor releases since this issue was created, I'll close it for now. I'm happy to re-open this issue if anyone is still noticing this problem (and can ideally provide a reproduction). Thanks!

**Closed by hwillson** 2017-09-05 18:22 UTC
