### ISSUE TITLE
Initial page load time in 1.8.3 is much too long

### ISSUE THREAD

**Issue by bobcassels** [meteor/meteor#10842] opened 2019-12-30 23:52 UTC
Bug in versions 1.8.2, 1.8.3
Worked fine in 1.8.1

macOS Catalina 10.15.2
Chrome 79.0.3945.88
Repository with test case: [https://github.com/NextDroid/meteor-bug-slow-1.8.3](https://github.com/NextDroid/meteor-bug-slow-1.8.3)

You will see that initial page load times are fine in Meteor 1.8.1, but unacceptably long in 1.8.2 and 1.8.3.

Clone the repository, install node modules, run (as described in README). 
Initial page load time is around 5 seconds.
Feel free to log in (see README), and click around. It's been mostly neutered, but a few things work. Note that the `master` branch is on Meteor 1.8.1.

Then update to Meteor 1.8.3, and repeat. See that the initial page load time (and refresh page time) is now over a minute. 1:15 on my 2015 MacBook Pro laptop. You can update using `meteor update`, or check out the `update-to-meteor-1.8.3` branch.

I didn't measure build times. They feel a little longer, as reported by others, but I am mostly concerned with page load times, since that's visible to my users.

**Comment by KoenLav** [comment] 2019-12-31 14:16
Most likely a duplicate of:

https://github.com/meteor/meteor/issues/10712

Try rewriting all your @material-ui/icons imports without deateucturing.

**Comment by bcasselsND** [comment] 2019-12-31 14:33
Thanks for the quick response! And the workaround.

Are you suggesting that the slowness with importing this way won't be fixed? I prefer that style, and it used to work fine. (Meteor tree-shaking is a good thing!) If I can expect it to be fixed in the near-ish future, I'll stick with Meteor 1.8.1 until it's fixed.

**Comment by KoenLav** [comment] 2019-12-31 14:34
I think it will be fixed, was just presenting a temporary workaround (also a way of validating that you are indeed experiencing the same issue).

**Comment by bcasselsND** [comment] 2019-12-31 14:35
Cool, thanks! I'll try your workaround, to make sure it is the problem.

**Comment by bcasselsND** [comment] 2019-12-31 15:43
Your workaround for material-ui/icons speeds initial page load a lot. It's down to about 12 seconds. That's still double what it was in 1.8.1, but a lot better. I see that I use destructuring imports a lot, in particular for mdi-material-ui icons. I also see that mdi now suggests a different way to use their icons. So I'll switch to that. I'll keep you posted on progress.

I pushed the workaround changes, to my `update-to-meteor-1.8.3` branch.

**Comment by bcasselsND** [comment] 2019-12-31 19:02
Changes to the "new" way of using MDI icons brings the time for 1.8.3 down to 3 or 4 seconds. So it appears that the material-ui/icons imports were causing all of the problems with page load times. So I agree that this is a duplicate of #10712. No new information in this example.

**Comment by sebakerckhof** [comment] 2020-01-02 13:27
Closing as duplicate. Thanks @KoenLav

**Closed by sebakerckhof** 2020-01-02 13:27 UTC
