### ISSUE TITLE
HTTP package with npmRequestOptions.encoding = null on a URL that return 404 but with a body : it crash

### ISSUE THREAD

**Issue by Rebolon** [meteor/meteor#4929] opened 2015-08-11 12:54 UTC
Hi,

i encounter a problem this night on one of my app. This happens when
* Meteor 1.1.0.3
* i add HTTP package
* i use npmRequestOptions with encoding=null
* i call a url that return a status code >= 400 AND a Body

Here is the code : 

    var response = HTTP.get(urlTo404ButWithContent, {
        "npmRequestOptions": {
            "encoding": null
        }
    });

Here is the error (not catchable) : 

    W20150811-14:32:48.809(2)? (STDERR) TypeError: Object <html>
    W20150811-14:32:48.809(2)? (STDERR) <body>
    W20150811-14:32:48.809(2)? (STDERR)    There is no content found for your request here.
    W20150811-14:32:48.809(2)? (STDERR) </body>
    W20150811-14:32:48.809(2)? (STDERR) </html> has no method 'replace'
    W20150811-14:32:48.809(2)? (STDERR)     at makeErrorByStatus (packages/http/httpcall_common.js:29:1)
    W20150811-14:32:48.809(2)? (STDERR)     at Request._callback (packages/http/httpcall_server.js:113:1)
    W20150811-14:32:48.809(2)? (STDERR)     at Request.self.callback (/home/me/projects/meteor-issue-http/.meteor/local/isopacks/http/npm/node_modules/request/request.js:344:22)
    W20150811-14:32:48.809(2)? (STDERR)     at Request.emit (events.js:98:17)
    W20150811-14:32:48.810(2)? (STDERR)     at Request.<anonymous> (/home/me/projects/meteor-issue-http/.meteor/local/isopacks/http/npm/node_modules/request/request.js:1239:14)
    W20150811-14:32:48.810(2)? (STDERR)     at Request.emit (events.js:117:20)
    W20150811-14:32:48.810(2)? (STDERR)     at IncomingMessage.<anonymous> (/home/me/projects/meteor-issue-http/.meteor/local/isopacks/http/npm/node_modules/request/request.js:1187:12)
    W20150811-14:32:48.810(2)? (STDERR)     at IncomingMessage.emit (events.js:117:20)
    W20150811-14:32:48.810(2)? (STDERR)     at _stream_readable.js:944:16
    W20150811-14:32:48.811(2)? (STDERR)     at process._tickCallback (node.js:442:13)

Here is an app on this repository that allows the reproduction of this issue (it's a really simple app) : 
https://github.com/MeteorLyon/meteor-httperror-bug

There is also a branch here where i did a quick fix (file packages/http/httpcall_common.js): 
https://github.com/MeteorLyon/meteor/tree/fix/httpBuffer

**Comment by stubailo** [comment] 2015-08-11 18:45
Duplicate of: https://github.com/meteor/meteor/issues/4847

**Comment by stubailo** [comment] 2015-08-11 18:46
@Rebolon could you submit a PR with that fix? And tag the other issue please

**Closed by stubailo** 2015-08-11 18:45 UTC

**Comment by Rebolon** [comment] 2015-08-11 19:56
ok, i just did the PR https://github.com/meteor/meteor/pull/4940
I've added a comment with the ref to the PR but i didn't find the way to add the right tag. Could you do it or explain me how to do ?
