### ISSUE TITLE
[1.4.2] Build failing on error -122 (oauth-sign/LICENSE)

### ISSUE THREAD

**Issue by snajjar** [meteor/meteor#8024] opened 2016-11-06 14:16 UTC
Hello, 
since Meteor 1.4.2, i'm not able to use meteor build on my remote servers. Upgrading disk from 1G to 2G doesn't solve the issue. Can't find anything related to "system error -122".
Any information about this will help.

Edit: BTW I use fibers/future in the server's code, and i've done a meteor npm install fibers.

```
-----> Building meteor bundle
/home/vcap/.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/runtime/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
Error: Unknown system error -122: Unknown system error -122, open '/tmp/staged/deploy/.build575714.bundle/programs/.build468450.server/npm/node_modules/oauth-sign/LICENSE'
    at Error (native)
 => awaited here:
    at Promise.await (/home/vcap/.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/runtime/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:39:12)
    at Object.wrapper [as writeFile] (/tools/fs/files.js:1522:32)
    at /tools/isobuild/builder.js:501:17
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:456:34)
    at /tools/isobuild/builder.js:485:13
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:456:34)
    at Builder.copyDirectory (/tools/isobuild/builder.js:512:5)
    at /tools/isobuild/bundler.js:1999:17
    at Function._.each._.forEach (/home/vcap/.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at JsImage.write (/tools/isobuild/bundler.js:1958:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2227:13)
    at /tools/isobuild/bundler.js:2322:30
    at /tools/isobuild/bundler.js:2455:9
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:2445:26
    at /tools/isobuild/bundler.js:2385:7
    at /tools/isobuild/bundler.js:2786:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2619:31)
    at /tools/isobuild/bundler.js:2566:32
    at Object.withCache (/tools/fs/files.js:1597:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2566:16)
    at buildCommand (/tools/cli/commands.js:927:30)
    at Command.func (/tools/cli/commands.js:802:12)
    at /tools/cli/main.js:1454:23

```

**Comment by snajjar** [comment] 2016-11-07 11:03
It seems to be related to space and quotas. However, expanding the space to 2G didn't solve the issue. Does meteor now need more than 2Go disk to build a (fairly simple) application? The deployed folder once compiled is sized 450MB..

**Comment by abernix** [comment] 2016-11-08 15:09
What was the last version of Meteor which worked?   If you downgrade the the most recent 1.4.1 release (1.4.1.3) does the problem go away?

You'll need to provide a lot more information in order to help reproduce this.  The amount of disk space you need to build your application is obviously determinate on how big your application is and what packages you include.  That appears to be a kernel error, but I have no idea what from (though since it's happening in a write function, I might assume it has something to do with a disk issue).

You should also include information about what _exactly_ environment (Unix flavor, HDD configuration, etc.) you're building it on and include a link to an example repro which demonstrates.  Otherwise it is very unlikely that anyone will be able to debug this problem.

**Comment by snajjar** [comment] 2016-11-08 16:16
Hello @abernix, thank you for your answer.

I have not been able (yet) to build a repro with a simple meteor app. I can't link to mine because it's my customer's property.

The problem appears to be linked to space quota, the build is taking more than 2G on disk. The servers are on Linux Darwin, can't get the version tho (thoses cloud providers nowaday... I run the app on IBM bluemix). It doesn't happen when i run meteor build locally.

The problem is here since the upgrade to 1.4.2 (from 1.4.1.3), so it seems that 1.4.2 is taking more space to build (maybe on /tmp? The 1.4.2 announcement is about improving rebuild performances, does it leaves so cache somewhere? Can i measure it?).

I've worked on a workaround so far (building locally, then upgrading the bundle to production), but that requires me to upload 150MB instead of 4MB, so it's consistently slower to deploy. 

Here's a list of all the packages included in the application:

> 
aadams:progress                         0.0.4  Animated, responsive progress bar
accounts-base                           1.2.14  A user account system
accounts-password                       1.3.1  Password support for accounts
alanning:roles                          1.2.15  Authorization package for Meteor
aldeed:autoform                         5.8.1  Easily create forms with automatic insert and update, and au...
aldeed:autoform-bs-datepicker           1.1.1  Custom bootstrap-datepicker input type for AutoForm
aldeed:simple-schema                    1.5.3  A simple schema validation object with reactivity. Used by c...
benjaminrh:user-session                 0.2.0  Provides a UserSession object that works just like Session d...
blaze-html-templates                    1.0.5  Compile HTML templates into reactive UI with Meteor Blaze
dburles:collection-helpers              1.1.0  Transform your collections with helpers that you define
dfischer:phantomjs                      1.0.4  Phantom JS wrapper
easy:search                             2.1.0  Easy-to-use search with Blaze Components (+ Elastic Search S...
ecmascript                              0.5.9  Compiler plugin that supports ES2015+ in all .js files
elvishjerricco:subs-cache               0.1.0  A package for caching Meteor subscriptions.
email                                   1.1.18  Send email messages
es5-shim                                4.6.15  Shims and polyfills to improve ECMAScript 5 support
force-ssl                               1.0.13  Require this application to use HTTPS
fortawesome:fontawesome                 4.7.0  Font Awesome (official): 500+ scalable vector icons, customi...
fullcalendar:fullcalendar               2.9.0  Full-sized drag & drop event calendar
http                                    1.2.10  Make HTTP calls to remote servers
iron:router                             1.0.13  Routing specifically designed for Meteor
jparker:crypto-base64                   0.1.0  Base64 (en/de)coding for CryptoJS, standard secure crypto al...
jparker:crypto-md5                      0.1.1  MD5 algorithm for CryptoJS, standard secure algorithms
jquery                                  1.11.10  Manipulate the DOM using CSS selectors
kit:sweetalert                          1.1.3  A beautiful replacement for JavaScript's alert
meteor-base                             1.0.4  Packages that every Meteor app needs
meteorhacks:kadira                      2.30.2  Performance Monitoring for Meteor
meteorhacks:ssr                         2.2.0  Server Side Rendering for Meteor with Blaze
meteorhacks:subs-manager                1.6.4  Subscriptions Manager for Meteor
mizzao:user-status                      0.6.6  User connection and idle state tracking for Meteor
mobile-experience                       1.0.4  Packages for a great mobile user experience
momentjs:moment                         2.15.2  Moment.js (official): parse, validate, manipulate, and disp...
mongo                                   1.1.14  Adaptor for using MongoDB and Minimongo over DDP
mquiblier:extthree                      0.0.1+
multiply:iron-router-progress           1.0.2  Progressbar for iron:router
natestrauser:connection-banner          0.4.3  A banner that displays when meteor server is disconnected wi...
natestrauser:publish-performant-counts  0.1.1* Publish counts of large collections efficently
ogourment:settings                      1.0.1  Reliably initialize Meteor.settings.
podometric:podo3d                       0.0.1+
rajit:bootstrap3-datepicker             1.5.1  Meteor packaging of eternicode/bootstrap-datepicker for Boot...
random                                  1.0.10  Random number generator and utilities
reactive-var                            1.0.11  Reactive variable
sacha:spin                              2.3.1  Simple spinner package for Meteor
session                                 1.1.7  Session variable
shell-server                            0.2.1  Server-side component of the `meteor shell` command.
silentcicero:jszip                      0.0.4  Create, read and edit .zip files on the client
standard-minifier-css                   1.3.2  Standard css minifier used with Meteor apps by default.
standard-minifier-js                    1.2.1  Standard javascript minifiers used with Meteor apps by default.
tracker                                 1.1.1  Dependency tracker to allow reactive callbacks
tsega:bootstrap3-datetimepicker         4.17.37_1  Bootstrap 3 DateTime picker from @Eonasdan, packaged for...
twbs:bootstrap                          3.3.6  The most popular front-end framework for developing responsi...
underscore                              1.0.10  Collection of small helpers: _.map, _.each, ...
vsivsi:file-collection                  1.3.6  Collections that efficiently store files using MongoDB GridF...
yogiben:admin                           1.2.8  A complete admin dashboard solution
`

And here's the list of Meteor npm dependencies:
`  "dependencies": {
    "bcrypt": "^0.8.7",
    "busboy": "^0.2.13",
    "fibers": "^1.0.15",
    "jszip": "^3.1.3",
    "meteor-node-stubs": "~0.2.0",
    "webshot": "^0.18.0"
  }
`

I'll link to a reproduction if i'm able to do it.

**Comment by abernix** [comment] 2016-11-08 20:09
I don't have answers about the size differences for 1.4.2 right now, but perhaps you should explore building it locally (or within a VirtualBox or docker image on your own machine, for example) using the `meteor build` command and taking a look at the differences yourself using the usual Unix file system tools (`df`, `du`, etc.).

If you find anything substantial please do report back!  It may be that they are necessary changes in order to speed up the build (which was something achieved in 1.4.2).

**Comment by abernix** [comment] 2016-12-12 16:42
Thanks for filing this originally.  I'm going to close this as there haven't been any updates on it and it hasn't gained any traction from others.  My suggestion above still stands.  Happy to look into it further, but would need additional information and research from your side as well!

**Closed by abernix** 2016-12-12 16:42 UTC
Labels: can't-reproduce
