### ISSUE TITLE
Upgrade break app Errors prevented isopacket load: While loading isopacket 'ddp'

### ISSUE THREAD

**Issue by jamalazza** [meteor/meteor#7227] opened 2016-06-15 17:44 UTC
on windows 7 Errors prevented isopacket load:  While loading isopacket `ddp`

**Comment by benjamn** [comment] 2016-06-15 18:25
Duplicate of https://github.com/meteor/meteor/issues/7221.

**Closed by benjamn** 2016-06-15 18:25 UTC
