### ISSUE TITLE
Terminal output on OS X doesn't print linebreaks properly on server logs/exceptions

### ISSUE THREAD

**Issue by aardvarkk** [meteor/meteor#5877] opened 2015-12-24 09:10 UTC
If I manage to generate a server exception the stack track doesn't properly print out the newline breaks contained within the text. I think the message would be a lot easier to read if the newlines were rendered properly. Here's an example of the output text, and notice all of the `\n` instances.

<img width="604" alt="screen shot 2015-12-24 at 4 09 07 am" src="https://cloud.githubusercontent.com/assets/1251092/11992464/37fb4872-a9f4-11e5-85aa-302eb6f960da.png">

**Comment by timbotnik** [comment] 2015-12-29 23:33
I could not reproduce this on OSX 10.10.4 - can you provide a simple reproduction?

**Comment by aardvarkk** [comment] 2016-01-07 00:22
Alright, so this is a weird one... it took me a while to reproduce it! Seems it's some bizarre combination of Iron Router and Kadira that makes it go off? Anyway, this triggers it. Also notice that the text for exceptions that's normally pink switches to black somewhere along the line...

```
meteor create repro
cd repro
meteor remove autopublish
meteor add iron:router
meteor add meteorhacks:kadira
```

Now inside `repro.js` add this:

```
if (Meteor.isServer) {
  Meteor.publish("test", function() {
    foo
  })
}

Router.route("/", {
  waitOn: function() {
    Meteor.subscribe("test")
  }
})
```

Terminal output is now in black and white and the newlines aren't working anymore. Not sure whose issue this is, but that's the effect I'm seeing!

**Comment by abernix** [comment] 2016-07-27 07:27
Closing as this behavior as this bug hasn't picked up traction.  It must be caused by some interference with the v8 Stack Trace API by a third-party package.  I'd guess `kadira` since it actually captures errors, but this is just pure speculation.  An issue should be opened with kadira if this behavior has continued.

**Closed by abernix** 2016-07-27 07:27 UTC
Labels: can't-reproduce
