### ISSUE TITLE
[1.3-beta.16]  error while deploying to production

### ISSUE THREAD

**Issue by cj** [meteor/meteor#6452] opened 2016-03-10 02:07 UTC
Here's a back-trace of the error:  https://gist.github.com/cj/d40ee2421fbc36abb709

I tried with and without the `cosmos:browserify` package.

Here's the buildpack I tried it with on heroku https://github.com/cj/meteor-buildpack-horse

**Comment by jamiter** [comment] 2016-03-10 08:51
This buildpack worked for me for beta.12: https://github.com/robinnewhouse/meteor-buildpack-horse

**Comment by benjamn** [comment] 2016-03-10 15:59
Possible dupe of #6449.

**Comment by benjamn** [comment] 2016-03-20 19:28
Fixed in [`1.3-rc.4`](https://github.com/meteor/meteor/issues/6266#issuecomment-198997482).

**Closed by benjamn** 2016-03-20 19:28 UTC
