### ISSUE TITLE
Meteor bundler/build issue when using yarn

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#8539] opened 2017-03-29 16:30 UTC
Reproduction repo: https://github.com/ffxsam/meteor-yarn-bug

Clone and install (using `meteor yarn`), then run. Note in the browser console that the `asn1` and `asn1.js` imports are identical, even though they shouldn't be. Run `node` in the project folder and look at the differences when typing `require('asn1')` and `require('asn1.js')`.

Reference: https://forums.meteor.com/t/managing-node-packages-with-yarn/33611/5

**Comment by benjamn** [comment] 2017-03-30 14:08
If you `meteor update --release 1.4.4-rc.4` I believe this should be fixed. Thanks for reporting this, and for providing a reproduction!

**Closed by benjamn** 2017-03-30 14:08 UTC
Labels: confirmed, known-fix

**Comment by ffxsam** [comment] 2017-03-30 15:26
Awesome (and quick) work, Ben!! Thanks a million. It's not urgent so I'll just wait for the official 1.4.4 release to update my actual project, but I did test this out and it worked perfectly. Can't wait to use yarn instead of npm! ⚡️ ⚡️

**Comment by ffxsam** [comment] 2017-04-02 05:29
Hey @benjamn, I got this error in an unrelated project:

```
yarn build v0.21.3
$ meteor build .deploy/ --architecture os.linux.x86_64

WARNING: The output directory is under your source tree.
         Your generated files may get interpreted as source code!
         Consider building into a different directory instead
         meteor build ../output

Errors prevented bundling:
While minifying app code:
packages/minifyStdJS_plugin.js:113:28: UglifyJS minification error:

SyntaxError: Name expected at
node_modules/react-addons-create-fragment/index.js line 343

within packages/modules.js (line: 112755, col: 6, pos: 13953756):

var {result, keyPrefix, func, context} = bookKeeping;

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS_plugin.js:113:28)
at packages/minifyStdJS_plugin.js:145:9
at Array.forEach (native)
at UglifyJSMinifier.processFilesForBundle
(packages/minifyStdJS_plugin.js:130:9)


error Command failed with exit code 1.
```

If I wipe out `node_modules` and `yarn.lock` and install via `meteor npm i`, it builds just fine. But with yarn, I get the above. Is this maybe related to your fix?

Actually, I updated the project to 1.4.4-rc.4 and got a different error:

```
yarn build v0.21.3
$ meteor build .deploy/ --architecture os.linux.x86_64

WARNING: The output directory is under your source tree.
         Your generated files may get interpreted as source code!
         Consider building into a different directory instead
         meteor build ../output

   Minifying app code                        -
<--- Last few GCs --->

   93837 ms: Scavenge 1390.8 (1456.2) -> 1390.8 (1456.2) MB, 0.9 / 0 ms (+ 2.4 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   95260 ms: Mark-sweep 1390.8 (1456.2) -> 1384.0 (1456.2) MB, 1422.8 / 0 ms (+ 3.7 ms in 2 steps since start of marking, biggest step 2.4 ms) [last resort gc].
   96585 ms: Mark-sweep 1384.0 (1456.2) -> 1391.2 (1456.2) MB, 1324.4 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2dbcfd4b4629 <JS Object>
    1: get [/Users/samh/.meteor/packages/standard-minifier-js/.2.0.0-rc.4.qcsjfd++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-traverse/lib/path/index.js:~76] [pc=0x10101a6fbf9c] (this=0x24362cac7e89 <JS Function NodePath (SharedFunctionInfo 0xbb5fdb54b21)>,_ref=0xdfc645fbfe9 <an Object with map 0x9902119dde9>)
    2: node [/Users/sa...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

I can't post this repo publicly but I can add you to a private repo. Is that cool?

**Comment by abernix** [comment] 2017-04-03 10:31
@ffxsam That error is not related to the fix.  It would appear that Uglify is failing to minify the project (because of reasons stated in #8378), and thus reverting to Babili (thanks to #8519) then Babili is croaking with the OOM (out of memory) error because of the sheer size of the file it's trying to minify.

What is the size of your `modules.js` in that project?  For example, what is the output of the following when ran from the project root:

    ls -la .meteor/local/build/programs/*/packages/modules.js

Lastly, I'm curious if the error goes away for you by replacing `standard-minifier-js` with `abernix:standard-minifier-js@1.3.19`?

**Comment by ffxsam** [comment] 2017-04-03 15:07
Hey Jesse, thanks for chiming in!

Of course, now I can't replicate it. 😄  The meteor build process works just fine now. This is the output of the `ls -lha` command:

```
-r--r--r--  1 samh  staff    31K Apr  1 22:01 .meteor/local/build/programs/server/packages/modules.js
-r--r--r--  1 samh  staff    38M Apr  1 22:45 .meteor/local/build/programs/web.browser/packages/modules.js
```

I'll also try doing `rm -rf .meteor/local/build` and rebuilding to see how those numbers pan out next time.

Side question: is it just generally a good idea to replace `standard-minifier-js` with yours? And is your version going to be official at some point?

**Comment by abernix** [comment] 2017-04-04 05:30
My version is the "bleeding-edge" (read: not "stable") version of UglifyJS's ["Harmony branch"](https://github.com/mishoo/UglifyJS2/tree/harmony).  The most important aspect of it is that it has ES6 support.

However, given it's constant state of flux/development, we're not certain we want to officially release it yet as we've seen some regressions and some improvements.  As you can see from the [commit log there](https://github.com/mishoo/UglifyJS2/commits/harmony), they've finally become super-active on `harmony` again after it being idle for months (and often, longer).

The `modules.js` weighing in at 39MB is certainly to blame as Babili seems to struggle a bit on larger files (likely relevant to https://github.com/babel/babili/issues/332).  

(Also, off-topic, but you'll likely benefit from Meteor 1.5's dynamic `import`s when it comes time to slim down that `modules.js` file. :wink:)

Anyhow, a bit strange that you only observed that behavior with `yarn` and not with `npm`.  I'd be curious in seeing the differences in your dependency tree, and you could also find some information by investigating that `.meteor/local/build/programs/web.browser/packages/modules.js` file after both installs to see what the differences are in the `node_modules/react-addons-create-fragment/index.js` file (you should be able to search the file for that name - it'll just be a concatenated collection of your npm packages).

**Comment by ffxsam** [comment] 2017-04-04 15:59
I wish I could replicate it again. If it comes up, I'll come back to this thread (unless you'd prefer I open a new ticket).

BTW, 38MB is _insane_ for this project! It's a small app.. almost a micro-app! 😁  Is there some way I can figure out what's making it so bloated?

**Comment by abernix** [comment] 2017-04-04 16:27
You can just come back to this thread.

I've had good success with [`cost-of-modules`](https://www.npmjs.com/package/cost-of-modules) before.  `modules.js` is basically the files deemed necessary from your `node_modules`, so make sure you aren't accidentally loading things that shouldn't be loaded or that should be in `devDependencies` (`faker` is a common one that ends up in the wrong place).  Also, you can always browse the `modules.js` file directly (and find a link to it in your browser's `view-source`) while you're in development.

**Comment by ffxsam** [comment] 2017-04-04 16:38
```
┌────────────────────────────────┬──────────────┬────────┐
│ name                           │ children     │ size   │
├────────────────────────────────┼──────────────┼────────┤
│ aws-sdk                        │ 17           │ 20.73M │
├────────────────────────────────┼──────────────┼────────┤
│ material-ui                    │ 28           │ 11.69M │
├────────────────────────────────┼──────────────┼────────┤
│ bcrypt                         │ 138          │ 8.03M  │
├────────────────────────────────┼──────────────┼────────┤
│ meteor-node-stubs              │ 112          │ 6.82M  │
├────────────────────────────────┼──────────────┼────────┤
│ react                          │ 17           │ 4.99M  │
├────────────────────────────────┼──────────────┼────────┤
│ react-dom                      │ 3            │ 3.60M  │
├────────────────────────────────┼──────────────┼────────┤
│ moment                         │ 0            │ 2.20M  │
├────────────────────────────────┼──────────────┼────────┤
│ formous                        │ 6            │ 1.84M  │
├────────────────────────────────┼──────────────┼────────┤
│ react-addons-pure-render-mixin │ 2            │ 1.57M  │
├────────────────────────────────┼──────────────┼────────┤
│ react-tap-event-plugin         │ 1            │ 1.57M  │
├────────────────────────────────┼──────────────┼────────┤
│ lodash                         │ 0            │ 1.33M  │
├────────────────────────────────┼──────────────┼────────┤
│ radium                         │ 16           │ 0.92M  │
├────────────────────────────────┼──────────────┼────────┤
│ immutable                      │ 0            │ 0.42M  │
├────────────────────────────────┼──────────────┼────────┤
│ react-dropzone                 │ 1            │ 0.26M  │
├────────────────────────────────┼──────────────┼────────┤
│ validator                      │ 0            │ 0.17M  │
├────────────────────────────────┼──────────────┼────────┤
│ keycode                        │ 0            │ 0.11M  │
├────────────────────────────────┼──────────────┼────────┤
│ react-mounter                  │ 2            │ 0.05M  │
├────────────────────────────────┼──────────────┼────────┤
│ copy-to-clipboard              │ 1            │ 0.02M  │
├────────────────────────────────┼──────────────┼────────┤
│ filesize                       │ 0            │ 0.01M  │
├────────────────────────────────┼──────────────┼────────┤
│ 19 modules                     │ 201 children │ 45.02M │
└────────────────────────────────┴──────────────┴────────┘
```

**Comment by ffxsam** [comment] 2017-04-04 16:39
Ok, so I'm wondering if I'm importing from `aws-sdk` and `material-ui` in a way that's including the entire library. Yikes!

**Comment by ffxsam** [comment] 2017-04-04 19:56
PS: Wouldn't `faker` go in `dependencies`, since one might typically use it in in `fixtures.js`?

```js
Meteor.startup(function() {
  if (Things.find().count() === 0) {
    // insert fake data using faker
  }
});
```

Or perhaps that whole block should/would be wrapped in `if (process.env.NODE_ENV === 'development')`...
