### ISSUE TITLE
Spiderable: Hostname not preserved when performing server-side rendering

### ISSUE THREAD

**Issue by petermikitsh** [meteor/meteor#5555] opened 2015-10-28 05:46 UTC
In multi-tenant Meteor application applications that require SSR, hostnames are masked when rendering server-side. 

Where a request might come from hostname `tenant.127.0.0.1.xip.io:3000`, in publication functions, the `this.connection` object will point to the meteor app's internal hostname (see object below). This is expected behavior, as the phantomjs process will directly render the webpage without doing a round-trip through the internet.

```javascript
{ id: 'nEe977xFuu4QGFdRa',
  close: [Function],
  onClose: [Function],
  clientAddress: '127.0.0.1',
  httpHeaders: 
   { referer: 'http://localhost:3000/mypage',
     'x-forwarded-for': '127.0.0.1',
     host: 'localhost:3000',
     'user-agent': 'Mozilla/5.0 (Macintosh; PPC Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.7 Safari/534.34',
     'accept-language': 'en-US,*' },
  headers: 
   { 'user-agent': 'Mozilla/5.0 (Macintosh; PPC Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.7 Safari/534.34',
     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
     connection: 'Keep-Alive',
     'accept-encoding': 'gzip',
     'accept-language': 'en-US,*',
     host: 'localhost:3000',
     'x-forwarded-for': '127.0.0.1',
     'x-forwarded-port': '3000',
     'x-forwarded-proto': 'http',
     'x-ip-chain': '127.0.0.1,127.0.0.1' },
  headerDep: { _dependentsById: {} } }
```

This practical side effect of this behavior is that publication functions can no longer identify which hostname a request came from in server rendering contexts. In a multi-tenant application, it is a common pattern to use a publication function to obtain the associated tenant document from a collection. In more concrete terms: for SaaS applications, for example, the tenant document could have css colors and content specific for a given tenant. It is essential to know the originating hostname in server-side contexts for proper page rendering.

The solution is to expose the original hostname (perhaps as a query parameter appended to the url fed to phantomjs) or retain it in the `connection` object.

**Comment by petermikitsh** [comment] 2015-10-29 05:15
A potential fix is on my fork of `spiderable`: https://github.com/WyvrnCo/spiderable/commit/96b890b14dded92b6773e325abd2a7ab1eb50e93#diff-287eee98cb072b73178dff67d5ca5755L62

**Comment by stubailo** [comment] 2015-11-03 22:23
I think this is a duplicate of: https://github.com/meteor/meteor/issues/4362

Would you mind re-posting your fix there?

**Closed by stubailo** 2015-11-03 22:23 UTC
Labels: Project:Webapp:Spiderable
