### ISSUE TITLE
Stripe is no longer working as expected since 1.3

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#6643] opened 2016-03-30 13:08 UTC
I try to include a script in `head`, as per [docs](https://stripe.com/docs/custom-form#step-1-collecting-credit-card-information).

However, while this used to work, it no longer works according to plan.

To reproduce:
Create simple project
Include `<script type="text/javascript" src="https://js.stripe.com/v2/"></script>` in head
In another script, try to set the stripe publishable key.

**Comment by ModrichBadr** [comment] 2016-03-31 10:34
Have you tried using https://github.com/tyler-johnson/stripe-meteor ?

**Comment by abernix** [comment] 2016-04-01 16:54
See #6672 for similar problem (and explanation as to why it happened) and suggested solution.  I might suggest a client JS that sets Stripe key and then calls `$.getScript`.

**Comment by nguyenhose** [comment] 2016-05-06 10:07
we can set publish key in client, but for security we can not set secret key in there.

**Comment by abernix** [comment] 2016-11-16 10:01
Closing in favor of #6672 (which is the same and has a resolution) and because this appears to be relatively idle.  Happy to reopen if that doesn't fix it, but please provide a suitable reproduction!

**Closed by abernix** 2016-11-16 10:01 UTC
