### ISSUE TITLE
[Crosswalk] Initial hot-code push

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#5297] opened 2015-09-27 02:06 UTC
When using the Crosswalk plugin for Cordova, it seems that Meteor runs an initial hot-code push after first start of the app. This issue doesn't happen when I use Cordova without Crosswalk. 

Think it's bad for the user experience when the app tries to reload all the data on first startup.

**Comment by mvaivre** [comment] 2015-10-03 14:07
+1 Most users think the app is broken since the hot push causes a blank screen at startup...

**Comment by martijnwalraven** [comment] 2015-10-04 13:27
I agree, if the code hasn't been changed there should be no need for a hot code push. Not sure what is going on with Crosswalk specifically, but this is something I'm looking into as part of the hot code push rewrite for Cordova.

@mvaivre Could you elaborate on why this causes a blank screen at startup?

**Comment by dnish** [comment] 2015-10-13 12:29
The combination <code>mdg:reload-on-resume</code> & <code>cordova-camera</code> can cause a unusual behavior in this case. If the user opens the camera window, the activity gets paused until he selected / shoot a picture. After that, reload-on-resume fires and the whole page refreshes.

**Comment by Wenape** [comment] 2015-10-23 14:33
Depending on the device, a hot code push will add a couple of extra seconds to the startup of your app. This is caused by all the downloads of the new update. If you are using `mdg:reload-on-resume`, you will save the user from a reload, but not from the extra secs that the all file downloads cause.

I'm using an edited version of the autoupdate packge that allows file downloads from an update just when the app is in the background. When the user resumes the app, the files should be already downloaded and he will get an instant reload. If the files are not completely downloaded by the time the user resumes the app, a native loader (via plugin) is displayed until after everything is downloaded and the app is reloaded.

The thing I don't like about this approach though is it that a user could be using the app without ever putting it in the background, but just closing it. The actual approach at least ensures that the user will get the new version of the app when it is opened a on second opportunity. That's why I'm pushing important updates to the play / app stores and small / less important updates are hot code pushed.

I think the ideal situation would be to download updates on startup, but using a background thread or a slower download of files to prevent a disturbance on the UX side of the app. If this is not possible, maybe control downloads via a session variable, so they could be executed later at a time when the app is not doing too much work (which is like what I'm doing now). This is just about downloading files thought. For the reload, probably a good approach is to continue doing it on reload or just ask the user to accept the update (and reload).

**Comment by martijnwalraven** [comment] 2015-10-23 14:50
Downloading updates in the background is what's being made possible by https://github.com/meteor/meteor/issues/4722. I've only implemented this for iOS so far, but what I'm doing there is using the `NSURLSession` support for background transfers, so downloads get started while the app is in the foreground but keep going even if the app is killed.

Additionally, there should probably be some amount of developer control over when these updates get applied, what the UX should be like, etc. There is some discussion of this in https://github.com/meteor/meteor/issues/4876.

**Comment by martijnwalraven** [comment] 2016-02-19 10:01
This should be fixed in Meteor 1.3! A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.

**Closed by martijnwalraven** 2016-02-19 10:01 UTC
Labels: in progress, Project:Mobile
