### ISSUE TITLE
Allow fuzzy versions (~0.1.0 or ^0.1.0) in Npm.depends

### ISSUE THREAD

**Issue by zardak** [meteor/meteor#4563] opened 2015-06-15 02:54 UTC
Currently when specifying a fuzzy version constraint
```js
Npm.depends({
  packagename: '^0.1.0'
});
```
meteor ceases to work.

Allowing fuzzy versions would ease the maintaining of packages, as I've seen many commits solely bumping a dependency version.

**Comment by anubhav94** [comment] 2015-06-16 21:12
Duplicate of #4355. Thanks!

**Closed by anubhav94** 2015-06-16 21:12 UTC
