### ISSUE TITLE
Custom ROOT_URL and HMR do not work

### ISSUE THREAD

**Issue by phibya** [meteor/meteor#11318] opened 2021-02-13 23:08 UTC
I tried to set the ROOT_URL to `http://localhost:3000/app` and the HMR module stop working.

Logs:
```
WebSocket connection to 'ws://localhost:3000/app/__meteor__hmr__/websocket' failed: Connection closed before receiving a handshake response
```

It worked when I tried to connect to `ws://localhost:3000/__meteor__hmr__/websocket`
```
socket = new WebSocket("ws://localhost:3000/__meteor__hmr__/websocket"); 

socket.addEventListener('open', function () {
    console.log("SOCKET connected")
});
```

I believe that the server is still listening to `/__meteor__hmr__/websocket` rather than `/app/__meteor__hmr__/websocket`

**Comment by filipenevola** [comment] 2021-02-25 20:16
@zodern any thoughts here?

**Comment by zodern** [comment] 2021-05-17 19:13
The fix will be in 2.3.

**Closed by zodern** 2021-05-17 19:13 UTC
Labels: Impact:few, Project:HMR, confirmed, in-development

**Comment by Oyshoboy** [comment] 2021-07-31 03:34
Hey, I'm having the same issue, on v2.3.2.  Is there any hotfix, that I can manually apply?

**Comment by filipenevola** [comment] 2021-08-20 01:05
Hi @Oyshoboy if this is still affecting you please open a new issue with a reproduction.

Read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)

Thanks.

**Comment by Oyshoboy** [comment] 2021-09-26 09:33
@filipenevola thank you! Already resolved issue, by providing correct ROOT_URL on dev, since I'm using a Nginx and remote server for meteor development.

**Comment by CaptainChainsaw** [comment] 2022-07-25 13:01
Hi, looks like I'm having this issue.  I'm using Win 11 WSL and Ubuntu and just getting started with the simple todo list app.  Its quite possible I've done something wrong if so anyone got any ideas how to solve this?  App always looks uses `192.168.84.128` when it should be using `192.168.1.105`.  At least that's my understanding anyway.

`  "scripts": {
    "start": "ROOT_URL=http://192.168.1.105:3000 meteor run --mobile-server 192.168.1.105:3000 android-device --port=3000",
    "test": "meteor test --once --driver-package meteortesting:mocha",
    "test-app": "TEST_WATCH=1 meteor test --full-app --driver-package meteortesting:mocha",
    "visualize": "meteor --production --extra-packages bundle-visualizer"
  },`



![image](https://user-images.githubusercontent.com/3913259/180781689-c10f697d-761a-4faf-9768-cb0e3aa6f7df.png)

192.168.1.105:3000 is accessible via mobile browser.

![image](https://user-images.githubusercontent.com/3913259/180782194-ba6af69b-df86-4b9f-888b-7a83af8f0932.png)

Windows 11 ipconfig:

![image](https://user-images.githubusercontent.com/3913259/180782442-33ebf233-aacc-47fa-b267-fb18a1a2996a.png)


ifconfig on Ubuntu WSL:

![image](https://user-images.githubusercontent.com/3913259/180782792-075951eb-3e19-4179-8b63-24a59b0844a6.png)

**Comment by denihs** [comment] 2022-07-25 17:48
Hi @CaptainChainsaw,

How are you trying to access your local app? Are you accessing `localhost` or the IP?

Could you try to access the IP directly? 

Also, make sure the IP you provide to ROOT_URL is the IP from your computer.

**Comment by CaptainChainsaw** [comment] 2022-07-25 17:57
Hi @denihs 

I'm able to access via the web on my laptop with these:
`http://192.168.1.105:3000`
`http://127.0.0.1:3000`
`http://192.168.84.128:3000`
`http://localhost:3000`

On my mobile browser I can access it via:
`http://192.168.1.105:3000`

I'm expecting the websocket to use `192.168.1.105` not `192.168.84.128`

I believe the IP is set correctly in my scripts `ROOT_URL`, see my previous post.

Am I doing something wrong or does this look like a bug?

**Comment by denihs** [comment] 2022-07-25 18:20
It looks like you're providing `--mobile-server` in the wrong way.

Could you try to replace it with `--mobile-server=http://192.168.1.105:3000`?

Let me know if it works.

**Comment by CaptainChainsaw** [comment] 2022-07-25 19:40
Tried updating that and it didn't fix it :-(

`ROOT_URL=http://192.168.1.105:3000 meteor run --mobile-server=http://192.168.1.105:3000 android-device --port=3000`


![image](https://user-images.githubusercontent.com/3913259/180860661-1538a5dd-efc8-4c54-a2fa-302d04986d7f.png)

**Comment by denihs** [comment] 2022-07-25 19:58
The IP `192.168.1.105` is from which device?

I think the problem is that you're accessing `localhost:12248` instead of the IP. 

What's the IP of the device you sent the image above? Is it `192.168.84.128`? 

Also, the port from ROOT_URL and mobile-server should be different. Try this: `ROOT_URL=http://192.168.1.105:3000 meteor run --port=5000 --mobile-server=http://192.168.1.105:5000 android-device`

**Comment by CaptainChainsaw** [comment] 2022-07-25 22:26
The IPs are on my original comment screenshots if you want further information on that.  `192.168.1.105` is my wireless lan adaptor WIFI.

I changed the ports to `5000` as per your suggestion and opened the port in windows.  Screenshots below.

![image](https://user-images.githubusercontent.com/3913259/180883836-482defef-13ce-491f-a4b0-86f1ce03602f.png)

![image](https://user-images.githubusercontent.com/3913259/180884138-d3ec83e4-db81-47f5-a708-2e7970b05381.png)
