### ISSUE TITLE
Mongo driver loses connection with error "MongoError: server instance pool was destroyed"

### ISSUE THREAD

**Issue by THPubs** [meteor/meteor#7822] opened 2016-09-26 23:35 UTC
I deployed a meteor app to a aws server using `mup` which used `docker` to deploy the app. I also used Mlab sandboxed db. The issue is, the app crash without warning after some time. Crashing means the app still work but data won't load from the database. I have two versions of the app (staging and production) running in two different servers. But both have this issue. In the docker logs I see this error repeated a lot of times :

    Exception in setInterval callback: MongoError: server instance pool was destroyed
        at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:446:16)
        at MongoConnection.<anonymous> (packages/meteor/helpers.js:119:1)
        at MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:771:49)
        at [object Object].update (packages/mongo/collection.js:589:29)
        at AccountsServer.Ap._expireTokens (packages/accounts-base/accounts_server.js:1100:14)
        at packages/accounts-base/accounts_server.js:1173:14
        at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
        at packages/meteor/timers.js:6:1
        at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
        - - - - -
        at Function.MongoError.create (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:29:11)
        at basicWriteValidations (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:433:51)
        at [object Object].Server.update (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:543:16)
        at [object Object].Server.update (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/server.js:386:17)
        at updateDocuments (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1037:19)
        at [object Object].Collection.update (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1075:44)
        at MongoConnection._update (packages/mongo/mongo_driver.js:560:18)
        at MongoConnection.<anonymous> (packages/meteor/helpers.js:118:1)
        at MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:771:49)
        at [object Object].update (packages/mongo/collection.js:589:29)

Any idea what's happening?

In the client browser console, I see this error `WebSocket connection to 'wss://oursite.com/sockjs/373/2lrpal10/websocket' failed: WebSocket is closed before the connection is established.`

**Comment by tmeasday** [comment] 2016-09-27 01:15
The "server instance pool was destroyed" sounds like the mongo driver has closed your connection for some reason. Have you looked at the mongo end to see if there's anything weird happening?

Perhaps you can get some logging for the mongo connection (at either end, I'm not sure of the best way) to figure out if the connection is being closed and why.

Does the client error only happen after the server loses it's db connection?

**Comment by tmeasday** [comment] 2016-09-27 01:16
Also you might try the latest version of the `npm-mongo` package.

**Comment by THPubs** [comment] 2016-09-27 09:22
@tmeasday Yeap. The client error come only when the site loose the connection with the db. :cry: I will try updating `npm-mongo`. Currently it's at `npm-mongo@1.5.48`

**Comment by abernix** [comment] 2016-09-29 07:59
I completely agree with @tmeasday that this appears to be a disconnection issue with the DB connection.   This error is typical when an `insert`/`update`/`remove` is executed (under the belief that the connection is still up), but the connection is determined to be down before the result is received.

One common stack-trace theme so far (here and in the [forum post about this](https://forums.meteor.com/t/meteor-app-crash-randomly-throwing-a-mongoerror-server-instance-pool-was-destroyed-error/29610/)) has been:
>     at AccountsServer.Ap._expireTokens (packages/accounts-base/accounts_server.js:1100:14)

The `_expireTokens` method here is not likely to blame itself, but since that is a periodic timer event which executes a query, it makes sense: When the recurring timer fires to clear those login tokens, the connection has silently failed since the last query and therefore it fails at this point in the code.

I'm curious if anyone is seeing this problem in development (i.e. when running the `meteor` tool), or if anyone is getting this error with a Mongo server deployment on the same machine as their app.

**Comment by abernix** [comment] 2016-09-30 07:20
For anyone experiencing this problem, a new version of the `npm-mongo` package (now 1.5.50) has been published.  This Meteor package includes the latest version of the Mongo Node driver, 2.2.10 ([View their bug-fixes here](https://github.com/mongodb/node-mongodb-native/blob/2.2/HISTORY.md#2210-2016-09-15)).

I can't say with any certainty that this will solve the problem, but its worth a try to see if it was related to something in the underlying driver.  You can update to this new package by running `meteor update npm-mongo` in your Meteor project:

```
user@host:~/project_dir $ meteor update npm-mongo

Changes to your project's package version selections from updating package versions:

npm-mongo  upgraded from 1.5.49 to 1.5.50
```

You should see the change to 1.5.50.  Please report back if this solves the problem for you!

**Comment by tcastelli** [comment] 2016-10-04 00:48
I am facing the same problem, will try to update and see if the problem is solved

**Comment by THPubs** [comment] 2016-10-04 01:50
I updated npm-mongo and launched. So far so good.. Will test more and let you know :smile:

**Comment by tcastelli** [comment] 2016-10-06 20:45
After some several testin, now I'm getting this error from time to time, quite hard to replicate

```
Unexpected mongo exit code 14. Restarting.
I20161006-21:13:57.034(2)? Exception while polling query {"collectionName":"users","selector":{"_id":"8d23hd23ygheyg2e3","disabled":{"$exists":false}},"options":{"transform":null,"limit":1,"fields":{"userData":1,"profile":1,"createdAt":1,"status.lastLogin.date":1,"image":1}}}: Error: read ECONNRESET
I20161006-21:13:57.040(2)?     at Object.Future.wait (C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:449:15)
I20161006-21:13:57.040(2)?     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1021:47)
I20161006-21:13:57.041(2)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1055:22)
I20161006-21:13:57.042(2)?     at SynchronousCursor.getRawObjects (packages/mongo/mongo_driver.js:1104:12)
I20161006-21:13:57.042(2)?     at PollingObserveDriver._pollMongo (packages/mongo/polling_observe_driver.js:152:48)
I20161006-21:13:57.067(2)?     at PollingObserveDriver.proto._pollMongo (packages/meteorhacks_kadira/lib/hijack/wrap_observers.js:100:1)
I20161006-21:13:57.070(2)?     at Object.task (packages/mongo/polling_observe_driver.js:90:12)
I20161006-21:13:57.071(2)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20161006-21:13:57.075(2)?     at packages/meteor/fiber_helpers.js:125:1
I20161006-21:13:57.075(2)?     - - - - -
I20161006-21:13:57.076(2)?     at exports._errnoException (util.js:907:11)
I20161006-21:13:57.082(2)?     at TCP.onread (net.js:557:26)
```

**Comment by tmeasday** [comment] 2016-10-06 23:13
Exit code 14 sounds like something is going wrong at mongo's end.

**Comment by tmeasday** [comment] 2016-10-07 02:29
Investigating further, it seems the behavior of the Mongo driver in 1.3 was to reconnect indefinitely, whereas in 1.4 if it loses the connection for 30s, it will never reconnect.

This looks like an easy fix with a tweak to the mongo settings.

**Comment by tmeasday** [comment] 2016-10-07 03:03
Please try `mongo@1.1.12-2-rc.0` :https://github.com/meteor/meteor/pull/7880#issuecomment-252142089

**Comment by tcastelli** [comment] 2016-10-07 03:12
Great! will try and tes again

**Comment by benjamn** [comment] 2016-10-07 21:57
I am unfortunately still seeing this problem, even when using the versions of `mongo` and `npm-mongo` enforced by #7880.

**Comment by Metamist** [comment] 2016-10-08 16:57
I am having the same problem, except for me it's collection.remove from _cleanStaleResults in oauth/pending_credentials.js.
I'm using Windows 8.1 and developing my app locally. As soon as the error occurs I lose all access to the database until I restart. 
Meteor version 1.4.1.2, mongo version 1.1.12_3, npm-mongo version 1.5.50.
Any workarounds to fix this? It's rather difficult for me to continue development of my app while this problem occurs.
```
Exception in setInterval callback: MongoError: server instance pool was destroyed
     at Object.Future.wait (C:\Users\Metamist\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:446:16)
     at MongoConnection.<anonymous> (meteor://�app/packages/meteor/helpers.js:119:1)
     at MongoConnection.(anonymous function) [as remove] (meteor://�app/packages/mongo/mongo_driver.js:771:49)
     at [object Object].remove (meteor://�app/packages/mongo/collection.js:624:29)
     at _cleanStaleResults (meteor://�app/packages/oauth/pending_credentials.js:30:1)
     at [object Object]._.extend.withValue (meteor://�app/packages/meteor/dynamics_nodejs.js:56:1)
     at meteor://�app/packages/meteor/timers.js:6:1
     at runWithEnvironment (meteor://�app/packages/meteor/dynamics_nodejs.js:110:1)
     - - - - -
     at Function.MongoError.create (C:\Users\Metamist\AppData\Local\.meteor\packages\npm-mongo\1.5.50\npm\node_modules\mongodb-core\lib\error.js:29:11)
     at basicWriteValidations (C:\Users\Metamist\AppData\Local\.meteor\packages\npm-mongo\1.5.50\npm\node_modules\mongodb-core\lib\topologies\server.js:434:51)
     at [object Object].Server.remove (C:\Users\Metamist\AppData\Local\.meteor\packages\npm-mongo\1.5.50\npm\node_modules\mongodb-core\lib\topologies\server.js:578:16)
     at [object Object].Server.remove (C:\Users\Metamist\AppData\Local\.meteor\packages\npm-mongo\1.5.50\npm\node_modules\mongodb\lib\server.js:393:17)
     at removeDocuments (C:\Users\Metamist\AppData\Local\.meteor\packages\npm-mongo\1.5.50\npm\node_modules\mongodb\lib\collection.js:1232:19)
     at [object Object].Collection.remove (C:\Users\Metamist\AppData\Local\.meteor\packages\npm-mongo\1.5.50\npm\node_modules\mongodb\lib\collection.js:1272:44)
     at MongoConnection._remove (meteor://�app/packages/mongo/mongo_driver.js:417:16)
     at MongoConnection.<anonymous> (meteor://�app/packages/meteor/helpers.js:118:1)
     at MongoConnection.(anonymous function) [as remove] (meteor://�app/packages/mongo/mongo_driver.js:771:49)
     at [object Object].remove (meteor://�app/packages/mongo/collection.js:624:29)
     at _cleanStaleResults (meteor://�app/packages/oauth/pending_credentials.js:30:1)
     at [object Object]._.extend.withValue (meteor://�app/packages/meteor/dynamics_nodejs.js:56:1)
     at meteor://�app/packages/meteor/timers.js:6:1
     at runWithEnvironment (meteor://�app/packages/meteor/dynamics_nodejs.js:110:1)

**Comment by jamielob** [comment] 2016-10-08 19:14
Updating to `npm-mongo@2.2.10_1` and then updating all dependencies fixed this for me:

```
meteor update npm-mongo // Check that it takes you to 2.2.x
meteor update --all-packages
```

**Comment by Metamist** [comment] 2016-10-09 11:21
@jamielob, Thank you, I had to do `meteor add npm-mongo@2.2.10_1` in order to get it updated, and that seems to have fixed the issue!

**Comment by tmeasday** [comment] 2016-10-09 23:14
@benjamn under what circumstances are you seeing the issue? Locally or with a separate mongo instance?

**Comment by benjamn** [comment] 2016-10-09 23:21
@tmeasday I was seeing it locally, as (I think) was @glasser. The good news is that I have not seen it since merging https://github.com/meteor/meteor/pull/7898, which was released as `mongo@1.1.12_5` (which uses `npm-mongo@2.2.10_1`, which may explain why it's working for @Metamist now). Unless anyone reports seeing it again, I think we can close this issue now.

**Comment by tmeasday** [comment] 2016-10-09 23:31
Ok, thanks @benjamn. `retries = Infinity` makes more sense than `= 0` (Although `= 0` definitely worked in some cases, go figure). I guess we can reopen if we see this again.

**Closed by tmeasday** 2016-10-09 23:31 UTC
Labels: bug, Impact:some, Project:Mongo Driver, Severity:production

**Comment by abhijeetabanave** [comment] 2019-10-24 09:46
> @jamielob, Thank you, I had to do `meteor add npm-mongo@2.2.10_1` in order to get it updated, and that seems to have fixed the issue!

**Comment by brunoboto96** [comment] 2019-11-18 10:22
[https://stackoverflow.com/questions/46523321/mongoerror-connect-econnrefused-127-0-0-127017](url)
