### ISSUE TITLE
meteor 1.5-rc.3 - get "Uncaught Error: Cannot find module 'core-js/modules/_core'" on the client

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#8699] opened 2017-05-16 09:09 UTC
I updated my app to 1.5-rc3 and got several problems. One says:

"Uncaught Error: Cannot find module 'core-js/modules/_core'"

on the client. Do i need to install additional npm packages? I already added "babel-runtime": "^6.20.0", with no luck

my babelrc:

```
{
  "presets": ["es2015", "stage-2", "react"],
  "plugins": [
    ["lodash", { "id": ["lodash", "recompose"] }],
    "react-require",
    "babel-root-slash-import",
    "array-includes",
    "transform-class-properties",
    "transform-object-rest-spread",
    "add-react-displayname",
    "styled-components-named"
  ]
}
```

**Comment by benjamn** [comment] 2017-05-16 16:01
Thanks for reporting this!

I would usually demand a reproduction, but since we're so close to the 1.5 release I tried to reproduce the problem with the `.babelrc` plugins you provided. Unfortunately I think I need to know more about the file/code where the exception is being thrown, if you can track that down?

**Comment by macrozone** [comment] 2017-05-16 16:16
Hi @benjamn , thx for trying it out!

I know that a reproduction is always better, but I thought that maybe someone immediatly knows, what might be wrong. I will try to add more information if I can.

**Comment by zeroasterisk** [comment] 2017-05-17 19:12
I am also getting this error:

`meteor --raw-logs --settings settings-devlocal.json --production --port 5000`

```
fe077b8….js?meteor_js_resource=true:23 Uncaught Error: Cannot find module 'core-js/modules/_core'
    at c (fe077b8….js?meteor_js_resource=true:23)
    at e (fe077b8….js?meteor_js_resource=true:23)
    at runtime.js (fe077b8….js?meteor_js_resource=true:147)
    at l (fe077b8….js?meteor_js_resource=true:23)
    at e (fe077b8….js?meteor_js_resource=true:23)
    at fe077b8….js?meteor_js_resource=true:147
    at fe077b8….js?meteor_js_resource=true:147
```

**Comment by benjamn** [comment] 2017-05-17 19:15
@zeroasterisk What version do you see in `your-app/node_modules/core-js/package.json`, if that file exists?

**Comment by zeroasterisk** [comment] 2017-05-17 19:18
sorry - i just trashed `node_modules` and just re-installed... updated the comment above w/ details while waiting...  

```
$ cat node_modules/core-js/package.json | ag version
  "_nodeVersion": "6.2.2",
  "_npmVersion": "3.9.5",
  "version": "1.2.7"
```

**Comment by zeroasterisk** [comment] 2017-05-17 19:28
even after rebuilding all npm packages, got the same error:

```
Uncaught Error: Cannot find module 'core-js/modules/_core'
    at c (c7d31f5….js?meteor_js_resource=true:23)
    at e (c7d31f5….js?meteor_js_resource=true:23)
    at runtime.js (c7d31f5….js?meteor_js_resource=true:146)
    at l (c7d31f5….js?meteor_js_resource=true:23)
    at e (c7d31f5….js?meteor_js_resource=true:23)
    at c7d31f5….js?meteor_js_resource=true:146
    at c7d31f5….js?meteor_js_resource=true:146
```

sadly this is a giant, private, project... want me to try anything, or provide you with more info?

**Comment by benjamn** [comment] 2017-05-17 19:43
Sure, I've got more questions! Does the file `your-app/node_modules/core-js/modules/_core.js` exist? If not, what does `your-app/node_modules/core-js/modules/index.js` use for `module.exports`?

**Comment by zeroasterisk** [comment] 2017-05-17 19:51
here's the error from a non `--production` build...

```
Uncaught Error: Cannot find module 'core-js/modules/_core'
    at makeMissingError (modules-runtime.js?hash=8587d18…:231)
    at require (modules-runtime.js?hash=8587d18…:241)
    at runtime.js (ecmascript-runtime-client.js?hash=731d642…:46)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at ecmascript-runtime-client.js?hash=731d642…:168
    at ecmascript-runtime-client.js?hash=731d642…:181
```

here's some craziness:

```
$ ls node_modules/core-js/modules/ | ag core
$.core.js
core.delay.js
core.dict.js
core.function.part.js
core.get-iterator-method.js
core.get-iterator.js
core.is-iterable.js
core.log.js
core.number.iterator.js
core.object.classof.js
core.object.define.js
core.object.is-object.js
core.object.make.js
core.string.escape-html.js
core.string.unescape-html.js

$ ls node_modules/core-js/modules/ | ag index
$.to-index.js
es6.array.find-index.js

$ cat node_modules/core-js/package.json | ag main
  "main": "index.js",
  "maintainers": [

$ ls node_modules/core-js/
library  modules  web  LICENSE  package.json  shim.js
```

if you want to IM me - we could do realtime, let me know @zeroasterisk on all of the things (hangouts?)

**Comment by benjamn** [comment] 2017-05-17 20:01
Ah, I think it's just an older version of `core-js` that had a different file layout, so [this line](https://github.com/meteor/meteor/blob/647e3a2fc53aa75b23c1afdefcdaa61eff3fc1f2/packages/ecmascript-runtime-client/runtime.js#L15) won't work.

What version do you see in `your-app/node_modules/babel-runtime/package.json`? I ask because `babel-runtime` is usually responsible for installing `your-app/node_modules/core-js`.

**Comment by zeroasterisk** [comment] 2017-05-17 20:06
```
$ cat node_modules/babel-runtime/package.json | ag version
  "_nodeVersion": "6.9.1",
  "_npmVersion": "3.10.8",
  "version": "6.23.0"
$ cat node_modules/babel-runtime/package.json | ag core
    "/babel-core",
    "/mantra-core",
    "/mantra-core/react-komposer",
    "core-js": "^2.4.0",
```

**Comment by zeroasterisk** [comment] 2017-05-17 21:01
want me to try with your latest version w/ changes?

and after that - want to tell me how to actually update to the correct latest version?

**Comment by macrozone** [comment] 2017-05-17 21:02
Ok i think you guys figured it out! Will try out the next rc and give feedback!

**Comment by benjamn** [comment] 2017-05-17 21:39
Yes, please try after `meteor update --release 1.5-rc.5`!

**Comment by zeroasterisk** [comment] 2017-05-17 22:21
new error
```
modules-runtime.js?hash=8587d18…:231 Uncaught Error: Cannot find module 'core-js/modules/es6.function.bind'
    at makeMissingError (modules-runtime.js?hash=8587d18…:231)
    at require (modules-runtime.js?hash=8587d18…:241)
    at runtime.js (ecmascript-runtime-client.js?hash=f5e024e…:112)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at ecmascript-runtime-client.js?hash=f5e024e…:176
    at ecmascript-runtime-client.js?hash=f5e024e…:189
```

**Comment by benjamn** [comment] 2017-05-17 22:24
Can you just try upgrading `core-js` to 2.4.1? That is, `meteor npm install --save core-js@2.4.1`.

**Comment by zeroasterisk** [comment] 2017-05-17 22:48
Working ! 👍 :1st_place_medal: 💯 🎉 

I also had to do the Buffer polyfill because some package I was using on the clientside needed a buffer --- I'll see if I can refactor that away...  

anyway - now loading on `1.5-rc.5` AFTER `meteor npm install --save core-js@2.4.1`

thanks for the help!

**Comment by macrozone** [comment] 2017-05-18 08:52
it works after adding core-js@2.4.1, but It feels a little bit awkward to add a dependency that is not directly used anywhere in the app :-/

**Comment by benjamn** [comment] 2017-05-18 16:33
Don't worry, I've got a better fix on the way.

**Comment by zeroasterisk** [comment] 2017-05-18 17:16
FYI - something seems off with this package, somehow...

1. I committed the new npm dependency `core-js@2.4.1` to my `package.json`
2. Switched to a new copy of the repo and `meteor npm i` 
3. Built and Deployed - and it failed in the same way
4. On the new copy of the repo, explicitly ran `meteor npm install --save core-js@2.4.1`
5. And then it worked

Here's the output from npm, for the 2nd copy, where the package was supposedly, already in place:

```
$ meteor npm install --save core-js@2.4.1
ElToroPortal@2.0.64 /Users/alan/Code/eltoro/portalV2DEPLOY/webapp
├─┬ babel-runtime@6.23.0
│ └── core-js@2.4.1  deduped
├── core-js@2.4.1
└─┬ meteor-node-stubs@0.2.6
  └─┬ util@0.10.3
    └── inherits@2.0.1
```

**Comment by benjamn** [comment] 2017-05-18 17:25
If you run `meteor update --release 1.5-rc.6` (just published), I'm hoping this will be fixed regardless of which version of `core-js` you're using.

**Closed** 2017-05-19 14:25 UTC
