### ISSUE TITLE
conflict of accounts-password package with npm-bcrypt

### ISSUE THREAD

**Issue by vidukapoor** [meteor/meteor#8233] opened 2017-01-11 05:12 UTC
Node_module_register conflict
![accounts-password](https://cloud.githubusercontent.com/assets/14005853/21836260/b215e346-d7e9-11e6-81a3-180882e9f00b.png)

**Comment by ramezrafla** [comment] 2017-01-13 18:05
@vidukapoor did you add your own npm packages?

**Comment by ramezrafla** [comment] 2017-01-24 01:32
I think we can close this.

**Comment by abernix** [comment] 2017-01-24 05:01
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)

(@ramezrafla, thanks.  Normally, we'd wait a _bit_ longer before closing without a reproduction, but only like 2 days more, :smile:)

**Closed by abernix** 2017-01-24 05:01 UTC

**Comment by vidukapoor** [comment] 2017-01-24 09:18
@abernix  thanks for the reply, the main issue behind this is that the rest of the packages are been outdated, onces i have updated all the rest packages the issue has been resolved :)

**Comment by abernix** [comment] 2017-01-24 18:23
Good to know.  Thanks for the follow-up! :)
