### ISSUE TITLE
[2.7.4-beta.2] Error when deploying to Galaxy

### ISSUE THREAD

**Issue by ixdi** [meteor/meteor#12069] opened 2022-06-28 06:57 UTC
Hi,
When deploying our code to Galaxy with meteor@2.7.4-beta.2 it fails with:
```
2022-06-28 08:46:44+02:00/app/bundle/programs/server/node_modules/fibers/future.js:280
2022-06-28 08:46:44+02:00 throw(ex);
2022-06-28 08:46:44+02:00 ^
2022-06-28 08:46:44+02:00
2022-06-28 08:46:44+02:00TypeError: Cannot read property 'constructor' of undefined
2022-06-28 08:46:44+02:00 at module (packages/mdg:meteor-apm-agent/lib/hijack/meteorx.js:49:3)
2022-06-28 08:46:44+02:00 at fileEvaluate (packages/modules-runtime.js:336:7)
2022-06-28 08:46:44+02:00 at Module.require (packages/modules-runtime.js:238:14)
2022-06-28 08:46:44+02:00 at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
2022-06-28 08:46:44+02:00 at module (packages/mdg:meteor-apm-agent/lib/hijack/wrap_observers.js:1:28)
2022-06-28 08:46:44+02:00 at fileEvaluate (packages/modules-runtime.js:336:7)
2022-06-28 08:46:44+02:00 at Module.require (packages/modules-runtime.js:238:14)
2022-06-28 08:46:44+02:00 at require (packages/modules-runtime.js:258:21)
2022-06-28 08:46:44+02:00 at /app/bundle/programs/server/packages/mdg_meteor-apm-agent.js:4263:1
2022-06-28 08:46:44+02:00 at /app/bundle/programs/server/packages/mdg_meteor-apm-agent.js:4282:3
2022-06-28 08:46:44+02:00 at /app/bundle/programs/server/boot.js:401:38
2022-06-28 08:46:44+02:00 at Array.forEach (<anonymous>)
2022-06-28 08:46:44+02:00 at /app/bundle/programs/server/boot.js:226:21
2022-06-28 08:46:44+02:00 at /app/bundle/programs/server/boot.js:464:7
2022-06-28 08:46:44+02:00 at Function.run (/app/bundle/programs/server/profile.js:280:14)
2022-06-28 08:46:44+02:00 at /app/bundle/programs/server/boot.js:463:13
```

This doesn't happen with meteor@2.7.3

Any ideas? Thanks

**Comment by radekmie** [comment] 2022-06-28 07:18
It's definitely caused by https://github.com/meteor/meteor/pull/12028, as `MongoInternals.defaultRemoteCollectionDriver` used [here](https://github.com/meteor/meteor-apm-agent/blob/83bba187049ca22bf3d98a4d7854300041598fae/lib/hijack/meteorx.js#L48-L49) now returns a promise. I'll look into it soon.

**Comment by denihs** [comment] 2022-07-25 18:47
Hi @radekmie, do you have any updates on this?

**Comment by radekmie** [comment] 2022-07-26 10:23
No, I didn't - will do it now.

**Comment by radekmie** [comment] 2022-07-26 10:25
Wait, isn't it already fixed by https://github.com/meteor/meteor-apm-agent/commit/4d484effa76e525d432b77c0c1f9965dc87dcdac?

**Comment by denihs** [comment] 2022-07-26 13:23
Sorry @radekmie, I completely forgot I did these changes...

@ixdi could you test it? You just need to run `meteor update mdg:meteor-apm-agent` to update the package.

**Comment by ixdi** [comment] 2022-08-16 07:26
Hi, now it works perfectly! Thanks

**Closed** 2022-08-16 07:26 UTC
Labels: in-discussion
