### ISSUE TITLE
server-render sink object's appendToHead accumulates upon each page load

### ISSUE THREAD

**Issue by samhiddenhand** [meteor/meteor#9767] opened 2018-03-23 19:06 UTC
In my server/main.js I have:

```
onPageLoad(sink => {
    sink.appendToHead("<meta itemprop='name' content='test' />\n");
});
```

I'm also using Blaze templates. However, upon each page load (even when switching browsers between loading site), I can see that the appended meta tag is accumulating, so if I visit the site 8 times, there are 8 meta tags in the head. Why is this happening? Is there a way to prevent this from happening?

**Comment by samhiddenhand** [comment] 2018-03-25 00:05
I found a workaround. Add this before you appendToHead to clear out the array (that otherwise keeps getting appended to):

`sink.head = '';`

**Comment by samhiddenhand** [comment] 2018-03-25 00:08
I feel like an official function for resetting the head and body arrays should be added, or at least the documentation should be updated to explain how this works... just my opinion.

**Comment by hwillson** [comment] 2018-03-26 18:38
Can you provide a small runnable reproduction that shows this happening? I just created a new app, added the `server-render` package, then added  your exact code to `server/main.js`, and I'm unable to reproduce this problem.

**Comment by hwillson** [comment] 2018-03-27 19:42
@samhiddenhand I'm going to go ahead and close this since this is working when tested with a new simple Meteor app. If you still think there's a Meteor bug here somewhere, please post back with a reproduction, and we'll take a look. Thanks!

**Closed by hwillson** 2018-03-27 19:42 UTC
Labels: can't-reproduce, needs-reproduction
