### ISSUE TITLE
Why Subscribe to something that is not in the database 

### ISSUE THREAD

**Issue by Saeeed-B** [meteor/meteor#11266] opened 2020-12-11 14:17 UTC
Hi, I have had a problem for a long time, in fact an object that is not in the database is shared.
With a little testing, it might be a problem with the fast rendering package, but I'm not quite sure.
If anyone can help me, thank you.

[https://forums.meteor.com/t/why-subscribe-to-something-that-is-not-in-the-database/54492/2](https://forums.meteor.com/t/why-subscribe-to-something-that-is-not-in-the-database/54492/2)

**Comment by Saeeed-B** [comment] 2020-12-11 20:15
I have given a very clear example in the following link : 
[https://github.com/Saeeed-B/Corrupted-data-in-SSR-and-fast-rendering](https://github.com/Saeeed-B/Corrupted-data-in-SSR-and-fast-rendering)

**Comment by filipenevola** [comment] 2021-01-04 15:28
Hi, I ran your app locally and yes, this issue is happening but I don't have any evidence that this problem is on Meteor or Meteor core packages or in Meteor community packages.

My best guess is that the problem is probably in the changes made in the publication system here https://github.com/abecks/meteor-fast-render/blob/master/lib/server/publish_context.js or in some other package that you are using that is not part of Meteor core.

If you use only the SSR you can see the issue is not happening so the app is working as expected except this extra publication.

You should open this issue in the third party repo or try to fix forking the repo.

As the issue is not a Meteor issue or a core package issue we don't have much to do here in the main repo, I'm closing this issue.

**Closed by filipenevola** 2021-01-04 15:28 UTC
