### ISSUE TITLE
Meteor memory consumption - possible leak

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#4327] opened 2015-05-05 11:04 UTC
I'm running latest Meteor ver on Win7 and I'm running into the issue of evergrowing node.exe memory usage.
After building the app with 'meteor' command in task manager node.exe takes circa 300mb of memory.
And with every restart\refresh it eats additional 30-50mb growing to over 1gb of memory in 15-20 refreshes.
Eventually I run out of memory and have to ctrl-c Meteor.

**Comment by Slava** [comment] 2015-05-05 18:07
I think this is a duplicate of https://github.com/meteor/meteor/issues/3898. @glasser is aware of this afaik.

**Closed by Slava** 2015-05-05 18:07 UTC
