### ISSUE TITLE
`Template.instance()` is `null` in nested helpers.

### ISSUE THREAD

**Issue by xbtsw** [meteor/meteor#4035] opened 2015-03-26 18:54 UTC
***9 Upvotes*** When the helper is a nested dictionary, `Template.instance()` inside the helper will return `null`

To reproduce:
`meteor create app`

change `app.js` and `app.html` as follows:

```js
//app.js


if (Meteor.isClient) {
  // counter starts at 0
  Session.setDefault('counter', 0);

  Template.hello.helpers({
    c: {
      counter: function () {
        //below line will throw exception since Template.instance() is null
        var data = Template.instance().data;
        return Session.get('counter');
      }
    }
  });

  Template.hello.events({
    'click button': function () {
      // increment the counter when button is clicked
      Session.set('counter', Session.get('counter') + 1);
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
  });
}
```

```html
<!-- app.html -->

<head>
  <title>app</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
</body>

<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{c.counter}} times.</p>
</template>
```

If we remove the extra level in helper dictionary:
i.e. change `c.counter` to `counter` then `Template.instance()` will behave normally.

**Comment by dgreensp** [comment] 2015-03-31 21:40
Confirmed bug.

Note that this can't be fixed in `lookup`, since only `c` (in the example) is looked up.

**Comment by LyuGGang** [comment] 2015-04-10 16:39
+1

**Comment by gwendall** [comment] 2015-04-26 14:04
+1

**Comment by bgrayburn** [comment] 2015-07-21 16:01
+1

**Comment by Cerealkillerway** [comment] 2015-08-18 23:46
+1

**Comment by jaltez** [comment] 2015-09-22 21:31
+1

**Comment by mkpazon** [comment] 2016-03-26 02:43
+1, wow 1 year already. Are there plans on fixing this?

**Comment by seeekr** [comment] 2016-03-26 19:08
I've never had the urge to write such helper code ("nested helpers"). Who does that? Does it really solve any real world problems that cannot be solved or cannot be solved without significant additional effort when not using this pattern? (Because if not, that might explain why this issue has not been solved yet.)

**Comment by cylwin** [comment] 2016-04-15 12:02
+1

**Comment by michaeljberry** [comment] 2016-04-26 19:18
+1

**Comment by adamgedney** [comment] 2016-06-22 19:38
+1

**Comment by soitech** [comment] 2016-07-29 16:03
+1

**Comment by mjovkovic** [comment] 2016-08-30 21:02
+1

**Comment by cselvarasu** [comment] 2016-09-09 14:22
+1

**Comment by Sntax** [comment] 2016-09-18 11:52
+1

**Comment by hwillson** [comment] 2016-10-20 16:50
I've moved this over to the Blaze repo as meteor/blaze#140. Since it will be tracked there, this issue can be closed.

**Comment by stubailo** [comment] 2016-10-20 17:03
Good call.

**Closed by stubailo** 2016-10-20 17:03 UTC
Labels: bug, confirmed, Impact:some, Project:Blaze
