### ISSUE TITLE
Cannot run previous meteor release, but it does install?

### ISSUE THREAD

**Issue by jerradpatch** [meteor/meteor#9556] opened 2018-01-20 06:04 UTC
Title: Can run but not install old meteor releases.
OS: Ubuntu 16.04
EB: Run the desired version of meteor with the corresponding needed version of node. I needed on older version of node to be installed was the reason to want to use an older version of meteor
AB: It showed it installed the older version but running "meteor --version" always returned the latest version, and the newest version of node was shown in the /dev-bundels/bin directory.

Reproduction:
$ curl "https://install.meteor.com/?release=1.5.4" | sh
$ meteor --version
Meteor 1.6

here is a little debugging info:
in meteor.sh:
echo "$DEV_BUNDLE/bin/node" \
          ${TOOL_NODE_FLAGS} \
          "$METEOR" "$@"

$ meteor --version
/home/jerrad/.meteor/packages/meteor-tool/.1.5.4.j68t73.ea7zo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node /home/jerrad/.meteor/packages/meteor-tool/.1.5.4.j68t73.ea7zo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/index.js --version
Meteor 1.6

Again, I can see 1.5.4 is install and has the correct version on node embedded.

**Comment by benjamn** [comment] 2018-01-20 15:49
There are a couple ways to run an older version of Meteor:
* Pass the `--release` flag to make the latest version of Meteor "springboard" back to the older version before running the command:
  ```sh
  $ meteor --release 1.5.4.1 --version
  Meteor 1.5.4.1
  ```
* Create an app pinned to the older version. Any `meteor` commands run inside the application directory will automatically springboard to the version specified in `.meteor/release`:
  ```sh
  $ meteor --version
  Meteor 1.6.0.1
  $ meteor create --release 1.5.4 app154
  $ cd app154
  $ meteor --version
  Meteor 1.5.4
  ```
In general, when you're not inside an application directory, and you don't specify a `--release`, `meteor` always runs the most recent installed version.

Since everything appears to be working as intended, I'll close this issue now, but I hope this explanation has been helpful, and of course feel free to reopen if I'm missing something.

**Closed by benjamn** 2018-01-20 15:49 UTC
