### ISSUE TITLE
[1.4.x] Unable to install certain packages (ENOENT)

### ISSUE THREAD

**Issue by Metamist** [meteor/meteor#7944] opened 2016-10-20 18:18 UTC
Currently using Windows 8.1
When installing certain packages, I receive the error

```
λ meteor add vsivsi:job-collection
C:\Users\Metamist\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Metamist\AppData\Local\Temp\mt-148d2fn\os\packages\mrt_later.js'
    at Error (native)
```

I can reproduce this both on my PC and on my laptop (both running Windows 8.1), by creating a new meteor app with `meteor create app`. It only happens on some packages and it completely prevents me from adding these packages. Here's some examples of packages that I am unable to add: `mrt:later`, `chart:chart`, `jparker:crypto-aes`.

If I go to the path that it tries to open, I can see the file, except it has an invalid character in it rather than underscore, which is `C:\Users\Metamist\AppData\Local\Temp\mt-148d2fn\os\packages\mrtlater.js`
Here's a picture to see it more clearly:
![](http://i.imgur.com/C626aLj.jpg)

I've tried all workarounds on every issue that is similar to this and none is working, such as `set METEOR_WAREHOUSE_URLBASE=https://d3fm2vapipm3k9.cloudfront.net`, editing the host file with `54.192.225.217 warehouse.meteor.com` or running `meteor npm rebuild`. I have also tried completely removing .meteor/local, %LOCALAPPDATA%/.meteor and reinstalling meteor.
None of these solutions have worked for me and I can't figure out how to solve it. 

If I create a meteor app with version 1.3.5.1, it seems to work fine without the above error. That means there is nothing wrong with npm. I am also unable to downgrade my app to this version, because it tells me

```
λ meteor update --release 1.3.5.1
Update to release METEOR@1.3.5.1 is impossible:
While selecting package versions:
error: No version of mongo satisfies all constraints: @1.1.12, @=1.1.9_1
[...]
```

[Full downgrade error](https://share.metamist.xyz/HkszjtIJg.txt)

This completely blocks me from developing my app and I would appreciate any help in the matter.

**Comment by abernix** [comment] 2016-12-16 15:33
I'm unable to reproduce the first part of your issue using Windows 8.1 on a new project in both Meteor 1.4.1.1 (which you appeared to have been using) and 1.4.2.3 (the latest).  In order to test this, I've ran the following simple commands on Windows 8.1 Enterprise Build 9600:

```sh
> meteor create 7944
> meteor npm install
> meteor add mrt:later
```

I tried the same thing after with:
```sh
> meteor add chart:chart
> meteor add jparker:crypto-aes
```

Something is quite peculiar with the fact that you're seeing that weird character.  I'm not sure if it came through properly, but if I run: 

```javascript
"".charCodeAt(0)
```

It returns 61498 which translates to [`U+F03A`](https://codepoints.net/U+F03A) which appear to be in a "Private Use Area" of the Unicode spec.  But if my thinking is correct U+003A would be the colon (`:`) and your locale on your computer might be using that range of Unicode characters? (i.e. 003A + F000 = F03A).  So that would be a colon, which could be right, so this could be a situation of you being in a particular locale?  What Region/Language settings do you use in Windows?

Ultimately, this might be the same issue as https://github.com/meteor/meteor/issues/7661#issuecomment-263936772 (better explanation found there) but I was at least able to reproduce that issue.

**Comment by Metamist** [comment] 2016-12-16 16:27
I have windows on English as display language, but keyboard layout in Swedish, so windows might be using Swedish for Unicode. 
I am not sure if the issue is still valid since I haven’t used meteor for a while, and I had this issue about a month ago.

**Comment by abernix** [comment] 2017-01-20 17:15
Since you're not actively using Meteor anymore, I'm going to close this as I wasn't able to reproduce it (on a Finnish keyboard too, nonetheless! :wave:).

If you're able to reproduce this again and assist in debugging, let us know!  Happy to reopen! :smile:

**Closed by abernix** 2017-01-20 17:15 UTC
Labels: can't-reproduce
