### ISSUE TITLE
Unexpected behaviour of `Template.dynamic`

### ISSUE THREAD

**Issue by nomosyn** [meteor/meteor#4909] opened 2015-08-07 23:24 UTC
![screen shot 2015-08-08 at 01 03 49](https://cloud.githubusercontent.com/assets/2693150/9147581/6280c574-3d69-11e5-8bc5-8bb6197b636b.png)
![screen shot 2015-08-08 at 01 04 28](https://cloud.githubusercontent.com/assets/2693150/9147592/77fa6e1e-3d69-11e5-8b12-8acb8495b68b.png)
## Problem

Tested with Meteor@1.1.0.3 & devel: 262e06aec1

This does not hold when using `{{> Template.dynamic template=myTemplate data=myData}}`:

**if in `Template.myTemplate.onCreated` we have `this.data === 1`, 
then in `Template.myTemplate.onDestroyed` we have `this.data === 1`**

Instead we have:
**if in `Template.myTemplate.onCreated` we have `this.data === 1`, 
then in `Template.myTemplate.onDestroyed` we have `this.data === "who knows..."`**
## Recipe
- clone [this demo repo](https://github.com/nomosyn/meteor-templateDynamic-mess-with-data)
- open dev tools
- $ meteor
- => debugger stops in `Template.helloLeft.onCreated` & `Template.helloLeft.onDestroyed` callbacks
- inspect `this.data` in those callbacks

Provided this `Template.body` helper:

``` javascript
'curTpt': function () {

    // Session.get('button') ∈ Boolean
    return Session.get('button') ?
        { 'template': 'helloLeft', 'data': { 'withTemplateDynamic': 'left' } }
    : { 'template': 'helloRight', 'data': { 'withTemplateDynamic': 'right' } };
}
```

This call in `Template.body`

``` handlebars
{{> Template.dynamic curTpt}}
```

Is expected, in order:

```
Template.helloLeft.onCreated(_) ⇒ this.data === { 'withTemplateDynamic': 'left' }
Session.get('button') === true
Session.set('button', false)
Template.helloLeft.onDestroyed(_) ⇒ this.data === { 'withTemplateDynamic': 'left' }
```

What we actually have, in order:

```
Template.helloLeft.onCreated(_) ⇒ this.data === { 'withTemplateDynamic': 'left' }
Session.get('button') === true
Session.set('button', false)
Template.helloLeft.onDestroyed(_) ⇒ this.data === { 'withTemplateDynamic': 'right' }
```
## Investigation

`onDestroyed ⇒ this.data = { 'withTemplateDynamic': 'right' }` should be 
`onDestroyed ⇒ this.data = { 'withTemplateDynamic': 'left' }` 

so, searching how `this.data` is built, in order:
- `Session.get('button') === true`
- {{> Template.dynamic curTpt}}
- [`view.dataVar.set({ 'withTemplateDynamic': 'left' })`](https://github.com/meteor/meteor/blob/2229fdfd25e625109ba49ae4c31e1c81574bf8b8/packages/blaze/builtins.js#L22)
- `Session.set('button', false)`
- [`view.dataVar.set({ 'withTemplateDynamic': 'right' })`](https://github.com/meteor/meteor/blob/2229fdfd25e625109ba49ae4c31e1c81574bf8b8/packages/blaze/builtins.js#L22) // Session reactivity fires the autorun. The wrong `view` is affected: `with` of instance of `helloLeft` instead of `with` of `helloRight`
- [`inst.data = Blaze.getData(view);`](https://github.com/meteor/meteor/blob/devel/packages/blaze/template.js#L165) // Blaze.getData(view) should have returned `{ 'withTemplateDynamic': 'left' }`
- [`fireCallbacks(destroyedCallbacks, inst)`](https://github.com/meteor/meteor/blob/devel/packages/blaze/template.js#L192)
- [`Template.helloLeft.onDestroyed.call(inst)`](https://github.com/meteor/meteor/blob/devel/packages/blaze/template.js#L116)
- `Template.helloLeft.onDestroyed ⇒ this.data = { 'withTemplateDynamic': 'right' }`
- ???
- [`inst.data = Blaze.getData(view);`](https://github.com/meteor/meteor/blob/devel/packages/blaze/template.js#L165)
- `Template.helloRight.onCreated ⇒ this.data = { 'withTemplateDynamic': 'right' }`

[interesting commit](https://github.com/meteor/meteor/commit/10fd9ab74c637f55f0b947a8a08b975ebb5fc93f)
## Diagnostic

Init state:

```
  curTpt → { template: 'catTpt', data: { 'lol': 'cat'} }; 
  {{> Template.dynamic curTpt}} ⇔ render({{> catTpt data={ 'lol': 'cat' } }})
```

Reactive update: 
- instead of: `curTpt → { template: 'catTpt', data: { 'lol': 'cat'} }`
- we have: `curTpt → { template: 'dogTpt', data: { 'lol': 'dog'} }`

Then we have:
  `curTpt → { template: 'dogTpt', data: { 'lol': 'dog'} }`
  `{{> Template.dynamic curTpt}}`
  ⇔ [`view.dataVar.set({ 'lol': 'dog' })`](https://github.com/meteor/meteor/blob/2229fdfd25e625109ba49ae4c31e1c81574bf8b8/packages/blaze/builtins.js#L22) // data context is treated independently from the template name in a ≠ and nested `with` contextual template (see [__dynamicWithDataContext](https://github.com/meteor/meteor/commit/10fd9ab74c637f55f0b947a8a08b975ebb5fc93f))
    `destroy({{> catTpt data={ 'lol': 'dog' } }}); // aouch!`  
    `render({{> dogTpt data={ 'lol': 'dog' } }});  // ok!`

What we would have liked...

```
  curTpt → { template: 'dogTpt', data: { 'lol': 'dog'} }
  {{> Template.dynamic curTpt}} 
  ⇔ destroy({{> catTpt data={ 'lol': 'cat' } }}); // ok!
    render({{> dogTpt data={ 'lol': 'dog' } }});  // ok!
```

...because it had never been said through `{{> Template.dynamic curTpt}}` to ever
have something like `{{> catTpt data={ 'lol': 'dog' } }}`. Who would render a
lol-dog in a cat template anyway?
## Conclusion

What could be done:
- Getting rid of the nested "with" templates in `<template name="__dynamicWithDataContext">`: instead of 

```
with:
  data = { template: 'templateName', data: {_} }
  with:
    {{> template ../data}}
```

maybe:

```
with:
  data = { template: 'templateName', data: {_} }
  {{renderTemplateWithContext}}  {{!-- ⇔ {{> template data.data}} --}}
```

=> one autorun less => do not treat 'templateName' & {_} independently but at the same time.
- caching the data ?

```
Template.helloLeft.onCreated(function () {
    var self = this;
    self.autorun(function () { self.context = Template.currentData(); });
});
```
- ???

**Comment by nomosyn** [comment] 2015-08-08 09:42
Updated diagnostic

**Comment by nomosyn** [comment] 2015-08-08 12:05
Simplified issue description

**Comment by stubailo** [comment] 2015-08-11 23:17
@nomosyn can you tell me the higher-level problem overview here?

What are you expecting Template.dynamic to do, why, etc.

This contains a lot of technical information but it's hard for me to unpack what your expected behavior is.

**Comment by nomosyn** [comment] 2015-08-11 23:47
The problem is that `this.data` gives unexpected value in the `onDestroy` callback when using `Template.dynamic` to render templates.

With this setup:

helper:
```javascript
'curTpt': () => Session.get('bool')  ?
                        { 'template': 'tpt_1', 'data': { d: 1 } } 
                      : { 'template': 'tpt_2', 'data': { d: 2 } }
```
inside helper's corresponding template html code:
```
{{> Template.dynamic curTpt }}
```

this init value: `Session.get('bool') === true`

Then: 
```
{{> Template.dynamic curTpt }} <=> {{> tpt_1 data={ d: 1 } }}
```

If `Session.set('bool', false)` then we have:
```javscript
// reactivity => curTpt() = { 'template': 'tpt_2', 'data': { d: 2 } } => tpt_1 cleaned
tpt_1.onDestroyed(function(){ 
self.data === { d: 2 }  // instead of { d:1 }
})
```

We should have had:
```javscript
tpt_1.onDestroyed(function(){
self.data === { d: 1 } 
})
```

because, given `curTpt`, the only possible values of `{{> Template.dynamic curTpt }}` are:
`{{> tpt_1 data={ d: 1 } }}` or `{{> tpt_2 data={ d: 2 } }}` but never `{{> tpt_1 data={ d: 2 } }}`

I'm willing to help clarify more wherever needed.

**Comment by mitar** [comment] 2015-10-15 01:57
>  I expected to call some functions supposed to be

Huh huh. Using data context to pass functions? This will never turn out well. :-)

But I do not see the problem here, you have a reactive data context and you change it and it is different than at the end? This is normal behavior. Data contexts do not necessary make template be recreated. This is a good thing. So when data context change, template might stay the same. Or sometimes it is being destroyed, and yes, at that point data can happen to already be updated during destruction phase because data changes is driving the destruction in the first place.

**Comment by stubailo** [comment] 2015-10-15 05:01
I think I get it - the point is, it's not a consistent worldview. Either d is 1 and we have `tpt_1` rendered, or d is 2 and we have `tpt_2`. There shouldn't be a situation where we are still dealing with `tpt_1` and the data context is already 2.

**Comment by mitar** [comment] 2015-10-15 05:06
Oh, it is pretty inconsistent. It is even different across browsers. :-) In [tests for Blaze Component](https://github.com/peerlibrary/meteor-blaze-components/blob/master/tests/tests.coffee#L1220) I have a test case where I log all changes to reactive sources (like `isCreated`, `isRendered`, `isDestroyed`, `data` and so on) and there are some strange changes in data context when data context triggers recreation of a template.

**Comment by phfrohring** [comment] 2015-10-15 05:53
@stubailo Yes. With current settings `{{> Template.dynamic curTpt }}` expresses: "given some context values (`Session.get('bool')` here) give me either the template `tpt_1`with context `{d:1}` or `tpt_2` with context `{d:2}` and respectively each associated behavior (`onCreated, onDestroyed, ...`).

Instead we have a piece of unexpected behavior: `tpt_1.onDestroyed` with context `{d:2}`

**Comment by phfrohring** [comment] 2015-10-15 05:56
@mitar Thx for the explanation and tests.  What would you do to avoid this problem?

**Comment by mitar** [comment] 2015-10-15 06:05
I do not know, I use [Blaze  Components](https://github.com/peerlibrary/meteor-blaze-components) these days which do not require you to mess with data context manually. You use data context for stuff coming from the database, while other stuff you simply pass through components tree or components arguments.

**Comment by mitar** [comment] 2015-10-15 06:07
(But this is not the solution to the fact that when data context changes, old data context is not available anymore when destroying. I would say this is just how the design is. Data context is leading changes.)

**Comment by phfrohring** [comment] 2015-10-15 06:32
@mitar We experimented a bit and came up with [this stuff](https://github.com/phfrohring/alternative-todos-architectures) instead...

One consequence is that we almost don't use data context anymore contrary to Blaze Components.
Instead, we bind/unbind so-called free variables of what we call components to the application state.
Components send messages to  this state, then interpretation than reactivity does the rest (which makes it ≠ from Flux/React: we "talk" to the DB thx to `Meteor.Collection` that are reactive data sources)

You may have a look...
[here is the problem we try to solve](https://github.com/phfrohring/alternative-todos-architectures/blob/master/README.md)
[here is the solution we offer](https://github.com/phfrohring/alternative-todos-architectures/blob/master/arch_d/README.org)
[here is a short implementation](https://github.com/phfrohring/alternative-todos-architectures/tree/master/arch_d)  (based on meteor todos for functionalities but with implementation we offer)

Thx!

**Comment by mitar** [comment] 2015-10-15 06:39
Interesting. And no, Blaze Components do not necessary use data context. If you want to use, you can. But main form of reactivity is local state for each component, where you attach it with [reactive-field](https://github.com/peerlibrary/meteor-reactive-field). And then you can navigate the component tree to get access to other components and use any API you want to talk to them.

I dislike global states and events/messages. Some my [thoughts on this subject](https://github.com/peerlibrary/meteor-blaze-components/issues/82).

**Comment by mitar** [comment] 2015-10-15 06:46
Also look at the [computed-field](https://github.com/peerlibrary/meteor-computed-field) package. It seems that is what you are calling derived variables.

OK, looking at your diagrams. I would say that my ideas are similar, just that I am using reactivity for both directions of communication, not messages for one, and reactivity for another. Because in my opinion reactivity is a general case of message passing (message passing with a state). You can always use reactivity as message passing: you simply wait in the autorun for the first state change and then you stop your autorun. You just received your message.

But it allows also that you combine your messages and have actions which should happen only when some combinations of states becomes true. It is pretty hard to do that with messages.

**Comment by phfrohring** [comment] 2015-10-15 07:45
[reactive-field](https://github.com/peerlibrary/meteor-reactive-field) looks great :-), will try that!
[computed-field](https://github.com/peerlibrary/meteor-computed-field) and that too!

> I dislike global states and events/messages

Well it is not actually global.  

Each component has the same structure, it's recursive.
=> component may host a state and an interpreter,
=> may build a message from other messages and pass it into a higher interpreter.

The interpreter hosts a rooting table:
  message `click` from `sidebar.dashboard` => do this
  message `click` from `header.title` => do that
  ...

=> each component can be developped independently from the context, because it
takes the context to interpret the messages.
Ex: a component emit the same type of messages whatever its address is
`sidebar.dashboard` or `main`.

The topology is not included in the network of templates but rather in the rooting tables, else it makes the components to rely on an implicit context that has to be discovered by "looking up" in ancestors: it tieds them together when I'm searching for a way to split the development in parallel and merge it afterwards. Merging <=> building a routing table + interpretation of messages.

I'm still not finished with the [Actor Model](https://en.wikipedia.org/wiki/Actor_model) but it looks like a great way to get inspiration from... Alan Kay also!

PS: I copy this message to your thread since it drifts a bit from this thread.

**Comment by mitar** [comment] 2015-10-15 07:47
Yes, let's move it there.

**Comment by hwillson** [comment] 2016-11-16 12:57
Hi @mitar - it's difficult to tell from this issues thread if this issue should be migrated over to the Blaze repo or just closed. I believe people have gotten used to the way `Template.dynamic` works, and as you mentioned in https://github.com/meteor/meteor/issues/4909#issuecomment-148291525, this is just how the current design is. Let me know if you think this should be migrated to the Blaze repo, and I'll get it done. Thanks!

**Comment by mitar** [comment] 2016-11-16 19:03
I vote for just closing. This is probably a very tricky thing to change, and I think we should anyway move away from data context.

**Closed by mitar** 2016-11-16 19:03 UTC
Labels: Project:Blaze
