### ISSUE TITLE
Install Script Failing on Debian/Ubuntu

### ISSUE THREAD

**Issue by nephogram** [meteor/meteor#7353] opened 2016-07-04 08:32 UTC
- What version of Meteor you're using, and the platform(s) you're running it on
latest version

- What packages or other dependencies you're using
Not yet using any package.

- OS
ubuntu 14.04
3.13.0-88-generic

- The behavior you expect to see, and the actual behavior
command: $ curl https://install.meteor.com | /bin/sh
expect: Complete Downloading Meteor distribution.
actual message: /bin/sh: 151: [[: not found

- An *isolated* way to reproduce the behavior
bash command: $ curl https://install.meteor.com | /bin/sh

plz fix meteor.com install script.

while [ $CODE -ne 0 ] && [ $ATTEMPTS -lt $MAX_ATTEMPTS ]
do
  ATTEMPTS=$((ATTEMPTS + 1))

  # Only show progress bar animations if we have a tty
  # (Prevents tons of console junk when installing within a pipe)
  **if [[ -t 1 ]]; then**
    curl --progress-bar --fail "$TARBALL_URL" -C - -o "$TARBALL_FILE"
  else
    curl -s --fail "$TARBALL_URL" -C - -o "$TARBALL_FILE"
  fi

  CODE=$?
done
set -e

**Comment by abernix** [comment] 2016-07-04 11:16
Thanks for reporting this – and sorry for the issue.  This is happening because a recent change to the installer script to resolve network issues (#6960) and most likely affects systems which don't have `bash` as the default system shell (for example Ubuntu uses `dash` instead of `bash`).

This should be fixed in a few hours, but assuming your system has `bash` installed _somewhere_ (it probably does), you can run:

    curl https://install.meteor.com | bash

**Comment by tmeasday** [comment] 2016-07-04 13:15
Sorry about this! I've reverted the relevant change. Let me know if it's not fixed.

**Closed by tmeasday** 2016-07-04 13:15 UTC
Labels: bug, confirmed, Impact:some, Project:Installer, Severity:blocks-development, Severity:has-workaround

**Comment by abernix** [comment] 2016-07-04 13:27
Confirmed fixed on Ubuntu 14.04 using `dash`.
