### ISSUE TITLE
Bumping Package Versions

### ISSUE THREAD

**Issue by janat08** [meteor/meteor#9159] opened 2017-09-30 15:50 UTC
What purpose could this possibly server other than making it difficult to ship hacked versions of base packages, and merging git branches, in addition watering down importance of versioning.

**Comment by hwillson** [comment] 2017-10-05 12:21
GitHub issues are reserved for bugs with Meteor. I don't quite follow what you're saying here, and can't extract a bug report, so closing for now.

**Closed by hwillson** 2017-10-05 12:21 UTC

**Comment by janat08** [comment] 2017-10-05 13:06
Every time there's a new release, accompanying it are bumped base package versions as per the title.

**Comment by hwillson** [comment] 2017-10-05 14:35
Sorry, I didn't quite get that question from your title. The reason why is outlined [here](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13) in the release notes, but I'll re-cap:

> Versions of Meteor core packages are once again constrained by the current Meteor release.
> 
> Before Meteor 1.4, the current release dictated the exact version of every installed core package, which meant newer core packages could not be installed without publishing a new Meteor release. In order to support incremental development of core packages, Meteor 1.4 removed all release-based constraints on core package versions (#7084). Now, in Meteor 1.4.3, core package versions must remain patch-compatible with the versions they had when the Meteor release was published. This middle ground restores meaning to Meteor releases, yet still permits patch updates to core packages.

This isn't a bug - this approach is by design. If you think it should be handled differently, please consider opening a feature request over in https://github.com/meteor/meteor-feature-requests.
