### ISSUE TITLE
ServerResponse.OutgoingMessage.write: write after end

### ISSUE THREAD

**Issue by elie222** [meteor/meteor#8043] opened 2016-11-10 21:43 UTC
I'm seeing this error a lot in development at the moment. It just seems to happen randomly and causes the server to crash. Any ideas? It may also happening in production.
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:430:15)
    at IncomingMessage.ondata (_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:368:10)
    at flow (_stream_readable.js:759:26)
    at resume_ (_stream_readable.js:739:3)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by elie222** [comment] 2016-11-11 03:42
I just got another type of random shutdown in development. This time the error is merely:
```Abort trap: 6```

**Comment by PEM--** [comment] 2016-11-16 12:26
Same for me since 1.4.2.1.

**Comment by timothyarmes** [comment] 2016-11-16 12:38
I'm also getting a random shutdown after upgrading to 1.4.2.1 from 1.4.1.3:

```
Darwin 16.1.0
npm ERR! argv "/Users/Tim/.nvm/versions/node/v6.5.0/bin/node" "/Users/Tim/.nvm/versions/node/v6.5.0/bin/npm" "run" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! mysite@3.5.0 start: `meteor --settings settings.dev.json`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the mysite@3.5.0 start script 'meteor --settings settings.dev.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mysite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor --settings settings.dev.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mystic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mysite
npm ERR! There is likely additional logging output above.

```

The log file gives this error:

```
14 verbose stack Exit status 6
14 verbose stack     at EventEmitter.<anonymous> (/Users/Tim/.nvm/versions/node/v6.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/Tim/.nvm/versions/node/v6.5.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by thierryler** [comment] 2016-11-16 14:06
Same bug for me :-( I cannot find the pattern that makes it crash. When my mac book pro turns into screensaver mode, it uses to crash but not every time.

**Comment by vblagomir** [comment] 2016-11-21 11:10
Getting `Abort trap: 6` regularly when client is rebuilding.. just now happened after changed a .less file.

**Comment by abernix** [comment] 2016-11-21 11:56
I do not have a recommendation for the original issue here but if you're getting the `Exit status 6` or `Abort trap: 6`, please try raising your open file limits on OS X [using these instructions](https://gist.github.com/abernix/a7619b07b687bb97ab573b0dc30928a0).

**Comment by abernix** [comment] 2016-11-21 11:57
As to the original issue, it will be near impossible to help without a reproduction so please try to assist with [the making of one](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) if you are experiencing this issue!  Thanks!

**Comment by PEM--** [comment] 2016-11-21 12:00
@abernix My ulimit are already set to 524288.

**Comment by timothyarmes** [comment] 2016-11-21 12:05
my ulimit is also very high - it's not that.

**Comment by abernix** [comment] 2016-11-21 12:28
@timoabend @PEM-- Ok, thanks, was just good to check as functioning file-watchers are more even more important in Meteor 1.4.2!  Are you both getting the issue originally mentioned in this issue (i.e. `write after end`)?

**Comment by PEM--** [comment] 2016-11-21 12:37
In my case, the crashes occur randomly at least 4 times per day with random messages too, like this issue (a `write after end`), like the one mentioned by @timothyarmes and like the one mentioned by @vblagomir (a `SIGABRT`). 

Not sure if they are all correlated.

**Comment by abernix** [comment] 2016-11-21 13:49
Ok, thanks for the clarification.  In bizarre issues like this the more details the better because this is not something that a lot of users are reporting and 1.4.2.x has been out for a while now.  Have you had an opportunity to monitor the memory usage throughout the day?  Are you able to reproduce this on a basic project or only with a larger application?

@timothyarmes, I'm not sure that it's in play here but I would recommend using `meteor npm start` instead of just `npm start` to avoid any potentially-weird situations arising from a `node` 6 process (which is what you seem to have installed globally, and used by `npm`) spawning a `node 4` process (which is what Meteor uses).  There have been bizarre situations in the past with `node`s running `node`s (#7491).  If you use `meteor npm` you will match your `node` versions.

**Comment by elie222** [comment] 2016-12-29 06:57
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:430:15)
    at IncomingMessage.ondata (_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:368:10)
    at flow (_stream_readable.js:759:26)
    at resume_ (_stream_readable.js:739:3)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)
```

I'm getting this error consistently when opening my app in Safari while developing.

**Comment by arggh** [comment] 2017-02-08 09:00
>  better because this is not something that a lot of users are reporting and 1.4.2.x has been out for a while...

Thought I'd report here as well, I've been getting this...

```
=> App running at: http://localhost:3000/
=> Client modified -- refreshing (x12)Abort trap: 6
```

...for a while now, crashing my app locally 4-10 times per day. It's probably not the allowed open files limit, I have adjusted those (actually specifically according to instructions by @abernix in a Gist).

Seems to happen at random: I might just leave my app running, write an email or two and later find out that it has crashed in the background.

**Comment by abernix** [comment] 2017-02-09 12:05
@arggh You should chime in on #8002, which I just [commented on](https://github.com/meteor/meteor/issues/8002#issuecomment-278622730) as that sounds more like your problem.  A debuggable reproduction is necessary to get to the bottom of it, so if you can assist with that it'd be much appreciated!

**Comment by arggh** [comment] 2017-02-09 12:23
Thanks, I tried searching for the appropriate issue to report in, but completely missed #8002 somehow.

**Comment by anderson916** [comment] 2017-03-03 05:53
the same error on 1.4.3.1

**Comment by elie222** [comment] 2017-05-15 16:40
same error happening to this day. and in production too

**Comment by airstep** [comment] 2017-08-03 11:58
Same error:

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write after end
>     at ServerResponse.OutgoingMessage.write (_http_outgoing.js:442:15)
>     at IncomingMessage.ondata (_stream_readable.js:542:20)
>     at emitOne (events.js:77:13)
>     at IncomingMessage.emit (events.js:169:7)
>     at IncomingMessage.Readable.read (_stream_readable.js:368:10)
>     at flow (_stream_readable.js:759:26)
>     at resume_ (_stream_readable.js:739:3)
>     at nextTickCallbackWith2Args (node.js:511:9)
>     at process._tickCallback (node.js:425:17)
> 

Meteor 1.5.1

**Comment by hwillson** [comment] 2017-09-14 15:43
As mentioned in https://github.com/meteor/meteor/issues/8043#issuecomment-261918087, this is a difficult issue to troubleshoot without a reproduction (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). If anyone is still encountering this problem using a recent version of Meteor, and can supply a reproduction demonstrating this issue, that would really help. Until then however, there isn't much we can do here, so closing for now. Thanks!

**Closed by hwillson** 2017-09-14 15:43 UTC
Labels: can't-reproduce

**Comment by elie222** [comment] 2017-09-14 16:11
We figured out the cause of our issue. We were serving an iframe from the
public folder. We also use iron router. The fix was to add a server side
route for iron router for this iframe we were getting from the public
folder.
