### ISSUE TITLE
Installing/Downloading meteor fails on 100KBps internet connections

### ISSUE THREAD

**Issue by Tusharsb** [meteor/meteor#7101] opened 2016-05-23 05:55 UTC
I am installing Meteor 1.3 by following the [installation instructions](https://www.meteor.com/install). I type the following in my terminal
`curl https://install.meteor.com/ | sh`
And I end up with this error
> curl https://install.meteor.com/ | sh              tushar@Tushar-Goswami-PC
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  6675    0  6675    0     0   4890      0 --:--:--  0:00:01 --:--:--  4893
> Removing your existing Meteor installation.
> Downloading Meteor distribution
> #########                                                                 13.2%
> curl: (18) transfer closed with 152287334 bytes remaining to read
> 
> gzip: stdin: unexpected end of file
> tar: Unexpected EOF in archive
> tar: Unexpected EOF in archive
> tar: Error is not recoverable: exiting now
> Installation failed.

I tried this from 3 different Internet connections at different locations of North India. Each one of them is running at 100-200KBps. They all fail at 13%, sometimes at 50% or sometimes at 80%.

The download & installation processes works perfect when I try from my digitalocean or google cloud serves (probably the download speed are faster there). I think 100KBps speed is not that bad. To get around this error I had to do the following to install meteor via
> git clone https://github.com/meteor/meteor.git
> cd meteor
> ./meteor --help

I skimmed through a few issues on github to see if anyone else is facing similar issue. Can this be solved sooner ?

**Comment by abernix** [comment] 2016-05-23 06:28
Closing as a duplicate of #6960 (recently reopened).  Please check there for instructions on how to report your error and debug information as well as information on how to install manually!  Thanks!

**Closed by abernix** 2016-05-23 06:28 UTC
