### ISSUE TITLE
[1.3-modules-beta.8] Can't use NPM packages with directories named "private", "packages", "server", "programs"

### ISSUE THREAD

**Issue by jperl** [meteor/meteor#6001] opened 2016-01-14 16:01 UTC
Getting this TypeError thrown from [the linker](https://github.com/meteor/meteor/blob/release-1.3/tools/isobuild/linker.js#L231) when trying to run our project with 1.3-modules-beta.4.

<img width="895" alt="screen shot 2016-01-14 at 10 59 40 am" src="https://cloud.githubusercontent.com/assets/1136652/12329379/25f3995c-baae-11e5-9e46-cf1ffa206fb1.png">

**Comment by vraptor75011** [comment] 2016-01-15 06:23
I got this one because i had a folder named private. I changed the name and it was OK.

**Comment by avital** [comment] 2016-01-21 17:19
@vraptor75011 Was the folder in a package or your app?

**Comment by avital** [comment] 2016-01-21 17:19
We'd like to look into this but we'll need a proper repro to look at.

**Comment by vraptor75011** [comment] 2016-01-22 17:15
In my app /client/components/private . Sorry no repro available since I changed the name and went on !

**Comment by raix** [comment] 2016-01-23 05:14
This happens if a package like `dispatch:signature@1.0.1` https://github.com/DispatchMe/meteor-signature contains an example app inside of it.

fixed in `1.0.2-rc.1`

**Comment by reohjs** [comment] 2016-01-31 20:40
I managed to reproduce this on 1.3-modules-beta.5.

Repo: https://github.com/reohjs/tests-1-3

The cause indeed is related to folder naming: `packages, programs, cordova-build-override; `
and
`server or private`
on the client

**Comment by newsiberian** [comment] 2016-02-02 07:23
Also faced with this error in [reaction](https://github.com/reactioncommerce/reaction). Reaction widely uses packages as modules and there are few places with `private` folders inside.

**Comment by AdamBrodzinski** [comment] 2016-02-05 06:17
Deleting `.meteor/versions` fixed the error for me.

**Comment by avital** [comment] 2016-02-10 01:19
As of 1.3-modules-beta.8, the bug manifests itself differently.

Instead of the TypeError described above, it just fails to import files from within subdirectories of a NPM package with certain names ("private", "packages", "server", "programs").

**Comment by avital** [comment] 2016-02-10 01:19
@newsiberian What are some examples of NPM libraries that have subdirectories that don't work?

**Comment by newsiberian** [comment] 2016-02-10 03:33
@avital, I'm sorry, with the two latest betas I don't faced with this anymore.

**Comment by avital** [comment] 2016-02-10 07:15
Can other people confirm or deny that there is still such a problem with some NPM libraries on 1.3-modules-beta.8?

**Comment by avital** [comment] 2016-02-10 19:35
@benjamn It seems that all the users that reported it so far say that they are no longer hitting this issue -- I thought that makes this low priority especially compared to the many other very serious regressions. Do you disagree?

**Comment by jperl** [comment] 2016-02-10 19:37
We are no longer seeing this.

**Comment by benjamn** [comment] 2016-02-10 19:43
@avital I agree it's not as urgent, but I wanted to be sure I wrote a test for it.

**Comment by benjamn** [comment] 2016-02-26 22:03
This should be fixed in the next beta, if it was not fixed before.

**Closed** 2016-03-01 19:33 UTC
Labels: confirmed, known-fix, needs-repro
