### ISSUE TITLE
[1.3-beta.16] Phaser.io Error: Uncaught ReferenceError: PIXI is not defined

### ISSUE THREAD

**Issue by vadimmelnicuk** [meteor/meteor#6458] opened 2016-03-10 16:02 UTC
I have added npm package 'phaser' to newly create beta.16 meteor project like so:

`meteor create project --release 1.3-beta.16`
`npm install phaser --save`

I also added `import Phaser from 'phaser';` to main.js

When trying to run the project I get `phaser.js:45903 Uncaught ReferenceError: PIXI is not defined` error in Chrome console.

**Comment by benjamn** [comment] 2016-03-10 18:53
The problem is that Phaser expects `PIXI` to be defined [globally](https://github.com/photonstorm/phaser/blob/47123c192df7f3a78ac25110a9a72b72f61417c2/src/Phaser.js#L364), but the version of PIXI that it bundles tries to be intelligent about assigning itself to `module.exports` when possible:
```js
if (typeof exports !== 'undefined') {
    if (typeof module !== 'undefined' && module.exports) {
        exports = module.exports = PIXI;
    }
    exports.PIXI = PIXI;
} else if (typeof define !== 'undefined' && define.amd) {
    define('PIXI', (function() { return root.PIXI = PIXI; })() );
} else {
    root.PIXI = PIXI;
}
```
In Meteor 1.3, `exports`, `module`, and `module.exports` are defined because, well, Meteor 1.3 introduces a CommonJS/Node-compatible module system. So you can see the problem!

It looks like newer versions of PIXI [solve](https://github.com/pixijs/pixi.js/blob/6eb8c5ae6783a6dce30587eaa9dc9961e6eb4cc9/src/index.js#L27-L28) this problem. I would tell you to import `PIXI` yourself and define it globally, but it's buried inside a Browserify bundle, so I'm afraid you'll just have to wait until Phaser releases a version that upgrades PIXI. I know that's not what you want to hear, but that's what happens when your dependencies take responsibility for their own bundling and get it wrong.

**Closed** 2016-03-10 22:19 UTC

**Comment by vadimmelnicuk** [comment] 2016-03-11 08:23
Ben, thanks for this comprehensive answer.
