### ISSUE TITLE
Meteor 1.2-rc12: "to: wrong arguments" and "toEnd: wrong arguments" errors on startup

### ISSUE THREAD

**Issue by brianlukoff** [meteor/meteor#5107] opened 2015-09-04 22:26 UTC
Using the TAPi18n package with 1.2-rc12 causes the following errors on startup:

```
=> Started proxy.
=> Started MongoDB.
to: wrong argumentstap-i18n-compiler` fr...  |

toEnd: wrong arguments
```

It appears to be due to a conflict between Shell.js (which appears to be newly utilized in 1.2) and String.js, which is used by the popular simple-schema package (and possibly others).  (TAPi18n in turn uses simple-schema.)  Shell.js modifies the String prototype -- see this Shell.js issue: https://github.com/arturadib/shelljs/issues/159

One possible resolution would be for simple-schema to use a newer version of String.js that works around this issue, but it's possible that Shell.js's modification of String could have other unintended consequences for apps or packages.  Another resolution would be for Meteor to not use Shell.js.

**Comment by avital** [comment] 2015-09-08 21:27
Hmm. Not sure what the right answer is here, but based on the [shelljs issue thread](https://github.com/arturadib/shelljs/issues/159) you linked to, String.js recently released a new version that might work around this problem. So maybe the answer is to have simple-schema switch to that version instead? Looks like this has been noticed by the simple-schema maintainers as well: https://github.com/aldeed/meteor-simple-schema/issues/443

**Comment by brianlukoff** [comment] 2015-09-08 21:59
This only happens with Meteor 1.2 -- is shelljs a necessary dependency of Meteor, or is there an alternative that Meteor 1.2 could use in its place?  There may be other packages out there that use an old version of String.js, and they would also trigger this error.

**Comment by dgreensp** [comment] 2015-09-09 19:13
Where does the interaction occur?  If the fact that Meteor uses `shelljs` means that `String.prototype.to` and `String.prototype.toEnd` are set in the Meteor server environment, I would move to remedy that right away, though in some quick testing that doesn't seem to be the case.

**Comment by brianlukoff** [comment] 2015-09-09 19:22
It's not clear to me exactly where it occurs, but it must be on the server somewhere -- the logs that I posted above are from the server console in dev mode.

**Comment by mquandalle** [comment] 2015-09-09 19:46
More specifically doesn't that happen for build plugins? cf. the `simple-schema` dependency on the `tap-i18n` plugin: https://github.com/TAPevents/tap-i18n/blob/547097be1bc449f73322541c39653fc6bad2f51c/package.js#L55. I guess the string prototype shouldn't be modified for these.

**Comment by mquandalle** [comment] 2015-09-09 21:04
Yes I've just verified that on build plugins `String.prototype.to` is a defined function on 1.2 RCs whereas it was previously undefined.

**Comment by dgreensp** [comment] 2015-09-09 23:07
It looks like the dependency on `shelljs` is coming from `cordova-lib`, which the tool now uses.  Notably, `cordova-lib` does not itself use the weird `String#to` and `String#toEnd` methods, based on my grepping.

I decided to be bold and implement a workaround in the tool that prevents `shelljs` from doing its damage.  See: 98886f98ef71994fe43d23794270af8c24c3d006  @martijnwalraven, what do you think of this?

I don't quite understand why String.js is so sensitive to the presence of unexpected properties on String.prototype, but I certainly understand the desire to not have them be there.

I'm going to close this to take it off our radar for now.

**Comment by obiwarn** [comment] 2016-02-25 13:33
@avital 

reappears in 1.3 - beta 11

**Comment by martijnwalraven** [comment] 2016-02-25 19:52
@obiwarn: Could you post the complete stack trace? Curious to see what package depends on an older version of `string.js` (< 3.1.1) that doesn't include the workaround for the modifications `shelljs` adds. Or maybe some other package also gets confused by them.

**Comment by obiwarn** [comment] 2016-02-25 19:58
um...it is just logged in my console. how can i trace this?


"C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\bin\runnerw.exe"
C:\Users\sebas\AppData\Local\.meteor\meteor.bat run android-device -p 4000
[[[[[ C:\Users\sebas\Documents\storeapp ]]]]]

=> Started proxy.
=> Started MongoDB.
toEnd: wrong arguments

to: wrong arguments


WARNING: You are testing your app on a remote device. For the mobile app
         to be able to connect to the local server, make sure your device
         is on the same network, and that the network configuration allows
         clients to talk to each other (no client isolation).
I20160225-19:11:38.106(1)? ** You are using the appcache package but the
total size of the
I20160225-19:11:38.106(1)? ** cached resources is 7.1MB.
I20160225-19:11:38.107(1)? **
I20160225-19:11:38.107(1)? ** This is over the recommended maximum of 5 MB
and may break your
I20160225-19:11:38.107(1)? ** app in some browsers! See
http://docs.meteor.com/#appcache
I20160225-19:11:38.107(1)? ** for more information and fixes.
I20160225-19:11:38.107(1)?
=> Started your app.

=> App running at: http://localhost:4000/

Sebastian Obentheuer




+49 0176 569 88 564

sebastian@hoardspot.com


www.hoardspot.com


einFach GmbH, Alexanderstrasse 3, 10178 Berlin, Geschäftsführer: Anthony
Forsans

Registergericht: Amtsgericht Charlottenburg (Berlin), HRB 154297 B

2016-02-25 20:53 GMT+01:00 Martijn Walraven <notifications@github.com>:

**Comment by martijnwalraven** [comment] 2016-02-25 20:02
@obiwarn: Not sure if this helps, but could you try running with `--verbose`?

**Comment by martijnwalraven** [comment] 2016-02-26 11:32
@obiwarn: I've been able to reproduce this with `tap:i18n` added. 

Unfortunately, there is no easy workaround that will not break the Cordova packages, but `tap:18n` could update its `aldeed:simple-schema` dependency. That should solve at least this immediate issue, because recent versions of `aldeed:simple-schema` no longer depend on `string.js`. I've opened an issue for this: https://github.com/TAPevents/tap-i18n/issues/147.

Longer term, [it seems `shelljs` may finally get its act together and no longer modify `String.prototype`](https://github.com/shelljs/shelljs/pull/360). But we'll have to wait for that release to land and for the Cordova packages to update their dependencies before the issue has truly been solved.

**Comment by obiwarn** [comment] 2016-02-29 14:53
@martijnwalraven: Same here: tap:i18n causes this.

Thank you for the quick support.

But I did not get what it has to do with my Cordova packages?

**Comment by martijnwalraven** [comment] 2016-02-29 20:10
@obiwarn: The issue is that one of the Cordova packages the tool depends on (`cordova-android`) uses the String prototype methods `shelljs` adds.

**Comment by benjamn** [comment] 2016-02-29 22:38
I think I've fixed this in [a more reliable way](https://github.com/meteor/meteor/commit/757660a85d9eedb68bfe4a6b42ad63f4ba3d2070), though I really wish npmjs.org/package/string and npmjs.org/package/shelljs could cooperate better. In my opinion, the real problem is that npmjs.org/package/string tries to call every `String.protoype` method just to see if it exists. It's not unreasonable that some methods added by npmjs.org/package/shelljs don't like being called with zero arguments.

**Comment by martijnwalraven** [comment] 2016-03-01 05:21
@benjamn: Great work!

**Comment by benjamn** [comment] 2016-03-01 16:19
Fixed in [`beta.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-190789852).

**Closed by benjamn** 2016-03-01 16:19 UTC

**Comment by derwaldgeist** [comment] 2020-05-09 20:31
I have this on Meteor 1.10.2 now. Anything changed here?

**Comment by filipenevola** [comment] 2020-05-21 11:38
@derwaldgeist I don't think so.
