### ISSUE TITLE
Multiple (unwanted) mongodb connections saturate db deployment (Meteor 1.7.0.3, Mongodb 3.2.18)

### ISSUE THREAD

**Issue by igalicodean** [meteor/meteor#10174] opened 2018-08-22 08:38 UTC
I posted [a question on stackoverflow](https://stackoverflow.com/questions/51953997/meteor-multiple-unwanted-mongodb-connections-saturates-db-deployment)

It points out a gradual db connections leak in Meteor. It might be a little early to say, but it does look like a meteor framework bug.

I'm willing to provide repro scenarios + relevant resources to figure it out

**Comment by TheGame2500** [comment] 2018-08-22 14:40
Started happening for me too on the 16th of August according to compose.io metric graphs, had a 
prod deploy 2 days prior to that, but issue only began on the 16th. Attempted fixes were setting maxPoolSize/poolSize parameters to mongo url, did not work. Multiple apps with obviously different code are  suddenly spamming my database with connection. Experiencing exactly the same errors as @igalicodean . I have APM/Kadira enabled but it shows no erratic behaviour. App logs look normal. Only thing in common with @igalicodean seems to be the compose database.

**Comment by evolross** [comment] 2018-08-22 21:30
Possibly related: I had a mystery issue using Atlas DB on a production app using three Galaxy containers... a subset of new visitors to my app couldn't log in.  The app ran fine, no errors in client, or server (logs or Kadira) but **one** of my three containers stopped responding to `Meteor.loginWithPassword`.  I could never figure it out. The container was only a few days old. The other containers were working fine. I killed the container and the new container started working.  Could this be the same thing?

**Comment by TheGame2500** [comment] 2018-08-23 05:57
@evolross seems different, it's our database which responds slowly, our containers behave ok, albeit slowed down by the app. 

On a side note, I had a similar issue, but it was related to an Accounts.onLogin hook calling a Meteor method which never responded (and was our fault) so you could look into that.

**Comment by TheGame2500** [comment] 2018-08-23 06:38
I believe the issue might lie with https://github.com/meteor/meteor/blob/a52a2c28f148c6136ce5ddccade9d141fd1baf0e/packages/mongo/mongo_driver.js#L141  coupled with enabling TLS? I was seeing the same errors as https://stackoverflow.com/questions/51928555/meteor-consuming-huge-number-of-mongo-connections so perhaps failing SSL handshakes are at fault? Can anyone easily disable TLS?

**Comment by igalicodean** [comment] 2018-08-23 08:09
Update:
I've been communicating with Compose support re this issue. The point me to the direction of modifying Meteor's connection pool. They suggested the following (I didn't get to test it, yet):

> Could you try using the options described by Ross to set maxPoolSize to 1 and maxIdleTimeMS to 240000 (4 min)? I'm assuming the options are the standard connection string options (but you should double check that):
> 
> https://docs.mongodb.com/manual/reference/connection-string/#connection-pool-options
> 
> I came across this in my search:
> 
> https://github.com/danwild/set-connection-options
> 
> It might let you set further driver options:
> 
> http://mongodb.github.io/node-mongodb-native/3.1/reference/connecting/connection-settings
> 
> A common antipattern is creating multiple connection objects instead of just creating one and reusing it. This is a typical scenario in connection leaks, sometimes an object isn't destroyed and connections remain open and unused. They pile up faster than they time out. If you set the connection to 1 and still see many connections being created it can tell us that either the setting is not being applied or multiple objects are being created.
>

**Comment by TheGame2500** [comment] 2018-08-23 08:11
@igalicodean we did get the same directions from compose. Tried and didn't work.

**Comment by igalicodean** [comment] 2018-08-23 08:17
@TheGame2500 so, if I understand correctly - you've applied Compose's suggested solution on each and every app which is connected to the db deployment, and still saw increasing connections count on the Meteor instances?

**Comment by igalicodean** [comment] 2018-08-23 08:32
@evolross The issue you point out could be app-specific. 

As a reminder, you can check for increasing connection counts on your meteor instance using:
```sh
sudo lsof -p $(ps awx | grep node | grep main.js | cut -f 2 -d " ") | egrep 'TCP|UDP'
```
This is assuming your meteor is launched via `node mains.js`

On my meteor environments, I either see a handful of connections (about 6) or hundreds/thousands. Thousands mean you're bumping into this issue

**Comment by TheGame2500** [comment] 2018-08-23 10:09
@igalicodean I poked around meteor's guts and found there are 2 places where mongo connections are established (one for MONGO_URL and one for MONGO_OPLOG_URL) via the MongoConnection class defined there. 

Given that an oversight resulted in my apps not having an oplog url until yesterday (thought that might be the fix, it's not) it means that the `new MongoConnection` call for  MONGO_URL is the one triggering all the (re)connections.

I've found a way to reliably reproduce this locally (just connecting to the db with a dev app which I've created a special user for and checking authentication logs sent by Compose to papertrail). Modyfing aforementioned line from Infinity to 5 in `~/.meteor/packages/mongo/1.5.1/os/mongo_driver.js` and then `meteor reset`-ing and `meteor run`-ing my app seems to prevent all the connections from being spawned, but also results in my app hanging/crashing

**Comment by edwardupton** [comment] 2018-08-23 10:17
@igalicodean Does your app use aggregate db function via `meteorhacks:aggregate` package? That was behaviour that changed in Meteor 1.7, so just wondering if it's connected? i.e. whether aggregate calls don't free up connections.

Either way, if the `maxPoolSize` parameter from the connection URL was being respected, this issue wouldn't occur.

**Comment by igalicodean** [comment] 2018-08-23 17:26
@edwardupton `meteorhacks:aggregate` isn't in use by my apps.
Also, are you certain that the `maxPoolSize` connection option isn't respected by the driver?

**Comment by edwardupton** [comment] 2018-08-24 08:04
@igalicodean yes, all our apps have `maxPoolSize` set to 5 since we discovered this issue. We have around 20 instances connected to the db, so that should result in ~100 connections.

Yet the Compose db router is maxing out at 5000 connections.

The `maxIdleTimeMS` is cutting in at 5 minutes, but it seems that too many connections are created within a 5 minute period to keep the connections below 5000.

**Comment by igalicodean** [comment] 2018-08-24 09:33
@edwardupton it's interesting that we're all hosting our mongodb deployments at Compose. I'm curious if there are any deployments at mongodb.com or mlabs which are also showing this issue. So far, I don't know of any

**Comment by evolross** [comment] 2018-08-24 14:44
@igalicodean I run MongoDB Atlas in production. Six Galaxy containers, anywhere from 20 to a few hundred users at anytime. I checked the connections and I’m steady between 30-50 for months. I don’t see any spikes.  I redeploy a few times a week. Running Meteor 1.5.x.

**Comment by igalicodean** [comment] 2018-08-25 13:52
@evolross ok. Since you haven't noticed a high connections count, there's no reason to conclude you're deployment is experiencing the issue at hand

**Comment by igalicodean** [comment] 2018-08-30 09:42
I've rcvd this note from Compose:

> For some users the connection count issues appears to be caused by a bug in the node native driver which has been fixed with the v3.1.3 release (it is only about 2 weeks old).


Can anyone tell how to update a Meteor project to use this newer version of the mongodb driver?

**Comment by edwardupton** [comment] 2018-08-30 09:53
@igalicodean that makes sense.

Driver version would need to be updated here:
https://github.com/meteor/meteor/blob/devel/packages/npm-mongo/package.js

@benjamn can you make the update for the next release?

**Comment by TheGame2500** [comment] 2018-08-30 11:45
@igalicodean we should be able to roll our own npm-mongo package if we copy https://github.com/meteor/meteor/blob/devel/packages/npm-mongo into own-app-folder/packages/npm-mongo and change https://github.com/meteor/meteor/blob/a52a2c28f148c6136ce5ddccade9d141fd1baf0e/packages/npm-mongo/package.js#L11 to "3.1.3" but we need to beware breaking changes and stuff

**Comment by igalicodean** [comment] 2018-08-30 19:03
@TheGame2500 Sounds like a great intermediate approach, which might hold until the meteor devteam updates the official release!
Have you been able to test & deploy this change?
btw, once I make this change, and `meteor reset` how can I confirm the driver version has actually changed?

**Comment by TheGame2500** [comment] 2018-08-30 20:21
@igalicodean just add a console.log where you change the mongodb driver version. Whenever the log fires you’ll know the package is in action. I didn’t try it yet but I have some experience replacing a meteor default package (an accounts related adventure). You can also bump the package version (the one in projectFolder/.meteor/versions and the one in projectFoler/packages/npm-mongo/package.js) to a previously unexisting version (e.g. “99.99.99”) and if `meteor run` throws no error it is certainly running your local replacement.

**Comment by etyp** [comment] 2018-08-31 03:44
@evolross sounds like an issue we've been having for a while - see my forum post about it [here](https://forums.meteor.com/t/meteor-login-method-never-invokes-callback-blocks-all-future-rpc-calls/36305/14). Any info you can add there might help the rest of us resolve.

**Comment by edwardupton** [comment] 2018-08-31 05:08
Seems that driver update is coming soon:
https://forums.meteor.com/t/upgrade-mongodb-driver-on-meteor-1-7-0-4/45363/5

I see release 1.7.0.5 upgraded npm-mongo to 3.0.11, but that may not
include fix for connections issue.

**Comment by abernix** [comment] 2018-08-31 09:29
Thanks for all the research that's gone into this.  The underlying Node.js Mongo driver is definitely in play here. Historically, in terms of connection handling, changing its version has usually been the source of and solution to many connection problems since, as you've discovered, Meteor leverages that driver's connection handling functionality.

To try and get an extra data point that validates that the newer driver would solve this problem (instead of blindly publishing a new version that might introduce other problems), could someone who can reliably reproduce this copy the [`npm-mongo` package source](https://github.com/meteor/meteor/tree/master/packages/npm-mongo) into their own application's `packages/` directory and try bumping the `mongo` version to the latest 3.1.x release? ([`3.1.4` is now out](https://github.com/mongodb/node-mongodb-native/blob/master/HISTORY.md#314-2018-08-25)).  You can download a tarball of the (above) `npm-mongo` source using [this link](https://download-directory.github.io/?url=https://github.com/meteor/meteor/tree/master/packages/npm-mongo).

**Comment by TheGame2500** [comment] 2018-08-31 09:37
Hey @etyp I had the same issue and stumbled upon your post a while ago. What caused it for me was an Accounts.onLogin hook getting stuck; it was running Promise.await() on a sometimes never resolving/rejecting promise (top code right there @self).

**Comment by etyp** [comment] 2018-08-31 19:28
@TheGame2500 hmm interesting. Our server-side `Accounts.onLogin` doesn't (I think) use anything which would return a promise. See it below:

```
Accounts.onLogin(() => {
  const user = Meteor.user();
  if (user.emails) {
    const regex = new RegExp(user.emails[0].address, 'i');
    Meteor.users.remove({ existingAccount: { $regex: regex, $options: 'i' } });
  }
});
```

Anything that stands out there?

**Comment by benjamn** [comment] 2018-09-18 19:27
Can folks try updating to the latest Meteor 1.8 release candidate to get `mongodb@3.1.6`?
```bash
meteor update --release 1.8-rc.15
```

**Comment by omidahourai** [comment] 2018-09-19 15:35
@benjamn also having this issue, trying the update now. Just fyi I am getting the warning:
```
=> Started proxy.                             
The version of @babel/runtime installed in your node_modules directory 
(7.0.0) contains a breaking change which was introduced by 
https://github.com/babel/babel/pull/8266. Please either downgrade by 
running the following command:

  meteor npm install --save-exact @babel/runtime@7.0.0-beta.55

or update to the latest beta version of Meteor 1.7.1, as explained in 
this pull request: https://github.com/meteor/meteor/pull/9942.
```
even though I have `7.0.0-beta.55` version and I also tried upgrading the package to `^7.0.0`

**Comment by 4815162342** [comment] 2018-09-20 16:43
Hey guys – just wanted to add some interesting data here as I'm facing the same problem:

- Meteor 1.7.0.5
- Codebase hosted with Galaxy
- Database hosted with Compose which runs MongoDB 3.4.10
- Seeing maxed out (5,000) connections to just **one** mongo router
- Concurrent Galaxy users never exceeds 150

What I've found to be interesting is that the mongo router that's being maxed out is listed second in Meteor's environment MONGO_URL connection string. That is, our connection string is `mongodb://user:pass@aws-us-east-1-portal.50.dblayer.com:123,aws-us-east-1-portal.51.dblayer.com:123/db?ssl=true`, but 50 is seeing appropriate traffic while 51 is being maxed out.

Haven't gotten a chance to try Meteor 1.8 beta yet as benjamn recommended.

**Comment by omidahourai** [comment] 2018-09-24 15:30
Hey guys, I'm verifying the upgrade to meteor `1.8-rc.16` as @benjamn suggested is working. Before, compose was showing up to 5000 active mongo connections, now it's reduced to 35 in the latest logs.

**Comment by 4815162342** [comment] 2018-10-01 15:46
I'm getting the same results as @omidahourai – upgrading to Meteor `1.8-rc.16` completely fixed the issue. Open mongo connections deflated back to normal amounts.

Thanks!

**Comment by benjamn** [comment] 2018-10-03 22:17
Since I'm hoping for Meteor 1.8-rc.17 to be the last release candidate before the final 1.8 release, I think it's reasonable to recommend that folks run `meteor update --release 1.8-rc.17` to fix this problem, and thus we can consider it fixed. Thanks very much for the thorough discussion, everyone!

**Closed by benjamn** 2018-10-03 22:17 UTC
Labels: Impact:some, Project:Mongo Driver, Severity:production, bug, confirmed, fixed, known-fix

**Comment by yogeshwar607** [comment] 2018-12-14 21:08
I am also facing same issues on Meteor version - METEOR@1.4.4.6 , Mongodb - 3.2.10 
I can not update app to  --release 1.8-rc.17 due to some legacy code structure.

What should be the solution in that case ?

**Comment by igal1c0de4n** [comment] 2018-12-14 23:54
@yogeshwar607  I can confirm that the update to meteor 1.8 solved this issue in my deployment.

As for the legacy code structure - I'm no expert as for replacing the driver in meteor 1.4, but  
I can share that my apps had the older code structure which I've ended up modifying so they can benefit from meteor upgrades

**Comment by yogeshwar607** [comment] 2018-12-15 10:34
@igal1c0de4n can you please share code structure and any guideline for modifying app structure

**Comment by igal1c0de4n** [comment] 2018-12-15 23:59
I'm pretty sure we're going off subject, but anyhow since you asked, I meant I changed the code according to [this guide](https://guide.meteor.com/structure.html)

**Comment by rclai** [comment] 2019-01-16 15:51
Which version of MongoDB (not the driver) does this connection leak issue start? Is it 3.2.18? What's the oldest version where an older driver wouldn't have this connection leak?
