### ISSUE TITLE
[Cordova, Android] Application Error: The connection to the server was unsuccessful

### ISSUE THREAD

**Issue by jschlieber** [meteor/meteor#7560] opened 2016-08-03 09:33 UTC
I'm struggling with an annoying error message appearing when launching my android app on older devices (e.g. Samsung Galaxy S3, Minix devices). It always happens when auto launching the app with `cordova-plugin-autostart@2.0.1` and from time to time when launching manually as well. Interestingly the app loads and works correctly behind the error message, but it is stopped as soon as I tap the OK button.

![Screenshot of Error](https://s32.postimg.org/6qqa1dfs5/application_error.jpg)

I tried this [approach](http://stackoverflow.com/questions/12319809/application-error-the-connection-to-the-server-was-unsuccessful-file-andr) adding a `loadUrlTimeoutValue`, but to no avail.

This is a real show stopper as this app is intended to be used to automatically display information on startup...

Meteor Version: **1.3.4.4**

Packages:
```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

accounts-password
accounts-google
service-configuration

percolate:synced-cron
meteorhacks:picker
u2622:persistent-session
kadira:flow-router
fourseven:scss
react-meteor-data
reywood:publish-composite
aldeed:collection2
mdg:validated-method
tunifight:loggedin-mixin
okgrow:analytics

# cordova
crosswalk
mdg:reload-on-resume
```

Cordova Plugins:
```
cordova-plugin-autostart@2.0.1
cordova-plugin-fullscreen@1.0.3
cordova-plugin-insomnia@4.2.0
```

mobile-config.js:
```JavaScript
App.info({
    id: '***',
    name: '***',
    description: '***',
    author: '***',
    email: '***',
    version: '3.0.2'
});

App.setPreference("BackgroundColor", "#ffffffff");
App.setPreference("android-targetSdkVersion", "23");
App.setPreference("AutoHideSplashScreen", "true");
App.setPreference("SplashScreenDelay", "10000");
App.setPreference("FadeSplashScreenDuration", "250");
App.setPreference("ShowSplashScreenSpinner", "false");
App.setPreference("loadUrlTimeoutValue", "70000");  // doesn't solve the issue :/

App.accessRule('*://docs.google.com/*');
App.accessRule('*://www-onepick-opensocial.googleusercontent.com/*');
App.accessRule('*://oauth.googleusercontent.com/*');
App.accessRule('*://*.googleusercontent.com/*');
App.accessRule('*://accounts.google.com');
App.accessRule('*://ssl.gstatic.com/*');
App.accessRule('*://fonts.gstatic.com/*');
App.accessRule('*://csi.gstatic.com/*');
App.accessRule('*://googledrive.com/*');
App.accessRule('*://content.googleapis.com/*');
App.accessRule('*://fonts.googleapis.com/*');
App.accessRule('*://apis.google.com/*');

App.icons({
    "iphone_2x": "resources/icons/iphone_2x.png", // 120x120
    "iphone_3x": "resources/icons/iphone_3x.png", // 180x180
    "ipad": "resources/icons/ipad.png", // 76x76
    "ipad_2x": "resources/icons/ipad_2x.png", // 152x152
    "ipad_pro": "resources/icons/ipad_pro.png", // 167x167
    "ios_settings": "resources/icons/ios_settings.png", // 29x29
    "ios_settings_2x": "resources/icons/ios_settings_2x.png", // 58x58
    "ios_settings_3x": "resources/icons/ios_settings_3x.png", // 87x87
    "ios_spotlight": "resources/icons/ios_spotlight.png", // 40x40
    "ios_spotlight_2x": "resources/icons/ios_spotlight_2x.png", // 80x80
    "android_mdpi": "resources/icons/android_mdpi.png", // 48x48
    "android_hdpi": "resources/icons/android_hdpi.png", // 72x72
    "android_xhdpi": "resources/icons/android_xhdpi.png", // 96x96
    "android_xxhdpi": "resources/icons/android_xxhdpi.png", // 144x144
    "android_xxxhdpi": "resources/icons/android_xxxhdpi.png" // 192x192
});

App.launchScreens({
    "iphone_2x": "resources/splashes/iphone_2x.png", // 640x490
    "iphone5": "resources/splashes/iphone5.png", // 640x1136
    "iphone6": "resources/splashes/iphone6.png", // 750x1334
    "iphone6p_portrait": "resources/splashes/iphone6p_portrait.png", // 2208x1242
    "iphone6p_landscape": "resources/splashes/iphone6p_landscape.png", // 2208x1242
    "ipad_portrait": "resources/splashes/ipad_portrait.png", // 768x1024
    "ipad_portrait_2x": "resources/splashes/ipad_portrait_2x.png", // 1536x2048
    "ipad_landscape": "resources/splashes/ipad_landscape.png", // 1024x768
    "ipad_landscape_2x": "resources/splashes/ipad_landscape_2x.png", // 2048x1536
    "android_mdpi_portrait": "resources/splashes/android_mdpi_portrait.png", // 320x480
    "android_mdpi_landscape": "resources/splashes/android_mdpi_landscape.png", // 480x320
    "android_hdpi_portrait": "resources/splashes/android_hdpi_portrait.png", // 480x800
    "android_hdpi_landscape": "resources/splashes/android_hdpi_landscape.png", // 800x480
    "android_xhdpi_portrait": "resources/splashes/android_xhdpi_portrait.png", // 720x1280
    "android_xhdpi_landscape": "resources/splashes/android_xhdpi_landscape.png", // 1280x720
    "android_xxhdpi_portrait": "resources/splashes/android_xxhdpi_portrait.png", // 1080x1440
    "android_xxhdpi_landscape": "resources/splashes/android_xxhdpi_landscape.png" // 1440x1080
});
```

Any help would be greatly appreciated.

**Comment by dagatsoin** [comment] 2016-08-08 09:17
I had the same today. I solved it by increasing the time because I use a S3mini and it is (very very) slow.
`App.setPreference("LoadUrlTimeoutValue", 1000000);`

My conf also has `App.setPreference("WebAppStartupTimeout",1000000);`

**Comment by jschlieber** [comment] 2016-08-09 07:57
@dagatsoin Thanks for the hint. I'll give it a try and post my results here, but won't have time before September...

**Comment by abernix** [comment] 2016-09-13 22:54
@jschlieber Is there a way you can bundle this into a bare-minimum reproduction GitHub repo and possibly reproduce it in an emulator?  Truthfully, I'm not sure there is much Meteor can do for this as it would seem to be a Cordova issue and something that would need to be resolved in the Cordova core (or within the responsible Cordova plugin).  Additionally, with such a specific environment (S3mini, etc.), its unlikely that it will get any attention as it won't be easy to reproduce and debug.

**Comment by jschlieber** [comment] 2016-09-14 07:31
@dagatsoin Increasing the timeout value from 70s to 100s and also using `App.setPreference("WebAppStartupTimeout", 100000);` solved the issue for me. Thank you.

@abernix Creating a bare-minimum reproduction repo fails. I suspect the issue is related to the size of the app.

Anyway, thanks for your help.

**Comment by abernix** [comment] 2016-10-25 08:41
Thanks for reporting back with the solution and for reporting the problem originally.

This does sound like an issue with the size of the app as the default `WebAppStartupTimeout` is 20 seconds, I believe.  If you continue to have problems with this, I believe it would be best to address it with the https://github.com/meteor/cordova-plugin-meteor-webapp/ module.

Closing this as the problem was reported resolved.

**Closed by abernix** 2016-10-25 08:41 UTC
Labels: can't-reproduce, Project:Mobile

**Comment by derwaldgeist** [comment] 2017-08-25 12:13
This problem just struck me after I updated from 1.2 to 1.5. It is been reported many times on the Meteor forums and seems to happen on devices that have a slow startup time.

The dialog that appears on error is very ugly, it appears multiple times, and after that the app crashes completely. This is a very bad user experience. It would be way better if Meteor just waited "forever" in this case. Setting a higher timeout seems to be quite arbitrary to me. It would be great if this could be re-opened and fixed.

**Comment by derwaldgeist** [comment] 2017-11-08 23:10
@jschlieber What do you mean by this?
> Increasing the timeout value from 70s to 100s

**Comment by dagatsoin** [comment] 2017-11-09 08:52
He talk about those settings I think https://github.com/meteor/meteor/issues/7560#issuecomment-238183591

**Comment by jschlieber** [comment] 2017-11-09 08:54
@dagatsoin yep

**Comment by derwaldgeist** [comment] 2017-11-09 09:56
@jschlieber Ah, ok, thanks. I just wasn't sure what you meant by `70s`, since there is by default no entry for this in the config file.

**Comment by jschlieber** [comment] 2017-11-09 10:10
@derwaldgeist yes, `70s` was my previous setting trying to resolve this issue, which didn't work. Increasing this value to `100s` solved it, although strangely the app never took close to `70s` before the described error message was displayed...
