### ISSUE TITLE
Running --production on windows duplicated file path

### ISSUE THREAD

**Issue by pedrofg** [meteor/meteor#9844] opened 2018-04-27 13:17 UTC
When running `meteor --production` on windows this happens:

```
[server]: TypeScript Files Compilation: 1339.427ms
[server]: HTML Files Compilation: 0.016ms    -
[server]: SCSS Files Compilation: 0.040ms    -
=> Errors prevented startup:

   While processing files with angular-compilers (for target web.browser):

   C:\Users\Pedro\AppData\Local\.meteor\packages\angular-compilers\0.3.1_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-scss-compiler\node_modules\node-sass\lib\index.js:439:16:
   File to read not found or unreadable:
   D:/GitProjects/kimayo-angular/D:/GitProjects/kimayo-angular/client/imports/app/search/search.component.scss
```

As you guys can see the path: `D:/GitProjects/kimayo-angular/` is being duplicated so it can not find the file. Anyone knows how to fix it?

**Comment by hwillson** [comment] 2018-05-02 12:02
This doesn't appear to be a Meteor core problem. It looks like an issue caused by the [`angular-compilers`](https://github.com/Urigo/angular-meteor/tree/ffa83ed1a01241161c6faecb6239582977a1cce7/atmosphere-packages/angular-compilers) package. You might want to try opening an issue for this in that repo. Closing here - thanks!

**Closed by hwillson** 2018-05-02 12:02 UTC
