### ISSUE TITLE
1.6-beta.1 Can't deploy from bundle (npm-rebuild.js)

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#8808] opened 2017-06-16 05:35 UTC
When `npm-rebuild.js` runs (on both OSX on my machine, and on an Ubuntu server), an error is thrown. It appears this could be a change or bug in Node itself because it works with `6.10.1` but not `7.3.0` or `8.1.2`.

I did notice that in [the following code](https://github.com/meteor/meteor/blob/19fdc5c65faa28834f26403fb6ad2d7984e2c1f4/tools/static-assets/server/npm-rebuild.js#L26-L31), env is always an empty object `{}` but this is true of all node versions I tested, so it seems redundant. Wondered if env was now overwriting the default `process.env` in Node 7+ leaving an empty path but even commenting out the `env: env` option passed to spawn doesn't help.
 
```js
// Make sure the npm finds this exact version of node in its $PATH.
var binDir = path.dirname(process.execPath);
var PATH = binDir + path.delimiter + process.env.PATH;
var env = Object.create(process.env, {
  PATH: { value: PATH }
});
```

Error:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

NPM log from server:

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> fibers@2.0.0 install /home/[redacted]]/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /home/[redacted]]/bundle/programs/server
> node npm-rebuild.js

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in: [redacted]
```

Relevant part of the complete log:
```
826 silly install runPostinstallTopLevelLifecycles
827 silly build meteor-dev-bundle@0.0.0
828 info linkStuff meteor-dev-bundle@0.0.0
829 silly linkStuff meteor-dev-bundle@0.0.0 has /home/[redacted]/bundle/programs as its parent node_modules
830 verbose linkBins meteor-dev-bundle@0.0.0
831 verbose linkMans meteor-dev-bundle@0.0.0
832 silly install meteor-dev-bundle@0.0.0
833 info lifecycle meteor-dev-bundle@0.0.0~install: meteor-dev-bundle@0.0.0
834 verbose lifecycle meteor-dev-bundle@0.0.0~install: unsafe-perm in lifecycle true
835 verbose lifecycle meteor-dev-bundle@0.0.0~install: PATH: /home/[redacted]/.nvm/versions/node/v8.1.2/lib/node_modules/npm/bin/node-gyp-bin:/home/[redacted]/bundle/programs/server/node_modules/.bin:/home/[redacted]/.rvm/gems/ruby-2.3.0/bin:/home/[redacted]/.rvm/gems/ruby-2.3.0@global/bin:/home/[redacted]/.rvm/rubies/ruby-2.3.0/bin:/home/[redacted]/.nvm/versions/node/v8.1.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/[redacted]/.rvm/bin
836 verbose lifecycle meteor-dev-bundle@0.0.0~install: CWD: /home/[redacted]/bundle/programs/server
837 silly lifecycle meteor-dev-bundle@0.0.0~install: Args: [ '-c', 'node npm-rebuild.js' ]
838 silly lifecycle meteor-dev-bundle@0.0.0~install: Returned: code: 1  signal: null
839 info lifecycle meteor-dev-bundle@0.0.0~install: Failed to exec install script
840 verbose stack Error: meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
840 verbose stack Exit status 1
840 verbose stack     at EventEmitter.<anonymous> (/home/[redacted]/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
840 verbose stack     at emitTwo (events.js:125:13)
840 verbose stack     at EventEmitter.emit (events.js:213:7)
840 verbose stack     at ChildProcess.<anonymous> (/home/[redacted]/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
840 verbose stack     at emitTwo (events.js:125:13)
840 verbose stack     at ChildProcess.emit (events.js:213:7)
840 verbose stack     at maybeClose (internal/child_process.js:897:16)
840 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
841 verbose pkgid meteor-dev-bundle@0.0.0
842 verbose cwd /home/[redacted]/bundle/programs/server
843 verbose Linux 4.9.15-x86_64-linode81
844 verbose argv "/home/[redacted]/.nvm/versions/node/v8.1.2/bin/node" "/home/[redacted]/.nvm/versions/node/v8.1.2/bin/npm" "install"
845 verbose node v8.1.2
846 verbose npm  v5.0.3
847 error code ELIFECYCLE
848 error errno 1
849 error meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
849 error Exit status 1
850 error Failed at the meteor-dev-bundle@0.0.0 install script.
850 error This is probably not a problem with npm. There is likely additional logging output above.
851 verbose exit [ 1, true ]
```

**Comment by mjmasn** [comment] 2017-06-16 05:43
Actually passing `env: process.env` to spawn _does_ work in Node 8, so it looks like an issue with that `Object.create`. Pretty sure that function is expecting a prototype not an object so not sure why it would have ever worked... 

Using `Object.assign` appears to work on my machine with Node 8.1.2:
```js
// Make sure the npm finds this exact version of node in its $PATH.
var binDir = path.dirname(process.execPath);
var PATH = binDir + path.delimiter + process.env.PATH;
var env = Object.assign(process.env, {
  PATH
});
```

**Comment by mjmasn** [comment] 2017-06-16 07:40
While the fix above does work to re-build the native dependencies without erroring, the app no longer runs.

- `node main.js` just exits instantly, no output or exit code
- Running with `pm2` and all the required env vars seems to keep the app running (not crashing/restarting or anything like that) but zero output and the app stays around to 50MB RAM mark (we usually see 150-200MB for a freshly restarted app). 

This seems separate to the original problem and may need its own issue though.

**Comment by abernix** [comment] 2017-06-16 08:15
This might have to do with your `npm` version (you have 5.0.3 installed).  What if you install `npm@4` instead of `npm@5`? (`npm install -g npm@4` should do the trick)

Why?  Meteor 1.6 is still [using `npm@4.6.1`](https://github.com/meteor/meteor/blob/6ca1b9877ed99245b3248f2d362a8fcbea209772/scripts/build-dev-bundle-common.sh#L10).  Work is still being made on migrating to npm 5 since it requires additional changes to support the new [`package-lock.json`](https://docs.npmjs.com/files/package-lock.json) file (which will be amazing when it's done due to reproducible builds and the increased speed they, and npm v5 in general, bring).

**Comment by mjmasn** [comment] 2017-06-16 08:37
@abernix nope, still get the ENOENT unless I apply my changes to `npm-rebuild.js`, and the app still fails to finish starting up.

Just to confirm Node/NPM versions:

```
36 silly install runPostinstallTopLevelLifecycles
37 silly build meteor-dev-bundle@0.0.0
38 info linkStuff meteor-dev-bundle@0.0.0
39 silly linkStuff meteor-dev-bundle@0.0.0 has /home/[redacted]/bundle/programs as its parent node_modules
40 verbose linkBins meteor-dev-bundle@0.0.0
41 verbose linkMans meteor-dev-bundle@0.0.0
42 silly install meteor-dev-bundle@0.0.0
43 info lifecycle meteor-dev-bundle@0.0.0~install: meteor-dev-bundle@0.0.0
44 verbose lifecycle meteor-dev-bundle@0.0.0~install: unsafe-perm in lifecycle true
45 verbose lifecycle meteor-dev-bundle@0.0.0~install: PATH: /home/[redacted]/.nvm/versions/node/v8.1.2/lib/node_modules/npm/bin/node-gyp-bin:/home/[redacted]/bundle/programs/server/node_modules/.bin:/home/[redacted]/.rvm/gems/ruby-2.3.0/bin:/home/[redacted]/.rvm/gems/ruby-2.3.0@global/bin:/home/[redacted]/.rvm/rubies/ruby-2.3.0/bin:/home/[redacted]/.nvm/versions/node/v8.1.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/[redacted]/.rvm/bin:/home/[redacted]/.rvm/bin
46 verbose lifecycle meteor-dev-bundle@0.0.0~install: CWD: /home/[redacted]/bundle/programs/server
47 silly lifecycle meteor-dev-bundle@0.0.0~install: Args: [ '-c', 'node npm-rebuild.js' ]
48 silly lifecycle meteor-dev-bundle@0.0.0~install: Returned: code: 1  signal: null
49 info lifecycle meteor-dev-bundle@0.0.0~install: Failed to exec install script
50 warn meteor-dev-bundle@0.0.0 No description
51 warn meteor-dev-bundle@0.0.0 No repository field.
52 warn meteor-dev-bundle@0.0.0 No license field.
53 verbose stack Error: meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
53 verbose stack Exit status 1
53 verbose stack     at EventEmitter.<anonymous> (/home/[redacted]/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
53 verbose stack     at emitTwo (events.js:125:13)
53 verbose stack     at EventEmitter.emit (events.js:213:7)
53 verbose stack     at ChildProcess.<anonymous> (/home/[redacted]/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
53 verbose stack     at emitTwo (events.js:125:13)
53 verbose stack     at ChildProcess.emit (events.js:213:7)
53 verbose stack     at maybeClose (internal/child_process.js:897:16)
53 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
54 verbose pkgid meteor-dev-bundle@0.0.0
55 verbose cwd /home/[redacted]/bundle/programs/server
56 verbose Linux 4.9.15-x86_64-linode81
57 verbose argv "/home/[redacted]/.nvm/versions/node/v8.1.2/bin/node" "/home/[redacted]/.nvm/versions/node/v8.1.2/bin/npm" "i"
58 verbose node v8.1.2
59 verbose npm  v4.6.1
60 error code ELIFECYCLE
61 error errno 1
62 error meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
62 error Exit status 1
63 error Failed at the meteor-dev-bundle@0.0.0 install script.
63 error This is probably not a problem with npm. There is likely additional logging output above.
64 verbose exit [ 1, true ]
```

**Comment by mjmasn** [comment] 2017-06-16 09:03
Same same on a brand new default app. Repro here: https://github.com/mjmasn/meteor-8808

**Comment by mjmasn** [comment] 2017-06-19 03:09
Added separate issue (#8817) for the immediate exit as it appears to be unrelated to the npm rebuild issue.

**Comment by benjamn** [comment] 2017-06-30 15:00
This should be fixed now, thanks to the commit referenced above. Thanks again for tracking down the root cause, @mjmasn!

**Closed by benjamn** 2017-06-30 15:00 UTC
