### ISSUE TITLE
Meteor returns a copy of the entire page instead of a 404

### ISSUE THREAD

**Issue by dtruel** [meteor/meteor#9027] opened 2017-08-21 01:51 UTC
Hello, and thanks for all your hard work on Meteor!

This affects all recent versions of meteor including 1.5

The basic bug is that Meteor returns the entire webapp for any and every nonexistent URL when no router such as iron router or flow router is used.   If I try to access a file like this:

```
localhost:3000/images/nonexistent_image.png
```
Meteor will return a copy of the *entire webapp* instead of a 404 like it should.  It does not make any sense whatsoever to return the entire webapp when someone requests a nonexistent png.  I understand that there was probably some rationale for this behavior, however, I can't imagine any scenario in which returning an entire webapp instead of a 404 for a missing png is appropriate.  It has been mentioned in the forums that one can avert this issue by using a router.  However, many applications don't need to use a meteor router.  In such cases it is undesirable to add a whole extra package simply for proper 404 behavior.

Meteor should return a 404 by default for nonexistent files.  If this is not accomplished, there should at least be a way to cause meteor to return 404s for nonexistent files.

**Comment by klaussner** [comment] 2017-08-21 07:28
> I can't imagine any scenario in which returning an entire webapp instead of a 404 for a missing png is appropriate.

All single-page application servers, including Meteor, have to return the page if a resource doesn't exist on the server. Otherwise, using a client-side router would be impossible. For example, if a user requests `http://example.com/route/to/something`, `/route/to/something` is probably not a file on the server, so only the client knows how to handle it. If the server would respond with 404, you wouldn't be able to navigate to this route directly.

**Comment by dtruel** [comment] 2017-08-21 10:18
@klaussner, I get that.  However, no frontend router is ever going to be using a route that ends in .png, and if it does it is probably a poor design choice.  So for some cases it makes sense, and for others (such as loading an image file), the default response doesn't seem to be the best.

2 possible solutions.  What do you think?

1. Allow turning off this functionality somehow
2. Check if the requested file has an extension.  If it doesn't return the app.  If it does, return 404.  When using client side routes, nobody uses extensions at the end (and they shouldn't).  So if it has an extension, that should be a queue to the server that they are requesting an actual file.

**Comment by klaussner** [comment] 2017-08-21 12:14
I think that Meteor (and the [`webapp`](https://github.com/meteor/meteor/tree/devel/packages/webapp) package in particular) shouldn't make assumptions about what client-side routes look like. You would have to maintain a long (and likely incomplete) list of file types because dots in the path can't be used to detect extensions. For example, `http://example.com/show.customer` is a valid route.

You can, however, implement the behavior you described as connect middleware:

```js
import { existsSync } from 'fs';
import path from 'path';
import url from 'url';

import { WebApp } from 'meteor/webapp';

const appDir = path.join(
  path.dirname(__meteor_bootstrap__.serverDir),
  'web.browser',
  'app'
);

WebApp.connectHandlers.use('/', (req, res, next) => {
  const fileName = url.parse(req.url).pathname;

  if (path.extname(fileName)) {
    const filePath = path.join(appDir, fileName);

    if (!existsSync(filePath)) {
      res.writeHead(404);
      res.end('404 :(');
    }
  }

  next();
});
```

The middleware checks if a requested file has an extension and responds with 404 if the file doesn't exist in the app's `public` folder.

**Comment by dtruel** [comment] 2017-08-22 13:17
Hm, you make a good point.  Thank you for the code, that is very helpful.  I don't think people will be using periods in routes much, and I have never seen it done before.  Normally they use slashes instead, and I think that makes more sense so as not to confuse with the domain periods.  However, I guess they could.

I wonder if the code above will have a performance penalty, checking for the existence of a file for each route of webapp.connect handlers. Do you think it will?

**Comment by klaussner** [comment] 2017-08-23 20:30
@dtruel You can avoid calling the `existsSync` function on every request by storing all file names in a `Set` (using [`fs.readdirSync`](https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options)) when the server starts because the files won't change while the server is running. Then you can check if the file exists by looking up `fileName` in the set.

**Comment by klaussner** [comment] 2017-08-31 11:50
Closing this issue because it's not a bug in Meteor.

Regarding the code I posted above: I'm using the undocumented `__meteor_bootstrap__` variable to get the path of the public directory. If you think that there should be an official API for accessing such metadata about the app, please open a [feature request](https://github.com/meteor/meteor-feature-requests). Thanks! 🙂

**Closed by klaussner** 2017-08-31 11:50 UTC

**Comment by dtruel** [comment] 2017-08-31 13:51
Ok, I will probably post a feature request.  Thanks for your time and help @klaussner
