### ISSUE TITLE
Warn CoffeeScript users to add`modules` to use modules

### ISSUE THREAD

**Issue by abernix** [meteor/meteor#8115] opened 2016-11-30 12:23 UTC
This issue came up in discussion about meteor/docs#106 and about whether [`modules`](https://atmospherejs.com/meteor/modules) could be implied safely and automatically when users used [`coffeescript`](https://atmospherejs.com/meteor/coffeescript).  The answer is: not really.

Explained succinctly by @benjamn:
> the use of (Meteor) `modules` introduces the `require`, `export`, and `module` variables into your code, which can confuse libraries that detect whether they're being loaded as modules. Instead, I think developers should have to `meteor add modules` if they want to use `import` declarations in CoffeeScript, for now.

This issue is intended to try to provide that advice automatically.  Something along the lines of:

> Hey, you've attempted to use modules in your CoffeeScript .  Since this could potentially cause unexpected results, you need to `meteor add modules` if if this is what you're intending to do.  See an explanation here http://guide.meteor.example.com/...

/cc @lorensr
/cc @GeoffreyBooth (fyi)

**Comment by GeoffreyBooth** [comment] 2016-12-04 22:48
> the use of (Meteor) `modules` introduces the `require`, `export`, and `module` variables into your code, which can confuse libraries that detect whether they’re being loaded as modules.

I’m not sure I understand this. First, I assume @benjamn meant `exports`, as `export` has always been a reserved word in both JavaScript and CoffeeScript. But leaving that aside, is there an example that you can point to that demonstrates this problem?

I tried to reproduce it via the following:
```sh
meteor create --bare test
cd test
meteor npm install
meteor remove ecmascript
mkdir server
echo "console.log require 'fs'" > server/main.coffee
meteor add coffeescript # Installs 1.11.1_4
meteor npm install
meteor
# Fails to start, instructs to run meteor npm install --save babel-runtime
meteor npm install --save babel-runtime
meteor
# Fails to start, says ReferenceError: require is not defined
```

So is the case where this is an issue where someone writes code along the lines of `if require?` to check if we’re in a CommonJS environment? But that would have to be in user-written code; if you’re importing a library, presumably you’ve added `modules`, so that you can `require` or `import` that library.

There’s always the case where people add a library by simply saving a file into the project, and don’t follow directions by putting it in `client/compatibility`, so I guess in _that_ circumstance such a library could be confused. Is that what you’re talking about?

**Comment by benjamn** [comment] 2016-12-05 17:37
Consider an existing package that depends on `coffeescript` but does not use `ecmascript` or `modules`, and its `package.js` file calls `api.addFiles("library.js", ...)` where `library.js` is a library that tries to detect if it's in a CommonJS environment by testing `typeof exports === "module"` (or similar). A good example of this pattern is [jQuery](https://github.com/jquery/jquery/blob/7fbab88110725c6e0b89f6513b9f7cff50320e1e/src/wrapper.js#L19). If `library.js` thinks it's in a CommonJS module, it exports things via `exports`, otherwise it assigns to global variables (which is what the package expects it to do).

Now, if the package upgrades to a version of `coffeescript` that implies `modules`, `library.js` will think it's in a CommonJS module (which is true), but the package will still be expecting `library.js` to assign its exports to global (i.e. package-scoped) variables. This breaks the package.

**Comment by hwillson** [comment] 2017-06-09 15:27
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Warn%20CoffeeScript%20users%20to%20add%60modules%60%20to%20use%20modules&body=Migrated%20from:%20meteor/meteor%238115) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-09 15:27 UTC
Labels: feature
