### ISSUE TITLE
Minimongo/Mongo  element addition through method triggers two updates and ugly flicker (minimongo bug)

### ISSUE THREAD

**Issue by santiagopuentep** [meteor/meteor#4624] opened 2015-06-25 05:52 UTC
Adding an element to an array attached to an each tag in Blaze using a method like:

    ItemsList.update(parentId, {$push:{children: {$each: [{text: "********"}], $position: 1}}});

creates a very ugly flicker because the array gets updated first with the item at the end of the array and then in the correct position.

The DDP log shows a single update with the array in the correct order.

Example:

```
// this array is rendered with an Blaze/Spacebars each statement
[a, b, c]
// after calling the method to add the text "********" at index 1, the output is:
[a,b,c,**************]
[a,**************,b,c]
// this creates a very ugly flicker
```

This is the full code of the simplified program:

```
<head>
  <title>ReactivityBugTest</title>
</head>

<body>
	<h3>Click the button to add a child.</h3>
	<p>See it flicker at the end of the list.</p>
	<p>Check the output to see the reactivity.</p>
	{{> root}}
</body>

<template name="root">
	{{#with root}}
		<button type="button" class="reset">Reset</button>
		<button type="button" class="addChild">Add child at position 1</button>
		<div class="itemContainer">
			{{#each getChildren}}
				<div>{{text}}</div>
			{{/each}}
		</div>
	{{/with}}
</template>
```

```
MyCollection = new Mongo.Collection("items");

if (Meteor.isClient) {
	Template.root.helpers({
		root: function () {
			return MyCollection.findOne('root');;
		},
		getChildren: function () {
			//*****************
			// logs the children every time blaze asks for them
			var output = "chidren:[";
			for	(var i = 0; i < this.children.length; i++) {
				output += this.children[i].text;
				
				if (i < this.children.length - 1) {
					output += ",";
				}
			}
			output += "]";
			console.log(output);
			//*****************
			
			return this.children;
		}
	});
	  
	Template.root.events({
		'click .addChild': function (e) {
			Meteor.call('addRandomChild', 'root', 1);
			e.stopPropagation();
		},
		'click .reset': function (e) {
			Meteor.call('reset');
			e.stopPropagation();
		}
	});
}

Meteor.methods({
	addRandomChild: function(parentId, positionIndex) {
		MyCollection.update(parentId, {$push:{children: {$each: [{text: "**************"}], $position: positionIndex}}});
	},
	reset: function () {
		MyCollection.remove({});
		
		MyCollection.insert({ _id:'root', text: "root", children: [
			{text: "a"},
			{text: "b"},
			{text: "c"}
		]});
	}
});

if (Meteor.isServer) {
	Meteor.startup(function () {
		Meteor.call('reset');
	});
}
```

**Comment by santiagopuentep** [comment] 2015-06-25 14:44
The problem may be missing support for $position argument for $push modifier in minimongo, as Rob Fallows pointed out in this post:

https://forums.meteor.com/t/reactivity-problem-when-adding-an-element-to-an-array-in-a-document/6001/4

**Comment by stubailo** [comment] 2015-06-30 21:21
I think this is a duplicate of https://github.com/meteor/meteor/issues/4158

That fix should come out in a future Meteor release. Thanks for reporting the UI problems that arise from this bug.

**Closed by stubailo** 2015-06-30 21:21 UTC
