### ISSUE TITLE
Second subscription to a collection falters when first subscription query has undefined field

### ISSUE THREAD

**Issue by sbalmer** [meteor/meteor#5097] opened 2015-09-02 22:46 UTC
We found this edge case where a subscription gets no documents because another subscription used an undefined field in the query. The found it in 1.1, and it persist in 1.2 RC.

Because it was actually an error in our code that caused the failure, we're not too stressed about it. We fixed our part.  It was pretty hard to pin down, and I still wonder what the root cause may be.

``` js
Thingies = new Meteor.Collection("Thingies");

if (Meteor.isClient) {
  // if we omit subscription to firstSub, it works
  Meteor.subscribe('firstSub');
  Meteor.subscribe('secondSub');

  Tracker.autorun(function() {
    console.log("I have " + Thingies.find().count() + " thingies!");
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    // if the tag field is omitted, it works
    if (Thingies.find().count() < 1) Thingies.insert({ tag: "lubricated" });
  });

  // if either of the queries look for any tag string, it works
  Meteor.publish('firstSub', function() { return Thingies.find({ tag: undefined }); });
  Meteor.publish('secondSub', function() { return Thingies.find(); });
}
```

Expected outcome:

```
"I have 0 thingies!"
"I have 1 thingies!"
```

Actual outcome

```
"I have 0 thingies!"
```

**Comment by avital** [comment] 2015-09-08 21:13
Hmm. I literally copied and pasted your code into a fresh app running Meteor 1.1.0.3 and ran it both in Chrome and Firefox and saw:

```
I have 0 thingies!
I have 1 thingies!
```

Are you sure this is the repro? If so, which browser are OS are you using? If it's actually something where the app behaves differently on your and my environment that would be interesting...

**Comment by sbalmer** [comment] 2015-09-23 22:55
I tried again with a new project and no repro! Then I did

    meteor remove autopublish

And now it's stuck at "0 thingies" again. Sorry I forgot about the autopublish.

I ran it with METEOR@1.2.0.1, on Debian 8.1.0 Jessie amd64, Firefox (Iceweasel) 31.8.0.

**Comment by abernix** [comment] 2016-11-25 19:35
I've packaged this into a repo with Meteor 1.4.2.3: https://github.com/abernix/meteor-issue-5097 which shows the issue you're speaking about.

I didn't have time to investigate further, but I am bit perturbed by it – though I feel like there must be a simple answer that I'm missing at the moment.  

Thanks for reporting this and providing the reproduction.  Hopefully someone can look further soon.

**Comment by hwillson** [comment] 2016-12-08 16:28
Hi @sbalmer - this is currently working as designed. I'll try to explain why below (sorry the long response!).

## The Why

To first help explain this, please see the Guide's [Subscription lifecycle](https://guide.meteor.com/data-loading.html#lifecycle) section, in particular item #4:

> 4) The server sets up a query observer on that cursor, **unless such an observer already exists on the server (for any user), in which case that observer is re-used.**

(important part in bold)

Looking at your first publish handler,

```js
Meteor.publish('firstSub', function () { 
  return Thingies.find({ tag: undefined }); 
});
```

when this handler is fired, behind the scenes an observer is setup and stored. This observer is then referenced internally by a defined [`observeKey`](https://github.com/meteor/meteor/blob/cf4133c7632137d870136f02100622aa7e8fcd95/packages/mongo/mongo_driver.js#L1191). This `observeKey` is created as follows:

```js
var observeKey = JSON.stringify(
    _.extend({ordered: ordered}, cursorDescription));
```    

The `cursorDescription` representation of the cursor setup in your `firstSub` publication looks like:

```js
{ 
  collectionName: 'Thingies',
  selector: { tag: undefined },
  options: { transform: null } 
}
```

When this is `JSON.stringify`'d, `undefined` is stripped since it's not valid JSON. So that means the `observeKey` is assigned a value that looks like:

```js
{
  "ordered": false,
  "collectionName": "Thingies",
  "selector": {},
  "options": {
    "transform": null
  }
}
```

Note that the `{ tag: undefined }` portion has been stripped out.

Now when your second publish function

```js
Meteor.publish('secondSub', function () {
  const results = Thingies.find();
  console.log("secondSub returned %d", results.count())
  return results;
});
```

attempts to setup a query observer for its cursor, an internal `observeKey` is first generated using a `curosrDescription` of:

```js
{ 
  collectionName: 'Thingies',
  selector: {},
  options: { transform: null } 
}
```

which when `JSON.stringify`'d looks like:

```js
{
  "ordered": false,
  "collectionName": "Thingies",
  "selector": {},
  "options": {
    "transform": null
  }
}
```

This is an exact match of the first cursor's `observeKey`, so instead of setting up a new query observer, the first one is returned, which is why you only see the `I have 0 thingies!` message.

## The Solution

Well, not using `undefined` like this would help. Actually, Mongo doesn't support comparing to `undefined` anyways, so this would fail with Mongo regardless. I guess a patch could be applied to Meteor's Mongo driver, maybe within the [`MongoConnection.prototype._observeChanges`](https://github.com/meteor/meteor/blob/cf4133c7632137d870136f02100622aa7e8fcd95/packages/mongo/mongo_driver.js#L1175) function, to replace `undefined` with say `null` before generating the `observeKey` (since `null` is JSON supported). This might cause strange behavior in existing applications however, since this change could lead to unexpected query observers being created. I think for now maybe just documenting that this happens somewhere (maybe here is enough?) so people are aware that this could happen, would be a good first step.

**Comment by hwillson** [comment] 2016-12-12 20:55
Since this functions as designed, I'll close this off. Thanks!

**Closed by hwillson** 2016-12-12 20:55 UTC
Labels: bug, confirmed, Impact:few, Project:DDP

**Comment by sbalmer** [comment] 2016-12-12 21:01
Wow, thanks @hwillson for the thorough examination. I agree with closing it, my curiosity is satisfied :-)

I just read up on `undefined` in mongo and am somewhat shell-shocked now. Instead of coercing `undefined` to `null` which I agree is not a solution, I think throwing an error, or having a strict mode that throws errors in such cases would be nice. No priority though.

**Comment by abernix** [comment] 2016-12-13 10:31
Thanks for the followthrough and great explanation, @hwillson.  I think for now this works as documentation and if this recurs as a trend (it has not, from what I've seen) then building in some additional checking might be reasonable.

**Comment by hwillson** [comment] 2016-12-13 18:33
Just a quick note for reference - I just stumbled across #819 that outlines this exact issue as well. Given that #819 was opened in 2013 with very little traction, I think it's still safe to keep this issue closed (since it can be re-visited later if needed).
