### ISSUE TITLE
Connecting to production Meteor Mongo does not work 

### ISSUE THREAD

**Issue by maxko87** [meteor/meteor#3487] opened 2015-01-16 20:37 UTC
```
$ meteor mongo myapp
Couldn't open a mongo connection: Service temporarily unavailable. Please try again later.
```

This has happened intermittently before, but has been ongoing for over an hour today. Any reason for the outage?

**Comment by justinsb** [comment] 2015-01-16 21:23
Confirmed.  We're looking into it...

**Comment by justinsb** [comment] 2015-01-16 22:33
This should now be fixed.  Sorry for the service interruption.

I'm going to close this issue, but please do reopen if it isn't fixed for you (or if it happens again in future!)

**Closed by justinsb** 2015-01-16 22:33 UTC

**Comment by arturcarvalho** [comment] 2015-05-08 06:45
Hi Justin,

I'm having the same issue for the last hour. The DB seems to be working correctly but I cannot connect. Same reason for the outage?

**Comment by cleor41** [comment] 2016-01-20 10:58
This has been happening to me for for almost a day now. Anyone else have the same problem?

**Comment by draperunner** [comment] 2016-01-25 03:06
I am having the same problem. I have not been able connect to db the last couple of days. And the website usually has the "This site is loading" error.
