### ISSUE TITLE
Corner cases in printing exceptions

### ISSUE THREAD

**Issue by awwx** [meteor/meteor#1211] opened 2013-07-08 23:46 UTC
Recently I had been commenting in a couple places about `err.stack` (which breaks if null or undefined is thrown, and so it's good to have a test like `err && err.stack`), but I also just remembered that even if the exception is an error, not all errors have a stack in all browsers... so it's good to alternatively get the error message if that's available; or to at least stringify the exception value itself if nothing else is available.  So I thought it might be a good idea to open an issue to get all the corner cases in one place...

* In JavaScript one can throw non-Error values such as strings, null, undefined, etc., so we need to avoid assuming that the error is an object or that it has useful fields.  (If the object doesn't have useful fields, such a string, it's nice to print the object itself so the user sees something).

* Even when the thrown value is an error, not all errors in all browsers have a stack field: the W3C spec for HTML requires that DOM errors do not include any fields besides the ones in the spec which doesn't include the stack; some browsers like Firefox follow the spec and don't include the stack field in DOM errors and others like Chrome go against the spec on this point and do include the stack in DOM errors.

For example, this doesn't print anything in Firefox:

```
try {
  document.createTextNode('').splitText(-1);
} catch (e) {
  console.log(e.stack);
}
```

I think this may cover all the cases:

`"" + (err && (err.stack || err.message || err))`

The `err &&` test checks that `err` is an object and so won't throw when accessing the fields while still preserving the information of whether the thrown value is `null` or `undefined`; and it falls back to stringifying the value itself if it doesn't have useful stack or message fields.

It might be nice to have a helper called `Meteor._stringifyError` or something that could be used uniformly.

Here are the places I've noticed that look like they'll break if a null or undefined exception is thrown and/or won't display something useful if the error doesn't have a stack and/or message field...

Deps:
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/deps/deps.js#L145
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/deps/deps.js#L234

_wrapAsync:
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/meteor/helpers.js#L81

timers:
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/meteor/timers.js#L14

fibers:
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/meteor/fiber_stubs_client.js#L37
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/meteor/fiber_helpers.js#L75

livedata:
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/livedata/livedata_server.js#L1069
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/livedata/livedata_server.js#L1251
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/livedata/livedata_connection.js#L605
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/livedata/livedata_connection.js#L692
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/livedata/crossbar.js#L56

webapp:
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/webapp/webapp_server.js#L370

mongo:
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/mongo-livedata/mongo_driver.js#L207

tinytest:
https://github.com/meteor/meteor/blob/9495307fd86da98c2348a67d93bd9bb03977d65b/packages/tinytest/tinytest.js#L415

**Comment by MattiSG** [comment] 2015-01-05 16:24
The way meteor handles client side exceptions is as unreasonable with Safari. The stack is not as huge as in FF and is clickable, but links lead to useless parts of the code and, most importantly, the original error message is not listed.

Safari:
![safari](https://cloud.githubusercontent.com/assets/222463/5615877/98dee8ac-94ff-11e4-9516-52f68e3293fd.png)

vs Chrome:
![chrome](https://cloud.githubusercontent.com/assets/222463/5615881/a4d4474c-94ff-11e4-85a1-01dbad738def.png)

**Comment by glasser** [comment] 2015-01-05 17:15
As suggested, I will close this as a duplicate of #2232, which has a better name than this one. My statement there about pull requests still stands.

**Closed by glasser** 2015-01-05 17:15 UTC
