### ISSUE TITLE
meteor-angular2 Cannot find module

### ISSUE THREAD

**Issue by PopPushOut** [meteor/meteor#8248] opened 2017-01-12 16:07 UTC
Good evening,

Past few days I was moving https://github.com/akveo/ng2-admin template on meteor base.
This might be useful for all meteor fans at some stage in their career, quite cool template.
 I skip some .ts and many packages that I do no need, like webpack and electron. After fixing compiler errors I launched the project.
Here is the console:
![image](https://cloud.githubusercontent.com/assets/23708256/21894033/67f10888-d8e6-11e6-809f-0e42c29dfaf3.png)
But then I inspect my project in web browser I get these errors:
![image](https://cloud.githubusercontent.com/assets/23708256/21894076/8b0baabc-d8e6-11e6-8281-9d6613946687.png)

What I tried:
1. Read in forums that might be meteor problems with cache, deleted it from .meteor/local.
2. Rechecked the imports and exports of cystom-typings.ts.

It seems okay, although I am not very familiar with typescript and moving big projects on another base.
I would be glad if you guys can run my project and check what could be done.
My Project git URL:
https://github.com/PopPushOut/Meteor-angular-ng2-akveo

to run the project: 
1. run - meteor npm install(to install all the packages).
2. run - meteor(launch the project).

Extra information:
Current node version I use: 6.9.1 and npm version: 3.10.9
Info about template structure to navigate faster:
https://akveo.github.io/ng2-admin/articles/012-project-structure/
This is original template made with angular2 CLI.

My project doesn't use all folders for example:
config( I do not use electron and webpack to make it easier), tslint.ts, typedoc and environment.ts everything else should be used.

If you need something else, please contact me any time.
Thank you!

**Comment by DerekTBrown** [comment] 2017-01-14 23:28
I think the problem is stemming from the fact that you tried to remove webpack.  This project seems pretty heavily dependent on it.  I think that is where the error is coming from- you have stopped webpack from importing the needed modules.

**Comment by laosb** [comment] 2017-01-16 08:41
That's doesn't sound like a bug of Meteor itself. You should post this to meteor-angular2. Closing.

**Closed by laosb** 2017-01-16 08:41 UTC
