### ISSUE TITLE
With 2.6+, DDP methods stop returning in some cases when server is connected to Oplog

### ISSUE THREAD

**Issue by perbergland** [meteor/meteor#11946] opened 2022-02-25 10:18 UTC
Tested with meteor 2.5.5, 2.6 and 2.6.1

This only happens in one of our production instance that runs mongodb 4.2.8 (not in our staging environment that has the same version) and also not in our other production instance that runs mongodb 4.4 on Atlas

What happens is that for some operations, the method invocation never returns. If we don’t provide a MONGO_OPLOG_URL, the problem does NOT appear.

![image](https://user-images.githubusercontent.com/2690254/155697407-64a5ef03-bf13-476d-ba35-a6e851e6f476.png)

We can reproduce this locally too after tunneling in to our mongodb production instance. Our method implementation does return and this does NOT happen with meteor 2.5.x so I suspect there is a driver change issue somewhere deep within meteor.

Unfortunately not easy to repro…

**Comment by perbergland** [comment] 2022-02-25 10:24
update: 2.5.6 also works fine

**Comment by bcluyse** [comment] 2022-02-28 09:14
In the Meteor 2.6 upgrade, the node mongo driver package was bumped to 4.3.1.
MongoDB 2.2.8 version has not been compatible with for a long time.
You can correct me if I am wrong but I dont think this use case is supported at all.

https://docs.mongodb.com/drivers/node/current/compatibility/

**Comment by perbergland** [comment] 2022-02-28 09:44
ooops typo (fixed) should have been 4.2.8

**Comment by perbergland** [comment] 2022-06-08 17:44
After upgrading to mongodb community edition 4.4, this problem disappeared

**Comment by radekmie** [comment] 2022-08-28 11:45
Can we close it, as the problem is no longer there (in 4.4) and it's unclear on how to reproduce it?

**Closed** 2022-08-28 11:51 UTC
