### ISSUE TITLE
Mongo.setConnectionOptions must run before packages that declare Mongo collections are loaded

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#7455] opened 2016-07-22 18:33 UTC
When using one or more packages that declare a Mongo collection (for example accounts-base), it isn't possible to call Mongo.setConnectionOptions in the main app code or imports directory. The only workaround is to create a new local package containing the configuration and place it above `accounts-base` in the packages file.

It would be good to have to option to put the settings in settings.json somehow although I'm not sure how that would work with importing PEM files (e.g. the sslCA option).

**Comment by abernix** [comment] 2016-07-25 05:28
Thanks for filing this issue.

Marking as confirmed bug because after thinking about it/discussing in forums, I'm sure this is true.

https://forums.meteor.com/t/meteor-with-the-new-mongodb-3-2-1-compose-io/17763/11

The work around is to use a package that `use`'s `mongo` and to call `Mongo.setConnectionOptions` from that package.  In your project `packages` list, this package should be above any package which uses a `Mongo.Collection`.

**Comment by hwillson** [comment] 2018-01-10 18:20
For now we're going to document this limitation and workaround (see https://github.com/meteor/docs/issues/173), instead of addressing this in the codebase. Thanks!

**Closed by hwillson** 2018-01-10 18:20 UTC
Labels: Impact:few, Project:Mongo Driver, Severity:blocks-development, bug, confirmed
