### ISSUE TITLE
meteor update runs, but does no update

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#3630] opened 2015-02-03 16:41 UTC
This problem occurs for my second project now. Whenever the project gets a little bigger and uses many packages. There is a point when calling "meteor update" has no effect. It runs through and tells me "upgrading X, upgrading Y" like if it is working, but nothing happens. When I call "meteor list" the packages are not updated. When I rerun "update" it tells me again "upgrading X, upgrading Y".

So far I had to recreate the project from scratch, add every single package manually again and then it worked. However, this is very annoying. 

See below the packages of said project:

```
accounts-base                        1.1.3  A user account system
accounts-password                    1.0.6  Password support for accounts
aldeed:autoform                      4.2.2  Easily create forms with automatic insert...
aldeed:collection2                   2.3.1  Automatic validation of insert and update...
cfs:gridfs                           0.0.27  GridFS storage adapter for CollectionFS
cfs:standard-packages                0.5.3  Filesystem for Meteor, collectionFS
chrismbeckett:fontawesome4           4.2.2  Scalable vector icons that can be customi...
coffeescript                         1.0.5  Javascript dialect with fewer braces and ...
cryptoquick:stylus-multi             1.2.0  Stylus, packaged with Nib, Jeet, Rupture,...
email                                1.0.5  Send email messages
fastclick                            1.0.2  Faster touch events on mobile
fezvrasta:bootstrap-material-design  0.2.1  FezVrasta's Bootstrap theme implementing ...
iron:router                          1.0.7  Routing specifically designed for Meteor
manuelschoebel:ms-seo                0.4.1  Easily config SEO for your routes
meteor-platform                      1.2.1  Include a standard set of Meteor packages...
meteorhacks:npm                      1.2.2  Use npm modules with your Meteor App
meteorhacks:ssr                      2.1.2  Server Side Rendering for Meteor with Blaze
meteorhacks:unblock                  1.1.0  a way to use this.unblock inside publicat...
miro:mailchimp                       1.0.4  A Meteor wrapper for MailChimp API
mizzao:bootboxjs                     4.3.0  Programmatic dialog boxes using Twitter's...
momentjs:moment                      2.9.0  Moment.js (official): parse, validate, ma...
npm-container                        1.0.0+ Contains all your npm dependencies
raix:handlebar-helpers               0.2.4  Handlebar helpers
softwarerero:accounts-t9n            1.0.5* Translations for the meteor account's err...
spiderable                           1.0.6  Makes the application crawlable to web sp...
tap:i18n                             1.3.2  A comprehensive internationalization solu...
tap:i18n-ui                          0.4.1  User interface for the tap-i18n package
twbs:bootstrap                       3.3.1_2* Bootstrap (official): the most popular ...
underscore                           1.0.2  Collection of small helpers: _.map, _.eac...
useraccounts:bootstrap               1.5.0* Accounts Templates styled for Twitter Boo...
vazco:maps                           0.0.1  Google Maps wrapper with gmaps.js plugin
yogiben:admin                        1.0.9* A complete admin dashboard solution
yogiben:autoform-file                0.1.7* U
```

**Comment by glasser** [comment] 2015-02-03 22:19
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

(CC @ekatek @dgreensp )

**Comment by obiwarn** [comment] 2015-02-04 10:51
Sorry, this is not possible in this case.

Found a workaround:

- Create a new meteor project
- Add packages & versions from the old project 
- update (works great)

Now if I go back to my old project, it also updates perfectly. So this must be some sort of "Meteor cache" bug?

**Comment by obiwarn** [comment] 2015-02-10 13:45
OK. To reproduce:

meteor add npm-container

add following packages.json File:

{
  "braintree": "1.22.0"
}


Result: Update of any other package works, but has no effect (without showing any error).

**Comment by glasser** [comment] 2015-02-10 16:39
Can you be really really specific? Like, not "update of any other package" but actually provide step by step instructions with specific packages and versions?

**Comment by glasser** [comment] 2015-05-26 21:16
Closing due to lack of specific reproduction; Version Solver was rewritten in 1.1 since then and this issue does not give enough information to be able to figure out if the issue was fixed or not.

**Closed by glasser** 2015-05-26 21:16 UTC
Labels: Project:Tool, Project:Version Solver
