### ISSUE TITLE
Meteor android CORS problem...

### ISSUE THREAD

**Issue by jh222xk** [meteor/meteor#3469] opened 2015-01-12 19:43 UTC
Hey!

I have built my application for Android running it like this; `ROOT_URL=http://domain.com meteor build ~/build-output-directory/ --server=http://domain.com`

Then I located to ~/build-output-directory/android/ and ran; `jarsigner -digestalg SHA1 unaligned.apk appname` then; `~/.meteor/android_bundle/android-sdk/build-tools/20.0.0/zipalign 4 unaligned.apk production.apk``

Then I located to ~/.meteor/android_bundle/android-sdk/platform-tools/ and ran: `./adb install ~/build-output-directory/android/production.apk`

All this results in; `(android:http://meteor.local/:0) XMLHttpRequest cannot load http://domain.com/sockjs/info?cb=mb48b4056b. Origin http://meteor.local is not allowed by Access-Control-Allow-Origin.`

I have the app published on a site as well running on http://domain.com which works fine... So why is it setting the url to http://meteor.local and makes this CORS fail?

Latest version of Meteor running.

**Comment by davidyaha** [comment] 2015-01-12 21:02
+1

**Comment by glasser** [comment] 2015-01-14 04:26
@Slava is this related to the thing where you were trying to change the headers?

**Comment by Slava** [comment] 2015-01-14 04:31
@glasser no, it does not look related.

**Comment by Kestanous** [comment] 2015-01-18 21:21
+1

**Comment by Lenin7** [comment] 2015-03-25 14:25
Any updates on this? I can't seem to be able to upload any files in Cordova.
Origin http://meteor.local is not allowed by Access-Control-Allow-Origin.

**Comment by arjunrao87** [comment] 2015-03-26 04:11
I am facing the same issue.

**Comment by djules75** [comment] 2015-03-28 12:27
+1, facing the same issue after updating to 1.0.4.2 with my Cordova build.
Using chrome webview debugger, this is the console error log:

XMLHttpRequest cannot load http://<my app server address>/sockjs/info?cb=ieu7ixlas4. Origin http://meteor.local is not allowed by Access-Control-Allow-Origin. myappname:1
METEOR CORDOVA DEBUG (autoupdate_cordova.js) cordova.file.dataDirectory is null, retrying in 20ms

**Comment by djules75** [comment] 2015-03-28 16:27
The problem was that I was deploying my app with mup using the server IP in the mup.json config file (ROOT_URL) and building the mobile app with the server url.
I changed the ROOT_URL to the server url instead of the IP address and now everything is working smoothly.

**Comment by jms301** [comment] 2015-04-01 12:29
I have this problem if I do: 

meteor run android --mobile-site <live site url> 

I think it looks like whatever is serving the meteor.local files is not giving CORS headers for the live site to the browser in the emulator? Certainly setting CORS headers for meteor.local in the live site does not fix the problem.

**Comment by glasser** [comment] 2015-04-01 17:54
This is supposed to work:

```

  // If the remote server domain is known, allow access to it for xhr and DDP
  // connections.
  if (serverDomain) {
    accessRules['*://' + serverDomain + '/*'] = true;
    // Android talks to localhost over 10.0.2.2. This config file is used for
    // multiple platforms, so any time that we say the server is on localhost we
    // should also say it is on 10.0.2.2.
    if (serverDomain === 'localhost') {
      accessRules['*://10.0.2.2/*'] = true;
    }
  }
```

**Comment by settinghead** [comment] 2015-04-01 20:32
+1

**Comment by settinghead** [comment] 2015-04-01 20:37
Not sure if this is the same issue, but my app has two DDP connections open (one that comes with the app and another one that connects to a different server). Everything runs fine until I got the same CORS error on Android mobile app.

**Comment by Igor1201** [comment] 2015-04-03 01:38
+1
Same issue here

**Comment by Igor1201** [comment] 2015-04-03 02:06
For those with this problem recently, it might be a security change that happened on Meteor.

Check: http://docs.meteor.com/#/full/App-accessRule

> Starting with Meteor 1.0.4 access rule for all domains and protocols (\<access origin="*"/\>) is no longer set by default due to certain kind of possible attacks.

So, a simple `App.accessRule("*");` (or, of course, something like `App.accessRule("*://myserver.com/*");`) on `mobile-config.js` fixes this issue for me.

**Comment by MichaelFBA** [comment] 2015-04-03 11:50
@djules75
Did you find a way around this issue? I've tried the access rules as mentioned above.
I'm experiencing the same issue with trying to uploading an mp4 file to the youtube api.

**Comment by nukeu666** [comment] 2015-04-05 19:58
Not sure if it's your question but I had a similar error and got it working after wrapping the call in a  if(Meteor.isServer) block

**Comment by jms301** [comment] 2015-04-08 13:54
My version of this problem was another badly configured ROOT_URL variable on the meteor server.

**Comment by PolGuixe** [comment] 2015-04-12 14:09
I have the same problem with Android and iOS? Any solution?

**Comment by kevohagan** [comment] 2015-04-13 09:59
+1 on this

**Comment by linhkurt** [comment] 2015-04-16 10:21
Thanks @Igor1201, adding <code>App.accessRule("*");</code> in <code> mobile-config.js</code> did the trick.

**Comment by PolGuixe** [comment] 2015-04-16 18:18
I have tried @Igor1201 solution and it works for me. ;)

**Comment by Anwain** [comment] 2015-05-19 08:06
+1 on this @Igor1201's solution hasn't worked for me

**Comment by Lenin7** [comment] 2015-05-19 19:05
After a lot of testing, It seems like CORS does not work on androids older than 4.4(KitKat). 
Android Platform Versions I tested this on: 4.1.x, 4.4, 5.0 .
If anyone could verify that this is indeed the issue, that would be great.
Thanks.

**Comment by Slava** [comment] 2015-05-22 01:06
I commented on the similar issue here: https://github.com/meteor/meteor/issues/4132

I also posted a possible workaround there.

Closing this as a dup of https://github.com/meteor/meteor/issues/4132.

**Closed by Slava** 2015-05-22 01:06 UTC
Labels: Project:Mobile

**Comment by gumkins** [comment] 2015-06-02 16:21
I can't fix the issue with any of described solutions with Meteor 1.1.0.2. Solutions I tried:
- `App.accessRule("*");` in  `mobile-config.js` (I can see appropriate rule appears in `.meteor/local/cordova-build/config.xml`). I also tried to specify special domain in rules.
- Add browser-policy package and put `BrowserPolicy.content.allowOriginForAll("http://meteor.local");` call inside `Meteor.startup` block. 

Some man mentioned this hack (in #4132)
> My understanding is, it can be solved by setting a response header in Meteor's "on-device" server: https://github.com/meteor/com.meteor.cordova-update/blob/master/src/ios/METEORCordovaURLProtocol.m#L57

I don't know what language it is written on and where it must be modified and possibly compiled somehow. 

Meteor motto is "Discover the easiest way to build amazing web and mobile apps in JavaScript". So I don't think we should learn new technologies it uses inside just to force it working in a way we need.
Should we?

**Comment by Slava** [comment] 2015-06-02 18:45
Alexander,

I believe you would need to learn things like CORS headers and how they
work if you want to build anything for the web. Regardless of the framework
you use.

On Tue, Jun 2, 2015 at 9:21 AM, Alexander Gumenyuk <notifications@github.com

**Comment by gumkins** [comment] 2015-06-02 20:22
Slava, 

I've just read several articles and I think I understand how the CORS works. What I don't know is how Meteor backend proxies frontend requests sent to other origins. Possibly it just resends them transparently or maybe modifies properly before resending. But it looks like this question should be asked in another thread.

**Comment by Slanman3755** [comment] 2015-06-05 18:12
@Slava I am still having this exact issue with my app.  I am running the app on Android 4.1 though.  I am trying to make an ajax call to one of our servers (cross-domain).  The server is running Nginx but is configured with CORS.  I can make ajax requests with no issues from my browser but when making the request from my phone I get "XMLHttpRequest cannot load https://foo.website.com/place/?get. Origin http://meteor.local is not allowed by Access-Control-Allow-Origin."  I have implemeneted App.accessRule("*") but it did not seem to change anything.  I've wasted a lot of time on this issue and I can confirm it definitely is still an issue so I'm not sure why it is closed.

**Comment by Slava** [comment] 2015-06-05 18:32
@Slanman3755 have you read my comment above? I closed this as a duplicate of https://github.com/meteor/meteor/issues/4132. I encourage to keep the discussion in one place - in that thread. I also posted a workaround there. As I said there, CORS concept is not related to `App.accessRule`.

**Comment by Slanman3755** [comment] 2015-06-05 19:04
I apologize for posting in the wrong issue.  I will post later comments there but your work around does not appear to be relevant to my issue.

**Comment by Slava** [comment] 2015-06-05 19:08
@Slanman3755 in that case, we require a full reproduction with steps to reproduce, descriptions of expected and observed results. Once you have that ready, I will be happy to look at it. Please, proceed in the issue I linked.

**Comment by barbatus** [comment] 2015-07-17 08:34
Hi @Slava,

Similar issue appears whenever I try to use Google API with OAuth authentication.
Google allows to set Javascript Origins in the development console, but it seems not recognize http://meteor.local is a correct address.
So as a result I always get same 'Origin http://meteor.local is not allowed by Access-Control-Allow-Origin’ response all the time. It’s possible only to make those requests through the server which is not always convenient. I wonder was there initially any strong reason behind having http://meteor.local instead of just http://localhost as it’s in pure Cordova applications?

**Comment by MichaelJCole** [comment] 2015-08-27 16:11
@slava's assumptions and resolution didn't work for me either.  [This was the problem](https://github.com/meteor/meteor/issues/3382) and here's the solution that worked for me:

```
meteor remove force-ssl 
```

Some notes for future readers:

  - `App.accessRule("*");` in `mobile-config.js` - this code runs once during the Meteor build to make [config.xml used by Cordova](https://cordova.apache.org/docs/en/4.0.0/guide_appdev_whitelist_index.md.html)
  - `BrowserPolicy.content.allowOriginForAll("http://meteor.local");` etc. is setting the [content-security-policy header](http://www.html5rocks.com/en/tutorials/security/content-security-policy/).  
      - TLDR;  This header asks clients to only make requests to certain servers.  This helps secure your app and users by not loading malicious code from external servers.
      - Incorrectly setting this header will show errors in the client, not the server.  
  - The error that googles here is talking about the [Access-Control-Allow-Origin header](http://www.html5rocks.com/en/tutorials/cors/).  
      - TLDR; This header asks browsers to only start your app if loaded from one of these domains.  This helps keep your app from being framed or hijacked.
      - Errors with this header are also in the client, not the server.  I'm guessing they show in the `meteor` output from a debug log on the client.

There is a bug in force-ssl that disrupts the Access-Control-Allow-Origin header.  This code was *not* a workaround for me:

```
WebApp.rawConnectHandlers.use(
  function(req, res, next) {
    // Cordova lives in meteor.local, so it does CORS
    if (req.headers && req.headers.origin === 'http://meteor.local') {
      res.setHeader('Access-Control-Allow-Origin', 'http://meteor.local');
    }
    next();
  }
);
```

If your app is using Stripe.com for example, you might need a Browser Policy like this:
```
Meteor.startup(function() {
  console.log('Configuring content-security-policy:');
  BrowserPolicy.content.allowSameOriginForAll();
  BrowserPolicy.content.allowOriginForAll('http://meteor.local');
  BrowserPolicy.content.allowOriginForAll('https://yourapp.io');
  BrowserPolicy.content.allowOriginForAll('https://*.yourapp.io');
  BrowserPolicy.content.allowOriginForAll('https://*.stripe.com');
  BrowserPolicy.content.allowEval();
  BrowserPolicy.framing.disallow();
});
```

**Comment by Exilz** [comment] 2015-09-14 10:12
I've been struggling with this issue for a few days too. I've tried everything listed here, thanks for your detailed answers @MichaelJCole. I'm using meteor 1.2 rc 12.
However, I still can't connect my Android app to my server.
The issue might be quite simple actually... Just like everyone I have a 

`XMLHttpRequest cannot load http://domain.net/sockjs/info?cb=qs5l6qd5wh. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://meteor.local' is therefore not allowed access. The response had HTTP status code 404.`

Error, however, it should try to load `http://domain.net:MYPORT/sockjs/info?cb=qs5l6qd5wh` or Apache will try to answer... Obviously it ends up as a 404 error.

I'm using a VPS and here is my mup config,

    {
    // Server authentication info
    "servers": [{
        "host": "domain.ovh.net",
        "username": "user",
        "password": "pass",
        "env": {
            "MONGO_URL": "mongodb://localhost:1337/meteor",
            "DDP_DEFAULT_CONNECTION_URL": "http://vps189425.ovh.net:4000"
        }
    }],
    "setupMongo": false,
    "nodeVersion": "0.12.7",
    "appName": "appname",
    "app": "/Users/...",
    "env": {
        "PORT": 4000,
        "ROOT_URL": "http://domain.ovh.net:4000",
        "DDP_DEFAULT_CONNECTION_URL": "http://domain.ovh.net:4000"
    },
    "deployCheckWaitTime": 30,
    "enableUploadProgressBar": true,
    "meteorBinary": "/Users/Maxime/Developpement/meteor-1.2/meteor",
    "buildOptions": {
        "debug": true,
        "executable": "/Users/Maxime/Developpement/meteor-1.2/meteor"
    }
    }

I'm pretty sure we're almost there :/ Hot-code push seems to be working properly though, same as opening my domain on a browser.

**Comment by pkumar-uk** [comment] 2015-09-20 17:47
I was also getting the CORS problem. The webapp working fine. The android mobile app working fine with emulator and connecting to the remote server; but the build apk refusing to connect to the server. My setup is meteor server sitting behind nginx with SSL.  Meteor server  running on 3002 port.  I am using mup to deploy the meteor app.


The problem I found later was a combination of ROOT_URL and SSL(ssl_trusted_certificate ) 
(Note - I have not used the Browser policy package yet. My mobile config file has App.accessRule("*");)

I have attached the conf files for mup, nginx and build param - I hope it helps somebody. 

mup.json
```
{
  // Server authentication info
  "servers": [
    {
      "host": “yyy.yyy.yy.yyy",
      "username": “ggg”,
      //"password": "password"
      // or pem file (ssh based authentication)
      "pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.36",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Show a progress bar during the upload of the bundle to the server.
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": “appname”,

  // Location of app (local directory)
  "app": "/Users/ddddd/dddd/ddd",

  // Configure environment
  "env": {
  "PORT": "3002", // The port you want to bind to on your server.
  "UPSTART_UID": "meteoruser", // The user you want to run meteor as.
  "ROOT_URL": "https://myappname.com"
},

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}
```

ngnix configuration available site for myappname
```
# Note: if you want to run multiple meteor apps on the same server,
# make sure you define a separate port for each.

# Upstreams
upstream myappname {  
    server 127.0.0.1:3002;
}

## redirect all non-www requests to the www subdomain
## Also redirect non-ssl to ssl, remove the server block if you do not use SSL
server {
    listen 80;
    listen 443 ssl;
    server_name www.myappname.com;
    ssl_certificate /etc/nginx/ssl/myappname/myappname.com.crt;
    ssl_certificate_key /etc/nginx/ssl/myappname/myappname.com.key;

 
    return 301 $scheme://myappname.com$request_uri;
}


server {
    server_name myappname.com;
    listen 80 spdy; #uncomment this line if you do not use SSL
    #if ($host = ‘myappname.com') {
    #    return 301 $scheme://www.$host$request_uri;
    #}
    # delete the following SSL block if you do not need https
    listen 443 ssl spdy;
    ssl_certificate /etc/nginx/ssl/myappname/myappname.com.crt;
    ssl_certificate_key /etc/nginx/ssl/myappname/myappname.com.key;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:DES-CBC3-SHA:!ADH:!AECDH:!MD5;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /etc/nginx/ssl/myappname/gd_bundle-g2-g1.crt;
    resolver 8.8.8.8 8.8.4.4;
    # end of SSL block

    ## performance boost using gzip
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    # end of GZIP block
  
    ## this is the actual load balancing to the meteor backend servers
    location / {
        proxy_pass http://myappname; # the name used in upstreams, substituted for any of the defined instances
        proxy_redirect off;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        # Make sure to use WebSockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

  
}
```


Build
```
meteor build ../bld-dir --server https://myappname.com:443
```

**Comment by mckinleymedia** [comment] 2015-09-23 05:16
For me, the answer was simple.  The app name in package.json in the app root directory needs to exactly match the deploy app name.

**Comment by alexissantos** [comment] 2015-12-29 04:19
BrowserPolicy didn't do the trick for me, but using this on the server did: http://enable-cors.org/server_meteor.html

```
// Listen to incoming HTTP requests, can only be used on the server
WebApp.connectHandlers.use(function(req, res, next) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  return next();
});
```

**Comment by ffxsam** [comment] 2016-01-17 05:34
Found this thread because I was having the same problem. I have a Meteor Cordova app that is supposed to fetch from a WordPress REST API endpoint. Worked fine on the desktop web, but not in the iOS Simulator.

Adding `App.accessRule("*");` to `/mobile-config.js` did the trick for me, thanks a ton!!
