### ISSUE TITLE
The handle returned by watching ... is the same with an already watched path

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5923] opened 2016-01-03 06:26 UTC
I'm in Meteor 1.3-modules-beta.2. Why might I be getting a ton of messages like the following?

```
The handle(6593) returned by watching /home/trusktr/src/trusktr+portfolio/public/party/jspm/github/RickMohr/Leaflet@better-inertial-scrolling/node_modules/karma/node_modules/http-proxy/node_modules/utile/node_modules/mkdirp/bin/cmd.js is the same with an already watched path(/home/trusktr/src/trusktr+portfolio/public/party/jspm/github/RickMohr/ Leaflet@better-inertial-scrolling/node_modules/karma/node_modules/http-proxy/node_modules/utile/node_modules/.bin/mkdirp)
The handle(6594) returned by watching /home/trusktr/src/trusktr+portfolio/public/party/jspm/github/RickMohr/Leaflet@better-inertial-scrolling/node_modules/karma/node_modules/http-proxy/node_modules/utile/node_modules/ncp/bin/ncp is the same with an already watched path(/home/trusktr/src/trusktr+portfolio/public/party/jspm/github/RickMohr/Leafle t@better-inertial-scrolling/node_modules/karma/node_modules/http-proxy/node_modules/utile/node_modules/.bin/ncp)
The handle(6700) returned by watching /home/trusktr/src/trusktr+portfolio/public/party/jspm/github/RickMohr/Leaflet@better-inertial-scrolling/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/uglify-js/bin/uglifyjs is the same with an already watched path(/home/trusktr/src/trusktr+portfolio/public/party/jspm/g ithub/RickMohr/Leaflet@better-inertial-scrolling/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/.bin/uglifyjs)
The handle(6701) returned by watching /home/trusktr/src/trusktr+portfolio/public/party/jspm/github/RickMohr/Leaflet@better-inertial-scrolling/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/bin/wscat is the same with an already watched path(/home/trusktr/src/trusktr+portfolio/public/party/jspm/github/Rick Mohr/Leaflet@better-inertial-scrolling/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/.bin/wscat)
The handle(7353) returned by watching /home/trusktr/src/trusktr+portfolio/public/party/jspm/github/RickMohr/Leaflet@better-inertial-scrolling/node_modules/karma-coverage/node_modules/dateformat/node_modules/meow/node_modules/redent/node_modules/strip-indent/cli.js is the same with an already watched path(/home/trusktr/src/trusktr+portfolio/publ ic/party/jspm/github/RickMohr/Leaflet@better-inertial-scrolling/node_modules/karma-coverage/node_modules/dateformat/node_modules/meow/node_modules/redent/node_modules/.bin/s trip-indent)
The handle(7309) returned by watching /home/trusktr/src/trusktr+portfolio/public/party/jspm/github/RickMohr/Leaflet@better-inertial-scrolling/node_modules/karma-coverage/node_modules/dateformat/node_modules/meow/node_modules/normalize-package-data/node_modules/semver/bin/semver is the same with an already watched path(/home/trusktr/src/trusktr+ portfolio/public/party/jspm/github/RickMohr/Leaflet@better-inertial-scrolling/node_modules/karma-coverage/node_modules/dateformat/node_modules/meow/node_modules/normalize-pa ckage-data/node_modules/.bin/semver)
```

**Comment by benjamn** [comment] 2016-01-06 23:08
The root cause seems to be symbolic links like `.../node_modules/.bin/uglifyjs` => `.../node_modules/uglify-js/bin/uglifyjs`. I think these errors can be safely ignored, though ideally they could be avoided by using `fs.realpath` in the file watching code.

**Comment by trusktr** [comment] 2016-01-07 07:56
The messages interfere with normal output, for example:

```
The handle(98) returned by watching /home/trusktr/src/trusktr+portfolio/public/node_modules/errno/cli.js is the same with an already watched path(/home/trusktr/src/trusktr+portfolio/public/node_modules/.bin/errno)
The handle(104) returned by watching /home/trusktr/src/trusktr+portfolio/public/node_modules/glslify/bin.js is the same with an already watched path(/home/trusktr/src/trusktr+portfolio/public/node_modules/.bin/glslify)
=> Started your app.

=> App running at: http://localhost:3000/
The handle(113) returned by watching /home/trusktr/src/trusktr+portfolio/public/node_modules/repeating/cli.js is the same with an already watched path(/home/trusktr/src/trusktr+portfolio/public/node_modules/.bin/repeating)
The handle(114) returned by watching /home/trusktr/src/trusktr+portfolio/public/node_modules/sha.js/bin.js is the same with an already watched path(/home/trusktr/src/trusktr+portfolio/public/node_modules/.bin/sha.js)
```

I'm getting about 50 of those messages, but I'm also getting the following message which I never got before except now:

```
=> It looks like a simple tweak to your system's configuration will make many tools (including this Meteor command) more efficient. To learn more, see
   https://github.com/meteor/meteor/wiki/File-Change-Watcher-Efficiency
```

It happens in tandem with the 50 other messages (I did what the wiki says, after which the message goes away temporarily until I restart my machine).

I'm running NPM install inside of the `public` folder (I've got a `package.json` in there, and I've got a Webpack workflow in there generating a bunch of static files. These messages happen while Webpack isn't running.

In case you want to, you should be able to reproduce by doing this:

```sh
git clone https://github.com/trusktr/site.git
git checkout meteor-issue-5923
cd site/public
npm install -g npm@3.5.2
npm install -g webpack
npm install
webpack
cd ..
meteor
```

**Comment by trusktr** [comment] 2016-02-06 19:02
This might also be causing a performance loss in build times.

**Comment by trusktr** [comment] 2016-02-06 19:07
The performance after renaming `public` to `.public` (which contains `node_modules` or my Webpack builds) increased by 60%.

**Comment by ElegantSudo** [comment] 2016-06-14 20:52
I'm getting these errors as well. What's the story with this?

**Comment by PeppeL-G** [comment] 2016-07-05 06:52
I have them too now in one of my apps. Could the underlying fault be that I have the application in a package (it's an application to test the package).

**Comment by micktaiwan** [comment] 2016-08-05 11:49
Getting this error too while getting TAPevents/tap-i18n from github

**Comment by mafzst** [comment] 2016-09-21 12:14
Any update?

**Comment by samuelgoff** [comment] 2016-09-23 15:28
`The handle(322) returned by watching [...].scss is the same with an already watched path[...]`

I'm getting the same thing, too, except I'm running Meteor 1.2.2-faster-rebuilds.0

Is anyone else seeing this on 1.4.1.1?

An associate of mine suggested that it was a Unix thing (he's seen it once on Linux and I'm on OS X 10.11.6), and that killing and restarting my terminal app might help. What OSes you others seeing this on?

Any other suggestions?

**Comment by trusktr** [comment] 2016-09-23 17:25
Do you have node_modules inside `/public`? That has led me to the same problem (above) and I solved it by moving those modules out of the public folder, then build my Webpack bundles into the public folder.

**Comment by samuelgoff** [comment] 2016-09-23 17:40
I appreciate the suggestion, however we do not use a /public folder, nor are we using any node modules, as we are currently pre-1.3. It must be something else at play.

**Comment by mafzst** [comment] 2016-09-23 17:44
@trusktr Nope

**Comment by samuelgoff** [comment] 2016-09-23 17:44
Oh, and we don't use webpack, either.

**Comment by ElegantSudo** [comment] 2016-09-23 17:44
@samuelgoff I haven't had this problem for a long time. If you're not on the latest version of Meteor, there's no reason to be pushing issues for bugs (because they may have already been fixed).

**Comment by mafzst** [comment] 2016-09-23 17:45
@ElegantSudo I'm on the latest version and I've this bug

**Comment by ElegantSudo** [comment] 2016-09-23 17:47
Hm, if that's the case and this is a known-fix, hopefully it won't be around for too long.

**Comment by trusktr** [comment] 2016-09-23 18:19
The problem seems to stem from the presence of *a ton* of files, eventually causing conflicts when (I think) a duplicate name exists (f.e. a symbolic link pointing to another file as Ben mentioned above). 

What does [`tree`](http://www.computerhope.com/unix/tree.htm) output look like? Run the command in the root of your project.

**Comment by samuelgoff** [comment] 2016-09-23 18:52
> If you're not on the latest version of Meteor, there's no reason to be pushing issues for bugs (because they may have already been fixed).

@ElegantSudo I'm not asking anyone to fix Meteor 1.2.2-faster-rebuilds.0; I'm trying to add another data point, to help narrow the search for the cause. For example, if this issue doesn't exist for anyone on 1.2, but it does exist on 1.3 and 1.2.2-faster-rebuilds.0, then that might point the way to the likely culprit. Since we're about to leapfrog to 1.4.1.1, it would be nice the make sure that the issue has, indeed, been resolved by the time we make the upgrade. And for anyone else that is supporting enterprise applications that don't get upgraded to the latest shiny new version on a dime, it would be nice to have more workaround options.

@trusktr `tree` says: `191 directories, 852 files.` Presumably, you don't need to see the ridiculous tree hierarchy we have in place.

Also, to correct myself from previously: We **_do_** have a `/public` folder; it's just empty, except for a fonts folder which contains 8 files.

From what I've personally experienced, this issue only occurs after I've had the same terminal window/tab open, pointing to the same project, and done a gazillion incremental tweaks while running in local dev mode -- **_without_** building for deployment for a great length of time. After a ridiculously large number of these successive, incremental (cached) builds, it seems that is when I experience one of these errors.

My linux-using associate said he ran into a similar issue with an EXT2 bug, in which a file deleted and immediately replaced with an **_identically-sized file_** (due to automated build processes) would revert back to the earlier state of the file, rather than the new file. Not saying that they employ the exact same shortcut for caching/faster rebuilds, but since the tweaks I'm making on these files are mainly SCSS tweaks, it is entirely possible that the new, minified version of these files is identical to the previous one. Hopefully they're comparing content hashes, not just file sizes. Just sayin.

**Comment by trusktr** [comment] 2016-09-24 03:52
Hi Sam, are there are any duplicate file names in that (presumably
ridiculous, hehe) tree hierarchy?

**Comment by samuelgoff** [comment] 2016-09-28 15:36
A few, however none are symbolic links. They are in separate packages (**_not_** modules), for separate microsite versions, with unique content (not identical). That said, any package-first architecture is going to have quite a few of the same filename: `package.js`.

**Comment by trusktr** [comment] 2016-09-28 23:46
Got a reproduction?

On Sep 28, 2016 8:37 AM, "samuelgoff" <notifications@github.com> wrote:

A few, however none are symbolic links. They are in separate packages (*not*
modules), for separate microsite versions, with unique content (not
identical). That said, any package-first architecture is going to have
quite a few of the same filename: package.js.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/meteor/meteor/issues/5923#issuecomment-250204807>, or mute
the thread

**Comment by samuelgoff** [comment] 2016-09-29 15:35
> Got a reproduction?

@trusktr I wish that were possible. Unfortunately, we cannot reproduce this reliably, and we have not been able to reproduce this issue on any of our dev's Windows or Ubuntu boxes running from within VMs. Only on my Mac. What's different about my configuration compared to my fellow devs? I'm running OS X 10.11.6 on a Fusion drive formatted as HFS+ Extended. Trying to produce a simplified test case is likely to remove the conditions that I suspect creates the issue: many files being automatically rebuilt over and over and over again.

Here's why: I've only encountered this a handful of times, after an epic camp-out on a single branch, making many small adjustments to the code, while the project has been running and doing a cached rebuild. That said, it has happened on numerous occasions in fairly rapid succession, depending on the phase of a project I'm working on (e.g. bug fix and polish before major version release). For some users, and for some types of work, I could see how this issue would be a serious bane. Restarting terminal or rebooting my system has seemed to resolve the issue, for the time being. Camping out on a branch for any length of time invites the issue to return.

As I mentioned earlier, we are considering the jump to 1.3.x or 1.4.x as quickly as we can fit it into our timelines, so we will be moving from a package-first architecture to a module-first architecture. From what I can tell reading above, that may either solve the issue or make it worse.

**Comment by benjamn** [comment] 2016-10-22 01:19
I think I may have finally fixed this: https://github.com/meteor/meteor/pull/7668/commits/35da19ab4e2c3ca297c7e6aae55a68fc079900a8

**Closed** 2016-10-25 21:16 UTC
Labels: bug, confirmed, Impact:few, known-fix, Severity:has-workaround
