### ISSUE TITLE
DDP messages can be parsed before the whole app is evaluated (leading to "Custom EJSON type not defined")

### ISSUE THREAD

**Issue by xbtsw** [meteor/meteor#4190] opened 2015-04-13 23:21 UTC
Hi,

When a EJSON type is defined in a package and the custom EJSON type is used in subscribed collection there's sometimes a racing condition where DDP trying to sync the collection before `EJSON.addType` is called, leading to "not defined" exception, which cause DDP to stop syncing even though `Meteor.status()` shows connected.

Please check this repo for a minimal reproducing project: https://github.com/xbtsw/ddp_package_issue

Since it is a racing condition the problem won't guarantee to happen every time, with debug console open, try clear cache and refresh the page few times you will be able to see the issue in console.

I believe this is because `ddp` package actually sometimes loads before package `cfs:ejson-file` (in the example). As `ddp` is not depending on `cfs:ejson-file` and there's no way to define that `ddp` require to load after it.

Thanks!

**Comment by glasser** [comment] 2015-04-14 22:32
I was not able to reproduce this on Chrome.

I also am not sure how it could happen.  `cfs:ejson-file` calls `EJSON.addType` at the top level, and there's no way to have received any data over the network at that point (clients can't yield).

**Comment by xbtsw** [comment] 2015-04-15 01:16
This is the `stack` property of the `Error` throwed, obtained from chrome console (save as global variable)

```
temp1.stack
"Error: Custom EJSON type FS.File is not defined
    at Object.builtinConverters.fromJSONValue (http://192.168.45.45:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:211:15)
    at fromJSONValueHelper (http://192.168.45.45:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:333:28)
    at http://192.168.45.45:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:306:21
    at Function._.each._.forEach (http://192.168.45.45:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:164:22)
    at EJSON._adjustTypesFromJSONValue (http://192.168.45.45:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:304:5)
    at http://192.168.45.45:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:313:7
    at Array.forEach (native)
    at Function._.each._.forEach (http://192.168.45.45:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:156:11)
    at EJSON._adjustTypesFromJSONValue (http://192.168.45.45:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:304:5)
    at http://192.168.45.45:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:313:7"
temp1.message
"Custom EJSON type FS.File is not defined"
```

I am not very familiar with meteor internals. if you could kindly provide some point of investigation I could try debug it on my end.

**Comment by glasser** [comment] 2015-04-15 02:03
That's a nice tip --- I didn't know about "Empty cache and hard reload". But I still can't reproduce it.

And that's a strange stacktrace... it seems like it should go back farther than it does.  Does it show more before you did "store as global variable"?

**Comment by glasser** [comment] 2015-04-15 02:04
Or ah, can you add `Error.stackTraceLimit=1000` to your code?

**Comment by xbtsw** [comment] 2015-04-15 02:14
After added `Error.stackTraceLimit=1000` I seem to consistently get the second version of the stack trace:

```
"Error: Custom EJSON type FS.File is not defined
    at Object.builtinConverters.fromJSONValue (http://192.168.45.45:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:211:15)
    at fromJSONValueHelper (http://192.168.45.45:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:333:28)
    at http://192.168.45.45:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:306:21
    at Function._.each._.forEach (http://192.168.45.45:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:164:22)
    at Object.EJSON._adjustTypesFromJSONValue (http://192.168.45.45:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:304:5)
    at http://192.168.45.45:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3293:26
    at Array.forEach (native)
    at Function._.each._.forEach (http://192.168.45.45:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:156:11)
    at parseDDP (http://192.168.45.45:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3291:5)
    at onMessage (http://192.168.45.45:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3678:17)"
```

**Comment by glasser** [comment] 2015-04-15 02:26
OK, I really don't understand how the message callback can get called before the *top-level* EJSON registration code runs.

**Comment by glasser** [comment] 2015-04-15 02:27
Although I don't think you're actually setting stackTraceLimit early enough either, because this is still a truncated 10-line stack trace.

**Comment by xbtsw** [comment] 2015-04-15 02:28
I just put it in the `app.js` on the top level for the example project. Could you suggest a better place?

**Comment by xbtsw** [comment] 2015-04-15 02:39
After play around with it I seem to got a reliable way of reproducing it, seems to work 6 out of 10 times I tried. Basically I tried to jam the network when page is loading. I will list the steps here, hopefully it works for you too.

1. Clone https://github.com/xbtsw/ddp_package_issue and get it running.
2. Visit the page in chrome, open devtools
3. Click "toggle device mode" button in devtools (second button to the top left)
4. Use following settings:
  * device: <Select Model> (not overriding)
  * not overriding resolution (uncheck), not fit (uncheck)
  * network: Regular 2G (250Kbps 300ms RTT)
  * UA: no override
5. Switch devtools to network pane, notice on the bottom of network pane there's a request counter showing how many requests are made
<Note: following steps need to be fast>
6. Right click refresh button, select "Empty Cache and Hard reload"
7. Open the network override dropdown, hover the mouse to "No throttling" and get ready
8. Watch the request counter, on my machine it will stuck at 63 for ~1secs
9. As soon as the counter jump to 70ish (always 76 for me), switch the network to "No throttling"
10. The error will be logged in devtools console.

This is the steps I got around 60% success rate for the example project. In the real meteor project I am working on it seems the file count & size hit a sweet spot, I just need to do a hard refresh it will almost guarantee to happen.

**Comment by glasser** [comment] 2015-04-15 04:24
*oh*  I see, this is because you're not in prod mode and the different source files are being fetched separately from the server.  And while multiple `<script>` tags are processed synchronously in the sense that you don't evaluate the next tag's JS until the previous one is done, event handlers can still run.

In a sense, Meteor.connect probably shouldn't be called until Meteor.startup but that would break every app ever.  I think one thing we could do is make the DDP client buffer up all messages (not even calling `parseDDP`) until after `Meteor.startup`, if `Meteor.startup` hasn't happened yet...

**Comment by xbtsw** [comment] 2015-04-29 15:20
Hi @glasser , I am attempting to fixing this myself but I don't understand why you say:

> ...Meteor.connect probably shouldn't be called until Meteor.startup but that would break every app ever.

Could you kindly explain why calling `Meteor.startup` disconnected is a problem?

**Comment by misha** [comment] 2015-09-23 01:33
Hi @xbtsw , have you had any progress with this issue? I'm in the identical situation. I've determined there's a race condition between code attempting to deserialize existing custom EJSON types in the database and the code declaring `EJSON.addType` for those types.

This happens about half the time locally, and *all* the time when deployed on Heroku, presumably because the gaps between files being loaded and processed are exaggerated.

I tried to learn about ordering Meteor's dependencies, but couldn't find anything other than [this](http://docs.meteor.com/#/full/structuringyourapp) documentation. Even after placing the two segments of code as far apart in the load ordering described (one in a `main` file, the other in a `lib/` file), I was unable to fix the issue.

If I can't fix this issue, I'll have to switch out of Meteor. It renders my application unusable...

**Comment by hwillson** [comment] 2017-06-16 18:38
Hi all - since there hasn't been any activity on this issue in quite some time, and there have been several new Meteor releases since this issue was created, I'll close it for now. Happy to re-open if anyone is still encountering this issue with a modern version of Meteor. Thanks!

**Closed by hwillson** 2017-06-16 18:38 UTC
Labels: Project:DDP
