### ISSUE TITLE
minifier-js error in Meteor 2.4, when recompiling npm package

### ISSUE THREAD

**Issue by markdowney** [meteor/meteor#11644] opened 2021-09-24 00:16 UTC
I have a monorepo setup where a private npm package is recompiled by meteor using:
```
  "meteor": {
    "nodeModules": {
      "recompile": {
        "mypackage": "modern"
      }
    }
  }
```
Since upgrading from 2.2 to 2.4 , the build throws the following error (development works fine):
```
Errors prevented bundling:
While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error
(SyntaxError:Unexpected token: operator (<))
Source file: node_modules/mypackage/index.js  (6:4)
Line content:     <div>My Component</div>

at maybeThrowMinifyErrorBySourceFile
(packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle
(packages/minifyStdJS/plugin/minify-js.js:66:11)
```
I've set up a reproduction repo here: https://github.com/markdowney/meteor-minify-repro
Might be related to: #11629

**Comment by StorytellerCZ** [comment] 2021-09-28 10:54
Can also be reproduced with just running `meteor --production`.

**Comment by StorytellerCZ** [comment] 2021-09-28 11:13
If you rename and import `mypackage/index.jsx`
`.js` => `.jsx` it works.

**Comment by renanccastro** [comment] 2021-09-29 12:35
Hi @markdowney 
I haven't dig deeper in comparing the behavior of the versions, but for me, it's clear that the error is spawning because you have react template code in your npm dependency and this dependency is only being recompiled for the "modern" bundle, thus failing to bundle the "legacy" one because JSX still exists in it.

It's the expected behavior. What changed in terser's version is that it's probably being pickier with what it minifies.

The correct way for this to work, while still bundling the legacy version, would be:

```
    "nodeModules": {
      "recompile": {
        "mypackage": ["legacy", "modern"]
      }
    }

```

I hope it helps and let me know what are your thoughts on it. I'm closing this issue for now, as I don't think there are any actions we can take, but please reopen it if you feel my answer is not convincing enough :)

**Closed by renanccastro** 2021-09-29 12:35 UTC
Labels: Project:Isobuild:Minifiers, Type:Bug, Severity:has-workaround
