### ISSUE TITLE
Critical: Meteor settings ENV variable broken?

### ISSUE THREAD

**Issue by tgoorden** [meteor/meteor#3866] opened 2015-03-04 22:23 UTC
This is a really difficult issue to solve and I fear it may be a serious bug. The documentation states that it is possible to change the Meteor settings with an environment variable called `METEOR_SETTINGS`. However, when you look at the code, there's this in the `run-app.js`:

    if (self.settings) {
      env.METEOR_SETTINGS = self.settings;
    } else {
      delete env.METEOR_SETTINGS;
    }

With `self.settings` loaded as a command line option. However, this seems to imply that if there is an environment variable called `METEOR_SETTINGS` in the `process.env`, it is simply ignored (and deleted!).

I think it's fairly easy to reproduce as well. First set an environment variable like:

    export METEOR_SETTINGS={\"test\":\"test\"}

This gets through the JSON parser at least. Start meteor with just a plain old `meteor`. Drop to `meteor shell` and you'll notice that there is no `METEOR_SETTINGS` in `process.env` to be found. (Meteor.settings is not initiated as well, but that seems like a secondary result.)

This is a critical problem as - for instance - Passenger doesn't allow you to pass command line options to Meteor, only environment variables. This is currently resulting in a completely broken app for us...

**Comment by glasser** [comment] 2015-03-04 22:59
Duplicate of #3466.

(It sounds like you're trying to use the development-mode runner in production, which is not recommended or supported.)

**Closed by glasser** 2015-03-04 22:59 UTC

**Comment by tgoorden** [comment] 2015-03-04 23:18
Well. Unfortunately, this is the way it's suggested in the Passenger deployment manual: https://github.com/phusion/passenger/wiki/Phusion-Passenger:-Meteor-tutorial

So, basically you are saying that you can only use bundles inside Passenger? Keep in mind that Passenger actually does start Meteor in production mode, I guess it's just that the entire app can be uploaded instead of a bundle.

I think if it's the case that bundles can accept METEOR_SETTINGS as ENV variable, but development mode can't, this is terribly confusing. If bundles also can't, I'm stuck.
