### ISSUE TITLE
Accounts-UI elements should have unique ID's 

### ISSUE THREAD

**Issue by msavin** [meteor/meteor#3848] opened 2015-03-02 05:24 UTC
Currently, Accounts-UI uses an single ID so it can't be used more than once on a website. If you do, it would cause both of them open and has caused some issues (from what I've seen with the package msavin:mongol). It would be great if each one had a unique ID so that they could be used in multiple places.

**Comment by glasser** [comment] 2015-03-03 02:04
Duplicate of #1472

**Closed by glasser** 2015-03-03 02:04 UTC
