### ISSUE TITLE
[1.6] Collection findOne returns first result of collection when id is undefined

### ISSUE THREAD

**Issue by programthis** [meteor/meteor#9296] opened 2017-11-03 15:15 UTC
Since updating to Meteor 1.6, using findOne on a collection with an id that is undefined now returns the first result in that collection (instead of an undefined result). However, specifying id in the query does work as expected.

Example:
```
let id = a;
Images.findOne(a) //first collection result
Images.findOne({_id: a}) //undefined
```

[This same issue was reported previously here](https://github.com/meteor/meteor/issues/8220).

**Package list**:
accounts-password@1.5.0
shell-server@0.3.0
kadira:flow-router
ostrio:files
kadira:blaze-layout
arillo:flow-router-helpers
zimme:active-route
aldeed:simple-schema
momentjs:moment
force-ssl@1.1.0
dynamic-import@0.2.0
email@1.2.3
fourseven:scss
aldeed:collection2

**Comment by hwillson** [comment] 2017-11-03 15:31
@programthis This should be working (I just tested quickly and can't reproduce this issue with Meteor 1.6). Please provide a small, runnable reproduction demonstrating this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)).

**Comment by programthis** [comment] 2017-11-03 18:10
I just tried to replicate the issue on a new project and am unable to as well so it must be related to one of the packages I am using. I've updated my post with my current package list. I will try to narrow them down one by one.

**Comment by zimme** [comment] 2017-11-05 14:50
@programthis if you're using `zimme:collection-softremovable` or `matb33:collection-hooks` make sure you're using the latest test version. There have been a problem with selectors that has been fixed but only beta/rc releases with those fixes are available.

**Comment by programthis** [comment] 2017-11-05 23:18
@zimme I'm not using either of those packages. I'm still trying to figure out if the problem might be with a dependency or something similar.

**Comment by hwillson** [comment] 2017-11-07 17:33
@programthis I'll close this for now since it doesn't appear to be a Meteor issue. Keep us posted if you find out otherwise though. Thanks!

**Closed by hwillson** 2017-11-07 17:33 UTC
Labels: can't-reproduce, Project:Minimongo
