### ISSUE TITLE
File changes are not always detected after updating to Meteor v1.5.1

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#8942] opened 2017-07-23 14:13 UTC
After updating to v1.5.1 (could also have been v1.5.0), I sometimes find myself in a situation where the app is acting strange and upon further inspection, the code I have on disk is different from code I have loaded in the browser.

This just happened today, again:

![bug](https://user-images.githubusercontent.com/17210302/28499940-48cbc928-6fc9-11e7-9a12-8757ef2f3541.png)

> VS Code on the left with the file saved, Chrome Dev Tools on the right showing the loaded javascript from where the error originated

I had commented out a piece of my code to prevent this specific error from happening, but it did anyway.

I haven't figured out a sure way to reproduce this yet, but I would start with moving or renaming files or folders, though this is just a hunch.

**Comment by trackchris** [comment] 2017-07-23 14:49
I'm experiencing the same problem. I was on 1.5 for several weeks and had no issues - they only started when I upgraded to 1.5.1 so think it must be related to the file watcher changes that were introduced.

**Comment by trackchris** [comment] 2017-07-23 15:12
I'm just trialling the `METEOR_WATCH_PRIORITIZE_CHANGED` option to see if that makes any diffference. I will report back shortly.

**Comment by trackchris** [comment] 2017-07-23 19:36
I can confirm that setting the `METEOR_WATCH_PRIORITIZE_CHANGED` environment variable to `false` has resolved the problem for me.

**Comment by rijk** [comment] 2017-07-24 10:45
Yes, same here! I posted it in the forum: https://forums.meteor.com/t/rebuild-sometimes-skips-files-since-1-5-1/38104. Will try the variable 👍

**Comment by hwillson** [comment] 2017-07-24 13:50
Hi all - are the changes being detected after waiting a bit (up to 5 seconds), or are they never showing up at all?

**Comment by arggh** [comment] 2017-07-24 14:15
For me they would not get picked up at all, or then there's a really long delay (minutes, not seconds).

**Comment by JackAdams** [comment] 2017-07-24 16:03
I can reliably create a repro for one variant of this:

1. Take a html file (call it `test.html`) with a blaze template `<template name="test"></template>` 
2. In the mac finder, duplicate the file (a rebuild will happen and hot reload and, on the client console, there will be an error message that there are two templates with the name `test`).
3. Rename the duplicated file to `new-test.html` (a rebuild will happen and hot reload and, on the client console, there will be an error message that there are two templates with the name `test`).
4. Edit the contents of `new-test.html` so that it has `<template name="new_test"></template>`. On saving, the client will rebuild, hot reload, but the error message in the client console will still be there, even though there are no longer templates with the same name in the codebase being watched.

After getting into this state, subsequent changes to the file `new-test.html`, don't help (although they result in client rebuilds). There must be a cached version of `test-copy.html` that resulted from duplicating the file that's sneaking into the build.

The only way to fix it is to stop the meteor process and start it again, then wait while the whole project builds from scratch again.

**Comment by hwillson** [comment] 2017-07-24 18:35
I haven't had a chance to dig into this much further, but I have been able to verify that the issue outlined in the above repro steps is coming from re-using existing file watchers. Commenting out https://github.com/meteor/meteor/blob/b52c6587d7542c0f27481a3bee8c65be06068ac1/tools/fs/safe-watcher.js#L81 fixes the issue (since this ensures a new file watcher is created after every change). This of course isn't a solution, but it helps point towards the real source of the problem. For some reason the re-used watcher is no longer capturing changes. I'll dig into this more hopefully later today, but if anyone is interested in taking a look sooner, the problem lies somewhere in https://github.com/meteor/meteor/blob/b52c6587d7542c0f27481a3bee8c65be06068ac1/tools/fs/safe-watcher.js.

**Comment by hwillson** [comment] 2017-07-25 11:41
I've found the issue - fix coming shortly.

**Comment by hwillson** [comment] 2017-07-28 11:20
A fix for this has been merged and will be coming in Meteor 1.5.2. Closing - thanks!

**Closed by hwillson** 2017-07-28 11:20 UTC
Labels: bug, confirmed, Impact:some, Project:Tool, Severity:blocks-development

**Comment by juiyout** [comment] 2017-09-04 10:39
In the mean time before 1.5.2 release, where do I set `METEOR_WATCH_PRIORITIZE_CHANGED`?
Do I do like this?
```
export METEOR_WATCH_PRIORITIZE_CHANGED=false
meteor build ...
```

I'm experiencing meteor build keep giving me old iOS project.

**Comment by rijk** [comment] 2017-09-14 08:24
This is still happening on 1.5.2! @hwillson

**Comment by arggh** [comment] 2017-09-14 09:31
I've noticed the same. Sometimes only killing the `meteor` process helps to get some files back under "watching".

**Comment by chrishearn** [comment] 2017-09-14 18:03
Also still having the issue in 1.5.2. I've recently moved from WebStorm to VS Code but don't think that is relevant anyway as it appears to be happening regardless of editor/IDE from the other reports here. 

I'm sticking with the `METEOR_WATCH_PRIORITIZE_CHANGED=false` as a current workaround, which does the trick.

Let me know if you need any more information or need any testing carried out that could help diagnose the problem.

**Comment by chrishearn** [comment] 2017-09-14 18:08
I'm working on reasonably large project, so not sure if this has any relevance, as clearly not everyone is hitting this issue:

![image](https://user-images.githubusercontent.com/11329036/30446061-f71cfae4-997f-11e7-992c-9f1e9b9d4851.png)

Might be worth comparing if anyone else here can provide similar info from their affected projects?

**Comment by ahmadsholehin** [comment] 2017-10-22 07:09
I can confirm that this issue still persists. `METEOR_WATCH_PRIORITIZE_CHANGED=false` didn't manage to solve my issue.

**Comment by cormip** [comment] 2017-11-20 01:27
I'm experiencing this issue with Meteor 1.6. `METEOR_WATCH_PRIORITIZE_CHANGED=false` did not solve the problem for me.

**Comment by Zusurs** [comment] 2018-01-19 17:34
Same here. 1.6 and terrible long (up to 15 seconds) file change detection on Windows machine.

**Comment by alanisdg** [comment] 2020-07-11 00:01
issue still persist on Meteor 1.10  React apps

**Comment by Jovan27** [comment] 2020-10-24 07:45
I also experience this issue in 1.11.1

**Comment by Jovan27** [comment] 2020-10-24 09:05
I solved this, for me this bug was due to not closing the headless browser. It seems like the puppeteer browser needs to be closed when code change happens, if it doesn't code from before is presisted, otherwise, a new code is applied.
