### ISSUE TITLE
1.4.2 Can't update

### ISSUE THREAD

**Issue by talha-asad** [meteor/meteor#7887] opened 2016-10-07 11:48 UTC
I don't know how, but you guys are great at building stuff but the updater/downloader for meteor updates has been getting worse after around 1.3

This is on OS X 10.12,
Tried it on Ubuntu as well, got the same error.

Check this out
```sh
Talhas-MacBook-Pro:app talhaasad$ meteor update
/Users/talhaasad/.meteor/packages/meteor-tool/.1.4.1_1.1bb4uc4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/sf/pz_64g8976dbzd89pq0d2s740000gn/T/mt-9u0mw8/os.json'
    at Error (native)
Talhas-MacBook-Pro:app talhaasad$ meteor update
^C                                                                                   
Talhas-MacBook-Pro:app talhaasad$ meteor update
/Users/talhaasad/.meteor/packages/meteor-tool/.1.4.1_1.1bb4uc4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/sf/pz_64g8976dbzd89pq0d2s740000gn/T/mt-14o49ne/os.json'
    at Error (native)
Talhas-MacBook-Pro:app talhaasad$ meteor update
/Users/talhaasad/.meteor/packages/meteor-tool/.1.4.1_1.1bb4uc4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/sf/pz_64g8976dbzd89pq0d2s740000gn/T/mt-jw5joy/os.json'
    at Error (native)
Talhas-MacBook-Pro:app talhaasad$ meteor update
/Users/talhaasad/.meteor/packages/meteor-tool/.1.4.1_1.1bb4uc4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/sf/pz_64g8976dbzd89pq0d2s740000gn/T/mt-tn24xy/os.json'
    at Error (native)
Talhas-MacBook-Pro:app talhaasad$ meteor update
/Users/talhaasad/.meteor/packages/meteor-tool/.1.4.1_1.1bb4uc4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/sf/pz_64g8976dbzd89pq0d2s740000gn/T/mt-13w9oxs/os.json'
    at Error (native)
Talhas-MacBook-Pro:app talhaasad$ meteor update
/Users/talhaasad/.meteor/packages/meteor-tool/.1.4.1_1.1bb4uc4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/sf/pz_64g8976dbzd89pq0d2s740000gn/T/mt-k0kxvg/os.json'
    at Error (native)
Talhas-MacBook-Pro:app talhaasad$ meteor update
   Downloading meteor-tool@1.4.1_2...        [=====                    ] 21% 260.5s
```

As you can see I tried a reasonable amount of times, before finally ditching the idea.

**Comment by talha-asad** [comment] 2016-10-07 11:49
That last one failed as well, FYI.

**Comment by abernix** [comment] 2016-10-07 12:39
Thanks for reporting.  This is a duplicate of #7806.  Unfortunately, there is no resolution at the current time as it hasn't been possible to reproduce it in an environment where it could be tested/fixed; it does not affect everyone who runs this.

Closing in favor of that issue, but [one solution has been a reinstall](https://github.com/meteor/meteor/issues/7861) and the other has been [changing the CDN](https://github.com/meteor/meteor/issues/7657).

If this is related to CDN/connectivity, I can say that the logic has been improved in more recent versions, but I wouldn't have expected this problem with 1.4.1.1.  Anyhow, that other issue is the place for more commentary.

**Closed by abernix** 2016-10-07 12:39 UTC
