### ISSUE TITLE
Filtering fields in one Meteor.users publication affects other publications

### ISSUE THREAD

**Issue by vazamb** [meteor/meteor#4678] opened 2015-07-03 08:48 UTC
I am currently refactoring publications and am running into some issues:
There are 2 publications for Meteor.users

````
// Public profile of all users, published to every logged in user
Meteor.publish("publicProfile", function() {
 if (!this.userId) return this.ready();  

  return Meteor.users.find(
    {},
    {
    fields: {
      'profile.name': 1,
      'profile.lastName': 1,
      // a bunch more fields
      'profile. ...........',

      'createdAt': 1,
      'status':1,
    }
    });
});

// Publication for admins to edit user data etc.
Meteor.publish("allUsers", function() {
  if (Roles.userIsInRole(this.userId,['moderator'])) {
  return Meteor.users.find({}, {
    fields: {
      "emails":1,
      "data":1,
      "profile": 1,
      "createdAt":1,
      "status":1,
      "services":1,
      "additionalInfo":1
    }
    });
  } else {
    return this.ready();
  }

});
````

Now, the problem is that "allUsers" should return the complete `profile` object but doesn't. I only get the fields that I already publish through "publicProfile". I do get the complete `data` object, so the publication itself is working. Specifying additional fields in "allUsers" does not fix the issue:

````
// Publication for admins to edit user data etc.
Meteor.publish("allUsers", function() {
  if (Roles.userIsInRole(this.userId,['moderator'])) {
  return Meteor.users.find({}, {
    fields: {
      "emails":1,
      "data":1,
      "profile.ADDITIONALPROPERTY": 1,
      "createdAt":1,
      "status":1,
      "services":1,
      "additionalInfo":1
    }
    });
  } else {
    return this.ready();
  }

});
````

`profile.ADDITIONALPROPERTY` will not get published.

**Comment by glasser** [comment] 2015-07-07 22:06
Duplicate of #4615. See my response at https://github.com/meteor/meteor/issues/4615#issuecomment-117336698

**Closed by glasser** 2015-07-07 22:06 UTC
Labels: Project:DDP
