### ISSUE TITLE
[meteor 1.4] MongoError: no mongos proxies found in seed list

### ISSUE THREAD

**Issue by patrickml** [meteor/meteor#7471] opened 2016-07-26 02:44 UTC
After updating from Meteor 1.3.5.1 I received this error

I am running a local mongo instance not the one that comes with Meteor. I use it to connect multiple apps together on the same DB.

```
W20160725-22:33:00.858(-4)? (STDERR) /Users/patricklewis/.meteor/packages/meteor-tool/.1.4.0.qhd473++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20160725-22:33:00.858(-4)? (STDERR)            				throw(ex);
W20160725-22:33:00.859(-4)? (STDERR)            				^
W20160725-22:33:00.873(-4)? (STDERR) MongoError: no mongos proxies found in seed list
W20160725-22:33:00.873(-4)? (STDERR)     at Object.Future.wait (/Users/patricklewis/.meteor/packages/meteor-tool/.1.4.0.qhd473++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
W20160725-22:33:00.873(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
W20160725-22:33:00.874(-4)? (STDERR)     at OplogHandle._startTailing (packages/mongo/oplog_tailing.js:200:33)
W20160725-22:33:00.874(-4)? (STDERR)     at new OplogHandle (packages/mongo/oplog_tailing.js:76:8)
W20160725-22:33:00.875(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:219:25)
W20160725-22:33:00.875(-4)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
W20160725-22:33:00.875(-4)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
W20160725-22:33:00.875(-4)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
W20160725-22:33:00.875(-4)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:103:40)
W20160725-22:33:00.876(-4)? (STDERR)     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
W20160725-22:33:00.876(-4)? (STDERR)     - - - - -
W20160725-22:33:00.876(-4)? (STDERR)     at [object Object].<anonymous> (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/topologies/mongos.js:304:35)
W20160725-22:33:00.876(-4)? (STDERR)     at [object Object].g (events.js:260:16)
W20160725-22:33:00.877(-4)? (STDERR)     at emitOne (events.js:77:13)
W20160725-22:33:00.877(-4)? (STDERR)     at [object Object].emit (events.js:169:7)
W20160725-22:33:00.877(-4)? (STDERR)     at Object.cb (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/topologies/server.js:265:14)
W20160725-22:33:00.878(-4)? (STDERR)     at /Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:443:18
W20160725-22:33:00.878(-4)? (STDERR)     at authenticateStragglers (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:399:16)
W20160725-22:33:00.878(-4)? (STDERR)     at [object Object].messageHandler (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:421:5)
W20160725-22:33:00.878(-4)? (STDERR)     at Socket.<anonymous> (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:294:22)
W20160725-22:33:00.879(-4)? (STDERR)     at emitOne (events.js:77:13)
=> Exited with code: 1                        
W20160725-22:33:21.895(-4)? (STDERR)          
W20160725-22:33:21.896(-4)? (STDERR) /Users/patricklewis/.meteor/packages/meteor-tool/.1.4.0.qhd473++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20160725-22:33:21.896(-4)? (STDERR)            				throw(ex);
W20160725-22:33:21.896(-4)? (STDERR)            				^
W20160725-22:33:22.034(-4)? (STDERR) MongoError: no mongos proxies found in seed list
W20160725-22:33:22.035(-4)? (STDERR)     at Object.Future.wait (/Users/patricklewis/.meteor/packages/meteor-tool/.1.4.0.qhd473++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
W20160725-22:33:22.035(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
W20160725-22:33:22.036(-4)? (STDERR)     at OplogHandle._startTailing (packages/mongo/oplog_tailing.js:200:33)
W20160725-22:33:22.036(-4)? (STDERR)     at new OplogHandle (packages/mongo/oplog_tailing.js:76:8)
W20160725-22:33:22.037(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:219:25)
W20160725-22:33:22.037(-4)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
W20160725-22:33:22.037(-4)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
W20160725-22:33:22.038(-4)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
W20160725-22:33:22.038(-4)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:103:40)
W20160725-22:33:22.038(-4)? (STDERR)     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
W20160725-22:33:22.038(-4)? (STDERR)     - - - - -
W20160725-22:33:22.039(-4)? (STDERR)     at [object Object].<anonymous> (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/topologies/mongos.js:304:35)
W20160725-22:33:22.039(-4)? (STDERR)     at [object Object].g (events.js:260:16)
W20160725-22:33:22.039(-4)? (STDERR)     at emitOne (events.js:77:13)
W20160725-22:33:22.039(-4)? (STDERR)     at [object Object].emit (events.js:169:7)
W20160725-22:33:22.040(-4)? (STDERR)     at Object.cb (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/topologies/server.js:265:14)
W20160725-22:33:22.040(-4)? (STDERR)     at /Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:443:18
W20160725-22:33:22.040(-4)? (STDERR)     at authenticateStragglers (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:399:16)
W20160725-22:33:22.041(-4)? (STDERR)     at [object Object].messageHandler (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:421:5)
W20160725-22:33:22.041(-4)? (STDERR)     at Socket.<anonymous> (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:294:22)
W20160725-22:33:22.041(-4)? (STDERR)     at emitOne (events.js:77:13)
=> Exited with code: 1                        
W20160725-22:33:31.294(-4)? (STDERR)          
W20160725-22:33:31.295(-4)? (STDERR) /Users/patricklewis/.meteor/packages/meteor-tool/.1.4.0.qhd473++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20160725-22:33:31.295(-4)? (STDERR)            				throw(ex);
W20160725-22:33:31.295(-4)? (STDERR)            				^
W20160725-22:33:31.446(-4)? (STDERR) MongoError: no mongos proxies found in seed list
W20160725-22:33:31.446(-4)? (STDERR)     at Object.Future.wait (/Users/patricklewis/.meteor/packages/meteor-tool/.1.4.0.qhd473++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
W20160725-22:33:31.446(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
W20160725-22:33:31.447(-4)? (STDERR)     at OplogHandle._startTailing (packages/mongo/oplog_tailing.js:200:33)
W20160725-22:33:31.447(-4)? (STDERR)     at new OplogHandle (packages/mongo/oplog_tailing.js:76:8)
W20160725-22:33:31.447(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:219:25)
W20160725-22:33:31.447(-4)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
W20160725-22:33:31.448(-4)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
W20160725-22:33:31.450(-4)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
W20160725-22:33:31.451(-4)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:103:40)
W20160725-22:33:31.452(-4)? (STDERR)     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
W20160725-22:33:31.453(-4)? (STDERR)     - - - - -
W20160725-22:33:31.453(-4)? (STDERR)     at [object Object].<anonymous> (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/topologies/mongos.js:304:35)
W20160725-22:33:31.454(-4)? (STDERR)     at [object Object].g (events.js:260:16)
W20160725-22:33:31.454(-4)? (STDERR)     at emitOne (events.js:77:13)
W20160725-22:33:31.455(-4)? (STDERR)     at [object Object].emit (events.js:169:7)
W20160725-22:33:31.455(-4)? (STDERR)     at Object.cb (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/topologies/server.js:265:14)
W20160725-22:33:31.455(-4)? (STDERR)     at /Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:443:18
W20160725-22:33:31.456(-4)? (STDERR)     at authenticateStragglers (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:399:16)
W20160725-22:33:31.456(-4)? (STDERR)     at [object Object].messageHandler (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:421:5)
W20160725-22:33:31.456(-4)? (STDERR)     at Socket.<anonymous> (/Users/patricklewis/.meteor/packages/npm-mongo/.1.5.45.1yvdada++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:294:22)
W20160725-22:33:31.456(-4)? (STDERR)     at emitOne (events.js:77:13)
=> Exited with code: 1                        
=> Your application is crashing. Waiting for file change.
```

**Comment by abernix** [comment] 2016-07-26 07:33
Closing as a duplicate of #7450, which I will re-open.  Please read that issue, relate and comment to the existing information in that issue.  Please only include your own error message (once) if it's different than what's already been posted.

**Closed by abernix** 2016-07-26 07:33 UTC
