### ISSUE TITLE
Loginwithpassword failed

### ISSUE THREAD

**Issue by GuofuHuang** [meteor/meteor#8465] opened 2017-03-07 16:02 UTC
I just update my Meteor to the latest version, but the login function doesn't give any feedback, no errs nor success callbacks. 

It works before I update it. 

Any clues?

**Comment by guiguidu60** [comment] 2017-03-07 16:07
What is your code ?

**Comment by GuofuHuang** [comment] 2017-03-07 16:12
`    if (this.loginForm.valid) {
      Meteor.loginWithPassword(this.loginForm.value.email, this.loginForm.value.password, (err) => {
        this.zone.run(() => {
          if (err) {
            this.error = err;
            console.log(err);
          } else {
            console.log('passed');
            this.router.navigate(['/createQuote']);
          }
        });
      });
    }
`

**Comment by GuofuHuang** [comment] 2017-03-07 16:15
nothing happened inside the callback.

**Comment by hwillson** [comment] 2017-03-07 16:25
Hi @GuofuHuang - since from your code sample we can't tell what `this.zone.run()` does, we can't help troubleshoot this further. I'd suggest first removing that entire call from your callback, and just dropping in a `console.log('aloha!')` within the callback, to verify that works first. If that doesn't work, then please consider posting back with a small, runnable reproduction that demonstrates this issue, to help with troubleshooting (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more details).

The above being said though, I'm pretty confident this isn't an issue with Meteor (I've verified `Meteor.loginWithPassword` is working with the latest version of Meteor). Please try posting on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) for more assistance with using Meteor. Closing this issue for now. Thanks!

**Closed by hwillson** 2017-03-07 16:25 UTC
