### ISSUE TITLE
Build android apk fails when using bower polymer 1.0 components

### ISSUE THREAD

**Issue by udiedrichsen** [meteor/meteor#4544] opened 2015-06-12 08:21 UTC
Hi,

I made an example repo to reproduce this:
https://github.com/udiedrichsen/polymer-apk-build-failed

Maybe, it already fixed in the new meteor release using cordova 5 ?

meteor build ../BUILDDIR --server 192.168.178.53:3000

/Users/doedel/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245 throw(ex); ^ Error: The APK file for the Android build was not found. at findApkPath (/Users/doedel/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:970:11) at /Users/doedel/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:950:21 at Array.forEach (native) at Function..each..forEach (/Users/doedel/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11) at buildCommand (/Users/doedel/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:933:29) at Command.main.registerCommand._.extend.name as func at /Users/doedel/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23

**Comment by beetaa** [comment] 2015-06-13 10:10
MY GOD, I met this issue today, too, and can not solve it with more than 5 hours' debug.
I've looked for answer from issue #4357 , but still not work, the APK file do not come out at all.
Can anybody help?

**Comment by beetaa** [comment] 2015-06-13 10:11
@udiedrichsen +1

**Comment by beetaa** [comment] 2015-06-15 00:36
@udiedrichsen hi, do you have any solutions? thank you.

**Comment by beetaa** [comment] 2015-06-15 01:56
hi @udiedrichsen , I think I've found the reason causing this Error, please go ahead #4357 and checkout my answer. hope can help.

**Comment by udiedrichsen** [comment] 2015-06-15 06:01
Hi @beetaa , I tried this tip without success.
My example repo for this error is very simple. Plain Meteor with just one package: polymer.

I also removed my complete local meteor installation, android sdk and the local project meteor folder.

But the error is still their.
I hope that with the next meteor release 1.1.1 with cordova 5 this is fixed.

**Comment by caio-ribeiro-pereira** [comment] 2015-06-22 16:34
I've been in the same issues, but I'm not using polymer.

**Comment by RaphaelRoyerRivard** [comment] 2015-06-22 18:56
I have the same problem. I know that the Cordova Plugin I am developing causes the issue, because when I remove it from my meteor project, the build succeeds.

**Comment by RaphaelRoyerRivard** [comment] 2015-06-22 20:41
After trying to add my cordova plugin localy instead of referencing tar ball without success, I decided to publish it in the plugin registry. I was then able to add it to my project by specifying its version number. But when I tried to build it, I still got the "Error: The APK file for the Android build was not found." message...

**Comment by glasser** [comment] 2015-06-23 00:37
Thanks for the report. The MDG core team is focused on some other areas of the platform right now, so we may not get to a fix for this soon. We’d welcome community help on this and other Cordova bugs in the form of PRs or other supporting information.

**Comment by caio-ribeiro-pereira** [comment] 2015-06-23 00:54
Thanks!! I hope get a new update soon, because I can't build a new version of my app =/

**Comment by RaphaelRoyerRivard** [comment] 2015-06-23 18:01
I found that the error is caused by syntax errors in the Java files of one of the Cordova Plugins. Since the error message and stack trace are unclear, it was not easy to find out. You can have a more representative error message by calling `meteor run android-device --verbose`.

I guess the right thing to do before closing the issue would be to call --verbose on the commands executed by `meteor build --verbose`.

**Comment by udiedrichsen** [comment] 2015-06-24 05:36
@RaphaelRoyerRivard I not sure if you checked my example repo:
https://github.com/udiedrichsen/polymer-apk-build-failed

In this repo are zero cordova plugins!

I also tried to build with the --verbose options. They are a lot of debug message, but they didn't help.
May be others apk builds are failed by corrupt cordova plugins, but this issues is something different.

**Comment by andresfelipemendez** [comment] 2015-07-06 13:56
+1 
i have the same issue, the moment i add polymer to the project i get this error 
```
VULCANIZE=true meteor build ../build --server=http://45.55.160.57

/Users/felipemendez/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: The APK file for the Android build was not found.
    at findApkPath (/Users/felipemendez/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:970:11)
    at /Users/felipemendez/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:950:21
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/felipemendez/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at buildCommand (/Users/felipemendez/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:933:29)
    at Command.main.registerCommand._.extend.name [as func] (/Users/felipemendez/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:746:12)
    at /Users/felipemendez/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
Felipes-MBP:CIApplicados felipemendez$ VULCANIZE=true meteor build ../build --server=http://45.55.160.57
```

**Comment by pmwisdom** [comment] 2015-07-09 19:49
Strangely enough I get this when trying to get crosswalk to work with meteor. May be related?

Error: The APK file for the Android build was not found.

    at findApkPath (/Users/Paul/.meteor/packages/meteor-tool/.1.1.3.1qxxxi7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:970:11)
    at /Users/Paul/.meteor/packages/meteor-tool/.1.1.3.1qxxxi7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:950:21
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/Paul/.meteor/packages/meteor-tool/.1.1.3.1qxxxi7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at buildCommand (/Users/Paul/.meteor/packages/meteor-tool/.1.1.3.1qxxxi7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:933:29)
    at Command.main.registerCommand._.extend.name [as func] (/Users/Paul/.meteor/packages/meteor-tool/.1.1.3.1qxxxi7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:746:12)
    at /Users/Paul/.meteor/packages/meteor-tool/.1.1.3.1qxxxi7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23

**Comment by martijnwalraven** [comment] 2015-10-23 00:42
Is still an issue with the updated Cordova integration in Meteor 1.2?

**Comment by andresfelipemendez** [comment] 2015-10-23 09:16
the problem seems to be the vulcanise package, if i import the libraries directly it can build for android no problem but with vulcanise throw the error

**Comment by Slanman3755** [comment] 2016-01-06 18:00
When I build a new blank Meteor project with just iron router and crosswalk it does not generate an APK either.

**Comment by andresfelipemendez** [comment] 2016-01-06 18:11
what your error message?

**Comment by Slanman3755** [comment] 2016-01-06 19:22
That's the odd part.  There is no error message that I can see even with verbose output.  It just doesn't create an apk file in the build directory.

**Comment by udiedrichsen** [comment] 2016-01-07 08:26
I tried today my own test repo:
https://github.com/udiedrichsen/polymer-apk-build-failed

and it works with meteor 1.2.1
-rw-r--r--   1 doedel  staff  340757 Jan  7 09:19 release-unsigned.apk

The APK was generated !

**Comment by brylie** [comment] 2016-02-15 03:21
Please support web component alignment in Blaze 2. See issue #6236.

**Comment by martijnwalraven** [comment] 2016-02-19 10:28
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion

**Closed by martijnwalraven** 2016-02-19 10:28 UTC
Labels: backlog, Project:Mobile
