### ISSUE TITLE
Random fiber lifecycle crash on project refreshing

### ISSUE THREAD

**Issue by Deadly0** [meteor/meteor#8958] opened 2017-07-28 14:07 UTC
When meteor starts refreshing server or client code when a file was changed random dev server crash happens.

NPM error debug:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start',
1 verbose cli   '--scripts-prepend-node-path=auto' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle finmanager@~prestart: finmanager@
6 silly lifecycle finmanager@~prestart: no script for prestart, continuing
7 info lifecycle finmanager@~start: finmanager@
8 verbose lifecycle finmanager@~start: unsafe-perm in lifecycle true
9 verbose lifecycle finmanager@~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Projects\riverstart\fin-manager\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Redis\;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\Deadly\AppData\Local\.meteor\;C:\Program Files\Mercurial;C:\Programms\executable;C:\Users\Deadly\AppData\Local\Microsoft\WindowsApps;C:\Python27\Scripts;C:\Users\Deadly\AppData\Roaming\npm;C:\OpenServer\modules\php\PHP-5.6;
10 verbose lifecycle finmanager@~start: CWD: C:\Projects\riverstart\fin-manager
11 silly lifecycle finmanager@~start: Args: [ '/d /s /c', 'meteor run' ]
12 silly lifecycle finmanager@~start: Returned: code: 3221225477  signal: null
13 info lifecycle finmanager@~start: Failed to exec start script
14 verbose stack Error: finmanager@ start: `meteor run`
14 verbose stack Exit status 3221225477
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid finmanager@
16 verbose cwd C:\Projects\riverstart\fin-manager
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start" "--scripts-prepend-node-path=auto"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error finmanager@ start: `meteor run`
22 error Exit status 3221225477
23 error Failed at the finmanager@ start script 'meteor run'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the finmanager package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     meteor run
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs finmanager
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls finmanager
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Packages
```
accounts-base@1.3.1
accounts-password@1.4.0
alanning:roles@1.2.16
allow-deny@1.0.6
autoupdate@1.3.12
babel-compiler@6.19.4
babel-runtime@1.0.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-tools@1.0.10
boilerplate-generator@1.1.1
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
check@1.2.5
coffeescript@1.12.6_1
ddp@1.3.0
ddp-client@2.0.0
ddp-common@1.2.9
ddp-rate-limiter@1.0.7
ddp-server@2.0.0
deps@1.0.12
diff-sequence@1.0.7
dynamic-import@0.1.1
ecmascript@0.8.1
ecmascript-runtime@0.4.1
ecmascript-runtime-client@0.4.2
ecmascript-runtime-server@0.4.1
ejson@1.0.13
email@1.2.3
es5-shim@4.6.15
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.12
id-map@1.0.9
jagi:astronomy@2.4.8
jagi:astronomy-softremove-behavior@2.0.6
jagi:astronomy-timestamp-behavior@2.0.0
jquery@1.11.10
livedata@1.0.18
localstorage@1.1.1
logging@1.1.17
mdg:validation-error@0.5.1
meteor@1.7.0
meteor-base@1.1.0
meteortoys:toykit@4.0.1
minifier-css@1.2.16
minifier-js@2.1.1
minimongo@1.2.1
modules@0.9.2
modules-runtime@0.8.0
mongo@1.1.19
mongo-id@1.0.6
msavin:mongol@4.0.1
npm-bcrypt@0.9.3
npm-mongo@2.2.24
observe-sequence@1.0.16
ordered-dict@1.0.9
percolate:migrations@1.0.2
promise@0.8.9
random@1.0.10
rate-limit@1.0.8
reactive-dict@1.1.9
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
reywood:publish-composite@1.5.2
routepolicy@1.0.12
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.2.4
spacebars@1.0.15
spacebars-compiler@1.1.2
srp@1.0.10
standard-minifier-css@1.3.4
standard-minifier-js@2.1.1
stylus@2.513.9
templating@1.3.2
templating-compiler@1.3.2
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:publish-counts@0.8.0
tracker@1.1.3
ui@1.0.13
underscore@1.0.10
urigo:static-html-compiler@0.1.8
urigo:static-templates@0.1.3
url@1.1.0
webapp@1.3.17
webapp-hashing@1.0.9
```

npm deps
```
 "@uirouter/angularjs": "^1.0.1",
    "angular": "^1.6.4",
    "angular-animate": "^1.6.4",
    "angular-aria": "^1.6.4",
    "angular-material": "^1.1.1",
    "angular-material-data-table": "^0.10.9",
    "angular-messages": "^1.6.4",
    "angular-meteor": "^1.3.11",
    "angular-moment": "^1.0.1",
    "angular-numeraljs": "^2.0.0",
    "angular-scalyr": "^1.0.4",
    "babel-runtime": "^6.18.0",
    "bcrypt": "^1.0.1",
    "highcharts": "^5.0.5",
    "highcharts-ng": "0.0.13",
    "lodash": "^4.17.2",
    "meteor-node-stubs": "~0.2.0",
    "module-bank-api": "^1.2.0",
    "moment": "^2.17.1",
    "node-schedule": "^1.2.3",
    "numeral": "^2.0.6"
```

I have this issue in all my projects where i use angularjs. So now i have 1 project with react on frontend and looks like this issue is gone for this project, but im not sure.

Meteor version: have this problem for a long time with meteor 1.4.x-1.5.x
OS: Windows 8.1/10, Ubuntu 16/17

**Comment by hwillson** [comment] 2017-11-24 18:55
Any chance you could supply a reproduction (using Meteor 1.6) that shows this happening? A reproduction will greatly help with troubleshooting, and help pinpoint whether this is a Meteor issue or not.

Closing for now - please post back if you're still having this problem, ideally with a reproduction. Thanks!

**Closed by hwillson** 2017-11-24 18:55 UTC

**Comment by vetedde** [comment] 2018-02-13 11:04
Good day,
I have this problem, when do production. I use Meteor 1.6.0.1 and angular2

**Comment by madc0w** [comment] 2018-05-29 09:13
I have this in dev even since a recent update (1.6.01, maybe?)

Please re-open this issue, as it is quite disruptive to development!

**Comment by sarachai** [comment] 2018-06-03 04:33
This was happening to me in dev (meteor@1.6.1.1 / node@v8.11.1). Same error code 3221225477.

Temporarily fixed it by wrapping the _makePromise method's promise in a try/catch in meteor-tool\1.6.1_1\mt-os.windows.x86_64\tools\runners\run-app.js

As per this warning from Node:
[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any more info about this would be great.

**Comment by madc0w** [comment] 2018-06-03 16:48
@sarachai Thanks, but that had no impact for me.  Server still crashing every few minutes.

Here is what I did to _makePromise:

`   _makePromise: function (name) {
	var self = this;
	try {
		return new Promise(function (resolve) {
			try {
				self._promiseResolvers[name] = resolve;
			} catch(e) {
				console.log("_makePromise callback failed", e);
			}
		});
	} catch(e) {
		console.log("_makePromise failed", e);
	}
  },
`

**Comment by sarachai** [comment] 2018-06-03 20:48
@madc0w Darn, that's too bad! That's pretty much what I did (just the outer try/catch). Mine was crashing every single time an automatic reload was spawned (e.g. saved a file change), and the log file says 'failed to exec start script'.

**Comment by madc0w** [comment] 2018-06-03 21:45
For anyone else having this issue: I found some advice in [this thread](https://github.com/sass/node-sass/issues/1326) that turned out to do the trick:  Upgrade git!  I upgraded from  2.13.1.windows.2 to 2.17.1.windows.2, and lo and behold... I this inscrutable error has ceased.  Well, almost.  It did happen exactly once today....

**Comment by sarachai** [comment] 2018-06-04 22:54
ugh, it was a fluke. it stopped working after a total server restart. no idea what the pattern was, but sometimes it would work, and sometimes it wouldn't. i ended up reinstalling meteor completely and also wiping out my own repo and recloning. but it still didn't work (wouldn't even run this time) until i updated just now to meteor 1.7!
