### ISSUE TITLE
[1.3-rc.6] Promise package failing to build

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#6560] opened 2016-03-22 19:12 UTC
I'm getting the following error when I try to run my app:

```
[[[[[ ~/workspace/casalova_map ]]]]]

=> Started proxy.
=> Started MongoDB.

/Users/clayne/.meteor/packages/less/.2.5.5-rc.6.1lz13h2++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
AssertionError: false === true
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:153:12)
    at /tools/isobuild/import-scanner.js:140:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:119:11)
    at /tools/isobuild/compiler-plugin.js:726:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:696:19)
    at ServerTarget._emitResources (/tools/isobuild/bundler.js:890:8)
    at /tools/isobuild/bundler.js:657:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ServerTarget.make (/tools/isobuild/bundler.js:648:18)
    at /tools/isobuild/bundler.js:2519:14
    at /tools/isobuild/bundler.js:2587:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2471:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

**Comment by benjamn** [comment] 2016-03-22 19:29
Can you provide a reproduction? Is there any chance your project contains two files whose paths differ only in case?

**Comment by clayne11** [comment] 2016-03-22 19:59
I doubt I can provide a reproduction. I'm also pretty sure that I don't have two files whose paths differ only in case.

I have over 100 packages I've created and over 170 packages total installed in my project. It's running fine under 1.2 and I was able to run under 1.3-rc.4 as long as I have `chimp` installed in my `node_modules` folder.

**Comment by benjamn** [comment] 2016-03-22 20:07
If you can reproduce this running meteor from a [checkout](https://github.com/meteor/meteor#slow-start-for-developers), you might try changing [this line](https://github.com/meteor/meteor/blob/29903ce2db073f2bb4718068303f8cd38d424d23/tools/isobuild/import-scanner.js#L153) to provide more debugging output, e.g.
```js
if (oldFile.lazy !== newFile.lazy) {
  console.log("old", oldFile);
  console.log("new", newFile);
  throw new Error("laziness mismatch");
}
```

**Comment by clayne11** [comment] 2016-03-22 20:24
Alright I'll try that, thanks.

**Comment by clayne11** [comment] 2016-03-23 02:33
I ran the project under `1.3-rc.8` from checkout and inserted some logging lines as you suggested.

It's complaining that the laziness doesn't mismatch but I only have one instance of this file and I'm not using `mainModule` in this package at all.

```
old { type: 'js',s.osx.x86_64                |
  data: <Buffer 76 61 72 20 5f 65 6e 74 69 74 69 65 73 20 3d 20 72 65 71 75 69 72 65 28 27 65 6e 74 69 74 69 65 73 27 29 3b 0a 0a 76 61 72 20 5f 65 6e 74 69 74 69 65 73 ...>,
  sourcePath: 'server/rentSyncSync-service.js',
  servePath: '/packages/casalova_rent-sync/server/rentSyncSync-service.js',
  hash: '00fd7a210533a44f1b7cd9d29814afe14f525947',
  lazy: false,
  bare: false,
  mainModule: false,
  imported: true,
  installPath: 'node_modules/meteor/casalova:rent-sync/server/rentSyncSync-service.js' }
new { type: 'js',
  data: <Buffer 76 61 72 20 5f 65 6e 74 69 74 69 65 73 20 3d 20 72 65 71 75 69 72 65 28 27 65 6e 74 69 74 69 65 73 27 29 3b 0a 0a 76 61 72 20 5f 65 6e 74 69 74 69 65 73 ...>,
  sourcePath: 'server/rentSyncSync-Service.js',
  servePath: '/packages/casalova_rent-sync/server/rentSyncSync-Service.js',
  hash: '00fd7a210533a44f1b7cd9d29814afe14f525947',
  lazy: true,
  bare: false,
  mainModule: false,
  imported: false,
  installPath: 'node_modules/meteor/casalova:rent-sync/server/rentSyncSync-Service.js' }

/Users/clayne/workspace/meteor/.meteor/packages/juliancwirko_postcss/.1.0.0-rc.2.7f5osk++os+web.browser+web.cordova/plugin.minifier-postcss.os/npm/node_modules/meteor/promise/node_modules/meteor/promise/npm/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: laziness mismatch
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:170:13)
```

**Comment by clayne11** [comment] 2016-03-23 02:37
Found the issue - it looks like I had a capitalization mismatch between the package.js file and the actual file name. The actual file was rentSyncSync-Service.js and the package.js file had rentSyncSync-service.js.

That's a really nasty bug that can happen with a typo. I hope a better error message can be made than this.

**Comment by Pushplaybang** [comment] 2016-03-29 06:11
just upgraded and having the same issue. :/

**Comment by Pushplaybang** [comment] 2016-03-29 07:23
Seems to be slightly different.

```sh
/Users/paul/.meteor/packages/coffeescript/.1.0.15.1ba6ro++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
AssertionError: false === true
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:153:12)
    at /tools/isobuild/import-scanner.js:140:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:119:11)
    at /tools/isobuild/compiler-plugin.js:756:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:726:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:910:8)
    at /tools/isobuild/bundler.js:677:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:668:18)
    at /tools/isobuild/bundler.js:2509:14
    at /tools/isobuild/bundler.js:2599:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/paul/.meteor/packages/meteor-tool/.1.3.0_3.1b54dt7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2598:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2490:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

**Comment by clayne11** [comment] 2016-03-29 13:55
The error in `promise_server` is a red herring. It's actually something else that's wrong. Try following the advice @benjamn gave me earlier in the thread of running Meteor from a checkout and adding some logging code around the line that's failing so that you can get some more insight.

My issue was related to file capitalization (aka a typo). Not sure if yours is the same but the first step is to add some logging and see what's going on.

**Comment by Pushplaybang** [comment] 2016-03-29 14:22
Yeah its a very deceptive error message.

I also had an issue where I was including a file in a custom package with `api.addFiles('Offensive.js', 'client')` and the file was actually named with a lowercase letter, `offensive.js`,  ending all productivity today.

thanks for the help.

**Comment by adamgedney** [comment] 2016-03-30 12:49
Same thing here. Just upgraded to 1.3 this morning. Same error message as @Pushplaybang. Turned out that in my package.js one of my api.addFiles items was written with an uppercase, when in fact I had named the file with a lowercase in my actual package folder.

**Comment by Pushplaybang** [comment] 2016-04-01 10:36
considering the number of packages most meteor apps probably have, it'd be great if this was a coherent error, not sure if that's possible but I suspect we won't be the last to hit this issue.

**Comment by benjamn** [comment] 2016-04-16 00:49
This should be fixed if you do `meteor update --release 1.3.2.1` (in fact, the one difference between 1.3.2 and 1.3.2.1 was this bug fix).

**Closed by benjamn** 2016-04-16 00:49 UTC
Labels: confirmed, known-fix

**Comment by Pushplaybang** [comment] 2016-04-16 07:59
@benjamn thanks.

**Comment by kurapikats** [comment] 2016-06-10 09:09
I had the same problem when I try to run 2 different apps on same machine.
Here's some info on my setup and how I've fixed it.
===============
**Error Message**: 
/Users/kurapikats/.meteor/packages/less/.2.5.5-rc.6.1lz13h2++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
**OS**: OSX El Capitan 
**Meteor**: v1.3.2.4
**Steps to reproduce**: 
  **Scenario 1**:
  a1. Run meteor project (ProjectZ) on port 3000
  a2. Run another meteor project (ProjectX) on port 4000
     This will cause ProjectX to fail and throws the error message above ^.

  **Scenario 2**:
  b1. Run project (ProjectX) on port 4000
  b2. Run project (ProjectZ) on port 3000 
    This will cause ProjectZ to fail and throws the error message above ^.

**Solution**: 
backup/delete _node_modules_ folders on both projects root dir, 
then re-run 'npm i' to re-install packages
