### ISSUE TITLE
Meteor 1.4.x bug with minifying files in production vs dev

### ISSUE THREAD

**Issue by akshatster** [meteor/meteor#7994] opened 2016-10-31 09:37 UTC
Reproduction

```
meteor create testbug
cd testbug
meteor npm install --save meteor-node-stubs bufferutil utf-8-validate diffusion
```

Add the following to a file
```
//testbug/client/main.js
import diffusion from 'diffusion';
```

Run meteor (no issues, **no javascript errors**)
```
meteor
```

But this has an issue:

```
meteor --production
```

Running in production has a javascript error, out of nowhere that isn't visible in dev mode. The issue must be a problem with minifying.

The problem also comes about in production where a single error breaks the entire app, however the issue is that this error isn't visible in dev mode as would be expected.

**Comment by lucfranken** [comment] 2016-11-07 08:16
This looks like a duplicate or very strongly related to https://github.com/meteor/meteor/issues/5517

**Comment by abernix** [comment] 2016-11-10 14:27
Thank you for reporting this issue and for including the reproduction.  Much appreciated.  I can confirm this behavior is exhibited by the reproduction you have provided.

As @lucfranken stated this does _seem_ to be strongly related to #5517, but as that is a feature issue I'm going to leave this open.  It also seems to maybe be a slightly different issue.

This is also now related to #8020.  I'm going to leave this open for now since it has the reproduction and see if we can confirm it's the same root problem as as #8020.  I'd also like to test this against newer versions of Uglify `harmony` branch as soon as possible.

**Comment by krem06** [comment] 2016-11-28 11:42
+ 1 on this issue, it's driving me crazy with so many hours looking for a fix or workaround... Is it a meteor or uglify problem ? Any hope to get a proper fix soon ?

Best regards

**Comment by abernix** [comment] 2016-12-08 15:00
As I've mentioned, this issue is related to #8020 but not the same (different ECMAscript features involved).  However, if you're experiencing this problem you may be interested in [my comment here](https://github.com/meteor/meteor/issues/8020#issuecomment-265758830).  It does not fix the reproduction provided in the original post here, but it does seem to fix some other cases.

**Comment by abernix** [comment] 2017-06-19 15:45
This is fixed thanks to the fallback to `babili` which now occurs when Uglify encounters unknown ECMAScript tokens.  Though, this is still a duplicate of #8020, ultimately so follow there if you're still encountering problems with this.

Thanks for reporting this originally! :smile:

**Closed by abernix** 2017-06-19 15:45 UTC
Labels: bug, confirmed, Impact:few
