### ISSUE TITLE
Android target: cmd: Command failed with exit code 1 Error output:

### ISSUE THREAD

**Issue by nitiz143** [meteor/meteor#9575] opened 2018-01-25 11:50 UTC
Some one please help to fix it
✗ Android target: cmd: Command failed with exit code 1 Error output:
  Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
  at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
  at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
  at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
  at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
  at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
  Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
  ... 5 more
SUCCESS Gradle

**Comment by klaussner** [comment] 2018-01-25 11:55
This is a duplicate of #9510. You have to install Java 8 to work with the Android SDK because the current SDK version is incompatible with Java 9. 🙂

**Closed by klaussner** 2018-01-25 11:55 UTC
