### ISSUE TITLE
Meteor-Cordova iOS app - After some time in bg app completely loses connection to a  local web server - http://localhost:{myPortNumber}

### ISSUE THREAD

**Issue by grundmanise** [meteor/meteor#8324] opened 2017-02-07 11:30 UTC
**Versions:**
- METEOR@1.4.2.3
- iOS 10.2
- iPhone 5s

**Platforms:**
- browser
- ios
- server

**Packages:**
- meteor-base@1.0.4             # Packages every Meteor app needs to have
- mobile-experience@1.0.4       # Packages for a great mobile UX
- mongo@1.1.14                   # The database Meteor supports right now
- blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
- reactive-var@1.0.11            # Reactive variable for tracker
- jquery@1.11.10                  # Helpful client-side library
- tracker@1.1.1                 # Meteor's client-side reactive programming library

- standard-minifier-js@1.2.1    # JS minifier run for production mode
- es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
- ecmascript@0.6.1              # Enable ECMAScript2015+ syntax in app code
- reactive-dict@1.1.8

- kadira:flow-router
- kadira:blaze-layout
- fourseven:scss
- session@1.1.7
- http@1.2.10

- aldeed:simple-schema
- aldeed:collection2

- fastclick@1.0.13
- dburles:google-maps
- abpetkov:switchery
- seba:minifiers-autoprefixer
- zimme:active-route

- momentjs:moment
- udondan:slick
- nolimits4web:swiper
- accounts-ui@1.1.9
- btafel:accounts-facebook-cordova
- philippspo:momentum-flow-router
- dschulz:jquery-qrcode
- shell-server@0.2.1
- ground:db
- percolate:momentum
- joncursi:socket-io-client
- mrt:jquery-easing

**Cordova plugins:** 

- com.phonegap.plugins.facebookconnect@file://../cordova_plugins/Facebook/
- com.phonegap.plugins.nativesettingsopener@file://../cordova_plugins/Cordova-open-native-settings/
- cordova-background-geolocation-lt@2.2.0
- cordova-plugin-EGAnimatedFullScreenImage@https://github.com/grundmanise/cordova-plugin-EGAnimatedFullScreenImage.git#d8da9f9b965bf08084466328aa62c134862af5b7
- cordova-plugin-actionsheet@2.3.1
- cordova-plugin-appavailability@0.4.2
- cordova-plugin-contacts@2.2.1
- cordova-plugin-device@1.1.3
- cordova-plugin-dialogs@1.3.1
- cordova-plugin-googlemaps@https://github.com/grundmanise/cordova-plugin-googlemaps.git#6ad1874ae7312ef8b0c63e1889c6f53bb71882ec
- cordova-plugin-inappbrowser@1.5.0
- cordova-plugin-meteor-webapp@https://github.com/grundmanise/cordova-plugin-meteor-webapp.git#011d9e8086628861d5b37c5aa26f71ac70f986de //@1.4.1 with this fix: https://github.com/meteor/cordova-plugin-meteor-webapp/issues/24
- cordova-plugin-nativestorage@2.2.0
- cordova-plugin-splashscreen@4.0.1
- cordova-plugin-wkwebview-engine@https://github.com/grundmanise/cordova-plugin-wkwebview-engine.git#f4a01b4d5fadb905ca28c556736f6bdac6416353
- cordova-plugin-x-socialsharing@5.1.2
- ionic-plugin-keyboard@2.2.1
- onesignal-cordova-plugin@2.0.10
- twitter-connect-plugin@file://../cordova_plugins/twitter-connect-plugin/
- uk.co.workingedge.phonegap.plugin.launchnavigator@3.2.1

**Problem**
After the app was some time in bg state when I open the "minimized" app it loses connection to the  local web server:

- Safari console outputs: `could not connect to http://localhost:{myAppPortNumber}`
- Xcode console outputs: `"App startup timed out, reverting to last known good version"`.

`location.reload();` - does not work - console outputs the same error: `could not connect to http://localhost:{myAppPortNumber}`.
Restarting the app from the `CDVWKWebViewEngine.m` with `[(WKWebView*)_engineWebView reload];` - does not work.
Restarting the app from the `WebAppLocalServer.swift` using
```
    func forceReload() {
        if let webView = self.webView as? WKWebView {
            webView.reloadFromOrigin()
        }
    }
```
does not work.

The only solution is to completely close the app and reopen it.
(Note: all these restart & reload methods work until the app loses connection to the local web server.)

Does anyone have any thoughts?
1) Is it possible to completely reload a cordova app? Google & SO says- 'no'
2) Any thought on how to fix it?

p.s. I even use the solution from this isse https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/221 that should prevent the `GCDWebServer` from ever stopping.. it works for the BG location, but does not prevent my app from losing a connection to the `localhost` (local web server).

**Comment by grundmanise** [comment] 2017-02-17 21:37
Restarting `localserver` every time the app enters foreground does not help either. (https://github.com/grundmanise/cordova-plugin-meteor-webapp/commit/9a414d88f8a84249009e22d663298fd2dcbb6eab)

**Comment by awwx** [comment] 2017-05-09 12:49
Possibly a duplicate of https://github.com/meteor/cordova-plugin-meteor-webapp/issues/24 ?

**Comment by grundmanise** [comment] 2017-05-13 09:06
@awwx It's not the same. As stated above I already use:

> cordova-plugin-meteor-webapp@https://github.com/grundmanise/cordova-plugin-meteor-webapp.git#011d9e8086628861d5b37c5aa26f71ac70f986de  //@1.4.1 with this fix: meteor/cordova-plugin-meteor-webapp#24

**Comment by macrozone** [comment] 2017-06-01 10:52
@grundmanise did you find a solution or workaround yet for this problem in your project? We are really suffering from this problem and I don't really know what to do anymore.

**Comment by grundmanise** [comment] 2017-06-01 10:55
@macrozone Unfortunately no. We are currently migrating to RN...

**Comment by Slavrix** [comment] 2017-07-19 06:41
We are experiencing a this (or similar) issue. The first step we have taken is to add a call to Meteor.reconnect() within the platform resume event.

Though this hasn't fully fixed out issue yet either.

**Comment by hwillson** [comment] 2017-11-28 17:25
Since this is already being tracked in https://github.com/meteor/cordova-plugin-meteor-webapp/issues/27, let's close it here. Thanks!

**Closed by hwillson** 2017-11-28 17:25 UTC
