### ISSUE TITLE
os.json error

### ISSUE THREAD

**Issue by ayushchd** [meteor/meteor#7888] opened 2016-10-07 15:54 UTC
Getting this error when trying to build our application today:

```
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-1qo8wl9/os.json'
    at Error (native)
```

On METEOR@1.3.3.1

**Comment by abernix** [comment] 2016-10-07 16:03
Duplicate of #7806.  Please browse/[search existing issues before opening new issues](https://github.com/meteor/meteor/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22Error%3A%20ENOENT%3A%20no%20such%20file%20or%20directory%22).

**Closed by abernix** 2016-10-07 16:03 UTC
