### ISSUE TITLE
[1.3-modules.1] updating npm deps very slow

### ISSUE THREAD

**Issue by mcbain** [meteor/meteor#5863] opened 2015-12-22 08:29 UTC
Every change in my package-client javascript files taken >30sec to be visible due `updating npm dependencies --`

``` javascript
Npm.depends({
  'big-js': '3.1.3',
  'react' : '0.14.3',
  'react-dom' : '0.14.3',
  'material-ui' : '0.14.0-rc2',
  "elasticsearch": "10.0.1"
});
```

**Comment by mcbain** [comment] 2015-12-28 13:41
Still slow with 1.3-modules.2. 
Figured out that `registry.npmjs.org` is hard coded and pinged before every module....

```bash
updating npm dependencies -- yahoo-finance, big-js, react,
react-dom, material-ui, elasticsearch, redux, react-redux, redux-logger,
redux-thunk, webdriverio...
Doing HTTP request:  GET http://registry.npmjs.org
Doing HTTP request:  GET http://registry.npmjs.org
Doing HTTP request:  GET http://registry.npmjs.org
Doing HTTP request:  GET http://registry.npmjs.org
Doing HTTP request:  GET http://registry.npmjs.org
Doing HTTP request:  GET http://registry.npmjs.org
Doing HTTP request:  GET http://registry.npmjs.org
Doing HTTP request:  GET http://registry.npmjs.org
Doing HTTP request:  GET http://registry.npmjs.org
Doing HTTP request:  GET http://registry.npmjs.org
Doing HTTP request:  GET http://registry.npmjs.org
```

**Comment by mcbain** [comment] 2015-12-28 16:25
btw. Using a local npm server also shows that always all npm packages are requested.

```
...
2015-12-28T16:23:08.420Z INFO,REQUEST 172.17.0.1 GET /source-map-url 304
2015-12-28T16:23:08.476Z INFO,REQUEST 172.17.0.1 GET /atob 304
2015-12-28T16:23:08.484Z INFO,REQUEST 172.17.0.1 GET /resolve-url 304
2015-12-28T16:23:08.516Z INFO,REQUEST 172.17.0.1 GET /balanced-match 304
2015-12-28T16:23:08.584Z INFO,REQUEST 172.17.0.1 GET /concat-map 304
2015-12-28T16:23:08.640Z INFO,REQUEST 172.17.0.1 GET /crc32-stream 304
2015-12-28T16:23:08.647Z INFO,REQUEST 172.17.0.1 GET /node-int64 304
2015-12-28T16:23:08.677Z INFO,REQUEST 172.17.0.1 GET /cryptiles 304
2015-12-28T16:23:08.748Z INFO,REQUEST 172.17.0.1 GET /sntp 304
2015-12-28T16:23:08.780Z INFO,REQUEST 172.17.0.1 GET /ctype 304
2015-12-28T16:23:08.814Z INFO,REQUEST 172.17.0.1 GET /hoek 304
2015-12-28T16:23:08.815Z INFO,REQUEST 172.17.0.1 GET /boom 304
2015-12-28T16:23:08.843Z INFO,REQUEST 172.17.0.1 GET /amdefine 304
...
```

**Comment by timbotnik** [comment] 2015-12-29 23:10
I wonder if this could have some relationship with #5269.

**Comment by avital** [comment] 2016-01-21 19:34
Is this new to 1.3?

**Comment by benjamn** [comment] 2016-01-21 19:34
cc @dgreensp who is working on tool performance

**Comment by marbemac** [comment] 2016-02-21 02:58
@dgreensp I'm seeing this as well. This happens with several NPM packages, but material is a good example.

Installed via npm, imported normally like so:

```
import TextField from 'material-ui/lib/text-field';
```

Whenever I add or remove a material-ui import, the subsequent rebuild time jumps from ~4-5 seconds to ~100 seconds. According to the profiler, it seems as if the "linker File#getPrelinkedOutput" step is the culprit (~95 seconds).

https://gist.github.com/marbemac/cf9f7f8c2c45116c57d1#file-meteor-1-3-beta-11-rebuild-profile-L53

**Comment by BlooJeans** [comment] 2016-02-22 15:45
Also experiencing slow builds on 1.3 beta 11 due to linker File#getPrelinkedOutput

We're trying to get webpack to work nicely with our build.  We have HMR working on client which takes ~7 seconds to hot swap modules (and then an additional ~10 seconds to actually rebuild client for future cold-loads).  Changing a server file, however, takes ~90 seconds.  If I only change whitespace in a server file, the server rebuilds in ~15s.  Not too sure what's useful, so I made 3 different gists with 3 scenarios in the hope that there's a clue somewhere in here.

**Starting meteor:**
https://gist.github.com/BlooJeans/09bcb7d6bc2901d0ad6d
Note that client is slow (~45s), server is fast (~23s), at least compared to 90s

**Changing a server file:**
https://gist.github.com/BlooJeans/610ac9cd73daebea1d01#file-gistfile1-txt-L71

> linker File#getPrelinkedOutput 92,270 ms (1)

Assuming I'm reading the METEOR_PROFILE=50 output correctly, it seems interesting that my output shows getPrelinkedOuput getting called once (1) whereas marbemac's is getting called 783 times?
And it looks like marbemac's slow getPrelinkedOutput is happening during makeClientTarget, whereas mine is slow during makeServerTarget?

**Changing a client file:**
https://gist.github.com/BlooJeans/0cd6ddc2e6e83dc207b0

**Comment by marbemac** [comment] 2016-02-22 15:52
In case it's important, I'm running with METEOR_PROFILE=1.

@BlooJeans yeah for us it's happening on the client. It seems to happen when we mess around with the imports at the top of a file (in particular, adding/removing material-ui imports triggers this issue quite often). I'm not sure if it would happen on the server side as well, if these files were in a shared folder. I would pull my hair out if that 100 seconds doubled!

**Comment by useruser1** [comment] 2016-06-26 19:29
Meteor 1.3.4.1 still very slow rebuilds when using "imports/ui..." methodology

**Comment by filipenevola** [comment] 2017-07-20 16:57
Hello @benjamn , is someone working on this?

Is @dgreensp doing that? I'm only using aws-sdk and even with only one dependency it is very slow.

That is anything we can do to help? Any tips for a new PR?

**Comment by filipenevola** [comment] 2017-08-31 17:41
@abernix sorry to mention you but I really want to solve this issue, is someone working on that? Can you give me tips on how can I have this fixed?

**Comment by abernix** [comment] 2017-08-31 19:55
@filipenevola What sort of times are you seeing for "updating npm dependencies"?  Are you installing your npms with `meteor npm install` or are you utilizing `Npm.depends` within packages?  Also, what platform are you on?  Do you have something which could be modifying the directories where your npm files live? (They shouldn't normally be rebuilt frequently!)

**Comment by filipenevola** [comment] 2017-09-01 15:27
Hello @abernix, let me explain to you my project structure.

I have two Meteor application sharing code (one is a mobile app and the other one is a admin dashboard), I share the common code using a local package with METEOR_PACKAGE_DIR variable, my local package has a Npm.depends for aws-sdk.

I think when I run my first app it uses the .npm folder inside my package and when I try to start my second app it tries to use the same .npm and that is my problem because now I can't run both at the same time. Sometimes I got an error and sometimes it just stay running 'updating npm dependencies' forever. Yesterday I noticed that if I remove the .npm folder from my package before run one of my apps it always works.

My biggest problem is to run both apps together but on my Jenkins CI even with two complete different workspaces (not sharing any file) I have to wait a long time always on 'updating npm dependencies', that is not a huge problem but it takes time on every deploy.

What do you think? Any solution or other way to avoid these problems?

**Comment by JesalR** [comment] 2017-10-10 08:50
I'm having a very similar issue to @filipenevola 

We have many microservices as Meteor servers that use local packages to share certain bits of code. For one of our front-end microserverices, any run causes a full rebuild of the local packages that it uses, eventually causing all other servers to restart as they detect a change in one of the packages they are using. This causes those servers to try and rebuild the same local package, and eventually leads to an error along the lines of `Error: ENOENT: no such file or directory, lstat '/Users/blinkpooler/dev/blink/sharedpackages/blinkddpmeteor/.npm/package/node_modules/ajv/lib/keyword.js'`

The particular front-end server uses React with Flow, and so I imagine build differently to the way the other servers are built, including building the local packages differently?

That's a guess, but I can't pin down any other real differences between our servers. I imagined when a local package was rebuilt it would be rebuilt within the same folder as the server that uses it, not over its source location

**Comment by hwillson** [comment] 2017-12-01 18:16
Hi all - the first half of this issue thread relates to build tool performance issues with Meteor versions  before 1.4.2. Meteor 1.4.2 introduced numerous build tool performance improvements, that have addressed many of the reported build tool problems. I think it's safe to say the first half of this issue thread has been addressed by newer Meteor versions.

Regarding the second half starting at https://github.com/meteor/meteor/issues/5863#issuecomment-316766390, we'll need more specific details to help troubleshoot this further. If anyone is able to provide a runnable reproduction that demonstrates `updating npm dependencies` slowness, that would greatly help. That being said, since most of this issue thread relates to build tool performance problems that have since been addressed, I'd recommend creating a new issue for any `updating npm dependencies` issues found as of Meteor 1.6. This way we can stay focused on current problems in a new issue thread, instead of having to review outdated issue comments here. Thanks!

**Closed by hwillson** 2017-12-01 18:16 UTC
Labels: Project:Isobuild:Performance, Project:NPM

**Comment by zhe1ka** [comment] 2023-08-22 11:39
I faced the same problem. did anyone find a solution?
