### ISSUE TITLE
[1.3] Files in local packages are processed even if they're unused; can't addAsset or publish

### ISSUE THREAD

**Issue by gadicc** [meteor/meteor#6217] opened 2016-02-11 15:56 UTC
Just noticed this one now.  Files that aren't referenced in `package.js` nor imported are still processed (checked for variable assignments, added to watch list, etc) and can break the build process.  Such "breaking files" can't be used with `api.addAsset()` nor can the package be published.

Repro: https://github.com/gadicc/meteor-package-file-eval

In particular see https://github.com/gadicc/meteor-package-file-eval/blob/master/packages/package/unused-file.js which shows examples of a few breaks (if the offending code is commented out, it works...).

The issue is present since beta.0 but gets more volatile in beta.3 (see above file).  Works fine in Meteor 1.2.

Considering that this was only picked up now, definitely less urgent than other stuff being tracked in 1.3.

**Comment by avital** [comment] 2016-02-11 17:37
Dupe of #5998

**Closed by avital** 2016-02-11 17:37 UTC
