### ISSUE TITLE
Tracker.afterFlush should bindEnvironment or noYieldsAllowed

### ISSUE THREAD

**Issue by cscott** [meteor/meteor#3293] opened 2014-12-15 15:46 UTC
It appears that Tracker.afterFlush does not use a proper Meteor.bindEnvironment on server-side:

```
I20141215-10:43:40.962(-5)? Exception from Tracker afterFlush function: Error: Can't wait without a fiber
I20141215-10:43:40.962(-5)?   at Function.wait (/home/cananian/.meteor/packages/meteor-tool/.1.0.36.1m269nh++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:83:9)
I20141215-10:43:40.962(-5)?   at Object.Future.wait (/home/cananian/.meteor/packages/meteor-tool/.1.0.36.1m269nh++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:325:10)
I20141215-10:43:40.963(-5)?   at [object Object]._.extend._nextObject (/home/cananian/Projects/MysteryHunt/2015/codex-blackboard/.meteor/local/build/programs/server/packages/mongo.js:900:47)
I20141215-10:43:40.967(-5)?   at [object Object]._.extend.forEach (/home/cananian/Projects/MysteryHunt/2015/codex-blackboard/.meteor/local/build/programs/server/packages/mongo.js:934:22)
I20141215-10:43:40.967(-5)?   at [object Object].Cursor.(anonymous function) [as forEach] (/home/cananian/Projects/MysteryHunt/2015/codex-blackboard/.meteor/local/build/programs/server/packages/mongo.js:783:44)
I20141215-10:43:40.968(-5)?   at updateRoundStart (/home/cananian/Projects/MysteryHunt/2015/codex-blackboard/.meteor/local/build/programs/server/app/lib/model.coffee.js:33:8)
I20141215-10:43:40.968(-5)?   at /home/cananian/Projects/MysteryHunt/2015/codex-blackboard/.meteor/local/build/programs/server/app/lib/model.coffee.js:54:18
I20141215-10:43:40.968(-5)?   at [object Object].Tracker.flush [as _onTimeout] (/home/cananian/Projects/MysteryHunt/2015/codex-blackboard/.meteor/local/build/programs/server/packages/tracker.js:421:11)
I20141215-10:43:40.969(-5)?   at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

The code in question looks like this:

``` coffeescript
# RoundGroups are:
#   _id: mongodb id
#   name: string
#   canon: canonicalized version of name, for searching
#   created: timestamp (sort key)
#   created_by: canon of Nick
#   touched: timestamp -- records edits to tag, order, group, etc.
#   touched_by: canon of Nick with last touch
#   tags: [ { name: "Status", canon: "status", value: "stuck" }, ... ]
#   rounds: [ array of round _ids, in order ]
#   (next fields is a bit racy, oh well)
#   round_start: integer, indicating how many rounds total are in all
#                preceding round groups (a bit racy, but server fixes it up)
RoundGroups = BBCollection.roundgroups = new Mongo.Collection "roundgroups"
if Meteor.isServer
  RoundGroups._ensureIndex {canon: 1}, {unique:true, dropDups:true}
  updateRoundStart = ->
    round_start = 0
    RoundGroups.find({}, sort: ["created"]).forEach (rg) ->
      if rg.round_start isnt round_start
        RoundGroups.update rg._id, $set: round_start: round_start
      round_start += rg.rounds.length
  queueUpdateRoundStart = do ->
    pending = false
    return ->
      if not pending
        pending = true
        Tracker.afterFlush ->
          pending = false
          updateRoundStart()
  # observe changes to the rounds field and update round_start
  queueUpdateRoundStart()
  RoundGroups.find({}).observeChanges
    added: (id, fields) -> queueUpdateRoundStart()
    removed: (id, fields) -> queueUpdateRoundStart()
    changed: (id, fields) ->
      queueUpdateRoundStart() if 'created' in fields or 'rounds' in fields
```

**Comment by glasser** [comment] 2015-01-12 22:24
It's definitely the case that it's wrong that afterFlush callbacks are neither wrapped in bindEnvironment nor executed via noYieldsAllowed.  Other parts of Tracker that run on the server (the actual autorun function and onInvalidate callbacks) use noYieldsAllowed, and I suspect that the correct thing here is that afterFlush should also use noYieldsAllowed — I don't think that the state machine in tracker is necessarily OK with other parts of the code calling Tracker functions during a yield in an afterFlush.

In order to make afterFlush OK with yielding, we'd probably need to make sure that multiple afterFlush callbacks can't be called overlappingly by using a queue or something.

For your purpose, it's probably better to just call Meteor.defer inside your afterFlush callback.

(To be thoroughly honest, Tracker is mostly designed for client use, which doesn't have yielding, and while we've done the bare minimum to make it kind of work on the server, the core team has never really sat down and put serious effort into making Tracker truly server native.  For example, while it makes sense to have a single global concept of "current computation" on the client, it probably makes less sense on the server, where maybe it should be fiber-dependent or DDP-client-dependent or something. It doesn't necessarily make sense that a slow recomputation for an autorun that is correlated to a specific user connection should affect the performance of an autorun correlated to another user.  Hopefully at some point there will be an iteration of Tracker focused on making it truly server-native.)

**Comment by cscott** [comment] 2015-01-12 23:00
So you're suggesting:
```coffeescript
 queueUpdateRoundStart = do ->
    pending = false
    return ->
      if not pending
        pending = true
        Tracker.afterFlush ->
          Meteor.defer ->  # this is the new bit
            pending = false
            updateRoundStart()
```
FWIW, the workaround I actually used was:
```coffeescript
  queueUpdateRoundStart = do ->
    pending = false
    return ->
      if not pending
        pending = true
        # this should be `Tracker.afterFlush`, but see
        # https://github.com/meteor/meteor/issues/3293
        # workaround with Meteor.setTimeout -- we want to ensure that
        # we give all the observeChanges time to fire before we do
        # the update
        Meteor.setTimeout ->
          pending = false
          updateRoundStart()
        , 0
```

It would be nice to better document the turn-taking behavior of the various methods, however.  I'm hoping that `afterFlush`/`setTimeout` will execute only after all of the `observeChanges` events have fired, but I don't think that's actually spelled out anywhere.

**Comment by glasser** [comment] 2015-01-13 00:48
OK, I actually read your whole snippet this time :)  Nothing in your snippet is using Tracker at all, so Tracker.afterFlush isn't actually a particularly relevant function to use. You're just using observeChanges, which (especially on the server) doesn't connect to Tracker at all.

Your goal is basically just to wait for a set of observeChanges calls to be done before doing some work, yeah?  That's not actually a part of the observeChanges interface (and eg, doesn't actually really make sense in the world of the oplog driver which is always (except for limit) acting on a single document at a time).  Perhaps what you want to be using is `_.debounce`.  (Or our Fiber-knowledgeable version coalesce, which can be copied from `tools/func-utils.js`; we've only used it in the tool, not packages, so far.)

**Comment by mitar** [comment] 2015-01-16 15:44
What about this old code: https://github.com/Diggsey/meteor-server-deps/blob/master/lib/server-deps.coffee It seems to do all necessary stuff?

**Comment by mitar** [comment] 2015-01-16 15:48
So we have a problem that we cannot run both server and client side code in parallel, because autorun does not operate correctly on the server side and do not allow database queries. We have some code for which user can decide to run in the client, or as a background process on the server, so that client can be turned off.

**Comment by mitar** [comment] 2015-01-18 01:15
I made this package: https://github.com/peerlibrary/meteor-server-autorun

**Comment by liron00** [comment] 2015-02-07 10:35
I just had a related problem using autorun in my publish function.

    Meteor.publish("foo", function() {
        var getValue = Meteor.bindEnvironment(function() {
            return 5;
        });

        var c = Tracker.autorun(function() {
            console.log("Value is: " + getValue());
        });

        c.invalidate();
        console.log("Invalidated the computation.");
    });

I got the following console output:

    I20150207-12:29:20.329(2)? Value is: 5
    I20150207-12:29:20.329(2)? Invalidated the computation.
    I20150207-12:29:20.330(2)? Value is: undefined

This is because there is no "return" in one branch of Meteor.bindEnvironment, line 122 of https://github.com/meteor/meteor/blob/556c0e28e94b9351cbf0b28e80a71a4e35f1362a/packages/meteor/dynamics_nodejs.js:

    120    if (Fiber.current)
    121        return runWithEnvironment();
    122    Fiber(runWithEnvironment).run();

**Comment by mitar** [comment] 2015-02-07 10:39
You know that official autorun does not really work on the server side?

**Comment by liron00** [comment] 2015-02-07 12:15
Ya I read this thread.

**Comment by glasser** [comment] 2015-02-11 02:29
bindEnvironment is intended to be used for callbacks to async Node methods (eg, things that tend to be queued by network/fs/timer/etc events), whose return values are rarely important.

There's really not a way to get a return value out of a possibly-yielding fiber when you are not already in a fiber yourself.  That's... kind of the definition of how Fibers work.  `run()` runs it until it yields the first time or finish.   Fortunately, the cases where you use a bindEnvironment are (as mentioned above) generally times when the return value doesn't matter anyway (because the Node APIs assume that the callback will need to itself do async work).

**Comment by hwillson** [comment] 2017-06-26 16:44
As discussed in this thread, the mentioned issue is actually functioning as designed. Since changing this functionality is a feature request, and [FR's are now managed in a new repo](http://github.com/meteor/meteor-feature-requests/issues), I'll close this issue here. Thanks!

**Closed by hwillson** 2017-06-26 16:44 UTC
Labels: Project:Tracker
