### ISSUE TITLE
Column must be greater than or equal to 0, got -1

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/meteor#7360] opened 2016-07-06 15:17 UTC
I have hit the most frustrating issue of all time. Which is getting in the way of the productivity of my entire team. 

When working on client folders making rapid changes my Meteor app will crash:
`Error getting callstack: [TypeError: Column must be greater than or equal to 0, got -1]`

As well as

```
I20160705-19:05:32.107(-7)? Internal exception while processing message { msg: 'sub',
I20160705-19:05:32.107(-7)?   id: 'aECPRg2aBnN38iX5X',
I20160705-19:05:32.107(-7)?   name: 'meteor.loginServiceConfiguration',
I20160705-19:05:32.108(-7)?   params: [],
I20160705-19:05:32.108(-7)?   _waitEventId: '941',
I20160705-19:05:32.108(-7)?   __kadiraInfo: 
I20160705-19:05:32.108(-7)?    { session: 'bsK6QjxSeDzEBwaEA',
I20160705-19:05:32.108(-7)?      userId: null,
I20160705-19:05:32.108(-7)?      trace: 
I20160705-19:05:32.108(-7)?       { _id: 'bsK6QjxSeDzEBwaEA::aECPRg2aBnN38iX5X',
I20160705-19:05:32.109(-7)?         session: 'bsK6QjxSeDzEBwaEA',
I20160705-19:05:32.109(-7)?         userId: null,
I20160705-19:05:32.109(-7)?         id: 'aECPRg2aBnN38iX5X',
I20160705-19:05:32.109(-7)?         events: [Object],
I20160705-19:05:32.109(-7)?         type: 'sub',
I20160705-19:05:32.109(-7)?         name: 'meteor.loginServiceConfiguration',
I20160705-19:05:32.109(-7)?         _lastEventId: null } } } Column must be greater than or equal to 0, got -1 TypeError: Column must be greater than or equal to 0, got -1
```

Okay now to make it worse, our galaxy container is also experiencing the same issue. What is this error? Why does it happen? How do we get rid of it?

Thanks.

**Comment by abernix** [comment] 2016-07-06 16:01
It's hard to make a lot out of that without more details.  The error seems to be getting _caught by_ the DDP stream server code [in here](https://github.com/meteor/meteor/blob/release-1.4/packages/ddp-server/livedata_server.js#L1343-L1380), but the actual error seems to be from the source-map consumer code in [here](https://github.com/mozilla/source-map/blob/7bc77b042582196e1bc7e950a7f4b4254bbabcd7/lib/source-map-consumer.js#L526-L548).

I can't make any connection between the two.  So, questions:

First, the basics:
* What version of Meteor are you using? 
* What operating system are you on?
* Did this start in a recent version?  If so, what version did it work last?

Then:

* Can you explain any particulars of your environment? Something unique to your setup?
* Are you doing something custom with source-maps?
* Are the files abnormally large in size?
* Are you doing some custom DDP stuff?

And most importantly...

* Can you whittle down the project and make a reproduction you could share?

**Comment by abhiaiyer91** [comment] 2016-07-06 16:38
Version 1.3.2.4
Mac OSX and in production/Dev Galaxy infrastructure
This has been happening to my computer since 1.2 this recently started happening on Galaxy


The only thing special is running our own mongo rather than rely on meteor mongo. Nothing special after that.

I have a Dev subscription so maybe I'll have MDG investigate this

**Comment by abernix** [comment] 2016-07-06 16:46
What do you mean by:

> making rapid changes my Meteor app

?

Are you talking about making changes to documents in Mongo?  Or are you talking about making changes to files?

**Comment by luisatlive** [comment] 2016-07-06 16:51
Making changes to source files that cause a build to retrigger.

But this has also happened twice on just a deploy to galaxy from clean code, where a single galaxy container out of the entire deployment will be in a state that constantly triggers this error.

I believe it's cause due to the overloading of Error.stack being done from source-map

**Comment by abernix** [comment] 2016-07-06 17:53
> I believe it's cause due to the overloading of Error.stack being done from source-map

Can you elaborate a bit on what is leading you to believe this?

Meteor is using it's [own fork of `source-map-support`](https://github.com/meteor/node-source-map-support/) that is forked from and very similar to (though not as current with the latest patches as it could be as) [the original](https://github.com/evanw/node-source-map-support/).

Both of those libraries use the [V8 Stack Track API](https://github.com/v8/v8/wiki/Stack-Trace-API).  By chance, are you using any packages that might be doing their own (or are you doing your own) `require('source-map-support').install()`?  I could foresee this causing some problems, if so – as even up to a couple versions ago, this wasn't supported by `source-map-support`.

If you're not sure what your packages are doing, you might be able to weed through this output a bit:

    grep -Rl source-map-support .meteor/local/build/programs

And see if any packages might be doing it on their own.

**Comment by tmeasday** [comment] 2016-07-07 02:05
So it looks like an error that's happening in the `meteor.loginServiceConfiguration` method call which is being obscured by this callstack problem with source maps. 

@abhiaiyer91 can you consistently reproduce the problem in your app in development?

I think @abernix is on the right track towards figuring out why `source-map-support`'s stack trace generation is throwing that error. Given I'm not finding any other cases of people with that problem, I'm inclined to think it's likely to be something in your app that's messing with Meteor's source maps.

In terms of what the actual error is, it seems to be coming out of the `meteor.loginServiceConfiguration` publication. I would investigate a couple of things:

1. Do you see anything in the Mongo logs about the query `meteor_accounts_loginServiceConfiguration.find {"0":{},"1":{"fields":{"secret":0}}}`? That's pretty much all that publication does, so my best guess would be Mongo is erroring.[1]

2. If you can reproduce this, you could fork the `service-configuration` package and wrap the find call in  a `try/catch` to and see if you can get more information off the exception without the stack trace. Or if that doesn't help, something similar with the ddp-server package's sub handling.

3. Is there anything unusual in the `meteor_accounts_loginServiceConfiguration` collection in Mongo?

[1]   What's odd about this theory is that looking at the Galaxy container, it consistently blows up for this publication, but is successfully running other Mongo queries, AFAICT from the logs.

[2]   At the end of the day, the stack trace from processing that sub message is pretty shallow (it does a simple query, and then passes it into livedata). The only other thing that could go wrong is that Mongo returns a document that some is blowing up livedata, which leads to 3. above

**Comment by TheSavior** [comment] 2016-07-12 02:56
We have had this same error message, but it happens on CI, only occurs occasionally, and we get this stack trace:

```
Uncaught TypeError: Column must be greater than or equal to 0, got -1
      at /tmp/81a76371d25387d45b5b0db72f6d0195.browserify:50990 <- ../node_modules/sinon/lib/sinon/spy.js:187:0
```

I too have been unable to track this down and have opened tickets in a few different places. Parent ticket here: https://github.com/mozilla/source-map/issues/243

Hopefully we can get to a resolution for all of our sakes. :)

**Comment by tmeasday** [comment] 2016-07-12 03:03
> Given I'm not finding any other cases of people with that problem

I guess that is no longer true. Thanks for chiming in @TheSavior. Let us know if you get anywhere.

**Comment by abhiaiyer91** [comment] 2016-08-24 02:48
Hit this one again and again
```
2016-08-23 19:47:51.987 [INTERNAL][ERROR] Uncaught Exception in fiber: 'TypeError: Column must be greater than or equal to 0, got -1\n    at SourceMapConsumer_findMapping [as _findMapping] (/Users/abhiaiyer/.meteor/packages/meteor-tool/.1.4.1.1qzkxnb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map/lib/source-map/source-map-consumer.js:281:15)\n    at SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/abhiaiyer/.meteor/packages/meteor-tool/.1.4.1.1qzkxnb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map/lib/source-map/source-map-consumer.js:310:26)\n    at mapSourcePosition (/Users/abhiaiyer/.meteor/packages/meteor-tool/.1.4.1.1qzkxnb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:160:42)\n    at mapEvalOrigin (/Users/abhiaiyer/.meteor/packages/meteor-tool/.1.4.1.1qzkxnb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:183:20)\n    at wrapCallSite (/Users/abhiaiyer/.meteor/packages/meteor-tool/.1.4.1.1qzkxnb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:311:14)\n    at wrapCallSite (/Users/abhiaiyer/Projects/Workpop-Org/Workpop-Web/.meteor/local/build/programs/server/boot.js:71:15)\n    at /Users/abhiaiyer/.meteor/packages/meteor-tool/.1.4.1.1qzkxnb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:330:26\n    at Array.map (native)\n    at Function.prepareStackTrace (/Users/abhiaiyer/.meteor/packages/meteor-tool/.1.4.1.1qzkxnb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:329:24)\n    at packages/underscore/underscore.js:860:1\n    at Array.forEach (native)\n    at _.each._.forEach (packages/underscore/underscore.js:105:1)\n    at Function._.pick (packages/underscore/underscore.js:859:1)\n    at Subscription.subscriptionProto.error (packages/meteorhacks_kadira/lib/hijack/wrap_subscription.js:51:1)\n    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1033:12)\n    at Subscription.MeteorX.Subscription._runHandler (packages/meteorhacks_unblock/packages/meteorhacks_unblock.js:55:1)\n    at Subscription.subscriptionProto._runHandler (packages/meteorhacks_kadira/lib/hijack/wrap_subscription.js:12:1)\n    at Session.MeteorX.Session._startSubscription (packages/meteorhacks_unblock/packages/meteorhacks_unblock.js:43:1)\n    at Session.sub (packages/ddp-server/livedata_server.js:617:12)\n    at Session.MeteorX.Session.protocol_handlers.sub (packages/meteorhacks_unblock/packages/meteorhacks_unblock.js:17:1)\n    at packages/meteorhacks_kadira/lib/hijack/wrap_session.js:77:1\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at Session.sessionProto.protocol_handlers.sub (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:76:1)\n    at packages/ddp-server/livedata_server.js:551:43'  >>> Error
```

**Comment by abhiaiyer91** [comment] 2016-08-25 21:01
This is now happening every 15 mins on our Galaxy Deployment for develop @benjamn @tmeasday

**Comment by abhiaiyer91** [comment] 2016-08-25 21:01
We just upgraded to meteor 1.4.1

**Comment by tmeasday** [comment] 2016-08-26 12:04
@abhiaiyer91 unfortunately that error isn't really all that helpful because it's something in the sourcemap's error handling going wrong and obscuring the real problem.

If this is happening that consistently on your devel server, I'd suggest deploying a patched version of livedata that logs the error before throwing it here: https://github.com/meteor/meteor/blob/devel/packages/ddp-server/livedata_server.js#L1033 to figure out what the subscription that's having a problem is.

Of course, I'd also try to figure out what the real problem (w/ the sourcemaps) is. Once you know what kind of error is causing it and where it's coming from, you should be able to reliably reproduce it, and then you could try removing things / recreating it in a simple project. (I would start by removing the various meteorhacks things you have in the stack ;) )

**Comment by hwillson** [comment] 2017-02-02 19:58
As part of the on-going old issue cleanup process, I'll close this issue. If this issue is still happening with the latest version of Meteor, please post back and let us know. Thanks for posting this originally!

**Closed by hwillson** 2017-02-02 19:58 UTC
Labels: bug, Impact:few
