### ISSUE TITLE
Mongo Server Not Working

### ISSUE THREAD

**Issue by elMauNunez** [meteor/meteor#4141] opened 2015-04-06 18:04 UTC
$ meteor mongo
mongo: Meteor isn't running a local MongoDB server.

This command only works while Meteor is running your application locally. Start your application first. (This error will also occur if you asked Meteor to use a different MongoDB server with $MONGO_URL when you ran your application.)

If you're trying to connect to the database of an app you deployed with 'meteor deploy', specify your site's name with this command.

**Comment by elMauNunez** [comment] 2015-04-06 18:09
$ meteor 
[[[[[ ~/code/play/meteor/simple-todos ]]]]]   

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/

**Comment by Slava** [comment] 2015-04-06 18:11
duplicate of https://github.com/meteor/meteor/issues/4115

This is going to be fixed with the release 1.1.0.2, please hold on for an hour, it is going to be out soon.

**Closed by Slava** 2015-04-06 18:11 UTC
