### ISSUE TITLE
Scaffold an official project structure on with `meteor create`

### ISSUE THREAD

**Issue by fandy** [meteor/meteor#6974] opened 2016-05-04 22:11 UTC
Having a pre-defined folder structure solves the problem of having to create them manually. It also enforces good practices for beginners. Deleting the todo-app every time I start a new project is tedious.
---

Requirements:
1. Update `meteor create` to take an argument `--bare` or `--scaffold`
2. Create two new skeletons to correspond
3. Bare skeleton should just have a `package.json` and `.meteor` directory
4. Scaffold should have a directory structure of the form https://github.com/meteor/meteor/issues/6974#issuecomment-217562277
5. Ensure help is updated

**Comment by stubailo** [comment] 2016-05-05 06:08
Right now we already have `client` and `server`, what should we add? `imports` with `api`, `ui`, `startup`, etc?

**Comment by fandy** [comment] 2016-05-05 11:52
It might be something like this:

```
client/
server/
lib/
ui/
api/
startup/
```

Empty/ unused directories wouldn't be added to git since we're not using `.gitkeep`. It'll keep it nice and clean while providing a nice foundation to your application which you don't have to worry about creating.

**Comment by laosb** [comment] 2016-05-06 12:07
Actually it's a problem of **having a perfect production structure** or **having a good example to play with**. I think we had discussed about it somewhere earlier but didn't come up with a solution. And now it comes again and we should have a solution now. @stubailo

**Comment by fandy** [comment] 2016-05-06 12:11
This scaffolding woolly act as a guideline for those who'd benefit from it (which is vastly greater than the simple-todos example). You can always follow your own project structure as needed, just like simple-todos.

**Comment by laosb** [comment] 2016-05-06 12:26
@fandy True. So what kind of structure is better as default? Something to play with the Meteor Magic or serious production? It makes differences.

**Comment by fandy** [comment] 2016-05-06 12:30
@laosb an empty project structure doesn't bloat the app in any way, especially since unused directories aren't added to Git. I don't see what the problem is you're suggesting.

**Comment by stubailo** [comment] 2016-05-06 17:15
@tmeasday would we take a PR to add more folders to the starter app?

**Comment by tmeasday** [comment] 2016-05-06 17:41
We discussed this previously and it was a bit tricky because there's a tension between a good boilerplate and something simpler that you use for things like quick hacks / repros / demos.

I personally am an advocate for 3rd party boilerplates. @fandy - what files are you deleting from the skeleton when you create a new app?

**Comment by lorensr** [comment] 2016-05-06 18:07
What about:

1. `meteor create`: basic. either current or maybe just a `package.json` (there have been a few times when making repros that i was annoyed at having to remove the client and server files. with repros you want the smallest amount of files/code – like a single `server.js`)
2. `meteor create --structured`: follows the Guide structure http://guide.meteor.com/structure.html – maybe with files that have comments and import/export demonstrations, but not code for an actual app

**Comment by tmeasday** [comment] 2016-05-06 20:37
How would 2. compare to https://themeteorchef.com/blog/introducing-base-v4-0-0/ ?

**Comment by tmeasday** [comment] 2016-05-06 20:37
(Btw I don't want to strip 1. down any further because of tutorials. I'd be open to `meteor create --bare` however)

**Comment by lorensr** [comment] 2016-05-06 21:24
> How would 2. compare to https://themeteorchef.com/blog/introducing-base-v4-0-0/ ?

Base has a lot of actual code in it, like a login system, and picks react. I was thinking like this, but nothing inside the html and css files, and the only thing in js files are imports and/or comments on what the file is for:

![image](https://cloud.githubusercontent.com/assets/251288/15085980/bd0a876e-13ab-11e6-8110-009e781bd88c.png)

Now that I look at Base, maybe 3 below could have other generally recommended & useful things like eslint and test packages and npm scripts.

1. `meteor create --bare` (does this need the package.json?)
2. `meteor create`
3. `meteor create --recommended-structure`

> I personally am an advocate for 3rd party boilerplates. 

Downside is 99% of people won't find them. If we want to improve the avg dev who wants to start off a new project in the best recommended way, maybe she'll find the option in the docs and try it, and that will improve her life. I even think that it would be good to have a fourth option `meteor create --with-react` or `--opinionated-structure` that has more opinions, maybe just clones Base.

**Comment by tmeasday** [comment] 2016-05-06 21:50
I'm pretty convinced, if someone wants to take the time to do this. I can help walk through whats involved.

My question would be should we switch it to 

1. `meteor create --bare` [yes I do think we need a `package.json`]
2. `meteor create --simple` [and change all the tutorials to do this]
3. `meteor create`

On 4. I think let's start here and let that develop. We'd need maintainers that are committed to keeping these opinionated structures up to date which would be a bit of work.

**Comment by stubailo** [comment] 2016-05-06 21:55
Hmm, what about the complex one being `meteor scaffold`? Then we can make it arbitrarily complex without being worried about `meteor create`.

**Comment by tmeasday** [comment] 2016-05-06 21:57
I'd prefer `meteor create --scaffold` so we aren't adding an extra command to the tool

**Comment by tmeasday** [comment] 2016-05-06 22:00
I updated the leading comment to describe the feature

**Comment by fandy** [comment] 2016-05-09 14:54
I'm going to propose a PR for this with `meteor create` flags that scaffold different levels of complexity.

`meteor create --bare` (empty)
`meteor create --simple` (client/ server)
`meteor create` (full project structure)

**Comment by tmeasday** [comment] 2016-05-09 18:07
@fandy sounds great, but can we make it `create --bare / create / create --scaffold` (see description at the top) so that the new user flow is less intimidating?

**Comment by fandy** [comment] 2016-05-09 21:44
@tmeasday should there be a prompt when `meteor create` is ran with no flags so users know about this feature?

**Comment by tmeasday** [comment] 2016-05-09 22:22
I guess that'd be good, but not required.

**Comment by lorensr** [comment] 2016-05-09 22:34
Maybe "Generate scaffold? (y / n)"  But that might subvert the goal of
making new user flow less intimidating, because I'd guess most new users
would choose the scaffold. Another option:

Would you like the simple directory structure or a full scaffold? ("simple"
/ "scaffold")

**Comment by tmeasday** [comment] 2016-05-09 22:50
I think building a project from the scaffold is rare enough (how commonly
do you start a big project, after all?) that it doesn't need to be
super-easy

**Comment by zol** [comment] 2016-05-09 23:11
We've refrained from adding prompts to the tool so far so it's more easily scriptable. I would prefer to add copy to the hint text that you see after you run `meteor create` inviting you to try out the scaffolded app.

**Comment by lorensr** [comment] 2016-05-09 23:26
Oh yeah, I like that best!

**Comment by fandy** [comment] 2016-05-11 16:00
@zoi agreed, I'll work on a PR soon.

Will look something like this:
`meteor create` client/server
`meteor create --bare` empty
`meteor create --full` large project structure

When no flags are used Meteor will log a hint so users are aware of this feature.

**Comment by zol** [comment] 2016-05-11 17:01
Great, thanks.

**Comment by lorensr** [comment] 2016-05-17 20:16
Here's another template that might be helpful, by @dburles https://github.com/dburles/meteor-guide-starter-react

**Comment by stubailo** [comment] 2016-05-17 21:49
@tmeasday I was under the impression that the above labels are only for bugs?

**Comment by lorensr** [comment] 2016-05-17 21:54
Confirmed, according to issuetriage, is for both. For FRs it means that it's clear and can't be done as a package

**Comment by tmeasday** [comment] 2016-05-17 21:55
What @lorensr said

**Comment by omgj** [comment] 2016-05-26 22:00
Another idea: Add the option of specifying view layer.
Could be done wither for the `--bare` or `--scaffold` ( I think only scaffold would make sense ).

For example:

`meteor create --scaffold <ViewLayer>`

`<ViewLayer>` one of: Blaze, React, Angular

I don't know if MDG gets stats about this stuff (from each time create is run), but it could be interesting to have an insight as to what view layer people are using. Could be overkill.

**Comment by zol** [comment] 2016-05-27 19:25
@omgj feels like overkill but thanks for the suggestion.

**Comment by laosb** [comment] 2016-08-08 08:33
Is there any final decisions? `pull-requests-encouraged` but how can people work on this

**Comment by fandy** [comment] 2016-08-08 11:23
Turns out I don't have enough time these days to work on a pull, so I'll pass it up to someone else!

**Comment by laosb** [comment] 2016-08-08 12:59
Never mind. For those who want to contribute, the final solution was described [there](https://github.com/meteor/meteor/issues/6974#issuecomment-218505623).

**Comment by mhidou** [comment] 2016-08-21 16:59
I started to work on this issue I will soon publish a PR

**Comment by Batistleman** [comment] 2016-09-09 09:41
Instead of adding this to meteor, how about creating a tool like this:

**Comment by tmeasday** [comment] 2016-11-08 23:58
#7807 is merged!

**Closed by tmeasday** 2016-11-08 23:58 UTC
Labels: confirmed, feature, Impact:some, Project:Tool, pull-requests-encouraged, Severity:has-workaround

**Comment by cyclops24** [comment] 2016-11-13 05:52
Hi, I think @omgj suggestion also good. for example:
`meteor create --scaffold <ViewLayer>`
`<ViewLayer>` one of: Blaze, React, Angular

**Comment by maka-io** [comment] 2018-03-15 18:03
You could try my scaffolding tool:
[maka-cli](https://www.npmjs.com/package/maka-cli)

``` sh
$ maka create react-app
```
