### ISSUE TITLE
 Mongo server and the Meteor query disagree

### ISSUE THREAD

**Issue by dan335** [meteor/meteor#9087] opened 2017-09-13 07:35 UTC
Since upgrading from 1.4.something to 1.5.2 I'm seeing this error in the logs.

    Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"playerIds":{"$elemMatch":{"playerId":"mZcMiDzhqsKCAjbe8","read":false}},"type":{"$nin":[]}} 
    at Error (native) 
    at packages/mongo/oplog_observe_driver.js:881:15 
    at Object.Meteor._noYieldsAllowed (packages/meteor.js:681:12) 
    at [object Object]._.extend._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12) 
    at [object Object]._.extend._runQuery (packages/mongo/oplog_observe_driver.js:758:10) 
    at packages/mongo/oplog_observe_driver.js:699:14 
    at [object Object].EVp.withValue (packages/meteor.js:1135:15) 
    at packages/meteor.js:452:25 
    at runWithEnvironment (packages/meteor.js:1189:24)

**Comment by mbrobbel** [comment] 2017-09-13 10:52
I've seen a similar exception after upgrading from 1.5.1 to 1.5.2. Maybe related to https://github.com/meteor/meteor-feature-requests/issues/146?  @radekmie 

The structure of my query:
```js
{
  field: { '$size': value },
  otherField: {
    '$elemMatch': {
      '$and': [
        { field: { '$in': [ value, otherValue ] } },
        { otherField: { '$bitsAllSet': value } }
      ]
    }
  }
} 
```

**Comment by hwillson** [comment] 2017-09-15 12:15
Thanks for reporting this - would one of you be able to create a small reproduction demonstrating this problem (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug))? A reproduction will definitely aid in troubleshooting, and help get this issue resolved more quickly.

**Comment by dan335** [comment] 2017-09-15 18:21
Here's my attempt but it doesn't cause the error.  https://github.com/dan335/disagreeRepro  

I'm not sure I understand the error enough to make a repro.  When would this happen?  

    The Mongo server and the Meteor query disagree on how many documents match your query.

Does it need an db with oplog and pub/sub to cause the error?

**Comment by zimme** [comment] 2017-09-16 13:42
Is this related to https://github.com/meteor/meteor/issues/3946 this issue perhaps?

**Comment by whtsky** [comment] 2017-09-18 05:33
found the same error with query
```
"members":{"$elemMatch":{"_id":value}}}
```

**Comment by elisei-timofte** [comment] 2017-09-18 08:11
I have the same issue. I've upgraded to 1.5.2 and now I'm getting `The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case?`

``` js
The query is:
{
  "id": "WasFasf932f",
  "anotherId": {
    "$ne": null
  },
  "$and": [
    {
      "_status": {
        "$not": {
          "$elemMatch": {
            "value": "closed"
          }
        }
      }
    },
    {
      "_status": {
        "$elemMatch": {
          "value": "paused"
        }
      }
    }
  ]
}
````

**Comment by abernix** [comment] 2017-09-18 09:43
@elisei-timofte @whtsky Thanks for providing some additional detail.  Would either of you be able to create a simple reproduction of this problem using a fresh Meteor application so it can be further analyzed?  A reproduction repository is the best chance of getting this resolved/explained!  Unfortunately, I don't think the query snippets by themselves provide enough context to understand what's going on or what could be wrong.

Thanks!

**Comment by elisei-timofte** [comment] 2017-09-18 16:13
I've created a fresh Meteor app, but I couldn't replicate the problem.

After some research I've discovered that the query brakes only if matches the second term in my $and query  `
{
      "_status": {
        "$elemMatch": {
          "value": "paused"
        }
      }
    }
`

If I have no elements with _status 'paused' it works fine.

**Comment by trancehime** [comment] 2017-09-25 08:46
I've also experienced this issue and I thought building with Meteor 1.5.1 would get rid of the problem but it didn't work after a reset, would it be possible that this problem is due to an update in Mongo adaptor?

**Comment by manueltimita** [comment] 2017-09-25 16:40
We came across the same issue just recently, and we solved it temporarily by changing our queries. 

It is a known issue an it looks like it's related to https://github.com/meteor/meteor/issues/2244 (see @glasser 's answer). It's seems to be about Meteor and Mongo disagreeing on how to treat a falsy value.

In our situation we were applying `$elemMatch` to an empty array.

Instead of using `$elemMatch` in a query like this `{"members":{"$elemMatch":{"_id":value}}}`, simply change it to `"{members._id":value}`.

There is also a Mongo documentation page that could be helpful: https://docs.mongodb.com/manual/tutorial/query-array-of-documents/

**Comment by dan335** [comment] 2017-09-25 17:01
I did not have the error in Meteor 1.4 and started seeing it after upgrading to 1.5.2.  It might be related to #2244 but something changed which caused this to start happening.

**Comment by trancehime** [comment] 2017-09-27 03:20
Adding disableOplog:true to my queries fixed some of them but when I discovered `Meteor.user()` wasn't reactive either, I removed MONGO_OPLOG_URL and all my problems were solved...

**Comment by abernix** [comment] 2017-09-27 10:18
Please check with Meteor 1.5.2.1, as the fix @hwillson provided https://github.com/meteor/meteor/pull/9134 was likely the source of this problem.

    meteor update --release 1.5.2.1

@trancehime Removing `MONGO_OPLOG_URL` is certainly not a recommended approach as it will force all queries to resort to fetching/polling, so hopefully 1.5.2.1 will resolve it for you.

**Comment by ubercolin** [comment] 2017-09-27 17:33
We were running into this problem as well (lost a good chunk of yesterday trying to figure out what was going on in various parts of the app). I can confirm that 1.5.2.1 seems to resolve this problem (at least in initial testing).

**Comment by trancehime** [comment] 2017-10-03 03:25
Tested in the staging environment and have successfully re-enabled the oplog; thank you very much for the prompt fix.

**Comment by hwillson** [comment] 2017-10-03 10:29
Fixed in 1.5.2.1 - closing - thanks!

**Closed by hwillson** 2017-10-03 10:29 UTC
Labels: Project:Mongo Driver

**Comment by lynchem** [comment] 2018-02-01 09:46
We got this last night after updating from 1.6.0.1 -> 1.6.1 . We use an mlab cluster for our db running mongo 3.0.12 MMAPv1 . Could the old version be the issue ? Sorry I've no time to create a repro. 

Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {}
 at packages/mongo/oplog_observe_driver.js:881:15
 at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
 at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
 at OplogObserveDriver.proto._publishNewResults (packages/mdg_meteor-apm-agent.js:2899:38)
 at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
 at OplogObserveDriver._runInitialQuery (packages/mongo/oplog_observe_driver.js:658:10)
 at packages/mongo/oplog_observe_driver.js:191:10
 at packages/mongo/oplog_observe_driver.js:15:9
 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
 at packages/meteor.js:502:25
 at runWithEnvironment (packages/meteor.js:1240:24)

Here was the list of packages that were updated. 

accounts-base              upgraded from 1.4.0 to 1.4.2
autoupdate                 upgraded from 1.3.12 to 1.4.0
babel-compiler*            upgraded from 6.24.7 to 7.0.0
babel-runtime              upgraded from 1.1.1 to 1.2.0
boilerplate-generator      upgraded from 1.3.1 to 1.4.0
callback-hook              upgraded from 1.0.10 to 1.1.0
check                      upgraded from 1.2.5 to 1.3.0
coffeescript               downgraded from 1.11.1_4 to 1.0.17
ddp-client                 upgraded from 2.2.0 to 2.3.1
ddp-common                 upgraded from 1.3.0 to 1.4.0
ddp-server                 upgraded from 2.1.1 to 2.1.2
diff-sequence              upgraded from 1.0.7 to 1.1.0
dynamic-import             upgraded from 0.2.1 to 0.3.0
ecmascript                 upgraded from 0.9.0 to 0.10.0
ecmascript-runtime-client  upgraded from 0.5.0 to 0.6.0
es5-shim                   upgraded from 4.6.15 to 4.7.0
http                       upgraded from 1.3.0 to 1.4.0
id-map                     upgraded from 1.0.9 to 1.1.0
meteor-base                upgraded from 1.2.0 to 1.3.0
minifier-css               upgraded from 1.2.16 to 1.3.0
minifier-js                upgraded from 2.2.2 to 2.3.1
modules                    upgraded from 0.11.1 to 0.11.3
mongo                      upgraded from 1.3.1 to 1.4.2
ordered-dict               upgraded from 1.0.9 to 1.1.0
promise                    upgraded from 0.10.0 to 0.10.1
random                     upgraded from 1.0.10 to 1.1.0
reload                     upgraded from 1.1.11 to 1.2.0
retry                      upgraded from 1.0.9 to 1.1.0
server-render              added, version 0.3.0
shim-common                added, version 0.1.0
socket-stream-client       added, version 0.1.0
standard-minifier-css      upgraded from 1.3.5 to 1.4.0
standard-minifier-js       upgraded from 2.2.3 to 2.3.1
url                        upgraded from 1.1.0 to 1.2.0
webapp                     upgraded from 1.4.0 to 1.5.0

                                              
* These packages have been updated to new versions that are not backwards
compatible.
obit: updated to Meteor 1.6.1.                
                                                                                   
Changes to your project's package version selections from updating package versions:
                                              
babel-runtime              upgraded from 1.2.0 to 1.2.2
caching-compiler           upgraded from 1.1.9 to 1.1.11
ecmascript-runtime-client  upgraded from 0.6.0 to 0.6.1
es5-shim                   upgraded from 4.7.0 to 4.7.3
jquery                     upgraded from 1.11.10 to 1.11.11
modules-runtime            upgraded from 0.9.1 to 0.9.2
mongo                      upgraded from 1.4.2 to 1.4.3
npm-mongo                  upgraded from 2.2.33 to 2.2.34
stylus                     upgraded from 2.513.13 to 2.513.14

**Comment by jessedvrs** [comment] 2018-02-01 12:42
@lynchem Cannot be coincidence, I had it this morning too. Updated from 1.4.4.2 to 1.6.1.

**Comment by abernix** [comment] 2018-02-01 12:48
@jessedvrs @lynchem Please open a new issue as this one is closed (and quite old — long before 1.6.1 even started!).  Of course, any and all details you can include in the new issue would be most helpful (@jessedvrs your Mongo server version, for example).

**Comment by RealHandy** [comment] 2018-02-22 19:08
I also just encountered this today. Also just upgraded to 1.6.1 last night.

**Comment by hwillson** [comment] 2018-02-22 19:11
This is now being tracked in https://github.com/meteor/meteor/issues/9619, and a fix is ready in https://github.com/meteor/meteor/pull/9671. We'll get this merged soon. Thanks!

**Comment by hacknlove** [comment] 2018-03-01 13:06
I had the problem

I found out that i had `{foo: undefined}` in a query

As soon as I prevent `undefined` in my query, everything runs smoothly

**Comment by filipenevola** [comment] 2018-03-26 11:37
Is there any workaround?

I'm guessing that just removing any "undefined" will resolve it but maybe if we can update a package and resolve it, that's a better workaround

**Comment by haveaguess** [comment] 2021-05-23 21:27
Digging into the comments of the pr above they seem to want to make this fail fast because they think people will see subtle bugs in mongo queries if they use undefined instead of null. If I'm reading it right

![Screenshot_20210523-222534](https://user-images.githubusercontent.com/85821/119277179-05f24d00-bc16-11eb-81b4-33342d2adef8.jpg)
