### ISSUE TITLE
Android Setup Page Missing Emulator Setup Step

### ISSUE THREAD

**Issue by oohaysmlm** [meteor/meteor#5908] opened 2015-12-30 20:09 UTC
The Android setup page here: https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Mac should have a short section on how to set up the emulator in Android Studio.  Until you do this, Meteor will give you the following error when you execute 'meteor run android'

app_store $ meteor run android
[[[[[ ~/Documents/MeteorDev/app_store_class/app_store ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --emulator:
   Error: Command failed:                     
   /Users/stevenkehoe/Documents/MeteorDev/app_store_class/app_store/.meteor/local/cordova-build/platforms/android/cordova/run
   --emulator

   /Users/stevenkehoe/Documents/MeteorDev/app_store_class/app_store/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   ERROR : No emulator images (avds) found.
   1. Download desired System Image by running:
   /Users/stevenkehoe/Library/Android/sdk/tools/android sdk
   2. Create an AVD by running:
   /Users/stevenkehoe/Library/Android/sdk/tools/android avd
   HINT: For a faster emulator, use an Intel System Image and install the HAXM
   device driver
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

**Comment by timbotnik** [comment] 2016-01-05 23:12
Duplicate of #5380

**Closed by timbotnik** 2016-01-05 23:12 UTC
