### ISSUE TITLE
Node assertion error after upgrading to meteor 2.0

### ISSUE THREAD

**Issue by doronrk** [meteor/meteor#11311] opened 2021-02-01 19:59 UTC
### This bug report should include:
-  version of Meteor showing the problem.
2.0
- The last version of Meteor where the problem did _not_ occur, if applicable.
1.11
- The operating system you're running Meteor on.
OS X
- The expected behavior.
Does not crash
- The actual behavior.
```
W20210201-11:27:47.096(-8)? (STDERR) /Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node[53589]: ../src/api/callback.cc:123:void node::InternalCallbackScope::Close(): Assertion `(env_->execution_async_id()) == (0)' failed.
W20210201-11:27:47.097(-8)? (STDERR)  1: 0x1011f62d5 node::Abort() (.cold.1) [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.098(-8)? (STDERR)  2: 0x1000a5a29 node::Abort() [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.098(-8)? (STDERR)  3: 0x1000a5891 node::Assert(node::AssertionInfo const&) [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.099(-8)? (STDERR)  4: 0x100001c96 node::InternalCallbackScope::Close() [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.099(-8)? (STDERR)  5: 0x10000223a node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.100(-8)? (STDERR)  6: 0x100016598 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.100(-8)? (STDERR)  7: 0x10015d560 node::StreamBase::CallJSOnreadMethod(long, v8::Local<v8::ArrayBuffer>, unsigned long, node::StreamBase::StreamBaseJSChecks) [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.101(-8)? (STDERR)  8: 0x10015f2d1 node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.102(-8)? (STDERR)  9: 0x1000c3224 node::(anonymous namespace)::Parser::OnStreamRead(long, uv_buf_t const&) [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.103(-8)? (STDERR) 10: 0x100163d6f node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.105(-8)? (STDERR) 11: 0x100975355 uv__stream_io [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.107(-8)? (STDERR) 12: 0x10097deac uv__io_poll [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.109(-8)? (STDERR) 13: 0x10096a651 uv_run [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.110(-8)? (STDERR) 14: 0x1000e8d97 node::NodeMainInstance::Run() [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.111(-8)? (STDERR) 15: 0x10007b0e9 node::Start(int, char**) [/Users/zach/.meteor/packages/meteor-tool/.2.0.0.9ea28f.b4qbd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20210201-11:27:47.112(-8)? (STDERR) 16: 0x7fff6b74bcc9 start [/usr/lib/system/libdyld.dylib]
=> Exited from signal: SIGABRT
=> Your application is crashing. Waiting for file change.
```
- [ ] A **simple** reproduction! (Must include the Github repository and steps to reproduce the issue on it.)
meteor --settings development.settings.json

If you don't include a reproduction the issue is probably going to be closed.

**Comment by filipenevola** [comment] 2021-02-01 21:38
Hi @doronrk I'm a Mac user as well and I never had this problem.

I didn't understand your reproduction as it is just a Meteor command. In which repository are you getting this issue?

Did you run:
```shell
meteor reset
rm -rf node_modules
meteor npm install
```

and then tried to run Meteor again? At least to clean up the node libraries and Meteor dependencies.

Could you provide a reproduction? 😉 Read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)

**Comment by doronrk** [comment] 2021-02-02 02:05
@filipenevola Thanks for jumping in here. 

I can confirm that 

```
meteor reset
rm -rf node_modules
meteor npm install
```

did not solve the problem. In case it is helpful, downgrading meteor to 1.11 solves this issue without changing any application code. Upgrading to 2.0 without changing any application code re-introduces it.

I cannot reproduce this using a minimal clean meteor application from scratch. What would you recommend here in terms of narrowing down the root cause here? What would you do if this were your application? 

We would love to start using hot module replacement, but this is a blocker for us.

**Comment by doronrk** [comment] 2021-02-02 04:29
https://github.com/DataDog/dd-trace-js/issues/1229

Looks like dd-trace might be at fault here, unclear as of now.

**Comment by filipenevola** [comment] 2021-02-02 13:36
Hi @doronrk as you explained in the issue dd-trace that disabling it fixes the problem I'm closing the issue here.

If in the end you find something that could be Meteor related please reply here and we can re-open.

Thank you for the investigation and feedback.

**Closed by filipenevola** 2021-02-02 13:36 UTC
Labels: needs-reproduction

**Comment by filipenevola** [comment] 2021-02-04 20:50
Bryan from dd-trace said on Meteor Slack Community: `dd-trace@0.30.6 was released with the workaround as default, for anyone seeing this issue`.

**Comment by rochdev** [comment] 2021-02-06 16:31
This issue should be reopened as the issue is with Meteor, or more specifically the fact that Meteor uses the `fibers` module which is not compatible with the official constructs provided by Node for context propagation. The only reason we were able to work around the issue in `dd-trace` is that we were using `AsyncLocalStorage` which was unnecessary as we can use `executionAsyncResource` directly for our purpose. Since the incompatibility is with `AsyncResource` and `AsyncLocalStorage`, we were able to resolve the issue for our use case in the short term, but it's likely that there will be an eventual regression as `async_hooks` and `fibers` continue to diverge. This is especially true since `fibers` is not only deprecated, but it's explicitly stated in its documentation that it's broken and should not be used.

The issue is quite easy to replicate since as soon as `AsyncLocalStorage` is used it causes an application crash.

```js
const Fiber = require('fibers') // fibers 4.x which is currently used by Meteor
const { AsyncLocalStorage } = require('async_hooks')

const storage = new AsyncLocalStorage()

Fiber(function () {
  const fiber = Fiber.current

  setImmediate(() => fiber.run())

  storage.run({}, () => {
    Fiber.yield()
  })
}).run()

```

Running the above outputs:

```
Error: async hook stack has become corrupted (actual: 4, expected: 1)
 1: 0x100001d08 node::AsyncHooks::pop_async_context(double) [/Users/roch.devost/.nvm/versions/node/v14.8.0/bin/node]
 2: 0x100001aec node::InternalCallbackScope::Close() [/Users/roch.devost/.nvm/versions/node/v14.8.0/bin/node]
 3: 0x1000015de node::InternalCallbackScope::~InternalCallbackScope() [/Users/roch.devost/.nvm/versions/node/v14.8.0/bin/node]
 4: 0x100076a6c node::StartExecution(node::Environment*, std::__1::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>) [/Users/roch.devost/.nvm/versions/node/v14.8.0/bin/node]
 5: 0x100005330 node::LoadEnvironment(node::Environment*) [/Users/roch.devost/.nvm/versions/node/v14.8.0/bin/node]
 6: 0x1000e49df node::NodeMainInstance::Run() [/Users/roch.devost/.nvm/versions/node/v14.8.0/bin/node]
 7: 0x100079482 node::Start(int, char**) [/Users/roch.devost/.nvm/versions/node/v14.8.0/bin/node]
 8: 0x7fff71782cc9 start [/usr/lib/system/libdyld.dylib]
```

Upgrading `fibers` to 5.0.0 resolves this specific error, but when a new async resource is created within the context of the resource created by `AsyncLocalStorage`, we get a different error.

```js
const Fiber = require('fibers') // fibers 5.x which is a bit better but still broken
const { AsyncLocalStorage } = require('async_hooks')

const storage = new AsyncLocalStorage()

Fiber(function () {
  const fiber = Fiber.current

  setImmediate(() => fiber.run())

  storage.run({}, () => {
    Fiber.yield()

    setImmediate(() => {}) // init a new async resource
  })
}).run()
```

Output:

```js
TypeError: Cannot read property 'Symbol(kResourceStore)' of undefined
    at AsyncLocalStorage._propagate (async_hooks.js:276:34)
    at AsyncHook.init (async_hooks.js:251:22)
    at emitInitNative (internal/async_hooks.js:198:43)
    at emitInitScript (internal/async_hooks.js:466:3)
    at initAsyncResource (internal/timers.js:155:5)
    at new Immediate (timers.js:218:5)
    at setImmediate (timers.js:272:10)
    at /Users/roch.devost/foo.js:14:5
    at async_hooks.js:303:14
    at AsyncResource.runInAsyncScope (async_hooks.js:192:9)
```

It's also worth noting that even with our workaround in place for `dd-trace` specifically and the crash no longer happening, it's extremely likely the the continuation is still broken and that Meteor applications will get unexpected behaviours when `async_hooks` is used. Since all APM vendors use `async_hooks` for context propagation and any modern production application should be monitored with an APM tool, this is a serious issue.

While short-term these issues should definitely be addressed as they cause a unrecoverable errors that crash the process, I think the only path forward will be to stop relying on `fibers` since it's inherently incompatible with `async_hooks` and it will only get worse over time, and continuing to use `fibers` means that eventually Meteor will be rendered completely unusable.

**Comment by filipenevola** [comment] 2021-02-10 16:20
hi @rochdev where did you read that fibers are broken?

We are going to discuss plans to replace Fibers or provide an alternative API here https://github.com/meteor/meteor-feature-requests/issues/392 but the author does not say AFAIK that fibers are broken.

This is the node in fibers repo:
> NOTE OF OBSOLESCENCE -- The author of this project recommends you avoid its use if possible. The original version of this module targeted nodejs v0.1.x in early 2011 when JavaScript on the server looked a lot different. Since then async/await, Promises, and Generators were standardized and the ecosystem as a whole has moved in that direction.
>
> I'll continue to support newer versions of nodejs as long as possible but v8 and nodejs are extraordinarily complex and dynamic platforms. It is inevitable that one day this library will abruptly stop working and no one will be able to do anything about it.

So this issue is closed as it is not about Fibers directly. Fibers future in Meteor is going to be discussed here https://github.com/meteor/meteor-feature-requests/issues/392

**Comment by rochdev** [comment] 2021-02-10 18:49
> where did you read that fibers are broken?

The note of obsolescence stated almost a year ago that the library will eventually stop working. From our early tests we can already say that it is actually broken at this point in many different ways from crashes to errors to incorrect asynchronous contexts to incorrect behaviour with using async_hooks directly, and the situation is not going to get any better. Fibers are fundamentally incompatible with how Node and even v8 work right now and even more so with how they are going forward, and that's why the project was abandoned: it can never work at this point and has been replaced by better alternatives. The longer Meteor keeps using it, and by extension its ecosystem, the more it will diverge from the Node ecosystem.

The reason that it's not immediately apparent is because most applications don't rely on `async_hooks`, WASM, and potentially worker threads, but that number is likely to increase over time, especially since these are all modules used by APM vendors.

I think it would be worth it as some point to have a discussion with folks closer to the implementation of `async_hooks` and v8 like @Qard who could provide more context of why that is the case as far as the implementation is concerned. A better understanding of the history and the technicalities will definitely help for all parties involved

> So this issue is closed as it is not about Fibers directly. Fibers future in Meteor is going to be discussed here meteor/meteor-feature-requests#392

IMO it should stay open if the issue is still happening for Meteor users, regardless of the underlying cause.

**Comment by filipenevola** [comment] 2021-02-11 13:37
As I explained in the call that we had yesterday we are working in a plan to mitigate this problem that is caused by the use of Fibers on Meteor.

This plan is going to be discussed with the Community here https://github.com/meteor/meteor-feature-requests/issues/392

**Comment by Qard** [comment] 2021-02-11 19:09
Fibers break `async_hooks`, and have _always_ broken `async_hooks`, because it introduces a new form of async barrier jumping which is not supported and the relevant information is not correctly reported to be able to restore contexts after returning to a yield.

The issue is that a "callback" or promise continuation is _expected_ to run before and after events around a context from a completely unwound id and resource stack. If you inject _another_ callback context within an existing one it will blow away the old context and switch to the new one. The problem is that when that task completes and the fiber releases control back to the yield point, there's no mechanism to restore the prior context, so the `after` event happens in a blank context after the inner task has resolved, which _should_ be impossible in normal conditions, and the process crashes because it doesn't have any id or resource to attribute to the _remainder_ of that callback. That crash you're seeing is `async_hooks` functioning _correctly_ and reporting that you're using it wrong.

Unfortunately for you, it would be impossible for `async_hooks` to correctly express the contextual jump from one fiber to another without specific support for it built into `async_hooks` itself to express the `run` and `yield` returnable barriers, and that's just not going to happen given that fibers are a feature the language and platform have never supported and are directly replaceable by async/await.

Given the chaos that fibers cause in Node.js core and in V8, I'd be trying to get away from them as quickly as possible. You're working against the language by not using the features the language gives you, and it's harming the performance and stability of your platform.

**Comment by doronrk** [comment] 2021-03-11 22:53
> IMO it should stay open if the issue is still happening for Meteor users, regardless of the underlying cause.

I would just echo this. https://github.com/meteor/meteor-feature-requests/issues/392 isn't really a good substitute for this issue.
