### ISSUE TITLE
[1.3-beta.11] scoping error using let/const

### ISSUE THREAD

**Issue by caedmon** [meteor/meteor#6276] opened 2016-02-20 02:32 UTC
Using let or const yields a build error when the name of the variable being declared matches the name of the containing class function.

```javascript
class Foo {
  bar() {
    let bar = 1;
    // must use 'var bar'  or rename 'bar' to avoid errors
    // const bar => const.js: /const.js: "bar" is read-only
    // let bar => const.js:3:8: /const.js: Duplicate declaration "bar"
  }
};
```
Simply insert this in the .js file of a newly created empty meteor app.

Found in 1.3-beta.11 on OSX

**Comment by benjamn** [comment] 2016-02-26 18:34
Given that there's an easy workaround, and the problem lies upstream (with Babel), let's revisit this after the 1.3 release.

**Comment by abernix** [comment] 2016-05-23 13:23
Duplicate of #6138, closing in favor of it because it was first. :)

**Closed by abernix** 2016-05-23 13:23 UTC
