### ISSUE TITLE
Invalid RegEx in build for os.linux.x86_64

### ISSUE THREAD

**Issue by boitewitte** [meteor/meteor#5725] opened 2015-11-27 11:19 UTC
When I build for os.linux.x86_64 and try to run the application (via Nginx and Phusion Passenger). I get the following error:
```javascript
SyntaxError: Invalid regular expression: /^/(/sockjs[/]?$/: Unterminated group
    at new RegExp (&lt;anonymous&gt;)
    at /*/programs/server/npm/ddp-server/node_modules/sockjs/lib/sockjs.js:107:16
    at generate_dispatcher (/*/programs/server/npm/ddp-server/node_modules/sockjs/lib/sockjs.js:121:27)
    at new Listener (/*/programs/server/npm/ddp-server/node_modules/sockjs/lib/sockjs.js:138:25)
    at Server.listener (/*/programs/server/npm/ddp-server/node_modules/sockjs/lib/sockjs.js:191:14)
    at Server.installHandlers (/*/programs/server/npm/ddp-server/node_modules/sockjs/lib/sockjs.js:200:22)
    at new StreamServer (stream_server.js:81:15)
    at new Server (livedata_server.js:1327:24)
    at Package (server_convenience.js:6:17)
    at /*/programs/server/packages/ddp-server.js:2136:4
</pre>
```

I've posted this as well to [Meteor Forums](https://forums.meteor.com/t/regex-error-in-deployment-as-build-invalid-regular-expression-sockjs-unterminated-group/14030/1)

**Comment by rdickert** [comment] 2015-12-01 23:20
This looks like it might be some kind of interaction between sockjs (which is outside code) and Phusion Passenger, which is not a supported deployment method. It would be really hard for us to track this down. Sorry, this feels like a "falling between the cracks" problem, but I don't think there is a way we'd be able to reproduce your result. I'm going to close this for now - I'd recommend also checking with Phusion support. If you find more information that might point us to something in the Meteor codebase, please feel free to reopen this.

**Closed by rdickert** 2015-12-01 23:20 UTC
