### ISSUE TITLE
hot code should work when you pass server url without "="

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#7112] opened 2016-05-24 14:33 UTC
this will not work

```
meteor build ../ios --server=http://139.162.2.61:3000
```

this will work, because you can't use "=" here, that will not pass ROOT_URL to cordova meteor_runtime_config

```
meteor build ../ios --server http://139.162.2.61:3000
```

check your building folder to find index.html, you can see that if your **meteor_runtime_config** ROOT_URL is not your server ip:port, that is the issue.

```
<script type="text/javascript">
  __meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.3.2.4%22%2C%22ROOT_URL%22%3A%22http%3A%2F%2F139.162.2.61%3A3000%2F%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22DDP_DEFAULT_CONNECTION_URL%22%3A%22http%3A%2F%2F139.162.2.61%3A3000%2F%22%2C%22autoupdateVersionCordova%22%3A%2212b3d5a0ecc9b973a11be1b8ac8e8762acd4934f%22%2C%22appId%22%3A%221kzvx321w733oi1ac503b%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%7D"));

  if (/Android/i.test(navigator.userAgent)) {
    // When Android app is emulated, it cannot connect to localhost,
    // instead it should connect to 10.0.2.2
    // (unless we're using an http proxy; then it works!)
    if (!__meteor_runtime_config__.httpProxyPort) {
      __meteor_runtime_config__.ROOT_URL = (__meteor_runtime_config__.ROOT_URL || '').replace(/localhost/i, '10.0.2.2');
      __meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL = (__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL || '').replace(/localhost/i, '10.0.2.2');
    }
  }
</script>
```

i used to asked once

https://github.com/meteor/meteor/issues/3852#issuecomment-76883310

```
 meteor help build
```

this help mislead

```
--server            Location where mobile builds connect to the Meteor server.
                  Defaults to localhost:3000. Can include a URL scheme
                  (for example, --server=https://example.com:443).
```

**Comment by crapthings** [comment] 2016-05-24 14:35
to make hot code push

have these in mobile-config.js

    App.accessRule("*");

    App.accessRule('*', { type: 'navigation' });

and if u have mup, make your mup.json env ROOT_URL === --server url that you passed with port

"env": {
    "PORT": 3000, // because this port does nothing
    "ROOT_URL": "http://139.162.2.61:3000",
    "NODE_ENV": "development"
  },

**Comment by laosb** [comment] 2016-05-25 04:04
Interesting. Need confirm.

**Comment by abernix** [comment] 2016-07-11 11:34
@crapthings I still don't see the same issue that you're referring to.  What version of Meteor are you using?  And can you provide a more detailed reproduction that I can follow to see this issue?  In the code you provided above, you said:

> you can see that if your meteor_runtime_config ROOT_URL is not your server ip:port, that is the issue

And in the other issue #7061, you wrote:

> because that equal sign will not set root url on client`s html head

However, in the code that you pasted above (the `<script>` from the `<head>`), I don't see an issue.  When I inspect the iOS Safari browser when the app loads, the `__meteor_runtime_config__.ROOT_URL` is `http://139.162.2.61:3000/` as it should be.

Also, I'm experiencing the same outcome regardless of whether I use `meteor build` with `--server=http://blah/` or `meteor run ios` with `--mobile-server=http://blah/`.

What am I missing?

**Comment by abernix** [comment] 2016-12-12 16:45
I'm curious if this might also be fixed by #8142.

**Comment by abernix** [comment] 2017-02-09 09:21
@crapthings Can you try and see if this is fixed with Meteor 1.4.2.6?

    meteor update --release 1.4.2.6

Thanks!

**Comment by abernix** [comment] 2017-02-22 12:10
@crapthings Any update on this?

**Comment by hwillson** [comment] 2017-03-06 18:55
Since we haven't heard anything back on this in quite some time, and haven't been able to reproduce this issue with newer versions of Meteor, I'll close this off. If anyone is still encountering this issue, please provide the details requested in https://github.com/meteor/meteor/issues/7112#issuecomment-231710061. Thanks!

**Closed by hwillson** 2017-03-06 18:55 UTC
Labels: bug, can't-reproduce, Impact:some, Project:Mobile, Project:Tool, Severity:has-workaround

**Comment by crapthings** [comment] 2017-03-07 02:03
Meteor 1.4.3.1

it works consistently

**Comment by iwoj** [comment] 2017-05-13 20:50
@crapthings What are your commandline options? I can't get it to work.
