### ISSUE TITLE
[1.10.1] Meteor doesn't refresh when modifying symlinked NPM dependency

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#11042] opened 2020-05-04 06:19 UTC
Meteor 1.10.1, Linux

### Actual behavior:

In certain cases, modifying a symlinked NPM dependency doesn't not refresh the client in dev mode.

### Expected behavior:

At least when code in a symlinked node_modules package changes, Meteor should rebuild and refresh the client. This does not always happen and I need to restart `meteor` to see the new changes.

The symlinking may be due to use of `npm link` for example.

Maybe the problem is due to the fact that I have linked dependencies which in turn have linked dependencies that aren't direct dependencies of the application.

What are the conditions in which Meteor will not refresh the client (as far as things in node_modules)?

### Reproduction

I need to make one...

**Comment by edemaine** [comment] 2020-09-01 18:41
Symlinked packages work fine for me, on Windows, but my package is marked as "recompile" in `package.json`:
```json
  "meteor": {
    "nodeModules": {
      "recompile": {
        "sym-linked-package": true
      }
    }
  }
```

Maybe worth trying adding this to see if that helps? It could also be a Windows vs. Linux thing (though I'd expect symlink issues on Windows, not the other way around).

**Comment by StorytellerCZ** [comment] 2021-05-07 20:48
@trusktr Did you manage to get around to making a reproduction? Did the solution from @edemaine helped?

**Comment by StorytellerCZ** [comment] 2021-07-15 08:19
I'm closing this issue because we haven't heard anything here for a while. Feel free to put reproduction here and we'll re-open this.

**Closed by StorytellerCZ** 2021-07-15 08:19 UTC
Labels: Type:Bug, confirmed, needs-reproduction
