### ISSUE TITLE
Assets referenced by url() in CSS do not load when ROOT_URL is set.

### ISSUE THREAD

**Issue by arigesher** [meteor/meteor#3152] opened 2014-11-21 22:27 UTC
This seems somewhat similar to https://github.com/meteor/meteor/issues/2106 but perhaps a bit different.

I have a number of font and svg files referenced in some less stylesheets that look like this:

```
@font-face {
  font-family: 'DinNextLT-400-normal';
  src: url('../../resources/pt.bootstrap.theme/fonts/DINNextLTW04-Regular.eot');
  src: local('☺'),
       url('../../resources/pt.bootstrap.theme/fonts/DINNextLTW04-Regular.eot?#iefix') format('embedded-opentype'),
       url('../../resources/pt.bootstrap.theme/fonts/DINNextLTW04-Regular.woff') format('woff'),
       url('../../resources/pt.bootstrap.theme/fonts/DINNextLTW04-Regular.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
```

These live in `client/less/blueprint/fonts.less`. 

When I deploy the app to my server, I'm running it behind nginx, mounted on a path on a larger server - so the app lives at `http://server/app/p/` and I run meteor with `ROOT_URL=http://server/app/p/`.

Running in development, without nginx, everything works fine.

Behind nginx, the fonts don't load and I see these messages in the javascript console on the client:

> GET http://server/resources/pt.bootstrap.theme/fonts/DINNextLTW04-Regular.ttf  404 (not found)

Note that the resource should be at http://server/**app/p**/resources/pt.bootstrap.theme/fonts/DINNextLTW04-Regular.ttf

The rewrites look consistent (not including ROOT_URL) with other assets when I inspect program.json.

**Comment by glasser** [comment] 2015-01-26 23:39
We fixed some things related to CSS and `$ROOT_URL` in 1.0.3.1 (see eg #3111).  I'm not sure if this fixes your issue or not because your issue doesn't have a clear reproduction recipe that makes it trivial for me to reproduce your setup and see if the issue still exists.  See  https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor for advice.  But maybe 1.0.3.1 did fix your issue?

**Comment by tomusdrw** [comment] 2015-03-27 08:06
Hi!
I'm having the same problem with fonts path on Meteor 1.0.4.2.

Here you can find minimal project that reproduces this behavior.
https://github.com/tomusdrw/meteor-issue-3152

Meteor tries to fetch the font without prefix. Fetching from `http://localhost:3002/xyz/fonts/anything.*` would be expected.

![image](https://cloud.githubusercontent.com/assets/581548/6864352/5d84d74e-d460-11e4-98d5-a0c1c2451f3b.png)

**Comment by glasser** [comment] 2015-03-28 05:44
This reproduction is a little hard to follow since the given fonts aren't actually in the repo, so the only thing we're looking for is "what does the error look like", not "does it work or not" (and my Chrome seems to cache the error sometimes and not retry on every load).

That said, there does seem to be a problem here; the `url('fonts/anything.eot')` is being processed into `url('/fonts/anything.eot')`.

Unfortunately, I think this is actually difficult to fix in the current model.  That's because CSS preprocessing is done at build time, but ROOT_URL is set at serve time.  The CSS preprocessing involves merging files into a single file at the root of the app (not necessarily the root of the domain), which requires urls to be rewritten (see `CSSTools.rewriteCssUrls`), but one would have to re-rewrite URLs again at serve time if the root URL path prefix is non-null.  I guess that's what we have to do here...

(I forget why we always merge CSS files; I think it's because we do for minification, and it leads to a more consistent experience if we consistently merge.)

**Comment by tomusdrw** [comment] 2015-03-28 08:23
That's exactly what's happening. I looked at `CSSTools.rewriteCssUrls` function as you suggested.
Do you know why in this function we rewrite everything to absolute urls? (concatenation?)
Wouldn't rewriting always to relative form solve all issue with `ROOT_URL`? Is it safe to assume that location of CSS file is predictable?

Here is a modified test case that I'm thinking of:
```javascript
parseOptions.source = 'packages/nameOfPackage/style.css';
  t('../image.png', '../image.png', 'parent directory');
  t('./../image.png', '../image.png', 'parent directory');
  t('../nameOfPackage2/image.png', '../nameOfPackage2/image.png', 'cousin directory');
  t('../../image.png', '../../image.png', 'grand parent directory');
  t('./image.png', './image.png', 'current directory');
  t('./child/image.png', './child/image.png', 'child directory');
  t('child/image.png', './child/image.png', 'child directory');
  t('/image.png', '../../image.png', 'absolute url');
  t('"/image.png"', '"../../image.png"', 'double quoted url');
  t("'/image.png'", "'../../image.png'", 'single quoted url');
  t('"./../image.png"', '"../image.png"', 'quoted parent directory');
  t('http://i.imgur.com/fBcdJIh.gif', 'http://i.imgur.com/fBcdJIh.gif', 'complete URL');
  t('"http://i.imgur.com/fBcdJIh.gif"', '"http://i.imgur.com/fBcdJIh.gif"', 'complete quoted URL');
  t('data:image/png;base64,iVBORw0K=', 'data:image/png;base64,iVBORw0K=', 'data URI');
  t('http://', 'http://', 'malformed URL');

  parseOptions.source = 'application/client/dir/other-style.css';
  t('./image.png', './image.png', 'base path is root');
  t('./child/image.png', './child/image.png', 'child directory from root');
  t('child/image.png', './child/image.png', 'child directory from root');
  t('/image.png', './image.png', 'absolute url');
  t('"/image.png"', '"./image.png"', 'double quoted url');
  t("'/image.png'", "'./image.png'", 'single quoted url');
  t('http://i.imgur.com/fBcdJIh.gif', 'http://i.imgur.com/fBcdJIh.gif', 'complete URL');
  t('"http://i.imgur.com/fBcdJIh.gif"', '"http://i.imgur.com/fBcdJIh.gif"', 'complete quoted URL');
  t('data:image/png;base64,iVBORw0K=', 'data:image/png;base64,iVBORw0K=', 'data URI');
  t('http://', 'http://', 'malformed URL');
```

**Comment by glasser** [comment] 2015-03-28 15:13
Oh, er, good point!

**Comment by tomusdrw** [comment] 2015-03-28 16:54
Ok. I will try to implement this in couple of days and will let you know if this works;)

**Comment by tysonclugg** [comment] 2015-07-06 04:09
@glasser -  I've signed the contributor agreement which is the reason the PR build failed - can you review https://github.com/meteor/meteor/pull/4648 please?

**Comment by SierraGolf** [comment] 2015-07-06 06:08
+1

**Comment by SierraGolf** [comment] 2015-07-07 07:19
fyi: I tested #4648 (because I urgently need this to work) and it works nicely.

**Comment by adrprado** [comment] 2015-11-13 15:07
@SierraGolf, what was the ROOT_URL you used to solved your issue? I am setting what I believe is the correct ROOT_URL, but Meteor removes the relative path ("../..") replacing it with "/".

**Comment by abernix** [comment] 2016-09-16 07:29
There have been a number of fixes to the CSS asset URL that his used in conjunction with `ROOT_URL` since this issue was originally opened.  Off the top of my head, I found #5841, #7357 and various commits inside #7416.

I'm closing this particular issue as I'm fairly confident that it's not an issue anymore but if this issue is still plaguing anyone, I would encourage them to open a new issue with a fresh reproduction with the latest Meteor.

**Closed by abernix** 2016-09-16 07:29 UTC
Labels: Project:Isobuild:Minifiers, Project:Webapp, pull-requests-encouraged
