### ISSUE TITLE
this.userId has wrong value in method

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#4261] opened 2015-04-23 12:44 UTC
Consider the following code:

```javascript
//---------------------------------

if (Meteor.isServer)
  Meteor.users.remove({});

//---------------------------------

Meteor.methods({

  // Create a user account
  createJohnAccount: function () {
    Accounts.createUser({
      username: 'john',
      email   : 'john@g.com',
      password: '123456'
    });
  },

  // Delete the current user then call 'doSomething'
  removeUser: function () {
    console.log('BEGIN - deleteUser: about to remove user ' + this.userId);
    Meteor.users.remove(this.userId);
    console.log('END   - deleteUser: user has now been removed');
    Meteor.call('doSomething');
  },

  // Do something based on userId
  doSomething: function () {
    console.log('this.userId = ' + this.userId + ' (shouldn\'t it be null?!)');
  }
});

//---------------------------------

// On client...
if (Meteor.isClient) {
  Meteor.startup(function () {
    // create a user...
    Meteor.call('createJohnAccount', function (error, result) {
      // then log him in...
      Meteor.loginWithPassword('john', '123456', function (error) {
        // then remove him...
        Meteor.call('removeUser');
      });
    });
  });
}

//---------------------------------
```
It gives this output both on client and server:
```
I20150423-14:40:51.199(2)? BEGIN - deleteUser: about to remove user qkY5CaAJJ6Sx9nJgm
I20150423-14:40:51.201(2)? END   - deleteUser: user has now been removed
I20150423-14:40:51.202(2)? this.userId = qkY5CaAJJ6Sx9nJgm (shoudln't it be null?!)
```

In a method, shouldn't `this.userId` be `null` after user removal?

(please let me know if you need a repo)

**Comment by mitar** [comment] 2015-04-23 22:53
> (please let me know if you need a repo)

You should always make a repo, based on Meteor bug request guidelines.

This is a duplicate of #4262.

**Comment by steph643** [comment] 2015-04-24 09:28
Here is a fix, thanks to @mitar and @splendido:
```javascript
   removeUser: function () {
      // Do this *before* removing the user. See https://github.com/meteor/meteor/issues/4262
      this.setUserId(null);
      // Actually remove the current user
      Meteor.users.remove(this.userId);
    }
```
I think this deserves a line in the Meteor doc.

**Comment by glasser** [comment] 2015-04-28 22:59
Thanks @mitar , a proper reproduction would have been helpful.

This is basically working as intended.  There is a process to close all active connections (including the current one) when a user object is deleted (or the connection's login token is removed from it) but it's an asynchronous process.  If you want to make sure that the user is logged out immediately after removing the document, just add a `Meteor.logout()` after the `remove` call to be sure to make it synchronous.

I can't think of a way to make this guarantee (that whenever you start running a method, the token is still in the database) without major performance impacts on all apps that use `accounts-base`; deleting yourself from a method without using `Meteor.logout()` seems like a rare enough use case to not be worth the performance impact.

If you have suggestions on how to implement this in a way that performs well, or a documentation PR that makes this more clear, that would be great!

**Closed by glasser** 2015-04-28 22:59 UTC
Labels: Project:Accounts (in user apps)

**Comment by steph643** [comment] 2015-04-29 09:36
@glasser, thanks a lot. Your explanation makes perfect sense.

Issues https://github.com/meteor/meteor/issues/4261, https://github.com/meteor/meteor/issues/4262 and https://github.com/meteor/meteor/issues/4263 make it overly complex to implement the "Delete My Account" feature. As this feature is (or should be) part of any application, I think updating the Meteor doc is required. I am about to issue a PR.

**Comment by steph643** [comment] 2015-04-29 09:39
For those landing here, the actual solution is to call `Meteor.call('logout')` **before** `remove()`, as described in https://github.com/meteor/meteor/issues/4263.

**Comment by steph643** [comment] 2015-04-29 12:10
@glasser:

There is a problem with calling `Meteor.call('logout')` instead of ` this.setUserId(null)`, as proposed earlier in this thread. The `logout` method is asynchronous and take 2 to 5 seconds to complete. In the meantime, on the client, `Meteor.userId()` still returns the former user id, allowing the logged-out user to perform actions authorized to logged-in users only (until he gets caught by a server-side exception).

So what I did is using the (undocumented !) client-side version of `setUserId()`:
```javascript
  removeUser: function () {
    if (Meteor.isClient)
      this.setUserId(null);
    else {
      var id = this.userId;
      Meteor.call('logout');
      Meteor.users.remove(this.userId);
    }
  }
```
This seems to work, but I have one question: do you confirm calling `setUserId(null)` on the client has no server-side effect? I am asking because I am afraid of the following scenario:
 1. Client-side call to `setUserId(null)` actually logs the user out.
 2. Then only is `removeUser` executed on the server, and it fails because there is no logged-in user anymore.

**Comment by mitar** [comment] 2015-04-29 12:14
See #3912 about undocumented `setUserId`.

**Comment by glasser** [comment] 2015-05-27 23:59
`connection.setUserId` on the client has no server-side effects.
