### ISSUE TITLE
METEOR@1.6.1-rc.9 meteor run ios-device android-device runs production

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#9557] opened 2018-01-21 02:39 UTC
OSX HighSierra

In the Chrome console Meteor.isProduction results in true

Because of this I am getting `[ERROR: Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build `

For the same reason, my devices don'tt connect locally unless I remove force-ssl.

I am pretty sure in 1.6.0.1 running with devices would be doing in dev and not prod.

**Comment by hwillson** [comment] 2018-01-21 18:17
Thanks @paulincai - this is a duplicate of https://github.com/meteor/meteor/issues/8096, so let's continue the discussion over there.

**Closed by hwillson** 2018-01-21 18:17 UTC
