### ISSUE TITLE
‘run ios-device’ fails – copy-www-build-step.js deletes provisioning file

### ISSUE THREAD

**Issue by RealHandy** [meteor/meteor#10863] opened 2020-01-14 18:38 UTC
As described here:

https://forums.meteor.com/t/run-ios-device-fails-copy-www-build-step-js-deletes-provisioning-file/51379

I'm having to comment out a line of copy-www-build-step.js
`//shell.rm('-rf', path.join(dstDir, 'embedded.mobileprovision'));

to get the play button of Xcode to install the app on my device for debugging. Here are excerpts from my support issue with Apple that isolated the problem.

> Please provide a descriptive title for your feedback:
> Xcode won't run debugger on iPhone due to wrong "A valid provisioning profile for this executable was not found" error
> Which area are you seeing an issue with?
> Xcode
> What type of feedback are you reporting?
> Incorrect/Unexpected Behavior
> Details
> What version of Xcode are you using?
> Xcode 11.2.1 GM Seed, Xcode 11.2
> Description
> Please describe the issue:
> When I build/run my App in Xcode on my connected iPhone 7 Plus, the app builds successfully, installs, and then does this (see full error message below). It works in the iPhone simulator.
> 
> Unable to install "Vium"
> --
> App installation failed
> Code: -402620395
> Failure Reason: A valid provisioning profile for this executable was not found.
> --
> Please list the steps you took to reproduce the issue:
> Note: I've done all of this a million times over the past two years and, except when there are Xcode bugs or real provisioning issues, it works)
> 
> 1. Open the Xcode workspace that was generated by a 'meteor run ios device' command
> 2. Set the signing to accepted values
> 3. Hit the Build/Run button to install and run the app on my connected (wired or wifi, either one) iPhone
> What did you expect to happen?
> I expect it to install and run the app, as it does successfully on the simulator.
> What actually happened?
> After all the building/installing progress messages, instead of running, I get a popup with nothing but
> Failed to install "Vium"
> 
> If the phone is locked, it does all of the building, then waits for the app to be unlocked, then provides this error popup.
> Apple
> Nov 21, 2019 at 6:08 AM
> After reviewing your feedback, we need more information to continue our investigation.
> 
> Please capture a sysdiagnose from your device and attach it here. Please also attach a copy of your app that reproduces the issue, if possible.
> ...
> Can you please reproduce this and then copy your app from your DerivedData directory and attach it to this bug report. I’d like to take a look at the embedded profile.
> ...
> Apple
> After reviewing your feedback, we need more information to continue our investigation.
> 
> The attached app doesn’t contain a provisioning profile. Can you still reproduce this? If so, can you attach your project file (we don’t need sources) and a full build log (make sure you are viewing all content of the log using the scope buttons at the top of the window before exporting)?
> ...
> 
> Apple
> Dec 20, 2019 at 8:02 PM
> After reviewing your feedback, we have some additional information for you.
> 
> The build log shows the profile being copied into the app bundle. However, a script subsequently runs:
> 
> PhaseScriptExecution Copy\ www\ directory /Users/opx/Library/Developer/Xcode/DerivedData/Vium-euswudncmerzyeanwvinmsjnjwsc/Build/Intermediates.noindex/Vium.build/Debug-iphoneos/Vium.build/Script-304B58A110DAC018002A0835.sh (in target 'Vium' from project 'Vium')
>     cd /Users/opx/vium/.meteor/local/cordova-build/platforms/ios
>     /bin/sh -c /Users/opx/Library/Developer/Xcode/DerivedData/Vium-euswudncmerzyeanwvinmsjnjwsc/Build/Intermediates.noindex/Vium.build/Debug-iphoneos/Vium.build/Script-304B58A110DAC018002A0835.sh
> 
> What’s this script doing? It must be deleting the profile, at least, because it’s no longer there in the attached app.
> 

Script-304B58A110DAC018002A0835.sh calls copy-www-build-step.js, which deletes the profile.

**Comment by RealHandy** [comment] 2020-02-16 17:54
Cut it out, stale-bot — this hasn’t been resolved or even looked into yet.

**Comment by RealHandy** [comment] 2020-03-06 17:41
Still having this issue after update to meteor 1.9.2, iOS 13.3.

**Comment by RealHandy** [comment] 2020-03-06 17:44
Same problem also occurs in the iOS build project created by meteor .build

**Comment by filipenevola** [comment] 2020-03-06 18:25
@RealHandy can you reproduce this issue on Meteor 1.10-rc.4?

**Comment by filipenevola** [comment] 2020-03-11 19:26
As we don't have feedback and I can't reproduce this I'm assuming it is fixed on 1.10.rc.4.

**Closed by filipenevola** 2020-03-11 19:26 UTC

**Comment by RealHandy** [comment] 2020-03-11 21:50
It’s not reproducible, which means it works for everyone even though that line removes their mobileprovision. My workaround is working. I assume this is a strange edge case that could be related to who knows what in my years-old-and-updated-a-million-times environment. The usual reasons for not wanting to install a release candidate apply, so I’ll check it on 1.10 and keep applying the workaround if it’s not fixed.
