### ISSUE TITLE
Meteor crash if too many files in 'public'

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#8236] opened 2017-01-11 10:56 UTC
Hello,
Just after creating a meteor application, (meteor create test), I created the 'public' directory and insert my files (310 files, 19 folders, 1.4 GB)
When I start meteor, meteor crash with the error:

P:\projet_test\test>meteor
[[[[[ ~\P\projet_test\test ]]]]]

=> Started proxy.
=> Started MongoDB.
C:\Users\YVAN\AppData\Local\.meteor\packages\templating-compiler\1.2.15\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:177
      throw error;
      ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:166:12)
    at new Buffer (buffer.js:56:12)
    at Object.fs.readFileSync (fs.js:419:16)
    at wrapper (C:\tools\fs\files.js:1535:35)
    at wrap.makeCacheKey._len2 (C:\tools\fs\optimistic.js:22:15)
    at Entry._reallyRecompute (C:\Users\YVAN\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\optimism\lib\entry.js:215:26)
    at Entry._recomputeIfDirty (C:\Users\YVAN\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\optimism\lib\entry.js:179:17)
    at Entry.recompute (C:\Users\YVAN\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\optimism\lib\entry.js:46:20)
    at optimistic (C:\Users\YVAN\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\optimism\lib\index.js:50:18)
    at C:\tools\fs\optimistic.js:189:17
    at wrap.makeCacheKey._len2 (C:\tools\fs\optimistic.js:22:15)
    at Entry._reallyRecompute (C:\Users\YVAN\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\optimism\lib\entry.js:215:26)
    at Entry._recomputeIfDirty (C:\Users\YVAN\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\optimism\lib\entry.js:179:17)
    at Entry.recompute (C:\Users\YVAN\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\optimism\lib\entry.js:46:20)
    at optimistic (C:\Users\YVAN\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\optimism\lib\index.js:50:18)
    at Watcher._fireIfFileChanged (C:\tools\fs\watch.js:375:19)
    at C:\tools\fs\watch.js:441:12
    at Function._.each._.forEach (C:\Users\YVAN\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at Watcher._startFileWatches (C:\tools\fs\watch.js:430:7)
    at new Watcher (C:\tools\fs\watch.js:358:10)
    at setupClientWatcher (C:\tools\runners\run-app.js:786:23)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:797:7)
    at AppRunner._fiber (C:\tools\runners\run-app.js:876:28)
    at C:\tools\runners\run-app.js:403:12

P:\projet_test\test>

Is this a bug and if there is a solution
Thank you for your reply.
YC

**Comment by ramezrafla** [comment] 2017-01-16 11:48
@ghost 1GB public is huge! How will you push into production? Imagine each time you make a fix. While it can be claimed that it's a bug in Meteor that there is a cap on buffer size, I can sympathize with the developers who wouldn't invest time fixing bugs that go against good practices.

You could use cloudfront backed by s3 for instance for these files.

**Comment by ramezrafla** [comment] 2017-01-24 01:34
I think we can close this one too

**Comment by abernix** [comment] 2017-01-24 04:28
I agree that this is a lot of files and not a recommended use pattern, but I think we need to truly consider the ramifications (and necessity) of Meteor watching all those files.

In some ways, this could be tagged as related to #6952.

I'll leave this open at the moment as I think this is a weird developer experience (and potentially a bug that could be fixed?).  If anything, Meteor could warn about it maybe?

**Comment by hwillson** [comment] 2017-11-06 17:06
Since https://github.com/meteor/meteor/issues/6952 has been addressed, it's possible the problem outlined here is no longer an issue. It's difficult to verify completely since the OP didn't include a reproduction (and their account no longer exists so we can't get in touch with them), but fingers crossed this is no longer an issue. Closing for now - thanks!

**Closed by hwillson** 2017-11-06 17:06 UTC
