### ISSUE TITLE
Mongo package recursive function call crashing production app

### ISSUE THREAD

**Issue by jfurneaux** [meteor/meteor#8375] opened 2017-02-15 15:49 UTC
Difficult to raise this helpfully, will do my best!

Meteor version: 1.4.2.3
OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

Our production app (hive.com) experiences a call stack crash approximately once every 2 days.

Through extensive investigation, we've narrowed it down to the oplog observer inside the Mongo package, specifically this section where we inserted a console.log to watch it rerun:

```
Meteor.defer(finishIfNeedToPollQuery(function () {
    while (!self._stopped && !self._needToFetch.empty()) {
          console.log('finishIfNeedToPoll: ' + self._cursorDescription.collectionName);

          if (self._phase === PHASE.QUERYING) {
            // While fetching, we decided to go into QUERYING mode, and then we
            // saw another oplog entry, so _needToFetch is not empty. But we
            // shouldn't fetch these documents until AFTER the query is done.
            break;
          }
```

When the application server gets into its spin, this reruns hundreds/thousands of times:

![image](https://cloud.githubusercontent.com/assets/1825452/23027288/cf24ee5a-f431-11e6-9e91-492542e67b78.png)

...eventually ending in a call stack crash:

```
rror        [ 'RangeError: Maximum call stack size exceeded', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '---------------------------------------------', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at null._.extend._scheduleRun (packages/meteor.js:783:5)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at null._.extend.queueTask (packages/meteor.js:749:10)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at ObserveMultiplexer._applyCallback (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/observe_multiplex.js:152:17)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at ObserveMultiplexer.self.(anonymous function) [as removed] (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/observe_multiplex.js:26:12)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at /bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_observe_driver.js:233:25', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at Object.Meteor._noYieldsAllowed (packages/meteor.js:671:12)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at OplogObserveDriver._removePublished (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_observe_driver.js:231:12)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at OplogObserveDriver.proto.(anonymous function) [as _removePublished] (packages/meteorhacks_kadira.js:2966:25)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at /bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_observe_driver.js:380:14', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '---------------------------------------------', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at Object.setImmediate [as _setImmediate] (packages/meteor.js:323:14)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at Object._.extend.defer (packages/meteor.js:514:12)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at OplogHandle._maybeStartWorker (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_tailing.js:253:12)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at /bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_tailing.js:242:14', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at loop (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/mongo_driver.js:1147:9)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at null._.extend.withValue (packages/meteor.js:1122:17)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at packages/meteor.js:445:45', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at runWithEnvironment (packages/meteor.js:1176:24)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '---------------------------------------------', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at handleOperationCallback (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:454:24)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:490:9', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at authenticateStragglers (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:429:16)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at null.messageHandler (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:463:5)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at TLSSocket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:309:22)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at emitOne (events.js:77:13)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at TLSSocket.emit (events.js:169:7)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at readableAddChunk (_stream_readable.js:153:18)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at TLSSocket.Readable.push (_stream_readable.js:111:10)' ] } 
Feb 15 05:02:47 appserver4-hive-production default:  info === 
```

What conditions could cause this to rerun endlessly?

Many thanks!

John

**Comment by jfurneaux** [comment] 2017-02-15 15:54
Difficult to raise this helpfully, will do my best!

Our production app (hive.com) experiences a call stack crash approximately once every 2 days.

Through extensive investigation, we've narrowed it down to the oplog observer inside the Mongo package, specifically this section where we inserted a console.log to watch it rerun:

`Meteor.defer(finishIfNeedToPollQuery(function () {
        while (!self._stopped && !self._needToFetch.empty()) {

          console.log('finishIfNeedToPoll: ' + self._cursorDescription.collectionName);

          if (self._phase === PHASE.QUERYING) {
            // While fetching, we decided to go into QUERYING mode, and then we
            // saw another oplog entry, so _needToFetch is not empty. But we
            // shouldn't fetch these documents until AFTER the query is done.
            break;
          }
`

When the application server gets into its spin, this reruns hundreds/thousands of times, sometimes resulting in a full call stack error and crashing:

rror        [ 'RangeError: Maximum call stack size exceeded', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '---------------------------------------------', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at null._.extend._scheduleRun (packages/meteor.js:783:5)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at null._.extend.queueTask (packages/meteor.js:749:10)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at ObserveMultiplexer._applyCallback (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/observe_multiplex.js:152:17)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at ObserveMultiplexer.self.(anonymous function) [as removed] (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/observe_multiplex.js:26:12)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at /bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_observe_driver.js:233:25', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at Object.Meteor._noYieldsAllowed (packages/meteor.js:671:12)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at OplogObserveDriver._removePublished (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_observe_driver.js:231:12)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at OplogObserveDriver.proto.(anonymous function) [as _removePublished] (packages/meteorhacks_kadira.js:2966:25)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at /bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_observe_driver.js:380:14', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '---------------------------------------------', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at Object.setImmediate [as _setImmediate] (packages/meteor.js:323:14)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at Object._.extend.defer (packages/meteor.js:514:12)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at OplogHandle._maybeStartWorker (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_tailing.js:253:12)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at /bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_tailing.js:242:14', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at loop (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/mongo_driver.js:1147:9)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at null._.extend.withValue (packages/meteor.js:1122:17)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at packages/meteor.js:445:45', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at runWithEnvironment (packages/meteor.js:1176:24)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '---------------------------------------------', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at handleOperationCallback (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:454:24)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:490:9', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at authenticateStragglers (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:429:16)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at null.messageHandler (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:463:5)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at TLSSocket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:309:22)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at emitOne (events.js:77:13)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at TLSSocket.emit (events.js:169:7)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at readableAddChunk (_stream_readable.js:153:18)', 
Feb 15 05:02:47 appserver4-hive-production default:  error          '    at TLSSocket.Readable.push (_stream_readable.js:111:10)' ] } 
Feb 15 05:02:47 appserver4-hive-production default:  info === 

What conditions could cause this to rerun endlessly (up to 5 minutes continuously)?

Many thanks!

John

**Comment by hwillson** [comment] 2017-04-20 13:45
Hi @jfurneaux - sorry to hear you're having trouble! Unfortunately, this is a very difficult issue to troubleshoot without some kind of reproduction demonstrating the problem (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). I know creating a reproduction for an issue like this (that only seems to have every couple of days) is a real pain, but without it there isn't much that can be done to help diagnose the issue. If I was to make a guess, maybe the `!self._needToFetch.empty()` check is never returning `false`, which keeps the loop running? Have you tried adding a `console.log(self._needToFetch.size());` call at the beginning of the `while` loop, to see if it changes?

The above being said, I'll close this issue for now. I know this isn't the answer you want to hear, but if you're able to put together a reproduction for this, we're happy to re-open this issue at any point. Thanks!

**Closed by hwillson** 2017-04-20 13:45 UTC

**Comment by etyp** [comment] 2017-05-03 12:06
@hwillson taking this over on behalf of @jfurneaux (same production app).

I've added your suggested logging, so I'll be sure to update the thread once we can tell if `self._needToFetch.size()` is stuck/not changing.

Like you said, it's difficult to recreate a production issue that only occurs once every few days, but with that in mind it would be great to know any potential next steps, ideas on root cause, etc. We've tried our best to recreate this issue in smaller Meteor apps by attempting to choke the oplog, time out mongo and plenty more.

**I know this comment isn't very conclusive, but assuming `self._needToFetch.size()` is never emptied, what might the root cause?**

I'll update the issue once logging is live and we experience the issue again.

**Comment by etyp** [comment] 2017-05-04 17:22
@hwillson @stubailo  following up here as we just had the incident again.

I've added logging in the `while` loop to see if `self._needToFetch.size()` gets stuck and never breaks the loop, like so:

```
        while (!self._stopped && !self._needToFetch.empty()) {
          console.log('finishIfNeedToPollQuery while - _needToFetch size:');
          console.log(self._needToFetch.size());
          if (self._phase === PHASE.QUERYING) {
            // While fetching, we decided to go into QUERYING mode, and then we
            // saw another oplog entry, so _needToFetch is not empty. But we
            // shouldn't fetch these documents until AFTER the query is done.
            console.log('Breaking finishIfNeedToPollQuery while');
            break;
          }
          console.log('*************************************************');
          // ...
        }
```

The incident just happened and our logs show that `self._needToFetch.size()` does in fact never change. It gets set to 1 and keeps running until the `RangeError: Maximum call stack size exceeded ` throws.

A few things to note:
- This happens even when the app is not under considerable load
- Kadira shows **absolutely no** spike in live queries, method throughput/response time, sub rates, pub response times, sessions, observer creation, cpu usage or memory usage on the box that experienced it (nor on any of the other boxes)
- Mongo package is at mongo@1.1.17
- Meteor is at METEOR@1.4.4.1
- This has happened to us since we were on Meteor 1.3


This issue is absolutely wrecking us, and we're a bit concerned at the fact that a never ending while loop exists in the core mongo package, especially since this is happening without any sudden spike in load.

**What next steps can I take here to try to get to the bottom of this?** I know it's difficult for you to help out without a consistent reproduction, but I need advice on where to add logging so we can help identify the root cause of this one.

Finally, based on your knowledge of the oplog observe driver, **what would cause `self._needToFetch.size()` to never empty out?**
