### ISSUE TITLE
`TypeError: Cannot supply flags when constructing one RegExp from another`

### ISSUE THREAD

**Issue by d4nyll** [meteor/meteor#6988] opened 2016-05-06 07:52 UTC
In one of my methods, I have the following code:

```
let classNameRegEx = new RegExp(/^className[0-9]{1,2}$/, 'ig');
```

On the server, it gives this error when the method is ran:

```
TypeError: Cannot supply flags when constructing one RegExp from another
```

According to [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/RegExp):

> Starting with ECMAScript 6, new RegExp(/ab+c/, 'i') no longer throws a TypeError ("can't supply flags when constructing one RegExp from another") when the first argument is a RegExp and the second flags argument is present. A new RegExp from the arguments is created instead.

I have the `ecmascript` package installed on the app, so if I am not mistaken, it should no longer throw this error.

---

I have created a [repository](https://github.com/d4nyll/meteor-regex-flags) for this issue. All it is is an empty Meteor app, with `let myRegEx = new RegExp(/^className[0-9]{1,2}$/, 'ig');` added to the `server/main.js`
1. I first created an empty repository
   
   ```
   $ meteor create regex-flags
   ```
2. Changed the `server/main.js` to:
   
   ```
   import { Meteor } from 'meteor/meteor';
   
   Meteor.startup(() => {
     let myRegEx = new RegExp(/^className[0-9]{1,2}$/, 'ig');
   });
   ```

**Comment by abernix** [comment] 2016-05-06 08:41
First of all, thank you very much for including a very clear explanation and reproduction.

You're right that this should work based on the spec, however Meteor code is currently using `babel-runtime` 5.x and I think this is fixed in a newer version.  I believe there is work underway already to make this upgrade happen (though I'll have to dig a bit more for the issue).

**However, as a work-around**, it does work if you just put the flags directly after the regex frames:

```js
let myRegEx = new RegExp(/^className[0-9]{1,2}$/ig);
```
or even better, use the shorthand version:
```js
let myRegEx = /^className[0-9]{1,2}$/ig;
```

And if you do need to actually change the flags on an existing Regex object, you could do something like this:
```javascript
let myRegEx = /^className[0-9]{1,2}$/ig;
let myRegEx2 = new RegExp(myRegEx.source, "g");
```

**Comment by d4nyll** [comment] 2016-05-06 08:46
Thanks @abernix!

**Comment by hwillson** [comment] 2017-01-26 02:56
I just updated and tested the provided repo with Meteor 1.4.2.3 (using `babel-runtime` version 6.18.0) and still see the same error. That being said, the workarounds mentioned in https://github.com/meteor/meteor/issues/6988#issuecomment-217384430 are great, and since this issue hasn't had any activity in quite some time, I'll close it for now. Thanks for reporting this originally!

**Closed by hwillson** 2017-01-26 02:56 UTC
Labels: bug, confirmed, Impact:few, Project:JS Environment, Severity:has-workaround
