### ISSUE TITLE
Meteor1.3.1 add local plugin failed

### ISSUE THREAD

**Issue by Doris1994** [meteor/meteor#6810] opened 2016-04-13 09:03 UTC
after I update meteor to 1.3.1 in terminal
$  meteor create myApp
$ cd myApp
$ meteor add-platform ios
$ meteor add cordova:com.example.appsetup@file://../plugins/appsetup
$ meteor run ios-device --mobile-server http://xxx.xxx.xxx:8080
In xCode,run the project,ouput:

> CDVPlugin class AppSetup (pluginName: appsetup) does not exist.

there [http://guide.meteor.com/mobile.html#installing-plugins](url),say add plugin method is correct.

but  in [https://github.com/meteor/meteor/issues/6050](url),

> The plugin also allows for local file access on both iOS and Android. You can construct file system URLs manually (http://localhost:<port>/local-filesystem/<path>) or use WebAppLocalServer.localFileSystemUrl() to convert a file:// URL. On iOS, core plugins like cordova-plugin-file and cordova-plugin-camera (using Camera.DestinationType.FILE_URI) will now automatically return these URLs instead of file:// URLs

so I'm not very understanding，Please also help to explain, I should how to add local plugin. 

Thanks very much

**Comment by wojtkowiak** [comment] 2016-04-13 10:58
To me it seems that you are more likely having problems with your plugin itself. Check if you are including all necessary files in plugin.xml. Check in XCode if you can see all your plugins files under Plugins dir in your project scope.

**Comment by wojtkowiak** [comment] 2016-04-13 10:59
> The plugin also allows for local file access on both iOS and Android. You can construct file system URLs manually (http://localhost:/local-filesystem/) or use WebAppLocalServer.localFileSystemUrl() to convert a file:// URL. On iOS, core plugins like cordova-plugin-file and cordova-plugin-camera (using Camera.DestinationType.FILE_URI) will now automatically return these URLs instead of file:// URLs

This has nothing to do with adding cordova plugins from local path as far as I know.

**Comment by Doris1994** [comment] 2016-04-14 01:35
@wojtkowiak ，thank you for your help, and I'm pretty sure I don't have any problem of plugin，So I am wondering where the mistakes

**Comment by Doris1994** [comment] 2016-04-14 02:15
@wojtkowiak ，This plugin is available in the Meteor 1.2, added in the Meteor 1.3 without any mistakes, but after adding plugin path seems to be some problems，in Xcode，such a plugin path by `meteor add cordova: com.example.plugin@1.0.1 `
![screen shot 2016-04-14 at 10 04 03 am](https://cloud.githubusercontent.com/assets/16999234/14515106/2b1e4126-0229-11e6-8f7e-65e80c03e10e.png)

 ,and by `meteor add cordova: com. example. Appsetup @ file://../ plugins/appsetup`
![screen shot 2016-04-14 at 10 04 19 am](https://cloud.githubusercontent.com/assets/16999234/14515111/39e381f8-0229-11e6-900c-9751564fcac8.png)

Attach plugin's plugin.xml
`<?xml version="1.0" encoding="UTF-8"?>
<plugin xmlns="http://apache.org/cordova/ns/plugins/1.0"
        id="org.hotshare.shareExtension"
        version="1.0.0">

  <name>HotShareShareExtension</name>

  <description>
    To Get HotShare Application Share Extension Data.
  </description>

  <license>MIT</license>

  <engines>
    <engine name="cordova" version=">=3.0.0"/>
  </engines>
  <js-module src="www/ShareExtension.js" name="ShareExtension">
      <clobbers target="cordova.plugins.shareExtension" />
  </js-module>

  
  <platform name="ios">
    <config-file target="config.xml" parent="/*">
      <feature name="ShareExtension">
        <param name="ios-package" value="ShareExtension"/>
      </feature>
    </config-file>
    <header-file src="src/ios/ShareExtension.h"/>
    <source-file src="src/ios/ShareExtension.m"/>

  </platform>

</plugin>`

**Comment by Doris1994** [comment] 2016-04-14 02:36
`The plugin also allows for local file access on both iOS and Android. You can construct file system URLs manually (http://localhost:/local-filesystem/) or use WebAppLocalServer.localFileSystemUrl() to convert a file:// URL. On iOS, core plugins like cordova-plugin-file and cordova-plugin-camera (using Camera.DestinationType.FILE_URI) will now automatically return these URLs instead of file:// URLs`
That this passage is how to understand the specific what should I do

**Comment by martijnwalraven** [comment] 2016-04-14 08:23
This passage has nothing to do with adding plugins from the local file path, it is about access local files in a Cordova app.

It seems you receive build errors as a result of adding your plugin, so that is where you should be looking. Maybe the plugin doesn't support the most recent versions of the Cordova platforms?

**Comment by Doris1994** [comment] 2016-04-14 09:06
@martijnwalraven  This is my plugin configuration，any incorrect place？
![screen shot 2016-04-14 at 5 03 13 pm](https://cloud.githubusercontent.com/assets/16999234/14522803/e90d16f6-0262-11e6-9773-85d408ae1629.png)

**Comment by martijnwalraven** [comment] 2016-04-14 09:10
Is this a plugin you wrote yourself? If the error message is `CDVPlugin class AppSetup (pluginName: appsetup) does not exist.`, that suggests you may have made a mistake in naming your class or another coding error.

**Comment by Doris1994** [comment] 2016-04-14 09:13
The two plugins are wrote myself, all the same mistakes.

**Comment by martijnwalraven** [comment] 2016-04-14 09:16
But where does the `AppSetup` name come from?

**Comment by Doris1994** [comment] 2016-04-14 09:19
These are two different plug-ins, in fact, all the local plug-in can not find, I'm just, for example, I'm very sorry, may be I describe is not clear.
![screen shot 2016-04-14 at 5 17 50 pm](https://cloud.githubusercontent.com/assets/16999234/14523191/e859908e-0264-11e6-8238-50563816b179.png)

**Comment by martijnwalraven** [comment] 2016-04-14 09:23
Are the .h and .m files present in the Xcode project?

**Comment by Doris1994** [comment] 2016-04-14 09:26
Yes ,but there is something wrong with the path.Such as：
![screen shot 2016-04-14 at 10 04 19 am](https://cloud.githubusercontent.com/assets/16999234/14523372/ec8cd53e-0265-11e6-8e5a-14791e18673c.png)

**Comment by martijnwalraven** [comment] 2016-04-14 09:31
But if you look at the full path, is that where the file is actually stored? Can you open it from within Xcode?

**Comment by Doris1994** [comment] 2016-04-14 10:31
Should directly on the code, so that can describe more clearly, this is my address of the project, also need to trouble you to help me take a look at what went wrong, I really don't understand, thank you very much.
[https://github.com/Doris1994/myApp.git](url)

**Comment by martijnwalraven** [comment] 2016-04-14 10:39
I cloned your repo and was able to successfully build and run the app. So there may be something wrong with your setup.

**Comment by Doris1994** [comment] 2016-04-15 01:57
ok，I am trying to use the rm - rf ~ /. Meteor delete a meteor, then reinstall.

**Comment by Doris1994** [comment] 2016-04-15 02:29
I reinstall the Meteor, but seem to have no change, if use `meteor -v run ios-device --mobile-server localhost:3000` can run the app, but if it is `meteor build ~/testbuild1-myApp --server=localhost: 3000 ` open in Xcode have wrong information below：

> clang: error: no such file or directory: '/share-extension/src/ios/ShareExtension.m'
clang: error: no input files

**Comment by martijnwalraven** [comment] 2016-04-15 07:23
Ah, you didn't mention you were using `meteor build`! I was able to reproduce your issue and I now also see the difference with `meteor run`.

The problem is that local plugin paths are interpreted relative to the `cordova-build` directory, but `meteor build` allows you to specify your own location. I don't see an easy way to support both, and local plugins are most often used during development. But a workaround is to use absolute path, like `meteor add cordova:com.example.appsetup@file:///Users/aei/Meteor/plugins/appsetup`.

**Comment by Doris1994** [comment] 2016-04-15 08:33
I appreciate your help.but use absolute path still can't solve the problem.Get the same error message：

> clang: error: no such file or directory: '/share-extension/src/ios/ShareExtension.m'
clang: error: no input files

**Comment by martijnwalraven** [comment] 2016-04-15 08:45
Hmmm, I don't have time to look into this in more detail now, but another workaround would be to change the path of the plugin files in Xcode after `meteor build`.

**Comment by Doris1994** [comment] 2016-04-15 09:00
I also thought of this method, but too much trouble if you have a number of plugins will be a huge task.But still want to thank you for taking the time to help me, hoping to find better solution.

**Comment by martijnwalraven** [comment] 2016-04-15 09:04
But don't you use `meteor run` during development and only use `meteor build` for a production release?

Another options is not to rely on local plugins, but to either add them from your Git repository or publish them on npm.

**Comment by Doris1994** [comment] 2016-04-15 09:10
Uh huh, that's a good idea.Thank you very much, certainly can find problems and solve the real reason for the better.Maybe I'm too seriously, the lack of kone.

**Comment by martijnwalraven** [comment] 2016-04-28 16:02
Closing this because it seems the issue has been identified and a workaround is available.

**Closed by martijnwalraven** 2016-04-28 16:02 UTC
Labels: Project:Mobile

**Comment by jackkav** [comment] 2016-09-22 02:52
This is a problem we also encountered and due to environmental constraints don't have luxury of using npm or git to pull out plugins. We solved the issue by post meteor build find replacing paths in 4 files.

**Comment by dmitry-sher** [comment] 2016-10-01 05:20
This is still an open issue. And i can imagine a perfectly legitimate reason for this 'workaround' not being actual workaround! Because it still **wastes developers' precious time**.

There are some cordova plugins on github and sometimes you need a particular commit of them. And you can be in some country where github is running very slow. E.g., you are working with https://github.com/Telerik-Verified-Plugins/Facebook and you need commit c0f190e23bce93d7ca49da2b7a8078736d3143aa. Because MDG is not supporting Facebook login on mobile devices properly, so you use that plugin. This plugin weights about 50mb on github with the download time of 10-15minutes in Indonesia.

You don't want to waste your time just watching it downloading **every time** you make a build. So you add local cloned copy. When you are running app in simulator, it just works from filesystem. At least the build is fast.

But when you need to make actual build to test integration with Facebook app on a real device... it means that either you go to that ugly hacks tweaking your generated pbxproj. Or you remove it from your plugins list, install it from git, make build, revert everything back -- **wasting again time and bandwidth**.

Ugly, time-wasting, hurting.
