### ISSUE TITLE
Avoid meteor restart for import/*.js files if imported from client only

### ISSUE THREAD

**Issue by aruntk** [meteor/meteor#6754] opened 2016-04-08 17:57 UTC
### Expected Behavior.
When a file inside imports folder is changed meteor should restart only if the file is imported from the server. If its imported from a client side file then do a simple hot code reload just like what meteor does in the case of files inside client folder. 
### Actual Behavior.
Meteor gets restarted on file change regardless of whether its imported from client or server
### Steps to reproduce the behavior.
Add files client/main.js and imports/ui/test.js . import test.js from main.js.

**Comment by gbisheimer** [comment] 2016-04-09 04:27
This issue is also related to #6576.

**Comment by Akryum** [comment] 2016-04-25 10:08
I get this behavior in Meteor 1.3.2.4, despite the changelog showing the opposite.

**Comment by abernix** [comment] 2016-05-23 12:47
Duplicate of #6576.

**Closed by abernix** 2016-05-23 12:47 UTC
