### ISSUE TITLE
Unable to build a MeteorJS solution for browser

### ISSUE THREAD

**Issue by mareksagan** [meteor/meteor#7346] opened 2016-07-03 19:27 UTC
$ meteor build ../build --directory

/home/ubuntu/.meteor/packages/meteor-tool/.1.3.4_1.tskw1g++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: EACCES, open '/home/ubuntu/DOMAIN/.meteor/local/bundler-cache/linker/.4df410f6c0a19d50a458dd58f5933ff11c965465.cache.s1a18a'

I am running the newest version (03/07/2016) of MeteorJS, so 1.3.4.1. No additional packages were in use, except for Fibers and couple of others which MeteorJS uses by default. Permissions are IMO fine. Running it all on AWS EC2 (Ubuntu 14.04.4 LTS).

**Comment by abernix** [comment] 2016-07-04 11:45
This is too vague to provide assistance on.  Are you able to provide reproduction steps on a fresh Meteor project?   Do you have a large number of files in your project?  Does it still happen if you run `meteor reset` first?

**Comment by stej4n** [comment] 2016-07-04 12:27
Hi,

I have almost the same problem.
I'm trying to install meteor on a Ubuntu Trusty VM created with vagrant :
```
vagrant init ubuntu/trusty64
vagrant up --provider virtualbox
```

First, I wasn't able to install using `curl https://install.meteor.com/ | sh`

The followig error occured :
```
Downloading Meteor distribution
sh: 151: [[: not found
```

So I just put install script content in a install-meteor.sh file, made it executable with chmod +x and It worked.

Then I created a dev/meteor folder under ~ and started a test project usng 
```
meteor create test
```

It worked but when I launched meteor, it stopped with the following error :

```
vagrant@vagrant-ubuntu-trusty-64:~/dev/meteor/test$ meteor
[[[[[ ~/dev/meteor/test ]]]]]

=> Started proxy.
=> Started MongoDB.

/home/vagrant/.meteor/packages/meteor-tool/.1.3.4_1.tskw1g++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at Object.exports.spawn (child_process.js:746:9)
    at AppProcess._spawn (/tools/runners/run-app.js:264:31)
    at AppProcess.start (/tools/runners/run-app.js:86:22)
    at AppRunner._runOnce (/tools/runners/run-app.js:761:16)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
vagrant@vagrant-ubuntu-trusty-64:~/dev/meteor/test$

```

I tried `meteor reset` but It didn't solved the problem :(

**Comment by abernix** [comment] 2016-07-04 12:30
@stej4n Actually both are completely different errors and unrelated to the original.  The installer failing is due to #7353 and `ENOMEM` is because you do not have your vagrant box configured with enough RAM.

**Comment by stej4n** [comment] 2016-07-04 12:32
@abernix Thank you, I'll check this !

**Comment by mareksagan** [comment] 2016-07-08 23:58
@abernix This was a basic project, I just followed the documentation when it comes to steps... Done nothing else there

**Comment by mareksagan** [comment] 2016-07-08 23:59
By basic, I mean, Hello World-like :P

**Comment by abernix** [comment] 2016-07-11 07:34
Unfortunately, this doesn't provided any additional assistance in debugging.  I am able to build without any problem with a bare project on Ubuntu 14.04.  Here is my walk-through:

**Show Ubuntu Release**
```sh
ubuntu@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:  Ubuntu 14.04.4 LTS
Release:  14.04
Codename: trusty
```

**Show Meteor Version**
```sh
ubuntu@ubuntu:~$ meteor --version
Meteor 1.3.4.1
```

**Create an empty project and get ready to run**
```sh
ubuntu@ubuntu:~$ meteor create test-issue-7346
Created a new Meteor app in 'test-issue-7346'.
...abernix snipped output...
ubuntu@ubuntu:~$ cd test-issue-7346
ubuntu@ubuntu:~/test-issue-7346$ meteor npm install
test-issue-7346@ /home/ubuntu/test-issue-7346
└─┬ meteor-node-stubs@0.2.3
  ├── assert@1.3.0
  ├─┬ browserify-zlib@0.1.4
...abernix snipped output...
```

**First Meteor Run**
```sh
ubuntu@ubuntu:~/test-issue-7346$ meteor
[[[[[ ~/test-issue-7346 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
^C
```

**Try Building for Production**
```sh
ubuntu@ubuntu:~/test-issue-7346$ meteor build ../build --directory
ubuntu@ubuntu:~/test-issue-7346$ # Builds successfully without error.
```

Your problem sounds like a permission issue.  When you get this error, what happens when you show the full permissions of the file listed after `Error: EACCES, open`?

For example, in your original issue:

    ls -l /home/ubuntu/DOMAIN/.meteor/local/bundler-cache/linker/.4df410f6c0a19d50a458dd58f5933ff11c965465.cache.s1a18a

**Comment by abernix** [comment] 2016-08-02 11:03
I'm going to close this.  It seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)

**Closed by abernix** 2016-08-02 11:03 UTC
Labels: bug, can't-reproduce, Impact:few
