### ISSUE TITLE
[accounts-base] `Accounts.onLogin` infinite loop when `Meteor.logoutOtherClients` is called and multiple tabs are open.

### ISSUE THREAD

**Issue by janzenz** [meteor/meteor#8669] opened 2017-05-05 01:49 UTC
```
meteor@1.4.4.2
accounts-password      1.3.6  Password support for accounts
accounts-ui            1.1.9  Simple templates to add login widgets to an app
autopublish            1.0.7  (For prototyping only) Publish the entire database to all clients
blaze-html-templates   1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript             0.7.3  Compiler plugin that supports ES2015+ in all .js files
es5-shim               4.6.15  Shims and polyfills to improve ECMAScript 5 support
insecure               1.0.7  (For prototyping only) Allow all database writes from the client
meteor-base            1.0.4  Packages that every Meteor app needs
mobile-experience      1.0.4  Packages for a great mobile user experience
mongo                  1.1.17  Adaptor for using MongoDB and Minimongo over DDP
reactive-var           1.0.11  Reactive variable
shell-server           0.2.3  Server-side component of the `meteor shell` command.
standard-minifier-css  1.3.4  Standard css minifier used with Meteor apps by default.
standard-minifier-js   2.0.0  Standard javascript minifiers used with Meteor apps by default.
tracker                1.1.3  Dependency tracker to allow reactive callbacks
```

## Behaviour
There seems to be an infinite loop for the Accounts.onLogin when Meteor.logoutOtherClients is called inside it and when there are multiple TABS open. See my code below:

```
Accounts.onLogin(() => {
  console.log('onLogin')
  Meteor.logoutOtherClients((error) => {
    if (error) {
      console.log(`error: ${error.error}`)
    }
  })
})

```
The console.log gets called infinitely as you can see here:
![image](https://cloud.githubusercontent.com/assets/1410147/25731307/b61a8270-3177-11e7-804a-b57d7ba8ef2b.gif)
The problem is gone when you close another tab.

## Expected Behavior
I'm not sure if this is the right behavior but I needed to inject calls inside `Accounts.onLogin()` to perform some actions when a User logs in. For example welcoming a user with an alert:

```
Accounts.onLogin(() => {
  console.log('onLogin')
  Meteor.logoutOtherClients((error) => {
    if (error) {
      console.log(`error: ${error.error}`)
    }
  })

  alert('Welcome User')
})
```

Problem here is that the alert gets called infinitely. I think this is a problem since sometimes User would want to open multiple tabs and I think this is not a good UX if we won't allow users to open multiple tabs.

See minimum project setup [here](https://github.com/janzenz/accounts-base-bug) for bug replication.

**Comment by crapthings** [comment] 2017-05-05 07:41
what happend if u setTimeout with onLogin

```
Accounts.onLogin(() => {
  console.log('onLogin')

  Meteor.setTimeout(function () {

      Meteor.logoutOtherClients((error) => {
        if (error) {
        console.log(`error: ${error.error}`)
      }
    })

  }, 3000})
  
  

  alert('Welcome User')


})
```

**Comment by janzenz** [comment] 2017-05-05 14:39
@crapthings same thing. Only difference is the `onLogin` gets fired after 3 seconds.

**Comment by hwillson** [comment] 2017-05-09 01:04
Hi @janzenz - first off thanks very much for the detailed issue description and reproduction - these details really help! 

When `Meteor.logoutOtherClients()` is called, 2 main things happen:

1. A new login token is generated with the same expiration as the connection's current token, and saved to the database. The current connection is then associated with this new token.

2. All other tokens (excluding the token associated with the current connection) are then removed from the database, which effectively logs all other connections out.

During step 1 above however, when a new token is associated with the current connection, that new token is stored in the browsers `localStorage`. Since `localStorage` is shared between tabs, Meteor polls `localStorage` every few seconds to watch for token changes, to keep login state in synch between multiple browser tabs. When a change is found in `localStorage`, that tab then calls Meteor's login Method again (see [`Ap.callLoginMethod`](https://github.com/meteor/meteor/blob/f0dd494c82244df79b544bdbf590ebecc0412189/packages/accounts-base/accounts_client.js#L230)), to re-log that tab back in. This then ultimately calls the `onLogin` hook again, which calls `Meteor.logoutOtherClients` again, which then starts the process over again (and again and again ...).

Long story short, this isn't quite a bug per-say. `Meteor.logoutOtherClients` is technically functioning as designed; it's just that the `onLogin` hook + `Meteor.logoutOtherClients` combo doesn't work very well (even though both parts are actually working). As a workaround, I'd suggest trying something like the following:

```js
Accounts.onLogin(() => {
  console.log('onLogin');
});

Tracker.autorun(() => {
  if (Meteor.user()) {
    console.log('logging others out ...');
    Meteor.logoutOtherClients();
  }
});
```

This isn't 100% perfect as you'll still end up logging out/in a couple of times, but you won't get caught in an infinite loop.

Moving forward I'm not quite sure what the best course of action is. Do we just document this issue, try to patch it, or something else? I'll leave this issue open for further discussion/suggestions. Thanks for reporting this!

**Comment by hwillson** [comment] 2017-12-22 15:11
As mentioned in https://github.com/meteor/meteor/issues/8669#issuecomment-300032382, this isn't necessarily a bug. I'm going to close this issue off, but https://github.com/meteor/meteor/issues/8669#issuecomment-300032382 should serve as documentation for anyone else encountering this issue, and searching through GH issues.

**Closed by hwillson** 2017-12-22 15:11 UTC
Labels: confirmed, Project:Accounts (in user apps)
