### ISSUE TITLE
Cannot publish package, missing pluginProviderPackageMap in isopack

### ISSUE THREAD

**Issue by robertpitt** [meteor/meteor#3685] opened 2015-02-09 14:09 UTC
Hey guys,

I seem to be having issues publishing to atmosphere, I have published successfully before so not sure why this is happening now.

Here's my terminal output.

```bash
rpitt@robert-laptop-05:~/Projects/crest/packages/centiq:crest$ meteor --version
Meteor 1.0.3.1
rpitt@robert-laptop-05:~/Projects/crest/packages/centiq:crest$ node --version
v0.10.35
rpitt@robert-laptop-05:~/Projects/crest/packages/centiq:crest$ npm --version
1.4.28
rpitt@robert-laptop-05:~/Projects/crest/packages/centiq:crest$ meteor whoami
rpitt
rpitt@robert-laptop-05:~/Projects/crest/packages/centiq:crest$ meteor logout
Logged out.                                   
rpitt@robert-laptop-05:~/Projects/crest/packages/centiq:crest$ meteor login
Username: rpitt
Password:                                     
                                              
Logged in as rpitt. Thanks for being a Meteor developer!
rpitt@robert-laptop-05:~/Projects/crest/packages/centiq:crest$ ls
contributers.txt  COPYRIGHT  lib  package.js  README.md  tests
rpitt@robert-laptop-05:~/Projects/crest/packages/centiq:crest$ meteor publish --create
                                              
/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: no pluginProviderPackageMap on isopack?
    at Error (<anonymous>)
    at bundleSource (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/package-client.js:286:11)
    at /home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/package-client.js:675:26
    at /home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:317:26)
    at Object.exports.publishPackage (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/package-client.js:674:16)
    at /home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands-packages.js:422:21
    at /home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:245:19)
    at Object.main.captureAndExit (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/main.js:257:29)
    at Command.main.registerCommand.name [as func] (/home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands-packages.js:418:8)
    at /home/rpitt/.meteor/packages/meteor-tool/.1.0.40.iy2fxi++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/main.js:1300:23
rpitt@robert-laptop-05:~/Projects/crest/packages/centiq:crest$ 
```

**Comment by glasser** [comment] 2015-02-10 23:56
Duplicate of #3680

**Closed by glasser** 2015-02-10 23:56 UTC

**Comment by robertpitt** [comment] 2015-02-11 09:58
@glasser - I am not running as root.

My `$HOME` directory is /home/rpitt

Regards.

**Comment by NathanH81** [comment] 2015-02-18 04:12
In my package.js file, I set my Package.describe to documentation:null and that worked for me.

**Comment by samhatoum** [comment] 2015-02-25 01:07
Also getting `no pluginProviderPackageMap on isopack`

@NathanH81 's workaround worked for me.

**Comment by glasser** [comment] 2015-03-03 21:38
Sorry, I mean to say duplicate of #3676

**Comment by glasser** [comment] 2015-03-04 15:24
Can you confirm for me that your app has at least one Cordova platform? (Ie `.meteor/platforms` contains something other than server and browser?)

**Comment by samhatoum** [comment] 2015-03-09 04:27
I didn't have an app, I was publishing a package app-less-ly

**Comment by strikeout** [comment] 2015-03-15 21:56
Package.describe `documentation: null` worked for me as well.
