### ISSUE TITLE
account username should not be case sensetive

### ISSUE THREAD

**Issue by babnik63** [meteor/meteor#3472] opened 2015-01-13 20:33 UTC
I'm using accounts and account ui packages, I think the login page is sensitive with username character case.
password must be case sensitive as is, but username must be case insensitive.

**Comment by d4nyll** [comment] 2015-01-14 04:10
Duplicate of #550, #870

**Comment by avital** [comment] 2015-01-14 04:25
Closed as duplicate.

**Closed by avital** 2015-01-14 04:25 UTC
