### ISSUE TITLE
[1.3] possible EventEmitter memory leak

### ISSUE THREAD

**Issue by tjmonsi** [meteor/meteor#6247] opened 2016-02-16 11:57 UTC
**_18 Upvotes**_ I am getting this weird warnings, which increases my memory and CPU consumption...

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1175:8)
    at Object.files.watchFile (/tools/fs/files.js:1486:10)
    at Object.watch (/tools/fs/safe-pathwatcher.js:85:9)
    at Watcher._watchFileOrDirectory (/tools/fs/watch.js:469:35)
    at /tools/fs/watch.js:547:18
    at Array.forEach (native)
    at Function._.each._.forEach (/home/ubuntu/.meteor/packages/meteor-tool/.1.1.13-modules.8.8bjtd++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at onWatchEvent (/tools/fs/watch.js:536:11)
    at thenCallback (/tools/utils/func-utils.js:37:18)
    at /home/ubuntu/.meteor/packages/less/.2.5.2-modules.8.126pjac++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/promise/node_modules/meteor-promise/fiber_pool.js:33:40
```

It usually happens when I am doing something in my code, it does a Meteor server restart and sometimes a hot code reload (if i am working on client code). 

I couldn't replicate it 100% all the time (like what do I need to do if I am going to do this), but usually it is happening when I am coding and saving several files (I usually open a lot of tabs in sublime/cloud9) while the restart and rebuilding is still happening.

**Comment by ljack** [comment] 2016-02-16 20:44
#6251 also coding in cloud9 environment

**Comment by tjmonsi** [comment] 2016-02-17 11:47
Just in case, I'll be reporting again.

This time it happened after a lot of code saves and reloads... It happened only once though, now on a 2.5 GB RAM

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1175:8)
    at Object.files.watchFile (/tools/fs/files.js:1486:10)
    at Object.watch (/tools/fs/safe-pathwatcher.js:85:9)
    at Watcher._watchFileOrDirectory (/tools/fs/watch.js:469:35)
    at /tools/fs/watch.js:665:14
    at Array.forEach (native)
    at Function._.each._.forEach (/home/ubuntu/.meteor/packages/meteor-tool/.1.1.13-modules.8.8bjtd++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/tools/fs/watch.js:659:7)
    at new Watcher (/tools/fs/watch.js:356:10)
    at setupClientWatcher (/tools/runners/run-app.js:797:23)
    at AppRunner._runOnce (/tools/runners/run-app.js:808:7)
    at AppRunner._fiber (/tools/runners/run-app.js:881:28)
    at /tools/runners/run-app.js:406:12

```

**Comment by ljack** [comment] 2016-02-18 08:51
Maybe related or maybe not, but sometimes you don't get the warning (possible EventEmitter..) but reload just doesn't pick up some changes. Then touching some random (trying to find in more detail which files trigger and which not) file/directory will trigger reload.

**Comment by ashersz** [comment] 2016-03-13 15:39
I am getting this error while trying to build my app in a docker image (meteor 1.3-beta.16) 
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:160:15)
    at Request.self._buildRequest (/opt/nodejs/lib/node_modules/npm/node_modules/request/request.js:490:10)
    at Request.init (/opt/nodejs/lib/node_modules/npm/node_modules/request/request.js:637:10)
    at Request.onResponse (/opt/nodejs/lib/node_modules/npm/node_modules/request/request.js:1038:10)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1691:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socketOnData [as ondata] (http.js:1586:20)
    at TCP.onread (net.js:528:27)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:160:15)
    at Request.start (/opt/nodejs/lib/node_modules/npm/node_modules/request/request.js:829:8)
    at Request.end (/opt/nodejs/lib/node_modules/npm/node_modules/request/request.js:1471:28)
    at end (/opt/nodejs/lib/node_modules/npm/node_modules/request/request.js:538:16)
    at /opt/nodejs/lib/node_modules/npm/node_modules/request/request.js:552:9
    at process._tickCallback (node.js:448:13)

**Comment by pagoad** [comment] 2016-04-22 12:55
+1

**Comment by enricofoschi** [comment] 2016-04-25 15:51
This is an open issue for me as well now

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1175:8)
    at Object.files.watchFile (/tools/fs/files.js:1486:10)
    at Object.watch (/tools/fs/safe-pathwatcher.js:85:9)
    at Watcher._watchFileOrDirectory (/tools/fs/watch.js:469:35)
    at /tools/fs/watch.js:665:14
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/enricofoschi/.meteor/packages/meteor-tool/.1.3.2_4.rb0p0a++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/tools/fs/watch.js:659:7)
    at new Watcher (/tools/fs/watch.js:356:10)
    at setupClientWatcher (/tools/runners/run-app.js:803:23)
    at AppRunner._runOnce (/tools/runners/run-app.js:814:7)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

**Comment by timbrandin** [comment] 2016-04-27 14:31
Same here:
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1175:8)
    at Object.files.watchFile (/tools/fs/files.js:1486:10)
    at Object.watch (/tools/fs/safe-pathwatcher.js:85:9)
    at Watcher._watchFileOrDirectory (/tools/fs/watch.js:469:35)
    at /tools/fs/watch.js:547:18
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/tim.brandin/.meteor/packages/meteor-tool/.1.3.2_4.1xba57a++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at onWatchEvent (/tools/fs/watch.js:536:11)
    at thenCallback (/tools/utils/func-utils.js:37:18)
    at /Users/tim.brandin/.meteor/packages/templating/.1.1.9.1uzfjsx++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:33:40
```

**Comment by Alfiepoleon** [comment] 2016-04-28 16:26
+1
`Client modified -- refreshing (x12)(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1175:8)
    at Object.files.watchFile (/tools/fs/files.js:1486:10)
    at Object.watch (/tools/fs/safe-pathwatcher.js:85:9)
    at Watcher._watchFileOrDirectory (/tools/fs/watch.js:469:35)
    at /tools/fs/watch.js:547:18
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/alfred/.meteor/packages/meteor-tool/.1.3.2_4.1r8m8g1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at onWatchEvent (/tools/fs/watch.js:536:11)
    at thenCallback (/tools/utils/func-utils.js:37:18)
    at /Users/alfred/.meteor/packages/fourseven_scss/.3.3.3_3.3vjk5n++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/promise/promise/node_modules/meteor-promise/fiber_pool.js:33:40`

**Comment by ChenLi0830** [comment] 2016-04-30 12:00
+1

**Comment by JesusPerez** [comment] 2016-05-02 23:50
+1

**Comment by zeroasterisk** [comment] 2016-05-05 01:34
Same here:

```
=> Meteor server restarted
=> Meteor server restarted
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1175:8)
    at Object.files.watchFile (/tools/fs/files.js:1486:10)
    at Object.watch (/tools/fs/safe-pathwatcher.js:85:9)
    at Watcher._watchFileOrDirectory (/tools/fs/watch.js:469:35)
    at /tools/fs/watch.js:665:14
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/alan/.meteor/packages/meteor-tool/.1.3.2_4.1et1nm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/tools/fs/watch.js:659:7)
    at new Watcher (/tools/fs/watch.js:356:10)
    at setupClientWatcher (/tools/runners/run-app.js:803:23)
    at AppRunner._runOnce (/tools/runners/run-app.js:814:7)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12

$ uname -a && node -v && npm -v && meteor --version
Darwin alan-MBP-151.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
v4.4.0
2.14.20
Meteor 1.3.2.4
```

**Comment by dgolds** [comment] 2016-05-06 03:44
Same problem for me, stack just like zeroasterisk.
stack:
```

I20160505-20:40:13.817(-7)? Running on server only (main_server.js)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1175:8)
    at Object.files.watchFile (/tools/fs/files.js:1486:10)
    at Object.watch (/tools/fs/safe-pathwatcher.js:85:9)
    at Watcher._watchFileOrDirectory (/tools/fs/watch.js:469:35)
    at /tools/fs/watch.js:547:18
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/dgolds/.meteor/packages/meteor-tool/.1.3.2_4.1ack9ji++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at onWatchEvent (/tools/fs/watch.js:536:11)
    at thenCallback (/tools/utils/func-utils.js:37:18)
    at /Users/dgolds/.meteor/packages/coffeescript/.1.0.17.ofd4v5++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:33:40
```

system:
```
20:42:18 ~$  uname -a && node -v && npm -v && meteor --version
Darwin DavidMac5K.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
v5.7.0
3.8.6
Meteor 1.3.2.4
```

**Comment by JesusPerez** [comment] 2016-05-06 05:11
This start starts be really a bit problem, it breaks development ... 
Is there a save position like downgrading upgrading or whatever ? At least to have something stable.
I do not want to open old wounds but node version meteor uses does not help at all.
Any solution or approach to move forward will be  really appreciate ?

**Comment by zeroasterisk** [comment] 2016-05-06 17:13
@JesusPerez they are working on node version updates in `1.3.3` -- I played with it for a while, you might try it out if you want to be on a dev branch, to at least get more info out of better node (potentially with new or different issues).

**Comment by JesusPerez** [comment] 2016-05-07 11:43
@zeroasterisk thanks I just tried to run Meteor from a git checkout and results looks the same. And it seems related  when code changes are made and meteor has to re-build, re-load, etc.  I use webpack but I do not thing it will be the source problem.
At first I thought it was something in my code but if you use 1.3.2.4 sooner or later you will get same issue. I even have no clear idea to approach this issue for tracing and tracking.

**Comment by in0ni** [comment] 2016-05-10 18:27
Same here, trace is same as those posted (running 1.3.2.4 on linux).

On each restart/refresh, due to code changes, the **browser tab** used for the app increases it's memory usage. I usually start with about 15MB, after some time the browser tab can increase beyond 500MB before throwing this same error. Again this memory usage increase is at the TAB level. Memory usage by meteor seems to be unaffected.

My solution has been to stop meteor & close my browser once memory usage gets too high, before swap starts being affected. Closing the tab doesn't clear the memory for a while... a little annoying but allows for continued development.

**Comment by merlinpatt** [comment] 2016-05-10 23:16
I'm also getting this issue with 1.3.2.4 on Ubuntu 14.04

**Comment by Hamatek** [comment] 2016-05-11 16:14
same here +1

**Comment by ramansycheuski** [comment] 2016-05-11 16:17
+1

**Comment by abernix** [comment] 2016-05-11 16:32
Can anyone make a basic sample reproduction of this problem in a new Meteor project (as small and simple example as possible)?

**Comment by adoultremont** [comment] 2016-05-11 20:55
+1

**Comment by wojtkowiak** [comment] 2016-05-11 21:13
+1
Hard to reproduce, just got it after few changes and server restarts. Will try to make something reproducible.

**Comment by deathgaze** [comment] 2016-05-13 19:29
+1

**Comment by rickmed** [comment] 2016-05-14 15:29
+1

**Comment by valentinvichnal** [comment] 2016-05-16 23:20
+1

**Comment by zenonn37** [comment] 2016-05-16 23:56
+1

**Comment by sanoyphilippe** [comment] 2016-05-18 05:52
+1

**Comment by tastemeru** [comment] 2016-05-20 20:30
+1

**Comment by fredericMagnenat** [comment] 2016-05-20 21:15
+1

**Comment by finfort** [comment] 2016-05-21 18:50
+1

**Comment by batjko** [comment] 2016-05-30 15:06
I'm getting the same error when using the [meteor-react-boilerplate](https://github.com/adambrodzinski/meteor-react-boilerplate), which uses the Meteor v1.3 recommended folder structure, usually when changing client-side code files (about 30-50% of the time). 

Other than that, I haven't seen any particular pattern yet. However, from the comments above as well, it does seem to be a memory leak on the client only (i.e. browser tab).

The stack looks like the issue raised by meteor's file watcher
I am using Windows 10, and Meteor 1.3.2.4.

**Comment by AccountsAtMavenXInc** [comment] 2016-06-02 14:55
+1

**Comment by niwsa** [comment] 2016-06-04 20:17
[http://www.jongleberry.com/understanding-possible-eventemitter-leaks.html](url)
As per the above link if we set the maxListeners to infinity or zero which makes the number of listeners unlimited it may potentially cause memory leaks.I just tried to grep the same in the meteor directory.Interestingly quite a few modules happened to set the listeners count.
`~/.meteor/packages/meteor-tool/1.3.2_4/mt-os.linux.x86_64/tools$ grep -iR  "setMaxListeners(0)\|setMaxListeners(Infinity)" *
node_modules/pathwatcher/lib/main.js:      this.setMaxListeners(Infinity);
node_modules/request/request.js:    response.connection.setMaxListeners(0)
node_modules/events/tests/check-listener-leaks.js:e.setMaxListeners(0);
node_modules/events/tests/add-listeners.js:f.setMaxListeners(0);
node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/request/request.js:    response.connection.setMaxListeners(0)
node_modules/phantomjs/node_modules/request/request.js:    response.connection.setMaxListeners(0)
node_modules/npm/node_modules/request/request.js:    response.connection.setMaxListeners(0)
`

Is this any help to solving this issue?

**Comment by reohjs** [comment] 2016-06-06 22:08
FWIW, I haven't seen this error since upgrading to 1.3.3-beta.2

**Comment by grundmanise** [comment] 2016-06-09 19:06
Same issue here: 

`(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1175:8)
    at Object.files.watchFile (/tools/fs/files.js:1486:10)
    at Object.watch (/tools/fs/safe-pathwatcher.js:85:9)
    at Watcher._watchFileOrDirectory (/tools/fs/watch.js:469:35)
    at /tools/fs/watch.js:547:18
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/admin/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at onWatchEvent (/tools/fs/watch.js:536:11)
    at thenCallback (/tools/utils/func-utils.js:37:18)
    at /Users/admin/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:33:40`

Meteor + Cordova-ios. Yosemite. After several changes in the `isClient` code and `Meteor server restarted`. Re-building the project solves this issue _for some time_.

**Comment by s-devaney** [comment] 2016-06-12 18:37
+1 pops up after a number (25+?) of "hot code pushes"/project rebuilds.

**Comment by dburles** [comment] 2016-06-15 01:57
+1 Just saw this on 1.3.2.4

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1175:8)
    at Object.files.watchFile (/tools/fs/files.js:1486:10)
    at Object.watch (/tools/fs/safe-pathwatcher.js:85:9)
    at Watcher._watchFileOrDirectory (/tools/fs/watch.js:469:35)
    at /tools/fs/watch.js:547:18
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/dave/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at onWatchEvent (/tools/fs/watch.js:536:11)
    at thenCallback (/tools/utils/func-utils.js:37:18)
    at /Users/dave/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:33:40
```

**Comment by batjko** [comment] 2016-06-15 14:02
Guys, if you're just here to +1, could you use the reaction feature instead of adding noise:
![image](https://cloud.githubusercontent.com/assets/7287076/16082641/1082c276-330a-11e6-8240-5b320140fecb.png)

Every time there's an update notification I come back here hoping there's news on the issue, and get disappointed.

**Comment by valentinvichnal** [comment] 2016-06-15 15:08
It looks 1.3.3 solved this issue.

**Comment by valentinvichnal** [comment] 2016-06-15 15:09
1.3.3 solved this issue so you can close this.

**Comment by Maziar-Fotouhi** [comment] 2016-08-23 18:11
It's not solved. I recently upgraded to Meteor 1.4.1 and as soon as I upgraded, I started getting this error:

```
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
  at TLSSocket.addListener (events.js:239:17)
  at TLSSocket.Readable.on (_stream_readable.js:680:33)
  at Request.<anonymous> (/Users/fotouhm/.meteor/packages/meteor-tool/.1.4.1.1fcsf98++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:169:7)
  at ClientRequest.<anonymous> (/Users/fotouhm/.meteor/packages/meteor-tool/.1.4.1.1fcsf98++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:791:10)
  at emitOne (events.js:82:20)
  at ClientRequest.emit (events.js:169:7)
  at tickOnSocket (_http_client.js:523:7)
  at onSocketNT (_http_client.js:535:5)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)

```

**Comment by in0ni** [comment] 2016-08-23 18:20
I also upgraded to 1.4.1 yesterday, have yet to receive the error -- but just restarted my OS due to high memory usage again... I've started up and in less than 5 minutes memory has filled up, and moving to swap... this was fine for me after 1.3.3

meteor-tool (../mt-os.linux.x86_64/tools/index.js) is using up most of the memory on the system.

**Comment by fhperuchi** [comment] 2016-08-24 17:43
+1

**Comment by ignl** [comment] 2016-08-24 19:43
+1

**Comment by ianpogi5** [comment] 2016-08-26 02:17
I get the same error when installing cordova-plugin-geolocation other than v2.1.0. I'm on meteor 1.4.1.1 and this is the first time I'm adding this plugin.

**Comment by Maziar-Fotouhi** [comment] 2016-08-26 13:55
I don't think it is specifically related to the _geolocation plugin_ since I'm not using it but still getting the error.

Here is a list of my cordova plugins:

```
cordova-plugin-3dtouch@1.3.5
cordova-plugin-android-fingerprint-auth@0.0.5
cordova-plugin-appavailability@0.4.2
cordova-plugin-camera@2.1.1
cordova-plugin-device@1.1.1
cordova-plugin-globalization@1.0.3
cordova-plugin-inappbrowser@1.3.0
cordova-plugin-network-information@1.2.0
cordova-plugin-passbook@0.2.1
cordova-plugin-statusbar@2.1.2
cordova-plugin-touch-id@3.1.0
cordova-plugin-whitelist@1.2.1
```


And again, it only happens to me when I am running` meteor run ios-device`. I have not yet tried it with `android-device` though.

**Comment by stief510** [comment] 2016-08-26 16:40
+1

**Comment by ahoasoul** [comment] 2016-08-29 10:06
+1
same with Maziar-Fotouhi

**Comment by abhaytalreja** [comment] 2016-09-12 18:42
You can fix it using the below...
```
require('events').EventEmitter.defaultMaxListeners = Infinity;  
```

**Comment by merlinpatt** [comment] 2016-09-12 19:32
@abhaytalreja That seems like it would have some negative consequences. Have you tested that fix thoroughly?

**Comment by abernix** [comment] 2016-09-14 16:05
@abhaytalreja That will get rid of the error message but isn't a fix for the problem itself.  There could still be listeners which aren't getting removed, but there just wouldn't be an error about it.  I don't know the true issue here, but in development and with appropriate system resources, that might be a suitable change if the the message is simply an annoyance – but that's about it.  I wouldn't recommend that as a true solution to this problem.

**Comment by rub1e** [comment] 2016-09-19 06:51
I'm getting this error as well on Meteor 1.4.1.1 - I've never had this error while developing locally, but I get it every time I deploy to Scalingo:

```
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
       Trace
           at TLSSocket.addListener (events.js:239:17)
           at TLSSocket.Readable.on (_stream_readable.js:680:33)
           at Request. (/build/74894309484d86db97f77e53a207cb02/.scalingo/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
           at emitOne (events.js:77:13)
           at Request.emit (events.js:169:7)
           at ClientRequest. (/build/74894309484d86db97f77e53a207cb02/.scalingo/node/lib/node_modules/npm/node_modules/request/request.js:791:10)
           at emitOne (events.js:82:20)
           at ClientRequest.emit (events.js:169:7)
           at tickOnSocket (_http_client.js:502:7)
           at onSocketNT (_http_client.js:514:5)
```

**Comment by v3rron** [comment] 2016-09-24 17:26
Just had the same issue as @rub1e while running `meteor build` on Meteor 1.4.1.1.
The only change I made recently is upgraded to `raix:push@3.0.3-rc.7` package which uses `phonegap-plugin-push`.

**Comment by timbrandin** [comment] 2016-09-28 09:24
I don't get this issue anymore, I guess it has solved itself at least for me.

**Comment by Maziar-Fotouhi** [comment] 2016-09-28 14:28
@timbrandin Have you by any chance updated your meteor to 1.4.2? If so, the problem may have been solved by the npm/fibers/node-pre-gyp upgrades in 1.4.2.
I have not updated to meteor 1.4.2 yet, though. Can someone else please confirm this?

**Comment by adamgins** [comment] 2016-10-02 22:27
@v3rron wondering if you resolved this?

**Comment by adamgins** [comment] 2016-10-03 10:11
Since upgrading to Meteor 1.4.1.1 I am getting the plugin ` TLSSocket.addListener ` issue and after a while my dev machine (Macbook with 16GB ram) runs out of memory and crashes.

```
cordova-custom-config: Skipping auto-restore of config file backup(s)
cordova-custom-config: Skipping auto-restore of config file backup(s)
%% "cordova-plugin-compat" is required by (cordova-plugin-file) and cannot be removed (hint: use -f or --force) and cannot be removed (hint: use -f or --force)
cordova-custom-config: Skipping auto-restore of config file backup(s)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
  at TLSSocket.addListener (events.js:239:17)
  at TLSSocket.Readable.on (_stream_readable.js:680:33)
  at Request.<anonymous> (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.1_1.1fir5ef++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:169:7)
  at ClientRequest.<anonymous> (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.1_1.1fir5ef++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:791:10)
  at emitOne (events.js:82:20)
  at ClientRequest.emit (events.js:169:7)
  at tickOnSocket (_http_client.js:523:7)
  at onSocketNT (_http_client.js:535:5)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)

cordova-custom-config: Installing plugin dependencies...==========      ] 75% 14.9s
cordova-custom-config: Installing plugin dependencies...==========      ] 75% 15.3s
cordova-custom-config: Installing plugin dependencies...==========      ] 75% 15.7s
cordova-custom-config: Skipping auto-restore of config file backup(s)===] 100% 0.0s
cordova-custom-config: Applied custom config from config.xml to /Users/adamginsburg/Documents/Development/buzzy7/.meteor/local/cordova-build/platforms/ios/Buzzy/Buzzy-Info.plist

```

**Comment by abernix** [comment] 2016-10-25 11:44
I believe this issue was resolved when NPM was updated (and in turn, the offending `npm-registry-client` package.  See npm/npm-registry-client#142 and npm/npm#13656 for more details.

Can anyone confirm that they are still experiencing this issue on Meteor 1.4.1.3 or Meteor 1.4.2?  Both include the newer NPM with the fix to `npm-registry-client`/`request`.

**Comment by abernix** [comment] 2016-11-15 12:02
Thanks for reporting this originally.  Closing as I believe this problem is resolved thanks to upstream fixes, as I previously mentioned.  If you're experiencing this problem, please update to a newer version of Meteor (>= 1.4.1.3).

**Closed by abernix** 2016-11-15 12:02 UTC
Labels: bug, can't-reproduce, Impact:some, Project:Isobuild

**Comment by NitroBAY** [comment] 2018-06-17 17:51
I have the same problem under METEOR@1.6.1 only on the server (I have meteor up with the docker image abernix/meteord:node-8.9.4-binbuild)

**Comment by NitroBAY** [comment] 2018-06-17 17:54
Does it explain why my Meteor.call sometimes return nothing. The official launch is today so help would be very much appreciated @abernix
