### ISSUE TITLE
Accounts is expecting to be exported globally.

### ISSUE THREAD

**Issue by robertpitt** [meteor/meteor#4638] opened 2015-06-27 23:34 UTC
I am building a package only system which uses accounts, I have a package that `api.imply`'s `accounts-base` and `accounts-google`.

I then have a application package that uses the above wrapper package.

But I get thee following error because the Accounts variable is not globally available

```js
Uncaught ReferenceError: Accounts is not defined
Google.requestCredential @ google_client.js:55
Meteor.loginWithGoogle @ google.js:12
Template.HeaderSection.events.click a[login] @ header.js:16
(anonymous function) @ template.js:463
Template._withTemplateInstanceFunc @ template.js:437
(anonymous function) @ template.js:462
(anonymous function) @ view.js:869
Blaze._withCurrentView @ view.js:523
(anonymous function) @ view.js:868
(anonymous function) @ events.js:47
jQuery.event.dispatch @ jquery.js:4665
jQuery.event.add.elemData.handle @ jquery.js:4333
```

Which leads to the following line:

```js
  if (typeof Accounts._options.restrictCreationByEmailDomain === 'string') {
    loginUrl += '&hd=' + encodeURIComponent(Accounts._options.restrictCreationByEmailDomain);
  }
```

A solution would be to set `Accounts` to `Package['accounts-base'].Accounts`

**Comment by robertpitt** [comment] 2015-06-28 17:08
In fact, the solution suggested above is quite silly, It would make more sense for the `google` pacakge to `apu.use("accounts-base", "client")`.

**Comment by zhenyasav** [comment] 2015-06-30 21:39
Thanks @robertpitt, it looks like you might have encountered the correct intended behavior when it comes to implying packages, but without a reproduction repo it is hard to be certain. If you could provide a crisp reproduction repo, it would help us get to the root cause if there is indeed a bug. At our current scale, it is too much work to triage issues that do not come with a simple reproduction. Thanks for your help!

**Comment by stubailo** [comment] 2015-06-30 21:39
I guess the intention here is that the `google` package could be used _without_ `accounts-google` or even `accounts-base`, since just having the `accounts-base` package results in side effects like creating a `Meteor.users` collection (among other things).

There is definitely some kind of bug here, and we should fix it either by accepting that `google` should depend on `accounts-base`, or by writing the appropriate `if` statement to get `Accounts`.

**Comment by stubailo** [comment] 2015-06-30 21:41
A reproduction would help check if the issue is resolved, though.

**Comment by robertpitt** [comment] 2015-07-01 00:40
Here's a reproduction guys.

1. git clone https://github.com/robertpitt/meteor-accounts-bug-4638.git
2. run meteor
3. open :3000
4. Click configure (add some credentials that work with localhost:3000/_oauth....)
5. Click login
6. Open chrome's console to see error.

Result: Uncaught ReferenceError: Accounts is not defined
Expected: Authentication popup to appear.

**Comment by robertpitt** [comment] 2015-07-07 22:36
If the label `PR Encouraged` get's added I will do it.

**Comment by robertpitt** [comment] 2015-07-07 22:55
PR pushed.

**Comment by nathan-muir** [comment] 2015-07-08 06:05
Duplicate of #3903 - with accompanying PR (#3910) that _removes_ the need to add `accounts-base` to `google`.

**Comment by stubailo** [comment] 2015-10-13 17:35
I think this was fixed by the above PR.

**Closed by stubailo** 2015-10-13 17:35 UTC
Labels: needs-repro, Project:Accounts (in user apps), pull-requests-encouraged

**Comment by robertpitt** [comment] 2015-10-15 14:56
Yea @stubailo, I did test this.
