### ISSUE TITLE
Subscription callback

### ISSUE THREAD

**Issue by erperejildo** [meteor/meteor#8557] opened 2017-04-03 08:16 UTC
Originally I published this issue on angular-meteor repository thinking that it was a problem related with that package but it looks like a general issue in Meteor.

My issue is when I subscribe and I get some data. Sometimes (not always) I get wrong data and only works well when I do `setTimeout` after subscribe.

I can check this doing 2 consoles: one one my publish method on client and another one after fill my cursor on my subscribe function callback. This data should be the same but not always as I commented.

More info about this issue: https://github.com/Urigo/angular-meteor/issues/1584

**Comment by hwillson** [comment] 2017-04-03 09:56
Hi @erperejildo - would you be able to put together a small, runnable reproduction demonstrating your issue? A reproduction will greatly help with troubleshooting (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Comment by erperejildo** [comment] 2017-04-03 12:23
On the link I have pasted is the whole script. It's a bit tricky to reproduce on other place, even the issue itself only happens a few times only.

This is a simple resume:
```
var promise = new Promise(function(resolve) {
            that.foodSubscription = that.subscribe('food', () => [{}, 
                that.searchString
            ], {
                onReady: ()=> {
                    resolve(true);
                },
                onStop: (err)=> {
                    // TODO: show error
                    resolve(true);
                }
            });
            return that.foodSubscription;
        });

        // wait after food cursor is done to get the owners
        promise.then(function() {
            if (that.foodSubscription.ready()){
                return that.foodSubscription;
            }
        });
```

That's a subscription with one parameter which is searching by title. I'm using a promise cause the normal subscription wasn't working well (same issue explained) and I tried to call this inside a promise in order to be sure I get the cursor well, but anyway I get the same issue.
This gets called by default and also when I type on search input.

And this is my helper with my cursor:
```
autorun() {
                Tracker.autorun(() => {
                    let owners = {};
                    let i = 0;
                    if (that.getReactively('foodSubscription') && that.foodSubscription.ready()){
                        // CASE 1
                        console.log(Food.find({}, {reactive: false}).fetch());
                        // CASE 2
                        setTimeout(function(){
                            console.log('Con timeout: '+Food.find({}, {reactive: false}).fetch());
                        },500);
                    }
```
**Case 1**
Sometimes as I said I get wrong data when I change the value of my search input. I can check this because I'm checking at the same time the `publish` function on my server and the data published is different from what I get on the client side

**Case 2**
This **always** works.

So I understand either the callback is not triggering well or I'm doing something wrong

**Comment by hwillson** [comment] 2017-04-09 15:26
Hi @erperejildo - I understand that it can be a bit tricky to put together a reproduction demonstrating an issue like this, but any kind of runnable reproduction you can provide will help with troubleshooting. It's difficult to extrapolate the big picture of what you're trying to do, from the code snippets you've provided. I do know that many people are using Angular with Meteor, and have found ways to transform subscription callbacks into Promises successfully. Since this doesn't appear to be an issue with Meteor itself, I'll close this issue for now. You might want to try reaching out on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) for assistance (since GitHub issues are reserved for bugs / feature requests).

If you still think this is a Meteor bug and can demonstrate the issue in some way, then we'll be happy to re-open. Thanks!

**Closed by hwillson** 2017-04-09 15:26 UTC

**Comment by erperejildo** [comment] 2017-04-09 16:05
I have created same post on both of them. Would be ok if I try to record a video explaining the issue?

**Comment by hwillson** [comment] 2017-04-10 12:05
By all means @erperejildo, please feel free to post a link to a video demonstrating this issue. A reproduction of some kind would still be preferred, but videos can help. I recommend posting this video on the forums as well though, since you'll likely have a better chance of someone using Angular with Meteor responding more promptly there. Issue reviewers here are primarily focused on bugs with the platform itself; helping with implementation issues usually takes a second seat.

**Comment by erperejildo** [comment] 2017-08-16 12:55
https://recipic.co/food (you'll need to loggin)

Find a recipe typing "Burg" and "Burgw". You will having one recipe (which is not correct). If you type another "w" ("Burgww") it will disappear and if you remove the las "w" again you won't have anything yet until you have "Burg".

What I found is that the callback is triggering to fast comparing with the `autorun` tracker which works as expected but I can't place my function there to get the post because it gets called many times then.

Any ideas?
