### ISSUE TITLE
White space in path gives error when running "meteor run android-device"

### ISSUE THREAD

**Issue by FancyGamer123** [meteor/meteor#7961] opened 2016-10-25 23:42 UTC
Meteor version: **METEOR@1.3.5.1**
Running Meteor on **Windows 7** Enterprise

Packages in use:
- autopublish  
- blaze-html-templates  
- ecmascript  
- es5-shim  
- insecure  
- jquery  
- launch-screen  
- meteor-base  
- mobile-experience  
- mongo  
- reactive-var  
- standard-minifier-css 
- standard-minifier-js  
- tracker  

The app runs **perfectly** with `meteor run`. No errors.

The problem is when running `meteor run android-device` it gives me this error:

```
C:\XXXXX\AppData\Local\.meteor\packages\meteor-tool\1.3.5_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
Error: Command failed: C:\XXXXX\Documents\Projects\Apps\cool app\.meteor\local\cordova-build\platforms\android\cordova\version
C:\XXXXX\Documents\Projects\Apps\cool not recognized as an internal or external command,
executable or batch file.
    at ChildProcess.exitCallback (C:\tools\utils\processes.js:151:23)
    at ChildProcess.emit (events.js:117:20)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

> "cool app" = the name of the directory (pay attention to the white space)
> The white space in the name of the directory is giving me error. When I remove the white space, `meteor run android-device` will then work, the app will run on the device.

Note: This problem does exist even my phone is not connected to my PC. The error happens before the program recognizes the phone.

So there is a bug ´meteor run android-device´. It doesn't turn the path into a string, while ´meteor run´ does.

**Comment by abernix** [comment] 2016-12-20 10:52
I can confirm that this is still a problem on Meteor 1.4.  The reason is that the command must be "quoted" when running with a space on it.

I'm sure this will be fixed by adding something along the lines of this [in this block](https://github.com/meteor/meteor/blob/8a81e7156e07ca9e1a6c2b2b89870eb4abe72a2d/tools/utils/processes.js#L82) of `execFileAsync` in `utils/processes.js`:

    command = `"${command}"`;

But I'm also curious if it doesn't need to be fixed at a higher level too, perhaps even in `convertToOSPath` – but I'm not sure what the implications of that would be on other Windows commands.

Anyhow, this needs a bit more investigation, but just leaving this as a note.  My fix above will fix this particular situation, but might not be the right solution.

The obvious work around is: Don't use spaces in your app name.

**Comment by hwillson** [comment] 2018-02-14 12:50
There hasn't been any traction on this issue in quite some time. If anyone comes across this issue and is interested in working on it, please let us know (it is `pull-requests-encouraged`). Until then however, this issue will be closed (especially since the error received is fairly self explanatory and an acceptable workaround is to avoid using spaces in your application name). Thanks!

**Closed by hwillson** 2018-02-14 12:50 UTC
Labels: Impact:few, Project:Mobile, Project:Windows, Severity:has-workaround, bug, confirmed, pull-requests-encouraged
