### ISSUE TITLE
CSS stylesheet is missing a sourcemap for files coming from packages

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#3304] opened 2014-12-17 07:55 UTC
Before version 0.7, CSS files were sent separately by `meteor run`, which facilitated debugging. Now they're always concatenated, which makes things difficult when you have several large CSS files already (e.g. Bootstrap Material Design).

@Slava[?](https://github.com/meteor/meteor/issues/3285#issuecomment-67188126)

**Comment by glasser** [comment] 2015-01-14 00:00
Thanks for the specific reproduction. Looks like the issue is that three included source CSS files (one from twbs:bootstrap and two from the fezvrasta package) contain `sourceMappingURL` comments which make it through to the concatenated (but NOT minified!) output. This confuses the browser into not trusting the X-SourceMap header.

Probably we need to remove (or at least deactivate, eg we can just change one character so as not to mess up file length/source maps) such comments when concatenating CSS.

**Comment by hwillson** [comment] 2016-10-30 15:21
I've tested the supplied reproduction with Meteor 1.4.2 and the (mostly) latest version of each major browser. The results are:

**Working:**

- Chrome 54.0.2840, package based sourcemaps are working
- Safari 9.1.1, package based sourcemaps are working

Here's a quick screenshot showing sourcemaps working from Chrome (Safari behavior is the same) - when inspecting an element the proper package source css is linked to instead of the `merged-stylesheets.css`:

![screenshot 2016-10-29 15 24 18](https://cloud.githubusercontent.com/assets/137740/19837530/0c9ce774-9e92-11e6-988c-e328563b2ad0.png)

**Not Working:**

- FireFox 49.0.2, package based sourcemaps are not working
- IE 11.0.9600, package based sourcemaps are not working
- MS Edge 38.14393, package based sourcemaps are not working

Here's a quick screenshot showing sourcemaps not working from FireFox (the behavior in the other browsers is the same) - when inspecting an element all styles are linked back to the `merged-stylesheets.css`, with no way to see where the original styles are coming from:

![screenshot 2016-10-29 16 06 31](https://cloud.githubusercontent.com/assets/137740/19837536/2110afd8-9e92-11e6-9333-9578779d33b8.png)

Looks like this is still an issue. Actually this issue is associated to issue meteor/meteor#7140 as well. The solution to both of these issues will be the same, so I'll dig in a bit further.

**Comment by abernix** [comment] 2016-11-08 16:32
Thanks for pointing out the duplicate, @hwillson – there is some valuable information in there, but I've closed it in favor of this.

Frankly, I've always had problems with Firefox Source Maps and Meteor.  It's entirely possible that FireFox doesn't support the way that they are being linked (via the `X-Sourcemap` header), or something, but that's just speculation on my part.

**Comment by hwillson** [comment] 2017-11-02 19:41
Package based stylesheet sourcemaps are working in most modern browsers. Given that this issue is coming up on 3 years old, and that there has been very little interest in this issue, I think we're safe to close this one off. Happy to re-open if anyone feels otherwise. Thanks!

**Closed by hwillson** 2017-11-02 19:41 UTC
Labels: bug, confirmed, Project:Isobuild:Minifiers, Severity:has-workaround
