### ISSUE TITLE
exception thrown in ddp-client/livedata_connection.js when noRetry flag is set.

### ISSUE THREAD

**Issue by n17r4m** [meteor/meteor#8457] opened 2017-03-06 04:42 UTC
Issue is in 1.4.3.1 and remains in devel branch.

in packages/ddp-client/livedata_connection.js
at line 318: `currentMethodBlock.splice(i, 1);`

This removes a `methodInvoker` from `self._outstandingMethodBlocks[0]`.
Unfortunately, the `_each` loop is executing with a fixed number of loop iterations detected from initial entry, so an iteration will occur where `methodInvoker` is undefined. 

This causes an exception to be thrown, and prevents the rest of the `onReset` from running. This breaks reconnection when there are methods in queue with the noRetry flag set.

Suggested resolution: store an array of indicies to remove, and remove the `methodInvoker`s from `self._outstandingMethodBlocks[0]` after the _each loop is complete.

**Comment by hwillson** [comment] 2017-03-06 19:21
Hi @n17r4m - thanks for reporting this. Any chance you could provide a small reproduction demonstrating this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug))? A small, runnable repro would definitely help with troubleshooting. Thanks!

**Comment by n17r4m** [comment] 2017-03-12 22:02
Just checking in on this issue. I'm not sure I would be able to provide a runnable example, as the problem is only manifested through a specific timing of disconnecting network connectivity, followed by calling a meteor method with the noRetry flag set, followed by reconnecting to the network.

However, it is plainly visible through looking at the code in packages/ddp-client/livedata_connection.js that the way the elements are being removed from self._outstandingMethodBlocks[0] is incorrect.

As the code currently stands, there is a mistake equivalent to https://gist.github.com/chad3814/2924672 line 45-50. It is just not a correct way to remove an item from an array while iterating over it.

Because I forgot to mention it explicitly in my original comment, the actual exception being thrown is
"Cannot read property 'sentMessage' from undefined" on line 304: `if (methodInvoker.sentMessage && methodInvoker.noRetry) {` . 

Because an element is being removed unsafely from the array, the _.each will perform an additional loop iteration beyond the array bounds and methodInvoker will be undefined.

**Comment by hwillson** [comment] 2017-03-13 14:47
Thanks for the follow up @n17r4m - I see what you mean. Interestingly enough if an `Array.forEach` was being used instead of `_.each`, this wouldn't be an issue (in this case), since the callback would have been skipped for the `undefined` method. Marking this as confirmed. Any chance you're interested in submitting a PR to help address this? 🙂 Regardless, thanks for pointing this out!

**Comment by ahmedhagii** [comment] 2017-03-16 17:45
I'm interested in tackling this if possible.

**Comment by n17r4m** [comment] 2017-03-20 06:50
Thank you @ahmedhagii, your fix looks elegant.

**Comment by ahmedhagii** [comment] 2017-03-21 13:27
thanks @n17r4m, @hwillson did you get a chance to look at this?

**Comment by hwillson** [comment] 2017-03-21 14:14
I haven't had a chance yet @ahmedhagii, but I should be able to take a look today. If not this will be reviewed during the weekly issue/PR review meeting, that happens on Wednesday's. Hopefully I'll get to it today though. Thanks for submitting this PR!

**Closed** 2017-03-22 15:48 UTC
Labels: bug, confirmed, Project:DDP, pull-requests-encouraged, Severity:production
