### ISSUE TITLE
Meteor 1.3.2.2 broke source-map with webpack

### ISSUE THREAD

**Issue by primeminister** [meteor/meteor#6851] opened 2016-04-19 10:53 UTC
I updated my project to meteor 1.3.2.2 and npm install works fine.
After I do a `meteor run ios` I get the following error in my terminal:

```
=> Started proxy.
=> Started MongoDB.

 /Users/charlie/.meteor/packages/fourseven_scss/.3.4.3.13ha73++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
 TypeError: Cannot call method 'substr' of undefined
    at Function.<anonymous> (/Users/charlie/.meteor/packages/meteor-tool/.1.3.2_2.u4or85++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-node.js:115:29)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/charlie/.meteor/packages/meteor-tool/.1.3.2_2.u4or85++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-map-consumer.js:155:16)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/Users/charlie/.meteor/packages/meteor-tool/.1.3.2_2.u4or85++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-node.js:80:26)
    at File._.extend.getPrelinkedOutput (/tools/isobuild/linker.js:729:38)
    at walk (/tools/isobuild/linker.js:272:23)
    at /tools/isobuild/linker.js:281:11
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/charlie/.meteor/packages/meteor-tool/.1.3.2_2.u4or85++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/linker.js:279:11
    at walk (/tools/isobuild/linker.js:286:9)
    at /tools/isobuild/linker.js:281:11
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/charlie/.meteor/packages/meteor-tool/.1.3.2_2.u4or85++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/linker.js:279:11
    at walk (/tools/isobuild/linker.js:286:9)
    at /tools/isobuild/linker.js:281:11
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/charlie/.meteor/packages/meteor-tool/.1.3.2_2.u4or85++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/linker.js:279:11
    at walk (/tools/isobuild/linker.js:286:9)
    at Module._chunkifyModuleTree (/tools/isobuild/linker.js:295:5)
    at Module._.extend.getPrelinkedFiles (/tools/isobuild/linker.js:171:24)
    at Object.fullLink (/tools/isobuild/linker.js:1012:31)
    at /tools/isobuild/compiler-plugin.js:1154:28
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at PackageSourceBatch._linkJS (/tools/isobuild/compiler-plugin.js:1153:18)
    at PackageSourceBatch.getResources (/tools/isobuild/compiler-plugin.js:1045:28)
    at /tools/isobuild/bundler.js:934:37
    at Array.forEach (native)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:916:19)
    at /tools/isobuild/bundler.js:684:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:675:18)
    at /tools/isobuild/bundler.js:2474:14
    at /tools/isobuild/bundler.js:2563:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/charlie/.meteor/packages/meteor-tool/.1.3.2_2.u4or85++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2562:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12`
```
With meteor version 1.3 it did not happen and is still working.

**Comment by ephemer** [comment] 2016-04-19 13:52
Could this be the same issue as here: https://github.com/meteor/meteor/issues/6850?

**Comment by primeminister** [comment] 2016-04-19 13:59
I tried the proposed solution
> rm -rf .meteor/local/bundler-cache

But that was not working for me.

**Comment by pors** [comment] 2016-04-26 14:03
I have the same issue with Meteor 1.3.2.4

I deleted ~/.meteor, did meteor reset, deleted all node_modules, but still this error:

```
/Users/mark/.meteor/packages/fourseven_scss/.3.4.3.ifmf9n++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;

TypeError: Cannot call method 'substr' of undefined
```

**Comment by ne8il** [comment] 2016-04-27 02:37
Seeing this same issue after updating from 1.3.1 to 1.3.2.4.
As part of that update, `fourseven:scss` was upgraded from 3.4.1 to 3.4.3.
If I remove that package (`meteor remove fourseven:scss`), I can start the project fine (though obviously my styling is broken).

**Comment by JanMP** [comment] 2016-04-27 20:24
I got the same issue with the stylus package

**Comment by pors** [comment] 2016-05-01 17:06
Have a look at the comment of @MasterAM here: https://github.com/fourseven/meteor-scss/issues/177 and my reply on it.

That solved it for me.

**Comment by abernix** [comment] 2016-07-14 10:01
This appears to be a duplicate of problems experienced starting half-way through this issue https://github.com/meteor/meteor/issues/7206#issuecomment-230332826

Closing as a duplicate – please refer to that issue for similar problems and solutions, try to reproduce in a new issue and if you're still having problems, open a new issue including a reproduction Meteor project repo link.

See also: #7076

**Closed by abernix** 2016-07-14 10:01 UTC
