### ISSUE TITLE
Adding less files to the package

### ISSUE THREAD

**Issue by lukejagodzinski** [meteor/meteor#8834] opened 2017-06-22 14:39 UTC
The Meteor [guide](https://guide.meteor.com/writing-atmosphere-packages.html#adding-style) says that in order to add the `less` files to the package but without importing them automatically into the app's styles, we have to add them with the option `isImport: true`:

```js
Package.onUse(function(api) {
  /* ... */
  api.addFiles([
    'component.less'
  ], 'client', {isImport: true});

  api.mainModule('component.js', 'client');
});
```

Now, we have to import this file in some other file:

```js
// component.js
import './component.less';
/* ... */
export default class ReactComponent extends Component {
  render() { /* ... */ }
}
```

But I get the `Cannot find module './component.less'` error.

The [docs](https://atmospherejs.com/meteor/less) for the less package only mentions "less imports" (`@import '{package}file.less'`) and doesn't say anything about importing less files from the js file, which is possible in Meteor app's code but seems to be impossible to do in a package. Is it somehow possible?

**Comment by jagi** [comment] 2017-06-22 14:54
And reproduction repository: https://github.com/jagi/reproduction-meteor-package-less-import

**Comment by coagmano** [comment] 2017-07-13 03:06
This should work the same way as importing a js file from within a package (avoiding mainModule)
```
import 'meteor/foo:bar/component.less';
```
with the package name (not the folder name), and the path from the project base

**Comment by jagi** [comment] 2017-07-13 11:03
@coagmano no it does not work. I can only import less file in another less file. And you've used syntax with the package name which is only reserved for importing from the application level and I want to import this less file from the package level.

**Comment by jagi** [comment] 2017-07-13 11:14
I've also made a test with *.css file and it works. So when I have an import in the package:

```js
import './component.css';
```

and css file export with the `isImport` flag set:

```js
api.addFiles('component.css', 'client', {
    isImport: true
  });
```

then it works. The same trick is not possible with the less file. Of course, the less file gets compiled to css so maybe that's a problem here.

**Comment by coagmano** [comment] 2017-07-13 23:11
So you're importing the less file from inside same package? You shouldn't need to add it to your `package.js` then. 
Works fine for me with sass and stylus, though I haven't tried less.

Which less package are you using?

**Comment by jagi** [comment] 2017-07-14 10:54
Even when I remove `api.addFiles` calls it still does not work with less files, it works correctly with css files. Take a look at my reproduction here https://github.com/jagi/reproduction-meteor-package-less-import/blob/master/packages/component/components/Button.js#L3 I'm importing less file the way you said and the component is not styled. However, when I uncomment css file import (which is the same as less file) then it works. I haven't tried sass. I'm just using built in less package for Meteor.

**Comment by jagi** [comment] 2017-07-14 10:59
Yes, I can confirm that it works with sass so the problem is Meteor's less package that does not work properly with packages.

**Comment by hwillson** [comment] 2017-11-22 21:07
I've updated the supplied reproduction to Meteor 1.6 and tested - the button is styled properly using `import './Button.less';`, so it looks like this was resolved at some point. Closing - thanks!

**Closed by hwillson** 2017-11-22 21:07 UTC
Labels: Project:CSS, Project:Tool
