### ISSUE TITLE
Maximum call stack size exceeded on setup

### ISSUE THREAD

**Issue by EddyFreddy** [meteor/meteor#9158] opened 2017-09-30 08:41 UTC
C:\Users\(myuser)\)AppData\Local\.meteor\packages\meteor-tool\1.5.2_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\q\q.js:70
    hasStacks = !!e.stack;
                   ^

RangeError: Maximum call stack size exceeded

Responds with this error on commands: meteor, meteor --version, meteor list and meteor npm list 
Uninstalling and deleting local app data and reinstalling, I'm at a loss.

**Comment by hwillson** [comment] 2017-10-05 12:24
Duplicate of https://github.com/meteor/meteor/issues/7896.

**Closed by hwillson** 2017-10-05 12:24 UTC
