### ISSUE TITLE
1.3 "meteor build" slow when node_modules contains many devDependencies

### ISSUE THREAD

**Issue by enricofoschi** [meteor/meteor#6750] opened 2016-04-08 07:18 UTC
Hi all,

using the very basic build of Meteor 1.3 (1.3.1 as well), I created a simple app with "meteor create" and then just triggered a build with:

"meteor build ../test.tarball"

It was pretty quick up to "Building the application" ("Building for web", "linking", etc...).

But then it got stuck in "Building the application" for a good 6 mins (10 mins sometimes). I have the latest gen Macbook pro with 2.8ghz processor, and I run it after a clean restart.

Is this expected?

**Comment by enricofoschi** [comment] 2016-04-08 08:17
(Issue closed as after reinstalling meteor completely from scratch, it went away and now a build on a basic project is down to "only" 2 mins)

**Comment by mzugn** [comment] 2016-04-08 08:25
I think it should be re-opened, this is a huge issue with 1.3. Even the betas had reasonable build times, but the "stable" release, and 1.3.1 for that matter, is completely unusable at this point for me. Also, when I change server-side files in dev mode, it takes at least 2 minutes to refresh the application, and the build is literally stuck there with 100% CPU usage, not even able to Ctrl+C out of it.

I have no idea how to start debugging something like this, nor do I have the time for it. Build time issues have been around for a *long* time now, and in my opinion this is the No. 1. most important thing to fix. I fear that if the core Meteor packages become npm packages before this is fixed, the build is going to suffer even more.

**Comment by benjamn** [comment] 2016-04-08 15:39
Can you provide some more details about your app, such as the contents of `.meteor/packages` and `package.json`?

**Comment by enricofoschi** [comment] 2016-04-08 16:36
@mzugn you are right - it just came back right after (or I was lucky once).

Hi @benjamn - thank you for your time (btw  - *LOVE* your help and community guidance / contribution!)

Here is how you can reproduce it in a fairly easy way:

packages:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
session                 # Client-side reactive dictionary for your app
tracker                 # Meteor's client-side reactive programming library
ecmascript              # Enable ECMAScript2015+ syntax in app code

check
kadira:flow-router-ssr
kadira:dochead
accounts-password
alanning:roles
standard-minifier-css
standard-minifier-js
```

packages.json:

```
{
    "name": "experiment",
    "version": "0.0.2",
    "dependencies": {
        "formsy-material-ui": "0.3.8",
        "formsy-react": "0.17.0",
        "keycode": "2.1.1",
        "mantra-core": "1.4.0",
        "material-ui": "0.15.0-alpha.2",
        "path-to-regexp": "1.2.1",
        "react": "0.14.8",
        "react-dom": "0.14.8",
        "react-mounter": "1.1.0",
        "react-notification-system": "0.2.6",
        "react-tap-event-plugin": "0.2.2",
        "redis-node": "0.4.0"
    },
    "devDependencies": {
        "babel-cli": "6.6.5",
        "babel-core": "6.x.x",
        "babel-plugin-react-require": "2.x.x",
        "babel-polyfill": "6.7.4",
        "babel-preset-es2015": "6.x.x",
        "babel-preset-react": "6.x.x",
        "babel-preset-stage-2": "6.x.x",
        "babel-root-slash-import": "1.x.x",
        "chai": "3.x.x",
        "eslint": "2.7.0",
        "eslint-plugin-react": "4.2.3",
        "gulp": "3.9.1",
        "gulp-autoprefixer": "3.1.0",
        "gulp-clean": "0.3.2",
        "gulp-cli": "1.2.1",
        "gulp-concat": "2.6.0",
        "gulp-foreach": "0.1.0",
        "gulp-less": "3.0.5",
        "gulp-minify-css": "1.2.4",
        "gulp-sourcemaps": "1.6.0",
        "gulp-watch": "4.3.5",
        "isparta": "4.0.0",
        "jsdom": "8.3.0",
        "json2csv": "3.2.0",
        "merge-stream": "1.0.0",
        "mocha": "2.x.x",
        "mup": "0.11.3",
        "npm-check": "5.1.3",
        "sinon": "1.17.x"
    },
    "scripts": {
        "compile-css": "gulp css --gulpfile .gulpfile.js",
        "build": "meteor build .build --directory --architecture=os.linux.x86_64",
        "watch-css": "gulp --gulpfile .gulpfile.js",
        "deploy-staging": "./.scripts/deploy_staging.sh",
        "deploy-production": "./.scripts/deploy_production.sh",
        "check-dependencies": "./node_modules/.bin/npm-check",
        "lint": "./node_modules/.bin/eslint ./lib ./client ./server ./packages --ext .js --ext .jsx",
        "test-only": "./node_modules/.bin/mocha --compilers js:babel-core/register ./packages/**/tests/**/*.js",
        "test": "npm run lint && npm run test-only",
        "test-watch": "npm run testonly -- --watch --watch-extensions js,jsx",
        "coverage": "./node_modules/.bin/babel-node ./node_modules/.bin/isparta cover --include 'packages/**/*.js' _mocha -- 'packages/**/tests/**/*.js' --reporter spec --ui tdd --report text --report html"
    },
    "private": true
}

```

I realized that removing the node_modules folder, the total build (meteor build) takes about 1 to 3 mins (still a lot, but comparable to what it takes with a blank project).

After running npm install, you end up with **20 minutes of build time**.

**Comment by aldeed** [comment] 2016-04-08 18:37
We are seeing some slow builds, too. Hard to pin down. No helpful reproduction yet, but it does not seem to be an isolated incident.

**Comment by enricofoschi** [comment] 2016-04-08 19:41
I can confirm that the issue became during the upgrade from `METEOR@1.3-beta.12` to `METEOR@1.3-rc.4`. I had a Jenkins build fired up exactly after the upgrade (main change) and it went from 1m30secs to 11mins.

**Comment by enricofoschi** [comment] 2016-04-08 20:20
I confirm now, I reverted all the app back to `METEOR@1.3-beta.12` and build time is back to < 2mins.

**Comment by khwerhahn** [comment] 2016-04-09 15:34
Same issue here. After a clean install of meteor 1.3.1 everything build fast. After some time, it just "hangs". 

MacBook Air (13-inch, Early 2015) OS X 10.11.4 8GB 2,2 GHz

**Comment by enricofoschi** [comment] 2016-04-09 18:26
The issue comes between beta.12 and the next beta (beta.16 - as 13,14,15 had version bump issues).

Notes: [https://github.com/meteor/meteor/issues/6266#issuecomment-194507690]

I do believe this may be the culprit:

> On the server, modules contained within node_modules directories are now loaded using the native Node require function. #6398 #6438 #6430 #6427 #6385 #6373

**Comment by benjamn** [comment] 2016-04-10 17:16
@enricofoschi wow that's half a gigabyte (530MB) of `node_modules` dependencies!

The version range identified above does contain a [commit](https://github.com/meteor/meteor/commit/26e3cd7df26dfbfac2f752919023ac310fabe8cf) that copies `node_modules` directories into the bundle during `meteor build`. It's possible that we can make that copy take less time, but it's always going to take some time to copy that many files, so you might be better served by (drastically) reducing the number of files that need to be copied.

To that end, I recommend you run
```sh
mv node_modules .node_modules.backup
meteor npm install --production
```
in your app before running `meteor build`, so that you don't have to copy the `devDependencies`. Then the `node_modules` directory will only be 46MB, and the copy should take 8% as long as it did before.

**Comment by benjamn** [comment] 2016-04-10 18:04
You might also try the `--directory` option for `meteor build`:
```sh
  --directory         Output a directory (rather than a tarball) for the
                      application server bundle. If the output location exists,
                      it will be recursively deleted first.
```

**Comment by enricofoschi** [comment] 2016-04-11 06:07
It does work indeed @benjamn, and here is my full jenkins script:
```
npm install
npm run test
rm -rf .node_modules.backup
mv node_modules .node_modules.backup
npm install --production
mup reconfig
mup deploy
rm -rf node_modules
mv .node_modules.backup node_modules
```

**Comment by aldeed** [comment] 2016-04-11 13:15
@benjamn maybe the build process should `npm install --production` in the build rather than copying `node_modules`. Everyone is bound to have a lot of dev deps in there.

**Comment by mxab** [comment] 2016-04-11 14:28
We also experiencing 10mins builds.

Actually it looks like our jenkins is not able to build it anymore as we are getting:
```
/var/lib/jenkins/.meteor/packages/coffeescript/.1.0.16.1vh9g04++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: ENOSPC, open '/var/lib/jenkins/jobs/pt-meteor-webapp/workspace/app/.meteor/local/build_tar/.build599317.bundle/programs/.build830064.server/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/LICENSE'
```

But our build system has still about 15 GB free.
It is a angular-meteor project

**Comment by benjamn** [comment] 2016-04-11 14:35
@aldeed IMO this is something we could warn about, but I am very much against magically altering the contents of `node_modules` because it seems to help in some cases. There are just too many different ways of using `npm` to justify that kind of scenario-solving invasive behavior.

**Comment by aldeed** [comment] 2016-04-11 15:00
@benjamn I'm not proposing altering `node_modules` in the code directory but only in the output directory/tarball. I'm a little confused why we need to install npm pkgs at all for a build. I'm not sure what specific ways of using npm you mean, but you could always have some way of specifying certain `node_modules` to copy in addition. Since that seems like <1% it does not make sense to do something really inefficient for that reason.

To me it seems most logical to just copy the `"dependencies"` object from the `package.json` into the `package.json` that is generated for the build. We already `cd /app/programs/server/ && npm i --production` when deploying anyway. I'm guessing there is some good reason why it isn't done that way, though.

**Comment by benjamn** [comment] 2016-04-11 15:51
I like the idea of only copying "dependencies" if (and only if) there is a `package.json` file, because it doesn't involve re-running `npm install`. That's not going to make it into 1.3.2, but I would consider implementing it in a future `1.3.x` release.

As for the diversity of ways of populating `node_modules` directories, here are some questions to consider:
* What if you don't have a `package.json` file, but only an `npm-shrinkwrap.json` file?
* What if you have multiple `node_modules` directories (`client/node_modules`, `server/node_modules`, etc.)?
* What if your `node_modules` directory is committed to version control?
* What if you're using `npm@3` to get a flatter dependency structure, and reinstalling with `--production` messes that up? 
* What if you're using one of those `devDependencies` in your code? 
* What if this list of questions is incomplete?

It's fine for you to have the opinion that these are fringe choices, and that the app may simply not work in production, but Meteor doesn't have the luxury of being so opinionated. As a Meteor application developer, you have complete control over the contents of your local `node_modules` directories. They're just directories. If they get accidentally huge, there may be consequences, and you can mitigate those consequences with a script like the one @enricofoschi posted above, or whatever makes sense for your project.

**Comment by aldeed** [comment] 2016-04-11 16:36
@benjamn I would actually argue that MDG responsibility is to define what the recommended way of doing it is, and make that way as fast as possible out of the box. It seems really reasonable to me to say that if you do things in a standard way (have a package.json and --save your deps there), it will work out of the box and build quickly. Then for edge cases, there can be a file where you list out additional folders to copy into `node_modules` when building, or a flag to turn on `--use-local-node-modules` mode.

As for the list, briefly:
- `devDeps` used in code and forgetting to `--save` are mistakes that should not be masked. It should error.
- Anything in `npm-shrinkwrap` in dep Meteor pkgs and in the app's `package.json` should be combined into the `dependencies` object of the built app's `package.json`.
- For a flat structure, you would just `cd /app/programs/server/ && npm i --production` in the built app while using latest npm. We are actually doing that in a couple 1.3 apps now, and it's fine. Are you saying it wouldn't work anymore if this change were made?
- Everything else could be supported with opt-in copying of select local modules folders.

I really appreciate all the work that went into modules support and I personally don't have a problem with working around this issue with build scripts, but I already see a bunch of people souring on 1.3 (and on using Meteor in general) due to the remaining issues with tool slowness (not just prod builds, but also dev builds and rebuilds, cordova builds, and test builds). It might be that some of the decisions you've made for broad compatibility are coming back to bite you in unintended ways. So I'm arguing this more for the community in general than for myself.

**Comment by AlmogRnD** [comment] 2016-04-15 12:58
Hi guys, 
Any finial news regarding this we just upgrade are meteor app to meteor 1.3 and it's taking us up to an hour to deploy the project? Is there is a final fix for this?

**Comment by StanLindsey** [comment] 2016-04-28 08:33
I agree with @aldeed - somebody who has had to work with multiple react dependencies by hand or is building their all in a non-common way should be very capable of adding a flag or two to the build command. 

Also a `meteor build --help` flag could also list 'common' edge cases and workarounds.

**Comment by baloodevil** [comment] 2016-04-28 14:08
Experiencing slow build times (60 seconds), and slow rebuild times (30 seconds), running 1.3.2.4.  Possibly, the rebuild is not detecting which files have changed, because it takes 30 seconds when only adding one line to an html page.

By the way, for troubleshooting build times, from command line enter `set METEOR_PROFILE=200`.  Then when building with `meteor`, the console will log any operation that takes longer than 200 milliseconds.  Attaching those logs here...
[build_log.txt](https://github.com/meteor/meteor/files/240660/build_log.txt)
[rebuild_log.txt](https://github.com/meteor/meteor/files/240661/rebuild_log.txt)

**Comment by enricofoschi** [comment] 2016-04-28 14:33
Slow rebuild time (30 secs when rebuilding) are new to me too. I hope this is some simple problem that can be easily fixed - maybe worth mentioning @benjamn here too.

**Comment by abernix** [comment] 2016-04-28 14:51
@baloodevil Your build logs shows that the `barbatus:typescript` compiler plugin is taking a **substantial** amount of time (20s on rebuild) and more on the initial build.

@enricofoschi attaching logs as @baloodevil did would be very helpful.  Simply add `METEOR_PROFILE=200 ` in front of your `meteor` command to see where the majority of time is being spent.  Then attach the results here (as a file, preferably).

**Comment by baloodevil** [comment] 2016-04-28 16:00
@abernix Thanks.  I noticed the same thing.  @barbatus is there room for improvement in the speed of the typescript compilation related to meteor?

**Comment by abernix** [comment] 2016-04-28 16:06
@baloodevil @enricofoschi Also, this issue is about the build times for building the production bundle (using `meteor build`), not the reload time between code changes when running with the meteor tool, so a bit off topic for this issue.  Maybe open separate issues with your detailed `METEOR_PROFILE` outputs and reproductions?

**Comment by barbatus** [comment] 2016-04-28 16:13
@baloodevil What version do you use? How many ts-files does your project have?

**Comment by enricofoschi** [comment] 2016-04-28 16:53
@abernix agree - not specifically related to this issue. Will investigate more with the useful tip provided and follow up on other relevant issues or create a new one if can't find a similar one.

**Comment by benjamn** [comment] 2016-05-16 23:00
Here's a better workaround: run [`npm prune --production`](https://github.com/npm/npm/issues/2854) before building/deploying.

With the flattening that npm v3 does, indirect dependencies of production dependencies are often installed outside the directory tree of the package you're depending on, so any solution to this problem must know better than to remove such packages.

The `npm ls --production` command can also be helpful for figuring out which packages are actually needed in production, though it displays the logical dependency tree rather than displaying packages as they are installed on disk.

**Comment by aldeed** [comment] 2016-05-17 12:43
Nice, thanks @benjamn

**Comment by priezz** [comment] 2016-05-17 16:00
@benjamn, maybe I am doing something wrong, but `npm prune --production` breaks the build process for me... I have a lot of PostCSS plugins in `devDependencies`. When they are removed, build fails (as expected). When not doing `prune`, everything goes well, these plugins are not in the `packages` directory, so regarding postcss the build process works fine. But I still have unexpected non-npm packages in the build, like babel and ecmascript. (Meteor 1.3.2.4)

**Comment by benjamn** [comment] 2016-05-17 16:07
@priezz `npm prune --production` does not remove any Meteor packages from your app, if that's what you expected? It just reduces the size of the `node_modules` directory in the root of your app.

**Comment by priezz** [comment] 2016-05-17 16:38
@benjamn, no, I mean that postcss plugins are removed while they are still required to build the app (not to run, that is why they are in devDependencies section). 
As to the Meteor packages (babel and ecmascript) - do they need to be in the final build? That is different topic, not about npm at all :), I have chosen wrong issue to write about that.

**Comment by benjamn** [comment] 2016-05-17 16:54
@priezz ok, then I don't recommend you do `npm prune --production`. Instead, please try running Meteor [from a checkout](https://github.com/meteor/meteor/blob/release-1.3.3/README.md#slow-start-for-developers), using the current `release-1.3.3` branch:
```js
cd path/to/meteor
git fetch origin
git checkout -t origin/release-1.3.3
cd path/to/your/app
path/to/meteor/meteor run
```
[This recent commit](https://github.com/meteor/meteor/commit/7574f74481574222a494d0993f2b3286cfcdf4d6) may fix your problems. If not, please open a new issue, as I think this is slightly different from the current issue.

**Comment by priezz** [comment] 2016-05-18 12:55
Ok, thanks! Will try that.

**Comment by kachkaev** [comment] 2016-05-19 19:29
@benjamn what is the current schedule for `1.3.3` alpha/beta/rc releases? I'd be keen frequently update and test new stuff including the improved build times. Fetching right from a branch seems to be too much (the stability is too unpredicted) and the latest release was 15 days ago.

Great that MDG deals with this issue before the next new version!

**Comment by abernix** [comment] 2016-05-20 10:07
@kachkaev Please watch the [Milestone for 1.3.3](https://github.com/meteor/meteor/milestones/Release%201.3.3) and the [[WIP] PR for 1.3.3](https://github.com/meteor/meteor/pull/7033).  I realize that there are not hard dates on things or schedules, but as you can see, there is still work to be done.  Things are moving as quickly as possible – and work is happening.

If you want to test new stuff (and please help test if you can!), the only *published* beta 1.3.3 branch right now is `--release 1.3.3-ddp-batching-beta.0` (however the above change is not in that).  If you want everything done so far, then you'll need to do as Ben said above and run from checkout (the `release-1.3.3` is *slightly* less unpredictable than `devel`, but alphas and betas are unpredictable too).

**Comment by benjamn** [comment] 2016-05-21 00:02
This should be fixed if you do `meteor update --release 1.3.3-beta.0`.

**Closed by benjamn** 2016-05-21 00:02 UTC
Labels: feature, Project:Isobuild:Performance, pull-requests-encouraged

**Comment by kachkaev** [comment] 2016-06-22 10:00
This is still the case as of `1.3.4-rc.1`. See discussion here https://github.com/meteor/meteor/pull/7218 and also an MWE here: https://github.com/kachkaev/meteor-build-times-mwe

**Comment by benjamn** [comment] 2016-06-22 14:49
@kachkaev I don't mean to split hairs, but this issue was about slow `meteor build` times, whereas your excellent reproduction demonstrates `meteor run` startup times. This issue (#6750) was mitigated by excluding `devDependencies` when doing `meteor build`, but it's still an open question (that you and I have discussed) whether we should do the same in development.

**Comment by aldeed** [comment] 2016-06-22 23:28
How about a `meteor run` option like `--include-dev-deps foo,bar`, and when that is used, only the listed dev deps are included?

**Comment by kachkaev** [comment] 2016-06-22 23:33
@aldeed there's a pretty good (temporary?) solution in 1.3.4 now. Have a look at https://github.com/meteor/meteor/issues/7008 and https://github.com/meteor/meteor/pull/7263.

**Comment by aldeed** [comment] 2016-06-23 00:26
cool thanks

**Comment by javascriptlove** [comment] 2017-11-09 15:41
Using latest Meteor 1.6, after meteor build to a folder i STILL see the development dependencies of meteor packages being in the `programs/server/npm/node_modules/meteor`. As an example, I took a meteor package `reywood:publish-composite` and here's what's inside:

```
root@a3cf364f0633:/built_app/programs/server/npm/node_modules/meteor/reywood_publish-composite/node_modules# du -hs ./*
29M	./eslint
2.4M	./eslint-config-airbnb
2.2M	./eslint-plugin-import
2.2M	./eslint-plugin-jsx-a11y
2.6M	./eslint-plugin-react
```

And there's more, in total for our rather small project the `npm/node_modules/meteor` has at least 100M of excessive weight
