### ISSUE TITLE
[1.5.1, 1.6.0] Incoming HTTP Request Hanging With Mocked Time

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#8975] opened 2017-08-02 05:14 UTC
## Tested with
Meteor 1.5.1, 1.6-beta.24, 1.6 branch, devel branch

## Expected Behavior
HTTP requests to Meteor should continue to work normally even if I mock out the time or change system timers.

## Actual Behavior
Under certain circumstances Meteor will stop responding to incoming HTTP requests when time is mocked

Mocking the date can cause incoming HTTP requests to Meteor to hang somewhere at the node level. By using `NODE_DEBUG=net,http` I can see that the incoming socket times out. (sample output in directory `3-debug-info`)

## Reproduction URL
https://github.com/hexsprite/meteor-issue-8975.git

There are two examples here:

- `1-node-example` - shows how this works fine under plain NodeJS

- `2-meteor-example` - shows how Meteor hangs under the circumstance. Then you can comment out `accounts-base` in `.meteor/packages` and see how it now works!

More details in various `README` files in the repo.

## Workaround

Disable `accounts-base` package -- try commenting it out in the example to see. Not sure why. But this could be a clue!

## Impact

I have been writing tests that mock the system time. I noticed that I could no longer access the client side tests. Right now I can't run my client side tests and server side tests in a single run.

**Comment by hexsprite** [comment] 2017-08-23 18:06
Just tested with 1.6b24 and this behavior is still occuring.

**Comment by hexsprite** [comment] 2017-09-15 18:33
just re-tested with 1.6b27, issue is still present. Updated the repro repo with the new meteor version.

**Comment by hexsprite** [comment] 2017-11-03 19:57
Still a problem with 1.6

**Comment by hwillson** [comment] 2017-11-07 18:02
@hexsprite I just tried your [`2-meteor-example`](https://github.com/hexsprite/meteor-issue-8975/tree/master/2-meteor-example) app (without changing anything), and it seems to work properly on my side. I don't see any errors in the console:

![screenshot 2017-11-07 12 59 52](https://user-images.githubusercontent.com/137740/32509594-bf5186f0-c3bb-11e7-92fd-c8b582a6a251.png)

**Comment by hwillson** [comment] 2017-12-01 20:29
Closing for now as we're unable to reproduce this issue with Meteor 1.6. Thanks!

**Comment by hexsprite** [comment] 2017-12-02 08:03
@hwillson by accident when I updated to Meteor 1.6 I committed the packages file in the "workaround" state. I've changed it so that it exhibits the error now by uncommenting `accounts-base` in the packages file. Please re-open this issue as it is still a problem.

**Comment by abernix** [comment] 2017-12-04 11:51
Re-opening so this doesn't get lost, though haven't looked at it again.

**Comment by klaussner** [comment] 2017-12-24 11:48
@hexsprite `lolex.install` mocks [several timer functions](https://github.com/sinonjs/lolex#var-clock--lolexinstallconfig), including [`setImmediate`](https://nodejs.org/api/timers.html#timers_setimmediate_callback_args), which Meteor uses in its (internal) `Meteor._SynchronousQueue` to schedule tasks:

https://github.com/meteor/meteor/blob/3f8c90a29f26ec6dc8ff55f736c36a68fa40398f/packages/meteor/fiber_helpers.js#L124-L128

If `setImmediate` is mocked and the mocked clock isn't advanced, the tasks in the queue are never executed. In your example, Meteor doesn't respond to incoming requests because the following task in the `webapp` package is scheduled but not executed:

https://github.com/meteor/meteor/blob/3f8c90a29f26ec6dc8ff55f736c36a68fa40398f/packages/webapp/webapp_server.js#L607-L627

The `accounts-base` package isn't directly related to this problem but it depends on `service-configuration`, which creates a new `Mongo.Collection`, which also uses `Meteor._SynchronousQueue` and schedules some tasks. As a result of this, the `webapp` task is executed before `setImmediate` is mocked but then other tasks (e.g., the ones scheduled when the `Mongo.Collection` is created) won't be executed instead. Even if the page loads, you will probably encounter other problems, such as publications not sending data to clients.

I don't think that this is a bug in Meteor because you are essentially replacing a Node.js API with a function that doesn't work as documented (it doesn't call a function "at the end of this turn of the Node.js Event Loop").

**Solution**

The easiest solution is to simply not mock `setImmediate` (if your tests don't need a mocked version):

```js
const clock = lolex.install({
  toFake: ["setTimeout", "clearTimeout", "setInterval", "clearInterval", "Date"]
});
```

However, `setTimeout`, `setInterval`, and `Date` are also used in many Meteor core packages, so it's probably safer to call `lolex.install` only for short code blocks and to uninstall the mocks as soon as they aren't needed anymore.

**Comment by hwillson** [comment] 2018-01-02 18:01
As mentioned in https://github.com/meteor/meteor/issues/8975#issuecomment-353779984, this isn't an issue caused by Meteor itself. Closing for now (thanks for the awesome detective work @klaussner!).

**Closed by hwillson** 2018-01-02 18:01 UTC

**Comment by hexsprite** [comment] 2018-01-03 06:41
@klaussner thanks for taking the time to write up the detailed explanation. Indeed I tried your suggestion and it helps!
