### ISSUE TITLE
App hangs on new user creation after meteor update to 1.6.1 . User document has been created but can not be logged in.

### ISSUE THREAD

**Issue by AayushShrestha** [meteor/meteor#9697] opened 2018-02-26 04:43 UTC
After meteor was updated recently to 1.6.1 we found out that our meteor app would not register new user. Registration process would drop after showing this error

```
Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {}
```
(Searched for this error and found out that the issue is tracked in #9087 and a solution is to be patched soon in #9671 )

Here are a few interesting things that are happening:
- Even though the register action is dropped, the new user document is created.
- We can not log in using this new user credentials even though all fields are there.
- All previously created users can still be logged in, no problem there.
- We have been saving some data in the `profile` field. On the new user document, if we delete the `profile` field, we can log in to these accounts again.
- All problems vanish once you reset database, that is why we are not being able to reproduce the issues locally. The issue is currently happening in our remote staging server. 

Of course, we can not reset the database in our staging or production servers. So, we were looking for someone to explain what exactly is causing these problems so that we can work on a fix. 
Thanks.

**Comment by hwillson** [comment] 2018-02-27 20:47
@AayushShrestha The problem you're encountering is caused by https://github.com/meteor/meteor/commit/ce3885b6df10f9f69f425af8698642a388efa6f2. Mongo connections are now configured using `ignoreUndefined`, which means `undefined` fields are stripped before being fired over to Mongo, instead of being converted to `null` (like they were previously). This reason for this change is outlined in that commit. 

Unfortunately, as discussed in https://github.com/meteor/meteor/issues/9087, there are certain cases where not stripping the `undefined` fields on the minimongo side can cause errors, like the one you've mentioned. The fix supplied in https://github.com/meteor/meteor/pull/9671 aims to address those errors.

As a quick fix on your side, you could try to make sure you're never attempting to send `undefined` fields into Mongo, in any way (in a selector, in a document, etc.). Just strip those fields before communicating with minimongo/mongo, and you should avoid this error. We'll aim to have the proper fix deployed shortly. 

Since this is already being tracked in https://github.com/meteor/meteor/issues/9087, I'll close this issue. Let's continue the discussion in https://github.com/meteor/meteor/issues/9087 as needed. Thanks!

**Closed by hwillson** 2018-02-27 20:47 UTC
