### ISSUE TITLE
Bug: Extracting meteor-tool on windows

### ISSUE THREAD

**Issue by Infonautica** [meteor/meteor#8871] opened 2017-07-02 16:37 UTC
I know i am **not the first one** with this problem, but i can't find a **100% working solution**.

I have PC and laptop, both on Windows 10 and on both computers having infinite **extracting of meteor-tool@1.5.0** package. 
Here my specs:
- Windows 10 Pro
- Node v7.7.2
- Npm 4.4.4
- Updating from Meteor v1.4 up to v1.5
- Don't have 7z installed

What should i do?

**Comment by Infonautica** [comment] 2017-07-02 16:57
I also tryed remove WinRar and disable Windows Defender. Didn't work

**Comment by Infonautica** [comment] 2017-07-03 08:27
ConEmu shows process name, and it log 7z.exe:4180, while extracting

**Comment by abernix** [comment] 2017-07-04 20:59
How long did you wait for it to finish?  Did you disable any other virus scanner you might have enabled?  As a last resort, how is your experience using these [manual installation instructions](https://github.com/meteor/docs/blob/version-NEXT/long-form/alternate-windows-installation.md)?

The version of Node.js and npm you have installed don't matter – in fact, you don't need them installed at all since Meteor packages its own.

**Comment by Infonautica** [comment] 2017-07-12 12:46
Can't remember for how long i wait. For now i have solved this problem, but don't know what exactly helped. That is not right, when i want to use something automatic, like Meteor and spend few days to install it. But what i do remember is manual installation didn't extract correctly, it start throwing errors in 7z's console in progress

**Comment by coagmano** [comment] 2017-07-18 23:13
The Windows folks on my team had very long extraction times as well. It did eventually finish after 5-10min, unlike OP.
Probably points to an area where the upgrade process could be optimized on Windows

**Comment by shashank7200** [comment] 2017-07-19 13:30
I can confirm this issue.

**Comment by shashank7200** [comment] 2017-07-19 14:49
@Infonautica This Solution worked for me:

1. Stop all `meteor` commands, if executing.
2. Installed [7z1604-x64.msi](http://www.7-zip.org/a/7z1700-x64.msi)
3. Deleted `pre-installed` 7zip came with meteor from `C:\Users\%username%\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\dev_bundle\bin` 
    - Change `meteor-tool` **version** (in my case `1.5.1`) that is currently available in your directory
4. Now run the command which earlier executed, which started `meteor-tool` installation.
5. Extraction process for me took about 10-15 minutes.

:octocat:  Hope it works for you too!

**Comment by justbill2020** [comment] 2017-08-03 15:04
can we get a x86 and x64 bit version for the windows dev_bundle? and have meteor-tools identify which version to use so that this isn't happening and we don't have to use the work around?

**Comment by hwillson** [comment] 2017-08-03 16:01
@justbill2020 Meteor's 32-bit support is being dropped for all architectures in the not too distant future. That work is being tracked here: https://github.com/meteor/meteor-feature-requests/issues/152

**Comment by mitar** [comment] 2017-08-06 21:16
> can we get a x86 and x64 bit version for the windows dev_bundle? and have meteor-tools identify which version to use so that this isn't happening and we don't have to use the work around?

Why does 64 bit helps here with the performance?

**Comment by justbill2020** [comment] 2017-08-07 00:44
@mitar it's a 7zip issue... meteor uses a 32 bit version so if you have a 64bit version of windows it takes forever... @shashank7200 provides a workaround above...

**Comment by abernix** [comment] 2017-08-07 09:58
The version of 7z that we package with Meteor is not just 32-bit, according to the description of the file from [this page](http://www.7-zip.org/download.html) that we're installing:

![image](https://user-images.githubusercontent.com/841294/29021877-b6206ab8-7b6f-11e7-8321-31d32add44b9.png)

As you can see it says, `x86 / x64` and this is the file installed into the dev bundle [via this script/line](https://github.com/meteor/meteor/blob/3b2e0b6dbcd32ab8adebf1fb3ead69fe236da944/scripts/generate-dev-bundle.ps1#L50).

**Comment by AirBorne04** [comment] 2017-08-08 09:58
@abernix the package that you are installing is containing both versions, the question is if the reference is than the 32 bit version (in the root of the archive) or the 64 bit version (from the x64 subfolder)

**Comment by abernix** [comment] 2017-08-08 11:42
@AirBorne04 Ok, that makes sense (I admittedly didn't look into the archive, to look for that strangely-separate directory).  In light of this, and the very real possibility that a 32-bit version is terribly inefficient on a 64-bit platform, it seems that https://github.com/meteor/meteor-feature-requests/issues/152 is still our best bet here.  Performance overall is probably going to be quite a bit better given a 64-bit Node.js, etc.

**Comment by hwillson** [comment] 2017-09-14 16:09
There is a workaround to this problem outlined in https://github.com/meteor/meteor/issues/8871#issuecomment-316411859, and 32-bit Windows support is scheduled to be dropped soon (https://github.com/meteor/meteor-feature-requests/issues/152), so we should be okay to close this issue off. Thanks all!

**Closed by hwillson** 2017-09-14 16:09 UTC

**Comment by justbill2020** [comment] 2017-09-19 18:41
so @hwillson this wasn't fixed in 1.5.2??? back to horrible load times and had to replace the 7z.exe file again.

**Comment by hwillson** [comment] 2017-09-19 19:23
@justbill2020 No, it hasn't been fixed yet. The Meteor 32-bit deprecation work is being done off of the `release-1.6` branch, so those changes will likely be coming in a future 1.6.x release.

**Comment by Elemb** [comment] 2017-10-01 15:23
That was an recursive function, which infinitely added files to 
C:\Users\%user%\AppData\Local\.meteor
mine was added 800.000 files.
fault of guys which writes manuals..

**Comment by Harolinch** [comment] 2019-04-09 16:32
i just waited for some time, and it worked. just be patient
