### ISSUE TITLE
meteor doesn't run on windows10

### ISSUE THREAD

**Issue by dotcomet** [meteor/meteor#6738] opened 2016-04-07 12:16 UTC
hi, 
i ran the windows (10) installer from meteor.com, created an app, changed into the app directory and typed run and got an error - please advise.
i asked on the meteor forum, there i was told i didn't do anything wrong and should report an issue.

hereis the text from my terminal.

Microsoft Windows Version 10.0.10586 2015 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\ma-ia>cd C:\Users\ma-ia\meteor

C:\Users\ma-ia\meteor>meteor create simple
Created a new Meteor app in 'simple'.

To run your new app:
cd simple
meteor

If you are new to Meteor, try some of the learning resources here:
https://www.meteor.com/learn

C:\Users\ma-ia\meteor>cd simple

C:\Users\ma-ia\meteor\simple>meteor run
[[[[[ C:\Users\ma-ia\meteor\simple ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

While loading plugin compileTemplatesBatch from package templating:
module.js:338:15: Cannot find module '../modules/es6.object.get-own-property-descriptor'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.
(C:\Users\ma-ia\AppData\Local.meteor\packages\templating\1.1.7\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\ecmascript-runtime\node_modules\meteor\ecmascript-runtime\node_modules\meteor-ecmascript-runtime\node_modules\core-js\es6\object.js:12:1)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.
(C:\Users\ma-ia\AppData\Local.meteor\packages\templating\1.1.7\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\ecmascript-runtime\node_modules\meteor\ecmascript-runtime\node_modules\meteor-ecmascript-runtime\server.js:1:1)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at npmRequire (C:\tools\isobuild\bundler.js:1665:14)
at Module.useNode (packages/modules-runtime.js:453:20)
at fileEvaluate (packages/modules-runtime.js:157:20)
at require (packages/modules-runtime.js:92:16)
at meteorInstall.node_modules.meteor.ecmascript-runtime.runtime.js (packages/ecmascript-runtime.js:24:18)
at fileEvaluate (packages/modules-runtime.js:158:9)
at require (packages/modules-runtime.js:92:16)
at packages/ecmascript-runtime.js:2832:15
at packages/ecmascript-runtime.js:2845:3

=> Your application has errors. Waiting for file change.

+++++++++++++++++++++++++++++++++++++++++++++++++++

and this is the output of my local host:

Your app is crashing. Here's the latest log:
Started MongoDB.
Errors prevented startup:

While loading plugin compileTemplatesBatch from package templating:
module.js:338:15: Cannot find module '../modules/es6.object.get-own-property-descriptor'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\ma-ia\AppData\Local.meteor\packages\templating\1.1.7\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\ecmascript-runtime\node_modules\meteor\ecmascript-runtime\node_modules\meteor-ecmascript-runtime\node_modules\core-js\es6\object.js:12:1)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\ma-ia\AppData\Local.meteor\packages\templating\1.1.7\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\ecmascript-runtime\node_modules\meteor\ecmascript-runtime\node_modules\meteor-ecmascript-runtime\server.js:1:1)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at npmRequire (C:\tools\isobuild\bundler.js:1665:14)
at Module.useNode (packages/modules-runtime.js:453:20)
at fileEvaluate (packages/modules-runtime.js:157:20)
at require (packages/modules-runtime.js:92:16)
at meteorInstall.node_modules.meteor.ecmascript-runtime.runtime.js (packages/ecmascript-runtime.js:24:18)
at fileEvaluate (packages/modules-runtime.js:158:9)
at require (packages/modules-runtime.js:92:16)
at packages/ecmascript-runtime.js:2832:15
at packages/ecmascript-runtime.js:2845:3

Your application has errors. Waiting for file change.

**Comment by abernix** [comment] 2016-04-07 14:46
This was just fixed in Meteor 1.3.1, but it's not being forced out yet (the release is stable though).  You can fix this by running `meteor update --release 1.3.1`.  Same as #6609  and #6669.

Please close this issue if this resolves it for you. :smile_cat:

**Comment by wkyleg** [comment] 2016-04-07 19:08
I have experienced the same error as others with version 1.3.1 using windows 10.  I uninstalled the packages that were causing problems and reinstalled them (templates, ecmascript, etc) and it solved the problems above.  I tried running the above command (meteor update --release 1.3.1) and meteor says it is up to date.

The problem I still have is that when I type "meteor run" or just "meteor" the app never launches.  I have tried with the "--verbose" command as well, and meteor does not identify anything as wrong.  

Meteor just hangs up at "starting proxy", then "starting your app" and freezes there.  CPU and memory are at normal levels too.  Even letting this run for 10-15 minutes does nothing.  I have installed and uninstalled meteor multiple times and this is the furthest I can get.  Its really frustrating because I really want to start learning this framework even the example apps wont run

**Comment by tk303** [comment] 2016-04-24 09:51
I'm experiencing similar problem.
In my case meteor gets stuck trying to download/install meteor-tools package (I'm using the latest version of meteor)
It seems that the problem lays somewhere that the very deep folder structure results in file path names beein too long for Windows to handle.
It creates files with too long path under: C:\Users\<UserName>\AppData\Local\Temp and C:\Users\<UserName>\AppData\Local\.meteor that I'm not even able to delete manually.

**Comment by abernix** [comment] 2016-07-11 12:21
There have been problems with long paths in Windows.   Please update to Meteor 1.3.4.4 which _greatly_ improves this problem.  If you still have an issue, please open a new issue with a fresh reproduction and the full output from your logs.  You can update to the latest version by running:

    meteor update --release 1.3.4.4

Closing this issue as the original issue should be resolved by this.  Though, please be aware that if you are using Cordova, there are similar issues with that being tracked in #7358.

**Closed by abernix** 2016-07-11 12:21 UTC

**Comment by kowalsk** [comment] 2016-10-26 11:39
This has worked for me on Windows 10, after standard installer failed:

https://github.com/meteor/docs/blob/version-NEXT/long-form/alternate-windows-installation.md

For your convenience the contents of the link:

On some network or machine setups Meteor's installer for Windows may fail. In such cases, follow these simple steps to install Meteor manually:

Install 7-Zip or any other program that knows how to extract tar.gz files.
Download the installation archive from https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_32.
In a command prompt, run echo %LocalAppData%\.meteor -- this is the directory in which Meteor should be installed.
Extract the installation archive into the directory above.
Add this directory to your PATH environment variable.
You should now be able to open a new command prompt and run meteor. Some versions of Windows may require restarting your machine first.
