### ISSUE TITLE
rawCollection isn't present in the docs.

### ISSUE THREAD

**Issue by mariorodriguespt** [meteor/meteor#4304] opened 2015-04-30 17:44 UTC

**Comment by benjamn** [comment] 2015-05-05 22:11
@glasser Looking at https://github.com/meteor/meteor/issues/3640, I can't tell if `rawCollection` was intended to be a public API. Thoughts?

**Comment by rclai** [comment] 2015-05-05 22:13
I've been using it a lot please don't make it inaccessible.

**Comment by mariorodriguespt** [comment] 2015-05-05 22:17
Me too, keep it public.

**Comment by keyscores** [comment] 2015-08-14 17:02
I think lots of people are using rawCollection as a work-around for mongo aggregation support. See here: https://github.com/meteor/meteor/issues/4947

**Comment by hwillson** [comment] 2016-12-20 20:16
`rawCollection` is mentioned in the docs [here](https://docs.meteor.com/api/collections.html#Mongo-Collection-rawCollection). Closing - thanks!

**Closed by hwillson** 2016-12-20 20:16 UTC
Labels: Project:Docs
