### ISSUE TITLE
Allow installing meteor to a folder other than $HOME/.meteor, so it can be cached in Travis CI

### ISSUE THREAD

**Issue by rbabayoff** [meteor/meteor#4726] opened 2015-07-12 08:00 UTC
So builds can run faster in Travis CI, using it's caching feature:

http://docs.travis-ci.com/user/caching/

The meteor install script can check for a METEOR_HOME env var and use it, instead of the default target folder.

**Comment by glasser** [comment] 2015-07-14 23:48
Duplicate of #2268.

**Closed by glasser** 2015-07-14 23:48 UTC
Labels: Project:Installer
