### ISSUE TITLE
[1.7] Cannot import .json files in packages

### ISSUE THREAD

**Issue by MacRusher** [meteor/meteor#10122] opened 2018-08-03 11:15 UTC
Since Meteor 1.7, you cannot import `.json` files in local packages on the server side.

```
// Inside a local package
import data from './example.json';

if (Meteor.isServer) {
  console.log(data); // data is always {}
} else {
  console.log(data); // works as intended
}

```

### Reproduction steps

Full reproduction repo, based on default 1.7 project can be found here:  
https://github.com/MacRusher/meteor-json-issue

```
git clone https://github.com/MacRusher/meteor-json-issue
cd meteor-json-issue
meteor run
```

You can also use `meteor test-packages` for TinyTest test suite.

#### Expected behavior
Server console output:
```
--- JSON file data: ---
{ example: 42 }
-----------------------
```

#### Actual behavior
Server console output:
```
--- JSON file data: ---
{}
-----------------------
```

Code in question can be found [here](https://github.com/MacRusher/meteor-json-issue/blob/master/packages/example/example.js)

### Affected versions

- 1.6.1.3 - Works as intended
  Can be reproduced with `meteor run --release 1.6.1.3 --allow-incompatible-update`
- 1.7.0.3 (current stable) - Fails
- 1.7.1-beta.14 (current beta) - Fails
  Can be reproduced with `meteor run --release 1.7.1-beta.14`

### Extra info
- OS: Ubuntu Linux
- `meteor node -v`: `v8.11.3`
- It seems that packages imported from Atmosphere are working correctly, but I've not confirmed this yet.
- Replacing `import` with `require` has no effect.

**Comment by benjamn** [comment] 2018-08-03 14:33
Thanks for this great bug report @MacRusher! Every bit of information you provided is helpful, and I had no trouble confirming the problem using your reproduction repo.

**Comment by benjamn** [comment] 2018-08-03 16:40
This should be fixed if you run
```sh
meteor update --release 1.7.1-beta.25
```
Please feel free to reopen if this still seems to be broken after updating.

**Closed by benjamn** 2018-08-03 16:40 UTC
Labels: bug, confirmed, in progress
