### ISSUE TITLE
Meteor deploy mongo server outage 2015-May-12

### ISSUE THREAD

**Issue by jndewey** [meteor/meteor#4373] opened 2015-05-12 18:01 UTC
I am getting below exception in logs.  In addition, connection to Mongo seems to be dead.  Is there any way to recover the data in the databases?  The apps work fine in local environment, but will not load as deployed on meteor server.

[Tue May 12 2015 17:56:10 GMT+0000 (UTC)] INFO Exception while polling query
{"collectionName":"meteor_accounts_loginServiceConfiguration","selector":{},"options":{"transform":null,"fields":{"secret":0}}}: Error: No replica set primary available for
query with ReadPreference PRIMARY
at Object.Future.wait (/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:395:16)
at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:929:1)
at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:963:1)
at [object Object]._.extend.getRawObjects (packages/mongo/mongo_driver.js:1012:1)
at [object Object]._.extend._pollMongo (packages/mongo/polling_observe_driver.js:147:1)
at Object.task (packages/mongo/polling_observe_driver.js:85:1)
at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
at packages/meteor/fiber_helpers.js:125:1
- - - - -
at [object Object].ReplSet.checkoutReader
(/meteor/containers/008f0b7f-0584-b63a-14c2-96f2230acbd1/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:613:14)
at Cursor.nextObject (/meteor/containers/008f0b7f-0584-b63a-14c2-96f2230acbd1/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:748:48)
at [object Object].fn [as _synchronousNextObject] (/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:89:26)
at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:929:1)
at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:963:1)
at [object Object]._.extend.getRawObjects (packages/mongo/mongo_driver.js:1012:1)
at [object Object]._.extend._pollMongo (packages/mongo/polling_observe_driver.js:147:1)
at Object.task (packages/mongo/polling_observe_driver.js:85:1)
at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
at packages/meteor/fiber_helpers.js:125:1

**Comment by glasser** [comment] 2015-05-12 20:26
We are aware of this outage to some of our Mongo servers and are actively working on resolving it.

**Comment by jndewey** [comment] 2015-05-12 20:27
Thanks!  Back up.

**Comment by DeBraid** [comment] 2015-05-21 16:27
Experienced this today.  `meteor deploy` and was back up and running.

**Closed** 2015-05-27 23:36 UTC
Labels: Project:Deploy Server

**Comment by abhisheksoni27** [comment] 2015-07-08 18:06
This issue is still not resolved. Please Fix, ASAP.

**Comment by ekatek** [comment] 2015-07-08 19:08
Thanks for the report, @abhisheksoni27, but we can't reproduce it. That is, I have checked all of the Mongo clusters, and they seem to be working fine, our canary apps are responding to `meteor mongo`, etc. This might be a transient failure -- is it still happening? Can you give us more information? You might also try redeploying your app as a temporary workaround (in case you are dealing with an old failure that has some sort of cascading consequences). For now, cannot reproduce.

**Comment by abhisheksoni27** [comment] 2015-07-09 06:51
It works now. And Since this outage is common with the mongo servers, is there a time span that we hae to wait before Galaxy hits the Meteor Universe?

**Comment by jaredtmartin** [comment] 2015-07-14 14:39
I'm having this issue on returnvisits.meteor.com  Any suggestions?
