### ISSUE TITLE
MONGO_OPLOG_URL sensitive to multiple username/passwords

### ISSUE THREAD

**Issue by oceddi** [meteor/meteor#7264] opened 2016-06-20 22:03 UTC
Just wanted to log an issue against this since it cause me hours of head scratching.  If you are connecting to a mongo replicaset and specify the username and password against each member name in the MONGO_OPLOG_URL you will see no errors but the oplog tailing won't work as expected (updates to the oplog won't get picked up by meteor).

Here is an example of what I mean (the config that causes this type of behavior):

MONGO_OPLOG_URL='mongodb://oplogger:password@10.1.3.109:27000,oplogger:password@10.1.3.8:27000,oplogger:password@10.1.3.139:27000/local?authSource=admin'

It was a simple typo but it was not picked up anywhere and made me troubleshoot in lots of areas (like oplogger mongodb account permissions).

Once I updated the string to the correct format things worked correctly.  Can't meteor validate this string before passing to mongodb?

**Comment by abernix** [comment] 2016-11-07 10:42
@oceddi Not sure why this was tagged as a feature.

I do have two questions if you're still familiar enough with this to provide answers:

0. Have you been able to reproduce this problem on the latest version of Meteor?  Meteor 1.4 brought a substantial upgrade to the Node Mongo driver (from v1.4 to v2.2) which was previously packaged with Meteor.  Additionally, the version has been continually bumped since the 1.4 release to stay in line with the most current release.

0. Since you have architecture setup to easily reproduce this, could you (or did you?) take an opportunity to see if the problem exists in the [Node MongoDB driver](https://github.com/mongodb/node-mongodb-native)?  Your help would be appreciated on this!

This probably isn't too hard to fix if it is indeed in Meteor, but Meteor passes most of its work on Mongo authentication off to the Node.  If it's a bug with the Node driver we should probably alert/help them with that and if it's already been fixed, then it'd be great to close this issue.

Please ping back when you have a second.  Thank you for opening this issue originally!

**Comment by hwillson** [comment] 2017-02-13 20:46
There hasn't been a follow up to the information requested in https://github.com/meteor/meteor/issues/7264#issuecomment-258802796, so as part of the on-going old issue cleanup process, I'll close this off. If this is still happening with a current version of Meteor, please post back and let us know. Thanks!

**Closed by hwillson** 2017-02-13 20:46 UTC
Labels: bug, Impact:few, Project:Mongo Driver, Severity:has-workaround
