### ISSUE TITLE
Client side bundling doesn't eliminate dead code in production

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6402] opened 2016-03-04 04:08 UTC
React has this pattern of writing:

``` js
if ("production" !== process.env.NODE_ENV) {
  // log warnings
}
```

Typically this code is eliminated by uglify when you bundle React. For whatever reason (the `process.env` symbol coming in some unusual way?) this doesn't happen when I run an app in `--production`. 

I'm not sure if this is a big deal, I just wanted to make a note of it. For more discussion see https://github.com/meteor/react-packages/pull/171

**Comment by zol** [comment] 2016-03-07 22:40
This optimization would be nice to revisit post 1.3

**Comment by jbaxleyiii** [comment] 2016-05-22 12:57
@zol @tmeasday is there any update on this? It has significantly increased our bundle size and is preventing us from moving to 1.3

**Comment by zol** [comment] 2016-05-23 17:16
@tmeasday - Do you know more about the scope of this issue? Are you sure it's uglify rather than webpack that does this dead code elimination?

**Comment by tmeasday** [comment] 2016-05-23 17:27
Not really. I just recall there's was a test on the `react-runtime` branch to check this worked properly.

**Comment by benjamn** [comment] 2016-05-23 17:43
This sounds like a case where you'd want to use something other than `standard-minifier-js`. Assuming `process.env.NODE_ENV` is a constant is not a sound decision for a generic minifier to make.

**Comment by jbaxleyiii** [comment] 2016-05-23 17:55
@benjamn just curious, why isn't that a sound decision?

**Comment by tmeasday** [comment] 2016-05-23 18:37
@benjamn I wonder how it worked once upon a time (Meteor 1.2)

**Comment by jbaxleyiii** [comment] 2016-05-24 00:14
@benjamn @tmeasday when does meteor load the node_modules needed for the app actually get run through the minifier plugin? I created a minifier but don't see where the bundled modules are passed to the minifer.

**Comment by jbaxleyiii** [comment] 2016-05-24 00:40
In case anyone is interested in a minifier that strips out dead code based on the environment: https://github.com/NewSpring/micro-minifer-js

Sadly, this hasn't fixed the bundle increase we have seen when moving off of the `webpack:webpack` package. 👎 I'm going to keep investigating to see why webpack's bundle size is ~1/2 the size of stock meteor. (From ~`300kb` using webpack to ~`600kb` using just 1.3)

**Comment by jbaxleyiii** [comment] 2016-07-21 01:54
@tmeasday with support for custom babel transforms this works great:

`babel-plugin-transform-dead-code-elimination` and `babel-plugin-transform-inline-environment-variables`

**Comment by tmeasday** [comment] 2016-07-21 01:59
@jbaxleyiii nice!

**Comment by hwillson** [comment] 2017-05-10 01:00
Hi all - this issue is really starting to come to the forefront, now that the React dev tools are showing when an app is using a development vs. production build of React. The React dev tools are showing that Meteor apps using React are using the development build of react, even though React is properly minified. 

(the following is a re-cap of my findings that I posted on the [forums](https://forums.meteor.com/t/new-react-devtools-check-if-your-production-build-is-really-in-production-mode/36199/10?u=hwillson) - sorry for double posting this content, but it is likely better suited here, so we can work towards a solution).

This problem is caused by the fact that React uses `if (process.env.NODE_ENV !== 'production') { ... }` checks throughout its code, and Meteor's `standard-minifier-js` package does not convert `process.node.NODE_ENV` references into the [`envify`](https://github.com/hughsk/envify) style of plain strings that React is expecting. So after minification, React expects `process.env.NODE_ENV !== 'production'` to become `'production' !== 'production'`. For example, making the following change in Meteor's [`packages/minifier-js/minifier.js`](https://github.com/meteor/meteor/blob/f0dd494c82244df79b544bdbf590ebecc0412189/packages/minifier-js/minifier.js) file demonstrates the issue:

```js
var uglify;

meteorJsMinify = function (source) {
  var result = {};
  uglify = uglify || Npm.require("uglify-js");

  // NOTE: This is intended to demonstrate the issue; this is not a proper fix!
  source = source.replace(/process\.env\.NODE_ENV/g, '"production"');

  try {
    result.code = uglify.minify(source, {
      fromString: true,
      compress: {
        drop_debugger: false,
        unused: false,
        dead_code: false
      }
    }).code;

  } catch (e) {
    // Although Babel.minify can handle a wider variety of ECMAScript
    // 2015+ syntax, it is substantially slower than UglifyJS, so we use
    // it only as a fallback.
    result.code = Babel.minify(source).code;
  }

  return result;
};
```

By adding that one `source = source.replace ...` line, we're replacing `process.env.NODE_ENV` references with `"production"` before minification, which then shows the React dev tools plugin that we're using a production build:

![screenshot 2017-05-09 20 36 39](https://cloud.githubusercontent.com/assets/137740/25878632/3dc5577e-34fa-11e7-8a22-323c4d817404.png)

(running locally with `--production`)

All of the above being said, a fix for this might not be best suited in the `standard-minifier-js` package, as @benjamn mentioned in https://github.com/meteor/meteor/issues/6402#issuecomment-221042378.

**Comment by macrozone** [comment] 2017-05-12 11:18
With the new bundle-size analyzer, i see that react-dom uses a whoping 180kb:

<img width="782" alt="bildschirmfoto 2017-05-12 um 13 11 57" src="https://cloud.githubusercontent.com/assets/1972353/25995945/f90ab2f6-3714-11e7-8b07-48fa0db0912e.png">

that is clearly more than it should be (see last comment here: http://stackoverflow.com/questions/39413855/webpack-why-react-dom-increase-size-in-about-150kb)

**Comment by hwillson** [comment] 2017-05-12 14:22
Hi @macrozone - that SO thread is a bit misleading. The absolute best we can hope for with a minified version of `react-dom` is what Facebook themselves offer. You can download a production ready copy from https://unpkg.com/react-dom@15.5.4/dist/react-dom.min.js directly and check the size - it comes in at around 125K. The smaller sizes being discussed in the SO post are after gzip compression has been applied; the `bundle-visualizer` is showing sizes before compression.

That being said, 125K is still better than the 180K you're seeing. The good news is that after applying the `process.env.NODE_ENV` hack I mentioned in https://github.com/meteor/meteor/issues/6402#issuecomment-300343883, and further updating [packages/minifier-js/minifier.js](https://github.com/meteor/meteor/blob/f0dd494c82244df79b544bdbf590ebecc0412189/packages/minifier-js/minifier.js) to flip `unused` to `true` and `dead_code` to `true`, the `react-dom` size comes down to the 125K.

![screenshot 2017-05-12 10 21 32](https://cloud.githubusercontent.com/assets/137740/26002185/da079864-36fc-11e7-83bc-3d57443bd84f.png)


Again, updating this standard minifier in this way might not be the best solution, so we definitely still need to come up with a way to handle this.

**Comment by hwillson** [comment] 2017-06-07 01:40
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Client%20side%20bundling%20doesn't%20eliminate%20dead%20code%20in%20production&body=Migrated%20from:%20meteor/meteor%236402) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-07 01:40 UTC
Labels: confirmed, feature, pull-requests-encouraged
