### ISSUE TITLE
Cordova plugins should be cached in ~/.meteor/cached-cordova-plugins

### ISSUE THREAD

**Issue by dotnetwise** [meteor/meteor#3992] opened 2015-03-21 22:22 UTC
Currently:

All the `cordova plugins` are being downloaded every single time the `meteor run` or `meteor build` commands are executed (if the local folder is missing).
Hence, since they are strictly versioned with the tarball hash, they should only be downloaded once per machine and then copied over in the referencing application.
(e.g. url//*tarball/0a1228236fea6d56f49c050f98f350b468d9d538*)

This would make `meteor run` and `meteor build` considerably faster, and not 100% dependent on the internet connection.

**Comment by stubailo** [comment] 2015-03-24 21:31
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by dotnetwise** [comment] 2015-03-31 08:15
This is not necessarily a feature, but an enhancement to make meteor run even faster!

**Comment by stubailo** [comment] 2015-03-31 14:53
@dotnetwise in terms of development prioritization, it makes sense that everything that is not a bug actively causing errors in someone's project is treated as a new feature, since it will have to be compared to other features when we are deciding what to work on next.

**Comment by boxxa** [comment] 2015-09-08 01:52
As Cordova support expands, this would be an awesome feature to move up the list. The redownload when you are building apps and running in simulator is pretty tough if you are doing work remote is a pain with no option to save.

**Comment by stubailo** [comment] 2015-09-10 18:10
@martijnwalraven what's the new status of this? I would suspect we don't redownload all of the plugins every time you build anymore.

**Comment by martijnwalraven** [comment] 2015-09-11 04:07
Indeed, we only reinstall plugins when there are changes (plugin added/removed or version changed), except for plugins loaded from the local filesystem, which we reinstall on every build (we have no exact version for those and this feature is meant for development).

Cordova now installs plugins from npm, so the usual npm caching mechanism is used. We no longer support installs from tarballs, but leave it to Cordova to download plugins from Git URLs. I don't believe those are currently cached, but that would be a feature request for Cordova.

**Comment by stubailo** [comment] 2015-09-11 04:26
Sounds like it's going to be fixed in Meteor 1.2 then!

**Closed by stubailo** 2015-09-11 04:26 UTC
Labels: feature, Project:Mobile

**Comment by Kostanos** [comment] 2016-02-29 23:06
Hi, if this issue is closed, can anyone explain how actually to cache the cordova plugins?

Thank you,

**Comment by martijnwalraven** [comment] 2016-03-01 05:16
@Kostanos: Caching plugins is the responsibility of Cordova, but that should happen at least for the ones downloaded from npm. See my comment from September 11 for more details.

**Comment by realyze** [comment] 2016-06-30 01:29
Hi guys, I don't know about you but I'm running Meteor 1.3 and it stills annoyingly downloads all Cordova plugins on every reload.

**Comment by softwarerero** [comment] 2016-12-21 16:40
I have the same problem with Meteor 1.4.2.3. I only use the camera and the webapp plugins and it takes 10-20 minutes to load the Cordova plugins.

**Comment by lanmower** [comment] 2018-04-11 11:15
I have the same problem still. We need a work around.
