### ISSUE TITLE
TypeError: port should be a number or string: null

### ISSUE THREAD

**Issue by Geekat-Manu** [meteor/meteor#7615] opened 2016-08-09 17:49 UTC
Hey,

Since this afternoon (I made the 1.4 update this morning), I got this error when I make a **meteor reset** :

```
As a precaution, meteor reset only clears the local database that is provided by meteor run for development. The database specified with MONGO_URL will NOT be reset.
C:\Users\Manu\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

TypeError: port should be a number or string: null
    at lookupAndConnect (net.js:942:13)
    at Socket.connect (net.js:921:5)
    at Object.exports.connect.exports.createConnection (net.js:69:35)
    at C:\tools\runners\run-mongo.js:280:24
    at findMongoPort (C:\tools\runners\run-mongo.js:279:12)
    at Command.func (C:\tools\cli\commands.js:1210:22)
    at C:\tools\cli\main.js:1410:23
```

Have you an idea about that ? Is this related to Meteor 1.4 ?

**Comment by realfresh** [comment] 2016-08-10 04:04
+1 same thing happening to me as well. I also cant start meteor without getting "Unexpected mongo exit code 14." Been using 1.4 for a decent bit and this hasn't happened so far.

**Comment by Geekat-Manu** [comment] 2016-08-16 09:24
I've update all my dependency (remove then re-add etc...), now this issue is fix !

**Comment by laosb** [comment] 2016-08-20 06:58
Sounds like fixed, please reopen if it happens again!

**Comment by MLescaudron** [comment] 2016-10-03 08:50
Same error on 1.4.2-beta.6

**Comment by abernix** [comment] 2016-10-04 11:54
@MLescaudron In your project directory, what are the contents of the `.meteor/local/db/METEOR-PORT` file?

**Comment by MLescaudron** [comment] 2016-10-04 13:37
I don't have any db folders. I'm working with meteor & angular + ionic
https://i.gyazo.com/a87104d39942a67eafb5bcbdde1f468b.png

**Comment by abernix** [comment] 2016-10-04 14:37
@MLescaudron What is the exact error that you are receiving?  (With full stack trace).  If you don't have a `db` folder then you must be using your own MongoDB database, right?  If so, what is your `MONGO_URL` set to? (For security, please modify any hosts/password, but keep it as close as possible to properly assist)

**Comment by MLescaudron** [comment] 2016-10-04 14:47
In my DB path, I don't have any METEOR-PORT file

**Comment by abernix** [comment] 2016-10-04 16:26
@MLescaudron You did not answer any of the questions that I asked.

**Comment by MLescaudron** [comment] 2016-10-05 11:26
mongodb://127.0.0.1:27017/db-dev

**Comment by yawlhead91** [comment] 2016-10-25 19:40
+1 Same issue

**Comment by raza2022** [comment] 2016-11-01 10:14
same issue any update.
Note: i am using 27107/custom_database

**Comment by abernix** [comment] 2016-11-01 10:18
@raza2022 What is the complete value of `MONGO_URL` that you're using?

On Windows in Command Prompt, you can get this with `echo %MONGO_URL%` and on Unix with `echo $MONGO_URL`.

@yawlhead91 Same question for you!

**Comment by raza2022** [comment] 2016-11-01 10:23
actually i set my mongo db in package.json with npm start
```
"scripts": {
    "start": "SET MONGO_URL=mongodb://localhost:27017/custom&& meteor -p 3000",
    "test":  "meteor reset"
  },
```
`npm start` correctly start the meteor project with my custom database, but the issue about meteor reset which not event with simple meteor reset in shell

**Comment by BogdanBucsa** [comment] 2016-11-21 09:04
Any news on this?

**Comment by abernix** [comment] 2016-11-21 09:53
@BogdanBucsa In your project, do you have a `.meteor/local/db` directory?  And if so, do you have a `METEOR-PORT` file inside that directory? (i.e. `/path/to/your/app/.meteor/local/db/METEOR-PORT`)

**Comment by BogdanBucsa** [comment] 2016-11-21 09:59
@abernix Hello!
I didn't. The folder was empty. But created the file and edit it with 3001.
Now i can run the reset, but the app hangs on Starting your app.... :) (which was the cause i ran meteor reset)

**Comment by abernix** [comment] 2016-11-21 10:05
@BogdanBucsa, do you have `MONGO_URL` set in your environment?

**Comment by BogdanBucsa** [comment] 2016-11-21 10:06
@abernix No I use the db meteor provides.

**Comment by abernix** [comment] 2016-11-21 10:15
What version of Meteor are you using (`meteor --version`)?  What version of Windows (`systeminfo | findstr /C:"OS"`)?  And What command prompt (e.g. PowerShell, Command Prompt cmd.exe, Ubuntu Bash, etc.).

Also, you can just (recursively) remove the `.meteor/local` directory in your project directory to accomplish the same thing as `meteor reset`.   Please try that and see if it helps.

**Comment by BogdanBucsa** [comment] 2016-11-21 10:53
Meteor 1.4.1.1, 

Cmd, git cmd (bash)
OS Name:                   Microsoft Windows 7 Professional
OS Version:                6.1.7601 Service Pack 1 Build 7601

Tahnk you! Will try.

**Comment by raza2022** [comment] 2016-11-22 09:26
any update on it (actually i just want run meteor reset command with my local db)

**Comment by abernix** [comment] 2016-11-22 15:41
If you've removed your `.meteor/local` directory, you've done the same thing as `meteor reset` does.  I'll leave this open as I think there may be a bug here, but I haven't been able to reproduce it yet.

**Comment by hwillson** [comment] 2017-02-27 20:03
Hi all - without a runnable reproduction demonstrating this issue, this is a difficult one to troubleshoot. If anyone here is able to provide a repro, that would definitely help with troubleshooting (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more info). For now though, since there hasn't been any traction on this in issue in a few months (and since there isn't an easy way to reproduce it), I'll close it off. If anyone it still running into this problem with a recent version of Meteor (1.4.3.1 is the latest as of February 13th, 2017), please post back and we'll re-open. Thanks for reporting this originally!

**Closed by hwillson** 2017-02-27 20:03 UTC
Labels: bug, can't-reproduce
