### ISSUE TITLE
New $v field in Mongo 3.6 oplog breaks OplogObserveDriver

### ISSUE THREAD

**Issue by benweissmann** [meteor/meteor#9623] opened 2018-02-01 20:26 UTC
Reproduction: https://github.com/benweissmann/mongo36meteorbug

Mongo 3.6 adds a new `$v` field to the `o` and `o2` fields of oplog records. This might be removed in the future (https://jira.mongodb.org/browse/SERVER-32240), but for now, it causes the OplogObserveDriver's calls to LocalCollection._modify to fail. In most cases, this is caught by the OplogObserveDriver, which then re-loads the document from the database, so it's not immediately visible. However, it's a substantial performance regression, and there are some cases in the main app that I work on where it doesn't catch the error, and causes incorrect behavior (I have not been able to reproduce this case, but the reproduction above shows the re-fetch behavior when you add breakpoints or watch the mongo logs).

I have implemented a questionable workaround: https://github.com/benweissmann/mongo36meteorbug/blob/master/server/main.js#L6, but I think a fix should make its way to the upstream OplogObserveDriver.

This occurs on (at least) Meteor 1.6.1 and 1.4.4.1, on MacOS, although I'd guess it occurs on all operating systems on all reasonable recent versions of Meteor.

**Comment by benjamn** [comment] 2018-02-01 21:53
Please pardon my ignorance, but do you happen to understand what this `$v` field does, or why it was added? Would it be enough to add an empty `$v` method to the `MODIFIERS` object [here](https://github.com/meteor/meteor/blob/9daf412b2b7f69c068319ba3f9762817f210eea1/packages/minimongo/local_collection.js#L1448), since that seems to be the source of the problem in `LocalCollection._modify` [here](https://github.com/meteor/meteor/blob/9daf412b2b7f69c068319ba3f9762817f210eea1/packages/minimongo/local_collection.js#L1135-L1139)?

**Comment by benweissmann** [comment] 2018-02-01 22:40
My understanding (from my reading of this ticket: https://jira.mongodb.org/browse/SERVER-32240) is that is was added so that Mongo can independently version the update language (with version indicated as `o.$v`) separately from the oplog record format (with version indicated as the top-level `v` field). My guess is that is was added to facilitate in-place upgrades of Mongo clusters, which I think is something Mongo has been focusing on (as evidenced by their introduction of `featureCompatibilityVersion`).

I agree that adding a no-op `$v` method to `MODIFIERS` should fix that and is definitely cleaner than what I'm doing in my workaround -- I just don't have a Meteor dev env set up, so the workaround I implemented allowed me to test a potential fix via a monkey-patch rather than a fork.

Any idea what the likelihood is that this bug is the root of the Mongo 3.6 issues you've been seeing? I saw that there was an upgrade to 3.6 followed by a rollback. I'm currently looking at re-rolling my Mongo cluster in the next ~4 weeks to move from Atlas to Cloud Manager, and I'm trying to decide whether to use 3.4 or 3.6.

**Comment by hwillson** [comment] 2018-02-02 00:56
> Any idea what the likelihood is that this bug is the root of the Mongo 3.6 issues you've been seeing?

I'm working on the Mongo 3.6 issues, and this doesn't appear to relate to the main issue we're having (although I wish it did!). Right now we're seeing test failures that appear to be caused by Mongo query differences between Mongo 3.4.x and 3.6.x. I'm still debugging, but I should have a new Mongo 3.6 PR ready shortly. 

This is great to know though @benweissmann, so thanks for sharing! I can incorporate a fix for this into the same PR.

**Comment by hwillson** [comment] 2018-02-02 13:15
Quick update on my last https://github.com/meteor/meteor/issues/9623#issuecomment-362452086 - the issue we're seeing isn't related to query differences; it's being caused by the fact that Mongo 3.6 has deprecated the option to disable journaling. We've had to enable Mongo journaling with the Meteor Tool, which has slowed down certain operations, and has impacted the timing of certain tests. The good news is that the timing differences aren't that bad - I'll put more details about this in a forthcoming PR.

**Comment by hwillson** [comment] 2018-02-02 18:53
PR https://github.com/meteor/meteor/pull/9632 includes a fix for this (and I've verified it works using the provided repro).

**Comment by zvictor** [comment] 2018-02-07 14:59
I couldn't wait for the support, so I created a patch for it.

```
meteor add quadric:mongo-3.6-patch
```

please let me know if you find errors on it.

**Comment by benlavalley** [comment] 2018-02-24 22:56
Mongo-connector from mongo-labs ran into this (tails oplog like Meteor), figured I'd link their solution as it might help and have additional background information [here](https://github.com/mongodb-labs/mongo-connector/pull/781).

The Mongo team also has removal of $v from the oplog entries as a [ticket](https://jira.mongodb.org/browse/SERVER-32240).

**Comment by abernix** [comment] 2018-03-23 16:58
I believe the `minimongo` aspect of this error should be fixed with the release of `minimongo@1.4.4`, thanks to part of the changes from #9533 being published (though the more complete support for Mongo 3.6, including in development, will be in Meteor 1.6.2).

Does that sound correct, @hwillson?

**Comment by hwillson** [comment] 2018-03-23 18:14
Definitely correct @abernix - thanks!

**Closed by hwillson** 2018-03-23 18:14 UTC
Labels: Impact:some, Project:Mongo Driver, Severity:production, bug, confirmed

**Comment by hridayeshgupta** [comment] 2018-10-11 08:11
we are also hitting on this issue, and while searching I checked this thread.
Currently we are using Meteor 1.6.1 which uses minimongo 1.4.3. I know this fix is in minimongo 1.4.4. I am unable to find which meteor version includes this fix. can any please guide me for the same.
Thanks
