### ISSUE TITLE
Download failure: Error parsing asset manifest

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#6782] opened 2016-04-11 13:17 UTC
meteor 1.3.1
osx 10.11.4

	Download failure: Error parsing asset manifest: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
	2016-04-11 20:58:14.526 cube[1276:593075] ERROR: {"line":36,"column":30,"sourceURL":"http://localhost:12776/plugins/cordova-plugin-meteor-webapp/www/webapp_local_server.js"}

    meteor run ios-device --mobile-server=http://ourdomain.com

mobile-config

    App.accessRule('*', true);

**Comment by martijnwalraven** [comment] 2016-04-12 01:53
Does `https://http://ourdomain.com/__cordova/manifest.json` actually serve the manifest? I suspect the server may not be serving the Cordova bundle that is needed for hot code push.

How are you building and deploying the server bundle?

**Comment by DanielDornhardt** [comment] 2016-04-27 10:53
Hello, a connected question maybe: For local development it seems to be required to add one of the 

`meteor run <target-platform>` - parameters to indicate a cordova target to get the app to serve the "cordova bundle" as you call it.

That means that we have to build a new version of our app each time we want to start developing. Wouldn't it be possible that the parameter --mobile-server which is required anyway for local serving of existing cordova apps would toggle the serving of the "cordova bundle"?

Or is there another way to start serving the "cordova bundle" in development without having to build a new app each time?

**Comment by wojtkowiak** [comment] 2016-04-27 20:31
@DanielDornhardt check https://github.com/meteor/meteor/issues/6862

**Comment by martijnwalraven** [comment] 2016-04-28 15:55
Closing this, because it seems the cause has been identified.

**Closed by martijnwalraven** 2016-04-28 15:55 UTC
Labels: Project:Mobile

**Comment by aqib1604** [comment] 2016-11-11 13:43
@martijndeh  In my case I am able to run through meteor run --mobile-server and when I build It gets succeed. But I am not able to run that build got following error.

```
Download failure: Error parsing asset manifest: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
2016-11-11 18:52:43.673 Test[14808:667960] ERROR: {"line":36,"column":30,"sourceURL":"http://localhost:12936/plugins/cordova-plugin-meteor-webapp/www/webapp_local_server.js"}
```

**Comment by martijndeh** [comment] 2016-11-11 20:57
@aqib1604 I think you mean @martijnwalraven.
