### ISSUE TITLE
Keyup event on entire document can't be listened to

### ISSUE THREAD

**Issue by woniesong92** [meteor/meteor#4650] opened 2015-06-29 15:00 UTC
Meteor 1.1.0.2

```
if (Meteor.isClient) {
  Template.someTemplate.events({
    'keyup': function (e, template) {
      // I am not fired
    }
  })
}
```

Can you confirm if this is a bug?

**Comment by robertpitt** [comment] 2015-06-29 15:20
See: #2024

**Comment by stubailo** [comment] 2015-06-29 20:35
Closed as duplicate of the above

**Closed by stubailo** 2015-06-29 20:35 UTC
