### ISSUE TITLE
[1.3.2.4] ecmascript incompatible with tap:i18n

### ISSUE THREAD

**Issue by danlg** [meteor/meteor#6941] opened 2016-04-29 09:59 UTC
Seem a related issue with 

> The spacebar '_' helper does not work anymore with Meteor 1.3.2.4
> https://github.com/TAPevents/tap-i18n/issues/163 

But it seems that the root cause is more with ecmascript or module import.

ecmascript@0.4.2, ecmascript-runtime@0.2.9 works (provided by meteor 1.3.1)
ecmascript@0.4.3, ecmascript-runtime@0.2.10 doesn't work (provided by meteor 1.3.2.4)

Using Meteor 1.3.1 works fine. This prevent us to use 1.3.2.4 which contains great features such as lazy loading... @benjamn Thanks for you help

**Comment by abernix** [comment] 2016-04-29 11:56
Hey @danlg,

Hmm, I know that `tap-i18n` does in fact work fine with 1.3.2.4, so it must be something a bit more complicated than that.

Could you please make a very basic sample reproduction of your problem in a new Meteor project (just a very small example) and upload that test project to GitHub?.  Someone will be much more likely to help you if you include this.  Unfortunately, without this it's very difficult.

**Comment by StorytellerCZ** [comment] 2016-04-29 19:06
Could this be related to #6919?

**Comment by juliomac** [comment] 2016-04-30 19:04
I think there's more to it. 


It works for me on all browsers running Meteor release [1.3.2.4] on '''localhost:3000'''
It works for me on all browsers running Meteor release [1.3.2.4] directly on my application at [libertas.saasmart.com.br](url)

But the intend use of this application is to be embeded inside an iframe. 

Inside an iframe, it only works for me now on Safari (release[1.3.2.4]) . See embedded on page at [clan.netlify.com](url) . On both Chrome and Firefox, it gives error '''Uncaught Error: No such function: _''' and the frame does not show up.

I had my app working fine on all browsers inside an iframe or not on Meteor release [1.2.1]. I have an older version  that can be seen working well in production at [www.markshotel.com.br](url). However, I develop on Safari browser and made many additions to the app to be released at an upcoming version, including the addition of cfs:standard-packages, cfs:gridfs and cfs:ui packages .

I was starting the work on my migration to 1.3, I noticed my 1.2 version wasn't working anymore inside an iframe on Chrome and Firefox. So the issue was already happening on Meteor 1.2.1 The main difference being the addition of those packages. Decided to continue migration as it could be fixed just with updating the packages. However that was not solved.

In SUMMARY:

|                      | No-iframe (All) | iframe Safari |  iframe Chrome/Firefox served on Heroku/Galaxy | iframe Chrome/Firefox      Meteor localhost |
|----------------------|-----------------|---------------|------------------------------------------------|---------------------------------------------|
| Meteor 1.2.1         |        OK       |       OK      |                       OK                       |                      OK                     |
| Meteor 1.2.1 + cfs+? |        OK       |       OK      |               No such function:_               |                      OK                     |
| Meteor 1.3.2.4       |        OK       |       OK      |               No such function:_               |                      OK                     |

Because of this other variables, I suspect it may not be directly attributed to Meteor upgrade.

**Comment by laosb** [comment] 2016-05-07 14:28
@juliomac So everything is going well and we can close this?

**Comment by juliomac** [comment] 2016-05-07 19:56
Hi @laosb ! For me, yes, we can close.

**Comment by laosb** [comment] 2016-05-08 00:33
I'll still leave this open as @danlg haven't come up with a repro.

**Comment by chongwang87** [comment] 2016-05-11 04:37
reference to https://github.com/TAPevents/tap-i18n/issues/163 @LionelGuerin repro
Broken : https://github.com/LionelGuerin/testTAP.git
Fixed : https://github.com/LionelGuerin/testTAP/tree/patch
fix only translations are out of the package folders

**Comment by chongwang87** [comment] 2016-05-13 09:05
i created a simple repro of the issue https://github.com/chongwang87/testTAP meteor 1.3.2.4 with tap-i18n 1.8.0

the languages file packages/lib/i18n/en.i18n.json didn't work. 
if move packages/lib/i18n to i18n (root), then it'll works.

**Comment by chongwang87** [comment] 2016-05-14 14:47
@juliomac have you try to include tap-i18n and translation file in package?

**Comment by stewiegaribaldi** [comment] 2016-06-29 17:27
I have same issue, having both packages: ecmascript & tap:i18n and defining {{_ "TranslateMe}} throws error Error: No such function: _. Any workaround?

**Comment by aboire** [comment] 2016-06-30 05:23
I use the version 1.3.4_1 all packages updated and it works without any worries. Is using modules?

**Comment by lucendio** [comment] 2016-08-16 23:24
I think, it might be save to say, that the reason is hidden in the new build process, which is the fundament for the `modules` package. since 1.3.x the `ecmascript` package implies the `modules` package, so if you are still using `ecmascript` in your package but not explicitly requiring `modules`, you package still get's build the new way.
When I am leaving out `ecmascript`, the part from tap:i18n, [that pulls in the language files ](https://github.com/TAPevents/tap-i18n/blob/63c1ca957c27c86bc93c6075224f8b3e74f8cddb/lib/plugin/compilers/i18n.generic_compiler.coffee#L27) can be found in `meteor/local/build/programs/[platform]/packages/[pkg which depends on tap:i18n].js` (also the content of `.meteor/isopacks/[your pkg that depends on tap:i18n]/os/packages/[pkg which depends on tap:i18n]/packages/[your pkg that depends on tap:i18n]i18n/LANG.i18n.json`). But if the package depends on `ecmascript`, the mentioned part is not in the build result of that package.

maybe @benjamn might has an idea on that
/cc @theosp

side note: we are using `tap:i18n` in a lot of projects and it blocks us from upgrading to 1.3 and above

**Comment by theosp** [comment] 2016-08-17 04:51
Hi @lucendio ,

I am actually in the same situation. The effort I need to put in order to migrate existing projects to v1.3 and above is so big that I just can't do it. 

My solution at the moment is to maintain my own Meteor fork with security updates and improved features but without es6 and without the changes to the packaging system introduced in v1.2 .

I am curious though, what are the features you need from v1.3 that incentives you to upgrade?

I wish I could help you more,
-Daniel

**Comment by lucendio** [comment] 2016-08-17 08:54
Hi @theosp ,

we have a bunch of meteor projects and packages, not just one. Currently we are in a middle of a major refactoring process. Hence we are upgrading all of them and starting to use ES6 and modules.
Going down the road of a fork isn't an option for use, because as I said we are working on a couple of projects - a fork is a bad dependency in the long run.

I started to have a deeper look into your package. My guess is, switching to the new [BuildPlugin API](https://docs.meteor.com/api/packagejs.html#build-plugin-api) might fix the problem. Although this bug seems to be originated in meteors new build process, because we had no new major release, the old API should work fine.
I might going to upgrade the builder in your package, but therefore I have to drop the coffee dependency, otherwise I have to put to much cognitive effort into this work.

Anyway, I would still appreciate a look into this issue from the side of MDG.

**Comment by theosp** [comment] 2016-08-17 09:08
Alright,

Make sure checking this attempt to rewrite tap:i18n : https://github.com/TAPevents/tap-i18n/pull/135 perhaps they are advanced enough there (it is a massive work, so I had no time to learn it) - let me know your opinion if you take that path - perhaps we can come up with v2 for tap-i18n based on this work.

I agree that for the long run, having to maintain your own fork is a bad dependency - I'll switch when the benefit will outweigh the effort required (that's why I was curious about the benefits you find in the new version, as I didn't see yet any killer feature that I fill I have to switch for).

**Comment by helfer** [comment] 2016-08-26 07:29
@theosp while 1.3 may not have any features that you absolutely want, 1.4 has upgrades to node and mongoDB. Considering that Node.js is going to stop supporting 0.10 and 0.12 by the end of the year, I think that's a pretty good reason to upgrade.

Also note that you don't actually have to rewrite your app. All the changes are in theory backwards compatible, but there may be some packages that break for weird reasons that need to be updated. I think getting those packages to work with 1.3 and 1.4 will be a lot easier than trying to apply security patches to a fork.

**Comment by helfer** [comment] 2016-08-26 07:32
As for the issue with this specific package, someone from MDG will definitely look into it as soon as someone can make a minimal reproduction.

**Comment by theosp** [comment] 2016-08-26 07:50
Alright, thanks for the comment @helfer .

**Comment by lucendio** [comment] 2016-09-05 02:04
okay, I made the upgrade to the newer version of the Build Plugin API and opened up a PR (https://github.com/TAPevents/tap-i18n/pull/185). I have to apologize in advance, because I might have found myself ending up in rewriting the whole package (because off coffeescript). It is by fare not perfect, but now it wont block us from upgrading to meteor anymore, so we are going to start using it in production.
But please, feel free to take a look - all kind of feedback would be much appreciated.

**Comment by hwillson** [comment] 2017-02-03 16:51
There are a few different things happening in this thread, but with regards to the original issue, we still haven't received a small runnable reproduction demonstrating the problem. As such, the time has come to close this issue. If anyone is still having this problem and can supply a small reproduction to help with troubleshooting, please post back and we'll re-open. Thanks very much for posting this issue originally!

**Closed by hwillson** 2017-02-03 16:51 UTC
Labels: bug, Impact:few, Project:Imported Packages
