### ISSUE TITLE
`echo 1+1 | meteor shell` should print "2"

### ISSUE THREAD

**Issue by avital** [meteor/meteor#5055] opened 2015-08-28 15:37 UTC
This makes it very hard to use `meteor shell` for scripting.

```
$ meteor &

$ echo | meteor shell

Welcome to the server-side interactive shell!

Tab completion is enabled for global variables.

Type .reload to restart the server and the shell.
Type .exit to disconnect from the server and leave the shell.
Type .help for additional help.


/Users/avital/.meteor/packages/meteor-tool/.1.1.4.1k57gpn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/shell-client.js:106
    process.stdin.setRawMode(true);
                  ^
TypeError: Object #<Socket> has no method 'setRawMode'
    at Socket.onConnect (/Users/avital/.meteor/packages/meteor-tool/.1.1.4.1k57gpn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/shell-client.js:106:19)
    at Socket.emit (events.js:117:20)
    at Object.afterConnect [as oncomplete] (net.js:887:10)
```

**Comment by avital** [comment] 2015-09-09 02:14
#5056 improves things by eliminating the `setRawMode` exception, but it's still hard to use `meteor shell` in a shell script for two reasons (at least):
1. It takes time for the shell to start, so you have to wait before sending output into `meteor shell`.
2. `meteor shell` only exits once you send it `.exit`, and you have to wait until your command is done before doing that.

Ideally, you should be able to just do `echo 1+1 | meteor shell` and see "2".

**Comment by benjamn** [comment] 2015-09-10 16:59
I spent some time yesterday working on a branch implementing the ideal behavior, if you want to check it out: https://github.com/meteor/meteor/tree/pipe-to-meteor-shell

**Comment by abernix** [comment] 2016-05-23 15:01
Shouldn't this work exactly the same as the Node REPL?  You wouldn't be able to `echo 1+1 | meteor shell`, but you could do `echo 'console.log(1+1);' | meteor shell`.

Currently in node:
```sh
$ echo 'console.log(1+1);' | node
2
```

Issue-topic-wise though, this seems to be a duplicate of #3927.

**Comment by piotrekfracek** [comment] 2016-07-15 14:38
What about this feature? Is it working?

**Comment by benjamn** [comment] 2016-07-15 15:27
This is working for me: `echo 1+1 | meteor shell` works just like `echo 1+1 | node --print`

**Closed by benjamn** 2016-07-15 15:27 UTC
Labels: Project:Tool:Shell
