### ISSUE TITLE
Pretty stacktrace in method error

### ISSUE THREAD

**Issue by JWo1F** [meteor/meteor#7679] opened 2016-08-20 11:44 UTC
When I throw an error in the method I see an error message (and a stack trace) in the console like this:

```
Exception while invoking method 'polls@stats' { stack: 'TypeError: Cannot read property \'NxdNNaLS7G4HX3t9K\' of undefined\n    at Object.Future.wait (/home/alex/.meteor/packages/meteor-tool/.1.4.1.1eum391++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)\n    at [object Object].stats (packages/op:polls/stats/methods.js:15:36)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)\n    at packages/ddp-server/livedata_server.js:711:19\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at packages/ddp-server/livedata_server.js:709:40\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at packages/ddp-server/livedata_server.js:707:46\n    at Session.method (packages/ddp-server/livedata_server.js:681:23)\n    - - - - -\n    at packages/op:polls/stats/finalizers.js:53:28\n    at Array.map (native)\n    at packages/op:polls/stats/finalizers.js:52:36\n    at packages/op:polls/stats/finalizers.js:49:15\n    at /home/alex/.meteor/packages/meteor-tool/.1.4.1.1eum391++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:467:21', source: 'method' }
```

It's really not readable. I think, we need to make it more pretty. What do you think?

**Comment by abernix** [comment] 2016-09-26 14:09
You'll need to provide a reproduction of this problem because this is not the behavior I have experienced.

For me, when an error is thrown within a method on the server, the error printed on the server console is neatly formatted and shows the stack trace properly:

```
I20160926-17:03:18.560(3)? Exception while invoking method 'blah' Error: haha
I20160926-17:03:18.560(3)?     at [object Object].blah (imports/blahMethods.js:39:11)
I20160926-17:03:18.560(3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
...snip...
```

On the client, the error is sanitized to a generic 500 error (for security purposes) and comes through as:
```
errorClass {error: 500, reason: "Internal server error", details: undefined, message: "Internal server error [500]", errorType: "Meteor.Error"}
```

@laosb You marked this as a Feature.  Is that because you experience the same problem?

**Comment by abernix** [comment] 2016-10-25 11:33
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details  that are helpful in resolving it.  Please consult [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines for what is expected.  Thanks! :)

**Comment by brucejo75** [comment] 2017-03-30 02:20
Hi @abernix, I have been seeing this a lot also.  I narrowed down a repro case here: https://github.com/brucejo75/meteor-7679

The problem easily reproduces when `meteorhacks:kadira` is included in the project.  Take out `meteorhacks:kadira` and the problem disappears.

Can the bug be reopened?  Thanks!

**Comment by abernix** [comment] 2017-03-30 16:17
@brucejo75 Absolutely, the only reason for closing was the lack of reproduction.  Thank you for the excellent reproduction.

I'll reopen this, but the bug most likely lies in `meteorhacks:kadira` – it's fairly easy to munge a stack trace since it often involves manual string parsing, but [any of these places](https://github.com/meteorhacks/kadira/search?utf8=%E2%9C%93&q=stacks&type=) are starting points.  Cloning the package into a local project would be the best way to start debugging.

Let me know if I can help.

**Comment by brucejo75** [comment] 2017-03-31 02:42
Thanks @abernix 

I found the problem code and I built a [pull request](https://github.com/meteorhacks/kadira/pull/258).  

I cannot figure out how to run the kadira tests, I am failing 3-4 of them.  I am unfamiliar with tiny-test. Can you point me?

Thank, Bruce

**Comment by hwillson** [comment] 2017-03-31 10:10
Hi @brucejo75 - thanks for tracking down the issue! Just a heads up - I have a feeling PR's to Kadira won't be accepted anytime soon, since the product is currently in transition over to MDG (and the last PR accepted via the Kadira repo was in Oct. 2016). I'm not sure what MDG's future "Kadira" product will look like, but I just thought I'd give you a heads up so you aren't waiting for that PR to be accepted. You might want to be prepared to run with your own forked version with your fix.

Regardless, since this issue has been fixed (and it isn't an issue with Meter itself), are we okay to close this issue again? Thanks!

**Comment by abernix** [comment] 2017-03-31 10:41
@brucejo75 Thank you so much for looking into it.

I agree with @hwillson that the correct solution for now will be to keep a local package (or publish your own) with the fix.  That said, MDG will be considering any open PRs on that repo as we fork and integrate it, however I don't have a timeline for exactly when that will happen (though it will certainly be more near-term rather than sitting indefinitely).  Your PR looks like it will certainly need to be looked at as part of that process, but agree that this is not a bug with Meteor and we should be okay to close this (please close if you agree).

To run the tests locally, you _should_ be able to just run the following within the package directory:

    meteor test-packages

Though it seems they're doing some [more obscure things](https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh).  These may have been necessary on older versions of Meteor – you can see they're using `meteorite` still.

**Comment by brucejo75** [comment] 2017-03-31 19:39
@abernix, @hwillson,  That seems reasonable.  I put the [issue](https://github.com/meteorhacks/kadira/issues/259) in Kadira, hopefully it will not get lost in the MDG transition.
**Note**: I cannot close this bug, I didn't open it.

Essentially, Kadira was intercepting the exception.  They [modified it](https://github.com/meteorhacks/kadira/blob/master/lib/hijack/wrap_session.js#L178) and [forwarded the modified version on](https://github.com/meteorhacks/kadira/blob/master/lib/hijack/wrap_session.js#L181).  

I think they meant to modify a copy for themselves and forward the unmodified exception on.  That seemed to work for the exception types I was able to test for.  But I did not account for other exception types well enough and the tests are failing.  I am running in windows so I cannot really run their tests as-is.

I will revisit once MDG starts managing the code base. (or maybe someone will just fix it :-)

**Closed** 2017-04-01 20:17 UTC
Labels: bug, confirmed, Impact:few, Project:Imported Packages
