### ISSUE TITLE
1.7-beta.22: MongoError: database name must be a string

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#9827] opened 2018-04-19 09:04 UTC
Getting this error with 1.7-beta.22. Even after a meteor reset.
Probably related to upgrading the mongo driver to v3. Ping @klaussner 
```
W20180419-11:00:47.787(2)? (STDERR) MongoError: database name must be a string
W20180419-11:00:47.787(2)? (STDERR)     at Function.MongoError.create (/home/seba/.meteor/packages/npm-mongo/.2.2.34.1t0ofc9.mme3++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
W20180419-11:00:47.787(2)? (STDERR)     at validateDatabaseName (/home/seba/.meteor/packages/npm-mongo/.2.2.34.1t0ofc9.mme3++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/db.js:1680:57)
W20180419-11:00:47.787(2)? (STDERR)     at new Db (/home/seba/.meteor/packages/npm-mongo/.2.2.34.1t0ofc9.mme3++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/db.js:156:3)
W20180419-11:00:47.788(2)? (STDERR)     at Db.db (/home/seba/.meteor/packages/npm-mongo/.2.2.34.1t0ofc9.mme3++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/db.js:1208:12)
W20180419-11:00:47.788(2)? (STDERR)     at packages/mongo/mongo_driver.js:180:25
W20180419-11:00:47.788(2)? (STDERR)     at runWithEnvironment (packages/meteor.js:1241:24)
```

**Comment by jorisroling** [comment] 2018-04-19 09:42
+1

**Comment by klaussner** [comment] 2018-04-19 10:06
I could reproduce the error with:

```
meteor create --full --release 1.7-beta.22 issue-9827
cd issue-9827
meteor
```

But it worked when I ran Meteor from a checkout ([this commit](https://github.com/meteor/meteor/commit/5189713d01ac32bb5e2f57078ed6ffaa558685f5) on the `release-1.7` branch). :thinking:

**Comment by thhoang99** [comment] 2018-04-19 12:16
+1

**Comment by jeffreyflynt** [comment] 2018-04-19 13:56
I am getting this issue as well.

**Comment by benjamn** [comment] 2018-04-19 14:17
Yep, this is super reproducible! Fix coming in `1.7-beta.23` 🤞

**Comment by benjamn** [comment] 2018-04-19 15:43
Ok, this should be fixed in `1.7-beta.23`. Happy to reopen if `meteor update --release 1.7-beta.23` doesn't fix this.

**Closed by benjamn** 2018-04-19 15:43 UTC
Labels: Project:Mongo Driver, bug, confirmed, in progress, known-fix

**Comment by klaussner** [comment] 2018-04-20 14:08
I think the problem is that I didn't bump the version number of the `npm-mongo` package in #9790. A new `1.7-beta.22` (or `1.7-beta.23`!) project uses `npm-mongo@2.2.34`, which is the old driver version. [This commit](https://github.com/meteor/meteor/commit/567e620a867a5e34188024d3175d4cc9dedaff3b) (in the `1.7-beta.23` release) fixes the `database name must be a string` error by using the `databaseName` property, but this only works because `client` is actually a `Db` object if the old driver is used. In the new 3.x driver, `client.s.databaseName` should always be `undefined`.

I fixed the version number in #9831.

**Comment by dhamaniasad** [comment] 2018-05-22 16:46
I'm also seeing this issue in the `1.6.2` beta due to the `2.2.34` npm-mongo package

**Comment by sebakerckhof** [comment] 2018-05-22 19:05
@dhamaniasad . This issue has been closed already. `1.6.2` beta is replaced by `1.7.0` and you should make sure you have the latest version of the npm-mongo package, which solves this issue.
