### ISSUE TITLE
Facebook permissions not requested again if user uncheck a permission

### ISSUE THREAD

**Issue by sahanDissanayake** [meteor/meteor#7078] opened 2016-05-18 13:20 UTC
Hi There

This is how I ask for permission in my code

```
Meteor.loginWithFacebook({
      requestPermissions: ['public_profile', 'email']
    }, (err) => {
      if (err) {
        (err)
        // handle error
      } else {

      }
    });
```

Lets say the user is just wanna break the system and UNCHECK the email from the Facebook modal, which will in return will not send the email from the Graph api.

So, this is an issue, My feature request is so that if a user does remove permissions and if I do the following again
```
Meteor.loginWithFacebook({
      requestPermissions: ['public_profile', 'email']
    }, (err) => {
      if (err) {
        (err)
        // handle error
      } else {

      }
    });
```
 then the accounts-facebook should ask for the missing permission from the graph api

**Comment by abernix** [comment] 2016-10-14 13:54
This is the way the Facebook oAuth API behaves and this is already supported.  If you check the Facebook documentation you'll see two sections:

* [Manually Building a Login Flow](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow) which indicates that you'll need to specify an `auth_type` of `rerequest`.
* [Reauthentication](https://developers.facebook.com/docs/facebook-login/reauthentication), which I believe is a more extreme version of the previous option, involving an `auth_type` of `reauthenticate`

You can pass these options as the first parameter to:  `Meteor.loginWithFacebook` and it should just work.

I'm going to close this because it should work, but please @mention me for a reopen if you find that it does not work.  But please provide a reproduction which has `auth_type: "rerequest"` set.

Also, I'll update the documentation. :smile:

**Comment by abernix** [comment] 2016-10-14 14:28
Whoops.  Re-opening because I just realized that the [Meteor Facebook code is passing `authType` instead of `auth_type`](https://github.com/meteor/meteor/blob/9a85f0cbb369dea10110cc9f33d3ddedc8b38a8f/packages/facebook/facebook_client.js#L40-L42)!

So, it won't work right now.  I'll submit a PR to fix that.

**Closed** 2016-10-15 00:39 UTC
Labels: bug, confirmed, Impact:some, Project:Accounts:OAuth

**Comment by jirikrepl** [comment] 2020-05-01 19:15
I think that doing only this call once If, a user declined to share some information is enough.

```
Meteor.loginWithFacebook({
    auth_type: 'rerequest',
    requestPermissions: ['public_profile', 'email'],
}, (err) => {
    if (err) { throw new Meteor.Error(`Facebook login failed, error message: ${err.message}`); }
});
```

I read this Facebook docs page https://developers.facebook.com/docs/facebook-login/handling-declined-permissions#reprompt 

I think that `auth_type: 'rerequest'` works first but after the first `loginWithFacebook` call Meteor app needs to check that some permissions were not granted by calling this API:

```
GET https://graph.facebook.com/me/permissions?access_token=USER_ACCESS_TOKEN
```
and then call `loginWithFacebook again` with `auth_type: 'rerequest',`
