### ISSUE TITLE
meteor run test is building for cordova

### ISSUE THREAD

**Issue by nerdmed** [meteor/meteor#7355] opened 2016-07-05 09:17 UTC
Currently meteor run test seems to be building for web.cordova and is even slower for build/rebuild times then just running the app. While developing its really essential to be able to rebuild fast to encourage a test driven development. Running test with plain npm takes <100ms - Meteor takes minimum of 10-20sec. That should really be the goal. Right now there is a enourmous gap there.

Maybe we can improve this a bit by removing the web.cordova build target from tests?

**Comment by abernix** [comment] 2016-07-05 11:23
What you're saying does seem likely because of [this code](https://github.com/meteor/meteor/blob/release-1.3.4.1/tools/cli/commands.js#L1500-L1502).  I suppose it _might_ be possible for the test driver itself (i.e. `practicalmeteor:mocha`, etc.) to make decisions here, but I'm not familiar with that aspect of it.

Just to be sure this is reproducible properly: Can you clarify the exact command you're running?  (Since `meteor run test` isn't a valid test command).  Perhaps you meant `meteor npm run test`?  If so, please provide what that is defined as in your `package.json`: `scripts`.

**Comment by nerdmed** [comment] 2016-07-11 11:00
@abernix thx for your response, i am running my tests like suggested in the guide with
 `meteor test --driver-package practicalmeteor:mocha`

is there a way to run the tests without rebuilding? Its really hard to work with tests if it takes about 20 seconds for them to build!

**Comment by abernix** [comment] 2016-07-16 18:16
Unfortunately, I don't have an easy work around or solution for this.  Hopefully someone can dig into this sometime soon but it will need to be prioritized with everything else.  Feel free to make a pass at it!

**Comment by laosb** [comment] 2016-08-29 05:47
Close due to inactivity. If someone found this again, please open a new issue or comment below.

**Comment by nerdmed** [comment] 2016-09-23 14:37
@laosb wtf? sorry but did you read the previous comments? This issue is not closed and needs to be fixed. It does not make any sense to build for cordova when runninng tests. I think the is a one or two line change for someone who knows the bundler?!

**Comment by abernix** [comment] 2016-10-04 12:07
@nerdmed Not sure why @laosb closed it.  My previous comment stands.

**Comment by hwillson** [comment] 2017-02-10 17:54
The `meteor test` command does not build for cordova by default. You can verify this by running `meteor test` from a developer checkout, adding some debugging [here](https://github.com/meteor/meteor/blob/0830967644f672b27deccc7454872b7dd13d20a4/tools/isobuild/bundler.js#L809) to watch the `this.arch` value, and make test changes to cause a rebuild.

Give this, and the numerous [build tool performance improvements made in release 1.4.2](https://github.com/meteor/meteor/blob/devel/History.md#v142-2016-oct-25), I'll close this issue off. Thanks for posting this originally!

**Closed by hwillson** 2017-02-10 17:54 UTC
Labels: bug, Impact:some, Project:Testing, Severity:blocks-development
