### ISSUE TITLE
Support handling .js ext in build plugin

### ISSUE THREAD

**Issue by fourq** [meteor/meteor#3668] opened 2015-02-07 17:10 UTC
Can we offer support for handling .js extensions in building plugins? I would like to avoid using other file ext's in my projects. 

```javascript
Plugin.registerSourceHandler("js", _6to5);
```

```
error: conflict: two packages included in fourq:6to5, the app and fourq:6to5, are both trying to handle .js
```

**Comment by stubailo** [comment] 2015-02-09 02:48
Duplicate of #3508.

**Closed by stubailo** 2015-02-09 02:48 UTC
Labels: Project:Isobuild
