### ISSUE TITLE
[1.8.3] onLogin handler fired twice

### ISSUE THREAD

**Issue by AndyCC25** [meteor/meteor#10853] opened 2020-01-09 15:19 UTC
Updating the version from 1.8.1 to 1.8.3,  notice that a part of the code that relies in a callback to `Accounts.onLogin()` method from  it’s being called twice. reference to https://forums.meteor.com/t/onlogin-handler-fired-twice-meteor-1-8-3/51224.

- **Version: Meteor**: 1.8.3
- **Last version without the issue**: Meteor 1.8.1
- **OS**: Ubuntu 14.04
- **Expected Behavior**: `onLogin` callback should run once
- **Actual Behavior**: `onLogin` callback runs twice
- **Reproduction**: run the reproduction project and notice that the `onLogin` callback fire twice, can check by a simple ``console.log()``.  Project:  https://github.com/AndyCC25/meteor-login-bug

**Comment by afrokick** [comment] 2020-02-10 20:50
not stale

**Comment by brendonlamb** [comment] 2020-04-22 21:21
Still not state in Meteor 1.10.2 - just upgraded, same issue.

**Comment by AndyCC25** [comment] 2020-05-27 12:23
Also I notice that still happens the two fire

**Comment by AndyCC25** [comment] 2020-05-27 12:31
a WA could use a `once()` function from underscore

**Comment by namenotrequired** [comment] 2020-09-13 12:48
It seems like there's a few separate bugs going on here.

## On initial login

A seemingly old bug in `accounts-ui-unstyled/login_buttons_dropdown.js`: if I click on the login button, I login once. But if I submit the form by hitting enter, I trigger two separate event listeners that both try to log me in, and we end up calling `onLogin` twice.

I made a PR to fix it (and a related bug): https://github.com/meteor/meteor/pull/11173

## On load when already logged in

On refresh, it is called once by `loggedInAndDataReadyCallback`, as normal, and once by `_startupCallback` which was introduced in [this PR that was included in Meteor 1.8.2](https://github.com/meteor/meteor/pull/10543)

I assume this is the bug that didn't happen on 1.8.1. I haven't looked into it further yet.

**Comment by santiagopuentep** [comment] 2020-11-01 00:08
Still happening on Meteor 1.11.

**Comment by filipenevola** [comment] 2020-11-11 21:44
This should be fixed on Meteor 1.12

**Comment by jasongrishkoff** [comment] 2020-12-08 18:46
Was optimistic v1.12 would solve my double login issue, but I guess not.
`Accounts.onLogin` still fires twice for me.
But I'm using a different package: `std:accounts-ui`, which isn't part of the official Meteor packages. Will update if I figure it out.

**Comment by filipenevola** [comment] 2020-12-11 19:03
@namenotrequired maybe @jasongrishkoff's case is a different one?

**Comment by jamesloper** [comment] 2021-02-23 19:15
Same behavior here as @jasongriskoff - When I log in with my React form, it fires once. When using a resume token it's firing twice in rapid succession. It seems like a race condition to me. The time between the two logins is median 70 to 80 milliseconds but as high as 400 millis.

Would it be possible to reopen this issue?

**Comment by jamesloper** [comment] 2021-02-25 15:09
This bug might be simpler to find than we though. It looks like the first time it fires, `Meteor.user()` is `undefined` and the second time, it is the actual user document. `Meteor.userId()` is set both times. So it seems the meteor internals are emitting before and after the default `null` sub is ready.

**Comment by santiagopuentep** [comment] 2021-05-24 20:48
@jamesloper this is exactly the problem I'm having, it fires twice, but the first time Meteor.user() is not available; the second time it its.

**Comment by StorytellerCZ** [comment] 2021-06-28 20:55
This issue persists as per #11446, which was closed as a duplicate of this one.

**Comment by brucejo75** [comment] 2021-11-24 06:29
@jasongrishkoff & @namenotrequired you were right on target.
PR #11785 should address it.

Sorry I just noticed this issue.  To speed things up next time:
- Referencing a PR or other issue does not notify the author
- In a case like this it may have been addressed quicker if you had mentioned the author of the offending PR (e.g. @brucejo75)

Sorry I goofed it & sorry I did not see this earlier!  Simple fix.

**Comment by paulincai** [comment] 2022-01-09 15:42
@filipenevola this is still going on in 2.5.3

**Comment by filipenevola** [comment] 2022-01-18 18:27
Should be [fixed](https://github.com/meteor/meteor/pull/11785) in Meteor [2.5.5](https://github.com/meteor/meteor/milestone/91) coming out soon.

**Closed by filipenevola** 2022-01-18 18:27 UTC
Labels: confirmed, Project:Accounts (in user apps), Type:Bug
