### ISSUE TITLE
urigo:static-templates Meteor 1.5 rc6

### ISSUE THREAD

**Issue by p3pp8** [meteor/meteor#8715] opened 2017-05-23 16:47 UTC
Not working, imports an object containing a default attribute with the html, instead of importing  the html template itself as result.

**Comment by hwillson** [comment] 2017-05-23 16:53
Hi @p3pp8 - please see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug). Most importantly, please provide a reproduction demonstrating your issue, or at a minimum show some code. We need to see how you're importing to get a better understanding of what's going on. Thanks!

**Comment by p3pp8** [comment] 2017-05-25 07:47
Create a meteor project with release 1.4.4.2, update to 1.5-rc.6, install urigo:static-templates through npm, remove angular templates before. Create a component named example.

```
import angular from 'angular';
import angularMeteor from 'angular-meteor';

import template from './example.html';

class Example {
	constructor($scope) {
		'ngInject';
	}
}

const name = "example";

export default angular
	.module(name, [
		angularMeteor
	])
	.component(name, {
                template,
		controller: Example,
		controllerAs: name
	});

```
imported template contains an object containing:

```
default:<div ui-view></div>
Symbol(__esModule):true
Symbol(__reify):Entry
__proto__:Object
```

not just the HTML content like it was in 1.4 release. So i've to use template: template.default to fix the import. May be it depends on something i'm doing wrong as i'm missing some important thing coming with release 1.5, but going back to 1.4.4.2 everything is working fine. Hope thiz helps!

**Comment by hwillson** [comment] 2017-05-25 13:06
Thanks for the additional details @p3pp8 - this problem has been further explained in https://github.com/meteor/meteor/pull/8327#issuecomment-304001916. It sounds like a PR submitted to `urigo:static-templates` to help address this would be accepted (see https://github.com/meteor/meteor/pull/8327#issuecomment-304002227). Since this issue is best handled in the https://github.com/Urigo/meteor-static-templates repo, I'll close it here. Thanks!

**Closed by hwillson** 2017-05-25 13:06 UTC
