### ISSUE TITLE
Not all private assets are packaged into the build

### ISSUE THREAD

**Issue by Mklueh** [meteor/meteor#8987] opened 2017-08-06 11:42 UTC
I´m storing some asset files in

> /private/data/keys/

But most of the time only one of those files is getting packaged into the build. The rest isn´t available.

I´ve tried a meteor reset, but that didn´t help. The files are skipped or not recognized somehow.

How can I make Meteor move all files into the build package?

Besides that I wanted to ask if it´s possible to access those files in the production build with fs.readdir or if it is just possible during development? Because I´m currently doing it that way (I need to load those files dynamically) but I´ve found the Assets API https://docs.meteor.com/api/assets.html which says

> Assets allows server code in a Meteor application to access static server assets, which are located in the private subdirectory of an application’s tree. Assets are not processed as source files and are copied directly into your application’s bundle.

**Comment by AirBorne04** [comment] 2017-08-07 20:36
I have been using the assets api and that worked for my for dynamic loading, in dev and prod, did you try it?

How do you verify that the file is not copied? do you check in the local folder?

**Comment by larswolter** [comment] 2017-08-07 20:46
I am also using the Assets API but recognized that assets are not copied, if they are duplicates. Assets.absoluteFilePath(assetPath) delivers the same URL for the different Assets in this case. So it works when using the Assets API. So even when not using getText or getBinary you should get the URL through the API.

**Comment by hwillson** [comment] 2017-08-08 18:14
@Mklueh Do any of your files have the same content? The build process skips files that have similar contents (see https://github.com/meteor/meteor/issues/8159#issuecomment-267320302 for more details).

> Besides that I wanted to ask if it´s possible to access those files in the production build with fs.readdir or if it is just possible during development?

Meteor's [`Assets`](http://docs.meteor.com/api/assets.html) API is the currently supported approach for accessing static server assets. If you're interested in doing something that the `Assets` API doesn't support, you can definitely leverage any functionality Node has to offer. For more information about how to do this, try posting on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (using the tag `meteor`). Issues here are reserved for Meteor bugs. 

Since I'm not seeing a bug here, I'll close this issue for now. If you still feel like there is a bug lurking somewhere, please link to a small runnable reproduction that demonstrates this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Closed by hwillson** 2017-08-08 18:14 UTC
