### ISSUE TITLE
Certain Meteor packages will not download in Docker on a Circle CI build due to running as root leading to a chown

### ISSUE THREAD

**Issue by benwiley** [meteor/meteor#4566] opened 2015-06-15 14:46 UTC
**_1 Upvote**_ You can recreate the issue easily by SSHing into any circle ci build (that has Docker) and executing these commands.

``` bash
docker run -a stdin -a stdout -a stderr -i -t ubuntu /bin/bash
apt-get install curl
curl https://install.meteor.com/ | sh
apt-get install vim
cd /home/
meteor create app
cd app/
meteor add velocityjs:velocityjs
```

You will get this error:

``` bash
Error: EINVAL, chown '/tmp/<random dir>/<package you added>'
```

Running this in docker on my machine (Mac OS X) works correctly, but in CI, it always throws the error.

Questions I am trying to answer: 
- Why does it happens on a circle box, even though it's all within a docker container?
- Why do certain packages (like velocityjs:velocityjs) trigger the error? bjwiley2:server-watch does as well.

What I've tried with no success:
- Switching the directories that the meteor app is created in
- Using sudo to try and fix the chown issue
- chown nobody:nogroup /tmp
- Cloning bjwiley2:server-watch into my projects packages directory to see if it would run locally (it did)
- Installing package dependencies directly (like http and jquery) to see if one of those was the problem
- Tried to recreate problem on Ubuntu Server to see if it was working locally only because I was on OS X. It worked fine. The problem is still only on circle boxes.

**Comment by robertpitt** [comment] 2015-06-15 15:50
This seems like an Issue with Circle CI's platform, have you tried opening a issue with them.

Reference: https://github.com/reywood/meteor-iron-router-ga/issues/27

**Comment by benwiley** [comment] 2015-06-15 15:54
I have, but they told me to talk to meteor and/or package developers.  I hate it when that happens!

**Comment by glasser** [comment] 2015-06-16 21:52
Can you provide the full stack trace instead of just one line?

I don't see any calls to `chown` in the Meteor tool source, so this is strange.

**Comment by johnthepink** [comment] 2015-06-17 18:53
Hey @glasser I work with @benwiley. Here is the trace of what we have been getting:

~~~
/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: EINVAL, chown '/tmp/.tmp194dc3g/bjwiley2_server-watch-0.0.6'
    at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:395:16)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:556:31
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:554:9
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at enterJob (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at Object.forkJoin (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:531:3)
    at [object Object]._.extend.downloadPackagesMissingFromMap (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:562:18)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:668:25
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:667:20
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/catalog.js:100:5
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:666:13)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:238:35
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:228:18)
    at ProjectContext._.extend.saveChangedMetadata (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:216:10)
    at ProjectContext._.extend.prepareProjectForBuild (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:221:10)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:520:29
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:245:19)
    at bundleApp (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:519:31)
    at [object Object]._.extend._runOnce (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:591:35)
    at [object Object]._.extend._fiber (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:821:28)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:402:12
    - - - - -
    at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.files.extractTarGz (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:708:10)
    at Object.exports._extractAndConvert (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:49:9)
    at [object Object]._.extend._downloadBuildToTempDir (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:295:20)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:462:37
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:460:11
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at Object.download (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:419:20)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:566:18
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:537:23
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at enterJob (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:536:24
    at runWithEnvironment (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:139:21)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:146:14
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:549:11
    - - - - -
lxc-start: The container failed to start.

lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
~~~

**Comment by glasser** [comment] 2015-06-17 19:34
Ah, OK, so this is being done inside the tar package, or specifically some package being used by it.  Specifically, it's happening here:

https://github.com/npm/fstream/blob/master/lib/writer.js#L194-L211

... and it skips the chown unless you are root.  And also, the chown call itself is actually this polyfilled version:

https://github.com/isaacs/node-graceful-fs/blob/master/polyfills.js#L122-L185

... which ignores EINVAL... unless you are root.

It would be nice if there was a way to tell https://github.com/npm/node-tar to skip the chown even if running as root.  But there doesn't seem to be.  So if you want to send a PR to node-tar to add an option (which also needs an option in fstream) to not chown even if root, that would probably help.  Other than that, if there's a way to not run as root that seems like a workaround, but maybe that's just not how docker works.

**Comment by jraede** [comment] 2015-07-16 20:21
I'm having this issue as well - any new developments?

**Comment by Levino** [comment] 2015-08-03 11:28
Same here :(

**Comment by jraede** [comment] 2015-08-03 14:04
To whoever is interested, we were able to get this to work on TravisCI using their new trusty infrastructure. Add this to the top of your travis.yml file:

```yml
sudo: required
services:
  - docker
```

**Comment by Levino** [comment] 2015-08-03 20:28
So it is a Meteor problem. Will this be solved by the Meteor devs?

**Comment by kop** [comment] 2015-08-03 20:32
+1 to this issue. CircleCI is really good for building images, but this bug makes it unusable.

**Comment by Levino** [comment] 2015-11-06 11:20
This is still an issue! Is anyone going to fix this?

**Comment by kimh** [comment] 2015-11-13 05:09
I took a look a bit. So, the error seems happening [here](https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/tools/fs/files.js#L689). My assumption is `tar.Extract` tries to chown files to whatever uid not allowed on Docker container.

I think the fix is passing an option similar to `--no-same-owner` of GNU tar but it looks node-tar [doesn't support](https://github.com/npm/node-tar/issues/39) now.

I don't have time to work on now, but will have more look later.

**Comment by kimh** [comment] 2015-11-13 14:57
I debugged a bit more and now I have better understanding of the problem.

**Problem**
Meteor uses node-tar to extract meteor package (tar file) and node-tar tries to preserve the original uid.
However, the tar package of velocityjs:velocityjs contains uid that is larger than what Docker can handle, therefore EINVAL error.

I added debug print to meteor running on CircleCI and here is the output.

```
root@f3c3b5538d2b:/app# meteor add velocityjs:velocityjs
------------ Debug Start ------------1.2...  [==========================] 100% 0.0s
path: velocityjs:velocityjs-1.2.1-os+web.browser+web.cordova/
uid: 130450
------------ Debug End ------------
------------ Debug Start ------------
path: velocityjs:velocityjs-1.2.1-os+web.browser+web.cordova/isopack.json
uid: 130450
------------ Debug End ------------
------------ Debug Start ------------
path: velocityjs:velocityjs-1.2.1-os+web.browser+web.cordova/os/
uid: 130450
------------ Debug End ------------
------------ Debug Start ------------
path: velocityjs:velocityjs-1.2.1-os+web.browser+web.cordova/os/packages/
uid: 130450
------------ Debug End ------------

/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
                                                throw(ex);
                                                      ^
Error: EINVAL, chown '/tmp/.tmpkqwf3a/velocityjs:velocityjs-1.2.1-os+web.browser+web.cordova'
    at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.files.extractTarGz (/tools/fs/files.js:721:9)

<snip>
```

I don't know the maximum uid that Docker can handle on CircleCI but probably 130450 is out of the range.

**Solution**
Working on [PR](https://github.com/npm/node-tar/issues/39) of node-tar and implement a option like `--no-same-owner` of GNU tar and use the option in meteor.

**Comment by leolara** [comment] 2015-11-19 08:05
@kimh any work-around in the meantime?

**Comment by LewisW** [comment] 2015-11-30 20:56
@leolara I've had some success [running the build process as a non-root user](https://github.com/LewisW/meteord/blob/master/base/scripts/lib/build_app.sh#L15). Or another alternative is to use something like [shippable.com](http://shippable.com) - they have much better Docker support than CircleCI's.

**Comment by leolara** [comment] 2015-11-30 22:20
@LewisW I found a way to create a meteor app docker from CircleCI. The key is to build a meteor bundle on CircleCi, but outside Docker. Then the docker build just adds the meteor bundle to the docker fs.

Something like 

```
dependencies:
  pre:
    - meteor build .deployment/bundle
    - cd .deployment/bundle && docker build -t $DOCKER_REPOSITORY:$CIRCLE_BRANCH .

```

for circle.yml

and then the Dockerfile inside .deployment/bundle

```
FROM meteorhacks/meteord:base
MAINTAINER Leo Lara

COPY *.tar.gz /bundle/
```

:-)

**Comment by pward123** [comment] 2016-02-19 04:53
I'm working around this issue by adding another user to the dockerfile and running all commands as that user.

```
RUN        useradd -g root -ms /bin/bash ubuntu
USER       ubuntu
WORKDIR    /home/ubuntu
```

For a full example build image, see the below repo. I've added some items to this image to speed up my CircleCI builds, so I only recommend this image for building not running apps in production.

https://github.com/pward123/docker-meteor-build/tree/release/v1.3

**Comment by LewisW** [comment] 2016-02-19 10:11
Thanks for posting your workarounds. I'd be interested in how much building the bundle outside of docker speeds up building the docker image - since CircleCI will have already downloaded all the necessary dependencies.

**Comment by pward123** [comment] 2016-02-19 10:54
I just changed my building as a result of moving to meteor 1.3.  Before 1.3, my builds were approximately 7:30 in length.

When I first switched to 1.3 (building outside the container), build length increased to 15:00-16:00.  The majority of the increase was caused by meteor downloading the 1.3 build tool and associated files. With ~30 sec of that time being due to the additional npm install of the items defined in the package.json at the root of the project.

Switching to building inside the container dropped the builds back down to 10:00-10:30.  ~30 sec still being attributed to the extra npm install step.  The other 2:00-2:30 minute increase (from the original build times) was because I don't use docker hub (past reliability issues) so I'm downloading the ~550mb build image tgz from s3, unzipping and docker loading it for each build.

In order to keep the build times from dramatically increasing with the build container, I have the build container's dockerfile create a scratch app with the appropriate meteor release(s) that I use. This way it doesn't need to download the build tools each time.

**Comment by hwillson** [comment] 2017-01-23 12:25
It's been a while since there has been any activity on this issue, and it doesn't look like this is an issue that can be addressed within the Meteor codebase. Given that there are workarounds outlined in this issue thread, and as part of the on-going old issue cleanup process, I'll close this for now. Thanks for posting this originally!

**Closed by hwillson** 2017-01-23 12:25 UTC
Labels: Project:Isobuild

**Comment by mitar** [comment] 2017-01-23 17:16
Is node-tar even still being used?

**Comment by abernix** [comment] 2017-01-23 22:19
@mitar It's used as a last resort but preference is given to the [native implementation](https://github.com/meteor/meteor/blob/devel/tools/fs/files.js#L730-L736) of `tar` (or 7z, on Windows).
