### ISSUE TITLE
1.3 beta 11: build failure

### ISSUE THREAD

**Issue by ndarilek** [meteor/meteor#6335] opened 2016-02-24 22:10 UTC
Not sure if this is reported with different symptoms but a brief scan of recently-filed issues didn't reveal anything. Getting the following errors attempting to run a deployed Meteor app:

```

Error: Cannot find module 'react'
	

...n r(r){var e=f(m(n,r));if(e===b){var t=new Error("Cannot find module '"+r+"'");i...

	
85e3f85...ce=true (line 23, col 385)
TypeError: Package['service-configuration'] is undefined
```

I'm attempting to run my app in a Docker image that works around the fact that `meteor build` doesn't yet seem to install dependencies in package.json, but even without Docker this should be a useful example of how I'm attempting to build *any* production Meteor 1.3 beta app. Here is my Dockerfile:

```
FROM node:0.10.41
ENV PORT 3000
EXPOSE 3000
RUN adduser --system --no-create-home --disabled-login app
COPY . /src
RUN curl https://install.meteor.com |sh && \
  cd /src && \
  meteor build --directory / && \
  rm -rf /usr/local/bin/meteor /root/.meteor
RUN cd /bundle/programs/server && \
  npm install && \
  npm cache clear && \
  mv node_modules /bundle && \
  cp /src/package.json /bundle && \
  cd /bundle && \
  npm install && \
  npm cache clear && \
  ln -s /bundle/node_modules /bundle/programs/server && \
  ln -s /bundle/node_modules /bundle/programs/web.browser && \
  rm -rf /src
USER app
WORKDIR /bundle
CMD node main.js
```

[Here](https://github.com/ndarilek/meteor-beta-module-errors) is a reproduction that can be spun up with:

```
docker-compose up
```

It still renders because it uses Blaze, but it does demonstrate the errors I'm noticing in my React-based app.

Thanks.

**Comment by tmeasday** [comment] 2016-02-25 05:01
I suspect the issue is that you need to `npm install` in between `cd /src && \` and `meteor build...`

**Comment by tmeasday** [comment] 2016-02-25 05:02
We're working on a better error message in this (common) case where you forget to `npm install` #6322

**Comment by tmeasday** [comment] 2016-02-25 05:03
Closing - let me know if that's not what happened.

**Closed by tmeasday** 2016-02-25 05:03 UTC
