### ISSUE TITLE
Meteor Reactiveness & ContentEditable

### ISSUE THREAD

**Issue by saeho** [meteor/meteor#3496] opened 2015-01-18 01:31 UTC
Meteor reactiveness seems cause several unexpected behaviours when working with contenteditable elements. For example, it causes the position of cursor to move to end/beginning every time the collection is updated (because of the reactiveness). Sometimes it double-inserts the new collection data into the DOM (because the updated data is written on top of the current editable data, the data inside collection is always correct though.)

This won't be any issue for most apps but it makes things like autosaves very counter productive and buggy.

**Comment by Tarang** [comment] 2015-01-18 17:29
Similar to https://github.com/meteor/meteor/issues/2882

**Comment by glasser** [comment] 2015-01-21 01:42
This looks like a duplicate of #2882 and #1964.

**Closed by glasser** 2015-01-21 01:42 UTC
