### ISSUE TITLE
[meteor 1.3.rc.4] Failed Match.OneOf, Match.Maybe or Match.Optional validation + Match error: Expected Number

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#6553] opened 2016-03-22 02:55 UTC
my publish code:
```
Meteor.publish('categories.list', (params) => {
		Meteor._sleepForMs(3000);
		const selector = params ? params.selector : {};
		//const options = params ? params.options : {};
		const options = {
			limit: 5
		};
		return Categories.find(selector, options);
	});
```
and this error when i use limit, or skip options.
```
Exception from sub categories.list id 6FZnGpBkM4WDfQAtr Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
I20160322-09:51:15.014(7)?     at check (D:\DEV\Meteor\Meteor\source-rc4\.meteor\local\build\programs\server\packages\check.js:138:15)
I20160322-09:51:15.014(7)?     at [object Object]._getFindOptions (packages/mongo/collection.js:256:7)
I20160322-09:51:15.014(7)?     at [object Object].find (packages/mongo/collection.js:295:39)
I20160322-09:51:15.014(7)?     at Subscription._handler (src/server/publish/categories.js:13:21)
I20160322-09:51:15.014(7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1701:12)
I20160322-09:51:15.014(7)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20160322-09:51:15.015(7)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20160322-09:51:15.015(7)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20160322-09:51:15.015(7)?     at packages/ddp-server/livedata_server.js:551:43
I20160322-09:51:15.166(7)? Sanitized and reported to the client as: Match failed [400]
```

when i try to check:
`check(options.limit, Number);`

and error:
`Error: Match error: Expected Number `

if i empty options, it work !
what happen ?

**Comment by gkrizek** [comment] 2016-08-17 12:17
I'm getting this same issue on Meteor 1.4.0.1.

I have narrowed it down to any Publication that uses a `limit`. If I remove the `limit`, it works just fine. I uninstalled any other Collection type packages and I uninstalled `check` package to make sure those weren't the problem.

Stack Trace:
```
I20160817-06:11:17.610(-6)? Exception from sub chat id CzewXcKokPabHMt5h Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
I20160817-06:11:17.612(-6)?     at exports.check (packages/check/match.js:34:1)
I20160817-06:11:17.613(-6)?     at [object Object]._getFindOptions (packages/mongo/collection.js:277:7)
I20160817-06:11:17.614(-6)?     at [object Object].find (packages/mongo/collection.js:316:39)
I20160817-06:11:17.614(-6)?     at Subscription._handler (server/server.js:9:17)
I20160817-06:11:17.614(-6)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160817-06:11:17.615(-6)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20160817-06:11:17.616(-6)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20160817-06:11:17.616(-6)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20160817-06:11:17.616(-6)?     at packages/ddp-server/livedata_server.js:551:43
I20160817-06:11:17.620(-6)? Sanitized and reported to the client as: Match failed [400]
I20160817-06:11:17.620(-6)?
```

My Publication:
```
Meteor.publish("chat", function (lng, lat, limit) {
    return Chat.find({loc: {$geoWithin:{$center: [[lng, lat], 20]}}}, {limit: limit}, {fields: {'_id': 1, 'sender': 1, 'message': 1, 'createdAt': 1}});
});
```

**Comment by abernix** [comment] 2016-09-26 09:45
I also cannot reproduce this problem.  Please provide a full reproduction in the form of a Git Repo to assist in debugging this.

@gkrizek In your case, `limit` should be inside the `options` (i.e. in the same location as `fields` in your example).  See [docs](https://docs.meteor.com/api/collections.html#Mongo-Collection-find) for more information.

Closing as unreproducible.

**Closed by abernix** 2016-09-26 09:45 UTC
Labels: bug, can't-reproduce

**Comment by AChusuei** [comment] 2017-07-07 00:58
Suggestion: this could happen if your limit is a string of a number, not a number: a là:
```
{ limit: '1' }
```

**Comment by aliogaili** [comment] 2019-06-27 17:53
I think the issue is with the check library and specifically this line [here](https://github.com/meteor/meteor/blob/bf24ef3cb67ae05bf13b66d51ad7b72ce6c06612/packages/check/match.js#L339) where a recursive call is happening to a potentially undefined values. At least for me, the issue went away when I removed the undefined from the pattern.
