### ISSUE TITLE
App crashed on IE 11 after migrating from Meteor 1.2.1 to 1.5.2

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#9115] opened 2017-09-20 05:13 UTC
I have migrated my Meteor App from 1.2.1 to 1.5.2. App works perfect in all browers except IE 11.
Here are all the errors I am getting in IE browser console:

```
[SCRIPT438: Object doesn't support property or method 'for'
modules.js (516,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
es5-shim.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
promise.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
babel-runtime.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
ecmascript-runtime-client.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
ejson.js (18,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
diff-sequence.js (18,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
geojson-utils.js (17,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
id-map.js (18,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
random.js (18,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
mongo-id.js (17,1)
SCRIPT5007: Unable to get property 'DiffSequence' of undefined or null reference
minimongo.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
check.js (17,1)
SCRIPT5007: Unable to get property 'Random' of undefined or null reference
retry.js (18,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
ddp-common.js (17,1)
SCRIPT5007: Unable to get property 'Symbol' of undefined or null reference
reload.js (18,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
ddp-client.js (17,1)
SCRIPT5007: Unable to get property 'DDP' of undefined or null reference
ddp.js (14,1)
SCRIPT5007: Unable to get property 'LocalCollection' of undefined or null reference
allow-deny.js (18,1)
SCRIPT5007: Unable to get property 'AllowDeny' of undefined or null reference
mongo.js (17,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
reactive-dict.js (20,1)
SCRIPT5007: Unable to get property 'ReactiveDict' of undefined or null reference
session.js (18,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
jquery.js (17,1)
SCRIPT5007: Unable to get property '$' of undefined or null reference
twbs_bootstrap.js (17,1)
SCRIPT5007: Unable to get property 'Random' of undefined or null reference
localstorage.js (17,1)
SCRIPT5007: Unable to get property 'MongoID' of undefined or null reference
observe-sequence.js (19,1)
SCRIPT5007: Unable to get property '$' of undefined or null reference
blaze.js (17,1)
SCRIPT5007: Unable to get property 'Random' of undefined or null reference
accounts-base.js (20,1)
SCRIPT5007: Unable to get property 'Random' of undefined or null reference
srp.js (17,1)
SCRIPT5007: Unable to get property 'Accounts' of undefined or null reference
accounts-password.js (17,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
oauth.js (17,1)
SCRIPT5007: Unable to get property 'Random' of undefined or null reference
accounts-oauth.js (18,1)
SCRIPT5007: Unable to get property 'Accounts' of undefined or null reference
service-configuration.js (17,1)
SCRIPT5007: Unable to get property 'OAuth' of undefined or null reference
facebook-oauth.js (17,1)
SCRIPT5007: Unable to get property 'ObserveSequence' of undefined or null reference
spacebars.js (17,1)
SCRIPT5007: Unable to get property 'Blaze' of undefined or null reference
templating-runtime.js (18,1)
SCRIPT5007: Unable to get property 'Template' of undefined or null reference
templating.js (14,1)
SCRIPT5007: Unable to get property 'ServiceConfiguration' of undefined or null reference
accounts-ui-unstyled.js (19,1)
SCRIPT5007: Unable to get property 'Template' of undefined or null reference
facebook-config-ui.js (17,1)
SCRIPT5007: Unable to get property 'Accounts' of undefined or null reference
accounts-facebook.js (17,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
aldeed_simple-schema.js (20,1)
SCRIPT5007: Unable to get property 'SimpleSchema' of undefined or null reference
aldeed_collection2-core.js (17,1)
SCRIPT5007: Unable to get property 'Collection2' of undefined or null reference
aldeed_schema-index.js (17,1)
SCRIPT5007: Unable to get property 'Collection2' of undefined or null reference
aldeed_schema-deny.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
http.js (19,1)
SCRIPT5007: Unable to get property '$' of undefined or null reference
rajit_bootstrap3-datepicker.js (17,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
cfs_base-package.js (20,1)
SCRIPT5007: Unable to get property 'DDP' of undefined or null reference
livedata.js (14,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_storage-adapter.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_filesystem.js (17,1)
SCRIPT5007: Unable to get property '$' of undefined or null reference
dschulz_jquery-qrcode.js (17,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
mizzao_timesync.js (17,1)
SCRIPT5007: Unable to get property 'Accounts' of undefined or null reference
mizzao_user-status.js (17,1)
SCRIPT5007: Unable to get property 'Mongo' of undefined or null reference
tmeasday_publish-counts.js (17,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
ostrio_logger.js (18,1)
SCRIPT5007: Unable to get property 'Logger' of undefined or null reference
ostrio_loggerfile.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
kadira_dochead.js (19,1)
SCRIPT5007: Unable to get property '$' of undefined or null reference
mizzao_jquery-ui.js (17,1)
SCRIPT5007: Unable to get property 'Mongo' of undefined or null reference
lai_collection-extensions.js (17,1)
SCRIPT5007: Unable to get property 'Mongo' of undefined or null reference
dburles_mongo-collection-instances.js (17,1)
SCRIPT5007: Unable to get property 'Session' of undefined or null reference
angular-meteor-data.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
interwebs_ui-sortable.js (17,1)
SCRIPT5007: Unable to get property '$' of undefined or null reference
dangrossman_bootstrap-daterangepicker.js (18,1)
SCRIPT5007: Unable to get property '$' of undefined or null reference
fragaria_angular-daterangepicker.js (18,1)
SCRIPT5007: Unable to get property 'Template' of undefined or null reference
copleykj_stripe-sync.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
dynamic-import.js (17,1)
SCRIPT5007: Unable to get property 'Blaze' of undefined or null reference
ui.js (14,1)
SCRIPT5007: Unable to get property 'Blaze' of undefined or null reference
dotansimha_accounts-ui-angular-moded.js (17,1)
SCRIPT5007: Unable to get property 'meteorInstall' of undefined or null reference
webapp.js (18,1)
SCRIPT5007: Unable to get property 'EJSON' of undefined or null reference
cfs_data-man.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_file.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_tempstore.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_access-point.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_upload-http.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_collection.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_collection-filters.js (17,1)
SCRIPT5007: Unable to get property 'FS' of undefined or null reference
cfs_worker.js (17,1)
SCRIPT5007: Unable to get property 'Retry' of undefined or null reference
autoupdate.js (19,1)
SCRIPT5007: Unable to get property 'Mongo' of undefined or null reference
global-imports.js (3,1)
SCRIPT5009: 'meteorInstall' is undefined
app.js (1,1)
SCRIPT5007: Unable to get property 'check' of undefined or null reference
mdg_validation-error.js (17,1)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)
SCRIPT5: Access is denied.

pbastowski_angular-babel.js (1579,5)](url)

```

**Comment by AirBorne04** [comment] 2017-09-20 07:11
Hi,
did you have a look at the breaking changes

[1.3 Migration](https://guide.meteor.com/1.3-migration.html)
[1.4 Migration](https://guide.meteor.com/1.4-migration.html)
[1.5 Migration](https://guide.meteor.com/1.5-migration.html)

**Comment by abernix** [comment] 2017-09-20 08:01
The first thing that jumps out at me is your usage of the `pbastowski:angular-babel` package.  This package states pretty clearly on its [README](https://github.com/pbastowski/angular-meteor-babel) that it's deprecated.   It also _might_ be helpful to see what is on line 516 of `modules.js` (based on the `modules.js (516,1)` error).  All in all, I'm guessing you could have some very old Babel stuff going on if you were using `angular:meteor-babel`, and I'd suggest trying to clean that up.

I can assure you that Meteor 1.5 applications do work fine with IE11 (www.meteor.com is a Meteor application and loads fine on IE11), so we'll need an actual reproduction repository (per the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines) in order to help you diagnose this further.

I'll close this as it doesn't meet the requirements from the guidelines for opening an issue, but I'm more than happy to reopen this if you can provide a reproduction we can look at, and happy to continue to discuss even though this issue is closed. :smile:

**Closed by abernix** 2017-09-20 08:01 UTC

**Comment by abernix** [comment] 2017-09-20 08:04
Also, here are some other recent issues from the [issue search for "ie11"](https://github.com/meteor/meteor/issues?q=is%3Aissue+ie11+is%3Aclosed), as reported by other users.  Maybe https://github.com/meteor/meteor/issues/9056 or https://github.com/meteor/meteor/issues/8782 are relevant to you!

**Comment by mi-k4** [comment] 2017-10-10 08:42
Hello, for information I have exactly the same problem since the update of meteor and it seems to concern reify module.

I use google map auto-complete and if I delete the call to the cdn, it's work with internet explorer 11:

-

**Comment by yannickneemaa** [comment] 2017-11-22 12:58
@mi-k4 
I have the same problem as you : when I deactivate google map auto-complete, my site is OK on IE11.
Have you found a fix ?

**Comment by mi-k4** [comment] 2017-11-22 17:33
@yannickneemaa Hello, yes I moved the tag script of head to the end of the body

            <script src="https://maps.googleapis.com/maps/api/js?key=myKey&libraries=places"></script>
        </body>

**Comment by MartiniHenry1988** [comment] 2017-11-26 16:00
@abernix Can you please guide me what package should I use instead of using `pbastowski:angular-babel` ?

**Comment by AirBorne04** [comment] 2017-11-30 10:23
@MartiniHenry1988 I am using angular2-compilers (atmosphere) with angular2-meteor and angular2-meteor-polyfills (both npm)

**Comment by MartiniHenry1988** [comment] 2017-12-01 11:18
@AirBorne04  Actually I am using `angular 1` for client, so any idea what should replace `pbastowski:angular-babel` package in `angular 1 + Meteor 1.6` ??

**Comment by AirBorne04** [comment] 2017-12-01 11:43
@MartiniHenry1988 Yes sure :) for angularJS i am using `angular-templates` with `ecmascript` (atmosphere) and that is it. I have not yet updated that project to 1.6 i am running it on the latest 1.5 so i guess it would be working on 1.6 as well.

**Comment by MartiniHenry1988** [comment] 2017-12-01 11:47
@AirBorne04 Actually I am using plain Javascript & not using ecmascript, so would that be an issue to use `angular-templates` without ecmascript?

**Comment by AirBorne04** [comment] 2017-12-01 11:48
@MartiniHenry1988 That should be fine since it is just transpiling.

**Comment by MartiniHenry1988** [comment] 2017-12-01 11:49
@AirBorne04  Thanks a lot, I will give it a try

**Comment by MartiniHenry1988** [comment] 2017-12-01 16:29
@AirBorne04  Can you please provide me your `.meteor/packages` file? I want to see how you managed the angular js with Meteor 1.5

**Comment by AirBorne04** [comment] 2017-12-04 11:34
@MartiniHenry1988 sure thing

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

# base platform
meteor-base@1.1.0
mongo@1.2.0
tracker@1.1.3
email@1.2.3
dynamic-import@0.1.1

# ext platform
random@1.0.10
promise@0.9.0
shell-server@0.2.4

# images capabilities
cfs:standard-packages
cfs:filesystem

# server publish transforms
maximum:server-transform
matb33:collection-hooks

####### client side

# less, css and js build
less@2.7.9
juliancwirko:postcss
standard-minifier-js@2.1.1

# angular platform
angular-templates
ecmascript@0.8.2

# accounts login services
accounts-password@1.4.0
accounts-google@1.2.0
accounts-facebook@1.2.1
accounts-twitter@1.3.0
# bozhao:accounts-instagram
# liberation:accounts-paypal

service-configuration@1.0.11
bozhao:link-accounts
alanning:roles

# debug
# bundle-visualizer
```

**Comment by pisacode** [comment] 2017-12-25 10:59
@AirBorne04 i had the same error and it was caused by a npm module for json export and its import statement. I recommend checking all of your import statements.

**Comment by AirBorne04** [comment] 2017-12-25 19:22
@MartiniHenry1988 did you manage? @pisacode had a remark on this issue.

@pisacode for me it is working fine i am helping @MartiniHenry1988 here :)

**Comment by pisacode** [comment] 2017-12-26 13:37
Haha sorry @AirBorne04  I think, I read the thread a little too fast:)

@MartiniHenry1988 just check this line and i think you will see which import statement is causing the issues

`[SCRIPT438: Object doesn't support property or method 'for'
modules.js (516,1)`
