### ISSUE TITLE
Cant adding any package 

### ISSUE THREAD

**Issue by foxeverfox** [meteor/meteor#4794] opened 2015-07-23 07:14 UTC
I using the latest meteor , but i got problem , since yesterday suddenly  i cant adding any package to any of my project  , even a new one. 
Meteor keep showing endless "Updating Package Catalog" message. 
I already uninstal and reinstall  meteor and node JS   and change to other user account on my windows machine , still no luck

Thank for help.

**Comment by anubhav94** [comment] 2015-07-28 20:30
Hey @foxeverfox, please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it. We'd need a step by step method to know how to reproduce the problem, which version of Meteor you're using, you're environment, etc as described in the link above. Closing this for now, because there is no reproduction.

**Closed by anubhav94** 2015-07-28 20:30 UTC
Labels: needs-repro, Project:Windows
