### ISSUE TITLE
Invalid State Error (INVALID_STATE_ERR)

### ISSUE THREAD

**Issue by pmogollons** [meteor/meteor#10555] opened 2019-05-08 16:03 UTC
We are getting this issue on our app, error is not very helpful. Looks like it doesnt cause a crash or something similar on the app.

This issue is related to 2 other old issues that are already closed without a fix.
* #6365 
* #3396

I found 2 places in code that throw this error [place 1](https://github.com/meteor/meteor/blob/24865b28a0689de8b4949fb69ea1f95da647cd7a/packages/socket-stream-client/sockjs-0.3.4.js#L1087) and [place 2](https://github.com/meteor/meteor/blob/24865b28a0689de8b4949fb69ea1f95da647cd7a/packages/socket-stream-client/sockjs-0.3.4.js#L1220)

Can this issue be just ignored? And if so why not just log the error without throwing?

Meteor version: v1.8.1 but we have seen it in past releases too. Not sure how to create a reproduction for this issue.

Latest was on this browser:
Browser: Samsung Browser (WebKit) - 9.2  Android - 9, mobile - Samsung SM-G955F

```js
Error: INVALID_STATE_ERR
    at T._didClose (https://app.propiedata.com/8c987854f10db7034f3c8797722061d16e7c25ed.js?meteor_js_resource=true:57:15181)
    at https://app.propiedata.com/8c987854f10db7034f3c8797722061d16e7c25ed.js?meteor_js_resource=true:57:18968
    at r.XHRCorsObject.t.onfinish (https://app.propiedata.com/8c987854f10db7034f3c8797722061d16e7c25ed.js?meteor_js_resource=true:57:20192)
    at r.XHRCorsObject.a.emit (https://app.propiedata.com/8c987854f10db7034f3c8797722061d16e7c25ed.js?meteor_js_resource=true:57:1821)
    at XMLHttpRequest.a.xhr.onreadystatechange (https://app.propiedata.com/8c987854f10db7034f3c8797722061d16e7c25ed.js?meteor_js_resource=true:57:11936)
    at XMLHttpRequest.o (https://app.propiedata.com/8c987854f10db7034f3c8797722061d16e7c25ed.js?meteor_js_resource=true:5:763410)
```

**Comment by KoenLav** [comment] 2019-05-08 20:07
Same issue here from time to time.

Client being Mobile Safari 12.1, so I don't think it's related to a specific browser.

**Comment by lars-ewers** [comment] 2019-05-27 16:42
same here..

Client being mobile safari as well.

Any updates here?!

**Comment by arggh** [comment] 2019-06-04 20:22
I see these everyday in our logs. So far they haven't been related to any real bug reports or user complaints, which has led me to believe they are just noise from some timing issue etc. in the web socket connection handling.

<img width="351" alt="invalid_state_err" src="https://user-images.githubusercontent.com/17210302/58910880-51587b80-871f-11e9-86b7-34e94c76c030.png">

**Comment by Falkovic1993** [comment] 2019-06-21 08:22
Any news on this one? 

This is the most common error we have; in Mobile Safari (WebKit) - 9.0  iOS - 9.1, mobile - Apple iPhone

**Comment by jamesmillerburgess** [comment] 2019-07-14 14:37
We also started getting this error today, but it was after a big upgrade to our site, so pinpointing the issue is might be difficult. 

Interestingly, part of the upgrade was moving away from Meteor methods and to Apollo, so I wouldn't have expected to get more websocket errors than before.

**Comment by sourcerer52** [comment] 2019-07-18 08:54
We are also facing the same issue at the time of login. But the issue does not always reproduce.

**Comment by stolinski** [comment] 2019-07-18 19:50
Also getting this error even after disabling websockets.

**Comment by paulincai** [comment] 2019-07-31 19:58
In 20 seconds Googlebot called one of my urls 53 times. All my errors are related to the Google indexing.

![Screen Shot 2019-07-31 at 23 12 08](https://user-images.githubusercontent.com/26188915/62243797-1c029e00-b3ef-11e9-9cda-39d16817f39b.png)

![Screen Shot 2019-07-31 at 23 28 30](https://user-images.githubusercontent.com/26188915/62243789-16a55380-b3ef-11e9-9286-4a2bdb29d785.png)

**Comment by perbergland** [comment] 2019-09-28 10:43
I get thousands of these periodically (they come in bursts) - does anyone have any idea what's going on? My app runs on AWS with an ALB in case that matters.

Oh, and I get two variants of _didClose errors which are both picked up by montiapm (Kadira).

```
Error: INVALID_STATE_ERR

Error: INVALID_STATE_ERR
    at T.prototype._didClose (https://app.refapp.se/442e66b53c02fb70a9f09495e900592ca73664cf.js?meteor_js_resource=true:61:15175)
    at https://app.refapp.se/442e66b53c02fb70a9f09495e900592ca73664cf.js?meteor_js_resource=true:61:18963
    at onfinish (https://app.refapp.se/442e66b53c02fb70a9f09495e900592ca73664cf.js?meteor_js_resource=true:61:20192)
    at a.prototype.emit (https://app.refapp.se/442e66b53c02fb70a9f09495e900592ca73664cf.js?meteor_js_resource=true:61:1791)
    at a.xhr.onreadystatechange (https://app.refapp.se/442e66b53c02fb70a9f09495e900592ca73664cf.js?meteor_js_resource=true:61:11934)
```

and 

```
Error: Uncaught Error: INVALID_STATE_ERR

Error: INVALID_STATE_ERR
    at k._didClose (https://app.refapp.se/02171ba37de34beaffd62ffe624a50ecfb585c99.js?meteor_js_resource=true:61:20411)
    at https://app.refapp.se/02171ba37de34beaffd62ffe624a50ecfb585c99.js?meteor_js_resource=true:61:24198
    at n.XHRCorsObject.t.onfinish (https://app.refapp.se/02171ba37de34beaffd62ffe624a50ecfb585c99.js?meteor_js_resource=true:61:25422)
    at n.XHRCorsObject.i.emit (https://app.refapp.se/02171ba37de34beaffd62ffe624a50ecfb585c99.js?meteor_js_resource=true:61:7120)
    at XMLHttpRequest.s.xhr.onreadystatechange (https://app.refapp.se/02171ba37de34beaffd62ffe624a50ecfb585c99.js?meteor_js_resource=true:61:17166)
```

**Comment by zuus-keith** [comment] 2019-09-30 01:08
> Oh, and I get two variants of _didClose errors which are both picked up by montiapm (Kadira).
I believe both these errors are the same but the first error is coming from Chrome clients and the other are from Safari clients respectively.

**Comment by jamesmillerburgess** [comment] 2019-09-30 03:16
For us the issue was that we had tried to turn on Apollo subscriptions using the Meteor webapp internals. Deleting that line made the error go away, but now we need to look for a different way to enable subscriptions.

**Comment by klaussner** [comment] 2019-09-30 20:06
Judging from some of the comments above, the error can occur if WebSockets are disabled for DDP. If GraphQL subscriptions are configured as `WebApp` middleware, the DDP socket is closed in favor of the subscription socket and SockJS (the WebSocket library that Meteor uses for DDP) uses an XHR polling fallback instead. Maybe a SockJS update could help?

**Comment by brendonlamb** [comment] 2019-10-01 00:40
We're not using GraphQL for anything in our application and are experiencing the same error. 

We do use some vanilla Meteor subscriptions, including one for the logged in user.

This month in APM:

![image](https://user-images.githubusercontent.com/1816511/65926063-2c5fd680-e3a8-11e9-817f-a13c92f5b3ba.png)

Annoyingly, I haven't been able to reproduce this once on any of my physical devices or virtual ones... but clearly it's happening quite a bit. :(

Any speculation on whether this could be breaking the page/render entirely?

**Comment by jamesmillerburgess** [comment] 2019-10-01 02:57
For us it didn’t break the page or render, but it was getting us penalized by Google for having a javascript error on load.

**Comment by stolinski** [comment] 2019-10-01 15:32
I'm using GraphQL, but I don't think this error is related as we've been getting it since using Meteor/Blaze. I'd really love a solution to this as it gives us a ton of grief in our exception tracking tools.

**Comment by perbergland** [comment] 2019-10-02 06:53
So if I understand correctly (please correct me if I've misunderstood), the sockjs library is always used through the socket-stream-client meteor package and if the websocket connection fails  (corporate firewall issues? weird mobile phones?), it uses http calls to emulate websockets.
socket-stream-client brings in a very old sockjs implementation - 0.3.4

https://github.com/meteor/meteor/blob/devel/packages/socket-stream-client/sockjs-0.3.4.js

sockjs is currently at 1.4.0 - https://github.com/sockjs/sockjs-client and seems like a very different beast

Is it even feasible to bring in an updated sockjs?

**Comment by perbergland** [comment] 2019-10-06 07:47
Here's the relevant feature request - not sure if the feature request repo is reviewed at all anymore tbh:
https://github.com/meteor/meteor-feature-requests/issues/41

**Comment by mathieustan** [comment] 2019-12-17 16:33
We also have this error. We have received it more frequently since the upgrade from Meteor to 1.8.2.

**Comment by filipenevola** [comment] 2019-12-19 11:20
@mathieustan what is your server setup? Where are you running your app?

I checked a few Meteor apps that I have and I don't see this error at all but I'm running all my apps on Galaxy and because of that I think this could be related to server setup (nginx, proxy, load balancer, etc).

**Comment by brendonlamb** [comment] 2019-12-19 15:01
@filipenevola I know you weren't asking me but I figured this might be helpful.

We're running Meteor 1.8.2 with React 16.5.2 across three containers on Galaxy, I've seen 85 instances of this error in the last week, we're averaging about 120 client connections throughout this time:

Error: Error: INVALID_STATE_ERR

/5d24ee20d265e8b7e8592a014b713a6d0add7d03.js?meteor_js_resource=true:61:20271
/5d24ee20d265e8b7e8592a014b713a6d0add7d03.js?meteor_js_resource=true:61:24069
/5d24ee20d265e8b7e8592a014b713a6d0add7d03.js?meteor_js_resource=true:61:25288
/5d24ee20d265e8b7e8592a014b713a6d0add7d03.js?meteor_js_resource=true:61:6967
/5d24ee20d265e8b7e8592a014b713a6d0add7d03.js?meteor_js_resource=true:61:17013

This trace is the same for all of them, it happens on seemingly every page. Happy to dive deeper if there's anything else I can supply lmk. Cheers.

**Comment by banjerluke** [comment] 2019-12-19 17:26
Just to offer another data point: I've been getting INVALID_STATE_ERRs for ages. I'm on Meteor 1.8.1 right now but I was happening on 1.7 and probably several versions before that. Meteor is running in a simple node-based Docker image behind an haproxy load balancer. Standard Blaze/DDP stack. WebSockets are enabled and working fine according to DevTools.

Upon browsing through Sentry's reports (which include breadcrumbs of user activity), it seems that this error generally (though not exclusively) occurs after the page has been dormant (no user interactions) for long periods of time. Seems to happen on all browsers and devices. I haven't been able to connect it to any adverse behavior so I finally used a filter in Sentry to stop tracking the error.

**Comment by perbergland** [comment] 2019-12-22 15:00
I seem to get this error only from IE 11 clients.

Here's a typical call stack:
```
Error: INVALID_STATE_ERR
  at T.prototype._didClose @ https://app.redacted.com/e5c5d372d05c9d56811593b5e70e34af44b47161.js?meteor_js_resource=true:422:15147
  at Anonymous function @ https://app.redacted.com/e5c5d372d05c9d56811593b5e70e34af44b47161.js?meteor_js_resource=true:422:18946
  at onfinish @ https://app.redacted.com/e5c5d372d05c9d56811593b5e70e34af44b47161.js?meteor_js_resource=true:422:20178
  at a.prototype.emit @ https://app.redacted.com/e5c5d372d05c9d56811593b5e70e34af44b47161.js?meteor_js_resource=true:422:1761
  at a.xhr.onreadystatechange @ https://app.redacted.com/e5c5d372d05c9d56811593b5e70e34af44b47161.js?meteor_js_resource=true:422:11898
```

This error comes as part of a package of other errors so it's not sure which of them are only secondary errors.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/2690254/71323492-2de6f980-24d4-11ea-9157-03e92051f24f.png">

**Comment by pmogollons** [comment] 2019-12-24 12:13
@filipenevola It seems that this error doesn't cause any problems facing the user. As stated in the original post, the error is thrown [here](https://github.com/meteor/meteor/blob/24865b28a0689de8b4949fb69ea1f95da647cd7a/packages/socket-stream-client/sockjs-0.3.4.js#L1087) and [here](https://github.com/meteor/meteor/blob/24865b28a0689de8b4949fb69ea1f95da647cd7a/packages/socket-stream-client/sockjs-0.3.4.js#L1220).

It throws only on the _didClose callback when the connection is in an already closed state. And in send function when the state is CONNECTING.

So this issue is more an ask about if the error can be ignored completely (as it appears it can because Meteor should retry the send op after connecting) and if it can be ignored, should it be better to just log a warning or something instead of throwing that error? Or maybe throw an error with a more clear explanation.

**Comment by wildhart** [comment] 2020-01-15 21:42
I'm also getting these errors in my APM logs, but only from Android.  It's usually when a user is logged in.  It doesn't seem to cause any user side-effects because one of the users was my root 'dashboard' account and I didn't notice anything and none of my subscribers have complained.

Meteor v1.8.1.  Digital Ocean deployed with MUP, just standard pub/sub with mongo.

![image](https://user-images.githubusercontent.com/12505024/72473767-42f14700-384c-11ea-834b-4c9a271212bc.png)

![image](https://user-images.githubusercontent.com/12505024/72473620-f86fca80-384b-11ea-8916-79ab2650847a.png)

![image](https://user-images.githubusercontent.com/12505024/72473657-06255000-384c-11ea-86bd-71ab43c362b9.png)

**Comment by perbergland** [comment] 2020-02-17 10:49
I still get a lot of these from different browsers.
Here's from February (Datadog graph for the browser log)
![image](https://user-images.githubusercontent.com/2690254/74647195-8a386380-517b-11ea-8bb8-098ee5ce3e03.png)

**Comment by perbergland** [comment] 2020-02-17 10:52
I wonder if there's anyone still around that understand the sockjs/ddp source code well enough to dare to make any changes in this area, e.g. update sockjs to a recent version?

These kind of core changes to Meteor are not for the weak hearted...

**Comment by perbergland** [comment] 2020-03-20 11:35
Adding a comment to unstale it. Nothing has improved, still an issue

**Comment by focus97** [comment] 2020-04-16 03:43
Sentry alerted us about this tonight. Pinging this again to make sure it's not stale.

**Comment by brendonlamb** [comment] 2020-04-30 14:52
We're still getting this on both Chrome 81 both Windows 10 and MacOS 10.14

It appears to happen when the tab has been idle/inactive for sometime and then re-focused.

![image](https://user-images.githubusercontent.com/1816511/80724350-be12fc00-8acf-11ea-9e92-62cf648d73bf.png)

I think it was mentioned somewhere before but, maybe something to do with the web socket connection being interrupted/disconnected?

It doesn't appear to affect UX but it would be nice to know more about this.

**Comment by perbergland** [comment] 2020-06-01 15:51
Not stale

**Comment by IkKan** [comment] 2020-06-08 14:49
Not stale

**Comment by rpong** [comment] 2020-06-18 18:59
definitely NOT stale.

**Comment by filipenevola** [comment] 2020-06-24 13:20
I believe everyone that is experiencing this error is not getting any back feedbacks from their users or errors in the UI, should we replace this throws by debug logs or even nothing?

If we decide that is the way to go we could write a PR and release this change asap.

**Comment by stolinski** [comment] 2020-06-24 15:42
Yeah, that's my situation. No actual bugs, just this popping up in my Sentry logs.

**Comment by po-jo** [comment] 2020-06-24 15:57
Yes, same here !

**Comment by banjerluke** [comment] 2020-06-24 16:51
Same here. I eventually filtered these out of Sentry in my beforeSend handler (included below).

<details>
<summary>My filtering code</summary>
<br>
I'm including the whole thing in case folks find it useful; lots of Blaze-specific niceties in here. The relevant lines for this error are marked, about halfway down.<br>

```js

Sentry.init({
  dsn: Meteor.settings.public?.sentryDsn,
  release: Meteor.gitCommitHash,
  environment: /* function that returns "production" or something else based on ROOT_URL, etc.  */
  beforeBreadcrumb(breadcrumb, hint) {
    if ( breadcrumb.category == 'ui.click' ) {
      breadcrumb.message = breadcrumb.message.replace(/div#__blaze-root > /, '');
      breadcrumb.message = breadcrumb.message.replace(/(^| )(div|span)(\.|#)/g, '$1$3');
    }
    if ( /^Exception from Tracker (afterFlush|recompute) function:/.test(breadcrumb.message) ) return null;
    if ( /^Exception in template helper:/.test(breadcrumb.message) ) return null;
    if ( breadcrumb.category == 'xhr' ) return null;
    return breadcrumb;
  },
  beforeSend: (event) => {
    if ( typeof event.exception == 'object' && typeof (event.exception.values||[])[0] == 'object' ) {
      let message = event.exception.values[0].value;

      // filter out errors we don't want to track
      if ( /MSIE|Trident\/7\./g.test(navigator.userAgent) ) return null;  // IE is dead to me
/* ----- THESE ARE THE RELEVANT LINES: ----- */
      if ( /^INVALID_?STATE_?ERR(OR)?/i.test(event.exception.values[0].type) ) return null;
      if ( /^INVALID_?STATE_?ERR(OR)?/i.test(message) ) return null;
/* ----- */
      if ( /^Exception in template helper:/.test(message) ) return null;
      if ( /^Exception from Tracker (afterFlush|recompute) function:/.test(message) ) return null;
      if ( message == "Method invocation might have failed due to dropped connection. Failing because `noRetry` option was passed to Meteor.apply. [invocation-failed]" ) return null;
      if ( window.location.protocol == 'file:' ) return null;

      // handle Tracker errors
      if ( event.exception.values[0].type == 'Error' && /^[a-z]+: .+\n {4}at/i.test(message) && (event.exception.values[0].stacktrace||{}).frames ) {
        let matches = /^([a-z]+): (.+)\n/i.exec(message);
        event.exception.values[0].type = matches[1];
        event.exception.values[0].value = matches[2];
      }
    }

    return (!Meteor.isDevelopment || Meteor.isCordova) ? event : null;
  }
});

```

</details>

**Comment by brendonlamb** [comment] 2020-06-24 17:00
I still see it in APM, personally i'd replace the throw with debug logs, anything to point at a root cause or give us more info.

My main concern is whether or not this could be a red (or yellow) flag for Google- we aim to minimize client-side JS errors all together page-breaking or not.

**Closed** 2020-07-17 20:10 UTC
Labels: pinned

**Comment by filipenevola** [comment] 2020-07-17 20:12
Published socket-stream-client@0.3.1.         

I didn't change the other place that is throwing this error as I didn't see anybody complaining about that place, all stack traces that I saw were from _didClose function.

**Comment by hridayeshgupta-iticks** [comment] 2020-07-24 07:34
We are using Meteor 1.8.1/sockjs 0.3.4 and still get lot of these errors on Sentry. I have also noticed these errors come when it is xhr connections instead of websockets. Any way to fix this? as this is eating up all of our error quota on Sentry.

**Comment by filipenevola** [comment] 2020-08-10 22:04
Hey @hridayeshgupta-iticks are you using socket-stream-client@0.3.1.?

**Comment by hridayeshgupta-iticks** [comment] 2020-08-11 01:43
Hi @filipenevola .meteor/versions file shows socket-stream-client@0.2.2
When meteor package is published and I check the sourcemap, it shows sockjs-0.3.4.js file under socket-stream-client.

**Comment by filipenevola** [comment] 2020-08-13 10:40
@hridayeshgupta-iticks this was fixed on socket-stream-client@0.3.1. So you need to update your socket-stream-client package. Are you running latest Meteor (1.10.2)? If you run `meteor update` in your project Meteor will try to update all your dependencies.

**Comment by ksinas** [comment] 2020-10-23 10:30
Same issue brought me to this topic. However had to solve it myself :) I found out that the problem was a load balancer with multiple instances behind and without sticky sessions.

Some clients for some reason doesn't have websockets enabled. Then it falls back to polling. When sessions are not sticky, each request goes to another server and then you get 404 while doing a handshake. And you get into an infinite loop. If a user doesn't close the tab, you get a burst of requests and thousands of logs.

We are using AWS ALB, which allows to enable sticky sessions. This solved the issue.

**Comment by technicalbirdVayuz** [comment] 2021-04-20 13:31
HI @ksinas, Can you share the solution please?

**Comment by ksinas** [comment] 2021-04-21 07:20
@technicalbirdVayuz As I mentioned, we are using AWS elastic beanstalks with ALB. And here's an article about sticky sessions. https://docs.aws.amazon.com/elasticloadbalancing/latest/application/sticky-sessions.html

**Comment by technicalbirdVayuz** [comment] 2021-04-21 12:12
Tried the same but does not work. Its currently an infinite loop. & Meteor.calls are also not working

**Comment by po-jo** [comment] 2021-08-24 12:54
Just happened to me as I was browsing our app (good connection, macbook pro 2019 with a recent chrome => websocket supported) . As a user, we see everything re-loading (including Methods calls). Meteor.status was 'reconnecting' for about ~5 seconds. That seems odd since our app loads <100ms most of the time. 
We are using heroku with sticky sessions, Meteor2.1

**Comment by jamesloper** [comment] 2021-09-17 15:55
Some more info, in the context of Google crawler, It looks like you get `INVALID_STATE_ERR 3` when Google has not allocated, or does not have enough fetch quota.

**Comment by AndyNormore** [comment] 2022-01-02 05:18
Was able to fix this by adding:

socket-stream-client

to .meteor/packages

Then I cleared my Cloudflare CDN, purged cache, development mode

Then I cleared my browser cache on Chrome, issue seems resolved
