### ISSUE TITLE
"[name], this is your first time using Meteor!" is incorrect and mildly annoying

### ISSUE THREAD

**Issue by foobarbecue** [meteor/meteor#7424] opened 2016-07-17 17:59 UTC
When installing meteor, there's always a message that says,

"[username], this is your first time using Meteor!"

It's not. I just have to re-install meteor often.

How about "Meteor installation not found for user [aaron]. Installing." or words to that effect?

**Comment by abernix** [comment] 2016-07-18 12:14
Congratulations, you've been assigned issue number 7424!

But closing because it'd be more beneficial to identify and fix the problems requiring you to reinstall which should have their own separate issues (and probably already do).  

I'm pretty sure the next message after that is `Installing a Meteor distribution in your home directory` which aside from the formalities of Meteor trying to be polite and get you excited, is really the relevant part.

**Comment by foobarbecue** [comment] 2016-07-18 20:00
Haha, well I shouldn't have used "re-install" I suppose. I meant I have to install it a lot, on various different servers and things.

You're right, `Installing a Meteor distribution in your home directory` is the relevant part of the message. Something professional like "meteor installation not found" before that would be good. But get rid of the weirdly condescending, unprofessional, exclamation of noob-courtship.

**Comment by abernix** [comment] 2016-07-22 07:08
Ok, really closing this time, however if you came up with a pull request and reference this issue then it's up to the core team if they agree with you.

I'm marking this as `can't-reproduce` because I do not get the same "weirdly condescending unprofessional exclamation of noob-courtship" feelings as you.

**Closed by abernix** 2016-07-22 07:08 UTC
Labels: bug, can't-reproduce, Impact:few, Project:Installer, Severity:has-workaround
