### ISSUE TITLE
Windows 10 Installation Error

### ISSUE THREAD

**Issue by novialim** [meteor/meteor#9023] opened 2017-08-17 21:42 UTC
![image](https://user-images.githubusercontent.com/5988605/29435046-467f9a10-835a-11e7-9ba7-3ed066169aa2.png)

Windows installation seems successful without any error but running meteor on cmd gives above error.

**Comment by hwillson** [comment] 2017-10-13 16:35
This is a duplicate of https://github.com/meteor/meteor/issues/7439. Closing - thanks!

**Closed by hwillson** 2017-10-13 16:35 UTC
