### ISSUE TITLE
[1.4.0.1] Deferred imports (reify) not working.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#7646] opened 2016-08-14 22:21 UTC
I'm giving deferred imports a try, but no luck. I'm getting a syntax error on the [imports that are not at the top level](https://github.com/trusktr/meteor/blob/a3ebfa566a46c32f386bc3f94a9acbf9f31f2984/meteor-app/client/C.js#L8-L9).

Here's the [reproduction](https://github.com/trusktr/meteor/tree/a3ebfa566a46c32f386bc3f94a9acbf9f31f2984) which you can run with the `run-dev.sh` script.

EDIT: reproduction steps:

``` sh
git clone git@github.com:trusktr/meteor.git --branch issue-7646 --single-branch
cd meteor
./run-dev.sh
```

**Comment by benjamn** [comment] 2016-08-15 14:08
This reproduction works just fine for me. Please investigate further and reopen this issue when/if you have more details to provide. Thanks!

**Comment by trusktr** [comment] 2016-08-17 02:56
I keep having this problem. For example:

![screen shot 2016-08-16 at 7 54 46 pm](https://cloud.githubusercontent.com/assets/297678/17723006/6245f904-63eb-11e6-84ec-9436f0f09f5a.png)


![screen shot 2016-08-16 at 7 55 42 pm](https://cloud.githubusercontent.com/assets/297678/17723013/6f990ea2-63eb-11e6-81da-c558537e192f.png)

**Comment by trusktr** [comment] 2016-08-17 03:02
@benjamn I can reproduce by running the following in Mac OS X:

```sh
git clone git@github.com:trusktr/meteor.git
cd meteor
git checkout a3ebfa566a46c32f386bc3f94a9acbf9f31f2984
./run-dev.sh
```

then visiting localhost:7654, in which case I see the following on my screen:

![screen shot 2016-08-16 at 8 01 37 pm](https://cloud.githubusercontent.com/assets/297678/17723113/462164ec-63ec-11e6-9480-209571c5cdfc.png)

![screen shot 2016-08-16 at 8 02 09 pm](https://cloud.githubusercontent.com/assets/297678/17723118/551ac196-63ec-11e6-8358-cc540f72a736.png)

**Comment by trusktr** [comment] 2016-08-17 03:03
Seems like my import statements aren't being transpiled?

**Comment by trusktr** [comment] 2016-08-21 04:33
Re-opened in #7683.

**Comment by abernix** [comment] 2016-09-15 13:44
Re-opening this issue for better continuity since it has more information and closing the (now duplicate) #7683.

**Comment by abernix** [comment] 2016-09-26 10:33
Marking as confirmed as this behavior does appear on the client in your repo.

**Comment by hwillson** [comment] 2017-02-27 18:11
The original repro is now working after updating to Meteor 1.4.3.1:

![screenshot 2017-02-27 13 09 57](https://cloud.githubusercontent.com/assets/137740/23373471/28e35304-fcee-11e6-820f-48caf130876d.png)

There are no longer any errors on the client side and all `console.log` statements are working. I'll close this off - thanks for posting this originally!

**Closed by hwillson** 2017-02-27 18:11 UTC
Labels: bug, confirmed, Impact:few, Severity:has-workaround
