### ISSUE TITLE
Match.Optional inside a Match.ObjectIncluding behaves differently in dev and production

### ISSUE THREAD

**Issue by chfritz** [meteor/meteor#9374] opened 2017-11-15 19:43 UTC
Version: Meteor 1.4.4.2
OS: ubuntu 14.04

### Observed behavior

The following test passes in development but fails in production:
```
Match.test({name: "test"}, Match.ObjectIncluding({ name: String, a: Match.Optional(String) }))
```

### Expected Behavior

Dev and production to behave the same. The [documentation](http://docs.meteor.com/api/check.html#matchpatterns) seems to suggest that the test should *fail*, because by my read the use of `ObjectIncluding` requires all mentioned keys, even if their value is declared as `Optional`:

> Match.ObjectIncluding({ key1: pattern1, key2: pattern2, … })
> Matches an Object with the given keys; the value may also have other keys with arbitrary values.

### To reproduce:

To test the behavior in dev, just `meteor shell` into any dev meteor app and run the above command. You will get:

```
> Match.test({name: "test"}, Match.ObjectIncluding({ name: String, a: Match.Optional(String) }))
true
```

To test in production, either write the test into an app, or, like I did, add the following to the server of a bare-bones meteor app, create the production bundle and run it.
```
    fs.unlink('/tmp/shell.sock', function() {
        net.createServer(function (socket) {
            var r = repl.start({
                prompt: '[' + process.env.ROOT_URL + '] > '
                , input: socket
                , output: socket
                , terminal: true
                , useGlobal: false
              });
              r.on('exit', function () {
                socket.end();
              });
              r.context.socket = socket;
          }).listen('/tmp/shell.sock');
      });
```
Then you can connect to the running meteor process similar to a meteor shell using:
```
nc -U /tmp/shell.sock
```
In that shell, run the same command and you will get:
```
[http://localhost:3000] > Match.test({name: "test"}, Match.ObjectIncluding({ name: String, a: Match.Optional(String) }))
Match.test({name: "test"}, Match.ObjectIncluding({ name: String, a: Match.Optional(String) }))
false
```

**Comment by chfritz** [comment] 2017-11-15 20:08
Somehow it only happens when there is another required field. If the `name` field in the example is no longer required, then the `Match.Optional` behaves in production like in dev:
```
[http://localhost:3000] >  Match.test({}, Match.ObjectIncluding({ a: Match.Optional(String) }))
 Match.test({}, Match.ObjectIncluding({ a: Match.Optional(String) }))
true
```

**Comment by hwillson** [comment] 2018-02-13 17:57
Hi @chfritz - is this still a problem? If so could you please provide a small, runnable reproduction that demonstrates this issue? You've outlined a few reproduction steps, but the devil is in the details somewhere, as I'm not able to re-create this issue. I'm getting `true` when using the Meteor Tool and when running this `Match.test` in a production application.

**Comment by chfritz** [comment] 2018-03-02 05:59
I still seem to be getting this. But it's even more obscure than I thought.

Create a new meteor 1.6.1 app.
Replace `server/main.js` with this:
```js
import { Meteor } from 'meteor/meteor';
import { Match } from 'meteor/check'

import fs from 'fs';
import net from 'net';
import repl from 'repl';

fs.unlink('/tmp/shell.sock', function() {
  net.createServer(function (socket) {
    var r = repl.start({
      prompt: '[' + process.env.ROOT_URL + '] > ',
      input: socket,
      output: socket,
      terminal: true,
      useGlobal: false
    });
    r.on('exit', function () {
      socket.end();
    });
    r.context.socket = socket;
    r.context.Match = Match;
  }).listen('/tmp/shell.sock');
});

Meteor.startup(() => {
  // code to run on server at startup
  const result = Match.test(
    {name: "test"},
    Match.ObjectIncluding({
      name: String,
      a: Match.Optional(String)
    })
  );
  console.log("result", result);
});
```

Then run:
```
meteor build --directory /tmp/test
cd /tmp/test
(cd programs/server && npm install)
export MONGO_URL='mongodb://localhost:27017/test'
export ROOT_URL='http://example.com'
node main.js
```
It will print "result true". **But** if you now attach to that process using `sudo nc -U /tmp/shell.sock` and run
```js
Match.test({name: "test"}, Match.ObjectIncluding({ name: String, a: Match.Optional(String) }))
```
it will give you `false`.

Normally I would guess that the REPL somehow behaves differently from the "normal" run-time environment. But we've seen this in production runs as well. Unfortunately I'm not sure how to minimally reproduce that part.

**Comment by hwillson** [comment] 2018-03-09 18:05
Unfortunately I think this is definitely a case of the REPL behaving differently. Every `Match.test` I try using netcat returns `false`:

![screenshot 2018-03-09 13 01 10](https://user-images.githubusercontent.com/137740/37222172-2d682dea-239a-11e8-8b86-f10126259c5d.png)

While there could be an issue here somewhere, it's going to unfortunately be very difficult to track down using this method. If you have any other ideas or details that could help narrow this one down, please post them here. In the meantime however, since we can't effectively show that there is a bug here, I'll close this for now. Happy to re-open in the future as needed. Thanks!

**Closed by hwillson** 2018-03-09 18:05 UTC
