### ISSUE TITLE
 RangeError: Maximum call stack size exceeded doesn't print stack trace

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4991] opened 2015-08-19 08:07 UTC
I reoganized my app into packages and when I start it up, this is all I get

```
W20150819-01:06:11.543(-7)? (STDERR) 
W20150819-01:06:11.544(-7)? (STDERR) /Users/chet/.meteor/packages/meteor-tool/.1.1.4.1uijw63++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150819-01:06:11.544(-7)? (STDERR) 						throw(ex);
W20150819-01:06:11.544(-7)? (STDERR) 						      ^
W20150819-01:06:11.544(-7)? (STDERR) RangeError: Maximum call stack size exceeded
```

This message is very unhelpful and disheartening

**Comment by ccorcos** [comment] 2015-08-19 08:40
Wow. I really fucked up. I created a variable `setTimeout = (ms,f) -> Meteor.setTimeout(f,ms)` because I like coffeescript. Well then I exported it from my package which... well yeah.

**Comment by ccorcos** [comment] 2015-08-19 08:40
That said, I think there ought to be a stack trace here!

**Comment by stubailo** [comment] 2015-08-19 18:00
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by ccorcos** [comment] 2015-08-19 19:35
Sorry about that. Thats a very valid point. Here's a minimal reproduction app:

```
if (Meteor.isServer) {
  f = Meteor.wrapAsync(function(callback) {
    f()
  })
  f()
}
```

**Comment by newsiberian** [comment] 2016-02-20 19:29
Hello, after updating to `1.3-beta.11` I'm getting the similar error:
```
W20160221-01:25:57.826(6)? (STDERR) 
W20160221-01:25:57.828(6)? (STDERR) /home/sohaam/.meteor/packages/meteor-tool/.1.1.13-beta.11.or25it++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160221-01:25:57.828(6)? (STDERR) 						throw(ex);
W20160221-01:25:57.828(6)? (STDERR) 						      ^
W20160221-01:25:57.828(6)? (STDERR) RangeError: Maximum call stack size exceeded
```
repro repo: [here](https://github.com/newsiberian/reaction/tree/max-call-stuck-repro)

**Comment by koolaang** [comment] 2016-03-23 23:00
I am getting same error after updating to  1.3-beta.12

**Comment by maxnowack** [comment] 2016-09-21 11:43
I have a similar issue. Due the lack of the callstack, analyzing is much complicated. I cannot reproduce the issue locally. It only occurs on our production environment.


I see the following errors in my logs:
````
/app/bundle/programs/server/packages/meteor.js:1175
 Fiber(runWithEnvironment).run();
 ^

RangeError: Maximum call stack size exceeded
````

````
/app/bundle/programs/server/packages/ddp-server.js:1507
 }).run(); // 1386
 ^

RangeError: Maximum call stack size exceeded
````

Does anyone have an idea how I can get more informations, where the error originally come from?


@newsiberian I'm getting a 404 if I try to open your reproduction repo. Is it possible for you to fix the link?

**Comment by codeHatcher** [comment] 2016-09-21 23:44
I'm having a similar issue, normally I would add the debug-brk option but seems we can no longer do that in 1.4

**Comment by abernix** [comment] 2016-09-23 07:02
I'm going to close this issue because the issue as originally described is no longer the case.   Using 1.4.1.1 and adding the reproduction (above) to any server source file clearly shows a stack trace back to the original file which caused the issue.

To those who are just generally experiencing `RangeError: Maximum call stack size exceeded` errors, that is far too vague of an error which is quite typical from many JavaScript environments when using particular circular reference styles.  Circular references are notoriously hard to debug in any language.  With or without Meteor sometimes the stack trace is not included simply because the compiler wasn't able to generate it, which is even more likely in asynchronous situation calls.  If you can provide a reasonable reproduction repo demonstrating a problem with Meteor, then this can be looked at, but otherwise there is nothing that anyone can help with here aside from "help me debug my code".  This does not appear to be a bug in Meteor.

@codeHatcher If you are referring to the development environment, please consider using `meteor debug` in combination with using the `debugger;` statement in your code.  For production (i.e. `meteor bundle`-ized) deployments, normal Node [debugging](https://nodejs.org/dist/latest-v4.x/docs/api/debugger.html) tools (e.g. [`node-inspector`](https://github.com/node-inspector/node-inspector)) do work fine, however source maps are not available which makes tracing errors a bit more tedious since code is run through `uglify` before going to production (for security/optimization reasons).  In other words, `myHelfulVariableName` ends up being just `z` and unless you've got a stealthy eye for following the code, it can get a bit overwhelming/impossible.  #4384 is open for this currently.  If you're experiencing another reproducible error that isn't addressed with what I've suggested here, please open a new issue with the necessary reproduction steps.

**Closed by abernix** 2016-09-23 07:02 UTC
Labels: Project:JS Environment

**Comment by lamass** [comment] 2017-02-25 15:50
Trying to install meteor: after the install, when i type in the cli meteor i get: 
C:\Users\tonya>meteor
C:\Users\tonya\AppData\Local\.meteor\packages\meteor-tool\1.4.3_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\q\q.js:70
    hasStacks = !!e.stack;
                   ^

RangeError: Maximum call stack size exceeded

what to do? Any assistance, please?

**Comment by RafaelLiendo** [comment] 2017-03-24 04:55
@lamass, https://github.com/meteor/meteor/issues/7896#issuecomment-285356886 this worked for me!

**Comment by mroftalp** [comment] 2017-07-19 08:07
I'm experiencing the same as @maxnowack. Have you or anyone found a solution for this? Also just happens on production environment

**Comment by maxnowack** [comment] 2017-07-19 08:21
@mroftalp no, I haven't found a solution for this

**Comment by mroftalp** [comment] 2017-07-27 05:19
@abernix I am getting this error same as @maxnowack. 
Meteor version: 1.5.1

![image](https://user-images.githubusercontent.com/6789191/28655365-07348862-72ce-11e7-92fb-c64e749cdb61.png)

**Comment by abernix** [comment] 2017-07-27 07:15
@mroftalp I would check the more active, currently open issue https://github.com/meteor/meteor/issues/7896 for suggestions!
