### ISSUE TITLE
Autoprefixing on Imported files

### ISSUE THREAD

**Issue by bduff9** [meteor/meteor#7762] opened 2016-09-08 17:27 UTC
I opened an issue over at fourseven as well as at meteor postcss, and both told me essentially that what I need cannot be done currently in Meteor.

Similar to #5219, I would like to be able to have my sass files autoprefixed.  However, what I am doing is manually bringing them into each page by importing them.  This allows me to avoid any conflicts and ensure the right styles are loaded on each page.  This works great, however the files are not being processed and so do not have any css prefixes in the output.

If I instead put all stylesheets into client and then let Meteor autoload them for me, it does work so I do not think it is a config issue.  Is this something that is currently impossible and if so, is it something that might work in the future?  Or, if I am doing this wrong, what is a better way to only bring in specific styles on each page that will work with autoprefixing?  Thanks!

**Comment by abernix** [comment] 2016-09-16 07:14
I'm under the impression that developers are already accomplishing this through the use of [`juliancwirko:postcss`](https://github.com/juliancwirko/meteor-postcss) in conjunction with the [`autoprefixer` NPM package[(https://www.npmjs.com/package/autoprefixer) (and associated configuration in `package.json`).  Those docs lead me to believe that it is in-fact possible.

Irregardless, your issue as posted is essentially multiple questions and not a bug or a feature request ([guidelines](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests)).  If what you desire is, in fact, not currently possible with Meteor, I would encourage you to work hand-in-hand with the package developers who require this feature and submit a feature-request issue documenting the Meteor APIs that would be required.  I would assume that some of these packages already have a plan/desire in mind and there might already be other issues open to address those.

Closing.

**Closed by abernix** 2016-09-16 07:14 UTC

**Comment by mitar** [comment] 2016-09-27 19:11
See #7727 pull request for my work on this feature.
