### ISSUE TITLE
Spiderable package with Facebook Open Graph

### ISSUE THREAD

**Issue by eternalwaves** [meteor/meteor#3270] opened 2014-12-10 22:52 UTC
Not sure if this is an issue specifically with the spiderable package or something else. When I view source of my site [Beehive.codes](https://beehive.codes) using `?_escaped_fragment_=`, it renders fine. When I view it through FB's [https://developers.facebook.com/tools/debug/og/object/](Open Graph Debugger), I get the following error message:

> Meta Tags in Body
> Your page has meta tags in the body instead of the head. This may be because your HTML was malformed and they fell lower in the parse tree.
> Please fix this in order for the tags to be usable.

**Comment by glasser** [comment] 2015-01-12 20:23
Interesting. I'm not sure what you're referring to as far converting HTML entities goes; where do we do that? Maybe Phantom does this automatically somehow?

A reproduction would help us see what you're talking about: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

A pull request to fix this (with a full explanation of how to test) would be great.

**Comment by hwillson** [comment] 2017-02-10 19:49
Hi all - deprecating the `spiderable` package is currently being considered. The reasons for this include:

- Google has deprecated the [AJAX crawling specification](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) that the `spiderable` package is based on;
- Search engine crawlers (like Google's) have gotten much better at dealing with javascript/AJAX based applications, without the need for any special handling;
- There are now several better options for SEO goodness, like pre-rendering services (e.g. [Prerender.io](https://prerender.io/) - recommended in the Guide's [Enabling SEO](https://guide.meteor.com/deployment.html#seo) section and [supported out of the box with Galaxy](http://galaxy-guide.meteor.com/seo.html)), server-side rendering techniques, etc.

As such, I'll close this issue off for now. If anyone feels like this is a bad decision and can justify why `spiderable` should not be deprecated, please post back with your reasons. Thanks for opening this issue originally!

P.S. --> Anyone who wants to keep using the `spiderable` package after it has been deprecated will still be able to, by version pinning to the last non-deprecated version of `spiderable`.

**Closed by hwillson** 2017-02-10 19:49 UTC
Labels: Project:Webapp:Spiderable, pull-requests-encouraged
