### ISSUE TITLE
--unsafe-perm flag doesn't work with `meteor build`

### ISSUE THREAD

**Issue by jay-depot** [meteor/meteor#7964] opened 2016-10-26 05:30 UTC
`meteor --unsafe-perm build --directory ../app-name`

Outputs: 

```
You have run Meteor as root. Your permissions in your app directory will be incorrect if you ever attempt to perform any Meteor tasks as your non-root user. You probably didn't want this, but you can fix it by running the following from
the root of your project:

sudo chown -Rh <username> .meteor/local

'../app-name' is not a Meteor command. See 'meteor --help'.
```

Any other permutation causes Meteor to insist `--unsafe-perm` is not a valid parameter.

This is an URGENT issue, as it is currently breaking deployments for basically everyone using Docker.

**Comment by jay-depot** [comment] 2016-10-26 05:35
To be fair, we're on Meteor 1.2.x, so I'm sure this has something to do with it, but we simply cant upgrade.

**Comment by weasel-science** [comment] 2016-10-26 07:04
I second this issue. Our Docker building pipeline is failing, and switching to non-root building is not feasible on such short notice (we have hotfixes that need to be released)

**Comment by abernix** [comment] 2016-10-26 08:58
Duplicate of #7959.  It does work with `meteor build` but the issue is if your actual app is running a pre Meteor 1.4.2.  I will update #7959 momentarily.

**Closed by abernix** 2016-10-26 08:58 UTC
