### ISSUE TITLE
Cordova failing to fetch plugins from the Cordova Plugin Registry

### ISSUE THREAD

**Issue by ApostolisApo** [meteor/meteor#4207] opened 2015-04-15 18:59 UTC
Hi just tried to build my app and got this error. 

Error while running for mobile platforms: Error running /Users/apostolis/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.console/-/org.apache.cordova.console-0.2.13.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.console/-/org.apache.cordova.console-0.2.13.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.console/-/org.apache.cordova.console-0.2.13.tgz
Error: getaddrinfo ENOTFOUND
at errnoException (dns.js:37:11)
at Object.onanswer [as oncomplete] (dns.js:124:16)

Fetching plugin "org.apache.cordova.console@0.2.13" via plugin registry

**Comment by Slava** [comment] 2015-04-15 19:03
Looks like you failed to download a plugin from the Cordova registry. Make sure you are connected to the Internet and you have your proxy configured for the CLI tools (if you use proxy at all).

This can also be an issues with the Cordova plugin registry.

**Comment by ApostolisApo** [comment] 2015-04-15 19:07
maybe it is the registry because:

1) everything started working until i installed mdg:camera (what is mug? can it be that it messed up my registry? how can i see that? i ll try with a new app without the camera dependency and update)
2) i know i m on the internet :D

**Comment by coderany** [comment] 2015-04-15 19:10
Same problem. http://cordova.iriscouch.com/ not resolve

**Comment by sschepis** [comment] 2015-04-15 20:06
Same problem here.

**Comment by kickandrew** [comment] 2015-04-15 20:38
+1

**Comment by klismark** [comment] 2015-04-15 20:59
Same problem here.

**Comment by sschepis** [comment] 2015-04-15 21:17
this isn't a meteor problem - iriscouch.com has been down all morning. A search reveals that this isn't the first time this has happened.  Waiting until the site is back up seems to be the remedy here.

**Comment by Slava** [comment] 2015-04-16 00:24
Please, report here if you see the problem being resolved.

**Comment by BillSwift** [comment] 2015-04-16 01:09
Not yet. The site is still down and I still get same error.

**Comment by fungilation** [comment] 2015-04-16 01:11
cordova.iriscouch.com is down to me too, similar NPM fetch errors on cordova build.

**Comment by maverix** [comment] 2015-04-16 01:49
+1 - Same here.  Can we get around this by having a local copy?

**Comment by BillSwift** [comment] 2015-04-16 02:22
Working!

**Comment by fungilation** [comment] 2015-04-16 02:44
Works now. But +1 on a -offline flag, for starting meteor with local cordova packages only when shit happens.

**Comment by Slava** [comment] 2015-04-16 02:54
What is this offline flag? Do you have a link to a description how it works?

**Comment by rjerrems** [comment] 2015-04-16 03:12
+1 Same issue here, would be good to see it work offline.

**Comment by Slava** [comment] 2015-04-16 04:17
Meteor tool doesn't download the plugins directly. Meteor tool calls the cordova-cli, that fetches and stores the plugins on its own. It does have some caching, obviously you cannot cache everything you will ever need.

Closing this as the registry is back up online.

**Closed by Slava** 2015-04-16 04:17 UTC
Labels: Project:Mobile

**Comment by rjerrems** [comment] 2015-04-16 04:19
Fair enough, thanks @Slava

**Comment by guilhermedecampo** [comment] 2015-05-23 18:58
I'm still having this problem 

```
meteor run ios --settings /Users/Guilherme/Documents/project/project/config/development/settings.json
Error while running for mobile platforms: Error running
/Users/Guilherme/.meteor/packages/meteor-tool/.1.1.3.14z5cw5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh


/Users/Guilherme/.meteor/packages/meteor-tool/.1.1.3.14z5cw5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/src/cli.js:115
console.error(err.stack);
^
TypeError: Cannot read property 'stack' of undefined
at process.<anonymous>
(/Users/Guilherme/.meteor/packages/meteor-tool/.1.1.3.14z5cw5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/src/cli.js:115:30)
at process.emit (events.js:95:17)
at process._fatalException (node.js:295:26)


Fetching plugin "org.apache.cordova.console@0.2.13" via plugin registry
```

Can you confirm if registry offline @Slava ?

Thanks!

**Comment by Slava** [comment] 2015-05-23 19:35
@guilhermedecampo no, your error looks unrelated to this issue.

**Comment by guilhermedecampo** [comment] 2015-05-23 22:25
@Slava, thanks for the answer. Indeed I just had some problems with permissions here. 

For anyone with this problem: delete and reinstall meteor.

Cheers.

**Comment by akshaychauhan7737** [comment] 2017-07-08 16:03
i am getting problem 

```
 Failed to install 'cordova-plugin-media': CordovaError: Failed to fetch plugin cordova-plugin-file@^4.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN cordova-plugin-file-transfer@1.5.1 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN LearnApp@1.1.1 No repository field.
npm WARN LearnApp@1.1.1 No license field.
```

**Comment by nicholasaleks** [comment] 2017-07-28 23:32
Getting the same issue but for pushwoosh-cordova-plugin on ios

```
%% Calling plugman.fetch on plugin "cordova-plugin-device@2.1.3"
%% Fetching plugin "cordova-plugin-device@2.1.3" via npm
=> Errors executing Cordova commands:

   While adding plugin cordova-plugin-device@2.1.3 to Cordova project:
   Cordova error: Failed to fetch plugin cordova-plugin-device@2.1.3 via registry.
   Probably this is either a connection problem, or plugin spec is incorrect.
   Check your connection and plugin name/version/URL.
   Error: version not found: cordova-plugin-device@2.1.3
```

**Comment by yuvaraj119** [comment] 2017-09-05 02:26
I also getting the same error still 

`D:\Ionic and Cordova> ionic cordova plugin add de.appplant.cordova.plugin.local-notification
> cordova plugin add de.appplant.cordova.plugin.local-notification --save
× Running command - failed!
[ERROR] An error occurred while running cordova plugin add

        de.appplant.cordova.plugin.local-notification --save (exit code 1):

        Installing "de.appplant.cordova.plugin.local-notification" for android
        Plugin dependency "cordova-plugin-device@1.1.4" already fetched, using that

        version.
        Dependent plugin "cordova-plugin-device" already installed on android.
        Failed to install 'de.appplant.cordova.plugin.local-notification':
        CordovaError: Failed to fetch plugin cordova-plugin-app-event via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! code ENOLOCAL
        npm ERR! Could not install from "node_modules\cordova-plugin-app-event" as
        it does not contain a package.json file.

        npm ERR! A complete log of this run can be found in:
        npm ERR!
        C:\Users\Yuva\AppData\Roaming\npm-cache\_logs\2017-09-05T02_18_46_788Z-debu
g.log
             at
        C:\Users\Yuva\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova
-lib\src\plugman\fetch.js:205:33
             at _rejected
        (C:\Users\Yuva\AppData\Roaming\npm\node_modules\cordova\node_modules\cordov
a-fetch\node_modules\q\q.js:864:24)
             at
        C:\Users\Yuva\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova
-fetch\node_modules\q\q.js:890:30
             at Promise.when
        (C:\Users\Yuva\AppData\Roaming\npm\node_modules\cordova\node_modules\cordov
a-fetch\node_modules\q\q.js:1142:31)
             at Promise.promise.promiseDispatch
        (C:\Users\Yuva\AppData\Roaming\npm\node_modules\cordova\node_modules\cordov
a-fetch\node_modules\q\q.js:808:41)
             at
        C:\Users\Yuva\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova
-fetch\node_modules\q\q.js:624:44
             at runSingle
        (C:\Users\Yuva\AppData\Roaming\npm\node_modules\cordova\node_modules\cordov
les\cordova\node_modules\cordova-fetch\node_modules\
q\q.js:137:13)
             at flush                               les\cordova\node_modules\cordov
        (C:\Users\Yuva\AppData\Roaming\npm\node_modu
les\cordova\node_modules\cordova-fetch\node_modules\ess/next_tick.js:73:7)
q\q.js:125:13)                                      ess/next_tick.js:104:9)
             at _combinedTickCallback (internal/proc-app-event via registry.
ess/next_tick.js:73:7)                              , or plugin spec is incorrect.
             at process._tickCallback (internal/procn/URL.
ess/next_tick.js:104:9)                             Error output:
        Error: Failed to fetch plugin cordova-plugin
-app-event via registry.                            s\cordova-plugin-app-event" as
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! code ENOLOCAL
        npm ERR! Could not install from "node_modules\cordova-plugin-app-event" as
        it does not contain a package.json file.

        npm ERR! A complete log of this run can be found in:
        npm ERR!`

**Comment by abernix** [comment] 2017-09-05 06:33
This is a super old issue involving Cordova with the Meteor framework.  The last three updates don't even make it clear whether or not users are using Meteor (and I'm fairly sure the most recent certainly isn't.).

If you're still experiencing an issue, and you're using the Meteor framework, please open a new issue and include information about what version of Meteor you're using, along with reproduction instructions based on a new Meteor project.

Thanks!
