### ISSUE TITLE
[bug] [1.3-modules-beta.2] import * fails with an error

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5874] opened 2015-12-23 23:07 UTC
Trying to do something like

```js
import * as foo from './foo'
```

fails with an error in the browser:

```js
Uncaught TypeError: babelHelpers.interopRequireWildcard is not a function
  meteorInstall.app.src.client.config.routes.utilities.js @ utilities.js:5
  fileEvaluate                                            @ install.js:183
  require                                                 @ install.js:75
  meteorInstall.app.src.client.config.routes.index.js     @ index.js:6
  fileEvaluate                                            @ install.js:183
  require                                                 @ install.js:75
  (anonymous function)                                    @ app.js?hash=3cc4b471ccc6efbb3976924b77fd96ea30aa0190:32042
  (anonymous function)                                    @ app.js?hash=3cc4b471ccc6efbb3976924b77fd96ea30aa0190:32077
```

As a workaround, I put all the export in an object, then just exported the object as `default`, which works fine.

**Comment by avital** [comment] 2015-12-24 04:40
Dupe of #5872

**Closed by avital** 2015-12-24 04:40 UTC
