### ISSUE TITLE
Error spawn ENOMEM

### ISSUE THREAD

**Issue by ThomasArbona** [meteor/meteor#4535] opened 2015-06-10 16:57 UTC
Hello everyone,

When I launch meteor, this error appears:

```
/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at Object.exports.spawn (child_process.js:746:9)
    at [object Object]._.extend._spawn (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:254:31)
    at [object Object]._.extend.start (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:84:22)
    at [object Object]._.extend._runOnce (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:701:16)
    at [object Object]._.extend._fiber (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:821:28)
    at /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:402:12
```

So, I have tried to delete a pictures folder in /public (this folder weigh 2GB), and... it's work !
How can I run meteor without delete this pictures folder ?

Thank you in advance.

**Comment by stubailo** [comment] 2015-06-10 19:55
How much RAM and disk space do you have available?

**Comment by ThomasArbona** [comment] 2015-06-10 21:10
I have 4GB RAM, 20GB disk space on the current partition, and 1To in total.

**Comment by Slava** [comment] 2015-06-10 21:14
This is a duplicate of https://github.com/meteor/meteor/issues/1129

**Closed by Slava** 2015-06-10 21:14 UTC
