### ISSUE TITLE
Remove template dependencies from meteor-base

### ISSUE THREAD

**Issue by DerekTBrown** [meteor/meteor#7516] opened 2016-07-28 19:02 UTC
`meteor-base` includes a lot of blaze-specific dependencies which aren't great for users trying to use only React or Angular for templating.  For example, I want to use Angular2Meteor, but I don't want to include things like Blaze or JQuery on the client side (should be simple??).  However, the following dependency relationship exists:

meteor-base -> webapp -> boilerplate-generator -> spacebars -> blaze -> jquery

Thus preventing me from removing these dependencies.  Looking at the actual code, it seems that boilerplate-generator references both Blaze and the deprecated UI Library:

https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator/boilerplate-generator.js#L34

There are a couple of things we need to move forward on:

1) Refactor the boilerplate generator to remove dependency on Blaze
This should be pretty easy, but this requires enforcing a limited set of directives be passed into the extra data fields, which would break others' code.

2) Remove JQuery dependency from Blaze
This looks like it was something that was in the pipeline anyway- move forward?

https://github.com/meteor/meteor/blob/devel/packages/blaze/package.js#L8

**Comment by DerekTBrown** [comment] 2016-07-28 19:03
This seems to be a known issue:

https://github.com/meteor/meteor/issues/6844

**Comment by abernix** [comment] 2016-07-29 08:52
This seems like an exact duplicate of that issue.  Closing in favor of #6844.  Please add contribution to that issue! :)

**Closed by abernix** 2016-07-29 08:52 UTC
