### ISSUE TITLE
[1.4] Cannot pipe to or use multi-line in shell

### ISSUE THREAD

**Issue by mdorn** [meteor/meteor#7504] opened 2016-07-27 17:32 UTC
After upgrading to Meteor 1.4 (I'm on OS X 10.10.5), the Meteor shell is no longer useful for developing/debugging, because I cannot use multi-line statements (either typing or pasting them).  For example, if I want to declare a constant like this:

```
const ITEM_WITH_LOTS_OF_LINES = {
    a: 'foo',
    b: 'bar',
    c: 0,
    // etc.
}
```  

It fails after the first line:

```
> const ITEM_WITH_LOTS_OF_LINES = {
SyntaxError: Unexpected token (2:0)
    at Parser.pp.raise (/Users/mdorn/.meteor/packages/babel-compiler/.6.9.0.66tov5++os+web.browser+web.cordova/npm/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/mdorn/.meteor/packages/babel-compiler/.6.9.0.66tov5++os+web.browser+web.cordova/npm/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseIdentifier (/Users/mdorn/.meteor/packages/babel-compiler/.6.9.0.66tov5++os+web.browser+web.cordova/npm/node_modules/babylon/lib/parser/expression.js:1053:10)
    at Parser.pp.parsePropertyName (/Users/mdorn/.meteor/packages/babel-compiler/.6.9.0.66tov5++os+web.browser+web.cordova/npm/node_modules/babylon/lib/parser/expression.js:858:117)
    at Parser.pp.parseObj (/Users/mdorn/.meteor/packages/babel-compiler/.6.9.0.66tov5++os+web.browser+web.cordova/npm/node_modules/babylon/lib/parser/expression.js:774:12)
    at Parser.pp.parseExprAtom (/Users/mdorn/.meteor/packages/babel-compiler/.6.9.0.66tov5++os+web.browser+web.cordova/npm/node_modules/babylon/lib/parser/expression.js:486:19)
    at Parser.parseExprAtom (/Users/mdorn/.meteor/packages/babel-compiler/.6.9.0.66tov5++os+web.browser+web.cordova/npm/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
    at Parser.pp.parseExprSubscripts (/Users/mdorn/.meteor/packages/babel-compiler/.6.9.0.66tov5++os+web.browser+web.cordova/npm/node_modules/babylon/lib/parser/expression.js:272:19)
    at Parser.pp.parseMaybeUnary (/Users/mdorn/.meteor/packages/babel-compiler/.6.9.0.66tov5++os+web.browser+web.cordova/npm/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/Users/mdorn/.meteor/packages/babel-compiler/.6.9.0.66tov5++os+web.browser+web.cordova/npm/node_modules/babylon/lib/parser/expression.js:183:19)
```

This was not an issue with v1.3.2.

Incidentally this also makes the `.load` option in the shell useless.

**Comment by abernix** [comment] 2016-08-01 14:04
Thanks for reporting this!  This does in-fact appear to be a bug in the Meteor 1.4 REPL shell!

**Comment by abernix** [comment] 2016-08-02 06:31
For a similar reason, as reported by @veered, the following doesn't work:

    echo "console.log('hello');" | meteor shell

Presumably due to c91a95cbef89d8ba3676191fa51a1222fce2ea34

**Comment by veered** [comment] 2016-08-02 16:27
Thanks for your quick response! What do you think the timeline is for merging a fix for this? It has broken a lot of our internal tools which rely upon piping commands to the meteor shell.

**Comment by abernix** [comment] 2016-08-02 17:02
Unfortunately, I'm not positive as the easy fix (reverting that commit) didn't fix it for me so this will require more investigation.

**Comment by veered** [comment] 2016-08-02 22:00
I would like to note that trying to pipe to the meteor shell also failed on an old project running 1.3, so somehow it is broken globally.

**Comment by paulgrever** [comment] 2016-08-02 22:02
+1

**Comment by benjamn** [comment] 2016-08-03 14:22
The root cause seems to be that Babel parse errors are not passing [the `isRecoverableError` test](https://github.com/nodejs/node/blob/0974fc6a25c343744235331eb20d31f6412ff7e1/lib/repl.js#L1133-L1146) in the `node/lib/repl.js` code. That's definitely something I can fix!

**Closed** 2016-08-03 20:51 UTC
Labels: bug, confirmed, Impact:some, Project:Tool:Shell
