### ISSUE TITLE
No way to cancel the build in progress

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3892] opened 2015-03-09 18:07 UTC
If I change something in code and Meteor starts building things on change and this takes quite some time because of NPM packages, etc., and I change the file again in meantime, the Meteor does not stop currently running build process, but it continues working until it finishes, and then starts again a new one. I think this should be improved.

**Comment by glasser** [comment] 2015-03-09 18:11
Duplicate of #3011.

**Closed by glasser** 2015-03-09 18:11 UTC
