### ISSUE TITLE
TypeError in blaze.js after meteor upgrade from 1.0.5 to 1.1

### ISSUE THREAD

**Issue by solo999** [meteor/meteor#4112] opened 2015-04-02 18:47 UTC
What can cause below error:

Exception from Tracker recompute function: undefined
debug.js:43 TypeError: Cannot read property 'destroyMembers' of undefined
    at http://localhost:3000/packages/blaze.js?264be6a901108935eddf10209d174ed62a9bc64b:2031:17
    at http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:267:29
    at Object.Tracker.nonreactive (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:593:12)
    at Tracker.Computation.onInvalidate (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:266:13)
    at Object.Tracker.onInvalidate (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:610:30)
    at doRender (http://localhost:3000/packages/blaze.js?264be6a901108935eddf10209d174ed62a9bc64b:2030:15)
    at http://localhost:3000/packages/blaze.js?264be6a901108935eddf10209d174ed62a9bc64b:1865:18
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?264be6a901108935eddf10209d174ed62a9bc64b:3474:12)
    at http://localhost:3000/packages/blaze.js?264be6a901108935eddf10209d174ed62a9bc64b:1864:29
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?264be6a901108935eddf10209d174ed62a9bc64b:2195:12) undefined

**Comment by rclai** [comment] 2015-04-02 19:11
Taken care of [already](https://github.com/meteor/meteor/issues/4097).

**Comment by glasser** [comment] 2015-04-02 20:52
Duplicate of #4097.  1.1.0.1 is imminent.

**Closed by glasser** 2015-04-02 20:52 UTC
