### ISSUE TITLE
Meteor shell is buggy when using up-down-arrow keys to use last commands

### ISSUE THREAD

**Issue by thebarty** [meteor/meteor#5346] opened 2015-10-01 12:09 UTC
Hi guys,

I am using `meteor shell` on osx.

Entering each command manually works, but when using the **up-down-arrow keys**
to load the last used commands the shell **behaves buggy & is unusable**: basically the cursor is messed up and I am unable to edit the code when using the left-arrow key to go left.

Actually even when entering a new line and then using the left-arrow to set the cursor left the bug appears.

In detail: the previous line loads and I can fire it up again by hitting enter.
BUT when I want to go back to change something the cursor is messed up.

If you need more info: let me know.

**Comment by benjamn** [comment] 2015-10-06 22:07
What shell are you using (e.g. `bash` or `zsh`, which you can determine by typing `echo $SHELL`)? And are you using the OSX `Terminal.app`, or something more exotic?

**Comment by thebarty** [comment] 2015-10-07 09:29
Hi Ben,

I am using osx Terminal.app with 10.10.05.

**Comment by rhyslbw** [comment] 2016-04-25 06:37
Same issue here, using zsh shell via Terminal, iTerm, WebStorm

**Comment by abernix** [comment] 2016-05-12 10:08
@thebarty Do you experience the same problems when using the Node shell? Just run `node` on the command line.

**Comment by abernix** [comment] 2016-05-28 08:47
@rhyslbw @thebarty Any updates on this?  I'd like to see if it's fixed in a newer version of node REPL, but need help reproducing it.

**Comment by rhyslbw** [comment] 2016-05-28 14:05
_Sorry @abernix, thanks for the follow-up._ 

The `node` REPL works as expected without this problem.
To reproducethe problem I'm seeing enter a command with over 50 characters and it should start overwriting the first characters of that same command. Also using the up and down arrow keys to cycle back through causes the active line to move up, overwriting the view of the previous output

**Comment by abernix** [comment] 2016-05-30 07:01
@rhyslbw Thanks for trying to explain.  Unfortunately, I still can't reproduce this.  Even pasting extremely long (anywhere from 50 to 8000), non-breaking lines (and also separately tested breaking lines), etc. etc. with both iTerm2 and OS X built-in Terminal.app.  Tried on Meteor 1.2.1 and 1.3.2.4.  Up-down Arrows, history, etc. all working fine.  I'm using `xterm-256color` for my terminal capabilities.

What do you get if you type `echo $TERM`?

**Comment by rhyslbw** [comment] 2016-05-30 07:33
`xterm-256color`

**Comment by abernix** [comment] 2016-09-28 09:17
@rhyslbw Can you try and see if this issue still exists for you?  The REPL integration has changed in Meteor 1.4 (and the underlying Node 4.x).  Since I've never been able to reproduce this problem, I cannot say if it does, but would be nice to close this issue! :smile:

**Comment by rhyslbw** [comment] 2016-10-06 02:15
@abernix Unfortunately I'm still having the same problem with Meteor 1.4.1.2

**Comment by abernix** [comment] 2016-10-06 16:24
I was able to accidentally reproduce this while trying to prove that it worked fine for me.  (That's what I get for rubbing it in your face, I guess? :smile:)

Anyhow, I'm _guessing_ that the window that you're running the `meteor` server from has a different number of "columns" (or terminal width) than the window that you're running the `meteor shell` command from.  (If you're not sure, you can check by running `tput cols` in each of the Windows).

(I realized this when I sizing my terminal windows smaller in order to take a smaller screen recording; I made my server window smaller to make more room on the screen and then found myself with the same problem.)

Right now, the "width" of the terminal is determined not by the client connecting to it, but the server which its connecting to.  So this problem can be avoided by having both terminals at the same width.

I think this might be made slightly better by having the client pass its width to the server when making the initial connection.  While this would still cause problems if the window was resized AFTER the connection was made, it would probably fix it for you.

Let me know if this sounds like it could be your problem.

**Comment by rhyslbw** [comment] 2016-10-08 09:51
Yep that appears to be the issue. I use WebStorm to run the app, then the WebStorm terminal to open a meteor shell instance so it sounds like the col value isn't consistent with this scenario. Not sure just flipping the responsibility at point of connection is going to be enough to put this to bed though, I quite often am resizing windows when jumping between portable mode and desktop mode with my notebook, and I can see this as a common use-case. Any further thoughts on keeping the server in sync with the client's current state?

**Comment by abernix** [comment] 2016-10-10 14:22
I posted some additional thoughts on [the commit for my proposed fix](https://github.com/abernix/meteor/commit/add0798a3af118d894a251f322fd9a19a71fea7b) from my (own repo) above:

> A more complete solution would be to have the client listen on process.stdout "resize" and pass that to the server when it occurs, but I'm not sure of an easy way to do that with the current communication (perhaps pause-reconfigure-unpause).

I agree that it's not put to bed, but it actually does not seem to be all that common of a problem (based on votes for this issue since it was opened) so I think prioritization will be the issue.  At least with the change I made, you'd simply have to Ctrl-C and re-`meteor shell` instead of restarting the Meteor server.

**Comment by johanbrook** [comment] 2016-12-09 16:49
This is still a huge annoyance for me. I'm always opting for `meteor mongo` for DB operations rather than the Meteor shell. When stepping with the arrows between characters on a line, it's also not corresponding to the actual cursor position.

I'm running iTerm with a vertical split window (thus the shell is on one half of the screen width).

![shell](https://cloud.githubusercontent.com/assets/437261/21056885/6b9c31a2-be05-11e6-9a8d-c536d54eb017.gif)

**Comment by abernix** [comment] 2016-12-09 17:06
@johanbrook Not saying this is the solution (I've made my suggestion above), but if you split horizontally instead of vertically, it should work properly. 🙂

**Comment by johanbrook** [comment] 2016-12-09 17:13
@abernix Eheh :) Well, I kinda prefer vertical split.

> So this problem can be avoided by having both terminals at the same width.

The server terminal is the same width as the shell terminal, actually.

**Comment by abernix** [comment] 2016-12-12 11:05
> Well, I kinda prefer vertical split.

Again, not saying it was a solution; you should certainly be able to do both! :smile:

> The server terminal is the same width as the shell terminal, actually

Hmm, if this is true, this defeats my entire analysis above.  Keep in mind that the width is currently stored a single time at `meteor run` start time so if it's resized after that, it will break.  Please try restarting both the server and the shell (in that order) when they are *already* in split screen mode.  Remember that different font sizes also constitute different widths!  You can run `tput cols` to show the current widths before running `meteor run` and `meteor shell`.

**Comment by johanbrook** [comment] 2016-12-12 14:45
Yep, your hypothesis is correct – I restarted everything (server + shell) and all linebreaks in the shell seems to work now.

**Closed** 2016-12-13 23:49 UTC
Labels: bug, confirmed, Project:Tool:Shell

**Comment by johanbrook** [comment] 2016-12-14 00:29
🚀 💖 Thanks!

**Comment by abernix** [comment] 2016-12-14 00:38
I don't think this is the "be all end all" of solutions but I do hope it makes it a lot less painless for those users who use this setup regularly.

Developers will still need to restart their `meteor shell` if they resize the window running it, but will no longer be constrained to using a shell that is the same width as the server.

**Comment by NitroBAY** [comment] 2017-02-22 16:36
It's not very convenient nor intuitive but at least there's a fix. Couldn't you define again width each time `meteor shell` is started ?
Thanks anyway.

**Comment by NitroBAY** [comment] 2017-02-22 16:40
Hello,
In cmder (Windows) copy pasting code from my IDE causes the bug described as above.
