### ISSUE TITLE
Support .meteorignore files to restrict which files can be compiled or imported by Meteor apps or packages

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6002] opened 2016-01-14 19:27 UTC
**_1 Upvote**_ This would help developers avoid issues like https://github.com/meteor/meteor/issues/5999, among other potential benefits.

The syntax should be the same as `.gitignore` or `.npmignore` files.

cc @avital

**Comment by avital** [comment] 2016-01-14 21:31
This, or something similar should resolve the following error we get when running `./meteor test-packages`:

```
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While processing files with templating (for target web.browser):
   packages/local-test:spacebars-tests/assets/markdown_basic.html:1: Expected one of: <body>, <head>, <template>
   packages/local-test:spacebars-tests/assets/markdown_each1.html:1: Expected one of: <body>, <head>, <template>
   packages/local-test:spacebars-tests/assets/markdown_each2.html:1: Expected one of: <body>, <head>, <template>
   packages/local-test:spacebars-tests/assets/markdown_if1.html:1: Expected one of: <body>, <head>, <template>
   packages/local-test:spacebars-tests/assets/markdown_if2.html:1: Expected one of: <body>, <head>, <template>

=> Your application has errors. Waiting for file change.
```

**Comment by dagatsoin** [comment] 2016-01-15 09:49
Could this prevent Meteor to continuous building the app when working with Webstorm? (I think the .idea folder triggers the build at each keystrock.)

**Comment by avital** [comment] 2016-01-21 17:18
@dagatsoin probably!

**Comment by acidicX** [comment] 2016-03-20 18:20
Yes please!
This has been an issue [since 2012](https://github.com/meteor/meteor/issues/330) by the way.

**Comment by cunneen** [comment] 2016-04-11 13:44
Can the `.meteorignore` file please include a setting to disable the aggressive parsing of files (js, css and  html) that are not explicitly included in the package.js of a local package?

(ref @avital's comments on [this thread](https://forums.meteor.com/t/help-us-test-build-times-in-meteor-1-3/15031/17)

**Comment by mjmasn** [comment] 2016-04-14 14:05
@benjamn this is becoming fairly critical for our app as we move to using es6 modules / the imports directory. Meteor is trying to compile HTML generated by Istanbul test coverage reports. Temporary workaround I've found is to set the coverage directory in .istanbul.yml as follows (html inside node_modules directory appears to be ignored):

```yaml
reporting:
  dir: "node_modules/__coverage"
```

**Comment by pletinsky** [comment] 2016-05-29 17:36
Folders started from dot (for example .something) will be ignored by the meteor build system inside of both root or specific package directory.
So it looks like a workaround.

**Comment by emilianosantucci** [comment] 2016-07-05 21:51
+1 for project with mixin platform like Meteor + Angular 2 + Polymer (last need exclusion from angular compiler)

**Comment by servel333** [comment] 2016-07-06 13:39
From #4958 and #330 

As a developer, I would like to have a way to include custom folders to be ignored by the Meteor file gobbler.

These could be

* unique files generated by my choice of editors
* files that are part of some tool I am using
* a `docs/` directory I put documentation in
* a `tmp/` directory I might put files that are not part of the codebase but are related to the project in
* personal notes files I put notes into (I sometimes put program extensions on them so I can put syntax highlighted code in my notes)
* etc.

### Possible solutions:

* Add an ignore file that works like `.gitignore` (List of regexes, `#` for comments, `!` to include files)
  * Possible file names: `.meteorignore` or `.meteor/ignore`, or both
* Add a config file that lists files and folders to be ignore
  * Possible file names: `.meteor/config.json`, `.meteor/preload.js`

### Notes

Implementation of this might allow for simplification of the [ignore rules built into Meteor](https://github.com/meteor/meteor/blob/devel/tools/isobuild/package-source.js#L1303) by removing editor-specific and platform-specific ignore rules to become part of the users project configuration.

**Comment by Batistleman** [comment] 2016-07-06 13:49
Hi @servel333, are you sure you would want to include these files in your app folder?

I typically have a setup like this:

    /project/
          /.idea #webstorm files
          /app #contains the meteor app
          /docs 
          /sandbox
          /mup
          /tmp
          /reactnativeapp

**Comment by servel333** [comment] 2016-07-06 16:32
You could structure your project this way, however some of the projects I've worked on I did not set up the directory structure and there was no app directory. Instead, the root of the project was the app directory. In this case I would still want to be able to ignore these kinds of files.

**Comment by jeffyamada** [comment] 2016-09-19 23:46
+1 This would make my life much much better.

**Comment by mitar** [comment] 2016-10-04 19:08
This would also help with #7598.

But I think in #7598 one should also simply not scan a package for all files if it does not depend on a `modules` package.

**Comment by scharf** [comment] 2016-10-14 18:33
I have a few directories with artifacts in `/private` and in `/public` that the server needs but the files in those directories are often regenerated. Whenever a file is regenerated, meteor starts a rebuild during development.

The only solution I came up with: we put those files into `.#whatever` directories during development (when meteor watch is running) and put them into their normal places for the meteor deployment.

There are some resources that are served by meteor in `/public/assets`. For those resources I remove them during the development and put them in a directory not visible by meteor (e.g. `/public/.#assets`

```js
import { WebApp } from "meteor/webapp";
var fs = require('fs');
var path = require('path');

// only if DEV_PUBLIC_ABS_PATH is set we serve files
if(process.env.DEV_PUBLIC_ABS_PATH) {
// see https://docs.meteor.com/packages/webapp.html
    WebApp.connectHandlers.use('/assets', function (req, res) {
        const asset = req.url;
        const absPath = path.join(process.env.DEV_PUBLIC_ABS_PATH, asset);

        let contentType = 'text/html'
        if(asset.match(/.*\.js$/i)) {
            contentType = 'application/javascript';
        } else if(asset.match(/.*\.js\.map$/i)) {
            contentType ='contentType';
        }
        res.writeHead(200, { 'Content-type': contentType });

        // send the file http://stackoverflow.com/a/10047018/2297345
        var readStream = fs.createReadStream(absPath);
        // We replaced all the event handlers with a simple call to readStream.pipe()
        readStream.pipe(res);
    });
}
```

**Comment by mitar** [comment] 2016-11-07 21:09
Just to make sure this will be implemented for packages as well. Not just for apps.

**Comment by mair0z** [comment] 2016-12-30 08:20
+1 .meteorignore
I want it so much! it will save me from the pain! :D

**Comment by ejfrancis** [comment] 2017-01-06 01:26
+1

**Comment by joncursi** [comment] 2017-02-14 05:39
This is also problematic for users with custom npm scripts that are written outside of package.json. If you put your scripts in a `scripts/` directory, Meteor tries to take control of them

**Comment by mitar** [comment] 2017-02-14 05:40
Workaround for now: put them inside `.scripts`.

**Comment by joncursi** [comment] 2017-02-14 05:42
Confirmed the workaround, thanks @mitar !

**Comment by eskan** [comment] 2017-04-06 10:54
+1 to .meteorignore

**Comment by javoire** [comment] 2017-05-23 18:56
My use case is that a 3d party node module bundle `require`s some devDependencies, that I have to install manually to get my app to work. Being able to tell Meteors bundle to skip those erroneous files would be useful... until they real problem is fixed... :)

**Comment by hwillson** [comment] 2017-06-07 01:28
This has been migrated to https://github.com/meteor/meteor-feature-requests/issues/5 - closing here. Thanks!

**Closed by hwillson** 2017-06-07 01:28 UTC
Labels: confirmed, feature, pull-requests-encouraged
