### ISSUE TITLE
Unknown package error, while package clearly exists....

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#7721] opened 2016-08-27 09:36 UTC
Often when adding a package to the 'use' list of another package, I get an error that the package does not exist, while I'm sure it does.

E.g.:

```
C:\Users\seba\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: Depending on unknown package pbastowski:angular-babel
    at Error (native)
    at processUse (C:\tools\isobuild\package-source.js:1707:15)
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\seba\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\package-source.js:1717:9
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\seba\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at PackageSource.getPackagesToLoadFirst (C:\tools\isobuild\package-source.js:1712:7)
    at IsopackCache._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:238:39)
    at C:\tools\isobuild\isopack-cache.js:76:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\seba\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at [object Object].eachPackage (C:\tools\packaging\package-map.js:49:7)
    at IsopackCache.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:75:24)
    at C:\tools\project-context.js:781:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (C:\tools\project-context.js:780:18)
    at C:\tools\project-context.js:268:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:258:18)
    at C:\tools\project-context.js:250:12
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:249:13)
    at C:\tools\runners\run-app.js:548:29
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundleApp (C:\tools\runners\run-app.js:547:31)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:625:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:884:28)
    at C:\tools\runners\run-app.js:402:12
```

Stopping and restarting meteor gives the same error. Only when executing a `meteor reset`, the problem is gone and the package is added.

**Reproduction**
If you checkout this repo:
https://github.com/sebakerckhof/meteor-7721

Start the app, and while it's running, uncomment this line:
https://github.com/sebakerckhof/meteor-7721/blob/master/packages/foo/package.js#L12
you should get the error.

**Comment by laosb** [comment] 2016-08-27 11:16
That's might be related to cache?

**Comment by laosb** [comment] 2016-08-27 11:18
Can you provide a reproduction? That might be hard, but without it we can't do much on it.

**Comment by cesarve77** [comment] 2016-08-27 11:53
Same issue

for reproduction
Just remove meteor 
  sudo rm /usr/local/bin/meteor
  rm -rf ~/.meteor

instal meteor 
  curl https://install.meteor.com/ | sh

> meteor create --package user:test

in /package/test/package.js insert
api.use(['aldeed:autoform'])

run meteor
 
and you will get

Error: Depending on unknown package aldeed:autoform

but if you install the package direct into app
>meteor add aldeed:autoform

compile again, it works
maybe some with cache?


sorry for me inglish

**Comment by laosb** [comment] 2016-08-27 13:52
Ah, that's must be something with cache.

**Comment by queso** [comment] 2016-09-02 14:56
Getting the same issue here on 1.4.0.1

**Comment by cesarve77** [comment] 2016-09-02 15:01
I solved updating meteor all packages and try again

**Comment by raphaelarias** [comment] 2016-09-16 07:28
Same issue here. meteor reset resolves.

**Comment by peterchoo** [comment] 2016-12-02 15:59
If you're in a situation like me where you are working on an application where you cannot update meteor, you can delete `meteor/local/resolver-result-cache.json` - this forces Meteor to re-cache the packages available.

**Comment by cpury** [comment] 2017-03-10 04:15
This is still happening to me every time I add a new package and it's very annoying. If I was new to Meteor, this would frustrate me a lot. Can't we add a fallback to when a package is not found in the cache, it checks once more if the package is actually present or not?

**Comment by chrisbutler** [comment] 2017-03-14 00:30
jesus fucking christ this should not still be an issue

**Comment by chrisbutler** [comment] 2017-06-26 18:45
seems like this has been an issue for a while, any ETA on a fix?

**Comment by rubenpa** [comment] 2017-06-26 18:48
Running meteor update my:package works for me, but this would be a very convenient fix.

**Comment by hwillson** [comment] 2017-09-13 13:00
If anyone is still encountering this problem with a recent version of Meteor (>= 1.5.2), please provide a reproduction recipe to help with troubleshooting (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Without reliable reproduction steps, there isn't much to go on here. I'll close this for now, but I'm happy to re-open this issue if anyone is still seeing this happen, and can provide a repro. Thanks!

**Comment by sebakerckhof** [comment] 2017-09-14 12:19
@hwillson this still exists in meteor >= 1.5.2 and can easily be reproduced.
If you checkout this repo:
https://github.com/sebakerckhof/meteor-7721

Start the app, and while it's running, uncomment this line: 
https://github.com/sebakerckhof/meteor-7721/blob/master/packages/foo/package.js#L12
you should get the error.

**Comment by hwillson** [comment] 2017-09-14 12:21
Thanks for the repro @sebakerckhof - re-opening.

**Comment by hwillson** [comment] 2018-03-05 15:39
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity (see the [bug issue lifespan](https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/ISSUE_TRIAGE.md#bug-issue-lifespan) section of Meteor's traige doc for more information). If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!

**Closed by hwillson** 2018-03-05 15:39 UTC
Labels: Impact:few, Project:Isobuild, Severity:has-workaround, bug, confirmed, not-implemented, pull-requests-encouraged

**Comment by damon-t** [comment] 2021-05-17 11:51
I am facing the same issue with the latest meteor version.

My reproduction steps are:

1. meteor create --blaze newproject --release 2.2
2. cd newproject
3. meteor create --package newpackage
4. add api.use('reactive-dict'); to package.js

as soon as the package is added meteor crashes with this error:

`C:\Users\damon\AppData\Local\.meteor\packages\meteor-tool\2.2.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^
Error: Depending on unknown package reactive-dict
    at processUse (C:\tools\isobuild\package-source.js:1548:15)
    at Function..each..forEach (C:\Users\damon\AppData\Local\.meteor\packages\meteor-tool\2.2.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:186:9)
    at C:\tools\isobuild\package-source.js:1558:9
    at Function..each..forEach (C:\Users\damon\AppData\Local\.meteor\packages\meteor-tool\2.2.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:186:9)
    at PackageSource.getPackagesToLoadFirst (C:\tools\isobuild\package-source.js:1553:7)
    at IsopackCache._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:232:39)
    at C:\tools\isobuild\isopack-cache.js:75:14
    at C:\tools\packaging\package-map.js:57:7
    at Function..each..forEach (C:\Users\damon\AppData\Local\.meteor\packages\meteor-tool\2.2.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:191:9)
    at exports.PackageMap.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at IsopackCache.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:74:24)
    at C:\tools\project-context.js:890:25
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._buildLocalPackages (C:\tools\project-context.js:889:18)
    at C:\tools\project-context.js:300:9
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:290:18)
    at C:\tools\project-context.js:282:12
    at Function.run (C:\Users\damon\AppData\Local\.meteor\packages\meteor-tool\2.2.0\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:289:14)       
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:281:13)
    at C:\tools\runners\run-app.js:556:29
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at bundleApp (C:\tools\runners\run-app.js:555:31)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:627:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:948:28)
    at C:\tools\runners\run-app.js:410:12`
