### ISSUE TITLE
HTML.Raw rendering issue in Meteor 1.5 : not rendering <input type="checkbox"/> 

### ISSUE THREAD

**Issue by cicode225** [meteor/meteor#8967] opened 2017-07-29 22:14 UTC
Hello,

First time reporting an issue.

It seems that `HTML.Raw` cannot render `<input type="checkbox"/>` 

```
Template.body.addContent((function() {
  var view = this;
  return HTML.Raw('<input type="checkbox">\n  <input type="submit" value="Submit">');
}));
Meteor.startup(Template.body.renderToDocument);
```

The above code (taken from browser code inspector) will only show in my browsers one submit button and no check box

 (Firefox 54.0.1 (32 bits) and Chrome Version 60.0.3112.78 (64 bits))

**Comment by klaussner** [comment] 2017-07-30 09:37
I can't reproduce the issue. This is the result I get with your code snippet:
![8967-1](https://user-images.githubusercontent.com/1312807/28752248-f93a4b3a-751a-11e7-84a4-f8dfd07b9548.png)
![8967-2](https://user-images.githubusercontent.com/1312807/28752245-de07c612-751a-11e7-8d08-6a49b7331f0e.png)
Have you checked the Inspector/Elements tab in the developer tools to see if the checkbox is in the DOM?

**Comment by cicode225** [comment] 2017-07-31 13:20
@klaussner 
Thank you. After looking in DOM I saw it there. Then after a little googling, I saw the issue is not about meteor (if I'm correct) but mainly about `materialzeCSS`  According to [this](https://github.com/Dogfalo/materialize/issues/1376), checkboxes have to be coded like this : `<input type="checkbox" id="checkbox_id"><label for="checkbox_id">custom_label</label>`

**Comment by hwillson** [comment] 2017-08-01 15:33
Sounds like we're okay to close this one off - thanks for looking into this @klaussner!

**Closed by hwillson** 2017-08-01 15:33 UTC
