### ISSUE TITLE
After Upgradation to Meteor 1.2.0.2, TypeError: Property 'undefined' of object [object Object] is not a function. ( /fibers/future.js) 

### ISSUE THREAD

**Issue by rakeshashetty** [meteor/meteor#5352] opened 2015-10-02 02:17 UTC
=> Started proxy.                             
=> Started MongoDB.                           
W20151002-07:43:48.644(5.5)? (STDERR)         
W20151002-07:43:48.646(5.5)? (STDERR) /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151002-07:43:48.646(5.5)? (STDERR) 						throw(ex);
W20151002-07:43:48.646(5.5)? (STDERR) 						      ^
W20151002-07:43:48.646(5.5)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20151002-07:43:48.646(5.5)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20151002-07:43:48.647(5.5)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20151002-07:43:48.647(5.5)? (STDERR)     at /Users/rakeshashetty/Projects/Meteor/latest_build/pranachallenge/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
W20151002-07:43:48.647(5.5)? (STDERR)     at /Users/rakeshashetty/Projects/Meteor/latest_build/pranachallenge/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
W20151002-07:43:48.647(5.5)? (STDERR)     at /Users/rakeshashetty/Projects/Meteor/latest_build/pranachallenge/.meteor/local/build/programs/server/boot.js:242:10
W20151002-07:43:48.647(5.5)? (STDERR)     at Array.forEach (native)
W20151002-07:43:48.647(5.5)? (STDERR)     at Function._.each._.forEach (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151002-07:43:48.647(5.5)? (STDERR)     at /Users/rakeshashetty/Projects/Meteor/latest_build/pranachallenge/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8

**Comment by mikeislearning** [comment] 2015-10-02 09:30
I have the exact same error!

**Comment by rakeshashetty** [comment] 2015-10-02 14:26
Thanks Mike... For me Issue was with meteortoys:allthings
But now i am facing an issue with meteor build .build --server='...'
                                                                                     
/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: ENOENT, no such file or directory
  at process.chdir (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:18:9)
  at process.chdir (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/graceful-fs/polyfills.js:14:9)
  at CordovaProject.runCommands (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova/project.js:749:15)
  at CordovaProject.buildForPlatform (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova/project.js:263:10)
  at /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/commands.js:897:28
  at /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:352:18
  at [object Object]._.extend.withValue (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:345:34
  at [object Object]._.extend.withValue (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:343:23
  at [object Object]._.extend.withValue (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at Object.enterJob (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:317:26)
  at /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/commands.js:894:24
  at /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:264:13
  at [object Object]._.extend.withValue (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:257:29
  at [object Object]._.extend.withValue (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:255:18
  at [object Object]._.extend.withValue (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:246:23
  at [object Object]._.extend.withValue (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at Object.capture (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:245:19)
  at Object.main.captureAndExit (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/main.js:257:29)
  at /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/commands.js:873:12
  at buildCommand (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/commands.js:918:7)
  at Command.main.registerCommand._.extend.name [as func] (/Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/commands.js:728:10)
  at /Users/rakeshashetty/.meteor/packages/meteor-tool/.1.1.9.a1gwwp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/main.js:1227:23

**Comment by stubailo** [comment] 2015-10-13 21:02
Duplicate of https://github.com/meteor/meteor/issues/5332

**Closed by stubailo** 2015-10-13 21:02 UTC
