### ISSUE TITLE
[meteor 1.3.2-rc.4] .babelrc support yet ?

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#6794] opened 2016-04-12 04:24 UTC
dear everyone !
i tested meteor 1.3.2-rc.4, this work great import style ( less + sass) from node_modules !
that perfect ! Woohoo !
i don't know this version support .babelrc yet ? i need plugin: jsx-control-statements.

thanks so much !

**Comment by skirunman** [comment] 2016-04-14 16:27
Looks like this is being tracked here #6351. If you add your question to the current open issue (and close this one) you'll probably get a better response.

**Comment by abernix** [comment] 2016-05-18 13:30
Duplicate of #6351.  Please +1 that if you have interest this functionality.

**Closed by abernix** 2016-05-18 13:30 UTC
