### ISSUE TITLE
minimongo and mongo disagree on an edge case involving `$or`, array indexes, and null

### ISSUE THREAD

**Issue by massimosgrelli** [meteor/meteor#3946] opened 2015-03-17 14:18 UTC
Making a small change in publication code of my project I got through this exception:

```
I20150317-15:04:09.146(1)? Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"$or":[{"type":"*"},{"createdByUser":null},{"partyIds.0":null}]}
I20150317-15:04:09.146(1)?     at Error (<anonymous>)
I20150317-15:04:09.147(1)?     at packages/mongo/oplog_observe_driver.js:827:1
I20150317-15:04:09.147(1)?     at Object.Meteor._noYieldsAllowed (packages/meteor/fiber_helpers.js:11:1)
I20150317-15:04:09.147(1)?     at [object Object]._.extend._publishNewResults (packages/mongo/oplog_observe_driver.js:797:1)
I20150317-15:04:09.147(1)?     at [object Object]._.extend._runQuery (packages/mongo/oplog_observe_driver.js:704:1)
I20150317-15:04:09.147(1)?     at [object Object]._.extend._runInitialQuery (packages/mongo/oplog_observe_driver.js:617:1)
I20150317-15:04:09.148(1)?     at packages/mongo/oplog_observe_driver.js:164:1
I20150317-15:04:09.148(1)?     at packages/mongo/oplog_observe_driver.js:16:1
I20150317-15:04:09.148(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150317-15:04:09.148(1)?     at packages/meteor/timers.js:6:1
```

The query that is causing the failure is this:

```
Meteor.publish('channels', function() {
    return Channels.find({$or : [{"type" : '*'}, {"createdByUser": this.userId}, {"partyIds.0" : this.userId}]});
});
```

and Channels collection is structured like in this sample ─ db.channels.find():

```
{
    "createdByUser" : "JqsHcufcuJNcMXzQy",
    "name" : "public",
    "partyIds" : [ ],
    "type" : "*",
    "_id" : "4QFpA6JrWSEgWqeYY"
}
{
    "_id" : "oFBXNdeyLQoQMsnQF",
    "createdAt" : 1426528800282,
    "createdByUser" : "AjRBHTJqFSqNJJns8",
    "name" : "whatsapp",
    "partyIds" : [
        "8G2aGEXEwsWAiBHk5"
    ],
    "type" : "#"
}
{
    "createdByUser" : "oFBXNdeyLQoQMsnQF",
    "name" : "massimo-john",
    "type" : "@",
    "partyIds" : [
        "AjRBHTJqFSqNJJns8",
        "8G2aGEXEwsWAiBHk5"
    ],
    "createdAt" : 1426528848479,
    "_id" : "pBsFDwphjEB2bdrPa"
}
```

PartyIds field is an array which can have 0 to N elements ─ IDs. I observed that if I change the query to:

```
Channels.find({$or : [{"type" : '*'}, {"createdByUser": this.userId}, {"partyIds" : this.userId}]});
```

the problem seems to disappear.

Am I doing something wrong?

P.S. The failure is visible during Login and Logout phases, otherwise it seems to work well.

**Comment by glasser** [comment] 2015-03-17 21:38
Yeah, this seems like an edge case in how Mongo (and Meteor) interpret the combination of explicit array indexes and null.  (BTW, are you intending this publication to run when there is no user logged in?)

Do you see this in development or just in production?  What version of MongoDB are you using?

If you can make this into a cloneable reproduction as described in https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor it will vastly improve the probability that we can track this down and fix it.

**Comment by glasser** [comment] 2015-03-17 21:39
(BTW, MongoDB has actually changed the semantics of edge cases like this multiple times between versions without even mentioning this in release notes.  We do our best to track the most recent semantics, but that does mean that you can run into these edge cases.  Ideally, if you can find a way to write your app without depending on strange MongoDB edge cases, it will make your app more resilient and comprehensible :)  But I'd still like to fix it!)

**Comment by BackSpaceTech** [comment] 2016-01-07 17:54
I have the same issue using $all.
db.workorders.find({"asset_treePath":{$all:["aWy5v43QWpDFF997d","u7iqLKGG8XSvEbXWh"]}})
in Mongo produces this data:
```
{ "_id" : "ucvXfDwTFHKnE7HA9", "type" : "workorder", "reqBy_id" : "3o2CMStNQFRwutE77", "reqByFirstName" : "Paul", "reqByLastName" : "Coady", "reqDate" : ISODate("2016-01-07T16:38:03Z"), "status" : "1", "asset_ID" : "u7iqLKGG8XSvEbXWh", "asset_treePath" : [ "aWy5v43QWpDFF997d", "u7iqLKGG8XSvEbXWh" ], "assetID" : "u7iqLKGG8XSvEbXWh", "assetText" : "Site 1", "refID" : "300", "reqPriority" : "3", "reqDescription" : "Test work request" }
{ "_id" : "sLPyZ4YSenkydybee", "type" : "workorder", "reqBy_id" : "3o2CMStNQFRwutE77", "reqByFirstName" : "Paul", "reqByLastName" : "Coady", "reqDate" : ISODate("2016-01-07T16:38:03Z"), "status" : "1", "asset_ID" : "u7iqLKGG8XSvEbXWh", "asset_treePath" : [ "aWy5v43QWpDFF997d", "u7iqLKGG8XSvEbXWh" ], "assetID" : "u7iqLKGG8XSvEbXWh", "assetText" : "Site 1", "refID" : "200", "reqPriority" : "3", "reqDescription" : "Test work request" }
```
but this in Meteor:
Workorders.find({"asset_treePath":{$all:["aWy5v43QWpDFF997d","u7iqLKGG8XSvEbXWh"]}}) produces:

```
I20160108-04:52:25.762(11)? Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"query":{"asset_treePath":{"$all":["aWy5v43QWpDFF997d","u7iqLKGG8XSvEbXWh"]},"reqBy_id":"3o2CMStNQFRwutE77"}}
I20160108-04:52:25.764(11)?     at Error (<anonymous>)
I20160108-04:52:25.764(11)?     at packages/mongo/oplog_observe_driver.js:880:1
I20160108-04:52:25.764(11)?     at Object.Meteor._noYieldsAllowed (packages/meteor/fiber_helpers.js:11:1)
I20160108-04:52:25.764(11)?     at [object Object]._.extend._publishNewResults (packages/mongo/oplog_observe_driver.js:850:1)
I20160108-04:52:25.765(11)?     at [object Object]._.extend._runQuery (packages/mongo/oplog_observe_driver.js:757:1)
I20160108-04:52:25.765(11)?     at [object Object]._.extend._runInitialQuery (packages/mongo/oplog_observe_driver.js:658:1)
I20160108-04:52:25.765(11)?     at packages/mongo/oplog_observe_driver.js:192:1
I20160108-04:52:25.765(11)?     at packages/mongo/oplog_observe_driver.js:16:1
I20160108-04:52:25.765(11)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160108-04:52:25.765(11)?     at packages/meteor/timers.js:6:1

**Comment by BackSpaceTech** [comment] 2016-01-07 18:31
Can I add you as a collaborator on my project to see the bug?

**Comment by BackSpaceTech** [comment] 2016-01-08 00:30
I rewrote my code and I suspect I was passing two sets of curly braces around the query. All good now.

**Comment by JamesLefrere** [comment] 2017-02-09 15:00
I ran into this bug today and have made a simple repository to isolate the issue, as @glasser recommended:

https://github.com/JamesLefrere/mongo-edge-case-bug

The error I get is as follows:
```
I20170209-15:50:02.363(1)? Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"references.reference.EJSON$value":"a"}
I20170209-15:50:02.404(1)?     at Error (native)
I20170209-15:50:02.404(1)?     at packages/mongo/oplog_observe_driver.js:880:15
I20170209-15:50:02.404(1)?     at Object.Meteor._noYieldsAllowed (packages/meteor.js:671:12)
I20170209-15:50:02.404(1)?     at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:850:12)
I20170209-15:50:02.405(1)?     at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:757:10)
I20170209-15:50:02.405(1)?     at OplogObserveDriver._runInitialQuery (packages/mongo/oplog_observe_driver.js:658:10)
I20170209-15:50:02.405(1)?     at packages/mongo/oplog_observe_driver.js:192:10
I20170209-15:50:02.405(1)?     at packages/mongo/oplog_observe_driver.js:16:9
I20170209-15:50:02.405(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170209-15:50:02.406(1)?     at packages/meteor.js:445:45
```

Looking at the oplog observer driver, the error does not appear if we define a limit in the find options, but that may just mask the error. 

I also think that indices/$in are not necessarily related, and it's rather an EJSON issue when comparing subdocuments.

I hope this helps!

**Comment by abernix** [comment] 2017-02-13 15:20
@JamesLefrere Thank you very much for taking the time and providing a reproduction!  This hasn't been a super popular issue so the likelihood of it getting attention super soon is not high, but if you need help debugging it or fixing it please let me know if there's anything I can do to get you started!  See [running Meteor from a checkout](https://github.com/meteor/meteor/#slow-start-for-developers) and [Contributing.md](https://github.com/meteor/meteor/blob/devel/Contributing.md) for more information.

**Comment by cesarve77** [comment] 2017-05-03 06:18
+1 same issue

**Comment by abernix** [comment] 2017-05-03 06:35
@cesarve77 Can you provide some details about the query that is triggering this?  Also, the relevant versions of Meteor and Mongo (if you're encountering this outside the development environment) would be helpful! (You can run `db.version()` on the Mongo server shell to find out the Mongo version if it's happening in production).

**Comment by cesarve77** [comment] 2017-05-03 13:29
Happen on both, development, and production (galaxy)
Meteor 1.4.2.3 
mongod version: 3.2.10 (MMAPv1) on mlab.com

query: 
```
 {"families":
    {"$elemMatch":
        {"status":"open","id":"BjxY5ntHyLrpyGEQs"}
    },
}
```

example schema:
```
families: Array
    status: String, id: String
description: String
```

everything works good while the first element of families don't be null (for a matching element)

I made a repo to reproduce the issue. https://github.com/cesarve77/mongodiscrep

see readme

**Comment by hwillson** [comment] 2017-12-19 12:19
Quick update - the issue demonstrated by the reproduction in https://github.com/meteor/meteor/issues/3946#issuecomment-298910703 has been fixed. The issue demonstrated by the reproduction provided in https://github.com/meteor/meteor/issues/3946#issuecomment-278666662 is still happening however.

**Comment by hwillson** [comment] 2018-01-16 11:36
The remaining issue here (https://github.com/meteor/meteor/issues/3946#issuecomment-278666662) appears to only happen under very specific circumstances, and hasn't been a popular issue. Since we're pushing hard to clean up the older backlog of issues, I'll close this issue for now. If this issue is still a problem for anyone, please post back and let us know. Thanks!

**Closed by hwillson** 2018-01-16 11:36 UTC
Labels: Impact:few, Project:Livequery, Project:Minimongo, bug, confirmed, pull-requests-encouraged

**Comment by jamesmillerburgess** [comment] 2018-01-17 18:14
I worked on this a few days ago, but was still understanding how the `mongo` package works before I ran out of time. I’ll reference this issue if I get around to finishing a fix.
