### ISSUE TITLE
`import`s inside npm packages don't work

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#7081] opened 2016-05-19 05:29 UTC
### Problem

- `npm i --save async-es`
- client file with `import { parallel } from 'async-es'`
- load client

results in this error:

`Uncaught SyntaxError: Unexpected token import`

![image](https://cloud.githubusercontent.com/assets/251288/15383411/d8862408-1d60-11e6-9548-935da3e593d0.png)

### Solution?

- Server: switch Meteor to a version of node that supports `import`
- Client: either have the npm package deal with this, or have the meteor build tool transpile

**Comment by abernix** [comment] 2016-05-19 11:10
It doesn't work on the client but I don't think this would work server-side either right now since Meteor is using Node 0.10.x and `import` is not directly supported.

`async-es` is providing non-transpiled ES6 code which is failing because Meteor doesn't (to my knowledge, nor should it) recursively transpile existing NPM code (it only does **your** code) and `async-es` doesn't provide a browser-only entry-point in it's `package.json` that would change this.  I think it would be up to the NPM package to provide code that would work in the environment that it's running in.  It appears that `async-es` does this normally by use of bower/component.

I'm not sure if there is much else to say about this – but perhaps you'd have more luck using `async` (without the `-es`)?

Maybe someone else can speak on this.

**Comment by lorensr** [comment] 2016-05-19 20:06
Thanks, so I guess it should start working when we upgrade to a node version that supports `import`

**Comment by abernix** [comment] 2016-05-19 20:34
Well, your particular error is coming from the browser.  Modules are not implemented in any browsers natively at this time.  Transpilation is going to have to happen – but it's a matter of where.

**Comment by lorensr** [comment] 2016-05-19 21:03
Haha right ☺️ More node packages will start coming out using import, so maybe we'll want the meteor build tool to support using them on client

Also yes, while `async` as a global import doesn't work in meteor 1.3, `async` v2 as a named import works fine.

**Comment by DrDanRyan** [comment] 2016-05-20 14:34
Just use the regular `async` package, not the `async-es` package.  Then do the import exactly as you were doing it before:
`import { parallel } from 'async'`

**Comment by abernix** [comment] 2016-05-21 12:38
Closing this as a duplicate of #4828.

**Closed by abernix** 2016-05-21 12:38 UTC
Labels: bug
