### ISSUE TITLE
Fabric.js > Canvas dependency breaking (meteor-node-stubs)

### ISSUE THREAD

**Issue by ArdentKid** [meteor/meteor#7567] opened 2016-08-03 18:23 UTC
Same issue as https://github.com/meteor/meteor/issues/6613 but left unresolved. After installing [fabric.js](fabricjs.com) with `npm install fabric --save`, and import the module on client, I get the error at bootup:

```
Unable to resolve some modules:

  "../build/Release/canvas" in
/Users/samh/weird-bug/node_modules/canvas/lib/bindings.js (web.browser)
```

Seems like it's missing "canvas**.node**" in the bindings.js file. Everything worked fine for me with Meteor 1.3-beta8, but upgrading breaks canvas with this error.

I've made a demo of the bug here: https://github.com/ArdentKid/meteor-fabric-bug for anyone to pull and see.

**Comment by abernix** [comment] 2016-08-05 08:27
First of all, you should absolutely be using `meteor npm install fabric --save` and not simply `npm install ...`.

Also, I'm copying relevant comments from #6613 (closed) here:

> ../build/Release/canvas is meant to refer to a .node binary module, and there's no way to load those modules on the web.browser platform

...indicating that this is occurring because when trying to load a binary in the `web.browser` bundle – which will not work.

> If the `canvas` package should not be on the client, then it might be advisable for them to make some changes to [their `package.json`](https://github.com/Automattic/node-canvas/blob/master/package.json) to make this more clear to projects like Meteor who have to consume them.  While they do specify the `engine`, they don't specify `engineStrict` so it merely acts as an advisory – but regardless, `engineStrict` has been deprecated in NPM 3.0 anyhow.  Another (probably better solution) is the [`browser`](https://github.com/defunctzombie/package-browser-field-spec) attribute (which they don't currently set) might solve the problem (though someone would have to test to be sure):
```
"browser": "./browser.js",
```
And then `browser.js` could just be an empty file right next to its `package.json`.

This probably worked for you in Meteor-1.3-beta8 because you were using a different module?  Or maybe an Atmosphere package?  Did you change anything during the upgrade?

Haven't had a chance to look at the reproduction but hopefully someone else can.

**Comment by ArdentKid** [comment] 2016-08-05 17:20
Exact same implementation, yes using `meteor npm install --save fabric` see the example for side by side comparison: https://github.com/ArdentKid/meteor-fabric-bug

Meteor 1.4 also requires that I install meteor-node-stubs so I did.

**Comment by abernix** [comment] 2016-10-03 09:42
Closing this for the same reason as #6613.  You will not be able to load a binary module in the browser and the NPM will need to make considerations on how to deal with that.  Last I checked `canvas` did not do that in a way that can be understood by Meteor.  `meteor-node-stubs` is available to try to solve this, however you can install whatever functions you'd like to mock Node functions and have them behave as you wish.  Additional conversation can be found in these issues:

* https://github.com/meteor/meteor/issues/6578#issuecomment-200895733
* https://github.com/meteor/meteor/issues/6890#issuecomment-214032062 (open, and ultimately a solution)

**Closed by abernix** 2016-10-03 09:42 UTC
