### ISSUE TITLE
Improve Tracker exceptions stack trace 

### ISSUE THREAD

**Issue by vonwao** [meteor/meteor#5310] opened 2015-09-28 21:24 UTC
I'm using third party package (Orion.js).  I got two different Exceptions and stack traces, impossible to debug:

Exception from Tracker recompute function:
meteor.js:862 TypeError: Cannot read property 'setMembers' of undefined
at doMaterialize (blaze.js:2004)
at Object.Tracker.nonreactive (tracker.js:597)
at doRender (blaze.js:2000)
at blaze.js:1844
at Function.Template._withTemplateInstanceFunc (blaze.js:3643)
at blaze.js:1842
at Object.Blaze._withCurrentView (blaze.js:2183)
at viewAutorun (blaze.js:1841)
at Tracker.Computation._compute (tracker.js:331)
at Tracker.Computation._recompute (tracker.js:350)

Exception from Tracker recompute function:
meteor.js:864 undefined

I cannot track down the source of these exceptions. 

I think meteor could compile code in such a way that the filename and line number of templates show up in the stack trace.  This may be very helpful dealing with complex code. 

Is this possible?

**Comment by stubailo** [comment] 2015-10-02 22:04
It's inherently hard to have good stack traces for asynchronous stuff, but we could certainly add more information here. It would be helpful for someone to post an app that demonstrates the issue so that we know what use case to target.

**Comment by hwillson** [comment] 2016-11-28 17:56
Given that there has been very little discussion regarding this issue in over a year, and there isn't a runnable reproduction available to work against, I'll close this issue for now. There is always room for error handling improvements, but without some form of reproduction to work against, or some other form of actionable requirements, this issue is difficult to move forward. Thanks for originally submitting this issue!

**Closed by hwillson** 2016-11-28 17:56 UTC
Labels: feature, Project:Blaze, Project:Tracker

**Comment by drone1** [comment] 2021-12-18 17:30
Is this not something others are running into, all these years later? I constantly have to do guesswork about which file the tracker's even in. Example trace:

```Error: No such function: foo
    at http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3012:15
    at Spacebars.call (http://www.dev.com:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:172:18)
    at Spacebars.mustacheImpl (http://www.dev.com:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:106:25)
    at Object.Spacebars.dataMustache (http://www.dev.com:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:138:39)
    at http://www.dev.com:3000/app/app.js?hash=6849b16612fb00d8fbad5f2a97dd99d1fea41e2f:21292:24
    at Blaze.View.<anonymous> (http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2535:44)
    at http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1778:18
    at Function.Template._withTemplateInstanceFunc (http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14)
    at http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1777:29
    at Object.Blaze._withCurrentView (http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2109:12) undefined
```

There is no useful information here from what I can glean -- no indication of which template, file or line number. Have there been no improvements here since 2015? If I'm doing something wrong I'd love to know what it is as I run into this any time I'm writing trackers, which is a lot. The best I can do is to grep my codebase for ``foo`` in this case.

Thank you Meteor team for all your awesome work. <3

**Comment by WilliamKelley** [comment] 2021-12-18 17:55
@drone1 In the closing comment the lack of a reproduction was a key factor. It sounds like you could provide a reproduction repository given your issues? I encourage you to do so. Then the issue can progress with a goal to work against.

**Comment by drone1** [comment] 2021-12-18 18:45
Sorry about that @WilliamKelley. So actually in my case, if I call a nonexistent 'foo' from a template's autorun(), the stack trace is correct. But the confusion for me was this: the error above was produced because I was calling a non-existent helper function _with a parameter_ from _within Blaze markup_, like this:

```
<!-- repro.html -->
{{test param='something'}}
```
When 'test' does not exist in any reachable context from Blaze at this point, the stack trace looks like this for me:
```
Exception from Tracker recompute function: undefined
meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1061 Error: No such function: test
    at http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3012:15
    at Spacebars.call (http://www.dev.com:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:172:18)
    at Spacebars.mustacheImpl (http://www.dev.com:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:106:25)
    at Object.Spacebars.mustache (http://www.dev.com:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:110:39)
    at Blaze.View._render (http://www.dev.com:3000/app/app.js?hash=85b49b59214d39d30d055901e65b01aec80a1212:21226:22)
    at Blaze.View.doRender (http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1925:25)
    at http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1778:18
    at Function.Template._withTemplateInstanceFunc (http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14)
    at http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1777:29
    at Object.Blaze._withCurrentView (http://www.dev.com:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2109:12) undefined
```
In this case, a filename (repro.html) and if possible line number would be amazing. repro.html in this case is in /imports/ui/components/ and is included from repro.js via ``import './repro.html'``.

[And I don't want to go off-top but in case it's useful: a related issue I've found since moving my .html/.js template files to a non-client-specific folder like Todo's is that when I've got compilation errors in repro.html (e.g. an ``{{#if}}`` without a closing ``{{/if}}``), I simply get a missing module exception rather than compilation error details.]

Please let me know if I can provide more assistance.

**Comment by WilliamKelley** [comment] 2021-12-18 19:28
No need to be sorry. I don't have the ability to contribute the improvement you're asking for, but I saw the issue update and wanted to clarify what's necessary.

By reproduction, I mean what's described [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor). Descriptions and snippets are much less helpful than the simplest repro.

Hope someone can pick this up for you.

**Comment by drone1** [comment] 2021-12-19 02:26
OK nevermind, there is actually a useful file/line in this trace! I was missing app.js, buried down a bit. So, nothing to see here after all. Thank you @WilliamKelley!
