### ISSUE TITLE
Not able to update to 1.6.2-beta.10 on Win10

### ISSUE THREAD

**Issue by lhz516** [meteor/meteor#9703] opened 2018-02-28 08:57 UTC
System env: Windows 10 64x

Error message:
```
D:\xxxx\xxxx> meteor update --release 1.6.2-beta.10
Retrying after error { Error: SQLITE_BUSY: database is locked
=> awaited here:
at Promise.await (C:\Users\hanz\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.10\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
at Db._execute (C:\tools\packaging\catalog\catalog-remote.js:349:15)
at C:\tools\packaging\catalog\catalog-remote.js:149:12
at Db._retry (C:\tools\packaging\catalog\catalog-remote.js:164:16)
at new Db (C:\tools\packaging\catalog\catalog-remote.js:147:8)
at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:708:15)
at C:\tools\cli\main.js:870:20 errno: 5, code: 'SQLITE_BUSY' }
Retrying after error { Error: SQLITE_BUSY: database is locked
=> awaited here:
at Promise.await (C:\Users\hanz\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.10\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
at Db._execute (C:\tools\packaging\catalog\catalog-remote.js:349:15)
at C:\tools\packaging\catalog\catalog-remote.js:149:12
at Db._retry (C:\tools\packaging\catalog\catalog-remote.js:164:16)
at new Db (C:\tools\packaging\catalog\catalog-remote.js:147:8)
at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:708:15)
at C:\tools\cli\main.js:870:20 errno: 5, code: 'SQLITE_BUSY' }
C:\Users\hanz\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.10\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: SQLITE_BUSY: database is locked
 => awaited here:
    at Promise.await (C:\Users\hanz\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.10\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
    at Db._execute (C:\tools\packaging\catalog\catalog-remote.js:349:15)
    at C:\tools\packaging\catalog\catalog-remote.js:149:12
    at Db._retry (C:\tools\packaging\catalog\catalog-remote.js:164:16)
    at new Db (C:\tools\packaging\catalog\catalog-remote.js:147:8)
    at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:708:15)
    at C:\tools\cli\main.js:870:20
```

**Comment by hwillson** [comment] 2018-02-28 13:40
@lhz516 See https://github.com/meteor/meteor/issues/9391#issuecomment-345666527. Let us know if that helps, or if you're still having problems.

**Comment by lhz516** [comment] 2018-03-01 02:12
@hwillson I rebooted and there's no meteor process running. However, it still happens.

In `xxxxxxx/.meteor/package-metadata/v2.0.1`, there're 3 files. I'm not sure if it's normal or not.

![image](https://user-images.githubusercontent.com/9879279/36823591-b556e5dc-1cb2-11e8-9f7c-493fd4f3a315.png)

**Comment by hwillson** [comment] 2018-03-01 16:17
Yes, those files are normal. Can you try removing the `~/.meteor/package-metadata` directory, to see if that helps? It will be re-created the next time you run a `meteor` command.

**Comment by lhz516** [comment] 2018-03-01 18:49
@hwillson Unfortunately it's still not working.

I also tried uninstall Meteor and reinstall it using `choco`, and same thing happens again.

**Comment by lhz516** [comment] 2018-03-17 07:58
Update:

On win 10 64x, Meteor 1.6-beta.0-5 can be updated, but beta,6+ won't work.

**Comment by claudiutraistaru** [comment] 2018-03-24 20:38
I can confirm the issue on windows 10 , trying to update to 1.6.2-beta.13 from 1.6.1:
meteor update --release 1.6.2-beta.13
Retrying after error { Error: SQLITE_BUSY: database is locked
=> awaited here:
at Promise.await
(C:\Users\Claud\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.13\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:1
2)
at Db._execute (C:\tools\packaging\catalog\catalog-remote.js:349:15)
at C:\tools\packaging\catalog\catalog-remote.js:149:12
at Db._retry (C:\tools\packaging\catalog\catalog-remote.js:164:16)
at new Db (C:\tools\packaging\catalog\catalog-remote.js:147:8)
at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:708:15)
at C:\tools\cli\main.js:870:20 errno: 5, code: 'SQLITE_BUSY' }
Retrying after error { Error: SQLITE_BUSY: database is locked
=> awaited here:
at Promise.await
(C:\Users\user\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.13\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:1
2)
at Db._execute (C:\tools\packaging\catalog\catalog-remote.js:349:15)
at C:\tools\packaging\catalog\catalog-remote.js:149:12
at Db._retry (C:\tools\packaging\catalog\catalog-remote.js:164:16)
at new Db (C:\tools\packaging\catalog\catalog-remote.js:147:8)
at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:708:15)
at C:\tools\cli\main.js:870:20 errno: 5, code: 'SQLITE_BUSY' }
C:\Users\user\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.13\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: SQLITE_BUSY: database is locked
 => awaited here:
    at Promise.await (C:\Users\user\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.13\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\p
romise_server.js:60:12)
    at Db._execute (C:\tools\packaging\catalog\catalog-remote.js:349:15)
    at C:\tools\packaging\catalog\catalog-remote.js:149:12
    at Db._retry (C:\tools\packaging\catalog\catalog-remote.js:164:16)
    at new Db (C:\tools\packaging\catalog\catalog-remote.js:147:8)
    at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:708:15)
    at C:\tools\cli\main.js:870:20

I will try to remove the package-metadata directory and run the update again , but will take some time .

**Comment by lmachens** [comment] 2018-04-07 07:39
Same issue with 1.6.2-beta.20 on Win10
```
Retrying after error { Error: SQLITE_BUSY: database is locked
=> awaited here:
at Promise.await (C:\Users\Admin\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.20\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
at Db._execute (C:\tools\packaging\catalog\catalog-remote.js:349:15)
at C:\tools\packaging\catalog\catalog-remote.js:149:12
at Db._retry (C:\tools\packaging\catalog\catalog-remote.js:164:16)
at new Db (C:\tools\packaging\catalog\catalog-remote.js:147:8)
at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:708:15)
at C:\tools\cli\main.js:870:20 errno: 5, code: 'SQLITE_BUSY' }
Retrying after error { Error: SQLITE_BUSY: database is locked
=> awaited here:
at Promise.await (C:\Users\Admin\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.20\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
at Db._execute (C:\tools\packaging\catalog\catalog-remote.js:349:15)
at C:\tools\packaging\catalog\catalog-remote.js:149:12
at Db._retry (C:\tools\packaging\catalog\catalog-remote.js:164:16)
at new Db (C:\tools\packaging\catalog\catalog-remote.js:147:8)
at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:708:15)
at C:\tools\cli\main.js:870:20 errno: 5, code: 'SQLITE_BUSY' }
C:\Users\Admin\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.20\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: SQLITE_BUSY: database is locked
 => awaited here:
    at Promise.await (C:\Users\Admin\AppData\Local\.meteor\packages\meteor-tool\1.6.2-beta.20\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
    at Db._execute (C:\tools\packaging\catalog\catalog-remote.js:349:15)
    at C:\tools\packaging\catalog\catalog-remote.js:149:12
    at Db._retry (C:\tools\packaging\catalog\catalog-remote.js:164:16)
    at new Db (C:\tools\packaging\catalog\catalog-remote.js:147:8)
    at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:708:15)
    at C:\tools\cli\main.js:870:20
```

**Comment by abernix** [comment] 2018-04-17 15:11
@lhz516 is suggesting in https://github.com/meteor/meteor/issues/9703#issuecomment-373902276 that 1.6.2 beta versions up until (and including) `1.6.2-beta.5` are working properly, which leads me to the believe that https://github.com/meteor/meteor/pull/9644 is having unintended consequences, since `1.6.2-beta.6` was the first version which that landed in.

@brucejo75, do you have any thoughts on the matter?

**Comment by brucejo75** [comment] 2018-04-23 01:00
**This is definitely an issue that will affect anyone running on windows!  And needs to be repaired.**

My previous [tests](https://github.com/meteor/meteor/pull/9644#issuecomment-363586515) only verified that meteor can bounce back and forth between `WAL` mode and `TRUNCATE` mode.  When a project is updated something more complicated occurs.

I think I see why a problem occurs on update, but I need some _help/ideas/feedback_ on a resolution.

### My Theory

When upgrading from `1.6.1.*` (or earlier) meteor runs version `1.6.1.*` which then loads the new version and executes the new version of meteor (e.g. `1.6.2.*`).

Version `1.6.2.*` tries to set the SQLite `journal_mode=TRUNCATE` and it fails.
I believe it fails because:
1. SQLite tries to delete 2 `WAL` specific files: `packages.data.shm` & `packages.data.wal` and install a `TRUNCATE` specific file: `packages.data.db-journal`.
2. SQLite cannot delete any of the files because version `1.6.1.*` retains an open handle on the SQLite DB until upgrade is complete.

### Workaround
To get the new version to load I [hand modified](https://github.com/meteor/meteor-feature-requests/issues/154#issuecomment-347664097) `catalog.remote.js` for the version I was migrating from to use `TRUNCATE` journal_mode.  Then I did an upgrade.  From there on out everything works as expected:
1. I can upgrade to a version that uses `TRUNCATE` journaling mode, build it and run it.  (this is because SQLite does not need to delete and add files).
2. I can run a project that is using an older version of meteor using `WAL` journaling mode.

### Repair

Can meteor release its connection to the catalog prior to starting the new version of meteor?
(I know nothing about the tool code here, if someone can point me I could try to see if I could close the connection at a good point)

**Option 1:**
- Back out `TRUNCATE` mode.
- Create an intermediate version (e.g. `1.6.1.2`, `1.6.2`?) that closes the connection to the catalog at the appropriate point.  This version would need to be `WAL` journaling mode.
 - Require all windows upgrades first upgrade to the intermediate version above before moving onto later versions that would support `TRUNCATE` journaling mode.

**Option 2:**
- Same as option 1, but make `1.7` the intermediate version that every windows user needs to update to before updating beyond `1.7`.

**Option 3:**
- Is there any way to distinguish between windows and `WSL`?  We could make this change `WSL` only.  Then we could publish the workaround for `WSL` users.

### Other
- I had not seen this issue because I have pretty much switched over to WSL full time.
- I had hacked previous versions so the upgrade had worked fine for me.
- Sorry I was slow responding, out on vacation.

**Comment by brucejo75** [comment] 2018-04-23 01:58
Another option:

Is there a way to do a post install change?  Another way to address the issue would be to let the version install and then change it over to `TRUNCATE` journal mode as a final patch.

**Comment by benjamn** [comment] 2018-04-24 14:05
> &#x1F536;Because `1.6.1_1` is the newest recommended version of meteor, I am assuming that this is the version that is run to find other versions?

That's correct.

> I think it would be worth trying to see if we can get the latest recommended version to release its connection to the DB before "springboarding".

I think this is a good idea, though I'm assuming it would need to be a standalone change in Meteor 1.7, without shipping the `TRUNCATE` changes until 1.7.1.

**Comment by brucejo75** [comment] 2018-04-24 16:00
> I think this is a good idea, though I'm assuming it would need to be a standalone change in Meteor 1.7, without shipping the `TRUNCATE` changes until 1.7.1.

Correct.  Do you need me to do anything re: removing the `TRUNCATE` change?

**Comment by benjamn** [comment] 2018-04-24 19:45
This should be fixed if you update to the latest beta: `meteor update --release 1.7-beta.24`

**Closed by benjamn** 2018-04-24 19:45 UTC
Labels: Project:Tool, Project:Windows

**Comment by brucejo75** [comment] 2018-04-24 20:12
My current recommended version is 1.6.1.1

I verified that the following updates work properly:
`1.6` -> `1.7-beta.24`
`1.6.1.1` -> `1.7-beta.24`
