### ISSUE TITLE
After updating a project from 1.1 to 1.1.0.1, meteor mongo no longer works 

### ISSUE THREAD

**Issue by skagedal** [meteor/meteor#4134] opened 2015-04-05 21:17 UTC
After upgrading a Meteor project from 1.1, `meteor mongo` no longer works for me and outputs the following:

```
This command only works while Meteor is running your application locally. Start     
your application first. (This error will also occur if you asked Meteor to use a    
different MongoDB server with $MONGO_URL when you ran your application.)            
                                                                                    
If you're trying to connect to the database of an app you deployed with             
'meteor deploy', specify your site's name with this command.  
```
This happens on all meteor projects after just doing the update. [Here is an asciicast](https://asciinema.org/a/18407) that demonstrates the error. My system is an Ubuntu 14.10.

**Comment by Slava** [comment] 2015-04-05 23:01
Duplicate of #4115

**Closed by Slava** 2015-04-05 23:01 UTC

**Comment by skagedal** [comment] 2015-04-06 09:39
Whoops, sorry.
