### ISSUE TITLE
Blaze not setting "selected" attribute

### ISSUE THREAD

**Issue by lourd** [meteor/meteor#3191] opened 2014-11-26 20:20 UTC
**_3 Upvotes**_ See [this repo](https://github.com/lourd/meteor-select-attr-issue) and [this demo](http://select-attr-issue.meteor.com).

Basically passing in an empty string to a `selected` attribute isn't working correctly. When setting multiple attributes as an object, e.g.

```
// Template
<select>
  <option {{ optionAttrs 'default' }}>Select an option</option>
  <option {{ optionAttrs 'one' }}>Option one</option>
  <option {{ optionAttrs 'two' }}>Option two</option>
  <option {{ optionAttrs 'three' }}>Option three</option>
  <option {{ optionAttrs 'four' }}>Option four</option>
</select>

// Helper
optionAttrs : function ( option ) {
  var attrs = {};
  if ( option === 'default' ) {
    attrs.value = "";
    attrs.disabled = "";
  } else {
    attrs.value = option;
  }
  // If it's option three, make it selected
  attrs.selected = option === 'three' ? "" : false;
  // passing in true instead of empty string didn't change the behavior
  // attrs.selected = option === 'three';
  // Neither did returning 'selected'
  // attrs.selected = option === 'three' ? "selected" : false;
  return attrs;
}
```

The selected attribute doesn't turn up at all. 

When setting the selected attribute explicitly, the correct `option` is selected (verified by getting the value on the `select` element), but the option that's supposed to be selected still doesn't actually have a `selected` attribute.

```
// Template
<select>
  <option selected={{ isSelected 'default' }}>Select an option</option>
  <option selected={{ isSelected 'one' }}>Option one</option>
  <option selected={{ isSelected 'two' }}>Option two</option>
  <option selected={{ isSelected 'three' }}>Option three</option>
  <option selected={{ isSelected 'four' }}>Option four</option>
</select>

// Template helper
isSelected : function ( option ) {
  return option === 'three' ? "" : false;
}
```

This does not follow the behavior as documented in the [Spacebars README](https://atmospherejs.com/meteor/spacebars), the [Meteor manual](http://manual.meteor.com/#blaze-reactiveatts), or the [wiki article on using Blaze](https://github.com/meteor/meteor/wiki/Using-Blaze#conditional-attributes-with-no-value-eg-checked-selected).

I've tested this on OS X 10.10  and 10.9 using Safari, Firefox, and Chrome, and iOS 7 and 8.

**Comment by dgreensp** [comment] 2015-02-04 00:33
There does seem to be something funny going on here.  Thanks for the repo.

First, to clarify:  From poking at the repo, I think it doesn't actually matter if the truthy value you use is `""`, or `true`, or `"selected"` -- the bug is there either way.  For the second part (the plain reactive attribute), that behavior is the same as for checkboxes and not necessarily a bug.  You won't necessarily see "checked" in the HTML, but it is set in the DOM (the same as if you set it using jQuery).

From a cursory look, it looks like we are setting `.selected` on the `option` element too soon -- before it has a parent node -- and it is not taking effect.  We will fix.

**Comment by geremora** [comment] 2015-02-11 02:10
It's true, I confirm this. Same issue in checkboxes and option element.

**Comment by steph643** [comment] 2015-04-21 22:14
There seems to be an additional issue:
- as decribed above, the selection works but the `selected` attribute is not set in the html
- calling `this.$('select').val()` from `rendered` returns null instead of the selected value

**Comment by aadamsx** [comment] 2015-05-13 06:23
I'm running into this now with the latest release of Meteor.  

I have to select the option twice for the 'selected' to take.

Any word if this is getting corrected in the next update?

**Comment by dkmooers** [comment] 2015-05-20 20:09
+1, I'm also having this issue. It's preventing me from *canceling* a select change reactively, I think, unless I'm missing something. E.g. on select change, fire confirm dialog, if cancel, change select back to what it was - and my "isSelected" template helper is re-running properly, but the select doesn't go back to the previous value, I think because Blaze isn't setting the "selected" attribute in the HTML.

**Comment by jbrozena22** [comment] 2015-05-25 23:03
+1 Same issue here. I can't set the default selected item in a dropdown list because of this.

**Comment by dkmooers** [comment] 2015-06-10 02:13
@jbrozena22 Have you tried this:

    option(selected="{{isSelected someValue}}" value=someValue) someValue

That's Jade BTW, sorry about that. But what you basically want is:

    selected="true"

... I think. I think I remember trying `selected="selected"` and it didn't work with Meteor. Try returning a boolean from your isSelected helper.

**Comment by Cerealkillerway** [comment] 2015-06-24 01:19
\+ 1

**Comment by jessekrasnostein** [comment] 2015-07-08 07:28
+1

**Comment by OminStyle** [comment] 2015-07-23 01:17
Any updates on this?

**Comment by hitchcott** [comment] 2015-07-26 06:42
This format works for me

```
<select name="platform" class='form-control'>
  <option value="osx" selected="{{platformIs 'osx'}}">Mac OSX</option>
  <option value="ubuntu" selected="{{platformIs 'ubuntu'}}">Ubuntu 14</option>
</select>
```

Where `platformIs` returns true if `this.platform` equals the argument.

**Comment by AnthonyAstige** [comment] 2015-08-01 20:55
I've just run into a similar issue and the workaround from @hitchcott seems to have fixed it.

**Comment by spencern** [comment] 2015-10-28 00:32
Also running into this issue and @hitchcott's solution is working as well.

**Comment by iwoj** [comment] 2016-09-22 19:39
Solution from @hitchcott doesn't work for me. Blaze doesn't seem to render any selected attribute I set, even if hardcoded. Very strange.

**Comment by hwillson** [comment] 2016-12-12 20:27
Moved to meteor/blaze#210 - closing here - thanks!

**Closed by hwillson** 2016-12-12 20:27 UTC
Labels: Project:Blaze

**Comment by aisamu** [comment] 2016-12-21 22:20
@iwoj Same here...
The funny thing is that `data-selected`, for example, works perfectly (without @hitchcott's workaround)

**Comment by abernix** [comment] 2016-12-27 13:30
In order to avoid conversation getting lost, please continue additional discussion on the new issue within the Blaze repo.

**Comment by mitar** [comment] 2016-12-31 09:25
This has been fixed in `master` of Blaze just now. In fact the second issue (only property being set, not attribute) is by design. The first issue was in fact that `false` from dynamic attributes (dicts) were seen as non-nully value (in contrast with values from helpers where `false` was converted to `null` already).

See [this comment](https://github.com/meteor/blaze/issues/210#issuecomment-269857113) for more information.
