### ISSUE TITLE
bug: importing aws-sdk breaks Accounts.setPassword

### ISSUE THREAD

**Issue by zeroasterisk** [meteor/meteor#7371] opened 2016-07-08 19:46 UTC
BUG: `Accounts.setPassword()` fails due to `aws-sdk` giving the super-not-helpful error `TypeError: undefined is not a function`

Here's a test repo:
https://github.com/zeroasterisk/simple-todos-react/tree/bug-importing-aws-sdk-breaks-accounts-setpassword

Firstly - this bug is only reliably re-created when you login via `meteor shell` and execute `Accounts.setPassword('userid', 'mypass')` --- but once you do that, after the server re-builds (attempting to restart from the crash state) it keeps crashing.

* if you install the npm `aws-sdk` but do not import it, no problem
* if you import `aws-sdk` but do not actually use it somewhere, BUG
* if you import `aws-sdk` and use it (not shown) AWS works, but the Accounts BUG
* if you require `aws-skd` (ES5) BUG

It was a few hours to whittle down this bug to this cause.

I do not know what inside of `aws-sdk` would be causing this problem... 

It might be only broken with recent versions of `aws-sdk` 
(unsure, I'll be testing a few soon, and will update if I find any working)

It is likely an npm issue (?) but if it's happening for AWS, it's important,
and perhaps indicative of a broader issue.

![ss](http://puu.sh/pUVn7/5508abfd9b.png)

**Comment by veered** [comment] 2016-07-08 21:17
I've been experiencing this bug for the past several weeks and it is very frustrating

**Comment by benjamn** [comment] 2016-07-08 22:40
I believe this is a duplicate of https://github.com/meteor/meteor/issues/7095.

If so, then this problem will not (and unfortunately cannot) be solved in Meteor 1.3.x, because the `bcrypt` authors have [refused](https://github.com/ncb000gt/node.bcrypt.js/issues/235) to fix the problem for Node 0.10.x.

Your best option is to update to Meteor 1.4: `meteor update --release 1.4-beta.7` (and keep updating as the betas are [released](https://github.com/meteor/meteor/releases), if you want to stay up to date).

**Comment by zeroasterisk** [comment] 2016-07-08 23:26
Excellent, that makes sense... sorry to duplicate.

I know it's impossible to say, but the last thing I read about 1.4 was that all tests were passing and it seemed mostly stable.... 

What do you say now?

I'm working on something that needs to roll to production in a few weeks, and the ability to change passwords is at least somewhat important :)

I'm also very excited about the node and mongo upgrades and underlying performance improvements, but I'm a little afraid that 1.4 is a big low level shift and we will find lots of odd things under the hood....

Meh. Sorry to ramble on. All things being equal, I'm in favor of a push to 1.4 vs. trying to fix something wonky in  1.3.  thanks!!!!

**Comment by benjamn** [comment] 2016-07-08 23:30
> All things being equal, I'm in favor of a push to 1.4 vs. trying to fix something wonky in 1.3.

I totally agree with this :)

**Comment by benjamn** [comment] 2016-07-08 23:33
> What do you say now?

I haven't seen any Node 4-specific problems in Meteor 1.4 in a long time. The main hurdle is making sure you can use the same installation of Meteor to develop Meteor 1.3.x apps and Meteor 1.4 apps, but I'm hoping Meteor 1.3.4.3 puts an end to those concerns. If all goes well, 1.3.4.3 will be released later today!

**Comment by abernix** [comment] 2016-07-11 06:49
I'll confirm that this is a duplicate of #7095 involving `bcrypt`'s error in it's callback to `crypto.randomBytes`.  You should be able to avoid it if you avoid using `meteor shell` entirely – which means you should be totally fine in production unless you're doing your own stuff with `domain`.

Meteor 1.4 will fix it, however, if you absolutely, positively cannot make that move, you can work around it (i.e. keep using `meteor shell`) by using benjamn's suggestion in https://github.com/meteor/meteor/issues/7095#issuecomment-220863824 in your development environment (try to keep it out of production):

> I'm not sure I can really recommend this solution, but it seems as if setting
```js
process._usingDomains = function(){};
```
early in your application, before `require("domain")` is called (i.e. before you import `aws-sdk`) will disable the logic that decides to abort on uncaught domain exceptions.

Still, the best solution here is updating to Meteor 1.4, which in my personal experience has been going well so far!

Closing as there isn't anything Meteor can do about this.  Sorry! 😞

**Closed by abernix** 2016-07-11 06:49 UTC
