### ISSUE TITLE
Would like to see Collection.count({applySkipLimit: true}); implemented 

### ISSUE THREAD

**Issue by Gacnt** [meteor/meteor#3379] opened 2014-12-29 08:02 UTC
I implemented my own pagination for a table via: 
```
Meteor.publish("homePage", function(gamePage) {
  return HomePage.find({}, { limit: 5, skip: gamePage, sort: { createdAt: -1 }});
});
```

But when the count is `<` than the amount left after skipped and limited, I want to return just the last 5 items in the collection instead.

Something like 
```
if (HomePage.find({}, { limit: 5, skip: gamePage, sort: { createdAt: -1 }}).count({applySkipLimit: true}) <= 5) {
   return HomePage.find({}, { limit: 5, skip: gamePage, sort: { createdAt: 1}});
};
```

**Comment by avital** [comment] 2015-01-14 01:28
This is duplicate of #1201.

This may be a useful feature, but even if we implemented `applySkipLimit` you wouldn't be able to write the code you want because publishes aren't reactive.

On a separate note, queries using `skip` can't be optimized using our efficient ["oplog tailing"](https://www.meteor.com/livequery) implementation for live Mongo queries. Also, pagination using `skip` in a reactive context is probably not the right UX since then you'd see the window of results changing whenever some earlier entries change. A better pattern would be to filter for items where `createdAt` is >= some value, and apply `skip` on that. Queries like these do perform efficiently under using oplog tailing.

**Closed by avital** 2015-01-14 01:28 UTC

**Comment by mitar** [comment] 2015-01-17 08:52
> A better pattern would be to filter for items where createdAt is >= some value, and apply skip on that. 

@avital: You mean to apply `limit` on that, no? To get a page? `skip` again complicates the life with oplog?

**Comment by avital** [comment] 2015-01-21 01:18
Yes, I mispelled `limit` as `skip`.
