### ISSUE TITLE
CLI bug on "meteor build"

### ISSUE THREAD

**Issue by cyclops24** [meteor/meteor#5920] opened 2016-01-02 08:01 UTC
Hi, 
When I try to deploy my app (with [meteor-up](https://github.com/arunoda/meteor-up) ```mup deploy``` command) I got this error on build step then I test and found that same error also return when use ```meteor build``` command:

    Building Started: /media/userName/Projects/Projects/appName
    
    /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                            throw(ex);
                                  ^
    TypeError: Cannot call method 'split' of undefined
      at Object.parse (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/parse-stack.js:23:26)
      at Object.exception (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:480:29)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:871:22
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:352:18
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:345:34
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:343:23
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at Object.enterJob (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:317:26)
      at ClientTarget.minifyJs (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:866:18)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:530:17
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:352:18
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:345:34
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:343:23
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at Object.enterJob (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:317:26)
      at ClientTarget.make (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:492:18)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2083:14
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2169:20
      at Array.forEach (native)
      at Function._.each._.forEach (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2168:7
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:264:13
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:257:29
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:255:18
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:246:23
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at Object.capture (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:245:19)
      at Object.exports.bundle (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2070:31)
      at buildCommand (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/commands.js:834:30)
      at Command.main.registerCommand._.extend.name [as func] (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/commands.js:728:10)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/main.js:1227:23
    
    
    => Build Error. Check the logs printed above.

And this is my ```meteor build --verbose``` output:

    meteor build --verbose "/media/userName/Projects/Projects/appName/test_build/"
    Local package version is up-to-date: accounts-base@1.2.2
    Local package version is up-to-date: accounts-password@1.1.4
    Local package version is up-to-date: alanning:roles@1.2.14
    Local package version is up-to-date: aldeed:autoform@5.8.1
    Local package version is up-to-date: aldeed:collection2@2.8.0
    Local package version is up-to-date: aldeed:collection2-core@1.0.0
    Local package version is up-to-date: aldeed:schema-deny@1.0.1
    Local package version is up-to-date: aldeed:schema-index@1.0.1
    Local package version is up-to-date: aldeed:simple-schema@1.5.3
    Local package version is up-to-date: anti:i18n@0.4.3
    Local package version is up-to-date: autoupdate@1.2.4
    Local package version is up-to-date: babel-compiler@5.8.24_1
    Local package version is up-to-date: babel-runtime@0.1.4
    Local package version is up-to-date: base64@1.0.4
    Local package version is up-to-date: binary-heap@1.0.4
    Local package version is up-to-date: blaze@2.1.3
    Local package version is up-to-date: blaze-html-templates@1.0.1
    Local package version is up-to-date: blaze-tools@1.0.4
    Local package version is up-to-date: boilerplate-generator@1.0.4
    Local package version is up-to-date: caching-compiler@1.0.0
    Local package version is up-to-date: caching-html-compiler@1.0.2
    Local package version is up-to-date: callback-hook@1.0.4
    Local package version is up-to-date: check@1.1.0
    Local package version is up-to-date: coffeescript@1.0.11
    Local package version is up-to-date: dburles:collection-helpers@1.0.4
    Local package version is up-to-date: dburles:mongo-collection-instances@0.3.4
    Local package version is up-to-date: ddp@1.2.2
    Local package version is up-to-date: ddp-client@1.2.1
    Local package version is up-to-date: ddp-common@1.2.2
    Local package version is up-to-date: ddp-rate-limiter@1.0.0
    Local package version is up-to-date: ddp-server@1.2.2
    Local package version is up-to-date: deps@1.0.9
    Local package version is up-to-date: diff-sequence@1.0.1
    Local package version is up-to-date: easy:search@2.0.6
    Local package version is up-to-date: easysearch:components@2.0.6
    Local package version is up-to-date: easysearch:core@2.0.5
    Local package version is up-to-date: ecmascript@0.1.6
    Local package version is up-to-date: ecmascript-runtime@0.2.6
    Local package version is up-to-date: ejson@1.0.7
    Local package version is up-to-date: email@1.0.8
    Local package version is up-to-date: fastclick@1.0.7
    Local package version is up-to-date: gadicohen:robots-txt@0.0.10
    Local package version is up-to-date: gadicohen:sitemaps@0.0.23
    Local package version is up-to-date: geojson-utils@1.0.4
    Local package version is up-to-date: hot-code-push@1.0.0
    Local package version is up-to-date: html-tools@1.0.5
    Local package version is up-to-date: htmljs@1.0.5
    Local package version is up-to-date: http@1.1.1
    Local package version is up-to-date: ian:accounts-ui-bootstrap-3@1.2.84
    Local package version is up-to-date: id-map@1.0.4
    Local package version is up-to-date: insecure@1.0.4
    Local package version is up-to-date: iron:controller@1.0.12
    Local package version is up-to-date: iron:core@1.0.11
    Local package version is up-to-date: iron:dynamic-template@1.0.12
    Local package version is up-to-date: iron:layout@1.0.12
    Local package version is up-to-date: iron:location@1.0.11
    Local package version is up-to-date: iron:middleware-stack@1.0.11
    Local package version is up-to-date: iron:router@1.0.12
    Local package version is up-to-date: iron:url@1.0.11
    Local package version is up-to-date: jquery@1.11.4
    Local package version is up-to-date: lai:collection-extensions@0.1.4
    Local package version is up-to-date: launch-screen@1.0.4
    Local package version is up-to-date: livedata@1.0.15
    Local package version is up-to-date: localstorage@1.0.5
    Local package version is up-to-date: logging@1.0.8
    Local package version is up-to-date: matb33:collection-hooks@0.8.1
    Local package version is up-to-date: matteodem:easy-search@2.0.0
    Local package version is up-to-date: maximum:package-base@1.1.2
    Local package version is up-to-date: maximum:reactive-cursors@0.2.0
    Local package version is up-to-date: maximum:server-transform@0.4.1
    Local package version is up-to-date: mdg:validation-error@0.2.0
    Local package version is up-to-date: meteor@1.1.10
    Local package version is up-to-date: meteor-base@1.0.1
    Local package version is up-to-date: meteorhacks:async@1.0.0
    Local package version is up-to-date: meteorhacks:npm@1.5.0
    Local package version is up-to-date: minifiers@1.1.7
    Local package version is up-to-date: minimongo@1.0.10
    Local package version is up-to-date: mobile-experience@1.0.1
    Local package version is up-to-date: mobile-status-bar@1.0.6
    Local package version is up-to-date: momentjs:moment@2.10.6
    Local package version is up-to-date: mongo@1.1.3
    Local package version is up-to-date: mongo-id@1.0.1
    Local package version is up-to-date: npm-bcrypt@0.7.8_2
    Local package version is up-to-date: npm-mongo@1.4.39_1
    Local package version is up-to-date: observe-sequence@1.0.7
    Local package version is up-to-date: ordered-dict@1.0.4
    Local package version is up-to-date: peerlibrary:assert@0.2.5
    Local package version is up-to-date: peerlibrary:base-component@0.14.0
    Local package version is up-to-date: peerlibrary:blaze-components@0.15.1
    Local package version is up-to-date: peerlibrary:computed-field@0.3.1
    Local package version is up-to-date: peerlibrary:fiber-utils@0.5.1
    Local package version is up-to-date: peerlibrary:reactive-field@0.1.0
    Local package version is up-to-date: peerlibrary:server-autorun@0.5.1
    Local package version is up-to-date: promise@0.5.1
    Local package version is up-to-date: raix:eventemitter@0.1.3
    Local package version is up-to-date: random@1.0.5
    Local package version is up-to-date: rate-limit@1.0.0
    Local package version is up-to-date: reactive-dict@1.1.3
    Local package version is up-to-date: reactive-var@1.0.6
    Local package version is up-to-date: reload@1.1.4
    Local package version is up-to-date: retry@1.0.4
    Local package version is up-to-date: routepolicy@1.0.6
    Local package version is up-to-date: sacha:spin@2.3.1
    Local package version is up-to-date: service-configuration@1.0.5
    Local package version is up-to-date: session@1.1.1
    Local package version is up-to-date: sha@1.0.4
    Local package version is up-to-date: spacebars@1.0.7
    Local package version is up-to-date: spacebars-compiler@1.0.7
    Local package version is up-to-date: srp@1.0.4
    Local package version is up-to-date: standard-minifiers@1.0.2
    Local package version is up-to-date: stylus@2.511.1
    Local package version is up-to-date: templating@1.1.5
    Local package version is up-to-date: templating-tools@1.0.0
    Local package version is up-to-date: tracker@1.0.9
    Local package version is up-to-date: twbs:bootstrap@3.3.6
    Local package version is up-to-date: ui@1.0.8 
    Local package version is up-to-date: underscore@1.0.4
    Local package version is up-to-date: url@1.0.5
    Local package version is up-to-date: webapp@1.2.3
    Local package version is up-to-date: webapp-hashing@1.0.5
    Doing HTTP request:  POST                     
    https://www.meteor.com/oauth2/authorize?state=ea01b021a4xyz90917e2d845c0b07b&response_type=code&client_id=Ldpxyz7xyzkDJ2&redirect_uri=https%3A%2F%2Factivity.meteor.com%2F_oauth%2Fmeteor-developer%3Fclose
                                                  
    /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
    						throw(ex);
    						      ^
    TypeError: Cannot call method 'split' of undefined
      at Object.parse (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/parse-stack.js:23:26)
      at Object.exception (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:480:29)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:871:22
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:352:18
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:345:34
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:343:23
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at Object.enterJob (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:317:26)
      at ClientTarget.minifyJs (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:866:18)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:530:17
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:352:18
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:345:34
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:343:23
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at Object.enterJob (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:317:26)
      at ClientTarget.make (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:492:18)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2083:14
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2169:20
      at Array.forEach (native)
      at Function._.each._.forEach (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2168:7
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:264:13
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:257:29
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:255:18
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:246:23
      at [object Object]._.extend.withValue (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:116:14)
      at Object.capture (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:245:19)
      at Object.exports.bundle (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2070:31)
      at buildCommand (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/commands.js:834:30)
      at Command.main.registerCommand._.extend.name [as func] (/home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/commands.js:728:10)
      at /home/userName/.meteor/packages/meteor-tool/.1.1.10.12dq88w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/main.js:1227:23

My app run correctly now without any error but has error on build. I deploy this project some days ago without any problem. But after ```meteor update``` and add [maximum:server-transform](https://atmospherejs.com/maximum/server-transform) package deploy error appear. I also try to remove ```maximum:server-transform``` package and test again but it isn't fix.

This is my project ```meteor list``` output if useful:

    accounts-password            1.1.4  Password support for accounts
    alanning:roles               1.2.14  Authorization package for Meteor
    aldeed:autoform              5.8.1  Easily create forms with automatic insert and update, and automatic reactive validation.
    aldeed:collection2           2.8.0  Automatic validation of insert and update operations on the client and server.
    aldeed:simple-schema         1.5.3  A simple schema validation object with reactivity. Used by collection2 and autoform.
    blaze-html-templates         1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
    check                        1.1.0  Check whether a value matches a pattern
    dburles:collection-helpers   1.0.4  Transform your collections with helpers that you define
    ejson                        1.0.7  Extended and Extensible JSON library
    gadicohen:sitemaps           0.0.23  functions to easily output valid sitemaps
    ian:accounts-ui-bootstrap-3  1.2.84  Bootstrap-styled accounts-ui with multi-language support.
    insecure                     1.0.4  (For prototyping only) Allow all database writes from the client
    iron:router                  1.0.12  Routing specifically designed for Meteor
    jquery                       1.11.4  Manipulate the DOM using CSS selectors
    logging                      1.0.8  Logging facility.
    matteodem:easy-search        2.0.0  Easy-to-use search with Blaze Components (+ Elastic Search support)
    maximum:server-transform     0.4.1  Meteor package to transform documents on publish
    meteor-base                  1.0.1  Packages that every Meteor app needs
    meteorhacks:npm              1.5.0  Use npm modules with your Meteor App
    mobile-experience            1.0.1  Packages for a great mobile user experience
    mongo                        1.1.3  Adaptor for using MongoDB and Minimongo over DDP
    npm-container                1.2.0+ Contains all your npm dependencies
    random                       1.0.5  Random number generator and utilities
    reactive-dict                1.1.3  Reactive dictionary
    reload                       1.1.4  Reload the page while preserving application state.
    sacha:spin                   2.3.1  Simple spinner package for Meteor
    session                      1.1.1  Session variable
    spacebars                    1.0.7  Handlebars-like template language for Meteor
    standard-minifiers           1.0.2  Standard minifiers used with Meteor apps by default.
    tracker                      1.0.9  Dependency tracker to allow reactive callbacks
    twbs:bootstrap               3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.
    
    
    + These packages are built locally from source.

I also try ```DEBUG=* mup deploy``` for verbose mode but it isn't new detail about error.

I also try build project after ```meteor reset``` but it isn't work.

Please help me to troubleshoot this error if it's possible. How to find that where is the error?? How to trace build process??
How to find that in which file ```TypeError: Cannot call method 'split' of undefined``` happened??

**I think it's a meteor CLI bug. Please see updated question in [StackOverflow](http://stackoverflow.com/questions/34554990/error-in-building-meteor-app) too.**

**Comment by one-pereyra** [comment] 2016-01-08 00:34
same error here. I updated from 1.1 to 1.2.1 and I am not using cordova so not sure why it is happening. I am using OSX 10.11.2

**Comment by kctang** [comment] 2016-02-03 00:54
Same issue with meteor 1.3 beta5. Initial check indicates my user auth has expired so i meteor login again.

After that, still getting this issue when i use --verbose mode:

    Local package version is up-to-date: webapp-hashing@1.0.6-modules.5
    Doing HTTP request:  POST
    https://www.meteor.com/oauth2/authorize?state=03dc5e4212b4d392f7eca9638fc5cdb5&response_type=code&client_id=xxxxx&redirect_uri=https%3A%2F%2Factivity.meteor.com%2F_oauth%2Fmeteor-developer%3Fclose
        Doing HTTP request:  GET
    https://activity.meteor.com/_oauth/meteor-developer?close=&state=03dc5e4212b4d392f7eca9638fc5cdb5&code=AZXhbMwiTdNqShJbj&only_credential_secret_for_test=1
    
        TypeError: Cannot call method 'split' of undefined
    at /tools/isobuild/compiler-plugin.js:699:42
    at Array.forEach (native)
    at /tools/isobuild/compiler-plugin.js:698:34
    at scan (/tools/isobuild/compiler-plugin.js:719:51)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:729:7)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:736:8)

Any idea what is wrong?

**Comment by cyclops24** [comment] 2016-04-06 03:38
I found the issue. I have near 1000 line of comments at the end of startup.js (files that contain some seed data for set default values) when I remove this comments my project build successfully.

What is the problem??

**Comment by abernix** [comment] 2016-10-03 09:48
Closing as a duplicate of #7311.  See the closing comment there for more information and other related issues and possible solutions.  Ultimately, a reproduction was never available so please start a new issue with a reproduction (see: [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)) if you're still experiencing this problem.

**Closed by abernix** 2016-10-03 09:48 UTC
Labels: confirmed, Project:Isobuild
