### ISSUE TITLE
Accounts.onCreateUser don't work

### ISSUE THREAD

**Issue by guiguidu60** [meteor/meteor#8466] opened 2017-03-07 16:06 UTC
Hi,
When I use Accounts.onCreateUser function, the server responds:

> Exception in callback of async function: Error: Accounts.createUser with callback not supported on the server yet.

What the hell ?! =)
NB: The error is the same for the Meteor API example.

**Comment by hwillson** [comment] 2017-03-07 16:17
Hi @guiguidu60 - can you show us your `Accounts.onCreateUser` call? [As documented](https://docs.meteor.com/api/accounts-multi.html#AccountsServer-onCreateUser),  `Accounts.onCreateUser` currently only supports one argument, the function you want to have called to customize user creation. It does not support a second argument, which is what it sounds like you're doing, based on the error message you're getting (see the full details [here](https://github.com/meteor/meteor/blob/b18b1e275559012bc76d81a07a17b40de8354ff6/packages/accounts-password/password_server.js#L1075)).

**Comment by guiguidu60** [comment] 2017-03-07 16:33
Yes, I know.
I have copied the Meteor API example, so, It's strange.

Can you try and tell me if you get the same error please ?

**Comment by hwillson** [comment] 2017-03-07 16:38
Yes, it's working properly for me - which API example are you trying? The one listed [here](https://docs.meteor.com/api/accounts-multi.html#AccountsServer-onCreateUser)? If you can post your code or better yet a small, runnable reproduction, we can help troubleshoot further.

**Comment by guiguidu60** [comment] 2017-03-07 16:39
Yes, I have used this code:

> Accounts.onCreateUser(function(options, user) {
>   var d6 = function () { return Math.floor(Random.fraction() * 6) + 1; };
>   user.dexterity = d6() + d6() + d6();
>   // We still want the default hook's 'profile' behavior.
>   if (options.profile)
>     user.profile = options.profile;
>   return user;
> });

**Comment by hwillson** [comment] 2017-03-07 16:47
Okay - copying and running the API example code works properly on my side, so there is likely a syntax error or equivalent somewhere on your side. Since this isn't an issue with the Meteor platform itself however, please consider posting to the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) for further assistance (we're trying to keep GH issues focused on either Meteor platform bugs or feature requests). Closing for now - thanks!

**Closed by hwillson** 2017-03-07 16:47 UTC

**Comment by guiguidu60** [comment] 2017-03-07 16:51
Ok,
I have create a new meteor project and It works.
So, I guess It's a bug in my (big) app but I don't know where...

**Comment by hwillson** [comment] 2017-03-07 16:55
Sorry to hear that @guiguidu60 - you might want to try creating a small reproduction of your app just to help with troubleshooting. The process of trying to cut your app down (removing packages, custom code, etc.) usually helps narrow down and uncover the problem. Good luck!

**Comment by hkabir** [comment] 2020-08-02 11:05
Unfortunately, I am getting "Accounts.onCreateUser is not a function" error. But "Accounts.createUser" works fine. Really confused what is the problem.

**Comment by hexsprite** [comment] 2020-08-02 14:21
@hkabir it's server side only

**Comment by hkabir** [comment] 2020-08-03 11:24
> @hkabir it's server side only

Thanks, But can "Accounts.createUser" work both in server and client? I have used it on the server. But it doesn't work. 

![CreateUser](https://user-images.githubusercontent.com/330789/89177811-0c8fd500-d5ae-11ea-81d5-bd4d1359272d.png)

**Comment by hexsprite** [comment] 2020-08-03 16:52
@hkabir this is an issue tracker for bugs, not the place for questions. Check the docs again, and if it's still not clear try posting on StackOverflow or in the Meteor forums.
