### ISSUE TITLE
Cannot compile android apps on Windows 10 with 2.5.0 or 2.5.1

### ISSUE THREAD

**Issue by cpravetz** [meteor/meteor#11779] opened 2021-11-22 21:03 UTC
Recreated on a clean PC running Win 10.  Meteor 2.5.1.  Steps to recreate:

1. meteor create --bare test
2. cd test
3. meteor add-platform android
4. meteor run android-device

Error is thrown by promise-server.js:218

Error: Command failed: c:\test\.meteor\local\cordova-build\platforms\android\cordova\version is not recognized as an internal or external command, operable program or batch file.
at ChildProcess.exitCallback (...\mt-os.windows.x86-64\dev_bundle\utils\tools\utils\processes.ts:174:23

I believe the problem is in CordovaProject.installedVersionForPlatform.  It triess to launch a file called "version" with no extension, which doesn't work in powershell.

**Comment by renanccastro** [comment] 2021-11-25 11:27
Hello @cpravetz, you can check here someone that had the same issue as you have: https://forums.meteor.com/t/errors-building-android-on-win10-version-is-not-a-command/57037/3?u=renanccastro

The cause is a missing SDK in your system. You can check the pre-reqs and the how to here: https://guide.meteor.com/cordova.html

While we can and should improve the error message, I think this is more appropriate as a broader discussion in our discussions channel: https://github.com/meteor/meteor/discussions

I will close it for now! Thanks for reporting

**Closed by renanccastro** 2021-11-25 11:27 UTC
