### ISSUE TITLE
html5 <video> blob createObjectURL works on ios not on Android

### ISSUE THREAD

**Issue by stormbkk87** [meteor/meteor#3229] opened 2014-12-04 15:36 UTC
MIME types returned from meteor.local client web server has a problem on Android. Below workaround works for iOS 8 and returns 200 success on Android and seems to load into the video tag. Is there something missing for Android? Using a direct link from a public apache web server for this same video works fine on Android.

    HTML
    <video controls id="video-bg"></video>

    JS
    getBlobURL("http://meteor.local/videos/intro.mp4", "video/mp4", function(url, blob) {
        var source = $("<source>");
        source[0].src = url;

        $("#video-bg").append(source);
    });

    function getBlobURL(url, mime, callback) {
      var xhr = new XMLHttpRequest();
      xhr.open("get", url);
      xhr.responseType = "arraybuffer";

      xhr.addEventListener("load", function() {
      
        var arrayBufferView = new Uint8Array( this.response );
        var blob = new Blob( [ arrayBufferView ], { type: mime } );
        var url = null;

        if ( window.webkitURL ) {
            url = window.webkitURL.createObjectURL(blob);
        } else if ( window.URL && window.URL.createObjectURL ) {
            url = window.URL.createObjectURL(blob);
        }

        callback(url, blob);
      });
      xhr.send();
    }

**Comment by nspangler** [comment] 2015-03-04 23:02
@stormbkk87 , @jperl ,  @Slava I am having the same problem. Is there a work-around or solution?

**Comment by glasser** [comment] 2015-03-31 18:31
Can you try this with Meteor at least 1.0.4 (eg 1.0.5, or 1.1 if it's out by the time you read this)?

**Comment by jperl** [comment] 2015-03-31 19:43
@glasser Same problem. I upgraded and tested the repro https://github.com/jperl/repro-meteor-3229

![screen shot 2015-03-31 at 3 40 55 pm](https://cloud.githubusercontent.com/assets/1136652/6927638/a872ce6e-d7bc-11e4-92a8-9e987c9dbfc4.png)

**Comment by glasser** [comment] 2015-04-01 17:44
I was unable to use your reproduction, because I couldn't even take a picture in the Android emulator due to #4069.  How are you able to take a picture?  Is there a reproduction that doesn't involve using the camera?

**Comment by jperl** [comment] 2015-04-01 17:59
Gotcha, I run it on an android device. I'll try to reproduce w/o needing the camera.

**Comment by jperl** [comment] 2015-04-01 20:00
Updated it to use file transfer instead of the camera -- the bug happens for me both on the android emulator and android device. https://github.com/jperl/repro-meteor-3229

**Comment by glasser** [comment] 2015-04-01 20:24
OK, I think this is a duplicate of #3799.

**Closed by glasser** 2015-04-01 20:24 UTC
Labels: Project:Mobile
