### ISSUE TITLE
accounts-facebook configuration confusing for deployment to production

### ISSUE THREAD

**Issue by rivertam** [meteor/meteor#3543] opened 2015-01-23 17:49 UTC
When trying to deploy an app that uses accounts-facebook on a remote server, the ROOT_URL is used. This is reasonable, but can lead to confusion with people who aren't familiar with it (see http://stackoverflow.com/questions/28080036/meteor-facebook-authorization-simply-isnt-working/28115621). The configuration instructions should mention this in the dialog box.

**Comment by glasser** [comment] 2015-01-27 22:23
I'm a little confused about what the issue is.  Is it that people are deploying Meteor apps on their own infrastructure without setting ROOT_URL?  The README in the bundled app tells you to but I now see that http://docs.meteor.com/#/full/deploying doesn't.  Would being more clear in that part of the docs help?  Or maybe you're talking about a change to the dialog box; a PR or generally example of what you think it should say would be helpful.

You might also be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by rivertam** [comment] 2015-01-29 19:42
I suppose the first is the biggest issue. I guess I'm just reporting my experience, so this might not be the best way to do that, and I apologize if it's not. I went through the tutorial on the meteor page and have been working on a few side projects. However, during the entire process, I don't think I've ever actually looked at the "deploying" section of the documentation or the README in the bundled app because I didn't need to. This was probably my mistake. However, based on the way the Facebook authorization is worded, it makes it seem like accounts-facebook is required to speak to Facebook via the localhost URL, regardless of where the site is actually deployed. I'm just suggesting that the instructions in the dialog box when you set up Facebook authorization should say more than just "enter localhost:3000". Maybe putting it in the documentation would be helpful, too, but my note was just about the dialog box.

Right now, under step 6. it says 

Under "Tell us about your website", set Site URL to: http://localhost:3000/ and click "Next".

I think it should say something more like:

Under "Tell us about your website", set Site URL to: http://localhost:3000/ and click "Next"
    note: If you're hosting your site remotely, be sure to change your ROOT_URL environment variable

I know it seems silly, but the configuration button is pretty much only used by Meteor beginners anyways (everyone else just uses Accounts.loginServiceConfiguration, I think) and this confusion sank like 3 hours of time for me.

**Comment by glasser** [comment] 2015-02-03 19:51
You're right, this does seem like a place where the wizard could be more helpful.  Pull requests encouraged.

**Comment by hwillson** [comment] 2017-03-02 16:26
There have been several documentation improvements made since this issue was created. The Guide's [Deployment and Monitoring](https://guide.meteor.com/deployment.html) section outlines how/when to use the `ROOT_URL` environment variable. Given this, I don't think updating the `facebook-config-ui` package installation instructions is necessary. Also, adding something along the lines of the suggested `ROOT_URL` text might actually further confuse some people, since using `ROOT_URL` is not necessary within certain deployment environments/scenarios (like [Galaxy](http://galaxy-guide.meteor.com/environment-variables.html)). Given this, I'll close this issue for now. Thanks for suggesting this initially!

**Closed by hwillson** 2017-03-02 16:26 UTC
Labels: feature, Project:Accounts:OAuth, Project:Docs, pull-requests-encouraged
