### ISSUE TITLE
error with live reload with meteor npm install

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#8328] opened 2017-02-08 01:24 UTC
- [ ] What version of Meteor you're using, and the platform(s) you're running it on: `1.4.2.3`
- [ ] The behavior you expect to see, and the actual behavior:

I expect that while Meteor is running in dev mode and in another terminal I run `meteor npm i` that it will not crash and instead it will gracefully hot reload once the npm install is completed.

Implementation idea: use a special file link to indicate to Meteor that a bulk update command is running eg `.meteor/local/.bulkupdateinprogress`. While that file exists Meteor will pause the hot reload until the file is removed. That would allow a command like `meteor npm i` to run to completion before the hot reload tries to pick up all the changes.

**Comment by abernix** [comment] 2017-02-08 11:31
I can theorize that you might actually be experiencing this problem, but can you please provide more information about the crash you're receiving (i.e. the `actual behavior` portion of the above bullet point)?

The output of the crash is especially nice as it might correlate with other open issues (for example, I believe there's another open issue right now which relates to deleting `node_modules` which this is ultimately a duplicate of).

**Comment by hexsprite** [comment] 2017-02-08 15:13
Fair enough.

```
/Users/jbb/.meteor/packages/meteor-tool/.1.4.2_3.1iou5yb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:77
      this.handle = binding.watch(this.path);
                            ^

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Users/jbb/.meteor/packages/meteor-tool/.1.4.2_3.1iou5yb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:77:29)
    at /Users/jbb/.meteor/packages/meteor-tool/.1.4.2_3.1iou5yb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:53:27
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by hwillson** [comment] 2017-06-07 01:39
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=error%20with%20live%20reload%20with%20meteor%20npm%20install&body=Migrated%20from:%20meteor/meteor%238328) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-07 01:39 UTC
Labels: feature, Project:Tool
