### ISSUE TITLE
Cordova app hangs on iOS with no internet on first load

### ISSUE THREAD

**Issue by zol** [meteor/meteor#3265] opened 2014-12-09 18:43 UTC
### Reproduction

1. Install Todos from the App Store.
2. Enable Airplane mode.
3. Launch Todos.

### Result

The app remains 'stuck' on the splashscreen with a spinner.

### Notes

- Re-enabling airplane mode whilst on the splashscreen will allow the app to continue loading.
- This behavior is only present the first time the app is run. On subsequent runs, with the same reproduction, the app is loaded from disk and is immediately 'offline' (as expected).

**Comment by davidyaha** [comment] 2015-01-12 20:41
+1

**Comment by MartinDelille** [comment] 2015-03-14 17:06
:+1:

**Comment by Slava** [comment] 2015-03-24 22:16
Looks like a pretty critical bug.

**Comment by martijnwalraven** [comment] 2016-02-19 11:08
This only seems to be an issue with the Todos app, I haven't been able to reproduce this behavior with either Local Market or a new skeleton app. I suspect it has to with waiting for data to be available before hiding the splash screen, possibly an interaction with Iron Router. As we are replacing Todos, I'm going to close this issue.

**Closed by martijnwalraven** 2016-02-19 11:08 UTC
Labels: planned, Project:Mobile
