### ISSUE TITLE
This vs global on package level

### ISSUE THREAD

**Issue by Firfi** [meteor/meteor#4105] opened 2015-04-02 10:19 UTC
I have package 1 (reactjs:react@0.2.1 but it isn't important which package it is) which expose variable with `api.export("React", "server");`.

I have package 2 which use package 1: `api.use('reactjs:react@0.2.1', ['server']);`

Then, package 2 imports dist.js file which is generated umd (https://github.com/umdjs/umd) bundle that uses `this` to assign necessary vars to it: `api.addFiles('dist.js', ['server']);`

Problem is, this in dist.js doesn't have variable React in `this` variable. Instead, it can access it only with `var react = React;` style.

Example dist.js:

    var global = Function('return this')() || (42, eval)('this'); // http://stackoverflow.com/questions/3277182/how-to-get-the-global-object-in-javascript
    console.warn('global: ', !!global.React);
    console.warn('this: ', !!this.React);
    console.warn('?: ', !!React);

Output:

    global:  false
    this:  false
    ?:  true

I'd like to know if it is bug and if it is not how I can get global object and what the difference between this and global environment on package level.

**Comment by Firfi** [comment] 2015-04-02 14:48
Thinking of it, actually it is related to my StackOverflow question http://stackoverflow.com/questions/29307018/meteor-api-exports-export-undefined-instead-of-function. In both cases, global variable is being assigned to `this`. When I do api.export my variable, it becomes undefined (as it should it seems, because api.export exports this global scope `undefined`). However, if I **don't** api.export, it is being accessible in code! 

This approach is quite counterintuitive to me so far.

**Comment by glasser** [comment] 2015-04-14 20:35
Meteor doesn't do anything special about `this` in the top level of apps or packages.  I suggest you directly use the specific object you're meaning (if you're trying to get at `window` on the server, say) and to use Meteor's syntax for exporting variables from packages (which looks like assigning to globals, not to properties on `this`).

Note that we're looking into using the standard ES6 module syntax at some point in the future for a more standardized way of doing imports and exports.

**Closed by glasser** 2015-04-14 20:35 UTC
Labels: Project:Isobuild

**Comment by Firfi** [comment] 2015-04-15 02:09
Thanks for the answer. Still, doesn't understand it. Webpack and Browserify clearly use `this` in programmatic builds. Do you suggest to pass `window` instead of `this`, or do you suggest to just wait until better implementation?

**Comment by glasser** [comment] 2015-04-15 05:04
The Meteor linker is not Webpack or Browserify and makes no promises about the top level value of `this`. Maybe this wasn't the best design decision (we've certainly learned a lot about the strengths and weaknesses of the linker since 0.6.5 was released 2 years ago) but this is working as intended.

**Comment by Firfi** [comment] 2015-04-15 05:44
To be clear, I'm not trying to accuse here, just want to know how to make it work (as 'right' way as possible) and then share this experience with community. There's increasing demand in React for instance, and almost all React third-party libs use these builds. So maybe I'll find a way to builders use 'window' instead of 'this' - but to be perfectly clear, is using 'window' would be right way? Would it work with server-side? (can't check right now myself)
