### ISSUE TITLE
[1.4.3-beta.2] Cannot build npm module

### ISSUE THREAD

**Issue by yogiben** [meteor/meteor#8278] opened 2017-01-23 16:23 UTC
We have a npm module that's local to our repo.

`"@proejct/shared": "file:./node_modules/@project/shared",`

Up to the latest official release, this has been building correctly. Since the beta, an error has occurred while trying to run.

```
Error: Cannot find module './config/index.js'
   at require (packages/modules-runtime.js:114:19)
   at meteorInstall.node_modules.@project.shared.index.js (packages/modules.js:604:14)
   at fileEvaluate (packages/modules-runtime.js:188:9)
   at require (packages/modules-runtime.js:111:16)
   at meteorInstall.node_modules.meteor.collections.index.js (packages/collections/index.js:12:21)
   at fileEvaluate (packages/modules-runtime.js:188:9)
   at require (packages/modules-runtime.js:111:16)
   at /Users/user/dev/project/project/v2/.meteor/local/build/programs/server/packages/collections.js:99:15
   at /Users/user/dev/project/project/v2/.meteor/local/build/programs/server/packages/collections.js:105:3
   at /Users/user/dev/project/project/v2/.meteor/local/build/programs/server/boot.js:303:34
=> Exited with code: 1
```

where the offending line is `const Collections = require('@project/shared').Collections;` in a Meteor package, requiring an npm package with the name `@project/shared`

**Comment by abernix** [comment] 2017-01-24 00:01
Nothing jumps out at me from the 1.4.3 changes that would have caused this.  Just to point out the obvious though, there's a typo in `@proejct`, specified above.  I'm not sure if that's a `package.json` definition you've provided there or what.

That being said, please provide a simple reproduction – it's the easiest way for us to be on the same page. :)

**Comment by turashrocks** [comment] 2017-01-25 16:50
If the file is located in your node_module folder than you must write this line of code
`import { YourComponentName } from "@project/shared";`
in top of your .ts file where you want to call along with the name of the Component

**Comment by hwillson** [comment] 2017-02-28 12:44
Hi @yogiben - as mentioned in https://github.com/meteor/meteor/issues/8278#issuecomment-274657996, if you're able to provide a small, runnable reproduction showing this issue, that would greatly help with troubleshooting (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more info). For now though since there isn't much we can do to help further without a reproduction, I'll close this off. Happy to re-open if can post back with a repro - thanks!

**Closed by hwillson** 2017-02-28 12:44 UTC
