### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by edbek** [meteor/meteor#9178] opened 2017-10-05 09:18 UTC
When will fix the error when running meteor on Windows ?

> meteor
...\q\q.js:70
hasStack = !!e.stack; 
                      ^
RangeError: Maximum call stack size exceeded

**Comment by hwillson** [comment] 2017-10-05 11:58
Duplicate of https://github.com/meteor/meteor/issues/9158.

**Closed by hwillson** 2017-10-05 11:58 UTC
