### ISSUE TITLE
seperate facebook/google and the configuration packages

### ISSUE THREAD

**Issue by mxab** [meteor/meteor#4045] opened 2015-03-27 08:07 UTC
Hi,
the google/facebook packages depends at the moment on templating
`api.use('templating', 'client');`

as far as I see it the template html files are only convenience for fast development setup but does not really belong to the functionality of the package itself

would it be possible to do a facebook package and a "facebook-conf-ui" package?

**Comment by glasser** [comment] 2015-04-01 16:44
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by mxab** [comment] 2016-04-29 05:43
@Urigo do you know if there is anything planned? or is there somehow a way around this with 1.3 ? the current meteor-angular-socially app also contains templating/blaze I think cause of the accounts-X packages

**Comment by laosb** [comment] 2016-04-29 07:09
@mxab Not only that one. It is reported that other core packages also depends on blaze.

**Comment by abernix** [comment] 2016-10-18 09:06
Is this is the the same as #7715? (in progress)

**Comment by abernix** [comment] 2017-02-10 09:12
Closing as duplicate of #7715, which is almost complete and, yes, will allow you to use these account packages without the inclusion of `blaze` in the client bundle, ideal for those using Angular or React.  Please follow there for additional updates!

Thanks for making this suggestion initially!

**Closed by abernix** 2017-02-10 09:12 UTC
Labels: feature, Project:Accounts (in user apps), Project:Accounts:OAuth
