### ISSUE TITLE
[1.4.2.3] directory not empty error.

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#8076] opened 2016-11-19 06:22 UTC
![image](https://cloud.githubusercontent.com/assets/8347826/20453524/eded84ae-ae5a-11e6-9c51-050a61d2652f.png)

rerun:
![image](https://cloud.githubusercontent.com/assets/8347826/20453534/347da3ae-ae5b-11e6-927d-ce38715f588b.png)

i dont' know what happen

**Comment by abernix** [comment] 2016-11-21 13:21
Thanks for filing an issue.  There is no reason for this very basic, non-cross-device operation to fail.

The _very likely_ reason that this is happening is that you are using "Bash on Windows" which is still incomplete and has an official warning that you should [expect "some things to work and for many things to fail"](https://msdn.microsoft.com/en-us/commandline/wsl/about).  

I attempted for several hours to get Meteor working with BashOnWindows over the weekend and ran into numerous problems with seemingly basic tasks.  For example `node-gyp install`, a very basic command which simply downloads and extracts the node headers into a directory fails because of a bizarre data flow error.

I was able to work around many things by doing things that I shouldn't have to had done (copying files manually, etc.), but the bottom line is: Bash on Windows is not ready.

There are [a lot of known problems](https://github.com/Microsoft/BashOnWindows/issues), and several which were only fixed by switching to the "Insider" builds which are not automatically released.  Many filesystem issues [are fixed only in internal Microsoft builds](https://github.com/Microsoft/BashOnWindows/issues?q=is%3Aissue+is%3Aopen+label%3Afixinbound).

You may have better luck if you run Bash as administrator but you shouldn't have to if everything is working properly.  Unless you are able to reproduce this problem with `bash` on a stable version of _actual_ Ubuntu, you'll probably need to open this issue [with Microsoft](https://github.com/Microsoft/BashOnWindows/).  For what it's worth, they do seem really eager to get it all working and are closing issues on a regular basis.

I think the only reasonable option here is to wait until Microsoft stabilizes the release and I think #7583 is a sufficient issue to wait for that to happen.

**Closed by abernix** 2016-11-21 13:21 UTC

**Comment by lyquocnam** [comment] 2016-11-21 23:24
yep, i use docker in windows, i tried restart docker and restart container, so it worked again :)
thanks mr @abernix !
