### ISSUE TITLE
server-render Sink class's renderIntoElementById doesn't work.

### ISSUE THREAD

**Issue by maka-io** [meteor/meteor#9429] opened 2017-11-30 02:05 UTC
Meteor Version 1.6
Mac OS Sierra

Expected behavior:
Render SSR generated markup before client rendered content.

Actual Behavior:
sink.renderIntoElementById does nothing.

Explanation:
I have set a timeout of 5 seconds to delay the client side loading in order to visually see if the server side content has loaded.  When I render the server markup into the element defined by ID, nothing happens before the 5 seconds.  After, the content appears proving the that server side content never loads.

If I change to the Sink.renderIndoBody method, I do see the server side markup rendered immediately, and then after 5 seconds the client side markup takes it's place.

It appears that sink.renderIntoElementById is broken, and produces the following warning which is generated by ReactDOM.hydrate (presumably because nothing ever gets loaded to hydrate):

```sh
Warning: Expected server HTML to contain a matching <div> in <div>.
```

Application div to render into:
```html
<body>
    <div id="app"></div>
</body>
```

Server Code:
``` js

import Routes from '../lib/routes.jsx';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { onPageLoad } from 'meteor/server-render';
import { StaticRouter } from 'react-router-dom';
import { ServerStyleSheet } from 'styled-components';
import { createMemoryHistory } from 'history';

onPageLoad(sink => {
    const history = createMemoryHistory(sink.request.url.pathname);

    const App = (props) => (
        <StaticRouter
            location={props.location}
            context={{}}>
            <Routes history={history}/>
        </StaticRouter>
    );

    const sheet = new ServerStyleSheet();
    const html = renderToStaticMarkup(sheet.collectStyles(
        <App location={sink.request.url} />
    ));
    console.log(html);
    sink.renderIntoElementById('app', html);
    sink.appendToHead(sheet.getStyleTags());
});
```

Client Code:

```js
/** @namespace Client */
import Routes from '../lib/routes.jsx';

import React from 'react';
import ReactDOM from 'react-dom';
import { Meteor } from 'meteor/meteor';

import { BrowserRouter } from 'react-router-dom'
import { onPageLoad } from "meteor/server-render";
import { browserHistory } from 'react-router';

const App = () => (
<BrowserRouter>
            <Routes history={browserHistory}/>
</BrowserRouter>
);

Meteor.startup( () => {
    Meteor.setTimeout(() => {
    onPageLoad(sink => {
        ReactDOM.hydrate(<App />,document.getElementById('app'));
    });
    }, 5000);
});
```

Router:
```sh
import React from 'react';
import { Router, Route, IndexRoute } from 'react-router';
import * as Component from './templates.jsx';

const Routes = (props) => (
    <Router history={ props.history }>
        
      <Route path='/' component={ Component.MasterLayout }>
          <IndexRoute component={ Component.Home }/>
      </Route>
      
      <Route path="*" component={ Component.MasterLayout }>
            <IndexRoute component={ Component.NotFound }/>
        </Route>
    </Router>
);
export default Routes;
```

Test Page to Render:
```js
import { Meteor } from 'meteor/meteor';
import React, { Component } from 'react';
import { withTracker } from 'meteor/react-meteor-data';


/**
 * @namespace Client.Component.HomeComponent
 * @memberof Client.Component
 */

/**
 * @memberof Client.Component.HomeComponent
 * @desc This is the root react component that will be wrapped
 * by the createContainer symbol.
 * @extends Component
 */
class HomeComponent extends Component {
    /**
     * @param { object } props The properties (attr) from the react component.
     * e.g. ( <Home title="new" /> , where "title" is the prop )
     *
     * @desc The only declaration here is the "this.state" which is a react object
     * and has special characteristics.  Note: to set this object use "this.setState()"
     */
    constructor(props) {
        super(props);
        this.state = {};
    }

    static propTypes = {

    }

    static defaultProps = {

    }

    /**
     * @public
     * @param { object } nextProps Will contain the next "this.props".
     * @param { object } nextState Will contain the next "this.state".
     * @desc Use shouldComponentUpdate() to let React know if a component's
     * output is not affected by the current change in state or props. The
     * default behavior is to re-render on every state change, and in the
     * vast majority of cases you should rely on the default behavior.
     *
     * If you are confident you want to write it by hand, you may compare
     * this.props with nextProps and this.state with nextState and return
     * false to tell React the update can be skipped.
     * @returns { bool } This needs to be either true or false.
     */
    shouldComponentUpdate(nextProps, nextState) {
        return true;
    }

    /**
     * @public
     * @desc componentWillMount() is invoked immediately before mounting
     * occurs. It is called before render(), therefore setting state in this
     * method will not trigger a re-rendering. Avoid introducing any
     * side-effects or subscriptions in this method.
     */
    componentWillMount() { }

    /**
     * @public
     * @desc When called, it should examine this.props and this.state and
     * return a single React element. This element can be either a representation
     * of a native DOM component, such as div, or another composite component
     * that you've defined yourself.
     * The render() method is required.
     *
     * Note: render() will not be invoked if shouldComponentUpdate() returns false.
     */
    render() {
        return (<h2 className="home">test</h2>);
    }

    /**
     * @public
     * @desc componentDidMount() is invoked immediately after a component is mounted.
     * Initialization that requires DOM nodes should go here. If you need to load
     * data from a remote endpoint, this is a good place to instantiate the network
     * request. Setting state in this method will trigger a re-rendering.
     *
     */
    componentDidMount() { }

    /**
     * @public
     * @desc componentWillUnmount() is invoked immediately before a component
     * is unmounted and destroyed. Perform any necessary cleanup in this
     * method, such as invalidating timers, canceling network requests, or
     * cleaning up any DOM elements that were created in componentDidMount
     */
    componentWillUnmount() { }
}

/**
 * @memberof Client.Component.HomeComponent
 *
 * @desc
 * Set up the data context for our component
 * This is where we would create our Meteor.subscribe handler as
 * well as any other context properties that will need to be reactive.
 *
 * Refer to this page for more information on the symbol
 * https://github.com/meteor/react-packages/tree/devel/packages/react-meteor-data
 */

const Home = withTracker((props) => {
        return {};
    })
(HomeComponent);

export { Home, HomeComponent };
```
Result When loaded:
![screen shot 2017-11-29 at 8 52 53 pm](https://user-images.githubusercontent.com/3743882/33409013-4ce7b150-d547-11e7-8a2d-c761d14fe389.png)

Server Response:
![screen shot 2017-11-29 at 8 54 05 pm](https://user-images.githubusercontent.com/3743882/33409058-72f55438-d547-11e7-9548-61c22c0005ea.png)

**Comment by benjamn** [comment] 2017-11-30 14:37
Are you using the `static-html` package to handle `.html` files, or something else (like `blaze-html-templates`)?

Can you put these files into a small reproduction repo so that we can test it out more easily?

**Comment by theodorDiaconu** [comment] 2017-12-01 21:25
Do a check with this repo: https://github.com/cult-of-coders/meteor-ssr-react-router-demo I actually managed to play a bit with SSR, dynamic imports, and some other crazy things, and they worked out as expected.

**Comment by maka-io** [comment] 2017-12-04 21:07
@benjamn I'm using blaze-html-templates, I'll push up a repo to test with.

@theodorDiaconu I'll check it out.  I'm able to get the ssr working fine, as long as I render into the body using 
``` js 
sink.appendToBody(html); 
```
however declaring the id of the element does nothing:

``` js 
sink.renderIntoElementById('app', html);
```

**Comment by maka-io** [comment] 2017-12-04 21:10
@benjamn I just tried static-html, and I think that may actually do the trick!  I'll run a few more tests and let you know.

**Comment by benjamn** [comment] 2017-12-05 15:29
@maka-io OK, cool! Just to expand on my hunch, `static-html` generates HTML that the `server-render` package can manipulate (because it's static), whereas `blaze-html-templates` generates HTML at runtime, after the `server-render` package runs.

**Comment by hwillson** [comment] 2017-12-12 15:46
@maka-io Did the suggestion in https://github.com/meteor/meteor/issues/9429#issuecomment-349338871 help? I'll close this for now, but let us know if this is still an issue. Thanks!

**Closed by hwillson** 2017-12-12 15:46 UTC

**Comment by msteinmn** [comment] 2018-02-10 17:36
Yes, replacing blaze-html-templates package with static-html package solves this problem with sink.renderIntoElementById not getting inserted.

**Comment by macrozone** [comment] 2018-03-21 13:51
@benjamn just ran into this after created an empty project. Maybe we should mention that somewhere!
