### ISSUE TITLE
Load order issue with meteor 1.2

### ISSUE THREAD

**Issue by netanelgilad** [meteor/meteor#5285] opened 2015-09-25 10:20 UTC
Hey guys,
So there seems to be an undocumented change (as far as I know) with the working of .js load order. Before 1.2 files that were compiled from another file extension into js files were loaded using the same load order that all files had. Since Meteor 1.2 it seems that files that are compiled into js from another extension are always loaded first, no matter where they are in the folder hierarchy.
You can find a quick reproduction here: https://github.com/netanelgilad/meteor-1.2-load-order-bug. running with meteor prior 1.2 will log to console in the correct order (lib files first) but with meteor 1.2 the order is reversed...

**Comment by glasser** [comment] 2015-09-25 15:38
Huh, I'm pretty sure this is because [the angular plugin specifies isTemplate: true](https://github.com/Urigo/angular-meteor/blob/master/plugin/annotate.js#L5).  The only effect of this flag is to ensure that all template files load before non-template files (there is no other effect).  That logic is very old. Are you sure this worked before 1.2?  Can you show me a version of Meteor/angular (ie a reproduction) where this wasn't the case?

**Comment by glasser** [comment] 2015-09-25 15:43
OH, I see what's happening here.

Before 1.2, here was [the code that detected isTemplate](https://github.com/meteor/meteor/blob/release/METEOR@1.1.0.3/tools/package-source.js#L48-L49):

```
    var isTemplate_a = _.has(templateExtnames, files.pathExtname(a));
    var isTemplate_b = _.has(templateExtnames, files.pathExtname(b));
```

In 1.2, [here's the code](https://github.com/meteor/meteor/blob/release/METEOR@1.2.0.1/tools/isobuild/package-source.js#L32-L44):

```
  const isTemplate = _.memoize((filename) => {
    const classification = sourceProcessorSet.classifyFilename(filename, arch);
    switch (classification.type) {
    case 'extension':
    case 'filename':
      if (! classification.sourceProcessors) {
        // This is *.js, not a template. #HardcodeJs
        return false;
      }
      if (classification.sourceProcessors.length > 1) {
        throw Error("conflicts in compiler?");
      }
      return classification.sourceProcessors[0].isTemplate;
```

Basically we switched it from a moderately hacky "use path.extname to look at the extension" thing to "use the same logic used everywhere else in the codebase to figure out what the file type is" (which now lives in an object called SourceProcessorSet).

The old version meant that if you had a multi-part extension like "ng.js", isTemplate would be completely ignored.

I think it's pretty clear that the new version is better, since it treats multi-part extensions the same as single-part extensions.

But that also means that in the past, `isTemplate: true` on `*.ng.js` files was basically ignored, so probably the right answer is to just remove that from the plugin!

I am going to close this because I don't think this is a core meteor bug.

**Closed by glasser** 2015-09-25 15:43 UTC
Labels: Project:Isobuild

**Comment by netanelgilad** [comment] 2015-09-25 15:52
Nice, that did it! Thanks!

**Comment by glasser** [comment] 2015-09-25 15:53
btw thanks for the reproduction, it made finding the issue easy!
