### ISSUE TITLE
[1.4.2.1] Won't run at all on Ubuntu 16.04 desktop

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#7923] opened 2016-10-13 23:33 UTC
When I try to run my app on Ubuntu 16.04, I get the following failure:

```
=> Started proxy.                             
=> Started MongoDB.                           
/home/samh/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-fuguq0/plugin.minifyStdCSS.os/program.json'
    at Error (native)
```

This is even after a fresh wipe of the local package repos (`rm -rf node_modules && rm -rf ~/.meteor`).

Trying to collect more specific details as to what might be causing it - will update this post.

**Comment by ffxsam** [comment] 2016-10-13 23:41
Was able to repro from scratch:

```
$ meteor create uhoh
$ cd uhoh
$ meteor add universe:i18n
```

On Mac OS, last I checked, I didn't have any issues with this.

**Comment by rhettlivingston** [comment] 2016-10-14 02:09
This looks like #7904 and is likely also the same as #7806 which I encountered on Ubuntu 16.04 as well and was able to work around by issuing the command `ulimit -n 4096` prior to invoking meteor. You might give that a shot.

**Comment by catin-black** [comment] 2016-10-14 08:18
+1 on vagrant

even meteor --version do not work

````
vagrant@precise64:~/app$ meteor --version
/home/vagrant/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: EPROTO: protocol error, stat '/home/vagrant/app/.meteor/local/dev_bundle'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Object.realpathSync (fs.js:1456:12)
    at exports.readLink (/tools/cli/dev-bundle-links.js:31:19)
    at [object Object].ensureDevBundleLink (/tools/project-context.js:1407:25)
    at [object Object]._readFile (/tools/project-context.js:1350:10)
    at new exports.ReleaseFile (/tools/project-context.js:1300:8)
    at /tools/cli/main.js:825:22
````

**Comment by catin-black** [comment] 2016-10-14 08:31
I removed ./meteor/local and start app with:

````
MONGO_URL="mongodb://localhost:27017/meteor" meteor --settings settings.json
````

**Comment by MichalW** [comment] 2016-10-14 11:49
+1
`$meteor`
`/home/michal/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165`
`      throw error;`
`      ^`
` `
`Error: ENOENT: no such file or directory, open '/tmp/mt-1sussnk/os.json'
    at Error (native)`

**Comment by graywolf336** [comment] 2016-10-16 03:33
Seems this fixes it for me: http://stackoverflow.com/questions/39153477/how-do-i-resolve-this-error-enoent-no-such-file-or-file-or-directory-open-t/39174861#39174861

**Comment by abernix** [comment] 2016-10-17 05:46
Thanks for opening this.  The fix that @graywolf336 posted should work.  This issue is a duplicate of #7904 and essentially the same as #7806 (which offers the same solution as the SO post above).

Either way, this is a failing CDN + failed extraction issue (from Meteor working with an incomplete tarball).  Closing in favor of the existing issue.

**Closed by abernix** 2016-10-17 05:46 UTC
