### ISSUE TITLE
More useful refreshing progress: "refreshing .. Done"

### ISSUE THREAD

**Issue by KrishnaPG** [meteor/meteor#3297] opened 2014-12-16 10:23 UTC
Presently Meteor (upon updating any piece of code during development), automatically rebuilds the code and the client browser gets updated.

Sometimes, the build / refresh process takes some time (about a minute on VMs and older machines) - the present "Client modified -- refreshing" is not really a useful status indicator (if the refresh was complete or not). On the client browser, we wouldn't know if we should wait for some more time (to let the refresh complete) or if it has already completed and client was already refreshed.

It would better if more useful stat is provided on the console - may be a time stamp of last refresh or at least "refresh Done" statement once its done.

**Comment by glasser** [comment] 2015-01-13 22:02
The line `Client modified -- refreshing` *is* the "refresh is done" indicator.  If it's still rebuilding, you should see something more specific like "Building the application" (which disappears when the rebuidl is done).

Note that a lot of the UX around rebuilds improved in 1.0.2/1.0.2.1, which were released in the week after this bug was filed, so I'm going to close this one since hopefully it is improved in 1.0.2.

**Closed by glasser** 2015-01-13 22:02 UTC

**Comment by nilsi** [comment] 2015-05-14 08:00
When my app is refreshing the client it says "Client modified -- refreshing (x2)" and when it finished it changes into "Client modified -- refreshing (x3)". So the change of the number tells me its finished. But the problem is that I often forgetting what number is the latest one. Is there a way to change this to something else like a timestamp? Or even better a percentage bar that tells me how much is left, since it sometimes take a minute or more for my app to update.

**Comment by rclai** [comment] 2015-05-14 12:24
Yes, it would be nice if it would say `rebuilding client code`, and then `Client modified -- refreshing (x3)`. Otherwise I lose count.

**Comment by sketch34** [comment] 2017-05-02 22:49
What does the `(x2)` (x3)` mean?

@glasser `=> Client modified -- refreshing (x3)` reads like the refresh is still in progress. Some less ambiguous language should be used here.

**Comment by glasser** [comment] 2017-05-02 23:05
It means that it has printed the same message multiple times.
