### ISSUE TITLE
crash on windows after 1.5 updade

### ISSUE THREAD

**Issue by mscherer82** [meteor/meteor#8750] opened 2017-06-02 09:28 UTC
I updated my project to 1.5. When I tried to run meteor crashed with the following message:

```
   Building for web.browser                  |
<--- Last few GCs --->

  180622 ms: Scavenge 700.4 (742.7) -> 700.4 (742.7) MB, 1.0 / 0 ms (+ 215.0 ms in 1 steps since last GC) [allocation failure] [incremental marking de
laying mark-sweep].
  182045 ms: Mark-sweep 700.4 (742.7) -> 693.0 (739.3) MB, 1423.6 / 0 ms (+ 303.0 ms in 12 steps since start of marking, biggest step 215.0 ms) [last
resort gc].
  183657 ms: Mark-sweep 693.0 (739.3) -> 693.4 (739.3) MB, 1611.6 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 2EC6CC95 <JS Object>
    1: mark [C:\Users\Marc\AppData\Local\.meteor\packages\ecmascript\0.8.0\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_mo
dules\babel-generator\lib\source-map.js:~59] [pc=4F7D76CC] (this=45E15251 <a SourceMap with map 4C385389>,generatedLine=57354,generatedColumn=60,line=
275,column=29155,identifierName=2EC08081 <null>,filename=2EC08081 <null>)
    2: append [C:\Users\Marc\...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

**Comment by s7dhansh** [comment] 2017-06-02 13:09
For me, this problem is only during build. Increasing max-old-space-size works.
```
TOOL_NODE_FLAGS="--max-old-space-size=4096" meteor
```

But now, the build process is very slow (almost three times slower).

**Comment by hwillson** [comment] 2017-06-02 15:06
Thanks for reporting this @mscherer82. This is, however, a duplicate of #8157 (which has a much larger discussion associated with it), so I'll close this issue. Please add any additional details, findings, questions, etc. to that thread. Thanks!

**Closed by hwillson** 2017-06-02 15:06 UTC
