### ISSUE TITLE
Template.parentData doesn't work with custom block helpers

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#3303] opened 2014-12-17 00:57 UTC
```sh
git clone https://github.com/dandv/meteor-parent-data-1-bug.git
meteor run
```

Click on `bar` under `custom block helper`. Notice how `Parent(1) data` is `null`.

Since the `player` template does have a parent template called `myEach` (as defined via `<template name="myEach">`), I would expect `Template.parentData(1)` from the `player` click event to return the `players` array.

**Comment by avital** [comment] 2015-01-06 05:59
Looks like a dup of #2923, where a workaround is suggested.

**Comment by stubailo** [comment] 2015-01-07 16:18
Definitely a dup. What's the policy, should we close this one and leave the other one?

**Comment by avital** [comment] 2015-01-07 19:31
I think leave the earlier one open, which presumably has more comments on it.

**Comment by stubailo** [comment] 2015-01-23 22:25
Working on this now!

**Comment by stubailo** [comment] 2015-01-23 23:12
It turns out that this is partially intended behavior, but I think it should be changed to fit this reproduction.

**Comment by stubailo** [comment] 2015-01-28 19:11
try running your app with `meteor --release TEMPLATE-CURRENT-DATA@0.0.1`, this includes the fix we just merged for this issue. let me know if it's fixed!

**Comment by avital** [comment] 2015-02-11 01:01
@dandv can you check if this is fixed on the `TEMPLATE-CURRENT-DATA@0.0.1` release?

**Comment by fpoirier1** [comment] 2015-02-11 16:49
I was facing the same issue and I can confirm that it is fixed with the `TEMPLATE-CURRENT-DATA@0.0.1` release.

**Comment by stubailo** [comment] 2015-02-11 17:12
Awesome. This will be out in the next official release (probably 1.0.4) so I'm going to close this issue.

**Comment by fpoirier1** [comment] 2015-02-13 19:35
I don't know if this is related but the `firstNode` and `lastNode` properties are `null` but when I do `console.log(this)` un the rendered callback of the template they have a value.

**Comment by stubailo** [comment] 2015-02-13 20:11
Can you give a full reproduction in the form of an app?

**Comment by fpoirier1** [comment] 2015-02-25 15:33
I realise the `firstNode` and `lastNode` properties are `null` inside helpers because the template is not finished rendering. So that's probably not an issue anyway here is a reproduction.

https://github.com/fpoirier1/meteor-template-data

**Comment by fpoirier1** [comment] 2015-02-25 15:44
BTW, any idea when the next release would official ? I tried `METEOR@1.0.3.2-rc.0` but the issue still happens. I can't deploy my app on modulus with `TEMPLATE-CURRENT-DATA@0.0.1`...

**Comment by stubailo** [comment] 2015-03-09 21:47
@dandv We fixed the problem that block helpers affected the result of `Template.currentData`

**Closed** 2015-03-09 21:48 UTC
Labels: Project:Blaze
