### ISSUE TITLE
Strange issue with deploying using old code

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6522] opened 2016-03-18 01:58 UTC
(Need to try and replicate with a simple app).

I'm deploying tutorial-viewer.
1. Yesterday I deployed version X
2. I've made changes, to Y, viewed locally
3. I deploy again, the version deployed is still X.
4. I run it again locally **NOW I SEE X**
5. I change a file locally, app rebuilds, **NOW I SEE Y**
6. Re-deploy, go to step 3.

**Comment by tmeasday** [comment] 2016-03-18 02:02
Note that this is *not* a file-caching issue, changing a single file at step file affects multiple templates

**Comment by tmeasday** [comment] 2016-03-18 02:04
@stubailo could this issue be something weird that your simple:markdown-templating package is doing wrt caching compilers?

**Comment by tmeasday** [comment] 2016-03-18 02:07
I did a `meteor reset` and was able to deploy version Y.

**Comment by tmeasday** [comment] 2016-03-18 02:08
(We should investigate what's going on here probably though).

**Comment by stubailo** [comment] 2016-03-18 02:27
No, I don't think my package should be the cause. I might not have updated it since before 1.2 anyway. So maybe it's some sort of backcompat issue? Who knows.

**Comment by tmeasday** [comment] 2016-03-18 03:02
Could be. I did upgrade the tutorial viewer to 1.2

**Comment by hwillson** [comment] 2017-01-23 18:05
There hasn't been any activity on this issue in a while, and the [tutorial-viewer](https://github.com/meteor/tutorial-viewer) has been stable (i.e. not touched) for a year. Closing this off - thanks!

**Closed by hwillson** 2017-01-23 18:05 UTC
