### ISSUE TITLE
process.env.NODE_ENV is set to 'production' on initial iOS build

### ISSUE THREAD

**Issue by dburles** [meteor/meteor#8096] opened 2016-11-23 03:14 UTC
The NODE_ENV environment variable on first build is set to `production` and not `development` as expected, though on subsequent builds it's `development`.

Reproduction:
`$ rm -rf .meteor/local/cordova_build` (if it exists)
`$ meteor run ios-device`

`=> production`

This simple reproduction app just logs the variable from `server/main.js` https://github.com/dburles/meteor-issue-ios-node-env

**Comment by abernix** [comment] 2016-12-07 17:01
Thanks for reporting this!  Definitely can mark this as confirmed!  I spent a bit of time on this and I understand what's happening but I'm not entirely sure of what the best solution would be.  I'm a bit concerned that this could be causing a number of other bizarre Cordova issues as well, for example #7029 or #7375 but possibly others as well.  There are also issues which come to mind where users are stating that they remove `.meteor/local/cordova-build` before each run (for example, https://github.com/meteor/meteor/issues/6761#issuecomment-249350516).

A quick run-down of what's happening here:

* When the `meteor run <anything-cordova>` occurs for the first time, it instantiates a `CordovaProject` [on these lines](https://github.com/meteor/meteor/blob/4418acd08099d00bc9471d98a67cefa7c5c46d56/tools/cli/commands.js#L349-L351).  Immediately before this, `process.env.NODE_ENV` is `undefined`.  When it continues, `process.env.NODE_ENV` is (incorrectly) set to `production`.
* During the `CordovaProject` init, the [`cordova-support` isopacket](https://github.com/meteor/meteor/blob/4418acd08099d00bc9471d98a67cefa7c5c46d56/tools/tool-env/isopackets.js#L57-L58) is getting loaded [in this function](https://github.com/meteor/meteor/blob/4418acd08099d00bc9471d98a67cefa7c5c46d56/tools/cordova/builder.js#L222) so it can utilize `xmlbuilder`.
* To load the `isopacket`, it loads some dependencies that it needs, namely the [`meteor` package](https://github.com/meteor/meteor/blob/4418acd08099d00bc9471d98a67cefa7c5c46d56/packages/meteor/package.js#L28) which brings in `server_environment.js` which [runs these lines](https://github.com/meteor/meteor/blob/devel/packages/meteor/server_environment.js#L3-L7) and sets an internal `meteorEnv` variable with `NODE_ENV` of `production` (among other things).
* This would be fine, but another dependency that is loaded during the loading of the `isopacket` is [`modules`](https://github.com/meteor/meteor/blob/devel/packages/modules/package.js#L1) which [loads](https://github.com/meteor/meteor/blob/devel/packages/modules/server.js#L3) the `process.js` file which overwrites `process.env` with `meteorEnv` [on this line](https://github.com/meteor/meteor/blob/4418acd08099d00bc9471d98a67cefa7c5c46d56/packages/modules/process.js#L27).

Now I can see two ways to fix this, but I haven't looked into the consequences of them yet:

* The obvious answer is to just set `buildMode` to `development` when calling `runAll.run` [here](https://github.com/meteor/meteor/blob/4418acd08099d00bc9471d98a67cefa7c5c46d56/tools/cli/commands.js#L1835) and [here](https://github.com/meteor/meteor/blob/4418acd08099d00bc9471d98a67cefa7c5c46d56/tools/cli/commands.js#L370).
* Anther option to consider would be to stop the loading of `meteorEnv` into `process.env` if it was done during the loading of an isopacket as I'm not sure if the loading of an isopacket should ever be modifying `process.env`?  I believe this could be done by ensuring that `Meteor.release !== "ISOPACKET"` before the `_.extend(process.env, meteorEnv)`.  (`ISOPACKET` is a special `meteorRelease` value set in `loadIsopacketFromDisk` [here](https://github.com/meteor/meteor/blob/4418acd08099d00bc9471d98a67cefa7c5c46d56/tools/tool-env/isopackets.js#L283)).  This may be a good option since it avoids this happening in other (future?) cases where an isopacket might be loaded before `process.env.NODE_ENV` is set.

**Comment by dburles** [comment] 2016-12-08 01:49
A simple workaround is to run like: `NODE_ENV=development meteor run ios`

**Comment by abernix** [comment] 2016-12-08 07:31
That brings up the problem with implementing the first bullet point (setting `buildMode` = `development`) I described above.  It would no longer be possible to set `NODE_ENV` as an environment variable when running `meteor run` (the tool) – the production bundle would still work.  This brings into question the intent of 2c617225cd706d65e9648edaa7ee58f26a1f1200 (see commit msg and #6461) and also #6399.

The second bullet point should be fine.

**Comment by hwillson** [comment] 2017-11-06 12:48
I've confirmed this is still an issue with Meteor 1.6.

**Comment by skirunman** [comment] 2018-02-05 17:09
@hwillson can we get the Project:mobile tag added to this issue?

**Comment by hwillson** [comment] 2018-04-10 17:37
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity. If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!

**Comment by benjamn** [comment] 2018-04-25 16:10
At long last, this issue appears to be fixed in Meteor `1.7-beta.24`, thanks to this commit: https://github.com/meteor/meteor/pull/9826/commits/6bcf2fbee9f48fb56ef42cdbe17cfcb88f0955c7

Thanks for your reproduction, @dburles, and thanks to everyone for their patience (though you certainly can't be faulted for losing patience after a year and a half).

**Closed by benjamn** 2018-04-25 16:10 UTC
Labels: Impact:some, Project:Isobuild, Project:Mobile, Severity:has-workaround, bug, confirmed, known-fix, not-implemented, pull-requests-encouraged
