### ISSUE TITLE
Unhelpful errors from build plugin.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4385] opened 2015-05-14 06:32 UTC
I'm making a build plugin, registering it with `Package.registerBuildPlugin`. When my plugin code runs, I'm getting an unhelpful error that looks like this:

```
=> Errors prevented startup:

   While loading plugin `rocket:module` from package `rocket:module`:
   <runJavaScript-126>:226:35: Unexpected token :
   at parseInfoFromPackageDotJs (<runJavaScript-126>:226:35)
   at getPackageInfo (<runJavaScript-126>:237:16)
   at <runJavaScript-126>:91:19
   at arrayReduce
   (/Users/josephpea/src/trusktr+meteor-with-webpack/meteor/packages/module/.npm/plugin/rocket:m
odule/node_modules/lodash/index.js:1516:23)
   at Function.<anonymous>
   (/Users/josephpea/src/trusktr+meteor-with-webpack/meteor/packages/module/.npm/plugin/rocket:m
odule/node_modules/lodash/index.js:3505:13)
   at dependentsOf (<runJavaScript-126>:90:14)
   at Package (<runJavaScript-126>:99:13)
   at <runJavaScript-126>:405:4
   at <runJavaScript-126>:412:3
```

Those locations are meaningless (f.e. `<runJavaScript-126>:226:35:`). It'd be nice if the error would give the actual line numbers and columns from my actual plugin file.

**Comment by trusktr** [comment] 2015-05-14 06:35
Oh, wait, it's because I have an `eval()` in there. hmmmm....

**Comment by trusktr** [comment] 2015-05-14 07:03
Okay, I got past the eval error, but now I'm getting similarly unhelpful errors with normal code (no eval):

```
=> Errors prevented startup:

   While loading plugin `rocket:module` from package `rocket:module`:
   <runJavaScript-138>:92:80: Cannot call method 'match' of undefined
   at <runJavaScript-138>:92:80
   at baseFindIndex
   (/Users/josephpea/src/trusktr+meteor-with-webpack/meteor/packages/module/.npm/plugin/rocket:m
odule/node_modules/lodash/index.js:322:11)
   at Function.<anonymous>
   (/Users/josephpea/src/trusktr+meteor-with-webpack/meteor/packages/module/.npm/plugin/rocket:m
odule/node_modules/lodash/index.js:3302:23)
   at <runJavaScript-138>:92:26
   at arrayReduce
   (/Users/josephpea/src/trusktr+meteor-with-webpack/meteor/packages/module/.npm/plugin/rocket:m
odule/node_modules/lodash/index.js:1516:23)
   at Function.<anonymous>
   (/Users/josephpea/src/trusktr+meteor-with-webpack/meteor/packages/module/.npm/plugin/rocket:m
odule/node_modules/lodash/index.js:3505:13)
   at dependentsOf (<runJavaScript-138>:90:14)
   at Package (<runJavaScript-138>:99:13)
   at <runJavaScript-138>:407:4
   at <runJavaScript-138>:414:3


=> Your application has errors. Waiting for file change.
```

Why are the errors unhelpful? Is this because the error is lodash's hands, and it's not being handled well?

**Comment by Slava** [comment] 2015-05-19 18:32
Do you use `coffeescript` anywhere in your app? We believe, we just fixed it on `devel`: https://github.com/meteor/meteor/commit/2922dd454b1c8fc394e222db738eddf128dd4cc6

In recent versions, coffeescript started overriding `Error.prepareStackTrace` that conflicts with Meteor's override. Bugs like this are hard to track, since it is caused by some other module and is not easy to find in isolation. This is exactly why we require a clonable reproduction with every bug report.

Closing this thinking our patch fixed it. If a reproduction appears proving otherwise, we can reopen.

**Closed by Slava** 2015-05-19 18:32 UTC

**Comment by trusktr** [comment] 2015-05-19 20:17
Hi @Slava, I'm not using coffee script. If I can find a way to reproduce consistently next time I run into this, I'll make a branch on my repo with it. Thanks for checking!
