### ISSUE TITLE
doc.meteor.com does not work on Firefox

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3380] opened 2014-12-29 08:56 UTC
Mac OS X, Firefox 34.0. It simply does not show anything. I have to add a random `?<random>` to even start loading something, but even then it creates a websocket connection, but this is it. There is only this warning:

```
Warning: Blaze.render without a parent element is deprecated. You must specify where to insert the rendered content."
```

**Comment by glasser** [comment] 2015-01-14 01:31
I'm going to close this as duplicate of #3248. One of them was "reloads a lot" and the other is "doesn't work", but they both seem to be generally "docs/appcache doesn't work well on Firefox, especially around updates".

**Closed by glasser** 2015-01-14 01:31 UTC
