### ISSUE TITLE
Importing v8-profiler as devDependency in development causes npm module resolution error

### ISSUE THREAD

**Issue by carlevans719** [meteor/meteor#9105] opened 2017-09-18 12:06 UTC
After upgrading to Meteor 1.6-beta.27, attempting to import `v8-profiler` fails with a "Cannot find module './build/profiler/v5.7.0/node-v57-linux-x64/profiler.node'" error.

- Meteor version 1.5.2 works as expected.
- OS is Ubuntu 16.04
- Repro is [here](https://github.com/carlevans719/v8-profiler-repro)

The error starts when v8-profiler attempts to [require a file](https://github.com/node-inspector/v8-profiler/blob/master/v8-profiler.js#L2). It seems the the Meteor build tool hasn't copied the file into `packages/modules.js` which is why the error is thrown. There _are_ entries for the following two files in `modules.js`:
```
node_modules/v8-profiler/package.json
node_modules/v8-profiler/v8-profiler.js
```
But v8-profiler is trying to resolve (in my case):
  `./build/profiler/v5.7.0/node-v57-linux-x64/profiler.node`
which I think would equate to:
  `node_modules/v8-profiler/build/profiler/v5.7.0/node-v57-linux-x64/profiler.node`
 in `modules.js`.

**Comment by abernix** [comment] 2017-09-18 12:41
Your reproduction works fine for me, but I'll warn you that I used `meteor npm install` and not `npm install` to ensure that the correct version of Node.js was used.  This is very important for npm modules which have binary dependencies, as `v8-profiler` does.  For example, if you used `npm install` but `node --version` didn't return a Node.js 8 version (and more technically, a Node.js 8 version which used the same ABI as Meteor's Node 8.5.0, currently v57), you would have compiled the Node module into your `node_modules/v8-profiler` directory with the wrong version of Node.js and Meteor would have ultimately tried loading the `v8-profiler` addon with Node.js 8.5.0.

Additionally, as https://github.com/node-inspector/v8-profiler/issues/114 and https://github.com/node-inspector/v8-profiler/issues/117 hint at, there haven't been ABI 57 versions of the binaries published for [`node-pre-gyp`](https://github.com/mapbox/node-pre-gyp) (which tries to save you the hassle of compiling native addons) to find.   I have my machine setup with [the compiler toolchain](https://github.com/nodejs/node-gyp#on-mac-os-x) necessary to build `v8-profiler` from source, so it was compiled during my `meteor npm install`.

Can you try making sure that you have the correct build tools on your machine and try `meteor npm install v8-profiler` again?  Please provide the output if you continue to have problems!

**Comment by carlevans719** [comment] 2017-09-18 12:49
Quite right - thanks.
Turns out I am running node 4.8.4 and I did use `npm install` instead of `meteor npm install`.

Closing as using `meteor npm install` works. Thanks again

**Comment by carlevans719** [comment] 2017-09-18 13:11
Sorry @abernix - turns out the reproduction was slightly wrong. I _still_ get the issue if the module is installed as a dev dependency. I've updated the repro to show the issue.

Is this expected behaviour for dev dependencies or is it a bug?

**Comment by abernix** [comment] 2017-09-18 13:42
That behavior is the same in Meteor 1.5.2 though, right?

If so, sounds like it's a duplicate of https://github.com/meteor/meteor/issues/7990.  Though I think failure is doing you somewhat of a favor since the reproduction you provided would absolutely crash if you deployed it to production (where `devDependencies` are stripped).

Perhaps you want to put `v8-profiler` in `dependencies` but nest the `import` inside a `if (Meteor.isDevelopment) {}` conditional?

Either way, I think #7990 is the same.  (And I'm happy to adjust the title of it accordingly.)

**Comment by carlevans719** [comment] 2017-09-18 14:47
I'll check 1.5.2 now. In my actual code I do have the `import` nested in `if (Meteor.isDevelopment) {}` - I just stripped it out for the repro.

This issue does seem to differ from #7990 in a couple of (minor) ways:
- devDependencies _are_ importable when using the runner in development
- dynamic `require`s inside devDependency modules are _not_ copied into the bundle in development

So it seems to me that this issue can be described as _"certain files/folders inside devDependency npm modules are stripped from the built app **even in development mode**, causing resolution failures"_

That being said, davidyuk/meteor@c609c3e looks like it might fix this issue too. I'll spin up his patch now and let you know whether it resolves this issue.

Out of interest; if I was to put `v8-profiler` in `dependencies` and leave the `import` wrapped in `if (Meteor.isDevelopment) {}`, would it still be included in the production build or is the linker able to see that it's wrapped in the conditional and only imported in development?
I imagine it would still be in the generated app's `package.json` so any CI would extract the bundle and then unknowingly install the module anyway (which I imagine is probably less of an issue as it would only impact disk usage and not memory, right)?

**Comment by hwillson** [comment] 2017-12-01 18:23
Hi all - the stripping of `devDependencies` in development mode is by design. I'll recap the reasoning for this from https://github.com/meteor/meteor/issues/7990#issuecomment-337708608:

> As of Meteor 1.4.2, devDependencies are stripped (from the bundled application) in everything except test mode. This means that if you want to access faker in development, you will need to add it to your package.json's dependencies section. If access to devDependencies based packages was allowed in development mode, the development version of your application could behave differently than your production application (since those devDependencies would be stripped in production). This could lead to bugs in production that don't appear in development, when the code that references a development dependency can't execute properly. For example, import's and require's associated with devDependencies would have to be handled differently between development and production (e.g. by catching lookup exceptions - yuck).

Thanks!

**Closed by hwillson** 2017-12-01 18:23 UTC
