### ISSUE TITLE
SyntaxError after the minification of Blaze.View.prototype.lookup

### ISSUE THREAD

**Issue by Deilv** [meteor/meteor#5179] opened 2015-09-15 21:41 UTC
**_1 Upvote**_ I recently noticed that Firefox throws an error "SyntaxError: unreachable code after return statement" in the console. After digging up a little I found out that during compilation (minification) a "return null;" is appened at the end of function "Blaze.View.prototype.lookup" in file ./packages/blaze/lookup.js which seems to be the cause of the problem.
This occurs constantly in meteor 1.1.0.3, not sure if it's already fixed.

**Comment by benjamn** [comment] 2015-09-15 21:42
Can you paste the minified code here?

**Comment by iliasch** [comment] 2015-09-15 21:43
Sure:
c.View.prototype.lookup=function(e,a){var o=this.template,s=a&&a.template,u,l;if(this.templateInstance&&(l=i.bind(this.templateInstance,this)),/^\./.test(e)){if(!/^(\.)+$/.test(e))throw new Error("id starting with dot must be a series of dots");return c._parentData(e.length-1,!0)}return o&&null!=(u=n(o,e))?r(t(u),l):s&&e in c.Template&&c.Template[e]instanceof c.Template?c.Template[e]:null!=c._globalHelpers[e]?r(t(c._globalHelpers[e]),l):function(){var t=arguments.length>0,n=c.getData();if(s&&(!n||!n[e]))throw new Error("No such template: "+e);if(t&&(!n||!n[e]))throw new Error("No such function: "+e);if(!n)return null;var r=n[e];if("function"!=typeof r){if(t)throw new Error("Can't call non-function: "+r);return r}return r.apply(n,arguments)};return null}

**Comment by iliasch** [comment] 2015-09-15 21:44
The last block of that function returns a function, which perhaps confuses the minify process.

**Comment by tcastelli** [comment] 2016-04-12 02:31
+1, I was getting 1 or 2 of those messages on the ecmascript package in 1.2.1, but now after switching to 1.3.1 and using modules, I get a  lot of  unreachable code after return statement. This is the faulter line
````javascript
this.modelType=modelType||jsts.geom.PrecisionModel.FLOATING;if(this.modelType===jsts.geom.PrecisionModel.FIXED){this.scale=1.0;}};jsts.geom.PrecisionModel.FLOATING='FLOATING';jsts.geom.PrecisionModel.FIXED='FIXED';jsts.geom.PrecisionModel.FLOATING_SINGLE='FLOATING_SINGLE';jsts.geom.PrecisionModel.prototype.scale=null;jsts.geom.PrecisionModel.prototype.modelType=null;jsts.geom.PrecisionModel.prototype.isFloating=function(){return this.modelType===jsts.geom.PrecisionModel.FLOATING||this.modelType===jsts.geom.PrecisionModel.FLOATING_SINLGE;};jsts.geom.PrecisionModel.prototype.getScale=function(){return this.scale;};jsts.geom.PrecisionModel.prototype.getType=function(){return this.modelType;};jsts.geom.PrecisionModel.prototype.equals=function(other){return true;if(!(other instanceof jsts.geom.PrecisionModel)){return false;}

````

**Comment by hwillson** [comment] 2016-12-06 19:54
It's been a while since this issue was reported, and many new Meteor versions have since been released. I'll close this issue for now, but will happily re-open if people notice this problem is still occurring with newer Meteor versions. If you do, please link to a runnable reproduction showing the issue. Thanks for originally reporting this!

**Closed by hwillson** 2016-12-06 19:54 UTC
Labels: Project:Blaze
