### ISSUE TITLE
[1.3.3-rc.1] TypeError: Object #<Set> has no method 'forEach' on startup

### ISSUE THREAD

**Issue by jcheroske** [meteor/meteor#7180] opened 2016-06-07 06:29 UTC
- Fresh `meteor create test-project`
- Appears on versions 1.3.3-beta.1 through 1.3.3-rc.1
- Disappears when downgraded to 1.3.2.4
- OSX
- No edits to `.meteor/packages` or `package.json`

```
W20160607-00:13:58.583(-6)? (STDERR) TypeError: Object #<Set> has no method 'forEach'
W20160607-00:13:58.583(-6)? (STDERR)     at setToArray (/Volumes/Data/Users/jay/.meteor/packages/babel-compiler/.6.8.0-rc.1.1k6wcn6++os+web.browser+web.cordova/npm/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-types/node_modules/lodash/_setToArray.js:14:7)
W20160607-00:13:58.584(-6)? (STDERR)     at Object.<anonymous> (/Volumes/Data/Users/jay/.meteor/packages/babel-compiler/.6.8.0-rc.1.1k6wcn6++os+web.browser+web.cordova/npm/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-types/node_modules/lodash/_createSet.js:15:31)
W20160607-00:13:58.584(-6)? (STDERR)     at Module._compile (module.js:456:26)
W20160607-00:13:58.584(-6)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160607-00:13:58.584(-6)? (STDERR)     at Module.load (module.js:356:32)
W20160607-00:13:58.584(-6)? (STDERR)     at Module.Mp.load (/Volumes/Data/Users/jay/.meteor/packages/babel-compiler/.6.8.0-rc.1.1k6wcn6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/reify/node/runtime.js:16:23)
W20160607-00:13:58.584(-6)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160607-00:13:58.585(-6)? (STDERR)     at Module.require (module.js:364:17)
W20160607-00:13:58.585(-6)? (STDERR)     at require (module.js:380:17)
W20160607-00:13:58.585(-6)? (STDERR)     at Object.<anonymous> (/Volumes/Data/Users/jay/.meteor/packages/babel-compiler/.6.8.0-rc.1.1k6wcn6++os+web.browser+web.cordova/npm/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-types/node_modules/lodash/_baseUniq.js:5:17)
=> Exited with code: 8
```

**Comment by jcheroske** [comment] 2016-06-07 17:35
I edited the following file:

`~/.meteor/packages/babel-compiler/.6.8.0-rc.1.1k6wcn6++os+web.browser+web.cordova/npm/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-types/node_modules/lodash/_setToArray.js`

I put a guard around the call to `Set.forEach()`:

```
function setToArray(set) {
  var index = -1,
      result = Array(set.size);

  if (set.forEach) {    // Check to make sure forEach() exists
    set.forEach(function(value) {
      result[++index] = value;
    });
    return result;
  } else {
    return [];    // Return an empty array if it does not  
  }

}

module.exports = setToArray;
```

This gets my app up and running again, but there is a bug lurking still I think. I console logged the value of the `set` variable that caused the error, and it appears to just be an empty object.

**Comment by benjamn** [comment] 2016-06-07 20:52
Try this again after `meteor update --release 1.3.3-rc.4`?

**Comment by jcheroske** [comment] 2016-06-07 22:06
Nope, same exact result.

**Comment by abernix** [comment] 2016-08-04 12:27
Is this still an issue?  If so, can you clarify how to reproduce this?  You're having this problem on a _completely_ fresh project?

**Comment by hwillson** [comment] 2017-02-02 20:12
Since you haven't posted back on this in a while, we'll assume this is no longer an issue. Closing - thanks for posting this originally!

**Closed by hwillson** 2017-02-02 20:12 UTC
