### ISSUE TITLE
Meteor.user() undefined in Meteor.startup() callback

### ISSUE THREAD

**Issue by martintreurnicht** [meteor/meteor#6745] opened 2016-04-07 18:17 UTC
Version : 1.3.1
ui: react

After logging in, if you refresh the page, the `Meteor.user()` sometimes returns `undefined`, it's a very difficult issue to test because of how intermittent it is. My suspicion is that this is happening because there must be some background thread binding the currentUser and other data, which causes inconsistent behavior in the ui thread.

This becomes very apparent when using `react-router` with `onEnter` verification function checking if the user is logged in. See code sample:

``` javascript
//snippet from main.jsx
Meteor.startup(() => {
		render(<App />, document.getElementById('render-target'));
});
```

``` jsx
//snippet from App.jsx
export default class App extends Component {
	
	render() {
		return (
			<Router history={browserHistory}>
				<Route path="/" component={Home} onEnter={requireAuth}/>
				<Route path="/login" component={Login} onEnter={requireNotAuthed}/>
			</Router>
		);
	}
}

function requireAuth(nextState, replace) {
	if (!Meteor.user()) {
		replace({
			pathname: '/login',
			state: { nextPathname: nextState.location.pathname }
		})
	}
}

function requireNotAuthed(nextState, replace) {
	if (Meteor.user()) {
		replace({
			pathname: '/',
		})
	}
}
```

Right now i made the following change to allow time for the data to load and so far it's been working on localhost, but it's a really bad hack and it is yet to be tested on a remotely hosted system:
```javascript
Meteor.startup(() => {
	setTimeout(() => {
		render(<App />, document.getElementById('render-target'));
	}, 200)
});
```

The easiest way to recreate this would be to take the react todos example and add in `react-router`. You'll then have to make a separate login component and make login required for viewing your todos list

**Comment by lorensr** [comment] 2016-04-07 19:51
I've sometimes found `Meteor.userId()` to be defined but `Meteor.user()` to be `undefined` because the user data (published in universal subscription) has not reached the client yet. Sometimes I autorun until `Meteor.user()` is defined.

**Comment by Primigenus** [comment] 2016-04-07 20:55
@martintreurnicht This is intended behaviour, not a bug, and due to the situation @lorensr describes above. I recommend closing this issue and reading up about the [subscription lifecycle](http://guide.meteor.com/data-loading.html#lifecycle). `autorun` is definitely the simplest API for dealing with this.

**Comment by stubailo** [comment] 2016-04-08 18:26
Yes, the way to do this is to do an autorun and wait until `Meteor.user()` has the data.

**Closed by stubailo** 2016-04-08 18:26 UTC

**Comment by martintreurnicht** [comment] 2016-04-08 20:56
@stubailo Thanks! Using `Tracker.autorun` solved the issue i was having. Might be worth it to put something in the examples that has a documented way of solving this type of problem

**Comment by martintreurnicht** [comment] 2016-04-09 00:18
@stubailo Actually this doesn't work, it causes very weird behavior with the navigation. What ended up working for me is just using the `Meteor.userId()` like @lorensr suggested earlier. i don't need any user data, i just need to know wether the user needs to log in or not, and that seems to be more reliable. This seems like a really stupid issue to have, there should be a better out of the box solution for dealing with routing related to data

**Comment by lorensr** [comment] 2016-04-09 20:57
@martintreurnicht I agree it's a problem that could be avoided with more complete documentation – I've opened issue #6768
