### ISSUE TITLE
Not same jQuery event object for Meteor and jQuery

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2851] opened 2014-10-18 08:48 UTC
See [example here](https://github.com/mitar/meteor-issue2851).

If you run it and press "Test", you will see in the console something like this:

```
oneMore level, event true
oneMore level, originalEvent true
document level, event undefined
document level, originalEvent true
```

Instead of:

```
oneMore level, event true
oneMore level, originalEvent true
document level, event true
document level, originalEvent true
```

It seems that jQuery event used by jQuery is not exactly the same object as that used by Meteor. To make plugins and 3rd party codebases really interoperable, it would be great if that would be the case. Otherwise that is a big reason why not to use `.events()` at all to hook up event handlers and just use event handlers in `.rendered`.

**Comment by hwillson** [comment] 2016-10-28 12:10
This is definitely a jQuery feature/issue. Here's a complete non-Meteor reproduction (and a [jsbin link to demonstrate it](http://jsbin.com/dibapuwori/edit?html,js,console,output)):

**Source:**

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <script src="https://code.jquery.com/jquery-3.1.0.js"></script>
</head>
<body>
  <script>
    $(document).on('click button', function (event) {
      console.log('document', event.customValue);    
      console.log('document', event.originalEvent.customValue);    
    });

    $(function () {
      $('div').on('click button', function (event) {
        event.customValue = 123;    
        event.originalEvent.customValue = 123;
        console.log('div', event.customValue);    
        console.log('div', event.originalEvent.customValue);    
      });
    });
  </script>
  <div>
    <button type="button">Test</button>
  </div>  
</body>
</html>
```

**Console Output:**

```
"div" 123
"div" 123
"document" undefined
"document" 123
```

As mentioned by @yyx990803, jQuery event listeners are getting different event objects. Since this appears to be by jQuery design, I think we can close this issue.

**Comment by mitar** [comment] 2016-10-28 18:51
But originalEvent stays the same across all, yes?

**Comment by mitar** [comment] 2016-10-28 18:52
Thanks for investigating this.

**Closed** 2016-10-28 18:51 UTC
Labels: Project:Blaze

**Comment by hwillson** [comment] 2016-10-28 18:55
> But originalEvent stays the same across all, yes?

Yes it does - `event.originalEvent.customValue` is preserved.
