### ISSUE TITLE
example todos app on the meteor website doesn't work on ios devices

### ISSUE THREAD

**Issue by cuikaiyun** [meteor/meteor#4775] opened 2015-07-18 23:25 UTC
Hi,

I'm a beginner using meteor to develop mobile apps. To begin my journey, I started with the tutorials on the meteor website. After finishing the tutorials, I created the todos app using meteor create --example todos. This app works fine on the ios simulator. But when I tried to launch the app on iPhone, it got stuck at the loading page. I have tried this on two Macs and two iPhones (4s and 6plus), both show the same issue. 

This could hurt the credit of Meteor seriously and leave the new users' a bad first-impression. Could you help fix this asap? Thanks!

Kevin

**Comment by martijnwalraven** [comment] 2015-07-19 00:00
I'm aware there are issues with the current Cordova integration, but I haven't been able to reproduce your case. The Todos example runs as expected on my iPhone. That makes these problems hard to debug and fix. They are likely to be the result of the interaction of specific versions of the different parts: Meteor, Cordova, Xcode, iOS, etc. 

I'm working on improvements to the Cordova integration that I hope to get into the Meteor 1.2 release, and I expect this to make these problems both less common and easier to diagnose.

**Comment by stubailo** [comment] 2015-07-19 05:23
Duplicate of #4764

**Closed by stubailo** 2015-07-19 05:23 UTC
