### ISSUE TITLE
[1.10.1] Release APK. Freezes in the splashscreen when open in first time.

### ISSUE THREAD

**Issue by CristianoGil** [meteor/meteor#10860] opened 2020-01-14 15:05 UTC
Debug APK works perfectly but APK release simply freezes in the splash screen when open in first time after installation, that is, must open and close to open successfully.

### Cordova plugins
cordova-pdf-generator@2.0.8
cordova-support-google-services@~1.3.1
cordova-plugin-appavailability@0.4.2
cordova-plugin-battery-status@2.0.2
cordova-plugin-camera@4.1.0
cordova-play-services-version-adapter@1.0.2
 cordova-plugin-crop@file:///home/xxxxxxx/xxxxxx/xxxxx/cordova-plugin-crop-with-ratio-local #(Local package)
cordova-plugin-customurlscheme@4.3.0
cordova-plugin-device@2.0.3
cordova-plugin-dialogs@2.0.1
cordova-plugin-facebook4@6.2.0
cordova-plugin-file@6.0.1
cordova-plugin-file-transfer@1.7.1
cordova-plugin-ionic-keyboard@2.1.3
cordova-plugin-native-keyboard@2.0.3
cordova-plugin-native-spinner@1.1.3
cordova-plugin-network-information@2.0.2
cordova-plugin-vibration@3.1.1
cordova-plugin-x-socialsharing@5.6.4
cordova-rtsp-rtmp-stream@0.1.24
cordova-support-android-plugin@1.0.2
phonegap-plugin-barcodescanner@8.1.0
phonegap-plugin-push@2.3.0
cordova-plugin-screen-orientation@3.0.2
cordova-plugin-geolocation@4.0.2
cordova.plugins.diagnostic@5.0.1

### Meteor packages
255kb:meteor-status@1.5.0
accounts-base@1.6.0
accounts-facebook@1.3.2
accounts-google@1.3.3
accounts-oauth@1.2.0
accounts-password@1.6.0
ajduke:bootstrap-tagsinput@0.7.1
alanning:roles@1.2.19
aldeed:simple-schema@1.5.4
allow-deny@1.1.0
anima:login-ddp@0.0.1
anti:fake@0.4.1
audit-argument-checks@1.0.7
autoupdate@1.6.0
babel-compiler@7.5.3
babel-runtime@1.5.0
barbatus:stars-rating@1.1.1
base64@1.0.12
binary-heap@1.0.11
blaze@2.3.4
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.7.0
caching-compiler@1.2.2
caching-html-compiler@1.1.3
callback-hook@1.3.0
ccorcos:clientside-image-manipulation@1.0.4
cfs:http-methods@0.0.32
check@1.3.1
chriswessels:hammer@4.0.2
coffeescript@1.0.17
cristiano:calendar@0.0.1
cristiano:img-qrcode@0.1.1
cristiano:reactive-animation@0.0.1
ddp@1.4.0
ddp-client@2.3.3
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.3.1
deps@1.0.12
diff-sequence@1.1.1
dynamic-import@0.5.2
easy:search@2.2.1
easysearch:components@2.2.2
easysearch:core@2.2.2
ecmascript@0.14.3
ecmascript-runtime@0.7.0
ecmascript-runtime-client@0.10.0
ecmascript-runtime-server@0.9.0
ejson@1.1.1
email@1.2.3
es5-shim@4.8.0
facebook-oauth@1.7.0
fastclick@1.0.13
fetch@0.1.1
fezvrasta:bootstrap-material-design@0.5.9
fortawesome:fontawesome@4.7.0
fourseven:scss@4.12.0
frozeman:persistent-minimongo2@0.4.0
gadicc:blaze-react-component@1.4.2
geojson-utils@1.0.10
google-oauth@1.3.0
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.4.2
id-map@1.1.0
inter-process-messaging@0.1.1
iron:controller@1.0.12
iron:core@1.0.11
iron:dynamic-template@1.0.12
iron:layout@1.0.12
iron:location@1.0.11
iron:middleware-stack@1.1.0
iron:router@1.1.2
iron:url@1.1.0
jquery@1.11.11
launch-screen@1.2.0
less@2.8.0
littledata:synced-cron@1.5.1
livedata@1.0.18
localstorage@1.2.0
logging@1.1.20
mdg:meteor-apm-agent@3.2.5
mdg:reload-on-resume@1.0.4
mdg:seo@3.2.2
mdg:validated-method@1.2.0
mdg:validation-error@0.5.1
meteor@1.9.3
meteor-base@1.4.0
meteor-platform@1.2.6
meteorhacks:aggregate@1.3.0
meteorhacks:collection-utils@1.2.0
meteorhacks:ssr@2.2.0
meteorhacks:subs-manager@1.6.4
meteorspark:util@0.2.0
minifier-css@1.5.0
minifier-js@2.6.0
minimongo@1.5.0
mizzao:build-fetcher@0.3.2
mizzao:jquery-ui@1.11.4
mizzao:timesync@0.5.1
mizzao:user-status@0.6.8
mobile-experience@1.1.0
mobile-status-bar@1.1.0
modern-browsers@0.1.5
modules@0.15.0
modules-runtime@0.12.0
momentjs:moment@2.24.0
mongo@1.9.1
mongo-decimal@0.1.1
mongo-dev-server@1.1.0
mongo-id@1.0.7
mongo-livedata@1.0.12
nilsdannemann:pdfmake@1.0.38
npm-bcrypt@0.9.3
npm-mongo@3.7.0
oauth@1.3.0
oauth2@1.3.0
observe-sequence@1.0.16
ongoworks:pdf@1.1.1
ordered-dict@1.1.0
ostrio:cookies@2.6.0
ostrio:files@1.14.0
peerlibrary:assert@0.3.0
peerlibrary:base-component@0.16.0
peerlibrary:blaze-components@0.21.0
peerlibrary:computed-field@0.10.0
peerlibrary:data-lookup@0.1.0
peerlibrary:reactive-field@0.6.0
percolate:find-from-publication@0.2.1
practicalmeteor:chai@2.1.0_1
practicalmeteor:faker@3.0.1_1
promise@0.11.2
raix:eventemitter@0.1.3
raix:handlebar-helpers@0.2.5
random@1.2.0
rate-limit@1.0.9
react-meteor-data@0.2.16
reactive-dict@1.3.0
reactive-var@1.0.11
reload@1.3.0
retry@1.1.0
routepolicy@1.1.0
service-configuration@1.0.11
session@1.2.0
sha@1.0.9
shell-server@0.5.0
socket-stream-client@0.2.3
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.12
standard-minifier-css@1.6.0
standard-minifier-js@2.6.0
steeve:jquery-qrcode@0.2.2
tap:i18n@1.8.2
templating@1.3.2
templating-compiler@1.3.3
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:check-npm-versions@0.3.2
tmeasday:publish-counts@0.8.0
tracker@1.2.0
twbs:bootstrap@3.3.6
typescript@3.7.6
ui@1.0.13
underscore@1.0.10
url@1.2.0
velocityjs:velocityjs@1.2.1
void:reloader-control@1.0.0
vsivsi:file-collection@1.3.5
webapp@1.9.1
webapp-hashing@1.0.9

### LogCat

04-29 19:06:16.040  4459  4459 I chromium: [INFO:library_loader_hooks.cc(51)] Chromium logging enabled: level = 0, default verbosity = 0
04-29 19:07:20.862  5545  5545 I chromium: [INFO:library_loader_hooks.cc(51)] Chromium logging enabled: level = 0, default verbosity = 0
04-29 19:07:21.008  5545  5545 E chromium: [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/my.app/cache/WebView/Crashpad: No such file or directory (2)
04-29 19:07:21.375  5545  5614 E chromium: [ERROR:database.cc(1584)] Web sqlite error 14, errno -2: unable to open database file, sql: -- sqlite3_open()
04-29 19:07:21.376  5545  5614 E chromium: [ERROR:web_database_backend.cc(113)] Cannot initialize the web database: 1
04-29 19:07:22.285  5545  5627 E chromium: [ERROR:gl_surface_egl.cc(467)] eglChooseConfig failed with error EGL_BAD_ATTRIBUTE
04-29 19:07:22.358  5545  5627 E chromium: [ERROR:gl_surface_egl.cc(467)] eglChooseConfig failed with error EGL_BAD_ATTRIBUTE
04-29 19:07:22.429  5545  5545 W chromium: [WARNING:aw_form_database_service.cc(25)] initializing autocomplete database failed

**Comment by davidfumo** [comment] 2020-01-14 15:08
I'm also having the same issue, any ideas why is this happening?

**Comment by rj-david** [comment] 2020-01-15 00:59
Any chance of running both debug apk and production apk in the same device? If this happens, the 2nd app will not run because it will be using an already used localhost port by the first app.

To be sure, previous app must be removed

**Comment by CristianoGil** [comment] 2020-01-17 04:42
@rj-david  Any chance of running both debug apk and production apk in the same device?
No, nope! I cautiously removed everything that could compromise the tests

**Comment by filipenevola** [comment] 2020-01-17 19:07
What version of `cordova-plugin-meteor-webapp` are you using? 

Please check on `.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp/package.json`

I just want to be sure you are running the expected version for Meteor 1.9.

You should be running `cordova-plugin-meteor-webapp@1.7.0` and the Meteor package `webapp@1.8.2`. If you are not running `webapp@1.8.2` please run meteor update again as we have published it yesterday. You can check your webapp version on `.meteor/versions`.

**Comment by filipenevola** [comment] 2020-05-21 10:57
I can't reproduce this and we don't have an answer after my comment then I'm closing it.

**Closed by filipenevola** 2020-05-21 10:57 UTC
