### ISSUE TITLE
[meteor 1.3.rc.5] Update release 1.3 rc5 promise_server.js error

### ISSUE THREAD

**Issue by RWizard** [meteor/meteor#6555] opened 2016-03-22 06:57 UTC
***3 Upvotes*** Update from rc4 to rc5  error with /meteor-promise/promise_server.js:116
system: OS X 10.11.3
![2016-03-22 9 54 40](https://cloud.githubusercontent.com/assets/190453/13944200/4b5ef2fe-f014-11e5-9889-6170490a5fc6.JPG)

**Comment by danlg** [comment] 2016-03-22 07:54
same issue

**Comment by jorisroling** [comment] 2016-03-22 09:54
same here

**Comment by alamont** [comment] 2016-03-22 10:19
Same on Windows 10

**Comment by cismous** [comment] 2016-03-22 12:28
+1

**Comment by M4v3R** [comment] 2016-03-22 12:41
Same issue here while updating from 1.2.2-faster-rebuilds, on OSX 10.11.3.

**Comment by miri-am** [comment] 2016-03-22 13:04
+1

**Comment by DanielDornhardt** [comment] 2016-03-22 13:24
+1 - Here too

**Comment by M4v3R** [comment] 2016-03-22 13:26
Do you guys have `angular:angular` package added to your project? It seems that the issue is somewhere in angular dependencies, specifically while parsing `plugin.compileNGTemplate.os`.

**Comment by M4v3R** [comment] 2016-03-22 13:45
I've nailed down this issue to a parsing problem in `bundler.js`. I fixed it by adding additional parsing rule, as you can see in this pull request #6559.

**Comment by benjamn** [comment] 2016-03-22 16:54
Fixed in [`1.3-rc.6`](https://github.com/meteor/meteor/issues/6266#issuecomment-199903292), thanks to #6559 and @M4v3R!

**Closed by benjamn** 2016-03-22 16:54 UTC
