### ISSUE TITLE
Won't install on Snow Leopard 10.6.8

### ISSUE THREAD

**Issue by bellwood** [meteor/meteor#3495] opened 2015-01-17 22:52 UTC
According the install docs:

"The official installer supports Mac OS X 10.6 (Snow Leopard) and above, and Linux on x86 and x86_64 architectures"

My Macbook is running 10.6.8 on an Intel Core Duo and Darwin Kernel 10.8.0 i386

When I try to install it tells me Meteor only supports 64-bit Intel Processors

Is my Macbook too old to dev on Meteor?

My apologies if this is covered already, I did not see it under closed issues when I searched.

Thank you =)

**Comment by glasser** [comment] 2015-01-21 01:40
Duplicate of #3483

**Closed by glasser** 2015-01-21 01:40 UTC

**Comment by bellwood** [comment] 2015-01-21 01:47
Thank you =)
