### ISSUE TITLE
Watcher: UNKNOWN error on MacOS

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#4660] opened 2015-06-30 22:48 UTC
MacOS 10.10.4
using 1.1.0.2 release

Reproduction repo here:

https://github.com/hexsprite/meteor-watcher-bug.git

Our project uses the MathJax library which has a lot of files in the public/ folder which includes font data, etc.

Meteor crashes on startup and displays the following traceback:

```
=> App running at: http://localhost:3000/     

/Users/jbb/.meteor/packages/meteor-tool/.1.1.3.1mj3lap++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
                        throw(ex);
                              ^
Error: UNKNOWN, open '/Users/jbb/co/mathjax-repro/public/MathJax/fonts/HTML-CSS/TeX/png/Fraktur/Bold/120/0029.png'
    at Object.Future.wait (/Users/jbb/.meteor/packages/meteor-tool/.1.1.3.1mj3lap++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper [as readFile] (/Users/jbb/.meteor/packages/meteor-tool/.1.1.3.1mj3lap++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1350:24)
    at readFile (/Users/jbb/.meteor/packages/meteor-tool/.1.1.3.1mj3lap++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:226:18)
    at [object Object]._.extend._fireIfFileChanged (/Users/jbb/.meteor/packages/meteor-tool/.1.1.3.1mj3lap++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:339:20)
    at onWatchEvent (/Users/jbb/.meteor/packages/meteor-tool/.1.1.3.1mj3lap++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:478:16)
    at [object Object].<anonymous> (/Users/jbb/.meteor/packages/meteor-tool/.1.1.3.1mj3lap++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/func-utils.js:35:18)
    at /Users/jbb/.meteor/packages/meteor-tool/.1.1.3.1mj3lap++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:161:12
```

**Comment by hexsprite** [comment] 2015-06-30 22:49
@jonlachlan

**Comment by hexsprite** [comment] 2015-06-30 22:52
Seems to be related to: https://github.com/meteor/meteor/issues/4607

**Comment by glasser** [comment] 2015-07-07 22:34
We're able to reproduce this, but I'm not sure what's going on. Definitely seems to be a problem with watching too many files, but `open` is returning an errno that libuv doesn't know about (or some other syscall is corrupting `errno`)?

**Comment by slateb** [comment] 2015-07-30 02:51
Has anyone found a fix to this yet?

**Comment by awatson1978** [comment] 2015-08-06 22:03
I'm receiving this error on a client project as well.

**Comment by awatson1978** [comment] 2015-08-07 03:28
Hmmm.  Seems to have been a disk space issue for me.  

I use SSD drives on my main partition, which means I have to do everything with a rather slim 250GB of disk space.  Of that, 230GB had filled up; and the remaining 20GB...  even though the operating said it was free, it was getting used by applications and then put into 'inactive' state.  

A ``sudo purge`` cleared the inactive memory, and ``Error: UNKNOWN`` disappeared.  

The underlying bug might be something akin to this:  Meteor typically moves around 200MB or more of data when launching an app in a local environment.  When it's moving data around, it might not be aware of the difference between 'active' and 'inactive' memory.  The 'inactive' memory that is used by applications, but marked available, turns out to be inaccessible to node/meteor.  End result is too many files for the space marked as available.  Similarly, the 'inactive' memory could be a cause for returning an atypical ``errno` result.

**Comment by forrestrice** [comment] 2016-01-14 06:36
I'm experiencing this issue with a public subdirectory with 15,000 jpg images. I suppose I can throw these up on a CDN or host my own image server but that seems excessive for prototyping my app. Any ideas appreciated.

**Comment by Zodiase** [comment] 2016-04-08 19:32
Any updates?

**Comment by krizka** [comment] 2016-05-04 10:52
Updates please.

**Comment by abernix** [comment] 2016-05-04 14:07
@Zodiase @krizka Could you provide reproductions or explanations of your particular problems?  The original report on this issue was from Meteor 1.1.x and a lot has changed since then.  Could you be experiencing the same problem as issue #6952?

**Comment by Zodiase** [comment] 2016-05-04 16:54
@abernix No, not the same as #6952. Could you take a look at the referenced issue #4889 (which was marked as duplicate of this).

**Comment by krizka** [comment] 2016-05-04 17:07
@abernix Yes. I was installed a lot of NPM modules, and then installed @kadira/storybook to the same dir. 
```json
  "dependencies": {
    "faker": "^3.1.0",
    "meteor-node-stubs": "^0.2.3",
    "react": "^15.0.1",
    "react-addons-create-fragment": "^15.0.1",
    "react-addons-css-transition-group": "^15.0.1",
    "react-addons-linked-state-mixin": "^15.0.1",
    "react-addons-perf": "^15.0.1",
    "react-addons-pure-render-mixin": "^15.0.1",
    "react-addons-test-utils": "^15.0.1",
    "react-addons-transition-group": "^15.0.1",
    "react-addons-update": "^15.0.1",
    "react-dom": "^15.0.1",
    "react-komposer": "^1.8.0"
    "@kadira/storybook": "^1.1.0"
  },
  "devDependencies": {
    "autoprefixer": "^6.3.6",
    "postcss-assets": "^4.0.1",
    "postcss-svg": "^1.0.4"
  },
```

**Comment by abernix** [comment] 2016-05-04 17:27
@krizka Hmm, but not anything to `public/` directory, right?  You don't have the error message anymore?
@Zodiase As we noted in the other issue, it does seem to be related.  The common theme here is :boat: "boatload of files" = problem – you had over 40000. See also: #6952

**Comment by krizka** [comment] 2016-05-04 17:31
@abernix I this message had it today after another `npm install`, then I cleanup a bit and it is gone. Not a lot of `public/` stuff.

**Comment by queso** [comment] 2016-05-05 02:42
I don't think this issue is related to just public/. I am getting this error in an app that has a lot of node_module dependencies from Chimp and a fair amount of files in the package system too. The project is based on Rocket Chat if that helps at all.

**Comment by queso** [comment] 2016-05-05 02:44
So I killed off my `.meteor/local` folder and tried to run the app again without the Chimp npm dep installed. I got this stacktrace as a result:

````
W20160504-22:35:29.512(-4)? (STDERR)     at Object.fs.readFileSync (fs.js:290:15)
W20160504-22:35:29.513(-4)? (STDERR)     at Object.Module._extensions..json (module.js:480:44)
W20160504-22:35:29.513(-4)? (STDERR)     at Module.load (module.js:356:32)
W20160504-22:35:29.513(-4)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160504-22:35:29.513(-4)? (STDERR)     at Module.require (module.js:364:17)
W20160504-22:35:29.514(-4)? (STDERR)     at require (module.js:380:17)
W20160504-22:35:29.514(-4)? (STDERR)     at Object.<anonymous> (/Users/josh/.meteor/packages/webapp/.1.2.8.110qi9z++os+web.browser+web.cordova/npm/node_modules/send/node_modules/mime/mime.js:87:13)
W20160504-22:35:29.514(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20160504-22:35:29.514(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)

Error: UNKNOWN, open '/Users/josh/Code/Clients/secretapp/packages/rocketchat-statistics/server/functions/getAverage.coffee'
```

**Comment by abernix** [comment] 2016-05-05 09:21
Ok, perhaps it's also a problem with `node_modules` getting too large – not just `public`.  It's already documented that `public` can definitely cause problems, so wouldn't be too surprising if `node_modules` was also affected.

The next person that experiences this, try including the output of this command, run from your project root.  It will print the top 5 directories with the most files.  It's generally expected that your `.meteor` directory will have 50k+ but the others might be causing problems.
```
find . -type f | cut -d / -f 2 | sort | uniq -c | sort -rn | head -5
```

**Comment by abernix** [comment] 2016-05-05 09:22
I'll try to look into this soon.  Perhaps using `graceful-fs` in place of `fs` will fix it.

**Comment by mcoenca** [comment] 2016-05-10 18:40
Just updated to 1.3, and got the same kind of bug. Forced me to downgrade.

Here is my log
`/Users/mcoenca/.meteor/packages/meteor-tool/.1.3.2_4.1m0jvz7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: UNKNOWN, readdir '/Users/mcoenca/Documents/Bridges/Code/Bridges-webapp/WebApp/app/packages/meteor-materialize-sass/material-design-icons/navigation/svg'`

And sometimes it happens in another places nearby

`Error: UNKNOWN, readdir '/Users/mcoenca/Documents/Bridges/Code/Bridges-webapp/WebApp/app/packages/meteor-materialize-sass/material-design-icons/maps/ios/ic_layers_clear.imageset'`

`$  find . -type f | cut -d / -f 2 | sort | uniq -c | sort -rn | head -5
90192 packages
15978 .meteor
 146 public
  90 client
  46 zbridges-odiki`

(packages are forked inside packages, that's why I've got so many files in that)

**Comment by abernix** [comment] 2016-05-26 06:20
I did get a chance to look at this briefly last week, but didn't have any super easy fix.  Check my  https://github.com/meteor/meteor/issues/6952#issuecomment-220289961 for a possible work-around for those willing to give it a shot.

I'm pretty close to merging these issues together as I feel they are likely the same problem: watching too many files in your project directory in order to provide the auto-reload on file-changes that Meteor provides.  The error messages vary so greatly because the "last straw" (so to say) in each case depends on whether the "Nth" operation is a file or a directory.

**Comment by hwillson** [comment] 2017-08-22 17:25
I've confirmed this is no longer an issue using the originally linked to reproduction and Meteor 1.5.1. Closing - thanks!

**Closed by hwillson** 2017-08-22 17:25 UTC
Labels: Project:Tool
