### ISSUE TITLE
[1.3-beta.12] Error building with raix:push - Package configured via .json config file

### ISSUE THREAD

**Issue by DanielDornhardt** [meteor/meteor#6411] opened 2016-03-04 11:18 UTC
Hello,

I receive this of error since updating from 1.3 Beta 11 to 1.3 Beta 12:

    Error: sourcePath not a file: push.config.web.browser.js
        at ImportScanner._ensureSourcePath (/tools/isobuild/import-scanner.js:208:13)
        at /tools/isobuild/import-scanner.js:101:28
        at Array.forEach (native)
        at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:100:11)
        at /tools/isobuild/compiler-plugin.js:709:15
        at Array.forEach (native)
        at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:689:19)
        at ClientTarget._emitResources (/tools/isobuild/bundler.js:749:8)
        at /tools/isobuild/bundler.js:516:12
        at /tools/utils/buildmessage.js:359:18
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:352:34
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:350:23
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at Object.enterJob (/tools/utils/buildmessage.js:324:26)
        at ClientTarget.make (/tools/isobuild/bundler.js:507:18)
        at /tools/isobuild/bundler.js:2232:14
        at /tools/isobuild/bundler.js:2322:20
        at Array.forEach (native)
        at Function._.each._.forEach (/Users/spaceman/.meteor/packages/meteor-tool/.1.1.13-beta.12.1p7kgab++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
        at /tools/isobuild/bundler.js:2321:7
        at /tools/utils/buildmessage.js:271:13
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:264:29
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:262:18
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:253:23
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at Object.capture (/tools/utils/buildmessage.js:252:19)
        at Object.exports.bundle (/tools/isobuild/bundler.js:2213:31)
        at /tools/runners/run-app.js:586:36
        at Function.run (/tools/tool-env/profile.js:489:12)
        at bundleApp (/tools/runners/run-app.js:576:34)
        at AppRunner._runOnce (/tools/runners/run-app.js:629:35)
        at AppRunner._fiber (/tools/runners/run-app.js:881:28)
        at /tools/runners/run-app.js:406:12

After a lot of humming and hawing, it seems to boil down to this:

raix:push is structured to be configured using a file `config.push.json` in the meteor projects' root directory.

Then there seems to be some kind of build plugin which is supposed to read the file and actually add some additional javascript. The whole thing is registered here: https://github.com/raix/push/blob/f3a5a653dc2d1d7cd1af0b4d6478d23bcbd0644f/plugin/push.configuration.js#L185

...AAAND that's how far I can isolate the error. Something (a lot I feel?) changed in the build process from 1.3 Beta 11 to 1.3 Beta 12 and this is one issue which probably needs to be patched somewhere.

Reproduction Repo: https://github.com/DanielDornhardt/meteor13Beta12errorBuildingWithRaixPushPackage

- just remove or rename the file config.push.json to see the build error disappear.

Note this ticket with a similar error message: https://github.com/meteor/meteor/issues/6383 - maybe it's connected somehow?

I cross-posted this to the other ticket and also to the raix:push issue-tracker here: https://github.com/raix/push/issues/185 .

**Comment by skirunman** [comment] 2016-03-04 17:00
We have the same issue. Would be awesome if Meteor could resolve this ASAP.

**Comment by inspiraluna** [comment] 2016-03-04 21:58
I have raix:push too but removed it and it did not help... tho my error looks slightly different:

``Error: sourcePath not a file: bootstrap/js/transition.js
  at ImportScanner._ensureSourcePath (/Users/nico/.meteor/packages/meteor-tool/.1.1.13-beta.12.1nth5ac++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/import-scanner.js:229:13)
  at /Users/nico/.meteor/packages/meteor-tool/.1.1.13-beta.12.1nth5ac++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/import-scanner.js:121:27``

**Comment by zol** [comment] 2016-03-07 21:57
@benjamn did we introduce a regression in beta 12?

**Comment by zol** [comment] 2016-03-07 22:49
This looks like a dupe of #6383

**Comment by DanielDornhardt** [comment] 2016-03-08 08:24
Hi @zol and @benjamn , I would just like to point out the fine reproduction case I created in this ticket so you can easily debug this issue :) .

**Comment by benjamn** [comment] 2016-03-08 18:29
Yeah, this is a better reproduction :)

[This line](https://github.com/raix/push/blob/f3a5a653dc2d1d7cd1af0b4d6478d23bcbd0644f/plugin/push.configuration.js#L203) appears to be the culprit. The `ImportScanner` assumes that `file.sourcePath` is a real (relative) path on the file system, and this build plugin appears to be setting it to a filename that probably does not exist. For Meteor 1.2+ compiler plugins, that property gets set [unconditionally](https://github.com/meteor/meteor/blob/515ff244699e5805d573ac9f4f7d7ec92d3d08b9/tools/isobuild/compiler-plugin.js#L463) to the original path, but `Plugin.registerSourceHandler`-style build plugins take their `.sourcePath` from the `options.sourcePath` value passed to [`compileStep.addJavaScript`](https://github.com/meteor/meteor/blob/515ff244699e5805d573ac9f4f7d7ec92d3d08b9/tools/isobuild/compiler-deprecated-compile-step.js#L379).

I think this can be fixed without any changes to third-party build plugin code.

**Comment by DanielDornhardt** [comment] 2016-03-09 08:16
Thank you, very nice! :D

**Comment by benjamn** [comment] 2016-03-09 18:58
This is fixed in `beta.16`. Thanks again for the reproduction!

**Closed by benjamn** 2016-03-09 18:58 UTC

**Comment by raix** [comment] 2016-03-09 18:59
Thanks guys :+1:

**Comment by zol** [comment] 2016-03-09 21:34
Thanks @DanielDornhardt - I may have been too aggressive when closing and marking this ticket as a dupe.
