### ISSUE TITLE
LocalCollection._isModificationMod is not a function

### ISSUE THREAD

**Issue by marcoschwartz** [meteor/meteor#8930] opened 2017-07-20 17:40 UTC
Hello,

I am having this error since I updated my Meteor app a few minutes ago:

TypeError: LocalCollection._isModificationMod is not a function
W20170720-19:37:30.923(2)? (STDERR)     at [object Object].MongoConnection._update (packages/mongo/mongo_driver.js:514:36)
W20170720-19:37:30.923(2)? (STDERR)     at [object Object].<anonymous> (packages/meteor.js:212:23)
W20170720-19:37:30.923(2)? (STDERR)     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:743:49)
W20170720-19:37:30.924(2)? (STDERR)     at [object Object].update (packages/mongo/collection.js:591:29)

I think it comes from an update of npm-mongo, before that there were no issues. Anyone else has the same issue?

**Comment by hwillson** [comment] 2017-07-20 18:23
Thanks for reporting this @marcoschwartz. This is a known issue (see https://github.com/meteor/meteor/commit/cbeba459ab123854bc898c3348aae9dd3e91f6b3). We're working on a fix, but for now pinning `mongo` to 1.1.19 will fix this issue.

**Comment by benjamn** [comment] 2017-07-20 20:07
This should be fixed if you run `meteor update mongo`, thanks to @hwillson's fix in #8931. Please close the issue if updating `mongo` works for you!

**Comment by steph643** [comment] 2017-07-20 21:58
`meteor update mongo` didn't work for me, but `meteor add mongo@=1.1.19` did.

**Comment by tenshis** [comment] 2017-07-20 22:02
Can confirm steph643's solution. `meteor update mongo` didn't work

**Comment by hwillson** [comment] 2017-07-21 00:57
Hmm - looks like the most recent `mongo` version still has the same problem. We have a working patch ready to go, but for some reason it wasn't published. We'll coax the publishing process into cooperating, and get the fixed version out shortly. In the meantime, pinning to 1.1.19 will definitely work. Thanks for your patience!

**Comment by rpesciotta** [comment] 2017-07-21 07:59
Have the same problem here, and `meteor add mongo@=1.1.19` indeed solves for me.
Awaiting the final fix.

**Comment by nacimgoura** [comment] 2017-07-21 08:18
I updated mongo in version 1.21 and I have the same problem "LocalCollection._isModificationMod is not a function"

**Comment by tab00** [comment] 2017-07-21 10:11
I now get this error after making the following updates:

```
mongo                   upgraded from 1.1.19 to 1.1.21
npm-mongo               upgraded from 2.2.24 to 2.2.30

```

**Comment by abernix** [comment] 2017-07-21 10:47
This was my mistake in publishing `npm-mongo@2.2.30` and `mongo@1.1.20`.  Some changes were included from `devel` in `mongo@1.1.20` which were not intended to be released yet (and are currently staged on `release-1.5.2`).  This should be really be fixed if you update to the latest `mongo@1.1.22`:

    meteor update mongo

or

    meteor add mongo@1.1.22

Sorry for the troubles!  And thanks for reporting the problem. (And thanks to @hwillson for help in fixing!)

**Closed by abernix** 2017-07-21 10:47 UTC
Labels: bug, confirmed, Impact:most, Severity:production

**Comment by hwillson** [comment] 2017-07-21 10:50
Thanks @abernix! This change means Meteor is now using the latest version of the Node mongo driver (which incorporates the stability and performance improvements made over the past 6 versions), so a big 👍!

**Comment by runarberg** [comment] 2017-07-21 10:52
@abernix I can confirm. running `meteor update mongo` fixed this for us.
