### ISSUE TITLE
Meteor.defer not covered in docs

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#4442] opened 2015-05-23 17:32 UTC
It would be great to see this documented. It's a powerful feature and not mentioned anywhere.

**Comment by rgoomar** [comment] 2015-05-23 17:46
Oh wow, never noticed that. It also isn't documented in comments either (JSDoc style).
https://github.com/meteor/meteor/blob/master/packages/meteor/timers.js#L67

**Comment by ekatek** [comment] 2015-05-26 21:29
Agreed. Thanks for catching this!

**Comment by mitjajez** [comment] 2016-03-18 11:46
This is duplicate of #2176.

**Comment by stubailo** [comment] 2016-04-07 18:31
Just added it! It will be deployed next time the docs are.

**Closed by stubailo** 2016-04-07 18:31 UTC
Labels: backlog, Project:Docs, pull-requests-encouraged

**Comment by ffxsam** [comment] 2016-04-07 18:34
This issue is so old, I forgot what `Meteor.defer` does! 😆  I guess I'll wait and see when the docs are updated.
