### ISSUE TITLE
2.0 - Beta.4 Type Error probably in the area of React-Int package

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#11231] opened 2020-10-31 23:18 UTC
When moving from Beta.3 to Beta.4 I get a Type Error probably related to something in React-Intl NPM package. The error prevents the web app from starting.
Moving back to Beta.3 fixes the issue.

<img width="1556" alt="Screen Shot 2020-11-01 at 03 07 58" src="https://user-images.githubusercontent.com/26188915/97791879-d2f05980-1bf0-11eb-8090-c94ebbbcf5f9.png">
<img width="937" alt="Screen Shot 2020-11-01 at 03 16 45" src="https://user-images.githubusercontent.com/26188915/97791881-d97ed100-1bf0-11eb-9308-cda6af9b7737.png">

**Comment by stolinski** [comment] 2020-11-10 17:25
I'm having a very similar issue with `import { mergeTypeDefs } from '@graphql-tools/merge'`
This is also throwing a type error that prevents the app from starting.

```
W20201110-10:24:12.489(-7)? (STDERR) /Users/scotttolinski/.meteor/packages/meteor-tool/.2.0.0-beta.4.2arhyi.b1xho++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20201110-10:24:12.490(-7)? (STDERR) 						throw(ex);
W20201110-10:24:12.490(-7)? (STDERR) 						^
W20201110-10:24:12.490(-7)? (STDERR)
W20201110-10:24:12.491(-7)? (STDERR) TypeError: Cannot read property 'definitions' of undefined
W20201110-10:24:12.491(-7)? (STDERR)     at /Users/scotttolinski/Sites/levelup/node_modules/@graphql-tools/merge/index.cjs.js:770:25
W20201110-10:24:12.491(-7)? (STDERR)     at Array.map (<anonymous>)
W20201110-10:24:12.491(-7)? (STDERR)     at mergeGraphQLTypes (/Users/scotttolinski/Sites/levelup/node_modules/@graphql-tools/merge/index.cjs.js:770:10)
W20201110-10:24:12.491(-7)? (STDERR)     at mergeTypeDefs (/Users/scotttolinski/Sites/levelup/node_modules/@graphql-tools/merge/index.cjs.js:737:22)
W20201110-10:24:12.491(-7)? (STDERR)     at module (api/config/apollo/graphQLSchemaDefinitions.ts:176:22)
W20201110-10:24:12.491(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201110-10:24:12.492(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201110-10:24:12.492(-7)? (STDERR)     at Module.moduleLink [as link] (/Users/scotttolinski/.meteor/packages/modules/.0.16.0-beta200.4.t2pndb.02us++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201110-10:24:12.492(-7)? (STDERR)     at module (api/config/createApolloServer.ts:55:8)
W20201110-10:24:12.492(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201110-10:24:12.492(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201110-10:24:12.492(-7)? (STDERR)     at Module.moduleLink [as link] (/Users/scotttolinski/.meteor/packages/modules/.0.16.0-beta200.4.t2pndb.02us++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201110-10:24:12.492(-7)? (STDERR)     at module (api/config/index.ts:4:8)
W20201110-10:24:12.492(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201110-10:24:12.492(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201110-10:24:12.492(-7)? (STDERR)     at Module.moduleLink [as link] (/Users/scotttolinski/.meteor/packages/modules/.0.16.0-beta200.4.t2pndb.02us++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201110-10:24:12.493(-7)? (STDERR)     at module (server/index.ts:3:8)
W20201110-10:24:12.493(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201110-10:24:12.493(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201110-10:24:12.493(-7)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20201110-10:24:12.493(-7)? (STDERR)     at /Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/app/app.js:59129:15
W20201110-10:24:12.493(-7)? (STDERR)     at /Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/boot.js:401:38
W20201110-10:24:12.493(-7)? (STDERR)     at Array.forEach (<anonymous>)
W20201110-10:24:12.493(-7)? (STDERR)     at /Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/boot.js:226:21
W20201110-10:24:12.493(-7)? (STDERR)     at /Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/boot.js:464:7
W20201110-10:24:12.493(-7)? (STDERR)     at Function.run (/Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/profile.js:280:14)
W20201110-10:24:12.494(-7)? (STDERR)     at /Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/boot.js:463:13
```

**Comment by renanccastro** [comment] 2020-11-10 19:37
I'm looking at this right now. I will try to put a reproduction with those libraries.

**Comment by stolinski** [comment] 2020-11-12 17:57
I posted this in slack, but feels like a good idea to have a reproduction repo here too:
https://github.com/stolinski/meteor-beta4-error-reproduction

**Comment by renanccastro** [comment] 2020-11-12 22:14
Still trying to understand if OP's issue is the same as yours @stolinski, but the issue is now clear to me. The new bundler is removing the .graphql file because it doesn't find any direct dependency on it, just on .graphl.js files, which are emitted by swydo:graphql. I'm working on a fix.

**Comment by Grubba27** [comment] 2023-03-22 12:29
As this issue has had any interaction for a long time, I will close it. If this start occurring again, I will happily reopen this issue

**Closed by Grubba27** 2023-03-22 12:29 UTC
Labels: confirmed, Project:Tree shaking
