### ISSUE TITLE
Warn before upgrading to new version if hot code push will be blocked

### ISSUE THREAD

**Issue by ianpogi5** [meteor/meteor#8012] opened 2016-11-04 01:13 UTC
It would be great if we could be warned if a certain version upgrade would block hot code push.

**Comment by abernix** [comment] 2016-11-04 08:02
Thanks for filing a feature request to improve an aspect of Meteor that you think needs work.

Can you be more clear about exactly what you're looking for and when?  It's not clear what the problem is that you're running into that could be improved.  For example, are you referring to production, development, etc?   Is this something you've run into recently?  Do you experience it frequently?

**Comment by ianpogi5** [comment] 2016-11-04 09:36
@abernix thanks for the response. Upgrading to 1.4.2 from 1.4.1.2 have changes in Cordova libs and plugins which has stopped hot code push.

I had an urgent fix that needed to be deployed to my app users. After getting annoyed by the update message every time I start my app and since it was just a patch (semver), I decided to update and deploy along with my urgent fix. To my surprise the app was not updating. Then I checked the meteor changelog and saw that there was changes in cordova. :( 

Yeah it was partly my fault because I didn't look at the changelog before upgrading but then again it was just a patch update which should not break anything.

**Comment by abernix** [comment] 2016-11-04 14:59
Thank you very much for the clarification.  Just to be clear, Meteor does **not** use sem-ver versioning.  (Well, it kind of does, but you need to forget about the first digit completely, so 1.4.1.3 = 4.1.3 and 1.4.2 = 4.2.0).

I can understand your confusion though.  The changelog is definitely the recommended place to read before doing an update for now, but it sounds like your problem would also be solved by the solution to #6804 though, correct?

**Comment by ianpogi5** [comment] 2016-11-04 15:15
Yes that could work.

**Comment by abernix** [comment] 2016-11-04 16:23
I agree.  I'm going to close this in favor of that and make a change to the subject over there.  Thanks for filing this!

**Closed by abernix** 2016-11-04 16:23 UTC
Labels: feature
