### ISSUE TITLE
Collection.findOne(id) returns wrong results when id is undefined

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#8220] opened 2017-01-05 19:48 UTC
`Collection.findOne(id)` still returns a doc when _id is undefined. `Collection.findOne({_id: id})` does work as intended.

![screen shot 2017-01-05 at 11 44 55 am](https://cloud.githubusercontent.com/assets/8436742/21695044/dc2059de-d33c-11e6-90d7-bbd207bb4a9b.png)

**Comment by hwillson** [comment] 2017-01-05 20:10
This should work properly - are you sure `a` really contains `undefined` in your example? Try `Tasks.findOne(undefined)` to make sure. I know your screenshot shows `undefined` after your `var a` declaration, but that doesn't necessarily mean `a` is undefined. You could have had a previous value set for `a`, then when you called `var a` again it doesn't do anything. For example:

![screenshot 2017-01-05 15 07 44](https://cloud.githubusercontent.com/assets/137740/21695662/c0474404-d358-11e6-8fa6-8d3384e16e41.png)

For reference passing an `undefined` selector into `findOne` is blocked in https://github.com/meteor/meteor/blob/c29a1e9b0be6f7cb0472eaa96213b99b5530bff0/packages/minimongo/selector.js#L89-L92:

```
    if (!selector || (('_id' in selector) && !selector._id)) {
      self._isSimple = false;
      return nothingMatcher;
    }
```

**Comment by WayneUong** [comment] 2017-01-05 20:15
@hwillson These are all the cases I can think of. Still not working properly, especially the last case.

![screen shot 2017-01-05 at 12 14 44 pm](https://cloud.githubusercontent.com/assets/8436742/21695939/ad1301e2-d340-11e6-84f6-8a3d3700f85f.png)

**Comment by WayneUong** [comment] 2017-01-05 20:27
@hwillson happens on server-side too.

![screen shot 2017-01-05 at 12 26 57 pm](https://cloud.githubusercontent.com/assets/8436742/21696308/5770928e-d342-11e6-9d09-d268270e327e.png)

**Comment by hwillson** [comment] 2017-01-05 20:35
Thanks @WayneUong - here's a working example using meteor.com:

![screenshot 2017-01-05 15 32 37](https://cloud.githubusercontent.com/assets/137740/21696480/47099bf6-d35c-11e6-8ae7-509e643ce4c8.png)

Any chance you could create a small runnable reproduction showing your issue? That would definitely help with troubleshooting.

**Comment by WayneUong** [comment] 2017-01-05 20:38
@hwillson I think it might have to do with the [softRemove](https://github.com/zimme/meteor-collection-softremovable) package that we used. Any chance you can improve this from meteor side?

![screen shot 2017-01-05 at 12 37 00 pm](https://cloud.githubusercontent.com/assets/8436742/21696652/d0825bde-d343-11e6-91fa-ddcffc089143.png)

**Comment by hwillson** [comment] 2017-01-05 20:46
Interesting - I haven't used [zimme:collection-softremovable](https://atmospherejs.com/zimme/collection-softremovable), but if it's causing the minimongo dangerous selector protection check to fail, then I think it would be better if this issue was fixed by the `collection-softremovable` package itself. Maybe try opening an issue with that package first. Thanks!

**Comment by hwillson** [comment] 2017-01-05 20:52
Thanks @WayneUong - since this is now being tracked via zimme/meteor-collection-softremovable#26, I'll close it here.

**Closed by hwillson** 2017-01-05 20:52 UTC

**Comment by programthis** [comment] 2017-11-03 15:09
I am now getting this exact issue since updating to Meteor 1.6. Was there ever a resolution to this?

**Comment by nevil-magnates** [comment] 2019-09-16 07:33
I have created a project in MeteorJS, now I am trying to fetch record as per my requirement, I am using following query

`db.getCollection('parcels').findOne({"barcode" : "484847u4u"})`

It's working fine in MongoDB and return data, but If same query I am using in MeteorJS and it's return Nil object.

I read lots of issue regarding same thing like First, Second, etc...but can't get any solution.

```
API Box: Parcels.js
    ------
    import { Mongo }        from 'meteor/mongo';
    export const Parcels = new Mongo.Collection('parcels');
    Meteor.methods({
            'parcels.checkBarcode': (parcelId) => {
      // find
          const parcel = Parcels.findOne(parcelId);
         // const parcels =  Parcels.findOne({ barcode : barcode }, {});
       return parcel;
     },
  });

  ParcelList.js
  -----
  import { Parcels } from '/imports/api/parcels.js';
  Parcels.findOne({barcode: "48484747u4u"})
```

![image (3) (3)](https://user-images.githubusercontent.com/45817089/64940634-14edfd00-d882-11e9-92c4-3402fffeb113.png)
![image (5) (5)](https://user-images.githubusercontent.com/45817089/64940639-17505700-d882-11e9-9c76-ff79dfae3118.png)
![image (4) (4)](https://user-images.githubusercontent.com/45817089/64940643-1a4b4780-d882-11e9-8076-abe832930e55.png)
