### ISSUE TITLE
[METEOR@1.4-rc.0] meteor build command fails while minifying

### ISSUE THREAD

**Issue by aniketdd** [meteor/meteor#7441] opened 2016-07-20 06:54 UTC
on Running 'meteor build --directory ../build' receiving following error on mint 17.3 64bit with node@4.4.7.

```
Errors prevented bundling:                    
While minifying app code:                     

/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:196:18:
Unexpected token name «i», expected punc «;»
at new JS_Parse_Error
(/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:196:18)
at js_error
(/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:204:11)
at croak
(/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:675:9)
at token_error
(/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:683:9)
at expect_token
(/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:696:9)
at expect
(/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:699:36)
at regular_for
(/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:929:9)
at for_
(/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:925:16)
at
/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:807:24
at
/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:722:24
```

**Comment by abernix** [comment] 2016-07-20 07:05
You haven't provided enough information to debug this issue. Have you tried a newer version of the 1.4 beta? `1.4-beta.14` is out.  As it looks like a weird syntax error in one of your files or packages, could you make a copy of your app and start removing packages and files until you still experience this problem but can't remove any more?  Unless the upgrade helps, this is likely the only process which will be helpful in resolving this.

**Comment by benjamn** [comment] 2016-07-20 15:08
`1.4-rc.0` is the latest version, but I agree more information would be helpful. UglifyJS errors are pretty unhelpful, even compared to other JS parsers, but I've had luck in the past modifying the `parse.js` file (in your case, `/home/user/.meteor/packages/standard-minifier-js/.1.1.8-rc.0.1e2t4p8++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js`) so that it prints out the source file name and the relevant part of the source code.

**Comment by abernix** [comment] 2016-07-20 15:38
Sorry, apparently I didn't make the transition from `beta` to `rc` today, apparently. ☕☕☕

**Comment by aniketdd** [comment] 2016-07-21 13:25
It did not work on 1.4-rc.1 too.
After removing standard-minifier-css & standard-minifier-js i was able to remove error during build command.

My Packages are:
meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.10-rc.0                   # The database Meteor supports right now
session@1.1.6                 # Client-side reactive dictionary for your app
tracker@1.1.0-rc.0                 # Meteor's client-side reactive programming library

es5-shim@4.6.13-rc.0                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.5.7-rc.0              # Enable ECMAScript2015+ syntax in app code

accounts-password@1.2.12-rc.0
kadira:flow-router
modules@0.7.5-rc.0
shcherbin:flex-grid
alanning:roles
planettraining:material-design-icons-font
standard-minifier-css@1.1.8-rc.0
standard-minifier-js@1.1.8-rc.0
http@1.2.8-rc.0
msavin:mongol
matb33:collection-hooks
reywood:publish-composite
nimble:restivus
practicalmeteor:chai
dburles:factory
xolvio:cleaner
practicalmeteor:mocha
meteorhacks:aggregate
static-html@1.1.11-rc.0

And Npm dependencies are:
"devDependencies": {
    "babel-core": "6.x.x",
    "babel-eslint": "^6.x.x",
    "babel-plugin-react-require": "2.x.x",
    "babel-polyfill": "6.x.x",
    "babel-preset-es2015": "6.x.x",
    "babel-preset-react": "6.x.x",
    "babel-preset-stage-2": "6.x.x",
    "babel-root-slash-import": "1.x.x",
    "chai": "3.x.x",
    "enzyme": "2.x.x",
    "eslint": "^3.0.0",
    "eslint-config-airbnb": "^9.0.0",
    "eslint-plugin-meteor": "^3.5.2",
    "eslint-plugin-react": "^5.x.x",
    "eslint-plugin-jsx-a11y": "*",
    "eslint-plugin-import": "*",
    "mocha": "2.x.x",
    "react-addons-test-utils": "15.0.1",
    "sinon": "1.17.x"
  },
  "dependencies": {
    "deep-diff": "^0.3.4",
    "getmac": "^1.2.1",
    "joi": "^9.0.1",
    "json-markup": "^0.1.7",
    "lodash": "^4.13.1",
    "material-ui": "0.15.2",
    "meteor-node-stubs": "^0.2.3",
    "moment": "^2.14.1",
    "properties-reader": "0.0.15",
    "react": "^15.2.1",
    "react-addons-shallow-compare": "^15.2.1",
    "react-dom": "^15.2.1",
    "react-komposer": "^1.13.1",
    "react-mounter": "^1.2.0",
    "react-simple-di": "^1.2.0",
    "react-tap-event-plugin": "^1.0.0",
    "react-virtualized": "^7.12.2",
    "redux": "^3.5.2",
    "stompjs": "^2.3.3",
    "validator": "^5.4.0",
    "winston": "^2.2.0",
    "xlsx": "^0.8.0",
    "xlsx-style": "0.8.13"
  }

**Comment by MHerszak** [comment] 2016-08-06 17:24
@benjamn I was just talking to Meteor support about the same issue and I can't resolve the problem I have. I can't even point to the source of the problem. Is there a good guide you can point to? Could you elaborate on how you manipulated parse.js so you would get some information from it?

**Comment by jorisbontje** [comment] 2016-08-12 15:42
I was able to solve a similar issue with `standard-minifier-js` by adding `api.use('ecmascript', 'client');` into the `Package.onUse` of my `package.js` for my local packages.

**Comment by Mr-Sab** [comment] 2016-09-03 09:54
@abernix 
Hi, I had have the same problem, I removed some of packages like what you suggest,
The problem had solved only after removing npm module "meteor-node-stubs"!
I think the problem must came from one of its dependencies! I hope this will be helpful.

**Comment by MHerszak** [comment] 2016-09-03 19:46
I had a similar problem and it had nothing to do with ecmascript. It was related to a deleted package which was referenced in the .version file but not existent anymore. Not sure if that helps but I resolved my minifier issue I had.

**Comment by smeijer** [comment] 2016-09-30 17:55
Seems like there is a bug in the minifier somewhere.

Having the same issue:

```
=> Started proxy.
=> Errors prevented startup:

   While minifying app stylesheet:
   packages/minifier-css/minifier.js:185:1: Cannot read property 'replace'
   of null
   at toOSPath (packages/minifier-css/minifier.js:185:1)
   at pathRelative (packages/minifier-css/minifier.js:206:1)
   at packages/minifier-css/minifier.js:165:1
   at Array.forEach (native)
   at Function._.each._.forEach
   (packages/underscore/underscore.js:105:1)
   at packages/minifier-css/minifier.js:122:1
   at Array.forEach (native)
   at Function._.each._.forEach
   (packages/underscore/underscore.js:105:1)
   at rewriteRules (packages/minifier-css/minifier.js:99:1)
   at Object.CssTools.rewriteCssUrls
   (packages/minifier-css/minifier.js:85:1)
   at packages/minifier-css/minifier.js:55:1
   at Array.forEach (native)
   at Function._.each._.forEach
   (packages/underscore/underscore.js:105:1)
   at Object.CssTools.mergeCssAsts
   (packages/minifier-css/minifier.js:32:1)
   at packages/minifyStdCSS/plugin/minify-css.js:100:1
   at CssToolsMinifier.processFilesForBundle
   (packages/minifyStdCSS/plugin/minify-css.js:20:1)


=> Your application has errors. Waiting for file change.
```

**Comment by smeijer** [comment] 2016-09-30 18:51
Found the problem; it's caused by a `leafletjs` stylesheet. The line that's causing the troubles is:

```css
.foo {
  behavior: url(#default#VML); /* throwing Cannot read property 'replace' of null */
}
```

**Comment by abernix** [comment] 2016-10-28 08:49
Thanks for reporting this issue originally.  I'm going to close this as a reproduction never came in which would allow testing if this was fixed, and also due to the lack of activity.  The `url(#default#VML)` usage is known to be problematic – or rather, the minifier is behaving according to spec.  See https://github.com/meteor/meteor/issues/7523#issuecomment-236575636 and the rest of the issue where this is discussed specifically and other suggestions for debugging problems like this are discussed.

Happy to reopen if this is still a known problem, but a reproduction repro is necessary.

**Closed by abernix** 2016-10-28 08:49 UTC
Labels: bug, can't-reproduce

**Comment by QHose** [comment] 2017-09-20 17:40
yeah, what helped me
* check which packages you recently added
* remove them
* use the abernix minifier
