### ISSUE TITLE
[Meteor 1.3 beta.11]  Error: Can't find npm module 'babel-runtime/helpers/toArray'.

### ISSUE THREAD

**Issue by caedmon** [meteor/meteor#6355] opened 2016-02-26 23:56 UTC
Build error when using destructuring with spread from function arg.  Add following to empty project.

function bar(x) {
  let [a,b, ...c] = x;
}

W20160226-15:47:33.821(-8)? (STDERR)          
W20160226-15:47:33.821(-8)? (STDERR) /Users/caedmon/.meteor/packages/meteor-tool/.1.1.13-beta.11.1kdrq62++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160226-15:47:33.821(-8)? (STDERR) 						throw(ex);
W20160226-15:47:33.821(-8)? (STDERR) 						      ^
W20160226-15:47:33.831(-8)? (STDERR) Error: Can't find npm module 'babel-runtime/helpers/toArray'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160226-15:47:33.831(-8)? (STDERR)     at Object.Npm.require (/Users/caedmon/projects/spread/.meteor/local/build/programs/server/boot.js:178:17)
W20160226-15:47:33.832(-8)? (STDERR)     at options.fallback (packages/modules-runtime/modules-runtime.js:28:1)
W20160226-15:47:33.832(-8)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:79:1)
W20160226-15:47:33.832(-8)? (STDERR)     at meteorInstall.spread.js (/Users/caedmon/projects/spread/.meteor/local/build/programs/server/app/app.js:9:17)
W20160226-15:47:33.832(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
W20160226-15:47:33.832(-8)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160226-15:47:33.833(-8)? (STDERR)     at /Users/caedmon/projects/spread/.meteor/local/build/programs/server/app/app.js:59:1
W20160226-15:47:33.833(-8)? (STDERR)     at /Users/caedmon/projects/spread/.meteor/local/build/programs/server/boot.js:245:10
W20160226-15:47:33.834(-8)? (STDERR)     at Array.forEach (native)
W20160226-15:47:33.834(-8)? (STDERR)     at Function._.each._.forEach (/Users/caedmon/.meteor/packages/meteor-tool/.1.1.13-beta.11.1kdrq62++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)

**Comment by zol** [comment] 2016-03-01 00:01
Please provide a repository with a full reproduction, I can't reproduce the issue by adding the snippet you mention to an empty project.

**Comment by caedmon** [comment] 2016-03-01 00:22
Repro at https://github.com/caedmon/spread

**Comment by benjamn** [comment] 2016-03-01 16:19
Fixed in [`beta.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-190789852).

**Closed by benjamn** 2016-03-01 16:19 UTC
Labels: can't-reproduce, needs-repro
