### ISSUE TITLE
1.3 - Getting non-useful error reports in console

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#6708] opened 2016-04-05 18:41 UTC
This is happening to me again, kind of randomly:

![title_here](https://cloud.githubusercontent.com/assets/12532733/14293851/3c4714f8-fb23-11e5-9eb2-a0a5d1d6a133.png)

What is causing this and how do I fix it? I used to get actual names of files in my code, now I just see modules.js or meteor.js.

**Comment by ffxsam** [comment] 2016-04-06 00:55
Another example below. I can't replicate this consistently.

![title_here](https://cloud.githubusercontent.com/assets/12532733/14302587/6b743c0e-fb57-11e5-8d8b-9a991a411d4d.png)

Source maps are missing maybe? It's showing transpiled code as opposed to my original source.

![title_here](https://cloud.githubusercontent.com/assets/12532733/14302595/871928b6-fb57-11e5-86b6-1d250b3e6415.png)

**Comment by serkandurusoy** [comment] 2016-04-06 18:38
To recap my problem from #6639 

* I am on Ubuntu
* Running Meteor 1.3.1
* All my scripts are appended ?hash=xxxxxx
* They do not map directly to my sources, rather to their corresponding built versions
* Scripts are not in `head` but prepended to `body`

**Comment by benjamn** [comment] 2016-04-12 17:37
The source maps issue will be officially fixed when Meteor 1.3.2 is released today or tomorrow, but you can test it out by doing `meteor update --release 1.3.2-rc.5` now.

**Comment by GrushinEgor** [comment] 2016-04-13 09:35
@benjamn I still have a merged app.js file
![image](https://cloud.githubusercontent.com/assets/6255315/14489124/2a9e602e-0174-11e6-8839-adf0e6bda685.png)

**Comment by benjamn** [comment] 2016-04-15 19:16
Just to summarize: we are still bundling/concatenating files in development, because it would be too much of a development/production difference not to do so, but Meteor 1.3.2 restores support for source maps so that the files appear distinct in the dev tools, and stack traces make sense.

**Closed by benjamn** 2016-04-15 19:16 UTC
Labels: in progress, known-fix

**Comment by GrushinEgor** [comment] 2016-04-15 21:24
@benjamn why I have only one file in dev tools while I have very big project with js files in /client and /model directories? 
![image](https://cloud.githubusercontent.com/assets/6255315/14575289/7916dde8-0369-11e6-9682-6e03baf8fe4a.png)

**Comment by itaibs** [comment] 2016-04-17 15:54
Hi!
Just updated to 1.3.2.1. 

When running locally this seems to be working perfectly. Thanks for the fix!

However, when deploying, with the debug flag, everything seems to be bundled to the same file like before... Is this intended?

**Comment by Sikwan** [comment] 2016-05-18 12:08
Hi everyone, it seems to me this issue is still not fixed.

Per https://forums.meteor.com/t/how-to-prevent-merging-files-in-1-3-when-running-in-dev/20312/9 I tried to remove the bundler-cache, I even wiped the whole .meteor/local but everything is still appearing as one file in the console.

I'm using latest Meteor (1.3.2.4), is there something I'm doing wrong ?

Thanks

**Comment by abernix** [comment] 2016-05-18 12:22
@GrushinEgor, @Sikwan, what if you scroll down that "Sources" list on the left – do you see "💻app"?  (see below)
<img width="297" alt="screen shot 2016-05-18 at 3 18 14 pm" src="https://cloud.githubusercontent.com/assets/841294/15358215/d734990e-1d0b-11e6-8b14-a498bac0ec67.png">

**Comment by Sikwan** [comment] 2016-05-18 13:19
Sorry I removed my comment by mistake, was complaining about the same issue even after having wiped the .meteor/local.

Within the 💻app I can only see CSS and using the source map in the app.js?hash, there are some files I cannot find unfortunately.

**Comment by abernix** [comment] 2016-05-18 13:21
@Sikwan Does it happen on a new project?  If not, and it's only your existing project, could you post a version of your `.meteor/versions` in a [Gist](//gist.github.com) and provide the link?

**Comment by Sikwan** [comment] 2016-05-18 14:13
Hi @abernix, tried it on a new project and it seems to work.

Here is the gist ! https://gist.github.com/Sikwan/d4815fed7f33532bf873687123717833 I had to remove a couple packages (proprietary from my company) but nothing related to it, it is just a custom driver on the server side.

**Comment by abernix** [comment] 2016-05-18 14:19
@Sikwan All good. :smile:  The reason I asked was I had a package a while back that was breaking my source map (it was actually `Npm.depends`-ing `source-map-support` and doing something very strange with it.  Unfortunately, I can't for the life of me remember what package it was.  I was hoping to recognize it in your package list, but no luck.

I don't know how reasonable it is to delete blocks of your packages at a time and see what happens, but you might uncover something.  If anything, the errors that it causes might suddenly become more understandable. 😆

**Comment by Sikwan** [comment] 2016-05-18 14:36
No problem ! Will do and post back what I can uncover :) Thanks

**Comment by GrushinEgor** [comment] 2016-05-22 12:16
Solved! I found the culprit — I had installed `pbastowski:angular-babel@1.0.4` manually (I dunno know why). After removing it and reinstall `angular` it works!

**Comment by Sikwan** [comment] 2016-06-21 13:52
I removed pbastowski:angular-babel but I still have the same issue. I can see some source-maps though not my application files.

**Comment by itaibs** [comment] 2016-07-09 04:53
Could there have been some regression on this on the last update? I'm getting the wrong source code when looking at different files on the chrome dev tools...

**Comment by abernix** [comment] 2016-07-11 08:05
@itaibs Nothing new known and seems to be working okay for me, but you didn't specify what "last update meant".  Regardless, this issue is closed so please reproduce in a fresh project and open a new issue with a reproduction git repo attached (follow the steps in new issue text).  Thanks!
