### ISSUE TITLE
Meteor.isCordova is false after redirect

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#9411] opened 2017-11-24 03:53 UTC
Meteor Cordova App

when u redirect to another meteor app with same code but different sub domain in cordova

Meteor.isCordova is false

is this a bug or what ?

reproduce

https://github.com/crapthings/meteor-is-cordova-bug

https://youtu.be/iL6QnSVgIn8

~~~to me its more like Meteor.isCordova is just detect cordova namespace exist and not the cordova building environment~~~

**Comment by crapthings** [comment] 2017-11-24 05:11
window.location.reload()  Meteor.isCordova = true
window.location.replace('http://localhost:3000') same origin Meteor.isCordova = false

**Comment by crapthings** [comment] 2017-11-24 06:22
i think i know what's goin' on here.

when cordova boot app, its start a local http server, and all cordova relative js served by that. when we replace url, that means u are going to server only code the html head serve to desktop version not web.cordova.

we have to switch ddp url instead of force redirect ? right ?

**Comment by hwillson** [comment] 2017-12-04 21:40
Hi @crapthings - yes, your explanation in https://github.com/meteor/meteor/issues/9411#issuecomment-346751492 sounds right. This is by design, so I'll close this off. Thanks!

**Closed by hwillson** 2017-12-04 21:40 UTC
Labels: Project:Mobile
