### ISSUE TITLE
Use npm scoped private package

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#7810] opened 2016-09-23 10:52 UTC
I've seen that there was a [thread](https://github.com/meteor/meteor/issues/4985) about scoped packages and it had been apparently resolved but I still can't use private scoped packages. It was probably about public scoped packages, not private. My project is in Meteor 1.4.1.1.

When I add my private package I get following error message:
`Error: Can't find npm module '@useful/bluebutton'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?`

I've tried both `import BlueButton from "bluebutton"` and `import BlueButton from "@useful/bluebutton"`.

**Comment by abernix** [comment] 2016-11-16 09:54
I believe private NPM repos are working as of late (@sebakerckhof – you use private repos right?), but can you try this again with the [latest Meteor 1.4.2.1](https://github.com/meteor/meteor/blob/devel/History.md#v1421)?  If you still experience the problem, please:

1. Create a reproduction repo (per [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug))
2. For the private package, fork a popular NPM into your private namespace, like [`moment`](https://www.npmjs.com/package/moment) or [`lodash`](https://www.npmjs.com/package/lodash), for example.
3. Publish that reproduction here.

Then someone trying to reproduce this can just fork the same package into their own private repo and simply change the `@`namespace and easily reproduce / fix it.

**Comment by abernix** [comment] 2016-12-14 18:11
I ran into this the other day during another reproduction so I'm pretty sure it's still a problem but I failed to save my reproduction.  I worked (hacked) around it by forcing [this statement](https://github.com/meteor/meteor/blob/8e32da57a128a70fdc09823b5d506758ce6a9b82/tools/isobuild/bundler.js#L2009-L2018) to `false` (and thus not excluding _any_ `node_modules` from the bundle).  I don't recommend this but it worked in my pinch. 😄

**Comment by sebakerckhof** [comment] 2016-12-14 18:23
Yeah, just FYI since I now only see you mentioned me: We use private repo's, but have no scoped packages.

**Comment by mart-jansink** [comment] 2017-02-16 11:57
Due to hardware constraints I'm still using version 1.3.5.1 for some projects and I had the same issue here. Thanks to @abernix hint I was able to resolve it by changing

```
copyOptions.directoryFilter = function (dir) {
  var base = files.pathBasename(dir);
  var parentBase = files.pathBasename(files.pathDirname(dir));
  if (parentBase !== "node_modules") {
    return true;
  }

  // Compute prodPackageNames lazily.
  prodPackageNames = prodPackageNames || meteorNpm.getProdPackageNames(nmd.sourcePath);

  return _.has(prodPackageNames, base);
};
```

to

```
copyOptions.directoryFilter = function (dir) {
  var base = files.pathBasename(dir);
  if (base[0] === "@") {
    return true;
  }
  var parentBase = files.pathBasename(files.pathDirname(dir));
  if (parentBase[0] === "@") {
    base = parentBase + "/" + base;
    parentBase = files.pathBasename(files.pathDirname(files.pathDirname(dir)));
  }
  if (parentBase !== "node_modules") {
    return true;
  }

  // Compute prodPackageNames lazily.
  prodPackageNames = prodPackageNames || meteorNpm.getProdPackageNames(nmd.sourcePath);

  return _.has(prodPackageNames, base);
};
```

at `tools/isobuild/bundler.js#L1964. This corrects the fact that a scoped package's name contains the parent directory name.

I didn't yet have the time implement this fix latest version as well, which has some more complex code to determine which directories are copied. But hopefully it helps the person who first gets round to fixing it.

**Comment by hwillson** [comment] 2017-09-08 19:04
As mentioned in https://github.com/meteor/meteor/issues/7810#issuecomment-260902481, if anyone encountering this issue (using Meteor >= 1.5.2) can supply a reproduction, that would really help with troubleshooting. Closing for now - thanks!

**Closed by hwillson** 2017-09-08 19:04 UTC
Labels: bug, confirmed, Impact:few
