### ISSUE TITLE
Vague error in web console when invoking method

### ISSUE THREAD

**Issue by CaptSaltyJack** [meteor/meteor#4032] opened 2015-03-26 04:47 UTC
I'm invoking a method defined on the server, and I get the below error. I'm opening an issue for this, because as a developer, this tells me nothing about what's happening. What kind of exception? It turns out the actual issue is that I was doing this in the `Meteor.call` callback:

```
if result.success
  Router.go '/seller/account-created'
else
  console.log error.error
```

A more appropriate error would've been something like "result is undefined," since that's what the issue was. Thoughts?

```
"Exception in delivering result of invoking 'createSeller': ["submit form"]/</<@http://localhost:3000/client/templates/seller/seller-create.coffee.js?224060aa0e4015a96a402b5ad1055c1d5364bcb7:21:1
Meteor.bindEnvironment/<@http://localhost:3000/packages/meteor.js?e53378596562e8922a6369c955bab1e047fa866b:978:17
._maybeInvokeCallback@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3860:7
.receiveResult@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3880:5
._livedata_result@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:4964:7
Connection/onMessage@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3725:7
._launchConnection/self.socket.onmessage/<@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:2717:11
_.forEach@http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:156:7
._launchConnection/self.socket.onmessage@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:2716:9
SockJS</REventTarget.prototype.dispatchEvent@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:156:9
SockJS</SockJS.prototype._dispatchMessage@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:1141:5
SockJS</SockJS.prototype._didMessage@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:1199:13
SockJS</SockJS.websocket/that.ws.onmessage@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:1346:9"
```

**Comment by CaptSaltyJack** [comment] 2015-03-26 05:02
I just realized, even if I call a nonexistent function, e.g.:

        Meteor.loginWithPassword user, password, (error) ->
          if error?
            fakeFunction()

I get an error similar to the above. No mention of calling a function that doesn't exist. This makes it *extremely* difficult to debug!

**Comment by glasser** [comment] 2015-03-26 23:19
I think this is a duplicate of #2232.  Our nested error printing code doesn't work very well on Firefox.   As I commented there last year, happy to take a pull request to improve this.

**Closed by glasser** 2015-03-26 23:19 UTC
