### ISSUE TITLE
Invalid ROOT_URL crashes without error message

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9242] opened 2017-10-18 02:04 UTC
### Environment
- Windows 10 1703 (OS Build 15063.608)
- Meteor 1.6-rc.9

### Repro
1. `set ROOT_URL=192.169.1.100:4000`
2. `meteor`

### Result
```javascript
E:\temp\simple-todos-16-rc9>meteor
Errors prevented isopacket load:

While loading isopacket `combined`:
packages/meteor.js:1233:20: Cannot read property 'slice' of null
at packages/meteor.js:1233:20
at packages/meteor.js:1245:4
at packages/meteor.js:1392:3


C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.9\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: isopacket load failed?
    at loadIsopacketFromDisk (C:\tools\tool-env\isopackets.js:319:11)
    at C:\tools\tool-env\isopackets.js:112:9
    at Object.exports.noYieldsAllowed (C:\tools\utils\fiber-helpers.js:37:14)
    at loadIsopackage (C:\tools\tool-env\isopackets.js:103:34)
    at ProjectContext._buildResolver (C:\tools\project-context.js:795:34)
    at C:\tools\project-context.js:508:29
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:507:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._resolveConstraints (C:\tools\project-context.js:506:13)
    at C:\tools\project-context.js:285:9
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:275:18)
    at Profile.run (C:\tools\project-context.js:245:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.resolveConstraints (C:\tools\project-context.js:244:13)
    at C:\tools\runners\run-all.js:75:27
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at new Runner (C:\tools\runners\run-all.js:74:18)
    at Object.exports.run (C:\tools\runners\run-all.js:366:16)
    at Command.doRunCommand [as func] (C:\tools\cli\commands.js:421:17)
    at C:\tools\cli\main.js:1492:15
```

### Fix
Issue is here: https://github.com/meteor/meteor/blob/release-1.6/tools/cli/main.js#L613
See this [runkit](url) to see how the `url` package parses that URL.

change L613 to:
```javascript
if (!parsedUrl.host || parsedUrl.protocol !== "http:" || !parsedUrl.slashes) {
```

Let me know if you want me to spin up a PR.

**Comment by hwillson** [comment] 2017-10-18 14:51
Thanks for reporting this @brucejo75! Yes, we'd definitely review a PR for this. One small suggestion - please consider protocols other than http in your PR (e.g. https). Thanks!

**Comment by hwillson** [comment] 2017-10-19 16:53
Oops, I just noticed this is a duplicate of https://github.com/meteor/meteor/issues/8026. I'll close this one since the other one is older, but it is also marked as `pull-requests-encouraged` if anyone is interested. Thanks!

**Closed by hwillson** 2017-10-19 16:53 UTC
Labels: bug, confirmed, Impact:few, pull-requests-encouraged, Severity:has-workaround
