### ISSUE TITLE
meteor run --test does not exit after the tests have run 

### ISSUE THREAD

**Issue by lnader** [meteor/meteor#4218] opened 2015-04-16 17:52 UTC
We are trying to run our tests as part of CI.  

meteor run --test 

doesn't exit with the status code, which is needed for CI to continue to next step. The process just stays up and running after running the tests.  It works correctly when there are test failures.

**Comment by glasser** [comment] 2015-04-16 18:04
What version are you running?  I thought this was fixed in 1.0.4 (see #3793).

**Comment by lnader** [comment] 2015-04-16 20:52
METEOR@1.0.4.2 

I have tried these combinations and none of them exit.

meteor run --test --once
meteor --test --once
meteor --test
meteor --once

**Comment by mhwheeler** [comment] 2015-04-17 01:32
I'm having a similar experience with my project. I tried switching to various meteor versions 1.0.2.1 through 1.1.0.2. I'll see if I can come up with a repro.

**Comment by ameesters** [comment] 2015-04-21 12:18
Just like mhwheeler i can confirm this, i also get:
`stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED`

and the runner doesn't exit, with or without `--once`.
the full command used: `VELOCITY=1 meteor run --test --settings ../config/development.default.json --once`

**Comment by tgardner4** [comment] 2015-04-21 17:48
This is a significant issue to us.  Would love to see a fix from meteor on this.

**Comment by marcuscarr** [comment] 2015-04-21 19:09
I've run into this as well.

**Comment by jonarnaldo** [comment] 2015-04-21 21:20
I've had this problem as well. :(

**Comment by glasser** [comment] 2015-04-21 22:52
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

The `meteor run --test` support is mostly maintained by the Velocity team.  I generally merge all their PRs after cursory review.  But that means that I'm much less familiar with this part of the codebase and really rely on good reproductions!

Have you filed this as a bug over at https://github.com/meteor-velocity/velocity ? I'd love to learn why this isn't working, since #3793 was supposed to fix exactly this.  Maybe Velocity changed something?

**Comment by lnader** [comment] 2015-04-22 03:50
Here's how to reproduce

git clone git@github.com:lnader/testing-in-meteor.git
cd testing-in-meteor
meteor add mike:mocha
meteor run --test --once

@glasser  - file at velocity https://github.com/meteor-velocity/velocity/issues/322

**Comment by samhatoum** [comment] 2015-04-22 04:10
Thanks for the report @lnader 
@glasser we'll look into this and report back here

**Comment by mpercival** [comment] 2015-05-25 14:35
This is still an issue for me. What is the time frame for getting this resolved?

**Comment by samhatoum** [comment] 2015-05-25 18:54
Hey @mpercival

Can you please follow this issue up with the Velocity filed issue here:

https://github.com/meteor-velocity/velocity/issues/322

Be sure to list all the versions of packages you are using, as well as debug log files.

**Comment by pauldowman** [comment] 2015-06-11 02:45
I can definitely reproduce this too, with @lnader's repo and with a newly created Meteor 1.1.0.2 app that has just the sample jasmine tests added.

Here's some more info:

1. This only seems to happen with the jasmine client integration tests, if I remove those it works. Commenting them out has no effect though, it seems to happen only if the mirror starts.
2. The jasmine client integration tests show 0 passing in the console reporter and it seems hung
3. As soon as I load the app in a browser the client integration tests run and then it exists successfully. Somehow the HTML reporter causes the client integration tests to run.

Other maybe notable things:

1. With --test the tests seem to be running twice
2. There's also the error `stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED` printed on stdout immediately when the app starts. (But even so, it still exits correctly when the HTML reporter is running).
3. the logs for the mirrors say `Using velocity:METEOR@1.1.0.2_3 as requested (overriding Meteor 1.1.0.2)`

I'll cross-post this on meteor-velocity/velocity#322 too.

**Comment by samhatoum** [comment] 2015-06-11 04:04
Running with `meteor --test --release velocity:METEOR@1.1.0.2_3` fixes the problem

@glasser can you please close this issue, anyone that needs further help can come to the issue on the velocity repo here:

https://github.com/meteor-velocity/velocity/issues/322

**Closed** 2015-08-12 02:25 UTC
Labels: Project:Tool

**Comment by ne8il** [comment] 2016-03-10 14:52
Hi, I'm still seeing this issue and was wondering if other people found a solution to it.
I'm not sure if there was a fix given in the Velocity issue(s) linked because they all lead to 404's now. I'm running Meteor 1.2.1. All my tests run with 
`meteor run --test --settings settings.json`
They all run through and then it outputs 
```
I20160310-09:47:08.470(-5)? mocha: 69 tests passed (11s)
```
but does not exit with a status code if they all pass - I've found if one fails it does output a `FAILURE` code.

**Comment by dhrubins** [comment] 2016-10-02 18:50
Sorry, ignore that reference.
