### ISSUE TITLE
npm peer requirements not installed after updating to React v15.0.1

### ISSUE THREAD

**Issue by tdhz77** [meteor/meteor#6753] opened 2016-04-08 16:43 UTC
```
W20160408-11:42:13.970(-5)? (STDERR) WARNING: npm peer requirements not installed:
W20160408-11:42:13.970(-5)? (STDERR)  - react@15.0.0 installed, react@0.14.x needed
W20160408-11:42:13.970(-5)? (STDERR)  - react-addons-pure-render-mixin@15.0.0 installed, react-addons-pure-render-mixin@0.14.x needed
W20160408-11:42:13.970(-5)? (STDERR) 
W20160408-11:42:13.970(-5)? (STDERR) Read more about installing npm peer dependencies:
W20160408-11:42:13.971(-5)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160408-11:42:13.971(-5)? (STDERR) 

```

**Comment by pabagan** [comment] 2016-04-09 00:07
Same issue here.

**Comment by Mistaken3lf** [comment] 2016-04-09 00:12
Same here. I was not able to update because of react-mounter.

**Comment by joetidee** [comment] 2016-04-09 00:34
Same here

**Comment by hobartwang** [comment] 2016-04-09 09:22
same here.
It throw a warning after adding meteor-react-data.

**Comment by preexo** [comment] 2016-04-10 04:28
same here

**Comment by dufia** [comment] 2016-04-10 13:21
same here but

````
WARNING: npm peer requirements not installed:
 - react@0.14.7 installed, react@15.x needed
 - react-dom@0.14.7 installed, react-dom@15.x needed
````

**Comment by taylorwc** [comment] 2016-04-11 16:55
I had this pop up today and found that it was due to version constraints in the package.json file. Try updating the versions associated with those packages in the dependency list for npm

**Comment by shouvik44** [comment] 2016-04-12 22:36
Can someone help me escape this Catch 22?  If I'm in react15.0.1, it wants react0.14.x. If I'm in react0.14.x, it wants react15.x.

Specifically,
When I install the npm packages mentioned in the "Migrating to Meteor 1.3" doc, Meteor wants every package to use an earlier version:
W20160412-14:56:42.318(-5)? (STDERR) WARNING: npm peer requirements not installed:
W20160412-14:56:42.318(-5)? (STDERR)  - react@15.0.1 installed, react@0.14.x needed
W20160412-14:56:42.319(-5)? (STDERR)  - react-dom@15.0.1 installed, react-dom@0.14.x needed
W20160412-14:56:42.319(-5)? (STDERR)  - react-addons-transition-group@15.0.1 installed, react-addons-transition-group@0.14.x needed
W20160412-14:56:42.319(-5)? (STDERR)  - react-addons-css-transition-group@15.0.1 installed, react-addons-css-transition-group@0.14.x needed
W20160412-14:56:42.319(-5)? (STDERR)  - react-addons-linked-state-mixin@15.0.1 installed, react-addons-linked-state-mixin@0.14.x needed
W20160412-14:56:42.319(-5)? (STDERR)  - react-addons-create-fragment@15.0.1 installed, react-addons-create-fragment@0.14.x needed
W20160412-14:56:42.319(-5)? (STDERR)  - react-addons-update@15.0.1 installed, react-addons-update@0.14.x needed
W20160412-14:56:42.319(-5)? (STDERR)  - react-addons-pure-render-mixin@15.0.1 installed, react-addons-pure-render-mixin@0.14.x needed
W20160412-14:56:42.320(-5)? (STDERR)  - react-addons-test-utils@15.0.1 installed, react-addons-test-utils@0.14.x needed
W20160412-14:56:42.320(-5)? (STDERR)  - react-addons-perf@15.0.1 installed, react-addons-perf@0.14.x needed

But, when I go into package.json and downgrade these to 0.14.8, I get this error

W20160412-17:31:33.167(-5)? (STDERR) WARNING: npm peer requirements not installed:
W20160412-17:31:33.169(-5)? (STDERR)  - react@0.14.8 installed, react@15.x needed
W20160412-17:31:33.169(-5)? (STDERR)  - react-addons-pure-render-mixin@0.14.8 installed, react-addons-pure-render-mixin@15.x needed

**Comment by taylorwc** [comment] 2016-04-14 14:18
@shouvik44 I would try running `npm update --dd` in your terminal and see if you can figure out which package is the constraint from the output. Then see if you need to correct any of the version requirements in your package.json file.

**Comment by shouvik44** [comment] 2016-04-14 16:11
Thanks Taylor - the issue was with the Atmosphere Package "ReactLayout" -
which is used with FlowRouter and wants to use React 0.14.8.

The kadira team wants users to shift to the npm package react-mounter, and
they are no longer maintaining ReactLayout.

**Comment by jujes** [comment] 2016-04-20 12:52
same issue here...

**Comment by mwdavisii** [comment] 2016-05-05 04:41
Everyone has been helpful. I had the same issue with ReactLayout. I moved to react-mounter and updated app, but still received warnings. I deleted my node_modules directory and re-added the npm modules one at a time. No more warning messages.
METEOR@1.3.2.4
react@15.0.2

**Comment by dufia** [comment] 2016-05-05 08:21
I downgraded these to 0.2.7 the the errors are gone

react-meteor-data@0.2.7
react-template-helper@0.2.7

**Comment by sascha1337** [comment] 2016-05-06 08:26
how to downgrade meteor packets dufia?

**Comment by dufia** [comment] 2016-05-06 10:28
@sascha1337 
yourappdirectory/.meteor/versions

**Comment by abernix** [comment] 2016-05-10 08:39
As I wrote in #6762 this is due to NPM package version constraints that you have in your `package.json` file.

@abernix wrote:
> A combination of using the latest Meteor 1.3.2.4 and the correct version NPM dependencies in your package should resolve this.
> 
> If you're still having problems, as others have said above, make sure your package.json is up to date with it's dependencies (you should be fine if you are using --save/--save-dev when installing new packages), remove your node_modules directory, and run meteor npm install to refresh everything.

Closing this as many have reported success by keeping their NPM versions in-line, but if anyone is still having a problem, please open a new issue with a complete reproduction repository per the [guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).  Also, try asking for help on either the [Meteor Forums](https://forums.meteor.com) or StackOverflow.

**Closed by abernix** 2016-05-10 08:39 UTC
