### ISSUE TITLE
Blaze: Uncaught Error: Must be attached

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2981] opened 2014-11-01 13:55 UTC
See [example project](https://github.com/mitar/meteor-issue2981). When clicking on "Click Me" button, there is an uncaught Error: `Must be attached`.

```
Uncaught Error: Must be attached domrange.js:337
DOMRange.containsElement domrange.js:337
(anonymous function) view.js:741
(anonymous function) events.js:47
jQuery.event.dispatch jquery.js:4624
elemData.handle jquery.js:4292
```

**Comment by Slava** [comment] 2015-03-03 22:28
Thanks @mitar, confirming this as a bug.

What happens here is:

- You click on a button
- button removes the document model associated with it and that removes the dom node
- the dom node is already removed but there are outstanding event handlers


There is no a single most obvious way to fix them. One of the ways would be to not remove the DOM node until all the event handlers are fired, but that's raises other questions. Another way is to not fire the rest of the event handlers after the DOM node is removed.

**Comment by steph643** [comment] 2015-03-30 12:19
Get this as well.

It seems the issue appeared in Meteor 1.1-rc.0 (I was using the Windows Preview before).

In my case I don't destroy the same DOM node the event is fired upon, but another one. Because of this, and because I have only one event handler, I don't see how an "outstanding event handlers" could cause  the issue.

Nevertheless, I followed @slava's idea number one and solved this by putting my destroying function in a Meteor.defer().

**Comment by serkandurusoy** [comment] 2015-04-15 21:11
I confirm that `Meteor.defer()` does the job in making the error disappear.

In my case raising the catchall `click` was not an option because it is used as a trigger to remove the enclosing do through a reactiveVar on the parent template. It works like a show/hide details in a table row and the button that I wanted to catch the specific click on is also used for deleting that document from the collection.

**Comment by That-David-Guy** [comment] 2015-05-28 09:01
I have a similar issue, but couldn't get the Meteor.defer() to work. Are you able to provide an example please @serkandurusoy?

My Template:
```
<template name="speechListItem">
  <li>
    {{title}}
    <button class="delete">X</button>
  </li>
</template>
```
My Event listener:
```
Template.speechListItem.events({
  'click button.delete': function(event) {
    event.preventDefault();
    Speeches.remove(this._id)  
    // Tried using Meteor.defer(function() { Speeches.remove(this._id) }); but nothing happened
  },
  'click li': function() {
    // when this event is here it causes 'Uncaught Error: Must be attached', but still deletes the element
    // If I remove this event listener it also works, but with no error
  }
});
```

**Comment by serkandurusoy** [comment] 2015-05-28 09:32
@That-David-Guy you could switch the order of `click li` and `click button.delete`

**Comment by That-David-Guy** [comment] 2015-05-28 09:34
Tried that as well. Didn't work.

**Comment by That-David-Guy** [comment] 2015-05-28 23:55
If I change my li to divs and select it with classes. I don't get the error.

**Comment by casperanderseneu** [comment] 2015-08-18 05:04
I experienced similar.
li element node, with an embedded remove button.
both have click handlers.
this worked for me, maybe it's useful for others: event.stopPropagation();

**Comment by sferoze** [comment] 2015-09-19 20:59
I am having this issue as well. But I cannot reproduce it reliably which is a huge headache. 

It happens once in awhile. Basically I have 2 click handlers setup on 2 dom elements attached using Template.events 

One click handler routes to a new page, the other just toggles a class to open the sidebar.

But for some reason, after a hot code push I think, the click handlers break, and when I click the elements it console.log `Blaze: Uncaught Error: Must be attached`

These are simple click handlers yet I get this error once in awhile. 

Even refreshing the page does not help to fix the click handlers. So a user would just think the entire site is broken even after refreshing the page. 

You have to actually quit the tab, and then navigate back to the app in a new tab. Then the click handlers work again.

This is a problem for me, and a headache since I cannot reproduce reliably. It just shows itself once in-awhile.

**Comment by sferoze** [comment] 2015-09-19 23:38
I think I may have solved the core issue which was causing this bug. Take a look

ORIGINAL CODE 
```
Template.notepad.destroyed = ->
  t = @
  t.instance.clear()
```

NEW CODE
```
Template.notepad.destroyed = ->
  t = @

  if t?.instance? and t?.instance?.clear?
      t.instance.clear()
```

I believe this has solved the issue for me. When the issue arose, typically after making changes to the code and having hot reload the issue still persisted. But after this change, the issue disappeared.

**Comment by mitar** [comment] 2015-09-19 23:43
What is `t.instance` in your case?

**Comment by sferoze** [comment] 2015-09-19 23:46
it is an meteor easy search component

```
t.instance = EasySearch.getComponentInstance
    index: 'notes'
```

**Comment by Anima-t3d** [comment] 2016-06-29 08:28
This seems to occur when a template onDestroyed causes an exception? Is it worth investigating whether an onDestroyed (more specific an exception in onDestroyed) can affect other templates and give an `Uncaught Error: Must be attached ` error?

**Comment by guillaumeko** [comment] 2016-09-16 14:23
Hey guys, just to let you know if it can help someone, I had this error when I wanted to delete my list. here is the solution I could manage:

**Code before:**
`'lists.remove'(listId) {
        check(listId, String);

        const list = Lists.findOne(listId);
        if (list.owner !== this.userId) {
            throw new Meteor.Error('not-authorized');
        }
            Tasks.remove({"listId": listId});
            Lists.remove(listId);
    },`

**Code working without error:**
'lists.remove'(listId) {
        check(listId, String);

        const list = Lists.findOne(listId);
        if (list.owner !== this.userId) {
            throw new Meteor.Error('not-authorized');
        }
        if (!this.isSimulation) {
            Tasks.remove({"listId": listId});
            Lists.remove(listId);
        }
    },

Hope it can help someone.

Cheers

**Comment by mitar** [comment] 2016-09-16 16:51
Could you make a reproduction where this happens regularly?

**Comment by guillaumeko** [comment] 2016-09-19 12:19
You can find the test project from this commit:
https://github.com/guillaumeko/my-todo/tree/86dd9d58e1a1b4323d98182fe02f4a920244ecb4
It happened everytime I deleted a List by the delete cross icon.

Let me know if you need anything else. Thanks

**Comment by MartinWillitts** [comment] 2016-11-05 21:15
I had a panel with a submit event that had no selector. I added it in the process of converting from SemanticUI to MaterializeCSS.
`  'submit'(event) {
    event.preventDefault();
  },
`
I should have had a selector e.g.:
`  'submit .shoot_sign_up_form'(event) {
    event.preventDefault();
  },
`
then I stopped seeing the 'must be attached' warning.

**Comment by hwillson** [comment] 2016-12-13 14:12
This issue has been moved to meteor/blaze#213 - closing here. Thanks!

**Closed by hwillson** 2016-12-13 14:12 UTC
Labels: Project:Blaze

**Comment by drone1** [comment] 2022-01-27 23:08
I hit this today and just found the reason. 

For anyone else who finds this thread, I'm hoping you find the following useful: in my case, I had an event handler in a template that was still being called because code in my template's onDestroyed() was triggering an exception (thus messing up proper event detachment, presumably). 

Example:

```
Template.foo.onDestroyed(function() {
   // trigger an exception
})

Template.foo.events({
  'mousemove div': function(e, template) { /* ... */ } // Won't be properly detached once the template is destroyed
})
```
