### ISSUE TITLE
remove templating dependency from facebook and google - oauth package

### ISSUE THREAD

**Issue by dohomi** [meteor/meteor#6564] opened 2016-03-23 00:32 UTC
Hi,

it would be nice if the new `Meteor 1.3` release would remove the `templating`dependency out of the oauth packages. Its only used for displaying a configuration file. Many users swop `Blaze`to `Angular`or `React`and it would be a great help to declare this dependency as `weak`.

Thanks Dominic

**Comment by abernix** [comment] 2016-10-28 11:48
Related to #7728

**Comment by hwillson** [comment] 2017-02-13 19:20
This is a duplicate of #7715, but the good news is this is coming in [Meteor 1.4.3](https://github.com/meteor/meteor/blob/devel/History.md#v143)! I'll close this issue since the discussion in #7715 is more recent. Thanks for posting this originally!

**Closed by hwillson** 2017-02-13 19:20 UTC
Labels: Project:Accounts (in user apps)
