### ISSUE TITLE
performance issue with collections observe

### ISSUE THREAD

**Issue by hiukim** [meteor/meteor#3804] opened 2015-02-24 06:25 UTC
I have experienced a performance issue with collection `observe`. When I have a large collection, ~120,000 documents, the collection `observe` call takes unreasonably long to execute and halt the system.

I have created a sample project to demonstrate the issue: https://github.com/hiukim/meteor_observe_performance
Checkout the file /server/main.js.  It basically just create a large collection and then benchmark the execution time of the `observe` call.

When I run the sample app locally, it takes more than a minute for that `observe` call to finish. Interesting thing is that, if I reduce the documents size to around ~100,000, then call takes only around 5 seconds. I suspect I have encountered some kind of threshold (maybe memory limit)  Also, the problem gets more serious when the size of each documents are larger. I have experienced a few minutes halt in my another production app every time I restarted the server due to this long-executing observe call.

With some diagnostic, It seems to me that the matched documents will be put into memory upon `observe`.  If that's the case, then the `observe` does not scale. I don't think putting the whole collection into memory is a viable option for large scale project. In fact, here we are just talking about 10^5 documents only.

**Comment by glasser** [comment] 2015-02-24 22:08
Thanks.  We're aware of this issue.  As mentioned in #3695 and #3694, we need to increase the number of strategies for implement `observe` to work better with large collections (with possible tradeoffs such as sometimes including redundant information about what has changed).  Since we are tracking this elsewhere, I'm going to close this issue.

**Comment by Slava** [comment] 2015-02-24 22:23
Right now, when you start a giant observe on all 120K documents in the collection, Meteor goes and fetches all of them from Mongo to memory. This is an explanation why it takes a while.

**Comment by mikowals** [comment] 2015-02-25 02:50
I think this should be reopened and is a separate issue to the feature requests in #3695 and #3694  .  It looks more like a bug in the node mongo driver that requires the 'batchSize' option of a cursor to be set.  It impacts fetch as well as observe and observeChanges.  

I have [forked the original reproduction](https://github.com/mikowals/meteor_observe_performance/commit/d2cbbceaabc71f5f4425a653da50c879e8c41ec9) and added a fetch call and some looping to explore the issue.

I don't know if changing the batchSize is the correct fix but [it is mentioned as a fix outside](http://stackoverflow.com/a/13726536/728291) of meteor where the problem also occurs around 100,000 docs.  There have also been [other node driver problems when batchSize uses the default](https://jira.mongodb.org/browse/NODE-300?jql=project%20%3D%20NODE%20AND%20text%20~%20batchSize).  Anyway, if I just look at fetching using meteor devel the time to fetch spikes intermittently to 50+ seconds.  If I add 'batchSize: 50000' to mongo-driver.js it continues fetching all the way up to 1 million docs with only a gradual slowdown from 4 to 19 seconds. 

For observe, I think batchSize fixes this specific issue but another problem occurs around 130,000 docs.  I don't know how long that observe takes as it pegs the CPU of my Macbook Air at 100% for 15min+ and I lose patience.

Fetch results running meteor devel branch (increasing limit in cursor by 5,000 docs per row):
> I20150225-11:13:58.869(10)? 90000 ' docs fetched.  Time used: ' 1457 'ms'
I20150225-11:14:45.407(10)? 95000 ' docs fetched.  Time used: ' 46635 'ms'
I20150225-11:14:47.122(10)? 100000 ' docs fetched.  Time used: ' 1714 'ms'
I20150225-11:14:49.060(10)? 105000 ' docs fetched.  Time used: ' 1938 'ms'
I20150225-11:14:50.983(10)? 110000 ' docs fetched.  Time used: ' 1922 'ms'
I20150225-11:14:52.896(10)? 115000 ' docs fetched.  Time used: ' 1913 'ms'
I20150225-11:16:09.205(10)? 120000 ' docs fetched.  Time used: ' 76309 'ms'
I20150225-11:17:37.255(10)? 125000 ' docs fetched.  Time used: ' 88050 'ms'
I20150225-11:19:13.000(10)? 130000 ' docs fetched.  Time used: ' 95745 'ms'
I20150225-11:20:59.668(10)? 135000 ' docs fetched.  Time used: ' 106667 'ms'
I20150225-11:22:50.640(10)? 140000 ' docs fetched.  Time used: ' 110972 'ms'
I20150225-11:24:51.660(10)? 145000 ' docs fetched.  Time used: ' 121020 'ms'

Fetch results running for [with 'batchSize:50000'](https://github.com/mikowals/meteor/commit/299ee9137bee0547886e849b8d704f8644b3b628) (increasing limit in cursor by 50,000 docs per row):
> I20150225-11:37:27.214(10)? 90000 ' docs fetched.  Time used: ' 1769 'ms'
I20150225-11:37:29.726(10)? 140000 ' docs fetched.  Time used: ' 2512 'ms'
I20150225-11:37:33.184(10)? 190000 ' docs fetched.  Time used: ' 3457 'ms'
I20150225-11:37:37.692(10)? 240000 ' docs fetched.  Time used: ' 4508 'ms'
I20150225-11:37:42.807(10)? 290000 ' docs fetched.  Time used: ' 5115 'ms'
I20150225-11:37:48.556(10)? 340000 ' docs fetched.  Time used: ' 5748 'ms'
I20150225-11:37:55.173(10)? 390000 ' docs fetched.  Time used: ' 6616 'ms'
I20150225-11:38:03.032(10)? 440000 ' docs fetched.  Time used: ' 7859 'ms'
I20150225-11:38:11.680(10)? 490000 ' docs fetched.  Time used: ' 8647 'ms'
I20150225-11:38:21.496(10)? 540000 ' docs fetched.  Time used: ' 9814 'ms'
I20150225-11:38:32.214(10)? 590000 ' docs fetched.  Time used: ' 10715 'ms'
I20150225-11:38:43.962(10)? 640000 ' docs fetched.  Time used: ' 11747 'ms'
I20150225-11:38:55.898(10)? 690000 ' docs fetched.  Time used: ' 11934 'ms'
I20150225-11:39:08.555(10)? 740000 ' docs fetched.  Time used: ' 12657 'ms'
I20150225-11:39:22.588(10)? 790000 ' docs fetched.  Time used: ' 14032 'ms'
I20150225-11:39:37.739(10)? 840000 ' docs fetched.  Time used: ' 15151 'ms'
I20150225-11:39:53.400(10)? 890000 ' docs fetched.  Time used: ' 15661 'ms'
I20150225-11:40:09.800(10)? 940000 ' docs fetched.  Time used: ' 16398 'ms'
I20150225-11:40:27.992(10)? 990000 ' docs fetched.  Time used: ' 18191 'ms'

Observe results running meteor devel branch:
> I20150225-12:20:26.203(10)? 90000 ' docs observed. Time used: ' 5609 'ms'
I20150225-12:21:26.763(10)? 95000 ' docs observed. Time used: ' 60558 'ms'
I20150225-12:25:48.249(10)? 100000 ' docs observed. Time used: ' 261484 'ms'
I20150225-12:26:02.249(10)? 105000 ' docs observed. Time used: ' 13998 'ms'
I20150225-12:27:24.866(10)? 110000 ' docs observed. Time used: ' 82614 'ms'
I20150225-12:27:31.750(10)? 115000 ' docs observed. Time used: ' 6883 'ms'
I20150225-12:27:38.777(10)? 120000 ' docs observed. Time used: ' 7025 'ms'
I20150225-12:27:46.244(10)? 125000 ' docs observed. Time used: ' 7467 'ms'

Observe results running [with 'batchSize:50000'](https://github.com/mikowals/meteor/commit/299ee9137bee0547886e849b8d704f8644b3b628):
> I20150225-12:18:20.794(10)? 90000 ' docs observed. Time used: ' 6151 'ms'
I20150225-12:18:27.082(10)? 95000 ' docs observed. Time used: ' 6360 'ms'
I20150225-12:18:33.732(10)? 100000 ' docs observed. Time used: ' 6649 'ms'
I20150225-12:18:41.191(10)? 105000 ' docs observed. Time used: ' 7459 'ms'
I20150225-12:18:49.079(10)? 110000 ' docs observed. Time used: ' 7888 'ms'
I20150225-12:18:56.981(10)? 115000 ' docs observed. Time used: ' 7902 'ms'
I20150225-12:19:04.734(10)? 120000 ' docs observed. Time used: ' 7753 'ms'
I20150225-12:19:12.505(10)? 125000 ' docs observed. Time used: ' 7770 'ms'

**Comment by glasser** [comment] 2015-03-28 16:48
(Not reopening since this is tracked in #3819.)

**Comment by hwillson** [comment] 2017-01-24 14:02
Reading over this issue and all referenced issues / PR's, it sounds like the best solution to this problem is to let people override a cursor's [`batchSize`](https://docs.mongodb.com/manual/reference/method/cursor.batchSize/). PR #3819 attempted this, but it included setting a default `batchSize` of 50,000 when a `batchSize` isn't  provided, which might not be the best option in some cases. To move this forward we should consider allowing the `batchSize` to be overridden, but keep the default behaviour as it is now, to reduce surprises for existing users. Comment https://github.com/meteor/meteor/pull/3819#issuecomment-77042526 alludes to this as well:

> So there are two things here — letting people override the batch size (which definitely seems like a good idea) and making a choice about what the best default is. I think the default currently is 1000, so this is 50x increase, which is a lot!

**Comment by macrozone** [comment] 2017-06-07 15:05
also struggling with this. 

I love cursor.observe for its simple and intuitive approach, but it does not scale well with large sets of data.

**Comment by hwillson** [comment] 2017-06-14 12:15
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=performance%20issue%20with%20collections%20observe&body=Migrated%20from:%20meteor/meteor%233804) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-14 12:15 UTC
Labels: confirmed, feature, Project:Livequery, Project:Server Performance, pull-requests-encouraged
