### ISSUE TITLE
1.4.3.1 default exports can't contain a variable named "exports"

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#8382] opened 2017-02-16 09:33 UTC
altough anonymous exports should be fixed in  1.4.3.1 I still found one that did not work.

in server folder:

```
// publications/index.js
import users from './users';
import pages from './pages';

export default function () {
  // ...
  users();
  pages();
}


// methods/index.js

import usermethods from './usermethods';
import pagesmethods from './pagesmethods';

export default function() {
 
  usermethods();
  pagesmethods();
}


```

in server/main.js:

```

import methods from './methods/index';
import publications from './publications/index';

publications(); // works!
methods(); // TypeError: methods is not a function

```

If I add a name to methods however, this works!

```
// methods/index.js

import usermethods from './usermethods';
import pagesmethods from './pagesmethods';

export default function methods() {
 
  usermethods();
  pagesmethods();
}

```

I don't need to add a name to publications however... Very strange. I don't know why it works in one case and not in the other. Any ideas?

**Comment by macrozone** [comment] 2017-02-16 15:50
I have faced another situation where a default export would just return a `{__esModule: true}`

```
// actions.js
import config from './config';
import admin from './admin';
import exports from './exports';

export default {
  config,
  admin,
  exports,
};

//other file
import actions from './actions'

// actions is {__esModule: true}  !

```

**Comment by klaussner** [comment] 2017-02-17 14:32
I can't reproduce either of the two cases. Do you have a Git repo that shows the problem?

**Comment by macrozone** [comment] 2017-02-17 15:56
I know its hard to reproduce. They are bigger customer projects and I can't show the git repo.

In both cases, " {__esModule: true}" is importet instead of the actual object. Under which conditions can this happen?

**Comment by abernix** [comment] 2017-02-20 15:13
To my knowledge, `exports.__esModule` is a property added by parsers to signify that an import is a ECMAScript module.  For example, if you use the Babel REPL, you'll see that it's added to the transpiled code [like this](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&experimental=false&loose=false&spec=false&code=export%20default%20function%20()%20%7B%0A%20%20%0A%7D&playground=true).

While the Babel transpiler uses it to mark it, I believe the `babel-runtime` is actually where this property would be detected and acted upon.

Your issue seems like it could be a bug, or it could be a misconfiguration (bad version of `babel-runtime` installed, for example?).  A reproduction would be quite helpful!

**Comment by macrozone** [comment] 2017-02-20 15:16
which version of babel-runtime should be installed? 

I can try to setup a reproduction, but It can take a while. It happens only with two files out of roughly 100 where it works.

**Comment by abernix** [comment] 2017-02-20 15:19
The last I've tested was `babel-runtime@6.22.x`, although I know `6.23.0` was released last week.  I have not tested it yet.

**Comment by macrozone** [comment] 2017-02-21 10:06
@abernix babel-runtime 6.23 did not help, but I found at least one bug that should be reproducable:



```

// actions/index.js
import config from './config';
import admin from './admin';
import exports from './exports'; // this somewhat shadows a already defined "exports" property

export default {
  config,
  admin,
  exports, 
};

//other file
import actions from './actions'

// actions is {__esModule: true}  !

```

workaround: do use property "exports" in default export:


```

// actions/index.js
import config from './config';
import admin from './admin';
import exportActions from './exports'; // this works now!

export default {
  config,
  admin,
  exportActions, 
};

//other file
import actions from './actions'

// actions is {__esModule: true}  !

```

**Comment by macrozone** [comment] 2017-02-21 16:25
also this comment mentions a similar problem with variables named "module":

https://github.com/meteor/meteor/pull/8327#issuecomment-280887113

**Comment by zvictor** [comment] 2017-02-27 18:18
@macrozone I suspect it is an issue introduced by `ecmascript@0.6.2`.

Would it be possible for you to downgrade your application to use `METEOR@1.4.2.5` and then compare the behaviour using `ecmascript@0.6.2` and `ecmascript@0.6.1` ?

**Comment by abernix** [comment] 2017-02-27 18:53
The prognosis here is probably correct but I'd recommend using Meteor 1.4.2.7 over Meteor 1.4.2.5 due to the [critical bug](https://github.com/meteor/meteor/issues/8325) that was fixed in [Meteor 1.4.2.6](https://github.com/meteor/meteor/blob/devel/History.md#v1426-2017-02-08).  You will, however, need to explicitly pin `ecmascript@=0.6.1` in your `.meteor/packages` file.

@macrozone Thanks for reporting these, but could you please make a reproduction of your problem(s) per the instructions for [opening an issue](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) and try to keep this to one distinct problem per issue?  It will truly make the debugging and tracking of the issues more manageable and easier to delegate/analyze.  The title of this issue doesn't even seem to match the original post now. 😕

**Comment by abernix** [comment] 2017-02-28 12:14
It's probably worth pointing out the `exports` identifier has special meaning, [at least in Node](https://nodejs.org/api/modules.html#modules_exports_shortcut), even if it's not explicitly listed in [ECMAScript `ReservedWord` grammar](https://www.ecma-international.org/ecma-262/5.1/#sec-7.6.1).

**Comment by hwillson** [comment] 2017-06-02 19:42
Hi @macrozone - any luck with creating a reproduction for this issue? Since it has been a while, I'll close this issue for now, but I'm happy to re-open it if you're able to provide a runnable repro demonstrating the problem. Thanks!

**Closed by hwillson** 2017-06-02 19:42 UTC
