### ISSUE TITLE
[1.6] Application Boot Fails [TypeError: Cannot read property '_' of undefined]

### ISSUE THREAD

**Issue by chasemaier** [meteor/meteor#9319] opened 2017-11-07 19:12 UTC
**Meteor Version:** 1.6, app worked previous on most recent release of 1.5
**OS:** Ubuntu 14.04

```
clydesdale => Started proxy.
...
clydesdale W20171107-10:46:28.699(-8)? (STDERR) /home/cmaier/git/csats/apps/clydesdale/.meteor/local/build/programs/server/boot.js:467
clydesdale W20171107-10:46:28.699(-8)? (STDERR) }).run();
clydesdale W20171107-10:46:28.700(-8)? (STDERR)    [39m
clydesdale W20171107-10:46:28.700(-8)? (STDERR) 
clydesdale W20171107-10:46:28.700(-8)? (STDERR) TypeError: Cannot read property '_' of undefined
clydesdale W20171107-10:46:28.700(-8)? (STDERR)     at packages/logging.js:7:28
clydesdale W20171107-10:46:28.700(-8)? (STDERR)     at packages/logging.js:490:3
clydesdale W20171107-10:46:28.700(-8)? (STDERR)     at infos.forEach.info (/home/cmaier/git/csats/apps/clydesdale/.meteor/local/build/programs/server/boot.js:414:13)
clydesdale W20171107-10:46:28.701(-8)? (STDERR)     at Array.forEach (<anonymous>)
clydesdale W20171107-10:46:28.701(-8)? (STDERR)     at /home/cmaier/git/csats/apps/clydesdale/.meteor/local/build/programs/server/boot.js:413:9
clydesdale W20171107-10:46:28.701(-8)? (STDERR)     at /home/cmaier/git/csats/apps/clydesdale/.meteor/local/build/programs/server/boot.js:463:5
clydesdale W20171107-10:46:28.701(-8)? (STDERR)     at Function.run (/home/cmaier/git/csats/apps/clydesdale/.meteor/local/build/programs/server/profile.js:510:12)
clydesdale W20171107-10:46:28.701(-8)? (STDERR)     at /home/cmaier/git/csats/apps/clydesdale/.meteor/local/build/programs/server/boot.js:462:11
clydesdale => Exited with code: 1
clydesdale => Your application is crashing. Waiting for file change.
```

This seems like an issue with the registering of the `underscore` package? But `_` is imported and used in that boot script and seems to be available as it gets far enough to get to the inner loop where it crashes.

I'm not sure if this is related to https://github.com/meteor/meteor/issues/9276, but it seems different since that is specifically about meteor shell.

Seems like all of the stack-trace is just boot code, so not sure if there is anything I can change in my app code to address it. I've also tried different configurations of importing the `underscore` package into the apps/dependent packages/etc.. with no luck.

**Comment by hwillson** [comment] 2017-11-07 19:29
@chasemaier This problem is coming from the `logging` package. If you open up your apps `.meteor/local/build/programs/server/packages/logging.js` file and look at line 7, you'll see:

```js
var _ = Package.underscore._; 
```

That means you're getting the `Cannot read property '_' of undefined` error because Meteor can't find its internally used `underscore` package. It should be available, which leads me to believe something in your app is conflicting with Meteor's `underscore`, or your app is in a broken state. Have you tried running a `meteor reset`? (usual warning: will delete your local DB)

**Comment by chasemaier** [comment] 2017-11-07 19:41
I hadn't originally -- but I just tried a `meteor reset` and it seems to still have to loading problem. I do see the line in the generated `logging.js` that you are referring to which matches the position in the error trace.

When troubleshooting initially I did attempt both a `meteor npm install underscore` and `meteor add underscore` (neither of which I had explicitly previously). Even with those it seems to be running into this loading issues in the logging package.

**Comment by hwillson** [comment] 2017-11-07 19:43
Okay - do you see the following file in your app?

```
.meteor/local/build/programs/server/packages/underscore.js
```

**Comment by chasemaier** [comment] 2017-11-07 19:49
Yes, looks like it.

`98da6ed0734f40ad81449b5bf51946d2  /home/cmaier/git/csats/apps/clydesdale/.meteor/local/build/programs/server/packages/underscore.js`

A 1374 line file ending in

```js
...



(function(){

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
// packages/underscore/post.js                                                                           //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                         //
// This exports object was created in pre.js.  Now copy the `_` object from it
// into the package-scope variable `_`, which will get exported.
_ = exports._;

///////////////////////////////////////////////////////////////////////////////////////////////////////////

}).call(this);


/* Exports */
if (typeof Package === 'undefined') Package = {};
(function (pkg, symbols) {
  for (var s in symbols)
    (s in pkg) || (pkg[s] = symbols[s]);
})(Package.underscore = {}, {
  _: _
});

})();
```

**Comment by hwillson** [comment] 2017-11-07 19:57
Interesting - any chance you could share a runnable reproduction of this? Something is interfering with the `Package.underscore` property. If you're unable to put together a repro, then if you can share your `.meteor/packages` file that might help (but a repro would definitely be better!).

**Comment by chasemaier** [comment] 2017-11-08 00:00
Okay, I think I have a repro with a bare app (`meteor create --bare newapp2`) that only has public packages.

Use following packages file instead (still hoping to widdle down this list, will edit if i find a more limited set):
```
iron:router
d3js:d3
pfafman:nvd3
accounts-base@1.4.0
accounts-google@1.3.0
audit-argument-checks@1.0.7
alanning:roles
accounts-password@1.5.0
package-stats-opt-out@1.0.7
reactive-var@1.0.11
meteor-base@1.2.0
mobile-experience@1.0.5
mongo@1.3.0
blaze-html-templates@1.0.4
session@1.1.7
jquery@1.11.10
tracker@1.1.3
logging@1.1.19
reload@1.1.11
random@1.0.10
ejson@1.1.0
spacebars@1.0.12
check@1.2.5
accounts-ui@1.2.0
natestrauser:connection-banner
tmeasday:publish-counts
meteorhacks:kadira
standard-minifier-css@1.3.5
standard-minifier-js@2.2.0
oaf:moment-duration-format
shell-server@0.3.0
google-config-ui@1.0.0
nitrolabs:cdn
dynamic-import@0.2.0
```

# Run Results

```
cmaier@chase3510:~/git/csats/apps/newapp2$ meteor run
[[[[[ ~/git/csats/apps/newapp2 ]]]]]          

=> Started proxy.                             
                                              
Changes to your project's package version selections:
                                              
accounts-base                   added, version 1.4.0
accounts-google                 added, version 1.3.0
accounts-oauth                  added, version 1.1.15
accounts-password               added, version 1.5.0
accounts-ui                     added, version 1.2.0
accounts-ui-unstyled            added, version 1.3.0
alanning:roles                  added, version 1.2.16
audit-argument-checks           added, version 1.0.7
blaze                           added, version 2.3.2
blaze-html-templates            added, version 1.1.2
d3js:d3                         added, version 3.5.8
ddp-rate-limiter                added, version 1.0.7
email                           added, version 1.2.3
es5-shim                        removed from your project
google-config-ui                added, version 1.0.0
google-oauth                    added, version 1.2.4
iron:controller                 added, version 1.0.12
iron:core                       added, version 1.0.11
iron:dynamic-template           added, version 1.0.12
iron:layout                     added, version 1.0.12
iron:location                   added, version 1.0.11
iron:middleware-stack           added, version 1.1.0
iron:router                     added, version 1.1.2
iron:url                        added, version 1.1.0
jquery                          added, version 1.11.10
less                            added, version 2.7.11
localstorage                    added, version 1.2.0
meteorhacks:kadira              added, version 2.30.3
meteorhacks:meteorx             added, version 1.4.1
momentjs:moment                 added, version 2.9.0
mongo-livedata                  added, version 1.0.12
natestrauser:connection-banner  added, version 0.5.2
nitrolabs:cdn                   added, version 1.3.0
npm-bcrypt                      added, version 0.9.3
oaf:moment-duration-format      added, version 1.3.2
oauth                           added, version 1.2.0
oauth2                          added, version 1.2.0
observe-sequence                added, version 1.0.16
package-stats-opt-out           added, version 1.0.7
pfafman:nvd3                    added, version 1.7.1
rate-limit                      added, version 1.0.8
reactive-dict                   added, version 1.2.0
service-configuration           added, version 1.0.11
session                         added, version 1.1.7
sha                             added, version 1.0.9
spacebars                       added, version 1.0.15
srp                             added, version 1.0.10
static-html                     removed from your project
templating                      added, version 1.3.2
templating-compiler             added, version 1.3.3
templating-runtime              added, version 1.3.2
tmeasday:publish-counts         added, version 0.8.0
ui                              added, version 1.0.13

=> Started MongoDB.                           
W20171107-15:53:54.434(-8)? (STDERR) /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:467
W20171107-15:53:54.450(-8)? (STDERR) }).run();
W20171107-15:53:54.450(-8)? (STDERR)    ^
W20171107-15:53:54.450(-8)? (STDERR) 
W20171107-15:53:54.450(-8)? (STDERR) TypeError: Cannot read property '_' of undefined
W20171107-15:53:54.450(-8)? (STDERR)     at packages/logging.js:7:28
W20171107-15:53:54.450(-8)? (STDERR)     at packages/logging.js:490:3
W20171107-15:53:54.451(-8)? (STDERR)     at infos.forEach.info (/home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:414:13)
W20171107-15:53:54.451(-8)? (STDERR)     at Array.forEach (<anonymous>)
W20171107-15:53:54.451(-8)? (STDERR)     at /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:413:9
W20171107-15:53:54.451(-8)? (STDERR)     at /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:463:5
W20171107-15:53:54.451(-8)? (STDERR)     at Function.run (/home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/profile.js:510:12)
W20171107-15:53:54.451(-8)? (STDERR)     at /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:462:11
=> Exited with code: 1
W20171107-15:53:57.650(-8)? (STDERR) /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:467
W20171107-15:53:57.650(-8)? (STDERR) }).run();
W20171107-15:53:57.651(-8)? (STDERR)    ^
W20171107-15:53:57.651(-8)? (STDERR) 
W20171107-15:53:57.651(-8)? (STDERR) TypeError: Cannot read property '_' of undefined
W20171107-15:53:57.651(-8)? (STDERR)     at packages/logging.js:7:28
W20171107-15:53:57.651(-8)? (STDERR)     at packages/logging.js:490:3
W20171107-15:53:57.652(-8)? (STDERR)     at infos.forEach.info (/home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:414:13)
W20171107-15:53:57.652(-8)? (STDERR)     at Array.forEach (<anonymous>)
W20171107-15:53:57.652(-8)? (STDERR)     at /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:413:9
W20171107-15:53:57.652(-8)? (STDERR)     at /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:463:5
W20171107-15:53:57.652(-8)? (STDERR)     at Function.run (/home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/profile.js:510:12)
W20171107-15:53:57.652(-8)? (STDERR)     at /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:462:11
=> Exited with code: 1
W20171107-15:53:58.206(-8)? (STDERR) /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:467
W20171107-15:53:58.208(-8)? (STDERR) }).run();
W20171107-15:53:58.208(-8)? (STDERR)    ^
W20171107-15:53:58.208(-8)? (STDERR) 
W20171107-15:53:58.209(-8)? (STDERR) TypeError: Cannot read property '_' of undefined
W20171107-15:53:58.209(-8)? (STDERR)     at packages/logging.js:7:28
W20171107-15:53:58.209(-8)? (STDERR)     at packages/logging.js:490:3
W20171107-15:53:58.209(-8)? (STDERR)     at infos.forEach.info (/home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:414:13)
W20171107-15:53:58.209(-8)? (STDERR)     at Array.forEach (<anonymous>)
W20171107-15:53:58.209(-8)? (STDERR)     at /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:413:9
W20171107-15:53:58.209(-8)? (STDERR)     at /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:463:5
W20171107-15:53:58.210(-8)? (STDERR)     at Function.run (/home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/profile.js:510:12)
W20171107-15:53:58.210(-8)? (STDERR)     at /home/cmaier/git/csats/apps/newapp2/.meteor/local/build/programs/server/boot.js:462:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by pkumar-uk** [comment] 2017-11-08 04:31
I am also facing the same problem. I had moved to 1.6 couple of days back for testing and then today moved another copy of the same project to 1.6 and the problem started occuring. When I do the diff I notice that only difference with all packages upgraded is last week meteor@1.8.0 has become meteor@1.8.1 ....Not sure if it is causing problems. I notice some changes related to global package registry.

**Comment by rcurrier666** [comment] 2017-11-08 06:40
Just updated to the 64-bit Windows version via Chocolatey and am now having the same problem. App worked fine in 1.5.2.2 and 1.6 32-bit. Not necessarily related to 64-bit as I had to do a lot of fixups on file permissions and ACLs that Chocolatey seemed to have messed up (lots of EPERM errors).

**Comment by Herteby** [comment] 2017-11-08 13:55
I'm having a possibly related issue. In my app I've been using lodash as a global import, like this:
```
_ = require('lodash')
```
It's been working fine until now when I updated to 1.6.
The issue is only on the server side, on the client it works.
_ is also undefined in the Meteor shell

If do this:
```
lodash = require('lodash')
```
then "lodash" is available globally, including the shell. So it's specifically the _ variable which seems to be getting overwritten.

**Comment by Herteby** [comment] 2017-11-08 15:41
Hmm, I removed all the version constraints from my Meteor packages and ran meteor update, and now it works again.

**Comment by YannLeBihan** [comment] 2017-11-08 17:31
@Herteby, thanks a lot. Was scratching my head on the very same problem when I saw your last post. Deleting the package versions file and running `meteor update` brought things back to normal.

**Comment by AlexAlbala** [comment] 2017-11-08 18:21
Still have the same issue... I reset the project, removed versions file, removed version constraints on packages file and still got the issue with meteor 1.6

My versions file (updated) looks like:

accounts-base@1.4.0
accounts-facebook@1.3.0
accounts-google@1.3.0
accounts-oauth@1.1.15
accounts-password@1.5.0
allow-deny@1.1.0
autoupdate@1.3.12
babel-compiler@6.24.7
babel-runtime@1.1.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.3.0
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
check@1.2.5
ddp@1.4.0
ddp-client@2.2.0
ddp-common@1.3.0
ddp-rate-limiter@1.0.7
ddp-server@2.1.0
deps@1.0.12
diff-sequence@1.0.7
dynamic-import@0.2.0
ecmascript@0.9.0
ecmascript-runtime@0.5.0
ecmascript-runtime-client@0.5.0
ecmascript-runtime-server@0.5.0
ejson@1.1.0
email@1.2.3
facebook-oauth@1.4.0
geojson-utils@1.0.10
google-oauth@1.2.4
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.3.0
id-map@1.0.9
iron:controller@1.0.12
iron:core@1.0.11
iron:dynamic-template@1.0.12
iron:layout@1.0.12
iron:location@1.0.11
iron:middleware-stack@1.1.0
iron:router@1.1.2
iron:url@1.1.0
jquery@1.11.10
livedata@1.0.18
localstorage@1.2.0
logging@1.1.19
meteor@1.8.1
meteor-base@1.2.0
minimongo@1.4.0
modules@0.11.0
modules-runtime@0.9.0
mongo@1.3.0
mongo-dev-server@1.1.0
mongo-id@1.0.6
npm-bcrypt@0.9.3
npm-mongo@2.2.33
oauth@1.2.0
oauth2@1.2.0
observe-sequence@1.0.16
ordered-dict@1.0.9
promise@0.10.0
random@1.0.10
rate-limit@1.0.8
reactive-dict@1.2.0
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
service-configuration@1.0.11
sha@1.0.9
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
templating@1.3.2
templating-compiler@1.3.3
templating-runtime@1.3.2
templating-tools@1.1.2
tracker@1.1.3
ui@1.0.13
underscore@1.0.10
url@1.1.0
webapp@1.4.0
webapp-hashing@1.0.9

**Comment by AlexAlbala** [comment] 2017-11-08 18:21
Still have the same issue... I reset the project, removed versions file, removed version constraints on packages file and still got the issue with meteor 1.6

My versions file (updated) looks like:

accounts-base@1.4.0
accounts-facebook@1.3.0
accounts-google@1.3.0
accounts-oauth@1.1.15
accounts-password@1.5.0
allow-deny@1.1.0
autoupdate@1.3.12
babel-compiler@6.24.7
babel-runtime@1.1.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.3.0
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
check@1.2.5
ddp@1.4.0
ddp-client@2.2.0
ddp-common@1.3.0
ddp-rate-limiter@1.0.7
ddp-server@2.1.0
deps@1.0.12
diff-sequence@1.0.7
dynamic-import@0.2.0
ecmascript@0.9.0
ecmascript-runtime@0.5.0
ecmascript-runtime-client@0.5.0
ecmascript-runtime-server@0.5.0
ejson@1.1.0
email@1.2.3
facebook-oauth@1.4.0
geojson-utils@1.0.10
google-oauth@1.2.4
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.3.0
id-map@1.0.9
iron:controller@1.0.12
iron:core@1.0.11
iron:dynamic-template@1.0.12
iron:layout@1.0.12
iron:location@1.0.11
iron:middleware-stack@1.1.0
iron:router@1.1.2
iron:url@1.1.0
jquery@1.11.10
livedata@1.0.18
localstorage@1.2.0
logging@1.1.19
meteor@1.8.1
meteor-base@1.2.0
minimongo@1.4.0
modules@0.11.0
modules-runtime@0.9.0
mongo@1.3.0
mongo-dev-server@1.1.0
mongo-id@1.0.6
npm-bcrypt@0.9.3
npm-mongo@2.2.33
oauth@1.2.0
oauth2@1.2.0
observe-sequence@1.0.16
ordered-dict@1.0.9
promise@0.10.0
random@1.0.10
rate-limit@1.0.8
reactive-dict@1.2.0
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
service-configuration@1.0.11
sha@1.0.9
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
templating@1.3.2
templating-compiler@1.3.3
templating-runtime@1.3.2
templating-tools@1.1.2
tracker@1.1.3
ui@1.0.13
underscore@1.0.10
url@1.1.0
webapp@1.4.0
webapp-hashing@1.0.9

**Comment by mounderwood** [comment] 2017-11-09 04:15
Running `meteor remove iron:router` and adding it back with `meteor add iron:router` fixed this issue for me.

**Comment by rcurrier666** [comment] 2017-11-09 06:49
Removing and adding iron:router also fixed it for me. No idea why (and don't really care as long as I can get back to work!).

**Comment by AlexAlbala** [comment] 2017-11-09 08:17
Removing and adding iron:router also fixed it for me. WTF...

**Comment by Herteby** [comment] 2017-11-09 08:55
I think my previous solution was just a red herring. @hexsprite mentioned in my forum thread that Meteor Shell was the issue, and he had reported it in early alpha 1.6. That was indeed my problem. If I launch Meteor without the shell, it works perfectly. As soon as the shell connects, _ becomes undefined.

**Comment by YannLeBihan** [comment] 2017-11-09 09:31
Confirmed : my app just raised a bunch of exceptions as soon as I launched the shell.

**Comment by tcastelli** [comment] 2017-11-15 09:21
Having the same problem, in our case also related to the Random package

**Comment by zeroonedev** [comment] 2017-11-21 02:54
Same issue here - upgrading from 1.5 to 1.6 and related to the meteor Random package

```
TypeError: Cannot read property '_' of undefined
W20171121-13:51:04.553(11)? (STDERR)     at /Users/../Documents/meteor_app/.meteor/local/build/programs/server/packages/random.js:7:28
```

**Comment by lynchem** [comment] 2017-11-22 15:21
We were having the Random issue too but were able to solve this by just doing 
`meteor remove underscore `
We don't actually use underscore anywhere but it's still a dependency of other packages so it's still in the versions file, but just removing it like this did the trick. If you need to use underscore apparently it works via npm (although we haven't tried that).

**Comment by pkumar-uk** [comment] 2017-11-22 17:29
doing 'meteor update' again made the problem disappear. Latest update seems to solve it. I noticed the meteor.js shows that it has moved from 1.8.1 to 1.8.2.

**Comment by lynchem** [comment] 2017-11-23 10:51
I can't say with certainty if the 1.8.1 -> 1.8.2 made any difference but we just tried to update another machine which was still on 1.5 and without removing underscore it still gave the same problem. It might be that the combination of both is needed.

**Comment by hwillson** [comment] 2017-11-23 12:49
Hi all - a proper fix for this has been completed in PR https://github.com/meteor/meteor/pull/9406. It will be merged soon. Thanks!

**Comment by hwillson** [comment] 2017-12-04 15:01
https://github.com/meteor/meteor/pull/9406 has been merged. Run `meteor update` or `meteor update shell-server` to get the fix. Thanks all!

**Closed by hwillson** 2017-12-04 15:01 UTC
Labels: Project:Isobuild, Project:Tool
