### ISSUE TITLE
Node fatal error: archived threads in combination with wasm not supported

### ISSUE THREAD

**Issue by doronrk** [meteor/meteor#11143] opened 2020-08-18 04:16 UTC
### This bug report should include:
I'm on version 1.10.1 and encountering the following issue locally after installing npm package `dd-trace` from Datadog and adding some traces:

```
W20200817-21:10:33.469(-7)? (STDERR) #
W20200817-21:10:33.469(-7)? (STDERR) # Fatal error in , line 0
W20200817-21:10:33.469(-7)? (STDERR) # archived threads in combination with wasm not supported
W20200817-21:10:33.470(-7)? (STDERR) #
W20200817-21:10:33.470(-7)? (STDERR) #
W20200817-21:10:33.470(-7)? (STDERR) #
W20200817-21:10:33.470(-7)? (STDERR) #FailureMessage Object: 0x7ffeefbefaa0
W20200817-21:10:33.470(-7)? (STDERR)  1: 0x1000d5de6 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.470(-7)? (STDERR)  2: 0x100d9f07f V8_Fatal(char const*, ...) [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.470(-7)? (STDERR)  3: 0x10072b042 v8::internal::wasm::(anonymous namespace)::CheckNoArchivedThreads(v8::internal::Isolate*)::ArchivedThreadsVisitor::VisitThread(v8::internal::Isolate*, v8::internal::ThreadLocalTop*) [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.471(-7)? (STDERR)  4: 0x1002cda53 v8::internal::ThreadManager::IterateArchivedThreads(v8::internal::ThreadVisitor*) [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.471(-7)? (STDERR)  5: 0x10072c1a4 v8::internal::wasm::(anonymous namespace)::WasmGCForegroundTask::RunInternal() [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.471(-7)? (STDERR)  6: 0x1000d4d6a node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.472(-7)? (STDERR)  7: 0x1000d42b7 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.472(-7)? (STDERR)  8: 0x1008ba8a9 uv__async_io [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.472(-7)? (STDERR)  9: 0x1008cb77f uv__io_poll [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.473(-7)? (STDERR) 10: 0x1008bad36 uv_run [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.473(-7)? (STDERR) 11: 0x1000b66fa node::NodeMainInstance::Run() [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.473(-7)? (STDERR) 12: 0x10005dc1f node::Start(int, char**) [/Users/doronroberts-kedes/.meteor/packages/meteor-tool/.1.10.1.1jki0ya.knhs++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node]
W20200817-21:10:33.473(-7)? (STDERR) 13: 0x7fff6fd5ccc9 start [/usr/lib/system/libdyld.dylib]
W20200817-21:10:33.474(-7)? (STDERR) 14: 0x2
=> Exited from signal: SIGILL
```

I saw https://github.com/meteor/meteor/commit/c37bab64a4750eafbc6483ee82f67e6ff6221029 which references https://github.com/nodejs/node/issues/29767 that seems to describe the same issue. Based on this, I've tried running with:

SERVER_NODE_OPTIONS=--no-wasm-code-gc (and SERVER_NODE_OPTIONS="--no-wasm-code-gc" just in case)

as a shot-in-the-dark, but to no avail.

I'm running OS X on my laptop.

repro:
`meteor npm i dd-trace` and add some traces

I'd love to get a high-level explanation of what is happening here and whether this is an issue I can expect to only happen in development mode, or whether I should hold off on deploying code like this to production as well. Thanks!

**Comment by namenotrequired** [comment] 2020-08-20 12:16
Sorry I cannot help with the issue itself, but about `SERVER_NODE_OPTIONS`, as far as I can tell from the [History](https://github.com/meteor/meteor/blob/devel/History.md#changes-2), it was only added in Meteor 1.10.2, maybe you can test your shot in the dark with that version?

Or with 1.11, as it looks like that would get you that option by default

**Comment by wvanooijen92** [comment] 2020-09-29 09:14
I am running into a similar issue. I want to use [blake3](https://github.com/connor4312/blake3) to generate content hashes for files. 

For now we have decided to

**Comment by opyh** [comment] 2020-10-26 21:58
https://github.com/meteor/meteor/issues/9568 appears to describe the same issue.

I might be wrong, but I'm afraid if we don't make fibers + WASM+GC compatible before more node modules adopt WASM+GC, this is going to be a showstopper for Meteor as we won't be able to use these modules without OOM crashes (or modules that use these modules).

**Comment by RaitoBezarius** [comment] 2020-11-28 00:50
> Sorry I cannot help with the issue itself, but about `SERVER_NODE_OPTIONS`, as far as I can tell from the [History](https://github.com/meteor/meteor/blob/devel/History.md#changes-2), it was only added in Meteor 1.10.2, maybe you can test your shot in the dark with that version?
> 
> Or with 1.11, as it looks like that would get you that option by default

I tried the option on 1.10.2 without any luck, alas.

**Comment by myoneflag** [comment] 2020-12-02 15:03
I have got an issue with METEOR@1.12-beta.3.
`archived threads in combination with wasm not supported`
![image](https://user-images.githubusercontent.com/47198076/100889471-d745b600-34bf-11eb-96db-58968e611c6d.png)
Same as with METEOR@2.0-beta.4 
Any luck?
Let me know the available latest version

**Comment by jhoxray** [comment] 2020-12-06 21:07
Running into the same issue with fresh install on nixos:

Loading isopacket `combined`              -

#
# Fatal error in , line 0
# archived threads in combination with wasm not supported
#
#
#
#FailureMessage Object: 0x7fc7acb9fb80
 1: 0xa5c711  [/nix/store/adcnybnz2kb01knzk7w70pjv33ljqnhn-meteor-1.10.2/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 2: 0x19b4ac5 V8_Fatal(char const*, ...) [/nix/store/adcnybnz2kb01knzk7w70pjv33ljqnhn-meteor-1.10.2/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 3: 0x11403a0  [/nix/store/adcnybnz2kb01knzk7w70pjv33ljqnhn-meteor-1.10.2/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 4: 0xcca16b v8::internal::ThreadManager::IterateArchivedThreads(v8::internal::ThreadVisitor*) [/nix/store/adcnybnz2kb01knzk7w70pjv33ljqnhn-meteor-1.10.2/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 5: 0x11479f2 v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC(v8::internal::Isolate*) [/nix/store/adcnybnz2kb01knzk7w70pjv33ljqnhn-meteor-1.10.2/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 6: 0xcc8883 v8::internal::StackGuard::HandleInterrupts() [/nix/store/adcnybnz2kb01knzk7w70pjv33ljqnhn-meteor-1.10.2/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 7: 0x1024376 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/nix/store/adcnybnz2kb01knzk7w70pjv33ljqnhn-meteor-1.10.2/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 8: 0x13a71b9  [/nix/store/adcnybnz2kb01knzk7w70pjv33ljqnhn-meteor-1.10.2/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
/run/current-system/sw/bin/meteor: line 10: 12333 Illegal instruction     (core dumped) /nix/store/adcnybnz2kb01knzk7w70pjv33ljqnhn-meteor-1.10.2/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node ${TOOL_NODE_FLAGS} /nix/store/adcnybnz2kb01knzk7w70pjv33ljqnhn-meteor-1.10.2/tools/index.js "$@"

**Comment by jhoxray** [comment] 2020-12-06 21:35
Would appreciate any insights into this, as it's messing with our production project :(

**Comment by filipenevola** [comment] 2020-12-09 20:32
Hi, could you provide a reproduction? 😉 Read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)

**Comment by opyh** [comment] 2021-01-04 14:58
Reproduction (using a different npm package, `blake3`):

```bash
git clone git@github.com:sozialhelden/meteor-fibers-gc-bug.git
cd meteor-fibers-gc-bug
meteor npm install
meteor
```

Trying to find more info how this could be fixed in node-fibers without having to get rid of fibers in Meteor in https://github.com/laverdet/node-fibers/issues/443#issuecomment-754021806 🤞

**Comment by opyh** [comment] 2021-01-06 09:35
https://github.com/laverdet/node-fibers/issues/443#issuecomment-755064211 looks like we need a Meteor rewrite with `async`/`await`? Phew 😬

**Comment by StorytellerCZ** [comment] 2021-04-22 20:37
Could also be related to #11246 
In case of `async`/`await` re-write that is long term-project.

**Comment by filipenevola** [comment] 2021-07-27 20:26
We are centralizing all the issues caused by Fibers [here](https://github.com/meteor/meteor/discussions/11505)

**Closed by filipenevola** 2021-07-27 20:26 UTC
Labels: needs-reproduction

**Comment by CyberCyclone** [comment] 2021-12-23 05:34
> #9568 appears to describe the same issue.
> 
> I might be wrong, but I'm afraid if we don't make fibers + WASM+GC compatible before more node modules adopt WASM+GC, this is going to be a showstopper for Meteor as we won't be able to use these modules without OOM crashes (or modules that use these modules).

I think you're right with this. I've been using Meteor for 5+ years but I'm now getting to the point where it's tight integration is becoming a burden and hard to use new technologies. Not having wasm support in Meteor has pretty much decided it for me.

**Comment by bmustata** [comment] 2022-03-14 10:28
In our case we have a issue with [@elastic/elasticsearch](https://www.npmjs.com/package/@elastic/elasticsearch) package.

**Comment by Subhadiptechnoexponent** [comment] 2022-03-31 12:22
same issue when i trying to import tatumio in my project, wasm is still not supported, i use meteor 2.6.1.

**Comment by SPodjasek** [comment] 2022-04-12 17:26
It seems that there's a similar issue in Meteor v2.7.2 when using `@elastic/elasticsearch@> 8.0` - which adds a package called `undici`, which uses wasm:

```console
$ meteor npm list undici
meteor@2.1.0-3
└─┬ @elastic/elasticsearch@8.1.0
  └─┬ @elastic/transport@8.0.2
    └── undici@4.16.0 
```

**Comment by bmustata** [comment] 2022-04-18 06:52
Why is the closed?

**Comment by CyberCyclone** [comment] 2022-04-18 07:04
> Why is the closed? 

Even if it was open, this issue has been around for a long time so they don't think it's worth fixing. This very issue forced me to find another framework and I've since moved on to using Next.js.

**Comment by bmustata** [comment] 2022-04-18 16:09
I agree but also lots of commercial and personal projects will have this issue. Could a new ticket be opened?

**Comment by WilliamKelley** [comment] 2022-04-18 23:00
@CyberCyclone @bmustata The [closing comment](https://github.com/meteor/meteor/issues/11143#issuecomment-887811451) explains why it was closed and should not be reopened/duplicated. This issue is not the symptom of a bug; it is a consequence of Meteor's internal technology choice. The reliance on Fibers means that Meteor cannot currently support WASM. So this is a feature request, and the discussion thread linked by Felipe is the centralization of features and topics related to the removal of Fibers, which is in Meteor's immediate roadmap.

**Comment by skeetmtp** [comment] 2023-07-07 15:21
For Elasticsearch our workaround is
```
import { HttpConnection } from '@elastic/transport';
new Client({ node, Connection: HttpConnection, requestTimeout: 2000 }) 
```
SERVER_NODE_OPTIONS='--noexpose_wasm'

A bit a hack, but did the job

**Comment by samtremblo** [comment] 2023-12-19 14:35
I also bumped into this issue trying to implement Elasticsearch to meteor. Seems like  '@elastic/transport' is what breaks. 

> For Elasticsearch our workaround is
> 
> ```
> import { HttpConnection } from '@elastic/transport';
> new Client({ node, Connection: HttpConnection, requestTimeout: 2000 }) 
> ```
> 
> SERVER_NODE_OPTIONS='--noexpose_wasm'
> 
> A bit a hack, but did the job

I tried this but it would completely refuse to work when built. 
After many builds and headaches the answer was to remove ES from my codebase and use axios instead. 

Request using ES
```
const client = new ESClient({ node:HOST, Connection: HttpConnection, requestTimeout: 2000 }) 

 doSearch () {
    return client.search(this.searchQuery.query).then(this.cleanResponse);
  }

```
Request using Axios
``` 
 doSearch() {
    const url = `${HOST}/${this.searchQuery.query.index}/_search`;
    return axios
      .post(url, this.searchQuery.query.body)
      .then((response) => this.cleanResponse(response.data))
      .catch((error) => {
        console.error('Search error:', error.message);
        throw error;
      });
  }

```
