### ISSUE TITLE
Publish Meteor developer account server side

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4577] opened 2015-06-17 04:59 UTC
I would like to offer in my own app a system similar to Meteor developer accounts. So be an auth provider through an app.

Could you release the source code to make that work?

**Comment by glasser** [comment] 2015-06-23 20:50
I don't think we have any plans at the moment to open source the Meteor developer accounts server, including its OAuth support.

**Comment by Lesp1ker** [comment] 2015-09-22 13:01
https://github.com/meteor/meteor/blob/devel/tools/meteor-services/auth.js it not it?

**Comment by mitar** [comment] 2015-09-22 21:50
No, this is just an OAuth client code for Meteor services.

**Comment by Lesp1ker** [comment] 2015-09-23 06:03
mitar, you couldn't realize oauth provider? (too it is necessary for me) sorry for bad english

**Comment by Type1J** [comment] 2016-01-04 18:12
I might have just opened a duplicate of this issue: #5930. Please read, and see if you're requesting something similar.

**Comment by Type1J** [comment] 2016-01-04 18:26
Would this help you? https://atmospherejs.com/rocketchat/oauth2-server

**Comment by mitar** [comment] 2016-01-04 18:28
This was literally just released. :-)

**Comment by hwillson** [comment] 2017-08-15 19:45
As mentioned in https://github.com/meteor/meteor/issues/4577#issuecomment-114638579, there are no plans to open source the Meteor developer accounts server code. Closing for now - thanks!

**Closed by hwillson** 2017-08-15 19:45 UTC
Labels: Project:Developer Accounts
