### ISSUE TITLE
Strange behaviors when manipulating large DOM set

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#3978] opened 2015-03-20 13:39 UTC
Tested under Windows and MacOS.

The issue is **best viewed with Chrome**.
### Code

Here is the repo: https://github.com/steph643/meteor-issue-3978

Consider the following code, where `MyCollection` contains **1000 numbers**, each number being displayed on the screen:

``` html
<head>
</head>

<body>
    <h2>Strange behaviors when manipulating large DOM set</h2>
    <p>
        <button id="addDocs">Add Docs</button>
        <button id="changeDocs">Change Docs</button>
        <button id="removeDocs">Remove Docs</button>
    </p>
    <p>myCollection:</p>
    <p>{{#each getValues}}{{value}}, {{/each}}</p>
</body>
```

``` javascript

MyCollection = new Meteor.Collection('myCollection');

if (Meteor.isServer) {

    MyCollection.remove({});

    Meteor.methods({
        addDocs:    function() { for (var i=0; i<1000; ++i) MyCollection.insert({ value: i }); },
        changeDocs: function() { MyCollection.update({}, { $inc: { value: 1 } }, { multi: true }); },
        removeDocs: function() { MyCollection.remove({}); }
    });
}

if (Meteor.isClient) {

    Template.body.helpers({
        getValues: function() { return MyCollection.find(); }
    });

    Template.body.events({
        'click #addDocs':    function(event, template) { Meteor.call('addDocs');    },
        'click #changeDocs': function(event, template) { Meteor.call('changeDocs'); },
        'click #removeDocs': function(event, template) { Meteor.call('removeDocs');  }
    });

    MyCollection.find().observeChanges({
        added:   function(id, doc)    { console.log('Added');   },
        changed: function(id, fields) { console.log('Changed'); },
        removed: function(id)         { console.log('Removed'); }
    });
}
```
### Normal Behavior

The collection is initially empty.
1. Press the "Add Docs" button -> the collection is populated with 1000 numbers, numbers are displayed on the screen and the console shows `1000 Added`
2. Press the "Change Docs" button -> each number is incremented, numbers are updated on the screen and the console shows `1000 Changed`

So the final console log is:

```
1000 Added
1000 Changed
```
### Strange Behavior 1

**In the above code, replace 1000 by 10000** and relaunch the application.

The collection is initially empty.
1. Press the "Add Docs" button -> the collection is populated with 10000 numbers, numbers are displayed on the screen and the console shows `10000 Added` (this takes about 50s on my machine)
2. Press the "Change Docs" button -> each number is incremented, numbers are updated on the screen and the console start showing the `Changed` message. **However**,  after 5862 changes (40s), the collection is suddenly emptied then reloaded again (total time: 1m). Final console log is:

```
10000 Added
5862   Changed
XHR finished loading: GET "http://localhost:3000/sockjs/info?cb=l5i9giallb".
10000 Removed
10000 Added
```
### Strange Behavior 2

**In the above code, replace 1000 by 20000** and relaunch the application.
1. Press the "Add Docs" button -> the collection is populated with 20000 numbers, numbers are displayed on the screen and the console shows `20000 Added`. **But then** the collection seems to be emptied then reloaded again. The final console log is:

```
20000 Added
sockjs-0.3.4.js:854 XHR finished loading: GET "http://localhost:3000/sockjs/info?cb=u4af1j9kbh".
20000 Removed
20000 Added
```

**Comment by steph643** [comment] 2015-03-20 13:58
Here is the repo: https://github.com/steph643/meteor-issue-3978

**Comment by steph643** [comment] 2015-03-20 14:00
Might be related to issue https://github.com/meteor/meteor/issues/3979
Might be related to issue https://github.com/meteor/meteor/issues/3976

**Comment by steph643** [comment] 2015-03-20 14:49
The issue remains if you remove `{{value}}` from the html, but not if you remove the `{{#each getValues}}` loop.

**Comment by dgreensp** [comment] 2015-03-31 22:46
Quoting sections of what I wrote in #3979:

>Just to get this out of the way up front:  Our overall performance definitely needs some work when it comes to receiving data over the network, storing it in Minimongo, pulling it out, and rendering it via Blaze.
>
>For anyone playing around with this, one thing to note is that `console.log` is fairly slow, and in cases like this can dominate the running time (even though the console nicely abbreviates the tens of thousands of messages).  Browser layout time also starts to become significant at the scale of tens of thousands of nodes, but I believe it is dwarfed by Blaze CPU in this case.
>
> I'm untagging this as Blaze and retagging as DDP since this is almost certainly some kind of race condition that occurs when Blaze is hogging the CPU.

Since I'm focusing on Blaze bugs right now, I tried reproducing this with a LocalCollection (no server involvement) and everything worked fine, so I'm declaring it not a Blaze bug.

**Comment by hwillson** [comment] 2017-07-31 17:22
I've tried the linked to repro (after updating it to Meteor 1.5.1), and can't seem to re-create the outlined issue. Adding / updating / removing docs seems to work properly:

![screenshot 2017-07-31 13 19 59](https://user-images.githubusercontent.com/137740/28789359-1d0c971a-75f3-11e7-884d-47bc0a7f8911.png)

I'll close this issue for now, but please post back and let me know if you're still seeing this issue, along with any additional steps needed to re-create it. Thanks!

**Closed by hwillson** 2017-07-31 17:22 UTC
Labels: Project:DDP
