### ISSUE TITLE
[1.4.2-beta.6+] After update, "Cannot find module" error

### ISSUE THREAD

**Issue by HatemJerbi** [meteor/meteor#7833] opened 2016-09-28 01:27 UTC
After updating my project to use 1.4.2-beta.6 + meteor reset + meteor run :

=> Started proxy.
=> Started MongoDB.
W20160928-02:20:17.916(1)? (STDERR) /Users/MacBook/Adonis/Redlean.Proto/.meteor/local/build/programs/server/boot.js:333
W20160928-02:20:17.974(1)? (STDERR) }).run();
W20160928-02:20:17.975(1)? (STDERR)    ^
W20160928-02:20:17.975(1)? (STDERR)
W20160928-02:20:17.975(1)? (STDERR) Error: Cannot find module '../core-js/symbol/iterator'
W20160928-02:20:17.975(1)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:85:1)
W20160928-02:20:17.976(1)? (STDERR)     at meteorInstall.node_modules.babel-runtime.helpers.typeof.js (node_modules/babel-runtime/helpers/typeof.js:5:1)
W20160928-02:20:17.976(1)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160928-02:20:17.976(1)? (STDERR)     at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160928-02:20:17.977(1)? (STDERR)     at Module.Mp.import (/Users/MacBook/.meteor/packages/modules/.0.7.6.1rr9fy6++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20160928-02:20:17.977(1)? (STDERR)     at meteorInstall.node_modules.meteor.webapp.webapp_server.js (/Users/MacBook/Adonis/Redlean.Proto/.meteor/local/build/programs/server/packages/webapp.js:33:26)
W20160928-02:20:17.977(1)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160928-02:20:17.977(1)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160928-02:20:17.978(1)? (STDERR)     at /Users/MacBook/Adonis/Redlean.Proto/.meteor/local/build/programs/server/packages/webapp.js:829:1
W20160928-02:20:17.978(1)? (STDERR)     at /Users/MacBook/Adonis/Redlean.Proto/.meteor/local/build/programs/server/packages/webapp.js:842:3
=> Exited with code: 1

**Comment by abernix** [comment] 2016-09-28 08:00
Can you provide the `devDependencies` and the `dependencies` from your `package.json`?  Also, did this problem exist for you in `1.4.2-beta.5`?

**Comment by HatemJerbi** [comment] 2016-09-28 11:29
I update from 1.4.1.1 .
package.json :
{
  "name": "Redlean.Proto",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "lint": "eslint ./packages --no-inline-config --ext .js",
    "lintfix": "npm run lint -- --fix",
    "lint": "eslint . --fix --no-inline-config"
  },
  "dependencies": {
    "meteor-node-stubs": "0.2.0",
    "react": "15.3.2",
    "react-dom": "15.3.2",
    "viewmodel-react": "0.7.6"
  },
  "devDependencies": {
    "babel-eslint": "6.1.0",
    "babel-plugin-transform-class-properties": "6.11.5",
    "babel-plugin-transform-object-rest-spread": "6.8.0",
    "eslint": "3.6.0",
    "eslint-plugin-jsx-a11y": "2.2.2",
    "eslint-plugin-react": "6.3.0",
    "viewmodel-react-plugin": "0.7.5"
  }
}

.babelrc :
{
  "presets": [
  	"latest", 
  	"react"
  ],
  
  "plugins": [ 
  	"babel-plugin-transform-class-properties",
  	"babel-plugin-transform-object-rest-spread",
  	"viewmodel-react-plugin" 
  ]
}

**Comment by HatemJerbi** [comment] 2016-09-28 11:52
Same problem with 1.4.2-beta.5 but ok with 1.4.2-beta.4

**Comment by abernix** [comment] 2016-09-28 12:58
Thanks for the details! This appears to be related to #7830 and possibly even #7815 which have started in recent beta releases.

**Comment by M4v3R** [comment] 2016-09-30 14:30
@benjamn I get the same error on a freshly cloned `meteor/todos` example repo with 1.4.2-beta.6.

**Comment by ishanbakshi** [comment] 2016-10-08 23:28
@benjamn  I get a similar issue in ubuntu 16.4 
`Error: Cannot find module '../core-js/symbol/iterator'
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:85:1)
    at meteorInstall.node_modules.babel-runtime.helpers.typeof.js (node_modules/babel-runtime/helpers/typeof.js:5:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at Module.Mp.import (~.../../.meteor/packages/modules/.0.7.7-beta.5.1cqvg24++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.node_modules.meteor.webapp.webapp_server.js (~.../../myapp/app/.meteor/local/build/programs/server/packages/webapp.js:33:26)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at ~.../../myapp/app/.meteor/local/build/programs/server/packages/webapp.js:829:1
    at ~.../../myapp//app/.meteor/local/build/programs/server/packages/webapp.js:842:3
Exited with code: 1`

**Comment by rhettlivingston** [comment] 2016-10-12 18:00
Still present on Ubuntu 16.04 in beta.9. Anyone found a workaround other than not using 1.4.2 betas?

**Comment by M4v3R** [comment] 2016-10-12 22:17
I've been trying to track this issue down, and from my little investigation it seems that Babel compiler in beta.6 and higher fails to produce complete JS bundles for the server. Just by comparing their size one can see that something's wrong:

```
todos - master! ❯ .meteor/local/build/programs/server/packages/modules.js | wc
     76558  106576 2169705
todos - master! ❯ .meteor-beta/local/build/programs/server/packages/modules.js | wc
     566    1523   22690
```

Comparing them further it turns out that for some reason compiler doesn't pull required dependencies.

Modules.js file in Meteor 1.4.1:

```
}],"typeof.js":["../core-js/symbol/iterator","../core-js/symbol",function(require,exports){

...

var _iterator = require("../core-js/symbol/iterator");

...

}]},"core-js":{"symbol":{"iterator.js":["core-js/library/fn/symbol/iterator",function(require,exports,module){

...
```

Modules.js file in Meteor 1.4.2-beta.9:

```
},"typeof.js":function(require,exports){

...

var _iterator = require("../core-js/symbol/iterator");

...

[../core-js/symbol/iterator doesn't get included]
```

**Comment by abernix** [comment] 2016-10-13 08:43
This is a duplicate of #7872 and probably #7830 and #7815 and discussed in #7668.

Closing in favor of #7872 which has a reproduction repo.

Thanks for opening this issue!

**Closed by abernix** 2016-10-13 08:43 UTC
Labels: bug

**Comment by benjamn** [comment] 2016-10-13 18:07
@M4v3R I think you may be onto something, but not building JS bundles on the server (for `node_modules` files) was an intentional decision: https://github.com/meteor/meteor/pull/7668/commits/03c5346873849151cecc3e00606c6e5aa13b3bbc

**Comment by tdesc** [comment] 2016-11-09 21:04
Solution for this remove node_modules folder and `meteor npm install`

**Comment by leosco** [comment] 2016-11-16 23:25
@tdesc I tried deleting and reinstalling all node_modules, and it didn't work, unfortunately. 
I'm getting the same issues as the rest of you :(

```
\.meteor\local\build\programs\server\boot.js:348
 }).run();
    ^

 Error: Cannot find module '../core-js/symbol/iterator'
     at require (packages\modules-runtime.js:109:19)
     at meteorInstall.node_modules.babel-runtime.helpers.typeof.js (packages\modules.js:1641:17)
```

Only happened once I updated to `Meteor 1.4.2.1`. Based on my research, something is going wrong with the Babel compiler, as @M4v3R pointed out.

**Comment by hwillson** [comment] 2016-11-17 10:55
@leosco It looks like your missing the `babel-runtime` npm package (see the [1.4.2.1 release notes](https://github.com/meteor/meteor/blob/devel/History.md#v1421)). Try:

```
meteor npm install --save babel-runtime
```

**Comment by leosco** [comment] 2016-11-17 18:37
@hwillson you're totally right. Jokes on me for not reading the release notes.

**Comment by derwaldgeist** [comment] 2017-07-16 22:31
Just stumbled upon this. Why isn't this mentioned in the Meteor 1.4 upgrade guide?

**Comment by hwillson** [comment] 2017-08-16 10:44
Thanks @derwaldgeist - it should be. I've opened https://github.com/meteor/guide/issues/657 to track this.

**Comment by derwaldgeist** [comment] 2017-08-16 14:29
Cool, thanks!

**Comment by chaitanyagiri** [comment] 2018-02-14 14:52
Quick update: In Meteor 1.6.1 update Babel has been updated from 6 to 7 hence consequence of the Babel 7 upgrade is that the babel-runtime npm package has been replaced by @babel/runtime, which can be installed by running
```
meteor npm install @babel/runtime
```
