### ISSUE TITLE
"meteor update" shows confirmation message even when it can't update

### ISSUE THREAD

**Issue by SachaG** [meteor/meteor#4040] opened 2015-03-27 00:51 UTC
While working on [this Telescope branch](https://github.com/TelescopeJS/Telescope/tree/meteor-update-bug), I ran `meteor update aldeed:autoform` to update the AutoForm package to `5.1.0`. 

I got the confirmation message, but then a few seconds later, the package version reset to the previous version, `5.0.3`.

Here's a screencast: http://recordit.co/4htGcVpcIT

It turns out I had pinned the version to `5.0.3` in `.meteor/packages`. So it makes sense that `meteor update` wouldn't work, but then I don't think it should show a confirmation message implying that it did?

**Comment by glasser** [comment] 2015-03-31 21:13
Are you running `meteor run` in another shell?  If so, this is a duplicate of #3582.  (And I wouldn't be surprised if it's fixed in 1.1.)

Note that `aldeed:autoforms@5.0.3` in `.meteor/packages` does NOT pin to 5.0.3: it specifies that the version should be compatible with 5.0.3, which means at least 5.0.3 but not 6.* or more.

**Closed by glasser** 2015-03-31 21:13 UTC
Labels: Project:Isobuild, Project:Tool

**Comment by SachaG** [comment] 2015-04-01 07:06
Yes, it sounds like it was the same issue. Hopefully it'll be fixed now :)
