### ISSUE TITLE
Meteor 1.4.2.1 bug with babel plugins

### ISSUE THREAD

**Issue by HatemJerbi** [meteor/meteor#8068] opened 2016-11-17 15:17 UTC
babel plugins added in .babelrc are not active When using package only architecture.

```
=> Started proxy.                             
=> Errors prevented startup:                  
   
   While processing files with ecmascript (for target web.browser):
   packages/framework:core/lib/client.js:5:4: /packages/framework:core/lib/client.js: Missing class properties transform.
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB.
```

[#repro](https://github.com/HatemJerbi/proto) 

- OS: MacOS Sierra 10.12.1

**Comment by benjamn** [comment] 2016-11-17 18:24
Both the `.babelrc` file and the `node_modules` directory have to be inside the package source root  directory to be found by the package. Otherwise it would be very easy for decisions about Babel compilation made by the app developer to interfere with the expectations of packages. And I've seen enough "bugs" due to stray `.babelrc` files within apps to know how confusing that would be.

You can make your reproduction work by symlinking the `.babelrc` file and `node_modules` directory:
```sh
cd proto/packages/framework-core
ln -s ../../.babelrc ./
ln -s ../../node_modules ./
```

Deliberately symlinking these files is an important signal of intent, and I don't want to undermine that signal by making it the default behavior.

**Comment by benjamn** [comment] 2016-11-17 18:30
Note that https://github.com/meteor/meteor/commit/1b855047aeb5d0df2439089799e5acb7a8bad691 just avoids unnecessary work by `InputFile#findControlFile`. The limitation to package source root directories was already enforced by `InputFile#resolve`.

**Comment by HatemJerbi** [comment] 2016-11-22 08:11
Hi @benjamn,
We must symlink in every package :-(. I think it will be great if package developper have the possibility to  inform the compiler to include the root .babelrc and node_modules, may be in package.js. With this solution decisions about Babel compilation made by the package developer dont interfere with the expectations of other packages.

**Comment by abernix** [comment] 2016-12-16 10:55
Closing for the reason listed above.  Happy to discuss further, but the implementation is working as intended right now.  Thanks for bringing up the conversation!

**Closed by abernix** 2016-12-16 10:55 UTC
