### ISSUE TITLE
Updating to meteor 1.5 causes a build error with ecmascript package.

### ISSUE THREAD

**Issue by michalczaplinski** [meteor/meteor#8800] opened 2017-06-14 10:48 UTC
**Meteor version**: 1.5, OS X

```
   While processing files with ecmascript (for target web.browser):
   /tools/isobuild/compiler-plugin.js:376:52: Cannot read property 'id' of null
   at InputFile.resolve (/tools/isobuild/compiler-plugin.js:376:52)
   at InputFile._require (/tools/isobuild/compiler-plugin.js:386:25)
   at InputFile.require (/tools/isobuild/compiler-plugin.js:380:17)
   at requireWithPrefix (packages/babel-compiler.js:428:32)
   at requireWithPath (packages/babel-compiler.js:357:14)
   at resolveHelper (packages/babel-compiler.js:330:22)
   at packages/babel-compiler.js:306:19
   at Array.forEach (native)
   at walkHelper (packages/babel-compiler.js:305:22)
   at walkBabelRC (packages/babel-compiler.js:295:7)
   at resolveHelper (packages/babel-compiler.js:333:11)
   at packages/babel-compiler.js:306:19
   at Array.forEach (native)
   at walkHelper (packages/babel-compiler.js:305:22)
   at walkBabelRC (packages/babel-compiler.js:295:7)
   at BabelCompiler.BCp._inferHelper (packages/babel-compiler.js:380:3)
   at BabelCompiler.BCp._inferFromPackageJson (packages/babel-compiler.js:268:17)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler.js:237:10)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:166:10)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:109:26)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:108:14)
```

**Comment by abernix** [comment] 2017-06-14 15:43
Aside from mentioning what version of Meteor you were on before and whether you have any special configurations (like `.babelrc`), could you please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple example as possible) and upload that project to GitHub?  Then, simply include the link to it and it will be easy for any developer to clone and see the same problem you're having and decide if it's a problem with your code, or a problem with Meteor itself.

Someone will be much more able to help you if you include this. Unfortunately, without providing a reproduction repository, it's very difficult to investigate.

**Comment by programmerneo** [comment] 2017-06-16 15:00
No idea why it happened, but looks like the .**babelrc** file is empty after the upgrade. Note this file must be valid JSON. To fix, either make it {}, or {
  "presets": ["meteor"]
}  ... meteor will load after that.

**Comment by hwillson** [comment] 2017-06-16 16:00
@programmerneo Are you suggesting that the originally reported issue here could be caused by having an empty `.babelrc`? If so, I believe this is a different issue. Taking a quick look behind the scenes, having an empty `.babelrc` would cause a different error (it would fail [here](https://github.com/meteor/meteor/blob/b010e205bcbfedbd91a27baab2b985d97482ef83/packages/babel-compiler/babel-compiler.js#L164)).

**Comment by s-devaney** [comment] 2017-07-03 19:41
I have the same issue on Windows

**Comment by s-devaney** [comment] 2017-07-04 18:59
For me, this issue was linked to #8801. I followed the advice in that issue and this is now resolved for me.

**Comment by adamwan92** [comment] 2017-08-11 10:28
I am having this exact same error

**Comment by hwillson** [comment] 2017-09-14 17:58
As mentioned in https://github.com/meteor/meteor/issues/8800#issuecomment-308472635, without additional debugging information (and ideally a reproduction - see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)), there isn't much we can do here. Closing for now - thanks!

**Closed by hwillson** 2017-09-14 17:58 UTC
Labels: can't-reproduce, Project:Isobuild
