### ISSUE TITLE
[cordova] Load issue - raix_cordova_plugins.js fail to load `<...`

### ISSUE THREAD

**Issue by raix** [meteor/meteor#3568] opened 2015-01-27 14:24 UTC
I'm not sure what's causing this issue, but setting `--production` solves the issue. This issue occurs on cordova mobile builds.

The `http://meteor.local/packages/raix_cordova_plugins.js` isnt available after hot code push:
![image](https://cloud.githubusercontent.com/assets/1136718/5919857/01d2899c-a638-11e4-9560-cf0bfa81d49a.png)

It seems as if `raix_cordova_plugins.js` isnt served when in dev mode - its unclear if this should be updated at all since its a plugin file?

Kind regards Morten

**Comment by Slava** [comment] 2015-01-27 22:47
@raix You would need to provide a reproduction for us to debug this. Also notice that `raix_cordova_plugins.js` is not a great name for a file in the first place since Apache Cordova is known to have a lot of bugs around recognizing special names like `cordova.js`, `cordova_plugins.js` and `plugins`.

**Comment by aldeed** [comment] 2015-01-30 01:07
@raix, the syntax error looks a little similar to my issue https://github.com/meteor/meteor/issues/3230

**Comment by raix** [comment] 2015-01-30 06:19
@aldeed true, its a similar response
@Slava I'll see if I can create a replication (but its a low priority) - this project is also under a big NDA

Regarding the naming, the plugin haven't a `cordova.plugins.js` (I've searched the build folder too for a `raix_cordova_plugins.js`) - If we aren't allowed that kind of naming we should prop. rename for the user or warn about it?

So I was thinking it was Meteor that wrapped the plugin js code into`raix_cordova_plugins.js` in the device server - but if what you are saying about naming that would be a problem?
```js
Package.describe({
  git: 'https://github.com/SpaceCapsule/Meteor-cordova.git',
  name: 'raix:cordova',
  version: '0.2.3',
  summary: 'Adds basic support for Cordova/Phonegap'
});

// Is the js from these wrapped on the mobile on device server as cordova_plugins.js?
Cordova.depends({
  'org.apache.cordova.dialogs': '0.2.10',
  'org.apache.cordova.vibration': '0.3.11'
});

Package.onUse(function (api) {
  api.versionsFrom('1.0');

  api.use('reactive-var', 'client');
  // The Meteor build solution
  api.addFiles('cordova.client.js', 'web.cordova');
  api.addFiles('cordova.client.notification.js', 'web.cordova');

  // The iFrame solution
  api.use('ejson', 'web.browser');
  api.addFiles('web.client.js', 'web.browser');
  api.addFiles('web.client.notification.js', 'web.browser');

  api.export('Cordova', 'client');
});

Package.onTest(function(api) {
    api.use('raix:cordova', ['client']);
    api.use('test-helpers', 'client');
    api.use(['tinytest', 'underscore', 'ejson', 'ordered-dict',
             'random', 'tracker']);

  api.addFiles([
    'plugin/meteor.cordova.js',
    'meteor.cordova.tests.js',
  ], 'client');
});
```

**Comment by Slava** [comment] 2015-02-11 18:08
I am closing this as a duplicate of #2920

**Closed by Slava** 2015-02-11 18:08 UTC
Labels: Project:Mobile
