### ISSUE TITLE
[1.3-beta2] issue. Many packages don´t found globals

### ISSUE THREAD

**Issue by bySabi** [meteor/meteor#5870] opened 2015-12-23 14:50 UTC
`sacha:spin` and other packages don´t found `module` global.
 
```
sacha_spin.js:43   Uncaught ReferenceError: module is not defined
```

**Comment by benjamn** [comment] 2015-12-24 16:24
Does the `package.js` file for `sacha:spin` have `api.use("modules")` or `api.use("ecmascript")` in its `Package.onUse` section?

**Comment by bySabi** [comment] 2015-12-24 16:29
no. https://github.com/SachaG/meteor-spin/blob/master/package.js

**Comment by trusktr** [comment] 2015-12-24 20:04
This happened to me too. If you open the console, things like `Meteor` or `_` aren't global any more.

There is a simple workaround: in your `main.js` file, before using the APIs of any other packages, export the globals you need to the `window`, f.e.:

```js
// client/main.js

window._ = _
```

The globals seems to be available to module code like your main.js file, but not to packages. After assigning to `window` the problem was fixed temporarily.

In the long run, I really do like the idea of symbols *not* being assigned to window, and kept private within the app's own scope. This is good for security, because imagine some external code (a browser plugin, or something else, etc) overriding underscore methods and then having access to your data that you pass to the modified underscore.

**Comment by trusktr** [comment] 2015-12-24 20:05
The package I had this problem with was [jparker:gravatar](https://atmospherejs.com/jparker/gravatar), which couldn't find `_` (underscore).

**Comment by osv** [comment] 2015-12-24 20:22
I think one day Meteor kill self if dev team continue "refactoring"

**Comment by bySabi** [comment] 2015-12-24 20:26
I create a `globals` package workaround.

package.js
```
Package.describe({
  version: '0.2.0',
});

Package.onUse(function(api) {
  api.use('modules');
  api.mainModule('main.js', 'client');

  api.export('module', 'client');
});
```
main.js
```
var global = this;
global.module = module;
```

lets will see how is work ...

**Comment by trusktr** [comment] 2015-12-24 20:31
@bySabi `global` might not be `window` in the module code. Did it work? If it is in strict mode, this won't work either:

```js
function putToGlobal() {
  var global = this; // this is undefined in strict mode
  global.module = module;
}

putToGlobal()
```

**Comment by trusktr** [comment] 2015-12-24 20:32
(I believe, if Meteor 1.3 is following ES2015 spec, then all ES2015 modules are always "strict mode".

**Comment by casperan** [comment] 2015-12-24 20:39
@osv the "refactoring" going on now, is really necessary and a natural part of the process. it is going on throughout the javascript community in a move towards standardisation thanks to the TC39 work on ES2015+.

Without this work, Meteor would be abandoned, and those who can't see it now, would eventually leave as well when those leading the community have left.

**Comment by bySabi** [comment] 2015-12-25 11:19
@trusktr it works both ways on packages ...
```
var global = this;
```
OR

```
var global = window;
```

But I´m afraid the problem is deep than that.
Now I have a new error:

```
ReferenceError: Spinner is not defined
```

on this `sacha:spin` package code ... 
```
Template.spinner.onRendered(function(){
  var options = _.extend({}, Meteor.Spinner.options, this.data);

  this.spinner = new Spinner(options);
  this.spinner.spin(this.firstNode);
}); 
```
A new global enter to scene and the `global.Spinner` trick not work this time.

**Comment by trusktr** [comment] 2015-12-26 02:45
This might be a duplicate of #5819.

**Comment by bySabi** [comment] 2015-12-26 09:13
yes it is. my mind spinning on 1.3 :-)

**Comment by trusktr** [comment] 2015-12-26 19:12
Possible duplicates: #5819 #5886

**Comment by avital** [comment] 2016-01-08 20:06
Should be fixed by https://github.com/meteor/meteor/commit/d542ffb1a96418b190d84999c5802a157dacea66 and will be out in `1.3-modules-beta.3` later today.

**Comment by avital** [comment] 2016-01-09 04:12
`1.3-modules-beta.3` was just released.

**Closed by avital** 2016-01-09 04:12 UTC
Labels: blocks-basic-module-use, known-fix

**Comment by trusktr** [comment] 2016-01-09 04:19
Sweeeeeeeeeeet.

**Comment by interfaith** [comment] 2016-05-17 16:02
so for webrtc the adapter.js file has globals such as var webrtcDetectedBrowser = null;
then how is this handled ? as now webrtcDetectedBrowser errors out as undefined.
