### ISSUE TITLE
Unable to run meteor on a different port (OS X)

### ISSUE THREAD

**Issue by sdarnell** [meteor/meteor#7676] opened 2016-08-19 22:42 UTC
On Mac OSX with Meteor 1.4.0.1 or 1.4.1 I'm unable to start meteor on a non-3000 port.
If I don't specify a port or specify --port 3000 everything is fine. But if I try, 3123, 3456, 6666 etc. it gets stuck at "Starting your app" (with negligible CPU usage).

With ps -ef I can see that there's one node process with --port 3456 as the last parameter, and a mongod process with --port 3457. But no joy...
I also tried adding an explicit app port (--app-port 4567).

I've tried --verbose and --raw-logs with no extra interesting indication.

**Comment by lieuwex** [comment] 2016-08-19 22:53
Duplicate of #7563?

**Comment by laosb** [comment] 2016-08-20 06:38
@sdarnell I guess that's at least related to #7563. If it's not, please reopen.

**Closed by laosb** 2016-08-20 06:38 UTC

**Comment by sdarnell** [comment] 2016-08-20 21:04
Yes it is a duplicate - sorry I didn't spot the previous one.
