### ISSUE TITLE
iOS 10 blocks websocket connections

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#7772] opened 2016-09-14 23:46 UTC
- [Update -- Fix](#update----fix)
  - [meteor v1.4](#meteor-v14)
    - [Wait](#wait)
    - [Immediate](#immediate)
  - [meteor < v1.4](#meteor--v14)
- [Problem](#problem)

# Update -- Fix

### Wait

You can wait until #7774 is merged and a new version of 

https://atmospherejs.com/meteor/boilerplate-generator

is published (currently at `1.0.9`), and then do:

```
$ meteor update boilerplate-generator
$ deploy
```

### Immediate

```
git clone git@github.com:gsaynac/meteor.git
cd meteor
git checkout cordova-csp-fix
cp -r packages/boilerplate-generator ~/myapp/packages/
cd ~/myapp
deploy
```

## meteor < v1.4

```
git clone git@github.com:gsaynac/meteor.git
cd meteor
git checkout cordova-csp-fix
cp -r packages/boilerplate-generator ~/myapp/packages/
cd ~/myapp
meteor
```

Now you'll get an error like this one:

```
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: No version of boilerplate-generator satisfies all constraints: @=1.0.9, @=1.0.8
   Constraints on package "boilerplate-generator":
   * boilerplate-generator@=1.0.9 <- top level
   * boilerplate-generator@=1.0.8 <- top level
```

This is when running meteor `v1.3.2.3`, but you may see a version on the bottom line other than `1.0.8`, in which case use that in this next step:

- edit `~/myapp/packages/boilerplate-generator/package.js`, changing `1.0.9` to `1.0.8` (or the version you see from above)
- rerun `meteor`, making sure there no longer is a startup error
- deploy

# Problem

It appears that WKWebView in iOS 10 no longer applies the Meteor Cordova CSP (`default-src *`) to websockets, and blocks the connection, with the below message. This breaks production apps that make websocket connections (perhaps only connections other than the default connection to the Meteor server? not sure) when their users update to iOS 10 (which has been released).

> Refused to connect to wss://my.domain.tld/sockjs/015/sdflkj/websocket because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.
> SecurityError (DOM Exception 18): The operation is insecure

I think this is the CSP that is currently used in Cordova apps:  

```
<meta http-equiv="Content-Security-Policy" content="default-src * data: blob: 'unsafe-inline' 'unsafe-eval';">
```
- https://github.com/meteor/meteor/blob/master/packages/boilerplate-generator/boilerplate_web.cordova.html#L7
- https://guide.meteor.com/mobile.html#csp

Replacing it in the generated html file in XCode with the below [worked for one person in the forums](https://forums.meteor.com/t/ios-10-compatibility/26065/33) (and it looks like for a couple people earlier in the thread as well):

```
<meta http-equiv="Content-Security-Policy" content="default-src * 'self' data: blob: 'unsafe-inline' 'unsafe-eval' wss://*.ourdomain.tld ">
```
(which has an added `wss://domain` at the end, and a `'self'`, if that matters)

If `wss://*` works, that would be nice, as it would match the default `browser-policy` CSP. 

> Add browser-policy to your app to enable a starter policy. With this starter policy, your app's client code will be able to load content (images, scripts, fonts, etc.) only from its own origin, except that XMLHttpRequests and WebSocket connections can go to any origin.
https://atmospherejs.com/meteor/browser-policy

@martijnwalraven

**Comment by crazybaud** [comment] 2016-09-15 08:14
Based on our [previous message](https://forums.meteor.com/t/ios-10-compatibility/26065/33?u=crazy) and our latest tests, the answer seems to add `ws:` and `wss:` "protocol". It works for us. We would send a PR in the following hours if it is ok for everyone.

In https://github.com/meteor/meteor/blob/master/packages/boilerplate-generator/boilerplate_web.cordova.html
From <meta http-equiv="Content-Security-Policy" content="default-src * data: blob: 'unsafe-inline' 'unsafe-eval';">
To <meta http-equiv="Content-Security-Policy" content="default-src * data: blob: 'unsafe-inline' 'unsafe-eval' ws: wss:;">

**Comment by mikeislearning** [comment] 2016-09-15 13:16
@crazybaud This doesn't seem to change any of the errors I'm getting.

I put the meta tag on both the client and the server, and it doesn't make a difference in most places.
iOS10 Safari seems to be fine. iOS10 Cordova cannot connect to the websockets and errors out.

**Comment by crazybaud** [comment] 2016-09-15 13:20
With iOS10 Cordova Safari console, do you have only one `<meta http-equiv="Content-Security-Policy" ...` in your `<head>` or more than one ?

**Comment by mikeislearning** [comment] 2016-09-15 13:20
Initially 2 printed out, but I went into Xcode before compiling to my device, and removed the second one.

**Comment by crazybaud** [comment] 2016-09-15 13:28
Ok so when you run your app, and look at the console, only one is present (not only before compiling).

(We can talk about it on https://gitter.im/meteor/meteor )

**Comment by mikeislearning** [comment] 2016-09-15 13:54
OK! So modifying the Staging/www to include this CSP fixed it for me.

**Comment by benjamn** [comment] 2016-09-15 21:25
If #7774 works, and you're using Meteor 1.4, this should be an easy fix: `meteor update boilerplate-generator` and then redeploy. Note: that won't work until we've merged #7774 and republished `boilerplate-generator`, so don't try it yet!

**Comment by lorensr** [comment] 2016-09-15 22:38
Thank goodness someone decoupled core packages from the release

**Comment by dgroch** [comment] 2016-09-16 01:32
We managed to get our app running by manually modifying the Content-Security-Policy declaration in the generated `head.html` file within X-code

![image](https://cloud.githubusercontent.com/assets/2666385/18572741/1eb3cdaa-7c01-11e6-81bb-2667e1950561.png)

Waiting for your PR to be merged @benjamn !!

**Closed** 2016-09-16 13:01 UTC
Labels: bug, confirmed, Impact:some, Project:Mobile, Severity:production

**Comment by benjamn** [comment] 2016-09-16 13:08
https://github.com/meteor/meteor/pull/7774#issuecomment-247596014

**Comment by lorensr** [comment] 2016-09-16 17:50
#7774 has been merged and published, thank you @crazybaud @gsaynac @benjamn. [See here](https://github.com/meteor/meteor/issues/7772#issue-177051862) for updating instructions

**Comment by lorensr** [comment] 2016-09-16 17:51
Ha, forgot that sometimes new comments don't appear on an old page. GH should just switch to Meteor.

**Comment by dgroch** [comment] 2016-09-18 23:22
We are running Meteor 1.4.1.1 and using `meteor update boilerplate-generator' didn't seem to work.
Looking at `.meteor/versions` it has bumped the version to `boilerplate-generator@1.0.10` but when running `meteor run ios-device` the app is building with the outdated CSP.

To get it running, I've had to clone the develop branch of meteor, and copy the package into my `app/packages` directory.

Any ideas?

**Comment by mirstan** [comment] 2016-09-18 23:26
Same, followed the instruction for <1.4, even tried upgrading to 1.4.1.1, but Staging/www/application/index.html still has:
`
<meta http-equiv="Content-Security-Policy" content="default-src * data: blob: 'unsafe-inline' 'unsafe-eval';">
`
Even a tried it with a fresh project. What am I missing?

**Comment by lorensr** [comment] 2016-09-19 00:39
Not sure, it should update on hot code push.

**Comment by cunneen** [comment] 2016-09-19 06:49
@lorensr does hot code push rely on a working DDP connection? :)

**Comment by laucheukhim** [comment] 2016-09-20 01:57
It turns out merely updating boilerplate-generator is not enough. This package is run during the build process and updating this package on a project level would not change what files are used to build the app. I have to update Meteor to a beta release to get this fixed.

```
meteor update --release 1.4.2-beta.4
```

**Comment by mitiaptest** [comment] 2016-09-20 10:01
Hello All,

Following is reproduction of meteor demo app in which I have added boilerplate-generatior still csp didn't seem to take effect.

https://github.com/mitiaptest/meteor-demo

Please let me know if anything missing from me?

Thanks,

**Comment by derwaldgeist** [comment] 2016-09-20 12:18
Does this affect Meteor 1.2 apps as well, and if so, is there a solution for this?

**Comment by cunneen** [comment] 2016-09-20 12:23
@derwaldgeist I'd expect it to affect Meteor 1.2 apps on iOS 10 (and any other cordova iOS 10 apps that use web sockets).

Try @lorensr 's  very first message in this thread, the section "meteor < v1.4".

**Comment by derwaldgeist** [comment] 2016-09-20 13:13
This seems to work, but is quite inconvenient :-/

Plus, I am getting the following error in the Safari debugger now:
```
Refused to load gap://ready because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy.
```

**Comment by derwaldgeist** [comment] 2016-09-20 23:29
I've tried the approach described for Meteor < 1.4 in Meteor 1.2, i.e. I downloaded the source code of the ```boilerplate-generator``` package, moved it to my packages folder, and added the CSP meta tag. But although the package code is executed (I inserted loggging), the CSP is not added to the index.html. Even the CSP already included in the 1.0.4 version of boilerplate-generator (the version used in Meteor 1.2) is not being added. Seems as if the boilerplate code comes from a different source. Any ideas why this happens?

**Comment by cunneen** [comment] 2016-09-21 01:29
Yes @derwaldgeist I spent some time looking into this yesterday; boilerplate-generator is bundled into the meteor build tool itself and not run from your app. So (as I and others above have found) that approach is not going to work until meteor itself is updated.

**Comment by cunneen** [comment] 2016-09-21 04:12
OK for those running meteor 1.4 (possibly others), I've created a little cordova plugin that overwrites the \<meta> tag. Don't get too excited, as it ***doesn't*** work with a ```meteor build``` command, but it ***does*** work with ```meteor run ios-device```. So it will help while you're developing, but you'll need to manually change the \<meta> tag when you do a ```meteor build```. 

To install it, just go:

```
meteor add cordova:meteor-ios10-csp-fix@0.1.0
```

The source repository is [here](https://github.com/AppWorkshop/meteor-ios10-csp-fix) , the npmjs page is [here](https://www.npmjs.com/package/meteor-ios10-csp-fix)

There's actually nothing meteor-specific about this, so it might work with ionic / cordova / telerik / phonegap etc apps that use web sockets on iOS10.

**Comment by danielbh** [comment] 2016-09-21 08:24
This fix seems to work for ios-device local but not with our Galaxy hosted remote server. In other words when we do ios-device --mobile-server subdomain.meteorapp.com. Any idea where I could be going wrong?

**Comment by cunneen** [comment] 2016-09-21 08:30
@danielbh that sounds like a ```meteor build``` command. See my notes above: ```meteor build ``` overwrites the (good) change made by my meteor-ios10-csp-fix cordova plugin with the (bad) one bundled with the meteor build tool. Unfortunately there's nothing you can do to automate this other than to add a manual post-processing step.

**Comment by danielbh** [comment] 2016-09-21 08:37
@cunneen Not using meteor build unfortunately. I'm starting to think its another issue with iOS10 entirely since I'm not getting any console error messages. It just doesn't connect...

**Comment by danielbh** [comment] 2016-09-21 09:48
@cunneen I used meteor run ios-device not meteor build. (sorry about repeats. Trying not to clutter things with unclear info)

Meteor version: METEOR@1.4.2-beta.4

I'm now getting the common console error in safari on local meteor server

> Refused to connect to ws:// ...  because it does not appear in the connect-src directive of the Content Security Policy.

I've installed the boilerplate-generator and I've looked in www/application/index and the meta tag is as follows

`<meta http-equiv="Content-Security-Policy" content="default-src * data: blob: 'unsafe-inline' 'unsafe-eval' ws: wss:;">`

I again can connect through wifi to my 192.168.1.45:3000 local meteor server through my device. But I've had no luck with any proposed fix so far connecting to a subdomain.meteorapp.com.

Again I'm using FORCE HTTPS on the galaxy server.

**Comment by derwaldgeist** [comment] 2016-09-21 10:19
@cunneen: Thanks for the clarification about the ```boilerplate-generator```. Unfortunately, updating Meteor is not an option for me, as I am using Cordova plugins that are not compatible with the latest Cordova release yet. Any other idea how the meta tag could be added programmatically?

**Comment by cunneen** [comment] 2016-09-21 13:08
Daniel that definitely looks like the same error; unfortunately I'm at as much of a loss as you as to why your meta tag doesn't fix it.

Sorry I can't be of more help.

**Comment by danielbh** [comment] 2016-09-21 14:03
Is there something I'm missing here with how the module `browser-policy` needs to be configured?

**Comment by danielbh** [comment] 2016-09-21 14:17
Ok I got the following message from Web Inspector: "XMLHttpRequest cannot load http://subdomain.meteorapp.com/sockjs/info?cb=zbiujoe5nl. Cross-origin redirection denied by Cross-Origin Resource Sharing policy." Any idea?

**Comment by cunneen** [comment] 2016-09-21 14:23
Ah that one I know. Create a file in your meteor/server folder called access-control-allow-origin.js . You need to deploy it to your server.

```
// prevent client CORS error when using meteor as HTTP server by adding an extra header:
// "Origin http://meteor.local is not allowed by Access-Control-Allow-Origin."
Meteor.startup(function(){
  // Listen to incoming HTTP requests, can only be used on the server
  WebApp.rawConnectHandlers.use(function(req, res, next) {
    res.setHeader("Access-Control-Allow-Origin", "*");
    return next();
  });
});
```

**Comment by danielbh** [comment] 2016-09-21 14:33
Very strange. It should be using https... Do I need to install another package or something like this? https://atmospherejs.com/meteor/force-ssl

**Comment by elledienne** [comment] 2016-09-21 16:14
Maybe the first post should be updated (the fix section) because as it is right now it gives the impression that a simple `meteor update boilerplate-generator` will fix the problem (personally I wasted a huge amount of time on it)

**Comment by derwaldgeist** [comment] 2016-09-22 07:20
@cunneen: That is interesting. Could this Header hook also be used to set the Content-Security-Policy header? Currently, I am doing this in a ```head.html```, since the boilerplate-generator approach did not work in Meteor 1.2. But this does not work reliably in my simulator, sometimes the connection still fails. Maybe it's because the meta tags of ```head.html``` are located after the first inline JavaScripts of Meteor. The header approach seems to be a better solution to me. I did not even know that the HTTP headers can be set this way.

**Comment by derwaldgeist** [comment] 2016-09-22 07:22
@elledienne: That a good proposal. The first post should IMHO also state that the ```boilerplate-generator``` approach does not work in Meteor 1.2. If I place my own boilerplate package in the packages folder, it is executed, but seems to be overridden later by a boilerplate baked into the build process. So my changes don't appear in the actual rendered HTML code. As an alternative, I am now setting the CSP in a ```head.html```, but this does not seem to work reliably.

**Comment by crapthings** [comment] 2016-09-22 08:38
hey @derwaldgeist will this package help this issue?

    https://github.com/kadirahq/meteor-dochead

**Comment by cunneen** [comment] 2016-09-22 13:42
@derwaldgeist No the same server hook won't work for CSP in a cordova app, since the starting index.html is not sent from the server; it's created by the meteor build tool and bundled with the app itself.

**Comment by ericterpstra** [comment] 2016-09-22 15:25
This is still not working for me.  Here's my situation...

* OS X El Capitan
* Meteor 1.4.1.1
* XCode 8
* iOS 10.0.1 

I installed:
```
cordova-plugin-meteor-webapp@https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5
```
That resolved the XCode 8 / Swift 3 compatability problem.

I also updated `boilerplate-generator` which seemingly did nothing.

Then I added `meteor-ios10-csp-fix@0.1.0` which finally got a new CSP into index.html (see below).

This is my current CSP entry in index.html

```
<meta http-equiv="Content-Security-Policy" content="default-src * data: blob: 'unsafe-inline' 'unsafe-eval' ws: wss:;">
```

I'm still getting the following error(s) in Safari inspector when running the app on my iPad:

```
[Error] Refused to connect to ws://10.23.6.121:3002/sockjs/812/tk_nssda/websocket because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.
[Error] SecurityError (DOM Exception 18): The operation is insecure.
	(anonymous function) (ddp-client.js:1363)
	websocket (ddp-client.js:1363)
	_try_next_protocol (ddp-client.js:1285)
	_didClose (ddp-client.js:1193)
	onfinish (ddp-client.js:1119)
	emit (ddp-client.js:239)
	onfinish (ddp-client.js:2108)
	emit (ddp-client.js:239)
	onreadystatechange (ddp-client.js:936)
```

Do I really need to update 1.4.2-beta4? Or am I still missing something?

**Comment by bryanterrell** [comment] 2016-09-23 01:05
Thought I'd post this since it wasn't completely evident to me at first - I was seeing this (modifying the meta tag of index.html file) work part of the time because I was only updating the index.html file in the root www folder and not the one that is also in the Staging folder of the Xcode project - I'm not positive how the Staging folder works, but I get the impression that Cordova creates it based on the www root folder, but not clear on when this happens or when it gets updated.

In any case, once I made sure both index.html files were updated and then it worked consistently, the two files being:
 - <PROJECT_ROOT>/www/application/index.html
 - <PROJECT_ROOT>/Staging/www/application/index.html

**Comment by cunneen** [comment] 2016-09-23 03:04
@bryanterrell yes, the cordova plugin modifies both of these (although it seems only the Staging one gets used). But of course it only works for ```meteor run ios-device ...``` commands. 

@ericterpstra That's very strange, you shouldn't see that error with that CSP. Can you confirm that you're looking at the index.html under the 'Staging' folder of the XCode project, as @bryanterrell points out?

**Comment by crazybaud** [comment] 2016-09-23 09:12
@ericterpstra for us :

Everything is ok with `ROOT_URL=https://sub.domain.com meteor run ios-device --mobile-server https://sub.domain.com`

The error is present in local with `MONGO_URL=mongodb://127.0.0.1:27017/dbname meteor run ios-device` => `[Error] Refused to connect to ws://192.168.2.240:3000/sockjs/565/_00exz4k/websocket because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.`

With :  
- `meteor update --release 1.4.2-beta.4`
- `meteor add cordova:cordova-plugin-meteor-webapp@https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5` + `Xcode 8 Beta 6`
- `mupx` + `nginx`

I think that this issue should be reopened, or a new one.

**Comment by ericterpstra** [comment] 2016-09-23 16:52
@cunneen Yes, that is the exact CSP tag in _both_ `/www/application/index.html` and `Staging/www/application/index.html`

@crazybaud Interesting.  I normally run my app in development with `ROOT_URL=http://localhost`, so I changed it to `ROOT_URL=http://10.23.6.121` (my static IP) but it did not make a difference. I still get the ws:// error.

I wonder if it's my alternative port causing a problem? Here are my development settings:

Run command:
`meteor run ios-device --settings=dev.settings.json --port=3002`

ENV:
```
ROOT_URL=http://10.23.6.121:3002
MONGO_URL=mongodb://localhost:27017/melodi
PORT=3002
```

**Comment by ericterpstra** [comment] 2016-09-23 18:37
Another note... this is localized to an actual device.  Running on the XCode simulator on my development machine does not display the ws:// error.

**Comment by cunneen** [comment] 2016-09-25 02:27
@ericterpstra You need to provide a full URL to the --port parameter if you're running on a device on a non-default port. You might also want to provide a --mobile-server parameter.

Here's a little script I sometimes use to start meteor with a --port parameter (bash on OS X, you might need to edit it for linux). I put it in a file called ```run_meteor.sh```.

You can then invoke it using e.g.

```
run_meteor.sh ios-device
```

```bash
#!/usr/bin/env bash

function myip() {
    ifconfig | sed -En 's/127.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | head -1
};
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "${DIR}/meteor-server"

echo "you can also run this script with --production flag"
ip=`myip`
echo "meteor run --settings settings.json --port http://${ip}:3000 $@"
meteor run --settings settings.json --port http://${ip}:3000 $@

```

**Comment by ericterpstra** [comment] 2016-09-26 16:45
So turns out I had another CSP header in my app template that I forgot about :(
After removing that, the ws: errors go away.  Thanks for your help!

**Comment by adamgins** [comment] 2016-10-05 21:10
HI, for Meteor 1.3 what's the soution pls? ie do we still need to do 

```
git clone git@github.com:gsaynac/meteor.git
cd meteor
git checkout cordova-csp-fix
cp -r packages/boilerplate-generator ~/myapp/packages/
cd ~/myapp
meteor
```

**Comment by adamgins** [comment] 2016-10-05 23:23
Hi any ideas on this error, pls? I started getting this issue, both on 1.3.5.1 and 1.4.2:

```

I kinda had it working, not sure what I did but now getting: `clear badge
<Appname>(3804,0x1b8026c40) malloc: *** error for object 0x1700b7040: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
(lldb) `

any ideas? 
```

**Comment by martinothamar** [comment] 2016-10-19 13:49
I'm on 1.4.2-beta.13 and installed boilerplat-generator 1.0.10 and cordova-plugin-meteor-webapp. I'm deploying with kadirahq/mup and the meta-tag is not present in the web.cordova/head.html file, so i echo it in manually now, post deployment. Is this issue considered fixed? Am I missing something?

**Comment by danlg** [comment] 2016-10-20 17:37
Still and issue on Meteor 1.3. This is a serious as it impacts. Can we manually patch without the generated head.html on the server without breaking Hot Code Push in 
`./programs/server/assets/packages/boilerplate-generator/boilerplate_web.cordova.html`
The issue should be reopened unless a fix is made on 1.3 (which by the means that Meteor should also have the concept of LTS like Ubuntu as you cannot expect developper to immediately pickup a new version change !).
This is serious as there is no workaround  for production app...

**Comment by ccuilla** [comment] 2016-10-20 22:59
I tried:

`meteor update --release 1.4.2-beta.4`

Same issue:

`[Error] Refused to connect to ws://192.168.0.4:3000/sockjs/424/cgqji2o1/websocket because it does not appear in the connect-src directive of the Content Security Policy.`

Then I tried:

`meteor update --release 1.4.2-beta.13`

(Which @martinothamar mentions above.)

Same issue:

`[Error] Refused to connect to ws://192.168.0.4:3000/sockjs/036/j27h2uth/websocket because it does not appear in the connect-src directive of the Content Security Policy.`

NOTE: Through all of this boilerplate-generator has been at 1.0.10.

I feel like I'm missing something too.

Do I need to add cordova-plugin-meteor-webapp even though this is not a Cordova app?

I may need to wait for 1.4.2 final. I hope it comes very soon...and fixes this issue for non-Cordova web apps as well.

**Comment by ccuilla** [comment] 2016-10-24 14:51
I understand this issue has been closed, but it seems to still be an issue at least from the web-only (non-Cordova) side of things. Any chance of re-opening this issue?

**Comment by abernix** [comment] 2016-10-25 09:34
@ccuilla Can you explain a bit more where you're receiving this error?  What browser and platform are you experiencing this in?  It's entirely possible that #7774 and #7934 might need to be applied in some way to the non-Cordova boilerplate.  Are you experiencing this on a brand new Meteor project?  Please provide reproduction steps so someone can take a look at it.  Thanks!

**Comment by ccuilla** [comment] 2016-10-25 12:44
@abernix It appears to happening on load or startup only on iOS (version 10...have not yet tried 10.1) in Safari, Chrome and launch from home screen (not Cordova) all of which appear to be based on WebKit. Not sure if Chrome is using the built in WebView on iOS. If so it might explain why it happens there also because this might be at that level.

I've tried adding variations of the CSP manually (and inspection with the Safari dev tools looks like the meta tag is getting to the browser when added manually).

Here's the current one:

`<meta http-equiv="Content-Security-Policy" content="default-src * 'self' data: blob: gap: 'unsafe-inline' 'unsafe-eval' ws://* wss://*;">`

But all seem to have the same problem.

I do suspect this needs to be added to the web boilerplate as well as the Cordova boilerplate.

This may be due to come change in WebKit starting with iOS 10.

**Comment by abernix** [comment] 2016-10-25 14:23
@ccuilla How are you adding it manually?  If you're adding it manually via a `head` tag (like, a `client/head.html` file with a `<head>` tag in it) and it's still not working, then I don't believe the boilerplate change would fix anything.

**Comment by ccuilla** [comment] 2016-10-25 14:28
@abernix That exactly how I added it manually (except it was client/main.html but should be same). I agree about the boilerplate change not likely fixing. I was just wondering if I was missing something here.

**Comment by abernix** [comment] 2016-10-25 14:48
@ccuilla I think your issue is different from what was being mentioned here.  I don't see the issue you're referring to with any of the 1.4.2 versions (btw, the current release is `1.4.2-rc.4`).   You should take a look at the docs for [the `browser-policy` package](https://atmospherejs.com/meteor/browser-policy) and consider adding/removing/configuring it.  If you still have an issue after that, please reproduce this error in a brand new app, upload it to GitHub and open a new issue with a link to that reproduction.  Please read the guidelines for [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) and make sure you explain what is necessary (Safari Remote Debugging, etc.).   My belief is that `browser-policy` might be the problem here, not the boilerplate.

**Comment by ccuilla** [comment] 2016-10-25 15:02
@abernix Thanks. I'll give that a try. I thought I had tried browser-policy for this issue before, but may not have been as systematic as I should be. Thanks!

**Comment by glasser** [comment] 2016-12-07 22:56
@benjamn Seeing something similar to this in OSX Safari when using the browser-policy package.  I can work around this with `BrowserPolicy.content.allowConnectOrigin("wss:"); BrowserPolicy.content.allowConnectOrigin("ws:");` but maybe the default policy should include ws: and wss: (after all, it contains `*`).

It looks like this rule changed between [CSP1](https://www.w3.org/TR/2012/CR-CSP-20121115/#matching) and [CSP3](https://www.w3.org/TR/CSP3/#match-url-to-source-expression); in CSP3 `*` only matches URLs with a "network scheme" (ftp, http, or https) or the same scheme as origin, but not ws or wss coming from https.
