### ISSUE TITLE
Meteor crashes if app doesn't depend on webapp

### ISSUE THREAD

**Issue by jsep** [meteor/meteor#2168] opened 2014-05-21 23:54 UTC
Hello, 

This is actually 3 bugs that need to be solved in order for run-command not to crash. Those are:

1. Missing no-ops in the livedata package if there is no webapp

2. ServiceConfiguration backwards compatibility code needs to be moved to service-configuration package from accounts-base

3. Missing check that Meteor.server exists in accounts-base  - this one cannot be reproduced without solving the above

We will publish shortly an app to reproduce all bugs as well as issue a pull request to fix all of them.

**Comment by glasser** [comment] 2015-01-09 22:52
Underlying issue split out into #3452.

**Comment by rbabayoff** [comment] 2015-01-20 02:30
@glasser , splitting ddp into 2 is a major task. This can simply be solved by first dealing with noop methods in case webapp doesn't exist, and then solve the circular dependency, which is a really easy task as well. Can I start by creating a pr for those 2?

**Comment by glasser** [comment] 2015-01-21 06:05
You can send a PR, but please do read our https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests policy to set expectations.

**Comment by rbabayoff** [comment] 2015-01-21 06:32
@glasser, that works for me. Can I assume I have you on board or should I post to meteor-core first?

**Comment by glasser** [comment] 2015-01-21 06:49
Sure, feel free to post it now, but that doesn't mean any promises about it finding its way up the priority list.

**Comment by abernix** [comment] 2016-07-15 10:39
Closing as this doesn't seem relevant anymore.  The reproductions seem to operate (generally) fine (without the error previously shown) in the latest Meteor, but I'm not even sure it's appropriate to test this anymore.  Happy to reopen if anyone feels differently. :smile:

**Closed by abernix** 2016-07-15 10:39 UTC
Labels: Project:DDP
