### ISSUE TITLE
Meteor 1.3's windows command-line output

### ISSUE THREAD

**Issue by alphashuro** [meteor/meteor#6785] opened 2016-04-11 16:04 UTC
Meteor 1.3's commandline output on windows 10 always prints at the very first line of the command-line, doesn't clear the previous text first (so it is jumbled up with whatever I had typed when I first opened cmd) and doesn't print complete output probably because of the fact that it keeps overwriting itself at the first line.

**Comment by benjamn** [comment] 2016-04-12 17:43
This issue will be officially fixed when Meteor 1.3.2 is released this Friday, but you can test it out by doing `meteor update --release 1.3.2-rc.5` now. Thanks for bringing this issue to our attention!

**Comment by alphashuro** [comment] 2016-04-12 18:31
Awesome stuff, I will test as soon as I boot up windows. What was the issue if I may ask?

**Comment by alphashuro** [comment] 2016-04-13 08:51
the issue is still there as you can see here in this screen shot:
![image](https://cloud.githubusercontent.com/assets/8580352/14487837/2707a5ba-0165-11e6-9bca-080cf13ebb45.png)
Also it takes REALLY long to start up the app on windows, I sometimes doubt if its even going to start up at all. It spends a lot of time building the application, trying to startup, then building again, and so on.

**Comment by benjamn** [comment] 2016-04-14 22:19
Hmm, you're right to ask, and I'm afraid I jumped the gun here. A [change](https://github.com/meteor/meteor/pull/6664) was made to `dev_bundle/bin/npm.cmd` that prevents it from echoing every `meteor npm` command, but the problems you're seeing in Powershell are clearly unrelated to that. Sorry for the false hope.

Do you get the same messy output if you run Meteor from the `cmd` prompt?

**Comment by alphashuro** [comment] 2016-04-15 06:01
Yes I get the same on the cmd prompt


Alpha

0737907955



From: Ben Newman

Sent: Friday, April 15, 12:20 AM

Subject: Re: [meteor/meteor] Meteor 1.3's windows command-line output (#6785)

To: meteor/meteor

Cc: Alpha Shuro



Hmm, you're right to ask, and I'm afraid I jumped the gun here. A change was made to dev_bundle/bin/npm.cmd that prevents it from echoing every meteor npm command, but the problems you're seeing in Powershell are clearly unrelated to that. Sorry for the false hope.


Do you get the same messy output if you run Meteor from the cmd prompt?

**Comment by alphashuro** [comment] 2016-04-15 06:03
Lol please ignore the extra stuff in that comment, wanted to see if replying to github emails would be a viable way to respond, it seems not!

**Comment by Rhywden** [comment] 2016-04-15 16:44
Just adding that I'm seeing this too on different PCs on both `cmd` and `powershell` on the current release 1.3.2

**Comment by Rhywden** [comment] 2016-04-15 16:53
@benjamn Um, how/when do we get the fix for this? Just asking because you closed the issue and if it's through doing `meteor update` just be aware that I can't read anything coming from that command - I'm just seeing that *something* is available to update but not what exactly.

**Comment by benjamn** [comment] 2016-04-15 18:19
Sorry, this got closed because I merged `release-1.3.2` into `devel`, and there was a commit that included the (incorrect) text "fixes #6785". Reopening.

**Comment by benjamn** [comment] 2016-04-21 17:38
Unfortunately I haven't been able to reproduce this on my Windows VM, using either Powershell or the `cmd` prompt, so in all honesty it will be fixed sooner if someone who is experiencing this behavior can dig into it further. You'll want to run `meteor/meteor.bat` from a [checkout](https://github.com/meteor/meteor/#slow-start-for-developers) and have a look at https://github.com/meteor/meteor/blob/devel/tools/console/console.js

**Comment by iamgmd** [comment] 2016-04-23 07:18
I am having the same problem on my Windows 10 build, both in the cmd prompt and powershell. I will have a look at console.js and see if I can spot the problem.

**Comment by iamgmd** [comment] 2016-04-23 07:43
This seems to be something to do with the Windows 10 console settings. I can fix the problem both in cmd prompt and powershell by opening a cmd prompt, go to the Default settings and check the 'Use legacy console (requires relaunch)' option. Then hit OK and then close any cmd prompts and powershells and run a command again.

As a guess it might have something to do with 'Enable line wrapping selection' option in the cmd prompt but I got mixed results. Seems to work for me just by using the legacy option.

**Comment by nbrady-techempower** [comment] 2016-06-25 08:26
Yes, I only started experiencing this problem when I moved away from the legacy option so that I could start messing with Windows Ubuntu bash.

**Comment by guyemerson** [comment] 2016-08-31 08:50
I can confirm that switching to the legacy option fixed this for me.

**Comment by Rhywden** [comment] 2016-11-18 21:01
It will probably become a bit more of an issue in the future:

http://news.softpedia.com/news/microsoft-replaces-command-prompt-with-powershell-in-latest-windows-10-build-510328.shtml

Summary: The Command Prompt (CMD) will be hidden by default and replaced with Powershell. 

Crystal ball prognosis: If they don't run into bigger issues it might go away completely.

**Comment by Rhywden** [comment] 2016-11-18 21:32
@benjamn Probing the issue would be way easier if the console.js file wouldn't pull in other dependencies from all over the project. Then we could put the output through its paces in isolation and wouldn't have to run the whole application just to test console output.

**Comment by abernix** [comment] 2016-11-21 15:13
@Rhywden Even PowerShell has the "Legacy" setting (which refers to "legacy features", not "legacy shell"), so the situation will remain the same regardless of this news.  (And personally, I'd say that it'll be great if Windows got rid of this weird duality between `cmd.exe` and PowerShell).

**Comment by Rhywden** [comment] 2016-11-21 15:39
No, it's not the same. Because if you put Powershell into "Legacy" mode you cannot use Bash (i.e. Ubuntu On Windows) anymore and other features the "non-legacy" mode has.

**Comment by guyemerson** [comment] 2016-11-21 16:05
@Rhywden it is the same, in the sense that removing CMD does not affect this PowerShell bug.  Not being able to use Bash and other non-legacy features is noted in the comments above.

**Closed** 2017-01-28 09:51 UTC
Labels: bug, confirmed, Project:Windows, pull-requests-encouraged

**Comment by shadowcat-mst** [comment] 2017-02-14 18:02
@alphashuro I'm confused as to why this issue was marked closed when I don't see a fix commit and this isn't precisely a dupe of 5798 - what am I missing?

**Comment by abernix** [comment] 2017-02-14 19:09
@shadowcat-mst The fix commit is listed above, and in the PR (https://github.com/meteor/meteor/pull/8082) where it's merged.  Additionally, the fix itself is in Meteor 1.4.3.1.  Do you mind giving it a try?

    meteor update --release 1.4.3.1

**Comment by guyemerson** [comment] 2017-02-15 11:12
I have tried version 1.4.3.1, and the problem is improved but not fully fixed.  The command line output does not go back to the first line of the console, but it does jump back several lines before it stabilises.  The exact number of lines seems to depend on the width of the console - e.g. for a width of 80 characters, it jumped 13 lines; for 120 characters, it jumped 8 lines.  After the root directory of the project has been printed, the command line output seems to work correctly.  However, the root directory gets printed several lines back.

Could it be that this fix has not been applied in all places where something is printed to the console?

**Comment by niquedegraaff** [comment] 2017-06-03 18:12
This problem shouldn't be closed. it is NOT fixed...

**Comment by Phrozyn** [comment] 2017-11-29 02:03
![2017-11-28 17_57_09-select administrator_ windows powershell](https://user-images.githubusercontent.com/4267984/33354044-b16e8fc8-d465-11e7-8ca4-7c59c4b962a3.png)

This is still an issue with meteor  - I installed 1.6 but my app  requires 1.4.3.1 - it jumped up to the top of the screen and started building stuff and is now hanging here.
Running in command prompt with legacy console turned on seems to work just fine though.

**Comment by abernix** [comment] 2017-11-29 09:38
@Phrozyn Instead of using the older 1.4.3.1 application, could you try creating a basic new test application, with Meteor 1.6 rather than the older 1.4.3.1 and see if the problem is still demonstrable?  We've had other improvements to console logic since 1.4.x which could help.

Either way, I'd highly recommend updating to newer versions as we've made other substantial improvements, including 64-bit speeds, if you update to Meteor 1.6.  There are guides available on [the Meteor Guide](https://guide.meteor.com/1.6-migration.html#older-versions) on how to update from Meteor 1.4.

**Comment by Phrozyn** [comment] 2017-11-29 17:10
Hi @abernix I'll definitely try that and see how it fares. I do believe updating the app is the correct path forward also.

I'll let you know.
