### ISSUE TITLE
Msg when building "WARN: Output exceeds 32000 characters"

### ISSUE THREAD

**Issue by guidouil** [meteor/meteor#8592] opened 2017-04-13 09:16 UTC
I just updated to Meteor 1.4.4.1 and I have this message when building 
`WARN: Output exceeds 32000 characters`
Although there seem not to be an issue since the build succeed and create the tarball.
Maybe it's linked to the new minifier or maybe I have too much code/pkgs in my project ^_^

**Comment by abernix** [comment] 2017-04-14 04:04
Thanks for filing the issue.  This can be safely ignored.

This is being caused by the newer version of UglifyJS which we implemented with #8519 and #8397.  It's a side-effect of UglifyJS's beautifier running on particularly large files (and as a reminder, the resulting output from your `meteor build` is a concatenation of all npm modules used in your project, so it can be quite large).  The default option for the minifier's beautify function sets `max-line-length` to `32000` (and we don't actually specify a value because it's not relevant to us).   This was added to UglifyJS with https://github.com/mishoo/UglifyJS2/pull/1496/files#diff-00fe37b20ddfb9ecc9c492b0725fa2b2R219.  Unfortunately, the current implementation provides no way to disable this warning.

I brought this up on https://github.com/mishoo/UglifyJS2/issues/124#issuecomment-293668017 yesterday and the great news is it looks like a few hours ago there were a number of commits made in this up-and-coming UglifyJS PR, https://github.com/mishoo/UglifyJS2/pull/1811, which claims to fix it.  We'll watch that PR and update the UglifyJS version that Meteor uses as soon as that becomes available and we've confirmed that it fixes the problem.  Luckily, the `standard-js-minifiers` package can be updated outside a full Meteor release as soon as this happens since the version isn't pinned to the release.

**Comment by abernix** [comment] 2017-08-23 16:46
This should be fixed in Meteor 1.5.1 as we've brought in the latest from the `uglify-js@3.x`!  Thanks for reporting this originally!

(Note this still isn't the more major `uglify-es` update, which is still being tracked in #8698 and should be released with Meteor 1.6).

**Closed by abernix** 2017-08-23 16:46 UTC
Labels: bug, confirmed, Impact:some, known-fix, Project:Isobuild:Minifiers
