### ISSUE TITLE
standard-minifier-js conflicts with ejs packages

### ISSUE THREAD

**Issue by tenshis** [meteor/meteor#11464] opened 2021-06-04 19:49 UTC
In my project, I have some npm dependencies which use ejs templates - this works fine without minification, but as soon as they are minified for production using standard-minifier-js, the packages crash because the template can't find required components.

Can I tell the standard-minifier-js to skip certain npm packages, or is there any other way to have ejs templates run in production?

**Comment by StorytellerCZ** [comment] 2021-06-05 13:23
Hi, could you provide a reproduction? 😉
You can read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor).

**Comment by StorytellerCZ** [comment] 2021-06-28 20:52
I'm closing this issue since we are lacking reproduction and communication from OP. Please feel free to re-open if this persist. If you just want to ask a question, please use the [Meteor Forums](https://forums.meteor.com).

**Closed by StorytellerCZ** 2021-06-28 20:52 UTC
Labels: Project:Isobuild:Minifiers, needs-reproduction
