### ISSUE TITLE
Mongodb Version 2.6 Compatibility

### ISSUE THREAD

**Issue by katywings** [meteor/meteor#3620] opened 2015-02-01 22:03 UTC
Is it just me, or who didn't know that meteor doesnt officially support 2.6? 

Somehow this information is not official too, i couldn't find any blog posts or something about this behavior...

**Comment by glasser** [comment] 2015-02-02 04:16
Duplicate of #2036 (which you'll be happy to know is my top priority for this upcoming week).

My impression is that Meteor works OK with 2.6 if you follow some caveats mentioned on that issue.

**Closed by glasser** 2015-02-02 04:16 UTC
