### ISSUE TITLE
Wrong ObjectId when using {idGeneration:'MONGO'} option in method.

### ISSUE THREAD

**Issue by amrutraj** [meteor/meteor#8356] opened 2017-02-12 07:15 UTC
#### PROBLEM
When you perform, `<_id>.getTimestamp()` from the `meteor mongo` console or `parseInt(<objId>.toString().substr(10,8), 16)` from meteor, it does not give "todays" timestamp. It shows a time 10 - 200 years in the future without any discernible pattern.

#### REPLICATE
1. `Branches=new Mongo.Collection('branches',{ idGeneration: 'MONGO' });` 
2.  `var objId=Branches.insert(doc);`
3. `console.log(parseInt(objId.toString().substr(10,8), 16));`

After inserting using  {idGeneration:'MONGO'} it gives `ObjectId("fd29f7d7dc7bba9eb6f9d9b8")` which translates to `ISODate("2104-08-05T13:27:51Z")` which is clearly wrong.

**Comment by klaussner** [comment] 2017-02-12 09:22
From the [Meteor API Docs](https://docs.meteor.com/api/collections.html#Mongo-ObjectID):

> ObjectID values created by Meteor will not have meaningful answers to their getTimestamp method, since Meteor currently constructs them fully randomly.

**Comment by hwillson** [comment] 2017-02-13 12:56
Closing as this is intended behavior (thanks @klaussner!).

**Closed by hwillson** 2017-02-13 12:56 UTC
