### ISSUE TITLE
iOS build not connecting to remote server

### ISSUE THREAD

**Issue by Loschcode** [meteor/meteor#5711] opened 2015-11-26 00:34 UTC
I'm building an **iOS App** which works well when I work locally. I'm currently trying to launch on the AppStore with everything ready : I try to switch the communication from my local machine to my remote server (DigitalOcean / Ubuntu 14.04) where the Meteor project has been released.

When you go on the server from browser / web-app everything works well, but I realized the iOS App has a problem. It is not considering the `--server` option and keep trying to reach `http://localhost:3000` when built despite what I say (the connection to the server is succeeding when I start my local server again and use any iOS emulator which prove it's not a server access problem)

`iron build --server=http://my-app.domain.tech`
`iron build --server=http://my-app.domain.tech:3000` (note : the app is running on port `3000` but Nginx is set to link it to port `80` when you reach `my-app-domain.tech`, i don't really know which port to define here so I try everything, if you have an answer to this too ...)

I'm using **Iron-cli** for the structure and **Meteor Up** to push it in production (if it can help) but i'm pretty sure the problem comes from Meteor itself not building the App correctly and ignoring the `--server` line : I digged a lot to reach this conclusion.

**Meteor 1.2.1
Iron 1.5.0**

Any idea what the problem is ? Where is the server variable located in Cordova / the App ? I can try to search more but after my App is built and available on Xcode I really don't know how to investigate on the matter.

**UPDATE : `iron run ios --mobile-server http://my-app.domain.tech` failing miserably too**

**Comment by martijnwalraven** [comment] 2015-11-27 09:15
If you want to make sure the URL specified with `--mobile-server` (for `run`) or `--server` (for `build`) is passed to the app, you can have a look at `www/application/index.html` in the generated Xcode project. There should be a line that sets configuration options that starts with `__meteor_runtime_config__ = JSON.parse(decodeURIComponent, ...)`. The easiest way to check this is to copy everything from JSON.parse to a browser debug console so you get an object back that you can expect.

I suspect the server is being set correctly in the built app however, and the problem is on the server-side. Even if the app connects to right server at first, it might reconnect immediately to the wrong one after a Hot Code Push. This is because subsequent updates delivered through Hot Code Push replace the initially bundled `index.html` with a freshly generated one, so the server should also be configured with the right connection URL.

Using `meteor deploy` takes care of setting these values automatically, so there is no need to specify anything in that case. But when deploying on your own server, you have to make sure to set at least the `ROOT_URL` environment variable (`DDP_DEFAULT_CONNECTION_URL` defaults to the same value). For Meteor Up for example, you can configure this in `mup.json`.

**Comment by martijnwalraven** [comment] 2016-02-19 11:32
Going to close this as there hasn't been any activity in a while. Please reopen it if you feel this is still an issue.

**Closed by martijnwalraven** 2016-02-19 11:32 UTC
Labels: Project:Mobile
