### ISSUE TITLE
Meteor.call does not work within observe/observeChanges

### ISSUE THREAD

**Issue by TimHeckel** [meteor/meteor#907] opened 2013-04-04 00:26 UTC
**_1 Upvote**_ Perhaps this is known...this is a simple workaround right now:

```
Collection.find({}).observeChanges({
    added: function(doc) {
        setTimeout(function() {
            Meteor.call("remoteMethod", function(err, res) { });
        }, 0);
    }
});
```

**Comment by glasser** [comment] 2015-01-09 23:11
This is somewhat related to #2315. The issue is that the observeChanges call that is triggered by the client-side stub write is also run in the stub context.  And when a stub calls Meteor.call, it calls the local stub (you can see this if you add a Meteor.methods call in the client file) instead of sending the message.

I think we should fix #2315 so that minimongo writes don't run observe callbacks synchronously, and at the same time ensure that they don't run observe callbacks in the stub context of the write.

**Comment by avital** [comment] 2015-01-10 00:00
I tried implementing a change that would resolve the specific issue here, without resolving the larger issues around it that @glasser points out: #3455.

(That PR is lacking a test for now, so not ready to merge yet but maybe this will help the users who are looking at this thread)

**Comment by briceburg** [comment] 2015-06-27 02:24
ran into this issue today (i stumble across all bugs when starting w/ a new framework it seems) -- confirm it still persists. 


code:

```js
Inhabitants.find().observeChanges({
  added: function(id, fields) {
    // skip call to createInhabitant on records coming from git
    if(fields.origin == 'git') {
      return;
    }
    
    Meteor.call('createInhabitant', fields.person, function(err,result){
      console.log(err,result);
    });
  }
});
```

the async callback passed to Meteor.call _immediately_ returns, and err + result are _undefined_. 

If I refresh the client (reload browser) -- the calls take place! 

Any way to take Meter.call() out of stub context?

**Comment by smowden** [comment] 2015-06-29 09:08
@briceburg if you wrap your call in setTimeout 0 or Meteor.defer it should work

**Comment by jfurneaux** [comment] 2015-07-06 04:56
This is quite a difficult issue to troubleshoot for new Meteor developers. Should something be put in the docs under .observe to save people time - I was in circles for 2 days! :)

**Comment by avital** [comment] 2015-07-07 16:40
Added a test to my pull request: https://github.com/meteor/meteor/pull/3455, I think it can be merged now. @glasser?

**Comment by krishprasadar** [comment] 2015-07-26 00:46
Please update Meteor docs with the issue. We are wasting a lot of time.

**Comment by avital** [comment] 2015-08-26 19:42
Fixed in d9fe23bc60234dbe72909c203ee10f75641e5820, should be out with Meteor 1.2!

**Comment by avital** [comment] 2015-08-26 21:23
Somehow tests actually fail on d9fe23b (thanks @mitar for noticing). Apologies. I'm reverting this.

**Comment by arnaudbesnier** [comment] 2016-03-24 15:28
Any news about this issue?
The setTimeout 0 does the job but this kind of workaround never smells good. It reminds me Appcelerator Titanium workarounds :japanese_ogre:

**Comment by keyscores** [comment] 2016-05-22 16:32
@avital @glasser @abernix  It's been 3 years since this was opened. This seems like a very serious limitation. And it seems ignored in future milestones.

If this limitation is intentional, can it please be documented?

**Comment by abernix** [comment] 2016-05-23 08:00
@keyscores, this issue hasn't been forgotten, however in 3 years, it has not had many +1's so it would seem the impact is relatively low (compared to other issues).

That being said, there has been some recent activity on #3455 – it will get more attention as the PR backlog gets worked through.

**Comment by mitar** [comment] 2016-05-23 08:13
@abernix: I count 11 participants in this issue, with 8 people reporting it and three issues linked to it. I even made a test for it: https://github.com/meteor/meteor/pull/5038

I think this is a pretty serious limitation.

**Comment by abernix** [comment] 2016-05-23 08:34
@mitar 
> I think this is a pretty serious limitation.

I didn't say it wasn't – and I'm not trying to trivialize it – but you know as well as I do that there are a lot more issues causing a lot more problems than this.  Again, in 3 years, this has had seemingly a very low amount of impact.

But again, #3455 doesn't seem far from resolution – perhaps someone could look at the problem that's still outstanding with the PR instead of us debating it's importance here.

**Comment by keyscores** [comment] 2016-05-23 15:22
@abernix I get the priority debate. The reason I think you should prioritize it, is that this is a bug of the worst kind: it is silent and generates no errors to the dev. So it's may be causing more frustration than actually gets reported.

**Comment by Shutik** [comment] 2016-06-14 07:50
+1

**Comment by insaneinc01** [comment] 2016-10-04 13:58
+1

**Comment by BenjaminMerlynS** [comment] 2017-04-24 17:43
+1

**Comment by hwillson** [comment] 2017-04-26 13:40
Hi all - to help move this along, I've marked this issue as `pull-requests-encouraged`. PR's #3455 and #5038 were already started to address this issue, but were closed due to inactivity. If anyone in the community is interested in blowing the dust off of those PR's, they will definitely be reviewed in a timely manner, and be considered for merging. Thanks!

**Comment by zimme** [comment] 2017-06-06 16:48
This issue seems to be fixed with #8734.

**Comment by mitar** [comment] 2017-06-06 17:01
Are you sure? Because this is a client side issue.

**Comment by zimme** [comment] 2017-06-06 17:04
@mitar, no I'm not sure. Maybe it's just the stub that's being called. Maybe I should have read through the issue more closely before commenting.

**Comment by hwillson** [comment] 2017-06-06 18:56
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor.call%20does%20not%20work%20within%20observe%2FobserveChanges&body=Migrated%20from:%20meteor/meteor%23907) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-06 18:56 UTC
Labels: confirmed, feature, Impact:few, Project:Minimongo, pull-requests-encouraged, Severity:has-workaround
