### ISSUE TITLE
App Crashing - Can't deploy site from windows

### ISSUE THREAD

**Issue by moazam1** [meteor/meteor#3721] opened 2015-02-14 00:24 UTC
I am using Meteor WINDOWS-PREVIEW@0.1.7. All seems working fine. I just can't deploy from my windows machine.

I have node v0.10.36 installed. When I run website from browser I get crash error. Here is the log from meteor:

	[Sat Feb 14 2015 00:08:01 GMT+0000 (UTC)] NOTICE Starting application on port 19079
	[Sat Feb 14 2015 00:08:01 GMT+0000 (UTC)] INFO STATUS waiting -> starting
	[Sat Feb 14 2015 00:08:01 GMT+0000 (UTC)] INFO STATUS starting -> running
	[Sat Feb 14 2015 00:08:01 GMT+0000 (UTC)] WARNING Meteor requires Node v0.10.36 or later.
	[Sat Feb 14 2015 00:08:01 GMT+0000 (UTC)] INFO STATUS running -> waiting
	[Sat Feb 14 2015 00:08:01 GMT+0000 (UTC)] ERROR Application crashed with code: 1

I deployed same app from mac and it worked fine.

**Comment by Slava** [comment] 2015-02-14 00:52
closing as a duplicate of https://github.com/meteor/windows-preview/issues/66

**Closed by Slava** 2015-02-14 00:52 UTC
