### ISSUE TITLE
`cannot read property 'buffer' of undefined` error when uninstalling Cordova plugins modifying the plist

### ISSUE THREAD

**Issue by raix** [meteor/meteor#5171] opened 2015-09-15 14:30 UTC
``` bash
=> Errors executing Cordova commands:         

   While removing plugins                     

# ... A list of packages...

   from Cordova project:
   TypeError: Cannot read property 'buffer' of undefined
   at walk_obj
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/plist/lib/build.js:131:18)
   at walk_obj
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/plist/lib/build.js:98:7)
   at walk_obj
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/plist/lib/build.js:109:9)
   at Object.build
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/plist/lib/build.js:76:3)
   at ConfigFile_save [as save]
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/ConfigFile.js:97:47)
   at
   /Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:61:49
   at Array.forEach (native)
   at ConfigKeeper_save_all [as save_all]
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:59:31)
   at PlatformMunger_save_all [as save_all]
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/config-changes.js:82:24)
   at Object.exports.process
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/config-changes.js:59:12)
   at Object.handlePrepare
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/prepare.js:70:20)
   at
   /Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/uninstall.js:341:28
   at _fulfilled
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
   at flush
   (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)

ExitWithCode:1
```

**Comment by raix** [comment] 2015-09-15 14:58
Might be related, this happens on reruns:
```bash
=> Errors executing Cordova commands:         
                                              
   While removing plugins                     
   # ... list of packages ...
   from Cordova project:
   Cordova error: CordovaError: Cannot find plugin.xml for plugin 'cordova-plugin-file'. Please try adding it again.
```

**Comment by martijnwalraven** [comment] 2015-09-15 18:39
Hmmm, these are all Cordova errors that I haven't encountered before. Is there anything more you can tell me about the circumstances this occurred under? Have you been able to reproduce it since?

**Comment by stubailo** [comment] 2015-09-21 04:21
Any more info on this? Is there a way to cause this error to happen reliably?

**Comment by jbl2024** [comment] 2015-09-21 12:44
I have the same problem on my project, upgrading from 1 to 1.2-rc17.

What kind of log/output should i provide to help finding this issue ?

**Comment by martijnwalraven** [comment] 2015-09-21 12:50
Preferably a minimal project that reproduces the issue reliably, but some details about the packages/plugins in your project and the specific error output would already be helpful. Could you try running with the `--verbose` flag?

**Comment by jbl2024** [comment] 2015-09-21 12:55
ok, got it,

i had an empty version field ('') in App.info:
 
```
App.info({
  name: 'xxx',
  description: '',
  author: '',
  email: '',
  website: '',
  version: '',
  buildNumber: '1'
});
```

by setting version to '1' for example, the problem disappears.

**Comment by martijnwalraven** [comment] 2015-09-21 13:16
Good to hear you fixed your problem! But are you sure it is the same issue? Did you get the same errors mentioned above under `While removing plugins`?

**Comment by jbl2024** [comment] 2015-09-21 13:28
Damn, you are right :(

I'm facing now the same issue:

```
=> Started proxy.
=> Errors executing Cordova commands:

   While removing plugins
   com.ionic.keyboard,com.meteor.cordova-update,cordova-plugin-facebook4,cordova-plugin-file,cordova-plugin-file-transfer,cordova-plugin-inappbrowser,cordova-plugin-legacy-whitelist,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-camera,cordova-plugin-console,cordova-plugin-geolocation
   from Cordova project:
   TypeError: Cannot read property 'buffer' of undefined
   at walk_obj (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/plist/lib/build.js:131:18)
   at walk_obj (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/plist/lib/build.js:98:7)
   at walk_obj (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/plist/lib/build.js:109:9)
   at Object.build (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/plist/lib/build.js:76:3)
   at ConfigFile_save [as save]
   (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/ConfigFile.js:97:47)
   at
   /Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:61:49
   at Array.forEach (native)
   at ConfigKeeper_save_all [as save_all]
   (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:59:31)
   at PlatformMunger_save_all [as save_all]
   (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/config-changes.js:82:24)
   at Object.exports.process
   (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/config-changes.js:59:12)
   at Object.handlePrepare
   (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/prepare.js:70:20)
   at /Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/uninstall.js:341:28
   at _fulfilled (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at /Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
   at flush (/Users/jbl2024/.meteor/packages/meteor-tool/.1.1.7-rc.16.k2750m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)
```

i have removed the raix:push package and tried to run the project after.

**Comment by jbl2024** [comment] 2015-09-21 13:32
It is probably related to https://github.com/jeduan/cordova-plugin-facebook4/issues/49 ?

**Comment by martijnwalraven** [comment] 2015-09-21 14:36
Good find! It seems there is a [Cordova issue](https://issues.apache.org/jira/browse/CB-7781) for this, but it is waiting for a pull request in `plist` to be merged.

I'm afraid there is nothing we can do about this on the Meteor side. As a workaround, `rm -rf .meteor/local/cordova-build` should help avoid the issue temporarily (until the plugin needs to be uninstalled again, which also happens when adding another plugin).

**Comment by raix** [comment] 2015-09-21 14:44
// we are not using the facebook plugin

**Comment by martijnwalraven** [comment] 2015-09-21 14:49
From the issue, it seems this is not specific to the Facebook plugin, but related to the plist modification Cordova does when adding/removing plugins.

@raix Any more information about the circumstances under which this occurs for you? Does removing `cordova-build` help?

**Comment by raix** [comment] 2015-09-30 16:19
I still get this issue - I'm not sure if it can be related to using `App.configurePlugin` - things work in separated QA apps - but not when added to the main project.

Are you manipulating the plist file from Meteor or is this only Cordova doing this?

> plist/lib/build.js:131:18
ref: https://github.com/TooTallNate/plist.js/blob/master/lib/build.js#L131

**Comment by martijnwalraven** [comment] 2015-09-30 20:14
Cordova modifies the plist as part of uninstalling plugins, so there isn't much we can do about it from the Meteor side. We'll have to wait till the fix is merged in `plist`.

**Comment by wmendes** [comment] 2015-12-17 19:23
Thank you @martijnwalraven. You save my life!!!

**Comment by martijnwalraven** [comment] 2016-02-19 10:11
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.

**Comment by grigio** [comment] 2016-03-09 09:33
@martijnwalraven yes on Meteor 1.3-beta.12

```
   While removing plugins cordova-plugin-facebook4,cordova-plugin-inappbrowser,cordova-plugin-statusbar from
   Cordova project:
   TypeError: Cannot read property 'buffer' of undefined
```

**Comment by martijnwalraven** [comment] 2016-03-09 09:42
@grigio: Thanks for testing this on Meteor 1.3. It seems this still an [open issue](https://issues.apache.org/jira/browse/CB-7781) in the most recent version of Cordova, so there isn't much we can do about it from the Meteor side.

**Comment by lorensr** [comment] 2016-05-02 01:38
> `rm -rf .meteor/local/cordova-build`

This works for me (Meteor 1.2.1)

**Comment by array-addu** [comment] 2016-09-02 10:03
Hello raix,
did you successfully modified the plist file with this plugin?

**Comment by hwillson** [comment] 2017-08-23 14:54
This issue should be fixed with newer versions of Meteor. If anyone is still encountering this problem, please post back (ideally with a reproduction) and we'll re-open. Thanks!

**Closed by hwillson** 2017-08-23 14:54 UTC
Labels: Project:Mobile
