### ISSUE TITLE
Error: Could not install npm dependencies for test-packages

### ISSUE THREAD

**Issue by MrChrisJoy** [meteor/meteor#8585] opened 2017-04-11 22:59 UTC
After running this command, in order to generate a meteor app
`meteor create app`
I get the following error messages:
```
C:\Users\chrisjoy\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: Error: Could not install npm dependencies for test-packages: Command failed: C:\Users\chrisjoy\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd install
'C:\Users\chrisjoy\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\init.cmd' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\chrisjoy\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\init.cmd' is not recognized as an internal or external command,
operable program or batch file.

    at Object.error (C:\tools\utils\buildmessage.js:430:11)
    at C:\tools\cli\default-npm-deps.js:32:20
    at C:\tools\utils\buildmessage.js:334:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:333:36
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.install (C:\tools\cli\default-npm-deps.js:27:27)
    at Command.func (C:\tools\cli\commands.js:747:36)
    at C:\tools\cli\main.js:1483:23
```

I installed meteor using the windows installer from the website, didn't run the installer using administrator rights.

**Comment by MrChrisJoy** [comment] 2017-04-11 23:05
When I do the following
```
cd app
meteor --verbose
```
I get the following output:
```
=> Started proxy.
Local package version is up-to-date: allow-deny@1.0.5
Local package version is up-to-date: autopublish@1.0.7
Local package version is up-to-date: autoupdate@1.3.12
Local package version is up-to-date: babel-compiler@6.14.1
Local package version is up-to-date: babel-runtime@1.0.1
Local package version is up-to-date: base64@1.0.10
Local package version is up-to-date: binary-heap@1.0.10
Local package version is up-to-date: blaze@2.3.0
Local package version is up-to-date: blaze-html-templates@1.1.0
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.0.11
Local package version is up-to-date: caching-compiler@1.1.9
Local package version is up-to-date: caching-html-compiler@1.1.0
Local package version is up-to-date: callback-hook@1.0.10
Local package version is up-to-date: check@1.2.5
Local package version is up-to-date: ddp@1.2.5
Local package version is up-to-date: ddp-client@1.3.3
Local package version is up-to-date: ddp-common@1.2.8
Local package version is up-to-date: ddp-server@1.3.13
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: diff-sequence@1.0.7
Local package version is up-to-date: ecmascript@0.6.3
Local package version is up-to-date: ecmascript-runtime@0.3.15
Local package version is up-to-date: ejson@1.0.13
Local package version is up-to-date: es5-shim@4.6.15
Local package version is up-to-date: fastclick@1.0.13
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.2.12
Local package version is up-to-date: id-map@1.0.9
Local package version is up-to-date: insecure@1.0.7
Local package version is up-to-date: jquery@1.11.10
Local package version is up-to-date: launch-screen@1.1.1
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: logging@1.1.17
Local package version is up-to-date: meteor@1.6.1
Local package version is up-to-date: meteor-base@1.0.4
Local package version is up-to-date: minifier-css@1.2.16
Local package version is up-to-date: minifier-js@1.2.18
Local package version is up-to-date: minimongo@1.0.21
Local package version is up-to-date: mobile-experience@1.0.4
Local package version is up-to-date: mobile-status-bar@1.0.14
Local package version is up-to-date: modules@0.7.9
Local package version is up-to-date: modules-runtime@0.7.9
Local package version is up-to-date: mongo@1.1.16
Local package version is up-to-date: mongo-id@1.0.6
Local package version is up-to-date: npm-mongo@2.2.24
Local package version is up-to-date: observe-sequence@1.0.16
Local package version is up-to-date: ordered-dict@1.0.9
Local package version is up-to-date: promise@0.8.8
Local package version is up-to-date: random@1.0.10
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.1.11
Local package version is up-to-date: retry@1.0.9
Local package version is up-to-date: routepolicy@1.0.12
Local package version is up-to-date: shell-server@0.2.3
Local package version is up-to-date: spacebars@1.0.13
Local package version is up-to-date: spacebars-compiler@1.1.0
Local package version is up-to-date: standard-minifier-css@1.3.4
Local package version is up-to-date: standard-minifier-js@1.2.3
Local package version is up-to-date: templating@1.3.0
Local package version is up-to-date: templating-compiler@1.3.0
Local package version is up-to-date: templating-runtime@1.3.0
Local package version is up-to-date: templating-tools@1.1.0
Local package version is up-to-date: tracker@1.1.2
Local package version is up-to-date: ui@1.0.12
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: url@1.1.0
Local package version is up-to-date: webapp@1.3.14
Local package version is up-to-date: webapp-hashing@1.0.9
   Starting your app                         \

```

And it takes forever to start the app.

**Comment by abernix** [comment] 2017-04-12 18:02
This certainly works fine for me on Windows 10 – I find the interesting part is that during your app creation (`meteor create <app-name>`) an `npm install` (spawned by Meteor from [around here](https://github.com/meteor/meteor/blob/devel/tools/cli/default-npm-deps.js#L30-L31) is trying to run a command called `init` (or since this is on Windows, `init.cmd`) – I'm not sure what that is, as it's not something that Meteor is calling directly.

Do you have some sort of global `npm` configuration that could be interfering with this?  I'd certainly suggest trying to reinstall Meteor if it's been a while since you've installed – preferably after a clean uninstall:

 * Uninstall Meteor from:
  * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
  * **Win7/Win8.1:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.  If you are unable to delete it due to long file-paths, please try using the [7-zip File Explorer](http://www.7-zip.org/) application to do it instead.
* Install fresh 1.4.4.1 from https://install.meteor.com/windows (you should skip logging in at the end due to bug #6218)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

**Comment by MrChrisJoy** [comment] 2017-04-12 23:06
@abernix  I've don't have NodeJS installed on my computer. I've just completed a clean uninstall and reinstall, following your instructions and I get the same error messages.

**Comment by abernix** [comment] 2017-04-12 23:19
What happens if you do `meteor create --release 1.4.4.1`?

**Comment by MrChrisJoy** [comment] 2017-04-12 23:40
It's been hanging on:
`   Extracting meteor-tool@1.4.4_1...         -`
for a while...

**Comment by abernix** [comment] 2017-04-12 23:45
First, this gives indication that the re-installation did not work because Meteor 1.4.4.1 would have been the version already installed (assuming you did that re-installation within the last 24 hours, which you've indicated you have).  I know this sounds extreme, but give it another 30+ minutes because Windows can be particularly slow at extracting the (relatively large) `meteor-tool` bundle.

**Comment by MrChrisJoy** [comment] 2017-04-13 00:00
I'll wait for another 30+ mins. If that doesn't work, I'll try re-downloading the installer, because I used 
an old installation file, that I had previously downloaded. 

Thanks

**Comment by MrChrisJoy** [comment] 2017-04-13 03:18
I've tried 

`meteor create --release 1.4.4.1 app3`

But I get the following error messages:
```
 Installing npm dependencies     C:\Users\chrisjoy\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: Error: Could not install npm dependencies for test-packages: Command failed: C:\Users\chrisjoy\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd install
'C:\Users\chrisjoy\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\init.cmd' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\chrisjoy\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\init.cmd' is not recognized as an internal or external command,
operable program or batch file.

    at Object.error (C:\tools\utils\buildmessage.js:430:11)
    at C:\tools\cli\default-npm-deps.js:32:20
    at C:\tools\utils\buildmessage.js:334:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:333:36
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.install (C:\tools\cli\default-npm-deps.js:27:27)
    at Command.func (C:\tools\cli\commands.js:747:36)
    at C:\tools\cli\main.js:1483:23
```

**Comment by txs** [comment] 2017-04-13 18:35
I have this issue too on windows 10

**Comment by MrChrisJoy** [comment] 2017-04-14 00:01
@abernix I've tried creating a new admin account and installing on that account and I get the same error messages.  Even with the --release 1.4.4.1 app3

**Comment by abernix** [comment] 2017-04-14 00:41
Thanks for your debugging efforts!  I just upgraded my Windows installation to Meteor 1.4.4.1 (from Meteor 1.4.3.2) and was able to successfully create an app.

**Windows Version**
```powershell
PS C:\Users\abernix> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.15063 N/A Build 15063
```

**Meteor Create**
```powershell
PS C:\Users\abernix> meteor create --release 1.4.4.1 test-app-1.4.4.1
Created a new Meteor app in 'test-app-1.4.4.1'.

To run your new app:
  cd test-app-1.4.4.1
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn

meteor create --bare to create an empty app.
meteor create --full to create a scaffolded app.

PS C:\Users\abernix>
```

So I'm curious if you have any environment variables which might be interfering, specifically any which might start with `NPM_*`.  You can get a list (in PowerShell) with:

```powershell
Get-ChildItem Env:
```

Or just `SET` in Command Prompt.

**Comment by MrChrisJoy** [comment] 2017-04-14 02:53
When I execute `SET` in cmd, I get the following: 

```
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\chris\AppData\Roaming
CARBON_MEM_DISABLE=1
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=Tue Jan 24 18:02:40 2017
ChocolateyToolsLocation=C:\tools
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=CHRIS-DESKTOP
ComSpec=C:\WINDOWS\system32\cmd.exe
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\chris
LOCALAPPDATA=C:\Users\chris\AppData\Local
LOGONSERVER=\\CHRIS-DESKTOP
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\chris\OneDrive
OS=Windows_NT
Path=C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Docker\Docker\Resources\bin;C:\tools\ruby23\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\adb;C:\ProgramData\chocolatey\bin;;C:\Users\chris\AppData\Local\Microsoft\WindowsApps;C:\Users\chris\AppData\Local\.meteor\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2a07
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\chris\AppData\Local\Temp
TMP=C:\Users\chris\AppData\Local\Temp
USERDOMAIN=CHRIS-DESKTOP
USERDOMAIN_ROAMINGPROFILE=CHRIS-DESKTOP
USERNAME=chris
USERPROFILE=C:\Users\chris
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
w
```

**Comment by MrChrisJoy** [comment] 2017-04-14 04:44
Alright, I performed a clean install, yet again (uninstall via "Apps & Features" settings menu, remove .meteor from the LocalAppData path via 7zip). Re-downloaded meteor and installed it. Rebooted my computer. I tried creating a  new meteor app using the following commands:

```
C:\Users\chris\workspace\local\chris-fs\tmp>meteor update
The latest version of Meteor, 1.4.4.1, is already installed on this computer. Run
'meteor update' inside of a particular project directory to update that project to Meteor 1.4.4.1

C:\Users\chris\workspace\local\chris-fs\tmp>meteor create --bare app
C:\Users\chris\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: Error: Could not install npm dependencies for test-packages: Command failed: C:\Users\chris\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd install
'C:\Users\chris\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\init.cmd' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\chris\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\init.cmd' is not recognized as an internal or external command,
operable program or batch file.

    at Object.error (C:\tools\utils\buildmessage.js:430:11)
    at C:\tools\cli\default-npm-deps.js:32:20
    at C:\tools\utils\buildmessage.js:334:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:333:36
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.install (C:\tools\cli\default-npm-deps.js:27:27)
    at Command.func (C:\tools\cli\commands.js:747:36)
    at C:\tools\cli\main.js:1483:23

```

When I execute `SET` via the command prompt it gives me this:
```
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\chris\AppData\Roaming
CARBON_MEM_DISABLE=1
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=Tue Jan 24 18:02:40 2017
ChocolateyToolsLocation=C:\tools
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=CHRIS-DESKTOP
ComSpec=C:\WINDOWS\system32\cmd.exe
HOMEDRIVE=C:
HOMEPATH=\Users\chris
LOCALAPPDATA=C:\Users\chris\AppData\Local
LOGONSERVER=\\CHRIS-DESKTOP
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\chris\OneDrive
OS=Windows_NT
Path=C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\adb;C:\ProgramData\chocolatey\bin;;C:\Users\chris\AppData\Local\Microsoft\WindowsApps;C:\Users\chris\AppData\Local\.meteor\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2a07
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\chris\AppData\Local\Temp
TMP=C:\Users\chris\AppData\Local\Temp
USERDOMAIN=CHRIS-DESKTOP
USERDOMAIN_ROAMINGPROFILE=CHRIS-DESKTOP
USERNAME=chris
USERPROFILE=C:\Users\chris
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
windir=C:\WINDOWS
```

**Comment by rwdietrich** [comment] 2017-04-18 19:26
This is frustrating. Meteor stopped working on an existing project, giving an error (below) after several minutes. And yes, I uninstalled/re-installed. I can create and run a new project, but that's a bit useless to me.

```
Cloning into 'test_existing'...
remote: Counting objects: 1687, done.
remote: Compressing objects: 100% (949/949), done.
remote: Total 1687 (delta 948), reused 1078 (delta 580)
Receiving objects: 100% (1687/1687), 293.48 KiB | 0 bytes/s, done.
Resolving deltas: 100% (948/948), done.
Checking connectivity... done.

c:\Build\meteor\test>cd test_existing
c:\Build\SMARTRodeo\test\dev>meteor help update
C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: No metadata files found for isopack at: /C/Users/Bob/AppData/Local/.meteor/packages/meteor-tool/1.4.3_2
    at [object Object]._.extend._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
    at C:\tools\packaging\tropohouse.js:521:21
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:520:13
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:515:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:600:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:597:20)
    at C:\tools\cli\main.js:462:30
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at C:\tools\cli\main.js:461:17
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at C:\tools\cli\main.js:459:33
    at [object Object]._.extend.withProgressDisplayVisible (C:\tools\console\console.js:639:14)
    at springboard (C:\tools\cli\main.js:458:11)
    at C:\tools\cli\main.js:1126:5

```

**Comment by abernix** [comment] 2017-04-18 20:35
@rwdietrich I'd suggest running:

* `meteor reset` in your **project** directory (warning, this will delete your development database. Alternatively, you can just delete `.meteor\local` which will preserve the DB)
* Re-install Meteor using [the steps above](https://github.com/meteor/meteor/issues/8585#issuecomment-293659947) (most notably, remove your `%LocalAppData%\.meteor` directory)
* Run `meteor` in your project again.

**Comment by abernix** [comment] 2017-04-18 20:42
@MrChrisJoy Is there any common denominator which exists in your global environment (which would exist even on a new account)?  Chocolatey, for example?  Can you backpedal through older Meteor releases to the point where it starts? (e.g. `meteor create --release 1.4.3.2 app1`,  `meteor create --release 1.4.3.1 app2`,  `meteor create --release 1.4.2.7 app3`, etc.)

**Comment by rwdietrich** [comment] 2017-04-18 23:14
@abernix I've followed the reinstall multiple times. For some time I've only been able to run my app by running `meteor reset` followed by `meteor`. Every. Time.

Seems like something worthwhile to fix rather than searching for workarounds.

**Comment by abernix** [comment] 2017-04-19 02:04
@rwdietrich Nobody is suggesting that it wouldn't be worthwhile to fix – but a reproduction doesn't exist right now.  Additionally, the error you've reported (`No metadata files found for isopack`) is not the same as the issue being reported here (`Could not install npm dependencies for test-packages`) so it'd be best to search for an issue whose error message more closely matches yours.  https://github.com/meteor/meteor/issues/8587 looks like the issue you're looking for, and your help in coming up with an easy reproduction would be greatly appreciated as an update to that issue!

**Comment by rwdietrich** [comment] 2017-04-19 07:01
@abernix Thanks for your measured comment. I wasn't trying to imply that contributors are ignoring particular issues, and certainly not dismissing the hard work they've contributed. And I realize my comment was a little off topic. What is coming out is my frustration with Meteor and the frequent blocking issues I've run into, including losing half a day on what I posted.

**Comment by txs** [comment] 2017-05-04 07:28
Accidentally, the issue is fixed, but I don't know why

**Comment by hwillson** [comment] 2017-09-12 16:20
This issue hasn't been updated in a while, and we haven't been able to re-create it. Without a runnable reproduction demonstrating this problem (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)), this issue is very difficult to troubleshoot. Given this and the fact that some people who have encountered this problem are now reporting it as fixed, I'll close this issue off. I'll happily re-open this issue if anyone disagrees and is able to provide a reproduction, using a modern version of Meteor. Thanks!

**Closed by hwillson** 2017-09-12 16:20 UTC
Labels: bug, can't-reproduce, Project:Tool, Project:Windows

**Comment by Vikhyat5** [comment] 2017-11-01 20:01
I am also facing the same Issue 
I have reinstalled  1.4.4.1
done meteor --release 1.4.4.1 test-app-1.4.41
Restart my computer
Still facing this problem
Please help I have very less time for submitting the Assignment

**Comment by Sevan-A** [comment] 2017-11-19 19:23
I'm getting this very same problem; Error: Could not install npm dependencies for test-packages.
I have a Windows 10.

C:\Users\sevan\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: Error: Could not install npm dependencies for test-packages: Command failed: C:\WINDOWS\system32\cmd.exe /c C:\Users\sevan\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd install
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sevan\AppData\Roaming\npm-cache\_logs\2017-11-19T16_59_09_168Z-debug.log
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sevan\AppData\Roaming\npm-cache\_logs\2017-11-19T16_59_09_168Z-debug.log

    at Object.error (C:\tools\utils\buildmessage.js:430:11)
    at C:\tools\cli\default-npm-deps.js:32:20
    at C:\tools\utils\buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.install (C:\tools\cli\default-npm-deps.js:27:27)
    at Command.func (C:\tools\cli\commands.js:799:36)
    at C:\tools\cli\main.js:1522:15

**Comment by klaussner** [comment] 2017-11-19 20:52
Try installing Git (or check you `PATH` environment variable if you have already installed it)! 🙂  It looks like `npm` couldn't find it:

```
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
```

**Comment by Sevan-A** [comment] 2017-11-20 00:41
Desktop Git is already installed... with C:\Users\sevan\AppData\Local\GitHubDesktop\bin appended to PATH. 
I looked in the log file and the problem seems to be that it can't find directories and files in c:\users\sevan\dev\image_share\node_modules\... there is nothing in this directory.

**Comment by abernix** [comment] 2017-11-20 11:25
@Sevan-A What happens if, prior to running ``meteor create image_share``, you just type `git --version` and press enter?

I'm truly not sure if the GitHub Desktop provides the necessary functionality, so you may need to install [Git for Windows](https://git-scm.com/download/win).

**Comment by Sevan-A** [comment] 2017-11-20 14:35
@abernix, I installed Git for Windows and it now works! Thank you all for your help 👍

**Comment by aptarmy** [comment] 2017-11-23 05:46
I had the same error as @mrchrisjoy's
 I couldn't either create a new app and even run an existing app. The error message was `Could not install npm dependencies for test-packages`.
But now the problem that i faced was solved. It looks like it's not an error from Meteor itself. I tried uninstalling Git, removing Git PATH and installing Git again and now everything works fine :)

**Comment by rccampeon** [comment] 2018-02-13 22:32
I had this issue too, for some reason running meteor create from PowerShell as admin didn't work, but from cmd it did

**Comment by ayoub1996-01** [comment] 2018-02-15 09:18
hello everyone !
i have the same error, i have fix it by fixing the git  ...
when i was trying  this commande ligne " meteor npm install " it said 

npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

so with this 3 steps i have fix the promblem and i have create my funy project with out error :

## _1__`npm install --save npm-git-install`

## _2__## In your pacakge.json 
add: 
{
  "scripts": {
    "install": "npm-git install"
  }
  "gitDependencies": {
    "private-package-name": "git@private.git.server:user/repo.git#revision",
    "public-package-name": "https://github.com/user/repo.git#revision"
  }
}

Obviously replace *-package-name and git URLs with values relevant to your project. URLs has to be in canonical form (i.e. one that you would provide to git clone on command line) - no fancy NPM shortcuts like user/repo or bitbucket:user/repo. If you want this, we are open for a PRs.

## _3__Then install your dependencies as usual:

 `npm install`

for more details visit this link : https://www.npmjs.com/package/npm-git-install
 
if anyone knows the relation between the git and my error explain me plz , because i don't know the git's effect on my project creation ...

**Comment by SabarinathNatarajan** [comment] 2018-03-14 09:57
Had similar issue in windows 10:
Problem : meteor could not install npm dependencies for test-packages
Steps I followed to fix it : 
1. execute the command meteor --verbose (this is will install some of the missed dependencies)
    after which it will throw another error 
2. Error: The @babel/runtime npm package could not be found in your node_modules
directory. Please run the following command to install it:

  meteor npm install --save @babel/runtime
3. After which execute the same command 'meteor npm install --save @babel/runtime'
4. It will start the application and furnish the below message : 

Local package version is up-to-date: templating-tools@1.1.2
Local package version is up-to-date: tracker@1.1.3
Local package version is up-to-date: ui@1.0.13
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: url@1.2.0
Local package version is up-to-date: webapp@1.5.0
Local package version is up-to-date: webapp-hashing@1.0.9
=> Meteor server restarted
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

5. Please verify the same in browser

**Comment by eicksl** [comment] 2018-06-11 05:04
This seems to be an issue of the internal version of NodeJS that Meteor uses conflicting with a separately installed version. Uninstalling NodeJS resolved the issue for me.

**Comment by terminal69** [comment] 2018-07-27 09:39
I encountered the same error, it was resolved by switching to my secondary ISP which gives me a better internet connection. (I stay on the first one most of the time because they offer unlimited downloads).

I have encountered other errors/problems such as errors and installations taking a long time when git is involved, for example with downloading/installing electron through npm. Switching to my secondary ISP usually solves the issue.

**Comment by Masterkey12** [comment] 2020-07-01 10:14
i have the problems with meteor

\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

RangeError: Maximum call stack size exceeded
(Use `node --trace-uncaught ...` to show where the exception was thrown)
