### ISSUE TITLE
loginExpirationInDays

### ISSUE THREAD

**Issue by lybertbox** [meteor/meteor#10644] opened 2019-07-22 14:49 UTC
When you define :

`Accounts.config({
    loginExpirationInDays: 0.04
});`

Meteor logout befor the loginTokenExpires.
I detected 0.05 is the minimum value where meteor is ok below meteor logout instantly

**Comment by klaussner** [comment] 2019-08-17 18:41
This looks like a duplicate of https://github.com/meteor/meteor-feature-requests/issues/119.

**Closed by klaussner** 2019-08-17 18:41 UTC
