### ISSUE TITLE
Meteor 1.5: Excruciatingly long production build times

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#8778] opened 2017-06-10 18:43 UTC
Galaxy deployments are taking forever since I've upgraded to 1.5, like 8 minutes and up. Sometimes they fail due to failed health checks. As a test, I run `meteor --production` locally, and that, too, takes an extremely long time.

I'm using the `standard-minifier-js` package. Should we still (as of 1.5) be using @abernix's minifier?

**Comment by abernix** [comment] 2017-06-12 07:17
I know I've mentioned this before, but please try to provide a little more clarity and debugging information when opening these issues.  "Since I've upgraded to 1.5" isn't really helpful without knowing what version you were on before the upgrade and what other packages you may have updated in the upgrade.

Have you tried experimenting with build time differences with `standard-minifier-js` versus `abernix:standard-minifier-js` versus removing them completely?  You can imagine how including information like this to quantify the differences is imperative to providing an answer.

It would also be interesting if you provided information about the (byte) size of the resulting bundles between the two different versions which you're using (whatever they are).  You can investigate by doing a `meteor build` (instead of a `meteor deploy`) and looking at the size of the resulting tarball from each.

Ultimately, this could be the same/similar as your similar experiences in https://github.com/meteor/meteor/issues/8157#issuecomment-307528600.  The difference in that issue is that it's just taking forever and ultimately running out of memory, whereas in this case it's taking forever and finishing.

**Comment by abernix** [comment] 2017-06-12 12:02
I guess your other issue, #8782, answers the question of which versions you were on before (Meteor 1.4.4.2), but still interested in the other details I discussed in the previous comment! 😉

**Comment by benjamn** [comment] 2017-06-12 19:05
Does the build seem to be spending a long time with the status `Minifying app code`?

**Comment by davidworkman9** [comment] 2017-08-03 20:19
When does Babili step in as a fallback? I'm also getting very slow build times, but I think it's coming from 1.5.1 not 1.5, as they've just recently became slow. I'm talking really slow, I run our build server on a micro instance in AWS, with a bunch of swap. Always been slow, but if I REALLY needed a build I'd shut it down and restart it as a c4.xlarge. Now even that size instance takes 8+ minutes, when it use to take around ~2.5.

**Comment by abernix** [comment] 2017-08-04 05:39
@davidworkman9 Babili steps in as a fallback when `uglify-js` (the default, very fast, mostly-feature complete, minifier) fails to compile.  UglifyJS generally only fails on very modern ECMAScript constructs which haven't been fully implemented.  On the other hand, Babili is generally 100% feature complete and supports all modern ECMAScript but is inherently slow, [by their own admission](https://github.com/babel/babili#benchmarks) (you'll see that they underperform in all of their benchmarks).

The newer [`uglify-es`](https://github.com/mishoo/UglifyJS2/tree/harmony) fork should be a lot more feature complete but it did have some regressions.  We're looking at trying it again in an upcoming version of Meteor.  Though you can try it yourself right now by using `abernix:standard-minifier-js` in place of `standard-minifier-js`.  You should try and see if this fixes your build speed; it's possible that you upgraded an npm package (or an indirect dependency got updated) which introduced new ECMAScript which `uglify-js` didn't support and now it's falling back to Babili.

**Comment by abernix** [comment] 2017-08-04 05:41
@ffxsam Closing as this has been idle for over a month and assuming you've found the answer based on my previous comments.  To follow the official UglifyES update, please follow #8698. :smile:

**Closed by abernix** 2017-08-04 05:41 UTC

**Comment by galdo666** [comment] 2017-09-12 14:39
I apologize, but, in my case, the problem persists. I checked the code of the new implementation of minifier and the performance difference between the 1.4.4.4 and 1.5 version depends on the presence of Babel.parse in the file stats.js (extractModuleSizesTree). Below an extract of build process with times relative to file modules.js:

 54s   Uglify
 202s   extractModuleSizesTree 

 I tried to remove this and the application works the same, what is it for?

Thanks

**Comment by felipegouveiae** [comment] 2018-02-27 01:02
Guys, I had the same problem on windows 10. 

What I've done was :

* Activated Ubuntu into Windows 10
* Had Ubuntu processing Meteor

The build time has reduced from 17sec to 3 sec.

Although MongoDB is not able to share window filesystem on windows, so Mongo is running on a Docker instance. 

In order to make run meteor easier on ubuntu, I created a sh file like that : 

```
#!/bin/sh

export MONGO_URL=mongodb://localhost:27017/vcpMeteorDB
export METEOR_PROFILE=1
export METEOR_WATCH_FORCE_POLLING=2

meteor
```

To access the meteor code inside the ubuntu machine to run, just 

```

$ cd /mnt/{drive letter on windows such as c or d }/{path to the code on windows}
$ ./my-sh.sh

```

Hope it helps.
