### ISSUE TITLE
@import CSS from Node package

### ISSUE THREAD

**Issue by edemaine** [meteor/meteor#8208] opened 2017-01-02 20:22 UTC
I'm running Meteor 1.4.2.3 on Windows.  I'm using the `katex` NPM package (via `meteor npm install --save katex`) which includes CSS under `katex/dist/katex.min.css`.  I'm trying to include the CSS into my Meteor app, ideally to load in the initial batch of CSS.

The [Meteor guide](https://guide.meteor.com/using-npm-packages.html#npm-styles) suggests that the following three methods should work, but here is what I find:

* [`client/lib/katex.less`] `@import (inline) '{}/node_modules/katex/dist/katex.min.css';`
  ```
   While processing files with less (for target web.browser):
   client/lib/katex.less:1: Unknown import: {}/node_modules/katex/dist/katex.min.css
  ```
* [`client/lib/katex.scss`] `@import '{}/node_modules/katex/dist/katex.min.css';`
  ```
   While processing files with fourseven:scss (for target web.browser):
   /client/lib/katex.scss: Scss compiler error: File to import: {}/node_modules/katex/dist/katex.min.css not found
   in file: C:/.../{}/client/lib/katex.scss
  ```
* [`client/lib/katex.js`] `import 'katex/dist/katex.min.css';`

  This one works, but loads the CSS later instead of the initial batch.

(I've tried relative paths (`../../` instead of `{}/`) and omitting the `{}/` altogether.  Less and SCSS still seem not to work.)

I also find it disappointing that the following do not work, although their behavior is at least "as documented" (though perhaps the documentation could warn against these potential gotchas...):

* [`client/lib/katex.css`] `@import "{}/node_modules/katex/dist/katex.min.css";`

  ```app/client/lib/katex.css: warn: there are some @import rules those are not taking effect as they are required to be in the beginning of the file```

* [`client/lib/katex.less`] `@import '{}/node_modules/katex/dist/katex.min.css';`

  ```app/client/lib/katex.css: warn: there are some @import rules those are not taking effect as they are required to be in the beginning of the file```

* [`lib/katex.js`] `import 'katex/dist/katex.min.css';` (loaded on server too)

  ```
  20170102-15:19:32.077(-5)? (STDERR) C:\...\node_modules\katex\dist\katex.min.css:1
  W20170102-15:19:32.081(-5)? (STDERR) (function (exports, require, module, __filename, __dirname) { @font-face{font-family:KaTeX_AMS;src:url(fonts/KaTeX_AMS-Regular.eot);src:url(fonts/KaTeX_AMS-Regular.eot#iefix) format('embedded-opentype'),url(fonts/KaTeX_AMS-Regular.woff2) format('woff2'),url(fonts/KaTeX_AMS-Regular.woff) format('woff'),url(fonts/KaTeX_AMS-Regular.ttf) format('ttf');font-weight:400;font-style:normal}@font-face{font-family:KaTeX_Caligraphic;src:url(fonts/KaTeX_Caligraphic-Bold.eot);src:url(fonts/KaTeX_Caligraphic-Bold.eot#iefix) format('embedded-opentype'),url(fonts/KaTeX_Caligraphic-Bold.woff2) format('woff2'),url(fonts/KaTeX_Caligraphic-Bold.woff) format('woff'),url(fonts/KaTeX_Caligraphic-Bold.ttf) format('ttf');font-weight:700;font-style:normal}@font-face{font-family:KaTeX_Caligraphic;src:url(fonts/KaTeX_Caligraphic-Regular.eot);src:url(fonts/KaTeX_Caligraphic-Regular.eot#iefix) format('embedded-opentype'),url(fonts/KaTeX_Caligraphic-Regular.woff2)
  W20170102-15:19:32.082(-5)? (STDERR)
  W20170102-15:19:32.082(-5)? (STDERR) SyntaxError: Unexpected token ILLEGAL
  W20170102-15:19:32.082(-5)? (STDERR)   at exports.runInThisContext (vm.js:53:16)
  W20170102-15:19:32.082(-5)? (STDERR)   at Module._compile (module.js:373:25)
  ...
  ```

**Comment by tcastelli** [comment] 2017-01-05 19:44
This a current limitation that has been there since 1.3.2 If i recall correctly. There are many issues talking about this, I can remember  #6037 or #6846  but the general idea is that for know the work-around is using import from js files like you did (and yes you can't load that on the initial batch unfortunately). As for assets you will have to copy from the npm package to your public folder or do some tricks commented on previous issues.

**Comment by edemaine** [comment] 2017-01-05 21:32
Yeah, I ended up copying the css into my project in the NPM postinstall script, along with the other assets, as a workaround.  Sorry, I meant to refer to those past issues; my impression was that they resulted in the current system, as documented, but it's clearly not done yet.

**Comment by hwillson** [comment] 2017-09-15 18:19
Closing as a duplicate of https://github.com/meteor/meteor/issues/6846. Thanks!

**Closed by hwillson** 2017-09-15 18:19 UTC
