### ISSUE TITLE
Meteor 1.5: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by joshuadavidson** [meteor/meteor#8740] opened 2017-06-01 14:45 UTC
Today I updated from Meteor 1.4.4.3 to 1.5 via cli. After the update when I try to run meteor locally (```meteor run```) I encounter the error below on Win10 64bit. I tried removing meteor via Windows Programs and Features and doing a clean install from the .exe available at https://www.meteor.com/install but I get the same error.

I am not sure if it is related but #8336 with the ImportScanner seems very similar?
```
TypeError: Cannot read property '0' of undefined
    at toDosPath (C:\Users\Joshua Davidson\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:41:8)
    at C:\Users\Joshua Davidson\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:98:16
    at Array.map (native)
    at Function._.map._.collect (C:\Users\Joshua Davidson\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:97:56)
    at C:\Users\Joshua Davidson\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:95:16
    at ImportScanner._getRelativeImportId (C:\tools\isobuild\import-scanner.js:525:43)
    at C:\tools\isobuild\import-scanner.js:509:33
    at _.each._.forEach (C:\Users\Joshua Davidson\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._resolve (C:\tools\isobuild\import-scanner.js:498:7)
    at C:\tools\isobuild\import-scanner.js:564:29
    at _.each._.forEach (C:\Users\Joshua Davidson\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:557:5)
    at C:\tools\isobuild\import-scanner.js:670:12
    at _.each._.forEach (C:\Users\Joshua Davidson\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:557:5)
    at C:\tools\isobuild\import-scanner.js:670:12
    at _.each._.forEach (C:\Users\Joshua Davidson\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:557:5)
    at C:\tools\isobuild\import-scanner.js:670:12
    at _.each._.forEach (C:\Users\Joshua Davidson\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:557:5)
    at C:\tools\isobuild\import-scanner.js:670:12
    at _.each._.forEach (C:\Users\Joshua Davidson\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:557:5)
    at C:\tools\isobuild\import-scanner.js:357:14
    at Array.forEach (native)
    at ImportScanner.scanImports (C:\tools\isobuild\import-scanner.js:355:22)
    at C:\tools\isobuild\compiler-plugin.js:1040:17
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:1008:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:1059:8)
    at C:\tools\isobuild\bundler.js:830:12
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:821:18)
    at C:\tools\isobuild\bundler.js:2879:14
    at C:\tools\isobuild\bundler.js:2968:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Joshua Davidson\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2967:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2860:31)
    at C:\tools\isobuild\bundler.js:2807:32
    at Object.withCache (C:\tools\fs\files.js:1652:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2807:16)
    at C:\tools\runners\run-app.js:588:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:587:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:631:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:890:28)
    at C:\tools\runners\run-app.js:417:12
```

**Comment by hwillson** [comment] 2017-06-01 17:47
I've done some quick digging into this one. The reported `Cannot read property '0' of undefined` error is happening in [`toDosPath`](https://github.com/meteor/meteor/blob/4b18c00cc6f0839c67c548360ae20639d66ef126/tools/static-assets/server/mini-files.js#L40-L51) as part of a call to the following code in [`tools/isobuild/import-scanner.js#_getRelativeImportId`](https://github.com/meteor/meteor/blob/4b18c00cc6f0839c67c548360ae20639d66ef126/tools/isobuild/import-scanner.js#L524-L538):

```js
const relativeId = convertToPosixPath(pathRelative(
  pathDirname(parentPath),
  childPath
), true);  
```

The error happens when `pathRelative` above is called; basically its first parameter is some kind of falsy value, so when processing logic is triggered afterwards (in [`tools/static-assets/server/mini-files.js#wrapPathFunction`](https://github.com/meteor/meteor/blob/4b18c00cc6f0839c67c548360ae20639d66ef126/tools/static-assets/server/mini-files.js#L88-L111)), an array is created containing that falsy path value, which is then used to populate the parameters passed into `toDosPath`.

Commit https://github.com/meteor/meteor/commit/d9184808cbe7bba552def7bf38dd252ca738286e was created to help address this issue, by making sure the [`parentPath` in the above code snippet exists](https://github.com/meteor/meteor/blob/4b18c00cc6f0839c67c548360ae20639d66ef126/tools/isobuild/import-scanner.js#L502-L507) before continuing. Since that code is in place, then something else is affecting the `parentPath` just before it's passed into `pathRelative`. That points to `pathDirname` as being the culprit. It looks like `pathDirname(parentPath)` is taking a valid path, and returning a falsy value of some kind.

I've tested calling `pathDirname` with a wide variety of non-falsy values (since we know `parentPath` has to exist thanks to https://github.com/meteor/meteor/commit/d9184808cbe7bba552def7bf38dd252ca738286e), but in every case if the incoming value can't be handled in some way, a default path dirname of `'.'` is returned. That's on a Mac though (I can't test Windows right now) - Meteor's `pathDirname` translates down to Node's [`path.dirname`](https://nodejs.org/docs/latest-v4.x/api/path.html#path_path_dirname_p), so it is handled a bit differently on Windows.

Long story short, that's as far as I've gotten (while still staying employed 🙂). I have a feeling a really quick fix to this issue would be to extend the code changes in https://github.com/meteor/meteor/commit/d9184808cbe7bba552def7bf38dd252ca738286e so we're also checking to make sure `pathDirname` returns a valid path; so changing [this code](https://github.com/meteor/meteor/blob/4b18c00cc6f0839c67c548360ae20639d66ef126/tools/isobuild/import-scanner.js#L502-L507) to be something like:

```js
if (! parentFile.installPath && pathDirname(parentFile.installPath)) {
  // If parentFile is not installable, then we won't return it
  // from getOutputFiles, so we don't need to worry about
  // recording any parentFile.deps[id].helpers.
  return;
}
```

but this is a bit of a kludge. We should really track down why `pathDirname(parentPath)` is returning an invalid path on Windows.

**Comment by tab00** [comment] 2017-06-02 11:04
I'm getting this exact same error after migrating my app to Meteor 1.5 on Windows 10.

**Comment by tab00** [comment] 2017-06-07 09:06
Is this issue being worked on? I'm eager to try Meteor 1.5.

**Comment by Rebolon** [comment] 2017-06-09 15:26
Strange for me because the migration to 1.5 worked well. But since a refactoring, i have this error... 

No idea of the source of the problem for instance

**Comment by Rebolon** [comment] 2017-06-12 08:10
This weekend i tried to run the app with vagrant and this time the error is not the same : 

```
/home/vagrant/.meteor/packages/templating-compiler/.1.3.2.gopvov++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.relative (path.js:496:3)
    at /home/vagrant/.meteor/packages/meteor-tool/.1.5.0.1cs9qa8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/static-assets/server/mini-files.js:109:14
    at ImportScanner._getRelativeImportId (/tools/isobuild/import-scanner.js:525:43)
    at /tools/isobuild/import-scanner.js:509:33
    at _.each._.forEach (/home/vagrant/.meteor/packages/meteor-tool/.1.5.0.1cs9qa8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._resolve (/tools/isobuild/import-scanner.js:498:7)
    at /tools/isobuild/import-scanner.js:564:29
    at _.each._.forEach (/home/vagrant/.meteor/packages/meteor-tool/.1.5.0.1cs9qa8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:557:5)
    at /tools/isobuild/import-scanner.js:670:12
    at _.each._.forEach (/home/vagrant/.meteor/packages/meteor-tool/.1.5.0.1cs9qa8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:557:5)
    at /tools/isobuild/import-scanner.js:670:12
    at _.each._.forEach (/home/vagrant/.meteor/packages/meteor-tool/.1.5.0.1cs9qa8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:557:5)
    at /tools/isobuild/import-scanner.js:670:12
    at _.each._.forEach (/home/vagrant/.meteor/packages/meteor-tool/.1.5.0.1cs9qa8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:557:5)
    at /tools/isobuild/import-scanner.js:670:12
    at _.each._.forEach (/home/vagrant/.meteor/packages/meteor-tool/.1.5.0.1cs9qa8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:557:5)
    at /tools/isobuild/import-scanner.js:357:14
    at Array.forEach (native)
    at ImportScanner.scanImports (/tools/isobuild/import-scanner.js:355:22)
    at /tools/isobuild/compiler-plugin.js:1040:17
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1008:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1059:8)
    at /tools/isobuild/bundler.js:830:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:821:18)
    at /tools/isobuild/bundler.js:2879:14
    at /tools/isobuild/bundler.js:2968:20
    at Array.forEach (native)
    at Function._.each._.forEach (/home/vagrant/.meteor/packages/meteor-tool/.1.5.0.1cs9qa8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2967:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2860:31)
    at /tools/isobuild/bundler.js:2807:32
    at Object.withCache (/tools/fs/files.js:1652:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2807:16)
    at /tools/runners/run-app.js:588:36
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:587:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:631:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12
```

i will continue to investigate, but after a diff between the 2 version of the app, there is not so much difference that could explain this problem.

**Comment by formspoint** [comment] 2017-07-03 12:49
I got this error too when updating to 1.5, every time it was because I wasn’t doing defense checks in the code before using something.

**Comment by joshuadavidson** [comment] 2017-07-03 15:43
@formspoint I'm not familiar with "defense checks". Can you give an example?

**Comment by joshuadavidson** [comment] 2017-07-06 16:09
@hwillson after looking at #8840 and #8878 I decided to update the same project but with a user that doesn't have a space in their name (e.g. C:\Users\dev rather than C:\Users\Joshua Davidson)--it upgraded and ran without an issue. Seems like the space in Windows user directories is causing quite the collection of issues. Hope this helps.

**Comment by hwillson** [comment] 2017-09-27 17:30
As mentioned in https://github.com/meteor/meteor/issues/8740#issuecomment-313442882, this issue is being caused by having a space in the user home directory name. Issue https://github.com/meteor/meteor/issues/8840 is currently tracking this problem (and is `pull-requests-encouraged` if anyone is interested 🙂), so I'll close this issue for now. Thanks!

**Closed by hwillson** 2017-09-27 17:30 UTC
