### ISSUE TITLE
meteor test --once not working

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#7272] opened 2016-06-21 23:06 UTC
I'm trying to run a CI test script using the following command:

`meteor test --once --settings private/dev/test-settings.json --driver-package dispatch:mocha-phantomjs`

This command is laid out in the Meteor guide. It's supposed to exit after the test run, however it doesn't exit. After the tests run, it sits with this output:

```
I20160621-19:02:13.185(-4)? --------------------------------
I20160621-19:02:13.185(-4)? ----- RUNNING CLIENT TESTS -----
I20160621-19:02:13.185(-4)? --------------------------------
I20160621-19:02:13.185(-4)?
I20160621-19:02:42.040(-4)? All client and server tests finished!
I20160621-19:02:42.041(-4)?
I20160621-19:02:42.042(-4)? --------------------------------
I20160621-19:02:42.042(-4)? SERVER FAILURES: 0
I20160621-19:02:42.042(-4)? CLIENT FAILURES: 2
I20160621-19:02:42.042(-4)? --------------------------------
=> Started your app.

=> App running at: http://localhost:3000/
```

I also don't actually have any client tests, so I'm not sure where those 2 failures are coming from.

**Comment by abernix** [comment] 2016-07-01 12:40
I wasn't able to reproduce this problem when testing with the `todos` app (it worked fine for me), but you didn't provide specifics (i.e. Meteor version, `dispatch:mocha-phantomjs` version, etc.) so there might be some differences in my setup.

If you'd like this re-opened, could you:

 * Try the [`todos` app](http://meteor.com/todos) and see if it works for you?  It provides tests out of the box and the same command you're using works there (and works for me)
 * Provide version numbers and a reproduction repo
 * Check recently resolved bugs with the [dispatch:* project](https://github.com/DispatchMe/meteor-mocha-phantomjs), as if this is a bug it would likely have to be fixed over there since [meteor code for `--once` is pretty straight forward](https://github.com/meteor/meteor/blob/release-1.4/tools/runners/run-all.js#L260-L285).

Closing, but happy to reopen.

**Closed by abernix** 2016-07-01 12:40 UTC
Labels: bug, Impact:some, Project:Testing, Severity:blocks-development

**Comment by clayne11** [comment] 2016-07-01 17:33
This got fixed in the latest release of `dispatch:mocha-phantomjs`. I just upgarded and tested it and it's all good.

**Comment by Redroest** [comment] 2017-07-11 11:16
@abernix I have exactly the same issue. Locally it works on a Linux Fedora 25 laptop. It also works on my local Windows 10 laptop in git bash. However, it doesn't work in my CodeBuild project that runs Linux Ubuntu 14

Here are the commands merged into one file to show what commands its running. I'm using these both locally and on my Continuous Integration setup:
```
#!/usr/bin/env bash

export MONGO_URL=***** #Hidden but working
export SERVER_TEST_REPORTER=xunit
export CLIENT_TEST_REPORTER=xunit
export TEST_BROWSER_DRIVER=nightmare

echo Installing Meteor
curl https://install.meteor.com/ | sh
echo Installing nightmare to run tests with
npm i --save-dev nightmare
echo Installing meteor npm dependencies
cd src && meteor npm install

echo Starting unit and integration tests
meteor test --once --allow-superuser --driver-package dispatch:mocha

echo Starting build
meteor build .. --allow-superuser --directory
cd ../bundle/programs/server && npm install --production && cd ../../../
echo "-----------------------------------"
echo Finished!
echo "-----------------------------------"

```

And here's the log file obtained from my build slave:
```
[[[[[ Tests ]]]]]

=> Started proxy.
[34mI20170711-10:59:31.568(0)? [39m
[34mI20170711-10:59:31.637(0)? [39m--------------------------------
[34mI20170711-10:59:31.638(0)? [39m----- RUNNING SERVER TESTS -----
[34mI20170711-10:59:31.639(0)? [39m--------------------------------
[34mI20170711-10:59:31.640(0)? [39m
[34mI20170711-10:59:31.643(0)? [39m<testsuite name="Mocha Tests" tests="1" failures="0" errors="0" skipped="0" timestamp="Tue, 11 Jul 2017 10:59:31 GMT" time="0.137">
[34mI20170711-10:59:31.644(0)? [39m<testcase classname="Tasks methods" name="can delete owned task" time="0.009"/>
[34mI20170711-10:59:31.645(0)? [39m</testsuite>
[34mI20170711-10:59:31.645(0)? [39m
[34mI20170711-10:59:31.646(0)? [39m--------------------------------
[34mI20170711-10:59:31.647(0)? [39m----- RUNNING CLIENT TESTS -----
[34mI20170711-10:59:31.647(0)? [39m--------------------------------
=> Started your app.

=> App running at: http://localhost:3000/
```

**Comment by Redroest** [comment] 2017-07-11 14:40
Another update. I've disabled client side tests by putting `TEST_CLIENT=0`. Now it works. I'm running in AWS CodeBuild. I think I've found the reason :) Its related to:

https://github.com/segmentio/nightmare/issues/534 #

**Comment by Redroest** [comment] 2017-07-12 09:34
SOLVED!! I've narrowed down the issue to the Continuous integration server. @clayne11 

I'm using AWS CodeBuild and these servers don't have displays. When running nightwatch or similar, these servers need some extra things. That's where xvfb steps in (for ubuntu). Look at this thread: https://github.com/segmentio/nightmare/issues/224

I've tried a couple of things and this one turned out to work for me on AWS CodeBuild running Ubuntu with nodejs v4.4.7: 

**test.sh:**
```
#!/usr/bin/env bash

apt-get update &&\
    apt-get install -y libgtk2.0-0 libgconf-2-4 \
    libasound2 libxtst6 libxss1 libnss3 xvfb

# Start Xvfb
Xvfb -ac -screen scrn 1280x2000x24 :9.0 &
export DISPLAY=:9.0

export SERVER_TEST_REPORTER=xunit
export CLIENT_TEST_REPORTER=spec
export TEST_BROWSER_DRIVER=nightmare

cd src && meteor test --once --allow-superuser --driver-package dispatch:mocha
```
