### ISSUE TITLE
1.5.2 Rebuilding hangs on rebuilding local packages

### ISSUE THREAD

**Issue by kirstu** [meteor/meteor#9094] opened 2017-09-15 06:59 UTC
With Meteor 1.5.2 I'm having an issue where the build process hangs at `_buildLocalPackages` phase when rebuilding the project after a file change. All the developers at our company are affected, so it seems at least that with our project the issue reproduces. We have a total of 116 local packages and 200 top level node modules. All are running macOS Sierra with MBP's.

Here's the relevant console output from `METEOR_PROFILE=1 METEOR_LOG=debug meteor run --verbose`:
```
|  Preparing project                         |
| ProjectContext prepareProjectForBuild........................82,705 ms (1)
| ├─ _initializeCatalog.............................................7 ms (1)
| │  ├─ LocalCatalog#initialize.....................................5 ms (1)
| │  │  └─ LocalCatalog#_loadLocalPackages                          4 ms (1)
| │  └─ other _initializeCatalog                                    1 ms
| ├─ _resolveConstraints...........................................36 ms (1)
| │  ├─ Select Package Versions....................................16 ms (1)
| │  │  ├─ new CS.Input                                            15 ms (1)
| │  │  └─ other Select Package Versions                            1 ms
| │  └─ other _resolveConstraints                                  20 ms
| ├─ _downloadMissingPackages.....................................132 ms (1)
| │  ├─ Isopack.readMetadataFromDirectory..........................13 ms (116)
| │  │  ├─ files.stat                                               2 ms (116)
| │  │  ├─ files.readFile                                           6 ms (116)
| │  │  └─ other Isopack.readMetadataFromDirectory                  6 ms
| │  └─ other _downloadMissingPackages                            118 ms
| ├─ _buildLocalPackages.......................................82,529 ms (1)
| │  ├─ IsopackCache Load local isopack............................10 ms (116)
| │  │  ├─ Isopack#getStrongOrderedUsedAndImpliedPackages           7 ms (116)
| │  │  └─ other IsopackCache Load local isopack                    3 ms
| │  └─ other _buildLocalPackages                              82,518 ms
| └─ _saveChangedMetadata                                           1 ms (1)
|
| Top leaves:
| other _buildLocalPackages...............................82,518 ms (1)
| other _downloadMissingPackages.............................118 ms (1)
|
| (#6) Total: 82,705 ms (ProjectContext prepareProjectForBuild)
```

On the first build this step completes a lot faster.

**Comment by jorgeer** [comment] 2017-09-19 11:56
Same problem.

**Comment by jorgeer** [comment] 2017-09-22 07:37
Noticing that local packages seem to be rebuilding every time, even if they have not been touched. surely that is not necessary?

**Comment by pmcochrane** [comment] 2017-09-22 08:40
I too encountered this with long rebuild times even for a simple scss file change. I have reverted to 1.5.1 for now.

**Comment by spencern** [comment] 2017-09-22 21:00
We're seeing this same problem at Reaction and have reverted to 1.5.1 https://github.com/reactioncommerce/reaction/issues/2933 with app rebuilds jumping from ~25 seconds to 2.5 minutes or longer.

It seems that CFS may be the culprit in our case as I've seen it popup after getting the `Downloading missing packages` message that #9125 refers to. The specific message referring to cfs is `Preparing to build package cfs:worker` (and a few other `cfs:` prefixed packages, but `worker` is the one that takes the longest.

**Comment by arist0tl3** [comment] 2017-09-23 18:56
Has anyone had success with 1.6? 

1.5.1 wasn't great in my project, as we kept running into caching issues in the rebuild process. Not eager to go back to that.

**Comment by spencern** [comment] 2017-09-23 21:07
@arist0tl3 We're experimenting with 1.6 beta, have some other issues to work out during that upgrade, will keep you in the loop.

**Comment by Rongky** [comment] 2017-09-25 06:04
Same here too. I have recently switched to using SSD, yet the build time is still really really slow. I’m on ubuntu 16.04, meteor 1.5.2 and using package-based architecture.

Below is the result of meteor profiling, and the buildLocalPackages is at 118,559 ms...

| (#88) Profiling: ProjectContext prepareProjectForBuild
| Preparing project 
| ProjectContext prepareProjectForBuild................................…120,199 ms (1)
| ├─ _initializeCatalog............................................................................…310 ms (1)
| │ └─ LocalCatalog#initialize.............................................................…298 ms (1)
| │ └─ LocalCatalog#_loadLocalPackages.....................................…277 ms (1)
| │ ├─ PackageSource#initFromPackageDir ...................................163 ms (20)
| │ └─ other LocalCatalog#_loadLocalPackages ...........................113 ms
| ├─ _resolveConstraints .........................................................................193 ms (1)
| ├─ _downloadMissingPackages…..................................................1,131 ms (1)
| │ ├─ Isopack.readMetadataFromDirectory ..................................141 ms (185)
| │ └─ other _downloadMissingPackages .......................................991 ms
| └─ _buildLocalPackages…...........................................................118,559 ms (1)
| ├─ IsopackCache Load local isopack............................................. 203 ms (185)
| ├─ IsopackCache Build local isopack…...........................................994 ms (10)
| │ ├─ Isopack#saveToPath.................................................................. 156 ms (1)
| │ └─ other IsopackCache Build local isopack............................. 692 ms
| └─ other _buildLocalPackages .................................................117,362 ms
|
| Top leaves:
| other _buildLocalPackages.....................................................…117,362 ms (1)
| other _downloadMissingPackages..............................................…991 ms (1)
| other IsopackCache Build local isopack....................................…692 ms (10)
| other LocalCatalog#_loadLocalPackages.................................…113 ms (1)
|
| (#88) Total: 120,199 ms (ProjectContext prepareProjectForBuild)
|
| Top leaves:
| other ClientTarget#minifyCss…...................................................1,189 ms (2)
| Target#minifyJs..................................................................................…812 ms (2)
| other PackageSourceBatch.computeJsOutputFilesMap…....572 ms (2)
| CssTools.parseCss.............................................................................…489 ms (38)
| Babel.compile.....................................................................................…427 ms (734)
| other plugin ecmascript.................................................................…400 ms (2)
| CssTools.stringifyCss........................................................................…354 ms (2)
| linker File#getPrelinkedOutput...................................................…354 ms (96)
| wrapped.fs.readFileSync.................................................................…299 ms (671)
| other Target#_runCompilerPlugins...........................................…295 ms (3)
| sha1.......................................................................................................…260 ms (5662)
| other linker Module#getPrelinkedFiles...................................…203 ms (2)
| ImportScanner#_getInstallPath…..................................................196 ms (4238)
| other PackageSourceBatch#_linkJS..........................................…184 ms (316)
| getPrelinkedFiles toStringWithSourceMap...........................…177 ms (3)
| Isopack#getUnibuildAtArch........................................................…158 ms (15290)
| other plugin templating-compiler............................................…130 ms (2)
| other Target#make.........................................................................…128 ms (3)
| files.rm_recursive….............................................................................113 ms (406)
| other JsImage#write…......................................................................106 ms (1)
|
| (#89) Total: 9,311 ms (Rebuild App)

**Comment by hwillson** [comment] 2017-09-25 14:01
Any chance anyone here could create a reproduction showing this happening, or share their full project? This issue is definitely becoming more popular (and showing up in related issues like https://github.com/meteor/meteor/issues/9125).

**Comment by benjamn** [comment] 2017-09-25 14:05
@hwillson Although it isn't minimal by any means (the entire Reaction Commerce app), https://github.com/reactioncommerce/reaction/issues/2933 contains a reliable reproduction.

**Comment by benjamn** [comment] 2017-09-25 17:10
Can you try updating to Meteor 1.5.2.1-rc.1 to see if the problem is fixed by https://github.com/meteor/meteor/commit/5d212926e795bba714abc9ca2b86429eff2831dd?
```sh
meteor update --release 1.5.2.1-rc.1
```

**Comment by spencern** [comment] 2017-09-25 18:05
Our app will not start with 5d21292
```
=> Errors prevented startup:

   While minifying app stylesheet:
   /tools/isobuild/bundler.js:1902:28: Cannot find module "autoprefixer"
   at Object.require (/tools/isobuild/bundler.js:1902:28)
   at packages/minifier-postcss/plugin/minify-css.js:52:37
   at Array.forEach (native)
   at getPostCSSPlugins
   (packages/minifier-postcss/plugin/minify-css.js:51:43)
   at packages/minifier-postcss/plugin/minify-css.js:155:36
   at Array.map (native)
   at mergeCss (packages/minifier-postcss/plugin/minify-css.js:139:23)
   at CssToolsMinifier.processFilesForBundle
   (packages/minifier-postcss/plugin/minify-css.js:109:18)
```
ran `meteor npm install` with no changes

I tried installing `autoprefixer` manually which did not resolve the issue

I also checked using the `standard-minifier-js` in place of `abernix:standard-minifier-js` which also did not change anything.

**Comment by benjamn** [comment] 2017-09-25 18:11
Ok, please be aware https://github.com/meteor/meteor/commit/5d212926e795bba714abc9ca2b86429eff2831dd is not the only change in 1.5.2.1, and this looks like something different (possibly https://github.com/meteor/meteor/pull/9133/commits/971d2b1272bd2b769d6e55cf1fa0efdd4498625b). Thanks for trying to work around it.

**Comment by benjamn** [comment] 2017-09-25 18:39
The culprit seems to be https://github.com/juliancwirko/meteor-postcss, which tries to import the `autoprefixer` npm package without depending on it.

You can work around this problem by cloning that package locally:
```sh
cd reaction/packages
git clone git@github.com:juliancwirko/meteor-postcss.git
```
Now edit `packages/meteor-postcss/package.js` to add `'autoprefixer': '7.1.4'` [here](https://github.com/juliancwirko/meteor-postcss/blob/d079d80d19e1d06ff90902e324cc078d0f00b198/package.js#L15).

**Comment by spencern** [comment] 2017-09-25 19:24
@benjamn Thanks for the workaround - not sure why I missed that the issue was in `meteor-postcss`. Your steps to add autoprefixer as a dependency to `meteor-postcss` have fixed the issue with startup.

Additionally, I can confirm that we are not seeing the package rebuilding issue in `1.5.2.1-rc.1` that is present in `1.5.2` so it seems like this fix is working.

**Comment by benjamn** [comment] 2017-09-25 21:46
@spencern We've published a `1.5.2.1-rc.2` that shouldn't require the workaround, fyi.

**Comment by spencern** [comment] 2017-09-26 01:48
@benjamn 
`1.5.2.1-rc.2` does solve the issue with having to include `meteor-postcss` in our packages directory.

The first few times I caused a rebuild by changing server code, it showed some aberrant behavior, but on the third change, was demonstrating rebuild times in line with `1.5.2.1-rc.1` with the workaround.

The first one was 84s, the second was 71s, the third 33s.
```
Rebuild App..................................................84,142 ms (1)
```

I've captured the whole rebuild here in case theres any reason to think something changed that could cause this behavior. https://gist.github.com/spencern/fe97d816910090a42e9154c6c12d130e

Since it's been normal after a few rebuilds, I'm inclined to think there was something going on on my machine rather than an issue with this release.

Thanks!

**Closed** 2017-09-26 16:26 UTC
Labels: Project:Isobuild, Project:Tool

**Comment by pmcochrane** [comment] 2017-09-27 08:47
The new release 1.5.2.1 seems to have resolved my issue above (a small css change taking ages to complete).
As a bonus it is now quicker than 1.5.1 so THANK YOU for the great work in a speedy fix.

I have to applaud you folks that resolve people's problems in what is effectively free software for the end user. Well done all involved.

**Comment by abernix** [comment] 2017-09-27 10:34
@pmcochrane Glad to hear it and thank you for the confirmation!  It's always great to know that the work which goes into those changes improves the developer experience.
