### ISSUE TITLE
Meteor deployment on Windows / IIS - fiber missing and npm won't install package

### ISSUE THREAD

**Issue by ejkelley** [meteor/meteor#5281] opened 2015-09-25 01:50 UTC
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Websites\simple-todos\bundle\programs\server\boot.js:1:75)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by stubailo** [comment] 2015-10-06 22:05
Is this a duplicate of https://github.com/meteor/meteor/issues/4906 ? Going to close unless commented otherwise.

**Closed by stubailo** 2015-10-06 22:05 UTC
