### ISSUE TITLE
simplesmtp@0.3.10 hangs the app

### ISSUE THREAD

**Issue by betacar** [meteor/meteor#6529] opened 2016-03-18 21:46 UTC
In Meteor@1.1.10, simplesmtp is used as default mail client for Mailgun. The 0.3.10 version has a bug where a counter cannot be increased because is a boolean. This is the stack trace:

````
/home/project/deployment/versions/2016-03-18_20.59.25/app/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:823
    this._xoauth2.reconnectCount = 0;
                                 ^
TypeError: Cannot assign to read only property 'reconnectCount' of false
    at SMTPClient._actionAUTHComplete (/home/project/deployment/versions/2016-03-18_20.59.25/app/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:823:34)
    at SMTPClient._onData (/home/project/deployment/versions/2016-03-18_20.59.25/app/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:329:29)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)
````
A description of the problem and solution can be found [here](http://www.meteorhub.org/t/npm-email-node-modules-simplesmtp-lib-client-js-823-this--xoauth2-reconnectcount-0/44). However, this a short term, since it would be replaced by the old version once the app is rebuild it again.

**Comment by aaronjudd** [comment] 2016-04-01 06:41
Shouldn't we be replacing simplesmtp since it's deprecated? 

>Simplesmtp is a module written for Node v0.6 and slightly updated for Node v0.8. It does not use Node v0.10 streams and probably is going to have a rocky future with Node v0.12. I do not have time to keep it up to date, the thing probably needs a major rewrite for Node v0.12.

**Comment by mlecoq** [comment] 2016-04-11 16:14
Same issue with Meteor@1.3.1

**Comment by betacar** [comment] 2016-04-11 16:47
@aaronjudd I agree. But, in that case, we will have to wait until the MDG decides which should be the future package.

**Comment by betacar** [comment] 2016-04-11 16:51
@mlecoq We found a temporary fix by manually installing the 0.3.34 version of simplesmtp into our deploy script, and after every build.
````shell
cd $ROOT_DIRECTORY/bundle/programs/server/npm/email
# Delete the defualt buggy version
rm -rf node_modules/simplesmtp
# Install the new one
npm install simplesmtp@0.3.34
````

**Comment by mlecoq** [comment] 2016-04-11 16:54
Thanks ! It works

**Comment by mlecoq** [comment] 2016-04-13 19:28
Could it be fixed in meteor 1.3.2 ? (the issue is still present in 1.3.2-rc.5)

**Comment by Sabst** [comment] 2016-05-23 20:20
@betacar Thanks!
In my case (different node/npm version), the first line is:
`cd $ROOT_DIRECTORY/bundle/programs/server/npm/node_modules/meteor/email`

@mlecoq In my environment and using 1.3.2.4 I did not have to hack npm-crypt though (this is not directly related to simplesmtp but as it was mentioned as another deployment pain...).

**Comment by abernix** [comment] 2016-07-15 11:27
Happy to say this is fixed in Meteor `1.4-beta.14` and should be fixed in `1.3.5-rc.1` as well (#7387).

While `simplesmtp` is now deprecated (and will eventually be replaced), the latest version appears to work fine on Node 4 (Meteor 1.4).

Closing, but please report back if problems still exist!

**Closed by abernix** 2016-07-15 11:27 UTC
Labels: Project:Utilities:Email

**Comment by SachaG** [comment] 2016-10-15 05:34
For some reason the `simplesmtp` package is still stuck at version `0.3.10` despite updating the `email` package to `1.0.15`: 

```
W20161015-14:04:03.984(9)? (STDERR) /Users/sacha/.meteor/packages/email/.1.0.15.18tuuin++os+web.browser+web.cordova/npm/node_modules/simplesmtp/lib/client.js:823
W20161015-14:04:03.985(9)? (STDERR)     this._xoauth2.reconnectCount = 0;
W20161015-14:04:03.985(9)? (STDERR)                                  ^
W20161015-14:04:03.985(9)? (STDERR)
W20161015-14:04:03.985(9)? (STDERR) TypeError: Cannot assign to read only property 'reconnectCount' of false
W20161015-14:04:03.986(9)? (STDERR)     at SMTPClient._actionAUTHComplete (/Users/sacha/.meteor/packages/email/.1.0.15.18tuuin++os+web.browser+web.cordova/npm/node_modules/simplesmtp/lib/client.js:823:34)
W20161015-14:04:03.986(9)? (STDERR)     at SMTPClient._onData (/Users/sacha/.meteor/packages/email/.1.0.15.18tuuin++os+web.browser+web.cordova/npm/node_modules/simplesmtp/lib/client.js:329:29)
W20161015-14:04:03.986(9)? (STDERR)     at emitOne (events.js:77:13)
W20161015-14:04:03.986(9)? (STDERR)     at TLSSocket.emit (events.js:169:7)
W20161015-14:04:03.986(9)? (STDERR)     at readableAddChunk (_stream_readable.js:153:18)
W20161015-14:04:03.986(9)? (STDERR)     at TLSSocket.Readable.push (_stream_readable.js:111:10)
W20161015-14:04:03.987(9)? (STDERR)     at TLSWrap.onread (net.js:536:20)
```

**Comment by SachaG** [comment] 2016-10-15 06:30
I'm not sure how to tell Meteor to update its own internal NPM packages, so for now the only way I was able to fix this was to manually update the offending file.

**Comment by tmeasday** [comment] 2016-10-17 00:11
But `1.0.15` is from July 8th

**Comment by tmeasday** [comment] 2016-10-17 00:11
The latest version is `email@1.1.17_1`

**Comment by SachaG** [comment] 2016-10-17 00:23
Oops, my bad! I followed the link to @abernix's PR to get the latest package version but didn't realize it linked to his own forked repo and not the main Meteor repo. Everything seems to be working fine now that I've updated to `1.1.17_1`.
