### ISSUE TITLE
Unordered dependency exports inconsistency

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#5279] opened 2015-09-24 19:35 UTC
**Problem**

When `{unordered: true}` is used for a dependency, the exports are still available without using the `Package` object. When running velocity package tests, though, the exports are _not_ available. I thought this was an issue with velocity, but then there is this comment, which disagrees with how things actually work: https://github.com/meteor/meteor/blob/a23cc0249217715cd160112a47c2fff6f5becf89/tools/isobuild/package-api.js#L119-L122

**Reproduction**

https://github.com/aldeed/temporary-testUnordered

**Resolution**

Need clear decision from MDG on what the correct behavior is, and then either Meteor tool or velocity needs to be fixed to match.

**Comment by benjamn** [comment] 2015-10-06 22:17
The `false,true,true,true` behavior is definitely the way this should work.

**Comment by aldeed** [comment] 2015-10-07 12:02
cc @Sanjo 

I'll leave this open so the comment can be fixed, too.

**Comment by Sanjo** [comment] 2015-10-07 17:45
I think this is a bug with the meteor test-packages command in the Meteor command line tool.

**Comment by abernix** [comment] 2016-11-01 14:50
I confirmed the original behavior in the attached repro but when that repro is updated to Meteor 1.4.2 it returns `false,true,true,true` as indicated as correct above.

@aldeed, @Sanjo Can this be closed?  And is there a comment that still needs to be updated?  Sorry, I realize this is relatively old, but trying to get it off the board. ;)

**Comment by hwillson** [comment] 2017-02-13 20:15
Since the original issue has been addressed (and there hasn't been any additional activity clarifying which comment needs to be updated), I'll close it off. Thanks for posting this originally!

**Comment by aldeed** [comment] 2017-02-13 20:54
@hwillson @abernix Sorry I never saw this. I'm fine with this being closed, but it does look like the incorrect comment is still there in the latest Meteor. Here is a PR that removes it: https://github.com/meteor/meteor/pull/8362

**Comment by hwillson** [comment] 2017-02-14 01:54
Great @aldeed, thanks! I'll re-open this issue until that PR is merged. Thanks again!

**Closed** 2017-02-14 17:03 UTC
Labels: bug, confirmed, fixed
