### ISSUE TITLE
[cordova] Inappbrowser White Screen during oAuth Login

### ISSUE THREAD

**Issue by brianscroggins24** [meteor/meteor#6882] opened 2016-04-22 20:27 UTC
Currently in one of my Meteor apps i'm using loginWithFacebook and loginWithGoogle auth along with the ServiceConfiguration package. When the inappbrowser comes up to login a user in they are able to enter their credentials. However when they submit those creds the the inappbrowser white screens. The activity only occurs on the device, on the simulator the inappbrowser disappears and logs the user in. I've tried every solution including adding the cordova-inappbrower-plugin to my project and adding loginStyle: 'popup' to the ServiceConfiguration but nothing has work. If anyone know of why this might be happening please shed some light. I'm working on iOS9 for both the simulator and the device.

**Comment by terenceng2010** [comment] 2016-05-09 09:32
Looks like an upstream issue
https://issues.apache.org/jira/plugins/servlet/mobile#issue/CB-11136

**Comment by terenceng2010** [comment] 2016-05-09 13:14
my current temporary fix to this issue is to override the cordova-plugin-inappbrowser plugin using by package oauth by adding this line in cordova-plugins:

`cordova-plugin-inappbrowser@https://github.com/ephemer/cordova-plugin-inappbrowser.git#04091fde737519c149e7ad6316971cb6b490c5b3`

**Comment by tekknikk** [comment] 2016-05-14 02:19
@terenceng2010 your fix works great.

**Comment by abernix** [comment] 2016-05-27 13:45
Per the debugging I did in #7102 and a repo that @mitiaptest posted, I'm re-posting the repo here as a reproduction for this problem so it will be easy to confirm when it's fixed.  I can confirm this issue and also confirm that it is resolved with the fix that @terenceng2010 suggested (command below)

##### Reproduction (see README.md for steps)
https://github.com/abernix/issue-6882

##### Workaround

    meteor add cordova:cordova-plugin-inappbrowser@https://github.com/ephemer/cordova-plugin-inappbrowser.git#04091fde737519c149e7ad6316971cb6b490c5b3

**Comment by hexsprite** [comment] 2016-12-05 21:41
@abernix I'm also having this issue. If it's as easy as upgrading the reference to the plugin couldn't this be released? Or is there concern about this causing some other impacts?

**Comment by hexsprite** [comment] 2016-12-05 21:50
OK, I dug a bit deeper and basically Google is deprecating this form of login. But in the meantime, it would be great to have a working Google oAuth with Meteor accounts on Cordova. So maybe we could cut a release with just this one patch enabled.

https://github.com/apache/cordova-plugin-inappbrowser/pull/162#issuecomment-243054022

In the near future switch to something like:
https://github.com/EddyVerbruggen/cordova-plugin-googleplus

**Comment by jlchereau** [comment] 2017-01-04 08:31
The future is https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller. The plugin works great on iOS but not on Android (see https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/issues/51).

For more information, check https://medium.com/@jlchereau/stop-using-inappbrowser-for-your-cordova-phonegap-oauth-flow-a806b61a2dc5

**Comment by abernix** [comment] 2017-01-04 14:41
Even if the previous two comments are true, the fix above (mentioned originally by @terenceng2010) is still progressing through the Cordova-sphere.  See apache/cordova-plugin-inappbrowser#187 which was merged yesterday.

When that lands the version Meteor includes can be bumped, possibly in conjunction with #8155.

**Comment by larssn** [comment] 2017-01-11 21:22
Fixed here https://github.com/apache/cordova-plugin-inappbrowser/commit/f32917df314f08296c53a4de0255a424be773184

**Comment by darkyen** [comment] 2017-01-26 13:22
A rather stable and more humble version of the safari tab plugin is at https://github.com/google/cordova-plugin-browsertab maybe Cordova should take that over?

**Comment by hwillson** [comment] 2017-09-08 13:00
Meteor is now using version 1.7.1 of `cordova-plugin-inappbrowser` (the most recent release), which includes the fix for this issue. Thanks!

**Closed by hwillson** 2017-09-08 13:00 UTC
Labels: bug, confirmed, Impact:some, Project:Mobile, Severity:has-workaround
