### ISSUE TITLE
Angular 2 app running perfectly locally (Meteor 1.21) won't run on Galaxy

### ISSUE THREAD

**Issue by dragGH102** [meteor/meteor#6476] opened 2016-03-13 14:07 UTC
**_1 Upvote**_ I am using **urigo:angular2-meteor** package to use Angular 2 instead of Blaze as Meteor frontend on Meteor 1.21, running on Linux Debian 8.

The following repository demonstrates the app which is giving this issue: https://github.com/dragGH102/angular2-meteor-part14

Locally it works perfectly (no errors at all and Angular 2 beta is quite verbose when it comes to print errors) when running **meteor run**.

whereas by running

> deploy someUrl.meteor.com

a long **list of JS errors** are printed on Google Chrome's DevTools' console, just like Galaxy used a different runtime / set of packages.

e.g.

```
d52c3ff13ff0e33472568f15418eb0010749cfde.js:101 EXCEPTION: No Directive annotation found on et.logError @ d52c3ff13ff0e33472568f15418eb0010749cfde.js:101
d52c3ff13ff0e33472568f15418eb0010749cfde.js:101 STACKTRACE:t.logError @ d52c3ff13ff0e33472568f15418eb0010749cfde.js:101
d52c3ff13ff0e33472568f15418eb0010749cfde.js:101 Error: No Directive annotation found on e
```

I initially posted the issue on the package repository (https://github.com/Urigo/angular-meteor/issues/1270) where additional information is available. However I believe that this is an issue with Meteor (Galaxy) or urigo:angular2-meteor themselves, not Angular, as **locally works perfectly**.

Also, I used to deploy other (non-Angular) apps in Meteor 1.20 and it didn't give any issue.

**Comment by xiaofeihe** [comment] 2016-03-13 16:29
Look here 
https://github.com/Urigo/meteor-angular2.0-socially/issues/36

**Comment by dragGH102** [comment] 2016-03-13 17:06
thanks for the input.
is it possible to deploy a Meteor app without many minification as a
temporary workaround to this issue?

**Comment by jeveloper** [comment] 2016-03-13 23:21
Workaround 

Set uglify.mangle to false for now.

**Comment by dragGH102** [comment] 2016-03-14 00:23
thanks @jeveloper .
How do I do exactly?
I found somewhere that I need to modify Meteor 's source code. is that the way?

**Comment by jeveloper** [comment] 2016-03-14 14:09
@dragGH102  Hey
I read of that and wanted to share with you.

I have a theory that it can be done differently, i'd really appreciate if others would share what they know.

I noticed that uglifyjs has parameters -nm or -no-mangle , however how do you pass that to meteor??
I could not find it.
Hack would be to go ahead and modify uglifyjs within .meteor and change default setting to false

https://github.com/shekhargulati/meteor-leaderboard-openshift-quickstart/blob/master/server/node_modules/uglify-js/bin/uglifyjs

var options = {
    ast: false,
    consolidate: false,
    mangle: **true,**
    mangle_toplevel: false,
    no_mangle_functions: false,
    squeeze: true,
    make_seqs: true,
......

**Comment by zol** [comment] 2016-03-14 22:17
@benjamn do we have a cleaner way to pass options through to uglify?

**Comment by jeveloper** [comment] 2016-03-15 14:13
Definitely needs to be a better way to control options to all the tools that are involved in meteor deploy

**Comment by dragGH102** [comment] 2016-03-18 11:15
+1 definitely agree.
hopefully Angular 2 stable release will have this fixed completed

**Comment by Urigo** [comment] 2016-04-12 21:29
keeping for reference - https://github.com/angular/angular/issues/6380

**Comment by FlawaCLV** [comment] 2016-08-30 15:41
@Urigo the issue [angular/angular#6380](https://github.com/angular/angular/issues/6380) seems to be solved & closed but I still get the error.

Using `METEOR@1.4.0.1`
```json
"dependencies": {
    "@angular/common": "^2.0.0-rc.4",
    "@angular/compiler": "^2.0.0-rc.4",
    "@angular/core": "^2.0.0-rc.4",
    "@angular/platform-browser": "^2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.4",
    "angular2": "^2.0.0-beta.17",
    "angular2-meteor": "^0.6.0",
    "angular2-meteor-polyfills": "^0.1.1",
    "...": "..."
  }

**Comment by Urigo** [comment] 2016-10-04 08:57
@dragGH102 @FlawaCLV please try the latest `angular2-meteor@0.7.0` package with `angular2-compilers@0.6.2_1` and the latest Angular 2.0 stable.
Let me know if this particular error still happens.

**Comment by FlawaCLV** [comment] 2016-10-04 18:46
@Urigo I've upgraded everything but now I encounter another problem `Zone.js has detected that ZoneAwarePromise (window|global).Promise has been overwritten`

Here is my `package.json` dependencies:
```json
"dependencies": {
    "@angular/common": "^2.0.1",
    "@angular/compiler": "^2.0.1",
    "@angular/core": "^2.0.1",
    "@angular/forms": "^2.0.1",
    "@angular/platform-browser": "^2.0.1",
    "@angular/platform-browser-dynamic": "^2.0.1",
    "angular2": "^2.0.0-beta.17",
    "angular2-meteor": "^0.7.0",
    "angular2-meteor-polyfills": "^0.1.1",
    "bcrypt": "^0.8.7",
    "bluebird": "^3.4.6",
    "chart.js": "^2.3.0",
    "es6-shim": "^0.35.1",
    "meteor-node-stubs": "^0.2.3",
    "reflect-metadata": "^0.1.2",
    "rxjs": "^5.0.0-beta.12",
    "ui-router-ng2": "^1.0.0-beta.3",
    "zone.js": "^0.6.25"
  }
```
and here are my meteor packages:
```text
meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.12                   # The database Meteor supports right now
reactive-var@1.0.10            # Reactive variable for tracker
jquery@1.11.9                  # Helpful client-side library
tracker@1.1.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.2.0   # CSS minifier run for production mode
#standard-minifier-js@1.1.8    # JS minifier run for production mode
es5-shim@4.6.14                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.5.8              # Enable ECMAScript2015+ syntax in app code

angular2-compilers@0.6.2_1
barbatus:angular2-runtime
deanius:promise
momentjs:moment
fortawesome:fontawesome
dburles:collection-helpers
accounts-password@1.3.0
promise@0.8.4
meteorhacks:ssr
email@1.1.17
jalik:ufs
jalik:ufs-local
service-configuration@1.0.10
accounts-facebook@1.0.10
accounts-google@1.0.10
accounts-twitter@1.1.11
percolate:synced-cron
shell-server
```
Any ideas ?

**Comment by Urigo** [comment] 2016-10-12 21:22
@FlawaCLV why do you have two different versions of `angular`?

`"@angular/common": "^2.0.1",`
`"angular2": "^2.0.0-beta.17",`

Also, you have some old dependencies...  
Maybe look into a fresh `angular2-meteor` project and update the dependencies from there?

**Comment by abernix** [comment] 2016-12-12 18:43
Thanks for reporting this originally.  I'm going to close this as I think this has gone idle but I believe the need to do that has been solved.  If there is still sufficient need for the ability to tweak UglifyJS settings, that should be opened in a new feature request issue.

@dragGH102 If you're still experiencing this, please create a fresh reproduction using the latest versions of Angular and Meteor and provide it here.
@FlawaCLV Please create a simple reproduction of your problem using the latest `angular2-meteor` project and and open a new issue if the problem persists.

**Closed by abernix** 2016-12-12 18:43 UTC
