### ISSUE TITLE
Meteor 1.5.2 underscore error

### ISSUE THREAD

**Issue by p3pp8** [meteor/meteor#9058] opened 2017-09-05 13:58 UTC
Just updated to release 1.5.2 my project stopped working with the following error:

` Error running template: TypeError: _.escape is not a function
    at eval (eval at <anonymous> (packages/underscore.js:1266:16), <anonymous>:6:28)
    at template (packages/underscore.js:1274:21)
    at packages/boilerplate-generator/template-web.browser.js:29:7
    at Array.map (native)
    at Function._.map._.collect (packages/underscore.js:157:56)
    at Boilerplate.template (packages/boilerplate-generator/template-web.browser.js:28:7)
    at Boilerplate.toHTML (packages/boilerplate-generator/generator.js:30:12)
    at packages/webapp/webapp_server.js:322:33
    at /Users/XXX/.meteor/packages/promise/.0.9.0.153itm7++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:39
`
The exception is thrown immediately, i think no code is yet executed.
Any suggestion is well appreciated!

**Comment by zimme** [comment] 2017-09-05 21:21
I've looked at the code in `boilerplate-generator.js` and `template-web.browser.js` and can't see anything that would explain this. The package does have and use `underscore` as a dependency so I don't know why this errors out.

I've just updated one of my apps to `1.5.2` and I can't reproduce this.

It would be really helpful if you could make a reproduction repo of this error.

**Comment by hexsprite** [comment] 2017-09-05 22:46
@p3pp8 does this only happen with the meteor shell open? if so I saw an issue like this before

**Comment by p3pp8** [comment] 2017-09-06 07:14
@hexsprite No, the shell isn't open. Thanx for the support guys, anyway, i've discovered this started to happens after i've updated these packages to the following versions:

` 
babel-compiler         upgraded from 6.19.4 to 6.20.0
boilerplate-generator  upgraded from 1.1.1 to 1.2.0
ddp-client             upgraded from 2.0.0 to 2.1.0
minimongo              upgraded from 1.2.1 to 1.3.0
modules                upgraded from 0.9.4 to 0.10.0
mongo                  upgraded from 1.1.22 to 1.2.0
mongo-dev-server       added, version 1.0.1
promise                upgraded from 0.8.9 to 0.9.0
webapp                 upgraded from 1.3.17 to 1.3.18
`

There must be something wrong, i'm afraid this could depend on something i did wrong or connected somehow to my project dependencies... At the moment i'm stuck to the ver 1.5.1 . I'll try to reproduce this on a dummy project and share it. Thanx

**Comment by p3pp8** [comment] 2017-09-06 07:24
The exception output was incomplete, sorry guys, in the first line of the exception there is the JS resource where the exception happens and the script line number:

`E20170906-09:20:08.940(2) (webapp_server.js:789)`

Hope this may help...

Thanx!

**Comment by p3pp8** [comment] 2017-09-07 14:24
Some more info...

```

babel-compiler         upgraded from 6.19.4 to 6.20.0
boilerplate-generator  upgraded from 1.1.1 to 1.2.0
ddp-client             upgraded from 2.0.0 to 2.1.0
ejson                  upgraded from 1.0.13 to 1.0.14
minimongo              upgraded from 1.2.1 to 1.3.0
modules                upgraded from 0.9.4 to 0.10.0
mongo                  upgraded from 1.1.22 to 1.2.0
mongo-dev-server       added, version 1.0.1
promise                upgraded from 0.8.9 to 0.9.0
webapp                 upgraded from 1.3.17 to 1.3.18


```
None of my code is executed, instead the following exception arises immediately after trying to open the app index page. It seems to be an internal error, i'm stuck at version 1.5.1.
```

E20170907-10:48:33.442(2) (webapp_server.js:789) Error running template: TypeError: _.escape is not a function
    at eval (eval at <anonymous> (packages/underscore.js:1266:16), <anonymous>:6:28)
    at template (packages/underscore.js:1274:21)
    at packages/boilerplate-generator/template-web.browser.js:29:7
    at Array.map (native)
    at Function._.map._.collect (packages/underscore.js:157:56)
    at Boilerplate.template (packages/boilerplate-generator/template-web.browser.js:28:7)
    at Boilerplate.toHTML (packages/boilerplate-generator/generator.js:30:12)
    at packages/webapp/webapp_server.js:322:33
    at /Users/Giuseppe/.meteor/packages/promise/.0.9.0.153itm7++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:39
Y

```
Any help is highly appreciated!

Thanx!


METEOR LIST
```

abernix:standard-minifier-js   2.1.0  Harmony javascript minifiers used with Meteor apps by default.
awatson1978:browser-detection  1.0.4  Meteorite package that provides browser detection.
base64                         1.0.10  Base64 encoding and decoding
deanius:promise                3.1.3  Utilities for Promise-based wrappers, method calls, helpers and HTTP in Meteor
dynamic-import                 0.1.1  Runtime support for Meteor 1.5 dynamic import(...) syntax
email                          1.2.3  Send email messages
es5-shim                       4.6.15  Shims and polyfills to improve ECMAScript 5 support
http                           1.2.12  Make HTTP calls to remote servers
iron:router                    1.1.2  Routing specifically designed for Meteor
jquery                         1.11.10  Manipulate the DOM using CSS selectors
meteor-base                    1.1.0  Packages that every Meteor app needs
mobile-experience              1.0.4  Packages for a great mobile user experience
pbastowski:angular-babel       1.3.7  Babel compiler and ng-annotate for Meteor 1.3
reactive-var                   1.0.11  Reactive variable
rwatts:uuid                    0.1.0  Easily generate a UUID on the client or server.
session                        1.1.7  Session variable
standard-minifier-css          1.3.4  Standard css minifier used with Meteor apps by default.
tarang:ssl                     1.0.1  Secure your application
tracker                        1.1.3  Dependency tracker to allow reactive callbacks
u2622:persistent-session       0.4.4  Persistently store Session data on the client
urigo:static-templates         0.1.3  Meteor plugin for importing static HTML templates"


```
NPM DEPENDENCIES

    "@uirouter/angularjs": "^1.0.6",
    "amqp": "^0.2.6",
    "angular": "^1.6.6",
    "angular-animate": "^1.6.6",
    "angular-aria": "^1.6.6",
    "angular-filter": "^0.5.16",
    "angular-i18n": "^1.6.6",
    "angular-material": "^1.1.5",
    "angular-messages": "^1.6.6",
    "angular-meteor": "^1.3.12",
    "angular-qr": "^0.2.3",
    "angular-sanitize": "^1.6.6",
    "angular-translate": "^2.15.2",
    "aws-sdk": "^2.110.0",
    "babel-runtime": "^6.26.0",
    "big-integer": "^1.6.25",
    "blob-stream": "^0.1.3",
    "cryptico": "^1.0.2",
    "deepmerge": "^1.5.1",
    "excel4node": "^1.2.1",
    "google-libphonenumber": "^2.0.19",
    "google-maps": "^3.2.1",
    "hashids": "^1.1.1",
    "http-proxy": "^1.16.2",
    "i18n": "^0.8.3",
    "meteor-node-stubs": "^0.2.11",
    "meteor-typings": "^1.4.1",
    "moment": "^2.18.1",
    "npm-shrinkwrap": "^6.0.2",
    "pg": "^6.4.2",
    "proxy-agent": "^2.1.0",
    "pubnub": "^4.15.1",
    "pubnub-angular": "^4.0.2",
    "screenfull": "^3.3.1",
    "sprintf-js": "^1.1.1",
    "winston": "^2.3.1"

**Comment by crapthings** [comment] 2017-09-12 02:42
try change this abernix:standard-minifier-js to standard-minifier-js ?

and what is your package order in this file ?
.meteor/packages

**Comment by p3pp8** [comment] 2017-09-13 10:24
@crapthings Thanx for suggestions, i discovered the problem and it was depending on some of my code that accidentally was overriding underscore '_' symbol. I must admit, i'm a bit ashamed for that. Thanx to everyone for your time and support!!!

**Comment by hwillson** [comment] 2017-09-13 11:11
Based on https://github.com/meteor/meteor/issues/9058#issuecomment-329125570, it sounds like we can close this. Thanks!

**Closed by hwillson** 2017-09-13 11:11 UTC

**Comment by stefanocudini** [comment] 2017-09-28 18:38
I have similar escaping problem from 1.5.1 to 1.5.2 but meteor shell don't show errors, here the issue: #9149
