### ISSUE TITLE
Babili minification error with 1.5-beta.12

### ISSUE THREAD

**Issue by jasongrishkoff** [meteor/meteor#8523] opened 2017-03-27 11:28 UTC
Tried uploading 1.5-beta.12 to my Galaxy and came up with the following error.  Could be related to the cfs:gridfs package.

I rolled back to 1.5-beta.10, and it uploaded without issue.

```
Talking to Galaxy servers at https://us-east-1.galaxy-deploy.meteor.com
Deploying your app...

Errors prevented deploying:
While minifying app code:
packages/minifyStdJS_plugin.js:107:26: Babili minification error within packages/cfs_power-queue.js:
packages/cfs:power-queue/power-queue.js, line 533

unknown: Deleting local variable in strict mode:

delete invocation;

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS_plugin.js:107:26)
at packages/minifyStdJS_plugin.js:141:11
at Array.forEach (native)
at MeteorBabelMinifier.processFilesForBundle (packages/minifyStdJS_plugin.js:125:9)
```

**Comment by abernix** [comment] 2017-03-27 12:14
Thanks for reporting this!

I believe this should be fixed in `meteor-babel`'s https://github.com/meteor/babel/commit/ea74a69288717f4dec032bb06f4287a3379af11d which is included in `meteor-babel@0.18.1`.  This has been committed to the [1.5 release branch](https://github.com/meteor/meteor/pull/8327) in [this commit](https://github.com/meteor/meteor/pull/8327/commits/6842ec9c8a1f85c7e49c2dd02aefea93ce8b4daf), but was made right after the last `beta` release was cut so is not currently included in any releases.

You could try [running from a checkout](https://github.com/meteor/meteor/blob/devel/Development.md#running-from-a-git-checkout) to see if the problem is fixed for you, just make sure to check out the `release-1.5` branch before doing so.

**Comment by hwillson** [comment] 2017-04-04 18:13
Hi @jasongrishkoff - just a quick FYI, the fix for this is available in the [`1.5-beta.13`](https://github.com/meteor/meteor/blob/b490d270f1d1b340c2186018d552c06fbb064a08/packages/babel-compiler/package.js#L13) release (`meteor update --release 1.5-beta.13`). Let us know if it's fixed or if you're still encountering issues. Thanks!

**Comment by jasongrishkoff** [comment] 2017-04-04 18:15
@hwillson yep, I tried beta.13 and it did indeed fix this; but it caused such a huge headache in other areas :( #8536

**Comment by hwillson** [comment] 2017-04-04 18:20
Okay, thanks for the follow up @jasongrishkoff - I'll close this one off then.

**Closed by hwillson** 2017-04-04 18:20 UTC
Labels: bug, known-fix
