### ISSUE TITLE
Ready callback for autopublish

### ISSUE THREAD

**Issue by malhal** [meteor/meteor#4854] opened 2015-08-01 01:19 UTC
Currently you can add an onReady call back param to the subscribe function but currently there is no way to know when an auto-published subscription is ready. E.g. something along the lines of this:

```
Meteor.autopublishReady(function onReady() {
});
```

Alternatively it would be great to know when all subscriptions are ready, e.g.

```
Meteor.allSubscriptionsReady(function onReady() {
});
```

The reason I ask for this is find doesn't return any records until the subscription is ready, so as soon as you want to use find you have to leave autopublish behind and use subscriptions.

**Comment by stubailo** [comment] 2015-08-03 17:42
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I think this would be a great idea - I also run into the problem of having to switch to manual subscriptions just to get the readiness state.

**Comment by mitar** [comment] 2016-07-29 21:51
Yes, please do this.

**Comment by mitar** [comment] 2016-07-29 21:51
(Also having a reactive source for that would be great.)

**Comment by mitar** [comment] 2017-04-24 04:13
Hm, I see that this is probably a duplicate of #8146.

**Comment by hwillson** [comment] 2017-04-24 12:48
Hmm, looks like it. Seems to be about the same amount of discussion in both issues, but #8146 gets a little more into detail (and has more discussion about how this could work / be implemented). Let's continue the discussion there - closing this one. Thanks @mitar!

**Closed by hwillson** 2017-04-24 12:48 UTC
Labels: feature, Project:DDP
