### ISSUE TITLE
Using Plugin.registerSourceHandler(), how can you compile regular .js files? 

### ISSUE THREAD

**Issue by faceyspacey** [meteor/meteor#4823] opened 2015-07-28 03:51 UTC
with ```Plugin.registerSourceHandler(fileExtension, handler)``` how can you compile regular js files, rather than just files ending with special extensions? I'd like to make some small changes to my code at this point. Perhaps there's another better way to accomplish this??

**Comment by Slava** [comment] 2015-07-28 03:54
It is not possible with the registerSourceHandler API but it is possible with the upcoming Batch Plugins API. See the example in this core package called `ecmascript`: https://github.com/meteor/meteor/blob/2229fdfd25e625109ba49ae4c31e1c81574bf8b8/packages/ecmascript/plugin.js#L69

Also, closing as a duplicate of https://github.com/meteor/meteor/issues/3508 :)

**Closed by Slava** 2015-07-28 03:54 UTC
