### ISSUE TITLE
Negative sessions in Meteor Server Facts

### ISSUE THREAD

**Issue by cscott** [meteor/meteor#3490] opened 2015-01-17 02:01 UTC
Interesting, no?
![meteor-server-facts](https://cloud.githubusercontent.com/assets/156080/5787165/d3c34cb2-9dc2-11e4-9271-d3bf1c194f8c.png)

This meteor app is under heavy load during mystery hunt... and it's not doing so well.

**Comment by mquandalle** [comment] 2015-01-17 03:34
I think this bug was fixed in a1f8394750dfa56f9de3a4c9188f1109fa1d38ec, and the fix will be included in v1.0.3 (probably next week).

**Comment by glasser** [comment] 2015-01-21 01:19
Duplicate of #3331.

**Closed by glasser** 2015-01-21 01:19 UTC
