### ISSUE TITLE
Meteor mongo doesn't see local database

### ISSUE THREAD

**Issue by Sindis** [meteor/meteor#4124] opened 2015-04-04 17:00 UTC
As states in title, meteor mongo leaves error:
```
mongo: Meteor isn't running a local MongoDB server.

This command only works while Meteor is running your application locally. Start
your application first. (This error will also occur if you asked Meteor to use
a different MongoDB server with $MONGO_URL when you ran your application.)

If you're trying to connect to the database of an app you deployed with
'meteor deploy', specify your site's name with this command.
```

I found a way around, but I just don't know why after update meteor mongo stopped working.

My way:
```
apt-get install mongodb-clients
mongo localhost:3001/meteor
```
Meaning that local database is visible, just not for meteor mongo

**Comment by dcsan** [comment] 2015-04-04 19:03
one of our team just noted this too on linux. 
on osx it seems fine for me tho...

**Comment by rclai** [comment] 2015-04-05 03:45
I'd like to +1 this as well. I'm on Trusty Tahr.

**Comment by Slava** [comment] 2015-04-05 04:43
Possible duplicate of https://github.com/meteor/meteor/issues/4115

**Comment by glasser** [comment] 2015-04-05 14:32
Yes, this is a duplicate of #4115, which @stubailo was in the process of releasing 1.1.0.2 to fix on Friday.  It appears that the last stage or two of the release process never happened.  Trying to get in touch with him to find out why, since so many users are hitting this.

**Closed** 2015-04-05 14:32 UTC

**Comment by mohessaid** [comment] 2015-11-01 16:14
Still get the same problem in 1.2.1?
