### ISSUE TITLE
Problem showing images

### ISSUE THREAD

**Issue by rafaelfaria** [meteor/meteor#4326] opened 2015-05-05 06:38 UTC
After the latest update i got a problem that i'm struggling to fix it:

on my media.js I have a server function like below:
```
if (Meteor.isServer) {

	Meteor.methods({

		/**
		* @method getUploadedFile
		* @return {object}
		* Return the information of the file, inclusing its strem to be served from the route
		*/
		'getUploadedFile': function(filename) {
			var fs 		= Meteor.npmRequire('fs'),
				path 	= Meteor.npmRequire('path');

			var basedir = process.env.PWD + '/.uploads/',
				ext 	= path.extname(filename),
				mimeType = 'application/octet-stream',
				file 	= basedir + filename;


			if (!fs.existsSync(file)) {
				file = process.env.PWD  + "/public/images/unavailable-placeholder.png";
			}

			var	fileStream 	= fs.readFileSync(file);

			switch( ext ) {
				case '.gif':
					mimeType = 'image/gif';
				break;
				case '.png':
					mimeType = 'image/png';
				break;
				case '.jpeg':
				case '.jpg':
					mimeType = 'image/jpg';
				break;
			}
			return { fileStream: fileStream, mimeType: mimeType };
		}
	});
}
```

If i add a console.log on fileStream i get:

```
I20150505-16:40:24.302(10)? <Buffer ff d8 ff e1 00 18 45 78 69 66 00 00 49 49 2a 00 08 00 00 00 00 00 00 00 00 00 00 00 ff ec 00 11 44 75 63 6b 79 00 01 00 04 00 00 00 64 00 00 ff e1 03 2d ...>
```

So far so good, i would expect a buffer.

---

Now, I have a router that does the following:

```
Router.route('/uploads/:filename', {
	name: 'uploads',
	where: 'server',
	controller: 'MediaLibraryController',
	action: 'uploads'
});


MediaLibraryController = RouteController.extend({
	uploads: function() {

		var filename 	= this.params.filename,
			fileObj 	= Meteor.call('getUploadedFile', filename), // call method getUploadedFile from /lib/media/media.js
			headers 	= { 'Content-type': fileObj.mimeType };

		// write the headers based on the type of the file
		this.response.writeHead(200, headers);

		// Return the stream of the file
		return this.response.end(fileObj.fileStream);
	}
});
```

if i do a console.log(fileObj)  i get a long long long long long output similar to below. It's like a never ending output, because i need to break the server otherwise it wont stop.

```

I20150505-16:45:49.377(10)? <Buffer ff d8 ff e1 00 18 45 78 69 66 00 00 49 49 2a 00 08 00 00 00 00 00 00 00 00 00 00 00 ff ec 00 11 44 75 63 6b 79 00 01 00 04 00 00 00 64 00 00 ff e1 03 2d ...>.
.
.
I20150505-16:41:49.463(10)?      '16487': 173,
I20150505-16:41:49.463(10)?      '16488': 29,
I20150505-16:41:49.464(10)?      '16489': 211,
I20150505-16:41:49.464(10)?      '16490': 188,
I20150505-16:41:49.464(10)?      '16491': 82,
I20150505-16:41:49.464(10)?      '16492': 244,
I20150505-16:41:49.464(10)?      '16493': 39,
I20150505-16:41:49.464(10)?      '16494': 52,
I20150505-16:41:49.464(10)?      '16495': 238,
I20150505-16:41:49.465(10)?      '16496': 232,
I20150505-16:41:49.465(10)?      '16497': 211,
I20150505-16:41:49.465(10)?      '16498': 52,
I20150505-16:41:49.465(10)?      '16499': 100,
I20150505-16:41:49.465(10)?      '16500': 212,
I20150505-16:41:49.465(10)?      '16501': 21,
I20150505-16:41:49.465(10)?      '16502': 232,
I20150505-16:41:49.466(10)?      '16503': 58,
I20150505-16:41:49.466(10)?      '16504': 215,
I20150505-16:41:49.466(10)?      '16505': 171,
I20150505-16:41:49.466(10)?      '16506': 125,
I20150505-16:41:49.466(10)?      '16507': 254,

.
.
.
.
so on...
```

---

This used to work just fine. If i print the 'fileStream' on the getUploadedFile method, it shows the buffer of the image, if i print the return on the router controller, the output is completely different. Therefore if i try something like 'http://localhost:3000/uploads/1424386049176rBeQ6KM3g5GdEidFv.jpg' throws an error:

```
W20150505-16:35:51.395(10)? (STDERR) TypeError: first argument must be a string or Buffer
W20150505-16:35:51.395(10)? (STDERR)     at ServerResponse.OutgoingMessage.write (http.js:852:11)
W20150505-16:35:51.395(10)? (STDERR)     at ServerResponse.res.write (/Users/rcardoso/.meteor/packages/webapp/.1.2.0.1wrdlo9++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/compress.js:110:17)
W20150505-16:35:51.395(10)? (STDERR)     at ServerResponse.res.end (/Users/rcardoso/.meteor/packages/webapp/.1.2.0.1wrdlo9++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/compress.js:116:14)
W20150505-16:35:51.396(10)? (STDERR)     at [object Object].RouteController.extend.uploads (app/lib/media/router.js:48:24)
W20150505-16:35:51.396(10)? (STDERR)     at [object Object].handle (packages/iron:middleware-stack/lib/handler.js:74:1)
W20150505-16:35:51.396(10)? (STDERR)     at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
W20150505-16:35:51.396(10)? (STDERR)     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
W20150505-16:35:51.396(10)? (STDERR)     at packages/meteor/dynamics_nodejs.js:121:1
W20150505-16:35:51.396(10)? (STDERR)     at [object Object].urlencodedParser (/Users/rcardoso/.meteor/packages/iron_router/.1.0.7.10sanjn++os+web.browser+web.cordova/npm/node_modules/body-parser/lib/types/urlencoded.js:72:36)
W20150505-16:35:51.396(10)? (STDERR)     at packages/iron:router/lib/router.js:277:1
```

I can assure that '1424386049176rBeQ6KM3g5GdEidFv.jpg' exists and it this was working before i've updated to the latest version. I can't really tell what version this was working.

This is how i show all my images so my whole site is broken because of that. Can anyone tell me what am i doing wrong, or what can i do to make it better?

Node Version:
```
$ node -v
v0.12.0
```

Thank you.

**Comment by ekatek** [comment] 2015-05-05 20:52
Hi, 
This is neat, and looks like an issue, but there is a lot of code to go through to understand it. (For example, how much of a role does the router play in this-- what router are you using? Iron router, for example, is not maintained by MDG.)

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a good way to replicate your problem, we can't debug, fix it, or understand if it is coming from the Meteor tool itself, or a community-maintained package.

**Comment by rafaelfaria** [comment] 2015-05-05 23:26
@ekatek  thanks for the reply. Yeah, i'm using Iron router, do you think this might be related to the router instead of meteor itself? 

I'm only raising the issue here because this started happening after I updated meteor, not really being sure it is related or not. Just wanted to have an idea if you guys would know something about it.

On the same note, what would be the best way to do what I'm trying to do? I mean, is this the best way? Should i be doing this differently? 

Thanks

**Comment by glasser** [comment] 2015-05-19 21:32
This bug does not have a reproduction, so I'm closing it. If anyone is able to come up a way to consistently reproduce it, we can reopen it.

**Closed by glasser** 2015-05-19 21:32 UTC
