### ISSUE TITLE
< input value="{{helper}}" > loses default value on reset

### ISSUE THREAD

**Issue by dwrensha** [meteor/meteor#5440] opened 2015-10-15 16:46 UTC
Example here: https://github.com/dwrensha/meteor-reset-form-bug (adapted from https://github.com/aldeed/meteor-autoform/issues/398)

If I have something like this in a template:
```
  <form>
    <input type="text" value="{{foo}}">
    <button type="reset">RESET</button>
  </form>
```
I expect that clicking on the button will reset the input to the value of the `foo()` helper. Instead, what actually happens is that the input gets totally cleared.

**Comment by krishamoud** [comment] 2015-10-15 18:29
Maybe a duplicate of https://github.com/meteor/meteor/issues/2431

**Comment by dwrensha** [comment] 2015-10-15 19:24
Thanks. #2431 does look related.
What's really confusing to me is this: When I inspect the <input> element with my browser's dev tools, the `value` attribute is not present at all! And yet if I add another attribute like this

```
 <form>
    <input type="text" value="{{foo}}" data-foo="{{foo}}">
    <button type="reset">RESET</button>
  </form>
```
then `data-foo` does indeed show up. So it seems that Meteor is somehow special-casing the `value` attribute. Is that correct? Are there other attributes that get special-cased as well?

**Comment by stubailo** [comment] 2015-10-20 20:47
Interesting! I had no idea there was an HTML form reset function.

You're right that the value attribute is special-cased to allow something like two-way data binding without lots of hassle. In React, for example, you need to explicitly set an input field to read only to be able to set the value reactively; and if it's not read only there is a special attribute called "defaultValue".

I think this is a special case of #2431, and it might not be worth having a separate issue for it.

**Closed by stubailo** 2015-10-20 20:47 UTC

**Comment by saliksaly** [comment] 2016-10-05 13:04
Hi,

Is this issue solved? 
I have still this problem in 1.3.3 version.

Ondra

**Comment by nosizejosh** [comment] 2017-06-10 21:22
what's the workaround or solution for this please?
