### ISSUE TITLE
NODE_ENV is set to development with "--production" flag

### ISSUE THREAD

**Issue by petermikitsh** [meteor/meteor#3839] opened 2015-03-01 15:20 UTC
Running my app locally:

`$ meteor --production`

```javascript
// server/environment.js
// prints NODE_ENV

Meteor.startup(function () {
  console.log(process.env.NODE_ENV);
})
```

Console output:
```
=> Meteor server restartedI20150301-10:13:36.563(-5)? development
```

I haven't set NODE_ENV elsewhere. Also from console:
```
$ env | grep NODE_ENV
```
produces no output.

**Comment by Tarang** [comment] 2015-03-01 17:57
When you use `meteor` instead of node to run your app isn't it still in development mode?

Afaik `--production` just minifies the files into a single one. The filewatcher is still active and mongo is still run from meteor.

When you create a bundle from `meteor bundle` and run that in node isn't that the actual production version?

**Comment by petermikitsh** [comment] 2015-03-01 19:43
@Tarang The filewatcher is indeed active, and mongo is started by Meteor... So maybe the `--production` flag is a bit of a misnomer? Maybe it should just be named `--minify`?

For my use case, I wanted to use one authentication strategy in development, and another in production mode. Instead of relying on `NODE_ENV` and the `--production` flag, I utilized Meteor.settings.

However, my usability concern stands. `--production` would imply `NODE_ENV=production`.

**Comment by glasser** [comment] 2015-03-03 22:02
I'm going to consider this a duplicate of #3748: we don't have predefined support for multiple environments such as dev and prod.

We set NODE_ENV=development whenever you are using the dev mode runner so that certain stack traces (eg from connect) are visible while you're developing.

I wish we had named `--production` something like `--minify` (though it now also drops debugOnly packages) or even `--simulate-production`; the dev mode runner is not and has never been designed for actual production use.

**Closed by glasser** 2015-03-03 22:02 UTC
Labels: Project:JS Environment, Project:Tool
