### ISSUE TITLE
[1.2 RC] Calling Meteor.call from client isn't actually calling server Meteor.methods functions

### ISSUE THREAD

**Issue by wallslide** [meteor/meteor#5113] opened 2015-09-07 07:05 UTC
In one of my projects that I've tried upgrading to 1.2 rc12 (from 1.1.0.3), calling ```Meteor.call``` on the client doesn't call the corresponding method defined in ```Meteor.methods``` on the server. The callback that I've defined in the ```Meteor.call``` method invocation on the client is never fired, and by putting a breakpoint in the corresponding server function, I can tell that it is never being called.

Subscriptions and publications seem to be working however. And I've also tested that the Collection.find/update functions are also working on the client. 

To eliminate the possibility of packages causing problems, I created an empty meteor project, copied my list of packages into the empty project, and attempted to make ```Meteor.call``` invocations with no problem. 

There are no modifications to the Meteor.call nor Meteor.methods functions in the project.

I created a super simple Meteor method on my server just to test if I can call it from the client, but of course it is not working:

```javascript
Meteor.methods({
  'tester': function(){
    return 'success';
  },
});
```

**Comment by dgreensp** [comment] 2015-09-07 15:36
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by dgreensp** [comment] 2015-09-09 17:15
Hi @wallslide, we'd really appreciate your help tracking this down, since it sounds like a regression.  Can you either provide us access to your code (privately, if you like), or reduce your app to try to pinpoint the problem?  Thanks.

**Comment by wallslide** [comment] 2015-09-10 06:40
Thanks @dgreensp, I'll try to whip up some sort of private code access for you.

**Comment by stubailo** [comment] 2015-09-11 04:16
@wallslide I talked to @n1mmy, and unfortunately we won't be able to look at a private repository to reproduce a bug. We'll need a open source reproduction to move forward.

**Comment by wallslide** [comment] 2015-09-11 04:41
As I mentioned above, I unfortunately wasn't able to reproduce the problem in an empty project using the list of packages taken from my real project.

**Comment by stubailo** [comment] 2015-09-11 04:47
Are you sure this isn't a duplicate of: https://github.com/meteor/meteor/issues/5027

That was a somewhat similar issue where methods weren't getting called.

**Comment by stubailo** [comment] 2015-09-11 04:48
The question to answer there is: do you have any publications that return `undefined`?

**Comment by wallslide** [comment] 2015-09-11 05:48
Thanks for the suggestion. I'll look into that, but actually our publications and subscriptions are working, it's only calls from the web browser using ```Meteor.call``` to ```Meteor.methods``` that we've defined that don't seem to ever make it to the server.

**Comment by stubailo** [comment] 2015-09-11 05:51
Yes, I'm aware, but it could still be a result of the same.

**Comment by stubailo** [comment] 2015-09-14 21:48
Any new information?

**Comment by wallslide** [comment] 2015-09-15 00:22
I'm still trying to debug what is going wrong. I tried upgrading to rc14, but after doing so the client couldn't even seem to load all of the initial subscriptions. On rc12 it loaded them fine however. I'll post if I make any more progress.

**Comment by stubailo** [comment] 2015-09-15 18:39
Have you checked all of your publications to see if they all either call `this.ready()` or return something? That's the only thing I can think of, otherwise I can't figure out the cause.

**Closed by stubailo** 2015-09-15 18:39 UTC

**Comment by chasemb** [comment] 2015-09-29 23:41
I'm having the exact same issue.  Did you find out what's causing this?

**Comment by wallslide** [comment] 2015-11-19 01:15
After holding out on upgrading for a bit, our project is no longer having this problem. We are running on 1.2.1 now. I assume it was an issue that has been subsequently fixed either in the meteor core, or in one of the packages we were using.

**Comment by jdcast** [comment] 2016-09-15 00:00
Was anyone able to find out the precise issue?  I'm experiencing the same problem even when attempting to update to 1.2.1 from 1.0.

**Comment by crsssl** [comment] 2016-09-20 10:19
I've got the same problem. Was this ever figured out?

**Comment by crsssl** [comment] 2016-09-20 15:24
@jdcast ... In my case, it was Kadira interfering. If installed, upgrade to 2.23.1 as per  https://github.com/meteorhacks/kadira/issues/181

**Comment by jdcast** [comment] 2016-09-21 01:54
@crsssl thanks!  I just updated meteorhacks:kadira to 2.30.0 (from 2.20.1) and the issue seems to be resolved.  
As a general note, upgrading the kadira also apparently upgraded meteorhacks:meteorx from 1.3.1 to 1.4.1.

**Comment by crsssl** [comment] 2016-09-21 03:17
@jdcast You're welcome.

Now if I can just figure out why my Bootstrap modals don't stay open when toggled, we'll be getting somewhere. 😉
