### ISSUE TITLE
Uncaught ReferenceError in mobx.js on production

### ISSUE THREAD

**Issue by achtan** [meteor/meteor#8537] opened 2017-03-29 14:17 UTC
Hi im getting this error on `--production` build (not on dev, there is no error)
`Uncaught ReferenceError: Ze is not defined at mobx.js (99efd91….js?meteor_js_resource=true:11) ...`
![screenshot 2017-03-29 16 10 01](https://cloud.githubusercontent.com/assets/1048212/24458965/b3366a78-149a-11e7-8eba-75d04e3b2190.png)

i dont have a clue where to start to fix this error... 
i tried different versions of mobx and meteor, but still the same result...

if it helps, here is the site with error http://priamereality.sk/ (see console)

METEOR@1.4.4-rc.3
```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.16                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.2                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.4   # CSS minifier run for production mode
standard-minifier-js@2.0.0-rc.3    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.7.1-rc.3              # Enable ECMAScript2015+ syntax in app code

bensventures:flow-router-ssr
kadira:dochead

npm-bcrypt@0.9.2
accounts-base@1.2.15
accounts-password@1.3.4
service-configuration@1.0.11
std:accounts-ui
std:accounts-bootstrap
alanning:roles

matb33:collection-hooks
meteorhacks:aggregate

fourseven:scss
fortawesome:fontawesome

# file upload
ostrio:files

percolate:migrations
less@2.7.9
```
npm
```
{
  "name": "real",
  "private": true,
  "scripts": {
    "start": "meteor run --settings settings.json",
    "production": "TOOL_NODE_FLAGS=\"--max-old-space-size=4096\" meteor run --production --settings settings.json",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "antd": "^2.7.2",
    "babel-runtime": "^6.18.0",
    "bcrypt": "^1.0.2",
    "bootstrap": "^4.0.0-alpha.6",
    "classnames": "^2.2.5",
    "domready": "^1.0.8",
    "enumify": "^1.0.4",
    "faker": "^3.1.0",
    "fs-extra": "^2.1.2",
    "jimp": "^0.2.27",
    "lodash": "^4.17.4",
    "meteor-node-stubs": "^0.2.4",
    "mobx": "^2.4.4",
    "mobx-react": "^4.0.3",
    "numeral": "^2.0.4",
    "react": "^15.4.2",
    "react-addons-css-transition-group": "^15.4.2",
    "react-addons-shallow-compare": "^15.4.2",
    "react-addons-transition-group": "^15.4.2",
    "react-dnd": "^2.1.4",
    "react-dnd-touch-backend": "^0.3.5",
    "react-dom": "^15.4.2",
    "react-dropzone": "^3.12.2",
    "react-google-maps": "^6.0.1",
    "react-image-gallery": "^0.7.12",
    "react-komposer": "^2.0.0",
    "react-redux": "^5.0.2",
    "react-selectize": "^2.1.0",
    "react-waypoint": "^5.0.3",
    "reactstrap": "^4.0.1",
    "redux": "^3.6.0",
    "redux-form": "^6.4.3"
  },
  "devDependencies": {
    "@kadira/storybook": "^2.21.0",
    "babel-plugin-import": "^1.1.1",
    "babel-plugin-transform-class-properties": "^6.23.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-es2016": "^6.11.3",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-1": "^6.13.0",
    "babel-preset-stage-2": "^6.18.0",
    "babel-root-slash-import": "^1.1.0",
    "node-sass": "^4.5.0",
    "sass-loader": "^6.0.2"
  }
}
````

**Comment by benjamn** [comment] 2017-03-29 15:17
I believe this may be the same issue as https://github.com/meteor/meteor/issues/8536. Let's continue discussion over there?

**Comment by benjamn** [comment] 2017-03-29 23:51
I'm no longer sure this is the same issue, so I've reopened this one. If you can provide a [reproduction](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor), that would be super helpful!

**Comment by hwillson** [comment] 2017-04-04 17:45
Hi @achtan - I've taken a look at your site but don't see any errors. Did you get this issue resolved or put a workaround in place? I'm assuming a workaround, since that site is using `METEOR@1.4.3.2` instead of a `rc`. Can you post back to let us know where things stand, and if you're still having this problem, can you please submit a reproduction demonstrating the issue? Thanks!

**Comment by achtan** [comment] 2017-04-06 11:55
hi I tried to create reproduction repo, but with no luck... sry

**Comment by hwillson** [comment] 2017-04-06 12:09
Thanks @achtan - are you still having this problem then?

**Comment by achtan** [comment] 2017-04-06 12:11
no i don cuz im on `METEOR@1.4.3.2` i can try updateing to latest rc if error shows up...

**Comment by hwillson** [comment] 2017-04-06 15:36
@achtan If you have spare cycles at some point, and don't mind updating and testing things out with `1.4.4-rc.8`, that would be awesome - thanks!

**Comment by achtan** [comment] 2017-04-07 09:01
i tried rc9 still the same error

**Comment by abernix** [comment] 2017-04-07 09:20
@achtan When you said you had no luck creating a reproduction, was there anything that got in the way?  What do you think might be making the reproduction not trigger the same problem?

**Comment by achtan** [comment] 2017-04-07 10:15
im not sure... i created new meteor project, installed rc3 release, added mobx and few other packages... but error didn't show up...

**Comment by abernix** [comment] 2017-04-07 10:28
What if, instead of creating a new project from scratch, you take the old project and make a copy of it.  Then, start removing large sections of code, followed by Meteor packages and then npm pacakges until the problem goes away?

You'll need to run with `--production` in order to find the problem, but if you do this in small steps, saving after each change, you can hopefully find the problem that way.

Please, your help in reproducing this is critical to our fixing it so without a reproduction we may not be able to help any further! :smile:

**Comment by abernix** [comment] 2017-04-19 03:20
Any update on this, @achtan?

**Comment by achtan** [comment] 2017-04-19 06:09
sorry i won't be able to provide reproduction update

**Comment by abernix** [comment] 2017-05-03 10:33
I'll close this for now then, but if you can reproduce in the future we'll be happy to take a look at it again!

**Closed by abernix** 2017-05-03 10:33 UTC

**Comment by fatso83** [comment] 2017-07-21 09:46
Got bit by this same thing, so thought I would add my two cents here, as I also found a solution, for anyone else getting hit by minification issues appearing with 1.5. Just upgrade the minifier to use the latest from Jesse, as [detailed here](https://github.com/meteor/meteor/pull/8698#issuecomment-315213059).

Running Meteor 1.5.1 fully updated

<details>
<summary>Full stacktrace</summary>
```
6950f2fc2c5126c96beef456147a4eb36c104f87.js:25 Uncaught ReferenceError: Ve is not defined
    at mobx.js (6950f2f….js?meteor_js_resource=true:25)
    at l (6950f2f….js?meteor_js_resource=true:23)
    at e (6950f2f….js?meteor_js_resource=true:23)
    at with_mobx.js (6950f2f….js?meteor_js_resource=true:25)
    at l (6950f2f….js?meteor_js_resource=true:23)
    at e (6950f2f….js?meteor_js_resource=true:23)
    at index.js (6950f2f….js?meteor_js_resource=true:25)
    at l (6950f2f….js?meteor_js_resource=true:23)
    at e (6950f2f….js?meteor_js_resource=true:23)
    at index.js (6950f2f….js?meteor_js_resource=true:25)
mobx.js @ 6950f2f….js?meteor_js_resource=true:25
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
with_mobx.js @ 6950f2f….js?meteor_js_resource=true:25
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
index.js @ 6950f2f….js?meteor_js_resource=true:25
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
index.js @ 6950f2f….js?meteor_js_resource=true:25
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
AppLayoutContainer.jsx @ 6950f2f….js?meteor_js_resource=true:167
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
routes.jsx @ 6950f2f….js?meteor_js_resource=true:167
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
index.js @ 6950f2f….js?meteor_js_resource=true:167
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
main.js @ 6950f2f….js?meteor_js_resource=true:167
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
(anonymous) @ 6950f2f….js?meteor_js_resource=true:167
6950f2fc2c5126c96beef456147a4eb36c104f87.js:75 There is no route for the path: /
d._notfoundRoute @ 6950f2f….js?meteor_js_resource=true:75
(anonymous) @ 6950f2f….js?meteor_js_resource=true:75
(anonymous) @ 6950f2f….js?meteor_js_resource=true:75
r @ 6950f2f….js?meteor_js_resource=true:75
n.dispatch @ 6950f2f….js?meteor_js_resource=true:75
n.replace @ 6950f2f….js?meteor_js_resource=true:75
e._page.(anonymous function) @ 6950f2f….js?meteor_js_resource=true:75
n.start @ 6950f2f….js?meteor_js_resource=true:75
n @ 6950f2f….js?meteor_js_resource=true:75
d.initialize @ 6950f2f….js?meteor_js_resource=true:75
(anonymous) @ 6950f2f….js?meteor_js_resource=true:75
a @ 6950f2f….js?meteor_js_resource=true:3
u @ 6950f2f….js?meteor_js_resource=true:3
6950f2fc2c5126c96beef456147a4eb36c104f87.js:93 Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined
    at 6950f2f….js?meteor_js_resource=true:93
    at a (6950f2f….js?meteor_js_resource=true:3)
    at HTMLDocument.u (6950f2f….js?meteor_js_resource=true:3)
(anonymous) @ 6950f2f….js?meteor_js_resource=true:93
a @ 6950f2f….js?meteor_js_resource=true:3
u @ 6950f2f….js?meteor_js_resource=true:3
6950f2f….js?meteor_js_resource=true:25 Uncaught ReferenceError: Ve is not defined
    at mobx.js (6950f2f….js?meteor_js_resource=true:25)
    at l (6950f2f….js?meteor_js_resource=true:23)
    at e (6950f2f….js?meteor_js_resource=true:23)
    at with_mobx.js (6950f2f….js?meteor_js_resource=true:25)
    at l (6950f2f….js?meteor_js_resource=true:23)
    at e (6950f2f….js?meteor_js_resource=true:23)
    at index.js (6950f2f….js?meteor_js_resource=true:25)
    at l (6950f2f….js?meteor_js_resource=true:23)
    at e (6950f2f….js?meteor_js_resource=true:23)
    at index.js (6950f2f….js?meteor_js_resource=true:25)
mobx.js @ 6950f2f….js?meteor_js_resource=true:25
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
with_mobx.js @ 6950f2f….js?meteor_js_resource=true:25
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
index.js @ 6950f2f….js?meteor_js_resource=true:25
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
index.js @ 6950f2f….js?meteor_js_resource=true:25
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
AppLayoutContainer.jsx @ 6950f2f….js?meteor_js_resource=true:167
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
routes.jsx @ 6950f2f….js?meteor_js_resource=true:167
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
index.js @ 6950f2f….js?meteor_js_resource=true:167
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
main.js @ 6950f2f….js?meteor_js_resource=true:167
l @ 6950f2f….js?meteor_js_resource=true:23
e @ 6950f2f….js?meteor_js_resource=true:23
(anonymous) @ 6950f2f….js?meteor_js_resource=true:167
6950f2f….js?meteor_js_resource=true:75 There is no route for the path: /
d._notfoundRoute @ 6950f2f….js?meteor_js_resource=true:75
(anonymous) @ 6950f2f….js?meteor_js_resource=true:75
(anonymous) @ 6950f2f….js?meteor_js_resource=true:75
r @ 6950f2f….js?meteor_js_resource=true:75
n.dispatch @ 6950f2f….js?meteor_js_resource=true:75
n.replace @ 6950f2f….js?meteor_js_resource=true:75
e._page.(anonymous function) @ 6950f2f….js?meteor_js_resource=true:75
n.start @ 6950f2f….js?meteor_js_resource=true:75
n @ 6950f2f….js?meteor_js_resource=true:75
d.initialize @ 6950f2f….js?meteor_js_resource=true:75
(anonymous) @ 6950f2f….js?meteor_js_resource=true:75
a @ 6950f2f….js?meteor_js_resource=true:3
u @ 6950f2f….js?meteor_js_resource=true:3
6950f2f….js?meteor_js_resource=true:93 Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined
    at 6950f2f….js?meteor_js_resource=true:93
    at a (6950f2f….js?meteor_js_resource=true:3)
    at HTMLDocument.u (6950f2f….js?meteor_js_resource=true:3)
(anonymous) @ 6950f2f….js?meteor_js_resource=true:93
a @ 6950f2f….js?meteor_js_resource=true:3
u @ 6950f2f….js?meteor_js_resource=true:3
```
</details>
