### ISSUE TITLE
1.6-rc.1 fibers won't build windows

### ISSUE THREAD

**Issue by janat08** [meteor/meteor#9162] opened 2017-10-01 14:08 UTC
1.6-rc.1 Brakes
~1.5.2 Worked
Windows
- [x] The expected behavior.
Meteor starts
- [x] The actual behavior.
```
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While loading package peerlibrary:fiber-utils@0.8.2:
   error: Command failed: C:\WINDOWS\system32\cmd.exe /c
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.0\mt-os.w
indows.x86_32\dev_bundle\bin\npm.cmd
   rebuild --update-binary
   gyp:
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.0\mt-os.w
indows.x86_32\dev_bundle\common.gypi
   not found (cwd:
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\peerlibrary_fiber-utils\0.8.2\
npm\node_modules\.temp-8l5l1o.p04wk\node_modules\fibers)
   while reading includes of binding.gyp while trying to load binding.gyp
   gyp ERR! configure error
   gyp ERR! stack Error: `gyp` failed with exit code: 1
   gyp ERR! stack     at ChildProcess.onCpExit
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.0\mt-os.
windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\configure
.js:336:16)
   gyp ERR! stack     at emitTwo (events.js:125:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit
   (internal/child_process.js:200:12)
   gyp ERR! System Windows_NT 10.0.15063
   gyp ERR! command
   "C:\\Users\\ALERATOR\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-rc.
0\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\ALERATOR\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-rc.
0\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gy
p\\bin\\node-gyp.js"
   "rebuild" "--release"
   gyp ERR! cwd
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\peerlibrary_fiber-utils\0.8.2\
npm\node_modules\.temp-8l5l1o.p04wk\node_modules\fibers
   gyp ERR! node -v v8.6.0
   gyp ERR! node-gyp -v v3.6.2
   gyp ERR! not ok
   node-gyp exited with code: 1
   Please make sure you are using a supported platform and node version. If
   you
   would like to compile fibers on this machine please make sure you have
   setup your
   build environment--
   Windows + OS X instructions here: https://github.com/nodejs/node-gyp
   Ubuntu users please run: `sudo apt-get install g++ build-essential`
   Alpine users please run: `sudo apk add python make g++`
   'nodejs' is not recognized as an internal or external command,
   operable program or batch file.
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the fibers@1.0.15 install script.
   npm ERR! This is probably not a problem with npm. There is likely
   additional logging output above.

   npm ERR! A complete log of this run can be found in:
   npm ERR!
   C:\Users\ALERATOR\AppData\Roaming\npm-cache\_logs\2017-10-01T14_03_32_857Z-debu
g.log
   gyp:
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.0\mt-os.w
indows.x86_32\dev_bundle\common.gypi
   not found (cwd:
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\peerlibrary_fiber-utils\0.8.2\
npm\node_modules\.temp-8l5l1o.p04wk\node_modules\fibers)
   while reading includes of binding.gyp while trying to load binding.gyp
   gyp ERR! configure error
   gyp ERR! stack Error: `gyp` failed with exit code: 1
   gyp ERR! stack     at ChildProcess.onCpExit
   (C:\Users\ALERATOR\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.0\mt-os.
windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\configure
.js:336:16)
   gyp ERR! stack     at emitTwo (events.js:125:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit
   (internal/child_process.js:200:12)
   gyp ERR! System Windows_NT 10.0.15063
   gyp ERR! command
   "C:\\Users\\ALERATOR\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-rc.
0\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\ALERATOR\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-rc.
0\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gy
p\\bin\\node-gyp.js"
   "rebuild" "--release"
   gyp ERR! cwd
   C:\Users\ALERATOR\AppData\Local\.meteor\packages\peerlibrary_fiber-utils\0.8.2\
npm\node_modules\.temp-8l5l1o.p04wk\node_modules\fibers
   gyp ERR! node -v v8.6.0
   gyp ERR! node-gyp -v v3.6.2
   gyp ERR! not ok
   node-gyp exited with code: 1
   Please make sure you are using a supported platform and node version. If
   you
   would like to compile fibers on this machine please make sure you have
   setup your
   build environment--
   Windows + OS X instructions here: https://github.com/nodejs/node-gyp
   Ubuntu users please run: `sudo apt-get install g++ build-essential`
   Alpine users please run: `sudo apk add python make g++`
   'nodejs' is not recognized as an internal or external command,
   operable program or batch file.
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the fibers@1.0.15 install script.
   npm ERR! This is probably not a problem with npm. There is likely
   additional logging output above.

   npm ERR! A complete log of this run can be found in:
   npm ERR!
   C:\Users\ALERATOR\AppData\Roaming\npm-cache\_logs\2017-10-01T14_03_32_857Z-debu
g.log
```

```
C:\Users\ALERATOR\garlic>meteor npm install
npm WARN deprecated graphql-server-core@0.6.0: critical bug related to GET queries
 fixed in v0.8.1

> bcrypt@0.8.7 install C:\Users\ALERATOR\garlic\node_modules\bcrypt
> node-gyp rebuild


C:\Users\ALERATOR\garlic\node_modules\bcrypt>if not defined npm_config_node_gyp (n
ode "C:\Users\ALERATOR\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.0\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp: C:\Users\ALERATOR\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.0\mt-os
.windows.x86_32\dev_bundle\common.gypi not found (cwd: C:\Users\ALERATOR\garlic\no
de_modules\bcrypt) while reading includes of binding.gyp while trying to load bind
ing.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\ALERATOR\AppData\Local\.mete
or\packages\meteor-tool\1.6.0-rc.0\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.
js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\ALERATOR\\AppData\\Local\\.meteor\\packages\\meteor-t
ool\\1.6.0-rc.0\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\ALER
ATOR\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-rc.0\\mt-os.windows.x8
6_32\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js
" "rebuild"
gyp ERR! cwd C:\Users\ALERATOR\garlic\node_modules\bcrypt
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional loggi
ng output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ALERATOR\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc
.0\mt-os.windows.x86_32\dev_bundle\.npm\_logs\2017-10-01T14_07_11_709Z-debug.log
```

- [ ] A **simple** reproduction!
      (example: A GitHub repository that anyone can clone to observe the problem.)
I suppose fiber-utils could be just installed.

**Comment by janat08** [comment] 2017-10-01 14:12
Meteor npm install works on 1.5 and I followed gyp troubleshooting steps. Npm install installs without errors at 3.10.10, but meteor will still fail after. Meteor npm is 5.4.2...

**Comment by janat08** [comment] 2017-10-01 14:20
1.6-rc.0 also failed. Running without 3rd party packages on same project will complain about absence of these packages first if that's any help.

**Comment by Rebolon** [comment] 2017-10-10 11:43
I upgraded my app from 1.5.x to 1.6-beta.30 without any problem on windows.
Since this upgrade i did all upgrade successfully up to rc 3 
But i'm facing errors with rc 5 : 
#9203

**Comment by hwillson** [comment] 2017-10-25 18:02
Please try `1.6-rc.17` and post back if you're still encountering this issue. Thanks!

**Comment by mitar** [comment] 2017-11-09 01:03
This still seems as an issue for people, see here: https://github.com/peerlibrary/node-fiber-utils/issues/3

**Comment by john-osullivan** [comment] 2017-11-29 22:02
This is breaking my build

**Comment by hwillson** [comment] 2017-12-21 17:20
Can anyone here provide a small runnable reproduction that demonstrates this issue?

**Comment by janat08** [comment] 2018-01-15 02:41
I sent the local files after meteor-reset along with npm folder and it showed the same error there.

**Comment by hwillson** [comment] 2018-02-13 17:14
If anyone is able to provide a reproduction that demonstrates this issue, we'll be glad to take a look. Closing for now.

**Closed by hwillson** 2018-02-13 17:14 UTC
Labels: Project:Tool, Project:Windows, needs-reproduction
