### ISSUE TITLE
my windows install meteor  error code   " 0x80070643"  

### ISSUE THREAD

**Issue by drioou** [meteor/meteor#7009] opened 2016-05-09 15:54 UTC
anyone can help me 
this is my error log
[15D8:70FC][2016-05-09T23:51:12]e000: Error 0x80070643: Failed to install MSI package.
[15D8:70FC][2016-05-09T23:51:12]e000: Error 0x80070643: Failed to configure per-user MSI package.
[15D8:70FC][2016-05-09T23:51:12]i319: Applied execute package: SetupMeteor_UserInstall, result: 0x80070643, restart: None
[15D8:70FC][2016-05-09T23:51:12]e000: Error 0x80070643: Failed to execute MSI package.
[15D8:70FC][2016-05-09T23:51:12]i318: Skipped rollback of package: SetupMeteor_UserInstall, action: Uninstall, already: Absent
[15D8:70FC][2016-05-09T23:51:12]i319: Applied rollback package: SetupMeteor_UserInstall, result: 0x0, restart: None
[15D8:70FC][2016-05-09T23:51:12]i329: Removed package dependency provider: {2DA24988-287C-4531-9B32-88729CBDF7F1}, package: SetupMeteor_UserInstall
[15D8:70FC][2016-05-09T23:51:12]i351: Removing cached package: SetupMeteor_UserInstall, from path: C:\Users\勇\AppData\Local\Package Cache\{2DA24988-287C-4531-9B32-88729CBDF7F1}v1.0\
[15D8:70FC][2016-05-09T23:51:12]i330: Removed bundle dependency provider: {e2d162ba-d521-4ab7-89c0-bcddd6010381}
[15D8:70FC][2016-05-09T23:51:12]i352: Removing cached bundle: {e2d162ba-d521-4ab7-89c0-bcddd6010381}, from path: C:\Users\勇\AppData\Local\Package Cache\{e2d162ba-d521-4ab7-89c0-bcddd6010381}\
[15D8:70FC][2016-05-09T23:51:12]i399: Apply complete, result: 0x80070643, restart: None, ba requested restart:  No

**Comment by abernix** [comment] 2016-05-09 17:01
Closing this issue because it is a duplicate of an existing known issue, #4932.  It seems to happen under very particular circumstances.  Check that Issue for more information and possible work-arounds, and please feel free to add details including what version of Windows you're using and any relevant details of your environment (admin permissions, network administrator controls, etc.).

**Closed by abernix** 2016-05-09 17:01 UTC
