### ISSUE TITLE
FR: git endpoints for `meteor add`

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4337] opened 2015-05-07 01:21 UTC
Eg `meteor add git@github.com:user/package.git` and shorthand `meteor add user/package` 

This is a useful pattern in bower:

http://bower.io/docs/api/#install

**Comment by stubailo** [comment] 2015-05-12 20:31
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

As a personal opinion, it would be awesome if this were possible, then it would be easier to use one's own packages from GitHub, or packages that are being constantly updated.

**Comment by glasser** [comment] 2015-05-19 21:33
Duplicate of #2919.

**Closed by glasser** 2015-05-19 21:33 UTC
