### ISSUE TITLE
NPM error with meteor package including namespace

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#7639] opened 2016-08-12 15:27 UTC
I have a package which name contains a namespace (e.g. `seba:test`). It requires the `connect` package from npm. When running the app I get this error:
`Error: ENOENT: no such file or directory, open 'D:\node_modules\meteor\seba:test\node_modules\mime\types\mime.types'`

When I remove the namespace, and just call the package `test`, it works fine...

Reproduction: https://github.com/sebakerckhof/meteornpmerror
Branch without namespace: https://github.com/sebakerckhof/meteornpmerror/tree/nonamespace

(only tested on windows 10 ...)

**Comment by benjamn** [comment] 2016-08-12 17:08
What version of Meteor are you using?

**Comment by sebakerckhof** [comment] 2016-08-12 17:20
Well, i can reproduce the error with the repo mentioned above, that uses 1.4.0.1

**Comment by sebakerckhof** [comment] 2016-08-23 14:46
@benjamn I updated the example to Meteor 1.4.1, error still occurs.

**Comment by benjamn** [comment] 2016-08-23 19:43
You might need to run `meteor reset` to clear out previously installed npm packages.

**Comment by sebakerckhof** [comment] 2016-08-23 21:19
@benjamn Yeah, it was actually a fresh clone on a new pc... This is 100% reproducible for me on every pc I tested so far...

**Comment by abernix** [comment] 2016-09-28 12:11
This must be a Windows only situation as I cannot reproduce on *nix.  Unfortunately, my Windows VirtualBoxes are not available to me at the moment to reproduce this or debug.

**Comment by hwillson** [comment] 2017-11-02 19:02
@sebakerckhof Can you verify if this is still happening with Meteor 1.6? Since this issue was created many Meteor versions ago, I'll close it for now. Let us know if it's still happening though and we'll re-open. Thanks!

**Closed by hwillson** 2017-11-02 19:02 UTC
Labels: bug
