### ISSUE TITLE
Transform on cursor doesn't work

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#9194] opened 2017-10-09 04:46 UTC
meteor version <= 1.5.2.2

according to meteor docs

http://docs.meteor.com/api/collections.html#Mongo-Collection-find

```
transform Function
Overrides transform on the Collection for this cursor. Pass null to disable transformation.
```

transform doesn't work here
```javascript
const Test = new Mongo.Collection('test')

Meteor.publish('test', function () {
  return Test.find({}, { transform: function(doc) {
    doc.abc = 123
    return doc
  } })
})
```

transform works with collection constructor
```javascript
const Test = new Mongo.Collection('test' , { transform: function(doc) {
  doc.abc = 123
  return doc
})

Meteor.publish('test', function () {
  return Test.find({}, { transform: null }) // but it doesn't override anything.
})
```

**Comment by klaussner** [comment] 2017-10-09 13:39
The `transform` function is not applied because you are trying to use it on cursors returned from publish functions; see the documentation for [`Mongo.Collection`](http://docs.meteor.com/api/collections.html#Mongo-Collection):

> Transforms are *not* applied for the callbacks of `observeChanges` or to cursors returned from publish functions.

Your second example (with the `transform` function on the collection) works because the documents are transformed at the client.

The documentation is a little confusing because this is not mentioned in the description of the `transform` option for `Mongo.Collection#find` and `Mongo.Collection#findOne`, so the docs could definitely be improved here!

I'm closing the issue because that's not a bug in Meteor. Could you open an issue at the [docs repo](https://github.com/meteor/docs) instead? :slightly_smiling_face:

**Closed by klaussner** 2017-10-09 13:39 UTC

**Comment by crapthings** [comment] 2017-10-10 01:57
it works with fetch. 6~

```javascript
Meteor.publish(null, function () {
  const data = Test.find({}, { limit: 10, transform(doc) { doc.a = 1; return doc } }).fetch()
  console.log(data)
})
```
