### ISSUE TITLE
[cordova] Cannot find module ‘is-property’

### ISSUE THREAD

**Issue by jomin92** [meteor/meteor#7358] opened 2016-07-06 08:10 UTC
Hello

I'm newbie to meteor and i try to create my first app, but i'm getting this error "Error: Cannot find module 'is-property'"
I get this error after command **meteor add-platform android**

Commands:

**meteor create simple-todos
cd simple-todos
meteor npm install
meteor**

(until here all working well)

**meteor add-platform android** (then i get error)

I tried **meteor npm install is-property** and i can see the folder is-property \node_modules\is-property
i try to install it globally **meteor npm install -g is-property** and **meteor npm install --save is-property** but the problem still here.

I'm using Windows 10 and Meteor 1.3.4.1

```
Error: Cannot find module 'is-property'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\index.js:1:18)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\index.js:1:14)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\lib\runner.js:5:17)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\lib\index.js:4:14)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\lib\har.js:5:16)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\request.js:25:11)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:145:19)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:4:15)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\index.js:73:20
at Array.forEach (native)
at CachingRegistryClient.RegClient (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\index.js:51:42)
at new CachingRegistryClient (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\cache\caching-client.js:20:18)
at C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\npm.js:369:22
at C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\config\core.js:82:7
at Array.forEach (native)
at C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\config\core.js:81:13
at f (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\once\once.js:17:25)
at finalize (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\config\core.js:200:5)
at afterExtras (C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\config\core.js:191:5)
at C:\Users\Jomin\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\mkdirp\index.js:48:26
at Object.oncomplete (fs.js:108:15)
```

**Comment by abernix** [comment] 2016-07-06 10:26
Hmm, any idea why your path is:

    C:\Users\Jomin\AppData\Local.meteor\packages\...etc, etc...

instead of

    C:\Users\Jomin\AppData\Local\.meteor\packages\...etc, etc...

(Note the addition of the extra backslash before `.meteor`)

?

**Comment by jomin92** [comment] 2016-07-06 12:52
@abernix 

I tried it again and i think the path it's ok now but the error is still here

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\index.js:1:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module.Mp.load (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\index.js:1:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module.Mp.load (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\lib\runner.js:5:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module.Mp.load (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\lib\index.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module.Mp.load (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\lib\har.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module.Mp.load (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\request.js:25:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module.Mp.load (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:145:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module.Mp.load (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module.Mp.load (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\index.js:73:20
    at Array.forEach (native)
    at CachingRegistryClient.RegClient (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\index.js:51:42)
    at new CachingRegistryClient (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\cache\caching-client.js:20:18)
    at C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\npm.js:369:22
    at C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\config\core.js:82:7
    at Array.forEach (native)
    at C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\config\core.js:81:13
    at f (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\once\once.js:17:25)
    at finalize (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\config\core.js:200:5)
    at afterExtras (C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\config\core.js:191:5)
    at C:\Users\Jomin\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\mkdirp\index.js:48:26
```

**Comment by abernix** [comment] 2016-07-06 13:16
Ok, that's better!  Was that a misconfiguration on your part?

Anyhow, this is most likely a problem with the file path being too long – in Windows, they are limited to 260 characters or 248 characters for directories.   I show you're over 260 with that most recent path.  It's a nightmare of a problem for Windows, in general.  Very similar to #7247 and a very important reason for Windows users to start using npm v3, which uses a flattened NPM directory tree, thus avoiding the problem.

...which is why Meteor 1.3.4.1 was released, as it upgrades `npm` to v3. :smile:  It did fix the issues for most everyone in #7247 so I'm concerned why you're still seeing that long directory format.

What is the output you receive when you type `meteor npm --version`?

**Comment by mking200** [comment] 2016-07-07 05:54
Hi, if this issue is caused by character limit in Windows.  Is there a way to manually install \.meteor\packages\ on the root directory instead C:\Users\username\AppData\Local\  ?

This way it could free up some characters to reach acceptable limit of Windows.  We are also experincing the same on npm version 3.9.6

**Comment by abernix** [comment] 2016-07-07 06:39
Realistically, the %LOCALAPPDATA% portion (`C:\Users\username\AppData\Local\`) isn't the problem it's the infinite nesting of package dependencies after that.  Even if you moved it up by those ~30 characters, another nested dependency will likely pop up in the next error.

I've reproduced this in my Windows 10 VirtualBox, so I will try to take a look at it soon.

**Comment by abernix** [comment] 2016-07-07 17:10
Unfortunately, it appears that despite the fact that Meteor 1.3.4.1 does make the move to npm 3 which does have a flattened dependency structure, it appears that [`cordova-lib` directly depends on npm 2](https://github.com/apache/cordova-lib/blob/master/cordova-lib/package.json#L32) 😞

Cordova seems to be aware of this.  They recently said they "won't fix" [this ticket](https://issues.apache.org/jira/browse/CB-9954) where they attempted to simply update it to npm 3, unsuccessfully.  However, they closed it with a pointer to [this discussion](https://github.com/cordova/cordova-discuss/pull/33) saying they are going to eliminate the dependency on npm and use what the user has installed.  This seems like it will work well for Meteor.  They are [making progress](https://github.com/apache/cordova-lib/pull/407) on it,  however the dependency is still there.

I imagine there are probably some hacks (i.e. cleanup) that Meteor can do but it needs to be done carefully.

I won't _recommend_ this as a solution as it's a bit too hacky, but doing **the following does fix the problem for me**... well, at least, until the next error :grin:

* Use your favorite Windows command prompt to `cd` to this folder:

  (It's really long, make sure you copy/paste all the way through `is-my-json-valid` at the end!)

  ```
C:\Users\YOURUSERNAME\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid
  ```
* Then run:

 ```
meteor npm install is-property
 ```
* After that, go back to your project directory and try running `meteor add-platform android` again and it _should_ work.

Essentially this moves `is-property` up a few levels in the dependency tree and makes it accessible.

Let me know if that works! 🙏

**Comment by mking200** [comment] 2016-07-08 09:04
Hi, your solution has fixed the "is-property" error.  Thanks for this.

**Comment by abernix** [comment] 2016-07-11 12:17
Glad to hear it @mking200.

@jomin92 How about you?

**Comment by ooronning** [comment] 2016-09-05 05:06
Hello, was wondering about the status of this. The workaround listed above doesn't work for me. It seems that Cordova closed the issue referenced above, but it doesn't seem to have done much. I have confirmed that I'm running the latest version of both Node and NPM. I appreciate any input anybody may have.

**Comment by abernix** [comment] 2016-09-14 13:56
@ooronning The solution above probably will work, but you'd need to adjust the `meteor-tool` version number to reflect your current version of Meteor.  For example, with Meteor 1.4.1.1 you'd need to change `1.3.4_1` to `1.4.1_1`.  If you still have issues, please provide more information on what doesn't seem to work: version of Meteor, version of Windows, etc.   I've updated my comment above to reflect this requirement.

**Comment by ooronning** [comment] 2016-09-14 15:55
@abernix Thanks for the response. Though I was indeed using the correct version number to cd properly, I was overlooking the fact that the project in question uses an older version of Meteor. Updating that allowed the add-platform utility to run just fine. Problem resolved, thanks!

**Comment by UrSolutionsGuru** [comment] 2016-09-17 19:35
Thank you, thank you, thank you - that's all I can say.

**Comment by lucasmonteiro001** [comment] 2016-10-11 12:01
thanks @abernix , it fixed my is-property problem

**Comment by Ingosmar89219** [comment] 2016-11-05 07:38
thanks @abernix . It works Fine

**Comment by fandyrahmats** [comment] 2016-11-10 17:04
As a work-around you can just install is-property globlally and then it will work:

`npm install is-property -g`

**Comment by abernix** [comment] 2016-11-10 17:18
@fandyrahmats Yes, but I would still suggest my above work around as more preferable.  While it does require you to implement the fix for each Meteor update version, it avoids contaminating the global namespace with the package and confines it to that particular segment of Cordova dependencies.

**Comment by abernix** [comment] 2016-12-14 16:01
Glad to see that [my previous answer](https://github.com/meteor/meteor/issues/7358#issuecomment-231144281) has been wildly successful!

I'd really like to submit a more permanent fix and alleviate this pain-point for Meteor+Cordova+Windows users.  Unfortunately, I'm not a frequent user of this combination so I'm curious if those of you who are might be willing to try a more simple solution: Simply deleting this nested version of `npm` from `cordova-lib` and allowing it to use the installed `npm`.

For those of you able to try, just run:

(The command is very long, so make sure you copy/paste all the way through!)

    rmdir /s %LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm

Confirm that the directory is correct then press "y" at the prompt.  Let me know your results!

**Comment by avesus** [comment] 2017-02-16 18:39
Any fixes are planned on this? New updates continue to be issued and make the Android workflow on Windows broken over and over after every update. Luckily, searching for `meteor Cannot find module 'is-property'` helps and this thread pops up first all the time. But, is it official production solution in order to allow build for Android on Windows?.. If you have such a configuration bug, you should state it in the official documentation about Android support for Windows builds (that a user should do some manual steps including searching a solution in order to make it work).

**Comment by abernix** [comment] 2017-02-17 14:05
@avesus Unfortunately, we don't control the `cordova-lib` which _still_ depends on `npm@2` (which does not have a flattened dependency tree) which means we have to package `cordova-lib` and its extended dependency tree within the Windows installation.  Because of this large dependency tree, it exceeds Windows [Maximum Path Length Limitation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx).  We would need to need to modify the Cordova package structure in order to make it work and we don't currently have assurance that this wouldn't break things (maybe not so obviously).

If you have any insight into how this might be done safely, or can setup tools which throughly vet the `cordova` functionality within Meteor if we did choose to do this programmatically, that would be great!  Maybe the Cordova test framework itself could be used?

Also, to be clear, we're currently planning on uncoupling Cordova from Meteor specifically because of problems like this: https://github.com/meteor/meteor/issues/8195, but the problem might still exist if we did that.  Ultimately, it would be nice if Cordova updated their dependency on NPM to at _least_ `npm@3` (`npm@4` is out).

**Comment by abernix** [comment] 2017-03-20 16:23
I hope this is good news for this issue:

I was not able to reproduce this problem on Meteor 1.4.3.2 running on Windows Insider Build 15058 which I believe was released to Windows Insider Fast Ring users this weekend.  If anyone is on that Fast Ring, I'd be interested to know how it goes for you.  I would love to say that this issue is fixed because Microsoft solved their wonky file-path length-limits!

If it is fixed, I believe this will be released in the Windows 10 Creators Update coming soon(ish??).  (It's purported to be coming out at the end of March)

**Comment by nosizejosh** [comment] 2017-04-02 13:39
@abernix I am not on the fast ring but can confirm the issue still exists, I cannot wait to get the new release to get rid of these cannot delete issues due to "path name too long" and cannot find "is-property".

**Comment by varunajmera0** [comment] 2017-04-06 10:05
Doesn't work for me
![image](https://cloud.githubusercontent.com/assets/22893376/24748836/a2b172de-1ade-11e7-8c1c-60bea5c90e3b.png)

**Comment by harry-g** [comment] 2017-04-06 19:10
As described above, either install it globally with -g 
`npm install is-property -g`
or dive down into the long version dependent path and install there...

**Comment by abernix** [comment] 2017-04-06 21:11
@varunajmera0 Review my suggestion [in this comment](https://github.com/meteor/meteor/issues/7358#issuecomment-231144281) carefully.  From your screenshot, you are running `meteor npm install is-property` from the wrong directory, when you should be running it from that very, very long directory, _not_ from your app directory.

**Comment by kmullings** [comment] 2017-07-03 20:05
@kevrat 's solution at https://github.com/meteor/tutorials/issues/106 got me past this error. I first started by upgrading from 1.2.1 to 1.5.

Now I get the following errors:

✗ Android target: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment
  variable.
✗ Gradle: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
  Looked here: C:\Users\Keno Mullings\AppData\Local\Android\sdk\tools\templates\gradle\wrapper

**Comment by hwillson** [comment] 2017-11-01 14:42
It sounds like the original issue here has been resolved. If anyone is still encountering this issue, please  first try updating to Meteor 1.6, to see if the problem still occurs. Meteor 1.6 introduces many new Windows changes (like 64-bit support and a new installation process). Please post back if you're still having `is-property` issues after updating to 1.6. Thanks!

**Closed by hwillson** 2017-11-01 14:42 UTC
Labels: bug, confirmed, Impact:few, Project:Windows, Severity:has-workaround
