### ISSUE TITLE
DDPRateLimiter mistake in docs

### ISSUE THREAD

**Issue by minden** [meteor/meteor#5728] opened 2015-11-29 13:32 UTC
The DDPRateLimiter example in the [Meteor docs](http://docs.meteor.com/#/full/ddpratelimiter)
```javascript
var loginRule = {
  userId: function (userId) {
    return Meteor.users.findOne(userId).type !== 'Admin';
  },
  type: 'method',
  method: 'login'
}
```

does not work for me. But if I change `method` to `name` it works. 

Is this a bug in the documentation?

**Comment by lieuwex** [comment] 2015-12-01 18:50
Duplicate of #5505

**Comment by minden** [comment] 2015-12-01 19:06
@lleuwex thanks :)

**Closed** 2015-12-01 19:06 UTC

**Comment by lieuwex** [comment] 2015-12-01 19:07
@minden you're welcome :)

**Comment by zol** [comment] 2015-12-01 22:36
Thanks @lieuwex
