### ISSUE TITLE
[accounts-base@1.3.2] cause problem after route changed if routes defined in multiple packages

### ISSUE THREAD

**Issue by fly19890211** [meteor/meteor#9082] opened 2017-09-12 07:31 UTC
Hello,
I have few packages of UI,
* namespace:ui
* namespace:ui-login
* namespace:ui-stations
When i change route to the routes defined in ui-stations from ui-login after logged in. Meteor.userId() became null and redirect to login due to i have triggersEnter set in flow router.
The problem is appeared at accounts-base 1.3.2
once i switch back to accounts-base 1.3.1, everything works fine.
Is it a bug? or?
Thanks

**Comment by hwillson** [comment] 2017-09-12 12:04
Hi @fly19890211 - it's difficult to tell if this is a bug or not without seeing more details around how you have things wired up. Would you be able to put together a small reproduction demonstrating this issue? See [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more info. Thanks!

**Comment by fly19890211** [comment] 2017-09-13 03:25
Hi @hwillson 
Thanks your reply. It's really wired. If i changed the version of accounts-base 1.3.2 to 1.3.1 from version file under .meteor directory, everything works well, and the problem appear after changed to 1.3.2.
I will try to make reproduction. Thanks.

**Comment by hwillson** [comment] 2017-09-15 12:22
Looking into this further, I believe this is a duplicate of https://github.com/meteor/meteor/issues/9066. The problem is explained in https://github.com/meteor/meteor/issues/9066#issuecomment-327942248. Since there is more context in https://github.com/meteor/meteor/issues/9066, I'll close this issue. Thanks!

**Closed by hwillson** 2017-09-15 12:22 UTC
