### ISSUE TITLE
Flickering when resizing the window in comparison with React.js

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3733] opened 2015-02-15 01:41 UTC
At the [Hype! React Conf talk from 2015](https://www.youtube.com/watch?v=z5e7kWSHWTg) interesting demos were presented. One of them was also a iTunes style interface. I [implemented a Meteor version of it](https://github.com/mitar/reactconf-2015-HYPE) and discovered that while for me it seems the code is much cleaner and simpler, rendering is not so smooth as it is with React.js. For example, when you are resizing the window and you are making it smaller, album thumbnails first wrap, pushing the content down, and then rerender. This makes user interface to Flicker. In comparison with React.js where it is smooth. Would it be possible to improve this?
- You can see Meteor demo here: http://itunes.meteor.com/
- Original source code: https://github.com/ryanflorence/reactconf-2015-HYPE
- My code: https://github.com/mitar/reactconf-2015-HYPE

See the video linked above to see how React.js behaves, or just run it.

**Comment by tomByrer** [comment] 2015-02-15 02:23
IMHO related to your #3732; gank redraws due lower performance.  Perhaps Blase doesn't have a VirtualDOM like React?

**Comment by mitar** [comment] 2015-02-15 03:10
Not sure. I think this one is more linked to the fact how reactivity works. Maybe just some good way to trigger flush on resize is needed or something?

**Comment by jagi** [comment] 2015-02-15 11:21
I think that it's not a problem with Blaze itself. It looks like flickering is caused by reloading images. I haven't tried it locally but I assume it will work without such visible flickering. And notice that all demos in the React conference were run locally. Moreover I assume that maybe React preloads images before placing/rearranging them in inside DOM.

**Comment by jagi** [comment] 2015-02-15 12:02
When setting `viewportWidth.set(400)` manually flickering does not occur. It's seems like accumulation of resize events and reactive rerenderings causes it to stuck.

I've also made fix and set viewportWidth as standard variable and albumsPerRow as reactive one. It caused for example 3 rerenderings when resizing window but still causing flickering. It would be nice to have mechanism to stop calculations (rerendering) when new value was set on reactive variable. Of course it could cause situation when rendering will never finish.

Is is so expensing (comparing to React.js) to rerender DOM in Blaze? How do they do that in React.js?

**Comment by awatson1978** [comment] 2015-02-16 00:59
I spent a few hours fussing with this today, and think there are a few things going causing flicker...  there's no offset for the scrollbars, which seems to be causing wraparound; also, the viewportWidth isn't behaving reactively as expected; that, in turn, is causing the ``Object.keys(...).reduce(...)`` to not get reduced correctly, and the  rows now to be calculated.  

Replacing the ReactiveVar with a Session variable was a definite improvement; and swapping out the static rows with an inline unordered list using bootstrap made the wrap around butter smooth.  Problem with a wrap-around list, however, is that the album details have to be added in a dynamic bottom margin; and the current panel wasn't quite designed for that.

**Comment by mitar** [comment] 2015-02-16 02:14
>  there's no offset for the scrollbars, which seems to be causing wraparound

I was keeping things exactly the same as they were in original React code base (which does not flicker). See [here](https://github.com/ryanflorence/reactconf-2015-HYPE/tree/master/demos). Maybe I missed some CSS?

> also, the viewportWidth isn't behaving reactively as expected

This is strange. I would expect it to be? This is my addition to use Meteor reactivity.

>  in turn, is causing the Object.keys(...).reduce(...) to not get reduced correctly, and the rows now to be calculated. 

How so? It works for me. It is just slower or something.

> Replacing the ReactiveVar with a Session variable was a definite improvement;

What? This is really strange. ReactiveVar is much simpler than Session (no EJSON serialization). Why it would be faster?

>  and swapping out the static rows with an inline unordered list using bootstrap made the wrap around butter smooth.

This is a no-go. Original React code is not doing this, we should also not do this. I know that the structure could be improved, but I am trying to keep it as close to the original as possible.

**Comment by mitar** [comment] 2015-02-16 02:14
Thank you for looking into this, though! I think it is a great example to learn more.

**Comment by tomByrer** [comment] 2015-02-16 07:51
> I think it is a great example to learn more.

I also, cheers @awatson1978 & @jagi

**Comment by awatson1978** [comment] 2015-02-16 09:36
Okay, took another look at it, with the original code this time.  A couple of issues:

First, we can see that wrap-around is occurring.  The breakpoint is 988 pixels for 8 albums, when it should be 960 pixels, meaning there's something like a 28 pixel offset, which I'm pretty sure is caused by the scrollbars.  

![screen shot 2015-02-16 at 2 40 11 am](https://cloud.githubusercontent.com/assets/675910/6209254/9b1ddb5c-b591-11e4-83fe-b3c856258c75.png)

Secondly, I'm pretty convinced the flicker has everything to do with how the reactive variable (either Session or ReactiveVar) is attached to the event listener.

````js
Meteor.startup(function() {
   $(window).resize(function(event) {
     Session.set('viewportWidth', $(window).width());
    // viewportWidth.set $(window).width()
  });
});
````

You can test this by resizing the window and moving the mouse slowly and consistently, and watch as the elements haven't gotten the update of the new window size.  
![screen shot 2015-02-16 at 4 08 05 am](https://cloud.githubusercontent.com/assets/675910/6209324/ab448020-b592-11e4-91a1-7b2d813ed632.png)

The event listener only updates on the end of ``onresize``, then the session variable gets set, the tracker gets invalidated, which causes the context function to get rerun, which redraws the element.  Attaching to the ``onresizestart`` and ``onresizeend`` seems to help a tiny bit; but not much.

Anyhow, link to a javascript version, if anybody's interested:
https://github.com/awatson1978/reactconf-2015-HYPE/tree/master/26-itunes-javascript

**Comment by mitar** [comment] 2015-02-16 09:41
[See code here](https://github.com/ryanflorence/reactconf-2015-HYPE/blob/master/demos/06-itunes-style-interface/components/Albums.js#L280). Maybe the issue is that I am not taking the `innerWidth`? But for react they listen to `resize`, not `onresizestart` or `onresizeend`.

**Comment by mitar** [comment] 2015-02-16 09:44
I am not observing the issue with scrollbars thought. Maybe because I am on Mac OS X and you are not? Mac OS X has those overlayed scrollbars which do not make content smaller. For me the wrap around point is correct. It is just delayed a bit, so you see the wrapping of albums happen, and then Meteor redraws.

**Comment by awatson1978** [comment] 2015-02-16 09:51
Nah, I'm on Mac OSX also, and Chrome.  

What I'm trying to say is that the wrap-around should never happen in the first place.  The flickering is just a symptom of something wrong with the underlying layout logic.  And that apparently has something to do with the wrap-around functionality.

Just because it works smoothly in React doesn't mean that we can expect the same code to work smoothly in Blaze.  They're different engines, with different rendering pipes, reactivity models, virtual DOM implementations, CSS subsystem handling.  Just because React is optimized to do clever things with object maps and reductions doesn't mean that we can use the same maps/reductions with Blaze.  Similarly, React wouldn't necessarily know what to do with a Mongo cursor.

**Comment by jagi** [comment] 2015-02-17 13:03
The best way to investigate what's going on is setting break point on DOM modifications and everything gets obvious. React uses virtual DOM so every DOM modification happens behind scene and just after all calculations DOM is updated at once. In Blaze every remove and insert gets directly into DOM so it is way flickering happens.

React:
![react1](https://cloud.githubusercontent.com/assets/1051229/6228476/c0e46718-b6ac-11e4-91f4-ec15d6337b31.png)
![react2](https://cloud.githubusercontent.com/assets/1051229/6228478/c3c78834-b6ac-11e4-8e0e-a42be702bd07.png)
![react3](https://cloud.githubusercontent.com/assets/1051229/6228479/c5f59d76-b6ac-11e4-9638-fdd04e1dae55.png)

Blaze:
![blaze1](https://cloud.githubusercontent.com/assets/1051229/6228532/52bd78c8-b6ad-11e4-9856-eb96ec5c9441.png)
![blaze2](https://cloud.githubusercontent.com/assets/1051229/6228534/550fca40-b6ad-11e4-9c68-6b53a239a830.png)
![blaze3](https://cloud.githubusercontent.com/assets/1051229/6228535/56e05e7a-b6ad-11e4-8def-ea9db1977e09.png)
![blaze4](https://cloud.githubusercontent.com/assets/1051229/6228537/588ffd8e-b6ad-11e4-86b6-8c2bd521a620.png)
![blaze5](https://cloud.githubusercontent.com/assets/1051229/6228539/5a508288-b6ad-11e4-9d17-5c19fc892cb9.png)

However it's possible to remove flickering by using small hack. It's not solution for all situations. You can just add CSS style `white-space: nowrap` to albums row. It removes flickering but still every change is directly reflected into DOM.

In my opinion to resolve this problem the only solution is using virtual DOM.

**Comment by jagi** [comment] 2015-02-17 13:29
I would like to ask question here. How React is updating DOM at once? If they just replace HTML content of body tag then it requires to run HTML parser for the whole website what seems to be very CPU expensive. So I assume that they don't do it that way, so how?

If they update each albums row, then we would see the same effect like in Blaze.

So the only solution (in my opinion) is to update the first parent DOM element that holds all DOM modifications which still is very expensive if it happens just in the child of DOM.

**Comment by jagi** [comment] 2015-02-18 09:52
Take a look at this lib https://github.com/wilsonpage/fastdom

**Comment by stubailo** [comment] 2015-03-03 23:02
@mitar is it a sufficient workaround to add an `_.throttle` around the window resize event?

```
Meteor.startup ->
  $(window).resize _.throttle((event) ->
    viewportWidth.set $(window).width()
    return
  , 100)
```

Blaze doesn't batch the updates and do them on requestAnimationFrame, but you can achieve a similar effect by reducing the rate at which your variables change using `_.throttle` and `_.debounce`. Or, is there some other issue that this approach wouldn't address?

**Comment by mitar** [comment] 2015-03-04 08:31
This would slow down moving album images into another row, so with original CSS this would temporary make the last album image wrap its line, which would make things flicker. In fact the issue is that it is too slow reacting. That there is a delay. Which React.js does not have. So adding more delay is probably not the best? :-)

But I have not tested it with debounce.

**Comment by hwillson** [comment] 2016-11-28 18:20
@mitar - this has definitely been an interesting exercise/discussion. Should we consider anything in this thread to be actionable, and migrate it over to the Blaze repo? Or close it off as a historical exercise? Thanks!

**Comment by mitar** [comment] 2016-11-28 20:26
Let's just close this for now. I will reference this from performance Blaze issue.

**Closed** 2016-11-28 20:26 UTC
Labels: Project:Blaze
