### ISSUE TITLE
'node-gyp rebuild' installation error when adding a package to a meteor app

### ISSUE THREAD

**Issue by ZJoveski** [meteor/meteor#4802] opened 2015-07-24 00:56 UTC
I was trying to add a package (mizzao:turkserver) to my Meteor application, but I kept getting this error:

mizzao:turkserver: updating npm dependencies -- request, libxmljs, validator, querystring, async, deepmerge...
gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv
"C:\Users\Zlatko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os .windows.x86_32\dev_bundle\bin\\node.exe" "C:\Users\Zlatko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os .windows.x86_32\dev_bundle\bin\node_modules\npm\bin\npm-cli.js"
"install" "libxmljs@0.8.1"
npm ERR! node v0.10.36
npm ERR! npm v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.8.1 install: node-gyp rebuild
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the libxmljs@0.8.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

=> Babel active on file extensions: es6.js, es6, jsx
=> Errors while adding packages:

While building package mizzao:turkserver:
error: couldn't install npm package

I am developing my Meteor application on a Windows 7 machine and from what I have been able to gather from posts on forums, the error seems to be related to that fact (interaction between npm and Windows - I did not find any posts describing the same problem on Linux machines).

I've already tried installing the latest Python version and MS Visual Studio 2013 as suggested here: https://github.com/TooTallNate/node-gyp#installation, as well as setting some environment variables as suggested here: https://github.com/atom/atom/issues/2754. But none of those helped.

The error can be reproduced with the following commands:

> git clone https://github.com/ZJoveski/meteor_node-gyp_rebuild_windows_bug.git meteor_node-gyp_rebuild_windows_bug

> cd meteor_node-gyp_rebuild_windows_bug

> git clone --recursive https://github.com/HarvardEconCS/turkserver-meteor.git packages/mizzao-turkserver

> meteor add mizzao:turkserver

Any help would be greatly appreciated!

**Comment by mizzao** [comment] 2015-07-24 16:07
Original issue: HarvardEconCS/turkserver-meteor#24

So I was able to reproduce this on a fresh **Linux** VM (Ubuntu 14.04) without npm installed. Then, installing npm using apt-get made the problem go away.

Is it possible that the Meteor bundled npm is out of date, or possibly mismatched with the OS, and that Meteor uses the system installed npm if it is available?

**Comment by mizzao** [comment] 2015-07-24 16:09
Some clues here: lovell/sharp#163. 

It seems that installing npm system wide has the side effect of setting the Python path correctly in some config file, even if Meteor is not using that version of it.

**Comment by martijnwalraven** [comment] 2015-07-27 06:44
Thanks for the bug report and the clear reproduction. I've been able to replicate the bug, but I don't think setting the Python path is the issue here. My guess is the issue is related to the 259 character path limit on Windows.

If I try to install libxmljs manually using the bundled npm, I get the following output:

```
> if not defined npm_config_node_gyp (node "C:\Users\IEUser\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: Cannot find module 'is-property'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:338:15)
gyp ERR! stack     at Function.Module._load (module.js:280:25)
gyp ERR! stack     at Module.require (module.js:364:17)
gyp ERR! stack     at require (module.js:380:17)
gyp ERR! stack     at Object.<anonymous> (C:\Users\IEUser\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin\node_modules\npm\node_modules\node-gyp\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\index.js:1:80)
gyp ERR! stack     at Module._compile (module.js:456:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
gyp ERR! stack     at Module.load (module.js:356:32)
gyp ERR! stack     at Function.Module._load (module.js:312:12)
gyp ERR! stack     at Module.require (module.js:364:17)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\IEUser\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.3\\mt-os.windows.x86_32\\dev_bundle\\bin\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\IEUser\node_modules\libxmljs
gyp ERR! node -v v0.10.39
gyp ERR! node-gyp -v v1.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\IEUser\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.3\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe" "C:\\Users\\IEUser\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.3\\mt-os.windows.x86_32\\dev_bundle\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "libxmljs@0.8.1"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE
```

As you can see, 'is-property' is a deeply nested dependency of libxmljs, and this apparently causes trouble. This may be similar to the issue reported in https://github.com/mafintosh/electron-prebuilt/issues/40 and seems to have been fixed in more recent versions of npm.

As a workaround, you can upgrade the bundled npm yourself. To do so:
```
cd C:\Users\<username>\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin
npm install npm
```

For me, this upgrades npm from the bundled 2.7.3 to 2.13.2, and this allows me to install mizzao:turkserver without problems. Can you try this and report back whether it fixes the issue for you as well?

I'll make sure we bundle a more recent version of npm wit the Meteor 1.2 release.

**Comment by ZJoveski** [comment] 2015-07-27 16:00
Martijn, thank you for your reply! Unfortunately what you suggested does not solve the problem on my machine. After upgrading the bundled npm, I get exactly the same error statement, except that <code>npm ERR! npm v2.7.3</code> now gets changed to <code>npm ERR! npm v2.13.2</code>. 

I didn't check how deeply libxmljs is nested, but I did try to put my meteor app into a one-letter-named folder on the C: drive, but that was not enough I suppose. 

Another thing - while updating the bundled npm package, I was getting these warnings:
<pre> C:\Users\Zlatko\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x
86_32\dev_bundle\bin>npm install npm
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json asap@1.0.0 No repository field.
npm WARN package.json punycode@1.3.2 punycode is also the name of a node core mo
dule.
npm WARN package.json wcwidth@1.0.0 No repository field.
npm WARN package.json string_decoder@0.10.31 string_decoder is also the name of
a node core module.
npm WARN unmet dependency C:\Users\PC4all\AppData\Local\.meteor\packages\meteor-
tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin\node_modules\bl requires readable
-stream@'~1.0.26' but will load
npm WARN unmet dependency C:\Users\PC4all\AppData\Local\.meteor\packages\meteor-
tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin\node_modules\readable-stream,
npm WARN unmet dependency which is version 1.1.13
npm WARN unmet dependency C:\Users\PC4all\AppData\Local\.meteor\packages\meteor-
tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin\node_modules\node-gyp requires mi
nimatch@'1' but will load
npm WARN unmet dependency C:\Users\PC4all\AppData\Local\.meteor\packages\meteor-
tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin\node_modules\minimatch,
npm WARN unmet dependency which is version 2.0.4
npm WARN unmet dependency C:\Users\PC4all\AppData\Local\.meteor\packages\meteor-
tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin\node_modules\realize-package-spec
ifier requires npm-package-arg@'^2.1.3' but will load
npm WARN unmet dependency C:\Users\PC4all\AppData\Local\.meteor\packages\meteor-
tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin\node_modules\npm-package-arg,
npm WARN unmet dependency which is version 3.1.0
npm@2.13.2 node_modules\npm</pre> 

But I do not know if they point to the reason why your suggested fix did not work on my machine.

**Comment by Slava** [comment] 2015-07-27 17:04
@martijnwalraven I think the command `npm install npm@3` will make sure to install the version 3 and not upgrade to a different version 2.x.

**Comment by ZJoveski** [comment] 2015-07-27 17:19
Slava, I just tried <code>npm install npm@3</code>, but I still get the same error message.

**Comment by martijnwalraven** [comment] 2015-07-27 17:35
For me, updating to the latest npm 2.13.2 seemed to fix the problem, no need to install npm 3. I'll try again on a clean Windows install to make sure there are no confounding factors.

**Comment by martijnwalraven** [comment] 2015-07-27 19:56
Hmmm, the plot thickens... If I try this without a global node installed, `meteor add mizzao:turkserver` fails with `Exit status 7` first, and `Exit status 1` after updating to npm 2.13.2. The latter error seems to be a separate issue that is due to `node-gyp rebuild` not finding node. Adding the bundled node to the path fixes this error too, but that obviously shouldn't be necessary.

Investigating further why `node-gyp rebuild` does not find node, as we are supposed to add it to the path before calling an npm command.

**Comment by mizzao** [comment] 2015-07-27 20:25
Sorry that `mizzao:turkserver` is such a pain in the butt :D

**Comment by ZJoveski** [comment] 2015-07-27 20:34
Martijn, I am not sure if this changes anything in your investigation, but I do have a global node (v0.12.7) already installed on my computer.

**Comment by martijnwalraven** [comment] 2015-07-27 21:12
Time to go to sleep now, it's 11pm here. I'll continue this hunt tomorrow.

**Comment by ZJoveski** [comment] 2015-07-27 21:20
Good night! And thanks!

**Comment by martijnwalraven** [comment] 2015-07-28 01:22
Couldn't sleep... I looked into this further and it seems the reason the fix worked is not because of the npm version upgrade, but because a new npm install regenerates all of its dependencies.

For me, installing is-property at the top-level `node_modules` in `dev_bundle\bin` also seems to do the trick. Could you see if this fixes the issue for you?

```
cd C:\Users\<username>\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin
npm install is-property
```

In the next release, we're upgrading to npm 3 for generating the dev bundle on Windows, which should help avoid deeply nested dependencies and the resulting file path issues.

**Comment by ZJoveski** [comment] 2015-07-28 02:24
I am sorry for putting you into that much trouble. But, unfortunately, installing is-property did not help either. 

One thing that I missed previously (sorry about that) - updating the bundled npm did change <code>Exit status 7</code> to <code>Exit status 1</code>, as on your computer.

**Comment by martijnwalraven** [comment] 2015-07-28 14:12
Hmmm, there seem to be multiple things going on.

One issue is the missing is-property module which is due to deeply nested dependencies and the Windows path length limit. This leads to `Exit status 7` and as a workaround you can install is-property at the `dev_bundle\bin` level or reinstall npm there. Should be fixed on devel, where we're upgrading to npm 3 for generating the dev bundle on Windows.

On my computer, this seems to be enough to succesfully add the `mizzao:turkserver` package. I first thought not having a global node installed triggered `Exit status 1`, but for some reason I can't reproduce that now. It always seems to work! So I'm not sure what is going on.

On devel, I've improved error reporting when calling out to npm commands, which should help diagnose these problems. `mizzao:turkserver` has some incompatibilities that stem from the batch plugins work however, so I haven't been able to test it there.

It seems likely the error you're experiencing is due to `node-gyp rebuild` not finding node or running using the wrong version of node (0.12). When I try to install libxmljs under these conditions, I get the same `Exit status 1` from `npm install`. This shouldn't happen however, as we add the bundled node path to env.PATH before calling out to npm.

There is a bug I fixed on devel that leads to the bundled node path being added multiple times to env.PATH. One hypothesis is that this somehow leads to trouble, maybe because the environment variable becomes too long. But I haven't been able to reproduce this.

Unless you have new information, I think the best course of action is to get `mizzao:turkserver` working on devel (or the latest preview release, which is based off devel and contains the same changes to npm). If there is still a problem, it makes more sense to fix it there so we can get it in with the 1.2 release.

**Comment by mizzao** [comment] 2015-07-28 14:23
Hey @martijnwalraven - thanks for all your work on this. I'd be happy to try and get this working on the 1.2 branch. Do you have a pointer to the main changes that package authors would need to be aware of?

**Comment by martijnwalraven** [comment] 2015-07-28 14:44
There is a [forum thread](https://forums.meteor.com/t/try-out-a-preview-of-batch-build-plugins-and-other-1-2-features/7374) and [a Github issue](https://github.com/meteor/meteor/issues/4800) about the preview release. I haven't been involved in this work and I haven't spent too much time looking into these changes, but I think the main incompatibility is with dependencies on newer versions of packages like `stylus` that use the new build plugins API.

**Comment by mizzao** [comment] 2015-08-05 23:00
FYI, I'm also seeing this error on my Travis CI builds on OS X: https://travis-ci.org/HarvardEconCS/turkserver-meteor/builds/74311334

Might have something to do with a new version of something.

**Comment by mizzao** [comment] 2015-11-17 22:38
On Meteor 1.2, still getting the original error (`node-gyp rebuild`) as described here. Do you still think it's due to the long path name problem, or something else?

What do you recommend as the best course of action to diagnose what is going on?

**Comment by camilleeyries** [comment] 2016-03-21 16:27
What is the solution :(

**Comment by abernix** [comment] 2016-05-30 13:23
This is very likely the a problem of using a different version of node to install (and build) your module than the one that Meteor is running it with – the binary dependencies won't match up and you'll get this kind of error.

You can avoid this problem if you use Meteor 1.3.1 or higher and use the new `meteor npm install` command instead of just `npm install` when adding NPMs to your Meteor project.

If you're on an existing project, simply run `meteor npm rebuild` in the root of your project and it should rebuild anything that has binary dependencies and resolve this error.  Basically, this allows you direct access to the version of node that ships with Meteor and prevents you from having to maintain your own node version.

Since this involves Windows, I would additionally state that you will likely need to have a compiler installed to build NPMs that have binary dependencies – Microsoft Visual Studio Community Edition 2015 should work fine for this.

**Closed by abernix** 2016-05-30 13:23 UTC
Labels: Project:Windows

**Comment by metju90** [comment] 2020-02-20 08:45
> This is very likely the a problem of using a different version of node to install (and build) your module than the one that Meteor is running it with – the binary dependencies won't match up and you'll get this kind of error.
> 
> You can avoid this problem if you use Meteor 1.3.1 or higher and use the new `meteor npm install` command instead of just `npm install` when adding NPMs to your Meteor project.

This was the answer i've been looking for! Thanks
