### ISSUE TITLE
ES6: Incorrect context in getter.

### ISSUE THREAD

**Issue by Zodiase** [meteor/meteor#8583] opened 2017-04-10 18:52 UTC
See https://github.com/Zodiase/Meteor-Tests/tree/es6-getter-issue for reproduction.

What's wrong? `this` in `super.getterMethod` has the prototype of the parent, not the child.

What should happen? `this` in instance methods should always be the child.

The reproduction is testing in Meteor release 1.4.4.1, the latest version I could see in the `history.md`. But I encountered this issue while working in an app that's in Meteor release 1.4.2.3 so I'm not sure when this error was introduced.

P.S.: Just tried using babel repl to get the transpiled es5 code and run it. The result is also correct.

**Comment by hwillson** [comment] 2017-09-11 17:55
This is a duplicate of https://github.com/meteor/meteor/issues/8990. Closing here as there is more context in https://github.com/meteor/meteor/issues/8990. Thanks!

**Closed by hwillson** 2017-09-11 17:55 UTC
