### ISSUE TITLE
reset password url redirects to login page

### ISSUE THREAD

**Issue by a11anarete** [meteor/meteor#9701] opened 2018-02-27 15:51 UTC
### Description:

Password reset URL is going to the login page.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.3
* mongoDB Version: 2.6.12

### Steps to Reproduce:

1. When a user clicks on reset password.
2. User gets the email and a link to reset their password.
3. User then clicks on the reset password link.
4. User is redirected back to the login page.

### Expected behavior:

The link shows the reset password page

### Actual behavior:

The link goes to the login page

### Other information -- the email example below:

Hello,

To reset your password, simply click the link below.

`https://[hostDNS]/#/reset-password/[SHA256 hash]`

Thanks.

#### * I found that removing the `#/`, the link goes to the correct URL.

`https://[hostDNS]/reset-password/[SHA256 hash]`

---

#### Just for information, I was looking at the `app.js` which had this line and thought this was the problem.  I removed the `#/` and restarted the service but still the same error.

...
				Accounts.emailTemplates.resetPassword.html = function (userModel, url) {
					url = url.replace('/#/', '/');
					return html.replace(/\[Forgot_Password_Url]/g, url);
				};
...

---

code block:

https://github.com/RocketChat/Rocket.Chat/blob/develop/server/methods/sendForgotPasswordEmail.js#L14

---

#### I got around the problem by adding a place holder for the reset password URL.

``` javascript
https://hostname/reset-password/sha256
```

#### Can this be changed somehow, without this `/sha256`?

https://github.com/meteor/meteor/blob/devel/packages/accounts-base/url_server.js

#### Can the `#/` be remove as this seem to be causing the url issue?

---

Thanks in advance.

Allan

**Comment by hwillson** [comment] 2018-02-27 20:01
Hi @a11anarete - issues here are reserved for bugs with the Meteor platform itself. It's difficult to tell if you think there's a bug in Meteor core somewhere or not, since your report is referring to RocketChat specifically. If you think there is a bug in core somewhere, please provide a small runnable reproduction that demonstrates this bug, without using 3rd party packages. For support with RocketChat, try their [issues](https://github.com/RocketChat/Rocket.Chat) directly. Closing or now - thanks!

**Closed by hwillson** 2018-02-27 20:01 UTC
