### ISSUE TITLE
First time git commit will raise error on eslint

### ISSUE THREAD

**Issue by lucfranken** [meteor/meteor#7824] opened 2016-09-27 12:37 UTC
I am in the process of testing the tutorial and other first time user issues related to: https://forums.meteor.com/t/community-involvement-setup/29538/29

**Case:**
Given: I forked the Meteor repository.
As a first time contributor to the meteor/meteor repository.
I try to make my first commit.
I expect to be able to do that without issues.
Actual: I get an error.

I setup my local checkout as described in: 
https://github.com/meteor/meteor#slow-start-for-developers

Then I did a commit with this as a result:
<img width="494" alt="schermafbeelding 2016-09-27 om 14 22 27" src="https://cloud.githubusercontent.com/assets/1609379/18873260/c085aade-84be-11e6-8f51-e3f1856d2a7b.png">

Because that failed I followed the instructions and ran the following command:

`./scripts/admin/eslint/eslint.sh`

That command gives me no useful output except a list of NPM packages. I expected a lint result but it just shows nothing. After running this command I can actually commit. So it seems to install some dependencies but **does not tell me to retry committing**.

Shouldn't those dependencies be just installed when I run my local checkout as a developer?

Version: 4c2ba4f

**Comment by abernix** [comment] 2016-09-27 16:26
I don't experience this same problem on a fresh checkout, however I use `git` on the command line.  Is that GitHub Desktop that you are using?

Assuming that you did run `./meteor --help` (or any `./meteor` command) at least once before attempting a commit, it would have installed the Git hooks which enable the linting.  Then, when you made your first commit, it would have executed `./scripts/admin/eslint/eslint.sh` for you, which would have in turn NPM installed the `eslint` executable into the `./scripts/admin/eslint/node_modules/.bin` directory.  But this is all assumed to be done on the command line.

I'm guessing GitHub Desktop doesn't have access to the proper environment to run the `eslint.sh` script properly.  If you run `./scripts/admin/eslint/eslint.sh` once on the command line, you might be able to use the GUI successfully.  The output from that command is actually helpful, it's showing that it's installing the `eslint` NPM module.

 I'm not sure what there is to do about this aside from recommend that you use `git` command line tools.  Is there more error output above that `Cannot find module` message?

**Comment by lucfranken** [comment] 2016-09-27 17:54
Yes, that's Github desktop. As related with the the other issues I am trying out how we can make contributing easier for developers by trying it out myself. 

Steps to take to reproduce the same behavior as I did above are below. 

1. Command line: git clone --recursive git://github.com/meteor/meteor.git (copy paste from README.md)

2. Github desktop: Add local repository:

<img width="229" alt="schermafbeelding 2016-09-27 om 19 22 27" src="https://cloud.githubusercontent.com/assets/1609379/18884459/c1cc95be-84e7-11e6-844d-49adfd8ffab4.png">

3. Create branch and make a commit:

<img width="687" alt="schermafbeelding 2016-09-27 om 19 23 14" src="https://cloud.githubusercontent.com/assets/1609379/18884491/e2f7a706-84e7-11e6-804e-83756113293e.png">

4. That will raise an error because I am not allowed to push to the Meteor repository (see my edit on: https://github.com/meteor/meteor/pull/7823):

<img width="487" alt="schermafbeelding 2016-09-27 om 19 23 38" src="https://cloud.githubusercontent.com/assets/1609379/18884500/ed2a2384-84e7-11e6-8666-20fc575468e9.png">

5. So I change to my fork:

<img width="291" alt="schermafbeelding 2016-09-27 om 19 27 14" src="https://cloud.githubusercontent.com/assets/1609379/18884614/70e75d90-84e8-11e6-8f4c-472a3d6e6e16.png">

I have to use: https://github.com/lucfranken/meteor.git otherwise it gives an error, so I do that:

<img width="525" alt="schermafbeelding 2016-09-27 om 19 28 20" src="https://cloud.githubusercontent.com/assets/1609379/18884644/9910a344-84e8-11e6-8a63-7258ef5795e0.png">

Now I can commit, and it won't run the eslint hook, as you correctly posted, it's not installed. So this commit went out without eslint: b7949c67cbedb09122420370f211ed8d62665b38

The pre-commit hook is not ready yet.

**What I do next:**

I did not run meteor --help, I am trying to fix an issue so that would not come up and is not required by the manual linked. Maybe it should be but then a command like: meteor --prepare would be more clear. I don't expect --help to have any side effects outside of showing help text in console.

**Run my project**

What I do, _which makes sense to me_, is just run my project with this Meteor checkout and that runs some automated scripts:

```
../mtemp/meteor/meteor 
It's the first time you've run Meteor from a git checkout.
I will download a kit containing all of Meteor's dependencies.
######################################################################## 100,0%
Installed dependency kit v4.2.11 in dev_bundle.
etc
```
Now when I create a JS error I get:

```
Linting Meteor tool code...
env: node: No such file or directory
module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/xxxxx/mtemp/meteor/scripts/admin/eslint/node_modules/.bin/eslint'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
Linter errors detected in pre-commit hook.

Run the linter with ./scripts/admin/eslint/eslint.sh

If you know what you are doing you can disable this
check using:

  git config hooks.ignore-eslint true

 (1)
```

I cannot proceed. I have to run that script eslint.sh otherwise I cannot go further. As far as I can think it should just run that script when it's running the "It's the first time you've run Meteor from a git checkout." ?

**Comment by abernix** [comment] 2016-09-27 18:05
> That will raise an error because I am not allowed to push to the Meteor repository (see my edit on: #7823):

Yes, as with all open source projects you cannot just push directly to anyone's repository.  Contributors need to fork, make changes, and submit those changes as pull requests.  There's really nothing to do to improve this other than explain the process of using Git.  But frankly, if the users don't understand this concept, they're probably going to have issues making meaningful contributions to the project.

> I did not run meteor --help, I am trying to fix an issue so that would not come up and is not required by the manual linked.

I know it doesn't seem intuitive to run the `--help` command, but to be fair, it does actually say to run `./meteor --help`, and it does not have it marked as `OPTIONAL` as with the previous command.  It doesn't say to make a commit to Meteor before running that command, as you did.  Perhaps it would be more clear to specify that they should run the command `./meteor --get-ready` (which is a much more extreme step, but might be more clear).

But yes, if you don't run `./meteor` first, on the command line (with SOME sort of command, `--help` or otherwise), it will not properly setup the `.git/hooks` and the `eslint` command will not be installed properly.

**Comment by lucfranken** [comment] 2016-09-27 18:25
@abernix I know and I get it, for more context see: https://forums.meteor.com/t/community-involvement-setup/29538/31 which is the thread which my work is based on: I am trying to find and remove barriers for Meteor adoption in both starting (with the tutorial) and in helping with fixing bugs etc for advanced users. So I will write those issues down as a simple user and try to use simple tools. As you can see in for example #7825 I did make a fork off course.

The explicit instruction at this moment is simply wrong:

> If you want to run on the bleeding edge, or help develop Meteor, you can run Meteor directly from a git checkout.
`git clone --recursive git://github.com/meteor/meteor.git`

> I know it doesn't seem intuitive to run the --help command, but to be fair, it does actually say to run ./meteor --help, and it does not have it marked as OPTIONAL as with the previous command.

Yeah, get it, but that's not the point. Do you and other maintainers of the repo think we should fix this kind of issues or is that not desired? The discussion on the semantics is not really relevant in that.

When the maintainers are happy that you need to call some command to get the environment stable I am fine with that. Then we should make the documentation a bit more clear. If we can fix the issue we can do that in my opinion.

**Comment by abernix** [comment] 2016-09-27 23:30
Yes, I'm following that thread.  Though, it's really not a thread about removing barriers for Meteor adoption, but rather a call for contributions from the community from members who are familiar enough with the various parts to help.

If you're legitimately struggling getting your environment up using the steps listed in the `README`, then yes, we should figure out adjustments to those steps – for example, adding more explicit instructions on how to use the checked-out `meteor` to run a Meteor project (as you suggested in the PR) is a great idea.  However, if you're merely pretending to be a more simple user to suggest improvements, I'm not sure that's helping.  (And I'm basing this on your recurring mention of "simple user").

Also, if you're suggesting that the Meteor README also walk you through the Git-related steps of forking the repository in order to submit a commit and a PR, I'm not sure I agree with getting down to that level of detail – though maybe linking to some other pre-existing Git-HOWTO might be appropriate?

> The explicit instruction at this moment is simply wrong: 

The instructions seem to be right.  It's not just that one command; there are many steps in that section.  If this isn't clear, perhaps adding more sub-section headers or numbered bullet points could help?  If you run the rest of the commands (excluding the one that was marked `OPTIONAL`), you should have a working development environment.  That being said, I doubt it works properly in GitHub Desktop – the instructions are not counting on that and the git hook is probably to blame for this.  Maybe that can be improved, but GitHub Desktop probably relies on the global `PATH` and nothing else.

> Do you and other maintainers of the repo think we should fix this kind of issues or is that not desired?

I think the commands should be clear to get contributors up and modifying the core code themselves as easily as possible so they can troubleshoot bugs.  Right now, I don't believe that's particular hard and I believe the instructions are accurate.  Hopefully these users will be able to submit PRs, but I think it's expected that these users know how to Fork & PR, if they so desire.  I think the more difficult task here is not running Meteor from checkout, but rather finding the users who are willing to make the contributions.

**Comment by lucfranken** [comment] 2016-09-28 06:50
Following the exact steps on the command line:

```

xxxx:Software xxxx$ git clone --recursive git://github.com/meteor/meteor.git
   Cloning into 'meteor'...
   remote: Counting objects: 157305, done.
   ----- cloning and more cloning ----
   Unpacking objects: 100% (80/80), done.
   Checking connectivity... done.
   Submodule path 'packages/non-core/blaze/tests/test-runner': checked out '5a1e5b01b39504bfbf4a42193ca56eade85224f2'
xxxx:Software xxxx$ cd meteor
xxxx:meteor xxxx$ ./meteor --help
   It's the first time you've run Meteor from a git checkout.
   I will download a kit containing all of Meteor's dependencies.
   ######################################################################## 100,0%
   Installed dependency kit v4.2.11 in dev_bundle.

   meteor: updating npm dependencies -- meteor-deque...
   modules-runtime: updating npm dependencies -- install...
   modules: updating npm dependencies -- reify...
   ---- more updating npm dependencies ----
   logging: updating npm dependencies -- cli-color...
   xmlbuilder: updating npm dependencies -- xmlbuilder...
   Usage: meteor [--release <release>] [--help] <command> [args]
          meteor help <command>
          meteor [--version] [--arch]

   With no arguments, 'meteor' runs the project in the current
   directory in local development mode. You can run it from the root
   directory of the project or from any subdirectory.

   Use 'meteor create <path>' to create a new Meteor project.

   Commands:
      run                [default] Run this project in local development mode.
      debug              Run the project, but suspend the server process for debugging.
      ---- more help command ---
      search             Search through the package server database.
      show               Show detailed information about a release or package.

   See 'meteor help <command>' for details on a command.

xxxx:meteor xxxx$ cd docs/
-bash: cd: docs/: No such file or directory

```

I see that the docs app is missing. Not sure if that one has side effects in this case.
Will get back to your other feedback in a separate comment.

**Comment by abernix** [comment] 2016-09-28 08:37
Ok, yes, sorry – you caught me: I've never actually finished those steps myself and have always stopped before the `docs` part 🙊, but I knew the steps before that would get you a working `devel` environment.  And as you can see from that output, it did!  So, yay. :smile:

Could you update your PR to remove the docs part?  They are no longer a stand-alone Meteor application and have been moved to their [own repo](https://github.com/meteor/docs/) where they're maintained separately.  This will make the steps look less daunting too. :)

**Comment by lucfranken** [comment] 2016-09-28 08:53
Updated: 309e545

Not here to catch someone, this is exactly why I was testing as a new user. To see the experience. Never followed those steps myself too, we just know to click fork etc. but it's not that simple. 

Also added a little note that you need to run at least one Meteor command. Let's do further discussion on that PR on this topic.

**Comment by lucfranken** [comment] 2016-09-28 09:30
> Yes, I'm following that thread. Though, it's really not a thread about removing barriers for Meteor adoption, but rather a call for contributions from the community from members who are familiar enough with the various parts to help.

Agree, see below:

> If you're legitimately struggling getting your environment up using the steps listed in the README, then yes, we should figure out adjustments to those steps – for example, adding more explicit instructions on how to use the checked-out meteor to run a Meteor project (as you suggested in the PR) is a great idea. 

Agree, good it's getting to merge. We can improve on it further later.

> However, if you're merely pretending to be a more simple user to suggest improvements, I'm not sure that's helping. (And I'm basing this on your recurring mention of "simple user").

To be clear I did 2 things:
- Test starting with Meteor as a brand new Meteor developer, so following the tutorial (see: https://github.com/meteor/guide/issues/568 for example).
- Trying to fix a bug in Meteor as an experienced developer but with no prior Meteor organization knowledge. So the person who is building an app (from the standard Meteor installation off course) and encounters an issue while doing that. How could he fix that? That's what I try to test and improve.

> Also, if you're suggesting that the Meteor README also walk you through the Git-related steps of forking the repository in order to submit a commit and a PR, I'm not sure I agree with getting down to that level of detail – though maybe linking to some other pre-existing Git-HOWTO might be appropriate?

Yes, the README should be in my opinion a very simple quick start. Maybe we should have something like jQuery is doing here:
https://github.com/jquery/jquery#contribution-guides
which links to:
http://contribute.jquery.org/commits-and-pull-requests/

How do you think about that? I think there are enough experienced developers who work with git only in their own organization (so they have all rights). Where adding a contribution with forking is a new experience. I like their first point: 

> If you didn't fork the repository initially and instead cloned it directly from the jQuery organization

Just what I did when following the instructions literally. That sort of things happen and I think we can help developers with that kind of issues.

> That being said, I doubt it works properly in GitHub Desktop – the instructions are not counting on that and the git hook is probably to blame for this. Maybe that can be improved, but GitHub Desktop probably relies on the global PATH and nothing else.

https://github.com/meteor/meteor/pull/7823 was made with GitHub desktop. I don't think there is any technical issue with it. Only thing which might be different is that you need to do some rebasing which is hard stuff. I see @glasser linked to https://github.com/blog/2243-rebase-and-merge-pull-requests which is very interesting on that point I think.

> Do you and other maintainers of the repo think we should fix this kind of issues or is that not desired?
I think the commands should be clear to get contributors up and modifying the core code themselves as easily as possible so they can troubleshoot bugs. Right now, I don't believe that's particular hard and I believe the instructions are accurate. Hopefully these users will be able to submit PRs, but I think it's expected that these users know how to Fork & PR, if they so desire. I think the more difficult task here is not running Meteor from checkout, but rather finding the users who are willing to make the contributions.

Here is a big difference I think in developers who are experienced with open-source contributions and the new ones who are actually good developers but not experienced with those processes. The quality of the contributions should be up-to-par with the high level of quality in the Meteor repo. On the other side any barriers which are not needed should in my opinion be removed.

Thanks for your comprehensive answers and support on the points made @abernix !

**Comment by abernix** [comment] 2016-09-29 16:53
> Trying to fix a bug in Meteor as an experienced developer but with no prior Meteor organization knowledge. So the person who is building an app (from the standard Meteor installation off course) and encounters an issue while doing that. How could he fix that? That's what I try to test and improve.

I think we'll do that with improving the "Slow start" section as we've already discussed in the PR that is now open for this.

> Yes, the README should be in my opinion a very simple quick start. Maybe we should have something like jQuery is doing

Wow.  That's a great guide by them.  I don't think we want to reproduce that but maybe linking to some of [the GitHub docs](https://help.github.com/articles/fork-a-repo/) one is a good start.  This is another conversation though.  More on that in a minute...

> #7823 was made with GitHub desktop. I don't think there is any technical issue with it.

But there is: GitHub Desktop doesn't work the same as the shell and doesn't work with the `PATH` the same way.  There are a number of issues about this if you search "GitHub Desktop git hooks" on Google.  Even if it could work with the Git hooks, it's going to be very hard to read the lint problems or interact with that small window.  Really, I do not recommend using GitHub Desktop for this and I would probably even put that into the docs.  Maybe add it as a disclaimer to the top of the instructions in the PR you have open right now?

****

I don't think we're ready to do it yet, but I'm beginning to think that the "Slow Start (for developers)" section should probably be moved into the `Contributing.md` guide.

Anyway, let's try to wrap up this issue because this discussion is already getting too many angles to it.  These issues are meant to have actionable items, so as it stands right now, let's try to wrap up the pull request that's attached to this issue.  We can have additional discussion about ideas for things in the forums on the thread for community participation and open issues with specific actionable items later on.

> Thanks for your comprehensive answers and support on the points made

And thanks for trying to help get things organized!  This is no easy beast! :smile:  We'll talk more about these other things in the forums (it looks like these topics are unfolding already).

**Comment by abernix** [comment] 2016-10-24 15:58
@lucfranken With the README updated (with #7823), can we break this down into smaller issues or close it?  As it stands right now I think the main remaining issues here are to to 1) add a disclaimer for GitHub Desktop, 2) Breakdown the slow start into more of a `BUILDING.md` (per the discussion in the PR).  But I'd like to get this closed if we can. :smile:

**Comment by lucfranken** [comment] 2016-10-25 11:15
@abernix Sure just close it. Always better to have small actionable items.

**Comment by abernix** [comment] 2016-10-25 11:26
Thanks for your help on this!  Let's continue to improve!

**Closed by abernix** 2016-10-25 11:26 UTC
Labels: Project:Docs
