### ISSUE TITLE
Meteor Accounts Facebook error: 666

### ISSUE THREAD

**Issue by rsmelo92** [meteor/meteor#8672] opened 2017-05-05 17:46 UTC
I'm running METEOR@1.4.1.3
Package: jsep:facebook-native-login (that uses accounts-facebook and cordova-plugin-facebook4)
I'm expecting to login with facebook both on my cordova app and in my site.

I'm trying to login with facebook, but I'm getting a strange error:
`Object { stack: "errorClass@http://localhost:3000/pa…", error: 666, reason: "{"createdAt":"2017-05-05T17:39:19.8…", details: undefined, message: "{"createdAt":"2017-05-05T17:39:19.8…", errorType: "Meteor.Error" }`

This error with code 666 (weird) has no details, no reason and no message. The only thing that shows is the information pulled from facebook like my name, gender etc, so it's working half way.

I think that is a bug beacuse I never saw an error with code 666

How can I find out what is happening so I can fix it?

Thank you

**Comment by hwillson** [comment] 2017-05-05 17:59
Hi @rsmelo92 - sorry to hear you're having trouble! Issues in this repo are reserved for bugs / feature requests for the Meteor platform itself, not third party packages. Since you're having issues with third party packages, I'd suggest reaching out via the repo's associated with those packages, or on the [Meteor forums](https://forums.meteor.com) /  [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor). If you're confident this is an issue with Meteor's `accounts-facebook` package/support, please provide a runnable reproduction demonstrating this issue (using the features that Meteor has built-in directly - not leveraging third party packages). Please see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more info. Closing - thanks for your understanding!

**Closed by hwillson** 2017-05-05 17:59 UTC
