### ISSUE TITLE
Add possibility for special characters in organization names 

### ISSUE THREAD

**Issue by Urigo** [meteor/meteor#3658] opened 2015-02-06 09:27 UTC
I would love to add the angular-ui organization to Meteor.

I will add it as angularui because organization names can contain lowercase letters a-z and digits 0-9, and must be at least three characters long.

It is possible to change that?  (I haven't found where it is in the code)

**Comment by glasser** [comment] 2015-02-10 23:23
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

This seems reasonable.

**Comment by glasser** [comment] 2015-03-23 20:20
Duplicate of #2487

**Closed by glasser** 2015-03-23 20:20 UTC
Labels: feature, Project:Developer Accounts
