### ISSUE TITLE
Cannot read property '0' of undefined METEOR@1.2-rc.12

### ISSUE THREAD

**Issue by leocavalcante** [meteor/meteor#5108] opened 2015-09-04 22:43 UTC
Any help creating Meteor 1.2 apps on Windows?

![image](https://cloud.githubusercontent.com/assets/183722/9695880/17c26328-533d-11e5-9c11-5dba59a15a7f.png)

**Comment by martijnwalraven** [comment] 2015-09-05 06:03
Duplicate of #5088.

**Closed by martijnwalraven** 2015-09-05 06:03 UTC
