### ISSUE TITLE
Error output is  incomplete in Windows PowerShell

### ISSUE THREAD

**Issue by damien-monni** [meteor/meteor#9118] opened 2017-09-20 11:48 UTC
Since the Windows 10 anniversary update the standard command prompt has been removed from the context menu and is now replaced by PowerShell so Windows users are encourage to use PowerShell instead of command prompt. First, as related in issue #4133, the blue color is hard to see. Second,
errors are not shown with details as it is in command prompt.

![cmd](https://user-images.githubusercontent.com/6009968/30642151-072bf9ce-9e0a-11e7-9027-35d9caadf017.jpg)

As you can see, PowerShell on the left only displays `(STDERR)` instead of the complete error shown in the command prompt on the right.

I am using Meteor 1.5.2 (but I've noticed this problem for a long time now).

**Comment by hwillson** [comment] 2017-09-20 11:57
Ouch - thanks @damien-monni - confirming this (and https://github.com/meteor/meteor/issues/4133) as a bug. If anyone is interested in working on PR for this, that would be awesome!

**Comment by abernix** [comment] 2017-09-20 12:59
@damien-monni So sorry about that – that must be frustrating.  Our resource allocation to work on Windows issues is certainly limited at the moment and the biggest factor is a lack of Windows-based community members working on Meteor core.  Plus, trying to fix these issues from a VirtualBox can be hard.

Would this be something you might be able to help look into?  No worries if you can't, but I'm sure fellow Windows developers would appreciate it!

**Comment by abernix** [comment] 2017-09-20 13:02
I should add:  As with anyone interested in helping or unsure how, other contributors and I are happy to guide if you post any issues you encounter getting started.  Most of what you'd need to get started will hopefully be in the [Development](https://github.com/meteor/meteor/blob/devel/Development.md) documentation though!

**Comment by damien-monni** [comment] 2017-09-26 15:20
Unfortunately I really won't have time to dig into Meteor core code. I guess you should be able to reproduce the error in a Windows 10 VirtualBox.
I can still test things in a real Windows 10 if needed.

It seems to happen when the error is related with MongoDB.
The most simple case to reproduce:

* Create a new Meteor project
```cmd
meteor create myapp --bare
```

* Add a new index.js file like this:
```javascript
import { Mongo } from 'meteor/mongo';

const todos = new Mongo.Collection('todos');
todos.hey();
```

In command prompt, the error message is good: `TypeError: todos.hey is not a function` but in PowerShell we just have `(STDERR)`

**Comment by agathver** [comment] 2017-10-01 08:13
Hi,
I am interested to work on this over this week. I've been looking around meteor code for contributing and this seems as a good starting point.

**Comment by agathver** [comment] 2017-10-02 20:10
It seems that the color `magenta` hardcoded in logging.js is incompatible with powershell. What could be a potential replacement color ?

**Comment by klaussner** [comment] 2017-10-02 20:23
Maybe red with a black background, like other PowerShell error messages?

![PowerShell error](https://user-images.githubusercontent.com/1312807/31097617-2a9df794-a7c0-11e7-927a-6c30cae33661.png)

**Comment by agathver** [comment] 2017-10-02 20:43
@klaussner We already use red for errors, it seems.

**Comment by damien-monni** [comment] 2017-10-11 15:30
I don't think the issue should be closed. The issue is about error details not showing in PowerShell. The colors issue is issue #4133, not this one, even if it is related.

**Comment by abernix** [comment] 2017-10-12 07:33
@damien-monni Since it appeared in `cmd.exe`, it was believed that the error was there but simply not visible because the foreground color was _exactly_ the same as the background (you can test this by highlighting the text in PowerShell).

Can you make a quick reproduction which shows the problem? (Or better yet, can you [run Meteor from a checkout](https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md#running-from-a-git-checkout), debug, and [submit a PR](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#making-changes-to-meteor-core) that fixes the problem?)

**Comment by damien-monni** [comment] 2017-10-12 09:30
Unfortunately I don't have time to debug and submit a PR. I already wrote the most simple case to reproduce the error above, I'll copy and past it here again:

* Create a new Meteor project
```cmd
meteor create myapp --bare
```

* Add a new index.js file like this:
```javascript
import { Mongo } from 'meteor/mongo';

const todos = new Mongo.Collection('todos');
todos.hey();
```

Here is the result with and without hightlighting the text:

![image](https://user-images.githubusercontent.com/6009968/31489333-9543869a-af40-11e7-92ab-da33f61089b5.png)

The detailed error message is missing.

**Comment by agathver** [comment] 2017-10-12 13:17
@damien-monni I used this test case to debug my PR. I can confirm the case was for colors only.

**Comment by abernix** [comment] 2017-10-12 13:47
I've reproduced and confirmed that this is fixed with the fix by @agathver. (Thanks!)

@damien-monni This was not "related" to https://github.com/meteor/meteor/issues/4133. It is, in fact, the same identical issue.  Even the screenshot you've provided is basically the same, just cropped differently! :smile:

**Closed by abernix** 2017-10-12 13:47 UTC
Labels: bug, confirmed, Impact:some, Project:Windows, pull-requests-encouraged, Severity:has-workaround
