### ISSUE TITLE
"meteor add-platform ios" fail

### ISSUE THREAD

**Issue by leebenson** [meteor/meteor#3481] opened 2015-01-15 21:08 UTC
Meteor 1.0.2.1

Getting this error when trying to add iOS support...

**meteor add-platform ios --verbose**
```
Running command  /usr/bin/xcrun cc --version  
Doing HTTP request:  GET https://warehouse.meteor.com/cordova/license_cordova_ios.txt
% Ensuring the cordova build project          
% Ensuring that platforms in cordova build project are in sync
Using (built-in) Android SDK at /Users/leebenson/.meteor/android_bundle/android-sdk
% Running synchronously:  /Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'list' ]
                                              
/Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: Error running /Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Current working directory is not a Cordova-based project.


    at execFileSyncOrThrow (/Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:263:11)
    at ensureCordovaPlatforms (/Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:391:23)
    at /Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:2909:5
    at /Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:327:18
    at [object Object]._.extend.withValue (/Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:326:36
    at [object Object]._.extend.withValue (/Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at Object.enterJob (/Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:317:26)
    at Command.main.registerCommand.name [as func] (/Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:2904:16)
    at /Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1285:23
 ```

And subsequently this error when I try to remove it...

**meteor remove-platform ios**

```
ios: removed platform

/Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: Error running /Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Current working directory is not a Cordova-based project.


    at execFileSyncOrThrow (/Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:263:11)
    at ensureCordovaPlatforms (/Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:391:23)
    at Command.main.registerCommand.name [as func] (/Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:2967:3)
    at /Users/leebenson/.meteor/packages/meteor-tool/.1.0.38.oofmjj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1285:23
```

**Comment by Slava** [comment] 2015-01-15 22:06
Looks like your project's build is in some corrupted state?

As bad as it is, it doesn't look like we can extract such case into a reproduction and a fix. As a workaround, can your try cleaning the build and trying again? `meteor reset` or `rm -rf .meteor/local/cordova-build`.

**Comment by leebenson** [comment] 2015-01-16 09:36
A simple `meteor reset` did it - thanks!

Perhaps some integrity checking/roll-back when adding packages/platforms would be good. Looking back through my bash history, it looks like the Cordova package had a network timeout, and things went downhill from there.

**Comment by lorensr** [comment] 2015-03-05 22:46
This worked for me:
```
meteor reset
rm -rf .meteor/local/cordova-build
meteor remove-platform ios
meteor add-platform ios
```
Problem arose when I starting working with a fresh clone of my repo from github.

**Comment by youngfreezy** [comment] 2015-05-11 13:24
I get the same issue as above.  @lorensr I tried what you did, then get this error: 

```
App id contains a reserved word, or is not a valid identifier.


Error: Error running /Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
App id contains a reserved word, or is not a valid identifier.


    at execFileSyncOrThrow (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:272:11)
    at ensureCordovaProject (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:376:22)
    at /Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3019:5
    at /Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:327:18
    at [object Object]._.extend.withValue (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:326:36
    at [object Object]._.extend.withValue (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at Command.main.registerCommand.name [as func] (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3015:16)
    at /Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23

/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Error running /Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
    at execFileSyncOrThrow (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:272:11)
    at ensureCordovaPlatforms (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:405:23)
    at /Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3020:5
    at /Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:327:18
    at [object Object]._.extend.withValue (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:326:36
    at [object Object]._.extend.withValue (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at Command.main.registerCommand.name [as func] (/Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3015:16)
    at /Users/FareezAhmed/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
```

**Comment by lorensr** [comment] 2015-05-11 19:44
What are the contents of your mobile-config.js?

**Comment by youngfreezy** [comment] 2015-05-11 20:55
Hello,




My repo is right here, looks like there isn’t a mobile config. js, I did follow the instructions in the tutorial though :-/ how would you suggest proceeding?




https://github.com/youngfreezy/MeteorTutorial5.11



Thanks,
Fareez

**Comment by lorensr** [comment] 2015-05-11 23:20
Interesting bug you've found! I've created a new ticket with your problem: #4358 

You can get rid of the error by:

```
git clone https://github.com/youngfreezy/MeteorTutorial5.11
mv MeteorTutorial5.11 different_name
cd different_name
meteor remove-platform ios
meteor add-platform ios
```

**Comment by youngfreezy** [comment] 2015-05-11 23:32
Interesting, thank you @lorensr, so looks like it had something to do with my including Meteor in the title?

**Comment by lorensr** [comment] 2015-05-11 23:44
Think so, maybe also the period and numbers.

**Comment by jcommaret** [comment] 2015-05-21 14:05
I have exactly the same problem... @Slava is there someone who is trying to fix this problem @meteor ?

**Comment by lorensr** [comment] 2015-05-21 21:02
Don't think so – low-priority, since it can be fixed just by changing the
directory name.

**Comment by Slava** [comment] 2015-05-21 22:31
Cordova is not building if the folder has some symbols it didn't like? I think we can safely close this issue as a duplicate of one of the following: https://github.com/meteor/meteor/issues/2920 https://github.com/meteor/meteor/issues/3023 https://github.com/meteor/meteor/issues/2868

**Closed by Slava** 2015-05-21 22:31 UTC
Labels: Project:Mobile

**Comment by jamesgibson14** [comment] 2016-07-20 21:26
I have had this problem as well with 1.3.4

**Comment by lorensr** [comment] 2016-07-20 21:30
@jamesgibson14 were you able to fix it with `meteor reset` (warning – clears your db)? Or if you're talking about the reserved word error, making the name alphanumeric?

**Comment by jamesgibson14** [comment] 2016-07-20 22:48
yes, I reset and change the folder name, and it starting working.
