### ISSUE TITLE
Meteor fails to start in OSX when ExtJS is in public folder

### ISSUE THREAD

**Issue by Zodiase** [meteor/meteor#4889] opened 2015-08-05 21:21 UTC
How to reproduce the error:

1. Create a new Meteor app.
2. Create a public folder in the app.
3. Download and unzip the latest gpl version of ExtJS to the public folder.
4. Start the Meteor app.

As of Meteor version 1.1.0.3, the output is:
```
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/     

/Users/xh/.meteor/packages/meteor-tool/.1.1.4.o3g6d0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
                        throw(ex);
                              ^
Error: UNKNOWN, open '/Users/xh/Workspace/Github/Zodiase/meteor-tests/extjs-in-public/public/ext-5.1.1/test/specs/layout/container/Table.js'
    at Object.Future.wait (/Users/xh/.meteor/packages/meteor-tool/.1.1.4.o3g6d0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper [as readFile] (/Users/xh/.meteor/packages/meteor-tool/.1.1.4.o3g6d0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1350:24)
    at readFile (/Users/xh/.meteor/packages/meteor-tool/.1.1.4.o3g6d0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:226:18)
    at [object Object]._.extend._fireIfFileChanged (/Users/xh/.meteor/packages/meteor-tool/.1.1.4.o3g6d0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:339:20)
    at onWatchEvent (/Users/xh/.meteor/packages/meteor-tool/.1.1.4.o3g6d0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:478:16)
    at [object Object].<anonymous> (/Users/xh/.meteor/packages/meteor-tool/.1.1.4.o3g6d0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/func-utils.js:35:18)
    at /Users/xh/.meteor/packages/meteor-tool/.1.1.4.o3g6d0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:161:12
    - - - - -
```

You could also find the test project here: https://github.com/Zodiase/meteor-tests/tree/master/extjs-in-public

Note: A friend helped tested in Windows and could not reproduce the error so it could be OSX specific.

Any idea why this happens and how to fix it? Why is Meteor/fibers/future even touching whatever is inside the public folder?

**Comment by jorjordandan** [comment] 2015-08-06 06:12
Looks like load order to me - it's failing when it's called in the Table.js ... why not load it from the /lib folder? As far as fibers/future, a lot of errors are thrown from there, since that's generally where processes are managed.

**Comment by deanius** [comment] 2015-08-06 14:58
If you just place a CDN build of extjs in your public its fine.. Do the same with CSS..

```
rm -rf public/ext-5.1.1
curl https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/ext-all.js > public/ext-all.js
meteor 
``` 

In general arbitrary folders including node_modules, need to not be present in a meteor apps subdirectories - only the files that make up the app.

**Comment by Zodiase** [comment] 2015-08-06 16:22
@deanius
What I'm trying to do is to rely on ExtJS's microloader to dynamically load modules on demand instead loading the whole library up on starting. Therefore I can't use the built version.

Also, since Meteor is supposed to serve whatever in the public folder "as is", why would the content inside the public folder affect the Meteor app?

**Comment by deanius** [comment] 2015-08-06 20:48
Ahh, I see the issue now.

**Comment by glasser** [comment] 2015-08-11 22:19
Duplicate of #4660.

**Closed by glasser** 2015-08-11 22:19 UTC

**Comment by abernix** [comment] 2016-05-04 17:00
@Zodiase I can't download ExtJS at the moment – they e-mailed me a dead link to the download.

Is it safe to say that it's got a lot of files?

After you extract it into your `public/` directory, what does `find public/ -type f | wc -l` output when run in the root of your Meteor project?

**Comment by Zodiase** [comment] 2016-05-04 17:07
Since the old repo in the first post has been deleted, I created a new one here: https://github.com/Zodiase/Meteor-Tests/tree/meteor-issue-%234889. It has ExtJS 6.0.1 GPL put inside the public folder.

Result from starting the app:

![image](https://cloud.githubusercontent.com/assets/1815174/15021984/1aac8278-11ef-11e6-8199-eb83bd0a3745.png)

**Comment by Zodiase** [comment] 2016-05-04 17:09
> After you extract it into your public/ directory, what does find public/ -type f | wc -l output when run in the root of your Meteor project?

That would be 40227.

**Comment by abernix** [comment] 2016-05-04 17:16
Yeah, so that most likely *would* be the same problem as #4660
>lot of files in the public/ folder
Probably also related to #6966 and #6952

**Comment by queso** [comment] 2016-05-05 02:16
I am getting this same error on a Mac and I am not using extJS. I did add Chimp and Cucumber.js today. I added one more package from Xolvio (email-stub) and that seem to kill things for me.

I noticed running `find node_modules/ -type f | wc -l` returns 33968
