### ISSUE TITLE
Not fullpath of compile error files inside packages that use ecmascript package.

### ISSUE THREAD

**Issue by bySabi** [meteor/meteor#5551] opened 2015-10-27 18:10 UTC
When we create a package that use `ecmascript` package, build time errors  not show the file fullpath.
Ex:
 A package that not use ES2015 features (without `ecmascript`package ), build output error 

```
=> Errors prevented startup:

   While computing assigned variables:
   /packages/test_package/file.js: Unexpected token (4:1)

```

The same package with:  api.use('ecmascript') , build output error: 

```
=> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):
   file.js:2: file.js: Unexpected token (2:0)
```

On last example is impossible to know who package belong `file.js`. This is really a problem on projects that follow package base architecture like Telescope https://github.com/TelescopeJS/Telescope/tree/master/packages. 

I create a repo that reproduce the problem:  https://github.com/bySabi/not-fullpath-console-output

To see it, comment and uncomment the line: 
```
 //api.use('ecmascript')
```
on packages.js

**Comment by benjamn** [comment] 2015-10-27 22:57
Thanks very much for the reproduction. This should be fixed in the next version of Meteor.

**Closed** 2015-10-27 22:57 UTC

**Comment by trusktr** [comment] 2016-04-28 21:34
@benjamn I'm getting similar error in Meteor 1.3.2 with a forked version of momentjs:moment:

```js
=> Errors prevented startup:

   While computing assigned variables:
   /packages/momentjs_moment/templates/default.js: Unexpected token (6:0)
   /packages/momentjs_moment/templates/locale-header.js: Unexpected token (7:0)
   /packages/momentjs_moment/templates/test-header.js: Unexpected token (7:0)

   While computing assigned variables:
   /packages/momentjs_moment/templates/default.js: Unexpected token (6:0)
   /packages/momentjs_moment/templates/locale-header.js: Unexpected token (7:0)
   /packages/momentjs_moment/templates/test-header.js: Unexpected token (7:0)
```

Unfortunately, I can't reproduce the error with a simple repo, and I can't publish the large private repo I have. :[

**Comment by trusktr** [comment] 2016-04-29 04:51
I can confirm that this error happens when the package is symlinked into the packages/ folder. There's no error if I remove the sym link then cp -r the package into the packages/ folder.

**Comment by trusktr** [comment] 2016-04-29 06:58
Nevermind, the error came back after a while with the local copy. No idea what's going on here.

**Comment by trusktr** [comment] 2016-05-03 18:32
I remember one reason why this error happens now, as I had these errors when deving `rocket:module`: when the size of the package source in cache is not the size that the compiler expects we get this error. To reproduce, open up any package code in `~/.meteor/packages` then add a new line for example. This causes the compiler to stop reading the characters of the modified file before reaching the end of the file.

I haven't tested, but a `meteor reset` along with removing `~/.meteor/packages` would probably fix the problem in some cases.

**Comment by Elyx0** [comment] 2017-12-06 18:15
@trusktr Is there a way to change a line without getting caught by this error? Can we tweak the size of the source in cache?

**Comment by Elyx0** [comment] 2017-12-06 18:24
A shorter build (removing comments lines) for example gives the following error:

```bash
/Users/Elyx0/.meteor/packages/meteor-tool/.1.6.0.qo7in5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: couldn't read entire resource
    at Object.files.readBufferWithLengthAndOffset (/tools/fs/files.js:1814:13)
    at /tools/isobuild/isopack.js:1005:26
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/Users/Elyx0/.meteor/packages/meteor-tool/.1.6.0.qo7in5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack.js:1003:9
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/Users/Elyx0/.meteor/packages/meteor-tool/.1.6.0.qo7in5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:969:7)
    at Isopack.initFromPath (/tools/isobuild/isopack.js:889:17)
    at /tools/isobuild/isopack-cache.js:288:23
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Profile.time (/tools/isobuild/isopack-cache.js:274:24)
    at Function.time (/tools/tool-env/profile.js:305:10)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:264:15)
    at /tools/isobuild/isopack-cache.js:77:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/Users/Elyx0/.meteor/packages/meteor-tool/.1.6.0.qo7in5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at exports.PackageMap.eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:76:24)
    at /tools/project-context.js:847:25
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:846:18)
    at /tools/project-context.js:285:9
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:275:18)
    at Profile.run (/tools/project-context.js:267:12)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:266:13)
    at /tools/runners/run-app.js:554:29
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:553:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:622:35)
    at AppRunner._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:408:12
```

**Comment by micktaiwan** [comment] 2020-04-05 19:52
@Elyx0 did you find a solution ?
