### ISSUE TITLE
Running meteor in other iOS simulator device

### ISSUE THREAD

**Issue by mcchrish** [meteor/meteor#5684] opened 2015-11-20 05:56 UTC
It seems to me that meteor 1.2.1 only runs on iphone 6 simulator. How can I target a specify device when running in the simulator?

**Comment by martijnwalraven** [comment] 2015-11-20 11:44
There is no command line option for this, but if you use `meteor run ios-device`, which opens Xcode, you can select another simulator there.

**Comment by joaopiopedreira** [comment] 2015-11-20 19:50
Can be tricky... You're better off building your project (meteor build ...) and then open it in Xcode. There you can easily change your device.

João Pio Pedreira
/// Sent from a mobile device ///

**Comment by martijnwalraven** [comment] 2016-02-19 11:49
Closing this as a duplicate of #3430.

**Closed by martijnwalraven** 2016-02-19 11:49 UTC
Labels: desired, Project:Mobile
