### ISSUE TITLE
[1.3-beta.11] Meteor.isTest is not properly set

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#6331] opened 2016-02-24 15:58 UTC
Reproduction: https://github.com/aldeed/13isTestIssue

Steps:
1. Clone
2. `npm install`
3. `meteor test-app --unit`
4. Open localhost:3000 and view the test results to see the issues.

(You may have to `meteor run` before `meteor test-app --unit` because there also seems to be an issue sometimes where you can't run tests in a new project until you've run the app once.)

The main problem:

As the test results show, `Meteor.isTest` is set properly only in client code, not server.

The additional problem:

As I was setting up the repro app, I tried to use `chai` from `avital:mocha` but it does not properly import. It might be a problem with that package, but I figured I'd leave that in the repro app, too.

**Comment by avital** [comment] 2016-02-24 18:08
Looking at this now. First of all, I fixed the bug with `test-app` not working before running the app once: https://github.com/meteor/meteor/commit/0bbae6a58dfbd0e4a1f6c27c99fa8a585f959820

**Comment by avital** [comment] 2016-02-24 18:12
Fixed `Meteor.isTest` on the server: https://github.com/meteor/meteor/commit/70983aa865397f260ca4e733b2c14ed48a0f68d6

**Comment by avital** [comment] 2016-02-24 18:16
And, regarding chai -- the `avital:mocha` package "implies" `practicalmeteor:chai`, which means chai is available to apps and test. But "imply" doesn't make it possible to import symbols from `avital:mocha` -- you still need to import them from `practicalmeteor:chai`. (That's what the todos sample app also does).

@tmeasday @benjamn flagging you so you are aware of this issue. Other users might trip on it as well. I think it's something that people can just learn but it could be considered confusing that you need to learn something about the implementation of `avital:mocha` (and soon `practicalmeteor:mocha`) to use Chai. (We *could* potentially have "imply" also imply ES6 imports...)

**Comment by aldeed** [comment] 2016-02-24 18:50
@avital Awesome thanks! The reason I was trying to import chai that way was because it's in the current draft guide article here: https://github.com/meteor/guide/blob/testing-modules-content/content/testing.md#defining-a-mocha-test

As long as that example is fixed before the guide article is final, I don't think it will be an issue.

That said, I was initially confused about implied packages exports not being available in some other circumstances. I agree it is something people will learn, but I think it would be nice if there is a way a Meteor package can "forward" the exports from its implied packages explicitly in the `package.js`. That way package authors can simplify things a bit if they want to, and it matches the pre-1.3 behavior better.

**Comment by tmeasday** [comment] 2016-02-24 22:46
@aldeed thanks for pointing that out, I've updated the example there.

I agree it's confusing about implied exports---@benjamn I remember discussing this a while back; is this something we explicitly decided not to support?

**Comment by aldeed** [comment] 2016-03-07 21:00
@tmeasday @benjamn, I have updated my repro (https://github.com/aldeed/13isTestIssue) with a couple additional tests. If you run the tests you can see that `Meteor.isTest` is still not correctly set in top-level package code though the original issue is fixed. I don't know if this is fixable but if not, it is something worth noting in the guide. Also, I was thinking it might be better to use env variables like `process.env.METEOR_IS_TEST = true` so that it can be checked more easily in node modules?

**Comment by avital** [comment] 2016-03-07 23:08
Yes, looks like this is happening because the code in `tools/isobuild/linker.js` puts the result of `getTestPreamble()` right before the app code, as opposed to right after the `meteor` package code. I thought the following diff would fix the problem but it seems to cause other build errors.

```
diff --git a/tools/isobuild/linker.js b/tools/isobuild/linker.js
index 118130f..cbf859a 100644
--- a/tools/isobuild/linker.js
+++ b/tools/isobuild/linker.js
@@ -978,11 +978,14 @@ export var fullLink = Profile("linker.fullLink", function (inputFiles, {
   // Include a short code snippet that sets `Meteor.isTest` and calls
   // `runTests`.
   if (global.testCommandMetadata) {
-    var weAreLinkingTheApp = (name === null);
-    if (weAreLinkingTheApp) {
-      prelinkedFiles.unshift({
+    // The `meteor` package comes first, so that's where we need to
+    // set `Meteor.isTest`
+    var weAreLinkingTheMeteorPackage = (name === 'meteor');
+    if (weAreLinkingTheMeteorPackage) {
+      // Add this file right after the `Meteor` symbol is defined
+      prelinkedFiles.push({
         source: getTestPreamble(),
-        servePath: "/packages/runTests.js"
+        servePath: "/packages/meteor-test-env.js"
       });
     }
   }
```

**Comment by aldeed** [comment] 2016-03-07 23:33
Thanks @avital. Can someone reopen this?

**Comment by tmeasday** [comment] 2016-03-09 03:36
Unfortunately @avital's approach isn't going to work AFAICT because the built+linked meteor package is cached between runs, which means if you switch from `meteor run` to `meteor test` you may get the wrong version.

**Comment by tmeasday** [comment] 2016-03-09 04:33
Ok, at @benjamn's suggestion, I've committed a change that passes the test metadata into the app via an environment variable, which is picked up by the `meteor` package at runtime. Some potential issues with this:

1. It doesn't come through to the client (yet). I would assume I can do that via a similar mechanism to 40857bdaff7ea648145ff1f1defb4ad8020287de

2. I'm not sure it'll work for `meteor test[-packages] --deploy`. I'm not sure what the status is of this feature (we could a) try to make it work, b) make it only work for `test-packages`, c) remove it entirely). @zol, thoughts here?

**Comment by tmeasday** [comment] 2016-03-09 04:50
https://github.com/meteor/meteor/pull/6442

**Comment by zol** [comment] 2016-03-09 21:43
Let's get rid of the `--deploy` argument (make sure the change is added to History.md). I think we can deprecate this now.

**Comment by tmeasday** [comment] 2016-03-09 22:52
@zol we definitely don't use this functionality for cross-browser testing of packages?

I see this in the help for it:

> This gives you a public URL that you can use in conjunction with a service like Browserling or BrowserStack to try the tests against many different browser versions.

I'm beginning to feel like b) might be a safer option..

**Comment by tmeasday** [comment] 2016-03-10 04:50
@zol I believe we use it in the release process (for `test-packages`) so I've left the code and just removed it from the help: https://github.com/meteor/meteor/commit/a5fb01310cc6dbfe7808e5cebc2b2ce31a7ca1fc

**Closed** 2016-03-10 23:22 UTC

**Comment by lucfranken** [comment] 2016-09-09 14:58
To my understanding this issue is not solved or came back. 

In my opinion this should be a sufficient way to see if isTest is set correctly:

```js
Tinytest.add('isTest should be true', function (test) {
  test.isTrue(Meteor.isTest);
});
```

https://github.com/lucfranken/meteor-issue-6331/blob/master/packages/demo/demo-tests.js

output:

<img width="484" alt="schermafbeelding 2016-09-09 om 16 45 09" src="https://cloud.githubusercontent.com/assets/1609379/18391020/ccfbeeec-76ac-11e6-9420-87c4ec2bdae2.png">

The repository is a complete reproduction: 
https://github.com/lucfranken/meteor-issue-6331

Run with: 

```sh
meteor test-packages --port 3020
```

Did not install anything otherwise, just meteor create (which takes 1.4.1.1) on Mac OSx.

console.log(Meteor) gives this on the flags:

<img width="158" alt="schermafbeelding 2016-09-09 om 16 52 06" src="https://cloud.githubusercontent.com/assets/1609379/18391298/d0251a5c-76ad-11e6-941b-c7242e2d872f.png">

There is a flag: isPackageTest which it not mentioned in the guide: https://guide.meteor.com/writing-atmosphere-packages.html#testing

It's set here so it seems intentional:
https://github.com/meteor/meteor/issues/6535
https://github.com/meteor/meteor/blob/be986fd70926c9dd8eff6d8866205f236c8562c4/packages/meteor/test_environment.js

So: Or the documentation on this flag is missing or the feature is incomplete. 

Expected outcome: As developer I would expect that isTest would be true, always when running tests. If there are more precise flags available that's nice. But I would want to filter out some code always when running tests.

**Comment by tmeasday** [comment] 2016-09-12 00:53
Hey @lucfranken, `Meteor.isTest` is only set when you are running `meteor test`, not `meteor test-packages`. https://guide.meteor.com/testing.html

**Comment by tmeasday** [comment] 2016-09-12 00:54
You can use `Meteor.isTest || Meteor.isAppTest || Meteor.isPackageTest`.

**Comment by lucfranken** [comment] 2016-09-13 09:30
Thanks @tmeasday ! Yes, got it that way now. A general flag would make more sense though, don't you think? It's maybe a bit unfortunate the isTest flag already got a more specific target.
