### ISSUE TITLE
Issue when importing via folder's index file.

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#6832] opened 2016-04-16 15:27 UTC
@benjamn As suggested in the [[1.3.1] Strange import behavior](https://forums.meteor.com/t/1-3-1-strange-import-behavior/20940/11) thread, I've created a reproduction.

The issue is, that I have a folder of models. All of the files export a model using `export { modelName }`. I've also created an `index.js` file, which contains `export { modelName } from './model_file'` for each model.

Importing like `import { modelName } from './'` works in some model files, while it doesn't in other ones. As said in the repo's README, it might be a load order thing, as one model `Office` uses models `Address` and `Person`, while `Person` depends on `Address` as well.

Here's the repo: https://github.com/zimt28/meteor_import_issue

**Comment by abernix** [comment] 2016-05-25 11:07
This is just a guess but are you sure you're not creating cyclical dependencies that cannot possibly be resolved?  At first glance, it would appear that both files are requiring each other and can't proceed since both are in the main scope of the file and preventing the symbols from ever getting resolved.

**Comment by zimt28** [comment] 2016-06-20 15:57
@abernix Quite sure, the exact same code works fine using `meteor-webpack`.

**Comment by abernix** [comment] 2016-06-27 12:45
With the directory structure that you're using, all of your modules are being eagerly imported and the import chain is not being followed in the way you might be expecting – this is to maintain for pre-Meteor 1.3 apps which operated under this eager-loaded ecosystem.

Since you're moving to modules, you should use the (Meteor-specific) `imports/` directory as files inside the `imports/` directory are _lazily loaded_ only when you explicitly `import {}` something in your code.  Again, this overcomes the obstacle of maintaining 1.3 compatibility with pre-1.3 apps which have not been migrated to modules.

Basically, I can get your reproduction to work if I:

0. Rename your `app` directory to `imports` and update references to use `/imports/`. (I just globally replaced `'/app/lib/` with `'../` since relative references are usually better anyhow)
0. Create an entry point for the **server** at `/server/main.js` with simply: `import '/imports/lib/models';`

So, I don't believe this is a bug since all your modules are being eagerly imported and your defined import statements don't really matter – they're just being imported using [the pre-1.3 rules](https://guide.meteor.com/structure.html#load-order).  See [this part of the Meteor Guide about ES6 modules and directory structure](https://guide.meteor.com/structure.html#es2015-modules).

Closing, but feel free to request a reopen if you think you have warrant for further discussion.

**Closed by abernix** 2016-06-27 12:45 UTC
Labels: bug
