### ISSUE TITLE
[1.3.2.4] Launch screens not showing up in android.

### ISSUE THREAD

**Issue by vacarsu** [meteor/meteor#7186] opened 2016-06-07 21:09 UTC
My launch screens are not displaying in android, all I see is a white screen until the app loads up. Launch screen are working fine in iOS however.

Here is the portion of my mobile-config
``` javascript
App.launchScreens({
  'iphone_2x': 'resources/splashscreens/FirebrandLoading640X960.png',
  'iphone5': 'resources/splashscreens/FirebrandLoading640X1136.png',
  'iphone6': 'resources/splashscreens/FirebrandLoading750X1334.png',
  'iphone6p_portrait': 'resources/splashscreens/FirebrandLoading1242X2208.png',
  'iphone6p_landscape': 'resources/splashscreens/FirebrandLoading2208X1242.png',
  'ipad_portrait': 'resources/splashscreens/FirebrandLoading768X1024.png',
  'ipad_portrait_2x': 'resources/splashscreens/FirebrandLoading1536X2048.png',
  'ipad_landscape': 'resources/splashscreens/FirebrandLoading1024X768.png',
  'ipad_landscape_2x': 'resources/splashscreens/FirebrandLoading2048X1536.png',
  'android_mdpi_portrait': 'resources/splashscreens/FirebrandLoading320X470.png',
  'android_mdpi_landscape': 'resources/splashscreens/FirebrandLoading470X320.png',
  'android_hdpi_portrait': 'resources/splashscreens/FirebrandLoading480X640.png',
  'android_hdpi_landscape': 'resources/splashscreens/FirebrandLoading640X480.png',
  'android_xhdpi_portrait': 'resources/splashscreens/FirebrandLoading720X960.png',
  'android_xhdpi_landscape': 'resources/splashscreens/FirebrandLoading960X720.png',
  'android_xxhdpi_portrait': 'resources/splashscreens/FirebrandLoading1080X1440.png',
  'android_xxhdpi_landscape': 'resources/splashscreens/FirebrandLoading1440X1080.png'
});
```
I don't get any errors when building, I also noticed there are some ldpi folders in the android build folder which are not getting populated, but an ldpi option is not available in app.launchscreens. Not sure if this could be a part of the issue or not.

**Comment by vacarsu** [comment] 2016-06-07 23:15
iOS launch screens seem to only show up for a second before showing a white screen for the remainder of the loading.

**Comment by abernix** [comment] 2016-09-16 10:51
I'm going to close this as no other users have reported this same problem in the three months since you've opened it and you haven't included a reproduction that would allow anyone to reproduce it (the snippet from your `mobile-config.js` is not enough).  It seems to be an isolated situation or strangeness in your setup as launch screens are known to work okay.  Would be happy to reopen it if you come up with some additional details that are helpful in reproducing, debugging and resolving it! :)

**Closed by abernix** 2016-09-16 10:51 UTC
Labels: bug, Project:Mobile

**Comment by NawazKhanMd** [comment] 2017-02-15 17:48
do we need a virtual host to run my meteor app on mobile?

cuz am running meteor run android-device -p MyIp:3000 --mobile-server virtualHostIpToWhichMobileIsConnected:3000

this gives me a blank screen

am i doing it wrong pls Reply :)
