### ISSUE TITLE
Dynamic import glitches: Cannot find module

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#10496] opened 2019-03-18 10:08 UTC
Running the latest beta, `1.8.1-beta.20` from #10248 , I'm working on upgrading a fairly large app to benefit from dynamic imports. Part of the process is dynamically importing templates at route-level, then importing all used child templates in the dynamically imported route-level templates. Like so:

```handlebars
<!-- parent.html -->
<template name="parent">
  {{> child ''}}
</template>
```

```js
// parent.js

import './child';

Template.parent....
```

```js
// routes
FlowRouter.route('/', {
  name: 'landing',
  waitOn() {
    return import('../../client/parent');
  },
  action() {
    this.render('parent');
  }
});
```

### Problem

For some reason, when adding new imports, I'm first getting `Cannot find module`error thrown, even though the path is perfectly valid.

```
[ostrio:flow-router-extra] [route.wait] Promise not resolved Error: Cannot find module '../../../components/tool_icons/mailbox_icon/mailbox_icon'
    at makeMissingError (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:232)
    at Module.require (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:251)
    at Module.moduleLink [as link] (modules.js?hash=09b63e0002909144323322723ef16c87833f772d:371)
    at eval (app_menu.js:1)
    at dynamic-import.js?hash=76097fc6a86e6a6d4b974469a5ee8a6a8ec2e694:138
    at fileEvaluate (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:346)
    at Module.require (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:248)
    at Module.moduleLink [as link] (modules.js?hash=09b63e0002909144323322723ef16c87833f772d:371)
    at eval (landing.js:1)
    at dynamic-import.js?hash=76097fc6a86e6a6d4b974469a5ee8a6a8ec2e694:138
```

### Workaround

1. Restart the Meteor app, might help...
2. ...If not, move the import declaration to a different line on the same file
-> Module is found and the error is gone.

This however, is painfully slow, having to restart the entire app all the time.

**Comment by arggh** [comment] 2019-03-18 10:20
Once again I was too hasty in reporting the issue, since right after I discovered more information. I just noticed, that I can make the module to be **not found** simply by removing the empty line between two imports.

From...

```
import './components/app_nav/app_nav';

import './components/header_right_menu/header_right_menu';
```

into this...

```
import './components/app_nav/app_nav';
import './components/header_right_menu/header_right_menu';
```

...results in `modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:232 Uncaught (in promise) Error: Cannot find module './components/app_nav/app_nav'`

**Comment by arggh** [comment] 2019-03-18 12:04
Now I encountered a situation where no amount of restarts or moving the import clause around helped. I was able to get the app running only after I removed the entire `.meteor/local` folder and restarted.

**Comment by arggh** [comment] 2019-03-18 14:00
Saga continues: it also happens with Meteor packages. Only deleting `.meteor/local` helped 😫

```
[ostrio:flow-router-extra] [route.wait] Promise not resolved Error: Cannot find module '/node_modules/meteor/arggh:dates/dates.js'
    at makeMissingError (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:232)
    at fileEvaluate (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:335)
    at Module.require (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:248)
    at Module.moduleLink [as link] (modules.js?hash=0190bb44e52acc3c8893785a5abdc460c640d217:371)
    at eval (date_banner.js:1)
    at dynamic-import.js?hash=4c6f5c174cf2e22c6c3f680ed4c5ed9c7f9a921c:138
    at fileEvaluate (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:346)
    at Module.require (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:248)
    at Module.moduleLink [as link] (modules.js?hash=0190bb44e52acc3c8893785a5abdc460c640d217:371)
    at eval (landing.js:1)
```

**Comment by arggh** [comment] 2019-03-18 14:25
More weirdness! Maybe I'm going crazy, but suddenly Meteor is complaining that module `isNil`is not found with this import:

```
import isFinite from 'lodash/isFinite';
import isNil from 'lodash/isNil';
```

After changin the import path to lowercase, it works:

```
import isFinite from 'lodash/isFinite';
import isNil from 'lodash/isnil';
```
...but VS Code sure complains, that the underlying file system doesn't match the casing. But Meteor bundler is happy.

**Comment by benjamn** [comment] 2019-03-18 14:28
This sounds like some sort of caching issue. Have you tried any of the previous betas? Does the problem happen in 1.8.0.2? I'd love to narrow down when this might have started happening.

**Comment by arggh** [comment] 2019-03-18 16:53
Downgrading from a beta release in the middle of a massive refactoring was somewhat painful, but now I got the same app running with `1.8.0.2`. However, testing the version in which this issue appered has proven to be a bit difficult.

With the build failing, I downgraded Meteor version to `1.8.0.2`, the build succeeded. Then I switched back to `1.8.1-beta.20` only to notice, that the build succeeded, even though it failed 20mins ago with the exact same code in place.

Then I introduce yet another new import, build fails and the site greets me with the familiar `Module not found`-error.

→ `git stash`, downgrade to `1.8.0.2`, `git stash apply`, build succeeds again
→ `git stash`, upgrade back to `1.8.1-beta.20`, `git stash apply`, build succeeds 🤷‍♂️

So there definitely is some sort of caching issues at least in the latest beta, but to get any valuable results, I think I must set up separate repositories of the same app with different Meteor versions, each with their own caches, and then try to get the issue to emerge in each of them.

Fiddling around in the same app with different versions doesn't really help, it seems.

**Comment by sakulstra** [comment] 2019-03-18 18:36
We're currently facing the same issue with dynamic imports. We are using dynamic imports at the router level for every page.

Not sure if that helps, but one fun thing I noticed is:
We're using '@material-ui/core/Tabs' all over the place without problems - when adding it to an page entry point which didn't previously contain it we suddenly get a client side only module not found error.

**Comment by arggh** [comment] 2019-03-18 19:00
I began bisecting with the strategy I described above, first preliminary results:

✅`v1.8.0.2` Doesn't break
✅ `v1.8.1-beta.10` Doesn't break
❌`v1.8.1-beta.20` Breaks and is easily reproducible, at least in our app

I haven't yet tried to extract a minimal reproduction, I'll first try to pin-point the culpable beta release.

**Comment by arggh** [comment] 2019-03-18 20:10
For some reason I couldn't install `1.8.1-beta.19`, maybe a bad release that got pulled down?

```bash
$ meteor update --release 1.8.1-beta.19
This project uses Meteor 1.8.1-beta.19, which isn't available on this platform. To work with this app on all supported platforms, use meteor update --release METEOR@1.8.0.2 to pin this app to the newest compatible release.
```

Here are rest of the results:

✅`v1.8.1-beta.15` Doesn't break
✅`v1.8.1-beta.17` Doesn't break
✅`v1.8.1-beta.18` Doesn't break
❌ `v1.8.1-beta.20` Breaks, triple-checked, every time.

→ it seems that the latest beta contains the change that broke the caching mechanism.

**Comment by arggh** [comment] 2019-03-18 21:12
Here should be a working reproduction with instructions attached: https://github.com/arggh/meteor-bundler-issue

**Comment by benjamn** [comment] 2019-03-19 01:04
Yep, `1.8.1-beta.19` was never published. No need to test that one.

Thanks to your reproduction, I believe I've found the root of the issue. PR coming soon!

**Comment by arggh** [comment] 2019-03-19 07:37
I'm glad I could help! Eagerly waiting for the next beta release.

**Comment by benjamn** [comment] 2019-03-19 19:06
This should be fixed with `meteor update --release 1.8.1-rc.0` (just published)!

**Closed by benjamn** 2019-03-19 19:06 UTC

**Comment by arggh** [comment] 2019-03-19 19:52
Great!

I immediately updated to the release candidate and tried to verify things got fixed..... that's when I noticed I had a wrong path defined for the `child`-template in the reproduction [_while placing my palm to my face_]. I sure hope that didn't throw you off too badly!

Just to make sure, I confirmed the fix with the original test case in our app and the problem really is gone, hurray!

**Comment by benjamn** [comment] 2019-03-19 20:09
Oh yeah, I figured out right away you meant `./components/child.js`, since importing that module reproduced the problem you described.

**Comment by adamgins** [comment] 2019-08-04 09:20
@benjamn @arggh I am using Meteor `1.8.1` any ideas what i am doing wrong please...

I am seeing `makeMissingError`

![Screen Shot 2019-08-04 at 7 18 12 pm](https://user-images.githubusercontent.com/7233741/62421880-b06d4900-b6ec-11e9-8199-7a6b4675fb21.png)


I have `import './micro_app_datatable_modal.html';` in my `index.js`  in a directory in my `imports` folder of the file I am requiring form inside an event on the client... ie I want to dynamically import that set of screens using a `require` in the click event. 

When I click I get the errors above. Any help appreciated
