### ISSUE TITLE
Not able to loginWithPassword in after calling Accounts.setPassword with the current password

### ISSUE THREAD

**Issue by jedwards1211** [meteor/meteor#7258] opened 2016-06-19 17:40 UTC
Meteor 1.2.1

This may seem absurd, but in my app I'm providing a way to set the admin password when the device is in a hardware provisioning mode, and since of course passwords are hashed there's no way to prevent a user from doing this. 

On server side:

``` js
Accounts.createUser({username: 'admin', password: 'password'})
let userId = Meteor.users.find({username: 'admin'})._id
Accounts.setPassword(userId, 'password', {logout: false})
```

Now try to log in as admin on the client, and the server will respond "incorrect password".

**Comment by abernix** [comment] 2016-09-16 12:05
Does it work properly if you do not use `logout: false` but instead use `logout: true` (the default) and require the user to log in again?

**Comment by ramezrafla** [comment] 2017-01-16 11:53
@jedwards1211 is this issue addressed? Can we close?

**Comment by ramezrafla** [comment] 2017-01-21 02:44
Ok, let's close this.

**Comment by hwillson** [comment] 2017-01-21 13:40
Since we haven't heard back on this in a while, we'll close it off. If this is still an issue with the latest version of Meteor, please post back, ideally with a small runnable reproduction (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks for opening this originally (and thanks @ramezrafla for the follow up!).

**Closed by hwillson** 2017-01-21 13:40 UTC
