### ISSUE TITLE
[1.4.2] package downgraded when meteor updates, unable to update to latest

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#7973] opened 2016-10-26 21:59 UTC
```
This project is already at Meteor 1.4.2, the latest release.
Your top-level dependencies are at their latest compatible versions.

The following top-level dependencies were not updated to the very latest version available:
 * mikowals:batch-insert 1.1.9 (1.1.13 is available)
```

**Comment by abernix** [comment] 2016-10-28 14:56
You haven't really given much information here.  What happens when you run:

    meteor add mikowals:batch-insert@1.1.13

?

**Comment by WayneUong** [comment] 2016-10-28 16:58
This is what I got:
```
meteor add mikowals:batch-insert@1.1.13
MINISAT-out: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
MINISAT-err: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
                                              
/Users/NFC/.meteor/packages/meteor-tool/.1.4.2.4lv8o++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
abort() at Error
    at jsStackTrace (packages/logic-solver.js:22:18626)
    at stackTrace (packages/logic-solver.js:22:18809)
    at abort (packages/logic-solver.js:52:28956)
    at enlargeMemory (packages/logic-solver.js:22:19142)
    at Function.Runtime.dynamicAlloc [as alloc] (packages/logic-solver.js:22:7927)
    at _sbrk (packages/logic-solver.js:22:58803)
    at Sd (packages/logic-solver.js:26:98389)
    at Ud (packages/logic-solver.js:26:109800)
    at qc (packages/logic-solver.js:26:47010)
    at Mb (packages/logic-solver.js:26:12251)
    at _b (packages/logic-solver.js:26:30189)
    at $b (packages/logic-solver.js:26:35130)
    at Bc (packages/logic-solver.js:26:54870)
    at Object.hd [as _solveAssuming] (packages/logic-solver.js:26:84479)
    at [object Object].MiniSat.solveAssuming (packages/logic-solver.js:157:18)
    at [object Object].Logic.Solver.solve (packages/logic-solver.js:1681:33)
    at [object Object].Logic.Solver.solveAssuming (packages/logic-solver.js:1714:21)
    at minMaxWS (packages/logic-solver.js:2000:32)
    at [object Object].Logic.Solver.minimizeWeightedSum (packages/logic-solver.js:2087:10)
    at packages/constraint-solver.js:1326:28
    at Function.time (/tools/tool-env/profile.js:305:10)
    at [object Object].CS.Solver.minimize (packages/constraint-solver.js:1310:16)
    at [object Object].CS.Solver.minimize (packages/constraint-solver.js:1304:10)
    at [object Object].CS.Solver._getAnswer (packages/constraint-solver.js:1693:8)
    at packages/constraint-solver.js:1561:17
    at Function.time (/tools/tool-env/profile.js:305:10)
    at [object Object].CS.Solver.getAnswer (packages/constraint-solver.js:1560:23)
    at packages/constraint-solver.js:2258:25
    at Object.Logic.disablingAssertions (packages/logic-solver.js:390:12)
    at Function.CS.PackagesResolver._resolveWithInput (packages/constraint-solver.js:2257:16)
    at [object Object].CS.PackagesResolver.resolve (packages/constraint-solver.js:2221:34)
    at /tools/project-context.js:518:35
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/project-context.js:514:19
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:486:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._resolveConstraints (/tools/project-context.js:485:13)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/cli/commands-packages.js:2036:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Command.func (/tools/cli/commands-packages.js:2035:27)
    at /tools/cli/main.js:1454:23
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

```

**Comment by WayneUong** [comment] 2016-11-02 17:51
@abernix I'm unable to update to the latest `mikowals:batch-insert` with a fresh project either. Are you able to reproduce the error now?

**Comment by abernix** [comment] 2016-11-02 18:18
Wow, that message is much different than what you originally reported!  However, I am not able to reproduce it.  Here is what I encounter on a brand new project:

```
$ meteor add mikowals:batch-insert@1.1.13
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint npm-mongo@1.4.39_1 is not satisfied by npm-mongo 2.2.11_2.
Constraints on package "npm-mongo":
* npm-mongo@2.2.11_2 <- mongo 1.1.14
* npm-mongo@1.4.39_1 <- mikowals:batch-insert 1.1.13
```

Which reveals that the problem is with the `mikowals:batch-insert` project because it depends on a very, very old version of `npm-mongo`.  `mikowals:batch-insert` hasn't been updated in a very long time and I wouldn't expect it to be compatible with the newest Meteor since Mongo has changed from 2.6 to 3.2 in the last year.  The solution to your original issue is therefore to have that package author update their package, but I see that you and others [have already reported](https://github.com/mikowals/batch-insert/issues) the issue to the author.

Your other error seems like a duplicate of #7533 and I think that would be very helpful information to provide in that issue if you are experiencing it regularly, however I cannot reproduce it here.  As the error message states, I suspect it has to do with large complex dependency trees exhausting their allocated memory.

**Comment by WayneUong** [comment] 2016-11-02 23:11
@abernix do you know of a way to bulk insert without going directly through rawCollection()? Is there going to be support for bulk operations soon?

**Comment by abernix** [comment] 2016-11-03 07:02
Not without using a package that does it for you, which is what `mikowals:batch-insert` did behind the scenes.  To start with, I might suggest forking that package into your `packages/` directory and attempting to change it to work with Mongo 3.2.  First, update the dependency on `npm-mongo` to be a much more recent version.  It's possible that change alone might fix it – but you'll probably want to test carefully to make sure it's working.  Luckily, it looks like there are some tests included in the package.

As it appears the package maintainer is no longer actively maintaining it (@mikowals, you around? :smile:) and under the MIT license, you might consider fixing the package and making it available to the Meteor community yourself.  I'm sure it would be appreciated by some!

I'm going to close this as this appears to be an issue with the package you're using being too out of date and not a bug with Meteor.  As for the bulk updates built-into Meteor without using `.rawCollection`, there is #1255 open to track that, but it hasn't received a lot of votes/attention over the years.

**Closed by abernix** 2016-11-03 07:02 UTC
Labels: can't-reproduce
