### ISSUE TITLE
Meteor.call updates document  until server restarts?

### ISSUE THREAD

**Issue by ramintagizade** [meteor/meteor#9392] opened 2017-11-19 07:27 UTC
Hi , I have this problem with Meteor , when i call update document, it updates the mongodb until the server refreshes.So, goes back to previous state .  What does this mean? Server synchs with Client side (minimongo) ? .

Meteor Version : 1.5 , OS version : Sierra 10.12.6 , Node_env : "development" . Insecure packages have been removed.  I define update in server methods , and call it from console with Meteor.call . It works okay . But after server refreshes it is in default mode . So i also  looked everywhere to see if the document is fetched by default from somewhere else ? But could not find such a thing . I am confused why it is not  behaving the way it should. So , little bit of code : 
      
     "update.widget": (id,obj) =>{
		return Widgets.update({_id:id},{$set:obj});
       },

**Comment by axelvaindal** [comment] 2017-11-19 13:33
@ramintagizade I'm using several updates in my codebase without noticing this issue with update.

Can you please : 

- Specify your environment (Meteor version, NODE_ENV, os version)
- Precise if you're using update in methods or updating client side (with insecure packaged still added or allow/deny rules specified)
- Tell if you using direct `Collection.update()` or some external packages such as `jagi:astronomy`
- Provide a small reproduction (minimal code as possible) of your issue or at least the incriminated code

Is there any way a server side code is setting back your data to their previous state (such as wiping the entire collection & repopulating it on startup for instance) ?

**Comment by ramintagizade** [comment] 2017-11-19 13:56
Meteor Version : 1.5 , OS version : Sierra 10.12.6 , Node_env : "development" . Insecure packages have been removed.  I define update in server methods , and call it from console with Meteor.call . It works okay . But after server refreshes it is in default mode . So i also  looked everywhere to see if the document is fetched by default from somewhere else ? But could not find such a thing . I am confused why it is not  behaving the way it should. So , little bit of code : 
      
     "update.widget": (id,obj) =>{
		return Widgets.update({_id:id},{$set:obj});
       },

**Comment by axelvaindal** [comment] 2017-11-19 14:10
Hum, this update looks fine.

- Can you copy/paste the declaration of the `Widgets` collection ?
- Can you actually see (client side) the effect of the update being done ? More precisely, are you sure the updated field of your collection are being updated as they should server side (check with mongo shell) ** AND ** published correctly before any server restarts (hot code push or manually) ?

**Comment by ramintagizade** [comment] 2017-11-19 14:19
Yeah it updates on mongodb , i see it via robo3t GUI , and from the  console i fetch Widget('id') and it looks okay as soon as i restart the server , it is gone ('no updated data') .

**Comment by axelvaindal** [comment] 2017-11-19 14:22
Okay, would you mind opening a public repository with the smallest reproduction possible of the issue (only the related code), so I could fork it and run it to look out deeper in this issue ? 🙂

This is necessary because I cannot reproduce in my test project.

**Comment by ramintagizade** [comment] 2017-11-19 14:26
Here is my updated json , I only update on each items's id , but after server restart that updated id is not there : 

      {
    "_id" : "demo-tabcontrol-widget",
    "name" : "TabControl Template Widget",
    "type" : "tabcontrol",
    "style" : {
        "wrapper" : {},
        "widthMU" : 8
    },
    "softDeleted" : false,
    "new" : false,
    "rank" : 10,
    "parent" : "demo-tabcontrol-page",
    "demo" : true,
    "settings" : {
        "current" : {
            "content" : {
                "default" : 0,
                "items" : [ 
                    {
                        "mode" : "tab",
                        "settings" : {
                            "title" : "Tab",
                            "icon" : "tab",
                            "hidden" : false,
                            "disabled" : false,
                            "contentID" : ""
                        },
                        "itemId" : "TabTemplate",
                        "id" : "TabTemplate"
                    }, 
                    {
                        "mode" : "link",
                        "settings" : {
                            "title" : "Link",
                            "icon" : "link",
                            "target" : "_blank",
                            "href" : "http://accessbank.az",
                            "hidden" : false,
                            "disabled" : false
                        },
                        "itemId" : "LinkTemplate",
                        "id" : "LinkTemplate"
                    }, 
                    {
                        "mode" : "modal",
                        "settings" : {
                            "title" : "Modal",
                            "icon" : "web",
                            "modalID" : "TestModal",
                            "modalTabType" : "trigger",
                            "modalOptions" : {},
                            "modalData" : {
                                "title" : "Testing...",
                                "content" : "blank-widget",
                                "data" : "function() { return {};}"
                            },
                            "hidden" : false,
                            "disabled" : false
                        },
                        "itemId" : "ModalTemplate",
                        "id" : "ModalTemplate"
                    }
                ]
            },
            "position" : "top",
            "system" : false
        },
        "rules" : []
    },
    "system" : true
}

**Comment by axelvaindal** [comment] 2017-11-19 14:32
Still cannot reproduce this 😟.
Can you provide a reproduction repository where the issue occurs with the smallest codebase as possible ?

**Comment by ramintagizade** [comment] 2017-11-19 14:34
Okay, I will look through this more carefully , sorry cannot create now .

**Comment by ramintagizade** [comment] 2017-11-22 05:46
Issue found , there was another same document id in other collection which were overriding  the mentioned document .

**Comment by axelvaindal** [comment] 2017-11-22 08:27
Glad you found out ! As this is not a problem with Meteor anymore, can we close this issue ? 🙂

**Closed** 2017-11-22 09:09 UTC
