### ISSUE TITLE
Babel bug in 1.8.2 "Cannot set property inList of [object Object] which has only a getter..."

### ISSUE THREAD

**Issue by benlavalley** [meteor/meteor#10781] opened 2019-11-17 08:59 UTC
I updated to 1.8.2 today and got an error only during production builds (development works fine):

```
=> Errors prevented startup:                  
   
   While minifying app code:

   /Users/ben/.meteor/packages/standard-minifier-js/.2.5.0.c2pu85.58zt++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-plugin-minify-simplify/lib/index.js:549:40:
   unknown: Cannot set property inList of [object Object] which has only a getter while minifying packages/iron_core.js
   at PluginPass.exit
   (/Users/ben/.meteor/packages/standard-minifier-js/.2.5.0.c2pu85.58zt++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-plugin-minify-simplify/lib/index.js:549:40)
```

I hit up Google and this seemed to be a regression issue introduced with babel 7.7.0 but fixed in 7.7.2:
https://github.com/babel/babel/issues/10654

To resolve the issue in my builds for now (I use [ghclone](https://pypi.org/project/ghclone/) to make this easy):
cd ~/yourMeteorApp/packages/ && ghclone https://github.com/meteor/meteor/tree/devel/packages/standard-minifier-js

then edit  ~/yourMeteorApp/packages/standard-minifier-js/packages.js

And bump @babel/runtime to 7.7.2.

I think that is probably all that is necessary, but I did this second below part first as I was troubleshooting and for now I don't feel like unwinding it from my app:

cd ~/yourMeteorApp/packages/ && ghclone https://github.com/meteor/meteor/tree/devel/packages/babel-compiler

Modify ~/yourMeteorApp/packages/babel-compiler/package.js to have meteor-babel point to your own fork of meteor-babel which has an updated packages.js that points to newer babel versions - or you can just point meteor-babel to my fork which has updated babel dependencies along with a few others - https://github.com/benlavalley/babel

Kudos to the team for the new release, I'd imagine they will make swift work of this one with a version update to babel 👍

**Comment by benjamn** [comment] 2019-11-18 15:33
Hey @filipenevola, let's go through this Babel package update process together sometime soon! It's a routine update that is not tied to the Meteor release, so we can fix it just by republishing `babel-compiler` and `ecmascript` (after making some changes to the underlying npm libraries, `meteor-babel` and `babel-preset-meteor`).

**Comment by bbenoist** [comment] 2019-11-20 17:42
@benlavalley The build keeps failing on my side if I only apply part 1 of your suggestions. It looks like meteor still uses an incorrect babel version:

```text
...

While minifying app code:

/root/.meteor/packages/babel-compiler/.7.4.0.1qzulgu.vh3e++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/babel-plugin-minify-simplify/lib/index.js:549:40:

...
```

I'll post an update once I've tested your second suggestion.

**Comment by bbenoist** [comment] 2019-11-20 22:47
@benlavalley It works with both suggestions 🎉 Thanks!

**Comment by chasemaier** [comment] 2019-11-22 21:12
@benjamn @filipenevola We're seeing this blocking production builds too. Is there any rough ETA for an upstream solution (v.s. the workaround described by the OP) -- seems like it's mostly a simple patch-version bump, no?

**Comment by wreiske** [comment] 2019-11-23 03:16
👀 just updated and found my way here.

**Comment by StorytellerCZ** [comment] 2019-11-28 23:51
@benlavalley Did the recent update to the standard minifiers fixed the issue?

**Comment by filipenevola** [comment] 2019-12-07 12:17
Hi, just for the record, the new versions were published 11 days ago then this issue should be fixed.

If you still have issues please feel free to open again.

**Closed by filipenevola** 2019-12-07 12:17 UTC

**Comment by scyv** [comment] 2019-12-07 14:47
I can confirm, meteor build runs without the workaround, again. (just remove the manually fixed packages and do a ``meteor update``.

Thanks Guys! Good work! :+1:
