### ISSUE TITLE
[1.4] Meteor loading merged-stylesheets from wrong path after automatic restart

### ISSUE THREAD

**Issue by vlasky** [meteor/meteor#7549] opened 2016-08-02 11:24 UTC
We are running a meteor project in a subfolder "/live".

When we make a change to a .css file, meteor normally detects this change and restarts the project with an updated merged-stylesheets.css file that reflects the changes and forces client's browser to re-render the page.

Since version 1.4, this mechanism has been slightly broken. This is what happens now:

The meteor projects starts normally and loads merged-stylesheets from the correct location, e.g.

`http://localhost:3000/live/merged-stylesheets.css?hash=24b867932657f3e30eeb1068ba530c6d7bb7846b`

But after we modify a .css file and wait for meteor to automatically restart, it loads the merged-stylesheets.css from the wrong path, e.g.

`http://localhost:3000/live/live/merged-stylesheets.css?hash=96fd2726a8f78be3e19aaae08a29a0bc318f9d8e`

the subfolder "/live" is repeated twice in the URL. As a result, the client cannot download the CSS file and the website looks mangled.

If we click the "refresh" button in the web browser to manually refresh the page, merge-stylesheets.css is retrieved from the correct location. Therefore, it looks like a bug in the dynamic update code.

**Comment by laosb** [comment] 2016-08-02 12:49
I think I've seen such a bug in issues, but I can't find it.

**Comment by laosb** [comment] 2016-08-02 12:54
It shouldn't be 1.4-specific as I can only see [a byte of code change on autoupdate](https://github.com/meteor/meteor/pull/7218/files#diff-acbd72f723dccb130a667915041c9fd9R37)

**Comment by vlasky** [comment] 2016-08-02 13:00
@laosb you are almost certainly right. I suspect it could have been a consequence of issue [#7416](https://github.com/meteor/meteor/issues/7416) which was the result of a minifier change to 1.3.4.4 (we upgraded directly from 1.3.4.1 to 1.4.0).

**Comment by laosb** [comment] 2016-08-02 13:05
It doesn't sounds like the same issue, I think?

**Comment by abernix** [comment] 2016-08-02 13:38
I don't think it's the same issue at all.  I think it's a similar issue only because it happens to projects that are deployed in a sub-directory, but the change in #7416 (which was to fix #5837) seems very unlikely to have affected the path of the minified CSS file which .  The actual cause of the issue is likely somewhere else entirely, perhaps 4be08cb01fa13711de8dc75203a9c22c76e1826b?

**Comment by abernix** [comment] 2016-08-03 08:43
@tmeasday This seems as it could be caused by the above referenced commit that was done for #7316.  Thoughts?

**Comment by tmeasday** [comment] 2016-08-04 02:02
@abernix it seems like a likely candidate.

However, I'm not seeing the issue. @vlasky can you please create a replication repository I can clone to see the issue (and an explanation of how to reproduce?).

**Comment by tmeasday** [comment] 2016-08-04 02:04
@mquandalle are you aware of an issue like this?

**Comment by vlasky** [comment] 2016-08-09 03:34
OK I got to the bottom of this issue.

Although we had run `meteor update` in the project folder when we updated our app to Meteor 1.4, there were several core packages that were not automatically updated to their latest versions.

It turns out that we had been using autoupdate 1.2.10 instead of the latest version autoupdate 1.3.11. The old version has the CSS dynamic update bug but the latest version doesn't.

To fix:

1. We deleted the file .meteor/versions

2. We ran meteor update again within the project folder and this time, once it finished, it prompted us to perform a specific package update for several core packages.

For us, the command was:

`meteor update autoupdate ddp-client ddp-server templating`

I think such confusion over core package versions could be the underlying cause of a number of issues reported on this forum.

**Comment by tmeasday** [comment] 2016-08-09 03:41
@vlasky great! So the issue you were seeing was in fact fixed by #7149, good to know I'm not writing complete junk.

You are totally right about the release versions -- I am actively working on https://github.com/meteor/meteor/issues/7495 right now.

**Closed by tmeasday** 2016-08-09 03:41 UTC
Labels: bug, Impact:few, Severity:blocks-development
