### ISSUE TITLE
Atmosphere doesn't show git repo for core packages

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#7581] opened 2016-08-04 15:48 UTC
Hi, this has bugged me for awhile, and I think would really make atmosphere more useful.

Many core packages (e.g. twitter) don't have a link to their code:  https://atmospherejs.com/meteor/twitter

And the link to the documentation is very general.  Could you please add a link to the code - even if it's in the meteor repo?  (in this example: https://github.com/meteor/meteor/tree/devel/packages/twitter)

Here's the atmosphere copy for the twitter package.
```
twitter

An implementation of the Twitter OAuth flow. See the project page on Meteor Accounts for more details.
```

WHY IS THIS IMPORTANT?

Because [`force_login` is a twitter option](https://github.com/meteor/meteor/blob/19d1c5beebffe44b5b739ae6505651bae7278e89/packages/twitter/twitter_client.js#L42), but it's not documented.  So it's nice to at least have a link to the code.  This code's location wasn't obvious when I first started with Meteor.

**Comment by abernix** [comment] 2016-08-05 08:36
Duplicate of #5000 – which is `pull-requests-encouraged`.  Please help!

**Closed by abernix** 2016-08-05 08:36 UTC
