### ISSUE TITLE
anvil not work meteor staff plz fix and also people useing meteor has this happened to yuo?

### ISSUE THREAD

**Issue by quackogamingyt** [meteor/meteor#11465] opened 2021-06-05 08:25 UTC

**Comment by StorytellerCZ** [comment] 2021-06-05 09:10
Hi, could you provide more information and a reproduction of the problem? 😉
You can read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor).

**Comment by StorytellerCZ** [comment] 2021-06-07 20:28
I'm closing this issue since we have no idea what is going here. @quackogamingyt if you provide actionable details I'm fine with re-opening this issue.

**Closed by StorytellerCZ** 2021-06-07 20:28 UTC
Labels: needs-reproduction
