### ISSUE TITLE
Blaze {{#each}} has {{else} that none tell you about {{/each}

### ISSUE THREAD

**Issue by adaptabi** [meteor/meteor#5566] opened 2015-10-29 17:23 UTC
Blaze's `#each` has a secret functionality called `else` but no-one tells you about in the docs.
Although it appears on [`Blaze.Else(argFunc, contentFunc, [elseFunc])`](http://docs.meteor.com/#/full/blaze_each) there is no example of how to use it.

Would be kindly appreciated if anyone would update the docs to give two basic example usages:

``` handlebars
{{#each players}}
<div>{{name}}</div>
{{/each}
```

``` handlebars
{{#each players}}
<div>{{name}}</div>
{{else}}
<div>No players specified</div>
{{/each}}
```

**Comment by stubailo** [comment] 2015-10-29 19:14
I think this would be a thing to mention in the Blaze guide: https://github.com/meteor/guide/issues/42

Right now, the docs about Spacebars aren't good, and mostly live in a secret README: https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#each

It does technically say there: An "else" section may be provided, which is used (with no new data context) if there are zero items in the sequence at any time.

So really the problem is that the Spacebars docs aren't discoverable, which we should fix by moving them into the Guide and not using READMEs in this fashion.

**Comment by stubailo** [comment] 2015-10-29 19:16
I'm going to close this because "technically" it is documented, and there's not a good place in the "docs" for it. We should move all of the spacebars docs to the guide.

**Comment by dotnetwise** [comment] 2015-10-29 19:24
Perhaps should be closed after you'll move the docs?

And also, the documentation mentioning `{{else}}` is quite poor since it is missing from the clear main code examples.

**Comment by stubailo** [comment] 2015-10-29 19:27
OK, perhaps you could pull-request the Spacebars README to start?

**Comment by AlbinoGeek** [comment] 2015-10-30 03:26
We need some real documentation, PR incoming.

**Comment by abernix** [comment] 2016-11-25 14:37
This is more clearly documented now, both in the guide (see above PR) and the docs: http://blazejs.org/api/spacebars.html#Each

Thanks for reporting this originally.

**Closed by abernix** 2016-11-25 14:37 UTC
Labels: Project:Blaze:Spacebars, Project:Docs, pull-requests-encouraged
