### ISSUE TITLE
Contenteditable with Blaze has duplication when the content is reactively updated

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#2882] opened 2014-10-22 11:10 UTC
Report:

The Blaze/DOM engine creates two blocks that are reactive. The initial one, along with a new block. When updated both create the effect of text duplication. This is evident in a `contenteditable` div.

Conditions Required:

The text must be `""` (empty) at the time the DOM is rendered. When the content is changed reactively, there is text duplication with the updated content of the contenteditable div.

Reproduction: https://github.com/Tarang/Meteor-Content-Editable-Text-Dup-Bug-Blaze

How to create the reproduction:

1). Git clone and fire up the app
2). Try changing the text in the textbox (contenteditable div).

3) Every page refresh/render the DB is cleared to re-simulate the issue. If there is text already there when the page is drawn there is no duplication.

Versions of Meteor (from Blaze- 0.8.3 to 1.0.0 pre). We've known about this for a while, hoping it would be fixed with the constant updates to the Blaze engine, but bringing it to attention now (sorry its late) but Pre 1.0 its kind of bad, since this affects us on production at http://servicelocale.com with our page builder.

We avoided this previously using `isolate`. Which isn't an option anymore.

**Comment by muvic08** [comment] 2015-01-28 13:00
@Tarang, Issue #3496 is not closed.

**Comment by avital** [comment] 2015-02-04 00:19
This is a duplicate of #1964. In short, Blaze is doing the "right" thing by changing the DOM in the minimal way possible. (Blaze doesn't "know" about the text nodes inserted by the user typing in.)

The workaround is to manually handle reactively updating the contents of the contenteditable DIV by using `this.autorun` inside the templates's `rendered` callback.

We should add an error when Spacebars parses a contenteditable DIV with any interpolation inside of it, eg `{{foo}}` or `{{> otherTemplate}}`.

**Closed by avital** 2015-02-04 00:19 UTC
Labels: Project:Blaze

**Comment by avital** [comment] 2015-02-04 00:22
Filed a new issue to throw an error when compiling templates with dynamic contents inside contenteditable DIVs. https://github.com/meteor/meteor/issues/3635

**Comment by avital** [comment] 2015-02-04 00:24
Looks like there may be a workaround here. https://github.com/meteor/meteor/issues/1964#issuecomment-57948734

**Comment by mitar** [comment] 2015-02-04 02:33
How would you detect if something is content editable? We enable that dynamically, when user clicks on "edit" button.
