### ISSUE TITLE
[bug] [Project:Isobuild:Minifiers] Minification in --production mode introduces undefined variable errors.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#9122] opened 2017-09-21 19:09 UTC
### This bug report should include:
- [x] A descriptive title
- [x] The version of Meteor showing the problem.: 1.5.1
- [ ] The last version of Meteor where the problem did _not_ occur (if applicable). Don't know
- [x] The operating system you're running Meteor on.: Ubuntu 16.04.3 LTS inside Crouton in Chrome OS
- [x] The expected behavior.: the app should work
- [x] The actual behavior.: I get an error:
  ```
  Uncaught ReferenceError: ue is not defined
  ```
  This seems to be a minified variable name. This error does not happen in non `--production` mode.
- [x] A ~**simple**~ reproduction!:
  ```
  git clone https://github.com/trusktr/trusktr.io
  cd trustkr.io/meteor-app
  npm i
  meteor --production
  ```

Minification is changing identifier names, and this is causing a variable to be undefined.

**Comment by trusktr** [comment] 2017-09-21 23:52
Can I configure it not to mangle the var names, for now?

**Comment by benjamn** [comment] 2017-09-22 00:07
Identifier renaming is a big part of what minification does, though it's supposed to do it safely. Can you narrow this down any more?

**Comment by benjamn** [comment] 2017-09-22 12:59
To answer your question, yes you can clone this repo somewhere and then symlink the `meteor/packages/minifier-js` package into your app's local `packages` directory, then modify the minifier package however you like.

As a first pass, you can add `mangle: false` [here](https://github.com/meteor/meteor/blob/069d3dffe7b264c672a24062c8ec6a09fc56328a/packages/minifier-js/minifier.js#L11). A better solution would be to specify certain identifiers with `mangle: { reserved: ["name"] }`, as described [here](https://www.npmjs.com/package/uglify-js#mangle-options).

**Comment by mroftalp** [comment] 2017-10-09 22:21
I get errors like this `Uncaught SyntaxError: missing ) after argument list` in production when I try to open my web apps in mobile (Chrome device toolbar), but in desktop is ok, locally mobile and desktop is okay as well. Is it related?

**Comment by maxfi** [comment] 2017-10-22 09:47
I had the same problem: `Uncaught ReferenceError: ji is not defined`. After a little `git bisect`ing I found that the package `sleep.promise:^1.0.0` imported with `import sleep from 'sleep.promise';` was causing the issue. Same as @trusktr's experience there weren't any issues until running locally with `--production` or deploying to galaxy which led to errors. `import {sleep} from 'es7-sleep';` seems to have the same issue.

From https://github.com/meteor/meteor/issues/9138#issuecomment-332476119 I tried:

```sh
meteor remove standard-minifier-js@2.1.2
meteor add abernix:standard-minifier-js
```

From a quick test this appeared to resolve the issue. Is it that the packages mentioned above weren't being transpiled/uglified properly? @abernix are you able to shed any light on this - sorry, I'm not super familiar with ES5/6/7 yet - I've been migrating from coffeescript, although now I have my doubts... 😜 

In https://github.com/meteor/meteor/issues/9138#issuecomment-332476119, about your package, you mention:
> The latter package includes uglify-es instead of uglify-js (its predecessor). If it fixes it for you, the change in that update should be the default behavior in Meteor 1.6 (unless it causes other problems).

Does this mean that `abernix:standard-minifier-js` will be included as default in Meteor 1.6?

**Comment by hwillson** [comment] 2017-10-24 17:00
@maxfi 

> Does this mean that abernix:standard-minifier-js will be included as default in Meteor 1.6?

Meteor 1.6 uses `uglify-es` (similar to `abernix:standard-minifier-js`), so the same functionality will be included.

**Comment by juho** [comment] 2017-10-31 23:30
Noticed it's happening within `client/compatibility` folder as well [with this file](https://gist.github.com/juho/d7ba12d2060ea63116538fdc20561c0f). The builder seems to be re-minifying already minified scripts named .min.js - didn't this use to skip the minification for them?

**Comment by sferoze** [comment] 2017-11-05 03:31
@juho I seem to be having the same issue. Getting console error uncaught variable only when simulating production after upgrading to Meteor 1.6

I removed all .min.js files from client side in compatibility folder. It changed the console error to not finding another variable so it had an effect. It should ignore reminifying .min.js files, and with Meteor 1.6 I don't think it is.

**Comment by juho** [comment] 2017-11-06 07:50
ping @benjamn

**Comment by hwillson** [comment] 2017-11-07 15:22
@juho @sferoze Would one of you mind opening a new issue regarding the minifier attempting to re-minify already minified files in `client/compatibilty`? That sounds like a separate issue. Please also include a reproduction if possible (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Comment by juho** [comment] 2017-11-07 18:30
Done

**Comment by hwillson** [comment] 2017-11-14 20:12
@trusktr I've tested running your reproduction with Meteor 1.6 (after removing the missing `meteor-broadcast` package), and there are no longer any minification errors. Please consider updating to Meteor 1.6 if you can, which is using [`uglify-es`](https://www.npmjs.com/package/uglify-es). Thanks!

**Closed by hwillson** 2017-11-14 20:12 UTC
Labels: Project:Isobuild:Minifiers
