### ISSUE TITLE
Error trying to deploy on meteor.com

### ISSUE THREAD

**Issue by romanrdgz** [meteor/meteor#3773] opened 2015-02-19 20:39 UTC
/Users/roman/.meteor/packages/meteor-tool/.1.0.40.qec7aw++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: not a tracked temp dir: /Users/roman/.meteor/packages/npm-bcrypt/.0.7.7.bhwxeq++os.osx.x86_64+web.browser+web.cordova
    at Error (<anonymous>)
    at Object.files.freeTempDir (/Users/roman/.meteor/packages/meteor-tool/.1.0.40.qec7aw++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/files.js:544:11)
    at /Users/roman/.meteor/packages/meteor-tool/.1.0.40.qec7aw++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/tropohouse.js:348:17
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/roman/.meteor/packages/meteor-tool/.1.0.40.qec7aw++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/roman/.meteor/packages/meteor-tool/.1.0.40.qec7aw++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/tropohouse.js:347:11
    at /Users/roman/.meteor/packages/meteor-tool/.1.0.40.qec7aw++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/MacBook-Air-de-Roman:eatsy roman$ 

Any idea?

**Comment by glasser** [comment] 2015-02-20 20:44
duplicate of #3761

**Closed by glasser** 2015-02-20 20:44 UTC
