### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by TylerL-uxai** [meteor/meteor#8874] opened 2017-07-04 05:18 UTC
Followed 3 tutorials. Set up a buildpack ( https://github.com/AdmitHub/meteor-buildpack-horse.git ) and the environmental variables ROOT_URL and MONGO_URL

    Tylers-MacBook-Pro:leeships tyler$ git push heroku master
    Counting objects: 111, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (100/100), done.
    Writing objects: 100% (111/111), 4.32 MiB | 731.00 KiB/s, done.
    Total 111 (delta 16), reused 0 (delta 0)
    remote: Compressing source files... done.
    remote: Building source:
    remote: 
    remote: -----> Node.js app detected
    remote: -----> Installing meteor
    remote: Downloading Meteor distribution
    remote: 
    remote: Meteor 1.5 has been installed in your home directory (~/.meteor).
    remote: 
    remote: Now you need to do one of the following:
    remote: 
    remote:   (1) Add "$HOME/.meteor" to your path, or
    remote:   (2) Run this command as root:
    remote:         cp "/app/tmp/cache/meteor/.meteor/packages/meteor-tool/1.5.0/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
    remote: 
    remote: Then to get started, take a look at 'meteor --help' or see the docs at
    remote: docs.meteor.com.
    remote: -----> Target Meteor version: Meteor 1.4.0.1
    remote: -----> Checking if this meteor version supports --server-only
    remote: -----> Using node: v4.4.7
    remote: ----->    and npm: 3.10.5
    remote: cook-app@ /tmp/build_ecd3ec27e9d102128a08bfe3b0221177
    remote: ├── angular@1.6.5 
    remote: ├─┬ angular-meteor@1.3.12 
    remote: │ ├─┬ jsondiffpatch@0.1.43 
    remote: │ │ └─┬ chalk@0.5.1 
    remote: │ │   ├── ansi-styles@1.1.0 
    remote: │ │   ├── escape-string-regexp@1.0.5 
    remote: │ │   ├─┬ has-ansi@0.1.0 
    remote: │ │   │ └── ansi-regex@0.2.1 
    remote: │ │   ├── strip-ansi@0.3.0 
    remote: │ │   └── supports-color@0.2.0 
    remote: │ └── underscore@1.8.3 
    remote: ├── angular-ui-router@0.3.2 
    remote: ├─┬ bootstrap@4.0.0-alpha.6 
    remote: │ ├── jquery@3.2.1 
    remote: │ └── tether@1.4.0 
    remote: └─┬ meteor-node-stubs@0.2.11 
    remote:   ├── asn1.js@4.9.0 
    remote:   ├── assert@1.4.1 
    remote:   ├── balanced-match@0.4.2 
    remote:   ├── Base64@0.2.1 
    remote:   ├── base64-js@1.2.0 
    remote:   ├── bn.js@4.11.6 
    remote:   ├── brace-expansion@1.1.7 
    remote:   ├── brorand@1.0.6 
    remote:   ├── browserify-aes@1.0.6 
    remote:   ├── browserify-cipher@1.0.0 
    remote:   ├── browserify-des@1.0.0 
    remote:   ├── browserify-rsa@4.0.1 
    remote:   ├── browserify-sign@4.0.0 
    remote:   ├── browserify-zlib@0.1.4 
    remote:   ├── buffer@4.9.1 
    remote:   ├── buffer-xor@1.0.3 
    remote:   ├── cipher-base@1.0.3 
    remote:   ├── concat-map@0.0.1 
    remote:   ├── console-browserify@1.1.0 
    remote:   ├── constants-browserify@1.0.0 
    remote:   ├── create-ecdh@4.0.0 
    remote:   ├── create-hash@1.1.2 
    remote:   ├── create-hmac@1.1.4 
    remote:   ├── crypto-browserify@3.11.0 
    remote:   ├── date-now@0.1.4 
    remote:   ├── des.js@1.0.0 
    remote:   ├── diffie-hellman@5.0.2 
    remote:   ├── domain-browser@1.1.7 
    remote:   ├── elliptic@6.3.2 
    remote:   ├── events@1.1.1 
    remote:   ├── evp_bytestokey@1.0.0 
    remote:   ├── fs.realpath@1.0.0 
    remote:   ├── glob@7.1.2 
    remote:   ├── hash.js@1.0.3 
    remote:   ├── http-browserify@1.7.0 
    remote:   ├── https-browserify@0.0.1 
    remote:   ├── ieee754@1.1.8 
    remote:   ├── indexof@0.0.1 
    remote:   ├── inflight@1.0.6 
    remote:   ├── inherits@2.0.1 
    remote:   ├── isarray@1.0.0 
    remote:   ├── miller-rabin@4.0.0 
    remote:   ├── minimalistic-assert@1.0.0 
    remote:   ├── minimatch@3.0.4 
    remote:   ├── once@1.4.0 
    remote:   ├── os-browserify@0.2.1 
    remote:   ├── pako@0.2.9 
    remote:   ├── parse-asn1@5.0.0 
    remote:   ├── path-browserify@0.0.0 
    remote:   ├── path-is-absolute@1.0.1 
    remote:   ├── pbkdf2@3.0.9 
    remote:   ├── process@0.11.9 
    remote:   ├── process-nextick-args@1.0.7 
    remote:   ├── public-encrypt@4.0.0 
    remote:   ├── punycode@1.4.1 
    remote:   ├── querystring@0.2.0 
    remote:   ├── querystring-es3@0.2.1 
    remote:   ├── randombytes@2.0.3 
    remote:   ├── readable-stream@2.2.10  (git+https://github.com/meteor/readable-stream.git#2e9112d7d31a2af6e0682db0e18679b1e5fd4694)
    remote:   ├── rimraf@2.6.1  extraneous
    remote:   ├── ripemd160@1.0.1 
    remote:   ├── safe-buffer@5.0.1 
    remote:   ├── sha.js@2.4.8 
    remote:   ├── stream-browserify@2.0.1 
    remote:   ├── string_decoder@1.0.1 
    remote:   ├── timers-browserify@1.4.2 
    remote:   ├── tty-browserify@0.0.0 
    remote:   ├─┬ url@0.11.0 
    remote:   │ └── punycode@1.3.2 
    remote:   ├── util@0.10.3 
    remote:   ├── util-deprecate@1.0.2 
    remote:   ├── vm-browserify@0.0.4 
    remote:   └── wrappy@1.0.2 
    remote: 
    remote: -----> Building Meteor app with ROOT_URL: http://leeships.herokuapp.com
    remote: -----> Moving built slug to /tmp/build_ecd3ec27e9d102128a08bfe3b0221177/.meteor/heroku_build/app
    remote: -----> Installing npm production dependencies on built slug
    remote: 
    remote: > fibers@1.0.13 install /tmp/build_ecd3ec27e9d102128a08bfe3b0221177/.meteor/heroku_build/app/programs/server/node_modules/fibers
    remote: > node build.js || nodejs build.js
    remote: 
    remote: `linux-x64-v8-4.5` exists; testing
    remote: Binary is fine; exiting
    remote: 
    remote: > meteor-dev-bundle@0.0.0 install /tmp/build_ecd3ec27e9d102128a08bfe3b0221177/.meteor/heroku_build/app/programs/server
    remote: > node npm-rebuild.js
    remote: 
    remote: 
    remote: > bcrypt@0.8.7 install /tmp/build_ecd3ec27e9d102128a08bfe3b0221177/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt
    remote: > node-gyp rebuild
    remote: 
    remote: make: Entering directory '/tmp/build_ecd3ec27e9d102128a08bfe3b0221177/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build'
    remote:   CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
    remote:   CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
    remote:   CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
    remote:   SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
    remote:   COPY Release/bcrypt_lib.node
    remote: make: Leaving directory '/tmp/build_ecd3ec27e9d102128a08bfe3b0221177/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build'
    remote: bcrypt@0.8.7 /tmp/build_ecd3ec27e9d102128a08bfe3b0221177/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt
    remote: bindings@1.2.1 /tmp/build_ecd3ec27e9d102128a08bfe3b0221177/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bindings
    remote: nan@2.3.5 /tmp/build_ecd3ec27e9d102128a08bfe3b0221177/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/nan
    remote: {
    remote:   "meteor-dev-bundle": "0.0.0",
    remote:   "npm": "3.10.5",
    remote:   "ares": "1.10.1-DEV",
    remote:   "http_parser": "2.5.2",
    remote:   "icu": "56.1",
    remote:   "modules": "46",
    remote:   "node": "4.4.7",
    remote:   "openssl": "1.0.2h",
    remote:   "uv": "1.8.0",
    remote:   "v8": "4.5.103.36",
    remote:   "zlib": "1.2.8"
    remote: }
    remote: meteor-dev-bundle@0.0.0 /tmp/build_ecd3ec27e9d102128a08bfe3b0221177/.meteor/heroku_build/app/programs/server
    remote: ├── amdefine@1.0.0 
    remote: ├── ansi-regex@0.2.1 
    remote: ├── ansi-styles@1.1.0 
    remote: ├── asap@2.0.4 
    remote: ├── escape-string-regexp@1.0.5 
    remote: ├── fibers@1.0.13 
    remote: ├── has-ansi@0.1.0 
    remote: ├── meteor-promise@0.7.2 
    remote: ├── promise@7.1.1 
    remote: ├── semver@4.1.0 
    remote: ├── source-map@0.1.32 
    remote: ├── source-map-support@0.3.2 
    remote: ├── strip-ansi@0.3.0 
    remote: ├── supports-color@0.2.0 
    remote: ├── type-of@2.0.1 
    remote: └── underscore@1.5.2 
    remote: 
    remote: npm WARN meteor-dev-bundle@0.0.0 No description
    remote: npm WARN meteor-dev-bundle@0.0.0 No repository field.
    remote: npm WARN meteor-dev-bundle@0.0.0 No license field.
    remote: -----> Adding PATH environment
    remote: -----> Running extras
    remote: -----> Adding profile script to resolve MONGO_URL from mongolab addon
    remote: -----> Adding profile script to resolve ROOT_URL from heroku app name
    remote: -----> Discovering process types
    remote:        Procfile declares types     -> (none)
    remote:        Default types for buildpack -> web
    remote: 
    remote: -----> Compressing...
    remote:        Done: 32M
    remote: -----> Launching...
    remote:        Released v8
    remote:        https://leeships.herokuapp.com/ deployed to Heroku
    remote: 
    remote: Verifying deploy... done.
    To https://git.heroku.com/leeships.git
     * [new branch]      master -> master

**Comment by merlinpatt** [comment] 2017-07-04 05:58
The build itself looks fine @TylerL-uxai. I went to the URL given in the output (http://leeships.herokuapp.com/) and saw the usual Heroku error page.

Can you run the following commands and paste their output here?

1. `heroku logs --app leeships --source app` - this outputs only the logs from your app
2. `heroku logs --app leeships` - this outputs everything

It may helpful / easier to only paste in the last 50 lines or so.

**Comment by TylerL-uxai** [comment] 2017-07-04 13:57
Wow! Thanks for the fast response :)

`2017-07-04T12:34:55.949850+00:00 app[web.1]: assert.js:93
2017-07-04T12:34:55.950185+00:00 app[web.1]:   throw new assert.AssertionError({
2017-07-04T12:34:55.950189+00:00 app[web.1]:         ^
2017-07-04T12:34:55.952034+00:00 app[web.1]: AssertionError: "undefined" === "function"
2017-07-04T12:34:55.952036+00:00 app[web.1]:     at wrapPathFunction (/app/build/bundle/programs/server/mini-files.js:77:10)
2017-07-04T12:34:55.952037+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/mini-files.js:108:24)
2017-07-04T12:34:55.952037+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2017-07-04T12:34:55.952038+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2017-07-04T12:34:55.952039+00:00 app[web.1]:     at Module.load (module.js:356:32)
2017-07-04T12:34:55.952039+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2017-07-04T12:34:55.952040+00:00 app[web.1]:     at Module.require (module.js:364:17)
2017-07-04T12:34:55.952040+00:00 app[web.1]:     at require (module.js:380:17)
2017-07-04T12:34:55.952041+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/boot.js:9:13)
2017-07-04T12:34:55.952042+00:00 app[web.1]:     at Module._compile (module.js:456:26)`

`2017-07-04T11:13:52.189788+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=leeships.herokuapp.com request_id=60253b95-a211-45aa-afc6-9d0b404b3e50 fwd="112.211.65.25" dyno= connect= service= status=503 bytes= protocol=http
2017-07-04T11:13:53.392022+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=leeships.herokuapp.com request_id=eb25d25f-08ac-46fd-87b5-b8b6a58c1223 fwd="112.211.65.25" dyno= connect= service= status=503 bytes= protocol=http
2017-07-04T11:15:00.535196+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=leeships.herokuapp.com request_id=93560caa-08b7-4fb2-8011-ec0b1820fa47 fwd="112.211.65.25" dyno= connect= service= status=503 bytes= protocol=http
2017-07-04T11:15:01.062023+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=leeships.herokuapp.com request_id=eb3a5b77-ec3c-43e6-a6d3-8b153f62148f fwd="112.211.65.25" dyno= connect= service= status=503 bytes= protocol=http
2017-07-04T12:34:31.694888+00:00 heroku[web.1]: State changed from crashed to starting
2017-07-04T12:34:53.621094+00:00 heroku[web.1]: Starting process with command `node build/bundle/main.js`
2017-07-04T12:34:56.051280+00:00 heroku[web.1]: State changed from starting to crashed
2017-07-04T12:34:56.041438+00:00 heroku[web.1]: Process exited with status 8
2017-07-04T12:34:55.949497+00:00 app[web.1]: 
2017-07-04T12:34:55.949850+00:00 app[web.1]: assert.js:93
2017-07-04T12:34:55.950185+00:00 app[web.1]:   throw new assert.AssertionError({
2017-07-04T12:34:55.950189+00:00 app[web.1]:         ^
2017-07-04T12:34:55.952034+00:00 app[web.1]: AssertionError: "undefined" === "function"
2017-07-04T12:34:55.952036+00:00 app[web.1]:     at wrapPathFunction (/app/build/bundle/programs/server/mini-files.js:77:10)
`

**Comment by merlinpatt** [comment] 2017-07-04 14:14
You may need to post the entire log in a gist and link to it. Though I don't think it will help.

It looks like there is a bug with your app, but it's ambiguous. When you run your app locally in dev mode, do you get any errors or warnings in the console? Or maybe some weird behavior?

Also, try running your app locally in production with the `--production` flag and see what happens.

**Comment by TylerL-uxai** [comment] 2017-07-04 14:22
Nope, no errors in dev or production. Also that pretty much sums up the log (those error messages keep repeating).

**Comment by merlinpatt** [comment] 2017-07-04 14:35
Given that there are no local errors, I would guess that the issue is more to do with the buildpack. Someone else posted about a similar issue (below), so I suggest commenting/re-opening that one for further help. Closing for now.

https://github.com/AdmitHub/meteor-buildpack-horse/issues/144

**Closed by merlinpatt** 2017-07-04 14:35 UTC
