### ISSUE TITLE
meteor1.3-beta5 build hangs when importing github npm module

### ISSUE THREAD

**Issue by sungwoncho** [meteor/meteor#6114] opened 2016-01-29 10:12 UTC
When I require [github](https://github.com/mikedeboer/node-github) npm package from the server side, the build hangs.

I created a repo for reproduction: https://github.com/sungwoncho/meteor-1.3-bug

Other npm modules work fine. Any ideas why this particular one causes the build to hang indefinitely?

Using:
METEOR@1.3-modules-beta.5
OSX El Capitan 10.11.2

**Comment by avital** [comment] 2016-02-02 23:19
Could this have been due to the GitHub outage last week? Does it work now?

**Comment by avital** [comment] 2016-02-03 00:31
Oh, sorry -- I misunderstood. I though it was an NPM package loaded from GitHub.

**Comment by benjamn** [comment] 2016-02-03 00:38
I think the cause of this problem is that that `github` npm package's `package.json` file has a "main" property that is simply `"."`, which means we should be loading the `index.js` file, but instead we try to load the `package.json` file again, and get stuck in an infinite loop.

**Comment by benjamn** [comment] 2016-02-03 18:40
My diagnosis above was correct, and this will be fixed by https://github.com/benjamn/install/commit/7808bd815a6b604b5916465d7c9f6bf9fa182b56 (which relies on https://github.com/benjamn/install/commit/7808bd815a6b604b5916465d7c9f6bf9fa182b56 for runtime support).

**Comment by benjamn** [comment] 2016-02-04 16:44
Thanks for reporting this! Let us know if it isn't fixed in the latest beta.

**Closed by benjamn** 2016-02-04 16:44 UTC
Labels: confirmed, in progress, known-fix

**Comment by sungwoncho** [comment] 2016-02-05 10:10
I can confirm that it is fixed in 1.6. Thanks for the hard work.
