### ISSUE TITLE
[1.3] meteor update fails on Windows 10 system

### ISSUE THREAD

**Issue by tonycastle** [meteor/meteor#6621] opened 2016-03-29 19:03 UTC
Currently have a 1.2.1 version project which I tried to update to 1.3. This failed with the following output:

>

>  Microsoft Windows [Version 10.0.10586]
> (c) 2015 Microsoft Corporation. All rights reserved.
> 
> C:\Users\tc>cd meteor_dev
> 
> C:\Users\tc\meteor_dev>cd memberz_app
> 
> C:\Users\tc\meteor_dev\memberz_app>meteor update
> 
> C:\Users\tc\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
>       throw error;
>             ^
> Error: No metadata files found for isopack at: /C/Users/tc/AppData/Local/.meteor/packages/fourseven_scss/3.3.3_3
>     at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:903:13)
>     at C:\tools\packaging\tropohouse.js:514:19
>     at Array.forEach (native)
>     at Function._.each._.forEach (C:\Users\tc\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
>     at C:\tools\packaging\tropohouse.js:513:11
>     at C:\tools\utils\buildmessage.js:359:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at Object.download (C:\tools\packaging\tropohouse.js:448:20)
>     at C:\tools\packaging\tropohouse.js:593:22
>     at C:\tools\utils\buildmessage.js:359:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:590:20)
>     at C:\tools\project-context.js:725:25
>     at C:\tools\utils\buildmessage.js:359:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at C:\tools\project-context.js:724:20
>     at C:\tools\packaging\catalog\catalog.js:100:5
>     at C:\tools\utils\buildmessage.js:271:13
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:264:29
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:262:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:253:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.capture (C:\tools\utils\buildmessage.js:252:19)
>     at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
>     at ProjectContext._.extend._downloadMissingPackages (C:\tools\project-context.js:723:13)
>     at C:\tools\project-context.js:278:9
>     at C:\tools\utils\buildmessage.js:359:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at ProjectContext._completeStagesThrough (C:\tools\project-context.js:268:18)
>     at C:\tools\project-context.js:260:12
>     at Function.run (C:\tools\tool-env\profile.js:489:12)
>     at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:259:13)
>     at C:\tools\cli\commands-packages.js:1523:20
>     at C:\tools\utils\buildmessage.js:271:13
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:264:29
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:262:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:253:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.capture (C:\tools\utils\buildmessage.js:252:19)
>     at Object.main.captureAndExit (C:\tools\cli\main.js:279:29)
>     at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1522:8)
>     at Command.main.registerCommand.name [as func] (C:\tools\cli\commands-packages.js:1594:29)
>     at C:\tools\cli\main.js:1408:23
> 
> C:\Users\tc\meteor_dev\memberz_app>

Installed packages:

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

aldeed:autoform
aldeed:collection2
twbs:bootstrap
accounts-ui
accounts-password
accounts-facebook
accounts-twitter
kadira:flow-router
kadira:blaze-layout
rajit:bootstrap3-datepicker
aldeed:autoform-bs-datepicker
meteortoys:allthings
fortawesome:fontawesome
check
alanning:roles
reywood:publish-composite
momentjs:moment
velocity:meteor-stubs
reactive-var
reactive-dict
mrgalaxy:stripe
meteorhacks:npm
themeteorchef:bert
meteorhacks:ssr
npm-container

**Comment by brucejo75** [comment] 2016-03-29 21:23
Try removing npm-container, see this [issue]( https://github.com/meteor/meteor/issues/6593)

**Comment by logvik** [comment] 2016-03-29 22:51
I don't have npm-container, but have the same error...

**Comment by suhail-ansari-apconic** [comment] 2016-03-30 10:05
remove meteorhacks:npm as well. You do not need it.

**Comment by tonycastle** [comment] 2016-03-30 15:56
Issue persists after I remover the npm packages and container. FYI, I copied the folder to a Linux installation and had no issues either running the app or updating to 1.3. I am convinced there is an issue with the Windows tool. I also cannot create a new project with 1.3 under Windows.

**Comment by Nolapete** [comment] 2016-03-30 16:06
Same here, meteor create <project_name> just hangs.  I've tried to completely uninstall and reinstall meteor to no avail.  Also, I get login failed even after resetting my developer account password at the login to your developer account screen.  (Everything works great on my Linux machines!)  Open to try anything you need me to in order to resolve this for Windows users.

**Comment by cdeadlock** [comment] 2016-05-04 01:03
My error looks very similar but a bit different
```
C:\Users\video\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
SyntaxError: Unexpected token
```

Stuck on versions:
```

accounts-base            1.2.5* A user account system
accounts-password        1.1.7* Password support for accounts
accounts-ui              1.1.8* Simple templates to add login widgets to an app
alanning:roles           1.2.15  Authorization package for Meteor
aldeed:autoform          5.8.1  Easily create forms with automatic insert and update, and automatic reactive val...
aldeed:collection2       2.3.1* Automatic validation of insert and update operations on the client and server.
blaze-html-templates     1.0.3* Compile HTML templates into reactive UI with Meteor Blaze
ecmascript               0.4.2* Compiler plugin that supports ES2015+ in all .js files
es5-shim                 4.5.9* Shims and polyfills to improve ECMAScript 5 support
jquery                   1.11.7* Manipulate the DOM using CSS selectors
materialize:materialize  0.97.5  Materialize (official): A modern responsive front-end framework based on Materi...
meteor-base              1.0.3* Packages that every Meteor app needs
mobile-experience        1.0.3* Packages for a great mobile user experience
mongo                    1.1.6* Adaptor for using MongoDB and Minimongo over DDP
session                  1.1.4* Session variable
standard-minifier-css    1.0.5* Standard css minifier used with Meteor apps by default.
standard-minifier-js     1.0.5* Standard javascript minifiers used with Meteor apps by default.
tracker                  1.0.12* Dependency tracker to allow reactive callbacks
```

Which is giving me super weird bugs, like i can't use SimpleSchema.validate()

**Comment by polux2016** [comment] 2016-08-06 05:27
run: meteor remove acounts-password  
run: meteor update
Works fine!

**Comment by abernix** [comment] 2016-09-13 11:40
Closing this.  This issue is fairly old and lacks a reproduction to clearly decide if it has been fixed in a newer version of Meteor.  There have been hundreds of changes to Meteor since the version you were trying to upgrade to was released.  Additionally, there are known issues with older versions of `fourseven:scss` that prevent it from working with newer versions of Meteor.  I highly recommend upgrading that package to a newer version – one that is compatible with the version of Meteor that you are migrating to.

If anyone is still experiencing this problem, please provide a simple reproduction of this problem in the form of a Meteor project uploaded to a Github repo.  This will allow someone to easily reproduce the problem and attempt to help.

**Closed by abernix** 2016-09-13 11:40 UTC

**Comment by mcbriandavids** [comment] 2018-10-30 19:14
Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\jefflittlecent>mkdir tins

C:\Users\jefflittlecent>cd tins

C:\Users\jefflittlecent\tins>meteor create template
Created a new Meteor app in 'template'.

To run your new app:
  cd template
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/tutorials

To start with a different app template, try one of the following:

  meteor create --bare    # to create an empty app

  meteor create --minimal # to create an app with as few Meteor packages as poss
ible
  meteor create --full    # to create a more complete scaffolded app
  meteor create --react   # to create a basic React-based app


C:\Users\jefflittlecent\tins>cd template

C:\Users\jefflittlecent\tins\template>meteor
[[[[[ C:\Users\jefflittlecent\tins\template ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

Terminate batch job (Y/N)?
^C
C:\Users\jefflittlecent\tins\template>meteor
[[[[[ C:\Users\jefflittlecent\tins\template ]]]]]

=> Started proxy.
   Starting your app                         \


This is the error i get for days now whenever i ctrl Cx2
This server won't run again

**Comment by mcbriandavids** [comment] 2018-10-30 19:18
Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\jefflittlecent>mkdir tins

C:\Users\jefflittlecent>cd tins

C:\Users\jefflittlecent\tins>meteor create template
Created a new Meteor app in 'template'.

To run your new app:
  cd template
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/tutorials

To start with a different app template, try one of the following:

  meteor create --bare    # to create an empty app

  meteor create --minimal # to create an app with as few Meteor packages as poss
ible
  meteor create --full    # to create a more complete scaffolded app
  meteor create --react   # to create a basic React-based app


C:\Users\jefflittlecent\tins>cd template

C:\Users\jefflittlecent\tins\template>meteor
[[[[[ C:\Users\jefflittlecent\tins\template ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

Terminate batch job (Y/N)?
^C
C:\Users\jefflittlecent\tins\template>meteor
[[[[[ C:\Users\jefflittlecent\tins\template ]]]]]

=> Started proxy.
   Starting your app                         \


This is the error i get for days now whenever i ctrl Cx2
This server won't run again
Please what do i do?

**Comment by mcbriandavids** [comment] 2018-10-30 19:20
Your environment has been set up for using Node.js 8.12.0 (x64) and npm.

C:\Users\jefflittlecent>cd meteor

C:\Users\jefflittlecent\meteor>cd brian
The system cannot find the path specified.

C:\Users\jefflittlecent\meteor>meteor --inspect
run: You're not in a Meteor project directory.

To create a new Meteor project:
  meteor create <project name>
For example:
  meteor create myapp

For more help, see 'meteor --help'.

C:\Users\jefflittlecent\meteor>cd brian
The system cannot find the path specified.

C:\Users\jefflittlecent\meteor>cd brians

C:\Users\jefflittlecent\meteor\Brians>meteor --inspect
Can't listen on port 3000. Perhaps another Meteor is running?

Running two copies of Meteor in the same application directory
will not work. If something else is using port 3000, you can
specify an alternative port with --port <port>.

C:\Users\jefflittlecent\meteor\Brians>msteor --inspect
'msteor' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jefflittlecent\meteor\Brians>meteor --inspect
[[[[[ C:\Users\jefflittlecent\meteor\Brians ]]]]]

=> Started proxy.
C:\Users\jefflittlecent\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: No metadata files found for isopack at: /C/Users/jefflittlecent/AppData/L
ocal/.meteor/packages/coffeescript/1.0.17
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:843:13)
    at _.each (C:\tools\packaging\tropohouse.js:521:21)
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\jefflittlecent\AppData\Local\.meteor\
packages\meteor-tool\1.8.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\unde
rscore\underscore.js:79:11)
    at buildmessage.enterJob (C:\tools\packaging\tropohouse.js:520:13)
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:515:22
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:600:22
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at exports.Tropohouse.downloadPackagesMissingFromMap (C:\tools\packaging\tro
pohouse.js:597:20)
    at C:\tools\project-context.js:832:25
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:831:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalo
g\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:830:
13)
    at C:\tools\project-context.js:296:9
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:286:18
)
    at Profile.run (C:\tools\project-context.js:278:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:277:13
)
    at C:\tools\runners\run-app.js:544:29
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundleApp (C:\tools\runners\run-app.js:543:31)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:610:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:908:28)
    at C:\tools\runners\run-app.js:398:12

C:\Users\jefflittlecent\meteor\Brians>
same challenge endless loading. I server refused to work until i restart another project
