### ISSUE TITLE
Service worker support

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#5982] opened 2016-01-13 02:57 UTC
Service workers are [becoming the preferred mechanism to serve offline-first apps](https://forums.meteor.com/t/meteor-and-service-workers/1765).

http://caniuse.com/#feat=serviceworkers - full support in Chrome, Firefox, Opera
http://alistapart.com/article/application-cache-is-a-douchebag

From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API):

> Note: For backwards compatibility, you could choose to use service workers and AppCache on the same web app to do equivalent things (if the AppCache will support doing those things, of course.) What happens in such a case is that browsers that don’t support Service Workers will use AppCache, and those that do will ignore the AppCache and let the service worker take over.

The Chrome team has shown [impressive performance gains from an application shell architecture using service workers](https://developers.google.com/web/updates/2015/11/app-shell): 0.8 seconds to the first paint on repeat visits over a 3G connection, vs. 2.5 seconds on the first visit.

**Comment by PEM--** [comment] 2016-01-13 09:27
:+1:

**Comment by trusktr** [comment] 2016-01-13 09:45
If it's supported natively by browsers, what does Meteor actually have to do? Doesn't it just work already?

**Comment by PEM--** [comment] 2016-01-13 09:53
The way the app is built differs greatly from conventional monolithic builds :wink:

Plus, it would be an amazing avantage for Meteor to propose it out of the box. There's no solid framework that does this for the moment.

**Comment by trusktr** [comment] 2016-01-13 10:55
Yes indeed, having some sort of thing that helps load the app faster without the new developer needing to know would be very nice.

What about the builds requires accomodation? Is it that service workers need independent files to load from a URL? If so, maybe we can just make a build plugin that reads `*.blob.js`, compiles the file into a Blob exported via CommonJS, then the module system in Meteor 1.3 let us easily import the blob URL to load the ServiceWorker with. Maybe something like

```js
import serviceWorkerBlob from '/app/path/to/service-worker.blob'
navigator.serviceWorker.register(serviceWorkerBlob, ...)
```

**Comment by Primigenus** [comment] 2016-01-14 14:20
I would love for there to be a `service-workers` package that you can add (or is added by default) that implements service workers for all the endpoints your app uses: your Mongo collections, methods, and REST calls. Meteor could have default behaviour where, when the connection is unavailable, the app behaves as normal, and then it syncs everything up over DDP once a connection is re-established.

Most importantly I think people should not have to know about service workers in order to use Meteor. My biggest complaint to the Chrome team (and about the extensible web manifesto in general) is that it makes things more complicated and increases the surface area of things the average web developer has to know to be productive. Meteor is the opposite: it reduces what you need to know and makes your job easier. If Meteor can "hide" the implementation of service-workers automatically while still allowing you to customise everything at will, I think we'll have a truly unique and powerful tool.

**Comment by trusktr** [comment] 2016-01-15 03:18
> implements service workers for all the endpoints your app uses: your Mongo collections, methods, and REST calls.

@Primigenus I would love to see some of Meteor's APIs be cached in ServiceWorkers. That might be really nice. JavaScript is already cached, of course, but runtime setup could now be cached too. Meteor methods is a great example. 

I think a first step would be for someone to make something like the blob handler I described above. This blob handler would basically be to Meteor as what [serviceworker-loader](https://github.com/markdalgleish/serviceworker-loader) is to Webpack, or what [serviceworkify](https://github.com/jazlalli/serviceworkify) is to Browserify. Then Meteor (or any package) could use it to start ServiceWorkers.

**Comment by trusktr** [comment] 2016-01-15 03:20
cc: @glasser @benjamn @avital @stubailo (for awareness of the idea)

**Comment by stubailo** [comment] 2016-01-15 03:28
@trusktr please do not mention people directly on issues like this unless it's very urgent. We are guaranteed to look at 100% of issues within several days of posting.

**Comment by trusktr** [comment] 2016-01-15 03:38
@stubailo Sorry, and will do the do not!

**Comment by Sewdn** [comment] 2016-01-19 22:11
Interesting write-up on progressive enhancement techniques by Addy Osmani:
https://addyosmani.com/blog/getting-started-with-progressive-web-apps/

Next to service workers for caching the app-shell (and as a potential data-caching layer), a lot of other techniques are mentioned for making 'progressive web apps'. If meteor could offer (a subset) of these best practices out-of-the-box, just like the appcache package by Andrew Wilcox (for setting up a manifest file for your meteo webapp), the world would be a better place.

**Comment by martijnwalraven** [comment] 2016-01-19 22:53
Service workers and related mechanisms definitely seem like an interesting direction for offline apps. There is currently design work underway for a more flexible data layer, and I think it makes sense to consider the implications of these mechanisms to at least make sure we can integrate with them in the future.

**Comment by rubencodes** [comment] 2016-01-20 17:02
Would love to help out with this as well. I've had some experience with service-workers, and would suggest using Google's [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox) and [sw-precache](https://github.com/GoogleChrome/sw-precache) packages if at all possible to make implementation easier (I was doing service workers by hand at one point, Google's API is much more intuitive).

**Comment by trusktr** [comment] 2016-01-20 23:34
Not only are `ServiceWorker`s useful themselves, but Chrome is [encouraging them](https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android?hl=en): having a ServiceWorker in your web app is one of the criteria that will make Chrome auto-ask your users to add your site to their home screen!

**Comment by mitar** [comment] 2016-01-27 17:57
+1

**Comment by ndarilek** [comment] 2016-01-27 23:48
Looking at implementing service workers in my Meteor app now that Firefox supports push notifications. I don't have any thoughts on a deeper integration path, but I think a low-hanging fruit would be some mechanism for me to package the service worker file in a way that serves it up as a separate script at a predictable URL, but that still processes it through the Meteor build/asset pipeline. Right now for instance I have public/scripts/serviceworker.js, which I assume is served up as is. It'd be nice if there was some way of processing that file as ES2015, with support for imports and such, while not bundling it into the main JS and making it available at a predictable URL.

Is there any current way of accomplishing that? Or is that the .blob.js support alluded to here?

**Comment by mitar** [comment] 2016-01-27 23:53
Serving such files is the same issue as with web workers in general.

I have a fork of Meteor which provides such extra target which nicely compiles files into custom targets so that then you could load stuff as `/__serviceworker/packages/myofflineworker.js` and would have whole Meteor compilation path in, and I have been opening pull request to get necessary changes upstream into Meteor, but they were slow in merging them in.

(Fork is not yet public because it waits for paper to be published.)

**Comment by mitar** [comment] 2016-01-27 23:55
List of pull requests related to extra custom targets:
* https://github.com/meteor/meteor/pull/6101
* https://github.com/meteor/meteor/pull/6085
* https://github.com/meteor/meteor/pull/6060
* https://github.com/meteor/meteor/pull/6059
* https://github.com/meteor/meteor/pull/5714
* https://github.com/meteor/meteor/pull/5703

**Comment by trusktr** [comment] 2016-01-29 18:05
@mitar Nice PRs!

@ndarilek Another idea that could help, alternative to the `.blob.js` idea: https://github.com/meteor/meteor/issues/5883. We could then write service workers as any normal JS file without need for a special extension, exclude it from the default bundle, then load it as a worker at the moment we wish.

**Comment by dandv** [comment] 2016-02-03 22:10
Microsoft has started implementing Service Worker in Edge:

https://blogs.windows.com/msedgedev/2016/02/03/2016-platform-priorities/

**Comment by mitar** [comment] 2016-02-11 23:07
I opened a ticket with my proposal how to implement this (I already have a working prototype): https://github.com/meteor/meteor/issues/6222

**Comment by ndarilek** [comment] 2016-02-11 23:11
Today I ran into some issues with service workers and browser-policy 
installed. Something was trying to access URLs of the form 
`blob:http://localhost:3000/<UUID>`. Didn't see that issue until I 
started playing with service workers and background push.

Anyhow, that may also require a fix if any sort of deeper integration 
lands. I've removed browser-policy for now.

**Comment by trusktr** [comment] 2016-02-12 19:36
If we were to make a build plugin to handle `.worker.js` files so that importing them gives us a worker constructor, the only problem would be that the code would run in an environment where `meteorInstall` doesn't exist (a worker). I think we might need to provide meteorInstall along with all the file's dependencies for running in a worker. Besides that, the package would be similar to (fork of) `ecmascript` and compile with `babel-compiler`.

**Comment by trusktr** [comment] 2016-02-12 19:37
Also, some of us prefer NPM modules over Meteor packages. Both the solution proposed here and a build plugin could work in tandem.

**Comment by mitar** [comment] 2016-02-12 19:40
> If we were to make a build plugin to handle .worker.js files so that importing them gives us a worker constructor,

No, because you might want to combine multiple files into one output file. You do want to bundle things together.

**Comment by trusktr** [comment] 2016-02-12 20:02
Not if you have an HTTP/2 pipeline.

**Comment by trusktr** [comment] 2016-02-12 20:22
A worker could get dependencies via HTTP/2 with a single connection, but if not, then fetching a single bundle would work. But I was originally just thinking of bundling them into the worker code too. The build plugin would have do that. Well, in any case, the code that I'm making with workers needs to be an NPM package, so that requires a prepublish script anyways, where I'm using Webpack to bundle dependencies into a worker blob. Once published, the code includes the worker blob inline (is there a better way?). I'll stick to this workflow for now. The solution here is really meteor-specific, but my lib is meant to be used externally as well. A build plugin would get us close to a universal solution, because the only thing to worry about is the import path used. For example: 

```js
import foo from 'foo.worker'
```

In Webpack or Browserify we can associate transforms or loaders with that *.worker.js name, and same with a Meteor build plugin. This makes the code portable (we can put the code in any of those environments and make it work, but not so with the Meteor package solution).

What ever the solution is, I think supporting import/require syntax is the most universal thing to do currently (even if import overloading isn't part of any standard).

**Comment by engelgabriel** [comment] 2016-03-29 23:28
We'd love to use this in Rocket.Chat :+1: 
Maybe this is something else we can collaborate on?

**Comment by mitar** [comment] 2016-03-29 23:59
@engelgabriel: You can find my solution in #6222, which I am already using in practice and it works great. :-)

**Comment by dandv** [comment] 2016-04-29 02:46
Massive support signal from Google today: the [2016 Founders' Letter](https://googleblog.blogspot.com/2016/04/this-years-founders-letter.html) mentions Progressive Web Apps as one of Google's two investments in the mobile web:

> We also continue to invest in the mobile web [...] Over this past year, Google has worked closely with publishers, developers, and others in the ecosystem to help make the mobile web a smoother, faster experience for users. A good example is [...] **Progressive Web Apps (PWA)**, which combine the best of the web and the best of apps—allowing companies to build mobile sites that load quickly, send push notifications, have home screen icons, and much more.

Service Worker support is the cornerstone of PWA support.

**Comment by Primigenus** [comment] 2016-04-29 08:13
When I read that yesterday I thought of you @dandv :) Maybe you can finagle Google into submitting the PR for service worker support in Meteor? ;-)

**Comment by UziTech** [comment] 2016-05-25 14:34
Looks like everyone is on the wagon accept Safari

**Comment by dandv** [comment] 2016-05-26 10:10
> Looks like everyone is on the wagon accept Safari

https://jakearchibald.github.io/isserviceworkerready/

**Comment by NitroBAY** [comment] 2016-06-18 15:32
Actually it took me few days but I succesfully developed a service worker with meteor, so it's possible :D

**Comment by trusktr** [comment] 2016-06-18 16:42
@NitroBAY It would be nice of you to share what you did! :]

**Comment by NitroBAY** [comment] 2016-06-18 22:44
With pleasure. I could probably not do it before 5 days tough. But when I could I will make code free, explain in the same time how my SW works and where I had problem with meteor and explain how to fix. Sorry that I can't do it before tough.

**Comment by vimes1984** [comment] 2016-06-20 14:03
@NitroBAY I'd be really interested in knowing how you did it.

**Comment by trusktr** [comment] 2016-06-20 19:22
@NitroBAY Cool. The info could be useful; knowing the caveats you faced could help eventually having an official solution.

**Comment by NitroBAY** [comment] 2016-06-23 19:50
Okay so for now it stores every single request on the Cache, send it back from the cache when the same request is made except for HTML which is taken from cache only if fetch from network failed (e.g no network). Pretty basic.
The only **problem**, for those who could be stop by that problem later on, was that the **"standard" SW** (i.e : the common exemples from the web) makes meteor refresh indefinitely. 
**Because** of hot code push that detect if the local css/js differs from the server.
So I had to **only return HTM**L if network failed to fetch. And also (because by default style.css?hash=test is equal to style.css?hash=second) check if the requested version differs from the cached one by checking the hash of the two versions. If the request version != cached version SW fetch from network, otherwise SW return the cached version.
Here's my implementation of Service Worker for every meteor apps :

**Comment by NitroBAY** [comment] 2016-06-28 01:55
There's still a problem where I need meteor's team to fix. SW need to be in a separate file in the root, so we must put it in /public. But then I can not import modules as the excellent (and necassary for a proper SW) [swivel](https://github.com/bevacqua/swivel). I hope Meteor could fix that soon

**Comment by mitar** [comment] 2016-06-28 01:59
This is exactly what my pull request in #6222 solved. :-)

**Comment by 7immy** [comment] 2016-07-26 22:45
Mobile applications and electron desktop apps could benefit greatly from this!

**Comment by dandv** [comment] 2016-09-06 17:38
[Apple is considering implementing service worker and `manifest.json` in Safari.](https://twitter.com/jonathandavis/status/767856921856442370)

**Comment by NitroBAY** [comment] 2016-09-18 19:45
I updated my repository. https://github.com/NitroBAY/meteor-service-worker

**Comment by laurentpayot** [comment] 2016-09-19 08:37
@NitroBAY Nice package but will it still be usable when Apollo will replace Meteor 1.5 data layer?

**Comment by NitroBAY** [comment] 2016-09-19 14:48
The service worker is only here to cache every assets of your website as images, fonts, javascript (the javascript files are mandatory to render your app as it includes HTML). I do not support making databases offline, for that option you need [ground:db](https://github.com/GroundMeteor/db).

**Comment by NitroBAY** [comment] 2017-02-10 18:07
Hello,
We're in february 2017, it's been almost 1 year since you tag this repo as "confirmed" so I'm wondering how far in this highly requested and extremely important request you progressed. Especially that you're closing every issue about appcache telling that SW is going to be implemented. I don't think that support SW take months to implement.
Thanks for your framework and your work.

**Comment by mitar** [comment] 2017-02-14 05:41
BTW, this is the 3rd most upvoted issue for Meteor.

**Comment by Twisterking** [comment] 2017-04-27 09:47
Dear MDG - any updates on this? Service Workers, even at a quite "simple" stage as proposed by @NitroBAY in [meteor-service-worker](https://github.com/NitroBAY/meteor-service-worker), would greatly enhance Meteor in many ways. Could you please update us on the progress on this front and (approx) when we will see Service Workers adopted into Meteor?! Thanks!

**Comment by spyhole** [comment] 2017-05-19 20:46
Dear MDG - any updates on this?

**Comment by trusktr** [comment] 2017-05-20 03:07
Service workers seem like the type of thing that would be great for Meteor tackle, for caching, faster loading, etc.

**Comment by dandv** [comment] 2017-05-24 21:38
Given that @trusktr kickstarted [the thread to kill bower](https://github.com/bower/bower/issues/2298) (:hooray:), I'd take his suggestion to heart.

**Comment by benjamn** [comment] 2017-05-25 00:00
@dandv I trust you will let us know when service workers are [supported](http://caniuse.com/#feat=serviceworkers) in Internet Explorer, Safari, or any mobile browser that works on iOS (important because Chrome iOS is based on mobile Safari, last I checked). Until then, perhaps it would be appropriate for you to disclose your affiliation?

As for Meteor 1.5, we managed to implement everything service workers claim to provide using [IndexedDB](http://caniuse.com/#feat=indexeddb) (for caching dynamic modules) and `WebSocket`s. To be clear, I genuinely wish service workers worked in all browsers, but that's simply not the case yet, so I can't help feeling like Google jumped the gun with its aggressive marketing campaign.

**Comment by mitar** [comment] 2017-05-25 00:05
> Until then, perhaps it would be appropriate for you to disclose your affiliation?

I think it is publicly visible on his GitHub profile?

**Comment by benjamn** [comment] 2017-05-25 00:07
Yes, but it may not be obvious to everyone participating in this thread that stumping for service workers and PWAs is literally @dandv's job.

**Comment by mitar** [comment] 2017-05-25 00:12
:-)

But 68 upvotes are not faked by Google.

Anyway, what would be a constructive path forward here? Provide support for new targets so that we can start experimenting with service (and web and other) workers?

I also agree that they are probably not yet ready for all use cases, so I agree that there is no need for them to be used by Meteor core code, if there are alternatives.

**Comment by benjamn** [comment] 2017-05-25 00:16
It's not hard to get 68 upvotes on GitHub for something people really want to use, even if that feature is not actually available yet. Google is glossing over that critical detail, and I'm pretty frustrated they went ahead with their marketing before they had buy-in from Apple and Microsoft. Everyone who is (rightly) excited about service workers ought to understand how much work remains before they are viable web technology.

**Comment by ndarilek** [comment] 2017-05-25 00:32
Will Meteor 1.5 let me set up code to run in the background so I can 
accept browser-based push notifications?

I'm no longer working on this project, but last year when I was, I 
basically wanted a JS file addressable at a specific URL, with its 
contents *not* added to the main bundle, but still with access to ES2015 
features so I could import modules and such. I basically wanted a 
transpiled file at something like /serviceworker.js which included 
whatever NPM modules I imported. My ugly workaround was to cut-and-paste 
all my dependencies into a file I maintained by hand. If Meteor let me 
do this then I'm sorry I missed it, but it was discouraging to hit that 
issue, and is a bit discouraging that this use case seems to be 
dismissed. At the end of the day I'm a whole lot less interested in who 
is affiliated with what, and a whole lot more interested in getting the 
job done. Meteor didn't deliver in this instance.

**Comment by mitar** [comment] 2017-05-25 00:36
> I'm no longer working on this project, but last year when I was, I basically wanted a JS file addressable at a specific URL, with its contents *not* added to the main bundle, but still with access to ES2015 features so I could import modules and such. I basically wanted a transpiled file at something like /serviceworker.js which included whatever NPM modules I imported.

+1

Custom targets could help with that. You could do `api.addFiles('my-source.js', 'web.serviceworker')` or something and have it done for you at `/__serviceworker/bundle.js`.

**Comment by dandv** [comment] 2017-05-25 00:50
@benjamn: Indeed, after being an unpaid [Meteor advocate](https://wiki.dandascalescu.com/essays/why_meteor), I'm now a Developer Advocate at Google, helping partners implement Progressive Web Apps, whose core technology is Service Worker.

Like everyone else in the ecosystem, I hope Safari implements SW support soon.

I also wish MDG best of luck and resources starting work on SW support for browsers currently supporting it, so it's ready shortly after Safari does release it.

Thank you for your all work so far. I really enjoyed using Meteor.

**Comment by hwillson** [comment] 2017-05-25 01:04
Given that WebKit service worker support is still [`Under Consideration`](https://webkit.org/status/#specification-service-workers) (and has been for more than a year), I think it's safe to assume we still have a long wait ahead of us (unfortunately 😞).

**Comment by trusktr** [comment] 2017-05-25 04:49
Now that `import()` is coming out, maybe that's one step closer to creating separate bundles for workers?

**Comment by hwillson** [comment] 2017-06-06 19:24
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Service%20worker%20support&body=Migrated%20from:%20meteor/meteor%235982) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-06 19:24 UTC
Labels: confirmed, feature, Impact:some, Project:Webapp:Force SSL
