### ISSUE TITLE
Can't use the positional $ operator on the client 

### ISSUE THREAD

**Issue by mart-jansink** [meteor/meteor#6948] opened 2016-04-30 18:16 UTC
Assume a `Students` collection with the following documents

```
{ "_id" : 1, "grades" : [ 80, 85, 90 ] }
{ "_id" : 2, "grades" : [ 88, 90, 92 ] }
{ "_id" : 3, "grades" : [ 85, 100, 90 ] }
```

updating 80 to 82 in the grades array in the first document, using the positional $ operator like

```
Students.update(
   { _id: 1, grades: 80 },
   { $set: { "grades.$" : 82 } }
)
```

doesn't work on the client because it throws the error `Not permitted. Untrusted code may only update documents by ID`. This is caused by the check on the number of fields in the selector on https://github.com/meteor/meteor/blob/devel/packages/minimongo/objectid.js#L13.

Can this extra check be removed and the update allowed if the selector has the `_id` field? That should suffice to ensure that only one document is updated by untrusted code and seems to work if I monkey patch `LocalCollection._selectorIsIdPerhapsAsObject`.

**Comment by mitar** [comment] 2016-05-07 06:25
So are you saying that it does not work at all in Minimongo, or that it does not work when running on the client inside untrusted context? As I understand it works with Minimongo, but it is limited when running as a remote operation outside Meteor method.

I think that in general calling `update` on collections outside Meteor methods is something you should not be doing. Just wrap your updates inside Meteor methods.

I think this ticket is duplicate of: https://github.com/meteor/meteor/issues/1921

**Comment by hwillson** [comment] 2017-06-12 14:36
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Can't%20use%20the%20positional%20%24%20operator%20on%20the%20client%20&body=Migrated%20from:%20meteor/meteor%236948) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-12 14:36 UTC
Labels: feature, Project:Minimongo
