### ISSUE TITLE
[1.3.3-beta.2] Breaks export {default} from './File';

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#7159] opened 2016-06-02 18:03 UTC
I use an `index.js` file to `export {default} from './File'` in a lot of my modules.

In `1.3.2.4` this would be equivalent to:

```javascript
import File from './File';
export default File;
```

In `1.3.3-beta.2`, however, it seems to add a named export of `default` rather than a default export.

Example:
```javascript
// File/File.js
export default 'file';

// File/index.js
import File from './File';
export default File;

// OtherFile/index.js
import File from '../File';

// 1.3.3-beta.2
console.log(File) // { default: 'file' }

// 1.3.2.4
console.log(File) // 'file'
```

**Comment by abernix** [comment] 2016-06-02 18:36
Duplicate of #7111. Please +1 that issue! :)

Closing.

**Closed by abernix** 2016-06-02 18:36 UTC
