### ISSUE TITLE
Cannot add a new dependency to the local package

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7892] opened 2016-10-08 07:10 UTC
I have an app with a local package. If I add a new dependency to the local package, like:

```
api.use([
  'peerlibrary:subscription-data@0.3.0'
]);
```

While running Meteor, Meteor reruns, but it fails with the error:

```
Error: Depending on unknown package peerlibrary:subscription-data
```

If I then stop Meteor, do:

```
meteor add peerlibrary:subscription-data

Changes to your project's package version selections:

peerlibrary:subscription-data  added, version 0.3.0

peerlibrary:subscription-data: Reactive and shared subscription data context
```

It works. After that I can remove the entry from `.meteor/packages` and it continues to work.

There should not be a need to add a package to the global scope for a new dependency in local package to work.

Meteor 1.4.1.2, but I have been observing this for previous versions as well.

The above is just an example package. It happens with any 3rd party package from Atmosphere.

I do not think there is anything special with my app, but it just happened for [this app](https://github.com/peer/mind).

**Comment by vacarsu** [comment] 2016-10-12 03:45
I have found that just restarting the server gets rid of the error. You shouldn't need to add the package to the global scope.

**Comment by mitar** [comment] 2016-10-12 03:48
When I was reporting the issue I got a feeling that this might be the case. I will try next time. :-)

But you are confirming that it happens only to you?

**Comment by mitar** [comment] 2016-10-12 03:48
Maybe this could be looked into by @benjamn as part of the next release.

**Comment by benjamn** [comment] 2016-10-12 16:15
This does seem like a bug.

**Comment by mitar** [comment] 2016-10-30 10:39
Just restarting didn't work for me. I have to add it to global scope and then I can remove it.

**Comment by husayt** [comment] 2016-11-17 09:38
Do you have any other workarounds meanwhile? Doing add package is very painful considering that we have many packages with dependencies

**Comment by sebakerckhof** [comment] 2016-12-06 00:07
Duplicate of: https://github.com/meteor/meteor/issues/7721

**Comment by chrisbutler** [comment] 2017-06-16 22:10
i'm still having this issue

**Comment by hwillson** [comment] 2017-11-15 15:19
As mentioned in https://github.com/meteor/meteor/issues/7892#issuecomment-265019522, this is a duplicate of https://github.com/meteor/meteor/issues/7721. Since #7721 has more details (and a reproduction), I'll close this one off. Thanks!

**Closed by hwillson** 2017-11-15 15:19 UTC
Labels: bug, confirmed, Impact:few, Project:Isobuild, Project:Tool
