### ISSUE TITLE
Unable to run meteor on a musl libc Linux distro

### ISSUE THREAD

**Issue by flatr0ze** [meteor/meteor#4640] opened 2015-06-28 01:17 UTC
Hello.

I have recently switched from a Debian-based distro to Void Linux (http://voidlinux.eu).
The meteor has installed well with `curl https://install.meteor.com | sh` but refused to run from both root and my user account, outputting
```
bash-4.3$ meteor create app
user, this is your first time using Meteor!
Installing a Meteor distribution in your home directory.
######################################################################## 100.0%
/home/user/.meteor/meteor: line 133: /home/user/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: No such file or directory
```

Hovewer:

```
host% /home/user/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node   
zsh: no such file or directory: /home/user/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node
host% file /home/user/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node
/home/user/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.15, BuildID[sha1]=71951c4923d99c39d40469808b81fefb77d613a0, stripped
```

and if I `cd` into that dir (.../bin) and run `exec ./node` it doesn't run the executable, says the same: "No such file or directory".

I will try to work this out together with the guys who maintain Void Linux on their irc channel, will report on how that goes. Seems like an issue with the way that node binary is compiled.

Thanks.

**Comment by flatr0ze** [comment] 2015-06-28 01:39
Okay, here's what I managed to find out so far:

```
bash-4.3$ file node
node: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.15, BuildID[sha1]=71951c4923d99c39d40469808b81fefb77d613a0, stripped
bash-4.3$ file `which node`
/usr/bin/node: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, BuildID[sha1]=488ab434f97d12dc6cc33a7d555197862114fdea, stripped
```
Apparently because I have `/lib/ld-musl-x86_64.so.1` instead of `/lib64/ld-linux-x86-64.so.2`, the `node` executable is unable to find _that_ file, therefore is starting to cry like a spoiled baby and refuses to do magic.

**Comment by glasser** [comment] 2015-06-30 21:38
Yes, this is a duplicate of #4573.

**Closed by glasser** 2015-06-30 21:38 UTC
