### ISSUE TITLE
ecmascript package crashes if a parent directory has a package.json file containing babel presets

### ISSUE THREAD

**Issue by iameli** [meteor/meteor#5654] opened 2015-11-12 06:17 UTC
**_2 Upvotes**_ That's not a great title, sorry. [Here's a reproduction](https://github.com/iameli/meteor-babel-bug).

With Babel 6, you can specify your preferred plugin presets in the `babel` section of the `package.json`. Trouble is, these settings seem to also apply to the `ecmascript` package's build process, and something's breaking.

Salient error appears to be `[BABEL] ecmascript.js: Unknown option: /Users/eli/code/meteor-babel-bug/package.json.presets`, but here's the full output:

```
[[[[[ ~/code/meteor-babel-bug/meteor-app ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  

   While processing files with ecmascript (for target web.browser):

   /Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11:
   [BABEL] random.js: Unknown option: /Users/eli/code/meteor-babel-bug/package.json.presets
   at Logger.error
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
   at OptionManager.mergeOptions
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
   at OptionManager.addConfig
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
   at OptionManager.findConfigs
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
   at OptionManager.init
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
   at File.initOptions
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:147:75)
   at new File
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:137:22)
   at Pipeline.transform
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
   at /Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:26:18
   at Cache.Cp.get (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/cache.js:89:19)
   at Object.compile (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:20:23)
   at Object.Babel.compile (packages/babel-compiler/babel.js:42:1)
   at packages/babel-compiler/babel-compiler.js:58:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:17:1)


   While processing files with ecmascript (for target os.osx.x86_64):

   /Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11:
   [BABEL] ecmascript.js: Unknown option: /Users/eli/code/meteor-babel-bug/package.json.presets
   at Logger.error
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
   at OptionManager.mergeOptions
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
   at OptionManager.addConfig
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
   at OptionManager.findConfigs
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
   at OptionManager.init
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
   at File.initOptions
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:147:75)
   at new File
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:137:22)
   at Pipeline.transform
   (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
   at /Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:26:18
   at Cache.Cp.get (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/cache.js:89:19)
   at Object.compile (/Users/eli/.meteor/packages/ecmascript/.0.1.6.l3ok10++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:20:23)
   at Object.Babel.compile (packages/babel-compiler/babel.js:42:1)
   at packages/babel-compiler/babel-compiler.js:58:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:17:1)


=> Your application has errors. Waiting for file change.
```

**Comment by timbotnik** [comment] 2015-11-17 23:02
Thanks for the reproduction, we will investigate further.

**Comment by laran** [comment] 2016-02-18 07:18
+1

**Comment by innervestRatio** [comment] 2016-05-23 20:42
+1

**Comment by abernix** [comment] 2016-11-25 19:48
Thanks for reporting this originally and providing a reproduction.  This has likely been fixed for a long time, so sorry this issue was ignored.

Everything should work properly in Meteor 1.4.2.3 due to significant changes to the way Meteor deals with Babel (see [History.md](https://github.com/meteor/meteor/blob/devel/History.md), starting with 1.3.3).  I was able to use the provided reproduction and get it working by:

```
cd meteor-app
meteor update --release 1.4.2.3
meteor update --all-packages
mv ../package.json .
meteor npm install babel-runtime --save
meteor npm install
```

Closing as resolved, but happy to discuss further if you have any issues!

**Closed by abernix** 2016-11-25 19:48 UTC
Labels: bug, confirmed, Impact:few, Project:JS Environment

**Comment by sanatankumar** [comment] 2017-08-24 00:44
I have meteor Meteor 1.5.1 version. Still I am getting this strange issue.

```
Errors prevented startup:

While processing files with ecmascript (for target web.browser):
/Users/sanatan/Desktop/tekie/node_modules/styled-components/lib/constructors/constructWithOptions.js:17:13: Cannot create styled-component for component: [object Object]
  at constructWithOptions (/Users/sanatan/Desktop/tekie/node_modules/styled-components/lib/constructors/constructWithOptions.js:17:13)
  at styled (/Users/sanatan/Desktop/tekie/node_modules/styled-components/lib/constructors/styled.js:15:12)
  at Function.memoisePluginContainer (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
  at Function.normalisePlugin (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
  at /Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
  at Array.map (native)
  at Function.normalisePlugins (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
  at OptionManager.mergeOptions (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
  at /Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
  at /Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
  at Array.map (native)
  at OptionManager.resolvePresets (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
  at OptionManager.mergePresets (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
  at OptionManager.mergeOptions (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
  at OptionManager.init (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
  at File.initOptions (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/index.js:212:65)
  at new File (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/index.js:135:24)
  at Pipeline.transformFromAst (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/pipeline.js:69:16)
  at transform (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:53:30)
  at compile (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:64:14)
  at Cache.Cp.get (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:102:19)
  at Object.compile (/Users/sanatan/.meteor/packages/ecmascript/.0.8.2.1umo2ry++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:28:23)
  at Object.Babel.compile (packages/babel-compiler.js:54:29)
  at packages/babel-compiler.js:183:22
  at Function.time (/tools/tool-env/profile.js:305:10)
  at profile (packages/babel-compiler.js:226:20)
  at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:182:20)
  at BabelCompiler.<anonymous> (packages/babel-compiler.js:114:26)
```

Here is my `.babelrc` file

```
{
  "presets": [
    "stage-3"
	],
  "plugins": [
    ["styled-components", {
      "displayName": true
    }]
  ]
}

```

and here is `package.json`

```
{
  "name": "tekie",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "babel-runtime": "^6.26.0",
    "meteor-node-stubs": "~0.2.4",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-materialize": "^1.0.10",
    "react-router-dom": "^4.1.2",
    "styled-components": "^2.1.2"
  },
  "devDependencies": {
    "babel-plugin-styled-components": "^1.1.7",
    "babel-preset-stage-3": "^6.24.1"
  }
}

```
I am trying to use babel-plugin-styled-components.

**Comment by klaussner** [comment] 2017-08-24 09:07
@sanatankumar That sounds like a different issue than what has been originally reported, and I couldn't reproduce the `Cannot create styled-component for component: [object Object]` error that you are getting. You should open a new issue and include a runnable reproduction, see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor). 🙂
