### ISSUE TITLE
RangeError:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by awatson1978** [meteor/meteor#3019] opened 2014-11-05 07:42 UTC
Hi there,
Getting a dinkum good bug while trying to compile our app today after upgrading from 0.9.4 to version 1.0.  Got this while trying to run ``demeteorizer``, then got it again when running ``meteor build ./output --server=http://dev.dart.cab``. 

````sh
Error: RangeError: Maximum call stack size exceeded
    at Object.Future.wait (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:323:16)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:535:31
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:533:9
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:338:18
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:331:34
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:329:23
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at enterJob (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:303:26)
    at Object.forkJoin (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:501:3)
    at _.extend.minifyJs (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:783:28)
    at _.extend.make (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:501:12)
    at makeClientTarget (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1951:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:2009:22
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:2008:9
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:250:13
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:243:29
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:241:18
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:232:23
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at Object.capture (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:231:19)
    at Object.exports.bundle (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1926:31)
    at buildCommand (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands.js:811:30)
    at main.registerCommand._.extend.name [as func] (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands.js:662:12)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1353:23
    - - - - -
    at Object.Future.wait (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:323:16)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:535:31
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:533:9
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:338:18
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:331:34
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:329:23
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at enterJob (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:303:26)
    at Object.forkJoin (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:501:3)
    at _minify (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:894:18)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:785:16
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:519:33
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:338:18
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:331:34
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:329:23
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at enterJob (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:303:26)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:518:34
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:516:28
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:515:33
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:514:29
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:513:31
    - - - - -
    at Object.Future.get (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:124:86)
    at Object.Future.wait (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:323:16)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:535:31
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:533:9
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:338:18
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:331:34
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:329:23
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at enterJob (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:303:26)
    at Object.forkJoin (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:501:3)
    at _minify (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:894:18)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:785:16
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:519:33
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:338:18
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:331:34
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:329:23
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at enterJob (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:303:26)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:518:34
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:516:28
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:515:33
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:514:29
    at _.extend.withValue (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.35.1pdmnj0++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:513:31
````

This was a Cordova enabled application, and was getting this error when ``server, browser, ios, android`` were all installed as platforms.  This particular error message was run after I removed ios and android.  As you can see, there are still plenty of references to ios and android.  

To be perfectly honest, I'm not entirely sure where to even begin debugging this message.  There's part of me that wants to nuke the ``.meteor`` directory, and see if a clean install would fix things.  But I figure I'd post, and see if anybody has some ideas before doing something drastic like that.

**Comment by PeppeL-G** [comment] 2015-03-04 13:14
@glasser, [here's a reproduction](https://github.com/PeppeL-G/meteor-big-js-problem). As Marco Vettorello said in the mailing list, the problem seems to have something to do with minimizing big JavaScript files.

**Comment by SDaron** [comment] 2015-03-08 18:57
I have the same error with openlayers 3.3.0 which is 480ko.
With Openlayers 3.2.0 (460ko) the error does not occur.
This is quite critic for me because I need to keep uptodate ith ol3...
Is there any workaround?

**Comment by markov00** [comment] 2015-03-09 08:21
@SDaron I've build myself OpenLayers with the following configuration setting
"compilation_level": "SIMPLE"
Try change this setting on the original ol.json build configuration and rebuild the OL library.

**Comment by SDaron** [comment] 2015-03-09 09:49
Unfortunatly, I've try this but it still raising the RangeError :-/
Did you successfully try with ol3 v3.3.0 & "compilation_level": "SIMPLE"?
On the meteor side, as minifying ol3 is not relevant, maybe it should be excluded from the minifying process.

**Comment by glasser** [comment] 2015-03-10 21:50
OK, it looks like this is UglifyJS2#414

It doesn't seem like they are going to fix it. One workaround is to run our node with a larger `--stack_size` but that could have a lot of impact (esp with fibers).

I think we should just make our call in `_minifyJs` catch errors, rethrowing anything but a range error, and if it's a range error, just put the non-minified code in.  Pull requests encouraged!

**Comment by dcworldwide** [comment] 2015-04-17 06:18
Just experienced this issue today. My stack is identical to @awatson1978.

**Comment by hamoid** [comment] 2015-04-17 18:58
I also had this issue when updating OpenLayers to 3.4.0.
https://forums.meteor.com/t/solved-mup-deploy-stopped-working/3086
As a solution, I built my own lighter version of OpenLayers, which is now down to 160Kb.

It was much work, because I had to specify each OL class and each OL #method I use in the json build file. Explained here: http://boundlessgeo.com/2014/10/openlayers-custom-builds-revisited/

**Comment by glasser** [comment] 2015-04-17 19:26
Oh good, this fix got released in UglifyJS 2.4.18 (devel is currently on 2.4.17).  Will try to upgrade devel soon.

**Closed** 2015-04-17 19:30 UTC
Labels: Project:Isobuild:Minifiers, pull-requests-encouraged

**Comment by serut** [comment] 2015-08-13 14:58
I don't understand why I still have this issue on my project. I first thought that was because the official build of meteor does not provide lastest fix, but now that I updated to meteor 1.1.0.3 it does not make sence.
I just have the openlayers 3.7.0 file in the client folder and I can't build.

**Comment by glasser** [comment] 2015-08-13 18:21
The fix is not yet released.  Meteor 1.1 came out in early April; see #4943 for the Meteor 1.2 release process.

**Comment by MasterAM** [comment] 2015-12-18 22:06
I received a related bug report for a package that I maintain (OpenLayers 3).

This only happens on Windows (at the moment), but I don't know how close the stack is to exhaustion in other environments.

The bug report: https://github.com/MasterAM/meteor-ol3/issues/5

The build fails because uglify.js runs out of stack space. This causes another error where the parse utility does not have a trace and therefore tries to call `spliet` on `undefined`, but that is unrelated.

When I changed the uglify.js statement threshold to 1000, it seemed to build fine.
(this is the relevant commit https://github.com/mishoo/UglifyJS2/commit/5801fa39e9524e7b7a565a39c5efa12cdef3202f).
and the relevant bug report: https://github.com/mishoo/UglifyJS2/issues/414

I think that the original thought of running the minifiers in a separate process with a larger stack or adding the ability to exclude files from the minification step was correct (I am not aware of such API option and this specific file is already minified, so the process wastes time and has little impact).

**Comment by lamass** [comment] 2017-02-25 15:54
Trying to install meteor: after the install, when i type in the cli meteor i get:
C:\Users\tonya>meteor
C:\Users\tonya\AppData\Local.meteor\packages\meteor-tool\1.4.3_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\q\q.js:70
hasStacks = !!e.stack;
^

RangeError: Maximum call stack size exceeded

what to do? Any assistance, please?
