### ISSUE TITLE
Meteor Truck Factor

### ISSUE THREAD

**Issue by gavelino** [meteor/meteor#4926] opened 2015-08-10 22:55 UTC
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Meteor** and obtained a value of **5**.

The developers responsible for this TF are:

David Glasser - author of 31% of the files
Slava Kim - author of 22% of the files
Sashko Stubailo - author of 17% of the files
David Greenspan - author of 16% of the files
Nick Martin - author of 10% of the files

To validate our results, we would like to ask **Meteor** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Meteor**?

(b) Do you agree that **Meteor** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Meteor** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by Slava** [comment] 2015-08-11 00:16
Not a bug. Closing.

**Closed by Slava** 2015-08-11 00:16 UTC

**Comment by rclai** [comment] 2015-08-11 10:37
You try the [forums](http://forums.meteor.com)

**Comment by grsabreu** [comment] 2015-08-12 11:48
You should try the forums, buddie [2]
