### ISSUE TITLE
Accounts.forgotPassword; Error: Did not check()

### ISSUE THREAD

**Issue by ubald** [meteor/meteor#5676] opened 2015-11-18 16:34 UTC
When using `audit-argument-checks` Meteor throws:

`Exception while invoking method 'forgotPassword' Error: Did not check() all arguments during call to 'forgotPassword'`

 when calling `Accounts.forgotPassword({email:'...'})`

**Comment by stubailo** [comment] 2015-11-24 22:47
That's very interesting, since we do in fact check that argument: https://github.com/meteor/meteor/blob/643d09a629a4fa28c466c72e1e3386f1080360f3/packages/accounts-password/password_server.js#L500

Do you have a reproduction of an app where this happens?

**Comment by ubald** [comment] 2015-11-25 02:41
I'll try to come up with a sample app, but meanwhile I re-tested and I realized that it's only doing that when called from the console in the browser.

**Comment by ubald** [comment] 2015-11-25 02:52
Or not... anyway, I made this simple test using the following packages in addition to the default ones when doing ```meteor create test```

```
audit-argument-checks
accounts-password
```

And only this in ```test.js```:

```
if (Meteor.isClient) {
  Meteor.startup(function () {
    Accounts.forgotPassword({email:'test@test.com'});
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    if ( !Meteor.users.findOne({username:'test'}) ) {
      Accounts.createUser({username:'test', email:'test@test.com'});
    }
  });
}
```

And when accessing ```http://localhost:3000/``` I see the mail message in the console, but right after it:

```
Exception while invoking method 'forgotPassword' Error: Did not check() all arguments during call to 'forgotPassword'
at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:411:1)
at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
at maybeAuditArgumentChecks (livedata_server.js:1695:18)
at livedata_server.js:708:19
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at livedata_server.js:706:40
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at livedata_server.js:704:46
at tryCallTwo (/Users/ubald/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
at doResolve (/Users/ubald/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
```

**Comment by hwillson** [comment] 2016-10-26 13:39
Hi all - I've traced this further. When a callback isn't included in [`Accounts.forgotPassword`](https://github.com/meteor/meteor/blob/f7271e214a689f5f6ae071faaecf581104ec0bed/packages/accounts-password/password_client.js#L219-L224), it passes `undefined` into its `Accounts.connection.call("forgotPassword", options, callback);` call. This translates into a DDP message that looks like the following (notice the second `null` element in the `params` array):

```
{ 
  msg: 'method',
  method: 'forgotPassword',
  params: [
    { email: 'test@octonary.com' },
    null 
  ],
  id: '1'
}
```

The `params` from this message get sent into the [`maybeAuditArgumentChecks`](https://github.com/meteor/meteor/blob/f7271e214a689f5f6ae071faaecf581104ec0bed/packages/ddp-server/livedata_server.js#L1705-L1712) function for verification, then fail because the [`forgotPassword`](https://github.com/meteor/meteor/blob/f7271e214a689f5f6ae071faaecf581104ec0bed/packages/accounts-password/password_server.js#L504-L517) Method is only checking the options object with the email; it's not expecting a second `null` parameter.

I believe the easiest fix for this is to avoid making the `forgotPassword` Method call with an `undefined` callback value. So we'd change `Accounts.forgotPassword` to something like:

```
Accounts.forgotPassword = function(options, callback) {
  if (!options.email) {
    return reportError(new Meteor.Error(400, "Must pass options.email"), callback);
  }
  if (callback) {
    Accounts.connection.call("forgotPassword", options, callback);
  } else {
    Accounts.connection.call("forgotPassword", options);
  }
};
```

I've submitted PR #7968 to help take care of this. Please fire over any feedback - thanks!

**Comment by tmeasday** [comment] 2016-11-08 23:58
#7968 is merged!

**Closed** 2016-11-08 23:58 UTC
Labels: bug, confirmed, Impact:few, Project:Accounts:Password
