### ISSUE TITLE
Error after updating meteor version to 1.4

### ISSUE THREAD

**Issue by BehrouzRiahu** [meteor/meteor#7614] opened 2016-08-09 17:35 UTC
I was working in a project in Meteor 1.3 and today I upgraded to 1.4 and when i try to run the project after running `meteor reset` I get the following error:

      While loading plugin `compileScss` from package `fourseven:scss`:
    
       /Users/mazinalmaskari/.meteor/packages/fourseven_scss/.2.1.1.xb5zda++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/lib/index.js:22:11:
       `libsass` bindings not found. Try reinstalling `node-sass`?
       at getBinding
       (/Users/mazinalmaskari/.meteor/packages/fourseven_scss/.2.1.1.xb5zda++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/lib/index.js:22:11)
       at Object.<anonymous>
       (/Users/mazinalmaskari/.meteor/packages/fourseven_scss/.2.1.1.xb5zda++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/lib/index.js:188:23)
       at Module._compile (module.js:409:26)
       at Object.Module._extensions..js (module.js:416:10)
       at Module.load
       (/Users/mazinalmaskari/.meteor/packages/meteorhacks_npm/.1.5.0.m71zaz++os+web.browser+web.cordova/plugin.initializing-npm-support.os/npm/initializing-npm-support/node_modules/node-echo/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
       at Function.Module._load (module.js:300:12)
       at Module.require (module.js:353:17)
       at require (internal/module.js:12:17)
       at Object.<anonymous>
       (/Users/mazinalmaskari/.meteor/packages/meteor-tool/.1.4.0-1.bf0k83++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/bundler.js:1633:22)
       at Object.require
       (/Users/mazinalmaskari/.meteor/packages/meteor-tool/.1.4.0-1.bf0k83++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/bundler.js:1607:31)
       at <runJavaScript-18>:15:16
       at <runJavaScript-18>:151:4
       at <runJavaScript-18>:158:3
       
       
    => Your application has errors. Waiting for file change.
                                                  
And when i remove the package `fourseven:scss` i get the following error:

    While processing files with stylus (for target web.browser):
       packages/ian:accounts-ui-bootstrap-3/accounts_ui.styl: Stylus compiler error: accounts_ui.styl:85:2
       81| }
       82| .btn-Twitter{
       83|     color: white;
       84|     background-color: #4099FF;
       85| }
       --------^
       86| 
       87| 
       
       fs.exists is not a function
       
       
    => Your application has errors. Waiting for file change.
                  

and when I install the package again after uninstalling it, i still get the second error instead of the first one.

What is the problem here?

**Comment by menelike** [comment] 2016-08-09 17:47
The second error might be related to https://nodejs.org/api/fs.html#fs_fs_exists_path_callback which states that this function is deprecated since v1.0.0.

See here as well https://github.com/fourseven/meteor-scss/issues/198 

All together I think your problems are related to https://github.com/fourseven/ and not to meteor.

**Comment by BehrouzRiahu** [comment] 2016-08-09 17:55
@menelike thanks, I am looking into it now

**Comment by benjamn** [comment] 2016-08-09 19:39
As for the original error, have you followed [the migration guide re: installing a build toolchain](https://guide.meteor.com/v1.4/1.4-migration.html#binary-packages-require-build-toolchain)?

**Comment by BehrouzRiahu** [comment] 2016-08-10 12:01
@menelike I had some connectivity issue and wasn't able to install meteor 1.4 after removing it, Thanks for the links :)

**Comment by BehrouzRiahu** [comment] 2016-08-10 12:01
@benjamn yes i did and the problem still exist

**Comment by laosb** [comment] 2016-08-10 22:11
Thinking that we should check whether the user have installed build toolchain correctly, and give a notice when they didn't.

**Comment by fourseven** [comment] 2016-08-11 04:58
This is being tracked here - https://github.com/fourseven/meteor-scss/issues/201

Meteor's ability to handle binary package requires VMs to build them, which isn't ideal. SCSS is probably the most popular css preprocessor, but also the only one Meteor doesn't officially support.

**Comment by digelim** [comment] 2016-08-13 02:57
Same problem here. Running my app as root solved for me.

**Comment by mitar** [comment] 2016-08-20 07:44
You should never run your app as root!

**Comment by abernix** [comment] 2016-09-26 13:38
Closing this as there are a number of issues here which do not all point to Meteor and you have not included a reproduction repo to further explore the problem.

In addition to the suggestions above, the version of `fourseven:scss` that you are using appears to be incredibly old.  There have been a lot of very important upgrades to that package and there have been some known issues along the way – `3.10.0` is out now and the related issues above (fourseven/meteor-scss#201 and fourseven/meteor-scss#198) have both been closed.

Finally, `metorhacks:npm` is no longer recommended or necessary and can cause problems in some cases.  Please read the `meteorhacks:npm` [instructions for migrating away](https://github.com/meteorhacks/npm#using-with-meteor-13) from it.

I highly recommend reading the migration guides available at http://guide.meteor.com/.

**Closed by abernix** 2016-09-26 13:38 UTC
