### ISSUE TITLE
Meteor bundles incorrect architecture for phantomjs executable

### ISSUE THREAD

**Issue by chompomonim** [meteor/meteor#5359] opened 2015-10-03 16:40 UTC
After upgrading into 1.2.0.1 phantomjs doesnt work on server. Getting: `bundle/programs/server/npm/npm-container/node_modules/phantomjs/lib/phantom/bin/phantomjs: Syntax error: Unterminated quoted string`

I'm developing on MacBook and deploying into Ubuntu server and into free Meteor.com hosting. Problem is on both servers.

The investigation result: there is apple OSX executable deployed onto linux machine (while bundling) I've checked file header, and experimentally downloaded the file back to my machine - it worked on Mac.

**Comment by avital** [comment] 2015-10-06 23:03
I wasn't able to reproduce this. I'm running on a Mac. I create a new app with 1.2.0.2 and ran `meteor deploy avital-use-phantomjs`. Then I hit http://avital-use-phantomjs.meteor.com/?_escaped_fragment_=1 and correctly got an HTML file that was fully rendered.

How can I reproduce this?

**Comment by dannymulvihill** [comment] 2016-02-04 11:23
I see this is old, but I'm seeing this issue as well. 

To reproduce you need to actually make use of phantomjs in the deployed app. In other words the app will deploy fine and everything will work. However, the parts of your app that rely on phantomjs will not work and you'll see the reported error in `meteor logs deployed-app-name.metoer.com`

In my case I am using webshot package, which employs phantomjs to grab screen shot of a given url. I have a meteor method that starts out like this:
```
getSiteImage: function(websiteId, url) {
	var newFile = new FS.File(),
		test = /:\/\/(.[^/]+)/,
		img  = url.match(test)[0].replace('://', ''),
		imageName = img+'.png',
		bufferArray = [];

	webshot(url, function(err, renderStream) {
		console.log(err);

		renderStream.on('data', Meteor.bindEnvironment(function(data) {
			bufferArray.push(data);
		}));
  		// ... removed rest for brevity as the error occurs here
```
The` console.log(err)` reports the following:
```
INFO [Error:
/meteor/containers/c5d82b48-9b9e-1f68-2581-f3cb9e282887/bundle/programs/server/npm/bryanmorgan_webshot/node_modules/webshot/node_modules/phantomjs/lib/phantom/bin/phantomjs: 4:
/meteor/containers/c5d82b48-9b9e-1f68-2581-f3cb9e282887/bundle/programs/server/npm/bryanmorgan_webshot/node_modules/webshot/node_modules/phantomjs/lib/phantom/bin/phantomjs:
Syntax error: Unterminated quoted string
]
```
Due to that the following exception is also thrown when attempting to call `renderStream.on`:
```
INFO Exception in callback of async function: TypeError: Cannot call method 'on' of undefined
at server/server.js:118:18
```

**Comment by hwillson** [comment] 2017-01-18 18:16
Give that one of the core devs (at the time) couldn't reproduce this issue, and no runnable reproduction has been provided, I'll close this issue off. Thanks for opening this originally!

**Closed by hwillson** 2017-01-18 18:16 UTC
Labels: Project:Webapp:Spiderable
