### ISSUE TITLE
'Segmentation fault 11' error during minification

### ISSUE THREAD

**Issue by oliverlloyd** [meteor/meteor#4446] opened 2015-05-24 21:41 UTC
During the minification step of the build I have recently started to get errors causing things to fail. It appears to be running out of memory and if I remove a few packages it goes away (but my project promptly breaks). It is a pretty big codebase but not crazy big.

    $ meteor build out.tar.gz
    Segmentation fault: 11

Sorry, I did try to create a demo repo but I wasn't able to reproduce the error outside of our specific project's codebase. I appreciate this make this issue vague but if you have any ideas for a workaround to get minification working they'd be appreciated.

**Comment by ekatek** [comment] 2015-05-26 21:28
We have not run into this (we did run into an issue that could be similar and might be fixed in the next release, but I don't think that this is it). We really can't debug it without a reproduction, because we don't know what is causing it.

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor 

You can turn off minification by passing in `--debug`. That's not really the same as getting minification working, but that's the best that we can do on this one unless we can reproduce the problem.

**Comment by oliverlloyd** [comment] 2015-05-26 21:36
I understand. If I manage to figure out a way to reproduce it I'll add a repo here but for now --debug keeps us moving.

Thanks anyway.

**Comment by abernix** [comment] 2016-05-25 12:00
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation – plus a lot has changed and Meteor 1.3 is out now.  Would be happy to reopen it if you're still experiencing this problem! :)

**Closed by abernix** 2016-05-25 12:00 UTC
Labels: Project:Tool

**Comment by oliverlloyd** [comment] 2016-05-25 12:07
Ha, sure, close away, we're not seeing this anymore. A year is a long time in Meteor land!

**Comment by ffxsam** [comment] 2017-03-19 22:20
I get this all the time, actually. Segmentation fault 11, and abort trap 6.. always kill my meteor process.

**Comment by michael-mccrickard** [comment] 2017-04-06 18:49
Segmentation fault 11, and abort trap 6 -- I'm getting this several times a day, also.  Seems like it started happening after one of the more recent updates / patches.

**Comment by ffxsam** [comment] 2017-04-06 20:56
@abernix Would be nice to see this issue re-opened if it makes sense to. 🙇

**Comment by michael-mccrickard** [comment] 2017-04-06 21:10
MIne does not happen on minify.  It just randomly occurs.  Is this the one that seems to be related to "too many files are open"?   The Mac seems to default to a relatively small number of files that are allowed to be open.  I saw a fix described once but did not try it.

**Comment by ffxsam** [comment] 2017-04-06 21:12
>It just randomly occurs.

Same here, actually. I can just be sitting there, and boom, seg fault. Or abort trap 6 (which I think is related to not having a high enough file limit). But the seg fault could be due to something else.

**Comment by michael-mccrickard** [comment] 2017-04-06 21:17
Oh, right!  Abort trap 6.  That's the file limit crash.  I knew it had a 6 in it. 

I assume this segmentation fault can't happen to the user running my app in their browser.  Or could it?

**Comment by ffxsam** [comment] 2017-04-06 21:33
I don't think it's a concern in production. I checked my Galaxy logs, everything has been running smoothly.
