### ISSUE TITLE
Error when publishing package to Atmosphere

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#4450] opened 2015-05-25 08:03 UTC
Hi, recently I've updated my package and received error. I don't remember exactly what the error was but it was something about the `toString` method. However, when I've checked on the Atmosphere, the new version was there. So I've assumed that everything works. Unfortunately when trying to run Meteor project I get following error:

```sh
App running at: http://localhost:3000/
=> Errors prevented startup:                  
   
   While checking for jagi:astronomy-validators@0.8.3:
   error: No compatible binary build found for this package. Contact the package author and ask them
   to publish it for your platform.
   
=> Your application has errors. Waiting for file change.
```

I've tried updating version **0.8.3** of my package with the command `meteor publish --update` but without the success. I had to change version number to **0.8.4** and after publishing everything works correctly. It's not the first time I have this problem.

**Comment by laosb** [comment] 2015-05-26 08:33
Is 0.8.x still supported by MDG? Maybe MDG could put a notice about it?

**Comment by jagi** [comment] 2015-05-26 09:17
When I wrote "version 0.8.x" I've meant version of my package not version of Meteor.

**Comment by ekatek** [comment] 2015-05-26 20:44
Thanks for the report, but without infomration on the error that you actually got when you first published to Atmosphere, we can't really debug this issue. We do know that there is some confusion when it comes to how publishing works (more on this in a bit).

When you publish a new version of a package, Meteor is actually doing two operations with the server, in sequence. First, we register that there is a new version (0.8.3). Then we register that there is a new build for this version (ie: actually upload the compiled isopack). As an example, for a package with binary code, we only do the first step (register the new version) and ask that the second step (uploading the isopack) be done from a designated build machine with `meteor publish-for-arch`. It looks like you ran into the problem where the first step succeeded (so Meteor knew that version `0.8.3` is supposed to exist), but the second step failed (so there was no build available).

Running `meteor publish --update` will only update the metadata, it won't upload a new build. This is intentional -- changing the actual uploaded code of your package would cause issues for its users. Instead, I would recommend trying `meteor publish --existing-version`, which will check that (1) there is no build for this architecture and (2) publish a new build for it. It is a command that we mostly use to publish the Meteor tool, but it should work in this instance too.

There is not enough information here to reproduce the issue, so I am going to close it for now.

**Closed by ekatek** 2015-05-26 20:44 UTC

**Comment by jagi** [comment] 2015-05-27 07:56
Ok thanks for clarification. I haven't just saved the error because it seemed to work. I will try checking if there is any build for this version. And if an error will appear in the future then I will repost this issue.
