### ISSUE TITLE
update Meteor error with meteor 1.4.1

### ISSUE THREAD

**Issue by wwwjason1994** [meteor/meteor#7902] opened 2016-10-10 14:58 UTC
when i update meteor on cmd ,i got a error
it show Downloading meteor-tool @1.4.1_1 [====       ]30%
but it can not complete  and show error after a few min 
like:
C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
    at Extract.Abstract.error (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)
    at Extract._streamEnd (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\extract.js:91:35)
    at BlockStream.<anonymous> (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:203:10)
    at BlockStream.resume (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:58:15)
    at Extract.Reader.resume (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\reader.js:242:34)
    at Entry.<anonymous> (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:261:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at Entry.resume (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:93:8)
    at resume (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:62:16)
    at unblockEntry (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:43:28)
    at Entry.<anonymous> (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:47:9)
    at FileWriter.<anonymous> (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:146:11)
    at emitNone (events.js:67:13)
    at FileWriter.emit (events.js:166:7)
    at WriteStream.<anonymous> (C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\file-writer.js:45:10)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:214:14
    at C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:241:16
    at C:\Users\--\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:232:16
    at FSReqWrap.oncomplete (fs.js:82:15)

I need some help ,
thank

**Comment by abernix** [comment] 2016-10-10 15:25
Duplicate of #7766.  Please read through that issue and use the issue search before opening new issues.

**Closed by abernix** 2016-10-10 15:25 UTC
