### ISSUE TITLE
meteor publish throw TypeError: Cannot call method 'toString' of undefined

### ISSUE THREAD

**Issue by chompomonim** [meteor/meteor#4920] opened 2015-08-10 09:50 UTC
I try to publish my package into atmosphere and get this error:

```
$ meteor publish

/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Cannot call method 'toString' of undefined
  at uploadFile (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/package-client.js:331:34)
  at /Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/package-client.js:758:7
  at /Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:352:18
  at [object Object]._.extend.withValue (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
  at /Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:345:34
  at [object Object]._.extend.withValue (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
  at /Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:343:23
  at [object Object]._.extend.withValue (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
  at Object.enterJob (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
  at Object.exports.publishPackage (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/package-client.js:757:18)
  at /Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-packages.js:435:21
  at /Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:264:13
  at [object Object]._.extend.withValue (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
  at /Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:257:29
  at [object Object]._.extend.withValue (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
  at /Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:255:18
  at [object Object]._.extend.withValue (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
  at /Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:246:23
  at [object Object]._.extend.withValue (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
  at Object.capture (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:245:19)
  at Object.main.captureAndExit (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:269:29)
  at Command.main.registerCommand.name [as func] (/Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-packages.js:431:8)
  at /Users/jaro/.meteor/packages/meteor-tool/.1.1.4.1gpolyt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
```

Any ideas what's the problem is?

**Comment by jortizsao** [comment] 2015-08-10 10:04
I also have the same problem when publish my package.

```
$ meteor publish

/Users/meteor/.meteor/packages/meteor-tool/.1.1.4.uzlqt4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Cannot call method 'toString' of undefined
    at uploadFile (/Users/meteor/.meteor/packages/meteor-tool/.1.1.4.uzlqt4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/package-client.js:331:34)
    at /Users/meteor/.meteor/packages/meteor-tool/.1.1.4.uzlqt4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/package-client.js:752:7
    at /Users/meteor/.meteor/packages/meteor-tool/.1.1.4.uzlqt4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:352:18
```

**Comment by anubhav94** [comment] 2015-08-11 22:22
Hey @jortizsao,

We'd need some more information to be able to check what was going wrong. It seems to be an error being returned which doesn't have an error property and thus getting the TypeError. Could you please provide a way for us to do the reproduction so we could figure out what's wrong and fix it?

**Comment by jortizsao** [comment] 2015-08-12 08:30
Hi @anubhav94 ,

I think this issue is the same as https://github.com/meteor/meteor/issues/4921 and https://github.com/meteor/meteor/pull/4922 . 

Thanks!

**Comment by anubhav94** [comment] 2015-08-12 09:16
Ahh ok I see. I'm going to close this then and we can reopen it if the problem still hasn't been solved.

**Closed by anubhav94** 2015-08-12 09:16 UTC
Labels: needs-repro, Project:Package Server
