### ISSUE TITLE
ConstraintSolver error while doing "meteor create simple-todos" in Meteor 1.0.3.1 and latest devel

### ISSUE THREAD

**Issue by graemian** [meteor/meteor#3516] opened 2015-01-21 08:51 UTC
This is the error:

Error: Match error: Expected plain object in field [0]
    at checkSubtree (packages/check/match.js:281:1)
    at packages/check/match.js:206:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at checkSubtree (packages/check/match.js:204:1)
    at check (packages/check/match.js:32:1)
    at [object Object].ConstraintSolver.PackagesResolver.resolve (packages/constraint-solver/constraint-solver.js:127:1)

I've debugged it a bit. Looks like a problem as it processes the ".meteor/packages" file. An object representing "meteor-platform" has a function as it's "constructor" field instead of an object.

**Comment by stubailo** [comment] 2015-01-22 23:21
Interesting, I don't have this issue. Can you think of what is different in your environment that might cause this?

**Comment by glasser** [comment] 2015-01-27 21:48
Are you running this from a checkout of Meteor or a built version of 1.0.3.1?  Your issue title alludes to this but isn't super clear.

I cannot reproduce this on either.  This could be related to changes @dgreensp has done recently (introducing better error checking into this code) but maybe it's already been fixed or something?

This bug does not have a reproduction, so I'm closing it. If anyone is able to come up a way to consistently reproduce it, we can reopen it.

**Closed by glasser** 2015-01-27 21:48 UTC

**Comment by graemian** [comment] 2015-03-04 09:30
I managed to solve this by removing ".meteor/packages" inside the Meteor repo. I don't know how this got broken in the first place though.
