### ISSUE TITLE
[1.3] IOS Build fails even with simplest possible scenario

### ISSUE THREAD

**Issue by Nomeasmo** [meteor/meteor#6604] opened 2016-03-28 17:59 UTC
OS X 10.11.3
Xcode 7.3 

It happened to my app from a 1.3 beta to somewhere 1.3-rc12.

``` sh
meteor create iOS-test
cd iOS-test
meteor update --release 1.3
meteor add-platform ios 
meteor run ios
```

This crashes as it does in my app

``` sh
=> App running at: http://localhost:3000/     
=> Errors executing Cordova commands:         

   While running Cordova app for platform iOS with options --emulator:
   Error: Command failed:                     
   /Users/oliver/Documents/node/spielwiese/ios-simple/.meteor/local/cordova-build/platforms/ios/cordova/run --emulator
   ENOENT, no such file or directory
   '/Users/xxx/Library/Logs/CoreSimulator/BE994A80-0F8E-4BBA-BE9C-C730DD580670/system.log'
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

/Users/oliver/.meteor/packages/meteor-tool/.1.3.0_3.8knbqj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
ExitWithCode:1
```

Unfortunately the log file does not exist

Using `meteor run ios-device` works well for this simple use case.

**Comment by martijnwalraven** [comment] 2016-03-29 07:43
This is most likely a permissions problem. Did you run `meteor` (or any other Cordova tool, like `ionic`) with `sudo` at any point maybe?

The easiest solution would probably be to just `rm -rf ~/Library/Logs/CoreSimulator`. Could you try that and let me know if that fixes it?

**Comment by Nomeasmo** [comment] 2016-03-29 08:11
Unfortunately this does not solve the problem. I get the same issue.
I recreated the CoreSimulator directory, so I have rw access.

Besides `meteor run ios-device` also `meteor build` works well.

**Comment by martijnwalraven** [comment] 2016-03-29 08:20
Yes, but `meteor run ios-device` and `meteor build` don't use `ios-sim`, which is what tries to create `system.log` here.

Are you sure you deleted `~/Library/Logs/CoreSimulator` and not just `~/Library/Developer/CoreSimulator`?

**Comment by Nomeasmo** [comment] 2016-03-29 10:37
Yes, like you suggested. 

But I gave it a try and created the log directory manually. This time `meteor run ios` worked well and the simulator started as expected.

**Comment by xusai2014** [comment] 2016-06-02 08:48
@Nomeasmo  I  met the same issue. I have remove the ~/Library/Logs/CoreSimulator but could not meteor run ios . the exception is as below: 

=> Started your app.                          
                                              
=> App running at: http://localhost:3500/     
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform iOS with options --emulator:
   Error: Command failed:                     
   /Users/xujerry/marathonApp/.meteor/local/cordova-build/platforms/ios/cordova/run
   --emulator
   ENOENT, no such file or directory
   '/Users/xujerry/Library/Logs/CoreSimulator/9AD0E49F-BE70-4426-A107-E50E58F01D83/system.log'
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)
                                              
/Users/xujerry/.meteor/packages/meteor-tool/.1.3.2_4.1lh9wc0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
ExitWithCode:1

**Comment by boblikesoup** [comment] 2016-06-03 23:24
Is this the solution? http://stackoverflow.com/questions/34773378/no-such-file-directory-message-when-trying-to-run-ios-emulator-using-meteor-run

**Comment by hwillson** [comment] 2017-08-23 13:01
As mentioned in https://github.com/meteor/meteor/issues/6604#issuecomment-202764238, this sounds like a permissions problem. Since there hasn't been any activity on this issue in a while (and we don't have a reproduction to help with troubleshooting - see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)), I'll close this for now. Thanks!

**Closed by hwillson** 2017-08-23 13:01 UTC
Labels: Project:Mobile
