### ISSUE TITLE
Blaze.remove on Views rendered based on a data context provided by template helper does not work

### ISSUE THREAD

**Issue by lucendio** [meteor/meteor#3828] opened 2015-02-27 18:32 UTC
I am not sure, if I'm holding it wrong or if its really a bug. I just ran into the problem introduced above.

I simply want to remove an list element by clicking on it. The event handler then just perform a Blaze.remove( template.view ). And that works, well, sort of. Only the once disabear which I put into the DOM by Blaze.renderWithData. The elemets rendered based on a data context provided by a template helper, just don't. Eaven if I make data source reative.

I provided an example: https://github.com/lucendio/blaze-remove-bug
The first 3 (client/templates/clog_onsceen.js:21) messages appearing on the top of the window wouldn't disapear by clicking on them, but the last does (client/templates/clog_onsceen.js:46)
disclaimer: I tried to run my example with a late version of devil (27th of Feb.), becasue I saw a potentialy related fix listed in the History.md for the next release. But without any success - I did as described in the readme and sadly run into "error: Symlink cycle detected at meteor/dev_bundle/lib/node_modules".

As I said, I am not sure, if it is really a bug or if I am doing anything wrong. If thats the case, I am sorry for bothering and would like to get an enlightenment from you guys :)

**Comment by stubailo** [comment] 2015-03-10 21:55
It looks like you have found a bug. Thanks for the clear reproduction, we will look into it deeply as soon as we can.

**Comment by taylordj** [comment] 2015-05-12 17:20
I'm encountering the same issue. @stubailo if you can point me generally in the right direction, I'd be happy to start debugging.

**Comment by jdmswong** [comment] 2016-03-01 00:57
I'm having this issue as well

**Comment by lucendio** [comment] 2016-03-03 14:55
now that blaze was break off into another repo, do you guys have any plans about how to get all related issues reloaced as well?

/cc @mitar

**Comment by flatr0ze** [comment] 2016-04-01 23:36
Same issue here.

I'm rendering with Blaze.renderWithData inside of Meteor.autorun.
When I do Blaze.remove on the view that the renderer returns, it does not destroy the view.

The whole thing works fine with Blaze.render, but once I render with data, it binds the events and callbacks (such as .onDestroyed) multiple times. It surely still a problem. Please fix it ASAP, very important for many of my projects!

Meteor 1.3.

P.S.
This time the aforementioned jQurey(...).remove() fix does not work in this case.

**Comment by mitar** [comment] 2016-04-02 00:41
What about calling `Blaze.renderWithData` inside `Tracker.nonreactive` inside `Tracker.autorun`?

**Comment by flatr0ze** [comment] 2016-04-02 01:23
Nah, same thing, @mitar

**Comment by flatr0ze** [comment] 2016-04-02 01:51
upd: the problem seems to be happening with Blaze.render as well. This problem occurs each time I re-create the same parent (container) DOM element and render a template inside it, either with Blaze.render or Blaze.renderWithData. Calling Blaze.remove() upon destroying the template helps, but only while the container DOM is still the same.

In my applications I render various templates inside that DOM, (within Meteor.autorun). I have Blaze.remove() on the first line of my .autorun's callback function and also prior removing that DOM element in my jQuery plugin.

**Comment by flatr0ze** [comment] 2016-04-02 02:51
Here's a my POS POC: https://github.com/flatr0ze/meteor-render-blaze-remove-bug

**Comment by mitar** [comment] 2016-04-02 05:02
I just quickly looked at your code and I think that you should not be using Blaze in the right way. You should not manually render code inside Blaze code. [This like this](https://github.com/lucendio/blaze-remove-bug/blob/master/client/templates/clog_onscreen.js#L45) is not proper way.

I would really argue that you do not manually render and remove Blaze views, but you leave to reactivity of Blaze to do this for you.

What I would do is have a reactive variable on your template for message which holds state if message is displayed or not. They message would be wrapped with `{{#if visible}}`. And event handler would just set that state to false. The rest would be decleratively been taken care by Blaze.

**Comment by flatr0ze** [comment] 2016-04-02 06:42
I have revamped my app's code to use an empty wrapping template, which has `this.autorun()` inside.
I assign both that template's own **view** and the inner **view** within `this.autorun()` to the top-level DOM element, as separate properties; this way I can clean both of them onRemove with
```
  var _cleanUp = function (box) {
    if ( box._view !== void 0 ) {
      Blaze.remove(box._view);
    }

    if ( box.inner_view !== void 0 ) {
      Blaze.remove(box.inner_view);
    }
  };
```

A little bit more code for me, but at the same time I get zero leaks this way.

Thank you for the help, @mitar

**Comment by mitar** [comment] 2016-04-02 07:00
But why oh why you are doing it like this? Simply forget about `Blaze.render` and `Blaze.remove` and try to do it without.

**Comment by flatr0ze** [comment] 2016-04-03 01:13
It's a massive application which hits the CPU hard. Putting the logic within Blaze templates makes things times slower. That's something I have been struggling with for a long time.

**Comment by mitar** [comment] 2016-04-03 01:38
This why you should try to limit your reactivity by using things like [computed field](https://github.com/peerlibrary/meteor-computed-field). Or switch to React.

**Comment by hwillson** [comment] 2016-12-06 19:49
Moved over to meteor/blaze#196 - closing here. Thanks!

**Closed by hwillson** 2016-12-06 19:49 UTC
Labels: confirmed, Project:Blaze
