### ISSUE TITLE
Deployed Meteor does not exit on replicaset failure

### ISSUE THREAD

**Issue by kostko** [meteor/meteor#3306] opened 2014-12-17 12:02 UTC
When a deployed Meteor instance (v1.0.1) is started too soon while the mongod instance is still initializing, it may fail with an exception like this:
```
2014-12-17_11:53:14.80685 Exception in callback of async function: Error: No valid replicaset instance servers found
2014-12-17_11:53:14.80688     at /bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:446:45
2014-12-17_11:53:14.80688     at /bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:376:9
2014-12-17_11:53:14.80688     at Server.Base._callHandler (/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
2014-12-17_11:53:14.80689     at /bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
2014-12-17_11:53:14.80689     at MongoReply.parseBody (/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
2014-12-17_11:53:14.80690     at null.<anonymous> (/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
2014-12-17_11:53:14.80690     at emit (events.js:95:17)
2014-12-17_11:53:14.80690     at null.<anonymous> (/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
2014-12-17_11:53:14.80691     at emit (events.js:98:17)
2014-12-17_11:53:14.80691     at Socket.<anonymous> (/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:422:22)
```

This by itself is not an issue, but the problem is that the nodejs process does not exit on such a failure and so the application is not restarted and hangs.

**Comment by glasser** [comment] 2015-01-14 00:12
Duplicate of #3038.

**Closed by glasser** 2015-01-14 00:12 UTC
