### ISSUE TITLE
Error: EBADF, read

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#4201] opened 2015-04-15 04:51 UTC
Happens on random source file modifications and subsequent client refresh.
Met 1.1 for Win

**Comment by glasser** [comment] 2015-04-15 05:01
Is there a full stack trace you can show?

**Comment by Slava** [comment] 2015-04-15 05:02
@glasser It happened to me on Mac too: https://github.com/meteor/windows-preview/issues/130

**Comment by avalanche1** [comment] 2015-04-15 05:11
How do I get it?

**Comment by glasser** [comment] 2015-04-15 05:37
I mean, please show more context about what was printed to your screen than just one line.

**Comment by glasser** [comment] 2015-04-15 05:45
Hmm, this is definitely strange.  `fs.readFile` is failing because an fd becomes invalid between open and fstat?

Maybe a rogue close somewhere else in the process? Would be easier to track down if it were replicable.

**Comment by avalanche1** [comment] 2015-04-15 06:27
Unfortunately there's nothing more to the error, only this description and timestamp:
W20150415-09:10:20.648(4)? (STDERR) Error: EBADF, read

**Comment by DannyFeliz** [comment] 2015-04-19 05:37
The error looks like this
![error](https://cloud.githubusercontent.com/assets/5460365/7218283/862a0576-e634-11e4-86d7-8bd7c6046dce.png)

**Comment by avalanche1** [comment] 2015-04-19 11:33
Yep, and sometimes it becomes
![image](https://cloud.githubusercontent.com/assets/10534563/7219283/61c76262-e6a9-11e4-9112-ef0691b8f183.png)

**Comment by Sanjo** [comment] 2015-04-27 13:05
I also get this sometimes when saving files I think. I use Mac OS X 10.10.2, Meteor 1.1.0.2 and Webstorm 10 with the option "Use safe write (save changes to a temporary file first)" turned on. I just mention this because maybe this has something to do with producing this error. This option is under "Appearance & Behavior" -> "System settings"

```
Error: EBADF, fstat
  at Object.Future.wait (/Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
  at Object.wrapper [as readFile] (/Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1350:24)
  at readFile (/Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:226:18)
  at [object Object]._.extend._fireIfFileChanged (/Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:339:20)
  at /Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:401:12
  at Function._.each._.forEach (/Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
  at [object Object]._.extend._startFileWatches (/Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:392:7)
  at new Watcher (/Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:323:8)
  at setupClientWatcher (/Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:723:23)
  at [object Object]._.extend._runOnce (/Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:764:9)
  at [object Object]._.extend._fiber (/Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:821:28)
  at /Users/jonas/.meteor/packages/meteor-tool/.1.1.3.omtlce++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:402:12

    - - - - -
```

**Comment by avalanche1** [comment] 2015-05-01 07:24
ok, i've got smth new:
```
E20150501-10:19:05.047(4) (webapp_server.js:419) Error serving static file Error: ENO
ENT, stat 'C:\Users\Artem\Desktop\Work\zBoard\.meteor\local\build\programs\web.browse
r\packages\minimongo.js'
E20150501-10:19:05.048(4) (webapp_server.js:419) Error serving static file Error: ENO
ENT, open 'C:\Users\Artem\Desktop\Work\zBoard\.meteor\local\build\programs\web.browse
r\packages\id-map.js'
E20150501-10:19:05.050(4) (webapp_server.js:419) Error serving static file Error: ENO
ENT, open 'C:\Users\Artem\Desktop\Work\zBoard\.meteor\local\build\programs\web.browse
r\packages\ordered-dict.js'
E20150501-10:19:05.051(4) (webapp_server.js:419) Error serving static file Error: ENO
ENT, open 'C:\Users\Artem\Desktop\Work\zBoard\.meteor\local\build\programs\web.browse
r\packages\geojson-utils.js'
E20150501-10:19:05.052(4) (webapp_server.js:419) Error serving static file Error: ENO
ENT, stat 'C:\Users\Artem\Desktop\Work\zBoard\.meteor\local\build\programs\web.browse
r\packages\ddp.js'
```

**Comment by alexcorre** [comment] 2015-06-09 20:22
I am seeing this periodically on mac Meteor 1.1.0.2

```
Error: EBADF, fstat
  at Object.Future.wait (/Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
  at Object.wrapper [as readFile] (/Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1350:24)
  at readFile (/Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:226:18)
  at [object Object]._.extend._fireIfFileChanged (/Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:339:20)
  at /Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:401:12
  at Function._.each._.forEach (/Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
  at [object Object]._.extend._startFileWatches (/Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:392:7)
  at new Watcher (/Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:323:8)
  at setupClientWatcher (/Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:723:23)
  at [object Object]._.extend._runOnce (/Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:764:9)
  at [object Object]._.extend._fiber (/Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:821:28)
  at /Users/alexcorre/.meteor/packages/meteor-tool/.1.1.3.l8m8fc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:402:12
```

**Comment by shrimpster00** [comment] 2015-07-02 18:31
I receive the same error, in Windows 8.1 x64 and Ubuntu 14.04 x64.
The "EBADF, read" error does not have an effect on the running application. However, the "Error serving static file" results in a file (in my case, an mp3 clip) from the static/ folder to not be played.

**Comment by stubailo** [comment] 2015-08-11 18:58
This is definitely a real thing. I just closed a thread on meteor/windows-preview with 35 comments about this; let's move the main discussio here.

@batjko originally posted:

This comes from the StackOverflow thread [here](http://stackoverflow.com/questions/26737053/w20141104-192353-8485-5-stderr-error-ebadf-read-meteor-js-error/29168406#29168406).

Essentially, every time the Meteor server refreshes (i.e. after a file change), it spits out this error to the console / command window:

![image](https://cloud.githubusercontent.com/assets/7287076/6756151/d9d6378e-cf1f-11e4-8899-f65129bfa6bd.png)


Note that the functionality seems to be unaffected (I was able to run through the entire standard tutorial on the Meteor.com site without problems). Just thought I'd log it and was directed to do so here.

**Comment by bernardoatworkpop** [comment] 2015-10-21 19:38
I'm hitting this quite frequently these days, around 2-3. I'm running El Capitain, anything related to that perhaps?

**Comment by bobacadodl** [comment] 2015-11-25 04:18
This error is spamming my console too. Doesn't seem to be affecting anything (everything seems to be working fine), but it is extremely annoying.

**Comment by sebakerckhof** [comment] 2015-12-01 11:17
I noticed that (at least in 1.2.1) these errors only show up when I open the browsers debug tools. 

I can consistently reproduce if I empty the browser cache and reload the page with developer tools closed -> No errrors. As soon as I open developer toools I get these errors. The second time I open the developer tools (even after a soft reload), I don't get these errors, because of the browser cache.

Therefore I think these errors are related to the missing locations the source maps refer to:  https://github.com/meteor/meteor/issues/5142

**Comment by glasser** [comment] 2015-12-02 02:33
@sebakerckhof Are you able to create a small consistent minimized reproduction we can experiment with?

**Comment by luisatlive** [comment] 2015-12-04 00:44
This is causing a lot of lost productivity here at Workpop. It's not something we can easily repro... as we're developing, between 3-15 times a day depending on the day meteor will cold crash and we have to manually restart it. With the slower 1.2.1 build times it's becoming really impactful unfortunately. I'm more than happy to run with an instrumented tool that could help you guys debug this with logs or whatever is needed when it happens, that tends to have better outcomes for heisenbugs such as this rather than trying to narrow down repro steps.

PS: You guys have our dev sub for a repro environment, albeit not very minimized :)

**Comment by avital** [comment] 2015-12-07 23:24
@glasser How did you deduce that "fs.readFile is failing because an fd becomes invalid between open and fstat?"

**Comment by glasser** [comment] 2015-12-08 00:52
So @Slava 's stack trace in windows-preview was:

```
Error: EBADF, fstat
  at Object.Future.wait (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
  at Object.wrapper [as readFile] (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1330:24)
  at readFile (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:226:18)
  at [object Object]._.extend._fireIfFileChanged (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:339:20)
  at onWatchEvent (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:478:16)
  at [object Object].<anonymous> (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/func-utils.js:35:18)
  at /Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:161:12
```

(I just re-enabled and re-disabled issues on windows-preview to get that)

**Comment by glasser** [comment] 2015-12-08 00:54
and so what that means is that fs.readFile is returning EBADF from fstat.  What EBADF means is that something tried to operate on an fd that is not valid.  The only fstat in fs.readFile comes right after the fs.open.

So most likely this means some concurrent part of the process is calling close() on the wrong file descriptor. Probably a double-close: ie, the buggy code does open() -> 42, close(42), close(42), and in between the two close(42) calls our friend fs.readFile gets its own open() -> 42.

It could also indicate a concurrency bug in how we wrap fs.readFile into files.readFile, but that's less likely.

**Comment by glasser** [comment] 2015-12-08 00:55
oh it's also what @sanjo's trace is showing

**Comment by abecks** [comment] 2016-03-10 00:07
This is happening to me using OS X 10.11.3 with WebStorm 10.  It happens the most when I save the same file frequently. I might hit save, then quickly fix a typo, then hit save again. The crash occurs while Meteor is building/refreshing. If it wait for it finish before I hit save again, it won't happen. I was not able to determine the right timing to make this reliably reproducible, but it happens fairly often.

Full stack trace:
```
/Users/andrew/.meteor/packages/meteor-tool/.1.1.10.1o4ugx1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: EBADF, fstat
    at Object.Future.wait (/Users/andrew/.meteor/packages/meteor-tool/.1.1.10.1o4ugx1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as readFile] (/tools/fs/files.js:1334:20)
    at readFile (/tools/fs/watch.js:243:18)
    at Watcher._fireIfFileChanged (/tools/fs/watch.js:372:20)
    at onWatchEvent (/tools/fs/watch.js:517:16)
    at [object Object].<anonymous> (/tools/utils/func-utils.js:35:18)
    at /tools/utils/fiber-helpers.js:158:12
    - - - - -
```

**Comment by Firfi** [comment] 2016-09-05 09:07
happens the same on OSX 

/Users/firfi/.meteor/packages/coffeescript/.1.0.16.1uhzf8w++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: EBADF, fstat

**Comment by tjramage** [comment] 2016-10-30 16:23
I can reproduce this issue on macOS Sierra 10.12.1 (have tried both Node v4 and v6). It happens when I try to install the `nathantreid:css-modules` package. Basic steps:

```
meteor create mytestapp
cd mytestapp
meteor add nathantreid:css-modules
```

After a couple of minutes of installing the `nathantreid:css-modules` package, it consistently fails right at the end with the following stack trace:

```
/Users/tjramage/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: EBADF: bad file descriptor, fstat
    at Error (native)
 => awaited here:
    at Promise.await (/Users/tjramage/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:39:12)
    at Object.wrapper [as readFile] (/tools/fs/files.js:1522:32)
    at /tools/isobuild/isopack.js:979:15
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/tjramage/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:965:7)
    at /tools/packaging/tropohouse.js:521:21
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/tjramage/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/packaging/tropohouse.js:520:13
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/packaging/tropohouse.js:515:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.download (/tools/packaging/tropohouse.js:427:20)
    at /tools/packaging/tropohouse.js:600:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object].downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:597:20)
    at /tools/project-context.js:776:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:775:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (/tools/project-context.js:774:13)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/cli/commands-packages.js:2036:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Command.func (/tools/cli/commands-packages.js:2035:27)
    at /tools/cli/main.js:1454:23
```

Any ideas? This is preventing me from upgrading to 1.4.2.

**Comment by bshamblen** [comment] 2016-11-01 16:37
I've been receiving a similar error since last Friday afternoon. About 70% of the time, when I try to run the following command:

```cli
meteor test-packages ./ --driver-package practicalmeteor:mocha --settings settings.json
```

```cli
/Users/bshamblen/.meteor/packages/meteor-tool/.1.4.2.cmq2de++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: EBADF: bad file descriptor, read
    at Error (native)
 => awaited here:
    at Promise.await (/Users/bshamblen/.meteor/packages/meteor-tool/.1.4.2.cmq2de++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:39:12)
    at Object.wrapper [as readFile] (/tools/fs/files.js:1522:32)
    at /tools/isobuild/isopack.js:979:15
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/bshamblen/.meteor/packages/meteor-tool/.1.4.2.cmq2de++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:965:7)
    at Isopack.initFromPath (/tools/isobuild/isopack.js:885:17)
    at /tools/isobuild/isopack-cache.js:286:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/isopack-cache.js:272:24
    at Function.time (/tools/tool-env/profile.js:305:10)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:262:15)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/Users/bshamblen/.meteor/packages/meteor-tool/.1.4.2.cmq2de++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:809:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:808:18)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/runners/run-app.js:549:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:548:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:617:35)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```

Meteor version 1.4.2
Mac OSX Sierra 10.12.1

Not sure if it's related, but I also haven't been able to use `spacejam` since then.

**Comment by mair0z** [comment] 2016-11-09 08:59
I have the same problem on Mac OSX Sierra 10.12.1, Meteor version 1.4.2. :( Does anybody have ideas?

**Comment by alvara** [comment] 2017-01-05 07:33
Same problem here on multiple machines. 

On Meteor 1.4.1.3, Mac El Capitan 10.11.6, WebStorm 2016.3, and chrome  55.0.2883.95 with dev tools open. I notice it happens mostly when I am refreshing the client immediately after saving a change to a file.

**Comment by luiseduardobrito** [comment] 2017-08-23 02:31
Got this today with Meteor 1.5.1, MacOS Sierra 10.12.6 (16G29) 3 times in a row.

Any updates?

**Comment by hwillson** [comment] 2017-11-24 19:11
If anyone sees this happen with Meteor 1.6, please let us know. I'll close this issue for now however, since most people who had this problem mentioned it was fixed by using a newer version of Node (and Meteor 1.6 is now using one of the most recent Node versions, 8.8.1). Thanks!

**Closed by hwillson** 2017-11-24 19:11 UTC
Labels: Project:Tool
