### ISSUE TITLE
Meteor doesn't load file named ad

### ISSUE THREAD

**Issue by Laboratory** [meteor/meteor#6617] opened 2016-03-29 13:38 UTC
Hello, everyone!

I created the files into directory `/client/templates/ad.coffee`, `/client/templates/ad.html` and this files doesn't load. If I renamed (for example to `active_dir.coffee[html]`), it would work.

- Meteor version 1.2.0.1
- MacOS
- Packages
`````bash
mbp-vitaly:SAML Laboratory$ meteor list
coffeescript     1.0.9* Javascript dialect with fewer braces and semicolons
fourseven:scss   3.2.0* Style with attitude. Sass and SCSS support for Meteor.js (with autoprefixer and sourcemaps).
http             1.1.1* Make HTTP calls to remote servers
iron:router      1.0.9* Routing specifically designed for Meteor
meteor-platform  1.2.3* (Deprecated) Include a standard set of Meteor packages in your app
meteorhacks:npm  1.5.0  Use npm modules with your Meteor App
npm-container    1.2.0+ Contains all your npm dependencies
tinytest         1.0.6* Tiny testing framework
twbs:bootstrap   3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.
`````

LV

**Comment by benjamn** [comment] 2016-03-29 16:50
Can you provide a reproduction?

Also, just in case you haven't heard, [Meteor 1.3 is out now](http://info.meteor.com/blog/announcing-meteor-1.3). If you update, you probably won't need `meteorhacks:npm` or `npm-container` anymore, and there's a good chance we've fixed your `.coffee` bug since 1.2.0.1.

**Comment by stubailo** [comment] 2016-03-29 22:20
Closing this until there is a reproduction.

**Closed by stubailo** 2016-03-29 22:20 UTC
Labels: needs-repro
