### ISSUE TITLE
Multiple subscriptions don't work on same document with different set of fields

### ISSUE THREAD

**Issue by aram90** [meteor/meteor#3259] opened 2014-12-08 18:43 UTC
For example there is a collection C and client is subscribed to `C.find({}, {fields: {a: true, b: true}})`. Then after some event client subscribes to `C.find({_id: 'some_id'}, {fields: {a: true, b: true, c: true}})`. In that case subscription is not updated, i.e. the field `c` is not available to client. It seems that wider subscription is not working on a document to which there is already an older subscription with less fields.

**Comment by kostko** [comment] 2015-01-04 14:17
Has there been any progress on this? I am experiencing the exact same issue.

**Comment by mitar** [comment] 2015-01-10 16:57
This definitely works and I am using it in my cases. But only top-level fields are merged. It does not work with subdocuments and this is a known Meteor limitation. But for top-level fields it works. Please create a small reproduction. See [guidelines to how to prepare a reproduction](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor) and report bugs.

**Comment by glasser** [comment] 2015-01-12 20:04
As many of our community members have said, code snippets are not a reproduction.  I'll be happy to re-open this if a full reproduction is included. https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Closed by glasser** 2015-01-12 20:04 UTC

**Comment by juliomac** [comment] 2015-08-22 17:38
I have the exact same problem. Thanks @aram90 for bringing it up on this post. I spent hours trying to figure it out.

I have made a simple repo to show up the problem. Hope it can contribute to fix this issue.

It is at: https://github.com/juliomac/Bug-MultiSubs-DifSetofFields-3259

**Comment by mitar** [comment] 2015-08-22 17:52
Reproduction repository is empty.

**Comment by juliomac** [comment] 2015-08-23 01:50
Ooops! Clicked upload too quickly. It is now up there. Sorry for it.

**Comment by mitar** [comment] 2015-08-23 03:14
OK, this example has some basic issues. Like you cannot subscribe inside a template helper and then just expect that data will be available immediately afterwards? You should put your subscribe calls inside `onCreated`, see [example](http://docs.meteor.com/#/full/Blaze-TemplateInstance-subscribe).

**Comment by aram90** [comment] 2015-08-23 08:12
Actually I found that it is working for high level fields as @mitar noted, but in my case it was like `stats.oneField` and `stats.*`, so sub-fields didn't got merged. Logically I believe it should behave in the same way for both top-level fields and sub-fields.

**Comment by juliomac** [comment] 2015-08-24 14:14
The problem on my example was something else. There was a silly bug on it. The second field now shows up.

After all, this example failed to reproduce the issue. Also tested with sub-documents and they also have shown up after second publication. I will have to rethink how to reproduce it or figure out if it was something else on my real app code.

I also checked @mitar observation and subscribed at ```onCreated``` and back directly at helpers. Couldn't see a difference as It worked in both cases.

I posted the updated example on repo.

**Comment by mohitag19** [comment] 2016-03-25 13:46
For anyone else landing here, I can confirm the top level fields are getting merged on subsequent subscriptions but not nested ones. Probably because of this - 

> The most important consideration is related to the way DDP, Meteor’s data loading protocol, communicates documents over the wire. The key thing to realize is that DDP sends changes to documents at the level of top-level document fields.

Quoting from [Meteor guide](http://guide.meteor.com/collections.html#schema-design)

**Comment by faizmh** [comment] 2016-06-22 07:24
My symptoms
1)i have a student list-all page where I would subscribe to some fields of student collection
2)once i select anyone student, it goes individual student page. Here I subscribe to all fields
3)Some fields remain surprisingly blank[BUG]
4)console.log of Student shows all fields
5)Note - Student is not reactive by design

My technical analysis - websocket inspection
T1) On student list, all students were getting added ("msg":addded) with subscribed fields
T2) On going to individual student page, Student subscription with all fields was triggering
T3) Server would respond back "msg":changed and the individual Student data is available on the page
T4) I also noticed, remaining students are being removed ("msg":removed) by the server
T5) In between i also see another "msg":changed . This contain fields which are not part of T3 , but some of them are part of T1

My troubeshooting
M1. I triedto timeout my single Student subscription, until, server removes  student-list subscription
and that worked. But I knew this was not a right solution
M2. I realized on T5, it had to do with nested projections

My final solution
In student list, i used nested projection. Once I removed the nested projection my issues were resovled.

Sequence of things
S1. in student list, i subscribe for list of students with {first_name:1, parent.name:1}
S2 in student page, i subscribe for {first_name,parent:1,address:1} // See how my subscribing for parent:1 and not parent.name:1 .... TADAAAA!!!!
S3. A "msg":changed with {address:data} is received
S4. A "msg":changed with {parent:data} is received

if in the above sequence of things, had i put {first_name:1, parent:1} in S1, then there would be no S4 

Summary
This had to do a lot on how nested projections are handled in meteor sync. 
There is an obvious element of network delay which can mess up things as well. 
I believe if I had autorun or reactive helpers, I may not have caught this problem either.
There isn't way to capture S4 unless you have reactive variables

Finally learned meteor well now

**Comment by sidzan** [comment] 2017-12-27 06:48
Any one has solution to this ? This is till happening !

**Comment by shadoath** [comment] 2021-03-29 16:54
This still is an issue as best I can tell. The [subscribe docs](https://docs.meteor.com/api/pubsub.html#Meteor-subscribe). Mention:

> Currently, when multiple subscriptions publish the same document only the top level fields are compared during the merge. This means that if the documents include different sub-fields of the same top level field, not all of them will be available on the client. We hope to lift this restriction in a future release.

Wonder how long this will be in place. Or if there are plans to allow upsert/merging.

**Comment by mitar** [comment] 2021-03-29 21:59
Yes, this is current trade-off between diffing on the server-side over bandwidth consumption. More diffing (deep diffing) is more CPU.
