### ISSUE TITLE
Initial compilation of already-minified JS files slow in `ecmascript`

### ISSUE THREAD

**Issue by IvanPortfolio** [meteor/meteor#7356] opened 2016-07-05 22:11 UTC
When I add static tinymce.min.js file to my lib subfolder in client folder build freezes four hours and is never ended. It stops on ecmascript package. 

My meteor version is 1.34.1 and OS is Ubuntu.
The size of library is ~300kb

**Comment by benjamn** [comment] 2016-07-05 22:40
Try renaming it to `tinymce.min.es5.js` to disable `ecmascript` compilation?

**Comment by IvanPortfolio** [comment] 2016-07-05 22:46
Thank you  very much.It really helped me. But this is still a bug of ecmascript package

**Comment by abernix** [comment] 2016-07-06 10:10
I reproduced this here: https://github.com/abernix/issue-7356-min-es5

I found that it did actually finish – it just didn't finish _quickly_ (it took 8 minutes).  Once the file was built, it was the same speed on additional rebuilds:

```sh
$ rm -rf .meteor/local/ # Make sure it's a clear build
$ time meteor build ../ --server http://localhost:3000/
meteor build ../ --server http://localhost:3000/  477.75s user 6.86s system 100% cpu 8:03.70 total
$ # Not fast, but did finish in 8 minutes, 4 seconds
$ mv lib/client/tinymce.min.js lib/client/tinymce.min.es5.js # Rename with .es5.js extension
$ rm -rf .meteor/local/ # Clean build
$ time meteor build ../ --server http://localhost:3000/
meteor build ../ --server http://localhost:3000/  45.42s user 4.78s system 106% cpu 47.122 total
$ # Much faster @ 47 seconds
$ mv lib/client/tinymce.min.es5.js lib/client/tinymce.min.js # Rename back to original name
$ rm -rf .meteor/local/ # Clean build
$ time meteor build ../ --server http://localhost:3000/
meteor build ../ --server http://localhost:3000/  475.73s user 6.75s system 100% cpu 8:00.37 total
$ # Back to 8-minute build time (so, reproducible)
$ # **NOT** Cleaning the build on purpose, to observe cache time...
$ time meteor build ../ --server http://localhost:3000/
meteor build ../ --server http://localhost:3000/  28.48s user 4.38s system 110% cpu 29.832 total
$ # Fast @ 29 seconds – so really just a problem with first time compilation.
```

So a performance related problem, but one that can be avoided.

**Comment by benjamn** [comment] 2016-07-06 13:24
This is likely something that would have to be improved in Babel itself, no?

**Comment by abernix** [comment] 2016-07-06 14:07
Yes, presumably.  I didn't have time to 100% confirm if it was `ecmascript` (and thus Babel, since that's pretty much all it does) or if it was just showing `ecmascript` as the last output in the shell – and perhaps it was `uglify` or something?

Also maybe it's possible to decide to skip it (on the Meteor side) based on some sort of criteria?

**Comment by abernix** [comment] 2016-07-06 16:21
This isn't the best way to make sure it's performing the same exact same task as `BabelCompiler` but a quick test on the command-line with `babel-cli` shows that Babel handles the minified file fine using the `meteor` preset:

```sh
$ time babel --presets meteor tinymce.min.js > /dev/null
[BABEL] Note: The code generator has deoptimised the styling of "src/tinymce.min.js" as it exceeds the max of "100KB".
4.39s user 0.31s system 107% cpu 4.368 total
```
...and it outputs just fine (despite the message, which I can avoid with `compact: false`)

**Comment by abernix** [comment] 2016-07-06 16:44
My previous update isn't accounting for whatever `require(`babylon`).parse` is doing to generate the AST and how Babel `.transformFromAst` behaves vs. `.transform` (which is what `babel-cli` uses), which could be a culprit, I suppose.

Anyhow, overall this is a pretty low priority as it likely affects very few, one time per file and the workaround is to simply rename the file.

**Comment by laosb** [comment] 2016-07-10 22:15
`.min.js` is skipped in minification, so renaming it to `tinymce.min.es5.js` may cause it be reminified. We should skip them in babel compiling too.

**Comment by laosb** [comment] 2016-08-09 04:26
*.min.js are now excluded from babel compiling. Closing.

**Closed by laosb** 2016-08-09 04:26 UTC
Labels: bug, confirmed, Impact:few, Project:Isobuild:Performance, Project:Tool, Severity:has-workaround
