### ISSUE TITLE
1.6.1: Uncaught (in promise) TypeError: Failed to resolve module specifier 'react'

### ISSUE THREAD

**Issue by s7dhansh** [meteor/meteor#9587] opened 2018-01-27 19:36 UTC
On upgrading to 1.6.1 from 1.6.0.1, the code

```
const [
		React,
		{render},
		{combineReducers, createStore, applyMiddleware},
		{Provider},
		{default: thunk},
	] = await Promise.all([
		import('react'),
		import('react-dom'),
		import('redux'),
		import('react-redux'),
		import('redux-thunk'),
	]);
```

causes the following error:

```
index.js:26 Uncaught (in promise) TypeError: Failed to resolve module specifier 'react'
    at main$ (http://localhost:4010/app/app.js?hash=b019f685a9c193aeb605e2469b36044433d75f7b:2653:52)
    at tryCatch (http://localhost:4010/packages/modules.js?hash=ae9f98c103a27d94caedeba5d4c7ef4c1a9479da:1136:40)
    at Generator.invoke [as _invoke] (http://localhost:4010/packages/modules.js?hash=ae9f98c103a27d94caedeba5d4c7ef4c1a9479da:1370:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:4010/packages/modules.js?hash=ae9f98c103a27d94caedeba5d4c7ef4c1a9479da:1188:21)
    at tryCatch (http://localhost:4010/packages/modules.js?hash=ae9f98c103a27d94caedeba5d4c7ef4c1a9479da:1136:40)
    at invoke (http://localhost:4010/packages/modules.js?hash=ae9f98c103a27d94caedeba5d4c7ef4c1a9479da:1226:20)
    at http://localhost:4010/packages/modules.js?hash=ae9f98c103a27d94caedeba5d4c7ef4c1a9479da:1269:11
    at new Promise (<anonymous>)
    at callInvokeWithMethodAndArg (http://localhost:4010/packages/modules.js?hash=ae9f98c103a27d94caedeba5d4c7ef4c1a9479da:1268:16)
    at AsyncIterator.enqueue [as _invoke] (http://localhost:4010/packages/modules.js?hash=ae9f98c103a27d94caedeba5d4c7ef4c1a9479da:1291:13)
```

Probably caused due to `@babel/runtime`. Can someone kindly confirm/help?

**Comment by benjamn** [comment] 2018-01-30 00:37
I'm afraid the only way to proceed here is for you to put together a small reproduction that demonstrates the problem.

**Comment by s7dhansh** [comment] 2018-01-30 14:25
Will do a reprod when I get some time. For now, removing `meteor` preset from `.babelrc` fixed it. I was using `babel-preset-meteor@^7.0.0-beta.38`. May be I was using a wrong version.

**Comment by benjamn** [comment] 2018-01-30 14:41
You don't need to include `babel-preset-meteor` in your `.babelrc` file, because it is always included automatically by Meteor. The `.babelrc` file is just for extra plugins that aren't in `babel-preset-meteor`.

**Comment by hwillson** [comment] 2018-01-30 17:51
Closing since this issue has been resolved.

**Closed by hwillson** 2018-01-30 17:51 UTC
