### ISSUE TITLE
Firefox client-side errors aren't helpful (compared to Chrome).

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6596] opened 2016-03-27 00:03 UTC
For example, here's an error I see in Firefox:

```
Exception in delivering result of invoking 'addPaymentSource': clickAddCardSubmit/</<@http://localhost:3000/app/app.js?hash=ddb4049aa0f8fcbda7e33505f4ea7577ab976446:16103:11
Meteor.bindEnvironment/<@http://localhost:3000/packages/meteor.js?hash=ec96c6f2d27fb027b17df77301967ce893b45963:1088:17
._maybeInvokeCallback@http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:3531:7
.receiveResult@http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:3551:5
._livedata_result@http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:4671:7
Connection/onMessage@http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:3359:7
._launchConnection/self.socket.onmessage/<@http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:2726:11
_.forEach@http://localhost:3000/packages/underscore.js?hash=8de51f9d86e95ae2ffee15a8db324a1decccba3e:139:7
._launchConnection/self.socket.onmessage@http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:2725:9
REventTarget.prototype.dispatchEvent@http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:165:9
SockJS.prototype._dispatchMessage@http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:1150:5
SockJS.prototype._didMessage@http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:1208:13
SockJS.websocket/that.ws.onmessage@http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:1355:9
```

In Firefox, the message about why the error happens is apparently completely missing. Also, the lines aren't clickable in order to navigate to those files.

In Chrome, the error shows the error reason properly (and the lines are clickable):

```
Exception in delivering result of invoking 'addPaymentSource': ReferenceError: refreshCards is not defined
    at http://localhost:3000/app/app.js?hash=ddb4049aa0f8fcbda7e33505f4ea7577ab976446:16103:11
    at ._callback (http://localhost:3000/packages/meteor.js?hash=ec96c6f2d27fb027b17df77301967ce893b45963:1088:22)
    at _.extend._maybeInvokeCallback (http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:3531:12)
    at _.extend.receiveResult (http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:3551:10)
    at _.extend._livedata_result (http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:4671:9)
    at onMessage (http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:3359:12)
    at http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:2726:11
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?hash=8de51f9d86e95ae2ffee15a8db324a1decccba3e:139:11)
    at self.socket.onmessage (http://localhost:3000/packages/ddp-client.js?hash=3bd962229011ceb88bc26f7adf751b510b111962:2725:11)
```

As you can see, Chome shows that `refreshCards is not defined`, but Firefox does not show that message. This makes it trickier to debug things in Firefox.

**Comment by stubailo** [comment] 2016-03-29 22:25
This is a duplicate of the following issue: https://github.com/meteor/meteor/issues/2232

There is some good discussion there.

**Closed by stubailo** 2016-03-29 22:25 UTC
