### ISSUE TITLE
Unintuitive include with Blaze

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4274] opened 2015-04-25 03:30 UTC
If I have a datacontext like this:

``` javascript
{
  render: function () { return Template.FooBar; },
  dataContext: { top: 42 }
}
```

And I try to render it using Blaze template it does not render:

``` handlebars
{{> this.render this.dataContext}}
```

From the syntax, one would assume that this would work. That one would call `render` on current data context, and then include it inside a `dataContext`. But no. Because this is internally converted to:

``` handlebars
{{#with this.dataContext}}
  {{> this.render}}
{{/with}}
```

`this.render` is tried to be resolved inside of `this.dataContext` where it does not exist.

**Comment by mitar** [comment] 2015-04-25 03:34
See reproduction [here](http://meteorpad.com/pad/LbwdhA39scJJ3totW/Meteor%20Issue%20#4274).

**Comment by stubailo** [comment] 2015-04-28 22:57
Yes, this is the way that template inclusions are implemented right now. This is the reason we have `Template.dynamic`. You could maybe define a template called "include" and do something like the following:

```
{{> include this}}
```

**Comment by hwillson** [comment] 2016-11-22 12:34
Since this functions as designed, I'll close this issue for now. @mitar - let me know if you think this should become a Blaze feature request, and I'll move it to the Blaze repo. Thanks!

**Closed by hwillson** 2016-11-22 12:34 UTC
Labels: Project:Blaze, Project:Blaze:Spacebars

**Comment by mitar** [comment] 2016-11-22 12:37
Thanks. I think it is good as it is.
