### ISSUE TITLE
Minifier - Galaxy - Chrome v38 error

### ISSUE THREAD

**Issue by flean** [meteor/meteor#9354] opened 2017-11-12 19:57 UTC
Meteor 1.6 creates this error under Chrome v38 (it's what WebOS 3 TVs use, no way to update)

```Uncaught TypeError: Identifier 'e' has already been declared a2fe8cc737a54f52d8fe54a52f1eebd8206a5337.js?meteor_js_resource=true:145(anonymous function) a2fe8cc737a54f52d8fe54a52f1eebd8206a5337.js?meteor_js_resource=true:145(anonymous function) a2fe8cc737a54f52d8fe54a52f1eebd8206a5337.js?meteor_js_resource=true:145(anonymous function) a2fe8cc737a54f52d8fe54a52f1eebd8206a5337.js?meteor_js_resource=true:145```

this is the line where it's getting stuck.

```!function(){var t=Package.meteor.Meteor,e=Package.meteor.global,n=Package.meteor.meteorEnv,i=Package["accounts-base"].Accounts,a=Package["twitter-oauth"].Twitter,o=Package.http.HTTP;(function(){!Package["accounts-ui"]||Package["service-configuration"]||Package.hasOwnProperty("twitter-config-ui")||console.warn("Note: You're using accounts-ui and accounts-twitter,\nbut didn't install the configuration UI for Twitter\nOAuth. You can install it with:\n\n    meteor add twitter-config-ui\n")}).call(this),function(){if(i.oauth.registerService("twitter"),t.isClient){const e=function(t,e){e||"function"!=typeof t||(e=t,t=null);var n=i.oauth.credentialRequestCompleteHandler(e);a.requestCredential(t,n)};i.registerClientLoginFunction("twitter",e),t.loginWithTwitter=function(){return i.applyLoginFunction("twitter",arguments)}}else{var e=_.map(a.whitelistedFields.concat(["id","screenName"]),function(t){return"services.twitter."+t});i.addAutopublishFields({forLoggedInUser:e,forOtherUsers:e})}}.call(this),"undefined"==typeof Package&&(Package={}),Package["accounts-twitter"]={}}();```

I'm almost sure this is a minifier issue but any solutions or suggestions on now to get this fixed? It only happens in production with Galaxy

**Comment by abernix** [comment] 2017-11-20 13:07
Thanks for reporting this, @flean.

Could you try the latest Meteor 1.6.1 (see #9274) and perform a staging environment test (since 1.6.1 is beta!) to see if the updates to [`uglify-es`](//npm.im/uglify-es) (the minifier in use by Meteor) solve this for your app? If this doesn't fix it, it would be incredibly helpful if you could put together a reproduction that exhibits this behavior.  It may take some time, and would require gutting parts of your application in order to narrow down the culprit, but it might be the best opportunity to get this looked at.

Thanks!

**Comment by flean** [comment] 2017-11-20 16:38
Thanks, I’ll setup this week and test. I resorted to removing the packages for now which worked.

**Comment by hwillson** [comment] 2017-11-28 20:19
Let us know if the comments https://github.com/meteor/meteor/issues/9354#issuecomment-345690262 helped - in the meantime, I'll close this for now. Thanks!

**Closed by hwillson** 2017-11-28 20:19 UTC
Labels: Project:Isobuild:Minifiers
