### ISSUE TITLE
unable to create app

### ISSUE THREAD

**Issue by heinhoang** [meteor/meteor#8521] opened 2017-03-26 00:59 UTC
- meteor version 1.4.3.2
- OS: Windows 10
I type this command `meteor create simple-todos` and get error:
```
C:\Users\myusername\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: Error: Could not install npm dependencies for test-packages: spawn C:\Users\myusername\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd ENOENT
    at Object.error (C:\tools\utils\buildmessage.js:430:11)
    at C:\tools\cli\default-npm-deps.js:32:20
    at C:\tools\utils\buildmessage.js:334:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:333:36
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.install (C:\tools\cli\default-npm-deps.js:27:27)
    at Command.func (C:\tools\cli\commands.js:747:36)
    at C:\tools\cli\main.js:1483:23
```

**Comment by abernix** [comment] 2017-03-27 09:06
I've tried to reproduce this with Windows 10 and have not been able to do so.  Any additional information you can provide would be helpful.  

For example, is this a new installation of Meteor or was it upgraded from a previous version?  After the command fails, what if you go into the `simple-todos` directory (which should have been created) and run `meteor npm install`?  What if you try creating a project with Meteor 1.4.2.7 and running `meteor npm install` manually inside?:

```sh
> meteor create --release 1.4.2.7 new-project
> cd new-project
> meteor npm install
```

**Comment by heinhoang** [comment] 2017-03-28 00:49
1. I made a new install, not from previous
2. I get error when run `meteor npm install`
```
'npm' is not a Meteor command. See 'meteor --help'.
```
3. Running `meteor create --release 1.4.2.7 new-project`
After awhile, I get this
```
{ [Error: EBUSY: resource busy or locked, unlink 'C:\Users\HEINHO~1\AppData\Local\Temp\mt-y1mpb9\npm\node_modules\sockjs\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\base.js']
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\Users\\HEINHO~1\\AppData\\Local\\Temp\\mt-y1mpb9\\npm\\node_modules\\sockjs\\node_modules\\faye-websocket\\node_modules\\websocket-driver\\lib\\websocket\\driver\\base.js' }
C:\Users\heinhoang\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: EBUSY: resource busy or locked, unlink 'C:\Users\HEINHO~1\AppData\Local\Temp\.tmpohl09v\autoupdate-1.2.11\package.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:932:18)
    at rimrafSync (C:\Users\heinhoang\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:295:17)
    at C:\Users\heinhoang\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\heinhoang\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\heinhoang\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at Function.rimrafSync [as sync] (C:\Users\heinhoang\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at Object.rm_recursive (C:\tools\fs\files.js:283:12)
    at Object.files.rename (C:\tools\fs\files.js:1684:13)
    at Object.files.extractTarGz (C:\tools\fs\files.js:753:9)
    at Object.exports._extractAndConvert (C:\tools\packaging\tropohouse.js:50:9)
    at C:\tools\packaging\tropohouse.js:505:42
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:502:24
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\heinhoang\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:469:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:613:18
    at C:\tools\utils\buildmessage.js:572:21
    at C:\Users\heinhoang\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:32:39
 => awaited here:
    at Promise.await (C:\Users\heinhoang\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:39:12)
    at Object.forkJoin (C:\tools\utils\buildmessage.js:604:6)
    at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:609:18)
    at C:\tools\project-context.js:776:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:775:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:774:13)
    at C:\tools\project-context.js:268:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:258:18)
    at C:\tools\project-context.js:250:12
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:249:13)
    at C:\tools\cli\commands.js:741:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:273:29)
    at Command.func (C:\tools\cli\commands.js:715:8)
    at C:\tools\cli\main.js:1483:23
```

**Comment by hwillson** [comment] 2017-04-10 20:06
Hi @heinhoang - just touching base on this. Are you still having this problem? What happens if you try with Meteor 1.4.4.1?

```
meteor create --release 1.4.4.1
```

**Comment by heinhoang** [comment] 2017-04-11 01:11
hi, thanks @hwillson, it works fine with version @1.4.4.1.

**Comment by hwillson** [comment] 2017-04-11 01:21
Great! 1.4.4.1 should be officially recommended soon (unless there are any major showstoppers encountered in the next little bit). I'll close this for now, but please post back if you notice this issue happening again, with 1.4.4.1 (or any future version). Thanks!

**Closed by hwillson** 2017-04-11 01:21 UTC

**Comment by icodehome** [comment] 2018-01-30 09:56
Great!

**Comment by ayoub1996-01** [comment] 2018-02-15 09:24
hello everyone !
i have the same error in my linux mint, i have fix it by fixing the git  ...
when i was trying  this commande ligne " meteor npm install " it said 

npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

so with this 3 steps i have fix the promblem and i have create my funy project with out error :

## _1__`npm install --save npm-git-install`

## _2__## In your pacakge.json 
add: 
{
  "scripts": {
    "install": "npm-git install"
  }
  "gitDependencies": {
    "private-package-name": "git@private.git.server:user/repo.git#revision",
    "public-package-name": "https://github.com/user/repo.git#revision"
  }
}

Obviously replace *-package-name and git URLs with values relevant to your project. URLs has to be in canonical form (i.e. one that you would provide to git clone on command line) - no fancy NPM shortcuts like user/repo or bitbucket:user/repo. If you want this, we are open for a PRs.

## _3__Then install your dependencies as usual:

 `npm install`

for more details visit this link : https://www.npmjs.com/package/npm-git-install
 
if anyone knows the relation between the git and my error explain me plz , because i don't know the git's effect on my project creation ...
