### ISSUE TITLE
Meteor does not resolve package dependencies correctly

### ISSUE THREAD

**Issue by RobinBuschmann** [meteor/meteor#4551] opened 2015-06-13 06:55 UTC
I'm using angular-meteor in my test project. It is implemented in a custom package. In the package.js of this package i've defined the dependency like this:

    api.use('urigo:angular', 'client');

As you can see, there is no explicit version specified, but meteor installs an old version of 'urigo:angular':

    urigo:angular@0.3.6 

The current version is 0.8.7. The project was created 2 days ago. So there was no existing version file with an old reference to urigo:angular@0.3.6. 

Here is my test repo: https://github.com/RobinBuschmann/meteor-example

https://github.com/Urigo/angular-meteor/issues/426

**Comment by stubailo** [comment] 2015-06-13 08:07
Meteor uses conservative dependencies. Since you did not specify a version of `urigo:angular` in your `package.js` file, Meteor assumes that it should work with any version, including the oldest one. If you would like to use a new version of Angular with your package, you should add that version to your `package.js` or to your app - this is working as intended.

At the very least, this is a duplicate of https://github.com/meteor/meteor/issues/4170

**Closed by stubailo** 2015-06-13 08:07 UTC
