### ISSUE TITLE
[1.3 beta 8] Error running template: Error: Meteor code must always run within a Fiber. 

### ISSUE THREAD

**Issue by fallenpeace** [meteor/meteor#6175] opened 2016-02-06 10:31 UTC
Havent been having issues with any of the updates until now. The project is basically a few routes and a few methods, using just react + mantra spec. Don't see the error point to any specific user created file so not sure how to approach this..

```
E20160206-02:22:58.071(-8) (webapp_server.js:716) Error running template: Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at Object.Tracker.autorun (packages/kadira:flow-router-ssr/server/plugins/ssr_data.js:51:29)
    at [object Object].Blaze.View.autorun (packages/blaze/view.js:209:1)
    at [object Object].<anonymous> (packages/blaze/builtins.js:157:1)
    at fireCallbacks (packages/blaze/view.js:279:1)
    at Object.Tracker.nonreactive (packages/tracker/tracker.js:589:1)
    at packages/blaze/view.js:276:1
    at Object.Blaze._withCurrentView (packages/blaze/view.js:538:1)
    at Object.Blaze._fireCallbacks (packages/blaze/view.js:275:1)

E20160206-02:22:58.224(-8) (webapp_server.js:716) Error running template: Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at Object.Tracker.autorun (packages/kadira:flow-router-ssr/server/plugins/ssr_data.js:51:29)
    at [object Object].Blaze.View.autorun (packages/blaze/view.js:209:1)
    at [object Object].<anonymous> (packages/blaze/builtins.js:157:1)
    at fireCallbacks (packages/blaze/view.js:279:1)
    at Object.Tracker.nonreactive (packages/tracker/tracker.js:589:1)
    at packages/blaze/view.js:276:1
    at Object.Blaze._withCurrentView (packages/blaze/view.js:538:1)
    at Object.Blaze._fireCallbacks (packages/blaze/view.js:275:1)

E20160206-02:22:58.229(-8) (webapp_server.js:716) Error running template: Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at Object.Tracker.autorun (packages/kadira:flow-router-ssr/server/plugins/ssr_data.js:51:29)
    at [object Object].Blaze.View.autorun (packages/blaze/view.js:209:1)
    at [object Object].<anonymous> (packages/blaze/builtins.js:157:1)
    at fireCallbacks (packages/blaze/view.js:279:1)
    at Object.Tracker.nonreactive (packages/tracker/tracker.js:589:1)
    at packages/blaze/view.js:276:1
    at Object.Blaze._withCurrentView (packages/blaze/view.js:538:1)
    at Object.Blaze._fireCallbacks (packages/blaze/view.js:275:1)
```

**Comment by huttonr** [comment] 2016-02-06 18:35
Appears to be a duplicate of https://github.com/meteor/meteor/issues/6170

**Comment by timothyarmes** [comment] 2016-02-09 10:32
@benjamn Is there any chance that this commit well be rolled into the next modules beta quite quickly? I haven't been able to compile my project since beta 5. Each time it gets a little further, and with beta 8 I'm getting this same error using FlowRouter SSR.

**Comment by avital** [comment] 2016-02-09 23:10
Closing since this is a dupe.

**Closed by avital** 2016-02-09 23:10 UTC

**Comment by avital** [comment] 2016-02-09 23:12
@timothyarmes It will probably be released in the next few days.
