### ISSUE TITLE
Spacebars parsing error

### ISSUE THREAD

**Issue by mquandalle** [meteor/meteor#3619] opened 2015-02-01 14:12 UTC
It seems that spacebars does not handle correctly inlined JavaScript scripts, for instance the following template:

```html
<body>
  <h1>Welcome to Meteor!</h1>
  <script>
  var hello = {
    world: "<textString>"
  };
  </script>
</body>
```

raises the following error:

```
spacebars-bug.html:7: Expected "textstring" end tag
   ...ng>"   };   </script>
```

A complete clon-able reproduction is available [here](https://github.com/mquandalle/spacebars-bug).

cc @acemtp who found the bug.

**Comment by PeppeL-G** [comment] 2015-02-01 15:36
That's not valid HTML, is it? I think `<textString>` should be interpreted as a tag, and the error message says that's a corresponding end tag is expected before `</script>` (this is a error occurred in the parsing phase, of course `<textString>` is also an invalid HTML tag, but that is discovered in a phase after parsing).

**Comment by mquandalle** [comment] 2015-02-03 17:40
@PeppeL-G I think you misread the code. `<textString>` shouldn't be interpreted as a HTML tag but as a simple string of text in a JavaScript variable. Spacebars already handles other similar cases — for instance `<textarea><textString></textarea>` works as expected.

**Comment by PeppeL-G** [comment] 2015-02-03 18:36
I'm sorry, I didn't now that it was valid to put tags inside `<script>` and `<textarea>` elements, but now I've done my reading, and I agree with you.

Sorry if I'm going off topic now (I'm curios! :P), but has this been the case for long? I'm quite convinced I've had trouble with this before (many years ago).

**Comment by dgreensp** [comment] 2015-03-03 22:47
We should fix this.

Closing as duplicate of #3797.

**Closed by dgreensp** 2015-03-03 22:47 UTC
Labels: Project:Blaze, Project:Blaze:Spacebars
