### ISSUE TITLE
Updating indirect dependencies not working

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#8488] opened 2017-03-14 22:47 UTC
When I run `meteor update`, it seems 3 indirect dependencies could be updated:
```
C:\Users\steph\Meteor\myProject>meteor update
This project is already at Meteor 1.4.3.2, the latest release.
Your top-level dependencies are at their latest compatible versions.

Newer versions of the following indirect dependencies are available:
 * aldeed:collection2-core 1.2.0 (2.0.0 is available)
 * aldeed:schema-deny 1.1.0 (2.0.0 is available)
 * aldeed:schema-index 1.1.1 (2.0.0 is available)
To update one or more of these packages, pass their names to
`meteor update`, or just run `meteor update --all-packages`.
```
But using `--all-packages`, as recommended, seems to have no effect:
```
C:\Users\steph\Meteor\myProject>meteor update --all-packages
This project is already at Meteor 1.4.3.2, the latest release.
Your top-level dependencies are at their latest compatible versions.

Newer versions of the following indirect dependencies are available:
 * aldeed:collection2-core 1.2.0 (2.0.0 is available)
 * aldeed:schema-deny 1.1.0 (2.0.0 is available)
 * aldeed:schema-index 1.1.1 (2.0.0 is available)
To update one or more of these packages, pass their names to
`meteor update`, or just run `meteor update --all-packages`.
```
And updating individual packages, as recommended, seems to have no effect either:
```
C:\Users\steph\Meteor\myProject>meteor update aldeed:schema-deny
The specified packages are at their latest compatible versions.

C:\Users\steph\Meteor\myProject>meteor update
This project is already at Meteor 1.4.3.2, the latest release.
Your top-level dependencies are at their latest compatible versions.

Newer versions of the following indirect dependencies are available:
 * aldeed:collection2-core 1.2.0 (2.0.0 is available)
 * aldeed:schema-deny 1.1.0 (2.0.0 is available)
 * aldeed:schema-index 1.1.1 (2.0.0 is available)
To update one or more of these packages, pass their names to
`meteor update`, or just run `meteor update --all-packages`.
```
Meteor version: 1.4.3.2
Environment: Windows 7

**Comment by abernix** [comment] 2017-03-15 09:25
Sorry for the confusion here.  This isn't actually a Windows bug but rather a text bug – see #5270.  We improved the CLI `--help` text about this (in https://github.com/meteor/meteor/pull/8431) but we still need to discuss the exact logic for this message.

Essentially, there are _newer_ versions of those three `aldeed` packages, however, they are not compatible with your current project based on their version constraints.  You can find out exactly which existing packages are constraining the new packages by explicitly `meteor add`-ing the newer versions.  For example:

    meteor add aldeed:schema-deny@2.0.0

Closing this as a duplicate of the above issue, but thank you for filing this, and happy to discuss further.

**Closed by abernix** 2017-03-15 09:25 UTC

**Comment by steph643** [comment] 2017-03-15 10:35
Understood, thanks.
