### ISSUE TITLE
Unable to start meteor on port other than 3000

### ISSUE THREAD

**Issue by gooor** [meteor/meteor#7941] opened 2016-10-20 12:52 UTC
On version 1.4.1.2 running `meteor` works ok, but `meteor --port 4000` hangs on `Starting your app`

Message to Meteor team:
Guys COME ON! We're wasting too much time on every minor meteor upgrade. This is unfortunately last project on meteor, it's fast to start but nightmare when goes a bit bigger (still 50 js files less than 100 lines each is not so big) and when going to production, it build very slow.

Edit:
I've did `meteor reset` and it worked. But still there's something wrong with that - why it did work on 3000 but not on 4000? Also why meteor reset worked?

**Comment by laosb** [comment] 2016-10-20 22:22
Meteor 1.4.2 is on its way and it has a improved build speed. See #7668.

I don't know, but if `meteor rest` did make it for you, there shouldn't be any problem. Sorry!

**Comment by abernix** [comment] 2016-10-21 07:46
Thanks for filing this issue.

This was a known bug (see #7563) caused by a major upgrade to Mongo in Meteor 1.4 (namely because of the change from MMAPv1 to WiredTiger) and is fixed in Meteor 1.4.2 (now a release candidate).  Tests were also added to ensure the same bug doesn't surface again.  You can also avoid this bug by running Meteor on the same port that it was originally started on.

Please help test the latest release candidate which fixes this, but additionally was focused on speed improvements.  As many users as possible are desired for release candidate and beta releases to help catch unintended bugs like this one before they get released!  See #7668 for lots of exciting changes and information on how to try it out.

Closing as duplicate but this is fixed in `1.4.2-rc.1` now!

**Closed by abernix** 2016-10-21 07:46 UTC
Labels: bug, confirmed, fixed

**Comment by benjamn** [comment] 2016-10-21 15:37
The fix for this issue will very likely be included in 1.4.1.3 as well: https://github.com/meteor/meteor/pull/7943
