### ISSUE TITLE
Meteor 1.6 not building in XCode due to cordova-plugin-console

### ISSUE THREAD

**Issue by tdotholla** [meteor/meteor#9300] opened 2017-11-04 14:52 UTC
i'm running Meteor 1.6 and trying to build to xCode; 
seeing an error exactly as [this StackOverflow Post](https://stackoverflow.com/questions/46633797/build-cordova-meteor-ionic-for-ios-duplicate-symbol-objc-class-cdvlogger): 

after digging it's caused due to Cordova 4.5+ incorporating `cordova-plugin-console`; so building with xCode is causing duplicate calls to certain classes. 

we can resolve by removing the classes after the build; but every time i build it gets placed back. 

How do we remove the dependency from meteor permanently? 

i've already tried:
- `meteor remove cordova:cordova-plugin-console` to no avail; says no such dependency exists in my project.
- `meteor remove-platform ios` and re-added it; to no avail. this is a piece of the log when i build again: 

```%% Install complete for cordova-plugin-meteor-webapp on ios.
%% Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-meteor-webapp on ios platform only.
%% Executing script found in plugin cordova-plugin-meteor-webapp for hook "after_plugin_install": plugins/cordova-plugin-meteor-webapp/scripts/iosAddBridgingHeader.js
%% Resolving module name for fs => fs
%% Resolving module name for path => path
%% Resolving module name for cordova-lib/src/cordova/util.js => ../cordova/util.js
%% Resolving module name for cordova-common => cordova-common
%% No scripts found for hook "after_plugin_add".
Adding plugin cordova-plugin-console@1.0.7 to Cordova project
%% No scripts found for hook "before_plugin_add".
%% Calling plugman.fetch on plugin "cordova-plugin-console@1.0.7"
%% Fetching plugin "cordova-plugin-console@1.0.7" via npm
npm WARN invalid config loglevel="notice"    [========                 ] 30% 163.9s
npm WARN deprecated cordova-plugin-console@1.0.7: This plugin has been deprecated since it is now included in the latest versions of cordova-ios
%% Copying plugin "/Users/tdotholla/.cordova/lib/npm_cache/cordova-plugin-console/1.0.7/package" => "/Users/tdotholla/Sites/thisapp/app//.meteor/local/cordova-build/plugins/cordova-plugin-console"
%% Calling plugman.install on plugin "/Users/tdotholla/Sites/thisapp/app/.meteor/local/cordova-build/plugins/cordova-plugin-console" for platform "ios
%% Installing "cordova-plugin-console" for ios
%% Running command: /Users/tdotholla/Sites/thisapp/app/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Command finished with error code 0: /Users/tdotholla/Sites/thisapp/app/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-console on ios platform only.
%% No scripts found for hook "before_plugin_install".
%% Install start for "cordova-plugin-console" on ios.
%% Beginning processing of action stack for ios project...
%% Action stack processing complete.
%% Install complete for cordova-plugin-console on ios.
%% Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-console on ios platform only.
%% No scripts found for hook "after_plugin_install".
%% No scripts found for hook "after_plugin_add".
Adding plugin cordova-plugin-statusbar@2.2.3 to Cordova project
%% No scripts found for hook "before_plugin_add".
%% Calling plugman.fetch on plugin "cordova-plugin-statusbar@2.2.3"
%% Fetching plugin "cordova-plugin-statusbar@2.2.3" via npm
%% Copying plugin "/Users/tdotholla/.cordova/lib/npm_cache/cordova-plugin-statusbar/2.2.3/package" => "/Users/tdotholla/Sites/thisapp/app/.meteor/local/cordova-build/plugins/cordova-plugin-statusbar"
%% Calling plugman.install on plugin "/Users/tdotholla/Sites/thisapp/app/.meteor/local/cordova-build/plugins/cordova-plugin-statusbar" for platform "ios
%% Installing "cordova-plugin-statusbar" for ios
%% Running command: /Users/tdotholla/Sites/thisapp/app/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Command finished with error code 0: /Users/tdotholla/Sites/thisapp/app/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-statusbar on ios platform only.
%% No scripts found for hook "before_plugin_install".
%% Install start for "cordova-plugin-statusbar" on ios.
%% Beginning processing of action stack for ios project...
%% Action stack processing complete.
%% Install complete for cordova-plugin-statusbar on ios.
%% Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-statusbar on ios platform only.
%% No scripts found for hook "after_plugin_install".
%% No scripts found for hook "after_plugin_add".
```

**Comment by skirunman** [comment] 2017-11-04 21:04
We have no problem building for iOS with Meteor 1.6 with Xcode 9. My suggestion, if you have not done this already, is to clean everything up and try to rebuild so:
``` bash
$ rm -r /yourapp/.meteor/local
$ rm -r  /yourapp/node_modules
$ meteor remove-platform ios
$ meteor reset
$ rm -r /yourhome/.cordova # optional to remove plugin cache
```
edit ` /yourapp/.meteor/cordova-plugins` and remove any duplications of plugins already used by Meteor. `/yourapp/.meteor/packages` should include `mobile-experience` and probably `launch-screen`.  Then add stuff back and rebuild:
``` bash
$ meteor add-platform ios
$ meteor npm install
$ meteor run ios-device # or however you build
```

I just checked our `.cordova/npm_cache` and Meteor Cordova does not seem to be installing cordova-plugin-console` by default.

If that does not work I guess you can search through your plugin's `plugin.xml` files for other [Cordova plugin dependencies](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#dependency).

There is also this PR https://github.com/meteor/meteor/pull/9213 where you can see that `cordova-plugin-console` is being [deprecated](https://cordova.apache.org/news/2017/09/22/plugins-release.html).

**Comment by btafel** [comment] 2017-11-05 16:21
I 'fixed' it by manually removing both cordova-plugin-console/CDVLogger.m and cordova-plugin-console/CDVLogger.h from .meteor/local/cordova-build/platforms/ios/<your project>.xcodeproj/<your project>.pbxproj file

**Comment by hwillson** [comment] 2017-11-07 17:38
Based on the comments in https://github.com/meteor/meteor/issues/9300#issuecomment-341929733 and https://github.com/meteor/meteor/issues/9300#issuecomment-341985150 (thanks @skirunman and @btafel), this doesn't appear to be a Meteor issue (or at least, not a common one). If the suggested fixes don't work, please post back with a small runnable reproduction demonstrating this issue. Closing for now - thanks!

**Closed by hwillson** 2017-11-07 17:38 UTC

**Comment by tdotholla** [comment] 2017-11-07 18:54
No problem! thanks @btafel and @skirunman. 
I ended up doing all of the steps above and `cordova-plugin-console` installed itself again. 

when i removed it from `.meteor/local/cordova-plugins` and tried to build i got an error stating that the plugin could not be referenced from a config.xml file. 

I did some hunting and it looked to be coming from the `meteor-tool` but that doesn't sound right...

so i'm doing the last bit of what @skirunman suggested and sifting through all of my node modules. but i also don't see why an NPM module would reference and force a cordova plugin to install. 

I only have one plugin installed other than defaults: `cordova-plugin-googlemaps` so when i get home today i'll remove it and try it all again. 

Much appreciating the help.

**Comment by tdotholla** [comment] 2017-11-09 23:30
This is still occuring... it's maddening...
just updated XCode to 9.1 
i remove everything and npm cache and then i get this in my `.meteor/local/build/star.json`
but i don't know what builds star.json. 

Also i see `cordova-plugin-console` referenced in `.meteor/local/cordova-build/plugins/cordova-plugin-inappbrowser/RELEASENOTES.md` but i can't remove that plugin using `meteor remove cordova:cordova-plugin-inappbrowser`

```
{
  "format": "site-archive-pre1",
  "builtBy": "Meteor METEOR@1.6",
  "programs": [
    {
      "name": "web.browser",
      "arch": "web.browser",
      "path": "programs/web.browser/program.json"
    },
    {
      "name": "web.cordova",
      "arch": "web.cordova",
      "path": "programs/web.cordova/program.json",
      "cordovaDependencies": {
        "cordova-plugin-whitelist": "1.3.2",
        "cordova-plugin-wkwebview-engine": "1.1.3",
        "cordova-plugin-meteor-webapp": "1.4.2",
        "cordova-plugin-console": "1.0.7",
        "cordova-plugin-statusbar": "2.2.1",
        "cordova-plugin-splashscreen": "4.0.1",
        "cordova-plugin-inappbrowser": "1.7.1",
        "cordova-plugin-googleplus": "https://github.com/meteor/cordova-plugin-googleplus.git#3095abe327e710ab04059ae9d3521bd4037c5a37",
        "cordova-plugin-geolocation": "2.1.0"
      }
    },
    {
      "name": "server",
      "arch": "os",
      "path": "programs/server/boot.js"
    }
  ],
  "meteorRelease": "METEOR@1.6",
  "nodeVersion": "8.8.1",
  "npmVersion": "5.4.2"
}
```

**Comment by skirunman** [comment] 2017-11-10 01:32
@tdotholla That sounds very frustrating. 

I quickly created a Meteor test app and ran it with the iOS simulator. I'm on MacOS 10.12.6, Xcode 9 and Meteor 1.6.

```bash
$ meteor create testApp
$ meteor add-platform ios
$ meteor npm install
$ meteor run ios
```
Besides `cordova-ios` only 5 other plugins are installed and built into the app:
`cordova-plugin-statusbar, cordova-plugin-meteor-webapp, cordova-plugin-whitelist, cordova-plugin-splashscreen, cordova-plugin-wkwebview-engine`

This would make me guess you have another cordova plugin dependency that is pulling in `cordova-plugin-console`.

What's in `yourapp/.meteor/local/cordova-build/plugins/ios.json`?

My test app's looks like:

```
{
    "prepare_queue": {
        "installed": [],
        "uninstalled": []
    },
    "config_munge": {
        "files": {}
    },
    "installed_plugins": {
        "cordova-plugin-whitelist": {
            "PACKAGE_NAME": "com.idnxeoi6gir6e.bsa5e00o2cyq"
        },
        "cordova-plugin-wkwebview-engine": {
            "PACKAGE_NAME": "com.idnxeoi6gir6e.bsa5e00o2cyq"
        },
        "cordova-plugin-meteor-webapp": {
            "PACKAGE_NAME": "com.idnxeoi6gir6e.bsa5e00o2cyq"
        },
        "cordova-plugin-statusbar": {
            "PACKAGE_NAME": "com.idnxeoi6gir6e.bsa5e00o2cyq"
        },
        "cordova-plugin-splashscreen": {
            "PACKAGE_NAME": "com.idnxeoi6gir6e.bsa5e00o2cyq"
        }
    },
    "dependent_plugins": {}
}
```

**Comment by skirunman** [comment] 2017-11-10 01:33
Just for completeness `testApp/.meteor/local/build/star.json`

```
{
  "format": "site-archive-pre1",
  "builtBy": "Meteor METEOR@1.6",
  "programs": [
    {
      "name": "web.browser",
      "arch": "web.browser",
      "path": "programs/web.browser/program.json"
    },
    {
      "name": "web.cordova",
      "arch": "web.cordova",
      "path": "programs/web.cordova/program.json",
      "cordovaDependencies": {
        "cordova-plugin-whitelist": "1.3.2",
        "cordova-plugin-wkwebview-engine": "1.1.3",
        "cordova-plugin-meteor-webapp": "1.4.2",
        "cordova-plugin-statusbar": "2.2.1",
        "cordova-plugin-splashscreen": "4.0.1"
      }
    },
    {
      "name": "server",
      "arch": "os",
      "path": "programs/server/boot.js"
    }
  ],
  "meteorRelease": "METEOR@1.6",
  "nodeVersion": "8.8.1",
  "npmVersion": "5.4.2"
}
```

**Comment by tdotholla** [comment] 2017-11-10 13:49
@skirunman  i totally appreciate all of this! even as it's ending up as a local issue i really appreciate the help. 

my `/.meteor/local/cordova-build/plugins/ios.json` file: 

```
{
    "prepare_queue": {
        "installed": [],
        "uninstalled": []
    },
    "config_munge": {
        "files": {}
    },
    "installed_plugins": {
        "cordova-plugin-whitelist": {
            "PACKAGE_NAME": "com.Mobbapp"
        },
        "cordova-plugin-wkwebview-engine": {
            "PACKAGE_NAME": "com.Mobbapp"
        },
        "cordova-plugin-meteor-webapp": {
            "PACKAGE_NAME": "com.Mobbapp"
        },
        "cordova-plugin-console": {
            "PACKAGE_NAME": "com.Mobbapp"
        },
        "cordova-plugin-statusbar": {
            "PACKAGE_NAME": "com.Mobbapp"
        },
        "cordova-plugin-splashscreen": {
            "PACKAGE_NAME": "com.Mobbapp"
        },
        "cordova-plugin-inappbrowser": {
            "PACKAGE_NAME": "com.Mobbapp"
        },
        "cordova-plugin-googleplus": {
            "REVERSED_CLIENT_ID": "com.googleusercontent.apps.123456789987654321",
            "PACKAGE_NAME": "com.Mobbapp"
        },
        "cordova-plugin-geolocation": {
            "GEOLOCATION_USAGE_DESCRIPTION": " ",
            "PACKAGE_NAME": "com.Mobbapp"
        }
    },
    "dependent_plugins": {
        "cordova-plugin-compat": {
            "PACKAGE_NAME": "com.Mobbapp"
        }
    }
}
```
so of course immediately i notice the `cordova-plugin-geolocation` and `cordova-plugin-googleplus` but i didn't add those... and i can't remove them by using `meteor remove cordova:cordova-plugin-geolocation`...
So i'll run through my meteor packages again, one of them is clearly adding cordova dependencies...

OK this should be the last assistance i need, it's clearly local and i just need to hunt it down.
