### ISSUE TITLE
1.7-beta.23 Iron Router no longer functional

### ISSUE THREAD

**Issue by jeffreyflynt** [meteor/meteor#9830] opened 2018-04-20 12:46 UTC
Environment: Ubuntu 17.10
Iron Router: 1.1.2

I have a project that uses Iron Router.  With the following change (DEPS being removed - Commit Modernize Tracker package), Iron Router doesn't work anymore as it will throw a DEPS not defined error.  

To get around this, I copied deprecated.js into tracker and added the necessary parameters in the (3) json files. (os.json, web.browser.json, web.browser.legacy.json).  

Depreceated.js
```
// Deprecated functions.

// These functions used to be on the Meteor object (and worked slightly
// differently).
// XXX COMPAT WITH 0.5.7
Meteor.flush = Tracker.flush;
Meteor.autorun = Tracker.autorun;

// We used to require a special "autosubscribe" call to reactively subscribe to
// things. Now, it works with autorun.
// XXX COMPAT WITH 0.5.4
Meteor.autosubscribe = Tracker.autorun;

// This Tracker API briefly existed in 0.5.8 and 0.5.9
// XXX COMPAT WITH 0.5.9
Tracker.depend = function (d) {
  return d.depend();
};

Deps = Tracker;
```
Json Files (Added)
```
{
      "name": "Deps",
      "testOnly": false
    }
```

&

```
{
      "type": "source",
      "extension": "js",
      "file": "os/deprecated.js",
      "length": 543,
      "offset": 0,
      "usesDefaultSourceProcessor": true,
      "path": "deprecated.js",
      "hash": "e6bc5717d7b2d73d327808fbd89fc4687a153b56",
      "fileOptions": {}
    }
```

Until I can move a few projects over to a different router, is this workaround the best option, or is there a flag one could use instead of doing it the manual way?

**Comment by abernix** [comment] 2018-04-20 12:51
What was the last version of Meteor that you used where Iron Router _did_ work?

**Comment by jeffreyflynt** [comment] 2018-04-20 12:54
It would have been: 1.6.2-beta.1

**Comment by abernix** [comment] 2018-04-20 13:01
It's been a while since I've worked with Iron Router (so I apologize for the ask here, but): Could you provide a basic reproduction application that demonstrates the problem?

**Comment by hwillson** [comment] 2018-04-20 14:31
Hi @jeffreyflynt - unless you can get a PR accepted with `ironrouter` (doubtful), your best bet is to either do something along the lines of what you're doing, or fork and update `ironrouter` yourself (to remove `Deps` use).

That being said, there is an easier way to accomplish what you're doing. You can copy the `tracker` package into a `packages` directory in your app, then modify it how you see fit. This way you can add back in the removed deprecated source, and everything will be available to your app automatically. To help show this I've submitted a PR to your repro.

There isn't much we can do with regards to ensuring legacy 3rd party packages stay up to date with Meteor core changes. Closing for now - thanks!

**Closed by hwillson** 2018-04-20 14:31 UTC
