### ISSUE TITLE
[bug] Error publishing, so package exists on Atmosphere, but apps not able to use it.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5735] opened 2015-12-01 03:28 UTC
I tried publishing a package, and it errored like this:

```
> meteor publish

/home/trusktr/.meteor/packages/meteor-tool/.1.1.10.17l30qr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
TypeError: Cannot call method 'toString' of undefined
    at uploadFile (/tools/packaging/package-client.js:329:66)
    at /tools/packaging/package-client.js:415:5
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at publishBuiltPackage (/tools/packaging/package-client.js:414:16)
    at Object.exports.publishPackage (/tools/packaging/package-client.js:800:7)
    at /tools/cli/commands-packages.js:432:21
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.main.captureAndExit (/tools/cli/main.js:268:29)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:428:8)
    at /tools/cli/main.js:1378:23
```

Now, when I try to use that version of `rocket:module` (which is 0.14.1) then the app complains like this:

```
> meteor -p 3006
[[[[[ ~/src/MetaEnterprises+whitespace ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While checking for rocket:module@0.14.1:
   error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

=> Your application has errors. Waiting for file change.
```

So, something happened during publish where Meteor/Atmosphere thinks the package is published, but it is not usable.

To work around the problem, I simply bumped the version to 0.14.2 and ran `meteor publish` again. It inexplicably worked this time.

**Comment by trusktr** [comment] 2015-12-01 06:07
It just happened to me again while trying to publish [`rocket:module` at 0.15.1](https://github.com/meteor-rocket/module/tree/v0.15.1), so I bumped to 0.15.2 inside of package.js and it worked.

**Comment by rdickert** [comment] 2015-12-01 22:51
Thanks for reporting this. I think @stubailo may have some ideas here.

**Comment by stubailo** [comment] 2015-12-02 03:37
@trusktr - I think you might be able to use `publish --existing-version` to re-publish on top of the same version number if the failure happens again. It's pretty hard to tell what the underlying issue is based on that error trace, though. Is there a way to reproduce it consistently?

**Comment by trusktr** [comment] 2015-12-02 04:27
Thanks for the tip, I'll try that next time. It seems to happen randomly;
I've no idea how to reproduce.

/#!/JoePea

**Comment by hwillson** [comment] 2017-01-20 13:06
The solution outlined in https://github.com/meteor/meteor/issues/5735#issuecomment-161171250 should address this. Due to the low recent activity on this issue, I'll close it for now. Happy to re-open if `publish --existing-version` doesn't work. Thanks for reporting this issue originally!

**Closed by hwillson** 2017-01-20 13:06 UTC
Labels: Project:Isobuild
