### ISSUE TITLE
[suggestion] Better error reporting on the client side.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4890] opened 2015-08-06 01:53 UTC
I see errors like this which are a pain to track:

```
Exception from Tracker afterFlush function:        debug.js:41
ReferenceError: Cards is not defined               debug.js:41
```

Errors of this form, from Tracker afterFlush, are always from line "debug.js:41", which is completely not helpful.

In the meantime, I'll keep laboriously hunting and hunting for the source of the error.

**Comment by rclai** [comment] 2015-08-06 11:57
I also suffer from this.

**Comment by Sanjo** [comment] 2015-08-06 14:17
Reproduce? I get this:

![bildschirmfoto vom 2015-08-06 16 17 24](https://cloud.githubusercontent.com/assets/727955/9113767/ac58b4fe-3c56-11e5-841f-cfea12f445a3.png)

So I see the stack trace.

**Comment by trusktr** [comment] 2015-08-07 04:13
Interesting. It seems to have a stack trace only sometimes:

<img width="512" alt="screen shot 2015-08-06 at 9 12 55 pm" src="https://cloud.githubusercontent.com/assets/297678/9128598/0a2585f2-3c80-11e5-9cc9-8fe380f54943.png">

**Comment by rclai** [comment] 2015-08-07 10:30
It's because @trusktr is using Blaze and @Sanjo is using React right?

It seems like React has better stack traces from what I see.

**Comment by Sanjo** [comment] 2015-08-07 12:59
When I use the starter app (`meteor create stack-trace-autorun`).

And use my reproduce trigger code:

```js
if (Meteor.isClient) {
  Tracker.autorun(function () {
    if (Session.get('throw')) {
      Cards.foo();
    }
  });
}
```

And trigger it with `Session.set('throw', true)`, then I get also the stack trace:

```js
Exception from Tracker recompute function:      debug.js:41
ReferenceError: Cards is not defined
    at stack-trace-autorun.js?087898c695bca84a46fc4ec3a4cad37d8878b275:5
    at Tracker.Computation._compute (tracker.js:294)
    at Tracker.Computation._recompute (tracker.js:313)
    at Object.Tracker._runFlush (tracker.js:452)
    at onGlobalMessage (setimmediate.js:102)
```

I use Google Chrome 44.

So still no reproduce :/

**Comment by rclai** [comment] 2015-08-07 13:04
I think it needs to be in the context of using Blaze. I'll see what I can do.

**Comment by stubailo** [comment] 2015-08-11 22:36
Yeah we definitely would need a reproduction to fix this. @trusktr when does it happen for you? Can you post an app where it happens here?

**Comment by Firfi** [comment] 2015-10-23 09:54
I found that can reproduce it with some older version of Meteor and packages. I'm trying to reproduce same issue with new application with same packages (but never versions), no 'luck' so far.

**Comment by Firfi** [comment] 2015-10-23 11:22
Issue is meteorhacks:kadira package _debug function overwrite. It removes stack trace, leaving only error message. Related bug is https://github.com/meteorhacks/kadira/issues/193

Reproduced here https://github.com/Firfi/meteor-tracker-kadira-bug-reproduction

**Comment by Firfi** [comment] 2015-10-28 12:02
It is fixed in Kadira.

**Comment by stubailo** [comment] 2015-10-28 16:34
@Firfi thanks for checking that out! Any luck reproducing it without kadira?

**Comment by Firfi** [comment] 2015-10-28 16:56
No luck reproducing it without.

**Comment by stubailo** [comment] 2015-10-28 17:01
OK I see no reproductions after 3 people tried, going to close it then.

**Closed by stubailo** 2015-10-28 17:01 UTC
Labels: needs-repro, Project:Tracker
