### ISSUE TITLE
METEOR_SETTINGS environment variable does not get set into Meteor.settings

### ISSUE THREAD

**Issue by jon617** [meteor/meteor#8455] opened 2017-03-05 16:06 UTC
Version: Meteor 1.4.2.7
OS: CentOS Linux 6.8 64-bit

Problem: METEOR_SETTINGS environment variable containing valid JSON should get loaded into the Meteor.settings server variable when running "meteor run" or when starting the app with Node.  Does not happen.  This feature should work, as per the documentation: https://docs.meteor.com/api/core.html#Meteor-settings

To reproduce:

In the source code, in `/server/main.js` add:

    import { Meteor } from 'meteor/meteor';
    console.log( Meteor.settings );

Run meteor with something similar to this (all on one line):
    `METEOR_SETTINGS='{ "public": { "SITE_URL_HTTP": "http", "SITE_URL_SUFFIX": "domain.com" }, "captchaServerKey": "abc123", "sikka": { "rateLimits": { "perIp": 30 }, "times": { "blockIpFor": 300000, "humanLivesUpto": 3600000 }, "captcha": { "siteKey": "abc123", "secret": "zxcvbn" } } }' MONGO_URL=mongodb://192.168.0.1/myname MAIL_URL=smtp://localhost:25 /usr/local/bin/meteor -p 0.0.0.0:3000`

When it runs, the Meteor.settings is empty.  The `console.log` put into `server/main.js` shows it's empty.

I created my own temporary fix which works.  First, I renamed the environment variable from `METEOR_SETTINGS` to `METEORSETTINGS` (removing the underscore) in the above commandline, then in the source code `/server/main.js`:

    import { Meteor } from 'meteor/meteor';
    try {
      Meteor.settings = JSON.parse( process.env.METEORSETTINGS );
    } catch (e) {
      throw new Error("METEORSETTINGS is not valid JSON: " + process.env.METEORSETTINGS);
    }

This temporary fix does not help with Meteor modules (downloaded from AtmosphereJS) which look for Meteor.settings, since Meteor modules load before `/server/main.js` populates Meteor.settings.

Notes.  I tested this when running meteor with the `meteor` commandline, and by doing a `meteor build` and running with `meteor node main.js`.

**Comment by abernix** [comment] 2017-03-06 12:47
> This feature should work, as per the documentation: https://docs.meteor.com/api/core.html#Meteor-settings

This feature is working as documented and the way you explain it above contradicts the documentation.  [The link you provided](https://docs.meteor.com/api/core.html#Meteor-settings) states that you should be using `--settings` when using `meteor run` (`run` is an optional keyword, and is the default):

> `Meteor.settings` contains deployment-specific configuration options. You can initialize settings by passing the `--settings` option (which takes the name of a file containing JSON data) to `meteor run` or `meteor deploy`. When running your server directly (e.g. from a bundle), you **instead** specify settings by putting the JSON directly into the `METEOR_SETTINGS` environment variable.

(emphasis mine)

So, in other words: in development (when using the `meteor`), you need to use the `--settings file.json` option and in production (a bundle) you need to use `METEOR_SETTINGS`.  **This is to allow reactivity in development.**  Changes to environment variables cannot be detected (nor could you actually change them unless you were the process itself), but a change to `settings.json` can be detected when the file is changed (i.e. when you save the file in your editor).

When you run `meteor build` you generate a Node.js bundle which can be run directly with `node`.  When using this bundle, the `METEOR_SETTINGS` environment variable **must** be used (this is the part the emphasis above is referring to).  `meteor node` is simply a wrapper for `node` which ensures the correct version of Node.js is used – it doesn't do anything fancy with `METEOR_SETTINGS`.

I've opened a PR to hopefully make this more clear and avoid confusion in the future.

**Comment by abernix** [comment] 2017-03-08 15:13
Closing as this is working as intended (unless you can demonstrate a bug in what I've explained!).  The PR should help make this more clear and remove confusion in the future.  Thanks!

**Closed by abernix** 2017-03-08 15:13 UTC
