### ISSUE TITLE
copy package from one owner to another - keep stars and stats

### ISSUE THREAD

**Issue by bevanhunt** [meteor/meteor#5002] opened 2015-08-20 15:20 UTC
Hi MDG,

I need to transfer a package bevanhunt:leaflet to camelot:leaflet. From Meteor developer to Meteor developer organization. I need to do this as I am adding contributors. The old one needs to stick around for legacy support but be unlisted. How do I do all this? I don't want to lose the stars and download stats.

Cheers.

**Comment by mizzao** [comment] 2015-08-21 22:21
#2392 contains an extensive discussion of how we might accomplish package renaming.

I think we should do it the way GitHub does it for repos, but that isn't implemented yet.

**Comment by bevanhunt** [comment] 2015-08-22 09:26
@mizzao - this ticket is just to change a database value in their backend.

**Comment by sjmcdowall** [comment] 2015-08-22 12:36
Isn't this better for contact@meteor.com instead of a bug tracking system? This is for the programming framework not meteor.com itself.

**Comment by mizzao** [comment] 2015-08-22 17:19
@bevanhunt yes, you just want one thing changed, but so do a lot of other people, and it would be a lot better to have a system to do that :)

**Comment by bevanhunt** [comment] 2015-08-22 17:23
@sjmcdowall - MDG bought Percolate and owns Atmosphere now. It is a missing feature to not allow transferring as @mizzao points out. I will email MDG as well - thanks.

@mizzao - agreed :)

**Comment by mizzao** [comment] 2015-08-22 17:33
Oh - that's news to me. Wonderful!

**Comment by glasser** [comment] 2015-08-25 21:09
As @mizzao said, this is a duplicate of #2392.

**Closed by glasser** 2015-08-25 21:09 UTC
