### ISSUE TITLE
Windows 7: Sorry, this OS is not supported.

### ISSUE THREAD

**Issue by DavidAPowers** [meteor/meteor#6221] opened 2016-02-11 22:14 UTC
Steps to replicate
1. Install Meteor from https://www.meteor.com/install
2. Add meteor.bat to PATH (C:\Users\<USER>\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32)
`> meteor`
`Sorry, this OS is not supported.`

**Comment by stubailo** [comment] 2016-02-12 03:39
What shell are you using? CMD?

**Comment by DavidAPowers** [comment] 2016-02-12 14:55
Windows 7 Ultimate, running ConEmu with GitBash giving me some (but not all) of the standard Linux Bash commands.

**Comment by stubailo** [comment] 2016-02-12 17:35
The issue is that Meteor on Windows doesn't run in Git Bash: #4938 

Works on Windows in PowerShell and CMD just fine!

Closing as a duplicate.

**Closed by stubailo** 2016-02-12 17:35 UTC
Labels: Project:Tool, Project:Windows
