### ISSUE TITLE
Error: "r" when logging in or resetting password

### ISSUE THREAD

**Issue by danielflippance** [meteor/meteor#6866] opened 2016-04-20 15:46 UTC
Some of my end users are having problems logging in a resetting their password. When I try to do the same using their username and password, the Meteor call returns an error "r". The two methods I'm calling are:

- Meteor.loginWithPassword 
- Accounts.resetPassword

Is "r" a code that I can lookup to find the meaning?
I'm running Meteor 1.2.1

**Comment by abernix** [comment] 2016-07-14 11:30
The `r` is probably coming from minified production code which is why it's not very helpful.  Is this something you can reproduce in development?  Perhaps you could export those users to your local development database and try there?  If so, please redact any sensitive information and make a reproduction repo.

Unfortunately, without additional information or a reproduction, this issue will be near impossible to track down and resolve and we'll need to close this.

**Comment by abernix** [comment] 2016-09-28 09:36
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)

**Closed by abernix** 2016-09-28 09:36 UTC
Labels: bug, can't-reproduce, Impact:few, Project:Accounts (in user apps)

**Comment by danielflippance** [comment] 2016-09-28 16:47
Sounds good, thanks. I don't recall how the issue was resolved.
