### ISSUE TITLE
Meteor fails on windows 7

### ISSUE THREAD

**Issue by DavidAPowers** [meteor/meteor#6227] opened 2016-02-12 17:51 UTC
After installing on Windows 7, and adding meteor.bat to global Path, I get the following error:
`$ meteor`
`C:\Users\david\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:18`
 ` if (p[0] === "\\" && (! partialPath)) {`
`       ^`
`TypeError: Cannot read property '0' of undefined`
`    at toPosixPath (C:\Users\david\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:18:8)`
`    at Object.convertToStandardPath (C:\Users\david\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:55:12)`
`    at Object.files.getHomeDir (C:\tools\fs\files.js:1125:13)`
`    at defaultWarehouseDir (C:\tools\packaging\tropohouse.js:30:43)`
`    at Object.<anonymous> (C:\tools\packaging\tropohouse.js:39:42)`
`    at Module._compile (module.js:456:26)`
`    at Object.Module._extensions..js (module.js:474:10)`
`    at Module.load (module.js:356:32)`
`    at Function.Module._load (module.js:312:12)`
`    at Module.require (module.js:364:17)`

**Comment by rdickert** [comment] 2016-02-16 23:24
Looking at this with @stubailo, he thought there might be a related bug involving Windows, but I have not found any issues that seem to match. @DavidAPowers, if so, this is an unusual/intermittent bug that doesn't occur for most users. It might be worth trying to reinstall, and make sure you reboot (sorry for the very limited ideas here). If you can provide any other context around this, that would help.

**Comment by abernix** [comment] 2016-07-19 21:51
A _lot_ has changed with the Windows version since this issue was opened.  If you are still having problems, please do a complete reinstall with the latest version of Meteor:

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.
* Install fresh from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

Closing this, but happy to reopen if we can reproduce in more current versions.

**Closed by abernix** 2016-07-19 21:51 UTC
Labels: Project:Windows
