### ISSUE TITLE
undefined function loginWithFacebook in Safari Version 8.0.5 (10600.5.17)

### ISSUE THREAD

**Issue by boasbam** [meteor/meteor#4322] opened 2015-05-04 22:27 UTC
This problem seems not to be related to #2639

For testing purposes I create a new app. `meteor list` yields the following packages _accounts-facebook, meteor-platform and service-configuration_. The test application setup follows [this tutorial](http://bulenttastan.net/login-with-facebook-using-meteor-js/) and [this part of the official docs](http://docs.meteor.com/#/full/meteor_loginwithexternalservice).

The connected Facebook app is set to public and does not run as a test-app.

The application works fine in Google Chrome and Firefox, but fails in Safari with the following error:
`TypeError: undefined is not a function (evaluating 'Meteor.loginWithFacebook')`

Is this an issue with Meteor or Safari? Can anyone reconstruct this issue?

**Comment by ekatek** [comment] 2015-05-06 07:40
Hi, thanks for reporting the issue. We will take a look at it. 

It would be helpful if you could have a more exact reproduction, as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without, we are less likely to be able to replicate the problem (and therefore less likely to be able to fix it).

**Comment by boasbam** [comment] 2015-05-06 08:18
Hi, I will update with a detailed replication recipe later today!

**Comment by albertmatyi** [comment] 2015-05-10 19:49
I have the same issue on Firefox 37 Linux (Though works well in Chrome)

So here is a small project demonstrating the bug:

# Reporuction

https://github.com/albertmatyi/meteor-accounts-facebook-bug

# Note
You might have to fill in the APP_ID / SECRET in the `server/facebook.js` file

**Comment by boasbam** [comment] 2015-06-11 23:03
##Reproduction
https://github.com/boasbam/loginWithFacebook

###Possible Solution

I turned off Adblock Plus which solved the problem and I can now login. Nevertheless it seems odd to me that console is telling *undefined is not a function (evaluating 'Meteor.loginWithFacebook')* if the problem was a blocked pop-up - do I err?

**Comment by albertmatyi** [comment] 2016-10-25 16:59
The issue still persists in Meteor 1.4.1.2 & Firefox 49

**Comment by abernix** [comment] 2016-11-14 17:13
@boasbam I used your reproduction in FireFox 49 with AdBlock Plus installed and was not able to reproduce this.

@albertmatyi I tried looking at this problem for you, but your reproduction doesn't even call `loginWithFacebook`.  I added a button which did call `loginWithFacebook` and it worked properly in FireFox 49 (macOS sierra) with the version of Meteor in your original reproduction (1.1.0.2).  Are you sure this isn't related to an extension that you have installed?  Happy to try to help you resolve this, but will require information in order to reproduce it.  Could you try again with all extensions disabled?  If you still experience the problem, can you please give me details about what version of Linux you're using?

**Comment by albertmatyi** [comment] 2016-11-14 19:40
Hi @abernix ,

I've just tested it with meteor version `METEOR@1.4.2.1-beta.0` and the issue only manifests itself in development mode on Firefox with Ad-Block-Plus enabled.

In all other cases it works well.

Cheers,
m

PS. In my sample project I was calling the method manually from the console.

**Comment by abernix** [comment] 2016-11-15 13:36
Ah, okay.  I just tried using `Meteor.loginWithFacbeook` from the Dev Tools console on Ubuntu Firefox 49.x and I ran into the same problem with `Meteor.loginWith*`.  Upon further investigation, it seems that I had an exception for `localhost` popups somewhere on my Mac because after I reset my Firefox, I ran into the same problem.

I do not run into the same problem if I simply ensure that `Meteor.loginWithFacebook` is triggered from a code entry point which was triggered by user input (e.g. mouse or keyboard selection).

You'll need to make sure that `Meteor.loginWithFacebook` is triggered by user-input or if you'd like to do it in testing, use `loginStyle=redirect` which doesn't use the popup method:

    Meteor.loginWithFacebook({ loginStyle: 'redirect' })

... from the console.

I don't believe there is a bug here.

**Comment by abernix** [comment] 2016-12-19 16:38
Closing for the above reasons.  I do not believe there is a bug here but rather the browser security policies are behaving correctly.  If you want the popup to work, you'll need to trigger it specifically from a user action which the browser would consider safe and Firefox doesn't consider the console "safe" in all cases.

**Closed by abernix** 2016-12-19 16:38 UTC
Labels: can't-reproduce, Impact:few, Project:Accounts:UI
