### ISSUE TITLE
Error on update meteor to 1.6.1+ version

### ISSUE THREAD

**Issue by ricaragao** [meteor/meteor#9959] opened 2018-06-07 01:56 UTC
After I update meteor to 1.6.1+, my app has this error:

=> Errors prevented startup:                  
   
   While minifying app stylesheet:
   app/client/stylesheets/style.less.css:2655:9: Missed semicolon
   
=> Your application has errors. Waiting for file change.

When I remove standard-minifier-css, it works!

**Comment by paulincai** [comment] 2018-09-16 12:07
Hi, it's been 3 months. Did you find the semicolon. If yes, would be great to close this issue.

**Comment by klaussner** [comment] 2018-10-31 20:31
Closing due to inactivity and missing reproduction.

**Closed by klaussner** 2018-10-31 20:31 UTC
