### ISSUE TITLE
App is throwing errors in firefox browser console  after upgrading to meteor 1.6

### ISSUE THREAD

**Issue by parveen-daffodil** [meteor/meteor#9446] opened 2017-12-07 09:19 UTC
I have upgraded my app to meteor 1.6 but it is showing errors in firefox browser console. I have added a screenshot of the errors.

![screenshot from 2017-12-07 14 38 48](https://user-images.githubusercontent.com/5242589/33707520-a7afdbd2-db5d-11e7-8c2c-84a8268675e0.png)

**Comment by axelvaindal** [comment] 2017-12-07 13:50
Hi @parveen-daffodil,

From which version were you upgrading from ?
Have you followed the migration guide available [here](https://guide.meteor.com/1.6-migration.html) ?
Is this only happening with Firefox ? Which version of Firefox are you using ? What happens with Chrome or Edge for instance ?
What about the syntax error in the console ? Is this related to your code ? To a package you're using ? If so, have you checked this package is compatible with Meteor v1.6 ?

**Comment by benjamn** [comment] 2017-12-07 14:46
The first error (`missing = in const declaration`) is very likely the cause of the rest.

There aren't any `const` declarations in the [`modules` package](https://github.com/meteor/meteor/tree/devel/packages/modules) itself, but Meteor does include modules from the application `node_modules` directory in the `modules` package bundle, so that they will be defined prior to any package or application code that depends on the `modules` package.

It seems probable that some npm package in your application `node_modules` directory has an uninitialized `const variable;` declaration, and Firefox is complaining about that.

If you click on the first error, does it go to any particular line within the `modules.js` bundle? Do you see any uninitialized `const` declaration(s) there? If so, can you identify the offending npm package from that code?

**Comment by parveen-daffodil** [comment] 2017-12-08 04:44
@benjamn I agree this error is coming from npm module `chalk` Actually, it is included as an indirect dependency of `marky-markdown` earlier I was using same modules with meteor 1.5 and do not face any issue.

Now the only difference I can see is that in meteor 1.6 has created a package.lock.json which creates tree of node modules 
like this 
`marky-markdown` requires `sanitize-html` requires `postcss` requires `chalk`

Earlier version of sanitize-html(before update it was 1.14.1) and now it has changed to 1.16.1.
May be that version change is causing the issue?

**Comment by parveen-daffodil** [comment] 2017-12-08 05:11
I have created `npm-shrinkwrap.json` in my folder structure and updated my `package.json`
with dependency "sanitize-html": "https://registry.npmjs.org/sanitize-html/-/sanitize-html-1.14.1.tgz" . Now `sanitize-html` with version 1.14.1 is saved in `npm-shrinkwrap.json` that solves the problem.
But I am still afraid that it will create any issue?

**Comment by benjamn** [comment] 2017-12-08 20:22
Yep, that sounds likely. Unfortunately the versions of indirect npm dependencies tend to drift unless you're really careful about your `package-lock.json` file.

In this case you should be able to force-install the older versions of `sanitize-html` and `chalk`:
```sh
meteor npm install sanitize-html@1.14.1 chalk@whatever.it.was
```
If you commit the resulting `package-lock.json` file, that should help keep the versions fixed.

Unfortunately, this probably won't be fixed even if we start allowing compilation for `node_modules` (see https://github.com/meteor/meteor-feature-requests/issues/6 for discussion of that), since Babel will definitely throw when it tries to compile this file.

**Comment by hwillson** [comment] 2017-12-12 13:26
Closing as this is outside of Meteor's control. See https://github.com/meteor/meteor/issues/9446#issuecomment-350362935 for a potential workaround. Thanks!

**Closed by hwillson** 2017-12-12 13:26 UTC
