### ISSUE TITLE
Unexpected error - Angular 1 + Meteor 1.6

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#9421] opened 2017-11-27 13:03 UTC
I am getting this error on client side in browser web application.

`Unexpected error.`

This appears in a totally white blank page in browser on top left corner when I access my web application.

It appears occasionally. There is no error in the Meteor Server Console or in browser console.

Whenever this error appears, non of my client apps (android, ios , web app) works, which are connected to this specific server. The server shows that its running but it does not. When I restart Meteor Server, then it starts working fine, I get this error once in about two weeks, I don't know what is causing this error, or how to debug this. Any idea what is causing this issue? This is really critical, I have my Live Application running, and it should not crash like this. Please provide me some solution or a way to debug. Thanks

**Comment by hwillson** [comment] 2017-11-27 14:07
Sorry to hear @MartiniHenry1988 - is there any chance you can provide a runnable reproduction that shows this happening (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug))? This could be coming from anything, so without more troubleshooting details like a complete exception, stack trace, a way to re-create this error, etc., there really isn't much to go on here.

**Comment by sebakerckhof** [comment] 2017-11-27 21:25
I've also seen this error in development mode, it came from: https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/tools/runners/run-proxy.js#L108 . Didn't bother to look into it further since it only happens occasionally.
So @MartiniHenry1988 are you by any chance running meteor in development mode instead of from a production build?

**Comment by MartiniHenry1988** [comment] 2017-11-28 12:25
@hwillson  It appears too much occasionally that I am unable to reproduce it since I don't know when it will appear or in what scenario.

**Comment by MartiniHenry1988** [comment] 2017-11-28 12:25
@sebakerckhof  Yes I am running my app using --production flag

**Comment by hwillson** [comment] 2017-11-28 13:08
> I have my Live Application running, and it should not crash like this.

@MartiniHenry1988 Are you saying that you're running your production application via the Meteor Tool? So you're running it using something like `meteor --production ...`? This is definitely not recommended, for many reasons - please see the [deployment section of the Guide](https://guide.meteor.com/deployment.html) for details.

If you're seeing the same error as @sebakerckhof mentioned, then it's happening when Meteor's HTTP proxy can't get a response from the application. For example, if you're running `meteor --production` then by default Meteor is setting up an HTTP proxy to redirect incoming `localhost:3000` requests to the internal `localhost` port your application was connected to when it was started up. So something like `localhost:3000` --> `localhost:[some internal port number]`. If the proxy can't send the request it received at `localhost:3000` to the internal application, then instead of crashing it's dumping that `Unexpected error` message. It keeps listening though, hoping the application will start responding again. Long story short - if this keeps happening for you, I'd recommend getting some additional application logging in place. When you see the `Unexpected error` message, start looking at your application logs to see if you can find anything else out of the ordinary.

All of this being said though, you won't have these issues in production unless you're attempting to use the Meteor Tool to run your production application. Again, please see the Guide for more details.

Given that this won't be an easy issue to reproduce and the impact here is quite low, I'll close this off. Thanks!

**Closed by hwillson** 2017-11-28 13:08 UTC
Labels: needs-reproduction

**Comment by MartiniHenry1988** [comment] 2018-04-16 09:57
@hwillson Where can I see the logs? I want to debug this issue thoroughly. Since my client needs to test the application on staging server, they cant if my app keeps crashing. Plus for the production deployment on live server, which tool should I use? Meteor Up or Phusion Passenger? Or is there any other easy way to run Meteor App?
