### ISSUE TITLE
BUG: Assets get mixed up when having same content (Repro included)

### ISSUE THREAD

**Issue by Narzerus** [meteor/meteor#8159] opened 2016-12-15 11:41 UTC
Meteor Version 1.4.2.3, OSX
Repro repository: https://github.com/Narzerus/add-assets-repro-repo

There is a bug in meteor packages with assets, apparently in certain conditions if two assets have the same contents the last one doesn't get bundled. This behaves in weird ways, for instance `Assets.absoluteFilePath` returns the path of *the first asset*, also only the first file gets bundled with the app.

**Comment by hwillson** [comment] 2016-12-15 12:52
Hi @Narzerus - first off thanks for providing a detailed reproduction, it's greatly appreciated! I know this looks like a bug up front, but the `Assets` API is actually functioning as designed. `Assets` goes to great lengths to help ensure duplicate static assets aren't included in the deployed application bundle, to help reduce overhead. To understand what's happening in your reproduction, crack open the `.meteor/local/build/programs/server/program.json` file in your application, and take a look at the following section:

```json
{
  "sourceMap": "packages/add-assets-repro-package.js.map",
  "path": "packages/add-assets-repro-package.js",
  "assets": {
    "files/folder1/0.txt": "assets/packages/add-assets-repro-package/files/folder1/0.txt",
    "files/folder1/1.txt": "assets/packages/add-assets-repro-package/files/folder1/0.txt"
  }
},
```

When you make a `getText` call for example, the path you pass in is matched above, and the appropriate file contents are returned. Since Meteor controls access to the filesystem through the `Assets` API, the behind the scenes location/name of the referenced file doesn't matter (as long as you use the `Assets` API). 

That being said, `Assets.absoluteFilePath` will return the real path of the file, and in your case that means it returns a file path that is different than the one you expected, since it's returning the only file it included after de-duping based on contents. But it is returning an absolute path to a file that has the same contents of your original file; so anything you intended to do with the file you referenced originally, you can do with this file. I know - it seems a bit strange, but the `Assets` API is really just intended to provide a way to get to bundled static content; it's not intended to be a full-fledged file manipulation API.

**Comment by Narzerus** [comment] 2016-12-15 12:57
I see, there are very specific use-cases in which this behavior can become an issue. For example, in our case we are using an scss parser to load `.scss` files and compile them in runtime. Because we have to override the `scss` loader, we need to reimplement the way it retrieves relative files, which means that getting a different file path from `Assets.absoluteFilePath` is causing the loader to look for the file inside a different directory.

Is there a way to disable this behavior? I can imagine there will be other specific cases where people will have trouble thanks to this.

Thanks for the quick reply!

**Comment by hwillson** [comment] 2016-12-15 13:14
No, there isn't currently a way to disable this functionality in the `Assets` API. If you need to do more extensive file manipulations, you can always consider using [Node's file API](https://nodejs.org/docs/v4.6.2/doc/api/fs.html#fs_file_system) directly. Since your issue relates to `scss` parsing/loading though, you might want to post your issue (with some sample code) on the [Meteor forums](http://forums.meteor.com). Handling `scss` with Meteor apps/packages is pretty common, so it's quite possible someone has already come up with a solution to the issue you're facing.

Thanks again for the great reproduction - I'll close this for now since everything is working as designed.

**Closed by hwillson** 2016-12-15 13:14 UTC

**Comment by Narzerus** [comment] 2016-12-15 13:19
Got it, we are actually using `Node's file API` but we still need `Assets.absoluteFilePath` to get the proper path to a certain file, specially since other exactly equal files don't get bundled at all.

Sadly we are compiling in *runtime*, not in *build time* so I'm not sure if there's too many people in the community who have faced this particular issue.

Thanks again, I guess the only workaround is to enforce content-uniqueness in our assets.

**Comment by rcsandell** [comment] 2020-11-03 03:15
Hi @hwillson ,

Thanks for taking the time to explain the deduplication of identical assets using the `Assets` API.

I just want to say that there is no mention that I could find of this in the meteor documentation, and this issue just caused me some major headaches and a good few hours because of loading an identical HTML template, although in a different folder, and so the `Assets` API was returning the path to the wrong HTML file that was the relatively referencing the wrong JavaScript file from the wrong folder.

I really think there needs to be a big warning at the top of the https://docs.meteor.com/api/assets.html#Assets-absoluteFilePath documentation, saying that, "Identical files, even in different sub-directories, will have the second duplicate file discarded, and the path to the first duplicate returned instead"

"The fix was to add a comment to each of the the files with the file path in the comment, e.g. folder1/template.html & folder2/template.html. This made the `Assets` API recognize the files as different files and everything then works again"

Please can you make sure some kind of warning about the deduplication functionality gets added to the documentation.

Kind Regards,
Robert

**Comment by filipenevola** [comment] 2020-11-12 15:47
Hi @rcsandell are you willing to give us a hand and update the doc here https://github.com/meteor/docs/blob/master/source/api/assets.md?

We are always reviewing and merge PRs as soon as possible.
