### ISSUE TITLE
Subpackage version dependencies not being resolved correctly in `api.use()`

### ISSUE THREAD

**Issue by cmnjcs** [meteor/meteor#4165] opened 2015-04-09 21:14 UTC
It appears that the version selector used in `api.use()` does not always follow the specification outlined in [the docs](http://docs.meteor.com/#/full/pack_use). Based on my experimenting, this problem happens more often with packages at `v0` than those at `v1` or greater. Process to replicate:

* Clone https://github.com/grovelabs/versioning-sample-app
* Run the application
* In `packages/meteor-collection2-master/package.js`, uncomment lines 21-24. Note that the four packages listed (as well as a fifth, `twbs:bootstrap`, which is a dependency of `fezvrasta:bootstrap-material-design`) are added to the project. Only `faisalman:ua-parser-js` is at the correct version (`0.7.5`); the others (excluding `twbs:bootstrap`) are old versions of their packages. The command line output is:
```
edgee:slingshot                      added, version 0.0.3    // should be 0.6.1
faisalman:ua-parser-js               added, version 0.7.5    // correct
fezvrasta:bootstrap-material-design  added, version 0.2.1    // should be 0.3.0
momentjs:moment                      added, version 2.8.4    // should be 2.10.2
twbs:bootstrap                       added, version 3.3.4    // correct
```
* Then, in the same `package.js` file, comment out lines 21-24 and uncomment lines 26-29. After saving, note that no packages are updated. According to the docs, specifying `x.0.0` should cause the package version with the highest version number still starting with `x` to be selected, but this does not match the observed behavior.
* Then, in the same `package.js` file, comment out lines 26-29 and uncomment lines 31-34. Note that the three packages with old versions are correctly updated to the specified versions. Command line output is:
```
edgee:slingshot                      upgraded from 0.0.3 to 0.6.1
fezvrasta:bootstrap-material-design  upgraded from 0.2.1 to 0.3.0
momentjs:moment                      upgraded from 2.8.4 to 2.10.2
```

Note: all of the packages selected for this project were effectively arbitrary; I was simply going for a spread of packages in `v0` and beyond.

**Comment by Alveoli** [comment] 2015-04-14 20:26
I appear to be suffering a similar-ish problem - basically api.use is picking up the wrong dependancies - see my SO post: http://stackoverflow.com/questions/29634773/meteor-package-yogibenadmin-refuses-to-install-seems-to-be-picking-up-wrong

**Comment by glasser** [comment] 2015-04-14 22:36
Duplicate of #4170.

(Though can you mention there which docs you're referring to when you say "specifying `x.0.0` should cause the package version with the highest version number still starting with x to be selected"?)

**Closed by glasser** 2015-04-14 22:36 UTC
Labels: Project:Version Solver
