### ISSUE TITLE
[1.8.0.1-rc.0] error

### ISSUE THREAD

**Issue by jorisroling** [meteor/meteor#10337] opened 2018-11-15 09:11 UTC
`/Users/XXX/.meteor/packages/tap_i18n/.1.8.2.1q9t9mx.tii1++os+web.browser+web.cordova/plugin.tap-i18n-compiler.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at Object.pathJoin (/Users/XXX/.meteor/packages/meteor-tool/.1.8.0-1-rc.0.jyce4h.gd43j++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/mini-files.js:109:14)
    at Isopack._getServePath (/tools/isobuild/isopack.js:1646:13)
    at new OutputResource (/tools/isobuild/compiler-plugin.js:876:23)
    at new JsOutputResource (/tools/isobuild/compiler-plugin.js:994:5)
    at new ResourceSlot (/tools/isobuild/compiler-plugin.js:596:37)
    at /tools/isobuild/compiler-plugin.js:1065:31
    at Array.forEach (<anonymous>)
    at new PackageSourceBatch (/tools/isobuild/compiler-plugin.js:1033:24)
    at /tools/isobuild/compiler-plugin.js:142:14
    at Array.map (<anonymous>)
    at Function._.map._.collect (/Users/XXX/.meteor/packages/meteor-tool/.1.8.0-1-rc.0.jyce4h.gd43j++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:97:56)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:136:27)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1102:22)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:835:34)
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:829:18)
    at /tools/isobuild/bundler.js:3128:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3279:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3233:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3109:31)
    at files.withCache (/tools/isobuild/bundler.js:3054:32)
    at Object.withCache (/tools/fs/files.js:1712:12)
    at Object.bundle (/tools/isobuild/bundler.js:3054:16)
    at Profile.run (/tools/runners/run-app.js:569:24)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:568:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:610:35)
    at AppRunner._fiber (/tools/runners/run-app.js:908:28)
    at /tools/runners/run-app.js:398:12`

**Comment by StorytellerCZ** [comment] 2018-11-15 09:31
Seems to be an issue with tap i18n package. Can you tell us more why you think it is related to Meteor 1.8.0.1-rc.0?

`TypeError: Path must be a string. Received undefined`
Please check that all the values you pass to the package methods have defined values.

**Comment by benjamn** [comment] 2018-11-15 15:54
I suspect this is somehow related to [this change](https://github.com/meteor/meteor/pull/10330/files#diff-3396ab7aa5a3a2dbcfffa54934610c7bR596) from https://github.com/meteor/meteor/pull/10330.

**Comment by benjamn** [comment] 2018-11-15 21:20
This should be fixed if you run `meteor update --release 1.8.0.1-rc.1`, though I can't be completely certain without a runnable reproduction. Please feel free to reopen this issue if the problem persists.

**Comment by jorisroling** [comment] 2018-11-17 18:43
After upgrading to 1.8.0.1-rc.1 I get this error:

/Users/XXX/.meteor/packages/tap_i18n/.1.8.2.1q9t9mx.tii1++os+web.browser+web.cordova/plugin.tap-i18n-compiler.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^

Error: addJavaScript on non-source ResourceSlot?
    at ResourceSlot.addJavaScript (/tools/isobuild/compiler-plugin.js:790:13)
    at ResourceSlot._addDirectlyToJsOutputResources (/tools/isobuild/compiler-plugin.js:594:10)
    at new ResourceSlot (/tools/isobuild/compiler-plugin.js:584:14)
    at /tools/isobuild/compiler-plugin.js:1069:31
    at Array.forEach (<anonymous>)
    at new PackageSourceBatch (/tools/isobuild/compiler-plugin.js:1037:24)
    at /tools/isobuild/compiler-plugin.js:142:14
    at Array.map (<anonymous>)
    at Function._.map._.collect (/Users/XXX/.meteor/packages/meteor-tool/.1.8.0-1-rc.1.jdmwi5.l2ar++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:97:56)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:136:27)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1102:22)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:835:34)
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:829:18)
    at /tools/isobuild/bundler.js:3128:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3279:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3233:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3109:31)
    at files.withCache (/tools/isobuild/bundler.js:3054:32)
    at Object.withCache (/tools/fs/files.js:1712:12)
    at Object.bundle (/tools/isobuild/bundler.js:3054:16)
    at Profile.run (/tools/runners/run-app.js:569:24)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:568:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:610:35)
    at AppRunner._fiber (/tools/runners/run-app.js:908:28)
    at /tools/runners/run-app.js:398:12

**Comment by benjamn** [comment] 2018-11-17 21:22
Try `1.8.0.1-rc.2`?

**Comment by jorisroling** [comment] 2018-11-18 07:55
Still this error:

/Users/XXX/.meteor/packages/tap_i18n/.1.8.2.1q9t9mx.tii1++os+web.browser+web.cordova/plugin.tap-i18n-compiler.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at Object.pathJoin (/Users/XXX/.meteor/packages/meteor-tool/.1.8.0-1-rc.2.17xoek4.j8tdi++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/mini-files.js:109:14)
    at Isopack._getServePath (/tools/isobuild/isopack.js:1646:13)
    at new OutputResource (/tools/isobuild/compiler-plugin.js:882:23)
    at new JsOutputResource (/tools/isobuild/compiler-plugin.js:1000:5)
    at ResourceSlot.addJavaScript (/tools/isobuild/compiler-plugin.js:795:22)
    at ResourceSlot._addDirectlyToJsOutputResources (/tools/isobuild/compiler-plugin.js:594:10)
    at new ResourceSlot (/tools/isobuild/compiler-plugin.js:584:14)
    at /tools/isobuild/compiler-plugin.js:1071:31
    at Array.forEach (<anonymous>)
    at new PackageSourceBatch (/tools/isobuild/compiler-plugin.js:1039:24)
    at /tools/isobuild/compiler-plugin.js:142:14
    at Array.map (<anonymous>)
    at Function._.map._.collect (/Users/XXX/.meteor/packages/meteor-tool/.1.8.0-1-rc.2.17xoek4.j8tdi++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:97:56)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:136:27)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1102:22)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:835:34)
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:829:18)
    at /tools/isobuild/bundler.js:3128:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3279:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3233:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3109:31)
    at files.withCache (/tools/isobuild/bundler.js:3054:32)
    at Object.withCache (/tools/fs/files.js:1712:12)
    at Object.bundle (/tools/isobuild/bundler.js:3054:16)
    at Profile.run (/tools/runners/run-app.js:569:24)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:568:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:610:35)
    at AppRunner._fiber (/tools/runners/run-app.js:908:28)
    at /tools/runners/run-app.js:398:12

**Comment by benjamn** [comment] 2018-11-18 16:03
Any chance you could provide a reproduction? Apparently my guessing is not working!

**Comment by jorisroling** [comment] 2018-11-19 08:11
@benjamn  I did send you an app example via e-mail

**Comment by benjamn** [comment] 2018-11-19 20:58
Ok, please try running `meteor update --release 1.8.0.1-rc.3` to see if [that problem](https://github.com/meteor/meteor/issues/10337#issuecomment-439674497) is fixed now. Note that the relevant change has not been pushed to the `release-1.8.1` branch yet, so 1.8.**0**.1 is important.

**Comment by jorisroling** [comment] 2018-11-20 12:34
Yeah, it works! Problem fixed... 😃

**Comment by jorisroling** [comment] 2018-11-21 08:52
`METEOR@1.8.0.1-rc.4` also works, but `METEOR@1.8.1-beta.5` does not. Probably, as @benjamn stated, because the changes have not been pushed to `release-1.8.1`. Are they going to be pushed?

**Comment by Antoine-O** [comment] 2018-11-23 15:21
My issues (similar to yours) are also resolved with METEOR@1.8.0.1-rc.4 but not METEOR@1.8.1-beta.5

**Closed** 2018-11-23 17:46 UTC

**Comment by jorisroling** [comment] 2018-11-26 08:56
Now METEOR@1.8.0.1 works, but METEOR@1.8.1-beta.6 does not...

**Comment by benjamn** [comment] 2018-11-26 16:21
@jorisroling That's good to know, because all the 1.8.0.1 changes should now be merged into 1.8.1-beta.6. Which error are you seeing? `Path must be string. Received undefined`?

**Comment by jorisroling** [comment] 2018-11-26 16:30
@benjamn You can see this by upgrading the app I sent you earlier.
For reference, I get this error now:
 
```
/Users/XXX/.meteor/packages/meteor-tool/.1.8.1-beta.6.1sz22kn.xpcx++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
		throw(ex);
		^

TypeError: Cannot read property 'constructor' of undefined
    at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
    at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
    at packages/meteorhacks_meteorx.js:175:1
    at packages/meteorhacks_meteorx.js:200:4
    at packages/meteorhacks_meteorx.js:208:3
    at /Users/XXX/Projects/YYY/app/.meteor/local/build/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /Users/XXX/Projects/YYY/app/.meteor/local/build/programs/server/boot.js:220:19
    at /Users/XXX/Projects/YYY/app/.meteor/local/build/programs/server/boot.js:471:5
    at Function.run (/Users/XXX/Projects/YYY/app/.meteor/local/build/programs/server/profile.js:510:12)
    at /Users/XXX/Projects/YYY/app/.meteor/local/build/programs/server/boot.js:470:11

```

**Comment by benjamn** [comment] 2018-11-26 17:04
Ok, at least that's something different. PR #10053 converted the `_namedSubs` object to a `Set`, which seemed safe because the `_` indicates it's not a stable public API. However, `meteorhacks:meteorx` still assumes it's an object [here](https://github.com/meteorhacks/meteorx/blob/5e789f0c5dee7a23fa22600dbd382df670178bf3/lib/livedata.js#L39). Since this package hasn't been updated since 2014, I think your best options are either to remove `meteorhacks:meteorx` from your app, or to clone it into your local `packages/` directory and change the offending code to `_namedSubs.has(subId)`.

**Comment by jorisroling** [comment] 2018-11-26 17:38
Cheers Ben, good catch. The package is not directly loaded by my app though.
I've informed the creator of Monti Agent (the Kadira replacement) of which I'm a customer. I hope he (she?) can resolve this issue. Thanks!

**Comment by benjamn** [comment] 2018-11-30 13:33
@jorisroling Working on removing the `meteorhacks:meteorx` dependency from `mdg:meteor-apm-agent`: https://github.com/meteor/meteor-apm-agent/pull/7

**Comment by jorisroling** [comment] 2018-11-30 14:11
@benjamn Great, it might inspire the good people @ https://github.com/monti-apm/monti-apm-agent aswell...

**Comment by haunguyen90** [comment] 2018-12-05 09:07
`mdg:meteor-apm-agent@3.2.0-rc.0` works great for me.
Based on my support ticket
![image](https://user-images.githubusercontent.com/8245883/49502523-d0234780-f8a7-11e8-8057-143b01b1f1a7.png)

Thank MDG
Thank Ben
