### ISSUE TITLE
[1.4-beta.14] npm-bcrypt 0.8.7 crashes the server

### ISSUE THREAD

**Issue by suhail-ansari-apconic** [meteor/meteor#7413] opened 2016-07-15 11:15 UTC
On Linux mint Sarah (18) when upgrading to 1.4-beta.14 the application even fails to start with npm-bcrypt 0.8.7 but works nicely with 0.8.6_2

**Comment by laosb** [comment] 2016-07-17 11:02
Sounds like a side effect on some updates related to #7408?

**Comment by suhail-ansari-apconic** [comment] 2016-07-18 08:45
This is the error that i get running on Ubuntu 16.04 LTS 64 bit


[[[[[ ~/projects/apconic/goodsmon ]]]]]

=> Started proxy.
=> Started MongoDB.
[34mW20160718-14:13:07.296(5.5)? (STDERR) [39m[35m/home/sansari/.meteor/packages/meteor-tool/.1.4.0-beta.14.1asvvss++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280[39m
[34mW20160718-14:13:07.331(5.5)? (STDERR) [39m[35m						throw(ex);[39m
[34mW20160718-14:13:07.332(5.5)? (STDERR) [39m[35m						^[39m
[34mW20160718-14:13:07.332(5.5)? (STDERR) [39m[35m[39m
[34mW20160718-14:13:07.332(5.5)? (STDERR) [39m[35mError: Module did not self-register.[39m
[34mW20160718-14:13:07.332(5.5)? (STDERR) [39m[35m    at Error (native)[39m
[34mW20160718-14:13:07.333(5.5)? (STDERR) [39m[35m    at Object.Module._extensions..node (module.js:434:18)[39m
[34mW20160718-14:13:07.333(5.5)? (STDERR) [39m[35m    at Module.load (module.js:343:32)[39m
[34mW20160718-14:13:07.333(5.5)? (STDERR) [39m[35m    at Module.Mp.load (/home/sansari/.meteor/packages/babel-compiler/.6.9.0-beta.14.hbheup++os+web.browser+web.cordova/npm/node_modules/reify/node/runtime.js:16:23)[39m
[34mW20160718-14:13:07.334(5.5)? (STDERR) [39m[35m    at Function.Module._load (module.js:300:12)[39m
[34mW20160718-14:13:07.334(5.5)? (STDERR) [39m[35m    at Module.require (module.js:353:17)[39m
[34mW20160718-14:13:07.334(5.5)? (STDERR) [39m[35m    at require (internal/module.js:12:17)[39m
[34mW20160718-14:13:07.334(5.5)? (STDERR) [39m[35m    at bindings (/home/sansari/.meteor/packages/npm-bcrypt/.0.8.7.1tks03d++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bindings/bindings.js:76:44)[39m
[34mW20160718-14:13:07.335(5.5)? (STDERR) [39m[35m    at Object.<anonymous> (/home/sansari/.meteor/packages/npm-bcrypt/.0.8.7.1tks03d++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/bcrypt.js:3:35)[39m
[34mW20160718-14:13:07.335(5.5)? (STDERR) [39m[35m    at Module._compile (module.js:409:26)[39m
=> Exited with code: 1

**Comment by markoshust** [comment] 2016-07-18 18:22
dupe of https://github.com/meteor/meteor/issues/7339

**Comment by abernix** [comment] 2016-07-19 10:26
Agree with @markoshust.  Please see #7339.

**Closed by abernix** 2016-07-19 10:26 UTC
