### ISSUE TITLE
Named ReactiveDict has null error in clear() after HCR

### ISSUE THREAD

**Issue by elidoran** [meteor/meteor#5805] opened 2015-12-14 16:54 UTC
I'm using a Mac and it does this in both Chrome and Safari.

Reproduce it with [this app](https://github.com/elidoran/meteor-reactivedict-null-error). It has instructions to git clone it, cd into it, and run it. After that, trigger a Hot Code Reload and you'll see the error in the console.

Explanation:

At [line 166](https://github.com/meteor/meteor/blob/master/packages/reactive-dict/reactive-dict.js#L166) it accesses multiple levels at once and I'm getting an error because the `[key]` portion is undefined after a Hot Code Reload.

```javascript
// I assume the line after it would error as well
changed(self.keyValueDeps[key][value]);
changed(self.keyValueDeps[key]['undefined']);
```

Error message ("value" is the value of the key value pair in the ReactiveDict before HCR): 

```
TypeError: Cannot read property '"value"' of undefined
    at reactive-dict.js:166
    at Function._.each._.forEach (underscore.js:113)
    at _.extend.clear (reactive-dict.js:164)
   ...
```

The reload's migration only restores the keys.
Calling `get()` for the value before calling `clear()` will avoid the issue for that one key because `get()` calls `_ensureKey()` inside it. So, should the migration call `_ensureKey()` for each key restored via migration?

Or, just null check lines 166 and 167 to avoid the error?

**Comment by tmeasday** [comment] 2015-12-15 23:05
Thanks for the report. This is a dupe of https://github.com/meteor/meteor/issues/5530 (already fixed)

**Closed by tmeasday** 2015-12-15 23:05 UTC

**Comment by elidoran** [comment] 2015-12-16 01:22
Great, thank you. Seems no matter how much I searched I couldn't find #5530. Probably because I searched for "clear" and that says "clearing". Wasted time, blarg.
