### ISSUE TITLE
server-render, ecmascript import scss file doesn't work.

### ISSUE THREAD

**Issue by minhna** [meteor/meteor#9456] opened 2017-12-09 15:55 UTC
- The version of Meteor: 1.6.0.1
- The operating system: Ubuntu linux 16.04

I use package[ fourseven:scss](https://atmospherejs.com/fourseven/scss) to compile scss files, it works fine if I don't call `onPageLoad` function on server.

I import scss file by simple command in my js file:
```
import './site.scss';
```

here is error:
```
W20171209-22:46:01.827(7)? (STDERR) /home/minhna/.meteor/packages/meteor-tool/.1.6.0_1.14od3k.cmakv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171209-22:46:01.828(7)? (STDERR) 						throw(ex);
W20171209-22:46:01.828(7)? (STDERR) 						^
W20171209-22:46:01.828(7)? (STDERR) 
W20171209-22:46:01.828(7)? (STDERR) Error: Cannot find module './site.scss'
W20171209-22:46:01.829(7)? (STDERR)     at makeMissingError (packages/modules-runtime.js:231:12)
W20171209-22:46:01.829(7)? (STDERR)     at require (packages/modules-runtime.js:241:19)
W20171209-22:46:01.829(7)? (STDERR)     at site.js (imports/ui/layouts/site/site.js:1:435)
W20171209-22:46:01.829(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20171209-22:46:01.829(7)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20171209-22:46:01.830(7)? (STDERR)     at routes.js (imports/startup/both/routes.js:1:301)
W20171209-22:46:01.830(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20171209-22:46:01.830(7)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20171209-22:46:01.830(7)? (STDERR)     at ssr-init.js (imports/startup/server/ssr-init.js:1:375)
W20171209-22:46:01.830(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
=> Exited with code: 1
```

**Comment by hwillson** [comment] 2017-12-09 17:11
Can you please provide a small runnable reproduction demonstrating this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug))?

**Comment by minhna** [comment] 2017-12-10 02:35
I pushed a demo to github at https://github.com/minhna/meteor-server-render-fourseven.
Thank you @hwillson

**Comment by hwillson** [comment] 2017-12-11 17:16
Thanks for the reproduction @minhna. This doesn't have anything to do with the `server-render` package however. In your reproduction, if you replace the contents of `/server/main.js` with `import '/imports/ui/layouts/site/site.js';`, you'll get the exact same error. This is because the `fourseven:scss` package is a web architecture only build plugin, which means it's only working with files that are intended for the client side. It won't work with files referenced on the server side, so you're `site.scss` file isn't being compiled by `fourseven:scss`.

As a quick workaround, you could consider referencing your component `.scss` files from a top level `main.scss` file, so they're covered/included by `fourseven:scss` on the client side (which will then be used when you render your server side components). So something like:

**/client/main.scss**

```css
@import '../imports/ui/layouts/site/site.scss';
```

This will allow you to keep your `.scss` files alongside your components, but you'll have to remember to keep this file up to date as you add/remove component `.scss` files (since `fourseven:scss` doesn't support globbing).

Closing as this isn't a Meteor issue. Thanks!

**Closed by hwillson** 2017-12-11 17:16 UTC
Labels: needs-reproduction
