### ISSUE TITLE
Objects flattened only in LocalCollection

### ISSUE THREAD

**Issue by basaundi** [meteor/meteor#4260] opened 2015-04-23 10:19 UTC
In the following example:

``` javascript
function A() { this.x = 5; }
A.prototype.test = function() { return 'hi'; }
var a = new A()
col.insert(a); // Previously created collection
var b = col.findOne();
```

The document `{ x: 5 }` is stored in the remote collection but variable `b` contains `A { x: 5, test: [Function] }`. 

I find two weird things on this behaviour:
- In my opinion, the local collection should be storing the same thing that's being stored remotely, disconnected from any prototype.
- The object is flattened so it's not even the object I intended to save but an aberration of it, because it now contains a function from its prototype.

A quick fix for the second concern I believe would be using `_.extendOwn` instead of `_.extend` in the following line:

`/packages/mongo/collection.js:470`

``` javascript
      args[0] = _.extend({}, args[0]);
```

**Comment by glasser** [comment] 2015-04-29 00:10
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

That said, I believe this is working as intended.  All types to be manipulated by Meteor data structures (like minimongo, DDP, etc) need to be [EJSON](http://docs.meteor.com/#/full/ejson); if you want to add extra behavior to your data, either use the `transform` argument to `Mongo.Collection`, or register your type as an [EJSON custom type](http://docs.meteor.com/#/full/ejson_add_type).

**Comment by basaundi** [comment] 2015-04-29 02:02
This is a full reproduction repository:
https://github.com/basaundi/meteor-issue-4260

I don't think this behaviour is the intended one, because its not consistent.
I'm not using EJSON because I don't need it; I'm just using the prototype of that object before insertion. Even if I used `transform` the behaviour would be inconsistent because the properties of the prototype are copied to the object in the LocalCollection.

Calling the following function before every insertion would solve the issue, but it's not desirable:
```javascript 
function withoutProto(x){
  var n = {};
  for(var k in x) if(x.hasOwnProperty(k)) n[k] = x[k];
  return n;
}
Things.insert(withoutProto(whatever));
```

**Comment by basaundi** [comment] 2015-05-08 07:36
Please, consider reopening this issue, or answering to the full reproduction repository comment.

**Comment by hwillson** [comment] 2017-07-31 12:52
I've verified both of the outlined issues

> 1. The local collection should be storing the same thing that's being stored remotely, disconnected from any prototype.
> 2. The object is flattened so it's not even the object I intended to save but an aberration of it, because it now contains a function from its prototype.

still exist in Meteor 1.5.1. `EJSON` is coming into play (via DDP) and stripping the function, which explains the differences in `#1`, but I agree it is a bit confusing (especially for newcomers to Meteor, who haven't yet had the chance to dig into how DDP + EJSON work together). `#2` is also a valid point.

I've marked this as `pull-requests-encouraged` to help clear out the issue backlog, but we'll definitely have to tread carefully with regards to addressing these inconsistencies, when it comes to backwards compatibility. These issues have been in place for quite some time, and it's possible that some applications have been built expecting this behaviour.

**Comment by mitar** [comment] 2017-07-31 19:29
I think we should really insert only enumerable fields and no functions when doing an insert. I had many issues because of that in the past. Especially if you use `transform`, you cannot wrap it into a custom object, with methods, change a field, and insert it back. You have to convert it to a plain object that it works well.

**Comment by jamesmillerburgess** [comment] 2018-01-04 21:38
It looks like this issue got fixed at some point. Taking the example from @basaundi and updating to `1.6.1-rc.1` eliminates the properties from `prototype` on the local collection.

The following test also passes on the current `devel` branch:

```
  function Thing() {
    this.a = 1;
  }
  Thing.prototype.b = 2;
  Thing.prototype.c = () => null;
  const before = new Thing();
  c.insert(before);
  const after = c.findOne();
  test.equal(after.a, 1);
  test.equal(after.b, undefined);
  test.equal(after.c, undefined);
```

However, minimongo does preserve own function properties on the object, which are then stripped by mongo the server, so the following does not pass:

```
  c.insert({ a: () => null });
  test.equal(c.findOne().a, undefined);
```

@hwillson I can make a PR for the regression test above. Is the second half of this intended behavior, or should I make a PR to change it?

**Closed** 2018-01-10 16:44 UTC
Labels: Impact:few, Project:Minimongo, Severity:has-workaround, bug, confirmed, pull-requests-encouraged
