### ISSUE TITLE
Error: Match error: Failed Match.OneOf or Match.Optional validation

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5712] opened 2015-11-26 03:54 UTC
I'm getting an error like this when Meteor tries to compile my app code:

```
W20151125-19:51:41.790(-8)? (STDERR)
W20151125-19:51:41.790(-8)? (STDERR) /home/trusktr/.meteor/packages/meteor-tool/.1.1.10.17l30qr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-li
b/node_modules/fibers/future.js:245
W20151125-19:51:41.790(-8)? (STDERR)                                            throw(ex);
W20151125-19:51:41.790(-8)? (STDERR)                                                  ^
W20151125-19:51:41.828(-8)? (STDERR) Error: Match error: Failed Match.OneOf or Match.Optional validation
W20151125-19:51:41.828(-8)? (STDERR)     at check (packages/check/match.js:33:1)
W20151125-19:51:41.828(-8)? (STDERR)     at [object Object]._.extend._getFindOptions (packages/mongo/collection.js:248:1)
W20151125-19:51:41.828(-8)? (STDERR)     at [object Object]._.extend.find (packages/mongo/collection.js:284:1)
W20151125-19:51:41.828(-8)? (STDERR)     at exposePollingDriver (packages/meteorhacks_meteorx/lib/mongo-livedata.js:24:1)
W20151125-19:51:41.828(-8)? (STDERR)     at exposeMongoLivedata (packages/meteorhacks_meteorx/lib/mongo-livedata.js:11:1)
W20151125-19:51:41.828(-8)? (STDERR)     at packages/meteorhacks_meteorx/lib/server.js:22:1
W20151125-19:51:41.829(-8)? (STDERR)     at runWithAFiber (packages/meteorhacks_meteorx/lib/server.js:33:1)
W20151125-19:51:41.829(-8)? (STDERR)     at Package (packages/meteorhacks_meteorx/lib/server.js:21:1)
W20151125-19:51:41.829(-8)? (STDERR)     at /home/trusktr/src/MetaEnterprises+whitespace/.meteor/local/build/programs/server/boot.js:249:5
```

Any idea what it might mean? It seems like an error in Meteor code as opposed to my app.

**Comment by trusktr** [comment] 2015-11-26 03:55
Line 249 in the `boot.js` file looks like this:

```js
  // run the user startup hooks.  other calls to startup() during this can still
  // add hooks to the end.
  while (__meteor_bootstrap__.startupHooks.length) {
    var hook = __meteor_bootstrap__.startupHooks.shift();
    hook(); // <-- RIGHT HERE
  }
  // Setting this to null tells Meteor.startup to call hooks immediately.
  __meteor_bootstrap__.startupHooks = null;
```

**Comment by trusktr** [comment] 2015-11-26 08:56
Alright, here's a clue to what's causing it. I have a file in my app, `client/entry.js`. When it contains [this content](http://trusktr.io:7777/qivopucume), I get no error. When I prepend [some code](http://trusktr.io:7777/ekigugavuh) to the beginning of it [like this](http://trusktr.io:7777/misiyomomu), the error happens. The code that I'm prepending is code released by Babel, the `dist/polyfill.js` file of the `babel-polyfill` package on NPM.

Something in that supposedly valid code that I'm prepending is causing Meteor to error.

**Comment by trusktr** [comment] 2015-11-29 00:58
@benjamn @glasser Any ideas by chance?

**Comment by glasser** [comment] 2015-11-29 06:28
From the stack trace, it looks like a bug in meteorhacks:meteor.

**Comment by trusktr** [comment] 2015-11-30 21:37
@arunoda Any ideas?

**Comment by arunoda** [comment] 2015-11-30 22:38
@trusktr this is the related code: https://github.com/meteorhacks/meteorx/blob/master/lib/mongo-livedata.js#L24

I can't find anything wrong there. 

Could you send me a sample repo where I can work on.

**Comment by glasser** [comment] 2015-12-01 00:01
Could this be something weird where Number is being redefined somewhere?

As Arunoda says, a full reproduction (ideally minimal) is probably
necessary for further progress.

**Comment by arunoda** [comment] 2015-12-01 04:44
@trusktr as glasser mentioned, I assume Number is defined again in a polyfill.

**Comment by trusktr** [comment] 2015-12-01 06:21
@arunoda Here's the reproduction: https://github.com/trusktr/meteor/tree/issue-5712

The app will run, then if you uncomment `meteorhacks:kadira` in .meteor/packages the error will happen.

While `meteorhacks:kadira` is disabled and the app runs, you can look in Chrome Inspector's Sources tab at the file `localhost:3000/packages/rocket_module.js` which has the code that causes the problem.

For reference, the relevant code is also viewable in `.meteor/local/rocket-module/platform-builds/web.browser/built/shared-modules.js`, which contains Babel's polyfill. I suppose this file is being loaded as part of `rocket:module` before `meteorhacks:meteorx`.

Is it indeed the polyfilling of Number that causes this?

**Comment by trusktr** [comment] 2015-12-01 19:01
@arunoda I updated the [repro](https://github.com/trusktr/meteor/tree/issue-5712) (delete and re-clone). There was a bug in rocket:module that would give you a second irrelevant error, so now it just gives the error in question.

**Comment by glasser** [comment] 2015-12-21 22:20
@benjamn Can you look into this? I think this is a different Number polyfill in `mongo` vs `check`.

**Comment by stubailo** [comment] 2016-01-05 23:10
Hi ben - bumping this, probably a real bug?

**Comment by benjamn** [comment] 2016-01-06 00:06
Thanks for assigning it to me—I'll take a look.

**Comment by YsnKsy** [comment] 2016-01-13 04:36
I've got the same problem

![meteorbug](https://cloud.githubusercontent.com/assets/5409223/12285168/36297c42-b9af-11e5-864d-0188626cc4f6.jpg)

**Comment by atoftegaard** [comment] 2016-02-03 08:17
Any news on progress, or perhaps a workaround to still be able to use kadira?

**Comment by Lenin7** [comment] 2016-02-07 23:33
This seems to be an issue with multiple meteor packages. Any updates?

**Comment by slaphead** [comment] 2016-09-21 17:07
Any more news on this? I am getting this issue still when trying to run kadira and have a reference to Babel-polyfill.

**Comment by smeijer** [comment] 2016-09-22 10:00
@slaphead , the problem lies in 

> and have a reference to Babel-polyfill.

Don't import the polyfill and you're all set. This is what was causing troubles for me as well.

**Comment by slaphead** [comment] 2016-09-22 21:53
The biggest problem is I am using a package that does the import, so removing it is not an option. Sorry I did not give a proper explanation. Essentially I am using simple-schema 2.0, which does the require to polyfill, so I am a bit stuck.

**Comment by joetidee** [comment] 2016-11-01 19:37
i'm still getting this error in Meteor 1.4.1.2

**Comment by abernix** [comment] 2016-11-21 10:08
This does not seem like it is related to Meteor, or if it was, I'm not sure this is relevant anymore.

@trusktr, Can this be closed?  @slaphead, are you still experiencing this [in Meteor 1.4.2.3](https://github.com/meteor/meteor/blob/devel/History.md)?

**Comment by trusktr** [comment] 2016-11-21 17:25
It is outdated, and I am not developing rocket:module anymore, and haven't
had these errors in current apps I work on, so just close.

**Comment by abernix** [comment] 2016-11-21 18:17
Thanks, @trusktr!  Happy to reopen if someone is still experiencing but please also note that this error can come from other places other than mongo and _usually_ indicates a legitimately mis-passed value to a method (or similar), even if that was NOT the case in this particular issue.

**Closed by abernix** 2016-11-21 18:17 UTC
Labels: Project:JS Environment

**Comment by ilinyevg** [comment] 2018-07-05 23:46
+1 
errorClass {message: "Match error: Failed Match.OneOf, Match.Maybe or Ma…", path: "", sanitizedError: errorClass, errorType: "Match.Error", stack: "Error: Match error: Failed Match.OneOf, Match.Mayb…"}

**Comment by CaptainN** [comment] 2018-07-06 03:55
In my case one of my autovalue fields was trying to access a data source (Meteor.users) and that was causing the error. I ended up moving that out of the autoform, and handling the query at startup, then using the result in the autovalue. I found a workaround, but I still don't know why it was triggering this error.

**Comment by aliogaili** [comment] 2019-06-27 12:34
I'm seeing the same error only in IE11, works find on modern browsers.

**Comment by aliogaili** [comment] 2019-06-27 17:54
I think the issue is with the check library and specifically this line [here](https://github.com/meteor/meteor/blob/bf24ef3cb67ae05bf13b66d51ad7b72ce6c06612/packages/check/match.js#L339) where a recursive call is happening to a potentially undefined values. At least for me, the issue went away when I removed the undefined from the pattern.

**Comment by emaciel10** [comment] 2020-03-25 01:13
@aliogaili did you ever resolve this issue on ie11? We are seeing this same issue right now and struggling to find a fix for it.

**Comment by KirillTertunov** [comment] 2021-11-22 11:49
> @aliogaili did you ever resolve this issue on ie11? We are seeing this same issue right now and struggling to find a fix for it.

Have you already found out a solution for IE11?
