### ISSUE TITLE
Meteor crashed and shut down when working on front-end

### ISSUE THREAD

**Issue by saginadir** [meteor/meteor#5995] opened 2016-01-14 09:08 UTC
Not sure if this will help, was working on the client side, editing html

Client side stopped refreshing, looked in console and saw an exception that caused a crash and shut down of meteor, here's the stack:

/Users/saginadir/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
                        throw(ex);
                              ^
Error: EBADF, fstat
    at Object.Future.wait (/Users/saginadir/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as readFile](/tools/fs/files.js:1334:20)
    at readFile (/tools/fs/watch.js:243:18)
    at Watcher._fireIfFileChanged (/tools/fs/watch.js:372:20)
    at /tools/fs/watch.js:440:12
    at Function._.each._.forEach (/Users/saginadir/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at Watcher._startFileWatches (/tools/fs/watch.js:429:7)
    at new Watcher (/tools/fs/watch.js:355:10)
    at setupClientWatcher (/tools/runners/run-app.js:758:23)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:801:9)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12
    - - - - -

**Comment by tmeasday** [comment] 2016-01-19 23:05
Thanks for the bug report @saginadir.

Has this happened repeatedly or was it a once off? It sounds like it might have been a weird timing issue where you deleted a HTML file right as the watcher was trying to read it perhaps, although I'm not sure.

If it is a repeated issue do you have any idea how to reproduce it?

**Comment by saginadir** [comment] 2016-01-20 16:11
Thanks for responding @tmeasday 

Working on PhpStorm
Happened just once.

Steps to reproduce:
Edit files under /client/ directory

Sorry for lack of other information :)

**Comment by jaysondaquer** [comment] 2016-03-11 06:15
HI Guys,

Any updates on this one? we're also experiencing some weird issue here.. Meteor just shuts down without any error or something. We think that we added something that maybe causing the build process to crash but we're not able to track it down coz its not providing any error logs

**Comment by tmeasday** [comment] 2016-03-12 00:06
There's really not a lot we can do without some more information / ideally some kind of reproduction.

I appreciate it's annoying from your perspective though!

**Comment by JuLoc88** [comment] 2016-03-12 22:35
I start up my meteor app.
Do nothing and wait for 20 seconds.
App crashes with this error.

/Users/Julian/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: UNKNOWN, open '/Users/Julian/projects/my_app/private/node_modules/transformers/node_modules/source-map/lib/source-map/source-map-generator.js'
    at Object.Future.wait (/Users/Julian/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as readFile] (/tools/fs/files.js:1334:20)
    at readFile (/tools/fs/watch.js:243:18)
    at Watcher._fireIfFileChanged (/tools/fs/watch.js:372:20)
    at onWatchEvent (/tools/fs/watch.js:517:16)
    at [object Object].<anonymous> (/tools/utils/func-utils.js:35:18)
    at /tools/utils/fiber-helpers.js:158:12
    - - - - -

Looks kind of like the report above, but I thought I would share.

Does my file structure matter? I have my app structured in my private folder and I have gulp tasks to move files to the client, server, lib, and public folders meteor will use.

**Comment by JuLoc88** [comment] 2016-03-12 22:42
After reading the Meteor documentation and what it had to say about node_modules I moved my node_modules dir out of private and back into the main app dir where all my other folders are (client, lib, private, public, server, and node_modules now). 

My app does not crash anymore so hopefully this information may help some of you!

**Comment by ffxsam** [comment] 2016-04-27 19:03
Same here, but error is thrown from the promise code:

```
/Users/samh/.meteor/packages/templating/.1.1.9.1h5n3gh++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: EBADF, fstat
```

I can't replicate it. It's totally sporadic, and rarely occurs.

**Comment by CaptainChemist** [comment] 2016-05-25 15:44
Was this resolved? I am having this exact issue.

**Comment by abernix** [comment] 2016-05-25 16:26
@CaptainChemist Can you please provide many more details?  How many times has this happened to you?  Do you have a working, reliable reproduction where this happens over and over again? (If so, please make a new project out of it and upload it to Git so someone can look at it!) Do you have your `node_modules` inside your public directory as one user above did?  What OS are you on?  What were you doing when it happened?

On this particular (still open) issue just saying you're "having this exact issue" is too vague to provide any help.

**Comment by CaptainChemist** [comment] 2016-05-25 20:09
@abernix Totally fair, sorry for the lack of detail. I can reproduce this issue by starting with the meteor base package from Meteor Chef:
https://themeteorchef.com/base/

The problem is that meteor will start and work for about 20 seconds and then quit. The exact error is:
```
/Users/user/.meteor/packages/templating/.1.1.9.1h5n3gh++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: UNKNOWN, readdir '/Users/user/Desktop/base/node_modules/npm/node_modules/fstream'
```

I was able to fix the issue by the following command:
`meteor --release 1.3.1`

**Comment by abernix** [comment] 2016-05-26 06:21
Thanks for the details @CaptainChemist.  Your particular problem is actually a separate issue over here: #4660 (and probably #6952 as related).

**Comment by abernix** [comment] 2017-02-08 11:29
This is a duplicate of #4201 so I'm closing in favor of that older issue with more context.  Please follow that issue for more information and thanks for opening this originally!

**Closed by abernix** 2017-02-08 11:29 UTC
Labels: bug, Project:Tool
