### ISSUE TITLE
Expire password reset links

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6462] opened 2016-03-11 04:47 UTC
When Eve gains access to Bob's email, a drive-by/automated action is to search for and try using all password reset emails. If Bob has used the link, the link no longer works. However, if Bob does not use the link, I don't think that the link expires over time?

Recommendations:

1. Expire it by default. (`services.password.reset`) Most people use the link right away, but expiring after a day should catch 99% of uses. In the worst case, the user can simply get another reset email sent. For reference, a `setInterval` is used for expiring resume tokens: https://github.com/meteor/meteor/blob/0f98ea22fcc3f10cfd36aba66e531bf22c70f96e/packages/accounts-base/accounts_server.js#L1127
2. Provide a configuration function similar to `Accounts.loginExpirationInDays`: http://docs.meteor.com/#/full/accounts_config

cc @michelfloyd

**Comment by MichelFloyd** [comment] 2016-03-11 17:00
24 hours should be more than adequate. Even 4 hours should cover 99.9% of cases.

**Comment by stubailo** [comment] 2016-03-15 22:19
I think it would be good to add a similar mechanism to expiring resume tokens, but for the password reset tokens. Would someone want to submit a PR for it?

**Comment by alphanso** [comment] 2016-04-16 09:36
I would like to give it a try. Is anybody else working on it?

**Comment by lorensr** [comment] 2016-04-16 14:57
Don't think so!

**Comment by alphanso** [comment] 2016-04-16 19:05
I have created a draft pull request. Just wanted to ensure that approach to fix the issue is correct. Once I get a sign-off, I will add test and update the pull request.

**Comment by lorensr** [comment] 2016-04-17 02:28
On a related note, I think I remember `Accounts.onEmailVerificationLink` logs you in? If so, do those links expire?

**Comment by alphanso** [comment] 2016-04-17 09:11
I checked 
https://github.com/meteor/meteor/blob/devel/packages/accounts-password/password_server.js

It doesn't expire verification link tokens.

**Comment by alphanso** [comment] 2016-04-21 06:31
@stubailo Please have a look at it

**Comment by tmeasday** [comment] 2016-08-04 01:43
Fixed by #7534!

**Closed by tmeasday** 2016-08-04 01:43 UTC
Labels: confirmed, feature, Project:Accounts:Password, pull-requests-encouraged

**Comment by serkandurusoy** [comment] 2016-08-10 12:46
When that PR is used with aldeed:collection2 where a user schema is attached to the users collection, it throws error: After filtering out keys not in the schema, your modifier is now empty.

I'll go ahead and post this over at the collection2 repo, but I thought it would not do harm if also noted here, or perhaps there's something we can do about it!

**Comment by MichelFloyd** [comment] 2016-08-12 04:10
I'm seeing the following possibly related error when deployed to galaxy:

**MongoError: Cannot apply $pull to a non-array value**
```
302z 2016-08-11 20:54:33-07:00 at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
302z
2016-08-11 20:54:33-07:00 at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)
302z
2016-08-11 20:54:33-07:00 at Object.cb (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1015:67)
302z
2016-08-11 20:54:33-07:00 at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:443:18
302z
2016-08-11 20:54:33-07:00 at authenticateStragglers (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:399:16)
302z
2016-08-11 20:54:33-07:00 at [object Object].messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:421:5)
302z
2016-08-11 20:54:33-07:00 at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:294:22)
302z
2016-08-11 20:54:33-07:00 at emitOne (events.js:77:13)
302z
2016-08-11 20:54:33-07:00 at Socket.emit (events.js:169:7)
302z
2016-08-11 20:54:33-07:00 at readableAddChunk (_stream_readable.js:153:18)
302z
2016-08-11 20:54:34-07:00Exception in setInterval callback: MongoError: Cannot apply $pull to a non-array value
302z
2016-08-11 20:54:34-07:00 at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
302z
2016-08-11 20:54:34-07:00 at MongoConnection.<anonymous> (packages/meteor/helpers.js:119:1)
302z
2016-08-11 20:54:34-07:00 at MongoConnection.(anonymous function) (packages/mongo/mongo_driver.js:771:49)
302z
2016-08-11 20:54:34-07:00 at Object.<anonymous> (packages/matb33_collection-hooks/update.js:88:1)
302z
2016-08-11 20:54:34-07:00 at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:120:1)
302z
2016-08-11 20:54:34-07:00 at [object Object].update (packages/mongo/collection.js:589:29)
302z
2016-08-11 20:54:34-07:00 at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:191:1)
302z
2016-08-11 20:54:34-07:00 at AccountsServer.Ap._expirePasswordResetTokens (packages/accounts-base/accounts_server.js:1137:14)
302z
2016-08-11 20:54:34-07:00 at packages/accounts-base/accounts_server.js:1174:14
302z
2016-08-11 20:54:34-07:00 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1
```

**Comment by tmeasday** [comment] 2016-08-15 01:16
@MichelFloyd what values do you have the the database for `services.password.reset` on users? AFAICT they should be arrays.

**Comment by tmeasday** [comment] 2016-08-15 01:59
Ok, I was talking jibe, please ignore me @MichelFloyd

**Comment by tmeasday** [comment] 2016-08-15 02:03
Apologies for this, I had thought the test was actually running `Ap._expirePasswordResetTokens` before merging this, but clearly not.

**Comment by drerichsu** [comment] 2016-08-17 05:08
I get the same issue as MichelFloyd on Galaxy. 

```
2016-08-17 00:54:32-04:00Exception in setInterval callback: MongoError: Cannot apply $pull to a non-array value
crx7
2016-08-17 00:54:32-04:00 at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
crx7
2016-08-17 00:54:32-04:00 at MongoConnection.<anonymous> (packages/meteor/helpers.js:119:1)
crx7
2016-08-17 00:54:32-04:00 at MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:771:49)
crx7
2016-08-17 00:54:32-04:00 at [object Object].update (packages/mongo/collection.js:589:29)
crx7
2016-08-17 00:54:32-04:00 at AccountsServer.Ap._expirePasswordResetTokens (packages/accounts-base/accounts_server.js:1137:14)
crx7
2016-08-17 00:54:32-04:00 at packages/accounts-base/accounts_server.js:1174:14
crx7
2016-08-17 00:54:32-04:00 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
crx7
2016-08-17 00:54:32-04:00 at packages/meteor/timers.js:6:1
crx7
2016-08-17 00:54:32-04:00 at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
crx7
2016-08-17 00:54:32-04:00 - - - - -
crx7
2016-08-17 00:54:32-04:00 at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
crx7
2016-08-17 00:54:32-04:00 at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)
crx7
2016-08-17 00:54:32-04:00 at Object.cb (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1015:67)
crx7
2016-08-17 00:54:32-04:00 at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:443:18
crx7
2016-08-17 00:54:32-04:00 at authenticateStragglers (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:399:16)
crx7
2016-08-17 00:54:32-04:00 at [object Object].messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:421:5)
crx7
2016-08-17 00:54:32-04:00 at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:294:22)
crx7
2016-08-17 00:54:32-04:00 at emitOne (events.js:77:13)
crx7
2016-08-17 00:54:32-04:00 at Socket.emit (events.js:169:7)
crx7
2016-08-17 00:54:32-04:00 at readableAddChunk (_stream_readable.js:153:18)
crx7
```

**Comment by serkandurusoy** [comment] 2016-08-30 02:21
Hmm, @tmeasday is this maybe too early to close this issue since I am now (on 1.4.1.1) getting the following:

```
Exception in setInterval callback: Error: services.password.reset.$or is not allowed by the schema
     at getErrorObject (packages/aldeed_collection2-core/lib/collection2.js:451:1)
     at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:433:1)
     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:185:1)
     at AccountsServer.Ap._expirePasswordResetTokens (packages/accounts-base/accounts_server.js:1137:14)
     at packages/accounts-base/accounts_server.js:1174:14
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at packages/meteor/timers.js:6:1
     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

**Comment by tmeasday** [comment] 2016-08-30 02:28
@serkandurusoy can we open a new issue? That sounds different.
