### ISSUE TITLE
Cannot find module '../plugman/platforms/ios'

### ISSUE THREAD

**Issue by lpender** [meteor/meteor#9040] opened 2017-08-24 15:49 UTC
Os X

After upgrading to Meteor `1.5.2-rc.2`

When running `meteor build`

```
Cannot find module '../plugman/platforms/ios'
```

Did not have this issue in Meteor `1.5.1`

Here is a [full gist](https://gist.github.com/lpender/a0290a68b985b1e489de195310c1ddd8) of the error.

Tried upgrading to cordova 7.0.1 (`npm i -g cordova@7.0.1`) to no avail.

**Comment by klaussner** [comment] 2017-08-31 11:10
This is a [bug](https://github.com/nordnet/cordova-universal-links-plugin/issues/110) in [`cordova-universal-links-plugin`](https://github.com/nordnet/cordova-universal-links-plugin). Cordova was updated to 7.0.1 for Meteor 1.5.2 and `cordova-universal-links-plugin` relies on a deprecated feature that has been [removed](https://github.com/apache/cordova-lib/commit/64fea70ea0554458ebc399f0ad4ba4b534b5cd3f) in the new Cordova version. There is already [a pull request with a fix](https://github.com/nordnet/cordova-universal-links-plugin/pull/114) but it hasn't been merged yet.

As a temporary workaround, you can install the pull request version of the plugin:

```
cordova-universal-links-plugin@https://github.com/aramando/cordova-universal-links-plugin.git#35b3ed7e9a0310b12f1ac92a5159b21ce50eee57
```

**Closed by klaussner** 2017-08-31 11:10 UTC

**Comment by cdcv** [comment] 2018-01-05 15:04
Would someone please indicate how to USE this workaround.
It appears that Meteor effectively no longer works with Android, and this is the only solution.
It would be really great to make it clear how to use it.
I tried what seemed like the most straightforward implementation of this comment (even this wouldn't be clear for someone new to meteor), 
meteor add cordova:cordova-universal-links-plugin@https://github.com/aramando/cordova-universal-links-plugin.git#35b3ed7e9a0310b12f1ac92a5159b21ce50eee57
This did not solve the problem.
Thanks for your help.

**Comment by klaussner** [comment] 2018-01-06 21:59
The command you posted should work. I tried it in a new Meteor 1.6.0.1 project and the `Cannot find module '../plugman/platforms/ios'` error disappeared. 🤔  Can you post the full stack trace of the error you are getting?

**Comment by cdcv** [comment] 2018-01-16 00:42
Still not working.
Here is the full trace.
Thanks for your help.  At the moment, we're completely unable to build.

<universal-links> tag is not set in the config.xml. Universal Links plugin is not going to work.
=> Errors executing Cordova commands:                                              
                                                                                   
   While preparing Cordova project for platform iOS:                               
   Error: Cannot find module '../plugman/platforms/ios'                            
   at Function.Module._resolveFilename (module.js:513:15)
   at Function.Module._load (module.js:463:25)
   at Module.require (module.js:556:17)
   at require (internal/module.js:11:18)
   at Context.requireCordovaModule (/Users/cdecharms/.meteor/packages/meteor-tool/.1.6.0.zkklna.8ta9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/Context.js:77:12)
   at loadProjectFile (/source/lib/ios/xcodePreferences.js:172:30)
   at Object.enableAssociativeDomainsCapability (/source/lib/ios/xcodePreferences.js:33:23)
   at activateUniversalLinksInIos (/source/afterPrepareHook.js:74:25)
   at /source/afterPrepareHook.js:47:11
   at Array.forEach (<anonymous>)
   at run (/source/afterPrepareHook.js:40:17)
   at module.exports (/source/afterPrepareHook.js:17:3)
   at runScriptViaModuleLoader (/Users/cdecharms/.meteor/packages/meteor-tool/.1.6.0.zkklna.8ta9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:189:18)
   at runScript (/Users/cdecharms/.meteor/packages/meteor-tool/.1.6.0.zkklna.8ta9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:165:16)
   at /Users/cdecharms/.meteor/packages/meteor-tool/.1.6.0.zkklna.8ta9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20
   at _fulfilled (/Users/cdecharms/.meteor/packages/meteor-tool/.1.6.0.zkklna.8ta9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done (/Users/cdecharms/.meteor/packages/meteor-tool/.1.6.0.zkklna.8ta9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch (/Users/cdecharms/.meteor/packages/meteor-tool/.1.6.0.zkklna.8ta9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:749:13)
   at /Users/cdecharms/.meteor/packages/meteor-tool/.1.6.0.zkklna.8ta9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:557:44
   at flush (/Users/cdecharms/.meteor/packages/meteor-tool/.1.6.0.zkklna.8ta9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:108:17)
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickCallback (internal/process/next_tick.js:180:9)
                                                                                   
/Users/admin/.meteor/packages/omega_custom-protocol/.3.1.0.fv30zp.l5vig++os+web.browser+web.cordova/plugin.custom-protocol-index-reader.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;

**Comment by klaussner** [comment] 2018-01-28 09:40
@cdcv Do you think you could put together a small reproduction that I can try out? The error seems to be thrown if the Cordova plugin is part of the project (independent of any project code), so maybe it's sufficient to add all plugins from your project to a new `meteor create --bare` project.

**Comment by scottstensland** [comment] 2018-02-25 00:36
I am also getting same error on meteor 1.6.0_1 on High Sierra 

<details>
<summary>

Preparing Cordova project for platform iOS
=> Errors executing Cordova commands:

   While preparing Cordova project for platform iOS:
   Error: Cannot find module '../plugman/platforms/ios'
</summary>


stens@chambord ~/src/github.com/loudthink/loudspeed $ meteor run ios-device --settings config/production.json --mobile-server $ROOT_URL
Opening db file /Users/stens/.meteor/package-metadata/v2.0.1/packages.data.db
Local package version is up-to-date: meteor-tool@1.6.0_1
Opening db file /Users/stens/.meteor/package-metadata/v2.0.1/packages.data.db
Getting installed version for platform android in Cordova project
Getting installed version for platform ios in Cordova project
Checking Cordova requirements for platform iOS
   Checking platform requirements            \
[[[[[ ~/src/github.com/loudthink/loudspeed ]]]]]

=> Started proxy.
Local package version is up-to-date: accounts-base@1.4.0
Local package version is up-to-date: accounts-password@1.5.0
Local package version is up-to-date: aldeed:collection2@2.10.0
Local package version is up-to-date: aldeed:collection2-core@1.2.0
Local package version is up-to-date: aldeed:schema-deny@1.1.0
Local package version is up-to-date: aldeed:schema-index@1.1.1
Local package version is up-to-date: aldeed:simple-schema@1.5.3
Local package version is up-to-date: allow-deny@1.1.0
Local package version is up-to-date: autoupdate@1.3.12
Local package version is up-to-date: babel-compiler@6.24.7
Local package version is up-to-date: babel-runtime@1.1.1
Local package version is up-to-date: base64@1.0.10
Local package version is up-to-date: binary-heap@1.0.10
Local package version is up-to-date: blaze@2.3.2
Local package version is up-to-date: blaze-html-templates@1.1.2
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.3.1
Local package version is up-to-date: caching-compiler@1.1.9
Local package version is up-to-date: caching-html-compiler@1.1.2
Local package version is up-to-date: callback-hook@1.0.10
Local package version is up-to-date: check@1.2.5
Local package version is up-to-date: ddp@1.4.0
Local package version is up-to-date: ddp-client@2.2.0
Local package version is up-to-date: ddp-common@1.3.0
Local package version is up-to-date: ddp-rate-limiter@1.0.7
Local package version is up-to-date: ddp-server@2.1.1
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: diff-sequence@1.0.7
Local package version is up-to-date: dynamic-import@0.2.1
Local package version is up-to-date: ecmascript@0.9.0
Local package version is up-to-date: ecmascript-runtime@0.5.0
Local package version is up-to-date: ecmascript-runtime-client@0.5.0
Local package version is up-to-date: ecmascript-runtime-server@0.5.0
Local package version is up-to-date: ejson@1.1.0
Local package version is up-to-date: email@1.2.3
Local package version is up-to-date: es5-shim@4.6.15
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.3.0
Local package version is up-to-date: id-map@1.0.9
Local package version is up-to-date: jquery@1.11.10
Local package version is up-to-date: launch-screen@1.1.1
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: localstorage@1.2.0
Local package version is up-to-date: logging@1.1.19
Local package version is up-to-date: mdg:validation-error@0.5.1
Local package version is up-to-date: meteor@1.8.2
Local package version is up-to-date: meteor-base@1.2.0
Local package version is up-to-date: minifier-css@1.2.16
Local package version is up-to-date: minifier-js@2.2.2
Local package version is up-to-date: minimongo@1.4.3
Local package version is up-to-date: mobile-experience@1.0.5
Local package version is up-to-date: mobile-status-bar@1.0.14
Local package version is up-to-date: modules@0.11.1
Local package version is up-to-date: modules-runtime@0.9.1
Local package version is up-to-date: mongo@1.3.1
Local package version is up-to-date: mongo-dev-server@1.1.0
Local package version is up-to-date: mongo-id@1.0.6
Local package version is up-to-date: npm-bcrypt@0.9.3
Local package version is up-to-date: npm-mongo@2.2.33
Local package version is up-to-date: observe-sequence@1.0.16
Local package version is up-to-date: ordered-dict@1.0.9
Local package version is up-to-date: peerlibrary:blocking@0.5.2
Local package version is up-to-date: peerlibrary:xml2js@0.4.8_1
Local package version is up-to-date: promise@0.10.0
Local package version is up-to-date: raix:eventemitter@0.1.3
Local package version is up-to-date: random@1.0.10
Local package version is up-to-date: rate-limit@1.0.8
Local package version is up-to-date: reactive-dict@1.2.0
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.1.11
Local package version is up-to-date: retry@1.0.9
Local package version is up-to-date: routepolicy@1.0.12
Local package version is up-to-date: service-configuration@1.0.11
Local package version is up-to-date: session@1.1.7
Local package version is up-to-date: sha@1.0.9
Local package version is up-to-date: shell-server@0.3.1
Local package version is up-to-date: spacebars@1.0.15
Local package version is up-to-date: spacebars-compiler@1.1.3
Local package version is up-to-date: srp@1.0.10
Local package version is up-to-date: standard-minifier-css@1.3.5
Local package version is up-to-date: standard-minifier-js@2.2.3
Local package version is up-to-date: stylus@2.513.13
Local package version is up-to-date: templating@1.3.2
Local package version is up-to-date: templating-compiler@1.3.3
Local package version is up-to-date: templating-runtime@1.3.2
Local package version is up-to-date: templating-tools@1.1.2
Local package version is up-to-date: tracker@1.1.3
Local package version is up-to-date: ui@1.0.13
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: url@1.1.0
Local package version is up-to-date: webapp@1.4.0
Local package version is up-to-date: webapp-hashing@1.0.9
=> Meteor 1.6.1 is available. Update this project with 'meteor update'.
Preparing Cordova project from app bundle
Processing mobile-config.js
Copying resources for mobile apps
Writing new config.xml
Reinstalling Cordova plugins added from the local path
Adding plugin cordova-plugin-splashscreen@4.0.3 to Cordova project
=> Started MongoDB.
Adding plugin cordova-plugin-whitelist@1.3.2 to Cordova project
Adding plugin cordova-plugin-wkwebview-engine@1.1.3 to Cordova project
Adding plugin cordova-plugin-meteor-webapp@1.4.1 to Cordova project
Subproject Path: CordovaLibns                [====                     ] 14% 147.7s
Adding plugin cordova-plugin-statusbar@2.2.3 to Cordova project
Adding plugin cordova-plugin-compat@1.0.0 to Cordova project
Adding plugin cordova-plugin-customurlscheme@4.2.0 to Cordova project
Adding plugin cordova-plugin-device@1.1.6 to Cordova project
Adding plugin cordova-plugin-device-name@1.0.0 to Cordova project
Adding plugin cordova-plugin-file@4.3.3 to Cordova project
Adding plugin cordova-plugin-file-transfer@1.6.3 to Cordova project
npm WARN deprecated cordova-plugin-file-transfer@1.6.3: This plugin has been deprecated
Adding plugin cordova-plugin-fullscreen@1.1.0 to Cordova project
Adding plugin cordova-plugin-inappbrowser@1.7.1 to Cordova project
Adding plugin cordova-plugin-ios-non-exempt-encryption@1.0.0 to Cordova project
Adding plugin cordova-plugin-vibration@2.1.5 to Cordova project
Adding plugin cordova-universal-links-plugin@1.2.1 to Cordova project
Installing dependency packages:              [==================        ] 71% 14.7s
{
  "mkpath": ">=1.0.0",
  "xml2js": ">=0.4",
  "rimraf": ">=2.4",
  "node-version-compare": ">=1.0.1",
  "plist": ">=1.2.0"
}
Adding plugin ionic-plugin-keyboard@2.2.1 to Cordova project
Adding plugin /Users/stens/src/github.com/loudthink/loudspeed/packages/plugins/org.wbt11a.nativecamera to Cordova project
Adding plugin phonegap-plugin-push@1.8.0 to Cordova project
Subproject Path: CordovaLibns                [=======================    ] 85% 8.4s
Adding plugin /Users/stens/src/github.com/loudthink/loudspeed/packages/plugins/phonegap-plugin-ringer-mode to Cordova project
Adding plugin /Users/stens/src/github.com/loudthink/loudspeed/packages/plugins/cordova-silent-mode to Cordova project
Preparing Cordova project for platform iOS
=> Errors executing Cordova commands:

   While preparing Cordova project for platform iOS:
   Error: Cannot find module '../plugman/platforms/ios'
   at Function.Module._resolveFilename (module.js:536:15)
   at Function.Module._load (module.js:466:25)
   at Module.require (module.js:579:17)
   at require (internal/module.js:11:18)
   at Context.requireCordovaModule (/Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/Context.js:77:12)
   at loadProjectFile (/Users/stens/src/github.com/loudthink/loudspeed/.meteor/local/cordova-build/plugins/cordova-universal-links-plugin/hooks/lib/ios/xcodePreferences.js:145:28)
   at Object.enableAssociativeDomainsCapability (/Users/stens/src/github.com/loudthink/loudspeed/.meteor/local/cordova-build/plugins/cordova-universal-links-plugin/hooks/lib/ios/xcodePreferences.js:30:21)
   at activateUniversalLinksInIos (/Users/stens/src/github.com/loudthink/loudspeed/.meteor/local/cordova-build/plugins/cordova-universal-links-plugin/hooks/afterPrepareHook.js:79:25)
   at /Users/stens/src/github.com/loudthink/loudspeed/.meteor/local/cordova-build/plugins/cordova-universal-links-plugin/hooks/afterPrepareHook.js:50:11
   at Array.forEach (<anonymous>)
   at run (/Users/stens/src/github.com/loudthink/loudspeed/.meteor/local/cordova-build/plugins/cordova-universal-links-plugin/hooks/afterPrepareHook.js:41:17)
   at module.exports (/Users/stens/src/github.com/loudthink/loudspeed/.meteor/local/cordova-build/plugins/cordova-universal-links-plugin/hooks/afterPrepareHook.js:18:3)
   at runScriptViaModuleLoader (/Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:189:18)
   at runScript (/Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:165:16)
   at /Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20
   at _fulfilled (/Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done (/Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch (/Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:749:13)
   at /Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:810:14
   at flush (/Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:108:17)
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickCallback (internal/process/next_tick.js:180:9)
   => awaited here:
   at Function.Promise.await (/Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
   at Promise.asyncApply (/tools/cordova/project.js:241:7)
   at /Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
   at Function.Promise.await (/Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:725:14)
   at CordovaProject.prepareForPlatform (/tools/cordova/project.js:239:10)
   at buildmessage.enterJob (/tools/cordova/runner.js:86:29)
   at /tools/utils/buildmessage.js:359:18
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at CordovaRunner.prepareProject (/tools/cordova/runner.js:77:18)
   at buildmessage.capture (/tools/runners/run-app.js:670:25)
   at /tools/utils/buildmessage.js:271:13
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:264:29
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:262:18
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:253:23
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.capture (/tools/utils/buildmessage.js:252:19)
   at AppRunner._runOnce (/tools/runners/run-app.js:669:39)
   at AppRunner._fiber (/tools/runners/run-app.js:880:28)
   at /tools/runners/run-app.js:408:12

/Users/stens/.meteor/packages/meteor-tool/.1.6.0_1.1sab8uw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^
ExitWithCode:1
stens@chambord ~/src/github.com/loudthink/loudspeed $
stens@chambord ~/src/github.com/loudthink/loudspeed $
stens@chambord ~/src/github.com/loudthink/loudspeed $     meteor list-platforms
Opening db file /Users/stens/.meteor/package-metadata/v2.0.1/packages.data.db
Local package version is up-to-date: meteor-tool@1.6.0_1
Opening db file /Users/stens/.meteor/package-metadata/v2.0.1/packages.data.db
android
browser
ios
server

</details>
