### ISSUE TITLE
[1.0.2.1] meteor update [--packages-only] fails

### ISSUE THREAD

**Issue by jamgold** [meteor/meteor#3393] opened 2014-12-30 20:53 UTC
I have two projects successively upgraded from previous meteor releases, in which meteor list shows new versions for certain packages. When I issue the meteor update (with or without optional --packages-only) it tells me it updates the outdated packages, but never does. 

Then new package versions get downloaded to $HOME/.meteor/packages (with their directory names changed with all : replaced with _ [when did that happen]) but the meteor list command keeps insisting there are new versions

```
 meteor update --packages-only
                                                                                   
Changes to your project's package version selections from updating package versions:
                                              
aldeed:autoform            upgraded from 4.2.1 to 4.2.2
aldeed:simple-schema       upgraded from 1.2.0 to 1.3.0
momentjs:moment            added, version 2.8.4
mrt:moment                 upgraded from 2.6.0 to 2.8.1
natestrauser:font-awesome  upgraded from 4.2.0 to 4.2.0_1

 meteor list | grep '*'       
aldeed:autoform                    4.2.1* Easily create forms with automatic ...
aldeed:simple-schema               1.2.0* A simple schema validation object w...
mrt:moment                         2.6.0* Moment.js, a JavaScript date librar...
natestrauser:font-awesome          4.2.0* Latest version Font-Awesome loaded ...
* New versions of these packages are available! Run 'meteor update' to try to
```
checking the .meteor/versions file it indeed lists those packages with the old version, even though $HOME/.meteor/packages has the newer versions downloaded.

How can I fix this? I tried to create a reproduction with a newly created project but can not reproduce this. There has to be a file from previous versions of meteor that confuses the new/latest meteor version when it comes to package versions ...

**Comment by laosb** [comment] 2015-01-03 02:51
Got the same issue.

**Comment by jamgold** [comment] 2015-01-08 00:44
I just noticed at the end of the meteor list command the following blurb
```
* New versions of these packages are available! Run 'meteor update' to try to update those packages to their latest versions. If your packages
  cannot be updated further, try typing `meteor add <package>@<newVersion>` to see more information.
```
Just following those instructions I was able to upgrade the packages just fine. Still don't understand why meteor update didn't update them, but I can live with this for now.

**Comment by ndarilek** [comment] 2015-02-19 16:43
Noticed this as well, but when you "meteor add package@newversion" and look at .meteor/packages, it looks like the package is locked to the new version. Am I mistaken? I certainly don't want a version conflict, but as of now my project is under development and I can afford to make version upgrades, and would rather not tie myself to individual versions until I go to production and that becomes more important.

**Comment by glasser** [comment] 2015-02-19 17:43
It locks you into a *compatible* version, so you won't upgrade from 1.2.3 to 2.0.0 but you can upgrade to 1.4.5. A precise version lock uses `@=` instead.

**Comment by ndarilek** [comment] 2015-02-19 18:03
Gotcha. So here's my question. I install a package in an app I'm
developing. Over time, an upgrade is released. I run:

`meteor list`

and it reveals the update, telling me to run:

`meteor update`

I run:

`meteor update`

and am told that the package has been updated.

My assumptions are two-fold. First, I assume that updating means that
.meteor/versions have changed. Next, I assume that `meteor update` will
have no action on next run. Both of these are false. I can `meteor
update` again and again and am told that packages have been updated, but
.meteor/versions is unchanged. Am I misunderstanding something? I
understand Semver so don't think that is the issue. It just seems that
if `meteor update` tells me that packages have been updated, then
.meteor/versions should be changed.

My temporary workaround is to rm .meteor/local .meteor/versions then do
another meteor update. This redownloads everything and writes a new
.meteor/versions file with the latest, desired packages. Is this how I
should be upgrading my Meteor app before I'm in production and versions
are locked down? It just seems like a bug that .meteor/versions isn't
updated, so I'm surprised this issue is closed.

Thanks.

**Comment by jamgold** [comment] 2015-02-25 00:57
I know this was closed, but I still don't understand why
```
meteor update

This project is already at Meteor 1.0.3.2-rc.0, which is newer than the latest release.
                                              
Changes to your project's package version selections from updating package versions:
                                              
meteorhacks:kadira  upgraded from 2.19.2 to 2.19.6
```
it says the package was updated and restarts the server, but when I look
```
meteor list|grep kadira
meteorhacks:kadira                 2.19.2* Performance Monitoring for Meteor
```
the old version of the package is still in use by my project. This is very confusing

**Comment by glasser** [comment] 2015-03-03 20:07
@jamgold I think this new issue (where you run update at the same time as `meteor run`) is a duplicate of #3582.

**Closed by glasser** 2015-03-03 20:07 UTC
Labels: Project:Tool
