### ISSUE TITLE
run ios-device will not work if the path to .xcodeproj includes directories with spaces in name

### ISSUE THREAD

**Issue by cameroncruz** [meteor/meteor#4000] opened 2015-03-22 19:50 UTC
When developing my meteor app I tried to run my app with meteor run ios-device.  However, I kept receiving the error message "Could not open your project in xcode."  

After troubleshooting, I noticed meteor would run the command with the file path and not account for any spaces in any directory names.

Thus, if I ran the same command with the path meteor used, ie 'open /Users/NAME/Documents/My Directory/APPNAME/.meteor/local/cordova-build/platforms/ios/APPNAME.xcodeproj' in another terminal, I would receive an error message:

"The files /User/NAME/Documents/My and /Users/NAME/Documents/My Directory/APPNAME/.meteor/local/cordova-build/platforms/ios/APPNAME.xcodeproj do not exist."

When I renamed the directory to /My_Directory/, the command meteor run ios-device was successful.

Not a huge deal, but I've noticed other people online have surfaced with the same issue.  Whenever this happens, meteor simply directs you to the directions on how to run the app on an iOS device.  It would be nice if the directions included a note/warning to be aware that your path must include directories with no spaces in the names.  It might lessen much confusion.

**Comment by glasser** [comment] 2015-03-24 20:35
Duplicate of #3367 (right?)

**Closed by glasser** 2015-03-24 20:35 UTC
Labels: Project:Mobile

**Comment by cameroncruz** [comment] 2015-03-25 02:15
Sort of.  #3367 focuses on how the Meteor app name cannot have non-alphanumeric characters.  However, the file path to the .xcodeproj can have non-alphanumeric characters, just no spaces, as they won't be escaped.

`% It is ios-device, just opening the Xcode project with `open` command`
`% Running synchronously:  sh [ '-c',`
`  'open /Users/myname/Documents/Foo/Example Directory/appname/.meteor/local/cordova-build/platforms/ios/*.xcodeproj' ]`

`Could not open your project in Xcode.`

The directory called 'Example Directory' is not escaped like this: `/Example\ Directory/`.  So, the `open` command cannot find the .xcodeproj.  

An easy fix might be to put quotes around the entire file path string before using it with the `open` command.  Or at least a short note on the [instructions to run on an iOS device](https://github.com/meteor/meteor/wiki/How-to-run-your-app-on-an-iOS-device) telling people not to use spaces in the names of their directories that are in the path to their Meteor app.
