### ISSUE TITLE
v1.0.4 regression (sort of): How to get reference to block template from content block?

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#3973] opened 2015-03-19 22:08 UTC
The v1.0.4 notes say

> Fix bug where, when a helper or event handler was called from inside a custom block helper, Template.instance() returned the Template.contentBlock template instead of the actual user-defined template, making it difficult to use Template.instance() for local template state.

While this may have been a bug, I was actually using it to work back to the block template instance from within a content block. Now I can't figure out how to do that, so it seems like a regression.

For example with

``` js
<template name="autoForm">
  <form {{atts}}>
    {{> Template.contentBlock ..}}
  </form>
</template>
```

I have a helper for use within the `{{#autoForm}}{{/autoForm}}` block, which gets the `autoForm` template instance using code like this:

``` js
var instance = Template.instance();
if (!instance) {
  return {};
}

var view = instance.view;
while (view && view.name !== 'Template.autoForm') {
  view = view.originalParentView || view.parentView;
}
```

But since `instance` is now returning the outer instance, we're already past 'Template.autoForm' in the hierarchy. How can I get the template instance I want?

**Comment by aldeed** [comment] 2015-03-20 20:10
OK, I think I found a solution using:

```js
var view = Blaze.currentView;
    while (view && view.name !== 'Template.blockTest') {
      view = view.originalParentView || view.parentView;
    }
```

I'll still leave this open for now since I think this should be explained better in the release notes. It's described as a "fix" but it completely broke my package, so I think it should be called out with a description of how to adjust code that relied on the old behavior.

**Comment by stubailo** [comment] 2015-03-24 21:56
The documentation is vague on this, but `Template.instance()` was intended to be a replacement for `this` inside the lifecycle callbacks and the `template` argument in event handlers, and the same thing inside helpers, which didn't exist previously.

I think there is a pretty good case to be made for it being an actual bug that was fixed. Furthermore, the fact that block helpers are templates is an implementation detail for everyone but package authors.

Your workaround is correct - iterating up the views until you find the one you are looking for is the right way to do it. We should include it in the release notes.

**Comment by mitar** [comment] 2015-04-25 05:42
You can use [`template.parent(1, true)`](https://github.com/aldeed/meteor-template-extension#templateparentnumlevels-includeblockhelpers) to go through template instances, including the block helpers:

```javascript
template = Template.instance();
while (template && template.view.name !== 'Template.blockTest') {
  template = template.parent(1, true);
}
return template || {};
```

**Comment by hwillson** [comment] 2016-11-22 12:30
I've migrated this issue over to meteor/blaze#170. Closing - thanks!

**Closed by hwillson** 2016-11-22 12:30 UTC
Labels: Project:Blaze, Project:Docs
