### ISSUE TITLE
Hangs on building application

### ISSUE THREAD

**Issue by cranesandcaff** [meteor/meteor#5275] opened 2015-09-24 16:18 UTC
**_2 Upvotes**_ Since updating to 1.2.X, Meteor will hang on building some times. Difficult to reproduce. I started a new meteor app to test it, it ran fine for some time then stopped refreshing. `ctrl-c` wouldn't kill it, so I killed it with activity monitor. After that it will refuse to build unless I start a new app. It's also using 100% of CPU.
![screen shot 2015-09-24 at 12 18 08 pm](https://cloud.githubusercontent.com/assets/1912168/10079134/5bf6a6b6-62b6-11e5-88bc-95ac0839091f.png)

**Comment by cranesandcaff** [comment] 2015-09-24 16:19
Hangs when running meteor debug as well.

**Comment by cranesandcaff** [comment] 2015-09-24 16:24
Running `meteor reset` claims Meteor is running, running `meteor` again will start the build process again but same hang. So something is telling it that meteor is running stopping reset but not stopping it from starting the app.

**Comment by c316** [comment] 2015-09-24 16:26
+1 I'm getting this issue to. It happened to me right after I added the ```ecmascript``` package. 

I have to kill the process 
    kill -9 `ps ax | grep node | grep meteor | awk '{print $1}'`

If I then removed the ```ecmascript``` package and start meteor again it works fine. 

It freezes at 
    
    => Started proxy.                             
    Acessing files with templating (for...  |

**Comment by cranesandcaff** [comment] 2015-09-24 16:30
I'm using `pbastowski:angular-babel` not `ecmascript` with Angular.

Mine gets to 

    => Started proxy.
    => Started MongoDB.
    Babel active on file extensions: es6.js, es6, jsx
    Building the application                  /

Then freezes.

**Comment by c316** [comment] 2015-09-24 16:31
@cranesandcaff What happens if you run ```meteor --verbose```

Mine gets to 

    ...
    Local package version is up-to-date: wylio:mandrill@0.3.0
    Local package version is up-to-date: wylio:winston-papertrail@0.1.2
    Local package version is up-to-date: zimme:iron-router-active@1.0.4
    Building for web.browser                  |

**Comment by cranesandcaff** [comment] 2015-09-24 16:33
Babel active on file extensions: es6.js, es6, jsx
    Doing HTTP request:  POST
    https://www.meteor.com/oauth2/authorize?state=da4ef2ddae97a0b10e4c14e2db218a4f&response_type=code&client_id=LdpZEt7ubqXAfkDJ2&redirect_uri=https%3A%2F%2Factivity.meteor.com%2F_oauth%2Fmeteor-developer%3Fclose
    Building the application                  |

**Comment by cranesandcaff** [comment] 2015-09-24 16:33
I removed both ecmascript and angular-babel. Same issue, same hang, same place.

**Comment by c316** [comment] 2015-09-24 16:35
Do any or your packages also have ecmascript dependencies?

**Comment by cranesandcaff** [comment] 2015-09-24 16:36
Looks like it according to `meteor --verbose`

**Comment by cranesandcaff** [comment] 2015-09-24 16:51
Is there any way to downgrade?

**Comment by cranesandcaff** [comment] 2015-09-24 17:00
I removed one of my templates and it worked. No idea what or why. Are you using angular or angular material @c316 ?

**Comment by c316** [comment] 2015-09-24 17:02
@cranesandcaff No, I'm not. I wonder if this fails when there is some ecmascript 2015 in use in the files. I only had one ```let``` I was trying out, but this is way to much work for just trying to incorporate something that simple. Was there any ecmascript 2015 in use in that template?

**Comment by ciwolsey** [comment] 2015-09-25 01:03
I'm having this issue too and I feel like it's related to the ecmascript package.

**Comment by ciwolsey** [comment] 2015-09-25 01:25
I think this is half user error, half bug. I believe the ecmascript package is not intended to be added as it's there by default. Check:
```
meteor --verbose
```
You'll notice the package is loaded. Adding it manually should not break the app as it does though.

The way I got my app up and running again was to remove every reference to the ecmascript package I could. Any packages you create now also have, by default a couple of lines like this:

api.use('ecmascript');

So you'll probably need to get rid of those.

As a final step I removed the dir /.meteor/local/

**Comment by c316** [comment] 2015-09-25 01:40
Are you sure this is true? If I remove the ecmascript package and then try
to use 'let' instead of var I get an error.

**Comment by ciwolsey** [comment] 2015-09-25 01:57
@c316 Yes I'm 100% sure and I just checked by creating a new app. I did:
```
let a = 1;
console.log(a);
```
I tried it on both server and client and got 1 in the console.

**Comment by c316** [comment] 2015-09-25 14:40
@ciwolsey When you setup a new package this happens differently then when you update to 1.2. The reason that you can setup a new project and use let is not because it is somehow built in, but because it is included in the packages list. 

The ecmascript package is in the list of packages in the ```.meteor/packages``` file when you use ```meteor create test```. This actually just confirms the problem is with the ecmascript package. I'm not sure what might be causing the problem, but it only happens when the ecmascript package exists on my projects that were at one time at a lower version than 1.2.

I setup a new project, then copied the list of packages into my existing project and it hangs in the same way. So I don't think this is a a problem with some other package conflict. I also did a ```meteor reset``` and I still have the problem.

**Comment by Exilz** [comment] 2015-09-25 14:47
I had the same problem on Windows 10 when I cloned my git repo with everything but .meteor/local.
Killing the process and re-launching it worked. It seems like it hanged after upgrading meteor 1.1.x to 1.2.

**Comment by c316** [comment] 2015-09-25 15:48
In my case it was a really large js file. flat-ui-pro.js. 

See #5198

I renamed it to flat-ui-pro.es5.js (which excludes it from compilation) and the app starts now. 

However, now I am having a different issue. The app starts, then crashes. ```=> Exited with code: 1```

**Comment by stubailo** [comment] 2015-09-28 18:54
Would it be reasonable to assume that this is a problem with large files in particular? Has anyone encountered this in an app with no large JS files?

**Comment by ciwolsey** [comment] 2015-09-28 19:03
I think that's a reasonable assumption. In the end, I realised it was due to a large js file I had. There's a previous issue related to large files which suggests renaming it to .es5.js might fix it but this never did, but since completely removing the large file I've had no problems building. It still seems like there might be a problem related to large files though as I never had this problem before 1.2 with the same file.

**Comment by stubailo** [comment] 2015-09-28 23:00
Yeah, I think this is because the Babel transforms we are using are particularly inefficient for huge files. We should maybe consider disabling them for very large files automatically. @benjamn what do you think?

**Comment by jedwards1211** [comment] 2015-10-13 16:28
Does Meteor have a tool to figure out what package is depending on ecmascript?  Besides, why would that compile with babel for the whole project?  I thought it would only do so for those packages

**Comment by jedwards1211** [comment] 2015-10-13 16:34
Using the `.es5.js` extension doesn't seem to fix the issue for me.  And I've been using large Webpack bundles for a long time.  Maybe it's a different issue?

**Comment by stubailo** [comment] 2015-10-13 17:17
> If I have done meteor remove ecmascript, it absolutely shouldn't compile any files in the project outside of packages, regardless of what other packages are doing, right?

Yes, if you don't have the `ecmascript` package, no compilation should be happening.

**Comment by jedwards1211** [comment] 2015-10-13 22:05
Okay, then that must not be the problem for me.  Is there any more debug output I can enable to try to diagnose the problem?

**Comment by jedwards1211** [comment] 2015-10-18 17:30
I'm now seeing Meteor hang on the `Linking` step when I put Webpack bundles into a Meteor package and I run testing like so:
```
VELOCITY_TEST_PACKAGES=1 meteor test-packages --driver-package velocity:html-reporter jcore-portal-tests
```
`Linking` definitely comes after all `ecmascript` transpilation, right?

**Comment by patte** [comment] 2015-10-19 09:13
I have the following: meteor -v, everything goes fine until Linking, then it blocks and node spins at 100%.
Is this the same problem discussed in this thread, or should I go somewhere else? How I see it from the logs, building is done when my node gets stuck.
To verify: How do you remove ecmascript? Meteor remove says: ecmascript is not in this project, but when I run meteor -v, I see it gets loaded at 0.1.5.

**Comment by patte** [comment] 2015-10-19 12:59
As this thread proposed, I tried to suffix some huge js files of my app with *.es5.js without any luck. but interestingly when I remove those files from the project, everything runs fine (expect the app doesn't work because it needs those files of course). Let me know I can help with further investigations.

**Comment by pvmeijel** [comment] 2015-11-01 12:33
I have this issue as well. When I include a package with Kendo UI, Meteor gets stuck. I tried to exclude it from ECMA script compilation, but to no avail. Moving the package contents directly to the client folder does not help. Only excluding Kendo UI seems to solve the problem, but breaks my app. Let me know if we can help on this issue.

**Comment by dmhall2** [comment] 2015-11-09 21:01
I have had a similar issue with with the handsontable (minified size 498kb).

**Comment by lubianm** [comment] 2015-11-12 17:32
We're still having the same issue with ecmascript (version 0.1.6). If we add that package, the application startup hangs on 'building for web.browser'; after having removed the package, the startup works like a charm.

**Comment by evenfrost** [comment] 2015-11-19 16:57
Having this issue as well, same process as for @lubianm, Ubuntu 15.10, medium-size project. Meteor with `ecmascript` completely hangs on `Building for web.browser` step.

**Comment by rlech** [comment] 2015-11-24 16:45
its freezing when I include framework7 js/css files into client folder. When I remove ecmascript package, it run

**Comment by vleipnik-miovision** [comment] 2015-12-10 13:38
Any update on this issue? I've recently begun evaluating Meteor as my framework of choice and very early ran into this issue with a critical library that I need to use (mxGraph) for my app. The library is ~2Mb, and is essential. Up until this point I was very excited about Meteor, but not this calls into question my ability to move forward. Also, it seems this has been open for 3 months, and not yet been slated into a release. I removed ecmascript, renamed the culprit file to .es5, but it gets stuck on "Building for web.browser" as others have mentioned.

**Comment by fentas** [comment] 2015-12-11 10:58
same here. `.es5.js` solved it for now, though.

**Comment by greggman** [comment] 2015-12-23 14:45
same for me. everything was working, added ecmascript package, freezes during build, removed ecmascript package, it builds again. I could try splitting files but if I do and then later run into the issue again I might be stuck in a corner with no options except to re-write a bunch of es6 code back to es5

**Comment by atoftegaard** [comment] 2015-12-26 19:23
I have the same issue with GoJS. It's a large file, but renaming it to go.es5.js does not fix anything. I get the following output though:
`[BABEL] Note: The code generator has deoptimised the styling of "/client/lib/go-debug.es5.js" as it exceeds the max of "100KB".`

**Comment by DominikGuzei** [comment] 2016-01-02 14:32
Just had the same problem with the raw generated bootstrap `less` file of  https://github.com/huttonr/bootstrap3. It probably was simply too large … a few thousand lines (with var declarations). Still a shame that this effectively kills the build process! The solution here was to disable raw output and let the package build bootstrap itself.

**Comment by greggman** [comment] 2016-01-02 17:01
I thought I should point out using babel directly it's able to compile the code that is failing in meteor. Meteor is using `babel-core@5.8.24` whereas the current babel-core is at `6.3.26`. On top of that meteor is using node `0.10.40` where as I'm running node 4.1.0 when I tested outside meteor.

I only bring the node version up as I have no idea if the bug is in babel-core or node but given large modules compile no problem outside of meteor with current babel and current node upgrading one or the other would probably fix the issue.

**Comment by razvanioan** [comment] 2016-02-06 20:16
This is getting frustrating !

I was excited as well about the framework, and started to play with it today (especially in combination with Kendo UI library, and here I stopped).

As soon as I add kendo package (very large JS file), my processor starts to boil (it's not a bad machine: i7 quad, 16 GB of RAM and SSD), but the app never gets built (stuck on building web.browser).

I've removed ecmascript package: no difference
I've renamed the big JS file with .es5.js: no difference (removed / re-added package)

The only thing which worked (like someone mentioning on some other repository), was to remove large JS files within the package config, move it to /public/scripts/ and manually load in HTML template head ...

Will be there some light into this ?

Thank you !

**Comment by thatguyhampton** [comment] 2016-02-11 01:26
I am also experiencing this issue. To view a reproduction take a look at my project : [Meteor Elm Compiler](https://github.com/thatguyhampton/meteor-elm-compiler). To view the issue go into the testapp folder, run "meteor", then check your cpu for node. Also try making a change to the testapp.js and nothing will recompile.

**Comment by thatguyhampton** [comment] 2016-02-11 15:09
After more investigation, I reverted my meteor version back to 1.2.0.1 and the build process was working just fine. Something seems to have changed from 1.2.0.1 -> 1.2.0.2 that has caused this.

**Comment by tomismore** [comment] 2016-02-13 16:54
Just wanted to hop in here and say that I got the very same error (hanging on 'build') when switching from meteor 1.1 to 1.2 in a phaser project I'm working on.

When I changed phaser.js out for phaser.min.js (2+ megs vs 700kb) it worked again

So that seems to lend credence to the large file thing... This is a pretty serious bug! Has the Meteor team responded to this yet?

**Comment by hiei189** [comment] 2016-02-27 05:41
My application is also hanging during Linking. Is there a workaround?

**Comment by Firfi** [comment] 2016-03-09 10:01
My application also hanging sometimes with activity 100%. I also use ecmascript package and jsx with es6 syntax. It isn't dying with ctrl+c but rather with kill -9 but I found a simple solution: just wait a little longer (several minutes worked for me). Most of you are on hourly rate anyways.

**Comment by Brianchat** [comment] 2016-03-13 10:41
Having the same problem on a Debian 7 virtual server. Commenting out the ECMAScript and ES-6 packages solves it but would like to use them.

**Comment by jedwards1211** [comment] 2016-03-14 19:02
@Firfi last time I tried this, though it was a long time ago, it took hours.  You might not be experiencing the same issue.

**Comment by Domiii** [comment] 2016-03-25 08:56
+1

Same problem here: Meteor cannot get past `Building the application`.

Funny thing is that, if I have `less` (or a package depending on `less`) in my build, the problem occurs during the `compilesLessBatch` step.

Using [c316](https://github.com/c316)'s recommendation (adding `.es5` to the filename) fixed the problem. Thanks!

**Comment by shiyeling** [comment] 2016-03-27 14:53
Having exact same problem with @atoftegaard while trying to add gojs.

**Comment by rlech** [comment] 2016-03-29 10:10
Sometimes I have problems when I add .min.js files into my project. When I use the uncompressed JS files its fine.

**Comment by mashiox** [comment] 2016-05-05 23:04
I had the build directory of my meteor application in the root directory of the project. Removing this directory from the project's filesystem scope resolved this issue. 

I would ensure that no executables (jars, apks, etc) are within reach of meteor's runtime.

**Comment by lyricalpolymath** [comment] 2016-05-14 13:52
I had the same issue and found **2 solutions**:
1- described here:  rename the minified version of the lib adding the postfix "es5.js"
ie: from   heavyLib.min.js   to  heavyLib.min.es5.js

2- inject the lib, without minification, in the head during onCreation of the template or component that needs it
use this Utils

```
Utils = {}

/**
 * Utility to inject in the head element some Css or js
 * this solves meteor problem that doesn't allow to load specific files per route
 * it checks if it already exists and removes the previous version, so that if a user reloads the page doesn't copy it many times
 * @param tagType   :String "css" or "js"
 * @param tagId     :String the id of the tag to create and remove
 * @param filePath  :String file to inject
 */
Utils.injectInHead = function (tagType, tagId, filePath) {
    if(tagType == "css") {
        //remove and inject the new one
        $("head #"+ tagId).remove();
        $("head").append($("<link rel='stylesheet' id='" + tagId + "' href='" + filePath + "' type='text/css' media='screen' />"));

    } else if(tagType == "js") {
        $("head").append($("<script id='" + tagId + "' src='" + filePath + "' ></script>"));
    }
} 
```

then use it like this inside an onCreated

```
var filePath = "http://example.com/heavylib/v2/heavyLib.min.js"
var tagId = "HeavyLibInjected";
Utils.injectInHead("js", tagId, filePath);
```

**Comment by shiyeling** [comment] 2016-05-31 13:06
Stuck in this problem again just when I need to do a build for release!
Do we have any definitive solution for such problem?

**Comment by ramonprata** [comment] 2016-07-02 01:29
I am trying to run a simple "hello world" with angular2-meteor following the tutorial: 
http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping 
and I am getting an error: constants.js:66Uncaught TypeError: Cannot read property 'CheckOnce' of undefined on the browser. 
Can anyone help me?

**Comment by djwatt5** [comment] 2016-07-06 19:45
Happens to me when trying to use the Plotly library in my application. Makes sense, though, since it is a huge js file. Application hangs at `Processing files with ecmascript (for...`.

Is it possible to exclude js files from ES6 processing? I use ES6 but this library in particular is made for standard js.

**Comment by greggman** [comment] 2016-07-06 20:36
Maybe this is noise but I'm just waiting for meteor 1.4. They're supposed to update to node 4.x or something. Maybe that will fix it. If not it still probably make it easier to fix?

**Comment by abernix** [comment] 2016-07-07 09:41
@djwatt5 You can rename the file with a `.es5.js` extension to avoid the `ecmascript` processing.  Out of curiousity, is the plotly JS file already minified (e.g. `.min.js`), or is it in full-form (e.g. easily readable :smile:)?

**Comment by bryankennedy** [comment] 2016-07-21 15:37
This is happening to me when trying to load the seriously.js library. It hangs when I include the threejs dependencies. `three.js` is a 808kb file and it chokes meteor on the `Processing files with ecmascript (for...  |` step every time. I tried renaming the file with `.es5.js` to no avail.

**Comment by shmendo** [comment] 2016-10-12 21:04
This is so frustrating. I'm actively pushing for our team to no loner use meteor as of now.

**Comment by jedwards1211** [comment] 2016-10-13 13:59
@shmendo yeah, I felt the same way but I was stuck with Meteor...I channeled my frustration with Isobuild into an app skeleton that doesn't build your app code in it, so only Meteor packages can trigger this issue or other isobuild slowness issues.  Maybe it will help you: https://github.com/jedwards1211/crater

**Comment by rgstephens** [comment] 2016-10-24 15:06
I'm running into the hang on a Meteor 1.4.1.2 project when I added android and tried to do a build.  It hangs on the message: `Processing files with ecmascript`. The CPU is pegged at 100% and I have to do a `kill -9` as reported by others.

If I do a `meteor remove-platform android` and `rm -rf .meteor/local/cordova-build` the problem goes away. Sounds like #5198 which is closed.

**Comment by shmendo** [comment] 2016-10-24 16:59
@jedwards1211 I ended up using ddp-server-reactive package w/express and wrote a bunch of node to use a tailing cursor to mimic the same behavior meteor has. Didn't have to adjust any front end code and I'm now a happy man. It's unfortunate that building is so fragile because at the beginning meteor made build a simple RT app so simple, we just added models and it handled streaming the data but the meteor black box made it impossible to debug issues like this. We have a weird use case, since we build docker containers and deploy them with aws cloudformation, so i don't expect everyone to reach the level of frustration that we did... it just made leveraging technology that we wanted to use impossible.

**Comment by jedwards1211** [comment] 2016-10-26 19:23
@shmendo wow, cool.  So it still uses minimongo and everything?  Do you have an app skeleton of any kind?  Yeah, I remember before my organization picked Meteor my boss had concerns about the way it controls the whole stack...and boy was he right to worry about it.

**Comment by jedwards1211** [comment] 2016-10-26 19:46
@shmendo there's a lot of things I wish I had known about meteor to begin with.  For instance how much spaghetti code is in the core.  For instance if you create a nearly empty project with:
```sh
meteor create spaghetti
cd spaghetti
# remove all packages
meteor remove $(grep -oE '^[-a-z]+' .meteor/packages)
# add meteor
meteor add meteor
```
And then `meteor add mongo`, you get:
```
allow-deny             added, version 1.0.5   
babel-compiler         added, version 6.13.0
babel-runtime          added, version 0.1.12
base64                 added, version 1.0.10
binary-heap            added, version 1.0.10
blaze                  added, version 2.1.9
blaze-tools            added, version 1.0.10
boilerplate-generator  added, version 1.0.11
callback-hook          added, version 1.0.10
check                  added, version 1.2.4
ddp                    added, version 1.2.5
ddp-client             added, version 1.2.9
ddp-common             added, version 1.2.7
ddp-server             added, version 1.2.10
deps                   added, version 1.0.12
diff-sequence          added, version 1.0.7
ecmascript             added, version 0.5.9
ecmascript-runtime     added, version 0.3.15
ejson                  added, version 1.0.13
geojson-utils          added, version 1.0.10
html-tools             added, version 1.0.11
htmljs                 added, version 1.0.11
id-map                 added, version 1.0.9
jquery                 added, version 1.11.10
logging                added, version 1.1.16
minimongo              added, version 1.0.18
mongo                  added, version 1.1.14
mongo-id               added, version 1.0.6
npm-mongo              added, version 2.2.11_2
observe-sequence       added, version 1.0.14
ordered-dict           added, version 1.0.9
promise                added, version 0.8.8
random                 added, version 1.0.10
reactive-var           added, version 1.0.11
retry                  added, version 1.0.9
routepolicy            added, version 1.0.12
spacebars              added, version 1.0.13
spacebars-compiler     added, version 1.0.13
tracker                added, version 1.1.1
ui                     added, version 1.0.12
webapp                 added, version 1.3.12
webapp-hashing         added, version 1.0.9
```
Some of that I can understand, like depending on `ddp` and in turn `webapp`, but it should not be bringing in `spacebars` and `blaze`...there should be a `mongo-blaze` package for that.

**Comment by jedwards1211** [comment] 2016-10-26 19:49
For another thing, I think npm packages have a way better approach precompiling down to es5 before publishing to npm.

**Comment by shmendo** [comment] 2016-10-26 20:22
@jedwards1211 Unfortunately I don't have an app skeleton and It doesn't use minimongo. The app we wrote uses polymer, so we just wrote ddp-connection, ddp-collection, ddp-method, and ddp-subscription web components which handle their respective parts of the ddp spec. 

It sounds complicated but the components are like 50 lines of js (maybe) each. It just handles the ping/pong and reconnect in the connection element. The others just pass a message to the backend and listen for data. I can throw together a gist for you but would prefer to keep it private. How can I get your email? I don't see it on your profile or personal site. Cave surveyer looks awesome btw.

**Comment by jedwards1211** [comment] 2016-10-26 20:49
@shmendo it's in the out-of-date resume on my website, thanks!

**Comment by shmendo** [comment] 2016-10-26 22:20
@jedwards1211 gist sent, let me know what you think. There is a subfolder (todos) which houses all the logic surrounding a collection.. such as methods and publications. Check it out. That is how you can segregate your logic into loadable modules. This is only a POC and i only spent a day on it so it's not amazing... code can be cleaner but you get the idea.

**Comment by elie222** [comment] 2017-01-13 11:53
Yup. 2017. Just hit this issue. Frustrating.

**Comment by hwillson** [comment] 2017-02-27 13:38
Hi all - this issue seems to come from really large ES5 files going through the `ecmascript` compilation process. As mentioned in https://github.com/meteor/meteor/issues/5275#issuecomment-143258705 (and ultimately #5198), the solution is to add the `.es5.js` suffix to files you want to have skip the `ecmascript` compilation process. Please also make sure you're using a recent version of Meteor (and you might need to `meteor reset` to get things working properly again - usual warning, don't forget `meteor reset` wipes your local db). 

Looking over this full issue thread, doing the above seems to fix most of the reported problems, but it's difficult to tell for sure (as this thread has certainly headed in a few different directions). If anyone is still experiencing this issue, can you please create a small/focused, runnable reproduction demonstrating the problem? This will greatly help with future troubleshooting (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more details).

For now however, since there isn't anything concrete to troubleshoot against (and many have reported that the `.es5.js` solution has fix this issue for them), I'll close this issue off. Happy to re-open if anyone feels differently, and is able to supply a reproduction showing this problem. Thanks!

**Closed by hwillson** 2017-02-27 13:38 UTC
Labels: Project:JS Environment

**Comment by mvgalle** [comment] 2017-04-04 15:57
I have had this problem from time to time also. I found a solution that usually fixes the issue. In the root of my project, I do the following: 

1. navigate to .meteor > local > plugin-chache 
2. remove all files in the plugin-cache (make a backup of them ... just in case) 
3. start your project by typing "meteor" in the console

This solution works for me, because my plugin-cache sometimes gets mixed up and cannot write/re-write to the directories within the plugin-cache. Deleting the plugin-cache fixes the problem as it gets re-created when you run your app. I hope this helps some of you facing this issue.

**Comment by sylido** [comment] 2017-07-13 11:05
Can confirm this bug is still present. One of the issues we also had is with an npm package that referenced a minified js version as the "main" starting point. The file us actually quite large as well 1.2mb JS so maybe when there isn't a cache of the plugin it has to go through rebuilding it and it takes waaay too long. I've left it for more than 30 minutes and had no luck.

Now I removed the /home/<user>/.meteor directory and reinstalled meteor.
Cleared the bundle-cache and plugin-cache directories.
Moved ecmascript and es5 shims on top of the list of packages in the <app>/.meteor/packages file.
Had to run with verbose and waited ~5 minutes for it to actually finally start.

If not anything else, as it seems people keep guessing, could we get a better debug flag ? I would really like to know if it's started on some process, be it either minification/uglification or re-compling of files. Would be nice to know on what it's currently working, since it usually pegs the CPU at 100%, but after a while goes to 5% and stays like that seemingly not doing anything.

**Comment by FinnFrotscher** [comment] 2017-08-09 18:37
+1

**Comment by derwaldgeist** [comment] 2017-09-23 18:10
+1

Had the same problem when adding Firebase to a meteor 1.2 app (by including the code directly). Adding `.es5.js` as and extension worked. Has this been fixed in later Meteor versions?

**Comment by Xeoncross** [comment] 2017-10-03 02:38
```
Meteor 1.5.2.1
Node 8.3.0
npm 5.4.2
```

I'm new to meteor. In three days I built an MVP of an internal application we needed. I spend all of the fourth day trying to get the project to build and deploy on the server. I used maybe 20 or so packages. All standard stuff like `axios`, `moment`, and `react-bootstrap`.

I had to raise node.js memory because the build was failing at 1.5GB of RAM usage(!)

After 30 minutes building, meteor FINALY produced a bundle. I had to rsync the build up to the server because the server didn't have 2.88GB of free RAM for me to run the compile there.

Meteor build problems and long build times (compared to almost nothing for `create-react-app` or `next.js` or even plain webpack) will insure people like me avoid this system.

**Comment by elie222** [comment] 2017-10-03 02:44
Calm down. You've used it for 3 days. In general build time is not a major
issue or hasn't been in the past few years.

**Comment by Xeoncross** [comment] 2017-10-03 02:53
I would love to see the community provide more resources for tracking down resource utilization problems. I assume I must be using bad packages or versions of libraries that cause meteor to choke.

**Comment by elie222** [comment] 2017-10-03 10:24
Sounds strange to me. Try the Meteor forums. Open a new GitHub issue. Try
meteor reset (will wipe the local db).

Also, would recommend using Meteor Up for deploy. Or Galaxy, but that's
expensive, but may be worth a test. Building locally shouldn't be an issue.
