### ISSUE TITLE
meteor-tool should allow downloading Atmosphere packages separately from building app

### ISSUE THREAD

**Issue by athyuttamre** [meteor/meteor#8618] opened 2017-04-21 07:54 UTC
I'd like the meteor-tool to support a way to download Atmosphere packages first, and then build the app with the downloaded packages.

### Why is this  important?

My use-case is in writing a Dockerfile for my Meteor app. Docker aggressively caches each build step, and it is common practice to first install dependencies (cache this step), and then copy application source code and build your app. This way, the cache is busted and dependencies re-downloaded only when they change, and not with every build.

### Suggested solution

I propose adding a `meteor add --all` option that downloads all existing dependencies from Atmosphere and stores them in `.meteor/plugin-cache`. If `meteor run` or `meteor build` is used in the future, it should draw from the plugins downloaded from the first step. If the plugins don't already exist, both commands retain existing behavior of first downloading them.

This solution retains existing behavior while adding an extra command to optionally download dependencies first. It would particularly help folks using Docker as well as anyone who wants to cache dependencies first.

**Comment by hwillson** [comment] 2017-04-21 09:59
Hi @athyuttamre - this sounds like a duplicate of #7914. I'll close this issue since there is already an on-going discussion about dependency caching in that issue thread. Pease add your comments/thoughts/support to that issue. Thanks!

**Closed by hwillson** 2017-04-21 09:59 UTC
