### ISSUE TITLE
Meteor saying packages were updated when they weren't

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#4942] opened 2015-08-11 21:58 UTC
I've run into this a couple times. When I do a `meteor update orionjs:core`, I get:

```
Changes to your project's package version selections from updating package
versions:

aldeed:autoform             upgraded from 5.1.2 to 5.4.0
aldeed:tabular              upgraded from 1.1.0 to 1.2.0
momentjs:moment             upgraded from 2.10.3 to 2.10.6
nicolaslopezj:roles         upgraded from 1.1.2 to 1.2.0
nicolaslopezj:router-layer  added, version 0.0.6
orionjs:accounts            upgraded from 1.1.0 to 1.4.0
orionjs:attributes          upgraded from 1.1.0 to 1.4.0
orionjs:base                upgraded from 1.1.3 to 1.4.0
orionjs:collections         upgraded from 1.1.0 to 1.4.0
orionjs:config              upgraded from 1.1.2 to 1.4.0
orionjs:core                upgraded from 1.1.0 to 1.4.0
orionjs:dictionary          upgraded from 1.1.0 to 1.4.0
orionjs:lang-en             upgraded from 1.1.1 to 1.4.0
softwarerero:accounts-t9n   upgraded from 1.1.2 to 1.1.3
useraccounts:core           upgraded from 1.8.1 to 1.12.0
```

Yet this is a lie. :) None of the above happened, and even the package I asked to be updated was not updated.

**Comment by glasser** [comment] 2015-08-11 22:05
Duplicate of #3582.

**Closed by glasser** 2015-08-11 22:05 UTC

**Comment by ffxsam** [comment] 2015-08-11 22:11
Maybe not entirely fixed? I'm using Meteor 1.1.0.3, and it still happens, but only if Meteor is running. So, I have to stop the Meteor server, update packages, then start the server again. If I do a package update while it's running, the versions get reverted.

**Comment by glasser** [comment] 2015-08-12 00:24
The fix has not yet been released.

**Comment by ffxsam** [comment] 2015-08-12 00:25
Ah, gotcha. Thanks for clarifying that.
