### ISSUE TITLE
[FR] Add a warning for local packages in packages directory not included in the main app

### ISSUE THREAD

**Issue by vjau** [meteor/meteor#3237] opened 2014-12-05 17:26 UTC
Hi everyone,
there is a mistake that i do very often with my apps, which is to forgot to add (with meteor add) an internal (local) package.
I think there should be a warning during building when packages that are under the app's "packages" directory are not included in the app.
It would prevent some problems which are discovered (too late) during runtime.

Thank you

**Comment by glasser** [comment] 2015-01-12 19:35
The problem is that this is actually a specifically requested feature (f0875d1d), to allow you to have test helper packages used by your package's tests but not by the app itself.  (Or used by other packages.)

So this is worth implementing, but we'd want to ensure that we do an extra check to make sure that the package wouldn't be used during `meteor test-packages` either (which adds overhead to builds, and we're pretty focused these days on not slowing down builds).

**Comment by glasser** [comment] 2015-01-12 21:53
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by vjau** [comment] 2015-01-12 22:18
Thank you @glasser, it's nice to be able to track feature requests (i fully understand that they can also be flaged as someday/maybe or never).

**Comment by viveksjain** [comment] 2015-01-30 22:14
Just wanted to pitch in that as someone relatively new to meteor, I didn't realize packages inside `/packages/` had to be added manually. I was almost about to file a bug request, but then searched and found this issue. I'm not sure of an elegant solution to this (maybe explicitly blacklist what you want to exclude instead of the current behavior of explicitly whitelisting what you want to include), but at the very least this behavior should be documented clearly at http://docs.meteor.com/ (perhaps in "Structuring your app"). Apologies if it's already documented, but I couldn't find it in any official documentation.

**Comment by vjau** [comment] 2015-01-30 22:40
The rationale for the packages not to be included is that you can have packages not included in the main app but required by other packages of you app. This prevent scope pollutions.

**Comment by hwillson** [comment] 2017-03-10 16:15
Since there is a very good reason why local packages aren't automatically included (https://github.com/meteor/meteor/issues/3237#issuecomment-69630683), and there hasn't been much interest in handling this any differently in the codebase, I'll close this issue. 

The above being said, there is definitely value in documenting the fact that local packages still need to be added (via `meteor add`, editing `.meteor/packages` directly, etc.). Since we now have the Meteor Guide (wasn't available when this issue was created), it would probably make sense to mention this fact within the [Using Atmosphere Packages](https://guide.meteor.com/using-atmosphere-packages.html) section. I'll open a new issue in the Guide repo to track this. Thanks for posting this originally!

**Closed by hwillson** 2017-03-10 16:15 UTC
Labels: feature, Project:Isobuild
