### ISSUE TITLE
Windows installer: "Login failed" during install

### ISSUE THREAD

**Issue by rdickert** [meteor/meteor#6218] opened 2016-02-11 17:49 UTC
Installing on Win7x64, the login step fails with "Login failed." alert box. I tried my username and two confirmed emails for my MDA. @justinsb confirmed the same problem.

Workaround: Just click the button "Skip this step" to complete installation. You can use `meteor login` in the cmd window.

**Comment by stubailo** [comment] 2016-02-16 23:16
Yeah in certain situations it might not work, and it's hard to identify what they are. Hopefully we can improve the installer in the future.

**Comment by animanoir** [comment] 2016-06-04 06:26
I have the same issue.

**Comment by Berkmann18** [comment] 2016-06-14 19:37
I also have the same issue on Win10 x64.

**Comment by romaroma** [comment] 2016-06-16 03:27
Same issue on two different PCs.

**Comment by animanoir** [comment] 2016-06-16 03:32
I actually managed to login but I did it instead in the console. Sorry, I forgot how exactly I did it, but yeah, login during installation seems to fail, but if you skip it and then do it on the console should work fine.

**Comment by Berkmann18** [comment] 2016-06-26 11:19
@romaroma I got the same thing by trying to login on the GUI which failed then skipped it and tryed to do `meteor login` which outputed this:

```
Errors prevented isopacket load:

While loading isopacket `ddp`:
module.js:338:15: Cannot find module './_baseClone'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-types\node_modules\lodash\clone.js:1:17)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load
(C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-types\lib\index.js:314:38)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load
(C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-template\lib\index.js:84:43)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load
(C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\lib\index.js:525:46)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load
(C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object._.extend.Npm.require (C:\tools\isobuild\bundler.js:1570:22)
at Object.require (C:\tools\isobuild\bundler.js:1547:11)
at Package (packages/babel-compiler/babel-compiler.js:17:1)
at packages/babel-compiler/babel-compiler.js:356:1
at packages/babel-compiler/babel-compiler.js:356:1



C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
Error: isopacket load failed?
    at loadIsopacketFromDisk (C:\tools\tool-env\isopackets.js:286:11)
    at C:\tools\tool-env\isopackets.js:88:23
    at Object.exports.noYieldsAllowed (C:\tools\utils\fiber-helpers.js:37:14)
    at Object.load (C:\tools\tool-env\isopackets.js:80:23)
    at getLoadedPackages (C:\tools\meteor-services\auth.js:15:21)
    at openAccountsConnection (C:\tools\meteor-services\auth.js:21:13)
    at Object.loginCommand (C:\tools\meteor-services\auth.js:33:16)
    at Command.main.registerCommand.name [as func] (C:\tools\cli\commands.js:1830:15)
    at C:\tools\cli\main.js:1402:23
```

**Comment by kevman** [comment] 2016-06-27 14:22
Same problem here!

**Comment by romaroma** [comment] 2016-06-28 03:54
@Berkmann18 it seems that the issues are related to very long paths in distribution so meteor couldn't find its own packages. It was discussed in #7221. I managed to fix the problem by reinstalling meteor, it downloaded 1.3.4.1 that has no issues with running apps. Though login in GUI is still broken.

**Comment by abernix** [comment] 2016-06-28 14:20
Using the latest 1.3.4.1 installer, I can confirm that I was **unable** to log in using the GUI Installer's "login" dialog in Windows 7 Enterprise (32-bit) **nor** Windows 10 Enterprise (64-bit).  However, I was **able to log in manually** on _both_ with `meteor login` from the command prompt without receiving the ````isopacket `ddp` ```` error.

**Comment by abernix** [comment] 2016-06-28 14:22
@Berkmann18 & @kevman Can you confirm that the problem goes away if you try updating one of your existing projects to 1.3.4.1 before trying to log in (as @romaroma said worked for him).  You should be able to `meteor update --release 1.3.4.1` then `meteor login`.

**Comment by Berkmann18** [comment] 2016-06-28 21:17
@abernix whenever I do `meteor update --release 1.3.4.1` when being on the directory of a project, it outputs the "Error prevent isopacket load: ..." error same thing for `meteor update` and I'm on v1.3.3.

**Comment by abernix** [comment] 2016-06-29 13:18
@Berkmann18 Perhaps try re-installing fresh with 1.3.4.1?:

* Uninstall Meteor:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.
* Install fresh 1.3.4.1 from https://install.meteor.com/windows (skip logging in at end due to this login issue)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it executes (the actual version isn't relevant).
* Then try `meteor update --release 1.3.4.1` within your existing project

**Comment by Berkmann18** [comment] 2016-06-29 20:31
@abernix Now it works, thank you.

**Comment by hwillson** [comment] 2017-03-24 17:15
It sounds like this might now be resolved? I'll close this issue since there hasn't been any activity on it in a while, but please post back if anyone is still having a problem. Thanks!

**Closed by hwillson** 2017-03-24 17:15 UTC
Labels: bug, confirmed, Impact:most, Project:Installer, Project:Windows

**Comment by ramintagizade** [comment] 2017-10-17 12:12
Same problem with Meteor installer on windows 8 .
