### ISSUE TITLE
[1.3.1] api.mainModule anywhere in PACKAGE_DIRS is erroring prior Meteor versions

### ISSUE THREAD

**Issue by JeremySaks** [meteor/meteor#6758] opened 2016-04-08 22:29 UTC
When I create or run a pre-1.3 Meteor project while I have any local 1.3 package with an `api.mainModule()` call in my `PACKAGE_DIRS` paths, the pre-1.3 project errors with:
```js
TypeError: Object #<PackageAPI> has no method 'mainModule'
```
These packages are not related to or included in the pre-1.3 projects I am trying to run, they are just in the `PACKAGE_DIRS` paths.

Above is true whether or not the 1.3 packages include, e.g., `api.versionsFrom('1.3.1')`.

Usually I just add a bunch of paths to `PACKAGE_DIRS` in my `.bash_profile` (Mac) but now I'm having to set `PACKAGE_DIRS` on a per-project basis. Bug, or something about my setup perhaps?

**Comment by benjamn** [comment] 2016-04-10 16:54
Duplicate of #6713. See https://github.com/meteor/meteor/issues/6713#issuecomment-206588917 for further explanation.

We could release an update to the 1.2 version of Meteor, but then you'd have to update to that version anyway (1.2.2), and then why not go ahead and update to 1.3.x? What's holding you back?

**Comment by benjamn** [comment] 2016-04-11 14:42
See https://github.com/meteor/meteor/issues/6713#issuecomment-208379752 for an even easier workaround.

**Closed by benjamn** 2016-04-11 14:42 UTC
