### ISSUE TITLE
release-1.6:  Constructor Map requires 'new'

### ISSUE THREAD

**Issue by shenrenguo** [meteor/meteor#8749] opened 2017-06-02 08:42 UTC
Hi,

In release 1.6, with [nathantreid:css-modules](https://atmospherejs.com/nathantreid/css-modules) package, encountered below error when building, but in meteor 1.5 works correctly.

```
While processing files with nathantreid:css-modules (for target web.browser):
   native: Constructor Map requires 'new'
   at FileMap.Map (native)
   at new FileMap (packages/mss/css-modules-build-plugin.js:24:5)
   at CssModulesBuildPlugin.processFilesForTarget
   (packages/mss/css-modules-build-plugin.js:65:24)
```

**Comment by klaussner** [comment] 2017-08-29 12:28
@arggh created a reproduction for this issue: https://github.com/arggh/meteor-css-modules-issue

**Comment by nathantreid** [comment] 2017-08-30 00:03
The error is caused by [this class](https://github.com/nathantreid/meteor-css-modules/blob/fe8a6932a5a52302aec0875ce8f021ccf88e7d7b/css-modules-build-plugin.js#L22):
`class FileMap extends Map {`.
From what I've found via google (for example [this issue](https://github.com/babel/babel/issues/2334) and the [caveats page](https://babeljs.io/docs/usage/caveats/#classes) linked from that issue), it seems that Babel has issues subclassing native classes like `Set` and `Map`. However, you can subclass the native `Map` in Node 8 if Babel isn't involved. This is a compiler plugin, so if Meteor were to use different Babel targets for the server vs the client, perhaps this error would go away?

**Comment by benjamn** [comment] 2017-10-12 19:36
This works if I clone https://github.com/nathantreid/meteor-css-modules locally, so I suspect `nathantreid:css-modules` may just need to be republished with Meteor 1.6 to make sure the compiler plugin gets rebuilt with Meteor 1.6 Babel plugins.

To test this hypothesis, you could go ahead and publish a beta version. I would recommend something like `2.8.0-beta.0`. Then remove [the `api.versionsFrom` line](https://github.com/nathantreid/meteor-css-modules/blob/f71c3c743466f162001765b50fe2f545230d1f57/package.js#L61) from `package.js` and run this command:
```sh
meteor --release 1.6-rc.7 publish
```

**Comment by hwillson** [comment] 2017-10-13 15:54
Given the findings in https://github.com/meteor/meteor/issues/8749#issuecomment-336243269, I'll close this issue for now. @nathantreid If that doesn't help address the issue, let us know. Thanks!

**Closed by hwillson** 2017-10-13 15:54 UTC
