### ISSUE TITLE
DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by anderson916** [meteor/meteor#7977] opened 2016-10-27 06:40 UTC
MacOS 10.12.1
Meteor 1.4.2
Chrome 54.0.2840.71 

<img width="833" alt="screen shot 2016-10-27 at 2 38 53 pm" src="https://cloud.githubusercontent.com/assets/195719/19757025/2ba91304-9c53-11e6-8461-57da65f510fa.png">

**Comment by damonmaria** [comment] 2016-10-27 08:14
And when I go to those URLs I get the HTML for the app itself (the `<head>` and `<script>`s in the `<body>`). Was working fine before 1.4.2.

**Comment by kurapikats** [comment] 2016-10-29 01:22
same thing happens to me

**Comment by brucejo75** [comment] 2016-10-29 05:43
### Client side
Same thing on windows:
Windows 10: 1511 (OS Build 10586.633)
Meteor: 1.4.2
Chrome: 54.0.2840.71

### Server side

Also getting this on NODE debug sessions
```
Network.loadResourceForFrontend failed.
Error: ENOENT: no such file or directory, open 'E:\mroot\meris\.meteor\local\build\programs\server\profile.js.map'
```

I do not know if it is related, but any commands in the console get lost in space (I assume the debugger may be parsing the entire symbol tree looking for things?).  The console is unusable.

**Comment by shawnohail** [comment] 2016-10-31 00:40
same thing happens to me 
i'm using meteor 1.4.2 and osx 10.12.1

**Comment by kulttuuri** [comment] 2016-11-01 09:38
Same issue here on 1.4.2. Using OS X. And also happens for my colleague on osx and colleague on windows.

**Comment by AntonioRossi** [comment] 2016-11-04 17:49
I upgraded a project from version 1,3,5 and now I have the same issue on Meteor 1.4.2 and Ubuntu 16.04.1:

![meteor no sourcemaps](https://cloud.githubusercontent.com/assets/2480229/20016278/0db4256a-a2bf-11e6-9067-734440db88a9.png)

**Comment by bpicori** [comment] 2016-11-07 09:27
Same thing on Ubuntu. 
Ubuntu 16.04
Meteor: 1.4.2
Chrome:  54.0.2840.90

**Comment by vparpoil** [comment] 2016-11-07 14:37
Same error on windows and OS X, wasn't happening in 1.4.1.1.

**Comment by benjamn** [comment] 2016-11-07 15:59
Can you try loading one of those URLs in your browser to see what's being served?

**Comment by benjamn** [comment] 2016-11-07 16:00
In the meantime, you might also try deleting `.meteor/local/bundler-cache`.

**Comment by vparpoil** [comment] 2016-11-07 16:35
@benjamn Actually, I went back to 1.4.1.1 my previous version after posting here. After reading your message I went back to 1.4.2 and no more pb on Os X. Same thing for my partner on windows. So I cannot confirme what solved it

**Comment by benjamn** [comment] 2016-11-07 16:45
It sounds like some sort of problem with the browser caching source map URLs for JS files it thinks it has loaded before, which would explain why the problem goes away eventually, but I agree this is annoying when it happens.

**Comment by abernix** [comment] 2016-11-07 17:35
Unfortunately, I cannot reproduce this problem on macOS sierra (10.12.1 / 16B2555) on Meteor 1.4.2 (or 1.4.2.1-rc.1) with Chrome 54.0.2840.71 or 54.0.2840.87.

If someone can attempt to see if it happens on a new 1.4.2 project, that might be helpful.  There have been third-party packages in the past which have done funny stuff with `source-map-support` (which as you might expect, is an NPM package which manages source map support) so if you could eliminate packages to try to debug this, that would also be a recommended course of action.

**Comment by vparpoil** [comment] 2016-11-07 17:41
if it can helps : in our case we worked on a first project on 1.4.1.1. 
Then created a **new** project on 1.4.2, serving it on the same local URL (localhost:3000), then encountered the bug, then rolled back to 1.4.1.1 and updated again to 1.4.2 and bug went away

**Comment by kulttuuri** [comment] 2016-11-07 18:01
This bug also went away for me. I deleted my .meteor local files as the folder started to be like 15gb and that seemed to fix the issue.

**Comment by hwillson** [comment] 2016-11-07 18:04
I'm able to re-create this with any new `meteor create some-project` (with no other changes), using 1.4.2 (OS X El Capitan 10.11.5, Version 54.0.2840.87 (64-bit)). Here's a quick screenshot of my console:

![screenshot 2016-11-07 12 55 28](https://cloud.githubusercontent.com/assets/137740/20069330/26391348-a4ea-11e6-96c0-b2c31cf3aab3.png)

Each one of the specified links just loads up the main page when clicked on, since those `.map` files are missing. I took a quick look in my apps `.meteor/local/build/programs/web.browser/packages` directory, and sure enough most of the `.map` files are missing.

![screenshot 2016-11-07 12 59 22](https://cloud.githubusercontent.com/assets/137740/20069339/2ecf2132-a4ea-11e6-9bf5-71db8d1febbb.png)

I've compared this with older pre-1.4.2 apps, and can see the missing `.map` files in `.meteor/local/build/programs/web.browser/packages`.

Clearing the local bundler cache has no affect (since this happens with brand new projects).

Since this seems easily reproducible in my environment, I'll trace this a bit more thoroughly and post back with more details shortly.

**Comment by abernix** [comment] 2016-11-07 19:38
@hwillson Not sure if this is any help, but I have the same `.map` files which you're showing in your output at `.meteor/local/build/programs/web.browser/packages` that you do (the files expected in a blank project), and I have no errors:

```sh
$ ls -la .meteor/local/build/programs/web.browser/packages/*.map
-r--r--r--  1 jesse  staff  32804 Nov  7 21:10 .meteor/local/build/programs/web.browser/packages/allow-deny.js.map
-r--r--r--  1 jesse  staff  49574 Nov  7 21:10 .meteor/local/build/programs/web.browser/packages/mongo.js.map
-r--r--r--  1 jesse  staff  17958 Nov  7 21:10 .meteor/local/build/programs/web.browser/packages/random.js.map
-r--r--r--  1 jesse  staff   1191 Nov  7 21:10 .meteor/local/build/programs/web.browser/packages/webapp.js.map
```

For those that do have .map files, the the source maps work properly, for example, in my `view-source` (for a blank project) I have a:

```html
<script type="text/javascript" src="/packages/webapp.js?hash=b74e2292d6087dc6f77d86b7e71ac0d672b0fbe8"></script>
```

And if I browse to `http://localhost:3000/packages/b74e2292d6087dc6f77d86b7e71ac0d672b0fbe8.map` it displays the source map properly (which is the same contents of the `webapp.js.map` file):

```
{"version":3,"sources":["meteor://💻app/packages/webapp/webapp_client.js"],"names":["WebApp","_isCssLoaded","document","styleSheets","length","_","find","sheet","cssText","cssRules","match","rule","selectorText"],"mappings":";;;;;;;;;;;;;;;;;;;
...truncated...
```

I don't recall off the top of my head how those `<hash>.map` URLs are served, but I'm pretty sure they are not intended to be direct mappings to files on disk.

**Comment by hwillson** [comment] 2016-11-07 19:51
Thanks @abernix - I was wondering the same thing ...

> I don't recall off the top of my head how those <hash>.map URLs are served, but I'm pretty sure they are not intended to be direct mappings to files on disk.

... but check this out from a 1.4.0.1 project I have:

![screenshot 2016-11-07 14 43 58](https://cloud.githubusercontent.com/assets/137740/20073035/a4269c4a-a4f8-11e6-8e37-49eba1ecd486.png)

I'm still tracing through the source, but am currently focusing on this block from [`tools/isobuild/linker.js`](https://github.com/meteor/meteor/blob/340f0f6fd416623489d7cd904402f9c07b3c8df3/tools/isobuild/linker.js#L201-L208):

```
          var swsm = node.toStringWithSourceMap({
            file: self.combinedServePath
          });
          result.source = swsm.code;
          result.sourceMap = swsm.map.toJSON();
          if (! result.sourceMap.mappings) {
            result.sourceMap = null;
          }
```

The files that are reported as having missing source maps are being assigned `null` here, as there are no `mappings` returned after the source files are processed using the NPM [`source-maps`](https://www.npmjs.com/package/source-map) package. The fact that no `mappings` are returned seems a bit odd to me, so I'll keep digging ...

**Comment by hwillson** [comment] 2016-11-07 21:10
Well, I can no longer reproduce this problem :-( ...

Within the [`tools/isobuild/linker.js`](https://github.com/meteor/meteor/blob/340f0f6fd416623489d7cd904402f9c07b3c8df3/tools/isobuild/linker.js#L201-L208) file I wanted to see what the `result.sourceMap` variable held if the missing `mappings` check was skipped, so I commented out the 

```
if (! result.sourceMap.mappings) {
  result.sourceMap = null;
}
```

block. This removed all `DevTools failed to parse SourceMap ...` warnings from my console after a rebuild. I see this check was added specifically in [this commit](https://github.com/meteor/meteor/commit/13db0e89ef8bc2c0ecda05553133e793ed470774) however, so it must be needed.

After I re-enabled this check however, the `DevTools failed to parse SourceMap ...` warnings didn't come back. I've now created several new projects using Meteor 1.4.2 (outside of my dev checkout), and the `DevTools failed to parse SourceMap ...` warning is completely gone! This leads me to believe there is/was definitely a caching issue somewhere along the line, most likely with Chrome. The funny thing is that I originally tried several `meteor reset`'s, complete browser cache clearing, etc. before commenting out the `mappings` check block, and the warnings alway persisted. Maybe a coincidence, but regardless I'm now completely unable to reproduce the original issue. So, I'll have to pass the torch to someone else.

**Comment by brucejo75** [comment] 2016-11-08 02:31
Given what @hwillson found, I just did an **Empty Cache and Hard Reload**.

This removed all of the mapping errors with the exception of map errors on css files.  Click and hold on the Chrome refresh button and it will bring up that option.

![hard reload](https://cloud.githubusercontent.com/assets/14342237/20084563/0d183e42-a518-11e6-81ab-3e4577f65fc6.png)

That resolves the issue for me.  Unfortunately, did not work for #7991

**Comment by lucfranken** [comment] 2016-11-08 07:03
@brucejo75 can confirm, that works. 

Maybe there are some cache headers off for source maps.

Maybe related bug in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=508270

**Comment by benjamn** [comment] 2016-11-08 17:41
@hwillson I suspect commenting out that code might have resulted in rehashing the source map names (`<hex>.map`), which made the DevTools not use the cached versions?

**Comment by hwillson** [comment] 2016-11-08 17:55
Thanks @benjamn, that's my guess as well - the funny thing is that I cleared the cache a thousand times before hand (using every cache clearing method known - including running my mac through my dishwasher) and the warnings still persisted. Right after commenting that line, they disappeared and never came back. There was definitely some Chrome caching weirdness happening, but since this issue can be resolved outside of Meteor (and seems to only be happening to a few people), we can probably consider closing this issue (and just to add - once resolved the warnings don't seem to ever come back, on existing or new projects).

**Comment by babenzele** [comment] 2016-11-08 19:33
@brucejo75 Just FYI for anyone trying to get rid of these messages, Chrome dev tools must be open for the Empty Cache and Hard Reload option to show up when you click and hold the refresh button.

**Comment by brucejo75** [comment] 2016-11-08 22:46
@babenzele, thanks I will add that to the comment!

**Comment by stallter4** [comment] 2016-11-09 00:56
the empty cache and hard reload worked for me as well.  interesting.  Thanks a lot!

**Comment by abernix** [comment] 2017-01-20 17:02
This hasn't picked up any more traction since it was originally reported and reproduction doesn't seem possible anymore.  In light of the problem, a salt was put in place in order to be super defensive, but it's still not absolutely necessary.

Closing as this doesn't seem to be an issue anymore.  Happy to reopen if someone is still reliably experiencing it though!  Thanks for reporting this originally. :)

**Closed by abernix** 2017-01-20 17:02 UTC
Labels: can't-reproduce

**Comment by sreezree** [comment] 2018-02-04 02:24
same issue happens for me...anybody please help me
