### ISSUE TITLE
Cordova custom config not reflected in Android App build

### ISSUE THREAD

**Issue by abhishekbatra** [meteor/meteor#3782] opened 2015-02-21 06:22 UTC
I'm using Meteor 1.0.3.1. I tried to customize the Android app build to use targetSdkVersion=16 by following: [the meteor wiki](https://github.com/meteor/meteor/wiki/Meteor-Cordova-Phonegap-integration#advanced-build-customization) and separately by adding a preference to mobile-config.js.

Added the following in cordova-build-override/config.xml:

```xml
  <platform name="android">
  ...
    <preference name="android-targetSdkVersion" value="16" />
  </platform>
```

mobile-config.js contains:

```javascript
  App.setPreference('android-targetSdkVersion', '16');
```
Despite these two, meteor/Cordova continues to build with targetSdkVersion = 19.

To validate a solution:
(config.xml):
1. Create a folder called `cordova-build-override` and inside create a file called `config.xml`
2. To the newly created `config.xml`, add the following xml:
 ```xml
  <platform name="android">
  ...
    <preference name="android-targetSdkVersion" value="16" />
  </platform>
```
3. Run `meteor run android-device --mobile-server={ip-address:port} --verbose` from project root.
4. Open project-name/.meteor/local/cordova-build/platforms/android/AndroidManifest.xml
5. In the `uses-sdk` element, check for `android:targetSdkVersion` attribute. It should be `android:targetSdkVersion="16"`

(mobile-config.js)
1. Add mobile-config.js to root of the project.
2. Add line: `App.setPreference('android-targetSdkVersion', '16');` to mobile-config.js
3. Run `meteor run android-device --mobile-server={ip-address:port} --verbose` from project root.
4. Open project-name/.meteor/local/cordova-build/platforms/android/AndroidManifest.xml
5. In the `uses-sdk` element, check for `android:targetSdkVersion` attribute. It should be `android:targetSdkVersion="16"`

Not sure if this issue would need a separate code repository as it is a build issue, but please let me know if needed. Thanks.

**Comment by Slava** [comment] 2015-02-24 21:56
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Also include instructions on how to validate that the configuration worked or didn't work.

**Comment by abhishekbatra** [comment] 2015-02-25 03:27
Hey,

I am assuming that a Github repo is what you're asking for. For some reason linking to an existing Android SDK doesn't work (but that would be a separate bug of course), hence I'll need to download the SDK for the new repo and push it as well. Currently I'm on a data limit and it would be a couple of days before I can create such a repo. If anyone else can try reproducing, I'd of course be grateful. If you want to close this bug in the meantime, it is fine with me, I'll open another later.

The steps for reproduction are mentioned already, though I should add a specific validation method. I'll do that in the first comment.

Thanks,
Abhishek

**Comment by dotnetwise** [comment] 2015-02-25 10:13
+1 for this.

An work around is to create a folder in your project root called `cordova-build-override`
Whatever you put in this folder will be copied over the build folder before the actual build.

Therefore, you should add your own `cordova-build-override/platforms/android/AndroidManifest.xml` targeting your own SDK you want.

It will be overwritten and used accordingly.

**Comment by redtree1112** [comment] 2015-06-15 18:57
@dotnetwise 
It's not working. Also info.plist of iOS isn't overwritten even if you place a file inside `cordova-build-override/`. I finally had to write some script to copy them manually.

They might be generated after the copy process is over?

**Comment by dotnetwise** [comment] 2015-06-16 08:10
I think the process was changed in meteor 1.1.0 release - but yes you can always add cordova hooks to copy your files over before_compile

**Comment by Baccanno** [comment] 2015-06-19 14:14
Just to mention that it does not work neither with written in the config.xml it always tries to do with the 22.


```
        <uses-sdk android:minSdkVersion="19" 
        android:targetSdkVersion="19"
        android:maxSdkVersion="19"
        />
```

nor

```
<preference name="android-targetSdkVersion" value="19" />
        <preference name="android-minSdkVersion" value="19" />
```

cordova-android 4.0.2
cordova cli 5.1.1

**Comment by joaopiopedreira** [comment] 2015-06-19 15:20
Hi guys,

I'm using meteor 1.1.0.2 release and this works for me (directly into the mobile-config.js file):

    App.setPreference('android-targetSdkVersion', '19');
    App.setPreference('android-minSdkVersion', '19');
    App.setPreference('android-versionCode', '3');

Hope it helps.

**Comment by artpolikarpov** [comment] 2015-08-23 16:38
@joaopiopedreira, thank you. Works.

**Comment by fableye** [comment] 2015-10-10 18:44
Hello,

I'm using meteor 1.1.9. I have similar problem :

`Manifest merger failed : uses-sdk:minSdkVersion 10 cannot be smaller than
   version 14 declared in library
   /home/fabien/meteor/simple-todos/.meteor/local/cordova-build/platforms/android/build/intermediates/exploded-aar/android/CordovaLib/unspecified/debug/AndroidManifest.xml
   Suggestion: use tools:overrideLibrary="org.apache.cordova" to force usage`

I tried @joaopiopedreira issue, but the genrated file  AndroidManifest.xml  seems always to be the same :

` <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="org.apache.cordova"
    android:versionCode="1"
    android:versionName="1.0" >
    <uses-sdk android:minSdkVersion="14" />
</manifest>`
Does someone have some issue ?

Thanks,

Fabien

**Comment by martijnwalraven** [comment] 2015-10-23 00:47
Is this still an issue with the updated Cordova integration in Meteor 1.2?

**Comment by fableye** [comment] 2015-10-23 08:42
I will try. I choosed to buy a more recent smartphone, so now it's ok. Thanks

**Comment by jamielob** [comment] 2015-10-29 18:58
@martijnwalraven - I've just use the App.setPreference that @joaopiopedreira suggested successfully in 1.2.  

```
App.setPreference('android-targetSdkVersion', '19');
App.setPreference('android-minSdkVersion', '19');
App.setPreference('android-versionCode', '3');
```

**Comment by jamielob** [comment] 2015-10-29 19:01
@martijnwalraven - Is there a full list of supported values for App.setPreference available anywhere?

**Comment by martijnwalraven** [comment] 2015-10-29 19:07
Basically, `App.setPreference` sets preferences on the Cordova `config.xml`, so you can see a list of supported options in the [documentation for that file] (http://cordova.apache.org/docs/en/5.1.1/config_ref_index.md.html#The%20config.xml%20File_global_preferences).

**Comment by jamielob** [comment] 2015-10-29 19:10
Oh great! For some reason I thought that it wasn't mapped directly to setting preferences.  Thanks!

**Comment by jamielob** [comment] 2015-10-29 20:29
@martijnwalraven - I spoke too soon. App.setPreference is setting the config.xml correctly, but then I'm still getting the following error:
```
uses-sdk:minSdkVersion 14 cannot be smaller than version 15
```

Even though when I check the listed AndroidManifest.xml file the following line is present:

```
 <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="22" />
```

Any ideas?

**Comment by jamielob** [comment] 2015-10-29 21:00
Update - it's related to Crosswalk.  Without crosswalk added, and the minSdkVersion set in mobile-config.js it's starting up fine.  However as soon as I add Crosswalk, it seems to ignore the AndroidManifest.xml file.

**Comment by jamielob** [comment] 2015-10-29 21:47
***Solution*** - Ok @martijnwalraven  - so this is a known Crosswalk problem that has just recently been patched:
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/commit/cd24c9cf90ed7741b3364cbd8b2b73d9f7dacb93

I fixed it in my project by removing crosswalk and then adding the latest version instead.
```meteor add cordova:mp-cordova-plugin-crosswalk-webview@1.4.0-dev```

Crosswalk will then obey the minSdkVersion that you set using App.setPreference.

**Comment by martijnwalraven** [comment] 2015-10-29 21:51
@jamielob: Ah, good to know!

**Comment by martijnwalraven** [comment] 2016-02-19 10:41
Going to close this as there hasn't been any activity in a while. Please reopen it if you feel this is still an issue.

**Closed by martijnwalraven** 2016-02-19 10:41 UTC
Labels: backlog, Project:Mobile
