### ISSUE TITLE
less package strips absolute paths

### ISSUE THREAD

**Issue by edemaine** [meteor/meteor#8209] opened 2017-01-02 21:40 UTC
Example file `test.less`:

```less
@font-folder: "/fonts";
@font-face { src: url('@{font-folder}/test.eot'); }
```

Output from `lessc` or `lessc -ru`:

```css
@font-face {
  src: url('/fonts/test.eot');
}
```

Output in `.meteor/local/build/programs/web.browser/merged-stylesheets.css`:

```css
@font-face {
  src: url('fonts/KaTeX_AMS-Regular.eot');
}
```

There seems to be some path magic going on in the `less` package that I couldn't figure out.  Relative URLs like this simply don't work in Meteor when we're trying to refer to static (font) files in the `public` directory.  (Relative paths would depend on the URL of the route being accessed; plus I couldn't even get `../` to be preserved in a font name.)  I could not find any way to get an absolute path emitted in the final CSS.

**Comment by ramezrafla** [comment] 2017-01-24 01:36
If you are referencing static fonts, why do you need less, just add to your css (this is what I do)? I wasn't around when all this was built, but I have a feeling there is clear separation of static vs dynamic. Maybe someone from MDG can comment.

**Comment by edemaine** [comment] 2017-01-24 02:34
I'm trying to use this code: https://github.com/Khan/KaTeX/blob/master/static/fonts.less
Just because it's static stuff doesn't mean it's simple!  Sure, I could compile with `less` into CSS myself, and then include the `.css` in my Meteor project -- but isn't that the point of the `less` Meteor package?

**Comment by abernix** [comment] 2017-01-24 04:23
@edemaine I can understand why you need this and sorry you've run into this bug.  Unfortunately, I don't think this is a common enough issue that it will get looked at very quickly, but if you'd be willing to take a look at this, I'm positive that the problem lies in [this code](https://github.com/meteor/meteor/blob/devel/packages/minifier-css/minifier.js#L122) of the `minifier-css` package – namely in the regex that rewrites the relative URLs.

Instead of relying on a Regex, this might be better detected (if possible, based on the information available) by using the AST, however, a fix to the regex is reasonable too.

If you want to fix it (and add tests to [`minifier-tests.js`](https://github.com/meteor/meteor/blob/devel/packages/minifier-css/minifier-tests.js#L1)), I'd be happy to review a pull-request and get this fixed in a patch release of the `minifier-css` package.  I think this would be a fairly easy Meteor contribution if you'd be willing to help out the project!  What do you think?  Happy to guide however I can!

**Comment by jamesmillerburgess** [comment] 2017-11-23 21:07
I was going to work on this, but I can't seem to reproduce the issue. It looks like `minifier.js` has changed a lot since the issue was reported, so maybe it got fixed in some other changes?

`test.less`
```
@font-folder: '/fonts';
@font-face {
  src: url('@{font-folder}/test.eot');
}
```

`merged-stylesheets.css`
```
@font-face {
  src: url('fonts/test.eot');
}
```
Should I create a PR with just a regression test for this?

**Comment by hwillson** [comment] 2017-11-24 13:17
Great to hear @jamesmillerburgess - thanks for checking! We just switched to using `postcss` behind the scenes in `minifier-css`, so it sounds like this now working is a welcome side effect. Submitting a PR with a regression test for this would be great - thanks!

**Comment by jamesmillerburgess** [comment] 2017-11-24 21:06
The following test passed on several versions of meteor going back to 1.2.2:

```
  checkMinified(
    `@font-face { 
      src:url(/fonts/test.eot);
      font-family: a;
    }
    a {
      font-family:a
    }`,
    '@font-face{src:url(/fonts/test.eot);font-family:a}a{font-family:a}',
    'preserve absolute paths'
  )
```
I've also tried reproducing the issue in an app and a self-test with different versions of meteor and the KaTeX fonts, but no luck.

As I can't isolate the issue, I don't think these would be very meaningful additions to the test suite. I'm not sure what else to check, so let me know if you have any ideas!

**Comment by edemaine** [comment] 2017-11-25 15:25
@jamesmillerburgess Thanks for investigating. Perhaps it's related to the variable expansion in the original example? And probably obvious, but did you downgrade the packages (particularly less) in addition to Meteor? I can try to figure out which version I was using back when I experienced this...

**Comment by hwillson** [comment] 2017-11-28 17:36
Let's close this one off for now then since it can't be reproduced. If this issue comes up again, we'll re-open. Thanks @jamesmillerburgess and @edemaine!

**Closed by hwillson** 2017-11-28 17:36 UTC
Labels: bug, confirmed, Impact:few, Project:CSS, pull-requests-encouraged, Severity:has-workaround
