### ISSUE TITLE
Keep getting stuck on 'Starting your app' on Windows

### ISSUE THREAD

**Issue by ErmosK** [meteor/meteor#4140] opened 2015-04-06 16:46 UTC
Running with --verbose and it keeps getting stuck there. Tried removing the mongodb lock numerous times to no avail.

Here is the output of --verbose

C:\Projects\meteorapp>meteor run --verbose
% Parsing the --port option
[[[[[ C:\Projects\meteorapp]]]]]

=> Started proxy.
Local package version is up-to-date: accounts-base@1.2.0
Local package version is up-to-date: accounts-facebook@1.0.4
Local package version is up-to-date: accounts-google@1.0.4
Local package version is up-to-date: accounts-oauth@1.1.5
Local package version is up-to-date: accounts-password@1.1.1
Local package version is up-to-date: aldeed:autoform@5.1.2
Local package version is up-to-date: aldeed:simple-schema@1.3.2
Local package version is up-to-date: autopublish@1.0.3
Local package version is up-to-date: autoupdate@1.2.1
Local package version is up-to-date: base64@1.0.3
Local package version is up-to-date: binary-heap@1.0.3
Local package version is up-to-date: blaze@2.1.2
Local package version is up-to-date: blaze-tools@1.0.3
Local package version is up-to-date: boilerplate-generator@1.0.3
Local package version is up-to-date: callback-hook@1.0.3
Local package version is up-to-date: check@1.0.5
Local package version is up-to-date: chuangbo:cookie@1.1.0
Local package version is up-to-date: ddp@1.1.0
Local package version is up-to-date: deps@1.0.7
Local package version is up-to-date: ejson@1.0.6
Local package version is up-to-date: email@1.0.6
Local package version is up-to-date: facebook@1.2.0
Local package version is up-to-date: fastclick@1.0.3
Local package version is up-to-date: geojson-utils@1.0.3
Local package version is up-to-date: google@1.1.5
Local package version is up-to-date: html-tools@1.0.4
Local package version is up-to-date: htmljs@1.0.4
Local package version is up-to-date: http@1.1.0
Local package version is up-to-date: id-map@1.0.3
Local package version is up-to-date: insecure@1.0.3
Local package version is up-to-date: iron:controller@1.0.7
Local package version is up-to-date: iron:core@1.0.7
Local package version is up-to-date: iron:dynamic-template@1.0.7
Local package version is up-to-date: iron:layout@1.0.7
Local package version is up-to-date: iron:location@1.0.7
Local package version is up-to-date: iron:middleware-stack@1.0.7
Local package version is up-to-date: iron:router@1.0.7
Local package version is up-to-date: iron:url@1.0.7
Local package version is up-to-date: jquery@1.11.3_2
Local package version is up-to-date: json@1.0.3
Local package version is up-to-date: launch-screen@1.0.2
Local package version is up-to-date: less@1.0.14
Local package version is up-to-date: livedata@1.0.13
Local package version is up-to-date: localstorage@1.0.3
Local package version is up-to-date: logging@1.0.7
Local package version is up-to-date: meteor@1.1.6
Local package version is up-to-date: meteor-platform@1.2.2
Local package version is up-to-date: meteorhacks:fast-render@2.3.1
Local package version is up-to-date: meteorhacks:inject-data@1.2.2
Local package version is up-to-date: meteorhacks:picker@1.0.2
Local package version is up-to-date: minifiers@1.1.5
Local package version is up-to-date: minimongo@1.0.8
Local package version is up-to-date: mobile-status-bar@1.0.3
Local package version is up-to-date: momentjs:moment@2.8.4
Local package version is up-to-date: mongo@1.1.0
Local package version is up-to-date: npm-bcrypt@0.7.8_2
Local package version is up-to-date: oauth@1.1.4
Local package version is up-to-date: oauth2@1.1.3
Local package version is up-to-date: observe-sequence@1.0.6
Local package version is up-to-date: ordered-dict@1.0.3
Local package version is up-to-date: pauli:accounts-linkedin@1.1.2
Local package version is up-to-date: pauli:linkedin@1.1.2
Local package version is up-to-date: random@1.0.3
Local package version is up-to-date: reactive-dict@1.1.0
Local package version is up-to-date: reactive-var@1.0.5
Local package version is up-to-date: reload@1.1.3
Local package version is up-to-date: retry@1.0.3
Local package version is up-to-date: routepolicy@1.0.5
Local package version is up-to-date: sacha:spin@2.0.4
Local package version is up-to-date: service-configuration@1.0.4
Local package version is up-to-date: session@1.1.0
Local package version is up-to-date: sha@1.0.3
Local package version is up-to-date: spacebars@1.0.6
Local package version is up-to-date: spacebars-compiler@1.0.6
Local package version is up-to-date: splendido:accounts-meld@1.2.0
Local package version is up-to-date: srp@1.0.3
Local package version is up-to-date: templating@1.1.1
Local package version is up-to-date: tracker@1.0.7
Local package version is up-to-date: ui@1.0.6
Local package version is up-to-date: underscore@1.0.3
Local package version is up-to-date: url@1.0.4
Local package version is up-to-date: webapp@1.2.0
Local package version is up-to-date: webapp-hashing@1.0.3
   Starting your app                         \

**Comment by ErmosK** [comment] 2015-04-06 16:53
Just a few notes. Tried also doing meteor reset, no help. It also sometimes gets stuck on starting proxy as well. 

Windows 8.1

**Comment by ErmosK** [comment] 2015-04-06 16:59
Without verbose :

=> Started proxy.
=> Started MongoDB.

**Comment by Slava** [comment] 2015-04-06 18:07
This is quite a mysterious behavior, I guess, the best we can do right now is to ask you a bunch of "diagnosis" questions:

- how much free space do you have left on disk C?
- what filesystem are you running?
- when your process gets "stuck", how long have you waited for it to be done? Is the CPU % high on the "node or mongodb"-related processes in the task manager?

**Comment by ErmosK** [comment] 2015-04-06 18:45
- I've got ~43GB on my C drive (Samsung 840 PRO SSD if that matters at all)
- Running NTFS
- I've waited for over 5 minutes. The 'mongod' process takes 24.9MB which is negligible. I've got quite a beefy system (Core i7 4790k, 16GB RAM, etc. Can provide full specs if necessary to pinpoint the issue).

**Comment by Slava** [comment] 2015-04-06 20:30
@ErmosK for the last bullet point: I was more interested if the process is actually doing anything useful or just spinning waiting for something.

**Comment by ErmosK** [comment] 2015-04-06 20:42
CPU Utilization was between 0% and 0.1%

**Comment by ErmosK** [comment] 2015-04-06 20:46
Also please note; this happens randomly. I have managed to run my meteor project on windows yesterday, and I have managed to run it once or twice today as well.

**Comment by ErmosK** [comment] 2015-04-07 06:19
This was on Meteor 1.1.0.1 but also happening on 1.1.0.2

**Comment by ErmosK** [comment] 2015-04-08 19:19
Any updates on this? Any indication what might be wrong/how to resolve?

**Comment by ErmosK** [comment] 2015-04-08 19:36
Ok.. I've done some digging around. I created a new project and it seems to work fine. So it has to do something with my pre-existing project (which I started on linux) and trying to run on Windows. Maybe one of the packages is incompatible?

**Comment by velum** [comment] 2015-08-10 20:28
Anything new on this? I am also having that problem, I am running Meteor on Windows 8.

**Comment by vyasamit2007** [comment] 2015-09-24 13:39
Having the same issue. Did anyone fixed this already?

Thanks!!
~Amit

**Comment by s-bhandari** [comment] 2016-10-11 04:42
Still facing the issue running meteor (1.4.1.2) on windows 8.1. Works fine on windows 10 x64.

System get stuck at following
Starting your app \

Any help is appreciated.

Regards

Saurabh

**Comment by laosb** [comment] 2016-11-05 14:08
Interestingly, I hit this on Meteor 1.4.2 on macOS Sierra. That's strange.

**Comment by abernix** [comment] 2016-11-08 12:23
On Windows, I would recommend a reinstall and updating to at least 1.4.2 for this – as the Mongo issue has definitely been improved through the versions, including notable changes in Meteor 1.4.2.

@laosb I'm not sure how your issue is related to this, but I wouldn't suggest +1'ing a Windows issue with a macOS issue like this which has so many other things which could be happening during startup.  Generally, something like this _has_ been caused by Mongo, but it's impossible to say.  Happy to try and help you debug this on OS X, but there's very likely a completely different issue at hand.

Closing this as there is really no helpful information in here to narrow this down.

**Closed by abernix** 2016-11-08 12:23 UTC
Labels: Project:Windows

**Comment by meteorplus** [comment] 2017-09-14 13:38
try doing npm start instead of meteor --settings settings.json

and put in the package.js

this in start 

{
  "name": "YourAppName",
  "version": "1.0.0",
  "engines": {
    "npm": "^3.0"
  },
  "scripts": {
    "start": "meteor --settings settings.json",

**Comment by yogesh249** [comment] 2019-04-01 06:33
I did a meteor reset, and it worked fine. Last time I had to shutdown abruptly using Ctrl+C because I don't know how else I should shut it down....

But meteor reset is not a solution, as it wipes out all the data in the database.
