### ISSUE TITLE
Data not synchronize

### ISSUE THREAD

**Issue by GuofuHuang** [meteor/meteor#8180] opened 2016-12-21 15:56 UTC
I find out that when Meteor connect to a remote MongoDB database, the reactive data in helpers() won't synchronize as it should be, is that correct?

Is there an easy way to synchronize them?

**Comment by laosb** [comment] 2016-12-24 01:59
This is not a bug report. Please include more information for us to investigate, eg. The code your app connects to remote MongoDB instance with, your helper code and better, a minimal repro.

Anyway, reactivity should be there out of box.

**Comment by abernix** [comment] 2016-12-30 14:42
Closing for the above reason.

**Closed by abernix** 2016-12-30 14:42 UTC
