### ISSUE TITLE
install-sdk android failing: invalid --abi x86

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#2848] opened 2014-10-18 01:31 UTC
Please let me know what I can do to further diagnose. Meteor `0.9.4`, OS X 10.9.5.

```
meteor create --example todos
cd todos
meteor install-sdk android

✓ Found Android bundle
✓ A JDK is installed
✗ Android emulator acceleration is not installed
    (The Android emulator will be very slow without acceleration)
Installing Android x86 image
✓ Installed Android x86 image
Creating android virtual device (AVD): meteor
[====================] 100% 0.0sUnexpected exit code 1 from /Users/me2/.meteor/android_bundle/android-sdk/tools/android [ 'create',
  'avd',
  '--target',
  '1',
  '--name',
  'meteor',
  '--abi',
  'default/x86',
  '--path',
  '/Users/me2/.meteor/android_bundle/meteor_avd' ] 
stdout:
 Valid ABIs: default/armeabi-v7a
 
stderr:
 Error: Invalid --abi x86 for the selected target.

Unexpected exit code from android process: 1
stdout: Valid ABIs: default/armeabi-v7a

stderr: Error: Invalid --abi x86 for the selected target.


/Users/me2/.meteor/packages/meteor-tool/.1.0.34.1ok1f6v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: Error running android tool: exit code 1
    at _.extend.runAndroidTool (/Users/me2/.meteor/packages/meteor-tool/.1.0.34.1ok1f6v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:1826:13)
    at /Users/me2/.meteor/packages/meteor-tool/.1.0.34.1ok1f6v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:1946:12
    at /Users/me2/.meteor/packages/meteor-tool/.1.0.34.1ok1f6v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:316:16
    at _.extend.withValue (/Users/me2/.meteor/packages/meteor-tool/.1.0.34.1ok1f6v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at Object.enterJob (/Users/me2/.meteor/packages/meteor-tool/.1.0.34.1ok1f6v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:307:26)
    at _.extend.createAvd (/Users/me2/.meteor/packages/meteor-tool/.1.0.34.1ok1f6v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:1928:18)
    at _.extend.checkRequirements (/Users/me2/.meteor/packages/meteor-tool/.1.0.34.1ok1f6v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:2255:16)
    at checkPlatformRequirements (/Users/me2/.meteor/packages/meteor-tool/.1.0.34.1ok1f6v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:1156:20)
    at null.func (/Users/me2/.meteor/packages/meteor-tool/.1.0.34.1ok1f6v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:2476:19)
    at /Users/me2/.meteor/packages/meteor-tool/.1.0.34.1ok1f6v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1255:23
```

**Comment by guilhermebruzzi** [comment] 2015-04-05 17:02
I was getting a similar error:
stdout:
 Valid ABIs: default/armeabi

stderr:
 Error: Invalid --abi x86 for the selected target.

And the command that meteor tries to run is similar to:
android create avd --target 1 --name meteor --abi default/x86 --path ~/.android/avd/meteor.avd

When i did: android list targets

I saw that the problem is that meteor always tries to use target id 1 when creating his avd, and my target 1 was an old android without abi default/x86.

The latest version of android with default/x86 i had was target id 9 on the list.

So after manually executing:
android create avd --target 9 --name meteor --abi default/x86 --path ~/.android/avd/meteor.avd

"meteor install-sdk android" was executed correctly.

I would suggest that meteor create an option to pass an avd that already exists or at least a target id to use on its installation.

**Comment by glasser** [comment] 2015-04-06 19:14
@guilhermebruzzi Good find!  Do you know what command can be used to figure out which target is correct automatically?  A pull request to improve the `createAvd` function in `tools/commands-cordova.js` would be great.

**Comment by guilhermebruzzi** [comment] 2015-04-06 19:36
@glasser Hi Glasser. I don't think there is a command to find the "best choice" (you can try to find the first avd which support x86, but i don't know if that is a good thing to do).
I think its possible to let the user choose from "android list targets" and select an target id to use.
I cloned the meteor project and thought about contributing. But i discovered that i don't have to only change createAvd function to include an "target" in options, i also have to change main.registerCommand({ name: 'install-sdk', ... to accept a parameter only when is android, so that the command can be something like "meteor install-sdk android --target 9".
And i don't know exactly how to do that, because i only saw a way of adding a parameter just like verbose and the command would be: "meteor install-sdk --target 9 android"  (and ignore that on ios or throw an error).
What do you think is the best solution? Any help on how to build that also?

**Comment by alpjor** [comment] 2015-05-29 18:08
FYI, even using the devel branch of meteor cloned today, I ran into this issue.

**Comment by gchpaco** [comment] 2015-06-10 21:23
Thanks for your report; I have pushed a fix to `devel`now.

**Closed** 2015-06-10 21:23 UTC
Labels: Project:Mobile
