### ISSUE TITLE
Package api.addFiles like client/compatibility

### ISSUE THREAD

**Issue by jamgold** [meteor/meteor#4695] opened 2015-07-07 15:13 UTC
I couldn't find documentation about how to include a file in a package unaltered, just the same as when adding it to the client/compatibility folder. Looking at the code it should work when adding `{bare: true}` to the addFiles call, but it does not seem to work correctly, the added file is still being wrapped into the overall package code (as far as I can tell).

Can this be done in a package?

**Comment by glasser** [comment] 2015-07-07 20:44
Duplicate of #3984.

Whole packages always will end up wrapped in a closure.  Use `api.export` to export variables from packages.  (In the future, we hope to move towards standard ES6 modules.)

**Closed by glasser** 2015-07-07 20:44 UTC
Labels: Project:Docs, Project:Isobuild
