### ISSUE TITLE
(STDERR) FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory 

### ISSUE THREAD

**Issue by manishchainThat** [meteor/meteor#9832] opened 2018-04-20 16:32 UTC
I am getting the above error while running the app in production environment (linux) but working fine in the  local (mac).Actually,I have added a functionality for consuming the objects from queue which is being filled by the any event happening from the Application server.For example,I am creating a record the created record first pushed into a queue which is in the ActiveMq broker.And From meteor server side , we are consuming the records via stompjs client(code below).While running the code in the production , i am constantly getting out of memory issue.

Code Snippets 🚔 
-----------------------------------------------------------------------------------------------
```js
stompClient.connect(
  headers, 
  Meteor.bindEnvironment(function startStreamingDraftFacility(frame) {
    stompClient.subscribe(
      DRAFT_FACILITY_QUEUE,
      Meteor.bindEnvironment(function sendDraftFacility(update,err) {
        if (update) {
          console.log('########### Subscribed ################'+update);
          let draftFacility = JSON.parse(update.body);
          Meteor.call('refreshDraftFacility',draftFacility);
        }
        client.disconnect();
      })
    )
```
---------------------------------------------------------------------------------------
Below is the error:
--------------------------------------------------------------------------------------
```
I20180420-14:00:28.737(0)? Security context: 0x3124444b4629 <JS Object>
I20180420-14:00:28.738(0)?     1: /* anonymous */ [packages/underscore.js:128] [pc=0x1b005d4b3fd4] (this=0x3124444d79f9 <JS Global Object>,obj=0x1c49de051849 <an Object with map 0x35719ad5579>)
I20180420-14:00:28.738(0)?     2: /* anonymous */(aka /* anonymous */) [/home/xcct_admin/CT-IBF-Meteor/framework/.meteor/local/build/programs/server/packages/mongo.js:~169] [pc=0x1b005d9227f9] (this=0x3124444041b9 <undefined>,document=0x1c49de051849 <an Obj...
I20180420-14:00:28.739(0)? 
W20180420-14:00:28.744(0)? (STDERR) FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
=> Exited from signal: SIGABRT
I20180420-14:00:37.630(0)? calling market publishing js
```

Please help !!!!!!!!

**Comment by hwillson** [comment] 2018-05-02 13:02
Unfortunately there are hundreds of reasons why your application could be encountering `process out of memory` errors. This isn't really something we can help with, given the small code snippets and error messages you've provided. Something is chewing up your memory, and if this is only happening in production, then I would guess that it's happening because of additional load on your application. Something is incrementally holding onto memory, as your application has additional users hit it. You might want to try load testing your application locally to see if that helps replicate the problem. Your code sample doesn't show much, but what `client` are you disconnecting in your `subscribe` callback? `client` isn't defined anywhere else in your code sample, so it doesn't look like you're trying to disconnect your `stompClient` connection. If it is associated with your `stompClient` connection, are you sure the connection is always being shutdown, when expected? Maybe the connection is being held open, which in turn prevents Node's garbage collection from doing its thing.

If you're able to provide a small runnable reproduction that demonstrates this issue (and points towards it being a Meteor core problem), then we'll take a closer look. I'll close this for now though. Thanks!

**Closed by hwillson** 2018-05-02 13:02 UTC
