### ISSUE TITLE
Crash when start after update to 1.2 on windows

### ISSUE THREAD

**Issue by gallen** [meteor/meteor#5227] opened 2015-09-22 02:41 UTC
Here is the error I got, anyone got the same?

[[[[[ ~\D\meteor\leaderboard ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Exited with code: 8
[34mW20150921-22:38:55.168(-4)? (STDERR) [39m[35m[39m
[34mW20150921-22:38:55.170(-4)? (STDERR) [39m[35mC:\Users\gliu\AppData\Local\.meteor\packages\meteor-tool\1.1.7\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245[39m
[34mW20150921-22:38:55.170(-4)? (STDERR) [39m[35m						throw(ex);[39m
[34mW20150921-22:38:55.170(-4)? (STDERR) [39m[35m						      ^[39m
[34mW20150921-22:38:55.170(-4)? (STDERR) [39m[35mTypeError: Cannot read property '_CurrentInvocation' of undefined[39m
[34mW20150921-22:38:55.170(-4)? (STDERR) [39m[35m    at withoutInvocation (packages/meteor/packages/meteor.js:404:1)[39m
[34mW20150921-22:38:55.171(-4)? (STDERR) [39m[35m    at bindAndCatch (packages/meteor/packages/meteor.js:414:1)[39m
[34mW20150921-22:38:55.171(-4)? (STDERR) [39m[35m    at Object._.extend.defer (packages/meteor/packages/meteor.js:469:1)[39m
[34mW20150921-22:38:55.171(-4)? (STDERR) [39m[35m    at [object Object].MongoConnection.tail (packages/mongo/packages/mongo.js:1136:1)[39m
[34mW20150921-22:38:55.171(-4)? (STDERR) [39m[35m    at [object Object]._.extend._startTailing (packages/mongo/packages/mongo.js:1602:1)[39m
[34mW20150921-22:38:55.171(-4)? (STDERR) [39m[35m    at new OplogHandle (packages/mongo/packages/mongo.js:1441:1)[39m
[34mW20150921-22:38:55.171(-4)? (STDERR) [39m[35m    at new MongoConnection (packages/mongo/packages/mongo.js:224:1)[39m
[34mW20150921-22:38:55.172(-4)? (STDERR) [39m[35m    at new MongoInternals.RemoteCollectionDriver (packages/mongo/packages/mongo.js:3353:1)[39m
[34mW20150921-22:38:55.172(-4)? (STDERR) [39m[35m    at Object.<anonymous> (packages/mongo/packages/mongo.js:3387:1)[39m
[34mW20150921-22:38:55.172(-4)? (STDERR) [39m[35m    at Object.defaultRemoteCollectionDriver (packages/underscore/packages/underscore.js:779:1)[39m
[34mW20150921-22:39:08.139(-4)? (STDERR) [39m[35m[39m
[34mW20150921-22:39:08.139(-4)? (STDERR) [39m[35mC:\Users\gliu\AppData\Local\.meteor\packages\meteor-tool\1.1.7\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245[39m
[34mW20150921-22:39:08.139(-4)? (STDERR) [39m[35m						throw(ex);[39m
[34mW20150921-22:39:08.140(-4)? (STDERR) [39m[35m						      ^[39m
[34mW20150921-22:39:08.140(-4)? (STDERR) [39m[35mTypeError: Cannot read property '_CurrentInvocation' of undefined[39m
[34mW20150921-22:39:08.140(-4)? (STDERR) [39m[35m    at withoutInvocation (packages/meteor/packages/meteor.js:404:1)[39m
[34mW20150921-22:39:08.140(-4)? (STDERR) [39m[35m    at bindAndCatch (packages/meteor/packages/meteor.js:414:1)[39m
[34mW20150921-22:39:08.140(-4)? (STDERR) [39m[35m    at Object._.extend.defer (packages/meteor/packages/meteor.js:469:1)[39m
[34mW20150921-22:39:08.140(-4)? (STDERR) [39m[35m    at [object Object].MongoConnection.tail (packages/mongo/packages/mongo.js:1136:1)[39m
[34mW20150921-22:39:08.141(-4)? (STDERR) [39m[35m    at [object Object]._.extend._startTailing (packages/mongo/packages/mongo.js:1602:1)[39m
[34mW20150921-22:39:08.141(-4)? (STDERR) [39m[35m    at new OplogHandle (packages/mongo/packages/mongo.js:1441:1)[39m
[34mW20150921-22:39:08.141(-4)? (STDERR) [39m[35m    at new MongoConnection (packages/mongo/packages/mongo.js:224:1)[39m
[34mW20150921-22:39:08.141(-4)? (STDERR) [39m[35m    at new MongoInternals.RemoteCollectionDriver (packages/mongo/packages/mongo.js:3353:1)[39m
[34mW20150921-22:39:08.141(-4)? (STDERR) [39m[35m    at Object.<anonymous> (packages/mongo/packages/mongo.js:3387:1)[39m
[34mW20150921-22:39:08.142(-4)? (STDERR) [39m[35m    at Object.defaultRemoteCollectionDriver (packages/underscore/packages/underscore.js:779:1)[39m
=> Exited with code: 8
[34mW20150921-22:39:21.009(-4)? (STDERR) [39m[35m[39m
[34mW20150921-22:39:21.009(-4)? (STDERR) [39m[35mC:\Users\gliu\AppData\Local\.meteor\packages\meteor-tool\1.1.7\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245[39m
[34mW20150921-22:39:21.010(-4)? (STDERR) [39m[35m						throw(ex);[39m
[34mW20150921-22:39:21.010(-4)? (STDERR) [39m[35m						      ^[39m
[34mW20150921-22:39:21.010(-4)? (STDERR) [39m[35mTypeError: Cannot read property '_CurrentInvocation' of undefined[39m
[34mW20150921-22:39:21.010(-4)? (STDERR) [39m[35m    at withoutInvocation (packages/meteor/packages/meteor.js:404:1)[39m
[34mW20150921-22:39:21.010(-4)? (STDERR) [39m[35m    at bindAndCatch (packages/meteor/packages/meteor.js:414:1)[39m
[34mW20150921-22:39:21.011(-4)? (STDERR) [39m[35m    at Object._.extend.defer (packages/meteor/packages/meteor.js:469:1)[39m
[34mW20150921-22:39:21.011(-4)? (STDERR) [39m[35m    at [object Object].MongoConnection.tail (packages/mongo/packages/mongo.js:1136:1)[39m
[34mW20150921-22:39:21.011(-4)? (STDERR) [39m[35m    at [object Object]._.extend._startTailing (packages/mongo/packages/mongo.js:1602:1)[39m
[34mW20150921-22:39:21.011(-4)? (STDERR) [39m[35m    at new OplogHandle (packages/mongo/packages/mongo.js:1441:1)[39m
[34mW20150921-22:39:21.011(-4)? (STDERR) [39m[35m    at new MongoConnection (packages/mongo/packages/mongo.js:224:1)[39m
[34mW20150921-22:39:21.012(-4)? (STDERR) [39m[35m    at new MongoInternals.RemoteCollectionDriver (packages/mongo/packages/mongo.js:3353:1)[39m
[34mW20150921-22:39:21.012(-4)? (STDERR) [39m[35m    at Object.<anonymous> (packages/mongo/packages/mongo.js:3387:1)[39m
[34mW20150921-22:39:21.012(-4)? (STDERR) [39m[35m    at Object.defaultRemoteCollectionDriver (packages/underscore/packages/underscore.js:779:1)[39m
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by stolinski** [comment] 2015-09-22 03:49
I'm getting the same "Cannot read property 'CurrentInvocation' of undefined"  but on OSX. Doesn't happen on  rc17, but upgrading to 1.2 causes the error.

**Comment by martijnwalraven** [comment] 2015-09-22 04:43
This indeed seems like a duplicate of #5228, closing this one.

**Closed by martijnwalraven** 2015-09-22 04:43 UTC
