### ISSUE TITLE
Implied dependencies not found

### ISSUE THREAD

**Issue by davidworkman9** [meteor/meteor#7215] opened 2016-06-14 17:06 UTC
two problems: 

### devDependencies

repro:

```
git clone git@github.com:davidworkman9/meteorTestBugIn1.3.3.git
cd meteorTestBugIn1.3.3
meteor npm install
meteor test --driver-package practicalmeteor:mocha --port 3100
```

Currently getting this when trying to run tests under 1.3.3. Tried running ```meteor npm install has``` but that didn't solve it.

```
/Users/dave/.meteor/packages/meteor-tool/.1.3.3.ems6rm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
                                            throw(ex);
Error: Can't find npm module 'has'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
     at Object.Npm.require (/private/var/folders/lg/zn86p4bn5m716q1wn7gjr46c0000gn/T/meteor-test-run1dmhmja/.meteor/local/build/programs/server/boot.js:203:17)
     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:88:1)
     at meteorInstall.node_modules.expect.lib.Expectation.js (node_modules/expect/lib/Expectation.js:11:1)
     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
     at meteorInstall.node_modules.expect.lib.index.js (node_modules/expect/lib/index.js:3:1)
     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
     at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
     at Module.Mp.import (/Users/dave/.meteor/packages/modules/.0.6.2.qhcqvd++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:52:16)
```

`has` is a dependency of `expect`, which is included in `package.json` under `devDependencies`. You see the above error on both the client and server. 

### after code reload

If you change `devDependencies` to `dependencies`, the error goes away until a hot code reload, after which it appears on the client. Repro: https://github.com/lorensr/meteorTestBugIn1.3.3 and video: https://youtu.be/J1pA53rZP20

From aldeed: 

We are having this problem on 1.3.3, too. It happens not only when running tests, but also when running the app locally, ONLY AFTER changing a client file. On initial load, app is fine, then the first time the browser hot reloads, we get these import errors.

This does NOT have a workaround and is a severe issue.

**Comment by lorensr** [comment] 2016-06-14 23:29
Hi David, looking at the output I'm not sure what the problem is – are you able to reproduce this in an a new repo? https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor

**Comment by davidworkman9** [comment] 2016-06-15 16:05
I was able to reproduce this in a fairly small package:

https://github.com/davidworkman9/meteorTestBugIn1.3.3

```
meteor npm install
meteor test --driver-package practicalmeteor:mocha --port 3100
```

**Comment by lorensr** [comment] 2016-06-15 21:34
Thanks! I got the same error. Fixed by switching `devDependencies` in `package.json` to `dependencies`. The former is for eg grunt – something used during development, but not by the app code.

**Comment by davidworkman9** [comment] 2016-06-16 14:00
I'm still getting the error on the client after a test rebuild. This works prior to 1.3.3.

Everything I've ever read said that ```devDependencies``` were for things your app only needed in development. I don't need to run my unit tests in production, so I don't agree that a testing library should be in my ```dependencies```.

**Comment by davidworkman9** [comment] 2016-06-16 14:08
I can confirm that using my github repo this happens as well.
* changed ```devDependencies``` to ```dependencies```
* ran ```meteor npm install```
* ran ```meteor test --driver-package practicalmeteor:mocha --port 3100```
* looked at ```localhost:3100```.
* added a space to ```file.test.jsx``` and saved
* when ```localhost:3100``` rebuilt the following error was in the console.

```
Uncaught Error: Cannot find module 'has'
require @ install.js:85
meteorInstall.node_modules.expect.lib.Expectation.js @ Expectation.js:11
fileEvaluate @ install.js:153
require @ install.js:82
meteorInstall.node_modules.expect.lib.index.js @ index.js:3
fileEvaluate @ install.js:153
require @ install.js:82
Mp.import @ runtime.js:52
meteorInstall.imports.file.test.jsx @ file.test.jsx:1
fileEvaluate @ install.js:153
require @ install.js:82
(anonymous function) @ app.js?hash=bbe7d86…:13
```

**Comment by lorensr** [comment] 2016-06-16 15:05
Oops right, we're testing here 😄

I tried again, and still don't get the error on server or client after the change: 

https://github.com/lorensr/meteorTestBugIn1.3.3

**Comment by davidworkman9** [comment] 2016-06-16 15:41
Much better title thanks!

I'm not sure what you're doing differently than me then, here's a video of what I do. This is after a fresh ```git clone``` from my repo.

https://youtu.be/J1pA53rZP20

**Comment by lorensr** [comment] 2016-06-16 15:49
Thanks for video, now I'm also seeing the client error after reload.

**Comment by aldeed** [comment] 2016-06-16 16:13
We are having this problem on 1.3.3, too. It happens not only when running tests, but also when running the app locally, ONLY AFTER changing a client file. On initial load, app is fine, then the first time the browser hot reloads, we get these import errors.

This does NOT have a workaround and is a severe issue.

**Comment by lorensr** [comment] 2016-06-16 16:21
@benjamn looks like this is an important regression to fix

**Comment by benjamn** [comment] 2016-06-16 17:44
These are definitely bugs that should be fixed asap. Thanks for reporting them.

In the meantime, here's a workaround for the second problem:
```js
import "expect/node_modules/has";
```
Put that `import` declaration anywhere in your client code, and the `package.json` file for the `has` package will definitely be included.

**Comment by davidworkman9** [comment] 2016-06-16 20:00
Thanks @benjamn. The workaround didn't quite work for me. I included it in a client only test file, and that made it work up until it came to a file that was only being ran on the client.

But, it's not really a big deal for me because it looks like you guys will have this resolved in short order.

**Comment by benjamn** [comment] 2016-06-17 21:02
This should be fixed in Meteor 1.3.3.1, which you can try by running `meteor update --release 1.3.3.1`. In case you're curious why the `has` package was affected in this way: https://github.com/meteor/meteor/commit/3f3a6dc6b59e67684694e06211daf42bdd9ae89d

**Closed by benjamn** 2016-06-17 21:02 UTC
Labels: bug, confirmed, Impact:some, in progress, known-fix, Severity:blocks-development

**Comment by lorensr** [comment] 2016-06-17 21:29
Haha, that's a funny one. Thank you @davidworkman9 @aldeed for reporting! 🙌😊

**Comment by aldeed** [comment] 2016-06-17 21:35
Interestingly, there are npm pkgs with all three of those names. :)

**Comment by benjamn** [comment] 2016-06-17 21:41
funny/sad… https://twitter.com/benjamn/status/743920313713451008
