### ISSUE TITLE
Click event handlers are sometimes not triggered

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2850] opened 2014-10-18 08:09 UTC
See [example project](https://github.com/mitar/meteor-issue2850). Open it (always open clean, not with hot-reload, to make reproduction clear):
- open Developer Tools
- click on "Sign in"
- document level line appears in the console
- click anywhere in the opened dialog (for example, email input form)
- both template level and document level lines appear in the console
- click on "Create account"
- only document level line appear in the console

This is unexpected. What would be expected is that both template level and document level events would be triggered in all cases. Click on a template is click, no? Why template level clicks are not triggered in those two cases above (clicking on "Sign in" and clicking on "Create account").

**Comment by hwillson** [comment] 2016-10-28 13:57
I can confirm this is still an issue (using Meteor 1.4.2, blaze 2.1.9 and accounts-ui-unstyled 1.1.13). A quick workaround to this problem is to register login button/link click events in a Template `onRendered` callback, instead of within the Template's event map. For example, modify @mitar's repro as follows:

**test-events.js**

```
if (Meteor.isClient) {
  $(document).on('click', function (event) {
    console.log("document level", event);
  });

  Template.loginButtons.onRendered(function onRendered() {
    this.$('#login-buttons').on('click', (event) => {
      console.log("template level", event);
    });
  });

  // Template.loginButtons.events({
  //   'click': function (event, template) {
  //     console.log("template level", event);
  //   }
  // });
}
```

This will make sure the Template level `click` event is triggered on all login elements.

The above workaround is clearly a hack though, so I've copied this issue over to the Blaze repo as meteor/blaze#143.

**Comment by hwillson** [comment] 2016-10-28 13:58
Sorry, forgot to add - since this is now being tracked in the Blaze repo, this issue can be closed. Thanks!

**Comment by abernix** [comment] 2016-10-28 14:53
Great triage.  Thanks, @hwillson.

Closing in favor of meteor/blaze#143.

**Closed by abernix** 2016-10-28 14:53 UTC
Labels: Project:Blaze
