### ISSUE TITLE
V1.4.2.3 on Windows 7 Refresh problems

### ISSUE THREAD

**Issue by pavlism** [meteor/meteor#8106] opened 2016-11-25 21:03 UTC
I have been using the latest version for a few days now and have seen errors with the refresher.

1. It misses new files.  I have often added new files, but the refresher doesn't pick up their changes.  It will pick up the file exists, but after I change it the changes don't trigger a refresh, and a refresh cause by changes in other files doesn't pick up changes in the new file. Restarting meteor fixes this.

2.  I seem to randomly end up with 2 sets of error (pictured below).  Restarting meteor fixes these problems as well.

![meteor bugs](https://cloud.githubusercontent.com/assets/12664484/20635219/49ff7424-b328-11e6-88f0-c7558d1ccaa2.png)

My machine:
Time of this report: 11/25/2016, 16:02:19
Machine name: GHQPJ02
Operating System: Windows 7 Professional 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_gdr.150525-0603)
Language: English (Regional Setting: English)
System Manufacturer: Dell Inc.
System Model: OptiPlex 3010
BIOS: BIOS Date: 09/16/13 09:02:29 Ver: A11.00 
Processor: Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz (4 CPUs), ~3.4GHz
Memory: 4096MB RAM
Available OS Memory: 3998MB RAM
Page File: 4912MB used, 3081MB available
Windows Dir: C:\Windows
DirectX Version: DirectX 11
DX Setup Parameters: Not found
User DPI Setting: Using System DPI
System DPI Setting: 96 DPI (100 percent)
DWM DPI Scaling: Disabled
DxDiag Version: 6.01.7601.17514 32bit Unicode

**Comment by abernix** [comment] 2016-12-16 13:16
The problem you're referring to is too vague to accurately provide help.  Is there any way you could provide a reproduction, and preferably a reproduction that could be cloned from GitHub and simply ran? (It's fine if some additional steps need to be taken, but please make them minimal and explain exactly what they are).

Thanks!

**Comment by pavlism** [comment] 2016-12-16 14:17
If your using the same version on windows 7 and your refreshing works, then close the issue.  It must be something wrong with my computer.  I did some testing in another machine and it seems to work fine.  Close the issue and my apologies for wasting your time.

**Comment by nizulzaim** [comment] 2016-12-17 19:48
Hi, i am also have same problem. Right now, some file in imports folder are not update when adding new file or changing file contents. I need to rerun meteor in project folder or make some change in server so that it can rebuild the package. But i dont have any error like @pavlism log. The problem only exist if i make file changing or adding in imports folder. the best way to fix it right now is back to 1.4.1.3 version.

**Comment by nizulzaim** [comment] 2016-12-18 03:42
Btw, i am using Windows 10 not windows 7.

**Comment by wesleyfsmith** [comment] 2016-12-23 21:06
I have this same issue on Windows 10. Difficult to reliably reproduce, but seems to happen when I make a bunch of rapid changes and keep re-saving my files, it will sometimes stop noticing the new changes. Will provide more information as I triage.

**Comment by tab00** [comment] 2017-02-08 04:22
This is similar to https://github.com/meteor/meteor/issues/8164

I think there is a problem in the detection of new or modified files.

**Comment by abernix** [comment] 2017-07-27 07:19
Closing in favor of #8164 but also since the original poster reported that it did not happen on another computer.

**Closed by abernix** 2017-07-27 07:19 UTC
Labels: can't-reproduce, Project:Windows
