### ISSUE TITLE
Custom watch folders for Meteor's rebuild

### ISSUE THREAD

**Issue by ahmadsholehin** [meteor/meteor#9251] opened 2017-10-20 15:34 UTC
We're trying to modularise our codebase by maintaining a private mono repo, e.g. `@datavis`. Our Meteor projects install packages in the mono repo, e.g. `@datavis/some-package`, by referencing the packages in `package.json` like so:

```
...
"dependencies": {
    "@datavis/some-package": "file:../datavis/packages/some-package",
...
```

Everything works fine, except that, frustratingly, the only way to run every code change in our mono repo is to terminate Meteor and run Meteor from scratch again. Rebundling does not seem to work although in certain cases, client will be auto-refreshed, but the bundle does not seem to change, i.e. the effects of code changes are not propagated to the client.

Anyone has any suggestions on how Meteor's watch folders for rebuilds can be customised or is there any workarounds for the situation? It's getting really tiring to have to ctrl+c Meteor and run them again and again to see small changes, e.g. adjusting small React props.

**Comment by benjamn** [comment] 2017-10-20 21:31
Generally we don't watch for changes inside `node_modules` except when the change affects the contents of the top-level `node_modules` directory (like installing a new package), or when the change occurs inside an `npm link`-ed package. Is your `node_modules/@datavis/some-package` directory a symlink or just a copy of the original folder?

**Comment by ahmadsholehin** [comment] 2017-10-21 18:40
Looking at how npm works, dependencies involving local paths are symlinked inside `node_modules`. Thus `node_modules/@datavis/some-package` is a symlink to the folder where the file changes are being made.

From your explanation @benjamn, would removing `node_modules/@datavis/some-package` and adding it back in again quickly be a possible workaround that triggers it to rebuild? I tried doing so but meteor crashed, thus needing me to rerun everything back again. :(

If only there's a fast way to trigger the rebuild.

**Comment by hwillson** [comment] 2017-12-21 11:39
> would removing node_modules/@datavis/some-package and adding it back in again quickly be a possible workaround that triggers it to rebuild? I tried doing so but meteor crashed

@ahmadsholehin As a workaround, instead of removing `node_modules`, try adding/removing a package you aren't using. That should still be enough to mark the `node_modules` directory as dirty, kick off the rebuild, and pick up any other `node_modules` based changes you've made. E.g.:

**rebuild.sh**
```sh
#!/bin/bash                                                                                                                                                               
meteor npm install is-number                                                         
meteor npm remove is-number
```

I'll close this issue for now though since there isn't a bug here. The `node_modules` watchers are currently working as designed (see https://github.com/meteor/meteor/commit/48a2ccbde7782e6b985a7b37b2064ce3c0963a2b). If you think any of this should be changed, please consider opening a new feature request over in http://github.com/meteor/meteor-feature-requests. Thanks!

**Closed by hwillson** 2017-12-21 11:39 UTC
Labels: Project:Tool

**Comment by ahmadsholehin** [comment] 2017-12-21 11:42
That sounds like a good idea. I'll try it soon. Thanks @hwillson.
