### ISSUE TITLE
HTTP.call(): "params" vs "data"

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#8690] opened 2017-05-12 12:11 UTC
I use Meteor v1.4.4.2 on Windows.

I'm logging this for the record, as I'm unable to investigate more and provide a repo right now.

**Case 1: using "params"**
```javascript
HTTP.call('POST', 'http://www.myDiscourse.org/categories.json', { params: { 
  name: 'myCategory',
  color: '000000', 
  text_color: 'FFFFFF' 
} })
```
On server: works as expected.
On client: server says it doesn't receive the `params`.

**Case 2: using "data"**
```javascript
HTTP.call('POST', 'http://www.myDiscourse.org/categories.json', { data: { 
  name: 'myCategory',
  color: '000000', 
  text_color: 'FFFFFF' 
} })
```
On server: server doesn't understand the request.
On client: works as one would expect with `params`.

**Comment by steph643** [comment] 2017-05-12 12:12
See also https://github.com/meteor/meteor/issues/719.

**Comment by hwillson** [comment] 2017-05-12 13:32
Hi @steph643 - can you explain what you mean by 

> On client: server says it doesn't receive the params.

a bit more? Are you saying that when you're using `HTTP.call` from the client side, that your receiving endpoint isn't able to get the sent `params`?

And for 

> On server: server doesn't understand the request.

do you mean when using `HTTP.call` with `data` from the server side, the receiving endpoint doesn't understand the request?

A reproduction for this will help immensely, as `HTTP.call` is being used extensively from both the client and server, and we haven't received any other (recent) reports of this being an issue. If you can add one when you have a chance, that would be great! Marking as `can't-reproduce` for now. Thanks!

**Comment by steph643** [comment] 2017-05-12 15:26
> Are you saying that when you're using HTTP.call from the client side, that your receiving endpoint isn't able to get the sent params?

That's correct.

> Do you mean when using HTTP.call with data from the server side, the receiving endpoint doesn't understand the request?

I think the receiving endpoint isn't able to get the sent params. However the receiving endpoint error message is less clear than for case 1, so I'm not so positive.

Will try to provide a repo.

Those stackoverflow posts might be related:
https://stackoverflow.com/questions/26998140/gmail-rest-api-mark-message-as-read/30201963#30201963
https://stackoverflow.com/questions/14279800/looks-like-meteor-http-post-is-not-working-properly
https://stackoverflow.com/questions/11205270/meteor-http-call-method
https://stackoverflow.com/questions/17550807/meteor-http-call-does-not-work-correctly-on-server

**Comment by hwillson** [comment] 2017-09-12 17:50
As mentioned in https://github.com/meteor/meteor/issues/8690#issuecomment-301077274, there isn't a lot we can do here without a reproduction demonstrating this issue. We haven't seen any other recent issues mentioning this `HTTP.call` problem. Since there hasn't been any activity here in a while, I'll close this for now. Thanks!

**Closed by hwillson** 2017-09-12 17:50 UTC
Labels: can't-reproduce
