### ISSUE TITLE
Minimongo desc sort bug in second level object + array

### ISSUE THREAD

**Issue by cesarve77** [meteor/meteor#8279] opened 2017-01-24 00:44 UTC
# Minimongo fail sorting:

`{sort: "level1.level2.0.name": 1}`

# but this works: 

`{sort: "level1.level2.0.name": -1}`

# Repo for reproduce bug:
https://github.com/cesarve77/minimongo-sort-bug

## Related issue:
https://github.com/meteor/meteor/issues/2439

## Meteor version 
1.4.2.3

**Comment by ramezrafla** [comment] 2017-01-24 01:32
I don't think minimongo was designed to sort that deep. Awaiting to hear from MDG.

**Comment by cesarve77** [comment] 2017-01-24 05:24
but works for {sort: "level1.level2.0.name": -1}, and in that case is good to put in documentation.

thanks

**Comment by ramezrafla** [comment] 2017-01-24 21:23
In your sort - shouldn't the sort-by field be level1.level2.name ?

**Comment by cesarve77** [comment] 2017-01-24 21:30
Yes this works. But you have to be able to order by
Level1.level2.4.name

As in Mongo

**Comment by ramezrafla** [comment] 2017-01-26 05:27
Sorry for delay, in your repo your schema is:
```
for this schema:

{
    level1: {
        level2: [
            {name: 'bbbb'},
            {name: 'yyyy'},
        ]
    }
}
```

Which means you are sorting `level2` by sort key `name` (the array is `level1.level2` NOT `level1.level2.0`)

If you sorted `level1.level2.0.name` you are only sorting one element, the first one (`bbbb`) in the case above.

**Comment by ramezrafla** [comment] 2017-02-02 04:17
@cesarve77 is everything ok now?

**Comment by ramezrafla** [comment] 2017-02-06 20:49
Can we close this?

**Comment by hwillson** [comment] 2017-03-02 16:28
Since we haven't heard back in a while (and the last few posts point towards this issue being resolved), I'll close this off. Thanks for reporting this originally!

**Closed by hwillson** 2017-03-02 16:28 UTC
