### ISSUE TITLE
`meteor update --all-packages` is not documented in help.txt

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#8154] opened 2016-12-14 01:27 UTC
The flag `meteor update --all-packages` added in #7653 is not mentioned in `meteor help update`.

**Comment by deadjdona** [comment] 2017-01-06 17:45
And it do not work properly ^_^

$ meteor update --all-packages
This project is already at Meteor 1.4.2.3, the latest release.
Your top-level dependencies are at their latest compatible versions.

Newer versions of the following indirect dependencies are available:
 * aldeed:collection2-core 1.2.0 (2.0.0 is available)
 * aldeed:schema-deny 1.1.0 (2.0.0 is available)
 * aldeed:schema-index 1.1.1 (2.0.0 is available)
 * coffeescript 1.11.1_4 (1.12.0_1 is available)
To update one or more of these packages, pass their names to `meteor update`, or just run `meteor update --all-packages`.

**Comment by abernix** [comment] 2017-01-16 16:31
@deadjdona `meteor update --all-packages` actually does work in the sense that it updates all possible packages to the latest versions possible based on the other package constraints in your project, but the message it provides is a bit confusing, I agree.  The problem you're encountering is that there are some _impossible_ constraints that are preventing you from upgrading to those higher versions of those four packages (e.g. `aldeed:*`, `coffeescript`).  You can get more information about exactly _which_ package is preventing the upgrade by running (for example):

    meteor add aldeed:collection2-core@2.0.0

(Just replace the package name and version with the package listed in the "Newer versions" message)

I'm going to try to improve this message soon to make it more clear what the problem is.

**Comment by hwillson** [comment] 2017-02-27 15:40
Hi @abernix - I just submitted PR #8431 to help address the issue of the missing help text. Since that should hopefully help address the original issue here, what do you think we should do with the issue of the unhelpful version solver messages (https://github.com/meteor/meteor/issues/8154#issuecomment-270960088)? Issue #5270 exists to track this already, so maybe that's enough? Thanks!

**Comment by abernix** [comment] 2017-03-03 14:44
#5270 is sufficient to track the rest of this problem (which is actually the output from the command versus the help itself), but your PR will fix this.   Thanks for opening #8431!

**Comment by abernix** [comment] 2017-03-09 19:54
Thanks for reporting, @glasser.  This should be released with Meteor 1.4.3.2.

    meteor update --release 1.4.3.2-beta.0

**Closed by abernix** 2017-03-09 19:54 UTC
