### ISSUE TITLE
No mobile platforms + `--mobile-settings` = build for android

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#7148] opened 2016-06-01 13:43 UTC
On my Mac, a project with no mobile platforms, that speciies `meteor build --mobile-settings` appears to try and build for android. This was counter-intuitive when trying to build for ios, because ios wasn't in the platform list. 

Also, how do I build just ios or android if both platforms are added?

**Comment by abernix** [comment] 2016-06-01 13:53
Thanks, Michael.  Will check this bug out soon.

As far as building for one or the other, right now it's not possible to build for only iOS or Android (without the other) without removing the particular platform.  I think the original thinking may have been that the developer would generally be publishing them together.  I can understand how this wouldn't always be the case though.  Sounds like your #7144 will build that into a feature request.

**Comment by MichaelJCole** [comment] 2016-06-01 14:14
Thanks for looking into this :-)

**Comment by abernix** [comment] 2016-07-11 11:52
Sorry for the terribly long delay in getting back to you!

Unfortunately, I haven't been able to reproduce this:

* `meteor create meteor-issue-7148`
* `meteor npm install`
* `meteor` Just to fire it up once, then Ctrl-C.
* `meteor build --directory ../meteor-issue-7148-build --mobile-settings "{}"`
* Just the single non-Android build is present (No `android` or `ios` folder):
```sh
$ ls -1 ../meteor-issue-7148-build
bundle
```

Am I missing something?

**Comment by MichaelJCole** [comment] 2016-07-12 21:16
Hi @abernix, thanks for checking on this.  Here's steps to reproduce (sorry I don't have a Mac to test on):

```
# On a mac w/o the android toolchain, build for ios
meteor create meteor-issue-7148
cd meteor-issue-7148
meteor npm install
meteor add-platform ios
meteor add-platform android
meteor  --port 4000
# Build once - ctrl-c to exit
echo "{}" > mobile-settings.json
# Now try and build for mobile
meteor build --directory ../meteor-issue-7148-build --server=https://localhost:4000 --mobile-settings mobile-settings.json
# ERROR missing android toolchain
```
The problem is the codebase needs to be edited (add/remove platforms) before building on Mac if android platform is there.

I think the message "Currently, it is only possible to build iOS apps on an OS X system." handles this for the reverse (no iOS toolchain on Linux/Windows).

**Comment by abernix** [comment] 2016-10-11 13:50
I realize this has taken me months to get back to, and I apologize!  Not completely forgotten though! :)

When I run the steps above on a Mac without Android, I get:

```sh
7148 $ meteor npm install
7148@ /Users/jesse/Dev/Misc/meteor-tests/7148
└─┬ meteor-node-stubs@0.2.3
***snipped***
```
```sh
7148 $ meteor add-platform ios
ios: added platform
```
```sh
7148 $ meteor add-platform android
android: added platform

Your system does not yet seem to fulfill all requirements to build apps for Android.

Please follow the installation instructions in the mobile guide:
http://guide.meteor.com/mobile.html#installing-prerequisites

Status of the individual requirements:
✓ Java JDK
✗ Android SDK: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
  Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
✗ Android target: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable.
✗ Gradle: Could not find gradle wrapper within Android SDK. Could not find Android SDK directory.
  Might need to install Android SDK or set up 'ANDROID_HOME' env variable.
meteor add-platform android
```
```sh
7148 $ meteor  --port 4000
[[[[[ ~/Dev/Misc/meteor-tests/7148 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:4000/
^C
 ✘ 7148 $ echo "{}" > mobile-settings.json
```
```sh
7148 $ meteor build --directory ../7148-build --server=https://localhost:4000 --mobile-settings mobile-settings.json
=> Errors executing Cordova commands:

   While building Cordova app for platform Android:
   Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
   Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
   at /Users/jesse/Dev/Misc/meteor-tests/7148/.meteor/local/cordova-build/platforms/android/cordova/lib/check_reqs.js:223:19
   at _fulfilled (/Users/jesse/Dev/Misc/meteor-tests/7148/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:834:54)
***snipped***
```

If I run `meteor remove-platform android` before the `meteor build`, it works properly with no error.  This sounds like it's working as intended if you're trying to build with `android` as a platform but don't have the Android SDK installed.  The message seems to be indicating exactly that.

I think the FR that you opened (#7144) is the ultimate solution to being able to easily switch between machines and build for exactly what you want without needing to worry about additional `add-platform`/`remove-platform` steps.  I'm closing this in favor of that.

**Closed by abernix** 2016-10-11 13:50 UTC
Labels: bug, Impact:few, Project:Isobuild
