### ISSUE TITLE
"spawn ENOMEM" Crash

### ISSUE THREAD

**Issue by janat08** [meteor/meteor#8553] opened 2017-04-02 14:05 UTC
#1129 I don't have much in public
```
Error: spawn ENOMEM
    at exports._errnoException (util.js:907:11)
    at ChildProcess.spawn (internal/child_process.js:309:11)
    at Object.exports.spawn (child_process.js:367:9)
    at [object Object]._.extend._spawn (/tools/runners/run-app.js:270:31)
    at [object Object]._.extend.start (/tools/runners/run-app.js:87:22)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:758:16)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12
```

. Meteor 1.4.3.2. I got vue and apollo packages. Nothing specific stands out about several times that I crashed.

**Comment by hwillson** [comment] 2017-04-02 14:46
Hi @janat08 - sorry to hear you're having trouble! A few questions/comments:

- What OS are you using?
- Since you're running out of memory, can you tell us more about your environment? Do you have a lot of memory available before running your Meteor app?
- Are you developing in a VM, and if so do you have swap space available? (if using Linux for example, can you post the output of `free -h`)

If this is happening consistently, maybe try to put together a small reproduction that demonstrates this issue, and link to it here (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more info).

**Comment by janat08** [comment] 2017-04-02 21:29
I'm using linux: opensuse. I did ran out of swap memory with another GB
left on ram when I restarted app after crash (or just after crash, can't
tell). I'm not in VM.

I don't remember if there's something specific to blame, but I was playing
with cookies last time.

**Comment by janat08** [comment] 2017-04-02 21:31
I got 4GB and 2GB sticks, so possibly linux follow dual channel thing and
loads my 2GB of swap as if it's RAM, while still offloading idle mem to it,
at which point in eyes of OS I ran out of space or something.

**Comment by hwillson** [comment] 2017-05-01 12:47
Hi @janat08 - is this still happening? If so, can you try updating to Meteor 1.4.4.1 and report back? As you can imagine, troubleshooting an issue like this without more details is quite difficult. Any additional information you're able to provide will greatly help. For now though, since there hasn't been any additional activity on this issue in a month, I'll close it off. Happy to re-open if you can provide any extra details that help demonstrate that this is an issue with Meteor. Thanks!

**Closed by hwillson** 2017-05-01 12:47 UTC
