### ISSUE TITLE
Oplog tailing stalls (usually during MongoDB failover) (maybe primarily with Compose Classic)

### ISSUE THREAD

**Issue by veered** [meteor/meteor#8598] opened 2017-04-13 21:18 UTC
Using the `replicaSet=...` option in `MONGO_URL` or `MONGO_OPLOG_URL` causes auto-reconnects to be disabled on that connection. Since including this parameter is the officially recommended approach, most people using Meteor in prod don't have auto-reconnecting DB connections. I am using Meteor 1.4.3.2, but I think this bug has pretty much always existed.

The bug is very easy to reproduce. Locally set `MONGO_URL` to a mongo url that includes `replicaSet=...`. Open up the meteor shell and do a find on a collection; the query should successfully complete. Now reset the network connection on your computer. Try the query again; the query should hang and eventually fail. Now try this same series of steps after removing the `replicaSet` parameter from `MONGO_URL`; notice that the query won't fail. The steps for replicating the problem for `MONGO_OPLOG_URL` is exactly the same.

Note: If removing the `replicaSet` parameter crashes your server, then make sure there is only a single host referenced in `MONGO_URL` and that this host is the primary. 

The main thing going on here is that by passing in the `replSet` parameter the Mongo driver uses the `replset` connection type rather than the `server` connection type. As you can see [here](https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/replset.js#L135) `replset` connections ignore the auto-reconnect property, but `server` connection types [do not](https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/server.js#L129).

You can view info about the `MONGO_URL` connection by typing `Meteor.users._driver.mongo.db.serverConfig` into the meteor shell, and info about `MONGO_OPLOG_URL` by typing `Meteor.users._driver.mongo._oplogHandle._oplogTailConnection.db.serverConfig` into the meteor shell.

This may be due to a relatively recent change in the mongo driver that happened on June 14th, 2016. [Here is the commit](https://github.com/mongodb/node-mongodb-native/commit/412b50d53dc8e958d3b726fc7f66fe0447b9da66#diff-3995a38a37cf6b7ad44d4c8e63893046R131). But it is also possible that auto-reconnect was never supported for `replset` connections, and that commit is just refactoring the code to reflect that fact. Hard to tell exactly. In any case, it isn't supported anymore. 

Seems like this problem is related to a bunch of issues people have been having, #5773 being the most popular.

Not really sure the best way to fix this. For now I've just dropped the `replicaSet` parameter and made sure that each connection URL only references the primary host, not the secondary. 

What is the purpose of passing in info about the secondary node (which is the only thing that is forcing us to use the `replicaSet` parameter)? It doesn't really seem to be used for anything except for failover support, and Meteor can't handle failover. I guess if you keep both hosts in the connection URL, Meteor will connect to the new primary upon restart.

The only solutions I can think of are:
  (1) Stop passing in the `replicaSet` parameter
  (2) Patch the mongo driver so that `replset` connections support auto-reconnects.
  (3) Handle reconnects at the Meteor level

Anyways, this is a pretty important bug. We had some serious outages over the past week because Compose reset all db connections a few times while debugging something unrelated on their end.

**Comment by mitar** [comment] 2017-04-13 21:29
I think having a way for having a callback when mongo connection disconnects/connects/reconnects could be helpful here to log how often is Meteor reconnecting, to detect such issues. I do not think there is a way for now for Meter to call custom code when it gets disconnected from Mongo?

**Comment by RobAWilkinson** [comment] 2017-04-19 01:18
Not related to the fix but want this information out there for other searchers:
If db queries through the regular mongo shell are running perfect for you, but you get massively slow db queries in your meteor application this could be the problem. It definitely was for us.

**Comment by Siyfion** [comment] 2017-06-29 08:42
I can't believe how ridiculous this issue is; since updating my application to the latest Meteor version (which I assume includes the new MongoDB driver) it's now crashing my production app with scary regularity. I'm going to be forced to revert to a single instance connection string which, let's face it, sucks.

I know this isn't a meteor issue per-se, but if anyone knows what the hell the MongoDB team are playing at, let me know

**Comment by abernix** [comment] 2017-06-29 11:33
@Siyfion So sorry to hear about your troubles.  Since you're able to reproduce this regularly, you may be our best source of investigating it and fixing it.

Though the version we use is [quite new](https://github.com/mongodb/node-mongodb-native/blob/2.2/HISTORY.md#2224-2017-02-14) (2.2.24), there _is_ actually a newer version of the Node Mongo driver out.  Could you consider forking the [`npm-mongo`](https://github.com/meteor/meteor/tree/master/packages/npm-mongo) package into your local `packages` directory in your project and bumping the `version` in [the `package.js` file](https://github.com/meteor/meteor/blob/master/packages/npm-mongo/package.js#L6) to the most recently published [`mongodb`](https://github.com/mongodb/node-mongodb-native/) version, [`2.2.29`](https://github.com/mongodb/node-mongodb-native/blob/2.2/package.json#L3)?  Then, re-deploy your production app (or preferably reproduce and use a staging environment, if you can!).

**Comment by veered** [comment] 2017-06-29 15:41
@abernix Do the repro instructions I posted in the issue description not work for you? I can reproduce extremely easily in dev mode

**Comment by Siyfion** [comment] 2017-06-29 16:36
@abernix I only managed to reproduce this regularly because Compose.io were having issues with one of the hosts that I was using; whereby it was having network connectivity issues every ~24-36hrs for about 1-2 secs each time. I've since changed to not use a replication set, and also switched host servers on Compose.io. So it's not likely to re-occur now in production, though I believe @veered's instructions should work.

I mean it's pretty trivial; set up a MongoDB server as part of a replication set, give a `MONGO_URL` connection string with more than one host, interrupt the connection, watch as it sits there doing nothing... :/

**Comment by veered** [comment] 2017-06-29 19:33
@Siyfion Sorry to hear about your issues w/ Compose. We had lots of similar issues... We've since switched to Atlas, and things have been working much better (also it's cheaper, has better tooling, and has better support). Also, Compose's support wasn't very helpful it figuring out this issue :(

**Comment by mjmasn** [comment] 2017-06-30 01:33
@Siyfion I think we had the same issue with Compose (MongoDB Classic), was happening every 24 hours when the backups were run. They seemed to think it was incompatibility between the latest drivers and Mongo 2.X (something like the hidden backup member wasn't appearing as hidden to the driver, although that seemed a bit odd to me). Anyway upgrading to Mongo 3.0 did solve the issue in case anyone else is experiencing this.

**Comment by Siyfion** [comment] 2017-06-30 09:49
Interesting comment from the Node.js driver developer: https://twitter.com/siyfion/status/880382404229287936

**Comment by angryrancor** [comment] 2017-07-13 22:05
If I understand correctly, it is impossible to use oplog tailing at the same time as autoReconnects, because of this issue?  Is there still no workaround?

**Comment by veered** [comment] 2017-07-13 23:01
I still haven't found a good workaround :( 

We've transitioned our DB hosting to Atlas, so the issues pop up much less frequently, but it still happens occasionally.

**Comment by angryrancor** [comment] 2017-07-14 05:03
Has anyone tried patching https://github.com/mongodb/node-mongodb-native and setting autoReconnect: true?  If so, did it work, and were there any side effects?

Honestly, it seems like the primary developers justification is bogus.  There could be something I'm missing, from my view that's what it looks like.

**Comment by Siyfion** [comment] 2017-07-14 06:53
@angryrancor Read the comments I posted from the dev.

**Comment by angryrancor** [comment] 2017-07-14 13:55
@Siyfion I read them over about seven times, before posting my comment.  It's still impossible to understand what is going on here, because of all the confusion and no posts of successful workaround.

The devs comments seem to imply that even patching the driver and setting autoReconnect: true would not work;  Which seems contradictory to the code change itself, as written.

**Comment by abernix** [comment] 2017-07-25 12:54
I tried reproducing this problem on an [mLab](https://mlab.com) database deployment which consisted of two nodes and an arbiter (the default setup).  I was not able to successfully reproduce it.

In my attempt to reproduce, I setup a Meteor 1.5.1 app using `npm-mongo@2.2.24` on my local development machine and pointed it to the `MONGO_URL` of the aforementioned mLab deployment, which included a `replicaSet` query parameter setting (as provided in the URL by mLab).

I tried a variety of ways of derailing the connection as suggested by @veered in the body of this issue.  I tried running an initial `find` and resetting my internet connection (both by turning off my wifi and turning it back on, and also by using `lldb` to connect to the process and forcibly close the file-descriptor, confirming it was closed by using `lsof`).  Regardless of whether I ran the second query after the connection been re-enabled, or whether I ran it and _then_ re-enabled the connection, it still completed correctly and without a timeout occurring.  Of course, if I ran the query without ever re-enabling the connection I would eventually receive a `ETIMEDOUT`.  Also, if a query in progress was terminated prematurely, that particular query would fail but the next query worked fine.

I'm not sure if it will be any help, but `npm-mongo@2.2.30` has been released and there were [a number of improvements](https://github.com/mongodb/node-mongodb-native/blob/2.2/HISTORY.md#2230-2017-07-07) since `2.2.24`, but I wasn't able to prove any improvements to this issue.  As I've requested previously, please do try it and report back if it helps at all!

Perhaps there are some other factors in play here?

**Comment by Siyfion** [comment] 2017-07-25 13:09
@abernix Sorry, but I think this issue is more complex than originally thought. I was getting this issue all the time using Compose.io hosted DBs, the moment I switched to using Mongo Atlas hosting, the issue has gone away. I think it must be something to do with their setup, and how it handles network instability / host failover.

**Comment by ottersoftware** [comment] 2017-07-25 13:18
That just increases my desire to move from Compose. That's a job for this weekend I think.

**Comment by veered** [comment] 2017-07-25 18:41
@abernix I tried repro'ing now that our DB's are on Atlas and it was able to reconnect properly. So it looks like it might be an issue w/ Compose in particular. 

Interestingly, we still host Redis on Compose and last night we were getting a ton of connection reset errors on our Redis DB. So perhaps this is an issue Compose has in general. Sigh. I don't understand what's up w/ them lately.

**Comment by mjmasn** [comment] 2017-07-26 02:59
Disclaimer: I probably don't fully understand this and some of my knowledge may be outdated. Any Mongo experts feel free to correct.

I haven't used the 'new' Compose instances but it seems like the setup is a lot more complex than Atlas. With Atlas, they are literally spinning up 3 EC2 instances for you and installing a replica set, then giving you a replicaset url (as you would have received with a 'classic' Compose setup). This is like what you would do if you set up your own replicaset on some VPS servers. Compose I think are spinning up containers on shared EC2 instances (may be wrong here?), and then using a HAProxy setup to handle primary/secondary routing (rather than using a replicaset url). And a separate HAProxy setup to allow you to access the oplog if you pay them more money. Compose have said [on their blog](https://compose.com/articles/connecting-to-the-new-mongodb-at-compose/) that there are issues with this different style of connection string and the Node.js MongoDB driver. With all that considered it would make sense that Atlas has less edge case issues with Meteor. I'm guessing the Compose way has other benefits over the standard setup (they presumably(?) know what they're doing!) but for Meteor/Node.js it seems to be a hinderance. 

We're looking to switch to Atlas from Compose's 'classic' MongoDB soon.

**Comment by robinleboe-sw** [comment] 2017-09-21 19:30
We are having connection issues with a Galaxy hosted Meteor app using Atlas. There were no issues until August 25th when both our Staging and Production deployments failed due to failed reconnection with the DB. 

Happened again yesterday on our Staging deployment. Trying to figure out what changed/ what's happening. Just found this thread.

Meteor 1.5, Node 4.8.3, npm-mongo@2.2.24

No errors in the Galaxy logs. Atlas alerts show lots of activity e.g. "Replica set elected a new primary" and these seem to be the likely candidates for triggers on the Mongo side given the timing. 

Whatever the trigger, our Meteor app doesn't get reconnected to Mongo and is rendered useless until the container is restarted. No alerts or errors from Galaxy. Very bad for business.

Just starting to investigate and thought I'd let people reading this thread know this issue, if related, is not necessarily a compose.io related problem.

**Comment by ottersoftware** [comment] 2017-09-22 08:24
It might be worth opening a support ticket with Atlas/MongoDB. When I migrated they got in touch and were very interested to hear about the Meteor connection issues.

**Comment by glasser** [comment] 2017-10-03 19:44
Good news — I have a reproduction of the issue that's pure Node (just the Node Mongo driver). I've reproduced it against MongoDB 3.0.11 with Compose Classic.  Have not tried other providers yet. The reproduction has some passwords to my test db in it so not ready to share yet, but fixing this is my top priority.

I'm reasonably sure that the root cause is a race condition in the Node Mongo driver (perhaps exacerbated by characteristics of Compose's offering), and if we can't directly fix it, it's likely we can work around it by detecting the issue and re-starting the oplog tailer.

If I don't fix it in the next day or two I'll clean up my reproduction and post it here.

**Comment by glasser** [comment] 2017-10-03 22:36
I believe the issue is https://jira.mongodb.org/browse/NODE-1039 and the intended fix https://github.com/mongodb-js/mongodb-core/commit/0763e65b659a4a63fa58d603be1e0c9c5f044c4e does not work.

There's an evident bug in that fix (the error passed to `workItem.cb`, `err`, is not actually a defined variable, and also it should be the first argument), but fixing that issue doesn't seem to be adequate.

**Comment by glasser** [comment] 2017-10-05 01:34
I've created a consistent localhost reproduction for this issue (turns out this is not Compose-specific), filed an issue in the Mongo Node driver JIRA, and sent in a PR. We'll see what the driver maintainer has to say about it.

Reproduction: https://github.com/glasser/mongo-driver-race-condition
Issue: https://jira.mongodb.org/browse/NODE-1153
PR: https://github.com/mongodb-js/mongodb-core/pull/224

**Comment by glasser** [comment] 2017-10-09 23:12
Unfortunately it's unclear when the maintainers of the Mongo driver will be able to look at this, since they are very focused on MongoDB 3.6.  I've filed https://github.com/meteor/meteor/pull/9200 to switch Meteor to a fork which hopefully fixes this issue.

https://github.com/meteor/meteor/pull/9199 is a workaround which might be worth doing on top of #9200 just as defense-in-depth against similar bugs in the future. However I'm finding that a test is sometimes failing with it (I assume that's not normally the case?) which means it might have some negative performance impacts on Meteor, so I'm a little wary.

**Comment by steve-ross** [comment] 2017-10-10 12:58
So will this make it into the next point release? and kudos for the fix, will definitely make our customers happy.

**Comment by glasser** [comment] 2017-10-10 19:23
This is actually released as the Meteor package `npm-mongo@2.2.31` right now, which you could upgrade to now. We released this because we weren't sure when the Mongo Node driver maintainers would get a chance to look at our patch; the great news is they're looking today, so you might want to hold off upgrading until they get their review in and perhaps we get it into an unforked 2.2.32 :)

**Comment by glasser** [comment] 2017-10-11 23:29
Great — the Mongo folks merged my change without any major differences (https://github.com/mongodb-js/mongodb-core/pull/224) so that gives me good confidence in `npm-mongo@2.2.31` (from #9200)!  (We should be able to unfork once they do another release.)

That makes me feel pretty good about this issue. I recommend that people run `meteor update npm-mongo` to get their `npm-mongo` up to 2.2.31.  This is now the default for newly created apps as well.

**Closed by glasser** 2017-10-11 23:29 UTC
Labels: bug, confirmed, Impact:most, Project:Mongo Driver, Severity:production

**Comment by abernix** [comment] 2017-10-12 08:03
@glasser Thank you for your extensive research and work on this!

**Comment by ottersoftware** [comment] 2017-10-12 08:23
Thank you for the fix. Your efforts are very much appreciated.

**Comment by Siyfion** [comment] 2017-10-12 08:50
Wow, fantastic work @glasser! Kinda cool to think that an issue we found has lead to a patch in the main MongoDB Node driver. ;)

**Comment by robinleboe-sw** [comment] 2017-10-12 20:37
Really appreciate your efforts @glasser!
