### ISSUE TITLE
Failure when included NPM has malformed JSON files inside

### ISSUE THREAD

**Issue by DrDanRyan** [meteor/meteor#7089] opened 2016-05-20 15:41 UTC
I have a project that uses a npm library named `sharp` that has some funny business in its index.js file that attempts some `require` statements that are really not necessary.  When I do `meteor` or `meteor build` on my OS X dev machine I get this warning: 
```
Unable to resolve some modules:

  "./build/Release/sharp" in /Users/mothership/Code/marymahoney/dbms/node_modules/sharp/index.js (os.osx.x86_64)
  "./lib/versions.json" in /Users/mothership/Code/marymahoney/dbms/node_modules/sharp/index.js (os.osx.x86_64)
```
but the app starts anyway and works fine. However, when I go to build on my production server (Ubuntu Server 15.10), the build fails at the same point as when the warning messages appear on my dev machine and I get the following error:
```
/home/dan/.meteor/packages/coffeescript/.1.0.17.1qmihgc++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
SyntaxError: Unexpected string
    at Object.parse (native)
    at Object.json [as .json] (/tools/isobuild/import-scanner.js:69:27)
    at ImportScanner._readModule (/tools/isobuild/import-scanner.js:556:23)
    at /tools/isobuild/import-scanner.js:505:22
    at _.each._.forEach (/home/dan/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:457:5)
    at /tools/isobuild/import-scanner.js:520:12
    at _.each._.forEach (/home/dan/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:457:5)
    at /tools/isobuild/import-scanner.js:489:18
    at _.each._.forEach (/home/dan/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:457:5)
    at /tools/isobuild/import-scanner.js:319:14
    at Array.forEach (native)
    at ImportScanner.scanImports (/tools/isobuild/import-scanner.js:317:22)
    at /tools/isobuild/compiler-plugin.js:837:17
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:805:19)
    at ServerTarget._emitResources (/tools/isobuild/bundler.js:913:8)
    at /tools/isobuild/bundler.js:684:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ServerTarget.make (/tools/isobuild/bundler.js:675:18)
    at /tools/isobuild/bundler.js:2502:14
    at /tools/isobuild/bundler.js:2570:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
    at buildCommand (/tools/cli/commands.js:909:30)
    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:789:12)
    at /tools/cli/main.js:1402:23
```

I think there is something with generating the error message that is causing the throw on the linux machine.  I was able to deploy anyway by doing `meteor build --architecture=os.linux.x86_64` and then transferring the built project to the server, so it is not a major issue, but took some time to figure out what was going on.

**Comment by abernix** [comment] 2016-05-21 11:52
That error is caused by invalid JSON being passed into `JSON.parse` [here in the Meteor code](https://github.com/meteor/meteor/blob/devel/tools/isobuild/import-scanner.js#L67-L71) while Meteor is analyzing the package.  This means that the npm package has an invalid JSON file somewhere in it's source.

After `npm install`, if you look in `<your_project>/node_modules/sharp/lib/versions.json`, this is what I see:
```json
{
  "exif": "0.6.21",
  "ffi": "3.2.1",
  "glib": "2.47.6",
  "gsf": "1.14.34",
  "jpeg": "1.4.2",
  "lcms": "2.7",
  "gm": "1.3.23",
  "orc": "0.4.25",
  "png": "1.6.21",
  "tiff": "4.0.6",
  "vips": "8.2.3"
  "webp": "0.5.0",
  "xml": "2.9.3",
  "zlib": "1.2.8",
}
```
There are actually **two** syntax errors in this "JSON" – there is a missing comma on the fourth-to-last-line and a trailing-comma which is not permitted in JSON.

It appears that the file is actually just mangled in the source tarball for vips 8.2.3 from https://dl.bintray.com/lovell/sharp/, but appears fixed in 8.3.1.  Looks like the author is [currently updating](https://github.com/lovell/sharp/commits/master) to vips 8.3.1, but hasn't published it yet on npm.  Once that happens, this problem should go away (and also one of the two errors you saw on dev which happens when trying to `require` that broken json file).  You may want to consider poking the package author with an issue about it – or checking for existing issues.

Meteor might be able to provide a better error message on the lines I linked above by catching the error which is produced by `JSON.parse`.  I will leave this open for review.

**Comment by abernix** [comment] 2016-05-21 14:58
Forgot to mention that you can manually fix that JSON file if you want to run it as-is. :wink:

**Comment by DrDanRyan** [comment] 2016-05-22 00:36
Thanks a lot, that was really helpful!

**Comment by laosb** [comment] 2016-06-03 07:30
This is not a meteor bug, and got fixed by the package author, so close.

**Closed by laosb** 2016-06-03 07:30 UTC
Labels: bug, confirmed, Impact:few, known-fix, npm-module-specific, Project:Isobuild, Severity:has-workaround
