### ISSUE TITLE
[1.4.1] Error: bad path

### ISSUE THREAD

**Issue by wilau2** [meteor/meteor#7675] opened 2016-08-19 17:12 UTC
Upgrading from 1.4.0.1 to meteor 1.4.1.
running on osx
I have a local package: sambegin:push
When i start meteor i have a problem that seems to be related with my local packages. 
It creates an other folder in my packages/ names sambegin_push

In my .meteor/local/plugin-cache/sambegin_push/local seems to be empty. 

The error is the following : 

`/Users/williamlauze/.meteor/packages/ecmascript/.0.5.8.157vaws++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: bad path: ../sambegin_push/.npm/plugin/configuration/node_modules
    at rejectBadPath (/tools/isobuild/bundler.js:185:11)
    at NodeModulesDirectory.getPreferredBundlePath (/tools/isobuild/bundler.js:273:5)
    at /tools/isobuild/bundler.js:1740:39
    at Function._.each._.forEach (/Users/williamlauze/.meteor/packages/meteor-tool/.1.4.1.w7wcti++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at JsImage.write (/tools/isobuild/bundler.js:1734:7)
    at /tools/isobuild/isopack.js:1474:36
    at Function._.each._.forEach (/Users/williamlauze/.meteor/packages/meteor-tool/.1.4.1.w7wcti++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /tools/isobuild/isopack.js:1468:11
    at Function._.each._.forEach (/Users/williamlauze/.meteor/packages/meteor-tool/.1.4.1.w7wcti++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /tools/isobuild/isopack.js:1467:9
    at Isopack.saveToPath (/tools/isobuild/isopack.js:1191:9)
    at /tools/isobuild/isopack-cache.js:378:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:315:18)
    at /tools/isobuild/isopack-cache.js:249:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:248:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/Users/williamlauze/.meteor/packages/meteor-tool/.1.4.1.w7wcti++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:781:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:780:18)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/runners/run-app.js:548:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:547:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:625:35)
    at AppRunner._fiber (/tools/runners/run-app.js:884:28)
    at /tools/runners/run-app.js:402:12
`

**Comment by Zodiase** [comment] 2016-08-19 20:55
I got the same situation.

My error log:
```shell
/Users/xh/.meteor/packages/promise/.0.8.4.1n4cex5++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: bad path: ../zodiase_mdl/.npm/plugin/build/node_modules
    at rejectBadPath (/tools/isobuild/bundler.js:185:11)
    at NodeModulesDirectory.getPreferredBundlePath (/tools/isobuild/bundler.js:273:5)
    at /tools/isobuild/bundler.js:1740:39
    at Function._.each._.forEach (/Users/xh/.meteor/packages/meteor-tool/.1.4.1.uuw53n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at JsImage.write (/tools/isobuild/bundler.js:1734:7)
    at /tools/isobuild/isopack.js:1474:36
    at Function._.each._.forEach (/Users/xh/.meteor/packages/meteor-tool/.1.4.1.uuw53n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /tools/isobuild/isopack.js:1468:11
    at Function._.each._.forEach (/Users/xh/.meteor/packages/meteor-tool/.1.4.1.uuw53n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /tools/isobuild/isopack.js:1467:9
    at Isopack.saveToPath (/tools/isobuild/isopack.js:1191:9)
    at /tools/isobuild/isopack-cache.js:378:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:315:18)
    at /tools/isobuild/isopack-cache.js:249:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:248:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/Users/xh/.meteor/packages/meteor-tool/.1.4.1.uuw53n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:781:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:780:18)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/cli/commands-packages.js:1509:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:273:29)
    at maybeUpdateRelease (/tools/cli/commands-packages.js:1508:8)
    at Command.func (/tools/cli/commands-packages.js:1582:29)
    at /tools/cli/main.js:1410:23
```

**Comment by laosb** [comment] 2016-08-20 06:57
Could you provide a *full reproduction* as was explained in Contributing.md? It's hard for us to reproduce your issue without a reproduction.

* For your reference:*

> A Meteor app has many moving parts, and it's often difficult to
> reproduce a bug based on just a few lines of code.  So your report
> should include a reproduction recipe.  By making it as easy as possible
> for others to reproduce your bug, you make it easier for your bug to be
> fixed. **It's likely that without a reproduction, contributors won't look into fixing your issue and it will end up being closed.**
> 
> **A single code snippet is _not_ a reproduction recipe and neither is an entire application.**
> 
> A reproduction recipe works like this:
> 
>  * Create a new Meteor app that displays the bug with as little code as
>    possible. Try to delete any code that is unrelated to the precise bug
>    you're reporting, including extraneous Atmosphere packages.  Ideally, try to use
>    as few source files as possible so that it's easy to see the whole reproduction
>    on one screen, rather than making a large number of small files, even if that's
>    not how you'd choose to structure an app.
> 
>  * Create a new GitHub repository with a name like
>    `meteor-reactivity-bug` (or if you're adding a new reproduction
>    recipe to an existing issue, `meteor-issue-321`) and push your code
>    to it. (Make sure to include the `.meteor/packages` and `.meteor/release` files!)
> 
>  * Reproduce the bug from scratch, starting with a `git clone`
>    command. Copy and paste the entire command-line input and output,
>    starting with the `git clone` command, into the issue description of
>    a new GitHub issue. Also describe any web browser interaction you
>    need to do.
> 
>  * If you reproduced the issue using a checkout of Meteor instead of using
>    a released version that was pinned with a `.meteor/release` file,
>    specify what commit in the Meteor repository was checked out.
> 
>  * Mention what operating system you're using and what browser (if any).
>

**Comment by mitar** [comment] 2016-08-20 07:08
I got the same when looking for a workaround for #7677:

```
api: updating npm dependencies -- mime-types...                                    
compileScssBatch: updating npm dependencies -- node-sass...
/home/ubuntu/.meteor/packages/promise/.0.8.4.3sv43l++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: bad path: ../fourseven_scss/.npm/plugin/compileScssBatch/node_modules
```

I will work on a reproduction.

**Comment by mitar** [comment] 2016-08-20 07:11
So I have a project into which I did:

```
git submodule add https://github.com/fourseven/meteor-scss.git packages/fourseven:scss
```

Trying to run `meteor list` now throws the error above. The interesting fact is that after that I can see both `packages/fourseven_scss` and `packages/fourseven:scss` directories.

It happens for me on both Linux and Mac OS X.

**Comment by mitar** [comment] 2016-08-20 07:29
Reproduction: https://github.com/mitar/meteor-issue7675

Just try to run `meteor` or `meteor list`.

**Comment by jwentwistle** [comment] 2016-08-21 00:24
I'm having an update issue: 

'''
~/.meteor/packages/meteor-tool/.1.3.5_1.tpttix++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: ENOSPC, write
'''

**Comment by Raincal** [comment] 2016-08-21 16:35
~/.meteor/packages/meteor-tool/.1.4.1.w7wcti++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/4l/110gqr8j7852rm73tmq58rk00000gn/T/mt-189qza6/os.json'
    at Error (native)

**Comment by MLublin** [comment] 2016-08-23 02:45
I had a similar issue caused by having a colon in the package folder name. Fixed it by changing the colon to a dash.

**Comment by allanesquina** [comment] 2016-08-23 05:35
I have the Meteor 1.4.1 installed, when I try to run a project in an older version, the Meteor try to download the meteor-tool@1.3.0 and then I get the following error:

```bash
/home/loloud/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-1ds3kvc/os.json'
    at Error (native)
```

Is it related with packages? If I run the command `meteor update` I get the same error. 

Thanks!

**Comment by matthewstewart** [comment] 2016-08-25 14:40
Same Issue. 

C:\Users\mstewart\AppData\Local\.meteor\packages\meteor-tool\1.4.1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\mstewart\AppData\Local\Temp\mt-4xgj1j\os.json'
    at Error (native)

Windows 10 64-bit, Meteor 1.4.1

**Comment by patrickml** [comment] 2016-08-25 20:45
I am getting this error on 1.3.5.1

**Comment by patrickml** [comment] 2016-08-25 21:29
Restarting my computer fixed the issue fyi.

**Comment by allanesquina** [comment] 2016-08-26 03:43
Seems to be a connection issue, I went to another city, getting a better internet and it works. For some reason, here in my city, the connection is closing without explanation, may be a CDN problem? Maybe time limit issue?

**Comment by aposidelov** [comment] 2016-09-12 09:35
I reproduced this type of issues. It because of problem with installing package dependencies. For example if I install kadira:flow-router it will be without errors because it doesn't have any dependencies. But I try to install matb33:bootstrap-glyphicons that depends on less package I got this "promise" errors after meteor failed to install less package. And I install less package before and after matb33:bootstrap-glyphicons - it installs OK. 
I found this problem after meteor updating to 1.4.1 version. I had a project with around 15 packages and got this errors. So I started to play with raw meteor project by adding packages.
So the question is why meteor fails to install package dependencies automatically...

**Comment by tanis2000** [comment] 2016-09-13 10:06
I'm experiencing the same issue with 1.4.1.1 with the nemo64:translator package

```
/home/meteor/.meteor/packages/meteor-tool/.1.4.1_1.vd12vq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: bad path: ../nemo64_translator/.npm/plugin/language-compiler/node_modules
    at rejectBadPath (/tools/isobuild/bundler.js:185:11)
    at NodeModulesDirectory.getPreferredBundlePath (/tools/isobuild/bundler.js:273:5)
    at /tools/isobuild/bundler.js:1740:39
    at Function._.each._.forEach (/home/meteor/.meteor/packages/meteor-tool/.1.4.1_1.vd12vq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at JsImage.write (/tools/isobuild/bundler.js:1734:7)
    at /tools/isobuild/isopack.js:1474:36
    at Function._.each._.forEach (/home/meteor/.meteor/packages/meteor-tool/.1.4.1_1.vd12vq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /tools/isobuild/isopack.js:1468:11
    at Function._.each._.forEach (/home/meteor/.meteor/packages/meteor-tool/.1.4.1_1.vd12vq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /tools/isobuild/isopack.js:1467:9
    at Isopack.saveToPath (/tools/isobuild/isopack.js:1191:9)
    at /tools/isobuild/isopack-cache.js:378:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:315:18)
    at /tools/isobuild/isopack-cache.js:249:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:248:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/meteor/.meteor/packages/meteor-tool/.1.4.1_1.vd12vq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:781:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:780:18)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/cli/commands.js:845:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:273:29)
    at buildCommand (/tools/cli/commands.js:844:8)
    at Command.func (/tools/cli/commands.js:798:12)
    at /tools/cli/main.js:1410:23
```

**Comment by aposidelov** [comment] 2016-09-14 10:02
Also I found during package installation some packages throw "/meteor-tool/.1.4.1_1" error and some packages install OK. Also as I wrote above If some package has dependencies it can throw an error that dependencies couldn't be installed. In this case you need to install dependecies separately before installing package itself.
Here's steps how to overcome "/meteor-tool/.1.4.1_1" error:
1) In app root folder create a "packages" folder.
2) Go to github page of a package you want install, download zipped archive or make a git clone to "packages" folder. If you download zip file you need to rename a package folder by removing "meteor-" and "-master" for example meteor-i18n-master folder should be renamed to i18n
3) Run meteor
4) if you still see an "/meteor-tool/.1.4.1_1" error it can be becasue some package dependencies, so make 1) 2) 3) for that dependency package as well.

**Comment by abernix** [comment] 2016-09-30 12:08
@Raincal @allanesquina @matthewstewart None of you are showing the same error as originally reported.  Please see #7806 (which seems to have a common theme), and +1 and provide the requested information in that issue if it sounds like the same problem.

**Comment by hwillson** [comment] 2017-02-09 13:46
Hi all - just reviewing this as part of the on-going old issue cleanup process. I've taken a look at the only reproduction provided in this issue thread (https://github.com/meteor/meteor/issues/7675#issuecomment-241184988); after updating to the most recent version of Meteor, the reproduction runs properly without any errors. Given this, and the fact that most of the other issues mentioned in this issue thread are in-fact different errors (and have been handled in #7806), I'll close this off. Thanks for reporting this originally!

**Comment by mitar** [comment] 2018-05-04 05:41
I have just been hit again with this. On Meteor 1.6.1.1. I put [postcss](https://github.com/juliancwirko/meteor-postcss) package as a git clone in `packages/juliancwirko:postcss`. After running `meteor`, `juliancwirko_postcss` gets created in that directory and after that an error message appears:

```
Error: bad path: ../juliancwirko_postcss/.npm/plugin/minifier-postcss/node_modules
```

I have no idea why is this reappearing.

**Comment by mitar** [comment] 2018-05-04 08:59
Also, interestingly, trying to run the reproduction I made above, with today version of Meteor (1.6.1.1) and just cloning (without submodules, so just regular clone of https://github.com/mitar/meteor-issue7675) and running `meteor` does throw a different exception, one mention by others in this thread:

```
Error: ENOENT: no such file or directory, open '/tmp/mt-hyee2/os.json'
    at Error (native)
```

But reproduction still work (in the sense of failing). I cloned it, recursively, I ran `meteor update` and it fails with:

```
Error: bad path: ../fourseven_scss/.npm/plugin/compileScssBatch/node_modules
```

**Comment by filipenevola** [comment] 2020-03-20 12:35
Please re-open if this is still affecting anyone.

**Closed by filipenevola** 2020-03-20 12:35 UTC
Labels: Impact:some, Project:Isobuild, Severity:blocks-development, bug, confirmed
