### ISSUE TITLE
Meteor 1.3 reload takes more than 2 minutes for just one line of change (Windows 10)

### ISSUE THREAD

**Issue by kevde** [meteor/meteor#7253] opened 2016-06-19 09:02 UTC
Please help me out. I am really fucked up implementing Meteor using Windows 10. Sometimes, I will just edit one line for Meteor Client then it will restart and build from start. It will take about 2 minutes. It slows down my development process. I have been working one tutorial for almost a day figuring out for this problem

**Comment by laosb** [comment] 2016-06-19 12:52
Hi, I'm sorry that you're suffering from slow build times. Can you provide detailed information, like which Meteor version, currently used packages(including npm ones), performance of your computer, etc?

And, is that any app, including the newly-`meteor create`d app have such a slow build time?

**Comment by Themandunord** [comment] 2016-06-19 13:30
Hi @kevde, @laosb,

I thinks it's similar to the issue #4284 
Many people have this problem, and dev team don't fix it at this moment, I suppose.

I have the same problem. With the [mantra architecture](https://github.com/kadirahq/mantra) and the [mantra-cli](https://github.com/mantrajs/mantra-cli) to create a new mantra project, you can see that the building time is very slow...
And when you add your website, it's more longer... 

So if you want to reproduce this, mantra-cli is the good start, and it don't have so much features...

I test a newly `meteor create` and OK th time is pretty good. But with some new files the buidling time increase dramastically !

I'm on Windows 10 for information.

**Comment by kevde** [comment] 2016-06-19 20:15
This is now shitty my run for just one meteor run is in minimum of 5 minutes. This is crap. https://github.com/kevde/mosikero/tree/angular2. 
Mine was Windows 10 on Intel(R) Core(TM) i3-3217U CPU @1.80Ghz 1.80 Ghz 4.00GB (asus vivobook x202e)
I am currently using 1.3.2.4. I tried 1.3.3.1 before but it was too shitty about ecmascript dependency.
(split of undefined). I am so disappointed about it. I was like developing app for three days. And this still comes upfront.

**Comment by Themandunord** [comment] 2016-06-19 20:18
I have the same feeling now... 
Develop an app with meteor was so exciting, but now when I want to test my code I wait so long that I don't want to develop...

**Comment by kachkaev** [comment] 2016-06-20 00:30
Hey @kevde ,

I know your pain – this is a desperate feeling. I'm facing the same issue even on Ubuntu! My build time is a bit smaller (≈20s), but I have to wait for this long even after a tiny tweak in a LESS file. This is just a nightmare, especially because I spent about two working days trying to find a solution but returned to where I was (except for that I'm using [meteor-hmr](https://github.com/gadicc/meteor-hmr) now). 

In addition to #4284 mentioned by @Themandunord slow build times are reported in #7008. It looks like your app builds for so long because you have too many things in `node_modules` (dev-only babel or linters generate 100s of directories there). This is totally fine, the issue is in Meteor's way of working with these folders – not your decision to use local packages!

It is surprising not to see comments from MDG members on slow builds – it feels like they treat this issue as unimportant. If anyone has heard anything, please let know – I don't exclude that I've simply missed smth. Looks like tomorrow I'll have another discouraging fight with meteor while trying to make a rather simple React-based interface. I'd move to webpack a week ago if it's building system did not look too rocket-science and if I did not want to use DDP. The latter seems to be less useful giving the speed at which GraphQL-based tools emerge.

Hope that this is not my last meteor project.

**Comment by laosb** [comment] 2016-06-20 05:00
As slow build times may not be caused due to the same reason, it's hard to say without direct repro repo. Tested `mantra-cli` as you mentioned before, but it runs normally on both macOS and Linux.

**Comment by Themandunord** [comment] 2016-06-20 09:35
@laosb With the `mantra-cli`, a simple modification of the `home.jsx` file took 10 seconds... It's too long.
When you add some modules, the time increase... this stater pack have only one page, thinks about a real website :/

I tested it with Meteor 1.3.2.4 on W7.

@kachkaev With meteor-hmr, the time building is better ? 
And yes, no communication from MDG team was totally weird... Many users are faced to this problem.

**Comment by kachkaev** [comment] 2016-06-20 09:39
@Themandunord meteor-hmr just lets you see the changes in your react components quickly, but that's it – no improvements in build times for css or server-side changes. This is still useful, because anything is better than 20s per build, but the solution is pretty hacky and it also adds a bit of dirt to your client's code. Try it out though!

**Comment by Themandunord** [comment] 2016-06-20 11:45
@kachkaev Ok thanks. I will try if I have time, but I spend many times on building times....
And Meteor 1.3.3.1 still doesn't work on Windows... so I think I will don't have your problem.

**Comment by benjamn** [comment] 2016-06-20 23:38
Please try running `METEOR_PROFILE=100 meteor`, and report your findings here.

The latest release candidate is also worth a try: `meteor update --release 1.3.4-rc.0`

**Comment by kevde** [comment] 2016-06-21 11:07
Thanks @benjamn.  Hoping for a better solution. I'll try this out

**Comment by kachkaev** [comment] 2016-06-21 16:03
Surprisingly I still have different build times after `devDependencies` are removed from `package.json` in 1.3.4-rc.0. Here is what happens when I change a single character in a less file:

![meteor 1 3 4-rc 0 no dev deps vs dev deps](https://cloud.githubusercontent.com/assets/608862/16236873/c53c7632-37d1-11e6-821f-a5a769892bd2.png)

I'll try to produce a MWE now.

**Comment by IvanPortfolio** [comment] 2016-06-21 23:54
My version is 1.3.4-rc.1 and the proble still exists for me

My laptop configuraton is
i5
8gb ram
windows 10
ssd

what I get with profiling `Top leaves:
| files.lstat.............................................24,412 ms (37161)
| files.writeFile..........................................4,531 ms (333)
| other compileUnibuild (the app)..........................3,960 ms (2)
| files.stat...............................................2,801 ms (12548)
| files.readdir............................................2,523 ms (3129)
| other JsImage#write......................................2,484 ms (1)
| files.readFile...........................................1,618 ms (1278)
| files.realpath.............................................870 ms (396)
| files.rm_recursive.........................................614 ms (4)
| other Resolver#_joinAndStat................................528 ms (2583)
| other PackageSourceBatch.computeJsOutputFilesMap...........483 ms (2)
| Babel.compile..............................................470 ms (170)
| files.rename...............................................465 ms (339)
| other plugin ecmascript....................................462 ms (2)
| ImportScanner#_getInstallPath..............................401 ms (1160)
| other Resolver#resolve.....................................267 ms (2595)
| sha1.......................................................258 ms (2030)
| other ClientTarget#write...................................242 ms (1)
| other Target#_runCompilerPlugins...........................232 ms (2)
| other Target#make..........................................178 ms (2)
| Isopack#getUnibuildAtArch..................................169 ms (3855)
| other Builder#write........................................165 ms (328)
| other Resolver#_resolveNodeModule..........................142 ms (400)
| other PackageSourceBatch#_linkJS...........................141 ms (172)`

I can see the the most chalenging part is file operations. But why should i have this problem with ssd?

**Comment by Greblak** [comment] 2016-06-22 07:52
@benjamn I tried with 1.3.4-rc.0
Equal build times when compared to 1.3.3 on Windows on the same project.
Getting build times of ~20 sec for a single file change.
From what I can gather it seems to be related to the npm_modules folder. 
Doing stuff like npm dedupe can in some cases shave a couple of seconds. Having no/very few npm deps also works wonders. Down to a couple of seconds.

I tried doing meteor npm install -g
That worked wonderfully for installing it correctly. However, meteor doesn't bother with using those packages. Checking for packages in the meteor node global folder would go a **long** way in solving this problem at least temporarily.

**Comment by kachkaev** [comment] 2016-06-22 08:31
@Greblak having global npm packages cannot be a solution since you might have several Meteor projects on one machine pointing to different version on the same node module. Perhaps having an option to skip the scan of npm directory completely would work better. If `node_modules` directory does not change between `npm install`, what's the reason for scanning it?

**Comment by Greblak** [comment] 2016-06-22 08:42
@kachkaev Doesn't node handle multiple versions globally? The global repo shouldn't act as more than a machine-local npm repo. It's not "correctly" bundled like app-local node_modules, but meteor should be able to use things installed in global, like normal npm apps are?

Also. Caching node_modules on cue might be a better solution indeed ;) +1 for that suggestion!

**Comment by IvanKaminskyi** [comment] 2016-06-22 12:18
has somebody tried  to build the same project but on linux? is it much faster?

**Comment by kachkaev** [comment] 2016-06-22 12:23
I have (Ubuntu 16.04). 20 seconds to wait even for a small change in a LESS
file given a couple of linters in devDependencies. Terrible dev UX :–(

**Comment by Greblak** [comment] 2016-06-22 12:25
@IvanKaminskyi it seems to be worse on Windows systems, but still affects most platforms. Depends on how the file system is managed.

@kachkaev I highly recommend putting the linters globally if possible. It's directly related to the size of node_modules. I use the WebStorm-plugin for ESlinting that in turn uses the global npm installation.
Shaved 10-15 sec of my build time to remove eslint from package.json :+1:

**Comment by Themandunord** [comment] 2016-06-22 12:33
@Greblak 
![eslint](https://cloud.githubusercontent.com/assets/2819925/16266647/38b6ae84-3886-11e6-99b9-7fc4a57c3bd8.PNG)

Is this plugin ? What is your configuration for this plugin ?

**Comment by Greblak** [comment] 2016-06-22 12:41
@Themandunord 
![capture](https://cloud.githubusercontent.com/assets/996032/16266892/65d01a4e-3887-11e6-9a1a-85b94227e292.PNG)

**Comment by benjamn** [comment] 2016-06-22 14:47
There are, without a doubt, way too many `files.stat` calls happening. On Mac and Linux, that isn't so much of a problem (kind of amazingly, tbh), but `fs.statSync` is much slower on Windows, so we really have to find a way to reduce the number of times we call it.

I have some hunches about what changed recently to cause so many more `stat` calls, and I'll be looking into this for the 1.3.4 release. If the necessary changes are too invasive, it may have to wait for Meteor 1.4.

**Comment by benjamn** [comment] 2016-06-22 20:02
Please confirm whether server restarts are improved after `meteor update --release 1.3.4-rc.2`. As soon as this is fixed, I'll release Meteor 1.3.4.

**Comment by IvanPortfolio** [comment] 2016-06-22 20:19
Installing ubuntu decreased rebuild time from 40-60 s to 10-11s but it is still ridiculous

**Comment by benjamn** [comment] 2016-06-22 20:21
@IvanPortfolio are you talking about initial build time or server restart time (e.g. when you change a file)?

**Comment by kachkaev** [comment] 2016-06-22 20:23
Great! I'm testing this now, will update https://github.com/kachkaev/meteor-build-times-mwe soon.

**Comment by kachkaev** [comment] 2016-06-22 20:37
Great! I updated [the demo repo](https://github.com/kachkaev/meteor-build-times-mwe soon) and the tests show that meteor is not crying as it used to on each small update. Would be nice to hear how the things are from the Windows guys – I only ran them on OSX.

@benjamn although the number of scanned files is much less now, a bit more of them is mentioned when `devDependencies` are on. Is this something under control or can it be some strange artefact? E.g. an increase of meteor's cache or smth similar. Won't the number of files become huge after a couple of hours of continuous development?

**Comment by benjamn** [comment] 2016-06-22 20:41
I haven't done anything to change the behavior of `devDependencies`, yet. Disabling importing `devDependencies` would be another way to avoid touching files in `node_modules`, potentially significant, but I don't want to go down that road until we have to.

**Comment by IvanPortfolio** [comment] 2016-06-22 20:44
@benjamn I mean server restart time after changes

**Comment by IvanPortfolio** [comment] 2016-06-22 20:59
@benjamn It is much better now on the latest revision. It is 9seconds now, but it is still too much

`Top leaves:
| meteorNpm.runNpmCommand..................................2,600 ms (1)
| files.readFile...........................................1,283 ms (1546)
| files.stat.................................................761 ms (6245)
| other Resolver#_joinAndStat................................513 ms (2970)
| other PackageSourceBatch.computeJsOutputFilesMap...........396 ms (2)
| files.realpath.............................................340 ms (204)
| other plugin ecmascript....................................312 ms (2)
| Babel.compile..............................................301 ms (170)
| other JsImage#write........................................279 ms (1)
| other Resolver#resolve.....................................252 ms (2977)
| ImportScanner#_getInstallPath..............................210 ms (1332)
| other Target#_runCompilerPlugins...........................209 ms (2)
| files.lstat................................................204 ms (335)
| sha1.......................................................191 ms (2195)
| other ClientTarget#write...................................169 ms (1)
| Isopack#getUnibuildAtArch..................................149 ms (3855)
| other Resolver#_resolveNodeModule..........................109 ms (410)
| files.symlink..............................................102 ms (134)
| 
| (#4) Total: 9,211 ms (Rebuild App)
`

**Comment by IvanPortfolio** [comment] 2016-06-22 21:13
I advice everybody to use webpak:webpack package. It is not working on windows, but on ubuntu my server rebuild time is 4s now

**Comment by Themandunord** [comment] 2016-06-22 22:44
My refresh take 6s now on my Windows 10 (before >20s), it's much better than before, thanks @benjamn for your work.
It needs some new features to have a better build time, but many thanks at this moment :+1:

**Comment by benjamn** [comment] 2016-06-22 23:01
I agree there's a lot more work to do, but I think we should take it up in Meteor 1.4 now that it's somewhat more tolerable in Meteor 1.3.4.

Closing this now, but definitely not claiming the problem is completely fixed :)

**Closed by benjamn** 2016-06-22 23:01 UTC

**Comment by Hongbo-Miao** [comment] 2016-06-28 03:26
Thanks for great work, before i need over 1 min, now only 8 seconds!!

**Comment by inestyne** [comment] 2016-07-13 01:01
I'm coming in from big Rails projects, making a change largely due to waiting 30-90s on every update. If meteor has slow build issues now i'm going to keep moving and so will everyone else.

Just sayin., the clock is ticking, runways are never as long as you think,

**Comment by ForHonor** [comment] 2016-07-24 14:33
I've been fighting with this and I am desperate. 
My times are 2 minutes.
Please offer suggestions to a newbie.
Windows 10, i7, 8GB, 700GB HD
I am on Meteor 1.3.5.1.
The app is the react/meteor tutorial from tuts.
https://www.youtube.com/watch?v=RFVMHlIMTk4

=> Started proxy.
| (#1) Profiling: ProjectContext prepareProjectForBuild
=> Started MongoDB.
| 
| sqlite query                                                     38 ms (3)
| files.readFile                                                    6 ms (2)
| files.stat                                                        0 ms (1)
| files.unlink                                                     27 ms (1)
| bundler.readJsImage.............................................213 ms (1)
| └─ meteorNpm.rebuildIfNonPortable                               203 ms (2)
| JsImage#load....................................................485 ms (1)
| └─ runJavaScript packages/npm-mongo.js                          396 ms (1)
| files.writeFile                                                   1 ms (1)
| ProjectContext prepareProjectForBuild.........................3,465 ms (1)
| ├─ _resolveConstraints..........................................931 ms (1)
| │  ├─ bundler.readJsImage                                       125 ms (1)
| │  └─ JsImage#load..............................................734 ms (1)
| │     ├─ runJavaScript packages/meteor.js                       116 ms (1)
| │     ├─ runJavaScript packages/logic-solver.js                 245 ms (1)
| │     └─ runJavaScript packages/constraint-solver.js            125 ms (1)
| ├─ _downloadMissingPackages.....................................226 ms (1)
| │  └─ Isopack.readMetadataFromDirectory.........................172 ms (71)
| │     └─ files.readFile                                         150 ms (71)
| └─ _buildLocalPackages........................................2,301 ms (1)
|    └─ IsopackCache Load local isopack.........................2,295 ms (71)
|       └─ Isopack#initFromPath.................................2,224 ms (71)
|          ├─ files.realpath                                      150 ms (71)
|          ├─ files.readFile                                      104 ms (213)
|          ├─ files.open                                          122 ms (562)
|          ├─ bundler.readJsImage...............................1,185 ms (5)
|          │  └─ meteorNpm.rebuildIfNonPortable.................1,086 ms (20)
|          │     └─ files.readFile                                868 ms (253)
|          ├─ meteorNpm.rebuildIfNonPortable......................336 ms (19)
|          │  └─ files.readFile                                   128 ms (275)
|          └─ other Isopack#initFromPath                          143 ms
| 
| Top leaves:
| files.readFile...........................................1,393 ms (1016)
| files.lstat................................................295 ms (1194)
| runJavaScript packages/logic-solver.js.....................245 ms (1)
| files.stat.................................................177 ms (869)
| files.realpath.............................................150 ms (71)
| other Isopack#initFromPath.................................143 ms (71)
| other meteorNpm.rebuildIfNonPortable.......................138 ms (39)
| runJavaScript packages/underscore.js.......................133 ms (2)
| runJavaScript packages/constraint-solver.js................125 ms (1)
| files.open.................................................122 ms (562)
| 
| (#1) Total: 4,236 ms (ProjectContext prepareProjectForBuild)
| 
| (#2) Profiling: Build App
| 
| bundler.readJsImage...........................................2,486 ms (1)
| └─ meteorNpm.rebuildIfNonPortable.............................2,462 ms (8)
|    ├─ files.readdir                                             174 ms (451)
|    ├─ files.lstat                                             1,384 ms (5022)
|    └─ other meteorNpm.rebuildIfNonPortable                      787 ms
| JsImage#load..................................................2,364 ms (1)
| ├─ runJavaScript packages/ecmascript-runtime.js                 344 ms (1)
| ├─ runJavaScript packages/babel-compiler.js                   1,572 ms (1)
| └─ runJavaScript packages/ddp-client.js                         100 ms (1)
| files.stat                                                        0 ms (3)
| files.readFile                                                   10 ms (4)
| Build App....................................................24,066 ms (1)
| └─ files.withCache...........................................24,066 ms (1)
|    ├─ compiler.compile(the app)..............................12,713 ms (1)
|    │  └─ files.withCache.....................................12,712 ms (2)
|    │     └─ compileUnibuild (the app)........................12,711 ms (2)
|    │        ├─ Isopack#ensurePluginsInitialized...............6,051 ms (24)
|    │        │  ├─ JsImage#load................................5,881 ms (5)
|    │        │  │  ├─ runJavaScript packages/underscore.js       245 ms (4)
|    │        │  │  ├─ runJavaScript packages/meteor.js           229 ms (4)
|    │        │  │  ├─ runJavaScript packages/minifier-js.js      438 ms (2)
|    │        │  │  ├─ runJavaScript packages/ecmascript-runtime.js 667 ms (2)
|    │        │  │  ├─ runJavaScript packages/babel-compiler.js 3,528 ms (2)
|    │        │  │  └─ runJavaScript packages/html-tools.js       162 ms (1)
|    │        │  └─ other Isopack#ensurePluginsInitialized        170 ms
|    │        ├─ files.withCache................................5,087 ms (2)
|    │        │  └─ files.realpath                              4,973 ms (15)
|    │        ├─ files.readdir                                    129 ms (192)
|    │        ├─ files.lstat                                    1,105 ms (1542)
|    │        └─ other compileUnibuild (the app)                  294 ms
|    ├─ bundler.bundle..makeClientTarget........................6,762 ms (1)
|    │  └─ Target#make..........................................6,762 ms (1)
|    │     ├─ Target#_runCompilerPlugins........................1,137 ms (1)
|    │     │  ├─ files.realpath                                   127 ms (52)
|    │     │  └─ plugin ecmascript                                938 ms (1)
|    │     └─ Target#_emitResources.............................5,570 ms (1)
|    │        ├─ PackageSourceBatch.computeJsOutputFilesMap.....5,286 ms (1)
|    │        │  ├─ ImportScanner#_getInstallPath                 107 ms (367)
|    │        │  ├─ ImportScanner#_findImportedModuleIdentifiers 4,266 ms (337)
|    │        │  ├─ Resolver#resolve..............................409 ms (935)
|    │        │  │  ├─ Resolver#_resolveRelative..................180 ms (331)
|    │        │  │  │  └─ Resolver#_joinAndStat...................176 ms (273)
|    │        │  │  │     └─ files.stat                           103 ms (372)
|    │        │  │  └─ Resolver#_resolveNodeModule................124 ms (58)
|    │        │  │     └─ Resolver#_joinAndStat                   106 ms (159)
|    │        │  ├─ ImportScanner#_readFile.......................340 ms (299)
|    │        │  │  └─ files.readFile                             302 ms (299)
|    │        │  └─ other PackageSourceBatch.computeJsOutputFilesMap 164 ms
|    │        └─ PackageSourceBatch#getResources..................272 ms (53)
|    │           └─ PackageSourceBatch#_linkJS                    270 ms (53)
|    ├─ bundler.bundle..makeServerTarget........................2,357 ms (1)
|    │  └─ Target#make..........................................2,356 ms (1)
|    │     ├─ Target#_runCompilerPlugins..........................504 ms (1)
|    │     │  ├─ files.realpath                                   185 ms (62)
|    │     │  └─ plugin ecmascript................................196 ms (1)
|    │     │     └─ Babel.compile                                 119 ms (39)
|    │     └─ Target#_emitResources.............................1,827 ms (1)
|    │        ├─ PackageSourceBatch.computeJsOutputFilesMap.....1,693 ms (1)
|    │        │  ├─ ImportScanner#_getInstallPath                 118 ms (414)
|    │        │  ├─ ImportScanner#_findImportedModuleIdentifiers  659 ms (382)
|    │        │  ├─ Resolver#resolve..............................428 ms (1012)
|    │        │  │  ├─ Resolver#_resolveRelative..................140 ms (384)
|    │        │  │  │  └─ Resolver#_joinAndStat                   135 ms (303)
|    │        │  │  └─ Resolver#_resolveNodeModule................158 ms (81)
|    │        │  │     └─ Resolver#_joinAndStat                   134 ms (269)
|    │        │  ├─ ImportScanner#_readFile.......................320 ms (338)
|    │        │  │  └─ files.readFile                             286 ms (338)
|    │        │  └─ other PackageSourceBatch.computeJsOutputFilesMap 169 ms
|    │        └─ PackageSourceBatch#getResources..................127 ms (63)
|    │           └─ PackageSourceBatch#_linkJS                    126 ms (63)
|    └─ bundler writeSiteArchive................................2,218 ms (1)
|       ├─ bundler writeTargetToPath............................1,807 ms (2)
|       │  ├─ ClientTarget#write..................................303 ms (1)
|       │  │  └─ bundler writeFile................................122 ms (54)
|       │  │     └─ Builder#write                                 121 ms (54)
|       │  └─ ServerTarget#write................................1,471 ms (1)
|       │     └─ JsImage#write..................................1,410 ms (1)
|       │        ├─ Builder#write.................................552 ms (114)
|       │        │  ├─ files.writeFile                            337 ms (114)
|       │        │  └─ files.rename                               114 ms (114)
|       │        ├─ files.readFile                                142 ms (221)
|       │        └─ other JsImage#write                           506 ms
|       └─ Builder#complete.......................................389 ms (1)
|          └─ files.renameDirAlmostAtomically.....................389 ms (1)
|             └─ files.rm_recursive                               386 ms (1)
| 
| Top leaves:
| files.realpath...........................................5,285 ms (129)
| ImportScanner#_findImportedModuleIdentifiers.............4,925 ms (719)
| files.lstat..............................................2,571 ms (6783)
| files.readFile.............................................986 ms (1238)
| other meteorNpm.rebuildIfNonPortable.......................787 ms (8)
| files.stat.................................................587 ms (2889)
| other JsImage#write........................................506 ms (1)
| files.writeFile............................................465 ms (225)
| files.rm_recursive.........................................389 ms (4)
| files.readdir..............................................387 ms (783)
| other PackageSourceBatch.computeJsOutputFilesMap...........332 ms (2)
| other compileUnibuild (the app)............................294 ms (2)
| runJavaScript packages/underscore.js.......................293 ms (5)
| files.rename...............................................231 ms (231)
| ImportScanner#_getInstallPath..............................229 ms (802)
| Babel.compile..............................................189 ms (69)
| other Isopack#ensurePluginsInitialized.....................170 ms (24)
| other Resolver#resolve.....................................169 ms (1947)
| runJavaScript packages/html-tools.js.......................162 ms (1)
| sha1.......................................................149 ms (1364)
| other Target#_runCompilerPlugins...........................133 ms (2)
| 
| (#2) Total: 28,927 ms (Build App)

**Comment by benjamn** [comment] 2016-07-24 15:17
@ForHonor Thanks for the detailed profile report. Is there a repository for that react/meteor app that I could clone to reproduce this problem?

**Comment by ForHonor** [comment] 2016-07-24 19:42
Since you asked, I just put it up here:
https://github.com/ForHonor/ytmr
This is the smaller of the 2 projects.
it is labelled Tutorial in my first post.
Thank you in advance for any advice.

**Comment by kevde** [comment] 2016-08-18 05:14
Is this issue been improved in meteor 1.4. Just curious

**Comment by ForHonor** [comment] 2016-08-31 19:14
I've stopped working on Meteor for the time being. I didn't have much luck
with the upgrades and shifted back to other things that I could make
progress on...

**Comment by laserbeak** [comment] 2016-10-18 07:48
Meteor 1.4 on Xubuntu. AMD Octacore @ 3GHz 32GB RAM... Just finished reading this entire thread and still refreshing.

**Comment by abernix** [comment] 2016-10-18 09:00
For those that are interested, Meteor 1.4.2 is in beta and many users are experiencing significant increases in refreshes between saves and initial build times.  I won't say the issue is put to rest completely, but it does appear to be _much_ quicker.

The beta channel isn't always bug free and you may run into unrelated bugs, but if you're in a position to test you might find significant speed increases.  You can participate in the discussion and find how to try the current beta release in #7668.

**Comment by manuelro** [comment] 2017-07-16 01:06
I don't know if someone has already made this recommendation above (I will not read the entire thread).

This happens mainly because Meteor is checking for updates in the currently installed packages, in order to disable that process just add a `METEOR_OFFLINE_CATALOG` to your settings file:

`/settings/development.json` (or `production.json`)
```json
{
    "METEOR_OFFLINE_CATALOG": 1
}
```

After this Meteor will refresh after a change in about ~0.7 or ~1.5 seconds (depending on the size of your project)
