### ISSUE TITLE
`bcrypt` crashes the server

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#7095] opened 2016-05-21 09:18 UTC
Meteor 1.3.2.4. 

Calling into `bcrypt` from either the shell or a method crashes the server. Strangely it only happens from `Accounts.createUser` if you have `aws-sdk` included in your app?

Simple reproduction: https://github.com/tmeasday/simpler-7095-repro

---

`aws-sdk` reproduction:

 Steps to reproduce:

```
$ meteor create tmp
$ cd tmp
$ meteor add accounts-password
$ meteor add peerlibrary:aws-sdk # OR, npm i --save aws-sdk
$ meteor
```

If using NPM `aws-sdk`, create a single file, `server/main.js` and add this line:

    import AWS from 'aws-sdk';

Then run `meteor shell` and do:

    Accounts.createUser({email: 'you@user.net', password: 'test'});

The following result should occur:

```
W20160521-02:16:41.393(-7)? (STDERR)
W20160521-02:16:41.394(-7)? (STDERR) undefined:0
W20160521-02:16:41.395(-7)? (STDERR)
W20160521-02:16:41.395(-7)? (STDERR)
W20160521-02:16:41.395(-7)? (STDERR) TypeError: undefined is not a function
```

Paging @benjamn and @tmeasday as I feel this is a pretty serious issue. I wish I at least had a workaround. :( I've got two products launching into beta, and both require AWS. Users cannot create accounts, so we're stuck.

**Comment by ffxsam** [comment] 2016-05-21 09:27
Actually, downgrading to Meteor 1.3 seems to be a workaround. I'll try to find a more recent version that works.

**Comment by abernix** [comment] 2016-05-21 13:29
This seems like a `bcrypt` issue as the failure is happening right after [this](https://github.com/meteor/meteor/blob/devel/packages/accounts-password/password_server.js#L52), but it only happens on the `meteor server` REPL shell, not in the server code.

The "work-around" would be not allowing your users to create their accounts on the server shell – which would be pretty unexpected if you were doing that. :wink:

I can confirm that this happens though.

**Comment by ffxsam** [comment] 2016-05-21 16:48
Actually, it happens on the client side too. Rather, the account creation on the client triggers the server crash.

**Comment by abernix** [comment] 2016-05-21 17:48
Please make a basic sample reproduction of the problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here – Button, etc.  I realize it may seem simple, but building reproductions takes a significant amount of core developer's time.

**Comment by ffxsam** [comment] 2016-05-21 18:00
Done. https://github.com/ffxsam/meteor-aws-accounts-bug

I also realized, while cobbling this together, that if I move any aws-sdk references to the server only, then `Accounts.createUser` works (if done in the client). I had aws-sdk in lib, because it was part of my Astronomy model as an event hook (to remove a file when a Mongo document was deleted). But that's actually better off done in the server, as a callback for `observe`.

However, there may be other server-side `accounts-base` clashes that I don't know about yet.

**Comment by ffxsam** [comment] 2016-05-21 18:12
Ok, I take that back. Even using aws-sdk purely on the server still causes problems for both `Accounts.createUser` and `Meteor.loginWithPassword`.

**Comment by tmeasday** [comment] 2016-05-21 22:44
There's an even simpler repro for the shell alone:

```
meteor create binary-test; cd binary-test
npm install --save bcrypt@0.8.5 # this is the version used by accounts-password
meteor

# second terminal
meteor shell
require('bcrypt').hash('a', 3, function() {})
```

**Comment by tmeasday** [comment] 2016-05-21 22:46
(I think we can call this `impact:some` as aws is pretty commonly used, and I suspect it may happen with other binary packages. Also marked `severity:production` as it sounds like it was affecting @ffxsam in production too).

**Comment by tmeasday** [comment] 2016-05-21 22:52
OK, my simpler repro (no `aws-sdk` involved), also works from the client: https://github.com/tmeasday/simpler-7095-repro

Changing the issue title and linking from the top

**Comment by tmeasday** [comment] 2016-05-21 22:52
I wonder why `Accounts.createUser` sometimes works; it's awfully odd.

**Comment by ffxsam** [comment] 2016-05-21 22:55
`Accounts.createUser` never works for me in 1.3.2+ when I import `aws-sdk`.

**Comment by tmeasday** [comment] 2016-05-21 22:57
> Accounts.createUser never works for me in 1.3.2+ when I import aws-sdk.

Right, but it *does* work w/o `aws-sdk`. The reproduction I posted above doesn't involve `aws-sdk` though (and calls `bcrypt.hash` which is where the problem occurs for you too).

**Comment by ffxsam** [comment] 2016-05-21 23:00
Oh, you meant in general - yeah, it usually works fine otherwise. But since my app requires AWS, I have to stay at Meteor 1.3.1 for the time being.

**Comment by benjamn** [comment] 2016-05-22 17:07
If you're running `npm install bcrypt` instead of `meteor npm install bcrypt`, you might be using a different version of Node/V8 than Meteor uses when it runs your app and tries to import `bcrypt`.

What is the output of `npm version` on your system? How does that compare to `meteor npm version`?

**Comment by benjamn** [comment] 2016-05-22 17:30
Interesting, I can reproduce this without even using Meteor:
```sh
$ mkdir -p /tmp/bcrypt-aws/node_modules
$ cd /tmp/bcrypt-aws
$ npm version
{ npm: '2.15.1',
  ares: '1.9.0-DEV',
  http_parser: '1.2',
  modules: '11',
  node: '0.10.45',
  openssl: '1.0.1t',
  uv: '0.10.36',
  v8: '3.14.5.9',
  zlib: '1.2.8' }
$ npm install bcrypt aws-sdk

> bcrypt@0.8.6 install /private/tmp/bcrypt-aws/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node

aws-sdk@2.3.14 node_modules/aws-sdk
├── xml2js@0.4.15
├── sax@1.1.5
├── jmespath@0.15.0
└── xmlbuilder@2.6.2 (lodash@3.5.0)

bcrypt@0.8.6 node_modules/bcrypt
├── bindings@1.2.1
└── nan@2.2.1

$ node
> process.version
'v0.10.45'
> require("aws-sdk")
# lots of exports, apparently successful
> require("bcrypt")
{ genSaltSync: [Function],
  genSalt: [Function],
  hashSync: [Function],
  hash: [Function],
  compareSync: [Function],
  compare: [Function],
  getRounds: [Function] }
> _.hash("a", 5, function(){})
undefined
> 
undefined:0


TypeError: undefined is not a function
$ # node has crashed!
```

**Comment by ffxsam** [comment] 2016-05-22 18:17
Meteor's versions of npm and node are 2.14.22 and 0.10.43. On my system, it's 3.8.9 and 6.0.0. But even using the Meteor package `peerlibrary:aws-sdk`, this bug occurred.

**Comment by benjamn** [comment] 2016-05-22 18:49
Here's an even simpler (again Meteor-free) reproduction:
```sh
% node
> require("domain")
{ _stack: [],
  Domain: 
   { [Function: Domain]
     super_: { [Function: EventEmitter] listenerCount: [Function] } },
  createDomain: [Function],
  create: [Function],
  active: null }
> require("bcrypt").hash("a", 5, function(){})
undefined
>
undefined:0


TypeError: undefined is not a function
```
Since `domain` is a built-in Node module, this is beginning to look like a bug that `bcrypt` will have to fix.

**Comment by benjamn** [comment] 2016-05-22 19:04
Likely related: https://github.com/ncb000gt/node.bcrypt.js/issues/235
Possibly related: https://github.com/nodejs/nan/issues/284

**Comment by tmeasday** [comment] 2016-05-22 20:44
> If you're running npm install bcrypt instead of meteor npm install bcrypt, you might be using a different version of Node/V8 than Meteor uses when it runs your app and tries to import bcrypt.

Oh, wow, so it's a problem in general if people install binary modules without using `meteor npm`? (Assuming that they have different `npm/node` versions? This seems like a huge caveat that I'm not sure we mention anywhere.

> this is beginning to look like a bug that bcrypt will have to fix.

Can we explain why it's a bug in 3.2 but not 3.1?

**Comment by ffxsam** [comment] 2016-05-22 20:51
Ahhh, wow. Nice find, Benjamin! In the immortal words of [tab00](https://forums.meteor.com/users/tab00/activity), "Fix it immediately." ;) (bcrypt team, not MDG)

**Comment by mitar** [comment] 2016-05-22 21:27
> Oh, wow, so it's a problem in general if people install binary modules without using meteor npm? 

Not necessary, `peerlibrary:aws-sdk` does not install binary module in any special way.

**Comment by ffxsam** [comment] 2016-05-22 21:37
Couldn't Meteor just require a previous version of `bcrypt` that worked?

**Comment by mitar** [comment] 2016-05-22 21:42
Hm, what is currently a workaround? (The issue is labeled as such.) Downgrading Meteor? Does this count as a workaround? :-)

**Comment by mitar** [comment] 2016-05-22 21:42
Moreover, this does not happen only in shell, no? Just reproduction is through shell?

**Comment by ffxsam** [comment] 2016-05-22 21:44
Correct, easiest repro was via shell. Users were unable to create accounts (client side), and I was unable to create them server side. My current workaround is to use Meteor 1.3.1.

**Comment by ffxsam** [comment] 2016-05-22 22:03
>Does this count as a workaround? :-)

It does if it works! 😀

**Comment by tmeasday** [comment] 2016-05-22 22:24
> > Oh, wow, so it's a problem in general if people install binary modules without using meteor npm? 

> Not necessary, `peerlibrary:aws-sdk` does not install binary module in any special way.

@benjamn was referring to my repro which just uses `bcrypt` in a straightforward way. I can confirm that reproduction works properly (i.e. doesn't crash) if you `meteor npm install`. This seems like it needs to be documented somewhere.

**Comment by ffxsam** [comment] 2016-05-22 23:12
Wait, are you saying if I use `meteor npm` instead of `npm`, this bug wouldn't happen?

**Comment by benjamn** [comment] 2016-05-22 23:41
@ffxsam Using a different version of Node/V8 to compile binary npm packages leads to other (more reasonable) errors, which can almost always be solved by running `meteor npm rebuild` in the parent directory of your `node_modules`. I was just trying to make sure that wasn't the issue here.

There's definitely something weirder happening between `domains` and `bcrypt`, here.

I'm not sure I can really recommend this solution, but it seems as if setting
```js
process._usingDomains = function(){};
```
early in your application, before `require("domain")` is called (i.e. before you import `aws-sdk`) will disable the logic that decides to abort on uncaught domain exceptions.

**Comment by abernix** [comment] 2016-05-24 09:38
As @benjamn's reproduction shows, there is something going on that is not Meteor's fault.  But things work fine until the `meteor shell` comes into the picture.

For example, @ffxsam's [reproduction repo](https://github.com/ffxsam/meteor-aws-accounts-bug) actually works fine for me out of the box.  When I click the button there is no crash and the user gets logged in immediately (checked with `Meteor.userId()` on the console before and after clicking the button).  However, as soon as I connect to that server via `meteor shell`, it starts crashing everywhere.  Even `build`-ing it, I cannot get the problem to happen at all unless I add `require('domain')` explicitly in the code.

So it really seems the problem exists in the Meteor environment once you open the shell, or if you're directly importing `domain`.

Here is [my reproduction](https://github.com/abernix/i7095-non-shell) that shows it working completely fine even *with* AWS calls – client and server.  Just don't connect to it using `meteor shell`.

As far as labels go – I've removed `has-workaround` but it still seems like I can avoid this problem by not running `meteor shell` (which obviously isn't reasonable for most developers).

**Comment by abernix** [comment] 2016-05-24 10:52
Ok, the actual crash happens inside Node's `crypto.randomBytes` callback, [called by `bcrypt` on these lines](https://github.com/ncb000gt/node.bcrypt.js/blob/master/bcrypt.js#L49-L56) and sounds strangely similar to [this node issue](https://github.com/nodejs/node-v0.x-archive/issues/3956).

The problem actually doesn't exist if you run @benjamn's simple repo from a script (and not REPL), and it appears to be fixed in every Node version above `0.10.45` (though I haven't looked where https://github.com/nodejs/node-v0.x-archive/commit/d1eff9ab68ae3fa32285544ad9f1d2c2ed52ab82 went because it appears to be in pre-0.10.45 Node branches).  🍒

Anyway, I tried:

* `v0.10.39` 💣 
* `v0.10.43` 💣 
* `v0.10.45` 💣 
* `v0.11.16` ✅ 
* `v0.12.14` ✅ 
* `v4.4.4` (Meteor 1.4) ✅ ✅ 
* `v5.11.1` ✅ 
* `v6.2.0` ✅ 

And, to ensure this is fixed in Meteor + New Node, I created a branch of `release-1.4` rebased against `release-1.3.3` and ran my and @ffxsam's repo without any problem.  So the good/bad news appears to be that this definitely isn't a Meteor bug that can be fixed in a patch release, but it can be fixed by upgrading Node, which is happening oh-so-very-soon.

@ffxsam Can you confirm that there are no problems as long as you do not (at all) open `meteor shell`?

**Comment by ffxsam** [comment] 2016-05-24 17:24
Nice catch, Jesse! You're correct. I can create users all day long, _until_ I run `meteor shell`. Then it all comes crashing down. :) However, if I stop the meteor process and re-run it, I'm fine again until I run `meteor shell` again.

**Comment by ffxsam** [comment] 2016-05-24 17:46
So then this doesn't affect production - whew! Sorry about the mis-report there.

**Comment by abernix** [comment] 2016-05-25 06:16
No worries at all.  It is indeed a very confusing issue!  I'm going to downgrade this to `blocks-development` for now since it does seem to be isolated to the dev `meteor shell`.  Meteor 1.4 is probably the true fix for this.

As @benjamn previously mentioned, if you find it *really* helps you in development right now – this would *probably be fine* if set very early on (e.g. top of `/server/main.js`) – but I do not understand the full reprocusions of doing that, so use it only if necessary:
```js
if (Meteor.isDevelopment) {
  process._usingDomains = function(){};
}
```

**Comment by tomtom87** [comment] 2016-05-26 04:33
I've been having the issue with `bcrypt` for some time now and didn't see this issue here. For now if I try to run `npm install` on a `meteor build .` outputted .tar.gz bundle in the `programs/server` directory the bcrypt installation will fail. But if I delete the one `npm install` is adding, and install by running `npm install bcrypt` somewhere then manually `cp -r` the files: it work's like a dream. 

Hope this helps at all just thought I would leave this here incase it can... cheers

**Comment by abernix** [comment] 2016-05-26 08:19
@tomtom87 Your issue is unrelated to this ticket, but probably happening because of differences between your build machine and your deployment machine.  See [custom deployment](http://guide.meteor.com/deployment.html#custom-deployment) in the Meteor Guide, specifically the part about using `--architecture` with `meteor build`.  Though, if you want to keep things how you're doing them right now, you can probably avoid the deleting/moving/copying by just running `npm rebuild` in `programs/server`.  Anyhow, please make a post on forums if you continue to have problems with that and myself or someone will be happy to help you out.

**Comment by abernix** [comment] 2016-05-26 08:20
Commenting for organizational reasons: #7035 will fix this.

**Comment by benjamn** [comment] 2016-06-28 19:54
I can confirm that this is fixed in the Meteor 1.4 beta: `meteor update --release 1.4-beta.4`

At this time, I don't know how we would fix this in Meteor 1.3.x, so this issue is as "fixed" as it's ever going to be.

**Closed by benjamn** 2016-06-28 19:54 UTC
Labels: bug, confirmed, Impact:some, Project:JS Environment, Severity:blocks-development

**Comment by ffxsam** [comment] 2016-06-28 19:57
Nice work! No biggie, it's not like it's a show-stopper bug anyway.

**Comment by steve-ross** [comment] 2016-07-20 21:01
Wow this issue has been driving us nuts (as in WTF is happening & why can't we seem to figure out why it is random)... +1 for all the debugging everyone
