### ISSUE TITLE
meteor update from 2.2 to 2.3.2 failing 

### ISSUE THREAD

**Issue by nosizejosh** [meteor/meteor#11536] opened 2021-07-13 22:03 UTC
```
=> Errors while initializing project:

While loading package akryum:vue-sass@0.1.2:
error: Command failed: C:\Windows\system32\cmd.exe /c
C:\Users\oajos\AppData\Local\.meteor\packages\meteor-tool\2.3.2\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd rebuild --update-binary
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Users\\oajos\\AppData\\Local\\.meteor\\packages\\meteor-tool\\2.3.2\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe',
gyp verb cli
'C:\\Users\\oajos\\AppData\\Local\\.meteor\\packages\\akryum_vue-sass\\0.1.2\\plugin.vue-component-sass.os\\npm\\node_modules\\meteor\\vue-component-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.17.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable
"C:\Users\oajos\AppData\Local\.meteor\packages\meteor-tool\2.3.2\mt-os.windows.x86_64\dev_bundle\python\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\oajos\AppData\Local\.meteor\packages\meteor-tool\2.3.2\mt-os.windows.x86_64\dev_bundle\python\python.exe
C:\Users\oajos\AppData\Local\.meteor\packages\meteor-tool\2.3.2\mt-os.windows.x86_64\dev_bundle\python\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Command failed:
C:\Users\oajos\AppData\Local\.meteor\packages\meteor-tool\2.3.2\mt-os.windows.x86_64\dev_bundle\python\python.exe -c import sys; print
"%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:319:12)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\oajos\\AppData\\Local\\.meteor\\packages\\meteor-tool\\2.3.2\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\oajos\\AppData\\Local\\.meteor\\packages\\akryum_vue-sass\\0.1.2\\plugin.vue-component-sass.os\\npm\\node_modules\\meteor\\vue-component-sass\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
C:\Users\oajos\AppData\Local\.meteor\packages\akryum_vue-sass\0.1.2\plugin.vue-component-sass.os\npm\node_modules\meteor\vue-component-sass\node_modules\.temp-10czik3.yy0wi\node_modules\node-sass
gyp ERR! node -v v14.17.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\oajos\AppData\Roaming\npm-cache\_logs\2021-07-13T21_38_11_998Z-debug.log
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Users\\oajos\\AppData\\Local\\.meteor\\packages\\meteor-tool\\2.3.2\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe',
gyp verb cli
'C:\\Users\\oajos\\AppData\\Local\\.meteor\\packages\\akryum_vue-sass\\0.1.2\\plugin.vue-component-sass.os\\npm\\node_modules\\meteor\\vue-component-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.17.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable
"C:\Users\oajos\AppData\Local\.meteor\packages\meteor-tool\2.3.2\mt-os.windows.x86_64\dev_bundle\python\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\oajos\AppData\Local\.meteor\packages\meteor-tool\2.3.2\mt-os.windows.x86_64\dev_bundle\python\python.exe
C:\Users\oajos\AppData\Local\.meteor\packages\meteor-tool\2.3.2\mt-os.windows.x86_64\dev_bundle\python\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Command failed:
C:\Users\oajos\AppData\Local\.meteor\packages\meteor-tool\2.3.2\mt-os.windows.x86_64\dev_bundle\python\python.exe -c import sys; print
"%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:319:12)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\oajos\\AppData\\Local\\.meteor\\packages\\meteor-tool\\2.3.2\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\oajos\\AppData\\Local\\.meteor\\packages\\akryum_vue-sass\\0.1.2\\plugin.vue-component-sass.os\\npm\\node_modules\\meteor\\vue-component-sass\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
C:\Users\oajos\AppData\Local\.meteor\packages\akryum_vue-sass\0.1.2\plugin.vue-component-sass.os\npm\node_modules\meteor\vue-component-sass\node_modules\.temp-10czik3.yy0wi\node_modules\node-sass
gyp ERR! node -v v14.17.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\oajos\AppData\Roaming\npm-cache\_logs\2021-07-13T21_38_11_998Z-debug.log
```

**Comment by StorytellerCZ** [comment] 2021-07-14 08:02
Hi @nosizejosh could you please provide more details? What command are you running, what OS, etc.

**Comment by fpreti** [comment] 2021-07-15 15:21
I have a similar problem..I'm upgrading from version 2.2.1 to 2.3

`=> Errors while initializing project:

While selecting package versions:
error: Conflict: Constraint accounts-base@1.1.3 is not satisfied by accounts-base 2.0.0.
Constraints on package "accounts-base":
* accounts-base@~2.0.0 <- top level
* accounts-base@1.1.3 <- useraccounts:core 1.14.2
* accounts-base@2.0.0 <- service-configuration 1.1.0 <- accounts-base 2.0.0 <- accounts-password 2.0.0
* accounts-base@2.0.0 <- accounts-password 2.0.0
* accounts-base@1.7.1 || 2.0.0 <- alanning:roles 3.3.0

Conflict: Constraint http@1.0.10 is not satisfied by http 2.0.0.
Constraints on package "http":
* http@~2.0.0 <- top level
* http@1.0.10 <- useraccounts:core 1.14.2
* http@1.0.8 <- cfs:http-methods 0.0.32 <- tap:i18n 1.8.2
* http@1.4.2 <- ostrio:files 1.14.0

Conflict: Constraint http@1.0.8 is not satisfied by http 2.0.0.
Constraints on package "http":
* http@~2.0.0 <- top level
* http@1.0.10 <- useraccounts:core 1.14.2
* http@1.0.8 <- cfs:http-methods 0.0.32 <- tap:i18n 1.8.2
* http@1.4.2 <- ostrio:files 1.14.0

Conflict: Constraint http@1.4.2 is not satisfied by http 2.0.0.
Constraints on package "http":
* http@~2.0.0 <- top level
* http@1.0.10 <- useraccounts:core 1.14.2
* http@1.0.8 <- cfs:http-methods 0.0.32 <- tap:i18n 1.8.2
* http@1.4.2 <- ostrio:files 1.14.0
`

**Comment by StorytellerCZ** [comment] 2021-07-15 20:08
@fpreti the error tells you exactly what the problem is. `accounts-base@1.1.3 <- useraccounts:core 1.14.2`
You need to upgrade `useraccounts:core` to a version that supports accounts v2 and the same applies for `ostrio:files` and `cfs:http-methods 0.0.32 <- tap:i18n 1.8.2` for http v2.

**Comment by StorytellerCZ** [comment] 2021-07-15 20:12
For example `ostrio:files` v2 is all upgraded.

**Comment by StorytellerCZ** [comment] 2021-07-15 20:19
@nosizejosh I just checked and the file the package is trying to download doesn't exist, so this is not an issue with Meteor. As such I'm closing this issue.
The issue is already documented in the package: https://github.com/meteor-vue/vue-meteor/issues/430

**Closed by StorytellerCZ** 2021-07-15 20:19 UTC
Labels: Type:Bug

**Comment by fpreti** [comment] 2021-07-15 21:36
> @fpreti the error tells you exactly what the problem is. `accounts-base@1.1.3 <- useraccounts:core 1.14.2`
> You need to upgrade `useraccounts:core` to a version that supports accounts v2 and the same applies for `ostrio:files` and `cfs:http-methods 0.0.32 <- tap:i18n 1.8.2` for http v2.

ok, there is no version of useraccount:core, useraccount:unstyled and useraccount:iron-routing that supports accounts-base@2.0.0. Do you have a suggestion on how to replace these libraries?

**Comment by filipenevola** [comment] 2021-08-20 00:27
hi @fpreti the change is probably not going to breaking these libraries.

Updating the versionsFrom to be compatible should do the work.

The problem here is that these packages are no longer maintained by the authors but you could create a new up-to-date versions of these packages by creating a Fork.

This community is also discussing this here https://github.com/Meteor-Community-Packages/organization/issues/13

**Comment by diavrank** [comment] 2022-02-27 03:53
@nosizejosh solution [here](https://github.com/meteor-vue/vue-meteor/issues/430#issuecomment-1053008366)
