### ISSUE TITLE
[1.3-beta5] ReferenceError when trying to create global collections

### ISSUE THREAD

**Issue by johanbrook** [meteor/meteor#6086] opened 2016-01-26 09:56 UTC
Hi! I updated to 1.3 beta 5 today to check it out, but ran into this:

```
W20160126-10:50:29.029(1)? (STDERR) ReferenceError: Buckets is not defined
W20160126-10:50:29.029(1)? (STDERR)     at meteorInstall.server.lib.collections.buckets._collection.js (meteor://💻app/server/lib/collections/buckets/_collection.js:1:1)
W20160126-10:50:29.029(1)? (STDERR)     at fileEvaluate (meteor://💻app/packages/modules-runtime/.npm/package/node_modules/install/install.js:183:1)
W20160126-10:50:29.029(1)? (STDERR)     at require (meteor://💻app/packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160126-10:50:29.029(1)? (STDERR)     at /Users/Johan/Projects/Code/lookback/lookback/app/.meteor/local/build/programs/server/app/app.js:9462:1
W20160126-10:50:29.029(1)? (STDERR)     at /Users/Johan/Projects/Code/lookback/lookback/app/.meteor/local/build/programs/server/boot.js:242:10
W20160126-10:50:29.030(1)? (STDERR)     at Array.forEach (native)
W20160126-10:50:29.030(1)? (STDERR)     at Function._.each._.forEach (/Users/Johan/.meteor/packages/meteor-tool/.1.1.12-modules.5.122q3k9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160126-10:50:29.030(1)? (STDERR)     at /Users/Johan/Projects/Code/lookback/lookback/app/.meteor/local/build/programs/server/boot.js:137:5
```

`Buckets` is a server side defined Mongo collection:

```js
Buckets = new Mongo.Collection('buckets');
```

Nothing out of the ordinary. It's fixed by med doing this instead:

```js
global.Buckets = new Mongo.Collection('buckets');
```

Feels a bit odd. Couldn't find any docs on this.

**Comment by gbersani** [comment] 2016-01-26 16:40
Related to #6072 
Global variables in general aren't working proper in beta.5

**Comment by avital** [comment] 2016-02-03 00:57
Yeah, this is a dupe of #6072 and should be fixed in `1.3-modules-beta.6` (that should be released today or tomorrow)

**Closed by avital** 2016-02-03 00:57 UTC

**Comment by benjamn** [comment] 2016-02-03 01:03
The specific commit that should fix this is https://github.com/meteor/babel-preset-meteor/commit/57316d6bab33f4888d1e4aca0feb508a0e5d2b8b.

**Comment by trusktr** [comment] 2016-02-04 02:56
@benjamn Are there any downsides to not having "use strict" that we should pay particular attention to? One that comes to mind is that hoisted functions can reference the global object with `this`.
