### ISSUE TITLE
RE: Meteor does not currently support objects other than ObjectID as ids" Only in Production

### ISSUE THREAD

**Issue by vhuerta** [meteor/meteor#6219] opened 2016-02-11 18:31 UTC
We are experimenting a problem, we have our app hosted in modulus, when we deploy a new release, arbitrarily they begin to generate documents in different collections with ids that can be json objects with one property or dates , which causes the application to start throwing the error i mention above. After researching about it and did not find any solution beginning to believe that the error may be caused when the javascript code of the application is updated while even local database is synchronizing with the server.

Below i share the server log:

```
Exception while polling query {"collectionName":"appraisalSpaces","selector":{"userId":"qoiG5kZW5GZomg8ow"},"options":{}}: Error: Meteor does not currently support objects other than ObjectID as ids
    at [object Object].MongoID.idStringify [as _idStringify] (packages/mongo-id/id.js:73:1)
    at [object Object]._.extend.has (packages/id-map/id-map.js:31:1)
    at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:998:1)
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1020:1)
    at [object Object]._.extend.getRawObjects (packages/mongo/mongo_driver.js:1069:1)
    at [object Object]._.extend._pollMongo (packages/mongo/polling_observe_driver.js:147:1)
    at [object Object].proto._pollMongo (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2725:1)
    at Object.task (packages/mongo/polling_observe_driver.js:85:1)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
    at packages/meteor/fiber_helpers.js:125:1
```

We have already checked we're not inserting these id values ​​intentionally in the application code.

Below I share some examples of bad generated records.

```javascript

{ 
    "_id" : {
        "_str" : "d5a3251635572f651a476dc6"
    }, 
    "title" : "DASHBOARD.ACTIVITIES.STATUS_CHANGE_TITLE", 
    "text" : {
        "message" : "DASHBOARD.ACTIVITIES.STATUS_CHANGE_TEXT", 
        "data" : {
            "one" : "160201061", 
            "two" : "Agendada"
        }
    }, 
    "unitId" : "C59E6eXd6nALvdQGm", 
    "createdAt" : ISODate("2016-02-09T12:06:25.253+0000"), 
    "createdDate" : {
        "year" : "2016", 
        "month" : "2", 
        "day" : "9"
    }, 
    "createdBy" : "HXiQEzNkvFEpwhNGT", 
    "collection" : "activities"
}

{ 
    "_id" : ISODate("2016-02-11T16:03:37.590+0000"), 
    "typesId" : "SALA", 
    "typesName" : ISODate("2016-02-11T16:01:51.157+0000"), 
    "userId" : "qoiG5kZW5GZomg8ow", 
    "appraisalId" : "HbgvZdNJRhiCTdEkN", 
    "createdAt" : ISODate("2016-02-11T16:08:21.256+0000"), 
    "createdBy" : "qoiG5kZW5GZomg8ow", 
    "progress" : "Amo9hEyJenxN24wzC", 
    "collection" : "appraisalSpaces"
}
```
Aditional bellow i share all the packages that we have instaled in our application:

```
appcache
iron:router
accounts-password
accounts-base
tap:i18n
nimble:restivus
copleykj:mesosphere
alanning:roles
momentjs:moment
less
http
underscorestring:underscore.string
meteorhacks:ssr
fixtures
anti:fake
u2622:persistent-session
mrt:moment-timezone
matb33:collection-hooks
stevezhu:lodash
meteorhacks:npm
reactive-var
mrt:moment
risul:accounting
mdg:geolocation
lookback:emails
blackcore:google-maps
meteorhacks:aggregate
percolate:synced-cron
standard-minifiers
meteor-base
mobile-experience
mongo
blaze-html-templates
session
jquery
tracker
logging
reload
random
ejson
spacebars
check
miro:json2html
ground:db
tap:i18n-bundler
mnmtanish:call
rafaelhdr:google-charts
kadira:debug
```

The actual version of meteor in our app is 1.2.1

Did you have any idea what is happening?

Greatly appreciated your help , Regards

**Comment by helfer** [comment] 2016-02-16 23:13
I can't think of any reason this would happen only in production but not in development, unless you have other services writing to your database. From Meteor you can only insert documents with string or ObjectID as _id. If you are sure that the meteor app is the only thing writing to the  database then you should be able to reproduce it in development mode.

Closing issue because it does not seem to be related to Meteor. If you have more concrete information later, we can reopen it.

**Closed by helfer** 2016-02-16 23:13 UTC

**Comment by svda** [comment] 2017-03-23 14:42
I am currently experiencing this issue, and have been scratching my head to find the solution. I forked to mongo-id package for debug purposes, and found that in some occasions, the input id in MongoID.idStringify(id) appears to be a plain object, with another key called id of type Uint8Array.

Either the mongo-id package needs updating, an incompatible node mongodb driver is being used, or the function simply gets called with faulty input, which is very hard to track down since this function is called very often frpm many different places.

**Comment by svda** [comment] 2017-03-23 14:59
Never mind, somehow we are generating wrong ObjectID's
