### ISSUE TITLE
Meteor Project initialization error

### ISSUE THREAD

**Issue by yawlhead91** [meteor/meteor#7831] opened 2016-09-27 20:50 UTC
Hi there trying to create my first meteor project on my desktop. When I try initialize my project after creation by entering the directory and entering meteor get and error.  I am working on windows 10. I tried uninstalling/installing. I am on node  5.6.0 and meteors 1.4.1.1

 C:\Users\Alex\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

TypeError: httpProxy.createProxyServer is not a function
    at Proxy.start (C:\tools\runners\run-proxy.js:40:28)
    at Runner.start (C:\tools\runners\run-all.js:119:16)
    at Object.exports.run (C:\tools\runners\run-all.js:322:10)
    at Command.doRunCommand [as func] (C:\tools\cli\commands.js:360:17)
    at C:\tools\cli\main.js:1410:23

**Comment by abernix** [comment] 2016-09-28 13:00
How did you install Meteor?  What Terminal environment are you using? (e.g. PowerShell, `cmd`, `bash`, etc.)

**Comment by yawlhead91** [comment] 2016-09-28 20:57
Hi @abernix  , First I tried bash then Powershell same error on both

**Comment by karthikraja34** [comment] 2016-09-30 08:31
I too got the same error whenever i try to initialize a new project.I am using windows 10 and i installed meteor from official installer.

**Comment by abernix** [comment] 2016-09-30 08:39
@karthikraja34 Again, please be more specific about your versions and your error so we can try to find a trend here and hopefully a solution.  Are you getting exactly `httpProxy.createProxyServer is not a function`?  Are you on Windows 10 Home, Pro, Pro Education, Enterprise?  Has it worked in the past?  Before a Windows Update? What shell are you using?  Command Prompt, PowerShell, Bash, MINGW64?

**Comment by yawlhead91** [comment] 2016-09-30 09:29
@karthikraja34 @abernix  Hi there I am on windows 10 . I got it working I had to reinstall my OP system and clean install everything. It was my last choice as i needed to get to work by today but Its working fine now.

**Comment by karthikraja34** [comment] 2016-09-30 10:18
I too got it working . I uninstalled meteor js and deleted all files from .meteor folder ,then again installed . Now it is working for me.

**Comment by abernix** [comment] 2016-09-30 11:46
Ok, closing.  Thanks for the update.  Hopefully this will be fixed going forward and is due to something left over with a previous version of Meteor or a temporary misconfiguration.

**Closed by abernix** 2016-09-30 11:46 UTC
Labels: Project:Windows

**Comment by yoonwaiyan** [comment] 2016-10-07 05:45
Have this error too on my machine.

OS: Mac OSX Yosemite
Meteor version: 1.4.1.2

Happened when I create my first Meteor project right after installing Meteor to my machine, but it works(server starts properly) after I've `cd`-ed into my project, run `npm install` and `meteor`.

**Comment by abernix** [comment] 2016-10-07 12:44
@yoonwaiyan Can you reproduce this problem?

For example, if you reinstall Meteor again (Just run `curl https://install.meteor.com/ | sh` which will uninstall, download and reinstall) and create a new project again?

And can you confirm that it goes away if you run `meteor npm install` before you start meteor (with the `meteor` command)?

Your help in reproducing the problem would be helpful to future users since this doesn't appear to happen to everyone.

**Comment by yoonwaiyan** [comment] 2016-10-10 05:42
@abernix Interestingly, there was no error at all when I initialize another Meteor app. I've tried re-installed by  `curl https://install.meteor.com/ | sh` and created another project again but without any error again, and I can call `meteor` directly. Btw this is my output of `npm version`:

```
{ npm: '3.3.12',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.4.1',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }
```

**Comment by abernix** [comment] 2016-10-10 14:26
@yoonwaiyan Thanks for the reply – I don't have any further ideas.  But please be careful using `npm install`, especially with those versions.  Meteor is bundled with its own version of `node` and `npm` in order to operate with the version which it was intended to run; Meteor is not tested with Node 5 and you could easily run into problems using an untested version (with mis-matched binaries, etc.).  You can use `meteor npm` instead of `npm` to avoid any possible issues.

**Comment by PainKKKiller** [comment] 2016-11-08 16:40
Have the same error with meteor installed on Windows 10. What I did:
installed meteor from installer for windows.
Then run in command line:
`meteor create mySite
cd mySite
meteor npm install
meteor` and then I got same error.
Tried to create another project and failed too.
