### ISSUE TITLE
Changing a `imports` file which is only imported on the client should not cause a server rebuild.

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#7434] opened 2016-07-19 03:32 UTC
Repro: https://github.com/tmeasday/client-rebuild-repro. Notice changing `client/import.js` only rebuilds the client, and `imports/test.js` rebuilds both.

Thinking about this more, it is not surprising, given the way that the watchSet is [put together](https://github.com/meteor/meteor/blob/7267-request-resuming/tools/isobuild/package-source.js#L1428).

I'm not exactly sure what would be involved, but it would sure be nice to not ask people to put files in `client/` directories inside `imports/` (see https://forums.meteor.com/t/application-structure/20187/56)

**Comment by davidworkman9** [comment] 2016-09-16 13:24
This would be really nice, my current workflow is pretty disgusting, I write a lot of my tests to run on the server because it's easier to work with the "sync"/fibers workflow. But for development I end up dragging stuff into a client directory so it rebuilds faster, then when I go to commit drag them back out and run the tests, not exactly optimum lol.

That said currently if you try to import something under a server folder on the client it doesn't find it, keeping that would be optimum so we're not leaking stuff we don't want to by accident to the client.

**Comment by merlinpatt** [comment] 2017-02-09 16:58
This seems to be a duplicate of https://github.com/meteor/meteor/issues/6576, which has more comments, and is more detailed, so I'm closing this one in favor of that one

**Closed by merlinpatt** 2017-02-09 16:58 UTC
Labels: feature, Impact:most, Project:Tool
