### ISSUE TITLE
[1.2.1] meteor run xxx-device fails on 2nd time if Cordova plugin contains dependency

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#8196] opened 2016-12-27 17:17 UTC
This is a follow-up on #7029, as I now found the root cause of my breaking builds on Meteor 1.2:  Cordova plugins that reference other Cordova plugins as a dependency.

If a Cordova plugin includes a dependency, it sometime happens that Meteor 1.2 won't purge this dependency plugin when trying to install new plugins. This causes the whole build process to fail. In some cases, this happens only if you really have added or removed plugins, but in the worst case (like the PayPal Mobile SDK) Meteor tries to purge all plugins on every startup, which breaks the build on nearly all server starts.

A detailed error description and a reproduction repo can be found here:
https://github.com/derwaldgeist-test/meteor-cordova-dependency

It contains two test cases that can be switched over by uncommenting packages in the ```packages``` file.

**Comment by abernix** [comment] 2017-01-02 10:36
Thanks for taking the time to debug this and provide a reproduction.

Your reproduction does demonstrate the problem you described (when running under Meteor 1.2), however, upon upgrading to Meteor 1.4.2.3 the problem goes away.

Among the massive number of changes between Meteor 1.2 and 1.4.2.3 are significant updates to Cordova versions.  Unfortunately, if you're not able to demonstrate that this bug exists in the most recent version of Meteor, I'm not sure what to recommend aside from upgrading.  Even if you could narrow down exactly what commit(s) fixed this, I'd venture to say that there is little chance the fix would be back-ported to such an old version of Meteor unless the demand was particularly high and the solution relatively simple.

I'll mark this as a bug, but I cannot mark it as confirmed for the above reason.

**Comment by ramezrafla** [comment] 2017-02-06 20:52
@derwaldgeist is still an issue given it has been resolved in more recent version?

**Comment by hwillson** [comment] 2017-02-07 10:26
Since upgrading to the latest Meteor version fixes this issue, I'll close it off. Thanks for reporting this originally @derwaldgeist (and thanks for the followup @ramezrafla)!

**Closed by hwillson** 2017-02-07 10:26 UTC
Labels: bug, can't-reproduce

**Comment by woutervanwijk** [comment] 2017-09-18 08:55
This issue pops up again in Meteor 1.5.2, when adding cordova-plugin-x-socialsharing@5.2.0 :(

**Comment by abernix** [comment] 2017-09-18 09:39
@woutervanwijk Would you please open a new issue with explicit reproduction steps (and ideally, an example repository of your own reproduction)?  

This issue is a couple years old and closed so not really the best place for new commentary. :smile:

**Comment by derwaldgeist** [comment] 2017-09-18 09:52
Just FYI: I can confirm that this issue is still there in later versions. I had a session on guzz.io recently with a guy from South Carolina who had the very same problem and was able to solve it by putting the dependency manually in the cordova plugins file. IIRC, he was on latest Meteor 1.5.x

**Comment by markoshust** [comment] 2017-11-18 20:20
I can also confirm that this is happening on Meteor 1.6:
`Failed to install 'cordova-plugin-splashscreen': Cannot find plugin.xml for plugin "cordova-plugin-splashscreen". Please try adding it again.`

I did add `cordova-plugin-splashscreen` to the installed list of cordova plugins, however I still get the error. It's random, but it occurs quite frequently (about 35% of the time a mobile build is executed).

**Comment by abernix** [comment] 2017-11-20 11:13
@markoshust Have you tested Meteor 1.6.1 (currently in beta) which has had some Cordova updates thanks to #9213.

**Comment by robertross** [comment] 2017-11-24 16:08
I would like to say this happens to me also after upgrading to 1.6

https://forums.meteor.com/t/cordova-error-plugin-cordova-plugin-actionsheet-is-not-present-in-the-project-see-cordova-plugin-list/40720

**Comment by tripflex** [comment] 2018-01-04 22:42
Just in case anybody has a problem similar to this, posting this in here just to give you troubleshooting tips:

I had this similar issue with a local Cordova plugin I was using, and turns out the problem was due to the configuration still remaining in the Cordova configuration, even though I had ran `meteor remove cordova:my-cordova-plugin`

What I recommend is to remove the plugin and add it back to see if that fixes it (did for me)

First, remove it through meteor:
`meteor remove cordova:my-cordova-plugin`

Then, goto the `.meteor/local/cordova-build/` directory, and run this command to list all cordova plugins:
`cordova plugin list`

If you see that one listed, run this command to remove it from Cordova:
`cordova rm my-cordova-plugin`

Then go back to source directory:
I would then run your application to see if it works (to build once first before adding back), and then add it back to the project:

`meteor add cordova:my-cordova-plugin`

**Comment by andreasseiler** [comment] 2018-01-17 09:08
I have the same issue with Meteor 1.6.0.1 if I try to install cordova-spotify-oauth@0.1.10 - Cordova error: The plugin 'es6-promise-plugin' is required by (cordova-spotify, cordova-spotify-oauth), skipping uninstallation. (try --force if trying to update)

**Comment by crapthings** [comment] 2018-08-15 02:42
meteor 1.7.0.4

jpush-phonegap-plugin@3.0.2

```
Writing new config.xml
Removing plugins
cordova-plugin-badge,cordova-plugin-calendar,cordova-plugin-device,cordova-plugin-geolocation,cordova-plugin-inappbrowser,cordova-plugin-ios-disableshaketoedit,cordova-plugin-keychain-touch-id,cordova-plugin-meteor-webapp,cordova-plugin-network-information,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-whitelist,cordova-plugin-wkwebview-engine,jpush-phonegap-plugin,phonegap-plugin-barcodescanner
from Cordova project
%% No scripts found for hook "before_plugin_rm".
%% Calling plugman.uninstall on plugin "cordova-plugin-badge" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-calendar" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-device" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-geolocation" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-inappbrowser" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-ios-disableshaketoedit" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-keychain-touch-id" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-meteor-webapp" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-network-information" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-splashscreen" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-statusbar" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-whitelist" for platform "android"
%% Calling plugman.uninstall on plugin "cordova-plugin-wkwebview-engine" for platform "android"
%% Calling plugman.uninstall on plugin "jpush-phonegap-plugin" for platform "android"
%% Removing /Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/plugins/jpush-phonegap-plugin because mandatory plugin variables were missing.
%% Calling plugman.uninstall on plugin "phonegap-plugin-barcodescanner" for platform "android"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Running command: "/Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version"
%% Command finished with error code 0: /Users/monsterstep/dev/cube-patch/cube copy/.meteor/local/cordova-build/platforms/android/cordova/version
=> Errors executing Cordova commands:

   While removing plugins
   cordova-plugin-badge,cordova-plugin-calendar,cordova-plugin-device,cordova-plugin-geolocation,cordova-plugin-inappbrowser,cordova-plugin-ios-disableshaketoedit,cordova-plugin-keychain-touch-id,cordova-plugin-meteor-webapp,cordova-plugin-network-information,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-whitelist,cordova-plugin-wkwebview-engine,jpush-phonegap-plugin,phonegap-plugin-barcodescanner
   from Cordova project:
   Cordova error: Cannot find plugin.xml for plugin "jpush-phonegap-plugin". Please try adding it again.
   at new PluginInfo
   (/Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/src/PluginInfo/PluginInfo.js:367:15)
   at PluginInfoProvider.get
   (/Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/src/PluginInfo/PluginInfoProvider.js:35:32)
   at /Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/dependencies.js:40:49
   at Array.forEach (<anonymous>)
   at Object.generateDependencyInfo
   (/Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/dependencies.js:36:45)
   at runUninstallPlatform
   (/Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/uninstall.js:252:53)
   at /Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/uninstall.js:93:16
   at _fulfilled (/Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:816:13)
   at
   /Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:624:44
   at runSingle
   (/Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:137:13)
   at flush
   (/Users/monsterstep/.meteor/packages/meteor-tool/.1.7.0_4.4cyydi.qo9kg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:125:13)
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickCallback (internal/process/next_tick.js:180:9)
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running again with the --verbose option to help diagnose the issue.)

/Users/monsterstep/.meteor/packages/coffeescript/.1.0.17.1htj6g3.wxr3++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^
ExitWithCode:1
```

**Comment by CineXMike** [comment] 2018-09-12 08:34
Still occuring.
First in installs everything and on the moment it finishes installing all the plugins and launches xcode it removes everything from config.xml again and you get this error in xcode:
ERROR: Plugin 'ActionSheet' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

**Comment by KoenLav** [comment] 2019-12-18 13:38
Same issue, still happening with Meteor 1.8.2.

**Comment by filipenevola** [comment] 2020-01-29 14:36
@KoenLav are you able to reproduce on 1.10 betas?

**Comment by KoenLav** [comment] 2020-02-06 09:22
@filipenevola I can't even get that far, with 1.10-beta.5 I keep running into:

`
   While adding plugin cordova.plugins.diagnostic@5.0.1 to Cordova project:        
   Cordova error: Failed to fetch plugin cordova.plugins.diagnostic@5.0.1 via registry.
   Probably this is either a connection problem, or plugin spec is incorrect.
   Check your connection and plugin name/version/URL.
   Error: npm: Command failed with exit code 1 Error output:
   'npm' is not recognized as an internal or external command,
   operable program or batch file
`
