### ISSUE TITLE
Better error reporting in Firefox??

### ISSUE THREAD

**Issue by CaptSaltyJack** [meteor/meteor#4402] opened 2015-05-19 01:58 UTC
Here's a look at console errors in Chrome vs Firefox.

In Chrome:
![chrome](https://cloud.githubusercontent.com/assets/440132/7694053/a96171b0-fd8f-11e4-8cc1-2bbed4f0feb3.png)

Informative, right? I have a general idea what to look for.

Now, the trainwreck that is Firefox:
![firefox](https://cloud.githubusercontent.com/assets/440132/7694066/d9387898-fd8f-11e4-85ba-711a9c251196.png)

Will we ever get better Meteor error reporting in Firefox?

**Comment by glasser** [comment] 2015-05-19 21:27
Duplicate of #2232.

**Closed by glasser** 2015-05-19 21:27 UTC
