### ISSUE TITLE
Cordova android throws error in aapt

### ISSUE THREAD

**Issue by jimmiebtlr** [meteor/meteor#6761] opened 2016-04-08 23:28 UTC
I'm running meteor 1.3.1 on fedora 23, fully updated and getting the following error when trying to 
`meteor run android`

```
:generateX86DebugResources
   Starting app on Android Emulator          /                       
   Starting app on Android Emulator          /                        
 FAILEDting app on Android Emulator          /                         

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processX86DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/jimmie/.android/build-tools/23.0.2/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16.293 secs
Error code 1 for command: /home/jimmie/.home/Documents/upwork/personalizedLearningSolutions/.meteor/local/cordova-build/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/jimmie/.home/Documents/upwork/personalizedLearningSolutions/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=x86,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true undefined
=> Errors executing Cordova commands:         

   While running Cordova app for platform Android with options --emulator:
   Error: Command failed:                     
   /home/jimmie/.home/Documents/upwork/personalizedLearningSolutions/.meteor/local/cordova-build/platforms/android/cordova/run
   --emulator

   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

/home/jimmie/.meteor/packages/meteor-tool/.1.3.1.lo8r21++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
ExitWithCode:1

```

It seems to be something in the asset build that's causing the issue.

What additional information would be useful?

**Comment by pnigroh** [comment] 2016-04-10 01:47
I'm having the same problem with latest ubuntu build

**Comment by jimmiebtlr** [comment] 2016-04-12 18:16
Another note, it's giving the same error on OSX, and IOS run's fine.

**Comment by wojtkowiak** [comment] 2016-04-12 19:02
If you have 64 bit distro, install 32 bit deps:
`sudo apt-get install -y lib32gcc1 libc6-i386 lib32z1 lib32stdc++6
sudo apt-get install -y lib32ncurses5 lib32gomp1 lib32z1-dev`

**Comment by wojtkowiak** [comment] 2016-04-12 19:03
If have the same problem on OSX then it probably not that issue.

**Comment by rlech** [comment] 2016-05-05 19:36
damn I have the same error. building for android or running for android is not working. iOS is working fine.

My Error on OS X (Meteor 1.3.2.4, and Android SDK API level 23)
```
* What went wrong:
Execution failed for task ':processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/username/Library/Android/sdk/build-tools/23.0.3/aapt'' finished with non-zero exit value 1
```

**Comment by jschlieber** [comment] 2016-05-11 14:37
I had a similar issue (Meteor 1.3.2.4 with crosswalk package). As soon as I added

```javascript
App.launchScreens({
    "iphone_2x": "resources/splashes/iphone_2x.png", // 640x490
    "iphone5": "resources/splashes/iphone5.png", // 640x1136
    "iphone6": "resources/splashes/iphone6.png", // 750x1334
    "iphone6p_portrait": "resources/splashes/iphone6p_portrait.png", // 2208x1242
    "iphone6p_landscape": "resources/splashes/iphone6p_landscape.png", // 2208x1242
    "ipad_portrait": "resources/splashes/ipad_portrait.png", // 768x1024
    "ipad_portrait_2x": "resources/splashes/ipad_portrait_2x.png", // 1536x2048
    "ipad_landscape": "resources/splashes/ipad_landscape.png", // 1024x768
    "ipad_landscape_2x": "resources/splashes/ipad_landscape_2x.png", // 2048x1536
    "android_mdpi_portrait": "resources/splashes/android_mdpi_portrait.png", // 320x480
    "android_mdpi_landscape": "resources/splashes/android_mdpi_landscape.png", // 480x320
    "android_hdpi_portrait": "resources/splashes/android_hdpi_portrait.png", // 480x800
    "android_hdpi_landscape": "resources/splashes/android_hdpi_landscape.png", // 800x480
    "android_xhdpi_portrait": "resources/splashes/android_xhdpi_portrait.png", // 720x1280
    "android_xhdpi_landscape": "resources/splashes/android_xhdpi_landscape.png", // 1280x720
    "android_xxhdpi_portrait": "resources/splashes/android_xxhdpi_portrait.png", // 1080x1440
    "android_xxhdpi_landscape": "resources/splashes/android_xxhdpi_landscape.png" // 1440x1080
});
```

to my `mobile-config.js` as described by [meteor-assets](https://github.com/lpender/meteor-assets), I got the following `meteor build` failure:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7ReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/krok/Android/Sdk/build-tools/22.0.0/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.551 secs
=> Errors executing Cordova commands:         
                                              
   While building Cordova app for platform Android:
   Error code 1 for command: /home/krok/dev/projects/meteor/itsalive/.meteor/local/cordova-build/platforms/android/gradlew with args:
   cdvBuildRelease,-b,/home/krok/dev/projects/meteor/itsalive/.meteor/local/cordova-build/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
```

Without `App.launchScreens({...})` everything worked fine, i.e. adding just the `App.icons({...})` worked. Explicitly adding `App.setPreference("android-targetSdkVersion", "23");` to `mobile-config.js` resolved the issue for me...

**Comment by abernix** [comment] 2016-05-12 07:58
Does @jschlieber's `App.setPreference("android-targetSdkVersion", "23");` fix work for anyone else?

If someone can please make a minimum reproduction of this that's easy to see the problem it will be easier to resolve this.

**Comment by rlech** [comment] 2016-05-15 21:26
be sure that no file contains a öäüß. also in the public folder. I had a similar issue and my problem was a image in the public folder with a `ß` in the filename

**Comment by boustanihani** [comment] 2016-05-20 21:56
Same issue here, `App.setPreference("android-targetSdkVersion", "23");` did not help :(

```
FAILURE: Build failed with an exception.
What went wrong: Execution failed for task ':CordovaLib:processDebugResources'.
com.android.ide.common.process.ProcessException:
org.gradle.process.internal.ExecException:
Process command
"/home/ubuntu/workspace/android/android-sdk-linux/build-tools/20.0.0/aapt"
finished with non-zero exit value 127
```

**Comment by jschlieber** [comment] 2016-05-21 07:31
Do you have SDK version 23 and build tools installed on your system? The line

`"/home/ubuntu/workspace/android/android-sdk-linux/build-tools/20.0.0/aapt"`

suggests the opposite...

**Comment by boustanihani** [comment] 2016-05-21 18:02
Issue solved, my problem was that I forgot to install the 32-bit libraries under Ubuntu 14.04 64bit:
`sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6`

It would be nice if meteor build checks all needed dependencies before trying to build because the error messages thrown are not always helpful :bowtie:

**Comment by mhoc** [comment] 2016-05-25 20:12
I ran into a similar problem, which arose after adding some nine-patch files to the `public` folder. The problem persisted even after removing the files and removing any reference to them in `mobile-config.js`. This was solved by deleting `.meteor/local/cordova-build` and re-running the build. 

The core problem with the files, however, remains unsolved. The 9patch files generated with `draw9patch` triggered this bug, despite being named completely normally (`splash.9.png`). However, 9patch files drawn with [this online tool](http://romannurik.github.io/AndroidAssetStudio/nine-patches.html) worked fine. /shrug

**Comment by carpmike** [comment] 2016-06-24 12:25
@mhoc I had the same problem, fixed in the same way you did (thanks!). However, I used the [online tool](http://romannurik.github.io/AndroidAssetStudio/nine-patches.html) you suggested and still get the error. 

As soon as I add a 9 patch image from that site in to my build it fails. Gotta say these 9 patch files are a PITA.

**Comment by AnthonyAstige** [comment] 2016-07-02 04:28
I encountered this same error like @mhoc & @carpmike did right after running adding 9-patch files from the [online tool](http://romannurik.github.io/AndroidAssetStudio/nine-patches.html).

When I ran `meteor build` with `--debug` the build looked successful, but when I went back without the `--debug` the error came back. I cleared `.meteor/local/cordova-build` and now the build works. The 9-patch display looks a pretty funky, but that's probably another issue.

**Environment**
* Ubuntu 16.04
* Android SDK 24
* Nexus 5

**Comment by stevenhornung** [comment] 2016-08-02 16:27
@AnthonyAstige I had the same error come up when I added a 9-patch file. Clearing `.meteor/local/cordova-build` resolved the error for me. Thanks!

**Comment by SPodjasek** [comment] 2016-08-18 01:20
Same as above, possibly some 9-patch file broke my build. Clearing ```cordova-build``` fixed it.

**Comment by patekuru** [comment] 2016-09-24 07:23
Using the images generated by the "online tool" mentioned above worked. But only if I totally removed the .meteor/local/cordova-build before each time running "meteor build".

**Comment by xoxmizo** [comment] 2017-02-17 13:54
I'm having the same problem with meteor when i put "mupx deploy --settings=settings.json" i get 
:cdvCreateAssetManifest UP-TO-DATE
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':CordovaLib:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\hamza\AppData\Local\Android\sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
=> Errors executing Cordova commands:

   While building Cordova app for platform Android:
   Error code 1 for command: cmd with args:
   /s,/c,"C:\Users\hamza\Desktop\nows\buysellmobileapp\codecanyon-16573615-buy-sell-mobile-app-full-application-with-meteor-and-ionic\tapshop-files\tapshop\.meteor\local\cordova-build\platforms\android\gradlew
   cdvBuildRelease -b
   C:\Users\hamza\Desktop\nows\buysellmobileapp\codecanyon-16573615-buy-sell-mobile-app-full-application-with-meteor-and-ionic\tapshop-files\tapshop\.meteor\local\cordova-build\platforms\android\build.gradle
   -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"

:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources FAILED

BUILD FAILED

Total time: 2 mins 16.895 secs

**Comment by hwillson** [comment] 2017-09-08 19:06
As mentioned in https://github.com/meteor/meteor/issues/6761#issuecomment-218686406, if anyone can supply a reproduction demonstrating this issue (using a recent version of Meteor), that would really help with troubleshooting (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Due to the low recent activity on this issue however, I'll close it for now. Thanks!

**Closed by hwillson** 2017-09-08 19:06 UTC
Labels: Project:Mobile

**Comment by gsadhas** [comment] 2017-09-11 14:08
@jimmiebtlr I'm facing the same issue. Meteor cordova build fails at AAPT. I'm not sure what I'm doing wrong here. I'm using,
Meteor 1.3.4.4
SDK tools 23.0.1
Build tools 23.0.1
Platform tools 23.0.1 
OS - Mac OS sierra

Any help is appreciated, thanks!

**Error log:**

While running Cordova app for platform Android with options --device:
   Error: Command failed:                     
   /Users/xxx/.meteor/local/cordova-build/platforms/android/cordova/run
   --device
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.

   /Users/xxx/.meteor/local/cordova-build/platforms/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3
   : AAPT: Error retrieving parent for item: No resource found that matches the
   given name
   'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
   

   /Users/xxx/.meteor/local/cordova-build/platforms/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4
   : AAPT: Error retrieving parent for item: No resource found that matches the
   given name 'android:TextAppearance.Material.Widget.Button.Colored'.
   
   
   FAILURE: Build failed with an exception.
   
   * What went wrong:
   Execution failed for task ':processDebugResources'.
   > com.android.ide.common.process.ProcessException:
   org.gradle.process.internal.ExecException: Process 'command
   '/Users/xxx/Library/Android/sdk/build-tools/23.0.1/aapt'' finished with
   non-zero exit value 1
   
   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or
   --debug option to get more log output.
   Error code 1 for command:
   /Users/xxx/.meteor/local/cordova-build/platforms/android/gradlew
   with args:
   cdvBuildDebug,-b,/Users/xxx/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
   undefined
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)
                                              
/Users/xxx/.meteor/packages/fourseven_scss/.3.8.1.19wbc3j++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
ExitWithCode:1
