### ISSUE TITLE
Meteor in Windows 10 Professional 64bit errors 

### ISSUE THREAD

**Issue by nigeljames** [meteor/meteor#7324] opened 2016-06-29 13:15 UTC
My Meteor installation stopped working a couple of weeks ago.

Existing project won't run, can't create new projects and can't even use meteor update.
Everything was working fine on previous day and then nothing was working the next. 
I may have updated Meteor, the message to update came up on the console but can't be certain I actually updated, but I have tried older versions and re-installed node/meteor and manually removed the .meteor folder but nothing works.

The error messages below were the messages I was originally getting on updating,creating and running any apps. 
However these errors no longer show up on cmd. In fact no errors show up on command line BUT when I close down cmd a error flashes to cmd just before it exits but I don't have time to read it. This message is much smaller than the other messages below.

I have looked to see if anyone else has got/had the same problem but have come up blank.

I can't continue with Meteor unless I find a solution
Any help would be much appreciated.

Thanks in advance. 
Nigel

```
// **Error when trying to update meteor**

C:>meteor update
Errors prevented isopacket load:

While loading isopacket ddp:
module.js:338:15: Cannot find module './isObjectLike'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.
(C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-types\node_modules\lodash\isPlainObject.js:3:20)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.
(C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-types\lib\converters.js:27:46)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.
(C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-types\lib\index.js:226:19)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.
(C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-template\node_modules\babel-traverse\lib\path\lib\virtual-types.js:6:43)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.
(C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-template\node_modules\babel-traverse\lib\path\index.js:13:45)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.
(C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-template\node_modules\babel-traverse\lib\index.js:14:13)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.
(C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-template\lib\index.js:74:46)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.
(C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\lib\index.js:525:46)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Module.Mp.load (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object..extend.Npm.require (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x8632\tools\isobuild\bundler.js:1639:22)
at Object.require (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\tools\isobuild\bundler.js:1613:31)
at Package (meteor://app/packages/babel-compiler/babel-compiler.js:17:1)
at meteor://app/packages/babel-compiler/babel-compiler.js:356:1
at meteor://app/packages/babel-compiler/babel-compiler.js:356:1

C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
throw error;
^
Error: isopacket load failed?
at loadIsopacketFromDisk (C:\tools\tool-env\isopackets.js:286:11)
at C:\tools\tool-env\isopackets.js:88:23
at Object.exports.noYieldsAllowed (C:\tools\utils\fiber-helpers.js:37:14)
at Object.load (C:\tools\tool-env\isopackets.js:80:23)
at new ServiceConnection (C:\tools\meteor-services\service-connection.js:29:28)
at Object.exports.openServiceConnection (C:\tools\meteor-services\auth-client.js:12:10)
at openPackageServerConnection (C:\tools\packaging\package-client.js:21:21)
at _updateServerPackageData (C:\tools\packaging\package-client.js:149:14)
at C:\tools\packaging\package-client.js:127:12
at C:\tools\utils\buildmessage.js:334:18
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:333:36
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
at Object.exports.updateServerPackageData (C:\tools\packaging\package-client.js:126:23)
at C:\tools\packaging\catalog\catalog-remote.js:777:36
at C:\tools\utils\buildmessage.js:334:18
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:333:36
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
at RemoteCatalog.refresh (C:\tools\packaging\catalog\catalog-remote.js:776:18)
at Object.catalog.refreshOrWarn (C:\tools\packaging\catalog\catalog.js:48:22)
at [object Object].catalog.Refresh.OnceAtStart.beforeCommand (C:\tools\packaging\catalog\catalog.js:21:16)
at C:\tools\cli\main.js:1398:32
at C:\tools\utils\buildmessage.js:334:18
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:333:36
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
at C:\tools\cli\main.js:1397:20

// **Error trying to run any existing project**
C:\pos>meteor
C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
throw error;
^
Error: No metadata files found for isopack at: /C/Users/Nigel/AppData/Local/.meteor/packages/meteor-tool/1.3.2_4
at Isopack.loadUnibuildsFromPath (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x8632\tools\isobuild\isopack.js:882:13)
at C:\tools\packaging\tropohouse.js:514:19
at Array.forEach (native)
at Function..each..forEach (C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
at C:\tools\packaging\tropohouse.js:513:11
at C:\tools\utils\buildmessage.js:359:18
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:352:34
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:350:23
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
at Object.download (C:\tools\packaging\tropohouse.js:448:20)
at C:\tools\packaging\tropohouse.js:592:22
at C:\tools\utils\buildmessage.js:359:18
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:352:34
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:350:23
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:589:20)
at C:\tools\cli\main.js:440:30
at C:\tools\packaging\catalog\catalog.js:100:5
at C:\tools\utils\buildmessage.js:271:13
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:264:29
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:262:18
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:253:23
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at Object.capture (C:\tools\utils\buildmessage.js:252:19)
at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
at C:\tools\cli\main.js:439:17
at C:\tools\utils\buildmessage.js:271:13
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:264:29
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:262:18
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at C:\tools\utils\buildmessage.js:253:23
at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
at Object.capture (C:\tools\utils\buildmessage.js:252:19)
at C:\tools\cli\main.js:437:33
at Console.withProgressDisplayVisible (C:\tools\console\console.js:631:14)
at springboard (C:\tools\cli\main.js:436:11)
at C:\tools\cli\main.js:1045:5

// **Running a newly created project**
C:\demoproject>meteor

C:\Users\Nigel\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
throw error;
^
TypeError: Object [object Object] has no method 'createProxyServer'
at Proxy.start (C:\tools\runners\run-proxy.js:40:28)
at Runner.start (C:\tools\runners\run-all.js:114:16)
at Object.exports.run (C:\tools\runners\run-all.js:317:10)
at Command.doRunCommand as func
at C:\tools\cli\main.js:1402:23
```

**Comment by abernix** [comment] 2016-06-29 13:22
This sounds the same as #6218.  Make sure you're running `meteor update` from within an existing project and not just in the root of your hard-drive.  Please see that issue and try the reinstall instructions I just posted in this comment: https://github.com/meteor/meteor/issues/6218#issuecomment-229352878

Closing as duplicate.

**Comment by nigeljames** [comment] 2016-06-29 13:46
Thanks for the quick response. 
Unfortunately I have already followed the re-installation steps from #7299 which are the same from #6218 (actually did it twice) to no avail. The command line shows nothing whether I do a meteor create, run or update globally or in a local project. Nothing gets written to the cmd until I close the cmd window and then a quick error message appears that I can't read. It seems there is an error that just prevents Meteor from starting to do anything. Why nothing gets written to the command line window until I click X to close window I do not know but maybe that is caused by the shutting of window itself and not meteor?
I can't even get the Meteor version to run. Nothing is blocking Meteor from running( anti-virus and firewall have been temporarily disabled ) and it seems installed correctly, installed many times exactly as originally installed when working correctly. 

Thanks
Nigel

**Comment by abernix** [comment] 2016-06-29 14:00
Yeah, I'll go ahead and leave this open for the time being because although you're seeing similar errors as the #6218 issue, you're not trying to login.  You might actually be encountering two separate issues.

For the new project aspect of things, can you actually look at issue #7306 which is showing similar problems with `meteor-promise`?  There are some recommended solutions for reinstalling/fixing `meteor-promise` in there.

Appreciate your help and patience in trying to resolve this.

**Comment by nigeljames** [comment] 2016-06-29 14:09
Thanks. I will have a look at #7306.
I have just noticed that I can type 'meteor node --version' and 'meteor npm --version' and get a return value but nothing gets returned with 'meteor --version'
I don't know if that will lead to any clues but just thought I would let you know.

**Comment by abernix** [comment] 2016-06-29 14:17
Hmm, `meteor --version` should definitely output something!

When you run `meteor create foo-bar-project-name-whatever`, does it create things properly?  If so, can you actually create it completely blank and upload it to GitHub?   I'll then try running it on my Windows 10 (Enterprise, myself).

Basically, assuming you have Git [installed somehow](https://git-scm.com/download/win):

0. `meteor create issue-7324-test`
0. `cd issue-7324-test`
0. `git init`
0. `git add .`
0. `git commit -m "Initial Commit"`
0.  _Create the repo on GitHub_
0. `git remote add origin WHAT_GITHUB_GIVES_YOU`
0. `git push -u origin master`

**Comment by abernix** [comment] 2016-06-29 14:19
Oh also, also please make sure you run `meteor npm install` before you try running a new project!

**Comment by nigeljames** [comment] 2016-06-29 14:59
Meteor create does not create anything, not even the project folder!!

I have noticed that meteor npm install, although runs, produces the following warnings:
+-- graceful-fs@4.1.4 
+-- jspm@0.16.35 
`-- UNMET PEER DEPENDENCY react@15.1.0

npm WARN optional Skipping failed optional dependency /react-native/fbjs-scripts/babel/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN enoent ENOENT, open 'C:\package.json'
npm WARN react-native@0.26.2 requires a peer of react@15.0.2 but none was installed.
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

**Comment by abernix** [comment] 2016-06-29 15:11
Ok, what happens when you run `meteor create project-name`?  Is there any output?

Also, just as a general note: all `meteor` commands **except** `meteor create` are intended to be run from _within_ a project directory **only**.  `meteor npm install` outside of a Meteor project directory will **not** produce any desired results.

**Comment by nigeljames** [comment] 2016-06-29 15:21
No, no output from meteor create to the console unless I close console and a brief error message then appears but I can't read it before console closes. 
Meteor npm install produced the same output, as pasted above, whether in a project directory or not!

**Comment by abernix** [comment] 2016-06-29 15:28
Have you tried using a different shell?  Perhaps try PowerShell?

**Comment by nigeljames** [comment] 2016-06-29 15:43
PowerShell gives the same result as cmd. As does powerCmd.

**Comment by abernix** [comment] 2016-07-05 17:21
Would it be possible for you to ZIP up your `C:\Users\YourUserName\AppData\Local\.meteor` folder and upload it to Dropbox (or similar)?  It could be rather large, but I can load it into a VirtualBox and try to reproduce the problem.  You can either post the link here or private message me on the Meteor Forums: http://forums.meteor.com/

**Comment by nigeljames** [comment] 2016-07-05 18:48
Unfortunately Meteor is no longer installed on my windows system, so I have no .meteor folder to upload.

Thanks

**Comment by abernix** [comment] 2016-07-06 06:18
Ok, I will close this issue then as it seems isolated.  Please re-open if you run into it again!

**Closed by abernix** 2016-07-06 06:18 UTC
Labels: bug, can't-reproduce, Impact:few, Project:Windows, Severity:blocks-development
