### ISSUE TITLE
Exclude force-ssl (https) for a health check path

### ISSUE THREAD

**Issue by ggn06awu** [meteor/meteor#6079] opened 2016-01-25 18:19 UTC
I am stuck, it doesn't seem possible to use force-ssl with Amazon's EC2 load balancers with SSL termination enabled. The health check agent can be configured to request either of the following:

- HTTPS health check is rejected because the certificate is invalid, it doesn't exist within the Meteor instance itself (and it's not possible to do this even if you don't want to use websockets?). 
- HTTP health check is redirected to HTTPS because that's what the force-ssl module does. 

It's catch 22, the only way out is to run an Nginx (or similar) proxy to SSL terminate after the load balancer rather than more conveniently (and cheaply) at the EC2 load balancers, which is a huge concession.

Can we please discuss adding the ability to ignore the HTTPS redirect for a /health_check end point?

**Comment by devonbarrett** [comment] 2016-01-26 10:28
There would not be much point having just a single statically ignored path, but the solution suggest as part of #5927 would work nicely, and is greatly needed!

**Comment by timbotnik** [comment] 2016-02-02 22:58
Agree with @devonbarrett, closing as duplicate of #5927.

**Closed by timbotnik** 2016-02-02 22:58 UTC
