### ISSUE TITLE
Sub templates starting with HTML comments that contain opening HTML tag trigger render bug

### ISSUE THREAD

**Issue by Anima-t3d** [meteor/meteor#5673] opened 2015-11-17 07:15 UTC
## Only happening in template inclusion

A HTML comment containing an opening tag of a HTML element that is not allowed in the HTML structure will trigger sanitizing.
### Expected

HTML code to be rendered as intended, not taking into account comments.
### Result

HTML code is stripped of invalid characters based on HTML code in HTML comments.
Only happens when HTML comment precedes wanted HTML content AND it contains an opening HTML tag which would break HTML validation when rendered.
### Conclusion

HTML comments containing opening elements will be attempted to be rendered. After rendering it will trigger sanitizing filters after which certain elements get removed.

Repro here: https://github.com/Anima-t3d/meteor-comment-bug

``` html
<table>
    <caption>Bugged</caption>
    <thead>
        <tr>
            <th>col 1</th>
        </tr>
    </thead>
    <tbody>
        {{#each array}}
            {{> ReproRow}}
        {{/each}}
    </tbody>
</table>

<table>
    <caption>Bugged2</caption>
    <thead>
        <tr>
            <th>col 1</th>
        </tr>
    </thead>
    <tbody>
        {{#each array}}
            {{> ReproRow2}}
        {{/each}}
    </tbody>
</table>
```

``` html
<template name="ReproRow">
<!--Will not render tr and td due to comment before code-->
    <!-- <p> -->
    <tr>
        <td><strong>Does not render tr and td</strong></td>
    </tr>
</template>

<template name="ReproRow2">
    <!--Will render tr and td BUT ALSO tbody due to comment before code containing <tbody> -->
    <!-- <tbody> -->
    <tr>
        <td><strong>Also renders tbody</strong></td>
    </tr>
</template>
```

**Comment by rdickert** [comment] 2015-11-17 23:11
Confirmed. Thanks for the detailed repro. 

We would consider accepting a PR that fixes this!

**Comment by AlbinoGeek** [comment] 2015-11-19 00:38
There is a known bug that all templates must have a "wrapper element" as their firstChild , else funky things start happening.  This seems to be a sub-issue based on that issue's side-effects.

What I mean is that the following causes random issues:

```jade
template(name='test')
  .firstDiv A first thing
  .secondDiv A second thing
  .thirdDiv A third thing
  input(type='button') Submit
```

But the following is fine:

```
template(name='test')
  .wrapper
    .firstDiv A first thing
    .secondDiv A second thing
    .thirdDiv A third thing
    input(type='button') Submit
```

An extension of this issue, is with comments being treated as the wrapping block.

```
template(name='test')
  #Raw HTML comment: <!-- This will break rendering! -->
  .wrapper
    .firstDiv A first thing
    .secondDiv A second thing
    .thirdDiv A third thing
    input(type='button') Submit
```

**Comment by AlbinoGeek** [comment] 2015-11-19 21:00
Fixed my broken sample codes.

**Comment by abernix** [comment] 2016-04-08 17:16
Spent some time debugging this today.  Narrowed it down to the `OptimizingVisitor` method in the `spacebars-compiler` optimizer.  Up until that point, the `htmljs` looks fine.  Then the optimizer just converts the whole thing to raw because `???` (and blows some stuff up? :bomb:) since it doesn't like the cut of it's jib.  Not sure why yet, but out of time for now.  Will maybe get to revisit this next week.  We'll see. :hamburger:

**Comment by hwillson** [comment] 2016-12-13 20:14
Moved over to meteor/blaze#215 - closing here. Thanks!

**Closed by hwillson** 2016-12-13 20:14 UTC
Labels: confirmed, Project:Blaze:Spacebars, pull-requests-encouraged
