### ISSUE TITLE
InstallMeteor.exe not running on Windows 8 .

### ISSUE THREAD

**Issue by ramintagizade** [meteor/meteor#9206] opened 2017-10-11 06:23 UTC
After removing meteor product key files , it runs okay . But files are corrupted . The result is :
meteor.bat
module.js:327
throw err;
^

Error: Cannot find module './_descriptors'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (C:\Users\ramin.taghizade\AppData\Local.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\core-js\modules\es6.symbol.js:5:19)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)

**Comment by TheRealNate** [comment] 2017-10-13 15:41
What exactly is happening? Does it have an error message, does nothing happen when you try to open it?

**Comment by ramintagizade** [comment] 2017-10-16 05:04
After removing meteor product key files , it runs okay . But files are corrupted . The result is : 
 meteor.bat
module.js:327
    throw err;
    ^

Error: Cannot find module './_descriptors'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\ramin.taghizade\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\core-js\modules\es6.symbol.js:5:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by benjamn** [comment] 2017-10-30 19:59
Good news! We're switching to a new Windows installer, based on [Chocolatey](https://chocolatey.org/). Can you please try the new instructions [here](https://www.meteor.com/install)?

**Comment by ramintagizade** [comment] 2017-10-31 04:43
Wow! That is a good switch to terminal in Windows. I am using Ubuntu currently , but will try it on Windows too.

**Comment by ramintagizade** [comment] 2017-10-31 09:14
Tried in Windows , but following error occured : 

Downloading meteor 64 bit
  from 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'
Progress: 97% - Saving 137.02 MB of 140.52 MB                                  E
RROR: The remote file either doesn't exist, is unauthorized, or is forbidden for
 url 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'. Except
ion calling "Read" with "3" argument(s): "Received an unexpected EOF or 0 bytes
from the transport stream."
This package is likely not broken for licensed users - see https://chocolatey.or
g/docs/features-private-cdn.
The install of meteor was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstal
l.ps1'.
 See log for details.

Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - meteor (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\mete
or\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by abernix** [comment] 2017-11-08 08:18
Your download was interrupted near the end.  This message indicates something happened with the download while it was happening:

> ```
> Progress: 97% - Saving 137.02 MB of 140.52 MB
> The remote file either doesn't exist, is unauthorized, or is forbidden for
> url 'packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'.
> Exception calling "Read" with "3" argument(s):
> "Received an unexpected EOF or 0 bytes from the transport stream."
> ```

The official download isn't corrupted, so could be a network problem.  Could you please try that again?

**Comment by ramintagizade** [comment] 2017-11-08 08:57
I tried it second time , but following was shown : 

Downloading meteor 64 bit
  from 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'
Progress: 50% - Saving 71.23 MB of 140.52 MB                                   E
RROR: The remote file either doesn't exist, is unauthorized, or is forbidden for
 url 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64'. Except
ion calling "Read" with "3" argument(s): "Received an unexpected EOF or 0 bytes
from the transport stream."
This package is likely not broken for licensed users - see https://chocolatey.or
g/docs/features-private-cdn.
The install of meteor was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstal
l.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - meteor (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\mete
or\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by abernix** [comment] 2017-11-08 09:18
For testing: Does your machine complete the download if you just download the link in your browser: https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64

**Comment by abernix** [comment] 2017-11-15 09:53
@ramintagizade Any updates on this?

**Comment by ramintagizade** [comment] 2017-11-15 10:33
I think it should download .

**Comment by abernix** [comment] 2017-11-15 10:36
I was talking about the answer to this question:

> For testing: Does your machine complete the download if you just download the link in your browser: https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64

**Comment by ramintagizade** [comment] 2017-11-15 10:38
I will check it out soon, but that should download ..

**Comment by ramintagizade** [comment] 2017-11-16 04:44
@abernix I have installed it on windows . Now what to do ?

**Comment by hwillson** [comment] 2017-11-28 20:59
The question in https://github.com/meteor/meteor/issues/9206#issuecomment-342757402 was intended to help verify that you could download the bootstrap file directly (the part that seemed to hang when using the new Chocolatey installer). If you can now download that file directly, then maybe try the Chocolatey installer again to see if it completes. Thanks!

**Comment by ramintagizade** [comment] 2017-11-29 04:42
Yeah , i think some sudden network interruption caused this .When i download that directly it also stopped and i resumed it again , but Chocolatey may be not supporting such cases .

**Comment by abernix** [comment] 2017-11-29 09:13
Our previous version of the Windows installer also suffered from this problem.  For what it's worth, Chocolatey has this on their sights: https://github.com/chocolatey/choco/issues/402.  Luckily, since Meteor updates itself (and does support resuming, in that updating process), hopefully this won't be a problem in the future.  Also, we'll continue to work toward decreasing the size of the installation bundle, thus making it even less of a problem.

I'll close this, but thanks for reporting it!  For future problems installing with Chocolatey on Windows, please file issues in the https://github.com/meteor/meteoer-chocolatey-installer repository.  Thanks!

**Closed by abernix** 2017-11-29 09:13 UTC
Labels: Project:Windows
