### ISSUE TITLE
Template destroyed callback not called

### ISSUE THREAD

**Issue by hpx7** [meteor/meteor#2793] opened 2014-10-10 05:49 UTC
Meteor version 0.9.3.1

When a template destroyed callback is initialized in an event handler, it doesn't get called when the template is removed.

Repo with steps to reproduce: https://github.com/hpx7/meteor-destroyed-not-called

This is a regression from meteor version 0.8.0

**Comment by Slava** [comment] 2015-03-03 22:00
Hi @hpx7. Thanks for a clear reproduction! I could reproduce it on version 1.0.3.2 but failed to reproduce the second part (with the uncommented line 19) on the `devel` branch.

There are a couple of things going on:

- There is an intended behavior that causes newly added "destroyed" callbacks not being called if they were added **after** the template instance was already materialized to DOM. Only the callbacks registered before the template was actually created are attached to the instance. This is not a bug.

- Secondly, there is a strange behavior with an empty callback that you registered before the moment the template is created ([line 19](https://github.com/hpx7/meteor-destroyed-not-called/blob/5b7d84590e2d96ae7ce7fdead53d75bb9803de1e/destroyed-not-called.js) in your repro). That is fixed in the new implementation of `onRendered`/`onCreated`/`onDestroyed` callbacks on devel. This is a bug but it is fixed already.

Perhaps, what you would do as a normal pattern, is to declare `onDestroyed` callbacks unconditionally and then decide what to do based on the template instance.

**Closed by Slava** 2015-03-03 22:00 UTC
Labels: Project:Blaze
