### ISSUE TITLE
[1.3] No metadata files found for isopact 

### ISSUE THREAD

**Issue by tamltn93** [meteor/meteor#6631] opened 2016-03-30 03:49 UTC
I have updated to meteor 1.3. When I run "meteor run". I have a issue:

> 
> Error: No metadata files found for isopack at: /C/Users/tle221/AppData/Local/.meteor/packages/fourse
> ven_scss/3.4.1

Please help me how to fix it ?

**Comment by Deilv** [comment] 2016-03-30 06:30
Issues with specific third-party packages should be directed to the package author.
That being said, I have no problem running the mentioned package in meteor 1.3, so did you try to remove and add the package again in case something is corrupted in your filesystem?

```
meteor remove fourseven:scss
meteor add fourseven:scss
```

**Comment by tamltn93** [comment] 2016-03-30 06:48
@Deilv I have already removed it and added it again but it not fix, the error still same as above

**Comment by logvik** [comment] 2016-03-30 08:51
I have commented in other tree about the same problem https://github.com/meteor/meteor/issues/6609#issuecomment-203327178 I have resolved it, may be it will help you...

**Comment by sebakerckhof** [comment] 2016-03-30 13:38
This seems to me like for some reason the package cache is corrupted. If you're on windows, try removing the following directory: %LOCALAPPDATA%\.meteor\packages\fourseven_scss

**Comment by abernix** [comment] 2016-07-11 12:12
@tamltn93 Could you please try to reproduce this problem with the latest version of Meteor?  You can update to it by running:

    meteor update --release 1.3.4.4

It includes a variety of fixes for Windows which will hopefully resolve this for you.

**Comment by Jabark** [comment] 2016-08-10 09:57
I had this problem today. Went to delete the package from the cache as @sebakerckhof suggested and Windows told me it couldn't because there was a file path too long! Ended up cutting and pasting it to my desktop instead which solved the issue for me. In my case, astronomer had created a bit of "node_modules" dependency-ception and Windows didn't like the long file path name, hence the error.

**Comment by Jabark** [comment] 2016-08-10 10:00
Oh and we're on Meteor version 1.3.5.1 @abernix

**Comment by abernix** [comment] 2016-09-14 07:27
Closing this as I believe the solution is to update to the latest Meteor which has a lot of updates for Windows (including updating to NPM v3 which flattens the `node_modules` structure significantly.  Additionally, deleting the `%LOCALAPPDATA%\.meteor` directory is certainly recommended before doing this upgrade (in order to clean-up old residue), however because of path length issues, you may not be able to do this with Windows Explorer (ridiculous, I know).  Consider using the [7-Zip file manager](http://www.7-zip.org/) or a NPM tool [such as `rimraf`](https://www.npmjs.com/package/rimraf) which is capable of deleting the long paths.

**Closed by abernix** 2016-09-14 07:27 UTC

**Comment by legna0616** [comment] 2016-10-06 09:15
Hi everyone , can anyone help me with this problem ? THANK YOU IN ADVANCE :)


Error: No metadata files found for isopack at: /C/Users/WINTELOGIC/AppData/Local
/.meteor/packages/coffeescript/1.0.17
   at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
   at C:\tools\packaging\tropohouse.js:521:21
   at Array.forEach (native)
   at Function._.each._.forEach (C:\Users\WINTELOGIC\AppData\Local\.meteor\pack
ages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\unders
core\underscore.js:79:11)
   at C:\tools\packaging\tropohouse.js:520:13
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at C:\tools\packaging\tropohouse.js:515:22
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at Object.download (C:\tools\packaging\tropohouse.js:427:20)
   at C:\tools\packaging\tropohouse.js:613:18
   at C:\tools\utils\buildmessage.js:572:21
   at C:\Users\WINTELOGIC\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt
-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:32:3
