### ISSUE TITLE
Spiderable on production server (docker) not working

### ISSUE THREAD

**Issue by katywings** [meteor/meteor#2429] opened 2014-08-24 17:11 UTC
**_1 Upvote**_ I found other _closed_ issues with this error code, but the solutions didn't work:
Spiderable on my meteor app works on my localhost but doesnt on my production server. So i really don't think its a problem with the subscriptions or anything of the code. And i tried it with current phantomjs of the phantomjs website and current phantomjs of npm.

I get the following error message on my production server:
spiderable: phantomjs failed: { [Error: Command failed: Can't open '/dev/stdin'
] killed: false, code: 255, signal: null } 
stderr: Can't open '/dev/stdin'

ls -alsh /dev/std*

gives following output:
0 lrwxrwxrwx 1 root root 15 Aug 24 17:11 /dev/stderr -> /proc/self/fd/2
0 lrwxrwxrwx 1 root root 15 Aug 24 17:11 /dev/stdin -> /proc/self/fd/0
0 lrwxrwxrwx 1 root root 15 Aug 24 17:11 /dev/stdout -> /proc/self/fd/1

As i said, it runs without any problems on my dev machine.

Do you have an idea?
Thanks alot!

**Comment by katywings** [comment] 2015-01-27 17:08
Hey hey ^^
Is this problem fixed now in the current version?

Its doesnt really look like...

P.S. aaronjudd: thx a lot for your fix! What would i do if you werent there? ;)

**Comment by katywings** [comment] 2015-02-04 21:54
Okay a little addition to this problem:
Using the https://atmospherejs.com/gadicohen/phantomjs
Package directly, this issue doesnt seem to make troubles!

**Comment by arunoda** [comment] 2015-05-10 11:26
@glasser Are you guys working on a fix.
Happen to me as well. 
We are moving Meteor Up to Docker and this will affect a lot of apps. 
I can ask them to install `ongoworks:spiderable` (Which works. Thanks!)
But, better if this can be implemented in the core)

**Comment by glasser** [comment] 2015-05-11 18:13
Well, this issue doesn't have a clear reproduction, so it would be a fair amount of work to even figure out if it's fixed yet or not.

**Comment by epeng5** [comment] 2015-05-25 17:47
@aaronjudd I'm running into this issue on modulus. Any idea if your ongoworks package will work there?

This is the error I get on modulus, which seems to only appear when I scale up servos.

spiderable: phantomjs failed: Error: Command failed: Can't open '/dev/stdin'
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12) 
stderr: Can't open '/dev/stdin'

Anyone run into similar issue on modulus or have ideas on how to resolve?

**Comment by aaronjudd** [comment] 2015-05-27 01:10
@epeng5 I've only tested it inside of docker with the ubuntu image.  I'd prefer to think of our package as short term solution, so your mileage may vary.

**Comment by epeng5** [comment] 2015-05-27 02:55
@aaronjudd I gave it a shot and it works! Thanks so much!

**Comment by arunoda** [comment] 2015-05-27 06:06
@glasser try running a meteor app inside a docker container with phantomjs installed.

We can't give a reproducible code this since this is infrastructure issue.
But there is a clear steps reproduce this issue.

* Deploy a meteor app inside a container
* easiest way to use Mupx: https://github.com/arunoda/meteor-up/tree/mupx#
* Or otherwise use meteord: https://github.com/meteorhacks/meteord

I hope Galaxy's meteor docker base image might have phantomjs installed.
If so, don't you guys see this issue?

**Comment by BradRyan** [comment] 2015-07-07 23:07
I have similar errors.  When checking my dev/std file, I notice I'm missing "/proc/self/" as a prefix to fd/x... I'm not sure if that is actually my issue.

```
ls -alsh /dev/std*
0 lr-xr-xr-x  1 root  wheel     0B Jun 22 14:41 /dev/stderr -> fd/2
0 lr-xr-xr-x  1 root  wheel     0B Jun 22 14:41 /dev/stdin -> fd/0
0 lr-xr-xr-x  1 root  wheel     0B Jun 22 14:41 /dev/stdout -> fd/1
```

I also don't have the issue locally, but when deployed on Modulus.  I was able to use ```ongoworks:spiderable``` package and things worked for the most part.  Still curious why spiderable is having a problem.  If it looks like it has something to do with with my /dev/stidin file I'd appreciate getting pointed in the right direction on how to fix it.

Here is my error on my Modulus log when including '?escaped_fragment=' in my application URL using ```spiderable``` and ```dfischer:phantomjs``` packages.
```
spiderable: phantomjs failed: { [Error: Command failed: Can't open '/dev/stdin'
] killed: false, code: 255, signal: null } 
stderr: Can't open '/dev/stdin'

Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
    at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
    at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
    at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
    at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
    at Object.router (packages/iron:router/lib/router.js:15:1)
    at next (/mnt/app/node_modules/connect/lib/proto.js:190:15)
    at packages/spiderable/spiderable_server.js:123:1
    at ChildProcess.exithandler (child_process.js:652:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

**Comment by sungwoncho** [comment] 2015-07-12 23:27
@aaronjudd's fix worked for me. Using phantomjs 1.9.8.

**Comment by OminStyle** [comment] 2015-07-17 17:33
Any updates on this? I am using ```dfischer:phantomjs``` and ```ongoworks:spiderable``` on Modulus.io but no luck.
```
spiderable: phantomjs failed: Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5) 
stderr: 
```

**Comment by daslicht** [comment] 2015-07-25 08:34
anyone tried this: https://github.com/meteorhacks/meteord#spiderable-not-working-but-have-a-fix

**Comment by chrisbutler** [comment] 2015-08-03 18:11
@aaronjudd ongoworks:spiderable worked for me with the latest version of mupx

**Comment by stevenhornung** [comment] 2015-09-04 21:19
@OminStyle did you find a workaround here or are you still experiencing issues? We are also using <code>dfischer:phantomjs</code> and <code>ongoworks:spiderable</code> on Modulus with the same error.  The error output is the good ole' <code>Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.</code> Would love any help here since this is still a big problem for us!

**Comment by OminStyle** [comment] 2015-09-11 07:15
@stevenhornung It took a while for me to figure out because the error wasn't very descriptive but Materialize package was causing the error for me.
https://github.com/Dogfalo/materialize/issues/1805

**Comment by mymedicalshopper** [comment] 2015-09-11 21:24
If I use ongoworks:spiderable, then the /dev/stdin issues goes away. However, I then have the SSL handshake error. 

If I use gentlenode:spiderable-ssl, then SSL issue goes away, but then I have the /dev/stdin issue. 

I can't seem to figure out how to eliminate the /dev/stdin issue and the SSL issue *at the same time*. I've looked everywhere, but it seems everything I see fixes one problem or the other, but not both.

I'm using Meteor Up X for my deployments. Any help would be appreciated!

**Comment by katywings** [comment] 2015-09-11 21:49
Did you try out lufrai:spiderable2?

**Comment by jstoeffler** [comment] 2015-09-16 09:02
@mymedicalshopper what do you mean by 

> the SSL handshake error

?

I just installed ongoworks:spiderable on a modulus server, and it works like a charm.

**Comment by mymedicalshopper** [comment] 2015-09-16 13:05
@jstoeffler I recant my earlier statement as ongoworks:spiderable using MupX does indeed work without issue now using https. I tried many different combinations of packages and code tweaks before, so it's possible I removed something that was formerly causing it to not work before, but all seems to be working great now, which is awesome!

**Comment by ciclopes** [comment] 2016-02-28 20:58
+1

I was having the same issue locally on Ubuntu 14.04.
@aaronjudd solution solved the issue (TY Aaron!).

**Comment by mhlavacka** [comment] 2016-04-08 02:31
@arunoda ongoworks:spiderable worked great, thanks! It seems to decrease my production memory consumption by around 100.000 KiB

**Comment by abernix** [comment] 2016-12-14 16:33
Closing as I'm confident this works if using `ongoworks:spiderable` with common Docker+Meteor deployment configurations.

**Closed by abernix** 2016-12-14 16:33 UTC
Labels: Project:Webapp:Spiderable

**Comment by davinderkumar** [comment] 2017-07-05 03:41
I'm getting the same issue with Meteor 1.5/mup-docker/Ubuntu 16 even after installing ongoworks:spiderable package. Error is being thrown by default spiderable package ( packages/spiderable.js). I have installed phantomjs on server as well but it is still there.
Do I need to disable the default package? How?

> spiderable: phantomjs failed: null 
stderr: 
spiderable: phantomjs failed at http://www.myaddresspin.com/robots.txt: { [Error: Command failed: /usr/bin/env bash -c exec phantomjs  --load-images=no --ssl-protocol=TLSv1 /dev/stdin <<'END'
var url = "http://www.myaddresspin.com/robots.txt";// 'url' is assigned to in a statement before this.
var page = require('webpage').create();

>var isReady = function () {
  return page.evaluate(function () {
    if (typeof Meteor === 'undefined'
        || Meteor.status === undefined
        || !Meteor.status().connected) {
      return false;
    }
    if (typeof Package === 'undefined'
        || Package.spiderable === undefined
        || Package.spiderable.Spiderable === undefined) {
      return false;
    }
    return Package.spiderable.Spiderable.isReady();
  });
};

> var dumpPageContent = function () {
  var out = page.content;
  out = out.replace(/<script[^>]+>(.|\n|\r)*?<\/script\s*>/ig, '');
  out = out.replace('<meta name="fragment" content="!">', '');
  console.log(out);
};

> page.open(url, function(status) {
  if (status === 'fail')
    phantom.exit();
});

> setInterval(function() {
  if (isReady()) {
    dumpPageContent();
    phantom.exit();
  }
}, 100);
END

> Can't open '/dev/stdin'
]
  killed: false,
  code: 255,
  signal: null,
  cmd: '/usr/bin/env bash -c exec phantomjs  --load-images=no --ssl-protocol=TLSv1 /dev/stdin <<\'END\'\nvar url = "http://www.myaddresspin.com/robots.txt";// \'url\' is assigned to in a statement before this.\nvar page = require(\'webpage\').create();\n\nvar isReady = function () {\n  return page.evaluate(function () {\n    if (typeof Meteor === \'undefined\'\n        || Meteor.status === undefined\n        || !Meteor.status().connected) {\n      return false;\n    }\n    if (typeof Package === \'undefined\'\n        || Package.spiderable === undefined\n        || Package.spiderable.Spiderable === undefined) {\n      return false;\n    }\n    return Package.spiderable.Spiderable.isReady();\n  });\n};\n\nvar dumpPageContent = function () {\n  var out = page.content;\n  out = out.replace(/<script[^>]+>(.|\\n|\\r)*?<\\/script\\s*>/ig, \'\');\n  out = out.replace(\'<meta name="fragment" content="!">\', \'\');\n  console.log(out);\n};\n\npage.open(url, function(status) {\n  if (status === \'fail\')\n    phantom.exit();\n});\n\nsetInterval(function() {\n  if (isReady()) {\n    dumpPageContent();\n    phantom.exit();\n  }\n}, 100);\nEND\n' } 
stderr: Can't open '/dev/stdin'
 
> stdout: 
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor.js:1075:11)
    at [object Object]._.extend.get (packages/meteor.js:1087:12)
    at [object Object].RouteController.lookupOption (packages/iron_router.js:143:29)
    at new Controller.extend.constructor (packages/iron_router.js:103:21)
    at [object Object].ctor (packages/iron_core.js:144:17)
    at Function.Router.createController (packages/iron_router.js:810:18)
    at Function.Router.dispatch (packages/iron_router.js:1335:25)
    at Object.router (packages/iron_router.js:624:12)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
    at packages/spiderable.js:171:11

**Comment by dr-dimitru** [comment] 2017-10-14 04:28
Lately, we have seen a lot of fails on our phantomjs setup due to ES6 features (*perhaps some NPM packages have ES6 syntax and it's not transpiled into ES5 by Meteor*).

Solved by moving to [prerendering service](https://ostr.io/info/prerendering) with ES6 support.
Hope this will help to someone else who has run into the same issue.
