### ISSUE TITLE
meteor install fail on OSX 10.11.4

### ISSUE THREAD

**Issue by gitlinming** [meteor/meteor#7045] opened 2016-05-13 04:13 UTC
I am trying to install meteor using the command:
`curl https://install.meteor.com/ | sh`
I am getting the below error in every try:
```
curl: (18) transfer closed with 161356020 bytes remaining to read
.meteor/package-metadata/v2.0.1/packages.data.db: (Empty error message)
tar: Error exit delayed from previous errors.
Installation failed.
```

**Comment by HIKALU-Z** [comment] 2016-05-13 04:20
I also meet This question！

**Comment by gitlinming** [comment] 2016-05-13 09:20
This issue is the same as#6960, the issue may cause by CDN(i currently in China).
i download the web page of _https://install.meteor.com/_ on bower and save as install.sh.
open install.sh and change the
`TARBALL_URL="https://static-meteor.netdna-ssl.com/packages-bootstrap/${RELEASE}/meteor-bootstrap-${PLATFORM}.tar.gz"`
into
`TARBALL_URL="https://d3sqy0vbqsdhku.cloudfront.net/packages-bootstrap/1.3.2.4/meteor-bootstrap-os.osx.x86_64.tar.gz"`
save install.sh and run it in terminal.
it work perfectly.

**Comment by HIKALU-Z** [comment] 2016-05-13 10:04
hello
can i ask a question .
how to run install.sh in terminal

**Comment by HIKALU-Z** [comment] 2016-05-13 10:07
i am also in China 
can i have your weChat?
18309717375,it's Mine.hope be a friend with you

**Comment by abernix** [comment] 2016-05-13 10:36
Closing this as a duplicate of #6960.  I will reopen that issue.

**Please help us debug!**  Will you please post the contents of http://debug.netdna-cdn.com and http://checkip.amazonaws.com into that issue, if you don't mind?

**Manual Instruction**
Also, see my instructions to download manually [in this comment](https://github.com/meteor/meteor/issues/6960#issuecomment-216478633) and then my instructions for installing it [in this comment](https://github.com/meteor/meteor/issues/6960#issuecomment-216485324).

Sorry about this, folks!

**Closed by abernix** 2016-05-13 10:36 UTC

**Comment by adibhanna** [comment] 2016-05-21 17:17
@HIKALU-Z you do ```sh install.sh```
