### ISSUE TITLE
My async/await calls to Stripe stopped working in Meteor 1.4.2.2

### ISSUE THREAD

**Issue by adamgins** [meteor/meteor#8064] opened 2016-11-16 21:08 UTC
I am using Meteor 1.4.2.2

In Meteor 1.3.x (and earlier releases) I successfully had async/await calls to Stripe.

For example, a Meteor server side method:

```
 'someMethod': async function (someParams) {
```

Then, inside the method I'd have a call to Stripe API and wait for the result:

```
 var someResult = await Stripe.subscriptions.retrieve(inputParams);
```

Previously I would successfully get the result of the call in `someResult`, now I just get `undefined`.

BTW, the call to Stripe exists and if I put a callback I can see results.

I tried moving my code into a `try catch`... no improvement

I do see some similar issues like https://github.com/meteor/meteor/issues/7662 and seemed like it may have been fixed in `1.4.2.2` release but after my recent test, I still have the issue. 

Any workarounds appreciated too. I see a bunch of options in articles like https://www.okgrow.com/posts/writing-asynchronous-code-in-meteor-and-javascript but keen to know why this is not working now. 

thanks for the help

My packages are:

```
accounts-facebook                        1.0.11  Login service for Facebook a...
accounts-google                          1.0.11  Login service for Google acc...
accounts-password                        1.3.3  Password support for accounts
accounts-twitter                         1.1.12  Login service for Twitter ac...
adamgins:microsoft-oauth                 0.0.2+ Login with hotmail etc
alisalaah:hogan                          1.0.1  Hogan templating from Twitter...
barbatus:stars-rating                    1.1.1  Stars rating control
blaze-html-templates                     1.0.5  Compile HTML templates into r...
boilerplate-generator                    1.0.11  Generates the boilerplate ht...
bozhao:accounts-instagram                0.2.2  Instagram account login for m...
browser-policy                           1.0.9  Configure security policies e...
buzzy-buzz:avatar                        0.9.2+ Consolidated user avatar temp...
buzzy-buzz:common-globals                0.1.3+
buzzy-buzz:resources-core                0.1.5+
check                                    1.2.4  Check whether a value matches...
copleykj:jquery-autosize                 1.17.8  Automatically adjust textare...
cordova:cordova-custom-config            2.0.3
cordova:cordova-plugin-calendar          4.4.7
cordova:cordova-plugin-compat            1.0.0
cordova:cordova-plugin-contacts          2.2.0
cordova:cordova-plugin-device            1.1.3
cordova:cordova-plugin-file              4.3.0
cordova:cordova-plugin-geolocation       2.4.0
cordova:cordova-plugin-splashscreen      4.0.0
cordova:cordova-plugin-statusbar         2.2.0
cordova:cordova-plugin-wkwebview-engine  1.1.0
cosmos:browserify                        0.10.0  Bundle NPM modules for clien...
crosswalk                                1.7.0  Makes your Cordova applicatio...
dburles:google-maps                      1.1.5  Google Maps Javascript API v3
dispatch:deep-link                       4.0.4  Handle deep linked data
djedi:sanitize-html                      1.11.3  Wrapper for punkave's Saniti...
ecmascript                               0.6.1  Compiler plugin that supports...
ejson                                    1.0.13  Extended and Extensible JSON...
email                                    1.1.18  Send email messages
fastclick                                1.0.13  Faster touch events on mobile
force-ssl                                1.0.13  Require this application to ...
fortawesome:fontawesome                  4.6.3* Font Awesome (official): 500+...
froala:editor-reactive                   2.3.5  A Meteor reactive template wr...
froatsnook:request                       2.74.0  A Simplified HTTP client whi...
harrison:papa-parse                      1.1.1  A powerful, in-browser CSV pa...
http                                     1.2.10  Make HTTP calls to remote se...
huttonr:bootstrap3                       3.3.6_13  Modular, customizable Boot...
iron:router                              1.0.13  Routing specifically designe...
jamielob:reloader                        1.2.3  More control over hot code pu...
jeremy:selectize                         0.12.1_5  Selectize is a hybrid of a...
johnantoni:meteor-appear                 0.0.2  jQuery plugin for tracking el...
jparker:crypto-hmac                      0.1.0  HMAC function for CryptoJS, s...
jparker:crypto-sha256                    0.1.1  SHA256 algo for CryptoJS, sta...
jquery                                   1.11.10  Manipulate the DOM using CS...
konecty:autolinker                       1.0.3  Autolinker.js packaged for Me...
less                                     2.7.8  Leaner CSS language
linto:jquery-ui                          1.11.2  jquery-ui 1.11.2 re-packaged...
logging                                  1.1.16  Logging facility.
lukemadera:social-share                  1.2.0  Cross platform (inc. Cordova)...
manuelschoebel:cheerio                   0.0.1  cheerio wrapped for meteor
maxharris9:connection-banner             0.5.0  A banner that displays when m...
mdg:geolocation                          1.3.0  Provides reactive geolocation...
meteor-base                              1.0.4  Packages that every Meteor ap...
meteorhacks:aggregate                    1.3.0  Proper MongoDB aggregations s...
meteorhacks:inject-initial               1.0.4  Allow injection of arbitrary ...
meteorhacks:kadira                       2.30.2  Performance Monitoring for M...
meteorhacks:subs-manager                 1.6.4  Subscriptions Manager for Meteor
meteorhacks:unblock                      1.1.0  a way to use this.unblock ins...
mizzao:timesync                          0.4.0  NTP-style time synchronizatio...
mobile-experience                        1.0.4  Packages for a great mobile u...
modules                                  0.7.7  CommonJS module system
momentjs:moment                          2.15.1* Moment.js (official): parse,...
mongo                                    1.1.14  Adaptor for using MongoDB an...
mquandalle:ismobile                      0.1.0  Add a Meteor.isMobile boolean...
mrt:twilio-meteor                        1.1.0  Twilio API Wrapper for Meteor
mrt:twit                                 0.2.0  Twitter API Client
natestrauser:filepicker-plus             2.0.0  filepicker script packaged fo...
npm-container                            1.2.0+ Contains all your npm depende...
oauth2                                   1.1.11  Common code for OAuth2-based...
okgrow:analytics                         2.0.0  Complete Google Analytics, Mi...
okgrow:router-autoscroll                 0.1.8  Smart management of scroll po...
peerlibrary:aws-sdk                      2.4.9_1  SDK for AWS services includ...
peppelg:bootstrap-3-modal                1.0.4  Simple usage of bootstrap 3 m...
percolate:google-api                     1.0.3  A Meteor library to interact ...
pfafman:filesaver                        1.3.2  filesaver.js packaged for use...
raix:handlebar-helpers                   0.2.5  Handlebar helpers
raix:ui-dropped-event                    0.0.7  Add dropped event to Meteor U...
random                                   1.0.10  Random number generator and ...
reactive-var                             1.0.11  Reactive variable
reload                                   1.1.11  Reload the page while preser...
reywood:publish-composite                1.4.2  Publish a set of related docu...
richsilv:owl-carousel                    0.1.0  Touch enabled jQuery plugin t...
risul:moment-timezone                    0.5.0_5* Timezone support for moment...
sacha:spin                               2.3.1  Simple spinner package for Me...
service-configuration                    1.0.11  Manage the configuration for...
session                                  1.1.7  Session variable
shell-server                             0.2.1  Server-side component of the ...
simple:reactive-method                   1.0.2  Call methods synchronously in...
spacebars                                1.0.13  Handlebars-like template lan...
standard-minifier-css                    1.3.2  Standard css minifier used wi...
standard-minifier-js                     1.2.1  Standard javascript minifiers...
tracker                                  1.1.1  Dependency tracker to allow r...
tsega:bootstrap3-datetimepicker          4.17.37_1  Bootstrap 3 DateTime pick...
underscore                               1.0.10  Collection of small helpers:...
webapp                                   1.3.12  Serves a Meteor app over HTTP


* New versions of these packages are available! Run 'meteor update' to try to
  update those packages to their latest versions. If your packages cannot be
  updated further, try typing `meteor add <package>@<newVersion>` to see more
  information.

+ These packages are built locally from source.

```

**Comment by benjamn** [comment] 2016-11-16 22:26
Since I don't see `babel-runtime` in that list, I wonder if you're missing [this code](https://github.com/meteor/meteor/blob/3a54bb73f153901cc3650603134e1cee15c1f5e9/packages/babel-runtime/babel-runtime.js#L24-L34)?

Is `babel-runtime` in your `.meteor/versions` file? If so, what version? If not, what happens if you do `meteor add babel-runtime`?

**Comment by benjamn** [comment] 2016-11-16 22:28
You might also try changing `await Stripe.subscriptions.retrieve(inputParams)` to `Stripe.subscriptions.retrieve(inputParams).await()`. Both should work, but the second will only work if Stripe is using the same global `Promise` class as Meteor.

**Comment by adamgins** [comment] 2016-11-16 23:33
@benjamn thanks a couple of issues:

I just copied my old 1.4.2.1 , ran  updated to 1.4.2.2, ran `meteor add babel-runtime` (so it's now in the package file) and changed the `await`s to .await()

and now when I try and run Meteor I see 

```
node.js:436
        callback();
        ^

Error: ENFILE: file table overflow, scandir '/Users/adamginsburg/Documents/development/buzzy7/node_modules/jquery/src/queue'
  at Error (native)
  at Object.fs.readdirSync (fs.js:808:18)
  at Object.wrapper (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_2.1omixl5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:1490:34)
  at readDirectory (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_2.1omixl5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:291:26)
  at Watcher._fireIfDirectoryChanged (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_2.1omixl5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:436:23)
  at /Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_2.1omixl5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:682:12
  at Array.forEach (native)
  at Function._.each._.forEach (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_2.1omixl5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Watcher._checkDirectories (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_2.1omixl5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:671:7)
  at new Watcher (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_2.1omixl5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:385:10)
  at AppRunner._runOnce (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_2.1omixl5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js:832:23)
  at AppRunner._fiber (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_2.1omixl5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js:933:28)
  at /Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_2.1omixl5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js:451:12

```

yes Babel-runtime is in versions file:

```
accounts-base@1.2.14
accounts-facebook@1.0.11
accounts-google@1.0.11
accounts-oauth@1.1.14
accounts-password@1.3.3
accounts-twitter@1.1.12
adamgins:microsoft-oauth@0.0.2
alisalaah:hogan@1.0.1
allow-deny@1.0.5
autoupdate@1.3.12
babel-compiler@6.13.0
babel-runtime@1.0.1
barbatus:stars-rating@1.1.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.1.9
blaze-html-templates@1.0.5
blaze-tools@1.0.10
boilerplate-generator@1.0.11
bozhao:accounts-instagram@0.2.2
browser-policy@1.0.9
browser-policy-common@1.0.11
browser-policy-content@1.0.12
browser-policy-framing@1.0.12
buzzy-buzz:avatar@0.9.2
buzzy-buzz:common-globals@0.1.3
buzzy-buzz:resources-core@0.1.5
caching-compiler@1.1.9
caching-html-compiler@1.0.7
callback-hook@1.0.10
check@1.2.4
coffeescript@1.0.17
copleykj:jquery-autosize@1.17.8
cosmos:browserify@0.10.0
crosswalk@1.7.0
dburles:google-maps@1.1.5
ddp@1.2.5
ddp-client@1.3.2
ddp-common@1.2.7
ddp-rate-limiter@1.0.6
ddp-server@1.3.11
deps@1.0.12
diff-sequence@1.0.7
dispatch:deep-link@4.0.4
djedi:sanitize-html@1.11.3
ecmascript@0.6.1
ecmascript-runtime@0.3.15
ejson@1.0.13
email@1.1.18
es5-shim@4.6.15
facebook@1.2.10
fastclick@1.0.13
force-ssl@1.0.13
fortawesome:fontawesome@4.6.3
froala:editor@2.3.5
froala:editor-reactive@2.3.5
froatsnook:request@2.74.0
geojson-utils@1.0.10
google@1.1.15
handlebars@1.0.7
harrison:papa-parse@1.1.1
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.10
huttonr:bootstrap3@3.3.6_13
huttonr:bootstrap3-assets@3.3.6_3
id-map@1.0.9
iron:controller@1.0.12
iron:core@1.0.11
iron:dynamic-template@1.0.12
iron:layout@1.0.12
iron:location@1.0.11
iron:middleware-stack@1.1.0
iron:router@1.0.13
iron:url@1.0.11
jamielob:reloader@1.2.3
jeremy:selectize@0.12.1_5
johnantoni:meteor-appear@0.0.2
jparker:crypto-core@0.1.0
jparker:crypto-hmac@0.1.0
jparker:crypto-md5@0.1.1
jparker:crypto-sha256@0.1.1
jparker:gravatar@0.5.1
jquery@1.11.10
konecty:autolinker@1.0.3
launch-screen@1.1.0
less@2.7.8
linto:jquery-ui@1.11.2
livedata@1.0.18
localstorage@1.0.12
logging@1.1.16
lookback:emails@0.7.5
lukemadera:social-share@1.2.0
manuelschoebel:cheerio@0.0.1
maxharris9:connection-banner@0.5.0
mdg:geolocation@1.3.0
meteor@1.6.0
meteor-base@1.0.4
meteorhacks:aggregate@1.3.0
meteorhacks:async@1.0.0
meteorhacks:collection-utils@1.2.0
meteorhacks:inject-initial@1.0.4
meteorhacks:kadira@2.30.2
meteorhacks:meteorx@1.4.1
meteorhacks:npm@1.5.0
meteorhacks:picker@1.0.3
meteorhacks:ssr@2.2.0
meteorhacks:subs-manager@1.6.4
meteorhacks:unblock@1.1.0
minifier-css@1.2.15
minifier-js@1.2.15
minimongo@1.1.0-ddp-batching-beta.0
mizzao:timesync@0.4.0
mobile-experience@1.0.4
mobile-status-bar@1.0.13
modules@0.7.7
modules-runtime@0.7.7
momentjs:moment@2.15.1
mongo@1.1.14
mongo-id@1.0.6
mongo-livedata@1.0.12
mquandalle:ismobile@0.1.0
mrt:q@1.0.1
mrt:twilio-meteor@1.1.0
mrt:twit@0.2.0
natestrauser:filepicker-plus@2.0.0
npm-bcrypt@0.9.2
npm-container@1.2.0
npm-mongo@2.2.11_2
oauth@1.1.12
oauth1@1.1.11
oauth2@1.1.11
observe-sequence@1.0.14
okgrow:analytics@2.0.0
okgrow:router-autoscroll@0.1.8
ordered-dict@1.0.9
peerlibrary:aws-sdk@2.4.9_1
peerlibrary:blocking@0.5.2
peppelg:bootstrap-3-modal@1.0.4
percolate:google-api@1.0.3
pfafman:filesaver@1.3.2
promise@0.8.8
raix:eventemitter@0.1.3
raix:eventstate@0.0.4
raix:handlebar-helpers@0.2.5
raix:push@3.1.0-pre.1
raix:ui-dropped-event@0.0.7
random@1.0.10
rate-limit@1.0.6
reactive-dict@1.1.8
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
reywood:publish-composite@1.4.2
richsilv:owl-carousel@0.1.0
risul:moment-timezone@0.5.0_5
routepolicy@1.0.12
sacha:juice@0.1.4
sacha:spin@2.3.1
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.2.1
simple:reactive-method@1.0.2
spacebars@1.0.13
spacebars-compiler@1.0.13
srp@1.0.10
standard-minifier-css@1.3.2
standard-minifier-js@1.2.1
templating@1.2.15
templating-compiler@1.2.15
templating-runtime@1.2.15
templating-tools@1.0.5
tracker@1.1.1
tsega:bootstrap3-datetimepicker@4.17.37_1
twitter@1.1.13
ui@1.0.12
underscore@1.0.10
url@1.0.11
webapp@1.3.12
webapp-hashing@1.0.9

```

**Comment by adamgins** [comment] 2016-11-16 23:49
@benjamn mmm... I seem to have "borked" my project. Even if I go back to 1.4.2.1 version ti Get this error...

```
Error: ENFILE: file table overflow, scandir '/Users/adamginsburg/Documents/development/buzzy7/node_modules/babel-runtime/core-js/reflect'
  at Error (native)
  at Object.fs.readdirSync (fs.js:808:18)
  at Object.wrapper (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_1.6ev1ni++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:1488:34)
  at readDirectory (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_1.6ev1ni++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:291:26)
  at Watcher._fireIfDirectoryChanged (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_1.6ev1ni++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:436:23)
  at /Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_1.6ev1ni++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:682:12
  at Array.forEach (native)
  at Function._.each._.forEach (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_1.6ev1ni++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Watcher._checkDirectories (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_1.6ev1ni++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:671:7)
  at new Watcher (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_1.6ev1ni++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:385:10)
  at AppRunner._runOnce (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_1.6ev1ni++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js:832:23)
  at AppRunner._fiber (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_1.6ev1ni++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js:933:28)
  at /Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.2_1.6ev1ni++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js:451:12

```

**Comment by benjamn** [comment] 2016-11-16 23:50
For the `ENFILE` problem, try this?
```sh
METEOR_DISABLE_FS_FIBERS=false meteor run
```
That will reenable async FS operations, and possibly avoid the immediate problem?

**Comment by benjamn** [comment] 2016-11-16 23:52
Since I can't reproduce this in a basic Meteor app, I'm guessing that Stripe uses its own `Promise` implementation, and that somehow interferes with the expected behavior.

Whenever you can get the app to start again, try this:
```js
var someResult = await Promise.resolve(Stripe.subscriptions.retrieve(inputParams));
```
My hunch is that this will convert the Stripe `Promise` to a Meteor `Promise`, which might make a difference. To be clear, both should work; I'm just trying to track down the problem.

**Comment by adamgins** [comment] 2016-11-17 00:23
@benjamn thanks, still getting the following issue:

I tried `var someResult = await Promise.resolve(Stripe.subscriptions.retrieve(inputParams));`

```
I20161117-11:22:52.127(11)? Exception while invoking method 'updateSingleSubscription' TypeError: Cannot read property 'id' of undefined
I20161117-11:22:52.128(11)?     at [object Object].updateSingleSubscription$ (server/methods/stripe.js:577:70)
I20161117-11:22:52.128(11)?     at tryCatch (/Users/adamginsburg/.meteor/packages/babel-runtime/.0.1.12.18cf7wg++os+web.browser+web.cordova/npm/node_modules/regenerator-runtime/runtime.js:62:40)
I20161117-11:22:52.130(11)?     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/adamginsburg/.meteor/packages/babel-runtime/.0.1.12.18cf7wg++os+web.browser+web.cordova/npm/node_modules/regenerator-runtime/runtime.js:336:22)
I20161117-11:22:52.130(11)?     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/adamginsburg/.meteor/packages/babel-runtime/.0.1.12.18cf7wg++os+web.browser+web.cordova/npm/node_modules/regenerator-runtime/runtime.js:95:21)
I20161117-11:22:52.131(11)?     at tryCatch (/Users/adamginsburg/.meteor/packages/babel-runtime/.0.1.12.18cf7wg++os+web.browser+web.cordova/npm/node_modules/regenerator-runtime/runtime.js:62:40)
I20161117-11:22:52.133(11)?     at invoke (/Users/adamginsburg/.meteor/packages/babel-runtime/.0.1.12.18cf7wg++os+web.browser+web.cordova/npm/node_modules/regenerator-runtime/runtime.js:138:20)
I20161117-11:22:52.133(11)?     at /Users/adamginsburg/.meteor/packages/babel-runtime/.0.1.12.18cf7wg++os+web.browser+web.cordova/npm/node_modules/regenerator-runtime/runtime.js:146:13
I20161117-11:22:52.134(11)?     at /Users/adamginsburg/.meteor/packages/promise/.0.8.8.kh910r++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:32:39

```

**Comment by adamgins** [comment] 2016-11-17 00:59
BTW< just checking did I have to `meteor add promise` to make this work?

**Comment by Type1J** [comment] 2016-11-17 13:09
@adamgins Have you seen this: http://benjamn.github.io/goto2015-talk/#/ ?

There's a package at https://github.com/meteor/promise that enables you to use promises with a slightly different syntax, but it works well with Meteor's fibers on the server side.

**Comment by adamgins** [comment] 2016-11-17 18:34
Yes thanks. It's just that async/await was working in 1.3 and stopped in 1,4.x

**Comment by benjamn** [comment] 2016-11-17 18:38
> just checking did I have to `meteor add promise` to make this work?

No, `ecmascript` [implies `promise`](https://github.com/meteor/meteor/blob/3a54bb73f153901cc3650603134e1cee15c1f5e9/packages/ecmascript/package.js#L23) already, so you're already using https://github.com/meteor/promise as @Type1J recommended!

**Comment by benjamn** [comment] 2016-11-17 18:40
@adamgins Just as a sanity check, can you tap the Stripe promise to make sure it's resolving to the value you're expecting?
```js
var someResult = await Stripe.subscriptions.retrieve(inputParams).then(result => {
  console.log("Stripe result:", result);
  return result;
});
```

**Comment by adamgins** [comment] 2016-11-17 19:18
Thanks. 

Phew kinda stuck between rock and hard place without async/await as have a complex set of actions that are really hard to implement using 'thenables'.  

Any more ideas on what changed between 1.3 and 1.4 to break this?

**Comment by benjamn** [comment] 2016-11-17 19:27
It's hard to say without a reproduction, but it's possible nothing changed/regressed on the Meteor side, and this problem was triggered by something changing in the Stripe API during that time period.

**Comment by benjamn** [comment] 2016-11-17 19:31
[This recent commit](https://github.com/stripe/stripe-node/commit/9c5f01d96487e15b0ebee37630f89c7b9fb7c612) is somewhat suspicious. What happens if you `meteor npm install --save stripe@4.9.1`?

**Comment by adamgins** [comment] 2016-11-17 23:46
@benjamn YES!!!! Rolling back fixes the issue, which I am hoping I can use as a stop gap (if it does not break Stripe) Thanks!!! 

So now I need to work out how how we bridge this gap
https://github.com/stripe/stripe-node/issues/284#issuecomment-261345030
@brandur any thoughts here, please? (not even sure if cross issue/repo tagging will work here?(I will post in stripe too.

**Comment by adamgins** [comment] 2016-11-28 23:19
@benjamn please see @brandur 's comments https://github.com/stripe/stripe-node/issues/284#issuecomment-263340466 

Stripe is a pretty major player for developers looking to take payments and the NodeJS library is a key component. 

Is there anyway to resolve this pls as I fear staying on an older Stripe package is going to be an issue. 

I can't believe I'd be the only Meteor developer hitting this issue. await/async really simplifies the code and using the older `thenable` approach would be a complete nightmare. 

Please See https://github.com/stripe/stripe-node/pull/260

Any thoughts on how we could support this library.

**Comment by abernix** [comment] 2016-12-27 12:36
@adamgins Yes, Stripe is certainly a "household name" at this point but to my knowledge many Meteor users are using it.

Someone would be happy to look at this issue further but please provide a simple reproduction per the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines.  Building reproductions takes time and if the users who are experiencing the problems can provide the reproductions, it makes it easier to get to the bottom of the problem, and ensures that any fix is the most relevant for your issue.

In a case like, this it's obviously fine to expect someone to provide their own Stripe credentials, but please provide the rest of the reproduction as concisely as possible.

Thanks!

**Comment by hwillson** [comment] 2017-02-22 15:37
Hi @adamgins - as requested in https://github.com/meteor/meteor/issues/8064#issuecomment-269320514, when you have a chance could you please supply a runnable (and concise) reproduction showing this issue (with your credentials left out of course)? This will greatly help with troubleshooting. For now though, since Stripe is being used across countless Meteor apps and there hasn't been any additional +1's on this issue, I'll close it for now. If you're able to supply a reproduction I'll be happy to re-open this issue. Thanks for reporting this originally!

**Closed by hwillson** 2017-02-22 15:37 UTC
