### ISSUE TITLE
Path for a package too long, deploy fails

### ISSUE THREAD

**Issue by AndreasGalster** [meteor/meteor#4782] opened 2015-07-21 15:10 UTC
My meteor deploy failed because I have a path that's too long for the prerender package.

PS C:\Users\Andreas Galster\Desktop\PigmentsIO\_development> meteor deploy pigments2.meteor.com --settings settings.json
Deploying to pigments2.meteor.com.

C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\files.js:748
        throw new Error("Path too long: " + entry.path + " is " +
              ^
Error: Path too long: C:\Users\Andreas Galster\Desktop\PigmentsIO\_development\.meteor\local\build_tar\bundle\programs\server\npm\dfischer_prerenderio
\node_modules\prerender-node\node_modules\request\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\.gitignore is 268 ch
aracters.
    at FileReader.fstream.Reader.filter (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fi
les.js:748:15)
    at statCb (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstrea
m\lib\reader.js:193:22)
    at Object.oncomplete (evalmachine.<anonymous>:108:15)
PS C:\Users\Andreas Galster\Desktop\PigmentsIO\_development>

**Comment by osv** [comment] 2015-07-21 16:02
Not sure this is Meteor bug, see https://github.com/npm/npm/issues/3697

**Comment by stubailo** [comment] 2015-07-21 16:10
It looks like you aren't running the official release of Meteor 1.1.0.2, but rather a preview version. What do you get when you type `meteor --version` inside your app?

**Comment by AndreasGalster** [comment] 2015-07-21 16:23
Windows-Preview@0.3.0
I remember installing one of your "recent" builds though where it said from now on it would automatically always update the meteor version without having to use a new Windows installer.

**Comment by stubailo** [comment] 2015-07-21 16:48
Ah, there was one more switch needed to go between the WINDOWS-PREVIEW and METEOR release tracks. We might also have had a bug or two in `meteor update` along the way. Sorry if we didn't communicate well enough about the transition.

Can you try installing again using the most recent installer? Then run `meteor update --release METEOR@1.1.0.2` inside your app, and from then on you should be all set.

**Comment by AndreasGalster** [comment] 2015-07-21 18:26
Ok, updated and now the deploying worked by the way. Just wondering, which versions did I jump now.  I think 0.3.0 was not the correct Meteor number but rather the Windows specific number, right? Just wanna read up on the logs which features I might have missed.

By the way in case it's relevant: The update did actually fail in my current project folder, so I just created a new meteor project and copy/pasted my files + packages.

PS C:\Users\Andreas Galster\Desktop\PigmentsIO\_development> meteor update --release METEOR@1.1.0.2

C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
TypeError: Cannot convert null to object
    at Object.Future.wait (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\
fibers\future.js:398:15)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:556:31
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_m
odules\underscore\underscore.js:79:11)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:554:9
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at enterJob (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at Object.forkJoin (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:531:3)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.window
s.x86_32\tools\tropohouse.js:562:18)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:668:25
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at Object.enterJob (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:667:20
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\catalog.js:100:5
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at Object.capture (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\
tools\catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_3
2\tools\project-context.js:666:13)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:238:35
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at Object.enterJob (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\
tools\project-context.js:228:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\too
ls\project-context.js:216:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\
tools\project-context.js:221:10)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\commands-packages.js:1462:20
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at Object.capture (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.main.captureAndExit (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\main.js:271:29
)
    at maybeUpdateRelease (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\commands-packages.js:1
461:8)
    at Command.main.registerCommand.name [as func] (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\too
ls\commands-packages.js:1523:29)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\main.js:1363:23
    - - - - -
    at hasOwnProperty (native)
    at Function._.has (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\unde
rscore\underscore.js:1074:27)
    at [object Object]._.extend._loadUnibuildsFromPath (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32
\tools\isopack.js:622:11)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:478:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_m
odules\underscore\underscore.js:79:11)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:477:11
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at Object.enterJob (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at Object.download (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:419:20)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:566:18
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:537:23
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
helpers.js:115:14)
    at enterJob (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:536:24
    at runWithEnvironment (C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:139:2
1)
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:146:14
    at C:\Users\Andreas Galster\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:549:11
PS C:\Users\Andreas Galster\Desktop\PigmentsIO\_development>
PS C:\Users\Andreas Galster\Desktop\PigmentsIO\_development>
PS C:\Users\Andreas Galster\Desktop\PigmentsIO\_development> cd ..
PS C:\Users\Andreas Galster\Desktop\PigmentsIO> meteor create _dev
_dev: created.

To run your new app:
  cd _dev
  meteor
PS C:\Users\Andreas Galster\Desktop\PigmentsIO> cd _dev
PS C:\Users\Andreas Galster\Desktop\PigmentsIO\_dev> meteor --version
Meteor 1.1.0.2

**Comment by abernix** [comment] 2016-08-02 07:13
There have been significant changes which should shorten the paths in Windows in newer versions of Meteor.  The problem is not gone entirely when using Cordova builds, however, I'm going to close this issue as it relates to `meteor deploy` (free hosting which is no longer provided) and there are other issues (#7358) which address the Cordova path issue.

**Closed by abernix** 2016-08-02 07:13 UTC
Labels: Project:Windows
