### ISSUE TITLE
meteor tool throws SQLITE_IOERR when trying to work with packages while another meteor process is running

### ISSUE THREAD

**Issue by Slava** [meteor/meteor#9501] opened 2017-12-26 21:39 UTC
Maybe it is specific to my environment, I am running on a Linux Subsystem (Ubuntu) on top of Windows 10 (newish windows feature).

Steps to reproduce:

1. Create a Meteor app
2. Run the app with `meteor run`
3. In another terminal session do `meteor list` or `meteor add accounts-password`
4. Observe the following error:

```
slava:~/app$ meteor add accounts-password
Error: SQLITE_IOERR: disk I/O error
Retrying after error { Error: SQLITE_IOERR: disk I/O error
=> awaited here:
at Promise.await (/home/slava/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
at Db._execute (/tools/packaging/catalog/catalog-remote.js:341:15)
at /tools/packaging/catalog/catalog-remote.js:144:10
at Db._retry (/tools/packaging/catalog/catalog-remote.js:156:16)
at new Db (/tools/packaging/catalog/catalog-remote.js:143:8)
at RemoteCatalog.initialize (/tools/packaging/catalog/catalog-remote.js:700:15)
at /tools/cli/main.js:869:20 errno: 10, code: 'SQLITE_IOERR' }
Retrying after error { Error: SQLITE_IOERR: disk I/O error
=> awaited here:
at Promise.await (/home/slava/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
at Db._execute (/tools/packaging/catalog/catalog-remote.js:341:15)
at /tools/packaging/catalog/catalog-remote.js:144:10
at Db._retry (/tools/packaging/catalog/catalog-remote.js:156:16)
at new Db (/tools/packaging/catalog/catalog-remote.js:143:8)
at RemoteCatalog.initialize (/tools/packaging/catalog/catalog-remote.js:700:15)
at /tools/cli/main.js:869:20 errno: 10, code: 'SQLITE_IOERR' }
/home/slava/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: SQLITE_IOERR: disk I/O error
 => awaited here:
    at Promise.await (/home/slava/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at Db._execute (/tools/packaging/catalog/catalog-remote.js:341:15)
    at /tools/packaging/catalog/catalog-remote.js:144:10
    at Db._retry (/tools/packaging/catalog/catalog-remote.js:156:16)
    at new Db (/tools/packaging/catalog/catalog-remote.js:143:8)
    at RemoteCatalog.initialize (/tools/packaging/catalog/catalog-remote.js:700:15)
    at /tools/cli/main.js:869:20

```

The workaround: kill `meteor run` process, then repeat.

**Comment by elmarti** [comment] 2017-12-26 21:54
Related issue? https://github.com/meteor/meteor/issues/9426

**Comment by klaussner** [comment] 2017-12-28 10:22
Thanks, @elmarti! That's indeed a duplicate of #9426 / meteor/meteor-feature-requests#154. :slightly_smiling_face:

**Closed by klaussner** 2017-12-28 10:22 UTC
