### ISSUE TITLE
Build plugin does not find a NPM installed package

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#8905] opened 2017-07-13 11:50 UTC
When trying to test a package with a build plugin, build plugin does not load and complains that the NPM package installed with `meteor npm install` cannot be found.

Reproduction: https://github.com/mitar/meteor-issue8905

Do:

```
meteor npm install
meteor test-packages failingplugin
```

Error:

```
=> Errors prevented startup:                  
   
   While loading plugin `failingPluginCompileTemplatesBatch` from package `failingplugin`:
   error: Can't load npm module 'vue' from packages/modules-runtime.js. Check your Npm.depends().
```

**Comment by abernix** [comment] 2017-07-13 18:49
I don't believe that build plugins were ever designed to support peer npm dependencies.  This is probably a feature request.

**Comment by mitar** [comment] 2017-07-13 18:59
I mean. I have `ecmascript` package as a dependency of the plugin. I would assume it will just work.

Sometimes it is hard to know if something is a feature request or a bug. It is definitely a surprising result one would not assume it will happen. In my case it prevents use of Blaze Components together with my Vue-powered Tracker.

**Comment by mitar** [comment] 2017-07-30 19:15
So this is a blocked for me. What can be done to address this?

**Comment by hwillson** [comment] 2017-08-01 16:35
@mitar For now if you add a 

```js
Npm.depends({
  "vue": "git://github.com/meteor-vue/vue.git#meteor"
});
```

call to your `simpledependency` `package.json`, it should work. Not an ideal solution since you're introducing the rigidity of `Npm.depends`, but for now it should help.

**Comment by mitar** [comment] 2017-08-01 20:37
Sadly, it does not seem to work. Adding the above to `simpledependency` and running `meteor test-packages failingplugin` gives me the following error:

```
=> Started proxy.                             
=> Started MongoDB.                           
simpledependency: updating npm dependencies -- vue...
=> Errors prevented startup:                  
   
   While running registerCompiler callback in package failingplugin:
   /tools/isobuild/build-plugin.js:43:15: Cannot read property 'setDiskCacheDirectory' of undefined
   at /tools/isobuild/build-plugin.js:43:15
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
...
```

Adding it to `failingplugin` does not work either.

I also see  [that there is a concept of build plugin npm dependencies](https://github.com/meteor/meteor/blob/devel/packages/stylus/package.js#L12), but it did not work for me either. Same error as above.

Also, in my case, it is really important that there is only one instance of Vue, because it has a concept similar to Tracker, so you need only one dependencies queue to exist in the system.

I am not sure why this is happening. The real problem is that I have an implementation of Tracker using Vue's dependency system and I wanted to [test it](https://github.com/meteor-vue/tracker/blob/master/circle.yml). It works by replacing `tracker` package with my own (see https://github.com/meteor/meteor-feature-requests/issues/47), which loads Vue. Now, the interesting thing is that it works with Blaze, but not Blaze Components. Not sure why. Difference is small:
* https://github.com/meteor/blaze/blob/master/packages/templating-compiler/package.js#L9
  * this one loads Tracker in this order: templating-tools -> spacebars-compiler -> htmljs -> tracker
* https://github.com/peerlibrary/meteor-blaze-components/blob/master/package.js#L9
  * and this one does it multiple times:
    * spacebars-compiler -> htmljs -> tracker
    * templating-tools -> spacebars-compiler -> htmljs -> tracker
    * html-tools -> htmljs -> tracker

So not sure why Blaze works, but Blaze Components not, and why this reproduction does not.

**Comment by mitar** [comment] 2017-08-01 20:40
I also tried `meteor test-packages --show-test-app-path --test-app-path /tmp/meteor-test-packages failingplugin` and manually installing Vue in that directory, and I get the `Cannot read property 'setDiskCacheDirectory' of undefined` error.

BTW, `Cannot read property 'setDiskCacheDirectory' of undefined` error is the one above in the initial comment description as well.

**Comment by hwillson** [comment] 2017-08-01 20:44
Right - I saw that error as well. Using `Npm.depends` does fix your `Vue` import though (I verified this by logging `Vue` right after the `import Vue from 'vue';` statement), but there is more to look into here for sure.

**Comment by mitar** [comment] 2017-08-01 20:58
Oh, so it loads Vue, but dies somewhere else? Interesting.

**Comment by hwillson** [comment] 2017-11-23 17:21
Hi @mitar - I just cloned your repro, updated it to Meteor 1.6, and tried running it. I was immediately greeted with the `Cannot read property 'setDiskCacheDirectory' of undefined` error you mentioned. I took a closer look at your repro though; your [`compile-templates.js`](https://github.com/mitar/meteor-issue8905/blob/f267f2b1e421611c8ce6cfe76790ecb4fa09267c/packages/failingplugin/compile-templates.js) compiler plugin is setup such that the factory function when executed is returning `undefined`. By design it has to return a compiler class instance. I updated your repro to return a dummy object instead and was able to successfully start your repro without any errors. Can you take another look on your side? Thanks!

**Comment by hwillson** [comment] 2017-12-04 15:02
Closing for now but please post back regarding https://github.com/meteor/meteor/issues/8905#issuecomment-346670257 when you have a chance. Happy to re-open if this is still an issue. Thanks!

**Closed by hwillson** 2017-12-04 15:02 UTC
Labels: Project:Isobuild
