### ISSUE TITLE
Crosswalk-based app not working on Android since upgrade to Meteor 1.5

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#8920] opened 2017-07-17 09:14 UTC
Since I upgraded my Meteor 1.2 app to 1.5, I can't get the Android version running anymore. There seem to be quite some problems related to Crosswalk. If I start the app, I get the following error messages in the console:

```
I20170717-11:11:22.042(2)? I/CordovaLog( 3789): Changing log level to DEBUG(3)
I20170717-11:11:22.093(2)? I/chromium( 3789): [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
I20170717-11:11:22.094(2)? E/chromium( 3789): [ERROR:xwalk_platform_notification_service.cc(143)] Not implemented reached in virtual bool xwalk::XWalkPlatformNotificationService::GetDisplayedPersistentNotifications(content::BrowserContext*, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*)
I20170717-11:11:22.094(2)? E/chromium( 3789): [ERROR:xwalk_browser_context.cc(87)] Failed to read preference, error num: 0
I20170717-11:11:22.094(2)? W/chromium( 3789): [WARNING:xwalk_external_extension.cc(58)] Error loading extension '/data/app/io.guzz.mobileapp-1/lib/arm/libxwalkcore.so': couldn't get XW_Initialize function.
I20170717-11:11:22.094(2)? W/chromium( 3789): [WARNING:xwalk_extension_server.cc(407)] Failed to initialize extension: /data/app/io.guzz.mobileapp-1/lib/arm/libxwalkcore.so
I20170717-11:11:22.113(2)? W/chromium( 3789): [WARNING:xwalk_external_extension.cc(58)] Error loading extension '/data/app/io.guzz.mobileapp-1/lib/arm/libxwalkdummy.so': couldn't get XW_Initialize function.
I20170717-11:11:22.114(2)? W/chromium( 3789): [WARNING:xwalk_extension_server.cc(407)] Failed to initialize extension: /data/app/io.guzz.mobileapp-1/lib/arm/libxwalkdummy.so
I20170717-11:11:22.114(2)? I/chromium( 3789): [INFO:xwalk_extension_renderer_controller.cc(42)] EXTENSION PROCESS DISABLED.
I20170717-11:11:22.114(2)? I/MeteorWebApp( 3789): Serving asset bundle with version: 4b969cbefac69da806589143e27267333d3cb677
I20170717-11:11:22.659(2)? E/chromium( 3789): [ERROR:layer_tree_host_impl.cc(2233)] Forcing zero-copy tile initialization as worker context is missing
I20170717-11:11:24.091(2) (android:http://localhost:12328/packages/modules.js:624) 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
I20170717-11:11:24.092(2) (android:http://localhost:12328/packages/modules.js:624) 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
I20170717-11:11:27.684(2) (android:http://localhost:12328/cordova.js:1223) deviceready has not fired after 5 seconds.
I20170717-11:11:27.684(2) (android:http://localhost:12328/cordova.js:1216) Channel not fired: onDOMContentLoaded
I20170717-11:11:34.442(2) (android:http://localhost:12328/packages/concats_app-main.js:175) %cguzz: Using Guzz as WebRTC backend provider
I20170717-11:11:36.811(2) (android:http://localhost:12328/packages/concats_app-main.js:175) %cguzz: Running as mobile app (Android)
I20170717-11:11:37.365(2)? E/chromium( 3789): [ERROR:web_contents_delegate.cc(197)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
I20170717-11:11:38.337(2) (android:http://localhost:12328/cordova.js:312) Error in Success callbackId: PushNotification452558307 : ReferenceError: device is not defined
I20170717-11:11:38.342(2) (android:http://localhost:12328/cordova.js:314) Uncaught ReferenceError: device is not defined
I20170717-11:11:38.734(2)? E/chromium( 3789): [ERROR:web_contents_delegate.cc(197)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
I20170717-11:11:38.755(2)? E/chromium( 3789): [ERROR:web_contents_delegate.cc(197)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
I20170717-11:11:40.452(2)? E/chromium( 3789): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
I20170717-11:11:40.529(2)? E/chromium( 3789): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
I20170717-11:11:41.380(2)? E/chromium( 3789): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
I20170717-11:11:42.173(2)? E/chromium( 3789): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
I20170717-11:11:42.873(2)? E/chromium( 3789): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
I20170717-11:11:43.140(2)? E/chromium( 3789): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
I20170717-11:11:45.572(2)? E/chromium( 3789): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
I20170717-11:11:45.812(2)? E/chromium( 3789): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
I20170717-11:11:47.443(2)? E/chromium( 3789): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
I20170717-11:11:51.112(2)? E/chromium( 3789): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
I20170717-11:11:51.137(2)? E/chromium( 3789): [ERROR:PlatformKeyboardEvent.cpp(84)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
I20170717-11:11:55.186(2)? E/chromium( 3789): [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
````

The last couple of messages appear every time I touch the app or try to type text using the virtual keyboard. The app won't connect to the server either, login is not possible anymore.

Is Crosswalk still supported in Meteor?

I'm also seeing these warnings in the Chrome inspector console:

```
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
modules.js:624 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
```
They seem to be related to the `reify` package.

**Comment by skirunman** [comment] 2017-07-17 20:55
> Is Crosswalk still supported in Meteor?

Crosswalk is still supported and we are still using it with Meteor 1.5.1. However, it is [end of lifed](https://crosswalk-project.org/blog/crosswalk-final-release.html) and last release is v23 (2.3.0). Meteor installs cordova-plugin-crosswalk-webview version 2.2.0, but you can install the latest version manually if you want by just installing the cordova plugin directly (we do this).

However, since [Android v7](https://en.wikipedia.org/wiki/Android_version_history) I would claim Crosswalk is not really needed as the default Android browser is based on Chromium, has pretty decent feature support for mobile and is performant. We have just not got around to removing Crosswalk yet from our Meteor project.

**Comment by dagatsoin** [comment] 2017-07-18 07:55
1. Have you tried to remove `reify` to see if it comes from it?

2. @skirunman is right you can install it manually by pasting `cordova-plugin-crosswalk-webview@2.3.0` in your `.meteor/cordova-plugins.

3. But maybe it could occurs with other non compatible plugins with Cordova 6.4 (or 6.5, I don't remember). So be sure all you plugins are up to date.

**Comment by derwaldgeist** [comment] 2017-07-18 15:45
@skirunman @dagatsoin Thanks for your hints. Will try that out and report back.

Regarding `reify`: I thought it is required by the latest Meteor version?

**Comment by derwaldgeist** [comment] 2017-07-29 10:06
On one of the devices (Nexus 7), when I am trying to use WebRTC, I am also getting this message:

```
I20170728-21:44:36.154(2)? 07-28 21:44:36.147 11309 11394 E chromium: [ERROR:audio_manager_android.cc(254)] Unable to select audio device!
```

and the video returned by the camera is 2x2 pixels (i.e. the video device cannot be opened, too).

On all devices, I can see these messages:

```
I20170728-21:44:36.337(2)? 07-28 21:44:36.331 11309 11309 E chromium: [ERROR:web_contents_delegate.cc(197)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
I20170728-21:44:36.344(2)? 07-28 21:44:36.338 11309 11309 E chromium: [ERROR:web_contents_delegate.cc(197)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
I20170728-21:44:36.345(2)? 07-28 21:44:36.339 11309 11309 E chromium: [ERROR:web_contents_delegate.cc(197)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
```

although I have added the permissions for accessing audio and video in the manifest. This all worked fine in Meteor 1.2.

**Comment by srtucker22** [comment] 2017-08-11 16:45
@derwaldgeist and now I'm here! did you figure out the audio device issue?!

**Comment by derwaldgeist** [comment] 2017-08-11 20:39
@srtucker22 Haha, welcome back :-)

I was able to solve this with this plugin:
https://github.com/NeoLSN/cordova-plugin-android-permissions

Here's my code:
```js
const ANDROID_PERMISSIONS = ['CAMERA', 'RECORD_AUDIO', 'MODIFY_AUDIO_SETTINGS'];
const permissions = cordova.plugins.permissions;
const requestedPermissions = [];
_.each(ANDROID_PERMISSIONS, p => requestedPermissions.push(permissions[p]));
const success = () => console.log('success');
const error = () => console.log('error');
permissions.requestPermissions(requestedPermissions, success, error);
```
In the real code, the first line retrieves the permissions from another configuration file.

**Comment by srtucker22** [comment] 2017-08-12 01:11
audio works great now!

@derwaldgeist you are just crushing it. made my day!

**Comment by derwaldgeist** [comment] 2017-08-12 19:00
Always glad to help. It actually took me at least 2 days to figure this out. I was quite desperate and thinking of dropping Meteor completely. As a last resort, I tried a production build of my app. This was when I saw that on the Marshmallow device no permissions were displayed. So I wondered why this happened and found out that since Android M, the permission model had been changed.

**Comment by hwillson** [comment] 2017-11-23 18:45
Meteor was updated to use the most recent (and last) version of `cordova-plugin-crosswalk-webview` (2.3.0). Given that others have confirmed Crosswalk is still working with Meteor >= 1.5, I'm not sure what else there is to do here. Any chance of supplying a reproduction that demonstrates this is a Meteor issue, if it's still happening with Meteor 1.6? I'll close this for now - thanks!

**Closed by hwillson** 2017-11-23 18:45 UTC

**Comment by adamgins** [comment] 2018-05-14 07:38
@hwillson I am still getting this with Meteor 1.6.1.1 

```
20180514-13:08:30.218(10)? 05-14 13:08:27.798  7872  7872 E chromium: [ERROR:xwalk_platform_notification_service.cc(143)] Not implemented reached in virtual bool xwalk::XWalkPlatformNotificationService::GetDisplayedPersistentNotifications(content::BrowserContext*, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*)
I2018051
```

Any ideas on how to resolve pls?

**Comment by crapthings** [comment] 2018-05-14 08:53
just remove xwalk
