### ISSUE TITLE
[1.3] support for local NPM packages

### ISSUE THREAD

**Issue by bySabi** [meteor/meteor#5891] opened 2015-12-27 08:54 UTC
In order to move projects to NPM based aproach local in-development code must be put on some place. Right know I put local npm´s this way

```
meteor-app
  node_modules
  client
  packages
     local-npm
  package.json
  ...
```

and add local npm  on `package.json` 
```
...
  "dependencies": {
    ...
    "local-npm1": "file:./packages/local-npm1",
    "local-npm2": "file:./packages/local-npm2",
    ...
  }
...
```
and update/install it with: `npm install` 

Will be great is meteor build system watch for changes on npm local package too and rebuild/reinstall  like it did with meteor local packages.

**Comment by timbotnik** [comment] 2015-12-29 22:59
Closing, looks like a duplicate of #5070 / #2876.

**Closed by timbotnik** 2015-12-29 22:59 UTC
