### ISSUE TITLE
Reactively changing src of <audio> 

### ISSUE THREAD

**Issue by msavin** [meteor/meteor#4026] opened 2015-03-25 21:10 UTC
On the helper side, I have:
` return Session.get("audioFile")

On the template side, I have:
` < audio src="{{helper}}">

My expectation was that the audio widget would re-render or update with the proper sound file whenever the Session variable changed, but it did not do anything. Instead I had to grab the element ID and set the source through JavaScript.

**Comment by dgreensp** [comment] 2015-03-31 21:12
Works for me in Chrome and Firefox.  Can you check again and maybe link to a reproduction?  Thanks!

**Comment by hwillson** [comment] 2016-11-11 11:26
Since a core dev (at the time) couldn't reproduce this issue, and no reproduction has been supplied, I recommend closing this issue. If this problem persists, a new issue should be opened in the [Blaze repo](https://github.com/meteor/blaze).

**Comment by abernix** [comment] 2016-11-11 15:10
Agree, @hwillson.  Thanks.

But of course thanks for reporting a potential issue originally, @msavin.  We just need to get some of the older issues under control.  Obviously this is still searchable if someone else runs into this problem. :smile:

**Closed by abernix** 2016-11-11 15:10 UTC
Labels: Project:Blaze
