### ISSUE TITLE
Keep order of class names when using in class=""

### ISSUE THREAD

**Issue by flyandi** [meteor/meteor#4044] opened 2015-03-27 07:10 UTC
Right now spacebars changes the order based on A-Z when replaced by expressions, e.g.

```
<div class="{{#if isTwo}}two{{else}}one{{/if}} column">
```
will result in
```
<div class="column one">  or <div class="column two">
```

Well the issue is that some classes are actually targeting the order of the class, e.g. in semantic-ui the css selector is ```[class*="two column"]``` , however spacebars is destroying this order.

**Comment by Slava** [comment] 2015-03-27 07:17
A duplicate of https://github.com/meteor/meteor/issues/3869?

**Comment by flyandi** [comment] 2015-03-27 07:20
Ah I was searching the issue pool - didn't find that one. Yep that's the same issue.

**Closed** 2015-03-27 07:22 UTC
