### ISSUE TITLE
Meteor 1.6 first time startup hangs 

### ISSUE THREAD

**Issue by QHose** [meteor/meteor#9321] opened 2017-11-08 12:51 UTC
If I try to run my meteor project via the dev client, it hangs

![image](https://user-images.githubusercontent.com/12411165/32550049-f3244c3a-c48b-11e7-8010-4fdd3b73addd.png)

Nothings happens, no CPU usage at all...

Steps to reproduce:

* blank windows 2012 r2 server
* `git clone https://GitHub.com/QHose/QRSMeteor.git --branch simplify-settings-file c:\GitHub\QRSMeteor`
* run meteor npm install 
* run `QRS start.bat` (which does meteor run command)

**Comment by QHose** [comment] 2017-11-08 12:53
if I run it a second time it goes further...

**Comment by hwillson** [comment] 2017-11-08 15:30
Out of curiosity, why are you setting the `ROOT_URL`? `localhost` is assumed automatically. If you remove the `set ROOT_URL`, what happens when you try to run it again?

Also - the reproduction you've linked to (https://github.com/QHose/QRSMeteor/tree/simplify-settings-file) is quite large. Any chance you could try creating a new reproduction that is as simple as possible, but still shows this problem?

**Comment by QHose** [comment] 2017-11-09 10:49
no clue why, first time I now get this suddenly:
![image](https://user-images.githubusercontent.com/12411165/32601749-fe80fb1a-c543-11e7-9f9b-fa51f7ce066f.png)

PS: I use the localhost for over 2 years now without any issues. I now removed it...

**Comment by abernix** [comment] 2017-11-09 12:09
@QHose Does running `meteor npm install --save core-js`, as shown in the error message, solve your problem?

**Comment by QHose** [comment] 2017-11-09 13:03
yeah it did!

**Comment by QHose** [comment] 2017-11-09 13:04
funny, never had this before...

**Comment by QHose** [comment] 2017-11-09 13:39
On another windows pc, I also get the new 0 undefined, error, which can be solved by removing the node modules directory
![image](https://user-images.githubusercontent.com/12411165/32608147-b7a0337e-c55b-11e7-98ca-1b5bbc0d7288.png)

**Comment by hwillson** [comment] 2017-11-09 17:07
Is everything okay here then @QHose? Can this issue be closed?

**Comment by QHose** [comment] 2017-11-09 17:53
well, it was a fresh install on a fresh pc, so I would assume it is a meteor bug if things don;t run well? in the past it always went smoothly.

**Comment by crapthings** [comment] 2017-11-10 00:35
https://github.com/meteor/meteor/issues/9333

**Comment by hwillson** [comment] 2017-11-10 19:53
@QHose The Meteor team definitely tries to make sure that the upgrade process for any new version of Meteor is as smooth as possible, but there can sometimes be hiccups. It's unfortunate you had to endure those hiccups, but I'm glad to hear things are working for you again. The new issue you've identified in https://github.com/meteor/meteor/issues/9321#issuecomment-343156750 is a known (upstream) npm bug, and is being tracked in https://github.com/meteor/meteor/issues/9333 (as you know, since you've commented there). Let's keep that discussion in https://github.com/meteor/meteor/issues/9333.

Given that there isn't much else we can do here, and that you're now back in business, I'll close this issue off. Thanks!

**Closed by hwillson** 2017-11-10 19:53 UTC
Labels: needs-reproduction, Project:Windows
