### ISSUE TITLE
Error when using forgotPassword without providing email as a default field

### ISSUE THREAD

**Issue by santiagopuentep** [meteor/meteor#11158] opened 2020-09-02 08:00 UTC
On Meteor 1.11, adding the `defaultFieldsSelector` config of `Accounts.config` has two problems:

1. BUG: it makes the `Accounts.forgotPassword` always return an error of "No such email" if the `defaultFieldsSelector` doesn't have email as a default field. It seems to be missing an internal fields selector on the internal query to the users collection.
2. LIMITATION: the `Accounts.onLogin` callback has no way of configuring the fields returned in the user that's given in the callback parameter.

### Expected behavior:

`forgotPassword` should work without errors when the `Accounts.config.defaultFieldsSelector` doesn't have the email as a default field. It seems to be missing a selector in it's internal query to the users collection.
`Accounts.onLogin` should allow to configure a selector for the user object that's given inside the callback parameter.

### To reproduce the problem:

1. add `Accounts.config({defaultFieldsSelector: {_id: 1}});` somewhere on the project (both client and server).
2. to see the forgot password error call:

```
Accounts.forgotPassword({ email: value }, (error) => {
	if (error) {
		console.log(error);
	} else {
		console.log("success");
	}
});
```
3. Call `Accounts.onLogin((loginData) => {console.log(loginData.user)});` to see that the user always return only the `_id`, but there's no way to make it return the username or email for only that callback unless adding those values to the `defaultFieldsSelector`.

**Comment by anatdagan** [comment] 2020-10-08 17:50
Hi, please assign this issue to me

**Comment by santiagopuentep** [comment] 2021-01-14 22:29
The second part of the problem `2. LIMITATION` is solved with the new `Accounts.setDefaultPublishedFields` function added in Meteor 1.12.

**Comment by filipenevola** [comment] 2021-01-19 13:46
Hi, 

Assuming #2 is already fixed I'll focus on #1 (I also renamed the issue).

If I understood the issue correctly the problem is when you remove email from your fields so your email is not fetched from the database.

But, thinking a little bit more, is it a bug as you removed the email from the fields that you want? Maybe we should emit a warning for this case but it doesn't seem to be a bug if the user doesn't want to user `forgotPassword` for example.

The warning could be:
`As you are not including email in your defaultFieldsSelector some methods can break, for example, forgotPassword`.

Am I correct or am I missing something here?

**Comment by santiagopuentep** [comment] 2021-01-22 21:54
@filipenevola Yes, I think that a warning would be great for those cases when the email required like in forgot password.

**Comment by filipenevola** [comment] 2021-02-04 20:31
Maybe even a warning is too much, it could be just a note in the documentation.

**Comment by denihs** [comment] 2021-05-24 15:35
The disclaimer is now added to the documentation in the field `defaultFieldSelector` description: https://docs.meteor.com/api/accounts-multi.html#AccountsCommon-config. I'm closing this issue ;)

**Closed by denihs** 2021-05-24 15:35 UTC
Labels: Project:Accounts:Password, good first issue, ready
