### ISSUE TITLE
[1.3-beta11] ROOT_URL with cordova and hotcode push not working

### ISSUE THREAD

**Issue by teknologist** [meteor/meteor#6296] opened 2016-02-22 20:16 UTC
When there is a hot code push on my cordova app I get this error:

adb logcat >

WebApp  : Download failure
WebApp  : com.meteor.webapp.DownloadFailureException: ROOT_URL in downloaded asset bundle does not match current ROOT_URL. Make sure ROOT_URL has been configured correctly on the server.

I have tried with and without ROOT_URL as an env var at build time.

I manage the server deploy with mup deploy.

I build the cordova app with 

meteor build ... --server https://myROOT_URL --architecture os.linux.x86_64

 Maybe this has something to do with mup... not sure though as I also specify the correct ROOT_URL in mup.js...

When I go to the cordova sources, the index.html contains the correct ROOT_URL in __meteor_runtime_config__ = JSON.parse(decodeURIComponent(   

And when I open a browser version of the webapp I can see the same ROOT_URL in 
__meteor_runtime_config__ = JSON.parse(decodeURIComponent( 

I am puzzled by this...

**Comment by teknologist** [comment] 2016-02-22 20:27
Closing as it seems to be a dupe of #6293

**Comment by teknologist** [comment] 2016-02-22 20:49
Checked le __meteor_runtime_config__ = JSON.parse(decodeURIComponent(  part on both and they seem to be the same...

Re openning...as I can't get past this

**Comment by martijnwalraven** [comment] 2016-02-22 21:56
This is indeed a duplicate of https://github.com/meteor/meteor/issues/6293, so I'm closing it again.

The Cordova version of the app is actually served from `http://domain.com/__cordova/`, and it seems that does have the added slash in `__meteor_runtime_config__`.

**Closed by martijnwalraven** 2016-02-22 21:56 UTC
