### ISSUE TITLE
meteor test-packages: npm dependencies from parent application cannot be found

### ISSUE THREAD

**Issue by Ben305** [meteor/meteor#7500] opened 2016-07-27 12:20 UTC
With Meteor 1.3.3, the following feature was introduced: 
Packages tested with meteor test-packages now have access to local `node_modules` directories installed in the parent application or in the package directory itself. #6827

This seems to be broken. When running tests for a local package that relies on a npm dependency from the parent application, this dependency cannot be found.

Steps to reproduce:

1) clone https://github.com/Ben305/AngularTemplatesSample.git
2) run `meteor npm i` in app-directory
3) Verify that is app is working by running `npm start`
4) Stop the application
5) Run `meteor npm run test` and navigate to http://localhost:3000
6) Check browser console errors, you will notice that the package `angular` cannot be found

cc @benjamn

This happens with Meteor `1.3.5.1` and `1.4`.

**Comment by abernix** [comment] 2016-10-05 07:52
Sorry for the long delay in getting to this!  And thank you for the clear reproduction!  This took a bit of time to dig into.

Originally, I was going to say that I only expected this support to work on the "server" target and not on the "client".  I think that statement was true when you originally made the issue, but is no longer true as your repo works if you do two things:

1. Require the `angular` NPM in your package.  For example in `main.js`:

        import angular from 'angular';

 When I first looked at this, my thought was along the lines of:
 > While this won't currently work (for other reasons), you should be importing `angular` in your module on the `client` if you expect it to work

 Without `require`-ing/`import`-ing the module, you won't have access to it here when relying on peer NPM dependency logic.  I didn't look extensively into this, but I'm assuming this is because the `angular-templates` package only has a [`weak` dependency](https://github.com/Urigo/angular-meteor/blob/9bcf2733cd9b5f5acd8f19f6dce283616d7b496b/packages/angular-meteor/packages/angular-templates/package.js#L24) on `angular` itself and (I don't think) `pbastowski:angular-babel` actually `require`s `angular` at all.

2. Update to Meteor 1.4.1.x

 This is strangely fixed by a78dde02254f9f2072e1db60e3fbeaa7ea26cc31.  I'm not sure that was the intention of that change or if this is a (positive!) side effect.  This is probably due to a misunderstanding on my part, or I missed something else (I was gone from Meteor-land for August).  I'll try to get to the bottom of that as it would seem that this would allow the removal of [this section](https://guide.meteor.com/writing-atmosphere-packages.html#testing-with-peer-dependencies) in the Meteor Guide which seems to indicate that this is (still) not possible.

**Comment by abernix** [comment] 2016-10-12 00:31
Closing as this is indeed fixed as a side-effect of a78dde02254f9f2072e1db60e3fbeaa7ea26cc31 and I've opened meteor/guide#572 to remove the section from the guide.

Please report back if you find differently!

**Closed by abernix** 2016-10-12 00:31 UTC
Labels: bug, confirmed, fixed

**Comment by macsj200** [comment] 2017-03-10 02:38
I've really been struggling to get phantomjs working with `test-packages`. It would appear to me that this bug is still a thing. Can anyone give me some advice for debugging the issue? I'm on the latest version of Meteor, and I'm using `dispatch:mocha` as my test driver.
