### ISSUE TITLE
[Blaze][Spacebars] Get array element under the X index

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#4476] opened 2015-05-29 21:01 UTC
Hi, right now in Spacebars to access N element of the array, we have to write following code:

```hbs
{{addresses.[0].state}}
{{addresses.[1].state}}
```

I'm curious why have you decided to use `[]` notation. Would it make sense to use following notation?

```hbs
{{addresses.0.state}}
{{addresses.1.state}}
```

I assume that there was reason for doing so, but could you explain me why? And is there any chance of providing `.N.` notation?

**Comment by stubailo** [comment] 2015-06-02 21:41
Duplicate of https://github.com/meteor/meteor/issues/2195, thanks for the feedback!

**Closed by stubailo** 2015-06-02 21:41 UTC

**Comment by jagi** [comment] 2015-06-03 08:18
Thanks didn't notice this one
