### ISSUE TITLE
meteor reset command resets user profile

### ISSUE THREAD

**Issue by inteldon** [meteor/meteor#11175] opened 2020-09-14 01:17 UTC
I attempted to "reset" my meteor project and found that although my user details were preserved, all information in the "profile" section was erased.

**Comment by santiagopuentep** [comment] 2020-09-14 01:23
To keep the database, copy the `.meteor/local/db` folder, do `meteor reset` and restore that folder. `meteor reset` is supposed to clear the database too, by design.

**Comment by SimonSimCity** [comment] 2020-09-24 14:28
Calling `meteor reset` should remove the folder `.meteor/local`, including all the data, as described here https://docs.meteor.com/commandline.html#meteorreset.

Out of your description it sounds like you either 1) ran the command while your meteor application was running, 2) the client preserved your user-data in some way - some kind of client-side storage - e.g. indexdb or webstorage, or 3) you have a package installed which re-inserts your user details if missing.

**Comment by inteldon** [comment] 2020-09-29 17:49
Thanks. What I did was run the reset command when the system stopped. I'm using a standard meteor application so to see all my databases get erased on the actual backend came as a surprise to me.

**Comment by SimonSimCity** [comment] 2020-09-30 09:16
If you do not want this to happen again, take a separate database.

1. Start up a database (download and start an instance of MongoDB).
1. Convert it to a replica set (https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/) - If you miss out on this, you won't have the collection `oplog` which is crucial for Meteor.
1. Run meteor as e.g. `MONGO_URL=mongodb://localhost:27017/meteor meteor` where `localhost:27017` is where your database is running and `meteor`, the text after the slash of the host, is the name of the database in your MongoDB installation you want Meteor to use.

If you follow this, your data will be stored separate from your Meteor project, which will not be affected by running `meteor reset` and you could even host it and share it with colleagues.

But this also means that you have to update the database yourself if you have to. The version, which comes bundled with Meteor is updated as you update Meteor. Sometimes updating the database brings along some critical changes where you have to do some things manually - when downgrading later it's then easy to just call `meteor reset` and you have a working set - even though your data is lost. It's a choice you have to take when building and managing a system that THAT simple as Meteor.

**Comment by StorytellerCZ** [comment] 2020-11-03 08:48
This is probably worth of a guide article.

**Comment by filipenevola** [comment] 2021-01-17 13:37
As this is the expected behavior of meteor reset I'm closing this issue.

The command itself is well documented here https://docs.meteor.com/commandline.html#meteorreset but maybe we could have an article on how to use your custom MongoDB.

**Closed by filipenevola** 2021-01-17 13:37 UTC
