### ISSUE TITLE
Allow pure HTML to be imported from within `imports`

### ISSUE THREAD

**Issue by ciro207** [meteor/meteor#6515] opened 2016-03-17 08:36 UTC
Hello! I already asked to meteor forum and I got a workaround.
https://forums.meteor.com/t/meteor-1-3-rc2-cannot-import-head/19568

Curently I'm using metor 1.3-rc.2, but problem is present in older versions
I would like to add one or multiple `<head>`. 

Following example on 
https://github.com/meteor/todos
I tried to put a head.html file into `/imports/ui/`

Following this commit
https://github.com/meteor/todos/commit/7ac55dbdfa60d93ced9db07308ae5b1991332052
I noticed that head.html would be available only if I put the file in `/client` folder

Even if this could be a solution for a single `<head>`, I don't know I to implement multiple ones, for example for different pages, as I did with meteor 1.2

**Comment by inspiraluna** [comment] 2016-03-18 09:42
It could be that the avatar module crosses the same problem in 

``Inject.rawHead('avatar-styles', '<style>' + css + '</style>');`` in helpers.js to inject the css which does not happen with 1.3 anymore?

https://github.com/meteor-utilities/avatar/issues/58

**Comment by tmeasday** [comment] 2016-03-19 01:56
How did you implement it in 1.2?

**Comment by ciro207** [comment] 2016-03-21 10:23
Normally, I put a html file into `/client/views/common/` with only the `<head>`
But I can place the file wherever I want and it works. Meteor concatenates with all the others found into application and put on the top of compiled code

**Comment by tmeasday** [comment] 2016-03-21 23:25
@ciro207 so this still works the same if you leave the file out of `imports/`. I guess pure HTML isn't importable (maybe it could be, we should think about this), so this sort of makes sense.

I still wonder about this comment: 

>  I don't know I to implement multiple ones, for example for different pages, as I did with meteor 1.2

I mean you can put multiple head tags outside of the `imports` dir, and it'll work the same but concatenate them all into one file in all cases. Is that what you wanted?

**Comment by aruntk** [comment] 2016-04-05 06:47
@tmeasday I'm working on a package to integrate meteor and polymer https://github.com/meteorwebcomponents/synthesis. I'm facing the same issue. It seems the cachingcompiler does not add body and head sections if file is in imports folder. Only js is getting added when I return {head:headcontents,body:bodycontents,js:scripts,bodyAttrs:{}} .

**Comment by tmeasday** [comment] 2016-04-06 22:31
@aruntk can you please open a new issue with a bit more of a reproduction of what you are doing?

**Comment by NitroBAY** [comment] 2016-08-09 21:53
+1. Reproduction : 
1) Create an head.html with <head> stuffs in client, it's imported.
2) Move it to imports and try to import it in /client, it throws an error.
As for me, I would like to import to keep client clean (as docs wants me to do) but seemingly this cause serious troubles to others.

**Comment by hwillson** [comment] 2017-02-02 12:57
HTML files stored under `/imports` are importable when called from `/client` (using a current version of Meteor). Quick example:

**/imports/more.html**

```html
<body>
  <p>This content is from /imports/more.html</p>
</body>
```

**/client/main.html**

```html
<head>
  <title>meteor-issue-6515</title>
</head>
<body>
  <p>This content is from /client/main.html</p>
</body>
```

**/client/main.js**

```js
import './main.html';
import '../imports/more.html';
```

When the above is run you'll see:

```
This content is from /client/main.html

This content is from /imports/more.html
```

As such, and since there is a workaround for the `<head />` issue discussed earlier in this thread, I'll close this issue. Thanks for reporting this originally!

**Closed by hwillson** 2017-02-02 12:57 UTC
Labels: confirmed, feature, Impact:few
