### ISSUE TITLE
App build failed after add crosswalk package

### ISSUE THREAD

**Issue by cyclops24** [meteor/meteor#8135] opened 2016-12-05 18:03 UTC
Hi guys,
I'm using Meteor.js 1.4.2.3 and add crosswalk package to my app with `meteor add crosswalk` but it returns below error when I try running my app on device with `meteor run android-device --mobile-server=<MY-SERVER-ADDRESS> --verbose`:

```
.
.
.
=> App running at: http://localhost:3000/     
Doing HTTP request:  POST                     
https://www.meteor.com/oauth2/authorize?state=60c7181520363545a02161ff67da417d&response_type=code&client_id=LdpZEt7ubqXAfkDJ2&redirect_uri=https%3A%2F%2Factivity.meteor.com%2F_oauth%2Fmeteor-developer%3Fclose
nulltarting app on Android Device            |
org.xwalk:xwalk_core_library:21+e            |
Observed package id 'build-tools;23.0.0' in inconsistent location '/home/myUserName/androidSDK/android-sdk-linux/build-tools/android-6.0' (Expected '/home/myUserName/androidSDK/android-sdk-linux/build-tools/23.0.0')
Incremental java compilation is an incubating feature.
Invalid cookie header: "Set-Cookie: WMF-Last-Access=05-Dec-2016;Path=/;HttpOnly;secure;Expires=Fri, 06 Jan 2017 12:00:00 GMT". Invalid 'expires' attribute: Fri, 06 Jan 2017 12:00:00 GMT
Invalid cookie header: "Set-Cookie: WMF-Last-Access=05-Dec-2016;Path=/;HttpOnly;secure;Expires=Fri, 06 Jan 2017 12:00:00 GMT". Invalid 'expires' attribute: Fri, 06 Jan 2017 12:00:00 GMT
Invalid cookie header: "Set-Cookie: WMF-Last-Access=05-Dec-2016;Path=/;HttpOnly;secure;Expires=Fri, 06 Jan 2017 12:00:00 GMT". Invalid 'expires' attribute: Fri, 06 Jan 2017 12:00:00 GMT
Invalid cookie header: "Set-Cookie: WMF-Last-Access=05-Dec-2016;Path=/;HttpOnly;secure;Expires=Fri, 06 Jan 2017 12:00:00 GMT". Invalid 'expires' attribute: Fri, 06 Jan 2017 12:00:00 GMT
Invalid cookie header: "Set-Cookie: WMF-Last-Access=05-Dec-2016;Path=/;HttpOnly;secure;Expires=Fri, 06 Jan 2017 12:00:00 GMT". Invalid 'expires' attribute: Fri, 06 Jan 2017 12:00:00 GMT
Invalid cookie header: "Set-Cookie: WMF-Last-Access=05-Dec-2016;Path=/;HttpOnly;secure;Expires=Fri, 06 Jan 2017 12:00:00 GMT". Invalid 'expires' attribute: Fri, 06 Jan 2017 12:00:00 GMT
Invalid cookie header: "Set-Cookie: WMF-Last-Access=05-Dec-2016;Path=/;HttpOnly;secure;Expires=Fri, 06 Jan 2017 12:00:00 GMT". Invalid 'expires' attribute: Fri, 06 Jan 2017 12:00:00 GMT
Invalid cookie header: "Set-Cookie: WMF-Last-Access=05-Dec-2016;Path=/;HttpOnly;secure;Expires=Fri, 06 Jan 2017 12:00:00 GMT". Invalid 'expires' attribute: Fri, 06 Jan 2017 12:00:00 GMT
Invalid cookie header: "Set-Cookie: WMF-Last-Access=05-Dec-2016;Path=/;HttpOnly;secure;Expires=Fri, 06 Jan 2017 12:00:00 GMT". Invalid 'expires' attribute: Fri, 06 Jan 2017 12:00:00 GMT
Invalid cookie header: "Set-Cookie: WMF-Last-Access=05-Dec-2016;Path=/;HttpOnly;secure;Expires=Fri, 06 Jan 2017 12:00:00 GMT". Invalid 'expires' attribute: Fri, 06 Jan 2017 12:00:00 GMT
   Starting app on Android Device            -
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any matches for org.xwalk:xwalk_core_library:21+ as no versions of org.xwalk:xwalk_core_library are available.
     Searched in the following locations:
         https://repo1.maven.org/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml
         https://repo1.maven.org/maven2/org/xwalk/xwalk_core_library/
         https://jcenter.bintray.com/org/xwalk/xwalk_core_library/maven-metadata.xml
         https://jcenter.bintray.com/org/xwalk/xwalk_core_library/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml
         file:/home/myUserName/androidSDK/android-sdk-linux/extras/android/m2repository/org/xwalk/xwalk_core_library/maven-metadata.xml
         file:/home/myUserName/androidSDK/android-sdk-linux/extras/android/m2repository/org/xwalk/xwalk_core_library/
         file:/home/myUserName/androidSDK/android-sdk-linux/extras/google/m2repository/org/xwalk/xwalk_core_library/maven-metadata.xml
         file:/home/myUserName/androidSDK/android-sdk-linux/extras/google/m2repository/org/xwalk/xwalk_core_library/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.734 secs
{ [Error: /home/myUserName/Projects/myApp/.meteor/local/cordova-build/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any matches for org.xwalk:xwalk_core_library:21+ as no versions of org.xwalk:xwalk_core_library are available.
     Searched in the following locations:
         https://repo1.maven.org/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml
         https://repo1.maven.org/maven2/org/xwalk/xwalk_core_library/
         https://jcenter.bintray.com/org/xwalk/xwalk_core_library/maven-metadata.xml
         https://jcenter.bintray.com/org/xwalk/xwalk_core_library/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml
         file:/home/myUserName/androidSDK/android-sdk-linux/extras/android/m2repository/org/xwalk/xwalk_core_library/maven-metadata.xml
         file:/home/myUserName/androidSDK/android-sdk-linux/extras/android/m2repository/org/xwalk/xwalk_core_library/
         file:/home/myUserName/androidSDK/android-sdk-linux/extras/google/m2repository/org/xwalk/xwalk_core_library/maven-metadata.xml
         file:/home/myUserName/androidSDK/android-sdk-linux/extras/google/m2repository/org/xwalk/xwalk_core_library/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.] code: 1 } 'Error: /home/myUserName/Projects/myApp/.meteor/local/cordova-build/platforms/android/gradlew: Command failed with exit code 1 Error output:\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring root project \'android\'.\n> Could not resolve all dependencies for configuration \':_armv7DebugCompile\'.\n   > Could not find any matches for org.xwalk:xwalk_core_library:21+ as no versions of org.xwalk:xwalk_core_library are available.\n     Searched in the following locations:\n         https://repo1.maven.org/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml\n         https://repo1.maven.org/maven2/org/xwalk/xwalk_core_library/\n         https://jcenter.bintray.com/org/xwalk/xwalk_core_library/maven-metadata.xml\n         https://jcenter.bintray.com/org/xwalk/xwalk_core_library/\n         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml\n         file:/home/myUserName/androidSDK/android-sdk-linux/extras/android/m2repository/org/xwalk/xwalk_core_library/maven-metadata.xml\n         file:/home/myUserName/androidSDK/android-sdk-linux/extras/android/m2repository/org/xwalk/xwalk_core_library/\n         file:/home/myUserName/androidSDK/android-sdk-linux/extras/google/m2repository/org/xwalk/xwalk_core_library/maven-metadata.xml\n         file:/home/myUserName/androidSDK/android-sdk-linux/extras/google/m2repository/org/xwalk/xwalk_core_library/\n     Required by:\n         :android:unspecified\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.\n    at ChildProcess.whenDone (/home/myUserName/Projects/myApp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:854:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)'
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --device:
   Error: Command failed: /home/myUserName/Projects/myApp/.meteor/local/cordova-build/platforms/android/cordova/run --device
   
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
   => awaited here:
   at Function.Promise.await
   (/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:715:22)
   at CordovaProject.run$ (/tools/cordova/project.js:261:10)
   at tryCatch
   (/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at GeneratorFunctionPrototype.invoke [as _invoke]
   (/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:337:22)
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
   (/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at tryCatch
   (/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at invoke
   (/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:139:20)
   at
   /home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:184:11
   at callInvokeWithMethodAndArg
   (/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:183:16)
   at AsyncIterator.enqueue
   (/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:206:13)
   at AsyncIterator.prototype.(anonymous function) [as next]
   (/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at Object.runtime.async
   (/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:226:14)
   at
   /home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
                                              
/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
undefined
 => awaited here:
    at Function.Promise.await (/home/myUserName/.meteor/packages/meteor-tool/.1.4.2_3.ol49b2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
    at /tools/cordova/runner.js:98:17
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at CordovaRunner.startRunTargets (/tools/cordova/runner.js:97:37)
    at AppRunner._runOnce (/tools/runners/run-app.js:763:21)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```

I also try to add crosswalk with this command: `meteor add cordova:cordova-plugin-crosswalk-webview@2.1.0` but It's also not working.

What is the problem? How to fix it?

**Comment by cyclops24** [comment] 2016-12-10 07:30
Anyone here to help me?
I have this issue over 1 week now.

**Comment by abernix** [comment] 2016-12-19 11:32
From the Meteor Guide:

> If you receive an error message trying to run the app on your device after adding or removing the Crosswalk plugin, you may have to remove the existing app from your device first.

I was just able to re-create an app using the steps you provided and it worked properly on an Android device.

**Comment by ramezrafla** [comment] 2017-01-14 04:09
We also use the crosswalk package and it works fine. @cyclops24 are you still facing the issue or can we close?

**Comment by hwillson** [comment] 2017-01-14 17:35
Since this is working for others, and this issue lacks a runnable reproduction showing the problem, I'll close it off. Thanks for reporting this originally (and the follow up @ramezrafla)!

**Closed by hwillson** 2017-01-14 17:35 UTC
Labels: can't-reproduce

**Comment by cyclops24** [comment] 2017-01-22 11:55
It's not working for me and I switched to React-Native completely. I don't know why but it's not fixed after 2 weeks try.

**Comment by erperejildo** [comment] 2017-05-16 10:42
I'm having this issue building the app with a Mac. On my Windows works as expected and I've got Android updated on my Mac.
