### ISSUE TITLE
How to add cordova plugin from local file system? 

### ISSUE THREAD

**Issue by kakahero** [meteor/meteor#4268] opened 2015-04-24 01:07 UTC
I used meteor develop android app and need to used android bluetooth api In my project . I used cordova to build a plugin. it work well. But I don't know how to add my plugin to my Meteor project. I used: 
meteor add cordova:file:///Users/apple/git/cordova-plugin-ihealth-bp@0.0.1

It can added cordova plugin, but It did not run . 
The terminal show:
simple-todos apple$ meteor run android-device
Error while running for mobile platforms: Error running 
/Users/apple/.meteor/packages/meteor-tool/.1.1.3.7747zc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
npm ERR! addLocal Could not install
file:///Users/apple/git/cordova-plugin-ihealth-bp@0.0.1
Error: ENOENT, stat 'file:///Users/apple/git/cordova-plugin-ihealth-bp@0.0.1
Fetching plugin "file:///Users/apple/git/cordova-plugin-ihealth-bp@0.0.1" via plugin
registry

How do I add cordova plugin from local file system to meteor project?

Sincerely.
Thanks a lot.

Xuewei Chen.

**Comment by glasser** [comment] 2015-04-29 08:21
This is not yet possible. Duplicate of #2925.

**Closed by glasser** 2015-04-29 08:21 UTC
Labels: Project:Mobile
