### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by themak01** [meteor/meteor#11292] opened 2021-01-18 09:29 UTC
```
import React, {useState,useEffect} from "react";
import "../styles.css";
import { API } from "../backend";
import Base from "../core/Base";
import PostCard from "../core/PostCard";
import { getPosts } from "../core/helper/coreapicalls";


export default function UserDashBoard() {
  const {posts, setPosts} = useState([])

  const {error, setError} = useState(false)

  const loadAllPosts = () => {
    getPosts().then(data => {
      if (data.error) {
        setError(data.error);
      }else {
        setPosts(data);
      }
    })
  }

  useEffect(() =>{
    loadAllPosts()
  },[])
  return (
    <Base title=" UserDash Board Page" description="Welcome to the Tshirt Store">
      <div className="row">
        {posts.map((post, index) =>{
          return (
            <div key={index}className="col-4 mb-4">
            <PostCard post = {post}/>
            </div>
          )
        })}
        
        
      </div>
    </Base>
  );
}
```

**Comment by StorytellerCZ** [comment] 2021-01-18 09:40
Your `posts` variable is undefined. Either return an empty array from `getPosts()` or do `posts?.map()` to prevent this. You might also want to consider using:
https://atmospherejs.com/meteor/react-meteor-data

And account for the time when the subscription is loading (`const isLoading = !Meteor.subscribe('mySubsbscription).ready()`).

Either way this is a bug in your code, not in Meteor so I'm closing this issue.

**Closed by StorytellerCZ** 2021-01-18 09:40 UTC

**Comment by filipenevola** [comment] 2021-01-18 14:19
Hi, the best place to ask questions is in the [Forums](https://forums.meteor.com) or in our [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).

Please send this question there and I'm sure you are going to get some help.

**Comment by radekmie** [comment] 2021-01-19 08:27
An error will occur if `getPosts()` will return `undefined`, but only in the following renders. During the first one, the problem is somewhere else - `useState` returns an array with two elements - using object restructuring won't work here, as there are no properties like `posts` or `error` in the array:

```diff
-  const {posts, setPosts} = useState([])
-  const {error, setError} = useState(false)
+  const [posts, setPosts] = useState([])
+  const [error, setError] = useState(false)
```

**Comment by themak01** [comment] 2021-01-19 08:53
export const getPosts = () => {
    return fetch(`${API}/all/users/posts`,{ 
        method: 'GET',

    })
    .then (response => { 
        return response.json();
    })
    .catch (err => console.log(err))
}
