### ISSUE TITLE
Allow use of NPMs not defined in server code within `meteor shell`

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#6624] opened 2016-03-29 22:41 UTC
Repro is really simple:

```
$ meteor create npmtest && cd npmtest
$ meteor npm install --save jquery.ui.touch
$ meteor run &
$ meteor shell
> require('jquery.ui.touch')
Error: Can't find npm module 'jquery.ui.touch'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
    at Object.Npm.require (/Users/jbb/co/npmtest/.meteor/local/build/programs/server/boot.js:195:17)
    at options.fallback (packages/modules-runtime.js:413:18)
    at require (packages/modules-runtime.js:98:16)
    at [object Object]:1:-61
    at Script.(anonymous function) [as runInThisContext] (vm.js:41:22)
    at /Users/jbb/co/npmtest/.meteor/local/build/programs/server/shell-server.js:366:27
    at /Users/jbb/.meteor/packages/meteor-tool/.1.3.0_3.1qdxblh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/meteor-promise/fiber_pool.js:33:40
```

If instead I try importing via node

```
$ node
> require('jquery.ui.touch')
ReferenceError: document is not defined
    at /Users/jbb/co/npmtest/node_modules/jquery.ui.touch/jquery.ui.touch.js:196:40
    at lastTap (/Users/jbb/co/npmtest/node_modules/jquery.ui.touch/jquery.ui.touch.js:20:26)
    at Object.<anonymous> (/Users/jbb/co/npmtest/node_modules/jquery.ui.touch/jquery.ui.touch.js:25:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at repl:1:1
```

Which is what I expect because it's a browser NPM.

**Comment by hexsprite** [comment] 2016-03-29 22:42
And just before anyone asks, it doesn't load on the client either:

```
> require('jquery.ui.touch')
Uncaught Error: Cannot find module 'jquery.ui.touch'(…)require @ modules-runtime.js?hash=939c79d…:95(anonymous function) @ VM260:1InjectedScript._evaluateOn @ VM219:145InjectedScript._evaluateAndWrap @ VM219:137InjectedScript.evaluate @ VM219:118
```

**Comment by Deilv** [comment] 2016-03-30 15:00
Adding the following line to **server/main.js**
```
import 'jquery.ui.touch';
```
Results in **ReferenceError: document is not defined**
Thus, if there is an issue, it is related to the shell, not meteor itself.

**Comment by jbrozena22** [comment] 2016-05-25 19:53
Having this same issue with the npm package MediumEditor. Is there any way to tell Meteor to only load an npm package onto the client only?

**Comment by abernix** [comment] 2016-11-25 22:04
@Deilv `ReferenceError: document is not defined` is actually the _expected_ behavior.  The `Can't find npm module 'jquery.ui.touch'` is the error in question here – which is not a jQuery error.

Anyhow, this is actually behaving as expected right now.  Per https://github.com/meteor/meteor/issues/7629#issuecomment-239196322:
>Yep, this is expected behavior. Not that it couldn't be improved, but the current recommendation is to explicitly import the module somewhere, e.g. if (false) require("/path/to/module.js"); so it won't be evaluated unless you import it in the shell.

That recommendation does work, even if it might be unintuitive.  Using NPMs on the `meteor shell` that aren't defined ANYwhere in your server code seems relatively uncommon though so the impact here is probably low (as indicated by an overall lack of issues with this).

Marking this as a confirmed feature and closing the other duplicate.  Thanks for reporting it so clearly!

**Comment by hwillson** [comment] 2017-06-09 15:27
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20use%20of%20NPMs%20not%20defined%20in%20server%20code%20within%20%60meteor%20shell%60&body=Migrated%20from:%20meteor/meteor%236624) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-09 15:27 UTC
Labels: confirmed, feature, Impact:few, Project:Isobuild, Severity:has-workaround
