### ISSUE TITLE
Cannot run my app after updating from 1.5.2.2 to 1.5.4

### ISSUE THREAD

**Issue by antoninadert** [meteor/meteor#9454] opened 2017-12-08 13:21 UTC
I cannot run my app anymore after updating to 1.5.4:
```

=> Meteor 1.6 is available. Update this project with 'meteor update'.
Errors prevented startup:

While selecting package versions:
error: Potentially incompatible change required to top-level dependency: mongo 1.2.3, was 1.3.0.
Constraints on package "mongo":
* mongo@1.2.2 <- top level
* mongo@~1.2.2 <- top level
* mongo@1.1.14 <- autoupdate 1.3.12 <- hot-code-push 1.0.4 <- meteor-base 1.1.0

To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the command line.

Your application has errors. Waiting for file change.
```

I tried on both MacOS and Windows 7 and 10.

The problem seems to be different according to my apps, sometimes the dependancy is on mongo, sometimes on less, sometimes on other packages, depending on the projects.

For this log, try to use my repro: https://github.com/antoninadert/basic-meteor-react-ssr
checkout the branch 'minimal' and update with meteor update --patch

**Comment by benjamn** [comment] 2017-12-08 20:18
What if you run `meteor update --release 1.5.4.1`? That works for me, with your reproduction. See also https://github.com/meteor/meteor/pull/9450.

**Comment by antoninadert** [comment] 2017-12-11 09:34
Could not update to this release: 
```
D:\CODE\Meteor\TESTS\basic-meteor-react-ssr>meteor update --release 1.5.4.1
C:\myUserPath\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_32\dev_bundle\lib
\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\myUserPath\AppData\Local\Temp\mt-boy0gp.0a9r\os
.json'
    at Object.fs.openSync (fs.js:648:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.wrapper [as readFile] (C:\tools\fs\files.js:1558:35)
    at C:\tools\isobuild\isopack.js:983:15
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\myUserPath\AppData\Local\.meteor\packages\meteor-tool\1.6.0\m
t-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:969:7)
    at _.each (C:\tools\packaging\tropohouse.js:521:21)
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\myUserPath\AppData\Local\.meteor\packages\meteor-tool\1.6.0\m
t-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at buildmessage.enterJob (C:\tools\packaging\tropohouse.js:520:13)
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:515:22
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:600:22
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at exports.Tropohouse.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:597:20)
    at C:\tools\cli\main.js:462:28
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at C:\tools\cli\main.js:461:15
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at C:\tools\cli\main.js:458:33
    at Console.withProgressDisplayVisible (C:\tools\console\console.js:619:14)
    at springboard (C:\tools\cli\main.js:457:11)
    at C:\tools\cli\main.js:1153:7
```

**Comment by benjamn** [comment] 2017-12-14 14:46
@antoninadert That error is annoying for sure, but it's usually not a permanent failure (just a temporary quirk of Windows file systems). Keep trying to update?

**Comment by hwillson** [comment] 2018-01-02 17:39
Are you still encountering this issue @antoninadert? As mentioned in https://github.com/meteor/meteor/issues/9454#issuecomment-351730997, this error is usually temporary. I'll close this for now, but let us know if it's still happening. Thanks!

**Closed by hwillson** 2018-01-02 17:39 UTC
Labels: Project:Tool, Project:Windows

**Comment by antoninadert** [comment] 2018-01-03 14:14
I rebooted my PC (Windows 7) with version 1.5.4.1 and I tried to run Meteor:

```
D:\CODE\Meteor\basic-meteor-react-ssr>meteor
[[[[[ ~\D\CODE\Meteor\basic-meteor-react-ssr ]]]]]

=> Started proxy.
=> Meteor 1.6.0.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
W20180103-15:10:51.531(1)? (STDERR) packages\modules.js:641
W20180103-15:10:52.085(1)? (STDERR) const { hasOwnProperty } = Object.prototype;
W20180103-15:10:52.086(1)? (STDERR)       ^
W20180103-15:10:52.088(1)? (STDERR)
W20180103-15:10:52.089(1)? (STDERR) SyntaxError: Unexpected token {
W20180103-15:10:52.090(1)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20180103-15:10:52.091(1)? (STDERR)     at D:\CODE\Meteor\basic-meteor-react-ssr\.meteor\local\build\programs\server\boot.js:332:30
W20180103-15:10:52.092(1)? (STDERR)     at Array.forEach (native)
W20180103-15:10:52.092(1)? (STDERR)     at Function._.each._.forEach (C:\Users\aadert\AppData\Local\.meteor\packages\meteor-tool\1.5.4_1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20180103-15:10:52.094(1)? (STDERR)     at D:\CODE\Meteor\basic-meteor-react-ssr\.meteor\local\build\programs\server\boot.js:158:5
W20180103-15:10:52.095(1)? (STDERR)     at D:\CODE\Meteor\basic-meteor-react-ssr\.meteor\local\build\programs\server\boot.js:388:5
W20180103-15:10:52.096(1)? (STDERR)     at Function.run (D:\CODE\Meteor\basic-meteor-react-ssr\.meteor\local\build\programs\server\profile.js:510:12)
W20180103-15:10:52.097(1)? (STDERR)     at D:\CODE\Meteor\basic-meteor-react-ssr\.meteor\local\build\programs\server\boot.js:387:11
```

It works on 1.6 though...

But on 1.6 I lose SSR performance...
