### ISSUE TITLE
Meteor 1.3.5.1 not running in Galaxy

### ISSUE THREAD

**Issue by filipenevola** [meteor/meteor#7456] opened 2016-07-22 18:44 UTC
I tried to update two production apps to Meteor 1.3.5.1 in galaxy today but it seems not working at all.

No logs are showed but the container can't stay up for more than 3 minutes and the application it self never have a healthy node to run.

https://forums.meteor.com/t/meteor-1-3-5-1-not-running-in-galaxy/26868
ticket: https://meteor.zendesk.com/hc/en-us/requests/2966

The solution for now was to downgrade to 1.3.4.4

2016-07-22 14:25:46-03:00The container has crashed. A new container will be started to replace it.
524p
2016-07-22 14:28:54-03:00The container has crashed. A new container will be started to replace it.
k2qz
2016-07-22 14:29:17-03:00The container has crashed. A new container will be started to replace it.
etsv
2016-07-22 14:30:46-03:00The container has crashed. A new container will be started to replace it.
ch9a
2016-07-22 14:32:26-03:00The container has crashed. A new container will be started to replace it.
k0nj
2016-07-22 14:34:15-03:00The container has crashed. A new container will be started to replace it.
pbxa
2016-07-22 14:38:26-03:00The container has crashed. A new container will be started to replace it.
5azk
2016-07-22 14:42:15-03:00The container is being stopped according to user kill request.
fch6
2016-07-22 14:44:37-03:00The container has crashed. A new container will be started to replace it.
gnbc
2016-07-22 14:45:13-03:00The container has crashed. A new container will be started to replace it.
c0tr
2016-07-22 14:46:13-03:00The container has crashed. A new container will be started to replace it.
7p6m
2016-07-22 14:48:26-03:00The container has crashed. A new container will be started to replace it.
m5g4
2016-07-22 14:51:47-03:00The container has crashed. A new container will be started to replace it.
23c6
2016-07-22 14:54:34-03:00The container has crashed. A new container will be started to replace it.
y2pn
2016-07-22 14:57:37-03:00The container has crashed. A new container will be started to replace it.
kmzp
2016-07-22 15:00:43-03:00The container has crashed. A new container will be started to replace it.
jvxy
2016-07-22 15:04:06-03:00The container has crashed. A new container will be started to replace it.
kp5r
2016-07-22 15:06:58-03:00The container has crashed. A new container will be started to replace it.
2g31
2016-07-22 15:10:18-03:00The container has crashed. A new container will be started to replace it.
cm5n
2016-07-22 15:13:19-03:00The container has crashed. A new container will be started to replace it.
q2qg
2016-07-22 15:16:07-03:00The container has crashed. A new container will be started to replace it.
ect9
2016-07-22 15:19:15-03:00The container has crashed. A new container will be started to replace it.
13hb
2016-07-22 15:22:25-03:00The container has crashed. A new container will be started to replace it.
hdfr
2016-07-22 15:25:44-03:00The container has crashed. A new container will be started to replace it.
k2s6
2016-07-22 15:28:55-03:00The container has crashed. A new container will be started to replace it.
yjzp
2016-07-22 15:32:00-03:00The container has crashed. A new container will be started to replace it.
tznq
2016-07-22 15:35:16-03:00The container has crashed. A new container will be started to replace it

**Comment by benjamn** [comment] 2016-07-22 19:09
Unfortunately, these error messages don't give any indication of what's wrong (and yes, I know that's part of the problem).

You might be able to get more insight by running
```sh
meteor build ../app-build
cd ../app-build
tar xf app.tar.gz
cd bundle/programs/server
meteor npm install
cd ../..
meteor node main.js
```
locally, which effectively simulates deploying the app. The final line will probably print some errors about environment variables that need to be set (e.g. `$MONGO_URL`), but you might also notice something that points to the problem.

Let us know how that goes!

**Comment by zol** [comment] 2016-07-22 22:05
Hey @filipenevola, I tried to reproduce this with a basic app and couldn't - the app comes online and works perfectly. I was wondering if you could help us out by posting a simplified reproduction with the goal of trying to get to the bottom of what specifically is different about your app that triggers the issue.

**Comment by filipenevola** [comment] 2016-07-24 19:40
Hi @benjamn  I tried to do your steps to simulate galaxy but meteor npm install result in error, link to npm-debug.log https://gist.github.com/filipenevola/94c8c76a24cc73eed365ee652bb73e94

@zol if this log is not enough I can try to isolate the problem.

**Comment by benjamn** [comment] 2016-07-24 20:34
@filipenevola It looks like you're somehow using Meteor 1.2.4 to run `meteor npm install`:
```
1620 info meteor-dev-bundle@0.0.0 Failed to exec install script
1621 verbose stack Error: meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
1621 verbose stack Exit status 1
1621 verbose stack     at EventEmitter.<anonymous> (/Users/filipenevola/.meteor/packages/meteor-tool/.1.2.4-rc.2.lgr86r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
1621 verbose stack     at EventEmitter.emit (events.js:98:17)
1621 verbose stack     at ChildProcess.<anonymous> (/Users/filipenevola/.meteor/packages/meteor-tool/.1.2.4-rc.2.lgr86r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/spawn.js:24:14)
1621 verbose stack     at ChildProcess.emit (events.js:98:17)
1621 verbose stack     at maybeClose (child_process.js:766:16)
1621 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
1622 verbose pkgid meteor-dev-bundle@0.0.0
1623 verbose cwd /Users/filipenevola/Documents/ts/ws/git/cavadinha/app-build/bundle/programs/server
1624 error Darwin 15.5.0
1625 error argv "node" "/Users/filipenevola/.meteor/packages/meteor-tool/.1.2.4-rc.2.lgr86r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install"
1626 error node v0.10.43
1627 error npm  v2.14.22
1628 error code ELIFECYCLE
1629 error meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
1629 error Exit status 1
1630 error Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
1630 error This is most likely a problem with the meteor-dev-bundle package,
1630 error not with npm itself.
1630 error Tell the author that this fails on your system:
1630 error     node npm-rebuild.js
1630 error You can get information on how to open an issue for this project with:
1630 error     npm bugs meteor-dev-bundle
1630 error Or if that isn't available, you can get their info via:
1630 error
1630 error     npm owner ls meteor-dev-bundle
1630 error There is likely additional logging output above.
1631 verbose exit [ 1, true ]
```
I believe this particular problem is fixed in 1.3.5.1 by [this commit](https://github.com/meteor/meteor/commit/fa14798115e79f0b9c9eca914aff69437659f669), so it's important that you're fully updated to Meteor 1.3.5.1.

Try these steps to force an update to the `~/.meteor/meteor` script:
```sh
meteor update --release 1.3.5.1
cd ~/.meteor
rm meteor
ln -s packages/meteor-tool/1.3.5_1/mt-os.osx.x86_64/meteor ./
~/.meteor/meteor --version
```
The last command should print 1.3.5.1 if all went well.

**Comment by filipenevola** [comment] 2016-07-24 22:03
@benjamn I think was some cache after my upgrade but now install command worked, below the error message trying to start node. I don't think it makes sense because just with meteor update --release 1.3.4.4 it works. What do you think?

```txt
/Users/filipenevola/Documents/ts/ws/git/cavadinha/app-build/bundle/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                      ^
Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at /Users/filipenevola/Documents/ts/ws/git/cavadinha/app-build/bundle/programs/server/packages/accounts-base.js:1829:15
    at /Users/filipenevola/Documents/ts/ws/git/cavadinha/app-build/bundle/programs/server/packages/accounts-base.js:1840:3
```

**Comment by santiq** [comment] 2016-07-26 19:01
Have the same problem, also with Meteor 1.4

**Comment by abernix** [comment] 2016-07-27 10:53
@filipenevola When running in production you need to set `MONGO_URL`.  This is a normal error if you haven't set that environment variable.  Please read the section of [the very helpful Meteor Guide](http://guide.meteor.com/) on [deploying to production](http://guide.meteor.com/deploying.html).

@santiq What problem?  Please clarify.  I'm closing this issue as the original issue as reported by the author appears to be resolved or is now related to a misconfiguration/misunderstanding.

**Closed by abernix** 2016-07-27 10:53 UTC
Labels: bug, can't-reproduce

**Comment by filipenevola** [comment] 2016-07-28 12:51
@abernix I guess you did not understand what I said.

if I just do meteor update --release 1.3.4.4 my app works so I have specified MONGO_URL correctly. The problem is in Meteor/Galaxy and I don't know what it is, can you please re-open?

**Comment by abernix** [comment] 2016-08-05 09:09
@filipenevola Locally, your Meteor uses its own Mongo unless you specify a `MONGO_URL` on your local development machine.  For Galaxy, you need to set the `MONGO_URL` in the environment using the [Galaxy environment variable settings](http://galaxy-guide.meteor.com/environment-variables.html).

**Comment by filipenevola** [comment] 2016-08-16 14:43
@abernix with meteor 1.4 it worked :)

but just to make it clear, we did not change anything. There is at least one bug in Meteor 1.3.5.1 related with my issue but for me it is ok now because I'm using 1.4 already.
