### ISSUE TITLE
Upgrading to 1.4.2-beta.11 Failed [Ubuntu 16.04]

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#7926] opened 2016-10-14 11:43 UTC
running:
```
meteor update --release 1.4.2-beta.11
```

From 1.4.2-beta.9

```
    /home/theodor/.meteor/packages/meteor-tool/.1.4.1_2.grfifw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
        throw error;
    ^

        Error: ENOENT: no such file or directory, open '/tmp/mt-ukz991/os.json'
        at Error (native)
```

**Comment by theodorDiaconu** [comment] 2016-10-14 11:45
Same happens with 1.4.2-beta.10

**Comment by benjamn** [comment] 2016-10-14 14:00
I'm having the same problem, and reliably this time. It looks like the extraction process errors before extracting all the files, and it affects both native `tar` and npmjs.org/package/tar, so perhaps the archive itself is incomplete.

**Comment by seeekr** [comment] 2016-10-16 00:29
Same thing on macOS 10.11. Tried several of the beta releases, none worked so far.

**Comment by sdarnell** [comment] 2016-10-16 10:38
Minor update, I get the same for 1.4.2-beta-12 on OSX 10.11.6 El Capitan  (tried beta 9, 10, 11, 12).
Don't think it is relevant, but for me, tmp filename is of the form: `/private/var/folders/yy/2bn52q0d2c59hrv5z0m0ty4w0000gn/T/mt-x5w0o8/os.json`

**Comment by abernix** [comment] 2016-10-17 05:43
Thanks for reporting this.  This is a duplicate of #7806 and related to poor/failing performance by the CDN.  Please see that issue for a temporary work-around and follow it for a permanent solution.

**Closed by abernix** 2016-10-17 05:43 UTC
