### ISSUE TITLE
Unable to update or add behind firewall

### ISSUE THREAD

**Issue by trysenga** [meteor/meteor#7151] opened 2016-06-01 18:56 UTC
Ok, I googled and followed all the suggestions about a month ago and got it working. Until today - it isn't working. I had't changed anything which is very frustrating. In the past month I have added and removed packages every other day or so as I was developing.

I have HTTP_PROXY and HTTPS_PROXY set up correctly. I can run curl https://packages.meteor.com with no errors. I'm at version 1.3.2.4 currently. Here is the output from update:

```
Unable to update package catalog (are you offline?)

If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY environment variables or see this page for more
details:  https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy

This project is already at Meteor 1.3.2.4, the latest release.
=> Errors while upgrading packages:

While downloading aslagle:reactive-table@0.8.31...:
error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND


And here is the output from an add:

Unable to update package catalog (are you offline?)

If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY environment variables or see this page for more
details:  https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy

 => Errors while adding packages:

While downloading percolate:synced-cron@1.3.2...:
error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

Your package catalog may be out of date.
Please connect to the internet and try again.
```

**Comment by niwsa** [comment] 2016-06-01 19:54
I do get issues with installing meteor packages,quite often multiple retries are needed to get it working,not sure whether its related to firewall or proxy.

**Comment by laosb** [comment] 2016-06-04 05:49
Sounds like a firewall/proxy problem. Can't reproduce with my HTTP proxy.

**Comment by abernix** [comment] 2016-07-11 11:13
@trysenga Any updates on this issue?  @laosb wasn't able to reproduce it and `HTTP_PROXY` and `HTTPS_PROXY` are known to work.

**Comment by abernix** [comment] 2016-07-11 11:14
I will say there were a lot of CDN issues at the time that you opened this issue that could have affected things too.  See #6960.  If you think your problem is resolved.  Please close this issue.

Thanks!

**Comment by trysenga** [comment] 2016-07-11 14:30
Dell - Internal Use - Confidential
I was never able to work around it. It is possible that something changed with our internal firewalls but IT was unwilling to work with me. I’ve gone a different route now for getting updates which will work for the one server I’m using. I’ll need a better solution down the road when we are ready for more.

Tobin

**Comment by feeloo007** [comment] 2016-09-15 17:49
Hi,

I've got the same problem.

We use Web Gateway Proxy (HTTP_PROXY / HTTPS_PROXY configured to use it).

Meteor update makes : 
````
GET https://packages.meteor.com/websocket HTTP/1.1
Host: packages.meteor.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: JTp1pr1aYw+C3AIhnuQ16Q==
Sec-WebSocket-Version: 13
User-Agent: Meteor/meteor-tool@1.3.1 OS/linux (Linux; 3.10.0-229.14.1.el7.x86_64; x64;)
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

Our Web Gateway configuration blocks websocket upgrade with HTTP 403 response : 

```
HTTP/1.1 403 WebSocketBlock
Via: 1.1 192.168.50.37 (McAfee Web Gateway 7.6.2.2.0.21927)
Connection: Keep-Alive
Content-Type: text/html
Cache-Control: no-cache
Content-Length: 2386

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
...
<!--Content-->
<table class="contentTable">
  <tr>
    <td class="contentData">
      Upgrade to WebSocket is blocked.
    </td>
  </tr>
</table>
...
      generated <span id="time">2016-09-15 19:28:23</span> by McAfee Web Gateway
      <br />
      Meteor/meteor-tool@1.3.1 OS/linux (Linux; 3.10.0-229.14.1.el7.x86_64; x64;)
...
```

Is it possible to disable websocket on meteor update, meteor add... ?

Best regards

Philippe

**Comment by hwillson** [comment] 2017-05-29 15:35
Hi all - it sounds like the original problem outlined in this issue could have been caused by the CDN issues that were occurring around the time this issue was created. Those issues have since been resolved. Regarding problems with Web Gateway specifically, they have a [knowledge center article on how to allow WebSocket traffic](https://kc.mcafee.com/corporate/index?page=content&id=KB84052&actp=null&showDraft=false&platinum_status=false&locale=en_US&viewlocale=en_US) that might help. If not, you can always disable WebSockets by setting the `DISABLE_WEBSOCKETS` environment variable to any truthy value - e.g.:

```
DISABLE_WEBSOCKETS=1 meteor ...
```

Given the above, I think we're okay to close this issue. Happy to re-open if anyone disagrees. Thanks!

**Closed by hwillson** 2017-05-29 15:35 UTC
Labels: bug, Impact:few, Project:Tool, Severity:production
