### ISSUE TITLE
npm install error in deployed bundle/programs/server/

### ISSUE THREAD

**Issue by madwiki** [meteor/meteor#8616] opened 2017-04-19 19:03 UTC
version: 1.4.4.1
node version: v7.7.4
npm version: v4.1.2
OS: MacXOS 10.12.3

After custom deployed,when I ran `npm i`

```
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.
```
I searched for solutions on github and stackoverflow,but not working.

**Comment by hwillson** [comment] 2017-04-19 20:23
Hi @madwiki - try matching your deployment environments Node and npm versions to the latest versions supported by your Meteor version. Meteor 1.4.4.1 supports Node 4.8.1 and npm 4.4.4. When in doubt, run the following from your command line, to see which versions your Meteor application has been developed against.

```
meteor node -v
meteor npm -v
```

**Comment by madwiki** [comment] 2017-04-20 18:18
@hwillson Thank you!It works!
I changed my node version to 4.8.1,npm version to 4.4.4.

But I encountered a new problem after trying the next step:
`MONGO_URL=mongodb://localhost:27017/myapp ROOT_URL=http://localhost:3000 node main.js`

Just nothing happened.No outputs, couldn't access the address.And I'm at home, port 3000 is available.

Do you know how to solve it?

**Comment by hwillson** [comment] 2017-04-21 16:26
Hi @madwiki - try splitting your host and port up into separate environment variables, like:

```
MONGO_URL=mongodb://localhost:27017/myapp ROOT_URL=http://localhost PORT=3000 node main.js
```

Since the original issue has been resolved, I'll close this for now. You're better off trying the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) for Meteor usage questions like this (you'll likely get a faster turnaround). Thanks!

**Closed by hwillson** 2017-04-21 16:26 UTC

**Comment by madwiki** [comment] 2017-04-22 17:44
Thx,I will.

**Comment by mrkhanakia** [comment] 2017-09-16 18:59
I have node version 4.8.1,npm version 4.4.4.
and i am having error

`Amans-MacBook-Pro:server aman$ npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> meteor-dev-bundle@0.0.0 install /Volumes/D/www/todos/.meteor/local/build/programs/server
> node npm-rebuild.js

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aman/.npm/_logs/2017-09-16T18_57_42_131Z-debug.log
`

**Comment by jaqua** [comment] 2017-10-13 18:07
I do get exactly the same error as mrkhanakia.

@mrkhanakia Did you fix you problem?

**Comment by jimmylogic** [comment] 2018-09-20 09:28
@mrkhanakia Did you fix you problem?

**Comment by groupfranchising** [comment] 2018-10-18 08:41
I am getting the same error. Any solution?

**Comment by imhazige** [comment] 2019-11-26 03:21
same here when works on local docker, but have the error when deploy to heroku docker.

**Comment by macrozone** [comment] 2021-11-15 17:42
> I have node version 4.8.1,npm version 4.4.4. I am still getting error please help
> 
> `Amans-MacBook-Pro:server aman$ npm i npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
> 
> > meteor-dev-bundle@0.0.0 install /Volumes/D/www/todos/.meteor/local/build/programs/server
> > node npm-rebuild.js
> 
> events.js:182 throw er; // Unhandled 'error' event ^
> 
> Error: spawn npm ENOENT at exports._errnoException (util.js:1024:11) at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19) at onErrorNT (internal/child_process.js:374:16) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9) at Function.Module.runMain (module.js:607:11) at startup (bootstrap_node.js:158:16) at bootstrap_node.js:575:3 npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /Users/aman/.npm/_logs/2017-09-16T18_57_42_131Z-debug.log`

after like 3 years of running without problem i have this exact error now on one of our pipelines. I have no idea what the problem is all of sudden
