### ISSUE TITLE
Allow configuration of crossorigin attribute in webapp/boilerplate

### ISSUE THREAD

**Issue by egoldblum** [meteor/meteor#4783] opened 2015-07-21 16:18 UTC
I would like to be able to set attributes on the script tag for the meteor JS bundle on the boilerplate base html page.  In particular, I want control of the `crossorigin` attribute.

I serve my JS bundle from a CDN via CORS.  When an error occurs in this file, browsers report only `Script Error` and do not include any more detailed information to prevent information from leaking cross origin[1][2][3].  I would like `webapp` to expose an API that allows me to set attributes for the boilerplate script tags, similar to how I can specify JS/CSS prefixes with `WebAppInternals.setBundledJsCssPrefix`

[1] https://bugsnag.com/blog/script-error
[2] https://errorception.com/docs/cors
[3] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-crossorigin

**Comment by glasser** [comment] 2015-07-21 21:59
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

In general, we need the HTML-serving part of Webapp to be much more configurable.

**Comment by abernix** [comment] 2017-03-17 12:52
I believe the implementation detail of this have been figured out in #7781 so I've marked this as `confirmed` and `pull-requested-encouraged`. 

@brianlukoff attempted to implement it but didn't have enough time to finish the implementation (though much appreciation for helping to hash out the details!)

I've updated this since @nadeemja [expressed interest](https://github.com/meteor/meteor/pull/7781#issuecomment-287324266) in reviving this.

**Comment by hwillson** [comment] 2017-06-07 18:28
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20configuration%20of%20crossorigin%20attribute%20in%20webapp%2Fboilerplate&body=Migrated%20from:%20meteor/meteor%234783) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2017-06-07 18:28 UTC
Labels: confirmed, feature, Project:Webapp, pull-requests-encouraged
