### ISSUE TITLE
Can't create or update to 1.4.2-beta.11 on Windows 10 x64 - Error: unexpected eof

### ISSUE THREAD

**Issue by jakobrosenberg** [meteor/meteor#7925] opened 2016-10-14 09:14 UTC
meteor create 1.4.2-beta.11 --release 1.4.2-beta.11  

<details>
 <summary>Trace log</summary>
Error: unexpected eof                                                                                                   
    at decorate (C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\n
ode_modules\fstream\lib\abstract.js:67:36)                                                                              
    at Extract.Abstract.error (C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\de
v_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)                                                                
    at Extract._streamEnd (C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bu
ndle\lib\node_modules\tar\lib\extract.js:91:35)                                                                         
    at BlockStream.<anonymous> (C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\d
ev_bundle\lib\node_modules\tar\lib\parse.js:51:8)                                                                       
    at emitNone (events.js:67:13)                                                                                       
    at BlockStream.emit (events.js:166:7)                                                                               
    at BlockStream._emitChunk (C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\de
v_bundle\lib\node_modules\block-stream\block-stream.js:203:10)                                                          
    at BlockStream.resume (C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bu
ndle\lib\node_modules\block-stream\block-stream.js:58:15)                                                               
    at Extract.Reader.resume (C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev
_bundle\lib\node_modules\fstream\lib\reader.js:242:34)                                                                  
    at Entry.<anonymous> (C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bun
dle\lib\node_modules\tar\lib\parse.js:261:8)                                                                            
    at emitNone (events.js:67:13)                                                                                       
    at Entry.emit (events.js:166:7)                                                                                     
    at Entry.resume (C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\l
ib\node_modules\tar\lib\entry.js:93:8)                                                                                  
    at FileWriter.<anonymous> (C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\de
v_bundle\lib\node_modules\fstream\lib\dir-writer.js:147:11)                                                             
    at emitNone (events.js:67:13)                                                                                       
    at FileWriter.emit (events.js:166:7)                                                                                
    at WriteStream.<anonymous> (C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\d
ev_bundle\lib\node_modules\fstream\lib\file-writer.js:45:10)                                                            
    at emitOne (events.js:77:13)                                                                                        
    at WriteStream.emit (events.js:169:7)                                                                               
    at C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\graceful-fs\graceful-fs.js:214:14                                                                                     
    at C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\graceful-fs\graceful-fs.js:241:16                                                                                     
    at C:\Users\jakob\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\cordova-lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:232:16                                           
    at FSReqWrap.oncomplete (fs.js:82:15)                                                                               
                                                                      
</details>

**Comment by abernix** [comment] 2016-10-14 13:03
Duplicate of #7766, please remember to search before opening new issues!

I've just posted an update in that issue so please take a look and see if you can assist!

**Closed by abernix** 2016-10-14 13:03 UTC
