### ISSUE TITLE
[1.3.3-beta.1] `meteor test` with `rethinkdb` - Neither TCP nor HTTP avaiable in this environment

### ISSUE THREAD

**Issue by dan335** [meteor/meteor#7135] opened 2016-05-30 05:59 UTC
Meteor 1.3.3-beta.1

When I run "meteor test --full-app --driver-package=practicalmeteor:mocha" I get

```
/Users/dan/web/dotsboxes/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                                 ^
ReqlDriverError: Neither TCP nor HTTP avaiable in this environment
    at ReqlDriverError.ReqlError (/Users/dan/web/dotsboxes/node_modules/rethinkdb/errors.js:23:13)
    at new ReqlDriverError (/Users/dan/web/dotsboxes/node_modules/rethinkdb/errors.js:68:50)
    at /Users/dan/web/dotsboxes/node_modules/rethinkdb/net.js:961:17
    at /Users/dan/web/dotsboxes/node_modules/rethinkdb/net.js:972:12
    at Function.<anonymous> (/Users/dan/web/dotsboxes/node_modules/rethinkdb/net.js:939:10)
    at Function.connect (/Users/dan/web/dotsboxes/node_modules/rethinkdb/util.js:43:16)
    at meteorInstall.lib.server.rethinkConnection.js (lib/server/rethinkConnection.js:4:3)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at /private/var/folders/v3/g4gz7fh91fzdlr3wd2k7t1ph0000gn/T/meteor-test-runoqejcj/.meteor/local/build/programs/server/app/app.js:986:1
    at /private/var/folders/v3/g4gz7fh91fzdlr3wd2k7t1ph0000gn/T/meteor-test-runoqejcj/.meteor/local/build/programs/server/boot.js:291:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/dan/.meteor/packages/meteor-tool/.1.3.3-beta.1.1qbkx1g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
Exited with code: 8
Your application is crashing. Waiting for file change.
```

When I have a file with this.

```
r = require('rethinkdb');
r.connect( {host:process.env.RETHINKHOST, port: 28015, user:'admin', password:process.env.RETHINKPASS});
```

Everything works with "meteor run".

**Comment by abernix** [comment] 2016-05-30 06:16
Please read the information for [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor).

You haven't included much information about the way your project is configured – packages, NPMs, etc.  I realize it may seem simple, but building reproductions takes a significant amount of core developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.  Please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here.

Thank you for understanding.

**Comment by dan335** [comment] 2016-05-30 07:18
Here's a reproduction.  https://github.com/dan335/meteor-test-repro

**Comment by abernix** [comment] 2016-05-30 09:21
Thanks for the reproduction.   This seems to be happening because the `rethinkdb` NPM is [checking `process.browser` to determine if it is running on `node` or the browser](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/net.coffee#L930).  Unfortunately, `practicalmeteor:mocha` is [setting `process.browser` to true](https://github.com/practicalmeteor/meteor-mocha/blob/meteor/meteor/src/setup/setupMochaServer.js#L6) when it sets up the server.

This is strange and doesn't seem to happen if you use a different test driver.  I'm not sure what the best course of action here.  Obviously  setting `process.browser = true` on the server seems counter-intuitive but maybe `practicalmeteor:mocha` is doing that for a good reason.  On the other hand, `rethinkdb` could probably also use a different way of checking to see if it's in an environment where it can open a TCP listener, as `process.browser` is a browserify thing, I believe.

Maybe @jsep can shed some light on this?

**Comment by dan335** [comment] 2016-05-30 15:39
dispatch:mocha is working fine.

**Comment by abernix** [comment] 2016-05-31 09:34
@rbabayoff might also have some input on this.  But I'm closing this though as it's not a Meteor bug, best I can tell.

**Closed by abernix** 2016-05-31 09:34 UTC
Labels: bug, npm-module-specific, Project:JS Environment

**Comment by jsep** [comment] 2016-06-23 17:15
Hello everyone sorry to wake this up, but from `practicalmeteor:mocha@2.4.5_3` we are not doing that anymore.
