### ISSUE TITLE
Hot Code Push doesn't work

### ISSUE THREAD

**Issue by Doris1994** [meteor/meteor#7061] opened 2016-05-16 03:18 UTC
When I upgrade my project to meteor1.3， hot code push can work normally when  run on the local server `meteor -v run ios-device --production --mobile-server=192.168.2.4:3000`，192.168.2.4 is is my IP address， but when I use server address `meteor -v run ios-device --production --mobile-server=http://host2.tiegushi.com`  will be submitted to the following error:

> Start downloading asset manifest from: manifest.json -- http://host2.tiegushi.com/__cordova/
Download failure: Error parsing asset manifest: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

I checked [http://host2.tiegushi.com/__cordova/manifest.json](url)，found no this file.The manifest. Json this file is compiled into the root directory[http://host2.tiegushi.com/manifest.json](url).

Who met this kind of situation, how to solve？

**Comment by abernix** [comment] 2016-05-16 09:07
Hi there,

We highly recommend reaching out to the [Meteor forums](http://forums.meteor.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/meteor) before opening an issue here due to the large number of issues that the Meteor project receives.

Initially it's really hard to tell if this is a problem with Meteor or a problem with your deployment.  If you haven't deployed the latest 1.3 version to your host2.tiegushi.com, then you would likely have incompatible versions and it also appears that you might be running into a problem similar to #4132.

*However, if you do feel like this is a bug and you would like someone to look at it...*

Please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple example as possible) and upload that project to GitHub. Then, simply include the link to it and it will be easy for any developer to clone and see the same problem you're having and decide if it's a problem with your code, or a problem with Meteor itself.

Someone will be much more able to help you if you include this. Unfortunately, without providing a reproduction repository, it's very difficult to get someone to investigate.

Thanks! :smile:

**Comment by wojtkowiak** [comment] 2016-05-16 09:54
How are you running meteor on `http://host2.tiegushi.com`? From a build or from `meteor` command line?

**Comment by crapthings** [comment] 2016-05-24 12:42
its very easy to reproduce

1. meteor create testhcp && cd testhcp
2. meteor add-platform ios
3. mupx deploy to your server
4. meteor run ios-device --mobile-server=http://yourip:port or
meteor build ../ios --server=http://yourip:port
5. change some code and mupx deploy again

mobile will not get the new version

the ROOT_URL is already set by mupx

**Comment by crapthings** [comment] 2016-05-24 14:36
#7112

**Comment by abernix** [comment] 2016-05-30 10:37
@crapthings Are you saying that not using the equals (`=`) sign when specifying `--server` or `--mobile-server` fixes this for you?

**Comment by crapthings** [comment] 2016-05-30 10:45
yes

**Comment by crapthings** [comment] 2016-05-30 10:48
because that equal sign will not set root url on client`s html head，this will cause hcp failed。

**Comment by abernix** [comment] 2016-05-30 10:57
@craptings What OS were you running into this problem on?

**Comment by crapthings** [comment] 2016-05-30 11:02
both android and ios

**Comment by abernix** [comment] 2016-05-30 11:03
@crapthings I mean, what system were you *building* it on?

**Comment by crapthings** [comment] 2016-05-31 01:37
@abernix osx

**Comment by abernix** [comment] 2016-07-11 11:16
Closing in favor of #7112

**Closed by abernix** 2016-07-11 11:16 UTC
Labels: bug, Project:Mobile

**Comment by iwoj** [comment] 2017-05-13 21:08
See #7760
