### ISSUE TITLE
The built-in `facts` package seems to break, starting with version 1.2.

### ISSUE THREAD

**Issue by cscott** [meteor/meteor#5984] opened 2016-01-13 04:47 UTC
On startup, I see:
```
I20160112-23:18:43.140(-5)? Exception in defer callback: TypeError: Object [object Object] has no method 'publish'
I20160112-23:18:43.142(-5)?   at /home/cananian/Projects/MysteryHunt/2015/codex-blackboard/.meteor/local/build/programs/server/packages/facts.js:68:12
I20160112-23:18:43.142(-5)?   at runWithEnvironment (/home/cananian/Projects/MysteryHunt/2015/codex-blackboard/.meteor/local/build/programs/server/packages/meteor.js:1083:24)
```
This seems to be a call to `Meteor.publish` -- somehow this is being called before the `Meteor` object is fully initialized?

**Comment by grsabreu** [comment] 2016-01-13 11:48
Can you give a little reproduce repo?

**Comment by cscott** [comment] 2016-01-13 15:54
github.com/cjb/codex-blackboard

**Comment by tmeasday** [comment] 2016-01-19 22:50
Works for me with the simplest possible reproduction. @cscott can you please provide a simple repro (see https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor)

**Comment by abernix** [comment] 2016-05-25 07:04
I'm sure that facts is working in Meteor 1.3.  [Read about using it here in the oplog docs](https://github.com/meteor/docs/blob/version-NEXT/long-form/oplog-observe-driver.md#how-to-tell-if-your-queries-are-using-oplogobservedriver).  Closing this since no additional reproduction has come.

**Closed by abernix** 2016-05-25 07:04 UTC
Labels: can't-reproduce
