### ISSUE TITLE
Updating single package not working

### ISSUE THREAD

**Issue by pmuens** [meteor/meteor#4425] opened 2015-05-21 09:11 UTC
I'm facing the problem that I cannot update a single package with e.g. ```meteor update juliancwirko:s-alert```

Maybe related to #3630

Here are the steps to reproduce the issue

```
$ meteor list
--- Omitted packages ---
jquery                            1.11.3_2  Manipulate the DOM using CSS selectors
juliancwirko:s-alert              2.3.1* Simple and fancy notifications / alerts / errors for Meteor
juliancwirko:s-alert-scale        1.0.3* Scale effect for s-alert - simple and fancy notifications / alerts for Meteor.
less                              1.0.14  The dynamic stylesheet language
matb33:collection-hooks           0.7.13  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
--- Omitted packages ---

                                              
* New versions of these packages are available! Run 'meteor update' to try to update those packages to their latest versions. If your packages cannot be updated further,
  try typing `meteor add <package>@<newVersion>` to see more information.
$ meteor update juliancwirko:s-alert
                                                                                   
Changes to your project's package version selections from updating package versions:
                                              
juliancwirko:s-alert  upgraded from 2.3.1 to 2.3.5

$ cat .meteor/versions 
--- Omitted packages ---
json@1.0.3
juliancwirko:s-alert@2.3.1
juliancwirko:s-alert-scale@1.0.3
launch-screen@1.0.2
less@1.0.14
--- Omitted packages ---
```

**Comment by glasser** [comment] 2015-05-26 21:17
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

You didn't provide a full reproduction, but I'm just going to guess that you were also running your app simultaneously in a separate shell.  Is that true?  If so, this sounds like a duplicate of #3582, which still hasn't been released (but is fixed on devel).

**Closed by glasser** 2015-05-26 21:17 UTC
Labels: Project:Tool, Project:Version Solver
