### ISSUE TITLE
Don't recreate the Xcode project on every run or provide the functionality to modify it post-build

### ISSUE THREAD

**Issue by tdesc** [meteor/meteor#3397] opened 2014-12-31 09:12 UTC
Hello,

If you're working with iOS and want to run meteor app on it, we have command
meteor run ios-device --mobile-server blablabla.... 

But, problem is that it recreate xcode project each time you run this command.
Imagine that you make changes in project, add custom cordova plugins, changes xcode settings....
And any changes in meteor js sources not reflected in xcode unless recreate it.

Since browsers on desktop and mobile have completely different behaviour, development for iOS becomes a real pain. 
We need to UPDATE xcode project, not recreate it from scratch each time.

Thanks in advance, you doing really great job, I hope you'll help us to do our part more comfortable way.

**Comment by nickw** [comment] 2015-01-25 20:44
As an example, one of our apps is using [PhoneRTC](https://github.com/alongubkin/phonertc/wiki/Installation), which requires almost 15 configuration changes in Xcode before it can be built properly. We have to perform these changes by hand every time we want to test on iOS.

**Comment by Slava** [comment] 2015-03-24 20:58
@tdesc Hello, Meteor is recreating the Cordova project (and consequently the Xcode project). This is an intended behavior by design of this integration.

The reason to do this: very often, after installing new plugins or adding platforms, the Cordova project would get to a state where it fails to build or link against various components. To avoid this, Meteor recreates the whole project (this usually works well).

I think, the real solution to this, would be an additional functionality to modify the Xcode project with scripts provided by the application developer (similar to the existing Cordova hooks, that Meteor doesn't support).

**Comment by tdesc** [comment] 2015-03-26 08:13
@Slava thanks for reply! 
I can propose solution based on human actions. Just add --update flag to update project www folder without changing project structure itself.
Unfortunately for developers iOS Safari and Android Chrome browsers have numerous differs in behavior and rendering css ( no support of shadow DOM, etc ). Developing mobile application with such cases become complete pain. 
Making changes in project not reflected in mobile code, since it become 'separate branch'. 
Just keep same behavior as it perform now, but add --update flag to sync www folder and code.

**Comment by martijnwalraven** [comment] 2016-02-19 11:10
We no longer recreate the Xcode project on every build (this has been the case since Meteor 1.2), so I'm closing this issue. Note that Cordova still considers the Xcode project a build artifact and doesn't officially support modifying it.

**Closed by martijnwalraven** 2016-02-19 11:10 UTC
Labels: desired, feature, Project:Mobile
