### ISSUE TITLE
[1.4.0.1] Symbol.hasInstance not assignable as a static class method.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#7669] opened 2016-08-19 01:35 UTC
When I run the following code in a Webpack+Babel environment,

``` js
class A {
    static [Symbol.hasInstance](obj) {
        if (this !== A) return super[Symbol.hasInstance](obj)
        return true
    }
}

console.log('What the?', Object.getOwnPropertySymbols(A))
```

the output is

```
What the? [Symbol(Symbol.hasInstance)]
```

but in Meteor the static `Symbol.hasInstance` method does not get set, and the output is

```
What the? []
```

Here is a reproduction. To run:

As a workaround, I found that instead of using `static` in the class declaration I can use `Object.defineProperty` to make it work:

``` js
class A {
}

Object.defineProperty(A, Symbol.hasInstance, {
    value: function(obj) {
        if (this !== A) return Object.getPrototypeOf(A)[Symbol.hasInstance].call(this, obj)
        return true
    }
})

console.log('What the?', Object.getOwnPropertySymbols(A))
```

but the downside is no longer being able to use the less-verbose `super` keyword.

**Comment by trusktr** [comment] 2016-08-19 01:43
Here is a reproduction. To run:

```sh
git clone git@github.com:trusktr/meteor --branch issue-7645 --single-branch
cd meteor
./run-dev.sh
```

**Comment by abernix** [comment] 2016-09-26 12:55
I'll preface this by saying that I'm generally clueless on this topic as it stands as I have yet to use these aspects of ES2015.  It seems to be a much higher-level spec discussion on something that may not be fully finished in various implementations.

While running these snippets _directly_ in Chrome 53 produces the same result, if you run them in Node 4.x or FireFox 49.x, it behaves the same way Meteor currently does (i.e. `Object.getOwnPropertySymbols(A).length === 0`).

Moving onto more recent versions, in FireFox Developer Edition and Node 6 you'll find that`Object.getOwnPropertySymbols(A).length === 1`.  I'm guessing this is because it's just recently been released into those implementations.

I will mark this as confirmed since what you're saying is in fact the behavior shown by this reproduction, but this seems like this might be a case of being too eager to use a feature that is still not fully mature.

**Comment by hwillson** [comment] 2017-11-06 14:03
Looking at the problematic code you've listed:

```js
class A {
    static [Symbol.hasInstance](obj) {
        if (this !== A) return super[Symbol.hasInstance](obj)
        return true
    }
}

console.log('What the?', Object.getOwnPropertySymbols(A))
```

Behind the scenes, Meteor's babel compiled equivalent of this code looks like:

```js
var A = function () {
    function A() {
        (0, _classCallCheck3.default)(this, A);
    }

    A[Symbol.hasInstance] = function (obj) {
        if (this !== A) return Function[Symbol.hasInstance].call(this, obj);
        return true;
    };

    return A;
}();
```

What's interesting here is the `A[Symbol.hasInstance] = ...` part. According to the JS spec, [`Function#@@hasInstance` is not writable](http://www.ecma-international.org/ecma-262/6.0/#sec-function.prototype-@@hasinstance), so this won't work (and is leading to the differences you've noticed). If you try running your code via Babel's live test environment, using the `es2015-loose` preset, you'll get the same problem:

- [Babel repro using `es2015-loose`](http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAECC0G8BQ1XQgFzBglsaA2gMoCeAtgEYD2IAdABaQCSAdpmC8AKYC6AFFQoArAJSIUaSTgBm0Phno4YAQgC8quGIBOXDAFctLdHoAOXLcXLU6jCK3adeA4SImTUO_YegYterm7QAL5IIUjAVGw0XLQgVADmfADkAOqMGD70XAD8SQA00ADywlzAGLTxuoUA7iwAClpUZloYJKSUNBB8sCIiANxAA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=es2015-loose%2Cstage-2&targets=&version=6.26.0)

If you switch to using the `es2015` preset on Babel's site instead, it will work, as it's no longer trying to directly overwrite `Function#@@hasInstance`:

- [Babel repro using `es2015`](http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAECC0G8BQ1XQgFzBglsaA2gMoCeAtgEYD2IAdABaQCSAdpmC8AKYC6AFFQoArAJSIUaSTgBm0Phno4YAQgC8quGIBOXDAFctLdHoAOXLcXLU6jCK3adeA4SImTUO_YegYterm7QAL5IIUjAVGw0XLQgVADmfADkAOqMGD70XAD8SQA00ADywlzAGLTxuoUA7iwAClpUZloYJKSUNBB8sCIiANxAA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=es2015%2Cstage-2&targets=&version=6.26.0)

So it looks like your issue is a result of Meteor leveraging Babel's loose mode. Using loose mode has its pros/cons, so I'm not sure if this issue is enough to consider moving away from loose mode. I'll definitely defer to @abernix and @benjamn here.

**Comment by hwillson** [comment] 2017-12-22 17:41
As mentioned in https://github.com/meteor/meteor/issues/7669#issuecomment-342157203, you're getting this error because Meteor is running Babel transforms in loose mode (for performance and browser-compatibility reasons). Changing this isn't currently planned. Thanks!

**Closed by hwillson** 2017-12-22 17:41 UTC
Labels: bug, confirmed, Impact:few, Project:JS Environment
