### ISSUE TITLE
Changes not always detected when developing on 1.5.2-beta

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#9054] opened 2017-09-01 11:48 UTC
I think there was an issue about this already (supposedly fixed?), but I now have witnessed this behavior multiple times on `1.5.2-beta.13`.

Just now, I was editing a CSS file repeatedly, making quick small changes and saving in-between.

At some point, Meteor just stopped registering changes for that file, which I noticed when I didn't see the expected outcome on my screen.

After killing the `meteor` process and restarting, the changes got picked up.

The relevant build plugin handling that CSS file was `nathantreid:css-modules`.

**Comment by abernix** [comment] 2017-09-05 07:27
Do you still have `METEOR_WATCH_PRIORITIZE_CHANGED` set to a particular value in your current environment?

**Comment by arggh** [comment] 2017-09-05 07:49
Here is my Meteor related env vars:

```
# Meteor
export METEOR_DISABLE_FS_FIBERS=1
export METEOR_PACKAGE_DIRS="$HOME/Development/meteor-packages"
export MONGO_URL=mongodb://localhost:27017/dev
alias meteorbeta="~/Development/meteor/meteor"
alias debugmeteor=~/.meteor/packages/meteor-tool/1.5.2-beta.13/mt-os.osx.x86_64/meteor
```

Also, I was running the customized Meteor tool version with Node argument `--expose-gc` removed, as per our discussions before related to the crashes, though I'm quite sure this used to happen before I changed the tool script.

**Comment by abernix** [comment] 2017-09-05 09:43
By quickly changing CSS styles and saving frequently, I'm able to reproduce this without `nathanreid:css-modules` on 1.5.1 and 1.4.4.3 as well (I haven't gone back further), so this doesn't seem isolated to Meteor 1.5.2 (beta).

For you (personally) would you say that this was certainly not happening before 1.5.2?

**Comment by arggh** [comment] 2017-09-05 09:47
> For you (personally) would you say that this was certainly not happening before 1.5.2? Or is it possible it's been a problem for a while?

Definitely can _not_ certainly say it hasn't happened before `1.5.2`. My memory fails, but I'm thinking this has been an issue before, declared as fixed. I just noticed it again while using `1.5.2-beta`

**Comment by arggh** [comment] 2017-09-05 09:48
Probably the frequent crashes prevented me from actually noticing the issue before. Now Meteor is not crashing anymore, so then this becomes the next problem!

**Comment by abernix** [comment] 2017-09-05 11:09
I'm able to reproduce this with a variation of the [`css hot code push` test]() which does something along the lines of (this may be extreme, but it seems to show the problem):

```js
s.write("test.css", "body { background-color: blue; }"); // rgb(0, 0, 255) - 2 changes
utils.sleepMs(500);
s.write("test.css", "body { background-color: burlywood; }") // rgb(222, 184, 135) - 3 changes
utils.sleepMs(500);
s.write("test.css", "body { background-color: cornflowerblue; }"); // rgb(100, 149, 237) - 4 changes
utils.sleepMs(500);
s.write("test.css", "body { background-color: ghostwhite; }"); // rgb(248, 248, 255) - 5 changes
utils.sleepMs(500);
s.write("test.css", "body { background-color: floralwhite; }"); // rgb(255, 250, 240) - 6 changes
utils.sleepMs(500);
s.write("test.css", "body { background-color: rebeccapurple; }"); // rgb(102, 51, 153) - 7 changes
run.match(/background-color: (rebeccapurple|rgb\(102, 51, 153\))/);
```

I can't get this test to end with `floralwhite` or `rebeccapurple` colors.  Playing around with the `sleepMs` I can get varying degrees of success.

The good news is it's not "stuck" in that state forever – one more save to the file and it updates again, but this could still be quite annoying, especially working with CSS.  I'm not entirely surprised if this existed already, especially since we've seen spurious failures in that test (existing) before.  We'll need to shore it up a bit, add a test to replicate rapid file changes, and see about fixing it.

Seeing as this problem seems to have existed before 1.5.2 (and I can't prove it's any more pronounced than before) coupled with the fact that Meteor 1.6 will make it much less painful to debug something like this (thanks to Node's `--inspect`), I'm going to say we slate this for after 1.5.2.

**Comment by brucejo75** [comment] 2017-09-05 23:10
Tossing in a couple of comments.  This issue has been nagging me ever since I filed this issue: #8075.

I have noticed that these changes to my work habits have reduced the incidence of this issue:
- I noticed that if I ever did a save during a build, Meteor would get pretty confused.  And it would possibly get so confused that it somehow would not recognize any other updates thereafter.  (Don't save during a build)
- I upgraded to SSD's for my project directory.  This has the effect of making my builds go faster.
- I had editors and anti-malware tools monitoring all of my build directories which was also causing some pain during the build I [turned off their monitoring](https://forums.meteor.com/t/10x-build-speed-improvement/37429) (and got a bug fix from VSCode).  Now my builds go a lot faster.

So my incidence of this problem has been reduced.  But occasionally, I will be building a new project.  Even one as simple as what `meteor create` produces.  I think it is often times associated with saving a file during a build.

### Suggestions for repro
- use a Hard drive (maybe even a slow one)
- leave your editor / anti-malware monitoring on

**Comment by hwillson** [comment] 2018-02-14 12:13
There have been additional file watching changes since 1.5.2, so please try using Meteor 1.6.1 and let us know if this is still happening. Closing for now - thanks!

**Closed by hwillson** 2018-02-14 12:13 UTC
Labels: Impact:few, Project:CSS, Project:Tool, Severity:has-workaround, bug, confirmed
