### ISSUE TITLE
Document how to clean up old Android SDKs when upgrading to Meteor 1.2

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#5150] opened 2015-09-14 04:16 UTC
Hey,
just read that Meteor 1.2 will now use a local installation of Android Studio and its SDK tools. Now I've the question if there is a command or recommend way to remove Meteors SDK installation from my Mac?

**Comment by martijnwalraven** [comment] 2015-09-14 13:12
Good point, we should at least document this somewhere. You can remove the bundled Android tools using `rm -rf ~/.meteor/android_bundle`.

**Comment by rjakobsson** [comment] 2016-10-26 17:04
This could be closed.

**Comment by abernix** [comment] 2016-10-28 14:59
@rjakobsson Excuse my unfamiliarity with the issue here – is this documented now?  Or no longer relevant?  I agree that it's for an old version of Meteor, but not sure if the problem is gone completely.

**Comment by rjakobsson** [comment] 2016-10-28 16:23
My understanding is that Meteor no longer offer documentation for when upgrading from 1.1 => 1.2. There is no place to make documentation from this information. The issue is still there, but as long as this issue is not deleted, it's still searchable and discoverable.

**Comment by rjakobsson** [comment] 2016-10-30 21:40
Is there a plan to add documentation for versions pre Meteor 1.2?

**Comment by abernix** [comment] 2016-10-31 08:24
I see.  And looking at it some more, it doesn't seem that this affecting many.  This issue has not received much attention nor does a cursory search return a recurring trend of similar questions.  I think it makes sense to close this now.

Most of the core 1.2 stuff is still documented in the current docs, even if it's combined with newer features that might not be available.  The breaking changes for 1.2 are still listed [here](https://github.com/meteor/docs/blob/master/long-form/breaking-changes-1.2.md) and that's linked from the [`History.md`](https://github.com/meteor/meteor/blob/devel/History.md) which seems sufficient.

Thanks again for looking at it.

**Closed by abernix** 2016-10-31 08:24 UTC
Labels: Project:Docs, Project:Mobile
