### ISSUE TITLE
[1.6.0.1] Exception in defer callback: TypeError: func is not a function

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#9486] opened 2017-12-19 18:05 UTC
```
Exception in defer callback: TypeError: func is not a function
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
at packages/meteor.js:452:25
at runWithEnvironment (packages/meteor.js:1188:24)
```

**Comment by hwillson** [comment] 2017-12-19 20:24
@WayneUong Can you provide more context around how you got this error?

**Comment by WayneUong** [comment] 2017-12-19 21:37
@hwillson The error appears randomly without any context. I assume it comes from a cron job, but it's hard to trace which one. We use this package for running cron jobs: https://github.com/percolatestudio/meteor-synced-cron

**Comment by hwillson** [comment] 2017-12-20 13:17
Okay, thanks @WayneUong. There really isn't much here for us to go on then. If we can't tell what's causing the error, we have no way of knowing if it's really a Meteor issue, or a problem caused by some external factor. Unfortunately, without more troubleshooting details, there isn't much we can do here. If you're able to track down anything additional that could help with troubleshooting, please post back and let us know. I'll close this for now, but I'm happy to re-open if you come across anything additional. Thanks!

**Closed by hwillson** 2017-12-20 13:17 UTC

**Comment by lmachens** [comment] 2018-04-05 06:31
I got the same error when using `Meteor.defer` the wrong way:

```
const f = () => {};
Meteor.defer( f() );
```
Correct version:
```
const f = () => {};
Meteor.defer( f );
```

Maybe you had a similar call?
