### ISSUE TITLE
JS not working/loading on Android device but works in emulator, browser and iOS

### ISSUE THREAD

**Issue by adamgins** [meteor/meteor#4741] opened 2015-07-14 01:51 UTC
Hi, I am struggling with trying to understand why my click events are not working on an actual Android Device but they work in the Android Emulator.

from:

I seem to have done something to my project to make Android stop listening to my clicks.

I posted here too: https://forums.meteor.com/t/notes-on-fastclick-for-android-devices/4744/3

My iOS app works fine... it accepts touch as clicks. The Android Emulator works fine too. Your work around works too.

However, on the Android physical devices it's does not work. I tried your workaround and deployed to 2 two physical local Android devices (one 4.4.4 and one 5.0.1) and they won't accept click on buttons. Links (hrefs )work fine.

My previous APK (in Playstore) works fine on those same physical devices... and all the updated to the server and deployed via hot-reload seem to work too. So it's just the current version freshly installed on to the physical devices. So I am thinking it's some Cordova plugin or update to a Cordova plugin... or more likely something else I have done???

the code looks like:

```
 'click #login-with-google': function(e, template) {
        alert("login")
       gLoginWithGoogle();

    },
```

The alert shows in the Android Emulator. It works on iOS devices. It works in the browser on the Android Device. Nothing happens except the button getting a yellow border on Cordova on the Android device.

I don't see any specific errors on the local server console.

I do see the following in the log, not sure if it's related:

```
Launching application...
LAUNCH SUCCESS
Command finished with error code 0: /Users/adamginsburg/Documents/Development/buzzy7/.meteor/local/cordova-build/platforms/android/cordova/run --device
I20150713-21:16:26.899(10) (android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Error reading version file Error: Failed to resolve entry: file:///data/data/buzz.buzzy.my1/files/meteor/version
I20150713-21:16:26.900(10) (android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Couldn't load from the manifest, falling back to the bundled assets.
I20150713-21:16:27.073(10) (android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local
```
Any ideas, pls?

Additional info: After further tests, it seems like the whole app is kinda broken on Android. I put in 'Template.signIn.onCreated' and 'Template.signIn.onRendered' with some basic logging and nothing shows. I don't see anything on the console that's letting me know if something is wrong. Is there some other way to debug the Android app?
 
Further update: the click not working is just a small bit... basically as the sign in page did not have much on it... I did not pick up on that. For some reason the Javascript for the templates is not loading/running.. and not errors in the console. Could be load order. Again not sure why this only happens on Android? (wondering if the load order/precedence of files is different to other Cordova and web?)

**Comment by adamgins** [comment] 2015-07-15 09:02
Ok, some more info: 

I have some code in a:

```
if (Meteor.isClient){
   Meteor.startup(function () {
       console.log("Show Domain:",  window.location.hostname);
   }
 
}
```
and the result of: ` window.location.hostname` is blank.

I have tried playing around with the load order, moving things into `lib` folders and renaming files `1_filename` etc but can't seem to get this to work. 

The weird things is I had a link to an external site, I placed the following in mobile-config.js: `App.accessRule('*') and then clicked a link to external site. I see the following in the console:

```
I20150715-18:58:57.082(10) (android:https://www.buzzy.buzz/b800fc8817dd92e8e7e3e95dce8869493050e19b.js:928) WaitOn resourcePageLImit
I20150715-18:59:00.122(10) (android:https://www.buzzy.buzz/:0) XMLHttpRequest cannot load https://buzzy.buzz/_timesync. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.buzzy.buzz' is therefore not allowed access.
I20150715-18:59:00.127(10) (android:https://www.buzzy.buzz/b800fc8817dd92e8e7e3e95dce8869493050e19b.js:3) Error syncing to server time: 
I20150715-18:59:00.737(10) (android:https://www.buzzy.buzz/b800fc8817dd92e8e7e3e95dce8869493050e19b.js:928) WaitOn resourcePageLImit
I20150715-18:59:00.753(10) (android:https://www.buzzy.buzz/b800fc8817dd92e8e7e3e95dce8869493050e19b.js:928) user not logged in - routing to start
I20150715-18:59:00.771(10) (android:https://www.buzzy.buzz/b800fc8817dd92e8e7e3e95dce8869493050e19b.js:928) WaitOn resourcePageLImit
I20150715-18:59:00.856(10) (android:https://www.buzzy.buzz/b800fc8817dd92e8e7e3e95dce8869493050e19b.js:1097) layout public onCreated
I20150715-18:59:01.120(10) (android:https://www.buzzy.buzz/b800fc8817dd92e8e7e3e95dce8869493050e19b.js:1097) layout public onRendered

```
After that everything starts working. The JS works, the clicks work etc etc ... it's like the error got things going. Any ideas?

**Comment by martijnwalraven** [comment] 2015-07-21 20:57
These types of issues are often caused by JavaScript errors. Have you tried using Chrome remote debugging to see if that is the case?

**Comment by adamgins** [comment] 2015-07-27 02:13
@martijnwalraven I seem to have bypassed this by testing out as an Alpha app on the playstore and it just worked. So this issue was specific to running the app with a USB cable from computer to chrome device. 

I have not debugged it further, so not sure if you want to leave this open till I give it another crack and try see what's happening with Chrome Remote?

**Comment by martijnwalraven** [comment] 2015-07-27 02:52
Good to hear you've managed to get around the problems. Because the issue doesn't have a full reproduction, I'm going to close it. If you run into similar problems in the future, please open a new issue.

**Closed by martijnwalraven** 2015-07-27 02:52 UTC
Labels: Project:Mobile

**Comment by adamgins** [comment] 2015-07-27 03:09
Thanks @martijnwalraven 

Is there a cheatsheet, please, to get the chrome://inspect/#devices working?

I see http://www.adamwadeharris.com/remote-debugging-in-phonegap-with-chrome-devtools/ but was not sure if there is some setting we should be doing from mobile-config.js instead?

I see the following in my desktop browser:

![image](https://cloud.githubusercontent.com/assets/7233741/8897921/8aee06be-3460-11e5-886d-e197bf5f6ea4.png)

**Comment by martijnwalraven** [comment] 2015-07-27 03:19
As far as I know (I can't test it right now), that description is still accurate. Cordova should take care of the setWebContentsDebuggingEnabled call for debug builds automatically.

**Comment by pors** [comment] 2015-09-07 16:46
@adamgins did works for me: https://developer.chrome.com/devtools/docs/remote-debugging
