### ISSUE TITLE
Why is "/imports/example/client/index.ts" not import-able server side ?

### ISSUE THREAD

**Issue by ArThoX** [meteor/meteor#7613] opened 2016-08-09 17:11 UTC
Hi

Here is a part of my project folder structure
```
/imports            /business         /client                 /private
(shared modules)   (business logic)  (understand customer)    (what is not public to everyone)
```

Server code
`import '../imports/business/client/private';`

fails with 

`W20160809-17:44:12.739(1)? (STDERR) Error: Cannot find module '../imports/business/client/private'`

However if I change the name of `client` to `client-profile` for instance, it works.

**Is that the expected behavior ? Shouldn't server/client directory filter based on the server/client execution be ignored given the fact that the `client`folder is not at the root and behind `imports` ?**
 
Regards

**Comment by Anima-t3d** [comment] 2016-08-10 09:25
Based on [structuring imports guide](https://guide.meteor.com/structure.html#structuring-imports) it seems the expected behaviour (client/server/startup)

**Comment by skirunman** [comment] 2016-08-10 17:23
Yes, this is the expected behavior. `/client` and `/server` are processed "specially" by the Meteor build tool even if they are located inside `/imports`.

**Comment by laosb** [comment] 2016-08-10 22:06
Yes, it's intended. You should just change the folder name. Closing.

**Closed by laosb** 2016-08-10 22:06 UTC

**Comment by ArThoX** [comment] 2016-08-11 09:27
Allright.
mv client client_ :'(
