### ISSUE TITLE
Meteor 1.6-beta.26 not working with the force-ssl package and --production flag

### ISSUE THREAD

**Issue by aliogaili** [meteor/meteor#9072] opened 2017-09-10 09:05 UTC
The force-ssl package is not working with Meteor 1.6-beta.26. 

To reproduce:

1. Create a new project with Meteor 1.6-beta.26 ( `meteor create test1.6 --release 1.6-beta.26` )
2. `meteor run --production`
3. Confirm app is loaded
4. Add force-ssl package `meteor add force-ssl `
5. App no longer loaded and `ERR_CONNECTION_REFUSED` is thrown

Once I deploy the project, I'm not running into this issue. 

- The version of Meteor showing the problem: **Meteor 1.6-beta.26**
- The last version of Meteor where the problem did _not_ occur: **Meteor 1.5.2**
- The operating system you're running Meteor on: **MAC OS**
- The expected behavior: **Meteor client connect to the server** 
- The actual behavior:  **Site can't be reached with console error GET http://localhost:3000/ net::ERR_CONNECTION_REFUSED**

**Comment by klaussner** [comment] 2017-09-10 10:01
The `ERR_CONNECTION_REFUSED` error happens because `force-ssl` redirects `http://localhost:3000` to `https://localhost` when Meteor is run in production mode. I quickly tried to reproduce it with the beta versions I have installed and it looks like the bug was introduced somewhere between `1.6-beta.20` and `1.6-beta.26`.

**Comment by klaussner** [comment] 2017-09-11 10:18
I've narrowed it down to this commit: https://github.com/meteor/meteor/commit/1caa9ce66c3e1da944130898216dd457a02c08fb (part of PR #8702).

**Comment by aliogaili** [comment] 2017-09-11 10:29
I'm not familiar with the code, but I can't see how this commit is causing the issue, it seems like a conditional path for supporting unix sockets. 

Unless maybe there is something wrong with this check 
```
 if (typeof localPort == "number")
     {
       var listenOptions = { port: localPort, host: host };
     }
```
@klaussner  are you sure it's caused by this?

**Comment by hwillson** [comment] 2017-09-11 14:50
Hi guys - `force-ssl`'s [`isLocalConnection`](https://github.com/meteor/meteor/blob/d416ed913dc3a465c89d02cb2bdb07cadfa512f7/packages/force-ssl-common/force_ssl_common.js#L6-L22) function is showing the connection as not local. This is because one of the HTTP forwarded parameters it's checking is `::ffff:127.0.0.1`, which fails  `isLocalConnection`'s localhost regex. `::ffff:127.0.0.1` is a valid localhost address though - `::ffff:` is the subnet prefix for 32 bit IPv4 addresses used in IPv6 (128 bit) land. The easy fix for this is to update the `isLocalConnection` function to include `::ffff:127.0.0.1` (which it really should regardless). I can take care of this, but it would be interesting to track down the source of the connection address change. The [`request.connection`](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_request_connection) used is coming directly from Node, so it's likely something has changed in Node land that caused this. I'll dig a bit deeper, but for now I'll post a `force-ssl` PR to address this (since again that change should be made regardless). More details shortly - thanks!

**Comment by aliogaili** [comment] 2017-09-11 15:00
Thanks for the insight @hwillson!  but I'm wondering why does this behavior only happens with the production flag?

**Comment by hwillson** [comment] 2017-09-11 15:16
`force-ssl` is a `prodOnly` package. When you're running locally with the `--production` flag, you're triggering the `force-ssl` package. You're then failing the `isLocalConnection` check locally only (it's returning `false` when it should be returning `true`); in your production environment `isLocalConnection` is already returning `false`, which is correct.

**Comment by aliogaili** [comment] 2017-09-11 15:29
Thank you so much @hwillson ! looking forward for the PR :-)

**Comment by klaussner** [comment] 2017-09-11 21:46
@aliogaili I checked it again (manually and with `git bisect`)—https://github.com/meteor/meteor/commit/1caa9ce66c3e1da944130898216dd457a02c08fb  is the first commit where the error occurs. 🤔

**Comment by aliogaili** [comment] 2017-09-12 03:07
I think you're right @klaussner, there might be a bug in this code, I think it's failing to specify the host c[ausing the node to accept connections on the unspecified IPv6 address](https://github.com/nodejs/node/blob/v8.x-staging/doc/api/net.md) (::).

The bug might have been introduced by this [line](https://github.com/meteor/meteor/blob/e94349937efc1fb0f37dc8f35cf3d938de792410/packages/webapp/webapp_server.js#L902): 

`var listenOptions = { port: localPort, host: host };`

I think host must have been the localIp var.

@hwillson why host was used here instead of localIp? most likely that's the bug.

**Comment by hwillson** [comment] 2017-09-12 11:29
Awesome @klaussner and @aliogaili - that makes sense to me! @klaussner has submitted a fix for this via https://github.com/meteor/meteor/pull/9083, so that's great. I think it still makes sense to keep the `force-ssl` change in place though, since `::ffff:127.0.0.1` is a valid local address (and this might prevent some other issue in the future). Thanks all!

**Closed** 2017-09-13 15:39 UTC
Labels: bug, confirmed, Project:Webapp:Force SSL

**Comment by abernix** [comment] 2017-09-15 10:38
This is hopefully fixed with `force-ssl@1.0.15` thanks to @hwillson's work.  Please test by running:

    meteor update force-ssl

Please report back if it doesn't work (and even if it **does** work too!) 😄

**Comment by aliogaili** [comment] 2017-09-15 15:40
It's working great now, thanks for the support folks :)

**Comment by paulincai** [comment] 2018-01-17 18:28
@abernix @hwillson I use force-ssl@1.1.0 and trying my first ios-device builds with METEOR@1.6.1-rc.6.

Without running Cordova everything looks fine. Within my local network I can access the local server from my Iphones in the browser. Once I start an ios-build, the Iphone browser is being directed to https://localhost. Safari debug window for my iphone shows: "Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made."
Cordova is not connecting.

I think this issue might be back in the bundle.

Remove force-ssl fixes the problem in both remote device browser and Cordova.
