### ISSUE TITLE
App lags after updating to meteor 1.10.1

### ISSUE THREAD

**Issue by longyarnz** [meteor/meteor#10990] opened 2020-03-28 12:27 UTC
I noticed a slight change with meteor build performance in the latest version 1.10.1. The app rebuilds faster especially with --exclude-args but it loads slower on the browser. Simply clicking refresh on the browser while the app is fully loaded takes a couple of seconds (~10s). The browser displays a blank screen during this time, there are no files loaded and no requests on the network tab until. The HTML, CSS and other media start to load after ~10s. Meanwhile, the app is fully loaded in the terminal and there are no activities going on.

**Comment by longyarnz** [comment] 2020-03-28 12:27
I downgraded to 1.8 and the issue was gone. The speed of the app in the browser was back to normal.

**Comment by KoenLav** [comment] 2020-03-29 07:36
Could you take a look at the size of all the JS files which are sent (from the network tab in Chrome)?

**Comment by longyarnz** [comment] 2020-03-29 07:44
Sure

**Comment by longyarnz** [comment] 2020-03-29 07:55
It's 32.7MB

It takes a considerable amount of time to paint anything on screen which was not so in the previous version.

**Comment by KoenLav** [comment] 2020-03-29 07:59
And I assume 1.8 it is less? (Which version of 1.8 btw?) 

This may be related/similar to: https://github.com/meteor/meteor/issues/10712

**Comment by longyarnz** [comment] 2020-03-29 08:04
Yeah, 1.8.1

**Comment by longyarnz** [comment] 2020-03-29 08:08
I'll comb through the app for destructured imports

**Comment by longyarnz** [comment] 2020-03-29 08:28
Yeah, I found a couple of destructured imports from material-ui icons. I removed them and the app loads fine 😀
Thank you very much @KoenLav

**Comment by KoenLav** [comment] 2020-03-29 08:34
Great to hear.

This does mean that issue has reappeared on 1.10 or it was never really fixed.

**Comment by longyarnz** [comment] 2020-03-29 09:01
I hope it gets fixed. I am new to meteor and I never would have found this if you didn't point it to me. I can safely close this now.

**Comment by KoenLav** [comment] 2020-03-29 09:18
@longyarnz let's keep this open because this should be fixed in Meteor.

**Comment by longyarnz** [comment] 2020-03-29 09:20
OK

**Comment by filipenevola** [comment] 2020-03-30 20:04
Hi @KoenLav I'm not sure if I understand what is the issue to be fixed here.

Could you clarify?

**Comment by KoenLav** [comment] 2020-03-30 20:07
@filipenevola Meteor should not take 10 seconds to load when using destructuring imports?

Also the original issue I linked mentions that this should be fixed, but it appears not to be.

**Comment by KoenLav** [comment] 2020-03-30 20:08
I think the minimal repro listed there might not cause the issue to surface (as soon)?

**Comment by filipenevola** [comment] 2020-03-30 20:37
Correct me if I'm wrong but I think what is happening, as Meteor does not have tree-shaking yet, is that when you import with destructuring the `material-icons` you are importing all the icons and then it's making the client bundle huge and that is adding this delay.

In my Meteor apps, I use `material-icons` but as I don't want to have a huge client bundle I'm always using direct imports for each icon to avoid the huge bundle.

So I think the problem is the huge bundle and not an issue in Meteor.

Am I missing something here?

**Comment by KoenLav** [comment] 2020-03-30 20:49
@filipenevola yeah, you're missing the fact that this worked fine in Meteor 1.8.1 and before but was somehow broken in 1.8.2.

Also when I take a normal webpack setup, without tree shaking, and use destructured imports it does cause a large bundle but no significant delay.

**Comment by AlanOrtega91** [comment] 2020-04-15 23:46
I also have this problem.
Updated from 1.8.1 to 1.10.1 and loading times whent from 3s max to 1min.
tree shaking material-ui icons was the issue hope this gets fixed.
Meanwhile I'll be importing the icons differently

**Comment by LaloMores** [comment] 2020-04-16 05:36
Same problem.
VERY difficult to spot! (The same does not happen for material-ui/core, or at least I think it does not: I have my code full of @material-ui/core destructured imports).

[This issue](https://github.com/meteor/meteor/issues/10712) stated the original problem.

**Comment by lyslim** [comment] 2020-05-08 03:58
I also had this problem - initial loading of the app went pretty slow after upgrading from 1.8.1 to 1.10.1

Had to workaround like @LaloMores (big thanks!) suggested in my thread [here](https://forums.meteor.com/t/initial-loading-becomes-very-slow-after-upgrading-to-1-10-1/52409/13)..

Hope Meteor would fix this soon...

**Comment by sebakerckhof** [comment] 2020-05-12 08:15
Closing as duplicate of https://github.com/meteor/meteor/issues/10712

**Closed by sebakerckhof** 2020-05-12 08:15 UTC
