### ISSUE TITLE
Meteor.user() and Meteor.userId() are not reseted on client after logout on server side

### ISSUE THREAD

**Issue by JD2k** [meteor/meteor#11843] opened 2022-01-10 16:47 UTC
When i delete the resume token in mongo db for a currently logged in user, my assumption would be that Meteor.user() and Meteor.userId() would be reseted.

For this case my tracker is working in meteor version 1.9:

`const useAccount = () => useTracker(() => {
    return Meteor.userId()
}, [])`

This tracker does not fire in version 2.2 and not in 2.5.3 

Are there some undocumented changes, maybe this is not the right way to track if the user is logged in.

**Comment by JD2k** [comment] 2022-01-10 18:59
Found the reason in file accounts_client.js (accounts-base package).

In method onResultReceived:

````
    const onResultReceived = (err, result) => {
      if (err || !result || !result.token) {
        // Leave onReconnect alone if there was an error, so that if the user was
        // already logged in they will still get logged in on reconnect.
        // See issue #4970.
      } else {
````

So i changed it:

````
    const onResultReceived = (err, result) => {
      if (err || !result || !result.token) {
        // Leave onReconnect alone if there was an error, so that if the user was
        // already logged in they will still get logged in on reconnect.
        // See issue #4970.
        if(err.error === 403) {
          // Error 403: reason: "You've been logged out by the server. Please log in again."
          // So we make a complete logout
          this.makeClientLoggedOut()
        }
      } else {
````

Maybe someone can tell me if this is the right way, and if this should be included in the next update?

**Comment by WilliamKelley** [comment] 2022-01-12 16:43
Can you paste the code you're using to remove the login resume token?

What you're describing is not part of the Accounts module's exposed API, you're modifying a protected field essentially. But, it's not too far off from what the module itself does sometimes.

**Comment by JD2k** [comment] 2022-01-12 16:47
Yes of course:

```
Accounts.onLogin(function () {
        Meteor.logoutOtherClients()
    });
```

My hook for determine if a user is logged in looks like this:

```
const useAccount = () => useTracker(() => {
    return Meteor.userId()
}, [])
```

My overall use case is to make sure a user is only on one browse logged in at the same time.

**Comment by WilliamKelley** [comment] 2022-01-14 20:44
Ah okay, so you are using the API. Yes it seems that this should be handled in that error flow. It seems like there's no test for this exact case. You're proposed solution seems reasonable to me, but I'm not knowledgeable enough to know if the previously commented case about `onReconnect` will trigger a 403 error and would be wrongfully affected. Will need a core contributor's opinion.

**Comment by JD2k** [comment] 2022-08-10 09:10
Is it possible to add this solution to next Meteor version? Currently i am adjusting this package in any new project.

**Comment by Grubba27** [comment] 2023-05-31 14:40
Hey @JD2k I think this issue _maybe_ related to the react-packages, but I would like a repo so I could reproduce and try to make this work.
Which version are you using? did you solve this, if yes, how?

**Comment by Grubba27** [comment] 2023-06-14 15:42
Since we have not seen any movement around here, this issue seems like it was solved. I will be closing this one for now.
If it is still happening or we have a reproduction we can work on, I will happily reopen this one.

**Closed by Grubba27** 2023-06-14 15:42 UTC
Labels: Project:Accounts (in user apps), needs-reproduction, needs-investigation
