### ISSUE TITLE
Allow Meteor to Install inside a custom location

### ISSUE THREAD

**Issue by arunoda** [meteor/meteor#2268] opened 2014-07-01 06:09 UTC
This is can be easily done as following

![screen shot 2014-07-01 at 11 38 22 am](https://cloud.githubusercontent.com/assets/50838/3439472/3017e18c-00e6-11e4-94c8-3e679f67aacc.png)

Then user has to do this

``` bash
export PREFIX=$HOME #to install on the home directory
curl https://install.meteor.com | /bin/sh
```

Please update the install script. 
- [Updated Script](https://gist.github.com/arunoda/e75a8bc55e65bc07b11f/revisions)

**Comment by il-katta** [comment] 2015-05-23 12:53
I think that sudo is usefull if you have no write permission in the destination dir. But if you have permission to write in the destination ... why use sudo ?

```
do_as_su () {
    if type sudo >/dev/null 2>&1; then
        sudo $@
    else
        su -c "$@"
    fi
}

[...]

if ! mkdir -p -m 755 $PREFIX &>/dev/null  ; then
    do_as_su mkdir -p -m 755 $PREFIX
fi
if ! mkdir -p -m 755 $PREFIX/bin &>/dev/null  ; then
    do_as_su mkdir -p -m 755 $PREFIX/bin
fi
```

**Comment by glasser** [comment] 2015-07-14 23:48
Reopening as a [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by marcomorain** [comment] 2015-12-02 10:40
This is an issue for any users of CircleCI too. We would love to see this implemented too.

**Comment by Sanjo** [comment] 2015-12-02 17:29
@marcomorain On CircleCI you can just do:

```
# Restore meteor symlink when Meteor was restored from the cache
- if [ -d ~/.meteor ]; then sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor; fi
# Download Meteor if isn't already installed via the cache
- if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi
```

**Comment by hwillson** [comment] 2017-03-31 10:28
This is a duplicate of issue #8489 (which has a detailed explanation of why this feature won't be implemented in https://github.com/meteor/meteor/issues/8489#issuecomment-286812145). As mentioned in https://github.com/meteor/meteor/issues/2268#issuecomment-161372809, there are workarounds for handling this within CI tools. Closing - thanks!

**Closed by hwillson** 2017-03-31 10:28 UTC
Labels: Project:Installer

**Comment by Zodiase** [comment] 2017-03-31 19:03
@hwillson Funny how an old issue is closed as a duplicate of a way newer issue. (-___,-)

**Comment by hwillson** [comment] 2017-03-31 19:06
@Zodiase Haha - I wasn't really closing this as a duplicate of the newer issue, to keep the newer issue open - the newer issue was already closed. It's just that the newer issue already listed the reason why this issue can also be closed. We're trying to get through reviewing all old issues as part of an on-going old issue cleanup process, so things like this are bound to happen. Sorry for any confusion!
