### ISSUE TITLE
[1.4.3.2] Cannot find module 'is-property'

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#8563] opened 2017-04-05 00:13 UTC
i tried: `meteor add-platform android`
and here is error:
```
Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bu
ndle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-js
on-valid\node_modules\generate-object-property\index.js:1:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle
\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bu
ndle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-js
on-valid\index.js:1:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle
\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bu
ndle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\lib\runner.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle
\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bu
ndle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\lib\index.js:4:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle
\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bu
ndle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\lib\har.js:5:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle
\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bu
ndle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\request.js:26:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle
\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bu
ndle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:145:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle
\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bu
ndle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle
\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\cordova-lib\node_modules\npm\node_modules\npm-registry-client\index.js:73:20
    at Array.forEach (native)
    at CachingRegistryClient.RegClient (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.
x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\index.js:51:42)
    at new CachingRegistryClient (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32
\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\lib\cache\caching-client.js:20:18)
    at C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\cordova-lib\node_modules\npm\lib\npm.js:369:22
    at C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\cordova-lib\node_modules\npm\lib\config\core.js:82:7
    at Array.forEach (native)
    at C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\cordova-lib\node_modules\npm\lib\config\core.js:81:13
    at f (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_mod
ules\cordova-lib\node_modules\npm\node_modules\once\once.js:25:25)
    at finalize (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\n
ode_modules\cordova-lib\node_modules\npm\lib\config\core.js:200:5)
    at afterExtras (C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\li
b\node_modules\cordova-lib\node_modules\npm\lib\config\core.js:191:5)
    at C:\Users\lynam\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\cordova-lib\node_modules\npm\node_modules\mkdirp\index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)
```

i'm using on windows 10 x64, nodejs 6

**Comment by hwillson** [comment] 2017-04-05 01:39
Duplicate of #7358 (see https://github.com/meteor/meteor/issues/7358#issuecomment-231144281 in particular for a potential solution). Closing - thanks!

**Closed by hwillson** 2017-04-05 01:39 UTC
