### ISSUE TITLE
Can't upgrade to version 1.5.2

### ISSUE THREAD

**Issue by p3pp8** [meteor/meteor#9064] opened 2017-09-07 09:06 UTC
Can't update to version 1.5.2 as one or more of the following packages, after upgrading, breaks my app:
```

babel-compiler         upgraded from 6.19.4 to 6.20.0
boilerplate-generator  upgraded from 1.1.1 to 1.2.0
ddp-client             upgraded from 2.0.0 to 2.1.0
ejson                  upgraded from 1.0.13 to 1.0.14
minimongo              upgraded from 1.2.1 to 1.3.0
modules                upgraded from 0.9.4 to 0.10.0
mongo                  upgraded from 1.1.22 to 1.2.0
mongo-dev-server       added, version 1.0.1
promise                upgraded from 0.8.9 to 0.9.0
webapp                 upgraded from 1.3.17 to 1.3.18


```
None of my code is executed, instead the following exception arises immediately after trying to open the app index page. It seems to be an internal error, i'm stuck at version 1.5.1.
```

E20170907-10:48:33.442(2) (webapp_server.js:789) Error running template: TypeError: _.escape is not a function
    at eval (eval at <anonymous> (packages/underscore.js:1266:16), <anonymous>:6:28)
    at template (packages/underscore.js:1274:21)
    at packages/boilerplate-generator/template-web.browser.js:29:7
    at Array.map (native)
    at Function._.map._.collect (packages/underscore.js:157:56)
    at Boilerplate.template (packages/boilerplate-generator/template-web.browser.js:28:7)
    at Boilerplate.toHTML (packages/boilerplate-generator/generator.js:30:12)
    at packages/webapp/webapp_server.js:322:33
    at /Users/Giuseppe/.meteor/packages/promise/.0.9.0.153itm7++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:39
Y

```
Any help is highly appreciated!

Thanx!

METEOR LIST
```

abernix:standard-minifier-js   2.1.0  Harmony javascript minifiers used with Meteor apps by default.
awatson1978:browser-detection  1.0.4  Meteorite package that provides browser detection.
base64                         1.0.10  Base64 encoding and decoding
deanius:promise                3.1.3  Utilities for Promise-based wrappers, method calls, helpers and HTTP in Meteor
dynamic-import                 0.1.1  Runtime support for Meteor 1.5 dynamic import(...) syntax
email                          1.2.3  Send email messages
es5-shim                       4.6.15  Shims and polyfills to improve ECMAScript 5 support
http                           1.2.12  Make HTTP calls to remote servers
iron:router                    1.1.2  Routing specifically designed for Meteor
jquery                         1.11.10  Manipulate the DOM using CSS selectors
meteor-base                    1.1.0  Packages that every Meteor app needs
mobile-experience              1.0.4  Packages for a great mobile user experience
pbastowski:angular-babel       1.3.7  Babel compiler and ng-annotate for Meteor 1.3
reactive-var                   1.0.11  Reactive variable
rwatts:uuid                    0.1.0  Easily generate a UUID on the client or server.
session                        1.1.7  Session variable
standard-minifier-css          1.3.4  Standard css minifier used with Meteor apps by default.
tarang:ssl                     1.0.1  Secure your application
tracker                        1.1.3  Dependency tracker to allow reactive callbacks
u2622:persistent-session       0.4.4  Persistently store Session data on the client
urigo:static-templates         0.1.3  Meteor plugin for importing static HTML templates"


```
NPM DEPENDENCIES

    "@uirouter/angularjs": "^1.0.6",
    "amqp": "^0.2.6",
    "angular": "^1.6.6",
    "angular-animate": "^1.6.6",
    "angular-aria": "^1.6.6",
    "angular-filter": "^0.5.16",
    "angular-i18n": "^1.6.6",
    "angular-material": "^1.1.5",
    "angular-messages": "^1.6.6",
    "angular-meteor": "^1.3.12",
    "angular-qr": "^0.2.3",
    "angular-sanitize": "^1.6.6",
    "angular-translate": "^2.15.2",
    "aws-sdk": "^2.110.0",
    "babel-runtime": "^6.26.0",
    "big-integer": "^1.6.25",
    "blob-stream": "^0.1.3",
    "cryptico": "^1.0.2",
    "deepmerge": "^1.5.1",
    "excel4node": "^1.2.1",
    "google-libphonenumber": "^2.0.19",
    "google-maps": "^3.2.1",
    "hashids": "^1.1.1",
    "http-proxy": "^1.16.2",
    "i18n": "^0.8.3",
    "meteor-node-stubs": "^0.2.11",
    "meteor-typings": "^1.4.1",
    "moment": "^2.18.1",
    "npm-shrinkwrap": "^6.0.2",
    "pg": "^6.4.2",
    "proxy-agent": "^2.1.0",
    "pubnub": "^4.15.1",
    "pubnub-angular": "^4.0.2",
    "screenfull": "^3.3.1",
    "sprintf-js": "^1.1.1",
    "winston": "^2.3.1"

**Comment by benjamn** [comment] 2017-09-07 14:08
Isn't this a duplicate of your other issue? #9058

**Comment by p3pp8** [comment] 2017-09-07 14:22
Yes but with more details. I'll close this and update the old one. Sorry!

**Closed** 2017-09-07 14:22 UTC

**Comment by stefanocudini** [comment] 2017-09-28 18:35
may be the problem is related to *boilerplate-generator*
I opened an issue about this #9149
