### ISSUE TITLE
Add a way to get the absolute path of assets

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#3705] opened 2015-02-11 10:11 UTC
The [`Assets` package](http://docs.meteor.com/#/full/assets) would benefit from a method to return the absolute path to an asset.

Use case: passing said path to an external process that needs a filepath as a command line argument.

For instance, to use `pdftk` to apply a watermark to a PDF file:

```js
Npm.require('child_process').execFile('pdftk', ..., Assets.resolvePath('pdfs/stamp.pdf'));
```

**Comment by stubailo** [comment] 2015-02-11 17:50
The current API emphasizes that assets are read-only. I am a little concerned that this might encourage people to edit those assets manually, and then they will be surprised when their changes don't stick across a server restart or other event.

Maybe we can just make the asset files read-only on the file system, and that will solve the above problem? But then people can do something like `fs.chmod` to make it writable.

What do you think?

**Comment by dandv** [comment] 2015-02-11 22:31
Honestly that hasn't crossed my mind. My use case is to stamp an input PDFs with a "stamp" PDF, and produce an output PDF in a temporary directory. If I wanted to modify an asset I'd have the output end up in `/tmp/`; don't know about other users.

**Comment by glasser** [comment] 2015-02-17 21:08
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Note that this is related to (but distinct from) #1193.

**Comment by hypno2000** [comment] 2015-05-21 11:25
There are some node libraries that only accept files paths as inputs. For example https://www.npmjs.com/package/soap accepts wsdl only in path/url format. Using assets here is not possible simply because there is no way to get the path of an asset. I would either need to read the asset and save to temp location or try to figure out the internal asset store location (which maybe diff in built and dev modes?) and both of them are nasty hacks.

```
soap.createClient(url, ...
```

**Comment by stubailo** [comment] 2015-05-21 17:53
Honestly it sounds to me like it wouldn't be a bad idea to provide a helper to copy a file to a temp location, just to make sure the file is not modified.

**Comment by paralin** [comment] 2015-11-09 05:11
Anyone planning to revisit this?

**Comment by mitar** [comment] 2016-02-09 23:03
One can use manifest file to resolve to assets file. The issue is that manifest file has sometimes wrong URLs (#5714).

So using information about the current package (#6192) and fixed manifest URLs (#5714) one could correctly resolve asset values (especially because all assets have a flag that they are assets (type: asset) in the manifest file).

**Comment by aldeed** [comment] 2016-03-13 03:46
@dandv this was merged into the 1.3 release from https://github.com/meteor/meteor/pull/6440. Can be closed.

**Comment by mitar** [comment] 2016-03-13 03:58
This is only for server-side now? So #1193 should still be open?

**Comment by aldeed** [comment] 2016-03-13 05:21
@mitar correct

**Closed** 2016-03-14 18:25 UTC
Labels: feature, Project:Isobuild
