### ISSUE TITLE
import less files in packages doesn't work

### ISSUE THREAD

**Issue by frozeman** [meteor/meteor#5242] opened 2015-09-22 20:46 UTC
Since 1.2 my packages less files aren't imported anymore.
 I have a package with the following files:
```
- main.less // imports elements.less
- elements.less
```

In `main.less` i tried everything:
```less
import 'elements.less';
import './elements.less';
import 'my:package/elements.less';
import 'my_package/elements.less';
import 'my-package/elements.less';
import '{my:package}/elements.less';
```

But i always get:
```
   While processing files with less (for target web.browser):
   packages/ethereum:elements/main.less:3: Unknown import: elements.less
```

I also tried already `api.addAssets()` to add the files before, but didn't help.

If i use `api.addFiles` to add all less files, it doesn't import the variables or mixing of the other less files to the following ones:
```js
  api.addFiles('lib/lesshat.less', 'client');
  api.addFiles('containers.less', 'client');
  api.addFiles('elements.less', 'client');
  api.addFiles('main.less', 'client');
```

I then get errors like:
```
   While processing files with less (for target web.browser):
   packages/ethereum:elements/containers.less:10:12: No matching definition was found for `.blur(4px)`
   packages/ethereum:elements/elements.less:37:17: variable @colorGray is undefined
   packages/ethereum:elements/main.less:3: Unknown import: {ethereum-elements}/elements.less
   client/styles/main.less:2: Unknown import: public/dapp-styles/dapp-styles.less
```

How do i do it right and where can if find proper docs?

**Comment by glasser** [comment] 2015-09-22 20:47
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by frozeman** [comment] 2015-09-22 20:48
Ok, but could you give me at least a description, of which of those ways i tried it is the supposed correct one?

**Comment by glasser** [comment] 2015-09-22 21:10
The first or last should be fine. You need to use addFiles, not addAssets.  But I don't quite understand the problem as described; it's a whole lot easier to debug and understand a tree on my disk than an abstract explanation.  I've debugged a lot of meteor bug reports; I'd say at least 75% of them were in a part of the code entirely unrelated to what the reporter thought it was and there was no way to figure that out without a reproduction!

**Comment by frozeman** [comment] 2015-09-23 08:46
Here Mr. @glasser :)
https://github.com/frozeman/meteor-test-import-less

It would be good if you could add better documentation for these package imports for less/coffescript etc to the docs.

**Comment by frozeman** [comment] 2015-09-23 09:04
I also could before import less files from the `public` folder from my apps less files, which doesn't seem to work either anymore. Any idea how would i go about doing this now?

**Comment by gjr-qm** [comment] 2015-09-23 09:14
Maybe try this?

`@import "{}/elements.less`

I was reading the [Meteor 1.2 Upgrade Guide](https://quip.com/RXFlAk9Rc2xI) and there it says it should be like that to load a file from your app.

**Comment by frozeman** [comment] 2015-09-23 09:15
I tried everything, doesn't work.

**Comment by frozeman** [comment] 2015-09-23 17:24
This issue is actually critical to run some of my packages and apps and it seems like a bug.
It would be awesome if this could get fixed fast :bow:

**Comment by frozeman** [comment] 2015-09-24 17:22
@glasser could you take a look, as our projects depend on a working import functionality for less files.
Its also seems impossible to downgrade from 1.2 as jquery seems not downgrade able for some packages:
```
Could not resolve the specified constraints for this project:
Error: conflict: constraint jquery@1.11.3_2 is not satisfied by 1.0.1.
Constraints on jquery come from:
  <top level>
  spacebars@1.0.3 -> blaze@2.0.3
```

**Comment by glasser** [comment] 2015-09-24 19:01
I am looking now, I was observing a religious holiday yesterday :)

less is documented in its readme, which you can see at https://atmospherejs.com/meteor/less

Files that are not intended to be processed by themselves but only via imports should be marked as import in one of the three ways described in the readme: rename otherfile.less to otherfile.import.less; move it into a directory named `imports`; or pass the `{isImport: true}` flag.

I noticed that the [upgrade guide](https://quip.com/RXFlAk9Rc2xI) gives an `@import` example that doesn't show this and doesn't link to the less README.  I updated the guide to be more helpful. Thanks for the report!

**Closed by glasser** 2015-09-24 19:01 UTC
Labels: Project:Imported Packages, Project:Isobuild

**Comment by frozeman** [comment] 2015-09-24 19:54
Aha!

Thanks for that clarification, it works now!
Sorry for being so pushing, but this issue put myself on halt for the last two days. The Meteor docs are sometimes very scattered. (But we have the same problem here at Ethereum :P )

Just one question, if i would like to import a less file from the `public` folder, is this possible?

**Comment by glasser** [comment] 2015-09-24 20:01
You can't do that.  Though in 1.2 you can do the equivalent inside a package (ie, a file can both be `addFiles` and `addAssets`).

**Comment by glasser** [comment] 2015-09-24 20:01
(Or well, it's possible that you could (if you're not using Windows) put a file in `public` and put a symlink to it outside of `public`.)

**Comment by frozeman** [comment] 2015-09-24 20:05
addAsset, makes it possible to access files like a image from a packages css right?
e.g. using `url('image/myimage.png')`?
It was possible before at least.

**Comment by glasser** [comment] 2015-09-24 20:23
Ought to: nothing has changed but the package.js syntax.

**Comment by mcwonka** [comment] 2015-09-25 08:42
I am still facing the same issue and all three ways are not working for me.

@frozeman Could you provide the code for your working example:
package.js and *.less and which way are you using, imports folder or *.import.less? 

Thanks for your help.

**Comment by frozeman** [comment] 2015-09-25 08:53
Ok so you use in your import file e.g.:
```css
import 'lib/lesshat.import.less';
@import 'containers.import.less';
@import 'elements.import.less';
```

And in your `package.js` you do:
```js
  api.addFiles('lib/lesshat.import.less', 'client');
  api.addFiles('containers.import.less', 'client');
  api.addFiles('elements.import.less', 'client');
  api.addFiles('main.less', 'client');
```

**Comment by mcwonka** [comment] 2015-09-25 14:55
Thank you very much, I got it working now, too. 
My problem was that the path for the import statement for *.import.less has to be relative from *.less

**Comment by sean-stanley** [comment] 2015-09-30 01:05
So what you are saying is the package author needs to specify all files needed at build time in the package.js file. Ironically they are but are only pushed to "server" and thus I can't import them in the client.

```
scssFiles = prepandPathToFiles(scssFiles, scssDirectory);
  api.addFiles(scssFiles, 'server');
  api.addFiles(['bower_components/materialize/sass/materialize.scss'], 'server');
```

since `'bower_components/materialize/sass/materialize.scss'` is not flagged `client` it's not included at runtime and I can't import it using the absolute path either?

Thank you for your quick responses.

**Comment by sean-stanley** [comment] 2015-09-30 01:05
I haven't written a package before so understanding the packages system is something still a bit fuzzy to me.

**Comment by lugehorsam** [comment] 2015-09-30 02:27
Would it be reasonable to change the less build system so that .less files can import other files using absolute paths? (Without having to create a whole package.)

**Comment by lugehorsam** [comment] 2015-09-30 02:39
nevermind...dumb question. here was how i got it working:


any of my .less files....

```
@import '/imports/variables';

``` 

then in my root directory I have imports/variables.less

Who would have thought? :)

**Comment by youclavier** [comment] 2015-11-13 08:15
you don't need to put the imports folder inside the root directory. You can create a imports folder within the place you want as long as the folder name is imports, then meteor will load the **.import.less files for you~

**Comment by jakobrosenberg** [comment] 2016-01-02 12:24
We need to define every single less file in package.js now? 

Bootstrap-3.2.0 has 70 less files.

If that's the case, it's the end of easy wrappers.

**Comment by mcwonka** [comment] 2016-01-04 14:17
I am using glob to avoid naming all files in package.js, maybe that helps you too.
 
```javascript
var glob = Npm.require('glob');
...
var packageBase = 'packages/PACKAGE_NAME/'
// Load all *.import.less inside package
files = glob.sync(packageBase + '/**/*.import.less')
files.forEach(function(file) {
  file = file.slice(packageBase.length) //remove packageBase
  //console.log('addFiles: ' + file);
  api.addFiles(file, 'client');
});
...

**Comment by llvasconcellos** [comment] 2016-10-28 08:37
I'm having the same problem but importing from a npm package. I'm trying to use font-awesome from npm as described in the guide:

https://guide.meteor.com/using-npm-packages.html

on client/stylesheets/style.less:
```css
@import "../../node_modules/font-awesome/less/font-awesome.less";
```
