### ISSUE TITLE
Meteor 1.3 beta 4/5 : React and Velocity Mocha incompatibility

### ISSUE THREAD

**Issue by dagatsoin** [meteor/meteor#5991] opened 2016-01-13 20:27 UTC
I d'ont know if it is related to Meteor or meteor-mocha-web but I can't start the mocha mirror due to this [error](https://github.com/mad-eye/meteor-mocha-web/issues/199). So I post it here.

Velocity Mocha does not start. I have this error:

```
tail -f /Users/vikti/dev/wizar-guide/.meteor/local/log/mocha.log

   While selecting package versions:
   error: Potentially incompatible change required to top-level dependency:
   react 0.14.3, was 0.14.3_1.
   Constraints on package "react":

   To allow potentially incompatible changes to top-level dependencies, you
   must pass --allow-incompatible-update on the command line.
```

I have also tried to launch via meteor --allow-incompatible-update 
I use Meteor 1.3.beta4 Any hint on this ?

**Comment by avital** [comment] 2016-01-19 22:47
Thanks for the report. Could you reproduce this in a small repository that you can share with us?

**Comment by dagatsoin** [comment] 2016-01-20 09:58
I have just done:
```
$ meteor create meteor-1.3beta4-#5991
$ cd meteor-1.3beta4-#5991/
$ meteor update --release 1.3-modules-beta.4
$ meteor add mike:mocha
$ meteor add react
$ meteor run
```
and `$ tail -f .meteor/local/log/mocha.log`to see the crash log

My environment:
mocha@2.3.4
node@v4.2.3
npm@2.14.7

**Comment by avital** [comment] 2016-01-21 18:52
Hmm. Why is this happening? Is there a dependency of some part of Velocity or meteor-mocha-web on React?

**Comment by dagatsoin** [comment] 2016-01-21 18:58
I don't see a React dependency in meteor-mocha-web package.json neither in meteor-velocity package.json
Maybe a deeper dependency ?

**Comment by dagatsoin** [comment] 2016-01-28 14:33
_As I don't know which repo is in cause. Here is a copy/paste from mike:mocha issue
_
After upgrading on beta5, I have

/Users/vikti/dev/wizar-guide/.meteor/local/mirrors/mocha/.meteor/local/build/programs/server/app/lib/collections.js:10
export { MapObjects };                                                 //
^^^^^^
SyntaxError: Unexpected reserved word
    at /Users/vikti/dev/wizar-guide/.meteor/local/mirrors/mocha/.meteor/local/build/programs/server/boot.js:241:30
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/vikti/.meteor/packages/velocity_meteor-tool/.1.1.10_2.1incwsp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/vikti/dev/wizar-guide/.meteor/local/mirrors/mocha/.meteor/local/build/programs/server/boot.js:137:5
Exited with code: 8
Your application is crashing. Waiting for file change.
And collections.js is juste exporting a Mongo Collection in ES6 syntax

// lib/collections.js
export let MapObjects = new Mongo.Collection('mapObjects');

**Comment by cheapRoc** [comment] 2016-02-12 20:40
Just because I didn't see it mentioned above and happened to stumble across your problem while hunting down mine... Did you `meteor add ecmascript` and/or `meteor add modules` @dagatsoin? 

As noted in [the beta release](https://github.com/meteor/meteor/blob/release-1.3/packages/modules/README.md#enabling-modules) `ecmascript` is responsible for introducing `import` and `export` keywords.

**Comment by abernix** [comment] 2016-07-19 23:56
At this point, Velocity is no longer maintained so I believe this will be closed in favor of other testing frameworks becoming the 1.3 "norm".

**Closed by abernix** 2016-07-19 23:56 UTC
