### ISSUE TITLE
[Meteor 3 Alpha] MINISAT-out: Cannot enlarge memory arrays

### ISSUE THREAD

**Issue by OlesZadorozhnyy** [meteor/meteor#12902] opened 2023-11-27 11:44 UTC
Hi,
After trying to install Alpha version of Meteor 3 it raises an error
```meteor update --release 3.0-alpha.19``` (other alpha versions as well

```
MINISAT-out: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
MINISAT-err: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
abort() at Error                              
    at jsStackTrace (packages/logic-solver.js:21:18626)
    at stackTrace (packages/logic-solver.js:21:18809)
    at abort (packages/logic-solver.js:51:28956)
    at enlargeMemory (packages/logic-solver.js:21:19142)
    at Function.dynamicAlloc [as alloc] (packages/logic-solver.js:21:7927)
    at _sbrk (packages/logic-solver.js:21:58803)
    at Sd (packages/logic-solver.js:25:98389)
    at Ud (packages/logic-solver.js:25:109800)
    at gc (packages/logic-solver.js:25:41378)
    at pc (packages/logic-solver.js:25:46259)
    at _b (packages/logic-solver.js:25:31709)
    at $b (packages/logic-solver.js:25:35130)
    at Bc (packages/logic-solver.js:25:54870)
    at hd (packages/logic-solver.js:25:84479)
    at MiniSat.solveAssuming (packages/logic-solver.js:156:18)
    at Logic.Solver.solve (packages/logic-solver.js:1680:33)
    at Logic.Solver.solveAssuming (packages/logic-solver.js:1713:21)
    at minMaxWS (packages/logic-solver.js:1999:32)
    at packages/constraint-solver.js:1381:22
    at CS.Solver.minimize (packages/constraint-solver.js:1365:3)
    at CS.Solver.minimize (packages/constraint-solver.js:1359:5)
    at CS.Solver._getAnswer (packages/constraint-solver.js:1749:3)
    at Object.Logic.disablingAssertions (packages/logic-solver.js:389:12)
    at Function.CS.PackagesResolver._resolveWithInput (packages/constraint-solver.js:2333:10)
    at CS.PackagesResolver.resolve (packages/constraint-solver.js:2294:14)
    at /tools/project-context.js:668:26
    at /tools/project-context.js:664:11
    at Object.enterJob (/tools/utils/buildmessage.js:387:12)
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:282:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:18)
    at ProjectContext._resolveConstraints (/tools/project-context.js:635:5)
    at /tools/project-context.js:401:9
    at Object.enterJob (/tools/utils/buildmessage.js:387:12)
    at /tools/cli/commands-packages.js:1746:5
    at Object.capture (/tools/utils/buildmessage.js:282:5)
    at Object.main.captureAndExit (/tools/cli/main.js:275:16)
    at maybeUpdateRelease (/tools/cli/commands-packages.js:1745:3)
    at Command.func (/tools/cli/commands-packages.js:1819:29)
    at /tools/cli/main.js:1527:1
```

There is already conversation in forum - https://forums.meteor.com/t/trouble-updating-to-3-0-alpha-17-minisat/60728
But no solution provided. Blocker to test new version Meteor. 
Please, do you have a workaround for this?

**Comment by Grubba27** [comment] 2023-11-28 12:57
I have not yet gotten this error while testing. Do you have any reproduction? (can be github, code sample). We are testing in some projects but have not gotten this one yet.

Also, thanks for the forum link. We can track there as well.

cc @denihs

**Comment by dallman2** [comment] 2023-12-13 20:58
I have a theory. I was getting this exact same error, but it went away when I removed the explicit version specifier from the package, ie `accounts-password@2.0.3` became `accounts-password`.

**Comment by dokithonon** [comment] 2023-12-21 20:29
I have also the same problem. Removing the version specifier on accounts-password was not helpful for me.
https://forums.meteor.com/t/trouble-updating-to-3-0-alpha-17-minisat/60728/4

**Comment by dallman2** [comment] 2023-12-21 20:33
Do you have any versions specified for any packages?

**Comment by dokithonon** [comment] 2023-12-21 20:34
I am removing them one by one and then I do 
`meteor update --release 3.0-alpha.19`
But until now no success

**Comment by dallman2** [comment] 2023-12-21 20:43
Try with no packages, then re add them one by one without version numbers

**Comment by bratelefant** [comment] 2024-01-17 18:08
Got a repo ready here with a minimal app and a packages file that causes this issue in my dev env.

https://github.com/bratelefant/meteor-beta3-bug

**Comment by bratelefant** [comment] 2024-01-20 13:43
Ok, finally got my meteor app to 3.0 beta! :) Followed the path suggested by @dallman2, removed a bunch of packages an readded them one-by-one, success even without specifying a version number. Anyway, imho the issue itself should be left open to smoothen the upgrade process.

**Comment by dallman2** [comment] 2024-01-20 21:54
I agree with @bratelefant on this. The solution may not be to specifically expand the memory pool available to the dependency resolver, but some sort of migration tool should be provided to automate this process. Or maybe, the package manager could be made the work with multiple versions of the same package (like npm).

**Comment by denihs** [comment] 2024-07-23 16:45
Hi, as this seems to be fixed now, I'm closing this issue. We can reopen it in the future if necessary.

**Closed by denihs** 2024-07-23 16:45 UTC
Labels: needs-reproduction, needs-investigation

**Comment by bratelefant** [comment] 2024-07-23 16:46
Yes, it's fine now, had no issue when I updated to rc10 yesterday

**Comment by nachocodoner** [comment] 2025-03-24 13:29
The fix of this problem has been delivered in Meteor 3.2, and already live to use it, `meteor update --release 3.2` / `meteor create --release 3.2`.

**Comment by dokithonon** [comment] 2025-03-24 15:20
Great work. I have Meteor 3.2 in test since a few days and everything is working fine
