### ISSUE TITLE
Friendlier error message instead of "No metadata files found for isopack"

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#5719] opened 2015-11-26 10:19 UTC
On Windows 7, `meteor run` crashes with 

> No metadata files found for isopack at: /C/Users/A/AppData/Local/.meteor/packages/meteor-tool/1.1.4

against a project that used to work in May 2015.

Reproduction steps:

```
git clone https://github.com/dandv/instagram-clone.git
cd instagram-clone
git checkout 21e37ec
meteor run
```

Output:

```
c:\meteor\instagram-clone>meteor run

C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: No metadata files found for isopack at: /C/Users/A/AppData/Local/.meteor/packages/meteor-tool/1.1.4
    at [object Object]._.extend._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:868:13)
    at C:\tools\packaging\tropohouse.js:500:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\A\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:499:11
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at Object.download (C:\tools\packaging\tropohouse.js:437:20)
    at C:\tools\packaging\tropohouse.js:575:22
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:572:20)
    at C:\tools\cli\main.js:431:30
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at C:\tools\cli\main.js:430:17
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at C:\tools\cli\main.js:428:33
    at [object Object]._.extend.withProgressDisplayVisible (C:\tools\console\console.js:611:14)
    at springboard (C:\tools\cli\main.js:427:11)
    at C:\tools\cli\main.js:1028:5
```

This [forum thread](https://forums.meteor.com/t/no-metadata-files-found-for-isopack-when-updating-xolvio-cucumber/12712) suggests there might be packages without Windows binaries involved. If that's the case, a more useful error message would indicate the offending package(s).

**Comment by tmeasday** [comment] 2015-12-01 22:57
Hey @dandv, thanks for the bug report. Is it possible to put together a reproduction of the issue? It'll make it a lot easier to fix the problem.

**Comment by dandv** [comment] 2015-12-03 01:30
Hey Tom, have you tried the steps under "Reproduction steps" in my first comment? If you need the minimum code that reproduces the problem, I can work on that, but probably after the holidays.

**Comment by tmeasday** [comment] 2015-12-03 01:52
Hi Dan, oh sorry, for some reason I thought the sample code you posted above was private. I think that repro is simple enough. Thanks.

**Comment by olumytee** [comment] 2016-06-26 18:51
Hi, getting this problem when I try to run meteor or meteor update right now. Meteor tool download was stuck for over 10hours so I uninstalled and reinstalled meteor, creating and running a new project works fine but this error is thrown when I try to update or run old projects

c:\Users\Olumide\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windo
      throw error;                                                             
            ^                                                                  
Error: No metadata files found for isopack at: /c/Users/Olumide/AppData/Local/.
    at Isopack._loadUnibuildsFromPath (c:\tools\isobuild\isopack.js:900:13)    
    at c:\tools\packaging\tropohouse.js:514:19                                 
    at Array.forEach (native)                                                  
    at Function._.each._.forEach (c:\Users\Olumide\AppData\Local\.meteor\packag
    at c:\tools\packaging\tropohouse.js:513:11                                 
    at c:\tools\utils\buildmessage.js:359:18                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at c:\tools\utils\buildmessage.js:352:34                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at c:\tools\utils\buildmessage.js:350:23                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at Object.enterJob (c:\tools\utils\buildmessage.js:324:26)                 
    at Object.download (c:\tools\packaging\tropohouse.js:448:20)               
    at c:\tools\packaging\tropohouse.js:592:22                                 
    at c:\tools\utils\buildmessage.js:359:18                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at c:\tools\utils\buildmessage.js:352:34                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at c:\tools\utils\buildmessage.js:350:23                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at Object.enterJob (c:\tools\utils\buildmessage.js:324:26)                 
    at [object Object].downloadPackagesMissingFromMap (c:\tools\packaging\tropo
    at c:\tools\cli\main.js:440:30                                             
    at c:\tools\packaging\catalog\catalog.js:100:5                             
    at c:\tools\utils\buildmessage.js:271:13                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at c:\tools\utils\buildmessage.js:264:29                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at c:\tools\utils\buildmessage.js:262:18                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at c:\tools\utils\buildmessage.js:253:23                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at Object.capture (c:\tools\utils\buildmessage.js:252:19)                  
    at Object.catalog.runAndRetryWithRefreshIfHelpful (c:\tools\packaging\catal
    at c:\tools\cli\main.js:439:17                                             
    at c:\tools\utils\buildmessage.js:271:13                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at c:\tools\utils\buildmessage.js:264:29                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at c:\tools\utils\buildmessage.js:262:18                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at c:\tools\utils\buildmessage.js:253:23                                   
    at [object Object].withValue (c:\tools\utils\fiber-helpers.js:89:14)       
    at Object.capture (c:\tools\utils\buildmessage.js:252:19)                  
    at c:\tools\cli\main.js:437:33                                             
    at Console.withProgressDisplayVisible (c:\tools\console\console.js:631:14) 
    at springboard (c:\tools\cli\main.js:436:11)                               
    at c:\tools\cli\main.js:1045:5

**Comment by abernix** [comment] 2016-06-28 16:24
In regards to the original issue, I have *not* been able to reproduce it using the latest version of the Meteor tool (1.3.4.1) on Windows 7 Enterprise (32-bit).  The project launches for me without the `No metadata files found for isopack` error.

Please try reinstalling Meteor using the following steps:

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.
* Install fresh 1.3.4.1 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's reinstalled properly
* Try your project again.

@olumytee Perhaps you might try doing a fresh reinstall as well.  Please at least indicate what version of Windows you're using if you're still having problems too. :smile:

**Comment by olumytee** [comment] 2016-06-29 14:18
@abernix I was using Windows 10. It was a fresh install but it was an old project that used an version 1.3.2 of Meteor. Removing old meteorhacks:npm fixed the issue for me. Thanks.

**Comment by abernix** [comment] 2016-07-27 07:22
Can't reproduce.  Closing.

**Closed by abernix** 2016-07-27 07:22 UTC
Labels: bug, can't-reproduce, Impact:few, Project:Tool, Project:Windows
