### ISSUE TITLE
Meteor.setTimeout() does not return a "Number" type handle

### ISSUE THREAD

**Issue by CdavM** [meteor/meteor#7778] opened 2016-09-15 23:44 UTC
Background:
I'm running Meteor 1.4.1.1 on Ubuntu 16.04. This bug is reproducible on a fresh Meteor app with no dependencies.

Actual behavior:
Running
`x = Meteor.setTimeout(function(){console.log("hello");}, 1000000);`
`typeof(x)` returns an `object`. Here is what mine looks like:

```
{ _called: false,
  _idleTimeout: 1000000,
  _idlePrev: 
   Timer {
     '0': [Function: listOnTimeout],
     _idleNext: [Circular],
     _idlePrev: [Circular],
     msecs: 1000000 },
  _idleNext: 
   Timer {
     '0': [Function: listOnTimeout],
     _idleNext: [Circular],
     _idlePrev: [Circular],
     msecs: 1000000 },
  _idleStart: 179871,
  _onTimeout: [Function],
  _repeat: null }
```

Expected behavior:
`typeof(x)` returns `number` which can be passed into a clearTimeout() function. For instance, running the code in a console returns an integer (in my case, 1146).

More info:
https://docs.meteor.com/api/timers.html#Meteor-clearTimeout 
Implies that a Number is returned as a handle from Meteor.setTimeout(). However, this is not the case. An object is returned instead. 

I think the server-side implementation should mimic both javascript conventions and the client-side.

I am unable to locate the function setTimeout() in the source (and the link on the docs page is not constructive). Please fix it or advise on how to bypass it. I'd like to have something that can be stored into a Mongo collection.

**Comment by mitar** [comment] 2016-09-15 23:47
Handles from `setTimeout` should be seen as an opaque resource you cannot and should not really be storing into Mongo. See them as a "file descriptor"-like thingy. They are valid just for that one process.

**Comment by CdavM** [comment] 2016-09-15 23:54
But is there a benefit to the current implementation, where you use "file descriptor"-like things on the client but expose the object on the server? Why not have the same behavior on both ends?

Anyway, the implementation should at least be reflected in the docs, so we either make this bug a feature and document it or change the behavior.

**Comment by mitar** [comment] 2016-09-15 23:57
> Why not have the same behavior on both ends?

Because it is an opaque value. You should not care what it is. :-)

Anyway, this is a duplicate of: https://github.com/nodejs/node-v0.x-archive/issues/5728

**Comment by mitar** [comment] 2016-09-15 23:58
So this is just what underlying implementation is returning, in browsers and on node.

See also: https://github.com/nodejs/node-v0.x-archive/pull/7082

So yea, we should probably improve Meteor documentation accordingly.

**Comment by CdavM** [comment] 2016-09-19 17:19
The fact that users shouldn't have to use it isn't an excuse for the developers being sloppy and having a different behavior between the client side and server side :-) 

Anyway, how do I fix the documentation?
I followed the link to https://github.com/meteor/docs/blob/master/source/api/timers.md but can't see the arguments (i.e. 'Number')

**Comment by mitar** [comment] 2016-09-19 17:32
It is [automatically generated](https://github.com/meteor/meteor/blob/devel/packages/meteor/timers.js#L26) from source code.

**Comment by abernix** [comment] 2016-09-23 10:31
@CdavM What do you propose calling it in the documentation?  Node calls the objects `intervalObject` and `timeoutObject` in [their documentation](https://nodejs.org/dist/latest-v4.x/docs/api/timers.html).  I agree that saying the `clearTimeout` and `clearInterval` expect a `Number` might be confusing.

**Comment by abernix** [comment] 2016-11-15 12:13
@CdavM Any thoughts on my previous comment?

**Comment by CdavM** [comment] 2016-11-28 03:24
@abernix I don't have any specific thoughts on the naming convention. Using Node's style seems appropriate.

**Comment by abernix** [comment] 2016-12-02 16:24
Thanks for reporting this, @CdavM.  I opened #8127 to fix it.  I've just gone with `Object` instead of `Number` since `Number instanceof Object === true`.  It is an opaque value though and you need not worry about what it is, only that you should pass it to `clearTimeout`/`clearInterval`.

**Closed by abernix** 2016-12-02 16:24 UTC
Labels: Project:Docs
