### ISSUE TITLE
First publish/subscribe has huge lag despite the data

### ISSUE THREAD

**Issue by neooleg** [meteor/meteor#8673] opened 2017-05-06 05:27 UTC
## Abstract

- First only subscription takes too much time comparing to other subscriptions.
- It reproduces even for _publish()_ returning empty array within empty (just scaffolded) project.
- Using _console.time()_ It looks like (for Windows 7, but for Mac OS X they are similar):
> subscribe(1st): 525.221923828125ms
> subscribe(2nd): 0.4111328125ms

## Investigation Details
- This lag in **on client side**, i.e. it appears this is _subscribe()_ issue, not _publish()_. It's easy to figure out this -- just run below test on different machine/mobile device.
- It doesn't reproduce w/ [a regular WebSockets lib](https://github.com/faye/faye-websocket-node) using simpler, but similar actions like setup WebSocket and handshake (sub) message.
- We're fixing very slow (~20 s) Meteor app start on mobile (mostly Android 4.4+) which is much more critical for JS execution than desktop. Thus the issue was found as bottleneck before start providing data. Basically, we need to know when to start use collections to render them within templates inside already existing (server rendered) HTML.
- It reproduces on Meteor 1.3 and 1.4.
- I can provide a whole example app to reproduce this on Meteor, just ask.

## Code
```
// Server
Meteor.publish('test', function() {
  return [];
});

// Client
console.time('subscribe(test)');

Meteor.subscribe('test', () => {
    console.timeEnd('subscribe(test)');
  });
```

**Comment by klaussner** [comment] 2017-05-06 10:26
If you call `console.time` and `Meteor.subscribe` in top-level code (like in your example), you are starting the measurement as soon as the script is evaluated, which happens before the browser has finished parsing the HTML and before the WebSocket is set up. Here is a screenshot of a Chrome performance profile for your example code:

![meteor-startup](https://cloud.githubusercontent.com/assets/1312807/25771524/6a91a21a-3254-11e7-98c2-8709af471a78.png)

The `subscribe` bar at the top shows the duration of the `console.time` measurement. As you can see, the subscription callback on the right has to wait for a lot of other things before it is called.

If you wait for the setup to finish before subscribing (for example, by moving the code to a global function and calling it in the browser console), there shouldn't be a difference between the first and subsequent subscriptions:

```js
global.sub = function () {
  console.time('subscribe');

  Meteor.subscribe('test', () => {
    console.timeEnd('subscribe');
  });
}
```

**Comment by hwillson** [comment] 2017-05-08 17:18
Thanks for the great explanation @klaussner! @neooleg - closing as there shouldn't be an issue here. Thanks for reaching out!

**Closed by hwillson** 2017-05-08 17:18 UTC

**Comment by neooleg** [comment] 2017-05-08 19:09
Thanks a lot @klaussner for you time and so good details w/ graphics!

Yeah, it's might not an issue of subscribe(). You pointing in another direction now, but still _performance problem didn't disappear_, i.e. Meteor app has lag on start.

Could you advise how to minimize this "starting" time? Any best practices for Meteor?

**Comment by klaussner** [comment] 2017-05-08 22:07
@neooleg Faster application startup will be in [Meteor 1.5](https://github.com/meteor/meteor/pull/8327#issuecomment-294819086):

> Just as Meteor 1.4.2 took aim at rebuild performance, Meteor 1.5 will be all about production app performance, specifically client-side application startup time.

If the long startup time in your app is caused by evaluating lots of JavaScript, [nested imports might help to reduce it](https://github.com/meteor/meteor/pull/8327#issuecomment-294819086).

**Comment by mitar** [comment] 2017-05-09 21:42
Also, you can make a loading icon [like I have here](http://council.cloyne.org/) ([code](https://github.com/peer/mind)). So sadly beyond rendering something on the server side, or having dynamic imports, you cannot really do much around the fact that web apps are just huge this days and it takes time to load them.

**Comment by neooleg** [comment] 2017-05-17 19:01
@klaussner thanks for pointing to the right direction. As I see Meteor 1.5 already forced to use nested imports, does it?

@mitar, unfortunately spinner doesn't improve UX, sometimes even bother a user. For instance in case when [RAIL](https://developers.google.com/web/fundamentals/performance/rail) is broken. This mostly happens on mobile with heavy loaded apps.

Thus, it's very important to have fast loading for user (considering mobile traffic today).
