### ISSUE TITLE
Meteor command throws error on  Windows 7 x64 (6.1.7601)

### ISSUE THREAD

**Issue by koasmsm** [meteor/meteor#7597] opened 2016-08-06 13:09 UTC
C:\Users\<cut>>meteor
C:\Users\<cut>\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

TypeError: Cannot read property 'join' of undefined
    at Table._generateQuestionMarks (C:\tools\packaging\catalog\catalog-remote.js:435:18)
    at Table._buildStatements (C:\tools\packaging\catalog\catalog-remote.js:425:28)
    at new Table (C:\tools\packaging\catalog\catalog-remote.js:418:8)
    at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:696:26)
    at C:\tools\cli\main.js:771:20

Reinstalled Meteor multiple times but the error persists.

**Comment by marcianosr** [comment] 2016-08-31 11:55
Take a look at this: https://github.com/meteor/meteor/issues/7439#issuecomment-238327569

**Comment by abernix** [comment] 2016-09-14 14:45
Closing as duplicate of #7439.

**Closed by abernix** 2016-09-14 14:45 UTC
