### ISSUE TITLE
Meteor crashes when sending a really long email and MAIL_URL not configured

### ISSUE THREAD

**Issue by extremeandy** [meteor/meteor#5646] opened 2015-11-11 01:08 UTC
Normally, if MAIL_URL is not configured, Meteor logs the email to the server console. However, if the email is really long (say 50KB of text), then Meteor crashes with a variety of errors while attempting to log the email to the console:
- Process exited
- Out of memory
- Some others...

**Comment by AlbinoGeek** [comment] 2015-11-13 12:31
This is duplicate of (due to/caused by) other bugs dealing with "Out of memory" on large console.log .

Please see: #5543

**Comment by timbotnik** [comment] 2015-11-17 23:09
@extremeandy - #5543 specifically refers to the issue being Windows-only.  Is this only on Windows as well?

**Comment by extremeandy** [comment] 2015-11-18 00:16
@timbotnik I am running Windows for dev environment, yes, but have not tested in other environments

**Comment by abernix** [comment] 2016-11-25 18:47
Closing in favor of #5543 to track this issue further.  Thanks for reporting this originally!

**Closed by abernix** 2016-11-25 18:47 UTC
Labels: Project:JS Environment, Project:Windows
