### ISSUE TITLE
Meteor Core jQuery dependency when using static-html

### ISSUE THREAD

**Issue by faburem** [meteor/meteor#6563] opened 2016-03-22 22:15 UTC
***1 Upvote*** When I create a new project where I remove blaze and jQuery in favor of static-html, jQuery is still loaded. This happens with Meteor 1.2.1 and also with 1.3-rc.5. Here is what I did and my test results:
```
meteor create static-html
meteor remove blaze-html-templates insecure autopublish jquery
meteor add static-html
```
![screen shot 2016-03-22 at 09 54 05](https://cloud.githubusercontent.com/assets/11456790/13946611/eeb537fa-f015-11e5-9457-9c246af489d2.png)
When I run this regularly:
![screen shot 2016-03-22 at 09 48 00](https://cloud.githubusercontent.com/assets/11456790/13946591/d6affff0-f015-11e5-9705-52abfdf6d15c.png)
and the same with --production:
![screen shot 2016-03-22 at 09 53 24](https://cloud.githubusercontent.com/assets/11456790/13946681/57b7f922-f016-11e5-88d1-27a6a35f77a3.png)

**Comment by faburem** [comment] 2016-03-23 13:55
I traced this down to the following packages:

- **check**: easy to resolve, is there any reason why this currently depends on jQuery (it didn't used to)?
- **boilerplate-generator**: this will be harder to resolve, it currently has a hard dependency on Blaze which in turn depends on jQuery. I definitely think this should be decoupled now that there are many alternatives to Blaze available and actively used.

**Comment by skirunman** [comment] 2016-03-23 17:47
Looks like part of jQuery lib was added to do object check in this this last commit https://github.com/meteor/meteor/commit/22e5a2611d7fd78abb4aeaddc2615bcb33adc0a9#diff-db148119d1602c9b3d16d4d020e4e7ff

Not sure why there is a strong dependency on jquery package here `api.use('jquery', 'client');`, but I agree this needs to be fixed.

@mitar what are your thoughts as this was your commit?

**Comment by skirunman** [comment] 2016-03-23 17:59
> it currently has a hard dependency on Blaze 

I did not see the Blaze dependency, but there is a Spacebars one.

```
api.use(['underscore',  'spacebars-compiler',
           'spacebars', 'htmljs', 'ui'], 'server');
```
https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator/package.js

**Comment by faburem** [comment] 2016-03-23 18:00
yeah its a bit hidden behind the ui dependency (which btw. is deprecated and resolves to Blaze)

**Comment by mitar** [comment] 2016-03-23 21:08
> @mitar what are your thoughts as this was your commit? Would just adding a weak dependency boolean fix this?

Not really. It is required for the correct check that object is plain object. jQuery provides that utility function and `check` package is using it now.

**Comment by mitar** [comment] 2016-03-23 21:10
BTW, a workaround for you might be that you simply create a `packages/jquery` dummy package which only provides `isPlainObject` method (if you are using `check`) or simply does not provide any real code.

**Comment by skirunman** [comment] 2016-03-23 22:00
Not sure why we have to create a dependency for entire jquery library for applications that are not using UI technology using jquery, but want to use check package in server methods because you chose to use `isPlainObject` for this test. Would it not be possible for the check package to only use that single function and not create this dependency? Seems like the approach you outlined makes more sense or you could simply write your own `isPlainObject` type function. 

I thought one of MDG's goals was to create less dependencies between Meteor core modules, especially with regards to different UI technologies. 
@stubailo What do you think?

**Comment by stubailo** [comment] 2016-03-23 22:06
Based on that commit, looks like we could easily just remove the jQuery dependency and use that shimmed function directly!

**Comment by skirunman** [comment] 2016-03-23 22:07
@stubailo Exactly my thoughts. Thanks.

**Comment by mitar** [comment] 2016-03-23 22:49
> Based on that commit, looks like we could easily just remove the jQuery dependency and use that shimmed function directly!

But in the future we would want to get rid of shimmed functions, not add more of them? When Meteor would support jQuery on the server side (which would help with isomorphic code), for example.

You do not want to maintain copies of code around? You wan to delegate this to existing projects which are working on this. Like jQuery or lodash (BTW, they have that function as well).

Maybe the solution is that jQuery should be included as multiple small files/packages and not one big bundle?

**Comment by stubailo** [comment] 2016-03-23 23:32
> But in the future we would want to get rid of shimmed functions, not add more of them?

I don't think this is necessarily true. Dependencies have a cost, and I think we should try to get rid of jQuery entirely, not provide more of it.

**Comment by mitar** [comment] 2016-03-24 00:03
Hm, what about using a copy, but add TODO to use lo-dash once Meteor supports it?

Also, current code for server, I think, might not work on the client. I remember that there was some IE specific code which I might removed.

**Comment by faburem** [comment] 2016-03-24 09:15
+1 for removing jQuery entirely.
@mitar why not depend on this npm package which provides this functionality and is imho better suited for the needs of check: https://github.com/jonschlinkert/is-plain-object
jQuery's IE specific code mostly handles plainobject checks for host objects which I don't see being a use case for the check package. I'll create a pull request for this if you don't mind.

**Comment by mitar** [comment] 2016-03-24 09:29
The package you referenced fails for `isPlainObject(Object.assign(Object.create({foo: "bar"}), {bar: "foo"}))`. Both jQuery and lodash were failing as well, but once we found out that for jQuery, lodash community automatically found out and fixed that in lodash as well (https://github.com/jquery/jquery/issues/2968, https://github.com/lodash/lodash/issues/2085). What I am trying to say that while there might exist NPM module using popular packages does often mean that bugs will be found sooner.

**Comment by faburem** [comment] 2016-03-24 09:58
agreed. In that case I vote for your proposal:
> Hm, what about using a copy, but add TODO to use lo-dash once Meteor supports it?

**Comment by stubailo** [comment] 2016-03-24 15:53
Wait can't we use this package? https://www.npmjs.com/package/lodash.isplainobject

It is literally just a tiny part of lodash you can import.

**Comment by skirunman** [comment] 2016-03-28 22:50
Can we get this fixed with @stubailo's last suggest on using package [lodash.isplainobject](https://www.npmjs.com/package/lodash.isplainobject). This was brought up by someone else on the [forum today](https://forums.meteor.com/t/jquery-dependency-in-babel-via-check-a-way-to-remove-it/20093).

**Comment by fabien-h** [comment] 2016-03-28 23:31
Yes please! I agree with the dependency cost @stubailo. Especially when we are talking about a 32ko cost for ten lines of code.

`lodash.isplainobject` is ok, because it's part of the lodash modularized project... So it's actually the full well maintained lodash behind. But generally speaking, I'm not confortable with that kind of small package.

With the way packages works in meteor, would it be possible to depends on the full lodash, but only import the modules we need here ? With something like `import { isplainobject } from 'lodash'` ?

The end goal is to combine the light import footprint of the small submodule and the reliability of the big brother.

**Comment by mitar** [comment] 2016-03-28 23:37
> The end goal is to combine the light import footprint of the small submodule and the reliability of the big brother.

+1

**Comment by skirunman** [comment] 2016-03-29 22:08
Not sure what I'm missing here and I'm struggling with the concept of creating another outside dependency on lodash for what I consider to be a core Meteor function, [check](http://docs.meteor.com/#/full/check), which is recommended in the Meteor Guide to be used in all applications. 

In @mitar's [commit above](https://github.com/meteor/meteor/commit/22e5a2611d7fd78abb4aeaddc2615bcb33adc0a9) does he not already provide a [shimmed jQuery.isPlainObject function](https://github.com/meteor/meteor/blob/22e5a2611d7fd78abb4aeaddc2615bcb33adc0a9/packages/check/jquery.js), but is only using the shimmed function on the server? Can this not be resolved and be made more understandable and maintainable by simply renaming the file from jquery.js to check-jquery.js (or similar) and then update the package as follows to use this same shimmed function on both the client and server, and thus, removing jquery dependency?

```
Package.onUse(function (api) {
  api.use(['underscore', 'ejson'], ['client', 'server']);

  api.export(['check', 'Match']);

  api.addFiles(]'check-jquery.js', 'match.js'], ['client', 'server']);
});
```

Also, is you want add a comment to where jQuery.isPlainObject is called in match.js that if Meteor ever switches from Underscore to Lodash to then refactor to use Lodash's version of isPlainObject.

**Comment by mitar** [comment] 2016-03-29 22:50
> If the current version of does not resolve the bug mentioned above then update to a version that does.

And who will update this function once the next bug appears? I think this is the question. Do you want to reimplement things (or by copying from current version of lodash/jQuery) or you want to depend on outside code so that you do not have to maintain it yourself. This is why one use external libraries. The issue is only that using external libraries mean also that you include stuff you do not need.

So maybe the solution would be that minimizer would be so smart to remove functions which are never called. So that at least if one does `import { isplainobject } from 'lodash'` the rest of the code from `lodash` is not included.

**Comment by fabien-h** [comment] 2016-03-29 22:55
The problem here is not the fact that we have a dependency. But the fact that we have a HUGE dependency for 10 lines of code.

And we have two solutions :

- include those ten line of code in a file
- change for a way lighter dependency

If it was my repo, I'd include the code. But from what I can see about the way meteor works, it would tend to be an import.

I don't even know if `import { isplainobject } from 'lodash'` is possible here. But this is definitely the best choice. If you go for `lodash.isplainobject` and meteor switch to lodash one day, this function would be duplicated. By importing from lodash, you prevent duplication.

**Comment by skirunman** [comment] 2016-03-29 23:14
> Do you want to reimplement things (or by copying from current version of lodash/jQuery) or you want to depend on outside code so that you do not have to maintain it yourself. 

In an ideal world we'd be using Lodash in Meteor core. Right now we are already using the shimmed function you provided on the server so extra technical debt incurred to use it on the client for now and refactor later. 

What is not great today is pulling in entire jquery library on client when I'm not using it in my app. Same would be true of Lodash for just one function. 

I agree that using well tested and well used libraries are the way to go, but in this case, it is overkill.

**Comment by stubailo** [comment] 2016-03-29 23:41
> If you go for lodash.isplainobject and meteor switch to lodash one day, this function would be duplicated. By importing from lodash, you prevent duplication.

I'm sure that when Meteor switches to lodash, we can do a simple find on the whole codebase to find places where we are using these small packages and replace them.

Let's go with this small single-function lodash dependency, I haven't heard any concrete reasons against using that, and I think it will work well!

**Comment by skirunman** [comment] 2016-04-02 01:15
I'm still don't think it is a good idea to create a Meteor build dependency on such a small NPM package especially with the whole[ left-pad fiasco](http://www.infoworld.com/article/3047177/javascript/how-one-yanked-javascript-package-wreaked-havoc.html). I think it would be safer (until Meteor upgrades to Lodash) and likely more performant to simple copy the [lodash.isplainobject](https://github.com/lodash/lodash/blob/npm-packages/lodash.isplainobject/index.js) function in to match.js as a shim function. There are already such [shim functions](https://github.com/meteor/meteor/blob/devel/packages/check/match.js#L337
) waiting to be replaced on upgrade to Meteor using Lodash instead of Underscore. 

I want to get this fixed either way, but just want to state my concerns with the npm import approach.

**Comment by stubailo** [comment] 2016-04-04 06:46
I think the left-pad thing is more about depending on small packages by authors which are not heavily invested in those packages. I believe lodash, and by extension the individual function packages which are also published by them, are trustworthy enough that this is not an issue.

**Comment by faburem** [comment] 2016-04-04 09:07
To be honest I'm fine with either solution as long as we can get rid of jQuery in Meteor Core. At this point I would like to point out that so far we are only tackling half of the problem. There is still the ui dependency of [boilerplate-generator](https://github.com/meteor/meteor/blob/bfc88706c4ce793018c762bf2289d7ad4f10fa9d/packages/boilerplate-generator/package.js#L8) which currently resolves to blaze (which, as we all know has a dependency on jQuery). Looking at the current implementation I am afraid that this will be much harder to resolve.

**Comment by stubailo** [comment] 2016-04-04 17:27
Note that the dependency of boilerplate-generator on Blaze is only on the server! So I would postulate that it is not important to get rid of. But it should be easy, since all it's doing is concatenating some strings.

**Comment by skirunman** [comment] 2016-04-04 21:24
I'm OK with either approach as well. For us the jquery dependency on the client is the real issue. Would be nice to remove it on server as well by using a string concat function from lodash and same approach of importing just that function?

Anyway, can we get this tagged for next 1.3.2 release as this jquery dependency bug was just introduced late in the 1.3 release cycle? A big thanks in advance.

**Comment by skirunman** [comment] 2016-04-05 17:51
Bumping for @benjamn as hoping this can get done ASAP along with #6626, which I know is causing lots of issues with using NPM packages that require jquery.

**Comment by skirunman** [comment] 2016-04-05 22:13
Pull request https://github.com/meteor/meteor/pull/6709

Maybe @mitar can look at the PR to make sure I did not mess anything up, thanks.

**Comment by benjamn** [comment] 2016-04-12 17:33
Once Meteor 1.3.2 is released today or tomorrow, it will be possible to avoid including jQuery in your project at all, or to use your own version throughout the project by `npm install`ing it yourself. You can test it out by doing `meteor update --release 1.3.2-rc.5` now. Thanks for your feedback, everyone!

**Comment by faburem** [comment] 2016-04-12 17:47
My first tests are looking good. Thanks for all your efforts and the quick release!
![screen shot 2016-04-12 at 19 45 59](https://cloud.githubusercontent.com/assets/11456790/14469951/3f45d42c-00e7-11e6-92ac-73afa4b53493.png)

**Comment by dohomi** [comment] 2016-04-12 18:01
It would be great if you could consider making a fix of: https://github.com/meteor/meteor/issues/6564
Otherwise @faburem or anybody else will get `blaze` injected as soon using `Facebook` or any other social login. Thanks for the fix of `jQuery`!

**Comment by skirunman** [comment] 2016-04-13 16:47
@benjamn Sorry if this is a duplicate, but did you see my comment about potential issue with jquery.isPlainObject code? https://github.com/meteor/meteor/commit/fbf7617111d0d4b7ee7ee7e63a6861f2dfc0fd16#comments @mitar said there may be issues with running this code on the client. Last time I looked in 1.3.2 branch we were still using this code for both client/server. Maybe lodash's isPlainObject code is a better way to provide this shim function.

**Closed** 2016-04-15 16:48 UTC
Labels: confirmed, known-fix, pull-requests-encouraged

**Comment by trajano** [comment] 2016-04-18 20:40
I need to check whether this can work with JQuery UI now :+1:

**Comment by trajano** [comment] 2016-04-18 21:21
Still a bit flakey, but that is to be expected if you use existing jQuery plugins that are not using imports so for those people in that boat (namely myself) removing jquery and ruslan:jquery-ui isn't going to work out without mucking around with legacy JS. :-1:
