### ISSUE TITLE
Inconsistent URL of client-side assets added from onTest

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2580] opened 2014-09-13 04:31 UTC
In [our package](https://github.com/peerlibrary/meteor-crypto) I add for testing a static asset:

```
  api.add_files([
    'assets/test.pdf'
  ], ['client', 'server'], {isAsset: true});
```

The issue is that when testing with:

```
meteor test-packages ./
```

the location of this asset becomes `/packages/local-test:peerlibrary:crypto/assets/test.pdf`, but otherwise is `/packages/peerlibrary:crypto/assets/test.pdf`. This is bad because tests then fail as it is not expected `/packages/peerlibrary:crypto/assets/test.pdf`.

**Comment by glasser** [comment] 2015-02-25 00:07
I think this is basically a duplicate of #1193.

**Closed by glasser** 2015-02-25 00:07 UTC
Labels: Project:Isobuild

**Comment by mitar** [comment] 2015-02-25 03:49
I agree. :-)

**Comment by D1no** [comment] 2015-04-03 08:09
I am stuck on this issue: finding the **correct URL to a static file during testing**. Without sparking a new discussion here, I created a [stackoverflow question](http://stackoverflow.com/questions/29428484/url-to-package-assets-ontest-for-scrape-testing) to clarify the outcome who minds to reply.
