### ISSUE TITLE
Using arrays defined in vm not recognized by Blaze #each directive

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#8160] opened 2016-12-15 21:15 UTC
I am creating arrays in a VM.  Then I am using these arrays in my Blaze template.  Blaze does not recognize that these are valid arrays.

## Environment
meteor v1.4.2.3

## Explanation

Blaze depends on the Meteor observe_sequence package.  And the observe_sequence package uses `instanceof Array` to determine if the sequence is an array.  `instanceof Array` does not work across windows, because there are 2 instances of `Array` one in each window.

There is a writeup [here](http://web.mit.edu/jwalden/www/isArray.html).

## Fix
change these 2 lines to use `Array.isArray(seq)` instead of depending on `instanceof Array`.
[observe_sequence.js#L97](https://github.com/meteor/meteor/blob/fe143dd84752bc3dea42ea35d44c2d4e93ba14f5/packages/observe-sequence/observe_sequence.js#L97)
[observe_sequence.js#L129](https://github.com/meteor/meteor/blob/fe143dd84752bc3dea42ea35d44c2d4e93ba14f5/packages/observe-sequence/observe_sequence.js#L129)

**Comment by stubailo** [comment] 2016-12-15 22:01
Would be great to see a PR for this - looks like a simple fix!

**Comment by mitar** [comment] 2016-12-16 00:16
I think we should just use `_.isArray`.

**Comment by stubailo** [comment] 2016-12-16 00:17
Isn't `Array.isArray` just a standard version of the exact same thing?

**Comment by mitar** [comment] 2016-12-16 00:17
Yes, and Underscore will use it if it is available, no?

**Comment by mitar** [comment] 2016-12-16 00:18
BTW, what is VM?

**Comment by stubailo** [comment] 2016-12-16 00:19
Yeah I guess avoiding underscore dependencies is a lost cause at this point.

**Comment by mitar** [comment] 2016-12-16 00:21
I mean, we should replace underscore with lodash, but otherwise it is a good idea to have a layer of abstraction in between.

**Comment by brucejo75** [comment] 2016-12-16 04:57
I am using `vm.browserify` to do my evals to keep the evals safe from global corruption.  They refer to running it in a `vm` (aka virtual machine), but I think it is just really another window.

**Comment by abernix** [comment] 2016-12-16 16:30
@brucejo75 Would there be anything stopping you from making a PR for this?  In other words, is there anything I/Meteor/we can do to help you submit your first PR?

**Comment by brucejo75** [comment] 2016-12-16 17:01
Thanks @abernix.  I will take a shot at it. Never submitted a PR to Meteor.  I will carve some time today.

**Comment by brucejo75** [comment] 2016-12-16 18:28
I may need some help.  Here is what I did:

1. forked meteor
2. made code change in `observe-sequence.js`
2. ran `.\meteor test-packages`
3. pointed my browser here: `http://localhost:3000/`

1335 tests of 1390 passed.  Most errors are this:

```
- exception - message Invalid array buffer length
RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at C_MINISAT (packages\logic-solver.js:22:20101)
    at new MiniSat (packages\logic-solver.js:93:21)
    at new Logic.Solver (packages\logic-solver.js:620:19)
    at packages\constraint-solver.js:1575:26
    at Function.CS.DummyProfile.time (packages\constraint-solver.js:2322:10)
    at [object Object].CS.Solver._getAnswer (packages\constraint-solver.js:1574:11)
    at packages\constraint-solver.js:1561:17
    at Function.CS.DummyProfile.time (packages\constraint-solver.js:2322:10)
    at [object Object].CS.Solver.getAnswer (packages\constraint-solver.js:1560:23)
```

I took a look at C_MINISAT.  single line of > 1000 characters.  :-).  But it looks like it has nothing to do with Blaze.

Next steps?

**Comment by mitar** [comment] 2016-12-17 09:37
Interesting. Didn't know about `vm` in the browser.

I think you should not worry about those other tests failing. So yes, create a PR.

**Comment by brucejo75** [comment] 2016-12-17 16:52
OK, I submitted a pull request for this issue.  Fairly benign.

I did a quick search of all instances of 'instanceof Array`.  There are quite a few argument checks for minimongo arguments that use `instanceof`, which could trip this issue again.

Mind if I take a look at this across Meteor?  Should I create separate bug?

**Comment by mitar** [comment] 2016-12-19 10:23
I would change only things where you notice a problem.

**Comment by abernix** [comment] 2016-12-19 10:31
Thanks for submitting that, @brucejo75.  The test failures are likely because running the test command you're using would be running all tests across all packages, some of which are known to fail ([and excluded explicitly](https://github.com/meteor/meteor/blob/8e32da57a128a70fdc09823b5d506758ce6a9b82/.travis.yml#L8)).  If you're ever developing on a particular package within Meteor you can run just that subset of the tests by passing the package name to `test-packages`.  (e.g. `.\meteor test-packages observe-sequence`.  Alternatively, the failures might be Windows-related as I'm not sure that entire suite is run on a Windows box.

If you can reproduce a problem with other instances, I think PRs for those are appropriate there as well but as @mitar says, only if you notice a problem.  Feel free to open separate issues if you feel it's worth separate discussions but I think a sufficient explanation in the PR body referencing this issue might be okay if there are a lot of cases.

**Comment by mitar** [comment] 2016-12-29 20:20
#8166 has been merged in.

**Closed by mitar** 2016-12-29 20:20 UTC
Labels: bug, Impact:few, pull-requests-encouraged, Severity:blocks-development

**Comment by brucejo75** [comment] 2017-02-19 22:48
This fix has an issue.  It does not work for sub-classed Array objects.  See https://github.com/meteor/meteor/pull/8166#event-898979875.

I will work on another PR.
