### ISSUE TITLE
Difference between dev and production

### ISSUE THREAD

**Issue by yanndebelgique** [meteor/meteor#4211] opened 2015-04-16 08:08 UTC
Hello,
I've encountered an elusive bug that has been documented by others on the iron-router project but should be referenced here. On some browsers iron-router when minified does not work properly (no routes are shown).
It should be the responsibility of MDG to make sure that the dev and prod version of an app behave the same way right? I understand this issue is hard to solve since I don't have a reproduction of the bug. Sorry for that.

**Comment by Slava** [comment] 2015-04-16 08:35
Is it the bug of Iron Middleware? https://github.com/meteor/meteor/issues/4030

Iron:Router relies on function's names to decide what code to execute. Things like this do break on minification. Your options are:

- do not use such features of Iron Router
- do not minify
- wait until the minifcation in Meteor becomes more configurable and configure it to not mangle the names

**Comment by yanndebelgique** [comment] 2015-04-16 11:35
yup probably its one and the same.
Thanks for the fast response.
Which features of IR can't I use?

**Comment by Slava** [comment] 2015-04-17 05:25
Then, closing as a duplicate of #4030.

Don't use features relying on the function name, such as iron-middleware-stack

**Closed by Slava** 2015-04-17 05:25 UTC
Labels: Project:Isobuild:Minifiers

**Comment by yanndebelgique** [comment] 2015-04-17 16:37
Ok so I've found the issue!
I had the following code in my lib directory in my client :
'''
 Accounts.ui.config({
    forceApprovalPrompt : true,
    passwordSignupFields: 'USERNAME_AND_EMAIL'
  });
''''
Wrapping it in Meteor.startup(function(){ })made it work! im so happy right now :)
This issue only showed up on mobile browsers! IOS simulator rescued me big time.
