### ISSUE TITLE
package system defaults to ancient versions if no semver is specified?

### ISSUE THREAD

**Issue by dcsan** [meteor/meteor#3282] opened 2014-12-12 07:26 UTC
if add a package with no semver specified it will default to the oldest version:

```
# .meteor/packages
aldeed:autoform

$ meteor update
  downgraded aldeed:autoform from version 4.0.0 to version 0.17.1
  downgraded aldeed:collection2 from version 2.2.0 to version 0.4.6

```
at the very least this seems wrong, it should default to the newest version?

separately, if I specify a recent version, however there is no way to say "at least 4.0" with meteor's flavor of semver. both of these:

```
   aldeed:autoform@4.0.0
   aldeed:autoform@=4.0.0
```
will pull in `4.0.0` where currently that package is at `4.2.0` . 
afaik there is no support for something like 

    aldeed:autoform@>4.0.0

**Comment by dgreensp** [comment] 2015-01-08 00:01
Reopening.

See also https://groups.google.com/forum/#!topic/meteor-talk/dN415Rbcvg0

**Comment by dgreensp** [comment] 2015-01-13 17:34
@RobertLowe, to clarify, your problem was with packages being downgraded that weren't listed in `.meteor/packages`, but were dependencies of packages listed in `.meteor/packages`, correct?

**Comment by RobertLowe** [comment] 2015-01-13 17:48
@dgreensp Yes, I believe that's the case, I'm mobile right now so if memory serves that is correct.

It happens when dependacies are left unspecified.

Cheers

**Comment by dgreensp** [comment] 2015-01-13 18:09
Fixed on devel.

What `meteor update foo` means is: Update the version of `foo` in `.meteor/versions`, and also edit the versions of its dependencies as necessary to satisfy all constraints.  The constraints on direct dependencies in `.meteor/packages` are maintained at all times.  Before this fix, `meteor update foo` only did-what-you-meant if `foo` was a direct dependency.  If `foo` was an indirect dependency (depended on by a package), it would actually downgrade `foo` instead of upgrading it.  This is now fixed.

**Closed by dgreensp** 2015-01-13 18:09 UTC
Labels: Project:Version Solver

**Comment by RobertLowe** [comment] 2015-01-13 19:27
Thanks @dgreensp you're awesome!

**Comment by arunoda** [comment] 2015-01-14 20:10
This may be somewhat related to this issue.

* I've pushed my app into git from a mac
* Then I trying to build it from a CI server (linux)
* Then I see something like below:

~~~
=> Started proxy.

Changes to your project's package version selections:

anti:gagarin                 downgraded from 0.3.3 to 0.3.0
meteorhacks:flow-components  downgraded from 0.0.20 to 0.0.13
meteorhacks:flow-router      downgraded from 0.0.12 to 0.0.2
~~~

None of these is a binary package. I think this is something relevant to this issue.
Is this fix comes with `1.0.3-rc.0` ?

**Comment by dgreensp** [comment] 2015-01-14 21:01
Did you commit .meteor/versions?  Just running the app shouldn't change the versions for no reason.

**Comment by arunoda** [comment] 2015-01-14 21:04
Ah yes. it's there.

**Comment by RobertLowe** [comment] 2015-01-14 21:14
@dgreensp OT: Is there a way to dump a dependancy's tree of dependancies? This would be fairly useful... As of right now it's a bit difficult to see what a dependancy is built on top of other then digging through atmosphere. 

Cheers

**Comment by dgreensp** [comment] 2015-01-15 05:01
@arunoda If you revert .meteor/versions and run again, does it downgrade again, reproducibly?  That sounds like a bug that I'd like to reproduce.  However, I suspect it is because if anything triggers a full run of the constraint solver, indirect dependencies may get downgraded.  That suggests a second question.  After you get the "downgraded" message, if you change only those versions back to what they were, does it downgrade again?

My fix only address what happens when you run `meteor update`, but it allows you to run `meteor update anti:gagarin meteorhacks:flow-components meteorhacks:flow-router` and have it work even if those packages aren't direct (i.e. top-level) dependencies.  The fix is included in 1.0.3.

@RobertLowe You're in luck.  There's no tree, but as of 1.0.3-rc.0, `meteor show foo-package@1.0.0` will list the dependencies of `foo-package@1.0.0`.  Thanks go to ekate for this feature.

**Comment by arunoda** [comment] 2015-01-15 05:07
@dgreensp It's hard to reproduce. Only happens on some linux boxes only. Yes, if I updated again with meteor update it will work correctly.

I try to find if it can be reproduced. Then I'll share the linux VM with you.

**Comment by queso** [comment] 2015-01-28 18:00
I am getting this with codeship test running. When I run the app in the codeship environment, it downgrades the app from 0.3.6 to 0.3.4 (xolvio:cucumber) for some reason.

Will see if I can make a quick repro of it.

**Comment by krstffr** [comment] 2015-02-02 15:45
I'm getting this error when deploying to Heroku servers using the https://github.com/AdmitHub/meteor-buildpack-horse buildpack. Random packages get downgraded unless I specify an exact version for them (running ```meteor add author:package@1.2.3``` for example).

**Comment by queso** [comment] 2015-02-02 15:54
Yes, mine turned out to be the same issue, with no semvar it seemed to just randomly downgrade. Once I pegged xolvio:cucumber@0.3.6, it worked fine on install.

@glasser should we open a new issue since this one is closed?

**Comment by dgreensp** [comment] 2015-02-02 16:31
Is there any way we can reproduce this?  I'd love to get to the bottom of it!

The part that's hard to figure out is that meteor should use the versions in .meteor/versions, which should be checked into your repo.  If it needs to choose different versions for some reason -- which may be possible to trigger based on architecture? I'm not sure -- it should write the new versions to .meteor/versions.  So you should at least be able to see the "paper trail" in .meteor/versions, and reproduce the downgrade repeatedly by reverting it.

Are you able to get the message repeatably?  Thanks.

**Comment by queso** [comment] 2015-02-02 17:03
I will see if I can get a simple repo up and repro on codeship... It has a debug console so you can ssh in and play around with the box directly... I have seen it happen 2 out of 2 times on codeship so far without cucumber being pegged to a version.

**Comment by queso** [comment] 2015-03-14 17:03
@dgreensp I assume MiniSat should solve this?

**Comment by dgreensp** [comment] 2015-03-14 20:11
My understanding is that this issue and #3653 are fixed on `devel`, and in the `METEOR@new-version-solver-2` release (and the upcoming 1.1 RC).
