### ISSUE TITLE
[Meteor 1.5 + React] Detecting changes in updated module exports

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#8811] opened 2017-06-16 12:22 UTC
Recently when upgrading my old app from Meteor 1.4 to 1.5, I've noticed strange behavior with imports. I can't reproduce it but it happened two times already. In both cases, the problem was solved by restarting Meteor app, but it took me some time to make sure that there is no error in my code. The problem is related with static imports and it looks like Meteor sometimes does not detect changes in a module. Let's say that I've exported wrong value from the module, I get an error and later when I update this module to export proper value Meteor fails to detect that and it still sees old value. I'm using React to render some components and the problem only occurred with modules exporting React components. I will try to reproduce this bug when the problem occurs one more time but I'm just curious if anyone had a similar problem.

**Comment by wansj** [comment] 2017-06-16 15:26
I had a similar problem about using vue-top-progress. I'm not sure if it's related with static import. The error indicated that the top-progress.vue file contains error. If I remove the vue-top-progress component from my project and delete the .meteor/local directory,  reinstall the vue-top-progress component and start app again, the error disappears. This happened at least 5 times.

**Comment by hwillson** [comment] 2017-06-16 15:44
Interesting - a reproduction here would really help, but could be quite tricky to put together. Please post any extra details you can think of the next time this happens. Thanks!

**Comment by wansj** [comment] 2017-06-17 13:53
@hwillson Here is a reproduction: [https://github.com/wansj/shift](url). The error in vue-top-progress source file prevented meteor start even though it was just installed from the npm.  After I remove vue-top-progress from the project completely  and start the app, then reinstalling the vue-top-progress package is very likely successful, and the top-progressbar shows normally. Isn't weird?

**Comment by hwillson** [comment] 2017-09-13 12:08
I've updated the repro to use Meteor 1.5.2, updated all `package.json` dependencies, and fired the app up. The app started properly. I did then see `vue-top-progress` errors, but these were just application errors. The way `vue-top-progress` is wired up in the repro isn't quite right. If you change your `imports/startup/client/index.js` as follows, everything works properly:

1) Change `import topProgress from 'vue-top-progress'` to `import { vueTopprogress } from 'vue-top-progress'`.

2) Change 

```js
    components: {
      App,
      NotFound,
      topProgress
    },
```

to

```js
    components: {
      App,
      NotFound,
      vueTopprogress
    },
```

3) Change `<top-progress ref="topProgress"></top-progress>` to `<vue-topprogress ref="topProgress"></vue-topprogress>`.

Since this no longer seems to be an issue with the latest version of Meteor, I'll close this off. Thanks!

**Closed by hwillson** 2017-09-13 12:08 UTC
Labels: Project:Isobuild, Project:Tool
