### ISSUE TITLE
[1.4.2] Breakpoints do not work for files in compatibility folder when debugging

### ISSUE THREAD

**Issue by ignl** [meteor/meteor#7986] opened 2016-10-28 18:55 UTC
After an update to 1.4.2 breakpoints are not hit when set in files in compatibility folder.  Works with 1.4.1.3 version. Windows 10, debugging with Webstorm.

**Comment by abernix** [comment] 2016-11-15 15:13
Have you seen this error with Meteor 1.4.2.1 as well?

I'd like to reproduce and try to offer a solution but I'm not a WebStorm user and I don't have any projects that are using the `compatibility` folder.  Mind putting together an easy explanation?  I'm happy to install WebStorm.

**Comment by ignl** [comment] 2016-11-17 13:00
Yes breakpoints do not work for 1.4.2.2 too. Reproducing it is very simple - just put some library js file into client/compatibilty folder (in my case it's [jquery-all-embed](https://github.com/starfishmod/jquery-oembed-all)) and try to set a breakpoint there. For 1.4.1.x it works and for 1.4.2.x it doesn't. Don't know if it is webstorm related but if it works on your setup then installing webstorm and starting in debug mode is very simple. Webstorm uses chrome extension for client debug so maybe it is related to that somehow... Maybe some changes regarding compatibility folder was done during build tool fixes?

**Comment by hwillson** [comment] 2017-02-16 12:24
While I have been able to confirm this behaviour using WebStorm, I'm not entirely convinced this is a Meteor issue. Using a [`debugger`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/debugger) statement in a `client/compatibility` based file does work properly in WebStorm, so I'm not sure why their UI based breakpoint system isn't working in these files. Regardless, since there is a workaround for this (use `debugger`) and there isn't much interest/activity in this issue (and finding the real problem could be a time consuming process for little gain, especially if it involves tracking down an issue with WebStorm), I'll close this issue for now. Happy to re-open if anyone disagrees. Thanks for posting this originally!

**Closed by hwillson** 2017-02-16 12:24 UTC
Labels: confirmed, Impact:few
