### ISSUE TITLE
[1.5.*] Compressed JS gives "SyntaxError: Parse error" on iOS / Safari 5.1

### ISSUE THREAD

**Issue by anjunatic** [meteor/meteor#9081] opened 2017-09-12 06:15 UTC
**SyntaxError: Parse Error on Line 55**
Unfortunately its not possible to get more detailed error information on iOS Safari

- Meteor 1.5.1, 1.5.2
- iOS 5.1.1 / Safari 5.1

Reproducing:
`meteor create .`
`meteor --production`

**Comment by klaussner** [comment] 2017-09-12 06:29
This looks like a duplicate of #8928. 🙂

**Closed by klaussner** 2017-09-12 06:29 UTC
