### ISSUE TITLE
If meteor method returns an object containing an error object, the call back is never called

### ISSUE THREAD

**Issue by AhmedSayed77** [meteor/meteor#8359] opened 2017-02-13 09:06 UTC
Meteor version: 1.4.2.3

Bug: I was trying to insert an object in db in with a try catch, and in the catch body I pushed the error in an array, then the meteor method returns an object containg the array. i.e.:

server:

`
Meteor.methods({
myMethod: function(options) {
const fails = []
options.records.forEach((record, i) => {
try {
myCollection.insert(record)
} catch (e) {
fails.push({
index: i,
error: e
})
}
})
console.log(fails)
return {
fails: fails
}
}
})
`

client:

`
Meteor.call('myMethod', options, (err, res) => {
    console.log(err, res)
})
`

Behaviour: what happens is that the callback is never called, althought the server logs the array, and no feed back that anything is wrong

Reason: the error object in the array causes the ddp to never call the callback without any feedback - I think because the error object is not serializable (??) - and it behaves normally if i change the code to this
`
fails.push({
    index: i,
    error: {message: e.message, error: e.error}
})
`

**Comment by gaillota** [comment] 2017-02-13 18:03
Hi,

1) Why is there a `:` after `Meteor.methods` ?
2) You can change the `let fails` into `const fails`
3) I think you forgot to add index in `forEach(record, index)`, and you can remove the` : i` after `index`
4) You can't serialize an Error object ([see here](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2017%2Creact%2Cstage-0%2Cstage-3&targets=&browsers=&builtIns=false&code=const%20e%20%3D%20new%20Error('test')%3B%0Aconsole.log(JSON.stringify(e))))

Greetings.

**Comment by AhmedSayed77** [comment] 2017-02-14 09:03
Hi,

1. The`:` is a typo - removed it
2. Changed
3. Typo - fixed
4. Thanks for the link
The first three points are comments on the code -which is obviously not the real code - the issue is that there's no feedback if i try to send an unserializable object, no error thrown, no warning, nothing.

**Comment by gaillota** [comment] 2017-02-14 09:32
What do you mean by "no feedback" ? The `result` object is empty ?

**Comment by AhmedSayed77** [comment] 2017-02-14 15:24
No, the callback in the client is never called, nothing in the client console and nothing in the server console,

**Comment by gaillota** [comment] 2017-02-15 21:48
Did you make sure your `records` object actually throws an error ?

**Comment by AhmedSayed77** [comment] 2017-02-16 08:59
I don't want to throw the error. The client sends an array of objects to be inserted, if one of them fails, I want the server to catch the error, insert it in an array, and keep trying to insert the rest of the array. The solution is to write this

`
try { myCollection.insert(record) } catch (e) { fails.push({ index: i, error: {message: e.message, error: e.error} }) } })
`

instead of this 

`
try { myCollection.insert(record) } catch (e) { fails.push({ index: i, error: e }) } })
`

I just want to report a bug that trying to send an unserializable object from a meteor method blocks the execution of the code without sending any feedback something wrong happened

**Comment by hwillson** [comment] 2017-04-19 13:19
Hi @AhmedSayed77 - it sounds like something outside of Meteor itself is causing this issue (like a 3rd party package, an issue with your code, etc.). Meteor Method calls won't block anything when trying to send an unserializable object back to the client, as part of the Method response. You can verify this by stripping your code down to the basics and testing this, or by clonining/running https://github.com/hwillson/meteor-issue-8359. The unserializable object won't be sent back to the client (this is intended), but you will get a response. 

I'll close this issue for now since this doesn't appear to be an issue with Meteor itself. I'm happy to re-open this if you're able to put together a small, runnable reproduction demonstrating your issue, and it's confirmed to be a Meteor bug (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Closed by hwillson** 2017-04-19 13:19 UTC
