### ISSUE TITLE
[1.3-rc.4] Endless recursing babel compiler on Ubuntu Linux & mup

### ISSUE THREAD

**Issue by danlg** [meteor/meteor#6551] opened 2016-03-21 22:38 UTC
I get this endless debug message babel  when running DEBUG=\* mup deploy on ubuntu:

```
Mon, 21 Mar 2016 22:31:29 GMT babel program.body[17].expression.arguments[1].body.body[19].expression.arguments[1].body.body[0].expression.arguments[1].body.body[0].expression.arguments[1].body.body[0].expression.arguments[1].body.body[3].declarations[0].init.body BlockStatement: enter
Mon, 21 Mar 2016 22:31:29 GMT babel program.body[17].expression.arguments[1].body.body[19].expression.arguments[1].body.body[0].expression.arguments[1].body.body[0].expression.arguments[1].body.body[0].expression.arguments[1].body.body[3].declarations[0].init.body BlockStatement: Recursing into...
```

Removing DEBUG doesn't help, the messages goes away but the build hangs.

I noticed 
babel-compiler@6.5.2-rc.4
babel-runtime@0.1.6-rc.4
are only in versions not package.

When running `meteor build` it compiles on ubuntu.

On mac OSX, mup deploy at least complles (then it breaks because it can't find the archive).

**Comment by benjamn** [comment] 2016-04-05 23:06
Do you still have this problem if you update to 1.3.1?

**Comment by danlg** [comment] 2016-04-26 11:12
@benjamn I have upgraded to 1.3.2.4. I don't have this issue on my dev branch. However, when I want to redeploy a bug fix to my production branch still using `METEOR@1.2.2-faster-rebuilds.0` , I have sometimes the mup build hanging at this stage.
```
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Parse start
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Parse stop
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Start set AST
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: End set AST
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Start module formatter init
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: End module formatter init
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Start transformer builtin-pre
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Finish transformer builtin-pre
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Start transformer builtin-basic
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Finish transformer builtin-basic
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Start transformer builtin-advanced
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Finish transformer builtin-advanced
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Start transformer builtin-modules
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Finish transformer builtin-modules
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Start transformer builtin-trailing
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Finish transformer builtin-trailing
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Start transformer meteor-named-function-expressions
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Finish transformer meteor-named-function-expressions
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Start transformer meteor-sanitize-for-in-objects
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Finish transformer meteor-sanitize-for-in-objects
Tue, 26 Apr 2016 11:06:42 GMT babel [BABEL] password_server.js: Generation start
Tue, 26 Apr 2016 11:06:43 GMT babel [BABEL] password_server.js: Generation end
```

Doing ```sudo dtruss -p <PID>``` on my mac (the ```strace``` equivalent of linux), I get 
```
kevent(0x5, 0x7FFF5FBF57E0, 0x0)		 = 0 0
__semwait_signal(0x190B, 0x0, 0x1)		 = -1 Err#60
kevent(0x5, 0x7FFF5FBF57E0, 0x0)		 = 0 0
__semwait_signal(0x190B, 0x0, 0x1)		 = -1 Err#60
kevent(0x5, 0x7FFF5FBF57E0, 0x0)		 = 0 0
__semwait_signal(0x190B, 0x0, 0x1)		 = -1 Err#60
kevent(0x5, 0x7FFF5FBF57E0, 0x0)		 = 0 0
__semwait_signal(0x190B, 0x0, 0x1)		 = -1 Err#60
```
which seems to indicate a dead lock.

**Comment by abernix** [comment] 2016-07-19 23:49
@danlg Do you have any updates on this?  A lot has changed since that version and if it's not happening anymore, I'd like to close this.

**Comment by abernix** [comment] 2016-11-25 20:20
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)

**Closed by abernix** 2016-11-25 20:20 UTC
