### ISSUE TITLE
/private assets crashes Meteor locally on Windows 7

### ISSUE THREAD

**Issue by artitw** [meteor/meteor#5410] opened 2015-10-12 09:09 UTC
I have been playing around on Windows 7 and tried to run my Meteor app locally with a 500 mb file in the `private` folder. It doesn't even boot up. Here's the sequence:

 1. `meteor create test`
 2. `cd test` and `meteor`
 3. default app loads fine on `localhost:3000`
 4. create a `/private` folder and place a 500 mb text file there
 5. `meteor` dies partway without ever loading on `localhost:3000`
 6. Removed `/private` folder and re-ran. 
 7. Works again after removing `/private` folder.

Anyone knows what may be causing this problem?

**Comment by sebakerckhof** [comment] 2015-10-13 15:13
Duplicate of: https://github.com/meteor/meteor/issues/1129

**Comment by stubailo** [comment] 2015-10-13 20:50
I agree that this is a duplicate of the unfortunate situation where Meteor can't handle large static files inside the app directory. I guess on Windows the file size limit might be smaller, but I bet the root cause is the same.

**Closed by stubailo** 2015-10-13 20:50 UTC
