### ISSUE TITLE
Error in package wrapper

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#6501] opened 2016-03-16 13:41 UTC
After updating to the release candidate for Meteor 1.3, I get this error:
```bash
W20160316-07:04:14.953(-5)? (STDERR) 
W20160316-07:04:14.953(-5)? (STDERR) /Users/zodern/.meteor/packages/meteor-tool/.1.2.4-rc.1.76l9yy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160316-07:04:14.953(-5)? (STDERR) 						throw(ex);
W20160316-07:04:14.954(-5)? (STDERR) 						      ^
W20160316-07:04:14.982(-5)? (STDERR) TypeError: Cannot read property 'meteor' of undefined
W20160316-07:04:14.982(-5)? (STDERR)     at /Users/zodern/dev/bizgame/app/.meteor/local/build/programs/server/packages/zodern_pure-admin.js:4:21
W20160316-07:04:14.982(-5)? (STDERR)     at /Users/zodern/dev/bizgame/app/.meteor/local/build/programs/server/packages/zodern_pure-admin.js:213:3
W20160316-07:04:14.982(-5)? (STDERR)     at /Users/zodern/dev/bizgame/app/.meteor/local/build/programs/server/boot.js:281:10
W20160316-07:04:14.982(-5)? (STDERR)     at Array.forEach (native)
W20160316-07:04:14.982(-5)? (STDERR)     at Function._.each._.forEach (/Users/zodern/.meteor/packages/meteor-tool/.1.2.4-rc.1.76l9yy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160316-07:04:14.982(-5)? (STDERR)     at /Users/zodern/dev/bizgame/app/.meteor/local/build/programs/server/boot.js:133:5
```

The top of the file is 
```javascript
(function () {

/* Imports */
var Meteor = Package.meteor.Meteor;
var global = Package.meteor.global;
var meteorEnv = Package.meteor.meteorEnv;
var Picker = Package['meteorhacks:picker'].Picker;
```

I tried removing the package (it then breaks in another package), and reinstalling meteor.

**Comment by zol** [comment] 2016-03-17 00:19
Please provide a reproduction repository.

**Comment by zodern** [comment] 2016-03-17 01:52
https://github.com/zodern/meteor-issue-6501

The problem is in [pure admin](https://atmospherejs.com/zodern/pure-admin)

**Comment by zol** [comment] 2016-03-17 20:00
@zodern - Thanks for including a repro but I can't reproduce the issue with it. Could you try removing `repro/.meteor/local` and `~/.meteor` and reinstalling Meteor. It's possible something broken may have been cached from previous betas.

**Comment by zodern** [comment] 2016-03-17 20:35
I had done that yesterday in the app that originally had this problem. I just did it again in the repro app and the problem still exists. This was happening in previous 1.3 beta releases also.

**Comment by zodern** [comment] 2016-03-17 20:38
If it helps, pure admin is a local package on my computer.

**Comment by zol** [comment] 2016-03-17 23:34
Right that does help and is the reason your repro worked for me. You should copy that into the packages folder and trim it down to the minimal lines of code that demonstrates the issue.

**Comment by zodern** [comment] 2016-03-18 00:20
I added the package to the repro. [This](https://github.com/zodern/meteor-issue-6501/commit/da6d1597ce064997391fdb8f6712c19f22a072e3) commit has all of the files. The last commit has the minimal files needed to reproduce. The error goes away after deleting the output/pure-admin.js. That file is generated using meteor-build-client from a meteor app in the src folder.

**Comment by zol** [comment] 2016-03-18 23:48
This is not a simple reproduction that we're going to be able to look at. `output/pure-admin.js` is a huge compiled file.

**Comment by zodern** [comment] 2016-03-19 00:07
If you look at the [package.js](https://github.com/zodern/meteor-issue-6501/blob/master/packages/pureadmin/package.js) in the repro, the file is not used. There were other issues of problems with files in packages that were not used, but I thought all of those were fixed.

**Comment by tmeasday** [comment] 2016-03-21 01:54
Can confirm that removing that file solves the problem, fwiw

**Comment by zodern** [comment] 2016-03-21 03:22
Thanks @tmeasday. I was worried that it wasn't reproducible.

When I removed all packages and files from the src app, it works. Adding any package to the src app causes the problem. The latest commit on github now has one package in the src app. If you comment out that line and recompile the file, it should work.

I have been running this from the app root to recompile the file:
```
cd packages/pureadmin && gulp build-client && cd ../.. && meteor
```

**Comment by vohtaski** [comment] 2016-04-04 14:11
I believe I have a similar problem with this package:
https://github.com/okland/accounts-phone

When installed via atmosphere, it works. However, when I install it via local packages folder, it does not work. I believe the same issue is mentioned here:
https://github.com/okland/accounts-phone/issues/22

I have similar log:
```
W20160404-16:03:33.006(2)? (STDERR) /Users/evgeny/.meteor/packages/meteor-tool/.1.3.0_3.nfybcd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160404-16:03:33.007(2)? (STDERR) 						throw(ex);
W20160404-16:03:33.007(2)? (STDERR) 						      ^
W20160404-16:03:33.007(2)? (STDERR) TypeError: Cannot read property 'meteor' of undefined
W20160404-16:03:33.007(2)? (STDERR)     at packages/okland_accounts-phone.js:4:21
W20160404-16:03:33.007(2)? (STDERR)     at packages/okland_accounts-phone.js:868:3
W20160404-16:03:33.008(2)? (STDERR)     at /Users/evgeny/app/.meteor/local/build/programs/server/boot.js:283:10
W20160404-16:03:33.008(2)? (STDERR)     at Array.forEach (native)
W20160404-16:03:33.008(2)? (STDERR)     at Function._.each._.forEach (/Users/evgeny/.meteor/packages/meteor-tool/.1.3.0_3.nfybcd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160404-16:03:33.008(2)? (STDERR)     at /Users/evgeny/app/.meteor/local/build/programs/server/boot.js:133:5
```

The problem is that `Package` is inserted as 'package-scope variables' even though it's now exported or defined globally anywhere.
```js
(function () {

/* Imports */
var Meteor = Package.meteor.Meteor;
var global = Package.meteor.global;
var meteorEnv = Package.meteor.meteorEnv;
// ...

/* Package-scope variables */
var SMS, SMSTest, Package;

(function(){

var Future = Npm.require('fibers/future');
var Twilio = Npm.require('twilio');

SMS = {};
SMSTest = {};
```

@zodern do you have a similar string in your case `var SMS, SMSTest, Package;`?

**Comment by vohtaski** [comment] 2016-04-04 14:34
When I removed `dist` folder with two js files there, it started to work.
I guess, the linker processed that folder and decided that `Package` should be exported as a global variable?

**Comment by abernix** [comment] 2016-07-27 08:33
Not sure when this got fixed but the original repo works fine in Meteor 1.3.5.1.

Closing as resolved.

**Closed by abernix** 2016-07-27 08:33 UTC
Labels: bug, can't-reproduce
