### ISSUE TITLE
update command did not complete even in a day

### ISSUE THREAD

**Issue by shahidkarimi** [meteor/meteor#7136] opened 2016-05-30 06:23 UTC
On windows when I run this command: meteor `update --release 1.3-cordova-beta.5`
It displayed '`Downloading meteor-tool...`' message and never completed.

I left my pc with 30MB internet speed for a day with this command.

What a joke is it? Haven't this issue fixed yet?

**Comment by laosb** [comment] 2016-05-30 07:39
Hi, where are you? It sounds like a CDN problem or something failed silently.

And, `1.3-cordova-beta.5` is an outdated release. The latest beta version is `1.3.3-beta.1` and the latest recommended version is `1.3.2.4`.

**Comment by shahidkarimi** [comment] 2016-05-30 09:50
Again taking the same amount of time. Even from ubuntu... Please tell me how to fix it? @laosb

**Comment by abernix** [comment] 2016-05-30 10:00
Where you located geographically?  There have been issues with CDN speeds lately affecting users in particular areas of the world (see #6960).  The Meteor tool is a 100+Mb download so it could take a while on a slow connection.  Currently, the installer is using a new CDN – could you see if this runs quickly for you:

On OS X, could you see how quickly this command performs for you?

    curl -O -C - https://meteorinstall-4168.kxcdn.com/packages-bootstrap/1.3.2.4/meteor-bootstrap-os.osx.x86_64.tar.gz

**Comment by shahidkarimi** [comment] 2016-05-30 10:01
I am from Lahore, Pakistan. @laosb

**Comment by abernix** [comment] 2016-05-30 11:54
@shahidkarimi How long is a "lot of time"?  On a 10Mbps connection it would be normal for it to take ~2.5 minutes to download.

**Comment by abernix** [comment] 2016-05-31 09:38
Closing as duplicate of #6960.  We do appreciate all help in resolving this matter.  The other issue will track this better and steps are being taken to reduce the size of the Meteor-tool in upcoming versions by 30% or more, which should further help this problem.

Sorry for the troubles you've faced so far.

**Closed by abernix** 2016-05-31 09:38 UTC
