### ISSUE TITLE
[iOS] New Google Native Signin can't complete on iOS - redirects to google.com

### ISSUE THREAD

**Issue by renanccastro** [meteor/meteor#8594] opened 2017-04-13 15:16 UTC
Meteor version: METEOR@1.4.4.1,
Using google-oauth@1.2.2 on iOS.

After clicking the google button for social login, the user is presented with an google account chooser and select the account used to login.
When it ends, the app redirects the user to the google page inside the browser used to input email/password and the login doesn't complete. It is expected that the browser redirects the user back to the app.

Background:
I created the iOS and android app on google developers console and defined the reversed client id inside mobile-config.js(because without it the app doesn't compile)
```
App.configurePlugin('cordova-plugin-googleplus', {
	'REVERSED_CLIENT_ID': 'com.googleusercontent.apps.xxxxxxxxx'
});

```
I can confirm that the keychain-access-groups entitlement is present inside my Entitlements-* plist:

```
		<key>keychain-access-groups</key>
		<array>
			<string>$(AppIdentifierPrefix)com.Cavadinha</string>
		</array>
```

OBS: The same app running on android completes the login flow and the user is successfully authenticated.

Can you guys help me?

**Comment by benjamn** [comment] 2017-04-14 22:24
Hi @renanccastro, this should now be fixed in `google-oauth@1.2.3`, thanks to https://github.com/meteor/meteor/pull/8604 (just merged). Please feel free to reopen the issue if it's still not working for you. I'm glad to hear that Android is working for you, though of course please let us know if `1.2.3` causes any problems on the Android side.

**Closed by benjamn** 2017-04-14 22:24 UTC

**Comment by realyze** [comment] 2017-04-14 23:20
@renanccastro I vaguely recall I had the same problem and in my case it was caused by me using `client id` instead of `iOS URL scheme` as `REVERSED_CLIENT_ID`. And/or by having a typo in the app id in the ios oauth credentials on console.developers.google.com.

I'm pretty sure redirecting to Google instead of the app is caused by a mis-configuration rather than by a bug in Meteor's oauth lib (that would produce an error visible in the app). This just sounds like the browser doesn't know where to go back to (i.e., like a mistyped client id or app id).

**Comment by renanccastro** [comment] 2017-04-17 23:57
@benjamn @realyze Solved my problem, it was caused by a fork I was using because of the conflicts with phonegap-push-plugin (duplicated libs).
That fork was outdated and did not included the newer version of the application:openURL:options: method on AppDelegate.

Once I added, the redirect worked. The code on my [fork](https://github.com/renanccastro/cordova-plugin-googleplus) worked.

Tried to use google-oauth@1.2.3, but cannot login on android anymore(ios works), had to go back to 1.2.2.

The following error spawned:

> I20170417-19:59:53.376(-3)? Exception while invoking method 'login' Error: Failed to fetch tokeninfo from Google. failed [400] {  "error": "invalid_token",  "error_description": "Invalid Value" }
I20170417-19:59:53.376(-3)?     at getScopes (packages/google-oauth/google_server.js:136:7)
I20170417-19:59:53.377(-3)?     at getServiceDataFromTokens (packages/google-oauth/google_server.js:12:16)
I20170417-19:59:53.377(-3)?     at [object Object].<anonymous> (packages/google-oauth/google_server.js:56:27)
I20170417-19:59:53.377(-3)?     at packages/accounts-base/accounts_server.js:471:32
I20170417-19:59:53.378(-3)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:248:14)
I20170417-19:59:53.378(-3)?     at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:468:18)
I20170417-19:59:53.378(-3)?     at [object Object].methods.login (packages/accounts-base/accounts_server.js:531:27)
I20170417-19:59:53.379(-3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170417-19:59:53.379(-3)?     at packages/ddp-server/livedata_server.js:719:19
I20170417-19:59:53.379(-3)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
