### ISSUE TITLE
Hot-code-reload does not work when using UIWebview on IOS

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#7183] opened 2016-06-07 13:29 UTC
WkWebview lacks some important features (see https://github.com/meteor/meteor/issues/7126 and https://github.com/meteor/meteor/issues/7173), but it is possible to switch to UiWebview which does not has these limitations (see https://github.com/meteor/docs/issues/48).

But hot-code-reload on local development does no longer work with UIWebview, so you have the choice between two broken implementations. I did not test hot-code-reload on a production app with UiWebview.

Edit: The UiWebview does reload when you do a local change, but still shows the same content.

**Comment by martijnwalraven** [comment] 2016-06-07 13:37
Hmm, I'm not sure why reload would no longer work with UIWebView. The only place in the code that is WKWebView-specific is [`forceReload()`](https://github.com/meteor/cordova-plugin-meteor-webapp/blob/master/src/ios/WebAppLocalServer.swift#L307-L311), which is only used when reverting to the last known good version.

**Comment by realyze** [comment] 2016-07-21 01:08
It would be great if MDG could bump the priority of this. Rebuilding the whole app to get new changes to the phone you're developing on is just, well, soul crushing.

**Comment by macrozone** [comment] 2016-08-03 16:27
Still an issue, totally forgot about it and ran again in it.

**Comment by lucfranken** [comment] 2016-09-07 15:25
That auto play issue seems to be fixed? Or is that still an active issue? So wouldn't it be fixed by just updating wkwebview?

**Comment by trymbill** [comment] 2016-09-07 22:06
+1, dealing with this issue too.

**Comment by macrozone** [comment] 2016-09-09 08:29
@lucfranken: i'll have to check whether this update is already in meteor's cordova version. Then I could switch to wkwebview

**Comment by ramezrafla** [comment] 2016-09-09 13:55
@trymbill and @macrozone,

Feel your pain! Have you guys tested out hot-code-reload in production? Maybe using a non-local server would fix this (i.e. non-production App but production server)

**Comment by trymbill** [comment] 2016-09-09 15:59
I just switched back to wkwebview and forced meteor to use the latest
version of it and I can confirm that autopsy now works

**Comment by ramezrafla** [comment] 2016-09-09 18:14
Thanks - we are stuck UIWebView for now as we need in-app-browser (that we van control). Do we know if hot code push works on it now?

**Comment by martijnwalraven** [comment] 2016-09-10 08:32
I looked into this, and it seems [a Cordova bug](https://issues.apache.org/jira/browse/CB-11375) is the culprit, and has been been fixed in Cordova iOS 4.2. 

I'm hesitant to upgrade Cordova versions before [the ability to override `cordovaCompatibilityVersions`](https://github.com/meteor/meteor/issues/7030) has been added though, because we'd be blocking hot code push for everyone for a minor update that only affects a small number of users.

**Comment by ramezrafla** [comment] 2016-09-10 13:10
@martijnwalraven
Thanks a lot for addressing this and answering the thread. Looking forward as always. Grateful as always ...

**Comment by macrozone** [comment] 2016-09-12 07:28
@trymbill how did you specify cordova version in meteor?

**Comment by trymbill** [comment] 2016-09-12 19:33
I didn't specify a version of Cordova, I simply replaced the wkwebview plugin as per the meteor guide (https://guide.meteor.com/mobile.html#installing-plugins) under "Installing a plugin from git". I just looked up the latest commit hash on the wkwebview cordova plugin (https://github.com/apache/cordova-plugin-wkwebview-engine) and referenced that when adding it to my meteor project:

```$meteor add cordova:cordova-plugin-wkwebview-engine@https://github.com/apache/cordova-plugin-wkwebview-engine.git#a1da5d22c091ed1d30536ccb31f43a107d89ed4c```

Note that when this fix gets released and Meteor updates the Cordova version you're going to want to remove this package.

**Comment by skirunman** [comment] 2017-05-10 23:20
@abernix I was wondering if this could be closed because of PR #8581

**Comment by hwillson** [comment] 2017-09-12 16:38
As mentioned in https://github.com/meteor/meteor/issues/7183#issuecomment-300639475, this should no longer be an issue. Closing - thanks!

**Closed by hwillson** 2017-09-12 16:38 UTC
Labels: bug, Project:Mobile
