### ISSUE TITLE
Local packages ENOENT .npm missing

### ISSUE THREAD

**Issue by zapaz** [meteor/meteor#7711] opened 2016-08-25 14:00 UTC
[1.4.1.1] local packages ENOENT .npm missing

On ‘meteor run’ got this error :

> => Started MongoDB.
> local:pack: updating npm dependencies -- diacritics, url, fs-extra...
> /root/.meteor/packages/fourseven_scss/.3.9.0.1xdzbya++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
>       throw error;
>       ^
> 
> Error: ENOENT: no such file or directory, rename '/home/app/packages/local_pack/.npm/package-new-14mph1f' -> '/home/packages/local:pack/.npm/package'
>     at Error (native)
>     at Object.fs.renameSync (fs.js:681:18)

Local package ‘local:pack’ is linked inside packages folder into another directory:
/home/app/packages/local:pack -> ../../packages/pack

Seems meteor, some times take local:pack and other times a sanitized version local_pack
Moreover it creates /home/app/packages/local_pack directory with .npm inside

One solution to get rid of the error is to add .npm directory manually inside all local packages /home/packages/*

With lot of local packages this script helps :
cd /home/packages ;
for i in \* ; do mkdir $i/.npm ; done

**Comment by cvax** [comment] 2016-08-25 14:28
I'm getting this on 1.4.1.1 with any packages that has not been previously installed on prior versions of Meteor. If I go back to an older, say 1.4.0.1 project, and run "meteor add" on it, it adds the package. Then when I go back to 1.4.1.1 and try to add the same package a second time it starts to work.

I am on Win7 x64.

**Comment by valentinvichnal** [comment] 2016-08-27 21:25
+1

**Comment by quintstoffers** [comment] 2016-08-29 07:39
I'm seeing this as well. In our case my case I didn't add the .npm directories in version control, causing this error on my CI environment. Adding the .npm directories to VCS fixed the error, but causes the Meteor server to restart once after installing the packages.

**Comment by elliotberg** [comment] 2016-09-01 18:18
I think I am having the same problem.
```
=> Started proxy.
=> Started MongoDB.
C:\Users\elliot\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\elliot\AppData\Local\Temp\mt-1wstfe9\os\packages\infinitedg_winston.js'
    at Error (native)
```

**Comment by abernix** [comment] 2016-09-14 15:36
Not confirming as a bug as I haven't had time to reproduce, but for the purposes of issue tracking, if someone could provide the exact shell commands to reproduce this from scratch it would facilitate any fix for this!

**Comment by zapaz** [comment] 2016-09-15 15:38
@abernix here is a script to reproduce the problem :
 
```
#!/bin/bash

meteor create issue-7711
cd issue-7711
mkdir packages
cd packages
meteor create --package my:pack
ls
# 'pack' directory created instead of my:pack
mv pack my:pack
cd my:pack
> pack.js
echo "Npm.depends({'fs-extra':'0.30.0'})" >> package.js
cd ../..
meteor add my:pack
# crash
ls packages
# wrong directory created with .npm, create good one :
mkdir packages/my:pack/.npm
meteor add my:pack
# works fine ...
cd ..
rm -rf issue-7711
```

**Comment by abernix** [comment] 2016-09-21 08:52
Thank you very much for the reproduction!   Someone will look into this as soon as possible.

**Comment by quintstoffers** [comment] 2016-10-04 15:14
It looks like this comes down to once again supporting packages with a colon instead of underscores. It turns out that this is also causing our server to restart in our CI environment because the creation of the directory "foo_package" instead of "foo:package" triggers the file watchers.

**Comment by johanbrook** [comment] 2016-10-28 14:23
I get this issue for our `lookback:emails` package when running in CI: https://circleci.com/gh/lookback/meteor-emails/3:

```
...
   Building package lookback:emails          /
                                              
/home/ubuntu/.meteor/packages/meteor-tool/.1.4.1_1.pjl67t++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, rename '/home/ubuntu/meteor-emails/example/packages/lookback_emails/.npm/package-new-1j4yiic' -> '/home/ubuntu/meteor-emails/example/packages/lookback:emails/.npm/package'
    at Error (native)
    at Object.fs.renameSync (fs.js:681:18)
    at Object.wrapper [as rename] (/tools/fs/files.js:1519:35)
    at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:968:9)
```

Works locally though, when invoking the `npm test` command (as the CI does).

**Comment by abernix** [comment] 2016-12-02 15:31
I believe this bug was caused by the fix to #7661, as I explained in https://github.com/meteor/meteor/issues/7661#issuecomment-263936772.

As I explain in that comment, I think the fix would be to use https://github.com/abernix/meteor/commit/991eb1dd5ad0f534f533590b43b90e183cdac09d instead of the previous commits (61c1ab0cac9f437f7472d526cf391ea565c9a0bb + 4c1fe8ff2205922e0659a69b81cb5c5ddd139fe2).

I _believe_ it would be safe to make that change.

**Comment by hwillson** [comment] 2017-11-02 19:59
I've confirmed this is still happening with Meteor 1.6.

**Comment by hwillson** [comment] 2018-02-13 18:01
There hasn't been any activity on this issue in quite some time, so I'll close it for now. If anyone is still encountering this problem, and is interested in working on a fix, please let us know. Thanks!

**Closed by hwillson** 2018-02-13 18:01 UTC
Labels: Impact:few, Project:Isobuild, Severity:has-workaround, bug, confirmed, pull-requests-encouraged

**Comment by ujwal-setlur** [comment] 2018-05-29 20:18
This is still an issue.
