### ISSUE TITLE
Meteor Update not working

### ISSUE THREAD

**Issue by amanpriyadarshi** [meteor/meteor#7310] opened 2016-06-27 07:12 UTC
Hi,

I have been trying to update meteor but it doesn't work. 
Below is the code for the same. I'm connected to the internet yet getting the same error message.

`aman@Aman:~/meteor/todos$ meteor --version`
`Meteor 1.3.4`
`aman@Aman:~/meteor/todos$ meteor update`
`Sorry, Meteor 1.3.4.1 is not installed and could not be downloaded. Please 
check to make sure that you are online.`

**Comment by benjamn** [comment] 2016-06-27 17:20
What do you see when you do
```sh
ls -al ~/.meteor/packages/meteor-tool/
```
in your terminal? Here's what I see:
```sh
total 136
drwxr-xr-x   37 ben  staff  1258 Jun 24 16:19 ./
drwxr-xr-x  159 ben  staff  5406 Jun 24 16:15 ../
drwxr-xr-x   18 ben  staff   612 Jun 24 16:15 .1.0.44.3be3lo++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun 24 16:19 .1.1.7.1qd5mv5++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Apr 20 16:02 .1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun 16 17:55 .1.3.3-1-rc.0.cg4zxl++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun 17 14:15 .1.3.3-1-rc.2.1rdsssn++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 May 20 19:02 .1.3.3-beta.0.1vyw4cf++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun  3 13:30 .1.3.3-rc.0.1brqola++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun  7 10:54 .1.3.3-rc.1.1vv4iea++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun  7 18:15 .1.3.3-rc.4.1lp0wd3++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun  9 13:05 .1.3.3-rc.5.6lo7fv++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun 10 17:05 .1.3.3.iio469++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun 17 18:53 .1.3.3_1.v88a39++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun 21 09:37 .1.3.4-rc.0.19jkg9v++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun 21 10:46 .1.3.4-rc.0.hn79rn++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun 22 16:12 .1.3.4-rc.2.vkj7nu++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun 22 17:56 .1.3.4.tcvrn0++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun 24 12:21 .1.3.4_1.117akp1++os.osx.x86_64+web.browser+web.cordova/
drwxr-xr-x   15 ben  staff   510 Jun 23 18:01 .1.4.0-beta.1.1xp4g75++os.osx.x86_64+web.browser+web.cordova/
lrwxr-xr-x    1 ben  staff    53 Jun 24 16:15 1.0.44@ -> .1.0.44.3be3lo++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    53 Jun 24 16:19 1.1.7@ -> .1.1.7.1qd5mv5++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    54 Apr 20 16:02 1.3.2_4@ -> .1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    52 Jun 10 17:05 1.3.3@ -> .1.3.3.iio469++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    59 Jun 16 17:55 1.3.3-1-rc.0@ -> .1.3.3-1-rc.0.cg4zxl++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    60 Jun 17 14:15 1.3.3-1-rc.2@ -> .1.3.3-1-rc.2.1rdsssn++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    60 May 20 19:02 1.3.3-beta.0@ -> .1.3.3-beta.0.1vyw4cf++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    58 Jun  3 13:30 1.3.3-rc.0@ -> .1.3.3-rc.0.1brqola++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    58 Jun  7 10:54 1.3.3-rc.1@ -> .1.3.3-rc.1.1vv4iea++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    58 Jun  7 18:15 1.3.3-rc.4@ -> .1.3.3-rc.4.1lp0wd3++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    57 Jun  9 13:05 1.3.3-rc.5@ -> .1.3.3-rc.5.6lo7fv++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    54 Jun 17 18:53 1.3.3_1@ -> .1.3.3_1.v88a39++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    52 Jun 22 17:56 1.3.4@ -> .1.3.4.tcvrn0++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    57 Jun 21 10:46 1.3.4-rc.0@ -> .1.3.4-rc.0.hn79rn++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    57 Jun 22 16:12 1.3.4-rc.2@ -> .1.3.4-rc.2.vkj7nu++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    55 Jun 24 12:21 1.3.4_1@ -> .1.3.4_1.117akp1++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 ben  staff    60 Jun 23 18:01 1.4.0-beta.1@ -> .1.4.0-beta.1.1xp4g75++os.osx.x86_64+web.browser+web.cordova
```

**Comment by benjamn** [comment] 2016-06-27 17:22
If you have a symlink called `1.3.4_1`, try deleting it and the actual directory it points to (e.g. `.1.3.4_1.117akp1++os.osx.x86_64+web.browser+web.cordova`), then try `meteor update` again.

**Comment by abernix** [comment] 2016-06-28 15:26
Maybe networking issues?  Maybe related to #7317?

**Comment by indesignlatam** [comment] 2016-07-09 23:23
Im having a similar issue, im on meteor 1.3.4.1 but when running meteor update i get this

This project is already at Meteor 1.3.4.1, the latest release.

when running
````sh
ls -al ~/.meteor/packages/meteor-tool/
````

i get this: 
````sh
drwxr-xr-x   14 pmogollon  staff   476 Jul  9 14:04 .
drwxr-xr-x  208 pmogollon  staff  7072 Jul  8 08:39 ..
drwxr-xr-x   15 pmogollon  staff   510 Jul  3 14:31 .1.3.2_4.14eu6k0++os.osx.x86_64+web.browser+web.cordova
drwxr-xr-x   15 pmogollon  staff   510 Jun 22 08:16 .1.3.3.5dgu3n++os.osx.x86_64+web.browser+web.cordova
drwxr-xr-x   15 pmogollon  staff   510 Jun 17 17:12 .1.3.3_1.1l8kce++os.osx.x86_64+web.browser+web.cordova
drwxr-xr-x   15 pmogollon  staff   510 Jun 24 10:23 .1.3.4.13jonbp++os.osx.x86_64+web.browser+web.cordova
drwxr-xr-x   15 pmogollon  staff   510 Jun 24 13:36 .1.3.4_1.xz9u64++os.osx.x86_64+web.browser+web.cordova
drwxr-xr-x   15 pmogollon  staff   510 Jul  9 14:04 .1.3.4_3.18kk0o7++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 pmogollon  staff    55 Jul  3 14:31 1.3.2_4 -> .1.3.2_4.14eu6k0++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 pmogollon  staff    52 Jun 22 08:16 1.3.3 -> .1.3.3.5dgu3n++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 pmogollon  staff    54 Jun 17 17:12 1.3.3_1 -> .1.3.3_1.1l8kce++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 pmogollon  staff    53 Jun 24 10:23 1.3.4 -> .1.3.4.13jonbp++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 pmogollon  staff    54 Jun 24 13:36 1.3.4_1 -> .1.3.4_1.xz9u64++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 pmogollon  staff    55 Jul  9 14:04 1.3.4_3 -> .1.3.4_3.18kk0o7++os.osx.x86_64+web.browser+web.cordova
````

but i cant find the symlink you talk about.

**Comment by abernix** [comment] 2016-07-11 09:13
@indesignlatam Consider updating to Meteor 1.3.4.4 which came out last night by running this inside your project directory:

    meteor update --release 1.3.4.4

**Comment by indesignlatam** [comment] 2016-07-11 11:51
Updating without --release worked at this time. Still very strange what happened before.

@abernix Thanks

**Comment by raffibag** [comment] 2016-07-13 16:39
You might also want to try running:

`curl https://install.meteor.com/ | sh`

That was, ultimately, the only thing that worked for me as it removed the existing install before downloading and installing release 1.3.4.4.

**Comment by indesignlatam** [comment] 2016-07-13 16:42
@raffibag before being able to update i tried that with no success.

**Comment by abernix** [comment] 2016-07-14 07:56
There were changes to the way the dev_bundle symlink worked in 1.3.4.4 that would probably resolve this and things could have got stuck.  An update or reinstall should fix it if you happen to be in that position.

Closing this issue because I believe it has been resolved if you update to 1.3.4.4, but please feel free to @mention me if you think it should be reopened.

**Closed by abernix** 2016-07-14 07:56 UTC
Labels: bug, Project:Tool, Severity:blocks-development

**Comment by rkusetty1** [comment] 2017-06-16 04:42
Friends, I currently have 1.5 but the project which was given by my client is developed using meteor 1.3.4.4.
When I ran the command, meteor update --release 1.3.4.4
It says:
Sorry, this project uses Meteor 1.3.4.4, which is not installed and could not be downloaded. Please check to make
sure that you are online.
   Downloading meteor-tool@1.3.4_4...        \

I even tried by removing --release 1.3.4.4, but the same error:
Sorry, this project uses Meteor 1.3.4.4, which is not installed and could not be downloaded. Please check to make
sure that you are online.
   Downloading meteor-tool@1.3.4_4...        \

Kindly help as it's a blocker for my work.

**Comment by abernix** [comment] 2017-06-16 07:43
@rkusetty1 Definitely should work.  I just confirmed that the release is still published!  You should check your internet connection to make sure it can download the tool correctly from `https://warehouse.meteor.com/`.

**Comment by ShravanBelde** [comment] 2018-11-01 18:10
Hi, @abernix @rkusetty1  I have the same problem. Checked my internet connection and Access Blocked to https://warehouse.meteor.com/, Can you guys direct me about how to solve this problem?

**Comment by pineshmenat** [comment] 2018-11-06 15:15
On some network or machine setups Meteor's installer for Windows may fail. In such cases, follow these simple steps to install Meteor manually:

Install 7-Zip or any other program that knows how to extract tar.gz files.
Download meteor of specific version by changing it in below URL (change 1.5 to 1.x) and install it manually: https://static-meteor.netdna-ssl.com/packages-bootstrap/1.5/meteor-bootstrap-os.windows.x86_32.tar.gz
In a command prompt, run echo %LocalAppData%\.meteor -- this is the directory in which Meteor should be installed.
Extract the installation archive into the directory above.
Add this directory to your PATH environment variable.
You should now be able to open a new command prompt and run meteor. Some versions of Windows may require restarting your machine first.

**Comment by toledoroy** [comment] 2021-09-14 16:15
A solution for the record, and future generations (since I just encountered the same issue)
Check your /etc/hosts file
[For an unknown reason in my /etc/hosts file, there was the entry: 54.192.225.217 warehouse.meteor.com; removed that entry](https://forums.meteor.com/t/solved-error-certificate-has-expired/49912/4), now it's working again.
