### ISSUE TITLE
Polymer 1.0 icon rendering issue while using blaze in Chrome

### ISSUE THREAD

**Issue by mattiLeBlanc** [meteor/meteor#4528] opened 2015-06-10 00:01 UTC
**_1 Upvote**_ Hi,

While using Blaze and Polymer I am running in some rendering issues.
Already posted on Polymer's gitpage: https://github.com/PolymerElements/iron-icon/issues/19#issuecomment-110401978

However,
for me it seems to be related to Blaze.
When I render the following in a template:

```
iron-icon(icon="inbox" item-icon)
                        | Inbox

```

I receive the message in Chrome Console: [iron-icon::_updateIcon]: could not find iconset `icons`, did you import the iconset?

When I make a standalone project without Blaze, the icon renders fine in Blaze.

When in Blaze, I make use of WebComponentsReady event to render the icon, it renders fine.
However, when I wait for Blaze itself to render only when WebCompontentsReady has fired, then my whole scaffold layout is rendered incorrectly:

```
#Jade code
paper-drawer-panel
    paper-header-panel(drawer)
        paper-toolbar
            div Application
        paper-input#searchInput(label="Search")

        div
            paper-menu
                 paper-item
                    iron-icon(icon="inbox" item-icon)
                    | Inbox


    paper-header-panel(main='')
        paper-toolbar
            paper-icon-button(icon='menu', paper-drawer-toggle='')
            div Title
        div
            +Template.dynamic template=main

```

I am not sure where the origin of the issue is, Blaze or Polymer or a combination of both. However, I would like resolve this issue.

I have added a test Repo demonstrating the issue here:

https://github.com/mattiLeBlanc/blaze-polymer1-test

You are required to have Meteor installed to test.

**Comment by emmanuelbuah** [comment] 2015-06-10 14:39
+1. It looks like its blaze related. I'm currently digging around to find out the cause. Hope others can help address this issues as well. @mattiLeBlanc you might want to include paper-drawer-panel to your test repo.

**Comment by Slava** [comment] 2015-06-10 21:32
I don't have any expertise in Polymer. It would be surprising if Blaze is breaking something for Polymer but not impossible.

That would be great if you could reduce the reproduction to the set of DOM manipulations Polymer performs that break because of Blaze.

**Comment by emmanuelbuah** [comment] 2015-06-12 21:26
@Slava I created a repo here https://github.com/emmanuelbuah/meteorpolymer to demonstrate the issue. I spent sometime digging into blaze render but had no luck so hopeful, you will be able to find what I missed. The repo has two navigable pages. 

### Steps to reproduce issues
1. Load app. Page 1 will display with a polymer button. It display as it should.
2. Navigate to Page 2 
3. Navigate back to page 1 
Expected result: Page 1 should display with polymer button 
Actual result: Page 1 shows with polymer button broken. 

If you look at the html, it looks like on rerending Page 1, the button html is some how messed up.

On page load, the button html looks like this 

```
<paper-button raised="" role="button" tabindex="0" aria-disabled="false" class="x-scope paper-button-0">

    <paper-ripple class="style-scope paper-button">
    <div id="background" class="style-scope paper-ripple"></div>
    <div id="waves" class="style-scope paper-ripple"></div>
  </paper-ripple>

    <paper-material animated="" class="content  style-scope paper-button x-scope paper-material-0" elevation="1">
    
      BUTTON
    
  </paper-material>

  </paper-button>
```

On page 1 rerender, the button text is outside the paper-material tag

```
<paper-button role="button" tabindex="0" aria-disabled="false" raised="" class="x-scope paper-button-0">

    <paper-ripple class="style-scope paper-button">
    <div id="background" class="style-scope paper-ripple"></div>
    <div id="waves" class="style-scope paper-ripple"></div>
  </paper-ripple>

    <paper-material animated="" class="content  style-scope paper-button x-scope paper-material-0" elevation="1">
    
      
     </paper-material>

  BUTTON</paper-button>
```

**Comment by Slava** [comment] 2015-06-12 21:33
@emmanuelbuah As I said above, it would help us a lot if you simplify the reproduction by narrowing down the exact DOM manipulations Polymer does that conflict with Blaze.

**Comment by emmanuelbuah** [comment] 2015-06-12 23:08
@Slava  I found the "exact DOM manipulations" causing the issues. Polymer components/tags inherits from dom element in order to participate in dom events: create, attach and detach. On create via document.createElement, the polymer elements generate specific children elements (per design). For example, document.createElement('paper-button') generates an elem with structure

```
<paper-button role="button" tabindex="0" aria-disabled="false" raised="" class="x-scope paper-button-0">
    <paper-ripple class="style-scope paper-button">
    <div id="background" class="style-scope paper-ripple"></div>
    <div id="waves" class="style-scope paper-ripple"></div>
  </paper-ripple>
    <paper-material animated="" class="content  style-scope paper-button x-scope paper-material-0" elevation="1">
     </paper-material>
</paper-button>
```

This happens in function - materializeTag in blaze/materalizer.js. After the element is created, blaze proceeds to append its children to the element. With our sample/example, the inner child of the button is the text BUTTON which results in 

```
<paper-button role="button" tabindex="0" aria-disabled="false" raised="" class="x-scope paper-button-0">
    <paper-ripple class="style-scope paper-button">
    <div id="background" class="style-scope paper-ripple"></div>
    <div id="waves" class="style-scope paper-ripple"></div>
  </paper-ripple>
    <paper-material animated="" class="content  style-scope paper-button x-scope paper-material-0" elevation="1">
     </paper-material>
  BUTTON</paper-button>
```
Mean while, polymer expects a paper-button structure to look like this 
```
<paper-button raised="" role="button" tabindex="0" aria-disabled="false" class="x-scope paper-button-0">
    <paper-ripple class="style-scope paper-button">
    <div id="background" class="style-scope paper-ripple"></div>
    <div id="waves" class="style-scope paper-ripple"></div>
  </paper-ripple>
    <paper-material animated="" class="content  style-scope paper-button x-scope paper-material-0" elevation="1">
      BUTTON
  </paper-material>
  </paper-button>
```

### Why its works on first load
On initial page load, the elements displays properly for when blaze materalizing kicks in for polymer element base library hasn't been loaded yet. Without the polymer library, the function materializeTag in blaze/materalizer.js produces the simple html element 

```
<paper-button>BUTTON </paper-button>
```
and appends it to the dom. After polymer element library loads, it finds all polymer tags in the page and augments them to produce the final structure.

**Comment by Slava** [comment] 2015-06-12 23:25
@emmanuelbuah I cannot open your reproduction, it doesn't have a `.meteor` folder. Without it, I can't make sure we use the same set of packages.

**Comment by emmanuelbuah** [comment] 2015-06-13 03:45
Sorry @Slava. Rectified the issue. The repo includes .meteor folder now.

**Comment by mattiLeBlanc** [comment] 2015-06-13 08:19
@emmanuelbuah I updated my test project: 
https://github.com/mattiLeBlanc/blaze-polymer1-test

it now includes a global html and a icon template.
In the client/startup I do the defer as mentioned by Loneandroo.
It breaks the paper-drawer setup, when you comment the return in the polymer.js startup file

**Comment by rohanray** [comment] 2015-06-14 17:23
I also have similar issues around paper-header-panel. Issue description @ http://stackoverflow.com/questions/30784680/meteor-polymer-1-0-template-dynamic-using-helper-is-not-working I have done a repo in Cloud 9 @ https://ide.c9.io/rohanray/socioui

can be checked live @ https://socioui-rohanray.c9.io

**Comment by rohanray** [comment] 2015-06-14 17:25
Polymer icon issue can be found here @ http://stackoverflow.com/questions/30608194/polymer-1-0-default-icon-set-in-iron-icons-not-working-using-blaze-meteor-temp/30713035#30713035

**Comment by emmanuelbuah** [comment] 2015-06-15 14:30
@Slava Not to overwhelm you but I thought it will be best to provide more info in relation polymer interoperability with other libraries. Polymer currently provides a custom api https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api for dom manipulation relating to polymer components. It looks like the team is aware of the fact that not all dom manipulation libraries will/can incorporate their custom api. They are currently working on an experimental feature/patch - https://github.com/Polymer/polymer/blob/master/src/lib/experimental/patch-dom.html that will allow existing dom manipulation libraries to work with polymer without augmentation.

**Comment by jordangarside** [comment] 2015-06-24 15:06
:+1:

**Comment by kctang** [comment] 2015-07-07 13:55
I created [kctang/meteor-polymer-test](https://github.com/kctang/meteor-polymer-test) to demonstrate integration issues between Meteor and Polymer 1.0. It is very easy to try out just `bower install` and `meteor`.

The demo pages in http://localhost:3000/demo based on [PolymerElements/app-layout-templates](https://github.com/PolymerElements/app-layout-templates) works nicely.

However, I can't seem to get `iron-icon` and `paper-radio-button` to work nicely together. Details is on the repository's README.md. Other Polymer features like `<form is="iron-form">` does not work too.

I think it has something to do with how materializer.js creates elements - described in this SO [post](http://stackoverflow.com/questions/30807881/polymer-iron-form-not-working). I wanted to tweak `materializeTag` in materializer.js but do not know how to do that.

Any hints on how to resolve the issue highlighted in my test repo is very much appreciate.

**Comment by ciampo** [comment] 2015-08-26 17:38
I have the same problem: I use [Swiper](http://www.idangero.us/swiper) for a carousel component. Slides are made or ```paper-card``` elements, and contain a ```paper-button``` element.
When I enable the looping behaviour on the carousel, the slides are copied. In the copied version of the slides, the buttons are broken, because of the same issue.

Any help ?

**Comment by brylie** [comment] 2016-02-15 03:22
Please support web component alignment in Blaze 2. See issue #6236.

**Comment by aruntk** [comment] 2016-04-01 19:11
Use polymer as the default view layer using mwc:synthesis package https://forums.meteor.com/t/polymer-meteor-with-meteor-webcomponents-packages/20536

**Comment by hwillson** [comment] 2016-12-06 13:32
I've moved this issue over to meteor/blaze#194 - closing here. Thanks!

**Closed by hwillson** 2016-12-06 13:32 UTC
Labels: Project:Blaze
