### ISSUE TITLE
Accounts.onLogin clientside not firing when user re-opens page and is already logged in

### ISSUE THREAD

**Issue by joaobarcia** [meteor/meteor#5127] opened 2015-09-09 13:16 UTC
onLogin is not firing when user opens the page and is already logged in, only when user actively goes from logged out to logged in state.

On the server side it works on both situations and it seems that it should work that way as well for the client side, at least for my use case. Is there any way around this? Is it possible to implement?

Thanks

**Comment by stubailo** [comment] 2015-09-15 21:26
Thanks for reporting! I agree that it should be consistent on the client and server.

I suspect that a workaround on the client could be:

```js
Tracker.autorun(function () {
  nowLoggedIn = !! Meteor.userId();

  if (nowLoggedIn) {
    alert("just logged in!");
  }
});
```

This should fire both when the user first logs in, and when they load any other page. Let me know if that works for you.

**Comment by luisreyes** [comment] 2015-09-16 00:46
Should the onLogin event only fire when the action has taken place? In my application `Accounts.onLogin` is firing on page refresh and I wish it wasn't since im trying to redirect them to the user's profile page when they successfully log in.

If I use the `Accounts.onLogin` it fires every time the user hit refresh or manually enter a url. Am I missing something?

**Comment by stubailo** [comment] 2015-09-16 02:21
Hmm, I didn't actually test it. It would make a lot of sense for `onLogin` to only fire when the user actually initiates a login.

**Comment by skifaster** [comment] 2015-11-24 17:20
Is there any progress on the issue? Any updates on what should be expected? In our current use case, we need to be able to log when people "login". Right now we define "login" as when someone provides a username and password, or provides a login token; not when a resume token is being re-negotiated on client/server. 

Having a parameter that provides the difference between resume token and other login methods would also work for our current scenario. 

Any feedback is much appreciated.

**Comment by LDubya** [comment] 2016-01-26 10:18
Bump. This is annoying. I want to redirect new logins to the dashboard. However it's also redirecting page-refreshes and URL links to the dashboard, since it counts those as logging in. This is not how anyone expects this to work.

**Comment by craigdrayton** [comment] 2016-02-03 08:03
I'm also encountering this issue - Accounts.onLogin is triggering every time the user changes page. I'm unable to simply redirect a newly logged in user to a particular route.

**Comment by rvrv** [comment] 2016-02-17 19:40
Im having same issue here. I want to call some redirects only when user successfuly logging in, and Accounts.onLogin is called also when logged user refresh page. 

As a workaround i call my redirects from onSubmitHook delivered by useraccounts:core as mentioned here https://github.com/meteor-useraccounts/core/blob/master/Guide.md#configuration-api

Hope this helps someone. Cheers.

**Comment by tylerhartley** [comment] 2016-03-04 18:14
Discovering that a code reload fires the client-side `onLogin`, but closing the tab and re-opening it does not. In both cases, the server-side `onLogin` hook fires. I am thoroughly confused...while I'm sure there's an explanation, it certainly is not expected behavior for a user or a dev.

**Comment by lorensr** [comment] 2016-03-10 18:50
On the server, `onLogin` fires during any login, including a resume login. On the client, `onLogin` does not fire during a resume login.

**Comment by lorensr** [comment] 2016-03-12 01:08
Here are two workarounds: one that watches client-side DDP, and one that sends the client an event from server-side `onLogin/onLoginFailure`:

http://stackoverflow.com/a/35929513/627729

**Comment by GeorgeCalvert** [comment] 2016-04-29 17:00
First &mdash; not to conflate the two issues, but note this forum post re [onLogin firing on Firefox but not on Chrome](https://forums.meteor.com/t/accounts-onlogin-chrome-vs-firefox/21041). @joaobarcia, you're seeing something different, right?

Second &mdash; my own expectation is that `onLogin` should fire any time users initiate a log in, they deliberately (re)load the page (i.e. an F5 or button refresh, a return in the address bar or clicking a bookmark) **or** a hot codepush refreshes the page.  For me, the router should manage redirects and catch links so `onLogin` doesn't fire for navigation within the SPA.

I want it firing on reloads because it makes debugging far easier.  I expect it on hot pushes because I want a full refresh of the auth (including the user in Minimongo and any settings I might derive) if I change the code (though this would count as a login for @skifaster).   I don't need it fired when the socket is only lost and renegotiated as long as I'm guaranteed the user has not changed.

FWIW, if you've got a requirement to default to some route upon login, I'd suggest looking at the URL and only redirecting if the URL is the root.  Thus you'll enable deep linking/bookmarking.

**Comment by joaobarcia** [comment] 2016-04-29 17:12
Disclaimer: I haven't looked into the issue for 6 months, results might be different by now

> First — not to conflate the two issues, but note this forum post re onLogin firing on Firefox but not on Chrome. @joaobarcia, you're seeing something different, right?

I believe my issue was different. In my case:

- Client-side fired on hard login. Did NOT fire on page load/refresh. Only tested Firefox on Ubuntu
- Server-side fired as expected

 
> Second — my own expectation is that onLogin should fire any time users initiate a log in, they deliberately (re)load the page (i.e. an F5 or button refresh, a return in the address bar or clicking a bookmark) or a hot codepush refreshes the page. For me, the router should manage redirects and catch links so onLogin doesn't fire for navigation within the SPA.

Agree!

**Comment by ksorskiy** [comment] 2016-09-19 22:20
Guys! `onLogin` function takes 1 parameter: `user`. This is a complex object, and it has a `type` field. so when you just refresh the page (and already logged in), then `type` = `resume`. and when you have logged in by password, then `type` will be `password`. all you need is to write something like

```
Accounts.onLogin(function(user) {
	//console.log(user.user.log[user.user.log.length - 1]);
	if(user.type == 'password') {
		var loginRecord = {
			date: new Date(),
			body: 'Вход выполнен',
		};
		console.log(this.userId);
		// Meteor.users.update( { _id: user._id }, {
		// 	$push: {
		// 		log: loginRecord,
		// 	},
		// });
	}
});
```

Hope it will help.

**Comment by pricetula** [comment] 2016-12-22 07:53
The onLogin() method fires on page refresh
Accounts.onLogin(function(user) {
    console.log(user) //<------ The user argument passed is always undefined and not an object if on client side
});

**Comment by sunlee-newyork** [comment] 2017-05-29 02:44
Same as @pricetula, user param is undefined for me on page refresh.

**Comment by hwillson** [comment] 2018-01-02 13:29
Hi all - just reviewing this issue thread. It seems as though some people expect registered `Accounts.onLogin` hooks to fire whenever an authenticated user refreshes a page (which happens currently), whereas other people expect the registered hooks to only fire when a user actually logs in. This means we can't really change this to be one way or the other exclusively, without upsetting at least some people.

https://github.com/meteor/meteor/issues/5127#issuecomment-248145303 mentions the possibility of checking `user.type` to figure out if the hook is being called on a page refresh versus a true login. While this is possible on the server (since registered `Accounts.onLogin` hooks on the server receive a `user` parameter), it is not currently possible on the client side (`Accounts.onLogin` hooks don't receive a `user` param client side). Adjusting client side `Accounts.onLogin` hooks so that they get back `user.type` information (where `type` equals `password` for logins, and `type` equals `resume` for page reloads) is fairly straightforward, and would provide a flexible way to address the original issue here (and is backwards compatible).

Marking as `pull-requests-encouraged`. If anyone is interested in working on this, please chime in, otherwise I'll get a PR ready for this shortly.

**Comment by hwillson** [comment] 2018-01-03 18:42
PR #9512 should help with this.

**Closed** 2018-01-10 17:07 UTC
Labels: Impact:some, Project:Accounts (in user apps), Severity:production, confirmed, pull-requests-encouraged
