### ISSUE TITLE
[1.4] Production: Ubuntu: Module did not self-register

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#7512] opened 2016-07-28 12:54 UTC
Hey,
I'm trying to deploy a 1.4 app to my Ubuntu 16.04 machine. I've set the --architecture os.linux.x86_64 flag on MacOS. After deploying it via pm2-meteor, I get the following error logs:

```
app-0 Error: Module did not self-register.
app-0     at Error (native)
app-0     at Object.Module._extensions..node (module.js:434:18)
app-0     at Module.load (module.js:343:32)
app-0     at Module.Mp.load (/opt/pm2-meteor/app/app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
app-0     at Function.Module._load (module.js:300:12)
app-0     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
app-0     at Module.require (module.js:353:17)
app-0     at require (internal/module.js:12:17)
app-0     at bindings (/opt/pm2-meteor/app/app/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bindings/bindings.js:76:44)
app-0     at Object.<anonymous> (/opt/pm2-meteor/app/app/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
```

Node is on 4.4.7 and node-gyp is also installed.

**Comment by abernix** [comment] 2016-07-28 13:09
Are you running `npm install` inside the `bundle/programs/server` directory using Node 4.4.7?

If so, did you have `g++` and `build-essential` installed? (e.g. `sudo apt-get install build-essential g++`)  These are requirements for building Node NPM modules on Ubuntu.

**Comment by dnish** [comment] 2016-07-28 13:24
Yeah, I've installed node-gyp. It works if I remove the bcrypt folder and running npm install bcrypt manually, I'm just wondering why I have to call this? Just thought that adding <code>--architecture os.linux.x86_64</code> will solve such issues.

**Comment by abernix** [comment] 2016-07-28 13:34
To be honest, I'm not even entirely sure that `--architecture os.linux.x86_64` does anything or when that became 'a thing'.  (I mean, really, how would specifying architecture on Mac allow it to compile for Ubuntu?).  I think that was originally a flag for Meteor packages so when you used `meteor publish` to publish on Atmosphere, it could build (using Atmosphere's build farm).

So more questions...

* Are you doing any of this as `root`?  I think if you're `root`, you need to run `npm install --unsafe-perm` instead of just `npm install`.  (I don't recommend being root except for running the final `node main.js`)
* `g++ --version` output?
* `make --version` outout?
* `python --version` output?
* `npm install` output?

**Comment by dnish** [comment] 2016-07-28 13:43
G++:

```
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.1) 5.4.0 20160609
```

Make:

```
GNU Make 4.1
```

Python:
```
Python 2.7.12
```

Running npm-install --unsafe-perm:

```
root@1-server:/opt/pm2-meteor/app/app/bundle/programs/server# npm install --unsafe-perm
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
\
> bcrypt@0.8.7 install /opt/pm2-meteor/app/app/bundle/programs/server/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory '/opt/pm2-meteor/app/app/bundle/programs/server/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
make: Leaving directory '/opt/pm2-meteor/app/app/bundle/programs/server/node_modules/bcrypt/build'

> meteor-dev-bundle@0.0.0 install /opt/pm2-meteor/app/app/bundle/programs/server
> node npm-rebuild.js

bindings@1.2.1 /opt/pm2-meteor/app/app/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bindings
nan@2.3.5 /opt/pm2-meteor/app/app/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/nan
{
  "meteor-dev-bundle": "0.0.0",
  "npm": "2.15.8",
  "ares": "1.10.1-DEV",
  "http_parser": "2.5.2",
  "icu": "56.1",
  "modules": "46",
  "node": "4.4.7",
  "openssl": "1.0.2h",
  "uv": "1.8.0",
  "v8": "4.5.103.36",
  "zlib": "1.2.8"
}

``` 

I have another app which is running on a 1.4 RC2 and there I didn't have any of these problems. Don't know if something has changed in the final version or if the new server got some other configuration (both Ubuntu 16.04 - but different hosters).

**Comment by zeroasterisk** [comment] 2016-07-29 17:20
Also having these problems... working on a recreation...

**Comment by mitar** [comment] 2016-07-31 23:21
I think this might be a duplicate of (or related to) #7469. While solving issues with bcrypt on Mac OS X with Meteor 1.4 I have occasionally got this error instead of the bcrypt compilation error. It seems this is confirmed with the fact that `accounts-password` breaks it (which uses bcrypt).

**Comment by mitar** [comment] 2016-07-31 23:30
Hm, but doing:

```
meteor create test-bcrypt
cd test-bcrypt/
meteor add accounts-password
meteor
```

Worked for me without problems. So what is a difference? Why sometimes it does not work?

**Comment by dnish** [comment] 2016-07-31 23:33
Mh, in my case it only stops working on the production version (MacOS deploys to Ubuntu). On the development version (MacOS) everything works fine.

**Comment by abernix** [comment] 2016-08-01 13:50
@zeroasterisk I don't understand your reproduction – though I'm not familiar with `pm2`.  Your app (itself) runs fine for me on [my Docker image for mup](https://github.com/abernix/meteord/tree/abernix) with `accounts-password` included.  Based only on its name I am really doubtful that the `4.4.7-slim` build has the necessary compiler toolchain to build things properly so I'm not surprised you're having an issue unless you're developing/bundling/building the image on an actual Debian Jessie machine.

I get the feeling that someone needs to do for `pm2` what I did for `mup`.

**Comment by zeroasterisk** [comment] 2016-08-01 15:55
@abernix - for that example:

* I am building the app locally (on OSX) and then just trying to run in docker (node slim)
* I just want to use `pm2`eventually, once the "basics" are working w/ `node main.js`

I'll try again w/ your image on the latest `mup` - thanks for looking into it

**Comment by abernix** [comment] 2016-08-01 15:58
@zeroasterisk Mark has also made significant changes to the Docker image that it appears you are basing your project on: https://github.com/markoshust/docker-meteor so I would probably check that out.

**Comment by zeroasterisk** [comment] 2016-08-03 02:16
@mitar in reply to your post above, about why it seems to work... (and as @dnish said)

It works fine locally, development mode, MacOS node 4.4.7.

But I have been fighting with every build/deploy toolchain I can try, and none of them seem to deploy to a Ubuntu server or Docker image/container.  Almost all of the time/variations, the build process works (results in a bundle) but I can not get that bundle to run in the Ubuntu image/container.  I have a tried (excellent) suggestions for removing `npm-bcrypt` and rebuilding it, or just using `bcrypt

**Comment by mitar** [comment] 2016-08-03 03:20
I can tell you how I fixed things: I manually increased version of accounts-password to the latest version in `.meteor/versions` and then it worked. :-)

**Comment by zeroasterisk** [comment] 2016-08-03 03:22
I'm gonna be pissed (and super happy) if that works... I'll try it in a few

**Comment by abernix** [comment] 2016-08-05 07:56
@zeroasterisk Can you provide a basic reproduction Meteor app (as fresh and clean and lacking of third-party packages as possible) that does not work on my image when you try deploying it?  I will try it myself and dig into it.

**Comment by abernix** [comment] 2016-08-05 08:01
@zeroasterisk Sorry, I take that back, I looked at your repo already!  I will dig through it some more, maybe I missed something.

**Comment by abernix** [comment] 2016-11-01 13:41
I'm fairly sure this is resolved with the changes to `bcrypt` and `accounts-password` a few releases ago; I cannot reproduce it with the reproductions above.  Closing, but happy to discuss further.  Make sure that you're running the latest versions of [`accounts-password`](https://atmospherejs.com/meteor/accounts-password) and [`npm-bcrypt`](https://atmospherejs.com/meteor/npm-bcrypt) if you're still experiencing problems!

**Closed by abernix** 2016-11-01 13:41 UTC

**Comment by isapoetra** [comment] 2017-08-18 06:18
if someone still faced this issue, here is my script to solve problem when running meteor bundle

```
tar -xzf app.tar.gz
cd bundle/
(cd programs/server && rm -rf npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/ &&  npm i -s bcrypt && npm install)

MONGO_URL=mongodb://localhost:27017/db ROOT_URL=http://somedomain.com/ node main.js

```
