### ISSUE TITLE
Show loading screen when loading development app

### ISSUE THREAD

**Issue by maartenbusstra** [meteor/meteor#5749] opened 2015-12-04 05:50 UTC
It would be pretty cool to show the same(-ish) loading screen as on *.meteor.com when firing up a Meteor app in development:

![Meteor Loading](http://i.imgur.com/LuljTPN.png)

Thoughts?

**Comment by tmeasday** [comment] 2015-12-08 23:01
Hi @qtbox,

Interesting idea. What are you imagining here? If you hit the webserver before it's finished building the app that you see that screen until the build is ready and then it refreshes itself?

The problem is that it's non trivial to detect if the build is ready, especially given we wouldn't be able to ship DDP with the loading app. I think there's been some experimenting done in this direction already and it wasn't simple.

**Comment by qtbox** [comment] 2015-12-09 14:27
@tmeasday That's exactly what I meant. Due to DDP not being available pre-build, perhaps it's feasible using a long-polling technique?

It would definitely fit in with the premium look & feel of Meteor overall.

**Comment by hwillson** [comment] 2017-01-17 19:41
Thanks for the interesting suggestion, but given the number of higher priority outstanding issues, and the low interest/support in this issue (as well as the potential complexity), it's unlikely to be worked on anytime soon. Closing for now - thanks again!

**Closed by hwillson** 2017-01-17 19:41 UTC
Labels: feature, Project:Tool
