### ISSUE TITLE
Cordova boilerplate does not play well with external scripts

### ISSUE THREAD

**Issue by ramijarrar** [meteor/meteor#8876] opened 2017-07-05 07:32 UTC
The cordova template in the boilerplate-generator package currently loads any user-specified ``<head>`` **after** application JS code. This creates an incompatibility with external scripts that are expected on startup e.g for Stripe, Twilio, etc. 

Is there a reason why we cannot load them first, or even move the application JS to ``<body>`` (which has already been done for the browser template)?

**Comment by hwillson** [comment] 2017-07-12 14:18
This issue is very similar to https://github.com/meteor/meteor-feature-requests/issues/24 (and https://github.com/meteor/meteor/issues/8651), which discusses the same problem but with CSS load ordering. The `boilerplate-generator` recently went through a fairly significant refactoring (see https://github.com/meteor/meteor/pull/8820), and the issue of load ordering was brought up in that discussion. This is something that should be addressed in the future.

**Comment by hwillson** [comment] 2017-07-12 14:19
That being said, since this functionality is currently working as designed (not a bug), I'll move this issue over to the `meteor/meteor-feature-requests` repo. Thanks!

**Closed by hwillson** 2017-07-12 14:19 UTC
