### ISSUE TITLE
[1.4.0.1] Cannot import module from shell, unless already explicitly imported on server.

### ISSUE THREAD

**Issue by wallslide** [meteor/meteor#7629] opened 2016-08-11 02:57 UTC
Tried to do this in `meteor shell`:
`import {updateAuth0UserEmail} from './imports/api/accounts/authUserManagement';`

But got the error:

```
Error: Cannot find module './imports/api/accounts/authUserManagement'
at Function.require.resolve (packages/modules-runtime/.npm/package/node_modules/install/install.js:101:1)
at Module.resolve (packages/modules-runtime/.npm/package/node_modules/install/install.js:57:1)
at Module.Mp.import (/Users/.../.meteor/packages/modules/.0.7.5.17f9vh9++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:61:29)
at repl:1:-23
at /Users/.../Documents/github/..../.meteor/local/build/programs/server/shell-server.js:386:27
at /Users/.../.meteor/packages/meteor-tool/.1.4.0-1.fwrrwv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/meteor-promise/fiber_pool.js:32:39
```

Then I found this thread:
https://forums.meteor.com/t/meteor-shell-require-cannot-find-module-if-not-already-imported-somewhere-within-the-app/27745

After adding this entry to `/server/main.js`:
`import '../imports/api/accounts/authUserManagement';`
The import statement in `meteor shell` works. 

I expected the import statement to work from `meteor shell` without having to first import it in `main.js`.

**Comment by laosb** [comment] 2016-08-11 03:14
I guess that's because non-imported files won't be included in the server bundle. So `meteor shell` can't find it. It's intended, I think.

**Comment by benjamn** [comment] 2016-08-11 15:27
Yep, this is expected behavior. Not that it couldn't be improved, but the current recommendation is to explicitly import the module somewhere, e.g. `if (false) require("/path/to/module.js");` so it won't be evaluated unless you import it in the shell.

**Comment by abernix** [comment] 2016-11-25 22:05
Closing as duplicate of #6624.  The workaround above will work.

Thanks for reporting this originally, @wallslide.

**Closed by abernix** 2016-11-25 22:05 UTC
Labels: feature, Impact:few, Project:Isobuild, Severity:has-workaround
