### ISSUE TITLE
templating@1.1.9 throws error, promise_server.js:116

### ISSUE THREAD

**Issue by derekrliang** [meteor/meteor#6926] opened 2016-04-28 05:34 UTC
# Issue
I suspect an issue with native package **templating@1.1.9** as running downgraded meteor with `meteor --release 1.3.1` that has templating@1.1.8 seems to work just fine.

# Console Output of Error
```
/Users/derekliang/.meteor/packages/templating/.1.1.9.wfr8bc++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: UNKNOWN, readdir '/Users/derekliang/Documents/dev/apollday/node_modules/material-design-icons/image/ios/ic_slideshow_white_18pt.imageset'
```

# Package Versions (working at 1.3.1)
```
accounts-base          downgraded from 1.2.7 to 1.2.5
accounts-password      downgraded from 1.1.8 to 1.1.7
allow-deny             downgraded from 1.0.4 to 1.0.3
autoupdate             downgraded from 1.2.9 to 1.2.7
babel-compiler         downgraded from 6.6.4 to 6.6.1
babel-runtime          downgraded from 0.1.8 to 0.1.7
base64                 downgraded from 1.0.8 to 1.0.7
binary-heap            downgraded from 1.0.8 to 1.0.7
blaze                  downgraded from 2.1.7 to 2.1.6
blaze-tools            downgraded from 1.0.8 to 1.0.7
boilerplate-generator  downgraded from 1.0.8 to 1.0.7
caching-compiler       downgraded from 1.0.4 to 1.0.3
caching-html-compiler  downgraded from 1.0.6 to 1.0.5
callback-hook          downgraded from 1.0.8 to 1.0.7
check                  downgraded from 1.2.1 to 1.1.3
ddp                    downgraded from 1.2.5 to 1.2.4
ddp-client             downgraded from 1.2.7 to 1.2.4
ddp-common             downgraded from 1.2.5 to 1.2.4
ddp-rate-limiter       downgraded from 1.0.4 to 1.0.3
ddp-server             downgraded from 1.2.6 to 1.2.5
deps                   downgraded from 1.0.12 to 1.0.11
diff-sequence          downgraded from 1.0.5 to 1.0.4
ecmascript             downgraded from 0.4.3 to 0.4.2
ecmascript-runtime     downgraded from 0.2.10 to 0.2.9
ejson                  downgraded from 1.0.11 to 1.0.10
email                  downgraded from 1.0.12 to 1.0.11
es5-shim               downgraded from 4.5.10 to 4.5.9
fastclick              downgraded from 1.0.11 to 1.0.10
geojson-utils          downgraded from 1.0.8 to 1.0.7
hot-code-push          downgraded from 1.0.4 to 1.0.3
html-tools             downgraded from 1.0.9 to 1.0.8
htmljs                 downgraded from 1.0.9 to 1.0.8
http                   downgraded from 1.1.5 to 1.1.4
id-map                 downgraded from 1.0.7 to 1.0.6
jquery                 downgraded from 1.11.8 to 1.11.7
launch-screen          downgraded from 1.0.11 to 1.0.10
livedata               downgraded from 1.0.18 to 1.0.17
localstorage           downgraded from 1.0.9 to 1.0.8
logging                downgraded from 1.0.12 to 1.0.11
meteor                 downgraded from 1.1.14 to 1.1.13
meteor-base            downgraded from 1.0.4 to 1.0.3
minifier-css           downgraded from 1.1.11 to 1.1.10
minifier-js            downgraded from 1.1.11 to 1.1.10
minimongo              downgraded from 1.0.16 to 1.0.13
mobile-experience      downgraded from 1.0.4 to 1.0.3
mobile-status-bar      downgraded from 1.0.12 to 1.0.11
modules                downgraded from 0.6.1 to 0.5.2
modules-runtime        downgraded from 0.6.3 to 0.6.2
mongo                  downgraded from 1.1.7 to 1.1.6
mongo-id               downgraded from 1.0.4 to 1.0.3
npm-bcrypt             downgraded from 0.8.5 to 0.7.8_2
npm-mongo              downgraded from 1.4.43 to 1.4.42
observe-sequence       downgraded from 1.0.11 to 1.0.10
ordered-dict           downgraded from 1.0.7 to 1.0.6
promise                downgraded from 0.6.7 to 0.6.6
random                 downgraded from 1.0.9 to 1.0.8
rate-limit             downgraded from 1.0.4 to 1.0.3
reactive-dict          downgraded from 1.1.7 to 1.1.6
reactive-var           downgraded from 1.0.9 to 1.0.8
reload                 downgraded from 1.1.8 to 1.1.7
retry                  downgraded from 1.0.7 to 1.0.6
routepolicy            downgraded from 1.0.10 to 1.0.9
service-configuration  downgraded from 1.0.9 to 1.0.8
session                downgraded from 1.1.5 to 1.1.4
sha                    downgraded from 1.0.7 to 1.0.6
spacebars              downgraded from 1.0.11 to 1.0.10
spacebars-compiler     downgraded from 1.0.11 to 1.0.10
spiderable             downgraded from 1.0.13 to 1.0.12
srp                    downgraded from 1.0.8 to 1.0.7
standard-minifier-css  downgraded from 1.0.6 to 1.0.5
standard-minifier-js   downgraded from 1.0.6 to 1.0.5
templating             downgraded from 1.1.9 to 1.1.8
templating-tools       downgraded from 1.0.4 to 1.0.3
tracker                downgraded from 1.0.13 to 1.0.12
ui                     downgraded from 1.0.11 to 1.0.10
underscore             downgraded from 1.0.8 to 1.0.7
url                    downgraded from 1.0.9 to 1.0.8
webapp                 downgraded from 1.2.8 to 1.2.7
webapp-hashing         downgraded from 1.0.9 to 1.0.8
```

**Comment by abernix** [comment] 2016-04-28 07:17
@derekrliang Would you mind making a reproduction example repo or listing steps to reproduce on a fresh project?  There is nothing to work with here otherwise.

**Comment by zeroasterisk** [comment] 2016-04-28 18:36
I am having similar problems with coffeescript... I think these are errors being thrown by relied-upon npm modules, which are not being found, where expected during the lazy load process.

```
/Users/alan/.meteor/packages/coffeescript/.1.0.17.3hxzbr++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: UNKNOWN, open '/Users/alan/Code/eltoro/portal_v2/webapp/node_modules/dom-helpers/query/scrollLeft.js'

$ meteor --version; node -v; npm -v
Meteor 1.3.2.4
v4.2.1
3.8.5
```

ref: https://github.com/meteor/meteor/issues/6778 https://github.com/meteor/meteor/issues/6560

**Comment by zeroasterisk** [comment] 2016-04-28 19:36
FYI -  just cloned `meteor` and used branch `release-1.3.3` and after it rebuilt everything

```
git clone https://github.com/meteor/meteor.git
cd meteor
git checkout release-1.3.3
meteor
...
meteor: updating npm dependencies -- meteor-deque...
modules-runtime: updating npm dependencies -- install...
babel-compiler: updating npm dependencies -- meteor-babel...
promise: updating npm dependencies -- meteor-promise, promise...
ecmascript-runtime: updating npm dependencies --
meteor-ecmascript-runtime...
babel-runtime: updating npm dependencies -- regenerator,
meteor-babel-helpers...
ddp-client: updating npm dependencies -- faye-websocket, lolex,
permessage-deflate...
npm-mongo: updating npm dependencies -- mongodb...
logging: updating npm dependencies -- cli-color...
xmlbuilder: updating npm dependencies -- xmlbuilder...
=> Running Meteor from a checkout -- overrides project version


promise  upgraded from 0.6.7 to 0.7.1

...

Unable to resolve some modules:

  "formsy-react-components" in
/Users/alan/Code/eltoro/portal_v2/webapp/node_modules/react-form-simple-schema/dist/QuickInput.js
(web.browser)

  meteor npm install --save formsy-react-components

=> Started your app.

=> App running at: http://localhost:3000/

/Users/alan/Code/Meteor/meteor/.meteor/packages/fourseven_scss/.3.4.3.lbtzv++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: UNKNOWN, open '/Users/alan/Code/eltoro/portal_v2/webapp/node_modules/less/test/css/media.css'
```

Then is broke again, but this error message actually helped me find a problem.

I'm working on [a npm package](https://github.com/zeroasterisk/react-form-simple-schema) and it didn't actually include all it's dependencies in the `package.json` _(doh)_

----

I then updated my npm package, published, and updated it locally in the meteor repo, restarted meteor, and then it crashed again, in a different place:


```
/Users/alan/.meteor/packages/coffeescript/.1.0.17.3hxzbr++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: UNKNOWN, open '/Users/alan/Code/eltoro/portal_v2/webapp/node_modules/react-bootstrap/lib/utils/CustomPropTypes.js'
```

**Comment by zeroasterisk** [comment] 2016-04-29 03:03
Sorry to spam... one more update.

I deleted my `node_modules` and `.meteor` folders.  I created a new meteor `1.3.3` project, copied in the `.meteor` folder and ran `npm i` --- after a lot of crunching (and praying) it seems to have worked... no idea what was lost along the way.... but this recovered it for me.

**Comment by msatala** [comment] 2016-04-29 10:26
Here's a repo with an example of the bug: https://github.com/msatala/meteor-1.3.2-templating-bug

This gives you the error:
```
npm install
meteor
```

It starts to work if you remove run it with `meteor --release 1.3.1` or remove `static-html` (meteor package) or `mapbox.js` (node package).

**Comment by rhyslbw** [comment] 2016-05-04 02:32
@msatala Did you push all local changes? There's just a single commit containing only a .gitignore

**Comment by msatala** [comment] 2016-05-04 05:28
Oops, you're right I forgot. Pushing it now.

**Comment by laosb** [comment] 2016-05-14 08:44
When I go and test it out, I found it strange: I got an error, but not the same error you've got.
```
$ meteor --port=5000
[[[[[ ~/tests/meteor-1.3.2-templating-bug ]]]]]

=> Started proxy.
=> Started MongoDB.

/Users/laosb/.meteor/packages/static-html/.1.0.7.1ehm8qs++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
TypeError: Cannot call method 'split' of undefined
    at Object.parse (/tools/utils/parse-stack.js:18:28)
    at Object.exception (/tools/utils/buildmessage.js:497:29)
    at /tools/isobuild/compiler-plugin.js:189:26
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/compiler-plugin.js:176:22
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/compiler-plugin.js:175:15
    at Function._.each._.forEach (/Users/laosb/.meteor/packages/meteor-tool/.1.3.2_4.1dtkk3h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:165:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:901:22)
    at /tools/isobuild/bundler.js:681:34
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:675:18)
    at /tools/isobuild/bundler.js:2474:14
    at /tools/isobuild/bundler.js:2563:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/laosb/.meteor/packages/meteor-tool/.1.3.2_4.1dtkk3h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2562:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

**Comment by ko0stik** [comment] 2016-05-18 09:40
I'm not sure it's related but we bump into this error every time we try to launch more than 2 apps (micro-services architecture) locally. The latest to be launched will invariably 
```/foobar/.meteor/packages/templating/.1.1.9.19qp0cv++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: UNKNOWN, open '/bar/project/node_modules/stripe/lib/Error.js'```

With the open Error randomly picking an existing node_module each time we try to launch it.

**Comment by SachaG** [comment] 2016-05-20 01:46
@ko0stik just ran into this as well, quitting one of my apps did the trick, thanks. I'll also look into the link you shared.

**Comment by abernix** [comment] 2016-05-20 10:31
@SachaG @ko0stik Please see #7032 too and see if you identify with that problem at all!

**Comment by meatwallace** [comment] 2016-05-26 01:52
Not sure if it's the same issue, but I am encountering this error while trying to deploy a new release to Modulus.

```
/mnt/home/.meteor/packages/templating/.1.1.9.18yb8nj++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
TypeError: Object [object Object] has no method 'await'
    at Object.wrapper [as realpath] (/tools/fs/files.js:1359:32)
    at IsopackCache.getSourceRoot (/tools/isobuild/isopack-cache.js:137:22)
    at /tools/isobuild/compiler-plugin.js:130:30
    at Array.map (native)
    at Function._.map._.collect (/mnt/home/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:97:56)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:127:27)
    at ServerTarget._runCompilerPlugins (/tools/isobuild/bundler.js:901:22)
    at /tools/isobuild/bundler.js:681:34
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ServerTarget.make (/tools/isobuild/bundler.js:675:18)
    at /tools/isobuild/bundler.js:2502:14
    at /tools/isobuild/bundler.js:2570:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
    at buildCommand (/tools/cli/commands.js:909:30)
    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:789:12)
    at /tools/cli/main.js:1402:23
```

I cannot downgrade to 1.3.1, as it would seem that Meteor 1.3.2.4 is baked into their deployment, but I am going to reach out to them. Everything works fine locally.

**Comment by mbiczysko** [comment] 2016-06-06 14:20
I have similar error when trying to compile to ios, app is just to-do tutorial app it's failing on point 6.

meteor --version
Meteor 1.3.2.4

meteor list-platforms
browser
ios
server

meteor run ios                                                                                                                                                                                   130 ↵
[[[[[ ~/Projects/app ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
=> Errors executing Cordova commands:

   While running Cordova app for platform iOS with options --emulator:
   Error: Command failed: /Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/cordova/run --emulator
   ** BUILD FAILED **


   The following build commands failed:
   CompileSwift normal i386 /Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/app/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift
   CompileSwift normal i386 /Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/app/Plugins/cordova-plugin-meteor-webapp/WebAppConfiguration.swift
   CompileSwift normal i386 /Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/app/Plugins/cordova-plugin-meteor-webapp/AssetBundleManager.swift
   CompileSwift normal i386 /Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/app/Plugins/cordova-plugin-meteor-webapp/AssetBundle.swift
   CompileSwift normal i386 /Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/app/Plugins/cordova-plugin-meteor-webapp/Asset.swift
   CompileSwift normal i386 /Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/app/Plugins/cordova-plugin-meteor-webapp/AssetBundleDownloader.swift
   CompileSwift normal i386 /Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/app/Plugins/cordova-plugin-meteor-webapp/AssetManifest.swift
   CompileSwift normal i386 /Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/app/Plugins/cordova-plugin-meteor-webapp/Errors.swift
   CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
   (9 failures)
   Error code 65 for command: xcodebuild with args:
   -xcconfig,/Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/cordova/build-debug.xcconfig,-project,app.xcodeproj,ARCHS=i386,-target,app,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/user/Projects/app/.meteor/local/cordova-build/platforms/ios/build/sharedpch
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

/Users/user/.meteor/packages/meteor-tool/.1.3.2_4.8vlv67++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
ExitWithCode:1

**Comment by mariohmol** [comment] 2016-06-16 01:06
@laosb i'm having the same split error.. how did u solve it? Here is how to reproduce https://github.com/Urigo/meteor-angular-socially/issues/120

**Comment by laosb** [comment] 2016-06-16 05:13
Actually I didn't solve it. I will give your repro a test.

**Comment by laosb** [comment] 2016-06-16 05:16
Comments above said that it might be related to multiple running apps. In my test of the first repro, I was debugging two other apps so you see I'd given a `--port=5000` to the test. Will try whether it runs without any other apps running.

**Comment by mariohmol** [comment] 2016-06-16 11:02
tested here , i have no running meteor, the ports are free.. maybe is something related to the packages .. i will try to clean and run again

**Comment by sloops77** [comment] 2016-06-21 10:38
@ko0stik link suggests increasing your system's ulimit. That fixed it for me.
http://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks

**Comment by arshabhsarda** [comment] 2016-07-21 17:17
This error exists not just for templating@ package, and not just on Mac, and not just for 1.3.4.*.
I'm getting it for multiple packages, on Windows & with 1.3.2.4, 1.2.1, as well was 1.3.5.1 and 1.4.*
Tried using multiple node versions as well, and a clean install.
See https://forums.meteor.com/t/major-node-issue-unable-to-build-meteor-app-windows-promise-server-js-116/26798 too.

Would be really great if MDG could take a look at this, have not written a productive line of code in Meteor in over a week. Thanks.

**Comment by abernix** [comment] 2016-07-26 07:28
@msatala your reproduction is the most helpful thing in this issue however it's not actually related to the original issue at all.  If you need further advice on your issue, please include your reproduction in a new issue.  I can specifically say that _your_ problem is occurring because the `mapbox.js` NPM includes _all_ of it's documentation (literally thousands of `.html` files) inside the NPM module and Meteor is trying to process those files.  Granted there could be some argument here about whether Meteor _should_ be processing those HTML files, the bigger concern is why `mapbox.js` isn't including an `.npmignore` file or using `package.json`'s `files` directive to indicate the important parts of the NPM package instead of copying thousands of `docs` from its previous versions into the builds of anyone using the NPM.  

@arshs I responded to your forum post

I'm going to close this issue because it's too vague and (at a glance) I see 4+ completely different errors within this issue.  

I understand it's hard to be certain what's going on but to hopefully clear up the ambiguity between these errors: (some copy-paste/paraphrasing from the forum post I made): Errors from `promise_server.js` are almost always errors elsewhere in your project in some asynchronous code.  Most of the errors above are happening because of third-party packages or NPMs.  They are simply caught at that particular point and this is what returns as the error. The more relevant information is the rest of the error below.

Reproductions are also very important.  Making a reproduction doesn't need to be difficult just because you have a large project with a lot of code. Simply start deleting large amounts of code, disabling various entry points (starting in Meteor 1.3, try commenting out various `import`'s), and removing third-party packages until you see the problem going away. Then, try transplanting your findings into a new project with the same version using `meteor create foobar --release 1.2.1`.  Once you've reproduced it.  Share it on GitHub and post a link to it in your issue.

Generally speaking, you'll find the problem during this process and if not, someone else will be able to help (and it will be easy for them).

**Closed by abernix** 2016-07-26 07:28 UTC
Labels: bug, Impact:few, Severity:blocks-development

**Comment by ChenLi0830** [comment] 2017-01-20 21:08
I think this problem might be memory related. I literally solved my problem by closing some memory hogs (iOS simulator and some other projects). Below is the error message I had

```
/Users/Chen/.meteor/packages/coffeescript/.1.0.17.xacr0v++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: UNKNOWN, open '/Users/Chen/Developer/Repository/Octokey/node_modules/meteor-node-stubs/node_modules/buffer/index.js'

```
