### ISSUE TITLE
Meteor legacy browser detection is detecting modern browsers as "legacy".

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#11670] opened 2021-10-04 06:59 UTC
Related to https://github.com/meteor/meteor/issues/11668, Meteor's browser detection is detecting a modern browser like Firefox Mobile 94 to be "legacy". I had to use the [`--exclude-archs web.browser.legacy`](https://github.com/meteor/docs/issues/721) to work around it.

It seems the browser detection needs some TLC.

**Comment by StorytellerCZ** [comment] 2021-10-04 07:59
This seems to be an issue effecting only Firefox Mobile. Closing as duplicate of #11668.

**Closed by StorytellerCZ** 2021-10-04 07:59 UTC
