### ISSUE TITLE
Meteor 2.6.1, which isn't available on this platform (OSX)

### ISSUE THREAD

**Issue by pmogollons** [meteor/meteor#11941] opened 2022-02-21 16:52 UTC
Project wont start on 2.6.1 and return the following message in the cli console.

This project uses Meteor 2.6.1, which isn't available on this platform. To work with this app on all supported platforms, use meteor update --release METEOR@2.6 to pin this app to the newest compatible release.

macOS monterry 12.1 on intel cpu.

This same project runs ok on ubuntu.

**Comment by renanccastro** [comment] 2022-02-21 18:47
Hello, I can't reproduce in a Monterey Mac OS.

Can you please give it another try?

I will close this issue for now, but if it still doesn't work please let me know here and we will reopen it!

Thanks

**Closed by renanccastro** 2022-02-21 18:47 UTC
