### ISSUE TITLE
Should we make meteor possible for io.js users?

### ISSUE THREAD

**Issue by laosb** [meteor/meteor#3700] opened 2015-02-10 14:26 UTC
It seems we didn't move to io.js. Did we have a plan of io.js? Shall we use io.js instead of Node.js?

**Comment by jagi** [comment] 2015-02-10 17:54
This question was already asked but left without any interest from Meteor team. I think moving to io.js would be good thing. Some not so small projects have already moved.

**Comment by jagi** [comment] 2015-02-10 17:56
#3479

**Closed** 2015-02-10 18:11 UTC

**Comment by glasser** [comment] 2015-02-10 18:13
Duplicate of #3479.  As described there, we're definitely interested in hearing from users about whether or not Meteor works for them with io.js, and we will consider all options the next time we upgrade Node major versions for which platform to test against and ship with.  We do tend to prioritize stability over bleeding-edginess, though.
