### ISSUE TITLE
ES6 module live bindings not working as expected (with circular dependencies)?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#7621] opened 2016-08-10 06:19 UTC
I have a circular dependency issue, and I'm not sure if I'm not understanding how ES6 live bindings work, or if there's an issue in the way it is implemented in Meteor. The problem I'm having is described (with examples) here: https://esdiscuss.org/topic/how-to-solve-this-basic-es6-module-circular-dependency-problem

Specifically, you can grab the code for the [last example](https://esdiscuss.org/topic/how-to-solve-this-basic-es6-module-circular-dependency-problem#content-8) (the Meteor app will have four files total), and the last output in the console will be

```
Entrypoint undefined
```

which shows that the value of what I thought was a "live binding" is `undefined` although it was assigned a value inside of the `setUpA` function which was called inside module C.

**Comment by trusktr** [comment] 2016-08-10 06:32
I guess this isn't Meteor-specific, as I get the exact same results with Webpack. @benjamn Do you know why this is? Maybe you can shed some light on how the modules work?

**Comment by trusktr** [comment] 2016-08-10 07:09
I found where Meteor and Webpack diverge in behavior. If we run the following entrypoint in Meteor and Webpack,

```js
import C from './C'
import A from './A'
console.log('Entrypoint', new C, new A)
```

then it fails in Meteor with `_A2.default is not a constructor`, *but it works in Webpack*.

However, if we swap the two import statements,

```js
import A from './A'
import C from './C'
console.log('Entrypoint', new C, new A)
```

then it fails with `_A2.default is not a constructor` in *both* Meteor and Webpack (both are using Babel).

**Comment by benjamn** [comment] 2016-08-10 16:30
Can you turn this into a reproduction repo that I can easily clone?

**Comment by trusktr** [comment] 2016-08-10 18:50
@benjamn Sure, here it is: https://github.com/trusktr/meteor/tree/issue-7621

To run it,

```sh
git clone git@github.com:trusktr/meteor.git
cd meteor
git checkout issue-7621
./run-dev.sh
```

`run-dev.sh` installs NPM stuff, then runs Meteor on http://localhost:7654.

You'll see that the default export of the `A` module is `undefined`.

**Comment by trusktr** [comment] 2016-08-10 18:56
If my understanding of "live bindings" is correct, then I think that `A` should be a reference to the class constructor defined in module A by the time the entrypoint main.js is evaluated.

**Comment by benjamn** [comment] 2016-08-10 20:25
Believe it or not, `A` in the `/client/A.js` module is assigned an undefined value *after* your `setUpA` function is called, so live bindings are working as expected here.

The problem is that Babel compiles [this `let A` declaration](https://github.com/trusktr/meteor/blob/11e98b0f833b4144fa4b251d7130b991c26c487d/meteor-app/client/A.js#L5) to `var A = void 0`, and reify picks up that new value of the local variable `A` when it hits [the `import A from "./A"` declaration in `main.js`](https://github.com/trusktr/meteor/blob/11e98b0f833b4144fa4b251d7130b991c26c487d/meteor-app/client/main.js#L23).

Because `import` and `export` declarations are hoisted along with function declarations (like `setUpA`), the statements `var A = void 0` and `console.log('Module A', C, setUpA)` in `A.js` are actually among the last code that runs in your app, after code in `B.js` and `C.js`, but before code in `main.js`.

This works in plain Babel/Webpack just because `var A = void 0` doesn't modify `exports.default`, which is sort of like selectively disabling a live binding. Meteor/reify respect the values of your actual local variables, so `var A = void 0` requires an update to any live bindings associated with `A`. In other words, `var A = void 0` is an invalid transpilation (`var A` alone would be fine) if your module system truly supports live bindings. Babel only supports live bindings for properties of the `exports` object, which is why you can kind of get away with it, if you assume Babel is implementing your module system.

Try putting a `debugger` keyword before [this `let A` declaration](https://github.com/trusktr/meteor/blob/11e98b0f833b4144fa4b251d7130b991c26c487d/meteor-app/client/A.js#L5):
```js
debugger;
let A;
```
and also in the `setUpA` function. Then turn off JS source maps in your browser, and see which happens first.

**Comment by benjamn** [comment] 2016-08-10 20:30
As for a workaround, you can change `let A` to `let A = A` to prevent Babel-generated code from reassigning `var A = void 0`. Just be aware that you're working around a Babel quirk, not a problem in Meteor or reify.

**Comment by trusktr** [comment] 2016-08-10 22:54
@benjamn Thanks for the explanation! I'm confused: Module C executes before module A, so how can module C successfully call `setUpA` if module A has not been evaluated yet and considering that `setUpA` is defined inside of the scope of the module?

This code extends from my original problem in which a base class needs to reference two child classes (something to avoid in general, but nonetheless something that can happen), and each class is defined in separate modules:

```js
// --- Entrypoint
import A from './A'
console.log('Entrypoint', new A)
```

```js
// --- Module A
import C from './C'
class A extends C {}
export {A as default}
```

```js
// --- Module B
import C from './C'
class B extends C {}
export {B as default}
```

```js
// --- Module C
import A from './A'
import B from './B'

class C {
    constructor() {
        // this may run later, after all three modules are evaluated, or
        // possibly never.
        console.log(A)
        console.log(B)
    }
}

export {C as default}
```

Any suggestions on how to make that work? My `setUpA` and `setUpB` functions were one solution idea, but that doesn't work in Meteor or Webpack without your workaround, and fails in `rollup.js` due to a hoisting problem. I wonder if there's a generic solution for this in general that should theoretically work in an ES6 environment regardless of implementation?

**Comment by benjamn** [comment] 2016-08-10 23:17
> Module C executes before module A, so how can module C successfully call `setUpA` if module A has not been evaluated yet and considering that `setUpA` is defined inside of the scope of the module?

That's because `setUpA` is a function declaration, visible before any code in module A has been evaluated.

**Comment by trusktr** [comment] 2016-08-10 23:18
@benjamn True, but what I mean is, how is it visible to module C (where it is called) before module A has been evaluated?

**Comment by benjamn** [comment] 2016-08-11 00:08
Fundamentally, you need module C to define and export class `C` before module B uses `C` to define the class `B`. But since module C imports module B before it defines class `C`, that's just not possible.

Imagine if `C` inherited from `B` the same way that `B` inherits from `C`—that would obviously be an unbreakable cycle, but the module system doesn't know the difference between these two scenarios, so that kind of logic cannot inform the module evaluation order. So it's up to module B to know that it may not be able to use class `C` immediately.

One way to accomplish that is to export a function from module B that creates the `B` class on demand, e.g.
```js
import C from "./C";
export function getB() {
  return class B extends C {};
}
```
That way, as long as module C defines class `C` before calling `getB()`, everything will work out fine.

**Comment by trusktr** [comment] 2016-08-11 00:17
Exactly, which is why I made the `setUpB` function, but instead of returning the class from the function, I am simply modifying the *live binding* inside of `setUpB` so that the end user doesn't have to actually call the `setUpB` function, they only have to `import B from 'B'` at which point B should be defined.

Aside from that, I still don't understand how in that reproduction the C module can call `setUpA` despite the fact that the A module evaluates *after* the C module.

Do you also know of some solution (other than making it the responsibility of the end user to call an initialization function) that may work in any ES2015 module environment?

I'm still thinking about it, and want to find a solution.

In my case, the public API is only A and B classes, and the end user should never import C. They will only ever `import A from 'A'` or `import B from 'B'`. In either case, I'd like the A and B classes to be importable. This is working with your workaround for some strange reason despite the fact that module C is evaluated before module A (somehow `setUpA` is visible to module C before module A evaluation).

**Comment by benjamn** [comment] 2016-08-11 00:20
Well, in Meteor, thanks to reify, you can push the `import A from "./A"` and `import B from "./B"` declarations inside the `constructor` method of class `C`, which effectively allows module C to define its class before importing anything.

**Comment by benjamn** [comment] 2016-08-11 00:29
> I still don't understand how in that reproduction the C module can call `setUpA` despite the fact that the A module evaluates *after* the C module.

The difference between `setUpA` and `class C` is that `setUpA` is a function declaration, visible from the very beginning of the module, and `class C` is a class declaration, which is not hoisted like a function declaration, and therefore does not have an exportable value until execution reaches the declaration.

If you could move the `class C` declaration before `import B from "./B"`, that might solve the problem, but currently `import` declarations are hoisted to the beginning of the module, so you can't put any normal statements before them.

However, if you're using reify, you have a bit more control over the ordering of `import` declarations relative to other statements, e.g.
```js
import A from './A';
let B;

class C {
  constructor() {
    console.log(A);
    console.log(B);
  }
}

{ // Since this import is enclosed in a block, it happens after class C is declared.
  import _B from "./B";
  B = _B;
}

export {
  C as default
}
```

**Comment by trusktr** [comment] 2016-08-11 07:40
As much as I'd *absolutely love* to use deferred imports, I've decided not to merely because I'm not sure that that will become standard (even though I really really like the idea).

I believe I have found a theoretical solution that should work in any ES2015 module environment (except that in the case of Babel it will require your aforementioned `let X = X` workaround, and [fails in Rollup](https://github.com/rollup/rollup/issues/845#issuecomment-239088432) because there's no live binding):

```js
// --- Entrypoint
import A from './A'
console.log('Entrypoint', new A)
```

```js
// --- Module A

import C from './C'
import {setUpB} from './B'

let A

export
function setUpA(C) {

    if (!A) {
        A = class A extends C {
            // ...
        }
    }

}

if (setUpA && C) setUpA(C)
if (setUpB && C) setUpB(C)

export {A as default}
```

```js
// --- Module B

import C from './C'
import {setUpA} from './A'

let B

export
function setUpB(C) {

    if (!B) {
        B = class B extends C {
            // ...
        }
    }

}

if (setUpA && C) setUpA(C)
if (setUpB && C) setUpB(C)

export {B as default}
```

```js
// --- Module C

import A, {setUpA} from './A'
import B, {setUpB} from './B'

class C {
    constructor() {
        // this may run later, after all three modules are evaluated, or
        // possibly never.
        console.log(A)
        console.log(B)
    }
}

if (setUpA && C) setUpA(C)
if (setUpB && C) setUpB(C)

export {C as default}
```

In theory, the `C` parameter to the setup functions should not even be needed because they should be live bindings (right?). So, the following code should work (with your workaround applied), but it simply fails because `C` is undefined inside of `setUpA` or `setUpB`:

```js
// --- Entrypoint
import A from './A'
console.log('Entrypoint', new A)
```

```js
// --- Module A

import C from './C'
import {setUpB} from './B'

let A

export
function setUpA() {

    if (!A) {
        A = class A extends C { // C should be available via live binding
            // ...
        }
    }

}

if (setUpA && C) setUpA()
if (setUpB && C) setUpB()

export {A as default}
```

```js
// --- Module B

import C from './C'
import {setUpA} from './A'

let B

export
function setUpB() {

    if (!B) {
        B = class B extends C { // C should be available via live binding
            // ...
        }
    }

}

if (setUpA && C) setUpA()
if (setUpB && C) setUpB()

export {B as default}
```

```js
// --- Module C

import A, {setUpA} from './A'
import B, {setUpB} from './B'

class C {
    constructor() {
        // this may run later, after all three modules are evaluated, or
        // possibly never.
        console.log(A)
        console.log(B)
    }
}

if (setUpA && C) setUpA()
if (setUpB && C) setUpB()

export {C as default}
```

**Comment by trusktr** [comment] 2016-08-12 00:56
I absolutely `<3` the concept of deferred imports, because that makes it very easy to specify which modules are evaluated first, and is a perfect solution to the problem.

I'm trying it out in Meteor, but I can't get it to work (repro). Meteor is using reify, so it should work right?

**Comment by trusktr** [comment] 2016-08-12 00:57
^ Added repro link

**Closed** 2016-08-14 22:19 UTC

**Comment by msand** [comment] 2017-05-28 11:56
How about applying Inversion of Control by implementing Dependency Injection using Constructor injection? Just make your C constructor take two parameters A and B like this:
```
// --- Module A

import C from './C';

export default class A extends C {
    // ...
}

// --- Module B

import C from './C'

export default class B extends C {
    // ...
}

// --- Module C

export default class C {
    constructor(A, B) {
        // this may run later, after all three modules are evaluated, or
        // possibly never.
        console.log(A)
        console.log(B)
    }
}

// --- Entrypoint

import A from './A';
import B from './B';
import C from './C';
const c = new C(A, B);
console.log('Entrypoint', C, c);
document.getElementById('out').textContent = 'Entrypoint ' + C + ' ' + c;
```
https://www.webpackbin.com/bins/-KlDeP9Rb60MehsCMa8u

**Comment by mitar** [comment] 2018-05-01 09:05
Yea, circular imports are tricky. Are some best practices documented anywhere?

https://forums.meteor.com/t/circular-imports/43473
