### ISSUE TITLE
Meteor.loginWithPassword does't respond under ipv6 root_url.

### ISSUE THREAD

**Issue by Eagles2F** [meteor/meteor#8192] opened 2016-12-25 14:40 UTC
Hi,
I've been working with angular-meteor and meteor backend for my cross-platform mobile project.
The IOS app store rejected my submission due to well-known ipv6-only network issue.

I have successfully reproduced the bug on my mac. Here is what I have done:
1. set up a NAT64/DNS64 local network following this [guide](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16)from apple.
2. start up a meteor server with this cmd: `ROOT_URL="http://2001:2::aab1:e:c6ff:feac:2264:3000" meteor run`
3. changed my angular-meteor DDP connection URL using this cmd: `window.__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL = 'http://2001:2::aab1:e:c6ff:feac:2264:3000';`
4. run my angular-meteor project using ionic cmd `ionic serve`

After the last 4 steps, I could successfully open my site. The websocket connection seems ok to me. no error log showed up. However, when I came to my login page. The code gets stuck here: `Meteor.loginWithPassword(username, password, Angular.bind(this, function(err) {
        if (err) {
          console.log('Login error - ', err);
          failure(err);
        } else {
          console.log('Login success');
          o.setSession(username, password);
          success();
        }
      }));`

This Meteor.loginWithPassword method never replied.

I'm wondering someone who knows this accounts package or meteor could help me.
My end goal is to make this login work under ipv6.

**Comment by mjmasn** [comment] 2016-12-26 16:26
Not sure if relevant but IPv6 urls generally look like `http://[2001:2::aab1:e:c6ff:feac:2264]:3000` (notice the square brackets around the IP address)

**Comment by abernix** [comment] 2016-12-27 11:35
@mjmasn is correct.  [Per RFC 2732](https://www.ietf.org/rfc/rfc2732.txt), literal IPv6 addresses in URLs must be enclosed in square brackets.  This is not unique to Meteor.

If you find that you still have problems after formatting your IPv6 URL correctly, someone will happily reopen this.

Also, I would not expect that you need to "change your angular-meteor DDP connection URL" to be the same as the `ROOT_URL` in the way that you are.  `DDP_DEFAULT_CONNECTION_URL` should be the same as `ROOT_URL` by default, so I'm not sure where you got the suggestion to do that.

Lastly, you should not be using `meteor run` for your production deployment or for the server that your mobile app is connecting to.  Please see [`meteor build`](https://docs.meteor.com/commandline.html#meteorbuild) in the Meteor docs and [the deployment section](https://guide.meteor.com/deployment.html#custom-deployment) of the Meteor Guide for the correct method to deploy your project.

**Comment by Eagles2F** [comment] 2016-12-28 06:11
@mjmasn 
Before posting this, I've tried using this URL: `http://[2001:2::aab1:e:c6ff:feac:2264]:3000` in the first place. The result is even worse, my angular-meteor-DDP client can not even connect to the server. 
@abernix I have to change DDP_DEFAULT_CONNECTION_URL because my client doesn't know which URL to connect to. And this client is not on the same host as my server.

One more note: my client is not built from meteor CLI.  it's from ionic CLI

**Comment by hwillson** [comment] 2017-03-06 18:44
Since there haven't been any additional complaints about this not working with Meteor, and a reproduction demonstrating this issue hasn't been provided, I'll close this for now. Happy to re-open if anyone can provide a repro showing this problem. Thanks!

**Closed by hwillson** 2017-03-06 18:44 UTC
Labels: can't-reproduce, Project:Accounts:Password
