### ISSUE TITLE
View returned from renderWithData not the template you tried to render

### ISSUE THREAD

**Issue by davidworkman9** [meteor/meteor#2573] opened 2014-09-11 18:44 UTC
When you use `Blaze.render(template, element);` you get back a view that you can call `.templateInstance()` on. With `Blaze.renderWithData(template, data, element);` you get a view with a name of `with` and no way to get the template instance you intended on building.

**Comment by Sanjo** [comment] 2015-05-12 02:09
This behavior also confused me a bit. `view._domrange.members[0].view.templateInstance()` worked for me as a workaround.

**Comment by hwillson** [comment] 2016-11-22 12:37
Since this functions as designed and there is a known workaround (see https://github.com/meteor/meteor/issues/2573#issuecomment-57387063), I'll close this off. Thanks!

**Closed by hwillson** 2016-11-22 12:37 UTC
Labels: Project:Blaze
