### ISSUE TITLE
allow users to delete their packages from atmosphere

### ISSUE THREAD

**Issue by bevanhunt** [meteor/meteor#4687] opened 2015-07-05 21:48 UTC
please allow users to delete their own packages from atmosphere.

**Comment by zardak** [comment] 2015-07-06 19:08
https://atmospherejs.com/i/faq

> ### How do I delete a package?
> You can’t delete a package (what if someone else is using it?!), but you can mark it “unmigrated”. This will prevent it from appearing in Atmosphere’s search results:
> `meteor admin set-unmigrated [packagename]`

**Comment by glasser** [comment] 2015-07-07 20:42
Duplicate of #2459.

**Closed by glasser** 2015-07-07 20:42 UTC
Labels: Project:Package Server
