### ISSUE TITLE
Error in Mongo query in polling observer blocks other queries

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2534] opened 2014-09-07 08:11 UTC
OK, because of a bug in [MongoDB](https://jira.mongodb.org/browse/SERVER-15164) my query was failing. This would not be a problem if that query would not more or less made other parts of the site inoperable.

See [this repository](https://github.com/mitar/meteor-pollbug). Run it with `meteor` and open `http://127.0.0.1:3000/`. You should start getting every 10 seconds something like the following in the console:

```
I20140907-01:00:39.069(-7)? Exception in queued task: MongoError: positional operator element mismatch
I20140907-01:00:39.069(-7)?     at Object.Future.wait (~/.meteor/packages/meteor-tool/.1.0.28.y8a796++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:326:15)
I20140907-01:00:39.070(-7)?     at _.extend._nextObject (packages/mongo/mongo_driver.js:858)
I20140907-01:00:39.070(-7)?     at _.extend.forEach (packages/mongo/mongo_driver.js:892)
I20140907-01:00:39.070(-7)?     at _.extend.getRawObjects (packages/mongo/mongo_driver.js:941)
I20140907-01:00:39.070(-7)?     at _.extend._pollMongo (packages/mongo/polling_observe_driver.js:144)
I20140907-01:00:39.071(-7)?     at Object.task (packages/mongo/polling_observe_driver.js:85)
I20140907-01:00:39.071(-7)?     at _.extend._run (packages/meteor/fiber_helpers.js:145)
I20140907-01:00:39.071(-7)?     at packages/meteor/fiber_helpers.js:123
I20140907-01:00:39.071(-7)?     - - - - -
I20140907-01:00:39.071(-7)?     at Object.toError (~/.meteor/packages/mongo/.1.0.4.cdngnx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:110:11)
I20140907-01:00:39.072(-7)?     at ~/.meteor/packages/mongo/.1.0.4.cdngnx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:686:54
I20140907-01:00:39.072(-7)?     at Cursor.close (~/.meteor/packages/mongo/.1.0.4.cdngnx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:969:5)
I20140907-01:00:39.072(-7)?     at commandHandler (~/.meteor/packages/mongo/.1.0.4.cdngnx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:686:21)
I20140907-01:00:39.072(-7)?     at ~/.meteor/packages/mongo/.1.0.4.cdngnx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1843:9
I20140907-01:00:39.072(-7)?     at Server.Base._callHandler (~/.meteor/packages/mongo/.1.0.4.cdngnx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
I20140907-01:00:39.073(-7)?     at ~/.meteor/packages/mongo/.1.0.4.cdngnx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
I20140907-01:00:39.073(-7)?     at MongoReply.parseBody (~/.meteor/packages/mongo/.1.0.4.cdngnx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I20140907-01:00:39.073(-7)?     at null.<anonymous> (~/.meteor/packages/mongo/.1.0.4.cdngnx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
I20140907-01:00:39.073(-7)?     at emit (events.js:95:17)
```

OK. There is a bug in my query (it would be really very very helpful if Meteor would output which query is failing, because otherwise it is really hard to debug, I had to [patch Meteor for that](https://github.com/peerlibrary/meteor/commit/daaefd81893804474b85b24244ab7b45b54ff46b)), but this should not block the rest of the site to work. For example, if you run now (while those errors are shown in the console) in the browser:

```
Meteor.subscribe('all', function () { console.log(Test.find().fetch()) } );
```

You will notice this subscription never returns any data. Even if by itself does not use any problematic query.

I have disabled oplog because for the queries where I was getting this problem on production Meteor was using polling as well (maybe because I am using old version of Meteor, pre Blaze).

**Comment by glasser** [comment] 2015-02-07 03:20
https://github.com/tmeasday/meteor-1633 is another reproduction, brought over from #1633.

**Comment by glasser** [comment] 2015-02-07 08:11
OK, so there are three related issues here:

(1) The root cause of any problem here: we can't tell the difference between a temporary connection error which we should retry, and a bad query error from Mongo which we should give up on.  This leads to observes that never get initial query completed, which is what causes the other problems.  We should figure out how to analyze Mongo's errors better to tell the different.

(2) Why does this affect the current DDP connection?  Well, if the observeChanges call that hangs is inside a publish function, or implicitly in the `_publishCursor` call invoked on a cursor returned by the publish function, then the DDP server will never finish processing the current message and will never move on to the next message.  So the connection is basically dead.  I think that we should probably defer the whole execution of the publish function (and `_publishCursor`).  This will also give the performance advantage that multiple subscriptions made at the same time can be processed in parallel.  We will have be careful to ensure that it's OK that if you call subscribe and then a method call, the write fence of the method call may not know about all observes related to the subscription yet, since the publish function may not have run (fully)!

(3) Why does this affect future DDP connections?  Specifically, it affects the `updated` message of methods on all DDP connections (ie, the write fence).  The idea behind the write fence is to create a connection between observes that are part of a subscription on a DDP connection and methods that run on that connection.  But it's not implemented that directly.  It actually connects ALL observes to ALL methods.  So, eg, if there's a broken observe on a collection (say, `Meteor.users`), and another method writes to that collection (as `login` does), then its write fence will include that broken observe, and thus never fire.  This is what is happening in @tmeasday 's reproduction.

To fix this, we could do something where observes have an EnvironmentVariable that is the current subscription (or really, current DDP connection) and WriteFences also know their connection and we only connect WriteFences to observes for the same connection?  It's a little tricky due to de-duping though.

**Comment by glasser** [comment] 2015-02-09 20:23
As far as fixing the root cause, I am told by the Node Mongo maintainer that we can differentiate between command errors and network errors (in Mongo 2.6 and up) by looking on the error object for a numeric `code`.

Some of the internal APIs around the ObserveMultiplexer and ObserveDrivers need to be reworked to properly get those errors back to the original `observeChanges` call(s).

**Comment by glasser** [comment] 2015-02-26 19:51
With the fix we just merged, Mitar's reproduction sends a 500 Meteor.Error over the wire and prints this, which contains the name of the sub and its bad selector and the error message:

```
I20150226-11:44:48.403(-8)? Exception from sub broken id uZPpvd3eSpdk7th55 Error: Exception while polling query {"collectionName":"Test","selector":{"importing.foo":"b"},"options":{"transform":null,"fields":{"jobs":{"$slice":-1},"importing.$":1}}}: Runner error: BadValue positional operator element mismatch
I20150226-11:44:48.403(-8)?     at Object.Future.wait (/Users/glasser/Projects/Meteor/meteor/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20150226-11:44:48.403(-8)?     at [object Object]._.extend.addHandleAndSendInitialAdds (packages/mongo/observe_multiplex.js:55:1)
I20150226-11:44:48.403(-8)?     at [object Object].MongoConnection._observeChanges (packages/mongo/mongo_driver.js:1166:1)
I20150226-11:44:48.403(-8)?     at [object Object].Cursor.observeChanges (packages/mongo/mongo_driver.js:841:1)
I20150226-11:44:48.403(-8)?     at Function.Mongo.Collection._publishCursor (packages/mongo/collection.js:302:1)
I20150226-11:44:48.403(-8)?     at [object Object].Cursor._publishCursor (packages/mongo/mongo_driver.js:822:1)
I20150226-11:44:48.404(-8)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:986:1)
I20150226-11:44:48.404(-8)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150226-11:44:48.404(-8)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150226-11:44:48.404(-8)?     at packages/ddp/livedata_server.js:546:1
I20150226-11:44:48.404(-8)?     - - - - -
I20150226-11:44:48.404(-8)?     at [object Object]._.extend._pollMongo (packages/mongo/polling_observe_driver.js:156:1)
I20150226-11:44:48.404(-8)?     at Object.task (packages/mongo/polling_observe_driver.js:85:1)
I20150226-11:44:48.404(-8)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20150226-11:44:48.404(-8)?     at packages/meteor/fiber_helpers.js:125:1
```

The subsequent subscription works fine.

Similarly, Tom's reproduction prints one error instead of an infinite number, and the subsequent login works.

Thanks for the great reproductions!

**Closed by glasser** 2015-02-26 19:51 UTC
Labels: Project:Livequery
