### ISSUE TITLE
Can't check all arguments on publications when using default values

### ISSUE THREAD

**Issue by lnmunhoz** [meteor/meteor#6937] opened 2016-04-29 00:19 UTC
I want to create a parameterized publication that has some default values on arguments when they are not passed. But the problem is that `check` can't check the anonymous object that has in my arguments.

```js
Meteor.publishComposite('technologies.single', function(technologyId, {
  organizations = false,
  projects = false,
  attachments = false
}) {
  check(technologyId, String);
  check(organizations, Boolean);
  check(projects, Boolean);
  check(attachments, Boolean);
...
```

When I subscribe to this publication, I got this on console:
```
Error: Did not check() all arguments during publisher 'technologies.single'
```

I think the anonymous object can't be verified by `check`, causing this problem. I could explicitly declare `options = { organizations = false, projects=false, attachments=false }`  and `check(options, Object)` but then I will loose the default values when some of the parameters are not passed...

It is possible to have some solution for this?

**Comment by ecwyne** [comment] 2016-04-29 03:08
This should probably be an issue [here](https://github.com/englue/meteor-publish-composite), but you may also be able to do the following

```javascript
  check(arguments[1], Object)
```

**Comment by stubailo** [comment] 2016-05-05 06:04
This is because of object destructuring, duplicate of: https://github.com/meteor/meteor/issues/5826

**Closed by stubailo** 2016-05-05 06:04 UTC
