### ISSUE TITLE
[Feature Request] Ignore npm package warnings

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#8675] opened 2017-05-07 23:02 UTC
It would be really nice if we could have a way to suppress these warnings:

```
Unable to resolve some modules:

  "pg" in
/Volumes/SuperData/Sites/reelcrafter/node_modules/raven/lib/breadcrumbs.js
(web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save pg
```

I think it's useful to get them once, in case we made a mistake, but Meteor is overly paranoid and anytime it sees a `require` (even if it's conditional) for something not in `node_modules`, it throws this warning.

It would be nice if we could have a file like `.meteorignore` where we could add a list of modules to ignore.

**Comment by hwillson** [comment] 2017-05-08 17:15
Closing as a duplicate of #7020 - thanks!

**Closed by hwillson** 2017-05-08 17:15 UTC
