### ISSUE TITLE
android-device + keycode_converter error

### ISSUE THREAD

**Issue by loevda** [meteor/meteor#6158] opened 2016-02-04 20:51 UTC
Hi,

I have the following error when running the app on Android when trying to login:
W/chromium(32413): [WARNING:keycode_converter.cc(100)] empty code string

Nothing happened. Anyone knows about it?

Thanks

**Comment by timbotnik** [comment] 2016-02-09 23:02
It's not clear from your description what the issue is.  Perhaps you can clarify what you mean by "nothing happened"?

**Comment by loevda** [comment] 2016-02-09 23:14
Hi,
 thanks for the help.

When I launch the mobile app and I get the login screen and if I try to type username or password notthing happened. Inside the console log I have the error mentioned above each time I try to type something. The webapp is working just fine. Any idea?
Thanks

**Comment by timbotnik** [comment] 2016-02-10 00:25
Do you mean that the characters don't appear in the form text box?  Are you using the `accounts-ui` package?

**Comment by loevda** [comment] 2016-02-10 08:13
Hi,

exactly. Nothing appears in the text box while typing and I have the error. I have accounts-ui installed but the login form is a custom template (no account-ui widget). The authentication is done calling Meteor.loginWithPassword.
Thanks

**Comment by henkverschoor** [comment] 2016-02-11 12:30
Hello, I have the same problem, but I don't know how I can solve it. I made a form with only an input field and a submit button.
If I typed anything in it, i got a few (2 or 3) warnings: 
`[chromium] [WARNING:keycode_converter.cc(100)] empty code string`

This is the HTML code: 

```
<p>What do you want to reminder?</p>
	<form>
		<input type="text" name="reminderBox" id="reminderBox" />
		<button type="submit" onclick="submitReminder()">Save</button>
	</form>

```
And this is the JS File:
```
$('#contactForm').submit(function()
{
	submitReminder();
	return false;
});

function submitReminder()
{
	//Create a new array
	var reminderItems = new Array();

	//If there is an array
	if (localStorage["reminderItems"] != null)
	{
		reminderItems = JSON.parse(localStorage["reminderItems"]);
	}

	var reminderItem = document.getElementById("reminderBox").value;
	reminderItems.push(reminderItem);

	localStorage["reminderItems"] = JSON.stringify(reminderItems);

	console.log(JSON.parse(localStorage["reminderItems"]));
}
``

**Comment by loevda** [comment] 2016-02-11 20:59
Hi,

I can't find anything related to this error. For now he all mobile thing is kind of stuck on this.

**Comment by martijnwalraven** [comment] 2016-02-19 11:43
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.

**Closed by martijnwalraven** 2016-02-19 11:43 UTC
Labels: Project:Mobile

**Comment by loevda** [comment] 2016-02-19 15:17
Hi,

yes I have still the issue. I'll try 1.3 during the weekend and post the result. Thanks

**Comment by loevda** [comment] 2016-02-21 22:09
Hi,

I have tried 1.3-modules-beta.7 but I run into a series of error with Iron router and messageformat.
Thanks

**Comment by martijnwalraven** [comment] 2016-02-22 02:51
`1.3-modules-beta.7` is an older beta that does not contain the mobile improvements. Could you try `1.3-beta.11`?

**Comment by loevda** [comment] 2016-02-22 13:53
Hi,

I confirm that the issue is no longer present in 1.3-beta.11!. Thanks a lot.
