### ISSUE TITLE
Error: While loading package fourseven:scss@3.4.3

### ISSUE THREAD

**Issue by SamuelEarl** [meteor/meteor#7440] opened 2016-07-20 03:23 UTC
I am trying to install `zurb:foundation-sites` in my project and I keep getting the following error message. I was able to install `fourseven:scss` and then `zurb:foundation-sites`, but then the Meteor development server wouldn't start--it would get stuck on `=> Building for web.browser` (I think that was where it would get stuck). So I uninstalled `fourseven:scss` and `zurb:foundations-sites` and now the dev server will startup again, but I don't have Zurb Foundation in my project.

I just upgraded my OS from Ubuntu 14.04 to Ubuntu 16.04 and now I am seeing this error, but I didn't see it before.

Any help would be greatly appreciated.

Thank you!

```
 => Errors while adding packages:             
                                              
While loading package fourseven:scss@3.4.3:
error: Command failed: 
module.js:340
throw err;
^
Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(/home/sam/.meteor/packages/fourseven_scss/.3.4.3.1ej5a6r++os.linux.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-109jgrk/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "node"
"/home/sam/.meteor/packages/meteor-tool/.1.3.5_1.1sksnpz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v0.10.46
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install
--fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/sam/.meteor/packages/fourseven_scss/.3.4.3.1ej5a6r++os.linux.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-109jgrk/npm-debug.log

module.js:340
throw err;
^
Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(/home/sam/.meteor/packages/fourseven_scss/.3.4.3.1ej5a6r++os.linux.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-109jgrk/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "node"
"/home/sam/.meteor/packages/meteor-tool/.1.3.5_1.1sksnpz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v0.10.46
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install
--fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/sam/.meteor/packages/fourseven_scss/.3.4.3.1ej5a6r++os.linux.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-109jgrk/npm-debug.log
```

**Comment by Ben305** [comment] 2016-07-20 05:17
Update fourseven:scss to 3.8.0_1

**Comment by abernix** [comment] 2016-07-20 07:10
I believe what @Ben305 is suggesting is most likely to help.  Alternatively, please upload a basic reproduction Meteor app to a GitHub repo and share the link so others could take a look.   This alone isn't enough to analyze the problem.

**Comment by Ben305** [comment] 2016-07-20 07:17
I ran into the same problem yesterday, and an update to 3.8.0_1 resolved this.

**Comment by abernix** [comment] 2016-07-20 16:00
Duplicate of #7437 which has the recommended work around for this (updating `fourseven:scss` to 3.8.0_1 first).

**Closed by abernix** 2016-07-20 16:00 UTC
Labels: bug, can't-reproduce

**Comment by SamuelEarl** [comment] 2016-07-20 22:35
I tried that, but I still got errors. I will search around for the problem that I am facing and open a new issue with more details if I can't resolve my problem.

Thank you for your help! You guys are great!

**Comment by Furqankhanzada** [comment] 2016-07-21 14:24
+1

**Comment by Furqankhanzada** [comment] 2016-07-21 15:02
@abernix thanks this working for me.

**Comment by c9s** [comment] 2016-07-22 00:34
Reproduced in #7453  :|

**Comment by indiedotkim** [comment] 2016-07-26 14:32
Updating `fourseven:scss` directly did not work for me due to some other package dependencies.

Workaround instead:

    meteor remove fourseven:scss
    meteor update
    meteor add fourseven:scss

The last step automatically picked the latest version of `fourseven:scss` (3.8.0_1).
