### ISSUE TITLE
Some NPM packages is missing after build

### ISSUE THREAD

**Issue by dr-dimitru** [meteor/meteor#8454] opened 2017-03-04 12:01 UTC
Possible related to #7674

My case:
 - Building on Mac (10.12.3), Meteor 1.4.3.1, with command `npm install --production && meteor build ../ --architecture os.linux.x86_64`
 - Running on Debian GNU/Linux 8, node v4.7.3, npm v2.15.11
 - Spawning process under `nodeapp` user
 - Deploy script has `cd ./bundle/programs/server && npm install --production` and `chown -R nodeapp:nodeapp /var/www/nodeapp`

Errors: 
```
programs/server/npm/node_modules/bson-ext/build/Release/bson.node: invalid ELF header

Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

meteor npm install --save bcrypt

in the root directory of your application.
```

bcrypt is definitely installed, here is `cat package.json`:
```json
{
  "name": "meteor-dev-bundle",
  "version": "0.0.0",
  "dependencies": {
    "bcrypt": "^1.0.2",
    "bson": "^1.0.4",
    "bson-ext": "^1.0.5",
    "fibers": "1.0.15",
    "meteor-promise": "0.8.0",
    "node-gyp": "3.4.0",
    "node-pre-gyp": "0.6.29",
    "promise": "7.1.1",
    "semver": "4.1.0",
    "source-map-support": "https://github.com/meteor/node-source-map-support/tarball/1912478769d76e5df4c365e147f25896aee6375e",
    "underscore": "1.5.2"
  },
  "devDependencies": {
    "eachline": "https://github.com/meteor/node-eachline/tarball/ff89722ff94e6b6a08652bf5f44c8fffea8a21da",
    "chalk": "0.5.1"
  },
  "scripts": {
    "install": "node npm-rebuild.js"
  }
}
```

I've solved it by running:
```shell
# Globally install node-gyp
npm install -g node-gyp
```
```shell
# Inside programs/server
npm install --save bcrypt bson bson-ext
cp -R node_modules/* npm/node_modules/

# Make sure we have right ownership
chown -R nodeapp:nodeapp /var/www/nodeapp
```

Of course we can add copy/paste command into deploy script, but this issue wasn't exist on earlier releases of Meteor 1.4.*

**Comment by abernix** [comment] 2017-03-08 15:30
Hmm, interesting.

Your usage of `/var/www/nodeapp` here isn't super clear, but I'm not sure that's relevant, but if anything, it seems you should be executing all of the tasks as the `nodeapp` user instead of as root instead of running as root and trying to fix it with `chown` later.

Regardless, the presence of `node-gyp` and `node-pre-gyp` in the `package.json` should be sufficient to not necessitate the global (`-g`) installation, and those packages (`bcrypt` included) are installed before the `node npm-rebuild.js` script is executed.  You can check yourself by peaking into the `npm/node_modules` after running `npm install`.

Npm version v2.15.11 is quite old at this point and Meteor natively uses v4.  Can you try upgrading your npm installation with `npm install -g npm@4` before you do the `npm install --production`?

All in all, it would be a lot easier to narrow down what the issue might be if you could find the specific version when this stopped working as there are ~15 releases earlier in the 1.4.* series and a lot of commits to consider. 🙂

**Comment by dr-dimitru** [comment] 2017-03-08 16:18
@abernix thank you for stepping in,

> Your usage of `/var/www/nodeapp` here isn't super clear, but I'm not sure that's relevant, but if anything, it seems you should be executing all of the tasks as the `nodeapp` user instead of as root instead of running as root and trying to fix it with `chown` later.

Well, `su -s /bin/bash -c 'npm install --production' nodeapp` gives exact same results. I've found using `chown` later gives me more control.

> Regardless, the presence of node-gyp and node-pre-gyp in the package.json should be sufficient to not necessitate the global (-g) installation, and those packages (bcrypt included) are installed before the node npm-rebuild.js script is executed. You can check yourself by peaking into the npm/node_modules after running npm install.

Right, globally installing `node-gyp` suggestion was found somewhere on SO, and actually did the trick.

I'm really confused by existence of `programs/server/npm/node_modules`, while running `npm install --production` inside `programs/server` will install modules into `programs/server/node_modules`.
Could you please explain why `programs/server/npm/node_modules` exists aside to `programs/server/node_modules`, and why Meteor looking for modules inside `programs/server/npm/node_modules` ?

> Npm version v2.15.11 is quite old at this point and Meteor natively uses v4. Can you try upgrading your npm installation with npm install -g npm@4 before you do the npm install --production?

Upgraded to `npm@4.3.0`, ended with same warnings:

```
[Error: /var/www/nodeapp/programs/server/npm/node_modules/bson-ext/build/Release/bson.node: invalid ELF header]
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

meteor npm install --save bcrypt

in the root directory of your application.
```

> All in all, it would be a lot easier to narrow down what the issue might be if you could find the specific version when this stopped working as there are ~15 releases earlier in the 1.4.* series and a lot of commits to consider. 🙂

Sure, previous version is exactly `1.4.2.7`

**Comment by abernix** [comment] 2017-03-15 12:14
Unfortunately, after quite a while playing around with it, I was not able to recreate the issue so I'm going to have to ask for an easier reproduction in order to assist further – possibly a Vagrant box or `docker-compose` configuration that can be easily cloned and ran.  You may also want to consider running the `npm` commands with `--verbose` (or with the environment variable `V=1` set) in order to provide more insight into the problem.

I used Meteor 1.4.3.2 (just released) and a fresh install of Debian Jessie to do the following (briefly summarized):

On macOS Sierra:
* `meteor create app && cd app`
* `meteor add accounts-password npm-bcrypt` (to create binary dependencies)
* `meteor npm install --save bcrypt`
* `meteor build ../build-dir`
* `scp ../build-dir/*.tar.gz debian@debian-box`

On new Debian Jessie Box:
* `apt-get install build-essential g++` (Make sure I have a compiler toolchain)
* I installed [`nvm`](https://github.com/creationix/nvm) to install Node.js easily.
* `nvm install 4`
* `npm install --global npm@latest`
* `tar -xzf bundle.tar.gz`
* `cd bundle/programs/server`
* `npm install --production`
* `cd ../.. ; MONGO_URL=... ROOT_URL=http://127.0.0.1:3000 PORT=3000 node main.js`

It worked properly.  Are you getting any errors when running `npm install --production` on the Debian box?

**Comment by hwillson** [comment] 2017-04-05 13:15
Hi @dr-dimitru - it's been a few weeks, any luck? I'll close this issue for now (since we can't reproduce this issue and we're aggressively trying to reduce the number of open issues), but please post back if you've uncovered any additional details that might help. Thanks for posting this originally!

**Closed by hwillson** 2017-04-05 13:15 UTC
Labels: can't-reproduce

**Comment by dr-dimitru** [comment] 2017-04-05 14:22
Hello @hwillson ,

My bad, forgot to respond. Thank you for following up.
Well, ended up what latest release (`1.4.3.2`) has no such problem on exact same environment, while originally issue was about `1.4.3.1`.

My guess is update of `node-gyp` and `pre-node-gyp` and `npm` itself is reason for it.

And as always many thanks to @abernix for quick responses.

**Comment by crapthings** [comment] 2017-07-05 06:20
i have the same issue~
