### ISSUE TITLE
`meteor self-test` should be more reliable

### ISSUE THREAD

**Issue by rbabayoff** [meteor/meteor#3569] opened 2015-01-27 22:54 UTC
Hello,

In your https://github.com/meteor/meteor/wiki/Contributing-to-Meteor document, you state that all code should have tests. We know how to test meteor packages, but there are no guidelines on how to test the meteor command line tool. What script(s) should be run and how?

**Comment by glasser** [comment] 2015-01-28 01:22
The answer is: There's something built in to the tool called `self-test`, but at the moment many of the tests are so flaky and slow that I don't feel comfortable telling people that they should run it and then try to evaluate which of the failures are real and which of the failures are flakiness.  (I mean, all you have to do is run `meteor self-test`, no arguments, nice and simple. But then you have to analyze the output.)  The flakiness is caused by dependencies on production services such as Meteor Developer Accounts and the package server (either the real service or a single deployed testing version).

There's a concept inside it where tests can have various tags, such as 'slow', and by default slow tests don't run (you pass `--slow` to make them run).  I had intended as part of my work on tool maintainability to spend some time auditing the existing tests and slapping `slow` on any test that didn't pass consistently in say 100 consecutive executions.  (Never mind if it's even "fast" or not.)  If somebody sent me a PR that did this, I'd take it in a heartbeat.  (It would be easy to test: I'd just merge the PR, start running a shell script that runs `self-test` 100 times, go to sleep, and confirm in the morning that it passed.)

In the medium term we have plans to make running the tool tests less flaky by building off of some other infrastructure we are building as part of Galaxy.

**Comment by hwillson** [comment] 2015-02-27 20:52
Hi @glasser - I've submitted pull request #3831 to help with this. I've marked several tests as "slow" to allow meteor self-test to complete consistently. Note - the tests run by default are still quite slow, but at least they all pass and complete properly. Here's a quick shell script I threw together to help verify things are working:
```
#!/bin/bash                                                                    
                                                                               
for i in `seq 1 100`;                                                           
do                                                                             
  start=`date +%s`                                                             
  echo "\"meteor self-test\" pass $i started"                                  
  fail_count=$(./meteor self-test 2>&1 | grep 'fail' | wc -w)                  
  stop=`date +%s`                                                              
  duration=$(($stop-$start))                                                   
  echo "\"meteor self-test\" pass $i finished (took $(($duration/ 60)) minutes $(($duration % 60)) seconds)"
  if [ $fail_count -ne 0 ]                                                     
  then                                                                         
    break                                                                      
  fi                                                                           
done                                                                           
                                                                               
echo \"meteor self-test\" completed $i pass(es), fail count: $fail_count 
```

Just a heads up - one full pass in my environment takes about 16 minutes so if you're planning on running this while you sleep, plan for about 26 hours of sleep :-). Thanks!

**Comment by hwillson** [comment] 2015-03-04 16:12
Hi @glasser - I was just in the process of preparing a new pull request for this (against the latest code in devel), but I've run into a couple interesting issues:

1) "cordova-platforms: add cordova platforms" always fails in my environment.

```
cordova-platforms: add cordova platforms ...  
  ... fail!                                   
  => exit-timeout at tools/tests/cordova-platforms.js:28
  => Last 100 lines:                          
  1| Installing Android bundle   
```
In tools/tests/cordova-platforms.js, If I bump 

```
run = s.run("install-sdk", "android");
run.waitSecs(90); // Big downloads
run.expectExit(0);
```

up to 

```
run.waitSecs(120); // Big downloads
```

it passes consistently. Do you think we should bump the wait time up then mark this test as "slow", to accommodate for different download speeds?

2) "hot-code-push: javascript hot code push" always fails in my environment.
  
```
hot-code-push: javascript hot code push ...   
running test with 1 client(s).               /
testing with phantomjs...
  ... fail!                                   
  => match-timeout at tools/tests/hot-code-push.js:193
...
```  

The reason for this failure looks like a match statement that isn't matched in the order outlined in the test. If I comment out line 188 of tools/tests/hot-code-push.js, the test passes normally:

```
// Fix it. It should notice, and restart. The client will restart too.
s.write("hot-code-push-test.html", "");
// run.match("server restarted");
run.match("client connected: 0");
```

I'm wondering if anybody else sees this same behavior?

Thanks!

**Comment by glasser** [comment] 2015-03-28 05:58
Yeah, we've definitely seen hot-code-push as flaky.  Haven't had time to look into it though.

**Comment by praveend** [comment] 2015-05-25 12:09
Hi @hwillson @glasser 

Could you provide some pointers on how to run the tests specific to mongo package? I see files like collection_test.js, doc_fetcher_test.js etc but not sure how to run them.

Thanks

Praveen

**Comment by praveend** [comment] 2015-05-25 16:09
Hi @hwillson  @glasser 

This stackoverflow thread http://stackoverflow.com/questions/10760601/how-do-you-run-the-meteor-tests helped me get the command meteor test-packages mongo

However I have hit on another blocker "Unexpected mongo exit code 1. Restarting." and then ends with a message "Cant' start Mongo server"

any guidance on how to overcome this?

I am running this command from the checkout directory on meteor.

Thanks

Praveen

**Comment by hwillson** [comment] 2017-02-21 15:02
There has been a lot of work on the tests run as part of the `meteor self-test` process over the past while, so the `self-test`'s should now complete without failures. Issues do still come up from time to time, but the process has been more or less stable for some time. When issues do come up they are addressed individually, so there isn't really a need for this issue to stay open.

With regards to finding more information outlining the meteor tool and meteor core library testing process, some of this is outlined in the [Running tests on Meteor core](https://github.com/meteor/meteor/blob/devel/Contributing.md#running-tests-on-meteor-core) section of the [Contributing.md](https://github.com/meteor/meteor/blob/devel/Contributing.md) doc. This doc can definitely be improved upon however, which is what PR #8267 is intended to help address (by creating a new one-stop shop "developing Meteor" `Development.md` guide - contributions welcome!).

Given the above, I'll close this issue off. Thanks for reporting this originally!

**Closed by hwillson** 2017-02-21 15:02 UTC
Labels: bug, Project:Tool, pull-requests-encouraged
