### ISSUE TITLE
[1.3.3] import from absolute paths no longer work

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#7225] opened 2016-06-15 14:53 UTC
Most mantra-applications have this import statement (because the cli generates it like this):

 `import * as Collections from '/lib/collections';`

which no longer work with meteor 1.3.3. Changing the import path to use a relative path resolves the issue:

`import * as Collections from '../../lib/collections';

I am not sure if this is intended or not.

**Comment by benjamn** [comment] 2016-06-15 17:00
Can you put together a small reproduction?

**Comment by v3rron** [comment] 2016-06-16 01:51
same here... also using Mantra

**Comment by laosb** [comment] 2016-06-16 05:34
I find it works, but actually it doesn't work with ESLint by default.

**Comment by macrozone** [comment] 2016-06-16 08:56
Actually, this was never a real absolute path. It got resolved to the app's root folder, not to the file-system-root. So it was sort of ambiguous.

Meteor provides `{}` like in `import {Products} from '{}/lib/collections/` for these app-relative-absolute-paths. But i am not sure if this is supported by webpack or the like.

**Comment by StephenBoyd** [comment] 2016-06-17 11:05
I'm having the same problem. In my source code, I am referencing imported files with a path that's relative from the project's root like 
`import Whatever from '/appRoot/client/modules/someModule/containers/whatever.js';`

Which worked perfectly fine until I installed 1.3.3.

Now I'm getting error messages like

```
Unable to resolve some modules:

  "/home/username/appRoot/client/modules/someModule/containers/whatever.js"
in /home/username/appRoot/client/modules/core/someOtherModule/another_component.jsx
```

The paths shown in the error messages are definitely the correct paths to the files. The problem goes away when I replace
`import Whatever from '/appRoot/client/modules/someModule/containers/whatever.js';`
in another_component.jsx with
`import Whatever from '../../someModule/containers/whatever.js';`

But I would have to do this change for each of the many locally imported modules in my app. And I find most relative-to-the-current-file paths harder to work with and remember than those that are relative to the app root.

**Comment by benjamn** [comment] 2016-06-17 16:45
@StephenBoyd I believe you want `/client/modules/someModule/containers/whatever.js` instead of `/appRoot/client/modules/someModule/containers/whatever.js`.

**Comment by benjamn** [comment] 2016-06-17 16:51
I still need a reproduction for this if you want to see it fixed in 1.3.3.1, as it works just fine for me.

**Comment by StephenBoyd** [comment] 2016-06-17 17:58
@benjamn That was a mistake in my hand-typed anonymization of closed-source code. The original paths started with `/client...`

**Comment by Szauren** [comment] 2016-06-18 14:28
> I still need a reproduction for this if you want to see it fixed in 1.3.3.1, as it works just fine for me.

Can you try this demo app https://github.com/mantrajs/meteor-mantra-kickstarter/issues/51 ?
So absolute paths that are resolved to root project are still supported or should we always use only relative ones ?

**Comment by martinhbramwell** [comment] 2016-06-18 15:00
@Szauren 

From a modularity point of view I believe we should favor absolute over relative.  That way, refactoring that moves files up/down the directory hierarchy can be done without endlessly fiddling with import statements.

**Comment by martinhbramwell** [comment] 2016-06-18 16:20
@benjamn   The Meteor Mantra Kickstarter mentioned by @Szauren does not work at all with 1.3.3 or 1.3.3.1, for exactly the reason @macrozone describes.

If I change all my imports to relative, the missing import CLI messages cease and my app starts, (although I hit a different error).  Changing any one of them to absolute brings back the error message.

**Comment by croogie** [comment] 2016-06-20 16:00
@benjamn Try generate new mantra app using `mantra-cli` npm tool (`npm install -g mantra-cli` and then `mantra c test-project`). Having described issue every time.

**Comment by benjamn** [comment] 2016-06-20 21:04
I was able to get absolute imports working in a Mantra app by removing the `babel-root-slash-import` plugin from [this `.babelrc` file](https://github.com/mantrajs/meteor-mantra-kickstarter/blob/50584c44c8912af58047fa4a47c80c9bcb8405cb/.babelrc#L3). Although I am not intimately familiar with why that plugin was introduced, the relevant change in Meteor 1.3.3 is that [we started paying attention to `.babelrc` files](https://github.com/meteor/meteor/issues/6351), whereas previously they were ignored.

This appears to be a problem specific to the misbehavior of the `babel-root-slash-import` plugin, which means it's probably best fixed by Mantra (by removing the plugin).

**Closed by benjamn** 2016-06-20 21:04 UTC
Labels: can't-reproduce

**Comment by tarun-batra** [comment] 2016-06-21 06:49
@benjamn yes, the issue doesn't occur when the `babel-root-slash-import` plugin is removed.
But without this plugin things like npm test fail.

**Comment by tarunbatra** [comment] 2016-06-21 06:55
@benjamn yes, the issue doesn't occur when the `babel-root-slash-import` plugin is removed.
But without this plugin things like `npm test` fail which are out of meteor environment and need this plugin by Mantra

**Comment by gsabran** [comment] 2016-06-23 00:35
As another datapoint (see https://forums.meteor.com/t/babelrc-not-working-properly/25347) this also happens with [babel-root-import](https://github.com/michaelzoidl/babel-root-import) that mantra's `babel-root-slash-import` is forked from. This looks like a fairly stable package, and it works perfectly when imports are resolved with [webpack:webpack](https://github.com/webpack/webpack) for instance.
So it sounds like there might be something wrong with how Meteor works with those babel plugins that hopefully doesn't affect many other.
Sure you can resolve that with removing those packages, or not using `.babelrc` at all, but that's not the answer we're looking for :)

**Comment by gsabran** [comment] 2016-06-23 01:30
Here is a small reproduction: https://github.com/gsabran/meteor-import-bug-repro

**Comment by arunoda** [comment] 2016-06-23 01:52
@gsabran is correct. Mantra's fork simply support '/lib/import/file` directly when used root imports outside of Meteor.

Yeah, anyway it seems like Meteor implementation of babelrc, doesn't support this feature.

**Comment by arunoda** [comment] 2016-06-23 03:43
Guys, I just introduce a new version of [`babel-root-slash-import`](https://github.com/mantrajs/babel-root-slash-import/blob/master/CHANGELOG.md#v110) which works properly inside Meteor.

Here's a sample app using it: https://github.com/mantrajs/mantra-sample-blog-app

**Comment by tarun-batra** [comment] 2016-06-23 04:54
@arunoda kudos for this fix and saving many apps in production from crashing. I still hope that Meteor's implementation of babel will support it and we don't have to do these workarounds.

**Comment by tarun-batra** [comment] 2016-06-23 04:57
@arunoda kudos for this fix and saving many apps in production from crashing. I still hope that Meteor's implementation of babel will support it and we don't have to do these workarounds.

**Comment by tarunbatra** [comment] 2016-06-23 04:57
@arunoda kudos for this fix and saving many apps in production from crashing. I still hope that Meteor's implementation of babel will support it and we don't have to do these workarounds.

**Comment by benjamn** [comment] 2016-06-23 13:48
@gsabran @tarunbatra Do you understand what this plugin was doing? It would replace `import "/absolute/path/etc"` with a full file system path, e.g. `import "/Users/name/projects/absolute/path/etc"`. Now, unless the file system where you deploy your app looks exactly like your local file system, this rewritten `import` will fail, and your app will be broken when you deploy it.

Absolute module identifiers in Meteor are relative to the root of your application directory so that your code will be **portable**, and will work exactly the same way in production as in development.

**Comment by gsabran** [comment] 2016-06-23 16:20
I think the plugin is run at build time on the deployment machine, so it's not using the local file structure and there's no conflict. And Meteor's build system probably works similarly.

In my case, which is probably slightly different than for most of the people in this thread, I was using it with webpack (without mantra). It seems that webpack only handles relative paths by default, so this plugin is needed to specify the root of the app. The plugin readme reads:
```
Babel plugin to add the opportunity to use import with root based paths.
```
This is the default behavior of Meteor's build so it sounds like two programs do the same thing and we end up with a path like `absolute-path-to-meteor-project/absolute-path-to-meteor-project/path-to-file-relative-to-meteor-project`

As a bonus with those plugins, if all your code is under `./src/` for instance, you can specify it in the `.babelrc` config and get rid of the extra `src` in your code.

I've had no issue of portability while using this plugin with webpack's build for deployment on a server with a different file structure.

Removing the plugin is a problem for running tests, using another build system for production etc. It seems that @arunoda 's fix is a mixed approach that disables the plugin when Meteor interferes, and else keeps the normal behavior.

Another more `.babelrc` compliant could be to include this plugin as part of Meteor's build, instead of using Meteor's own approach that duplicates the work. But that'd now break the latest version of babel-root-slash-import...

**Comment by benjamn** [comment] 2016-06-23 16:27
> I think the plugin is run at build time on the deployment machine

Unless you're running `meteor run` in production (a very bad idea compared to [`meteor build` etc.](https://guide.meteor.com/deployment.html#custom-deployment)), your assumption here is simply not true.

**Comment by gsabran** [comment] 2016-06-23 16:32
Hum anyway it's been working just fine when deploying with mupx. And my local looks nothing like my production server.
