### ISSUE TITLE
[1.4-beta.13] bcrypt fails to run on Windows 64

### ISSUE THREAD

**Issue by omasopust** [meteor/meteor#7408] opened 2016-07-14 16:35 UTC
Platform:
Windows 10 Pro x64
MS build tools installed

Reproduction steps:
```
meteor create test14 --release 1.4-beta.13
meteor add accounts-password
meteor run
```
Error during app starting: 
```
C:\Users\Ondra\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.13\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\
future.js:280
W20160714-18:26:19.872(2)? (STDERR)                                             throw(ex);
W20160714-18:26:19.873(2)? (STDERR)                                             ^
W20160714-18:26:19.874(2)? (STDERR) 
W20160714-18:26:19.874(2)? (STDERR) Error: %1 is not a valid Win32 application.
W20160714-18:26:19.875(2)? (STDERR) 
W20160714-18:26:19.876(2)? (STDERR) \\?\C:\Users\Ondra\AppData\Local\.meteor\packages\npm-bcrypt\0.8.6_2\npm\node_modules\bcrypt\build\Release\bcrypt_lib.node
W20160714-18:26:19.878(2)? (STDERR)     at Error (native)
W20160714-18:26:19.879(2)? (STDERR)     at Object.Module._extensions..node (module.js:434:18)
W20160714-18:26:19.880(2)? (STDERR)     at Module.load (module.js:343:32)
W20160714-18:26:19.881(2)? (STDERR)     at Module.Mp.load (C:\Users\Ondra\AppData\Local\.meteor\packages\babel-compiler\6.9.0-beta.13\npm\node_modules\reify\node\runtime.j
s:16:23)
W20160714-18:26:19.882(2)? (STDERR)     at Function.Module._load (module.js:300:12)
W20160714-18:26:19.884(2)? (STDERR)     at Module.require (module.js:353:17)
W20160714-18:26:19.885(2)? (STDERR)     at require (internal/module.js:12:17)
W20160714-18:26:19.888(2)? (STDERR)     at bindings (C:\Users\Ondra\AppData\Local\.meteor\packages\npm-bcrypt\0.8.6_2\npm\node_modules\bcrypt\node_modules\bindings\binding
s.js:76:44)
W20160714-18:26:19.890(2)? (STDERR)     at Object.<anonymous> (C:\Users\Ondra\AppData\Local\.meteor\packages\npm-bcrypt\0.8.6_2\npm\node_modules\bcrypt\bcrypt.js:3:35)
W20160714-18:26:19.892(2)? (STDERR)     at Module._compile (module.js:409:26)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

Can anyone try? Or any thoughts? Thanks

**Comment by benjamn** [comment] 2016-07-14 17:24
Try `meteor add npm-bcrypt@0.8.7`?

**Comment by omasopust** [comment] 2016-07-14 17:50
@benjamn Tried this. It updated from 0.8.6_2, but still the same error. Is it possible that this package gets somehow build for 64bit architecture? I don't understand how exactly these binary dependencies work, so I'm just guessing..

**Comment by benjamn** [comment] 2016-07-14 18:00
That is possible. We're building them on a 64bit machine now, for one thing, though the package works for me on a 32bit Windows machine.

What if you remove `C:\Users\Ondra\AppData\Local\.meteor\packages\npm-bcrypt` and try running the app again?

**Comment by omasopust** [comment] 2016-07-14 18:07
It downloaded the package again, and .... it's still the same error.

**Comment by H1net** [comment] 2016-07-14 20:24
Same problem when I pulled my changes over from MacBook today where it has been working great. 

This machine is on Win10x64.
Jumping back through the commits the problem seems to come up when we upgrade from 1.4-beta.9 to 14. All relevant build-tools and `node-gyp` working. I remember on a previous beta build we had had a bcrypt problem which was solved by correctly setting up the latter.

It's the weekend here so I'm happy using the lappy and tackling this next week but you can grab me on the ApolloStack slack if you want to remote debug.

**Comment by lvnr** [comment] 2016-07-15 02:16
The same thing here on a mac, when trying to add accounts-password package to Meteor 1.4-beta.14 (also tried with `meteor add npm-bcrypt@0.8.7`)

```
 => Errors while adding packages:             
                                              
While loading package npm-bcrypt@0.8.6_2:
error: Command failed:
/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm rebuild
--no-bin-links --update-binary
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/levonarakelyan/anaconda/bin/python" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion
(/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at
/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:486:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command
"/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/Users/levonarakelyan/.meteor/packages/npm-bcrypt/.0.8.6_2.1al7k1u++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-6vccrz/node_modules/bcrypt
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 16.0.0
npm ERR! argv
"/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild"
"--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/levonarakelyan/.meteor/packages/npm-bcrypt/.0.8.6_2.1al7k1u++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-6vccrz/npm-debug.log
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/levonarakelyan/anaconda/bin/python" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion
(/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at
/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:486:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command
"/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/Users/levonarakelyan/.meteor/packages/npm-bcrypt/.0.8.6_2.1al7k1u++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-6vccrz/node_modules/bcrypt
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 16.0.0
npm ERR! argv
"/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/levonarakelyan/.meteor/packages/meteor-tool/.1.4.0-beta.14.usy4p3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild"
"--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/levonarakelyan/.meteor/packages/npm-bcrypt/.0.8.6_2.1al7k1u++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-6vccrz/npm-debug.log
```

**Comment by omasopust** [comment] 2016-07-15 02:22
@lvnr Your issue seems to be related to python 3.5. See #7331. This issue is something different.

**Comment by lvnr** [comment] 2016-07-15 10:11
@omasopust You're right. Switching to python 2.7.11 fixed my issue. Thanks.

**Comment by H1net** [comment] 2016-07-15 10:33
My error is the same as @omasopust:

```
C:\Users\user\Documents\Workspace\hajaj>meteor
[[[[[ C:\Users\user\Documents\Workspace\hajaj ]]]]]

=> Started proxy.
=> Started MongoDB.
W20160715-13:27:36.195(3)? (STDERR) C:\Users\user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.14\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20160715-13:27:36.256(3)? (STDERR)                                             throw(ex);
W20160715-13:27:36.259(3)? (STDERR)                                             ^
W20160715-13:27:36.262(3)? (STDERR)
W20160715-13:27:36.265(3)? (STDERR) Error: %1 is not a valid Win32 application.
W20160715-13:27:36.270(3)? (STDERR)
W20160715-13:27:36.273(3)? (STDERR) \\?\C:\Users\user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\bcrypt\build\Release\bcrypt_lib.node
W20160715-13:27:36.279(3)? (STDERR)     at Error (native)
W20160715-13:27:36.283(3)? (STDERR)     at Object.Module._extensions..node (module.js:434:18)
W20160715-13:27:36.287(3)? (STDERR)     at Module.load (module.js:343:32)
W20160715-13:27:36.290(3)? (STDERR)     at Module.Mp.load (C:\Users\user\AppData\Local\.meteor\packages\babel-compiler\6.9.0-beta.14\npm\node_modules\reify\node\runtime.js:16:23)
W20160715-13:27:36.296(3)? (STDERR)     at Function.Module._load (module.js:300:12)
W20160715-13:27:36.300(3)? (STDERR)     at Module.require (module.js:353:17)
W20160715-13:27:36.305(3)? (STDERR)     at require (internal/module.js:12:17)
W20160715-13:27:36.309(3)? (STDERR)     at bindings (C:\Users\user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\bindings\bindings.js:76:44)
W20160715-13:27:36.315(3)? (STDERR)     at Object.<anonymous> (C:\Users\user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\bcrypt\bcrypt.js:3:35)
W20160715-13:27:36.320(3)? (STDERR)     at Module._compile (module.js:409:26)
=> Exited with code: 1
W20160715-13:28:01.293(3)? (STDERR) C:\Users\user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.14\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20160715-13:28:01.301(3)? (STDERR)                                             throw(ex);
W20160715-13:28:01.305(3)? (STDERR)                                             ^
W20160715-13:28:01.308(3)? (STDERR)
W20160715-13:28:01.312(3)? (STDERR) Error: %1 is not a valid Win32 application.
W20160715-13:28:01.315(3)? (STDERR)
W20160715-13:28:01.319(3)? (STDERR) \\?\C:\Users\user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\bcrypt\build\Release\bcrypt_lib.node
W20160715-13:28:01.325(3)? (STDERR)     at Error (native)
W20160715-13:28:01.328(3)? (STDERR)     at Object.Module._extensions..node (module.js:434:18)
W20160715-13:28:01.331(3)? (STDERR)     at Module.load (module.js:343:32)
W20160715-13:28:01.335(3)? (STDERR)     at Module.Mp.load (C:\Users\user\AppData\Local\.meteor\packages\babel-compiler\6.9.0-beta.14\npm\node_modules\reify\node\runtime.js:16:23)
W20160715-13:28:01.341(3)? (STDERR)     at Function.Module._load (module.js:300:12)
W20160715-13:28:01.345(3)? (STDERR)     at Module.require (module.js:353:17)
W20160715-13:28:01.348(3)? (STDERR)     at require (internal/module.js:12:17)
W20160715-13:28:01.352(3)? (STDERR)     at bindings (C:\Users\user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\bindings\bindings.js:76:44)
W20160715-13:28:01.358(3)? (STDERR)     at Object.<anonymous> (C:\Users\user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\bcrypt\bcrypt.js:3:35)
W20160715-13:28:01.364(3)? (STDERR)     at Module._compile (module.js:409:26)
=> Exited with code: 1
W20160715-13:28:18.378(3)? (STDERR) C:\Users\user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.14\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20160715-13:28:18.386(3)? (STDERR)                                             throw(ex);
W20160715-13:28:18.391(3)? (STDERR)                                             ^
W20160715-13:28:18.394(3)? (STDERR)
W20160715-13:28:18.397(3)? (STDERR) Error: %1 is not a valid Win32 application.
W20160715-13:28:18.400(3)? (STDERR)
W20160715-13:28:18.404(3)? (STDERR) \\?\C:\Users\user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\bcrypt\build\Release\bcrypt_lib.node
W20160715-13:28:18.409(3)? (STDERR)     at Error (native)
W20160715-13:28:18.413(3)? (STDERR)     at Object.Module._extensions..node (module.js:434:18)
W20160715-13:28:18.416(3)? (STDERR)     at Module.load (module.js:343:32)
W20160715-13:28:18.420(3)? (STDERR)     at Module.Mp.load (C:\Users\user\AppData\Local\.meteor\packages\babel-compiler\6.9.0-beta.14\npm\node_modules\reify\node\runtime.js:16:23)
W20160715-13:28:18.427(3)? (STDERR)     at Function.Module._load (module.js:300:12)
W20160715-13:28:18.430(3)? (STDERR)     at Module.require (module.js:353:17)
W20160715-13:28:18.434(3)? (STDERR)     at require (internal/module.js:12:17)
W20160715-13:28:18.438(3)? (STDERR)     at bindings (C:\Users\user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\bindings\bindings.js:76:44)
W20160715-13:28:18.443(3)? (STDERR)     at Object.<anonymous> (C:\Users\user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\bcrypt\bcrypt.js:3:35)
W20160715-13:28:18.449(3)? (STDERR)     at Module._compile (module.js:409:26)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by ignl** [comment] 2016-07-17 07:31
I can't even update project to 1.4-beta.14. I installed Visual C++ Build Environment: and did `meteor npm install node-gyp -g `
My error:
```
While loading package npm-bcrypt@0.8.7:
error: Command failed: C:\Users\Useris\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.14\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd rebuild --no-bin-links --update-binary
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\Useris\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.14\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Useris\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.14\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Useris\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-1sd1jyz\npm-debug.log
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by markoshust** [comment] 2016-07-18 18:25
possible dupe of https://github.com/meteor/meteor/issues/7339

**Comment by omasopust** [comment] 2016-07-19 19:00
**I managed to start the server.** Here is what I did:

1) Installed fresh new Windows 10 x64 Pro on a formatted drive.
2) Installed Meteor msi
3) Installed MS Build tools, **this time not with Default settings (which is Windows 8.1 SDK), but with both W8.1 SDK and Windows 10 SDK.**
4) Installed Python 2.7
5) meteor update --release 1.4-beta.13
6) meteor add npm-bcrypt@0.8.7
7) meteor add account-password
8) meteor run 
   => Started your app.

My notes to the issue:
- npm-brypt@0.8.6_2 doesn't compile even with this setup, but 0.8.7 does.
- it's run on the same machine, same OS, as original error from this issue was run.
- Two things that changed: 
  - MS Build tools installed with Windows 10 SDK
  - It's a fresh Win installation, whereas the old one was 2 years old and had a lot of software related to compiling C/C++ like Visual Studio, MinGW, 5 older C++ redistibutables and so on.
- These steps work with 1.4-rc.0 release + step 6 can be omitted as it's added automaticaly.

BTW @markoshust I think the possibility of this one being a dupe of #7339 is very low. It's more like a Windows only issue.

**Comment by abernix** [comment] 2016-07-27 12:45
Folks experiencing this problem still, please see duplicate issue #7469 and _specifically_ this comment: https://github.com/meteor/meteor/issues/7469#issuecomment-235545320.

I'm closing this as a duplicate so please report +1, etc. in that issue if the problem is/isn't solved for you.

**Closed by abernix** 2016-07-27 12:45 UTC
Labels: bug, Impact:some
