### ISSUE TITLE
meteor 1.5: can't do nested imports when using babel es2015-preset: xxx is read-only

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#8701] opened 2017-05-16 17:41 UTC
I have another issue with 1.5 with conditional imports and with babel preset "es2015":

```
const doServerStuff = () => {
  import { myFunc } from '/server/path/to/module.js';

  myFunc();
}


// later, in a method
// ...
if(Meteor.isServer) {
   doServerStuff();
} 
```

now I get an error on the server: `"doServerStuff" is read-only`

Workaround is to switch back to require("....") syntax or remove preset es2015 from babelrc, but we need this preset so that react-storybook is able to transpile the code as well

**Comment by benjamn** [comment] 2017-05-31 13:07
Hoping this is fixed for you with `meteor update --release 1.5`?

**Comment by macrozone** [comment] 2017-05-31 13:21
@benjamn The error still occures on Meteor 1.5. Have to use require(....) as a workaround :-/

**Comment by benjamn** [comment] 2017-05-31 13:25
I think we'll need a reproduction repo to proceed, then, since I haven't been able to reproduce this.

**Comment by macrozone** [comment] 2017-05-31 13:30
Its related to the "es2015" babel preset. I'll update the issue description

**Comment by klaussner** [comment] 2017-07-09 12:56
@macrozone I can't reproduce it, either. The following example works with Meteor 1.5 and outputs `42` on the server when `testMethod` is called.

`server/main.js`:
```js
const doServerStuff = () => {
  import { myFunc } from '/imports/module.js';
  myFunc();
}

Meteor.methods({
  testMethod() {
    if (Meteor.isServer) {
      doServerStuff();
    }
  }
});
```
`imports/module.js`:
```js
export function myFunc() {
  console.log('42');
}
```

`.babelrc`:
```json
{
  "presets": ["es2015"]
}
```

**Comment by hwillson** [comment] 2017-07-09 15:21
Thanks @klaussner - I'll close this for now since we haven't been able to reproduce it. Happy to re-open if a reproduction is provided. Thanks!

**Closed by hwillson** 2017-07-09 15:21 UTC
