### ISSUE TITLE
#Each with an array of string primitives gives this as string Objects in event handler

### ISSUE THREAD

**Issue by vjau** [meteor/meteor#5394] opened 2015-10-08 13:13 UTC
Look at minimal repro here : https://github.com/vjau/meteorbugeach
The value of this, in event handler attached to elements created with #each feeded with an array of string primitives, is a String Object where it should be a String Primitive.
I think this is a regression that was not happening before (when, i don't know).

**Comment by vjau** [comment] 2015-10-08 13:59
According to user Jorgeer on the forums, you cannot use a primitive value as this in Javascript.
What i'm now wondering is why my code has worked fine in the past, if there has been a recent fix about this, perhaps this should be documented as a breaking change somewhere.
Now i'm gonna audit my whole code for other bugs occuring because of this, hope there are not too many ;)

**Comment by stubailo** [comment] 2015-10-08 18:40
@vjau I'm pretty sure this has always been the case! Can you give an example of an app in a previous release of Meteor where `this` _wasn't_ an object?

**Comment by vjau** [comment] 2015-10-08 20:20
@stubailo this part of my code has been in production since november of 2014.
Today, when the problem was reported to me, i had to replace six occurences of this with String(this) to make it work. Nothing was working correctly.
I have been developing this part between september and november of 2014, the UI interactions are not trivial. There is no way i would have thinkered with this code for two months without realising it was not working at all because of improper usage of this in six (!) places.
It's not a difficult to track bug, the UI doesn't work at all, the options come out empty, when you click, nothing happens....
I'm not confortable with sharing this code publicly, do you have an email where i could send it to you for a quick review (at least so you can see the problematic usages of this).
I have tried to run my demo repository with old release of Meteor, and i always end up with a String Object. However, since i know this code was working, there must be some dependencies versions problems that prevent me from running the 'true' old version of meteor.
(or another explanation i really don't get).

**Comment by stubailo** [comment] 2015-10-08 20:25
That's very odd. I explicitly remember this being an issue since Blaze was released in Meteor 0.8.

**Comment by glasser** [comment] 2015-10-08 20:28
Yes, my memory was that we learned that JS just doesn't let you make non-objects into `this`

**Comment by stubailo** [comment] 2016-01-05 23:31
I guess we don't have a reproduction here, but I can't imagine how this worked before.

**Closed by stubailo** 2016-01-05 23:31 UTC
