### ISSUE TITLE
No CSS sourcemaps

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#5520] opened 2015-10-23 09:14 UTC
Sourcemaps don't seem to be working in some cases.

Reproduction:
Clone very simple app: https://github.com/sebakerckhof/meteor-tests

Inspect element refers to merged-stylesheets instead of original file
![image](https://cloud.githubusercontent.com/assets/88471/10688696/5516ef64-7976-11e5-9f7a-5ba761c22393.png)

**Comment by Slava** [comment] 2015-10-23 21:52
Couldn't reproduce on my machine. I am using Chrome 46.0.2490.80
![screen shot 2015-10-23 at 5 51 12 pm](https://cloud.githubusercontent.com/assets/2608446/10705802/c71e9b60-79ae-11e5-9a0a-7844114e43c3.png)

**Comment by abernix** [comment] 2016-07-27 07:30
This also works fine for me in the latest Chrome.  Closing as "can't reproduce"

**Closed by abernix** 2016-07-27 07:30 UTC
Labels: can't-reproduce, Project:Isobuild:Minifiers
