### ISSUE TITLE
[idea] APIs matching the client on server-side publications.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5882] opened 2015-12-26 02:32 UTC
For example, instead of requiring us to use `this.userId` inside of a pub function, perhaps make things like `Meteor.userId()` and `Meteor.user()` work inside there so we can re-use code there (for example, validation functions that might involve `Meteor.user()`). It might make sense with pub functions since they correspond to client instances.

```js
Meteor.publish('foo', function() {
  if (Meteor.userId() === someId) {...}
  let user = Meteor.user() // of the current session requesting a sub.
})

**Comment by trusktr** [comment] 2015-12-26 02:32
Related forums post: https://forums.meteor.com/t/15105

**Comment by mitar** [comment] 2015-12-26 07:52
Duplicate of #5462.

**Comment by stubailo** [comment] 2015-12-27 02:37
Indeed a duplicate.

**Closed by stubailo** 2015-12-27 02:37 UTC
