### ISSUE TITLE
meteor for Windows 7 freezes system for a second repeatedly

### ISSUE THREAD

**Issue by atomtigerzoo** [meteor/meteor#5020] opened 2015-08-24 15:02 UTC
I just tried meteor on my Windows 7. After running the meteor simple-todos app for a few minutes (trying the tutorial) I realize that the system freezes for about a second repeatedly. This freeze is not reproducible (like with clicks, pushes, reload, actions... in the app) and I do only see a peak in Task Manager. I found this because the music player brrrrrbbs for this second. Also mouse-movement and other things stop.

I am sorry, but I have no steps to reproduce :/ Only infos are: Windows 7 64bit with all patches installed with SSD and enough RAM, only Firefox, SublimeText3, FooBar200 and meteor running.

**Comment by avital** [comment] 2015-08-25 22:16
Thanks for the report. Unfortunately right now I don't have time to dig into this, but when we do another round of Windows improvements we'll take a look.

I'll keep this open, curious to hear from others users if they are affected as well.

**Comment by cwmp** [comment] 2015-12-31 01:51
I am also on Windows 7 (64bit) and encountered a major freeze like condition after mongodb insert method call. My system did not respond anymore to mouse and keyboard inputs but at the same time a youtube video playing in the background suffers a massive audio slowdown. A hard reboot was needed. 
I made a change to AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\runners\run-mongo.js (--bind_ip', '0.0.0.0') to listen on all interfaces because a remote service syslog service is inserting new documents.

**Comment by abernix** [comment] 2016-08-02 09:30
Closing.  Happy to reopen with a reliable reproduction.

**Closed by abernix** 2016-08-02 09:30 UTC
Labels: Project:Windows
