### ISSUE TITLE
Can't debug the meteor app, no source map

### ISSUE THREAD

**Issue by GrushinEgor** [meteor/meteor#6977] opened 2016-05-05 16:54 UTC
Meteor Version METEOR@1.3.2.4
In my Dev Tools client's scripts are not available in separated state. They are merged in app.js?hash.
![image](https://cloud.githubusercontent.com/assets/6255315/15050212/f7ae1752-12fa-11e6-8794-736fcedf042c.png)

Even more strange  is that I have a only one file from my model folder which are out of system and client folders

![image](https://cloud.githubusercontent.com/assets/6255315/15050239/21d280ea-12fb-11e6-85c7-c2f4050fac87.png)

**Comment by laosb** [comment] 2016-05-07 12:22
Could you provide a repro?

**Comment by GrushinEgor** [comment] 2016-05-07 15:51
@laosb  How can I do this? 
https://github.com/GrushinEgor/momentri - this project

**Comment by GrushinEgor** [comment] 2016-05-07 20:36
I'm also tried to recreate project, reistall meteor, node. All the same. OS: Windows 7 x64

**Comment by laosb** [comment] 2016-05-08 00:39
You mean, `meteor` automatically minified your js without providing `--production`? Can't reproduce on OS X El Capitan running `meteor` without `--production`. Someone should try to reproduce it on Windows 7 x64 I think.

**Comment by GrushinEgor** [comment] 2016-05-08 09:00
@laosb Even tried to remove standard-minifier-js package. Yes, without production option, just 'meteor' command in my meteor's project folder

**Comment by GrushinEgor** [comment] 2016-05-08 10:37
@laosb Even new project 
![image](https://cloud.githubusercontent.com/assets/6255315/15097383/06aaffbc-1522-11e6-9797-4e8cfc885b48.png)

**Comment by laosb** [comment] 2016-05-08 11:14
OK, hope someone on Windows 7 x64 could reproduce that. Leaving this open.

**Comment by GrushinEgor** [comment] 2016-05-22 12:16
@laosb Solved! I found the culprit — I had installed `pbastowski:angular-babel@1.0.4` manually (I dunno know why). After removing it and reinstall `angular` it works!

**Comment by laosb** [comment] 2016-05-23 04:23
So you may post this to `pbastowski:angular-babel`'s repo again! Closing as this doesn't like a Meteor-itself issue.

**Closed by laosb** 2016-05-23 04:23 UTC
Labels: bug

**Comment by deeeed** [comment] 2016-06-14 03:47
It does seem to be a Chrome issue. 
I tested on an empty project and chrome doesn't get the source map for the project files. It does work for the packages though.
<img width="293" alt="screen shot 2016-06-14 at 11 43 52 am" src="https://cloud.githubusercontent.com/assets/4800095/16030608/89252768-3225-11e6-9e0d-c2fd5dff2216.png">

The sourcemaps are working with Chrome Canary and Firefox.
![screen shot 2016-06-14 at 11 44 10 am](https://cloud.githubusercontent.com/assets/4800095/16030617/96493ce0-3225-11e6-9a90-8cf5752bd483.png)
<img width="527" alt="screen shot 2016-06-14 at 11 45 02 am" src="https://cloud.githubusercontent.com/assets/4800095/16030619/9b416916-3225-11e6-85dc-05495293768b.png">


Not sure what changed on the current Chrome version...

**Comment by laosb** [comment] 2016-06-14 12:17
I see... Hope it's just a browser problem.

**Comment by GrushinEgor** [comment] 2016-06-14 12:26
So now I have a this situation: In one hand with explicit installed pbastowski:angular-babel I can debug serverside, but can't clientside (source maps are broken). In the other hand with implicitly (automatic install as dependency for angular) source maps not broken, clientside debug works but..serverside debug broken....
