### ISSUE TITLE
[Performance] Add .pause for Blaze reactive update while data is arriving?

### ISSUE THREAD

**Issue by fungilation** [meteor/meteor#3976] opened 2015-03-20 06:48 UTC
**_1 Upvote**_ Continuing from https://forums.meteor.com/t/blaze-rendering-abnormally-slow-on-large-subsequent-dom-changes-iphone/1153

Consider a typical infinite scroll app. In my case at http://clubch.at/, a chat app. It loads 100 messages on initial page load, with Messages subscription done in a Iron Router waitOn so it doesn't render template until data is done loading. More messages are loaded on demand, at increments of 50 at a time in my case. This is how I did it before, with a 2nd subscription to the same publication 'msgsByClub with Media, Votes', but with a reactive var as the sub limit instead of the a static 100 as limit in the sub in the waitOn:

``` coffeescript
Tracker.autorun -> if Router.current()
  Template.instance().subscribe 'msgsByClub with Media, Votes', Router.current().params._clubName, Session.get('clubMsgsLimit ' + Router.current().params._clubName)
```

This is the way most people would suggest online, by setting a reactive var as the subscription limit. The problem with this is performance, vastly exaggerated by slow performance on mobile browsers which my app is targeting. Blaze as I've observed would attempt to render while data is arriving on iOS, in a staggered fashion. Of the 50 increment messages incoming, 5 would get rendered, more data arrive after a second, 5 more render, etc. On my iPhone 6 (which is no slow device), it would take 20-30s to finish rendering the 50 additional messages, while the UI is highly unresponsive and CPU is constantly pegged at 100%. (this is a case for Meteor to add Web Workers support to better utilize multiple cpu cores? Side topic)

The performance problem here is that on mobile, rendering is too slow and it chokes while attempting to render as data arrives, when Blaze should not render updates while data is arriving and CPU is pegged. On desktop browsers (Chrome) this isn't an issue, 50 messages gets rendered almost instantly in less than a second.

To illustrate how this rendering while data is arriving completely kills performance on mobile safari: A initial loading of 200 messages, in a IR waitOn subscription, gets rendered in less than a second on the iPhone. As such, I've done a workaround (hack?) that is working well for my app running at http://clubch.at/ currently, by requesting the 50 messages increment in bulk via a Meteor method call and then injecting the data into minimongo all at once. The above client code becomes this:

``` coffeescript
Tracker.autorun -> if Router.current()
  skip = Messages.find({ club_name: Router.current().params._clubName }).count()
  limit = Session.get('clubMsgsLimit ' + Router.current().params._clubName) - skip
  if limit > 0
    Meteor.call 'MessagesPage', Router.current().params._clubName, skip, limit, (error, result) ->
      if !error
        result.forEach (msg) ->
          return  if Messages._collection.find(msg._id).count() > 0
          Messages._collection.insert msg    # I feel slightly dirty abusing minimongo here. I do clean up after myself with _collection.remove on route change later
```

And the server method:

``` coffeescript
Meteor.methods          
  MessagesPage: (clubName, skip, limit) ->
    cursor = Messages.find
      club_name: clubName
    ,
      skip: skip
      limit: limit
      sort: { createdAt: -1 }
    return cursor.fetch()
```

The result is the 50 new messages gets rendered by Blaze in less than a second! Instead of the 20s+ it took for it to completely render before when subscription limit was raised by a Session var and gets rendered chunk by chunk.

I'm writing this here as more than just an account of my experience. Infinite scroll on mobile devices is a common enough pattern and use case nowadays, and I get the feeling that a performance bottleneck like this is overlooked as Meteor dev is still mostly done for desktop apps? If I'm doing something stupid here by hacking with minimongo like this, please let me know too as I haven't worked with Meteor for too long and not too familiar with Blaze's API and internals. If there's a method to pause reactive update of a select Template, so it can be resumed only when a subscription is Ready again after new data completes loading, there'd be no need then for my minimongo hack.

Many pennies for your thoughts.

**Comment by steph643** [comment] 2015-03-20 08:08
I am currently fighting against something strangely similar, although not on mobile. I will post here if I find something relevant.

Notice that, in my experience, anything you insert directly in `Messages._collection` may or may not be removed without notice by subsequent updates of the collection. This makes `_collection` very risky to use.

**Comment by steph643** [comment] 2015-03-20 08:49
You said:

>The performance problem here is that on mobile, rendering is too slow and it chokes while attempting to render as data arrives

Then you said:

>A initial loading of 200 messages, in a IR waitOn subscription, gets rendered in less than a second on the iPhone. 

Aren't those assertions contradictory?

I am asking because, on my side, I came to doubt that the problem relates to browser rendering.

**Comment by fungilation** [comment] 2015-03-20 09:05
No. On mobile safari, initial loading in waitOn doesn't render template until the 200 messages are done loading and sub is ready so that's fast. <1s fast, same as on desktop. It's the reactive limit (50 increments) placed on a second subscription to the same messages publication that chokes (on mobile) when the limit is raised and data and rendering happens together. The minimongo hack is my way of not letting the template to reactively render until all 50 messages arrived on client.

I'm not excluding a bug or strange behaviour with mobile safari in this.

For Messages._collection, it's ok for my usage as old messages are mostly static and currently I'm not letting messages get edited once posted.

**Comment by steph643** [comment] 2015-03-20 14:02
As promised:
Might be related to issue #3978
Might be related to issue #3979

**Comment by stubailo** [comment] 2015-03-24 22:04
One workaround for now is to use `Template.subscriptionsReady` to show a loading indicator while the data is being fetched over the wire, and then render everything all at once. Going to mark this as a feature in the sense that it is a performance enhancement.

**Comment by fungilation** [comment] 2015-03-24 22:20
How would Template.subscriptionsReady be a workaround? Can it stop progressive DOM rendering while data is arriving? That was my suggestion in title of this issue. Template.subscriptionsReady AFAIK only lets you render an alternative template, not to stop rendering of more collection data in an already rendered template that depends on an initial load of that collection as I've described in my infinite scroll case.

Thanks for tagging for addressing as performance enhancement.

**Comment by artpolikarpov** [comment] 2015-05-27 10:39
+1

**Comment by lorensr** [comment] 2015-07-09 18:40
If you also publish the count, this might work?
- add a dep to beginning of `items` helper
- wrap rest of helper in a `nonreactive` block
- change limit to n + 50
- wait for client-side count to reach either published count or n + 50
- invalidate `items` dep so that helper runs again

**Comment by fungilation** [comment] 2015-07-10 20:50
That's probably a more elegant way of doing the same as my solution with sample code I pasted in original post. Doesn't change the fact that reactivity is the point of Meteor and working around performance issues with DOM's reactive rendering like this is a hack.

**Comment by mitar** [comment] 2015-10-15 02:37
Is this ticket a duplicate of #2031?

**Comment by fungilation** [comment] 2015-10-15 03:18
I guess that's a more general case/request of the problem I had.

**Comment by mitar** [comment] 2016-02-11 20:12
@fungilation: Could you check if this pull request solves your problem? #5680

**Comment by mitar** [comment] 2016-11-01 23:50
I think this should be closed with same rationale as described in: https://github.com/meteor/blaze/issues/147

Moreover, one can use [computed field](https://github.com/peerlibrary/meteor-computed-field) to minimize impact of reactivity.

**Closed** 2016-11-01 23:51 UTC
Labels: feature, Project:Blaze
