### ISSUE TITLE
Template.currentData behaves differently in helpers and event handlers

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3249] opened 2014-12-07 05:18 UTC
Currently there is a big difference how `Template.currentData()` behaves inside a event handler and template helper. In event handler it returns always the data context at the top level of a template where event handler was defined (and `this` is a data context of where event was triggered).

But for template helper it is always where the template is rendered. So if one is using `Template.currentData()` to access the template-level data context in the event handler, you have to use `Blaze.getData(Template.instance().view)` to access the same template-level data context in the template helper. So reusing the code and learned behavior between event handlers and template helpers is hard and it leads to programming bugs.

See example:

https://github.com/mitar/meteor-issue3249

As example also shows, `Template.parentData` would not be a suitable approach here because the same code is used at various level of data contexts.

**Comment by avital** [comment] 2015-02-11 01:15
I think this is solved with #3546, can you please verify @mitar?

**Comment by mitar** [comment] 2015-02-11 11:12
@retronator, can I delegate to you to check this?

**Comment by Retronator** [comment] 2015-02-17 00:43
I've created a test project, which outputs what different functions are returning in template helpers and event handlers:
https://github.com/Retronator/meteor-contexts

With this I can now confirm that in the `devel` branch, template helpers and event handlers now return consistent results. 

Thanks for fixing this!

**Comment by stubailo** [comment] 2015-03-09 21:45
Unfortunately, we ended up not including this in the next release because it is a breaking API change that might break some real apps.

We will need to come up with a new function or API that includes this functionality.

**Comment by mitar** [comment] 2015-03-09 21:56
We created this nice chart on how things are: https://docs.google.com/spreadsheets/d/14DTa0096y7cA1wkbUXUo_lLPwHJji0ft14_9EnArhsM/edit?usp=sharing

I think it was really nicely fixed. Please don't add new function for things which were inconsistent before.

**Comment by stubailo** [comment] 2015-03-17 21:36
@mitar, I was thinking of implementing something like `Spacebars.lookup` inside all template callbacks, helpers, and event handlers. The intention is that it will work the same way as `{{...}}` when accessing the data context, scope, and helpers of the current DOM element.

So instead of using parentData, you can use `Spacebars.lookup("../x")`. This API will be uniform across all locations, significantly reducing the size of your table.

**Comment by mitar** [comment] 2015-03-17 21:41
Maybe rather `Template.lookup`?

But this still does not help with the fact that `Template.currentData()` behaves inconsistently. We had initially quite few bugs before we figured out the issue and that's why we opened it here. In my opinion, the current behavior is a bug. I think it probably makes more issues to people than those who depend on the current behavior.

**Comment by mitar** [comment] 2015-03-17 21:56
BTW, I implemented a bit better lookup in [meteor-template-extension](https://github.com/aldeed/meteor-template-extension). In fact it is anyway very error prone to have to specify exact number of parents when trying to access data. So for me your `Spacebars.lookup` would be just a workaround around `Template.currentData` issue and I will not be using `..` feature. So I am not sure how useful it is for you to complicate with `..` and so on.

Because for me using more declarative way when searching for parent data context and using `Template.parentData(fun)` is much better. I can then search for a data context which is an instance of my component system and it works. No matter how many other temporary data contexts were maybe added. And sometimes it is even impossible to specify a fixed value. Because when template is included in one location it might have different number of data contexts than in another location. And you want your event handlers to work in both cases.

**Comment by stubailo** [comment] 2015-03-17 23:45
@mitar I agree that is a concern. It seems almost too powerful though to have a function that searches all the way up the view tree - it would be very easy to have something unexpected up there that would cause your code to misbehave. Any ideas how to solve that problem?

**Comment by mitar** [comment] 2015-03-18 00:48
We have not yet had issues with that. But we had issues with trying to keep up the correct number of data contexts. `Template.parentData(7)` is hard to read, understand, and reason about. `Template.parentData(instanceOf(Component))` is much better. Of course, you can write bad functions, but you cannot fight that. In general, I had to use only two functions until now: one which searches for instance, and another which searchers for the first data context having a given field.

**Comment by mitar** [comment] 2015-03-26 08:57
What is current workaround to get with global function the data context of where the call occurred. So in template helper where it was called, and in event handler, where the click happened. So that I can call the same helper functions from both the event handlers and template helpers. With the fixed `Template.currentData()` that would be it, no?

So `Blaze.getData(Template.instance().view)` will always give me the template instance data context in both event handler and template helper.

**Comment by cwohlman** [comment] 2015-05-21 19:09
I'd like to agree with mitar that the existing implementation is extremely confusing. Meteor developers (like myself) are used to thinking of event handlers and template helpers as being called in an almost identical fashion (the only difference is that event handlers don't receive arguments), and this breaks that consistency.

**Comment by stubailo** [comment] 2015-05-21 19:12
I 100% agree. The problem is that some current apps and packages rely on the current functionality.

**Comment by cwohlman** [comment] 2015-05-21 19:20
@stubailo Wouldn't it make sense to deprecate the unexpected behavior, and then update meteor to support either the expected behavior, or some new api?

e.g. if `Template.parentData()` is called in an event handler we log an error to the console `Warning calling Template.parentData() from within an event handler may return unexpected results + a reference to this issue`?

Of course part of the issue is to figure out what is expected behavior... I personally have always used `Template.parentData()` to access the parent data context relative to whatever `this` is, but this thread seems to suggest that many developers expect `Template.parentData()` to refer to the parent of the Template's data context... which function is more useful greatly depends on how you use templates.

**Comment by hwillson** [comment] 2016-11-28 18:05
Migrated over to meteor/blaze#183 - closing here, thanks!

**Closed by hwillson** 2016-11-28 18:05 UTC
Labels: Project:Blaze
