### ISSUE TITLE
[1.3-beta.12] .addJavaScript does not accept repeated calls in build plugin

### ISSUE THREAD

**Issue by huttonr** [meteor/meteor#6409] opened 2016-03-04 08:56 UTC
It appears that you cannot call `.addJavaScript` more than once in a build plugin (at least the usual build plugin, possibly not the caching one which I believe uses a different system).

The second `.addJavaScript` overrides the initial call.

Therefore the following code does not work:

```javascript
// This file _will not_ be included in sources
settingsFile.addJavaScript({
  data: 'console.log("Cheeseburger");',
  path: path.join('client', 'lib', 'test.generated.js')
})

// This file _will_ be included in sources
settingsFile.addJavaScript({
  data: 'console.log("Caesar Salad");',
  path: path.join('client', 'lib', 'hello.generated.js')
})
```

**This is new to 1.3.**  This functionality worked as one would expect in 1.2.1.

Is this now unsupported?  There are use cases for adding multiple javascript outputs from a single original source.  Such as needing a bare source and a non-bare source.  One can wrap it manually but that isn't as pretty.

It obviously isn't vital vital vital as one can merge them, but it would be nice if it worked as it did previously.

**Comment by martijnwalraven** [comment] 2016-03-05 19:15
Duplicate of #6422.

**Closed by martijnwalraven** 2016-03-05 19:15 UTC
