### ISSUE TITLE
Windows binary build error 

### ISSUE THREAD

**Issue by arunoda** [meteor/meteor#4087] opened 2015-04-01 08:30 UTC
I tried to build `meteorhacks:kadira-binary-deps@1.4.0` for windows and got following error:
(using a machine created with meteor admin)

``` shell
npm ERR! node v0.10.36
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the v8-profiler@5.2.0 install script 'node-gyp
rebuild'.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

=> Errors while initializing project:

While building package meteorhacks:kadira-binary-deps:
error: couldn't install npm packages from npm-shrinkwrap
```

I also get this error on linux as well. So, I fixed it by building on my own machine.
I think this is due to the python version used on the box and I think this is coming from when trying to build the `v8-profiler`.

Anyway, this works without any issues on the mac machines and the previous machine used for windows (with 1.1 RC)

**Comment by glasser** [comment] 2015-04-01 16:59
Related to this? https://github.com/node-inspector/v8-profiler/issues/47

**Comment by stubailo** [comment] 2015-04-01 17:05
Wow, that's the worst. Maybe we need to install many versions of Visual Studio and let people pick somehow.

**Comment by jhuenges** [comment] 2015-04-03 17:44
I have a similar problem:
```
npm ERR! protobuf@0.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protobuf@0.11.0 install script 'nod
npm ERR! This is most likely a problem with the protobuf p
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protobuf
npm ERR! There is likely additional logging output above.
```
This is what I get if I use ```meteorhacks:npm``` on Windows 7 with Meteor 1.1.01.

**Comment by pvndemic** [comment] 2015-04-05 06:43
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.
npm: updating npm dependencies -- steam, dota2, steamidconvert,
random-words...
npm WARN package.json packages-for-meteor-smartpackage-hygn49@0.0.0 No
description
npm WARN package.json packages-for-meteor-smartpackage-hygn49@0.0.0 No
repository field.
npm WARN package.json packages-for-meteor-smartpackage-hygn49@0.0.0 No
README data
npm WARN peerDependencies The peer dependency steam@>= 0.6.0 included from
dota2 will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
npm WARN engine protobuf@0.8.7: wanted: {"node":">= 0.8.0 < 0.9.0"}
(current: {"node":"0.10.36","npm":"2.7.3"})
npm WARN engine protobuf@0.8.7: wanted: {"node":">= 0.8.0 < 0.9.0"}
(current: {"node":"0.10.36","npm":"2.7.3"})
gypgypgypgypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv
"C:\\Users\\Alan\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.1\\mt-os.w
indows.x86_32\\dev_bundle\\bin\\\\node.exe"
"C:\\Users\\Alan\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.1\\mt-os.w
indows.x86_32\\dev_bundle\\bin\\node_modules\\npm\\bin\\npm-cli.js"
"install"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! protobuf@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protobuf@0.8.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protobuf
npm ERR! There is likely additional logging output above.


=> Errors prevented startup:

   While building package npm:
   error: couldn't install npm packages from npm-shrinkwrap

=> Your application has errors. Waiting for file change.

Message produced with npm in .meteor/packages. The same message as "jhuenges" is reproduced if I use meteorhacks:npm in .meteor/packages. Has anyone been able to solve this? Working on Windows by the way.

**Comment by jhuenges** [comment] 2015-04-05 07:27
@pvndemic just out of curiosity, what are you application are you building? I get same error messages because I use dota2 and steam aswell :D

**Comment by pvndemic** [comment] 2015-04-05 07:32
im trying to deploy: https://github.com/paralin/D2Solo

just trying to learn new functionality but i cant even get it working

**Comment by arunoda** [comment] 2015-04-19 13:11
I managed build this by my own by installing by VS-2013 on a Win 7 32 machine. I hope we may need to use VS 2013 on the default server.

This raised an older discussion on building packages. I couldn't `meteorhacks:kadira-binary-deps` using the machines provided by meteor. So, I guess meteor admin machines have the oldest version of tools (or least common versions) assuming once build for them, it will work with all the versions.

But, that's not going to work.
Once meteor started to support 0.12.x or io.js, we need to build for those platforms as well.

**Comment by aaronjudd** [comment] 2015-08-13 17:13
@arunoda do you have a work around for publishing on windows? I'm also getting: 
```
$ meteor admin get-machine os.windows.x86_32
bin\\npm-cli.js"
"install"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.1.10 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the iconv@2.1.10 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

=> Errors while initializing project:

While building package ongoworks:google-spreadsheets:
error: couldn't install npm packages from npm-shrinkwrap
```

**Comment by arunoda** [comment] 2015-08-13 22:32
Try using a your own Windows box.

**Comment by hwillson** [comment] 2017-08-15 19:37
There has been recent discussion about potentially shutting the Meteor build farm down. MDG is moving towards a different build process internally, and the existing build farm is used very little. More details on this plan will be coming shortly (likely as part of the work on meteor/meteor-feature-requests#152). Given this new direction, I'll close this issue for now. Thanks!

**Closed by hwillson** 2017-08-15 19:37 UTC
Labels: Project:Isobuild, Project:Windows
