### ISSUE TITLE
Run Android Failed (simple-todos)

### ISSUE THREAD

**Issue by wsjwong** [meteor/meteor#5780] opened 2015-12-11 14:00 UTC
I followed the simple-todos tutorial on my mac (OS X Capitan), but when I do the meteor run android, it shows below errors. Any ideas? Thank you.

```
meteor run android
[[[[[ ~/git/simple-todos ]]]]]                

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                                                            
                                              
=> App running at: http://localhost:3000/     
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --emulator:
   Error: Command failed:                     
   /Users/Joe/git/simple-todos/.meteor/local/cordova-build/platforms/android/cordova/run
   --emulator

   /Users/Joe/git/simple-todos/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   ERROR : No emulator images (avds) found.
   1. Download desired System Image by running:
   /Users/Joe/Library/Android/sdk/tools/android sdk
   2. Create an AVD by running: /Users/Joe/Library/Android/sdk/tools/android
   avd
   HINT: For a faster emulator, use an Intel System Image and install the HAXM
   device driver
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

ExitWithCode:1
```

**Comment by mahammedzkhan** [comment] 2015-12-15 11:12
You need to install Android SDK to use the Android emulator:
http://developer.android.com/sdk/index.html

**Comment by timbotnik** [comment] 2015-12-15 23:00
@wsjwong can you confirm that this is a result of not having the Android SDK installed?  An installation guide can be found here: https://github.com/meteor/meteor/wiki/Meteor-Cordova-integration

**Comment by wsjwong** [comment] 2015-12-16 01:58
I have followed this guide except the last optional setting: https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Mac
Installed Android Studio and Android 5.1.1 (API 22), but it still does cannot find my emulator. Any debug command/setting I could try to find out more information about the issue? Thank you very much.

**Comment by wsjwong** [comment] 2015-12-16 02:06
I just found out there is an planned issue which is [Issue5358](https://github.com/meteor/meteor/issues/5358).
Is that a known issue?

**Comment by timbotnik** [comment] 2015-12-16 03:12
Hmm, perhaps creating an AVD manually is the workaround for now?

https://github.com/meteor/meteor/issues/5380

**Comment by peterobrien** [comment] 2016-01-05 19:31
Yes, had exactly the same issue here. Worked around by creating an initial (empty) project in Android Studio, and then being able to create an AVD via Tools -> Android -> AVD manager. There may be a way without creating the initial project but I don't know

Recommendation to add-to/improve tutorial in https://github.com/meteor/meteor/issues/5908 valid

**Comment by martijnwalraven** [comment] 2016-02-19 09:53
Closing this as a duplicate of #5380.

**Closed by martijnwalraven** 2016-02-19 09:53 UTC
Labels: Project:Mobile
