### ISSUE TITLE
Iron Router does not detect routes on cordova

### ISSUE THREAD

**Issue by TheRealNate** [meteor/meteor#6043] opened 2016-01-19 20:19 UTC
My app works fine but when I use meteor run android-build and, or use a debuggable apk.

But when I run the app on my device using a signed release apk I see the iron:router startup screen that tells me how to create a route.

How I am doing routes:
Router.route('startPage", 
  { 
    path: '/' 
  });

Is there some special place I should keep my router.js file? Please help me!

**Comment by martijnwalraven** [comment] 2016-01-19 22:41
From your description, I'm not sure what could be going on. Could you share a minimal project that reproduces the issue?

**Comment by TheRealNate** [comment] 2016-01-20 00:44
I'm not sure if this is pertinent, but:
I am getting a release-unsigned.apk instead of a unaligned.apk

**Comment by TheRealNate** [comment] 2016-01-20 00:48
I am still trying to make a minimal app that reproduces the issue.

**Comment by PeppeL-G** [comment] 2016-02-11 19:37
I encountered this problem as well, tried to debug it and presented my result at https://github.com/iron-meteor/iron-router/issues/1386 . Any suggestion on how I can debug the Android application when it has been built for production?

**Comment by martijnwalraven** [comment] 2016-02-11 19:42
You should be able to use the Chrome remote debugger (`chrome://inspect`) when the device is connected over USB.

Not sure if this solves your specific issue, but I just released a 1.3 beta with rewritten hot code push for Android: https://github.com/meteor/meteor/issues/6050.

**Comment by PeppeL-G** [comment] 2016-02-11 19:58
Are you sure that works for apps built for production? I only got that working for none-production apps, and the problem only occurs on production apps.

I'll try Meteor 1.3 when time permits, but I cross my fingers 1.3 will make it work.

**Comment by martijnwalraven** [comment] 2016-02-11 20:04
Hmmm, I'm not sure, a release build may actually disable the inspector in the web view.

**Comment by dagatsoin** [comment] 2016-02-11 22:30
Do you use hashHistory or browserHistory? I saw on SO that Cordova only works with hashHistory.

**Comment by martijnwalraven** [comment] 2016-02-11 22:34
@dagatsoin: Cordova normally only works with `hashHistory` because `file://`URLs don't support `pushState`. But in Meteor, we serve files from `localhost` (`meteor.local` in versions before 1.3), so we don't have that restriction.

**Comment by martijnwalraven** [comment] 2016-02-19 09:43
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.

**Closed by martijnwalraven** 2016-02-19 09:43 UTC
Labels: Project:Mobile

**Comment by PeppeL-G** [comment] 2016-02-20 18:16
@martijnwalraven, the error doesn't show up in `Meteor 1.3-beta.11`, so I think everything works as it should (I haven't tested it much). Good work!

**Comment by TheRealNate** [comment] 2016-02-20 19:16
The issue is fixed, I am not completely sure how, a mix of running in production and cleaning up file structure.

**Comment by nloui** [comment] 2016-06-03 07:15
Anyone else seeing this issue? I'm actually having the same problem with the latest versions

**Comment by TheRealNate** [comment] 2016-06-07 14:24
@nloui my advice is:
- Try running your app in production, if it doesn't work it won't work in cordova.
- Clean up your file structure, go online and check tips for meteor.
- Put your Router file in the "lib" directory

But one major thing I found was that Cordova builds everything. So if there is an error, even if it is in a file your not using, it will complain and fail.
