### ISSUE TITLE
[1.4.1.x] No such file or directory, open ... tmp ... /os.json

### ISSUE THREAD

**Issue by SahnounM91** [meteor/meteor#7785] opened 2016-09-18 17:18 UTC
hi , after the install of meteor and  start meteor commander under my project i get this error : 

**/home/sa7noun/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^
Error: ENOENT: no such file or directory, open '/tmp/mt-s7x2az/os.json'
    at Error (native)**

**Comment by MiGu3X** [comment] 2016-09-19 21:54
Getting same error with meteor fresh install
It seems to be an error with meteor tools 1.4.1.1 even though my project is in version 1.4.0.1 it throws me that error whenever trying to downgrade or run a meteor app

First it starts with 'Downloading meteor-tool@1.4.0-1...' and then it throws the same error.
`/home/miguel/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-1d0ypym/os.json'
    at Error (native)
`

**Comment by macielbombonato** [comment] 2016-09-29 12:37
On ubuntu 16.04 I tryed the #EDIT 1 solution and don't work to me.

**Comment by MiGu3X** [comment] 2016-09-30 00:37
@macielbombonato 
Try doing it with another computer, a friend made it with Windows 10 and it worked perfectly for him (he had the same issue on Ubuntu 16.04).

If this doesn't work, make a fresh install of nodejs, npm, meteor and your project.
Hope it helped.

**Comment by abernix** [comment] 2016-09-30 12:05
Closing as this appears to be a duplicate of #7806.  Please check over there, +1 if it sounds like the same problem, and provide the requested information to help resolve it!

Thanks!

**Closed by abernix** 2016-09-30 12:05 UTC
