### ISSUE TITLE
[1.6.1]The Mongo server and the Meteor query disagree on how many documents match your query.

### ISSUE THREAD

**Issue by lynchem** [meteor/meteor#9619] opened 2018-02-01 15:55 UTC
We got this last night after updating from 1.6.0.1 -> 1.6.1 . We use an mlab cluster for our db running mongo 3.0.12 MMAPv1 and deploy to Galaxy. This bug seems to be a duplicate of #9087 and has been reproduced by @jessedvrs. 

Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {}
at packages/mongo/oplog_observe_driver.js:881:15
at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
at OplogObserveDriver.proto._publishNewResults (packages/mdg_meteor-apm-agent.js:2899:38)
at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
at OplogObserveDriver._runInitialQuery (packages/mongo/oplog_observe_driver.js:658:10)
at packages/mongo/oplog_observe_driver.js:191:10
at packages/mongo/oplog_observe_driver.js:15:9
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
at packages/meteor.js:502:25
at runWithEnvironment (packages/meteor.js:1240:24)

Here was the list of packages that were updated.

accounts-base upgraded from 1.4.0 to 1.4.2
autoupdate upgraded from 1.3.12 to 1.4.0
babel-compiler* upgraded from 6.24.7 to 7.0.0
babel-runtime upgraded from 1.1.1 to 1.2.0
boilerplate-generator upgraded from 1.3.1 to 1.4.0
callback-hook upgraded from 1.0.10 to 1.1.0
check upgraded from 1.2.5 to 1.3.0
coffeescript downgraded from 1.11.1_4 to 1.0.17
ddp-client upgraded from 2.2.0 to 2.3.1
ddp-common upgraded from 1.3.0 to 1.4.0
ddp-server upgraded from 2.1.1 to 2.1.2
diff-sequence upgraded from 1.0.7 to 1.1.0
dynamic-import upgraded from 0.2.1 to 0.3.0
ecmascript upgraded from 0.9.0 to 0.10.0
ecmascript-runtime-client upgraded from 0.5.0 to 0.6.0
es5-shim upgraded from 4.6.15 to 4.7.0
http upgraded from 1.3.0 to 1.4.0
id-map upgraded from 1.0.9 to 1.1.0
meteor-base upgraded from 1.2.0 to 1.3.0
minifier-css upgraded from 1.2.16 to 1.3.0
minifier-js upgraded from 2.2.2 to 2.3.1
modules upgraded from 0.11.1 to 0.11.3
mongo upgraded from 1.3.1 to 1.4.2
ordered-dict upgraded from 1.0.9 to 1.1.0
promise upgraded from 0.10.0 to 0.10.1
random upgraded from 1.0.10 to 1.1.0
reload upgraded from 1.1.11 to 1.2.0
retry upgraded from 1.0.9 to 1.1.0
server-render added, version 0.3.0
shim-common added, version 0.1.0
socket-stream-client added, version 0.1.0
standard-minifier-css upgraded from 1.3.5 to 1.4.0
standard-minifier-js upgraded from 2.2.3 to 2.3.1
url upgraded from 1.1.0 to 1.2.0
webapp upgraded from 1.4.0 to 1.5.0

These packages have been updated to new versions that are not backwards
compatible.
obit: updated to Meteor 1.6.1.
Changes to your project's package version selections from updating package versions:

babel-runtime upgraded from 1.2.0 to 1.2.2
caching-compiler upgraded from 1.1.9 to 1.1.11
ecmascript-runtime-client upgraded from 0.6.0 to 0.6.1
es5-shim upgraded from 4.7.0 to 4.7.3
jquery upgraded from 1.11.10 to 1.11.11
modules-runtime upgraded from 0.9.1 to 0.9.2
mongo upgraded from 1.4.2 to 1.4.3
npm-mongo upgraded from 2.2.33 to 2.2.34
stylus upgraded from 2.513.13 to 2.513.14

**Comment by glasser** [comment] 2018-02-01 18:58
There were some changes in the `mongo` package bundled with Meteor 1.6.1 that were reverted after that release. Can you try `meteor update mongo` and see if you have the same issue?  cc @benjamn

**Comment by glasser** [comment] 2018-02-01 19:00
Although I'm confused from what you've pasted about whether you are running `mongo` 1.4.2 (which had the potentially problematic changes) or 1.4.3 (which reverted them). What do you see in the `mongo` line of `.meteor/versions`?

**Comment by lynchem** [comment] 2018-02-02 09:23
Hi @glasser , I deployed 1.4.3 
It's difficult to do any tests as our test/staging setups use mlab sandboxes and don't have oplog. I've noticed atlas now offer free tier clusters with oplog so I'll upgrade them soon if I can so I might be able to reproduce it. 

The above output from meteor update isn't entirely accurate as I produced it by running the command after I reverted the change. I thought it would be easier to see what had changed though. So in theory some package might have been updated between Wednesday (31st), day of the update/deploy and the morning after. I think babel-runtime for example was deployed at 1.2.2. 

Here's exactly what was deployed. 

255kb:meteor-status@1.5.0
accounts-base@1.4.2
accounts-password@1.5.0
alanning:roles@1.2.16
alanning:trace@0.0.2
aldeed:autoform@5.8.1
aldeed:collection2@2.10.0
aldeed:collection2-core@1.2.0
aldeed:schema-deny@1.1.0
aldeed:schema-index@1.1.1
aldeed:simple-schema@1.5.3
aldeed:tabular@2.2.2
aldeed:template-extension@3.4.3
allow-deny@1.1.0
amplify@1.0.0
anti:i18n@0.4.3
arillo:flow-router-helpers@0.5.2
autoupdate@1.4.0
babel-compiler@7.0.0
babel-runtime@1.2.2
babrahams:editable-json@0.6.3
babrahams:temple@0.4.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.4.0
brentjanderson:buzz@1.1.10
caching-compiler@1.1.11
caching-html-compiler@1.1.2
callback-hook@1.1.0
check@1.3.0
coffeescript@1.0.17
comerc:autoform-typeahead@1.0.6
comerc:bs-typeahead@1.0.2
constellation:console@1.4.0
constellation:position@0.4.0
constellation:session@0.4.1
constellation:subscriptions@0.4.1
dburles:collection-helpers@1.1.0
dburles:google-maps@1.1.5
dburles:mongo-collection-instances@0.3.5
ddp@1.4.0
ddp-client@2.3.1
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.1.2
deps@1.0.12
diff-sequence@1.1.0
dynamic-import@0.3.0
ecmascript@0.10.0
ecmascript-runtime@0.5.0
ecmascript-runtime-client@0.6.0
ecmascript-runtime-server@0.5.0
edgee:slingshot@0.7.1
ejson@1.1.0
email@1.2.3
es5-shim@4.7.3
fortawesome:fontawesome@4.7.0
fourseven:scss@3.13.0
froala:editor@2.7.3
geojson-utils@1.0.10
gwendall:body-events@0.1.6
gwendall:session-json@0.1.7
hausor:autoform-bs-minicolors@1.0.0
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.4.0
ian:accounts-ui-bootstrap-3@1.2.89
id-map@1.1.0
jquery@1.11.11
juliancwirko:s-alert@3.2.0
juliancwirko:s-alert-stackslide@3.1.3
kadira:blaze-layout@2.3.0
kadira:flow-router@2.12.1
lai:collection-extensions@0.2.1_1
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.2.0
logging@1.1.19
lytesoft:autoform-bs-datetimepicker@0.0.1
lytesoft:autoform-select2@0.0.1
matb33:collection-hooks@0.8.4
mdg:meteor-apm-agent@3.1.1
mdg:validation-error@0.5.1
meteor@1.8.2
meteor-base@1.3.0
meteorhacks:aggregate@1.3.0
meteorhacks:collection-utils@1.2.0
meteorhacks:meteorx@1.4.1
meteorhacks:picker@1.0.3
meteorhacks:search-source@1.4.2
meteorhacks:ssr@2.2.0
minifier-css@1.3.0
minifier-js@2.3.1
minimongo@1.4.3
mizzao:timesync@0.5.0
mizzao:user-status@0.6.7
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modules@0.11.3
modules-runtime@0.9.2
momentjs:moment@2.17.1
mongo@1.4.3
mongo-dev-server@1.1.0
mongo-id@1.0.6
mongo-livedata@1.0.12
nimble:restivus@0.8.12
npm-bcrypt@0.9.3
npm-mongo@2.2.34
observe-sequence@1.0.16
okgrow:analytics@2.1.3
ordered-dict@1.1.0
percolate:migrations@1.0.2
percolate:synced-cron@1.3.2
promise@0.10.1
raix:eventemitter@0.1.3
random@1.1.0
rate-limit@1.0.8
reactive-dict@1.2.0
reactive-var@1.0.11
reload@1.2.0
retry@1.1.0
reywood:bootstrap3-sass@3.3.6
reywood:publish-composite@1.5.2
routepolicy@1.0.12
server-render@0.3.0
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.3.1
shim-common@0.1.0
silentcicero:jszip@0.0.4
simple:json-routes@2.1.0
socket-stream-client@0.1.0
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-css@1.4.0
standard-minifier-js@2.3.1
stylus@2.513.14
templating@1.3.2
templating-compiler@1.3.3
templating-runtime@1.3.2
templating-tools@1.1.2
tracker@1.1.3
tsega:bootstrap3-datetimepicker@4.17.37_1
u2622:persistent-session@0.4.4
ui@1.0.13
underscore@1.0.10
url@1.2.0
webapp@1.5.0
webapp-hashing@1.0.9
zimme:active-route@2.3.2

**Comment by arminschleicher** [comment] 2018-02-05 11:29
I have the same issue, also upgraded from 1.6.0.1 to 1.6.1, mongo version is 1.4.3

**Comment by glasser** [comment] 2018-02-05 20:54
Could #9444 be at fault? cc @hwillson

**Comment by glasser** [comment] 2018-02-05 22:08
If that's the issue, then I suspect you have a query that you are observing that, while it looks in the error message like `{}`, is actually `{something: undefined}`.  (JSON encoding drops undefined values in objects.)

**Comment by scanton** [comment] 2018-02-12 16:29
I've been having this same problem.  So far, it has only crept up when running our app on Windows machines.

Running Meteor 1.6.1
mongo 1.4.2

**Comment by scanton** [comment] 2018-02-12 16:56
I upgraded using "meteor update mongo" which updated mongo from 1.4.2 to 1.4.3, but we still get the same problem

**Comment by scanton** [comment] 2018-02-12 19:13
Checked against my other (working) installation, and saw it was running Meteor 1.6.0.1.  Created a new installation using "meteor create testProject --release 1.6.0.1".  This removed the "Mongo server and the Meteor query disagree" issue for me.

But now I'm afraid to update anything.

**Comment by glasser** [comment] 2018-02-12 19:27
As I mentioned above, this is probably a new bug related to queries with `undefined` in them.

What you say you created a new installation, does that mean you have a relatively small reproduction of the issue?

**Comment by glasser** [comment] 2018-02-12 21:32
If you check in the `.meteor` directory from your app, you shouldn't need
all of those add and remove instructions — you should be able to get it to
just "check out, run".

**Comment by mrlowe** [comment] 2018-02-12 21:52
Weird ... I just encountered what looks like the same issue on my development box (MacOS, project using meteor 1.6.1) after I changed a file and the server restarted:

>=> Meteor server restarted
>=> Meteor server restarted
>=> Meteor server restarted
>I20180212-15:24:29.440(-6)? Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query.  Maybe it is hitting a Mongo edge case? The query is: {}
> at packages/mongo/oplog_observe_driver.js:881:15 ...

**Comment by rjsmith** [comment] 2018-02-12 22:24
I have also started observing a similar error trace after upgrading my application from 1.6.0 to 1.6.1. I am seeing it on both my local macbook OSX dev machine and on the same app deployed in Galaxy. It seems to appear when I log out out of the app (using accounts-password).

```
Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"_id":"LuBPEsWLxNCbJaFka","deleted":{"$exists":false}}
I20180212-22:15:21.158(0)?     at packages/mongo/oplog_observe_driver.js:881:15
I20180212-22:15:21.159(0)?     at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
I20180212-22:15:21.159(0)?     at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
I20180212-22:15:21.160(0)?     at OplogObserveDriver.proto._publishNewResults (packages/mdg_meteor-apm-agent.js:2899:38)
I20180212-22:15:21.160(0)?     at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
I20180212-22:15:21.160(0)?     at OplogObserveDriver._runInitialQuery (packages/mongo/oplog_observe_driver.js:658:10)
I20180212-22:15:21.160(0)?     at packages/mongo/oplog_observe_driver.js:191:10
I20180212-22:15:21.160(0)?     at packages/mongo/oplog_observe_driver.js:15:9
I20180212-22:15:21.161(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180212-22:15:21.161(0)?     at packages/meteor.js:502:25
I20180212-22:15:21.161(0)?     at runWithEnvironment (packages/meteor.js:1240:24)
```

**Comment by rjsmith** [comment] 2018-02-13 10:07
I can confirm that my issue appears to be due to an undefined query field in my code (the 'partitionId' attribute in the query below):

```
   return Plangy.ProjectsCollection.find(
      {
        _id: projectId,
        partitionId: partitionId,
        deleted:{$exists:false} // tx.softDelete=true
      }, 
      {sort: {versionNumber: -1}, limit: 1});    
```
I simply put a `if (partitionId) {...}` check before running the query, and I have not observed the exception since then.

**Comment by hwillson** [comment] 2018-02-13 12:26
Reproduction: https://github.com/hwillson/meteor-issue-9619

Thanks for the additional debugging details everyone, and for the accurate analysis of the problem @glasser (https://github.com/meteor/meteor/issues/9619#issuecomment-363217960). Marking as confirmed, and I'll work on a fix.

**Comment by tab00** [comment] 2018-02-19 11:42
It may not be good to actually strip out fields that are `undefined` as then the query result may return data that the user should not be receiving.

**Closed** 2018-02-28 19:32 UTC
Labels: Impact:some, Project:Mongo Driver, Severity:production, bug, confirmed

**Comment by JairAviles** [comment] 2018-04-04 03:15
Have the same issue with mongo@1.4.5, after updated today to meteor 1.6.1.1

**Comment by georgeiou** [comment] 2018-04-17 19:00
Had the same issue on Meteor 1.6.1 and 1.6.1.1. I downgraded back to Meteor 1.6.0 for the time being. Wasn't able to find the problematic query as the log didn't return anything I could easily look into. 

`Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"photoId":"123"}` 
would be nice to know what file & line the breaking query is on. I could probably find out what query it is but when you have dozens of queries running on that view with the same field its an expensive time investment to find and test.

**Comment by charlesdeb** [comment] 2018-04-25 16:37
Another "me too". Just did the upgrade to Meteor 1.6.1 and updated Mongo to 1.4.7 but the issue persists. I (think I) know exactly what lines are causing me grief so have  implemented the workaround from @lynchem, although my code is in reywood:publish-composite (which I also updated to the latest version of  1.6.0). My actual `find` is this:
```
return Meteor.users.find(
  {
    // if there is a token for this relationship, there should not actually be a  relatedUserId
    $or: [
      { _id: relationship.userId },
      { _id: relationship.relatedUserId }
    ]
  }
```   
and it is erroring out with this:
```
Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query.
Maybe it is hitting a Mongo edge case? The query is: {"$or":[{"_id":"bB6Qzbi2gkYYbRFLz"},{}]}
```
The annoying thing is that my code already has an `$or` in it to cover the (sometimes expected) case that `relationship.relatedUserId` is undefined. That's why I am doing an `$or` in the first place!

This appears to solve it for me:
```
const orQuery = [{ _id: relationship.userId }];
if (relationship.relatedUserId) {
  orQuery.push({ _id: relationship.relatedUserId });
}
return Meteor.users.find(
  {
    $or: orQuery
  }
);

```

**Comment by lynchem** [comment] 2018-04-26 10:30
Yeah @charlesdeb , we have several cases like that where we have to build the query step by step and ensure nothing undefined makes it in.

**Comment by heberallred** [comment] 2018-05-07 16:51
I'm getting a similar issue except when comparing to an empty string:

return Records.find({databaseId, parentId: ''});

The records are in hierarchical arrangement, so I'm using an empty string as root level.
I only get the issue if I return a "find" cursor, but if I do a .fetch() on the results, it doesn't have the issue.

**Comment by king-arch** [comment] 2019-02-15 06:33
while using a publish composite , i am getting same error/ using 1.6.1 version of meteor. Does anyone have a work arround ?

**Comment by charlesdeb** [comment] 2019-02-18 07:00
@king-arch Most likely `story_feed_id` is undefined when you are running this query. As per the workaround examples above, before doing the `find`, make sure that `story_feed_id` is not undefined. Good luck.

**Comment by king-arch** [comment] 2019-02-18 09:31
> @king-arch Most likely `story_feed_id` is undefined when you are running this query. As per the workaround examples above, before doing the `find`, make sure that `story_feed_id` is not undefined. Good luck.

Thanks Charles, for replying. I was able to solve this issue on my own (after one day :) ). As I was using publish composite package and $in was causing an issue with its basic functioning. So just took care of that and now its running good.
