### ISSUE TITLE
[1.3.rc-4]Meteor reload endless loop

### ISSUE THREAD

**Issue by newsiberian** [meteor/meteor#6556] opened 2016-03-22 07:29 UTC
Hello, since `1.3.rc-3` I started to see endless Meteor reload while changing code. Also, this happens with the latest version. Bug occurs now 100% of times but in a half of cases. Not sure, but usually this happens when I work with client-side code (maybe not). Visually it looks like:
![meteor_loop](https://cloud.githubusercontent.com/assets/11130487/13944275/a6b41cd4-f036-11e5-9d96-312b5226e21d.gif)
And you see this line all the time.

repro repo: [here](https://github.com/newsiberian/meteor-reload-loop-repro)
To repeat, try to change something in `components` within `packages/reaction-react` package several times.

**Comment by benjamn** [comment] 2016-03-22 15:21
If you stop the server and restart it, does it start up successfully?

**Comment by newsiberian** [comment] 2016-03-22 17:45
@benjamn, hello, yes, I do it all the time. Stop meteor, then start again. It could happen several times in 5 minutes. Maybe you could repeat it if save changes often, i.e. you could try to do several change one-by-one and save file after every change.

**Comment by benjamn** [comment] 2016-03-22 18:29
The way I was able to reproduce this was by running `meteor test-packages`, waiting for the server to start, changing a file, then changing the same file again before the rebuild completed. Something about checking the `mtime` in `watch.isUpToDate` just wasn't reliable enough to handle multiple changes like that, so I reverted my changes to that code, so now we're back to a version that's a little slower but has been around through multiple Meteor releases. I can't reproduce the problem anymore.

**Comment by benjamn** [comment] 2016-03-22 23:02
Fixed in [`1.3-rc.8`](https://github.com/meteor/meteor/issues/6266#issuecomment-200069991).

**Closed by benjamn** 2016-03-22 23:02 UTC
Labels: confirmed, in progress

**Comment by bogdanrn** [comment] 2017-08-31 16:33
i'm having this same issue again in 1.5.1
