### ISSUE TITLE
Meteor accounts facebook - Cannot redirect when using iOS in-app browser

### ISSUE THREAD

**Issue by sonlexqt** [meteor/meteor#8111] opened 2016-11-29 06:52 UTC
I'm implementing facebook's messenger platform [account linking flow](https://developers.facebook.com/docs/messenger-platform/account-linking), in short: 
- A user start a conversation with a messenger bot
- The messenger bot requires the user to click the "Login" button, which opens the log in page in messenger's in-app browser
- The user login via facebook
- If this is the first time, the user is required to authorize the app
- After finishing authorization, he will be redirected back to messenger app:
  + **Expected behavior**: After authorization, the browser window closes, user is redirected back to messenger app (It works just as expected in all desktop browsers and android devices)
  + **Reality**: On iOS (version >= 8) devices, after authorization, the iOS in-app browser stuck in a page with a URL like this:
`mydomain.com/_oauth/facebook?close&code=AQBQ46x7qVJyUD4oIdkLMs6kxDCnJ750LB9w4zOzcrTIQmffXr8UyjYAgq4hunwq-8S-EbUJeAnJn3cd9kykyrP5kJCoeL26stKFn60QA9nxsrf9nPPL3A92CjLCrJduf5_o7kjYLHDJoqL80CzIcP_GbviDdDSDxFsLH6acNl5cgK1UKbHJ6WeD8AuBbUnm3zl7ZRQXN1scopU3m6CtW2-I43j0NHP8PswCVFJhbU30YWz_nGcr8iJZIRFmfelPimUKCcvnQ8zb7dUOi7sDkWpBHsGW7NOTd3ctTXSv5UErUJ3y5Mrv6NzVitsrX_coBogV6EucAo6cwfqXiU9vuhzG&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJEb2xNYmRZWUNFdTd1M3VTTFFDZXllWjAwZnFvVk41LTR5ajNCem9tdk5aIiwiaXNDb3Jkb3ZhIjpmYWxzZX0%3D#_=_`
It shows: _"Login completed. Click here to close this window."_ 
When the users click the "click here" link, nothing happens, therefore the authorization failed.

I'm using `Meteor@1.4.2.3`, `accounts-facebook@1.0.11`.

**Comment by abernix** [comment] 2016-11-29 15:14
I realize it may seem simple, but building reproductions takes a significant amount of developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.

Someone can provide their own Facebook App credentials, but please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here.

[Guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor)

**Comment by abernix** [comment] 2017-01-04 12:17
Closing due to lack of reproduction repository.  Happy to reopen this issue if you can provide one!

**Closed by abernix** 2017-01-04 12:17 UTC
Labels: can't-reproduce

**Comment by ddaydd** [comment] 2018-05-07 09:37
I have the same probem, did you find a solution?

Thanks

**Comment by carlosalvidrez** [comment] 2020-03-11 23:01
Same challenge here. Any solutions?
