### ISSUE TITLE
[1.3] Stylus file can't be imported

### ISSUE THREAD

**Issue by Deadly0** [meteor/meteor#7051] opened 2016-05-13 20:11 UTC
I use Coffescript and Stylus.
When i try to import CSS file it works well
```require './module.css'```

but when i try to import Stylus file, get error ``Uncaught Error: Cannot find module './module.styl'``
```require './module.styl'```

Impossible create components structure like this https://forums.meteor.com/t/what-is-the-recommended-folder-structure-for-meteor-1-3/15828/19

**Comment by stubailo** [comment] 2016-05-17 01:45
@Deadly0 can you please post a reproduction of an app where this happens? Do you have the stylus package, etc?

**Comment by abernix** [comment] 2016-05-17 07:57
@stubailo I thought this was the intended behaviour based on [this code](https://github.com/meteor/meteor/blob/7c47e5ecd0caac547d86657e06cc21ee3602e542/packages/modules/css.js) and [this section of the guide](http://guide.meteor.com/build-tool.html#css-importing) (which seemed to *gently* suggeset that importing `.css` would only work in JS).

**Comment by abernix** [comment] 2016-05-31 17:41
@Deadly0 Any updates?  Can you please provide a basic reproduction repo on github?

**Comment by Deadly0** [comment] 2016-06-06 19:29
@abernix @stubailo 

```
meteor create import_issue
meteor add stylus
```

imports/m.styl
```
body
  color burlywood
  ```

client/main.js
```
import '../imports/m.styl'; // Unable to resolve some modules:
```

```
meteor
```

**Comment by abernix** [comment] 2016-06-28 16:01
Thanks for posting that @Deadly0.  I don't think I would call this a bug as I think it's the expected behaviour as of right now.  It's essentially the same issue with SCSS in #6852.

**Comment by ababba15** [comment] 2016-07-23 15:36
Any way to fix it now?

**Comment by abernix** [comment] 2016-07-25 10:56
This reproduction works perfectly starting with Meteor 1.3.3.  The other issue I referenced is now only an issue regarding importing on the **server**-side, which should be (and can be) avoided.

@ababba15 It "just works" if you use a recent version of Meteor.  I just tested the above reproduction in Meteor 1.3.3 and 1.3.5.1.  I'd recommend 1.3.5.1!

Closing this as it's resolved.

**Closed by abernix** 2016-07-25 10:56 UTC
Labels: bug, confirmed, Impact:some, Project:Isobuild

**Comment by ababba15** [comment] 2016-07-25 12:44
@abernix nope, it doesn't..

![image](https://cloud.githubusercontent.com/assets/13153161/17101702/a0aee260-527e-11e6-9a19-87e308c63321.png)

**Comment by abernix** [comment] 2016-07-25 12:50
@ababba15 It will not work without the stylus compiler.  The exact [steps written above](https://github.com/meteor/meteor/issues/7051#issuecomment-224062542) work perfectly.  You probably need to add the stylus package to support compilation of `.styl` files:

```
meteor add stylus
```

**Comment by ababba15** [comment] 2016-07-25 12:52
@abernix I just understood that I used the wrong package named `mquandalle:stylus`.

Installing clean stylus package has resolved the problem, thanks 👍
