### ISSUE TITLE
Mongo Collection.find() options bug

### ISSUE THREAD

**Issue by john-osullivan** [meteor/meteor#5860] opened 2015-12-21 21:46 UTC
Hello -- I'm running into an issue using find() options after recently updating all of my Meteor packages.  When I perform a find in a Meteor publication (e.g. `Meteor.users.find({username : args.username}, {limit : 1})`), using any additional options triggers an error:

`Exception from sub 'userProfile' id [...] Error: Match error: Failed Match.OneOf or Match.Optional validation`

The stack trace leads to the `_getFindOptions` method in `mongo/collections.js`:
```
  _getFindOptions: function (args) {
    var self = this;
    if (args.length < 2) {
      return { transform: self._transform };
    } else {
      check(args[1], Match.Optional(Match.ObjectIncluding({
        fields: Match.Optional(Match.OneOf(Object, undefined)),
        sort: Match.Optional(Match.OneOf(Object, Array, undefined)),
        limit: Match.Optional(Match.OneOf(Number, undefined)),
        skip: Match.Optional(Match.OneOf(Number, undefined))
     })));

      return _.extend({
        transform: self._transform
      }, args[1]);
    }
  },
```

I couldn't try debugging further by adding some log statements in this code because Meteor's build process overwrites any changes I add, but it would seem that `args[1]` doesn't have the expected options.  My interim workaround has been to remove all options from my finds, but that's clearly less than ideal.  Any ideas on how I'd fix this?  The syntax of my query seems fine and it used to work without a hitch.

**Comment by glasser** [comment] 2015-12-21 22:02
Can you show the exact `find` line that triggered this?

**Comment by john-osullivan** [comment] 2015-12-21 22:06
It's the one I included in the e.g.: `Meteor.users.find({username : args.username}, {limit : 1})`.  I've also got a different query `Meteor.users.find({ _id : { $in: userIds }}, {fields: {username : 1}})` which is working fine, though, so it might not be an issue for all options.

**Comment by glasser** [comment] 2015-12-21 22:08
I think this is a duplicate of #5712.

**Closed by glasser** 2015-12-21 22:08 UTC

**Comment by john-osullivan** [comment] 2015-12-21 22:14
The app is able to compile just fine, the bug only arises when I navigate to the page where the publication is subscribed to and the query is run.  It sounds like the underlying issue might be similar, although I'm not sure it's quite the same.

**Comment by john-osullivan** [comment] 2015-12-21 22:16
The stack trace is, by the way, was:

![image](https://cloud.githubusercontent.com/assets/3820981/11942745/a312319c-a806-11e5-80bd-7854e148c74b.png)

**Comment by glasser** [comment] 2015-12-21 22:19
It does look like the same error to me. Probably related to a different Number being used by the mongo package vs the check package due to polyfills.

**Comment by YsnKsy** [comment] 2016-01-13 04:37
I've got the same problem
![meteorbug](https://cloud.githubusercontent.com/assets/5409223/12285179/5bcb08bc-b9af-11e5-80a5-30607423ba97.jpg)

**Comment by KhalilHTM** [comment] 2016-04-27 05:28
What's the solution to this?
