### ISSUE TITLE
`meteor update` reports updates that don't occur

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4349] opened 2015-05-09 00:52 UTC
If I have `meteor run` in one Terminal, `meteor update` doesn't work in a second Terminal:

```
$ meteor list | grep cucumber
xolvio:cucumber                               0.6.6* CucumberJS for Velocity
$ meteor update
This project is already at Meteor 1.1.0.2, the latest release.
                                              
Changes to your project's package version selections from updating package versions:
                                              
meteorhacks:kadira                upgraded from 2.20.2 to 2.20.3
sanjo:long-running-child-process  upgraded from 1.0.3 to 1.1.1
xolvio:cucumber                   upgraded from 0.6.6 to 0.7.4

$ meteor list | grep cucumber
xolvio:cucumber                               0.6.6* CucumberJS for Velocity
$ meteor update
This project is already at Meteor 1.1.0.2, the latest release.
                                              
Changes to your project's package version selections from updating package versions:
                                              
meteorhacks:kadira                upgraded from 2.20.2 to 2.20.3
sanjo:long-running-child-process  upgraded from 1.0.3 to 1.1.1
xolvio:cucumber                   upgraded from 0.6.6 to 0.7.4

$ meteor list | grep cucumber
xolvio:cucumber                               0.6.6* CucumberJS for Velocity
```

I do not have any numbers in my `.meteor/packages` file.

**Comment by laosb** [comment] 2015-05-09 16:20
Same issue here.
```
Expo-LyudeMacBook-Pro:piet_new laosb$ meteor list | grep babrahams:editable-text
babrahams:editable-text      0.7.21* Editable text drop-in template helper

Expo-LyudeMacBook-Pro:piet_new laosb$ meteor update
This project is already at Meteor 1.1.0.2, the latest release.
                                                                                   
Changes to your project's package version selections from updating package versions:
                                              
aida:pagination              upgraded from 1.0.8 to 1.0.9
aldeed:simple-schema         upgraded from 1.3.2 to 1.3.3
babrahams:editable-text      upgraded from 0.7.21 to 0.7.24
cfs:http-methods             upgraded from 0.0.28 to 0.0.29
gwendall:simple-schema-i18n  upgraded from 0.1.4 to 0.1.7
meteorhacks:kadira           upgraded from 2.20.1 to 2.20.3

Expo-LyudeMacBook-Pro:piet_new laosb$ meteor list | grep babrahams:editable-text
babrahams:editable-text      0.7.21* Editable text drop-in template helper
```

**Comment by clayne11** [comment] 2015-05-12 16:37
You cannot have meteor running while running meteor update. I just discovered this myself today.

After shutting down my meteor server and then running meteor update I was able to update all of my packages.

**Comment by glasser** [comment] 2015-05-12 21:51
I believe this is a duplicate of #3582 which is fixed on devel but not yet released.

**Closed by glasser** 2015-05-12 21:51 UTC
Labels: Project:Version Solver
