### ISSUE TITLE
Subscription onReady callbacks don't fire on a re-subscription with the same arguments inside Deps.autorun

### ISSUE THREAD

**Issue by athiwatc** [meteor/meteor#1173] opened 2013-06-21 22:20 UTC
**_2 Upvotes**_ I don't know if this is the intended behavior but lets assume that the server publish is setup.

Then we do

``` coffeescript
Deps.autorun ->
  Session.set('ready', false)
  Meteor.subscribe 'call-this', Session.get('something'), ->
    Session.set('ready', true)

Session.set('something', 2)
#wait for the subscibe to complete and the page shows
Session.set('something', 2)
#Now the loading page gets stuck. Note that the loading page uses {{#if}} against the 'ready' session.
```

I don't really have time to get an example working right now but I will try to if I get time.

My current hack/fix right now is adding a non-sense field to trick meteor on tearing and setting up the subscription and calling the on finish again.

``` coffeescript
Deps.autorun ->
  Session.set('ready', false)
  Meteor.subscribe 'call-this', Session.get('something'), Math.random(), ->
    Session.set('ready', true)

Session.set('something', 2)
#wait for the subscibe to complete and the page shows
Session.set('something', 2)
#Now the loading page gets stuck. Note that the loading page uses {{#if}} against the 'ready' session.
```

**Comment by mizzao** [comment] 2015-03-11 17:20
Is a fix for this going to make it into 1.0.4 along with the other subscription-related updates?

**Comment by glasser** [comment] 2015-03-11 21:16
No, 1.0.4 is currently in release candidate stage and there hasn't been work on this issue.

**Comment by thehecht** [comment] 2015-04-03 18:01
Is this still considered a bug or is intended behaviour? My team adopted the current behaviour as it is using the reactive subhandle.ready() whenever we want to ensure that the data is ready but using the onReady callback when we need to know that fresh data just came from the server. If it's a bug we should not use the second case.

**Comment by RobertLowe** [comment] 2015-06-22 23:43
+1 this issue is severely annoying

**Comment by RobertLowe** [comment] 2015-10-23 00:30
@stubailo yeah, get on it! :+1:

**Comment by kokokenada** [comment] 2016-03-16 15:34
+1

**Comment by ankushsaxena5** [comment] 2016-07-15 14:46
+1

**Comment by DriesVandermeulen** [comment] 2016-07-28 21:13
+1 still need this

**Comment by reason211** [comment] 2016-08-27 02:27
+10086

**Comment by jetlej** [comment] 2016-09-14 19:37
+1

**Comment by Taxel** [comment] 2016-11-08 16:49
+1

**Comment by erperejildo** [comment] 2017-03-28 21:50
This issue almost has 4 years. Any solutions?

**Comment by felipenmoura** [comment] 2017-04-06 18:51
+Number.MAX_SAFE_INTEGER

**Comment by danielparas** [comment] 2017-04-30 07:28
+1

**Closed** 2017-07-12 22:45 UTC
Labels: Project:DDP, Project:Tracker, pull-requests-encouraged

**Comment by RobertLowe** [comment] 2017-07-13 00:49
4 years wow, time flies and Meteor still improves!

@benjamn while this doesn't need backwards compatibility per-say I think it's going to cause some strange behaviours for apps not expecting this (and having the callback suddenly re-fire after an app update), any thoughts here?

👍

**Comment by hwillson** [comment] 2017-07-13 01:03
@RobertLowe This was discussed in the original PR (https://github.com/meteor/meteor/pull/8754). It was decided that the fact that this could be a potentially breaking change would be documented in the [`History.md`](https://github.com/meteor/meteor/blob/devel/History.md#v151-2017-07-12) (5th bullet). Correcting this buggy behavior was deemed worth the potential BC headache.

**Comment by RobertLowe** [comment] 2017-07-13 01:18
@hwillson Thanks, glad to see it was considered
